# AI-Powered Network Intrusion Detection System

## Notebook 04 – Final Preprocessing & Model Preparation

**Project:** AI-Powered Network Intrusion Detection System  
**Dataset:** CICIDS-2017  
**Task:** Multi-Class Network Intrusion Detection  
**Primary Classification:** Eight Attack Families + BENIGN  
**Input:** Stage-1 Feature-Engineered CICIDS-2017 Dataset  
**Role:** Member A – ML & Data Engineering

## Notebook Purpose

This notebook establishes the final, leakage-controlled preprocessing and model
preparation pipeline for the AI-Powered Network Intrusion Detection System.

The notebook continues from Notebook 03, where the CICIDS-2017 dataset was
cleaned and subjected to initial feature engineering and feature analysis. The
persisted Stage-1 feature-engineered dataset is treated as the input to this
stage.

The purpose of this notebook is not to optimize a particular machine-learning
model. Instead, it establishes a reproducible and scientifically controlled data
foundation that can be used consistently by the subsequent Random Forest, LSTM,
ensemble, explainability, and evaluation stages.

The original CICIDS-2017 labels are consolidated into eight attack families,
with BENIGN traffic retained as a separate normal-traffic class. The resulting
primary classification problem therefore contains nine final classes:

- BENIGN
- DDoS
- Port Scan
- Brute Force
- Bot
- Web Attack
- Infiltration
- DoS
- Heartbleed

The consolidation is performed at the attack-family level rather than by
artificially relabeling distinct attack variants. In particular:

- FTP-Patator and SSH-Patator are grouped as Brute Force.
- Web Attack – Brute Force, Web Attack – XSS, and Web Attack – SQL Injection
  are grouped as Web Attack.
- DoS Hulk, DoS GoldenEye, DoS Slowloris, and DoS Slowhttptest are grouped as
  DoS.

Heartbleed is retained despite its very low number of observations. Its limited
support is treated as an explicit dataset limitation rather than being hidden,
discarded, or artificially represented as a well-supported class.

The notebook will establish the final data partitions, investigate duplicate
and leakage risks, perform training-only feature selection, fit the common
scaling transformation, document class imbalance, and persist the artifacts
required by downstream model experiments.

Class-imbalance handling is deliberately not assumed to be solved by a single
method. The common model-preparation dataset will remain representative of the
established partitions, while alternative training-time strategies such as
class weighting, controlled oversampling, and controlled SMOTE-based approaches
will be investigated separately in the downstream Random Forest and LSTM
experiments.

The independent test partition will remain isolated from feature-selection
decisions, preprocessing fitting, imbalance-method selection, hyperparameter
selection, and ensemble development.

## Objectives

The objectives of this notebook are:

1. Recover and validate the Stage-1 feature-engineered dataset produced by
   Notebook 03.

2. Establish the final nine-class target taxonomy consisting of eight attack
   families and BENIGN traffic.

3. Preserve the relationship between the original CICIDS-2017 labels and their
   consolidated attack-family labels.

4. Validate that every original target label is mapped exactly once to a final
   classification category.

5. Investigate duplicate observations, duplicate feature vectors, and
   cross-label duplicate patterns that may affect the independence of the
   evaluation partitions.

6. Establish leakage-controlled development, validation, and independent test
   partitions.

7. Ensure that identical observations are not unintentionally distributed
   across different evaluation partitions.

8. Perform standard-deviation-based feature filtering using training data only.

9. Perform correlation-based feature pruning using training data only.

10. Establish a final feature representation that is consistently applied to
    training, validation, test, and future inference data.

11. Fit the StandardScaler using training data only and transform the remaining
    partitions using the fitted scaler.

12. Analyze the resulting class distribution and quantify the remaining class
    imbalance across the training, validation, and test partitions.

13. Avoid applying synthetic sampling or oversampling to the independent test
    partition.

14. Prepare a common model-ready representation that can be used by both the
    Random Forest and LSTM pipelines.

15. Preserve model-specific imbalance handling as a downstream experimental
    decision rather than embedding a single assumed sampling strategy into the
    common dataset.

16. Persist the final feature matrices, target arrays, feature-selection
    information, label mapping, scaler, split information, class distributions,
    and preprocessing metadata.

17. Reload and independently validate the persisted artifacts to confirm that
    the model-preparation package is internally consistent.

18. Establish a reproducible data contract for all subsequent Random Forest,
    LSTM, ensemble, explainability, and final evaluation notebooks.

19. Produce sufficient preprocessing records to support transparent
    documentation of the methodology in the final research paper.

## Overall Experimental Methodology

The final preprocessing workflow follows the sequence:

**Recover → Validate → Define Taxonomy → Audit Duplicates → Partition →
Select Features → Prune Correlations → Scale → Analyze Imbalance →
Persist → Reload & Validate → Handoff**

The pipeline is designed so that decisions that may expose information from the
evaluation data are restricted to the appropriate development/training
partition.

The final independent test partition is treated as an evaluation-only resource.
It is not used to determine feature-selection thresholds, correlation-pruning
decisions, scaling parameters, imbalance strategies, model hyperparameters, or
ensemble configurations.

The resulting model-preparation artifacts form the common data foundation for
the subsequent Random Forest and LSTM experiments.

The downstream model notebooks may apply different training-time imbalance
strategies because Random Forest and LSTM models have different learning
mechanisms and data representations. Their results will nevertheless be
evaluated using the same independently established test partition.

## Research Principles

### Principle 1 – Stage-1 Continuity

Notebook 04 uses the persisted Stage-1 feature-engineered dataset produced by
Notebook 03 as its input.

The Stage-1 artifact is treated as the established upstream representation and
is not modified in place.

### Principle 2 – Explicit Attack-Family Taxonomy

The primary classification problem contains eight attack families plus BENIGN
traffic.

The taxonomy is defined explicitly rather than relying on implicit numerical
label assumptions.

Distinct CICIDS-2017 attack variants are consolidated only where they belong
to the same intended attack family.

### Principle 3 – Original Label Traceability

The original CICIDS-2017 labels remain traceable throughout preprocessing.

The final class mapping is persisted so that every model prediction can be
interpreted in terms of the final attack-family taxonomy while the original
dataset semantics remain recoverable for analysis.

### Principle 4 – No Blind Preprocessing

No preprocessing operation is introduced solely because it is commonly used in
imbalanced intrusion-detection pipelines.

Each operation must have a defined purpose, measurable effect, and reproducible
implementation.

### Principle 5 – Training-Only Fitting

Any preprocessing operation that estimates parameters or makes
data-dependent selection decisions is fitted using training data only.

This includes feature-selection thresholds, correlation-pruning decisions, and
feature-scaling parameters.

### Principle 6 – Independent Test Isolation

The final test partition is reserved for final evaluation.

It must not influence preprocessing decisions, imbalance-method selection,
hyperparameter tuning, model selection, ensemble selection, or confidence
calibration decisions.

### Principle 7 – Duplicate Leakage Control

Duplicate observations and duplicate feature vectors are explicitly
investigated before the final partitions are established.

The partitioning procedure must prevent identical observations from creating
artificial overlap between training and independent evaluation data.

### Principle 8 – Realistic Class Imbalance

The natural class distribution is preserved in the common model-preparation
partitions.

The notebook does not attempt to make the entire dataset artificially
balanced.

### Principle 9 – Imbalance Handling as an Experiment

No single imbalance technique is assumed to be optimal.

Class weighting, controlled oversampling, and controlled SMOTE-based approaches
may be investigated downstream using the same fixed data partitions.

### Principle 10 – Rare-Class Transparency

Extremely low-support classes, particularly Heartbleed and Infiltration, are
retained when required by the defined taxonomy.

Their limited statistical support is explicitly documented and considered when
interpreting class-wise metrics.

### Principle 11 – Model-Specific Training Strategies

The Random Forest and LSTM models may use different training-time imbalance
strategies.

The common model-preparation artifacts provide the shared evaluation basis,
while model-specific training procedures are investigated in their respective
notebooks.

### Principle 12 – No Test-Set Optimization

A strong test-set result does not justify modifying the preprocessing pipeline
after observing the test results.

If an experimental modification is required, it must be evaluated through the
development/validation procedure before the final test partition is accessed.

### Principle 13 – Reproducibility

All important preprocessing decisions are recorded through:

- fixed random seeds,
- explicit label mappings,
- split metadata,
- feature-selection metadata,
- scaler persistence,
- class-distribution records,
- artifact validation,
- and preprocessing configuration metadata.

### Principle 14 – Evidence Before Selection

A preprocessing or imbalance strategy is not considered successful merely
because it improves overall accuracy.

Macro-level metrics, class-wise precision, recall and F1, false-positive
behavior, balanced performance, and calibration-related results will be
considered in the downstream experiments.

### Principle 15 – Common Evaluation Foundation

All subsequent model experiments must consume the same finalized evaluation
partition produced by this notebook.

This ensures that Random Forest, LSTM, and the eventual ensemble are evaluated
against the same underlying test observations.

## Planned Notebook Stages

### Stage 1 – Environment and Project Recovery

Recover the established project environment, Stage-1 dataset, metadata, project
paths, and output locations.

### Stage 2 – Stage-1 Dataset Validation

Load and validate the persisted feature-engineered dataset from Notebook 03.

The dataset structure, feature representation, target column, numerical
integrity, and metadata will be verified before further processing.

### Stage 3 – Final Target Taxonomy

Inspect the original CICIDS-2017 target labels and establish the final
eight-attack-family-plus-BENIGN classification taxonomy.

The original labels will be mapped explicitly to the final classes and the
mapping will be validated and persisted.

### Stage 4 – Duplicate and Leakage Audit

Investigate exact duplicate rows, duplicate feature vectors, and
cross-label duplicate patterns.

The findings will be used to establish an appropriate partitioning strategy
without unnecessarily discarding valid observations.

### Stage 5 – Development, Validation, and Test Partitioning

Construct the final data partitions using a reproducible and
leakage-controlled procedure.

The independent test partition will be isolated before any
training-dependent feature-selection or scaling decisions are made.

### Stage 6 – Training-Only Feature Selection

Perform standard-deviation-based filtering using training data only.

The selected feature set will then be fixed for all remaining partitions.

### Stage 7 – Training-Only Correlation Pruning

Analyze feature correlations using training data only and remove redundant
features according to a predefined and documented criterion.

The resulting feature set will be applied consistently to validation, test, and
future inference data.

### Stage 8 – Feature Scaling

Fit the StandardScaler using training data only and transform the training,
validation, and independent test partitions using the same fitted scaler.

### Stage 9 – Class-Imbalance Analysis

Quantify the final class distribution and imbalance ratio across all partitions.

The notebook will document the imbalance problem without artificially
balancing the common evaluation dataset.

### Stage 10 – Downstream Imbalance Experiment Design

Define the controlled imbalance strategies that will be investigated separately
for Random Forest and LSTM training.

Potential strategies include:

- class-weighted learning,
- controlled random oversampling,
- controlled SMOTE,
- and additional sampling methods only when justified by experimental
  evidence.

No strategy will be declared optimal at this stage.

### Stage 11 – Final Artifact Persistence

Persist the finalized model-ready arrays, labels, feature metadata, label
mapping, scaler, split information, class distributions, and preprocessing
metadata under the new model-preparation output directory.

### Stage 12 – Artifact Reload and Validation

Reload the persisted artifacts and verify:

- shapes,
- feature ordering,
- class labels,
- partition integrity,
- scaler behavior,
- metadata consistency,
- and reproducibility.

### Stage 13 – Model Handoff

Establish the finalized artifact contract for the subsequent Random Forest and
LSTM notebooks.

The same independent test partition will be used for subsequent model
comparison and final ensemble evaluation.

## Final Data-Preparation Flow

The finalized preprocessing architecture is:

```text
Notebook 03 – Stage-1 Feature Engineering
                    │
                    ▼
          Original CICIDS-2017 Labels
                    │
                    ▼
       Final Taxonomy: 8 Attack Families
                  + BENIGN
                    │
                    ▼
          Duplicate & Leakage Audit
                    │
                    ▼
       Leakage-Controlled Partitioning
                    │
                    ▼
 Training-Only Standard-Deviation Filtering
                    │
                    ▼
      Training-Only Correlation Pruning
                    │
                    ▼
        Training-Fitted StandardScaler
                    │
                    ▼
       Common Model-Ready Representation
                    │
              ┌─────┴─────┐
              │           │
              ▼           ▼
     Random Forest       LSTM
        Pipeline        Pipeline
              │           │
              │           ├── Sequence construction
              │           ├── Weighted loss
              │           └── Balanced sequence sampling
              │
              ├── Class-weight experiments
              ├── Controlled oversampling
              └── Controlled SMOTE
              │           │
              └─────┬─────┘
                    │
                    ▼
        Common Independent Test Set
                    │
                    ▼
             Model Evaluation
                    │
                    ▼
          RF + LSTM Ensemble
                    │
                    ▼
       Calibration & Explainability

## 4.1 Environment & Project Recovery

This section recovers the established Google Drive project environment and
defines the input, output, and artifact paths required by Notebook 04.

Notebook 04 continues directly from the persisted Stage-1 feature-engineered
artifacts generated by Notebook 03. The Stage-1 dataset and metadata are
treated as upstream inputs and are not modified in place.

A new versioned output directory is used for the redesigned preprocessing
pipeline so that the previous model-preparation artifacts remain available for
reference and comparison.

The environment is also configured for reproducible experimentation through
fixed random seeds and centralized path definitions.

No dataset transformation or model training is performed in this section.

In [2]:
# ============================================================
# 4.1 Environment & Project Recovery
# ============================================================

from google.colab import drive
from pathlib import Path
import os
import json
import random
import numpy as np

# ------------------------------------------------------------
# 4.1.1 Mount Google Drive
# ------------------------------------------------------------

drive.mount("/content/drive", force_remount=False)

# ------------------------------------------------------------
# 4.1.2 Define Project Root
# ------------------------------------------------------------

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AI-Network-Intrusion-Detection-System"
)

# ------------------------------------------------------------
# 4.1.3 Define Project Directories
# ------------------------------------------------------------

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

NOTEBOOKS_DIR = PROJECT_ROOT / "notebooks"
OUTPUTS_DIR = PROJECT_ROOT / "outputs"
REFERENCES_DIR = PROJECT_ROOT / "references"
TRAINED_MODELS_DIR = PROJECT_ROOT / "trained_models"

# ------------------------------------------------------------
# 4.1.4 Define Notebook 03 Stage-1 Input Artifacts
# ------------------------------------------------------------

STAGE1_DATA_PATH = (
    PROCESSED_DATA_DIR /
    "CICIDS2017_stage1_feature_engineered.parquet"
)

STAGE1_METADATA_PATH = (
    PROCESSED_DATA_DIR /
    "CICIDS2017_stage1_metadata.json"
)

# ------------------------------------------------------------
# 4.1.5 Define Notebook 04 Versioned Output Directory
# ------------------------------------------------------------

MODEL_PREPARATION_V2_DIR = (
    OUTPUTS_DIR / "model_preparation_v2"
)

# Create only the new N04 output directory.
MODEL_PREPARATION_V2_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------
# 4.1.6 Define Reproducibility Configuration
# ------------------------------------------------------------

RANDOM_SEED = 42

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

# ------------------------------------------------------------
# 4.1.7 Validate Project Structure
# ------------------------------------------------------------

required_directories = {
    "Project Root": PROJECT_ROOT,
    "Data Directory": DATA_DIR,
    "Processed Data Directory": PROCESSED_DATA_DIR,
    "Notebooks Directory": NOTEBOOKS_DIR,
    "Outputs Directory": OUTPUTS_DIR,
    "References Directory": REFERENCES_DIR,
    "Trained Models Directory": TRAINED_MODELS_DIR,
}

missing_directories = [
    name
    for name, path in required_directories.items()
    if not path.is_dir()
]

if missing_directories:
    raise FileNotFoundError(
        "The following required project directories were not found:\n"
        + "\n".join(f"  - {name}" for name in missing_directories)
    )

# ------------------------------------------------------------
# 4.1.8 Validate Stage-1 Input Artifacts
# ------------------------------------------------------------

required_files = {
    "Stage-1 Dataset": STAGE1_DATA_PATH,
    "Stage-1 Metadata": STAGE1_METADATA_PATH,
}

missing_files = [
    name
    for name, path in required_files.items()
    if not path.is_file()
]

if missing_files:
    raise FileNotFoundError(
        "The following required Stage-1 artifacts were not found:\n"
        + "\n".join(f"  - {name}" for name in missing_files)
    )

# ------------------------------------------------------------
# 4.1.9 Recover Stage-1 Metadata
# ------------------------------------------------------------

with open(STAGE1_METADATA_PATH, "r", encoding="utf-8") as f:
    STAGE1_METADATA = json.load(f)

# ------------------------------------------------------------
# 4.1.10 Environment Summary
# ------------------------------------------------------------

print("=" * 72)
print("NOTEBOOK 04 — ENVIRONMENT & PROJECT RECOVERY")
print("=" * 72)

print("\n[PROJECT]")
print(f"Project Root       : {PROJECT_ROOT}")
print(f"Data Directory     : {DATA_DIR}")
print(f"Processed Data     : {PROCESSED_DATA_DIR}")
print(f"Notebooks          : {NOTEBOOKS_DIR}")
print(f"Outputs            : {OUTPUTS_DIR}")
print(f"References         : {REFERENCES_DIR}")
print(f"Trained Models     : {TRAINED_MODELS_DIR}")

print("\n[STAGE-1 INPUT]")
print(f"Dataset            : {STAGE1_DATA_PATH}")
print(f"Metadata           : {STAGE1_METADATA_PATH}")

print("\n[N04 OUTPUT]")
print(f"Model Preparation  : {MODEL_PREPARATION_V2_DIR}")

print("\n[REPRODUCIBILITY]")
print(f"Random Seed        : {RANDOM_SEED}")

print("\n[STAGE-1 METADATA]")
print(f"Dataset Name       : {STAGE1_METADATA.get('dataset', 'Not specified')}")
print(f"Stage              : {STAGE1_METADATA.get('stage', 'Not specified')}")
print(f"Record Count       : {STAGE1_METADATA.get('record_count', 'Not specified')}")
print(f"Feature Count      : {STAGE1_METADATA.get('feature_count', 'Not specified')}")
print(f"Target Column      : {STAGE1_METADATA.get('target_column', 'Not specified')}")

print("\n[VALIDATION]")
print("✓ Google Drive mounted")
print("✓ Project directories validated")
print("✓ Stage-1 dataset found")
print("✓ Stage-1 metadata found")
print("✓ N04 output directory ready")
print("✓ Reproducibility configuration initialized")

print("\n" + "=" * 72)
print("Environment recovery completed successfully.")
print("=" * 72)

Mounted at /content/drive
========================================================================
NOTEBOOK 04 — ENVIRONMENT & PROJECT RECOVERY
========================================================================

[PROJECT]
Project Root       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System
Data Directory     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/data
Processed Data     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/data/processed
Notebooks          : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/notebooks
Outputs            : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs
References         : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/references
Trained Models     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models

[STAGE-1 INPUT]
Dataset            : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/data/processed/CICIDS2017_stage1_feature_engineered.parquet
Metadata           : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/data/processed/CICIDS2017_stage1_metadata.json

[N04 OUTPUT]
Model Preparation  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2

[REPRODUCIBILITY]
Random Seed        : 42

[STAGE-1 METADATA]
Dataset Name       : {'name': 'CICIDS2017', 'number_of_records': 2830743, 'number_of_input_features': 63, 'target_column': 'Target'}
Stage              : Stage 1 - Feature Engineering
Record Count       : Not specified
Feature Count      : Not specified
Target Column      : Not specified

[VALIDATION]
✓ Google Drive mounted
✓ Project directories validated
✓ Stage-1 dataset found
✓ Stage-1 metadata found
✓ N04 output directory ready
✓ Reproducibility configuration initialized

========================================================================
Environment recovery completed successfully.
========================================================================

## 4.2 Stage-1 Dataset Validation

This section loads the persisted Stage-1 feature-engineered dataset generated by
Notebook 03 and verifies that it satisfies the structural and data-integrity
requirements for Notebook 04.

The Stage-1 dataset is treated as an upstream artifact and is not modified in
this section.

The validation covers:

- dataset existence and successful loading,
- dataset dimensions,
- feature and target columns,
- feature ordering,
- data types,
- missing values,
- infinite values,
- invalid negative values,
- target integrity,
- original class distribution,
- and consistency with the Stage-1 metadata.

The purpose of this section is to establish a verified baseline before any
target-taxonomy transformation, data partitioning, feature selection,
correlation pruning, scaling, or class-imbalance experiment is performed.

No rows, features, labels, or values are modified during this stage.

In [3]:
# ============================================================
# 4.2 Stage-1 Dataset Validation
# ============================================================

import pandas as pd

# ------------------------------------------------------------
# 4.2.1 Load Stage-1 Dataset
# ------------------------------------------------------------

print("=" * 72)
print("NOTEBOOK 04 — STAGE-1 DATASET VALIDATION")
print("=" * 72)

print("\nLoading Stage-1 dataset...")
print(f"Path: {STAGE1_DATA_PATH}")

stage1_df = pd.read_parquet(STAGE1_DATA_PATH)

print("✓ Stage-1 dataset loaded successfully.")

# ------------------------------------------------------------
# 4.2.2 Basic Dataset Dimensions
# ------------------------------------------------------------

n_rows, n_columns = stage1_df.shape

print("\n[DATASET DIMENSIONS]")
print(f"Rows              : {n_rows:,}")
print(f"Total Columns     : {n_columns:,}")

# ------------------------------------------------------------
# 4.2.3 Validate Target Column
# ------------------------------------------------------------

EXPECTED_TARGET_COLUMN = "Target"

if EXPECTED_TARGET_COLUMN not in stage1_df.columns:
    raise ValueError(
        f"Required target column '{EXPECTED_TARGET_COLUMN}' "
        "was not found in the Stage-1 dataset."
    )

TARGET_COLUMN = EXPECTED_TARGET_COLUMN

feature_columns = [
    column for column in stage1_df.columns
    if column != TARGET_COLUMN
]

print("\n[TARGET]")
print(f"Target Column     : {TARGET_COLUMN}")
print(f"Feature Columns   : {len(feature_columns):,}")

# ------------------------------------------------------------
# 4.2.4 Validate Feature Count Against Stage-1 Metadata
# ------------------------------------------------------------

metadata_dataset = STAGE1_METADATA.get("dataset", {})

expected_rows = metadata_dataset.get("number_of_records")
expected_features = metadata_dataset.get("number_of_input_features")
expected_target = metadata_dataset.get("target_column")

print("\n[METADATA CONSISTENCY]")

if expected_rows is not None:
    print(f"Metadata Rows     : {expected_rows:,}")
else:
    print("Metadata Rows     : Not available")

if expected_features is not None:
    print(f"Metadata Features: {expected_features:,}")
else:
    print("Metadata Features: Not available")

if expected_target is not None:
    print(f"Metadata Target  : {expected_target}")
else:
    print("Metadata Target  : Not available")

if expected_rows is not None and n_rows != expected_rows:
    raise ValueError(
        f"Row-count mismatch: dataset has {n_rows:,} rows, "
        f"but metadata specifies {expected_rows:,}."
    )

if expected_features is not None and len(feature_columns) != expected_features:
    raise ValueError(
        f"Feature-count mismatch: dataset has {len(feature_columns)} "
        f"features, but metadata specifies {expected_features}."
    )

if expected_target is not None and TARGET_COLUMN != expected_target:
    raise ValueError(
        f"Target-column mismatch: dataset uses '{TARGET_COLUMN}', "
        f"but metadata specifies '{expected_target}'."
    )

print("✓ Dataset dimensions and target metadata are consistent.")

# ------------------------------------------------------------
# 4.2.5 Validate Feature Ordering Against Metadata
# ------------------------------------------------------------

metadata_feature_columns = STAGE1_METADATA.get("feature_columns")

if metadata_feature_columns is not None:

    if feature_columns != metadata_feature_columns:
        print("\n⚠ Feature-order/name mismatch detected.")

        missing_from_dataset = [
            feature for feature in metadata_feature_columns
            if feature not in feature_columns
        ]

        unexpected_in_dataset = [
            feature for feature in feature_columns
            if feature not in metadata_feature_columns
        ]

        if missing_from_dataset:
            print("\nMissing features:")
            for feature in missing_from_dataset:
                print(f"  - {feature}")

        if unexpected_in_dataset:
            print("\nUnexpected features:")
            for feature in unexpected_in_dataset:
                print(f"  - {feature}")

        if not missing_from_dataset and not unexpected_in_dataset:
            print(
                "\nThe same feature names are present, but their ordering "
                "does not match the metadata."
            )

        raise ValueError(
            "Stage-1 feature structure does not match the persisted metadata."
        )

    print("✓ Feature names and ordering match Stage-1 metadata.")

else:
    print(
        "⚠ Feature-column list was not present in Stage-1 metadata; "
        "feature-order validation was skipped."
    )

# ------------------------------------------------------------
# 4.2.6 Validate Data Types
# ------------------------------------------------------------

feature_dtypes = stage1_df[feature_columns].dtypes

non_numeric_features = feature_dtypes[
    ~feature_dtypes.apply(pd.api.types.is_numeric_dtype)
]

print("\n[DATA TYPES]")
print(f"Numeric Features          : {len(feature_columns) - len(non_numeric_features)}")
print(f"Non-Numeric Features      : {len(non_numeric_features)}")

if len(non_numeric_features) > 0:
    print("\nNon-numeric feature columns:")
    for feature in non_numeric_features.index:
        print(f"  - {feature}: {feature_dtypes[feature]}")

    raise TypeError(
        "One or more feature columns are non-numeric."
    )

if not pd.api.types.is_numeric_dtype(stage1_df[TARGET_COLUMN]):
    raise TypeError(
        f"Target column '{TARGET_COLUMN}' is not numeric."
    )

print("✓ All model features are numeric.")
print("✓ Target column is numeric.")

# ------------------------------------------------------------
# 4.2.7 Missing-Value Validation
# ------------------------------------------------------------

missing_counts = stage1_df.isna().sum()
total_missing = int(missing_counts.sum())

print("\n[MISSING VALUES]")
print(f"Total Missing Values : {total_missing:,}")

if total_missing > 0:

    print("\nColumns containing missing values:")
    for column, count in missing_counts[missing_counts > 0].items():
        print(f"  - {column}: {count:,}")

    raise ValueError(
        "Missing values were detected in the Stage-1 dataset."
    )

print("✓ No missing values detected.")

# ------------------------------------------------------------
# 4.2.8 Infinite-Value Validation
# ------------------------------------------------------------

numeric_df = stage1_df[feature_columns]

infinite_mask = ~np.isfinite(numeric_df.to_numpy())

total_infinite = int(infinite_mask.sum())

print("\n[INFINITE VALUES]")
print(f"Total Infinite Values : {total_infinite:,}")

if total_infinite > 0:
    infinite_columns = numeric_df.columns[
        infinite_mask.any(axis=0)
    ]

    print("\nColumns containing infinite values:")
    for column in infinite_columns:
        print(f"  - {column}")

    raise ValueError(
        "Infinite values were detected in the Stage-1 feature matrix."
    )

print("✓ No infinite values detected.")

# ------------------------------------------------------------
# 4.2.9 Negative-Value Validation
# ------------------------------------------------------------

negative_mask = (numeric_df.to_numpy() < 0)

total_negative = int(negative_mask.sum())

print("\n[NEGATIVE VALUES]")
print(f"Total Negative Values : {total_negative:,}")

if total_negative > 0:

    negative_columns = numeric_df.columns[
        negative_mask.any(axis=0)
    ]

    print("\nColumns containing negative values:")
    for column in negative_columns:
        print(f"  - {column}")

    raise ValueError(
        "Negative values were detected in the Stage-1 feature matrix."
    )

print("✓ No negative feature values detected.")

# ------------------------------------------------------------
# 4.2.10 Target Integrity
# ------------------------------------------------------------

target_values = stage1_df[TARGET_COLUMN]

target_missing = int(target_values.isna().sum())
target_unique = sorted(target_values.unique().tolist())

print("\n[TARGET INTEGRITY]")
print(f"Missing Target Values : {target_missing:,}")
print(f"Unique Target Values  : {len(target_unique)}")
print(f"Target Values         : {target_unique}")

if target_missing > 0:
    raise ValueError(
        "Missing target values were detected."
    )

if len(target_unique) != 15:
    print(
        "\n⚠ Expected the original 15-class CICIDS-2017 target "
        f"representation, but found {len(target_unique)} unique values."
    )

# ------------------------------------------------------------
# 4.2.11 Original Target Distribution
# ------------------------------------------------------------

target_distribution = (
    stage1_df[TARGET_COLUMN]
    .value_counts()
    .sort_index()
)

target_percentages = (
    target_distribution
    / len(stage1_df)
    * 100
)

original_class_distribution = pd.DataFrame({
    "Target": target_distribution.index,
    "Count": target_distribution.values,
    "Percentage": target_percentages.values
})

print("\n[ORIGINAL TARGET DISTRIBUTION]")
display(original_class_distribution)

# ------------------------------------------------------------
# 4.2.12 Duplicate Count — Informational Only
# ------------------------------------------------------------

duplicate_rows = int(stage1_df.duplicated().sum())

print("\n[DUPLICATE OBSERVATIONS — INFORMATIONAL]")
print(f"Exact Duplicate Rows : {duplicate_rows:,}")

print(
    "\nNote: Duplicate observations are not removed in Section 4.2. "
    "They will be investigated and handled explicitly in the dedicated "
    "duplicate/leakage audit section."
)

# ------------------------------------------------------------
# 4.2.13 Final Validation Summary
# ------------------------------------------------------------

print("\n" + "=" * 72)
print("STAGE-1 DATASET VALIDATION SUMMARY")
print("=" * 72)

print(f"✓ Rows                    : {n_rows:,}")
print(f"✓ Feature columns         : {len(feature_columns):,}")
print(f"✓ Target column           : {TARGET_COLUMN}")
print(f"✓ Unique original classes : {len(target_unique)}")
print(f"✓ Missing values          : {total_missing:,}")
print(f"✓ Infinite values         : {total_infinite:,}")
print(f"✓ Negative feature values : {total_negative:,}")
print(f"✓ Exact duplicate rows    : {duplicate_rows:,}")

print("\n✓ Stage-1 dataset passed structural and integrity validation.")
print("✓ No data transformation was performed in Section 4.2.")
print("=" * 72)

========================================================================
NOTEBOOK 04 — STAGE-1 DATASET VALIDATION
========================================================================

Loading Stage-1 dataset...
Path: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/data/processed/CICIDS2017_stage1_feature_engineered.parquet
✓ Stage-1 dataset loaded successfully.

[DATASET DIMENSIONS]
Rows              : 2,830,743
Total Columns     : 64

[TARGET]
Target Column     : Target
Feature Columns   : 63

[METADATA CONSISTENCY]
Metadata Rows     : 2,830,743
Metadata Features: 63
Metadata Target  : Target
✓ Dataset dimensions and target metadata are consistent.
✓ Feature names and ordering match Stage-1 metadata.

[DATA TYPES]
Numeric Features          : 63
Non-Numeric Features      : 0
✓ All model features are numeric.
✓ Target column is numeric.

[MISSING VALUES]
Total Missing Values : 0
✓ No missing values detected.

[INFINITE VALUES]
Total Infinite Values : 0
✓ No infinite values detected.

[NEGATIVE VALUES]
Total Negative Values : 0
✓ No negative feature values detected.

[TARGET INTEGRITY]
Missing Target Values : 0
Unique Target Values  : 15
Target Values         : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

[ORIGINAL TARGET DISTRIBUTION]

    Target    Count  Percentage
0        0  2273097   80.300366
1        1     1966    0.069452
2        2   128027    4.522735
3        3    10293    0.363615
4        4   231073    8.162981
5        5     5499    0.194260
6        6     5796    0.204752
7        7     7938    0.280421
8        8       11    0.000389
9        9       36    0.001272
10      10   158930    5.614427
11      11     5897    0.208320
12      12     1507    0.053237
13      13       21    0.000742
14      14      652    0.023033

[DUPLICATE OBSERVATIONS — INFORMATIONAL]
Exact Duplicate Rows : 355,771

Note: Duplicate observations are not removed in Section 4.2. They will be investigated and handled explicitly in the dedicated duplicate/leakage audit section.

========================================================================
STAGE-1 DATASET VALIDATION SUMMARY
========================================================================
✓ Rows                    : 2,830,743
✓ Feature columns         : 63
✓ Target column           : Target
✓ Unique original classes : 15
✓ Missing values          : 0
✓ Infinite values         : 0
✓ Negative feature values : 0
✓ Exact duplicate rows    : 355,771

✓ Stage-1 dataset passed structural and integrity validation.
✓ No data transformation was performed in Section 4.2.
========================================================================

## 4.3 Final Target Taxonomy

The original Stage-1 dataset retains the 15 encoded CICIDS-2017 target
categories. For the primary intrusion-detection task, these fine-grained
labels are consolidated into an attack-family taxonomy consisting of eight
attack families and one separate BENIGN class.

The taxonomy is designed to preserve meaningful distinctions between different
types of network attacks while avoiding unnecessary fragmentation of closely
related variants.

In particular, network/service-level brute-force attacks are distinguished
from web-application attacks, while the individual DoS variants are grouped
under their common DoS attack family.

The original target representation is preserved throughout this section.
The final taxonomy is first defined explicitly and is subsequently mapped to
the dataset only after complete label coverage and consistency have been
validated.

The final classification problem therefore contains nine classes:

1. BENIGN
2. DDoS
3. Port Scan
4. Brute Force
5. Bot
6. Web Attack
7. Infiltration
8. DoS
9. Heartbleed

### 4.3.1 Define Final Attack-Family Taxonomy

The final taxonomy is defined by grouping the original CICIDS-2017 labels into
their corresponding attack families.

The grouping follows the semantic structure required by the project rather than
forcing every fine-grained dataset label to remain an independent model class.

The following rules are established:

- BENIGN remains a separate normal-traffic class.
- DDoS remains a dedicated attack family.
- PortScan remains a dedicated attack family.
- FTP-Patator and SSH-Patator are grouped as Brute Force because both represent
  service-level brute-force activity.
- Web Attack – Brute Force, Web Attack – XSS, and Web Attack – SQL Injection
  are grouped as Web Attack because they belong to the web-application attack
  category.
- DoS Hulk, DoS GoldenEye, DoS slowloris, and DoS Slowhttptest are grouped as
  DoS because they are distinct variants of denial-of-service activity.
- Bot remains a dedicated attack family.
- Infiltration remains a dedicated attack family.
- Heartbleed remains a dedicated attack family despite its very low support in
  the dataset.

This produces eight attack families plus BENIGN, resulting in nine primary
classification classes.

The original fine-grained labels are retained for traceability and can be used
later for error analysis within each consolidated attack family.

In [4]:
# ============================================================
# 4.3.1 Define Final Attack-Family Taxonomy
# ============================================================

# The taxonomy is defined explicitly before any transformation
# is applied to the Stage-1 target column.

FINAL_CLASS_NAMES = [
    "BENIGN",
    "DDoS",
    "Port Scan",
    "Brute Force",
    "Bot",
    "Web Attack",
    "Infiltration",
    "DoS",
    "Heartbleed",
]

# Number of final classes
N_FINAL_CLASSES = len(FINAL_CLASS_NAMES)

# Explicit final class IDs.
# These IDs are part of the N04 data contract and will be
# preserved for all downstream model notebooks.

FINAL_CLASS_ID_MAPPING = {
    "BENIGN": 0,
    "DDoS": 1,
    "Port Scan": 2,
    "Brute Force": 3,
    "Bot": 4,
    "Web Attack": 5,
    "Infiltration": 6,
    "DoS": 7,
    "Heartbleed": 8,
}

# ------------------------------------------------------------
# Display the taxonomy
# ------------------------------------------------------------

taxonomy_definition = pd.DataFrame({
    "Final Class ID": range(N_FINAL_CLASSES),
    "Final Class": FINAL_CLASS_NAMES,
    "Type": [
        "Normal",
        "Attack",
        "Attack",
        "Attack",
        "Attack",
        "Attack",
        "Attack",
        "Attack",
        "Attack",
    ],
})

print("=" * 72)
print("4.3.1 — FINAL ATTACK-FAMILY TAXONOMY")
print("=" * 72)

display(taxonomy_definition)

# ------------------------------------------------------------
# Validate taxonomy definition
# ------------------------------------------------------------

assert N_FINAL_CLASSES == 9, (
    f"Expected 9 final classes, found {N_FINAL_CLASSES}."
)

assert set(FINAL_CLASS_NAMES) == set(FINAL_CLASS_ID_MAPPING.keys()), (
    "Final class names and class-ID mapping are inconsistent."
)

assert sorted(FINAL_CLASS_ID_MAPPING.values()) == list(range(N_FINAL_CLASSES)), (
    "Final class IDs must be consecutive integers starting from 0."
)

assert FINAL_CLASS_NAMES[0] == "BENIGN", (
    "BENIGN must remain the dedicated normal-traffic class."
)

print("\n[VALIDATION]")
print(f"✓ Final classes defined : {N_FINAL_CLASSES}")
print("✓ Eight attack families defined")
print("✓ BENIGN retained as separate normal-traffic class")
print("✓ Class IDs are unique and consecutive")
print("✓ Taxonomy definition is internally consistent")

print("\nNo target values have been modified in this subsection.")
print("=" * 72)

========================================================================
4.3.1 — FINAL ATTACK-FAMILY TAXONOMY
========================================================================

   Final Class ID   Final Class    Type
0               0        BENIGN  Normal
1               1          DDoS  Attack
2               2     Port Scan  Attack
3               3   Brute Force  Attack
4               4           Bot  Attack
5               5    Web Attack  Attack
6               6  Infiltration  Attack
7               7           DoS  Attack
8               8    Heartbleed  Attack

[VALIDATION]
✓ Final classes defined : 9
✓ Eight attack families defined
✓ BENIGN retained as separate normal-traffic class
✓ Class IDs are unique and consecutive
✓ Taxonomy definition is internally consistent

No target values have been modified in this subsection.
========================================================================

### 4.3.2 Map Original Labels to Attack Families

The Stage-1 dataset stores the original CICIDS-2017 target categories as
integer-encoded values. These encoded values are mapped explicitly to their
corresponding original CICIDS-2017 labels before being consolidated into the
final attack-family taxonomy.

The mapping preserves the semantic distinction between:

- service-level Brute Force attacks,
- Web Attack variants,
- and individual DoS variants.

The original target encoding is not overwritten. A separate final-class
representation will be created so that the original dataset labels remain
available for traceability and later fine-grained error analysis.

The expected original target encoding recovered from the Stage-1 dataset is:

| Original Target ID | Original CICIDS-2017 Label | Final Attack Family |
|---:|---|---|
| 0 | BENIGN | BENIGN |
| 1 | Bot | Bot |
| 2 | DDoS | DDoS |
| 3 | DoS GoldenEye | DoS |
| 4 | DoS Hulk | DoS |
| 5 | DoS Slowhttptest | DoS |
| 6 | DoS slowloris | DoS |
| 7 | FTP-Patator | Brute Force |
| 8 | Heartbleed | Heartbleed |
| 9 | Infiltration | Infiltration |
| 10 | PortScan | Port Scan |
| 11 | SSH-Patator | Brute Force |
| 12 | Web Attack – Brute Force | Web Attack |
| 13 | Web Attack – SQL Injection | Web Attack |
| 14 | Web Attack – XSS | Web Attack |

This explicit mapping is used instead of relying on the numerical ordering of
the final classes.

In [5]:
# ============================================================
# 4.3.2 Map Original Labels to Attack Families
# ============================================================

# ------------------------------------------------------------
# 4.3.2.1 Define Original CICIDS-2017 Label Mapping
# ------------------------------------------------------------

ORIGINAL_LABEL_MAPPING = {
    0: "BENIGN",
    1: "Bot",
    2: "DDoS",
    3: "DoS GoldenEye",
    4: "DoS Hulk",
    5: "DoS Slowhttptest",
    6: "DoS slowloris",
    7: "FTP-Patator",
    8: "Heartbleed",
    9: "Infiltration",
    10: "PortScan",
    11: "SSH-Patator",
    12: "Web Attack – Brute Force",
    13: "Web Attack – SQL Injection",
    14: "Web Attack – XSS",
}

# ------------------------------------------------------------
# 4.3.2.2 Define Original Label → Final Family Mapping
# ------------------------------------------------------------

ORIGINAL_TO_FINAL_FAMILY = {
    "BENIGN": "BENIGN",
    "Bot": "Bot",
    "DDoS": "DDoS",
    "DoS GoldenEye": "DoS",
    "DoS Hulk": "DoS",
    "DoS Slowhttptest": "DoS",
    "DoS slowloris": "DoS",
    "FTP-Patator": "Brute Force",
    "Heartbleed": "Heartbleed",
    "Infiltration": "Infiltration",
    "PortScan": "Port Scan",
    "SSH-Patator": "Brute Force",
    "Web Attack – Brute Force": "Web Attack",
    "Web Attack – SQL Injection": "Web Attack",
    "Web Attack – XSS": "Web Attack",
}

# ------------------------------------------------------------
# 4.3.2.3 Construct Explicit Taxonomy Mapping Table
# ------------------------------------------------------------

taxonomy_mapping_table = pd.DataFrame({
    "Original Target ID": list(ORIGINAL_LABEL_MAPPING.keys()),
    "Original Label": list(ORIGINAL_LABEL_MAPPING.values()),
})

taxonomy_mapping_table["Final Attack Family"] = (
    taxonomy_mapping_table["Original Label"]
    .map(ORIGINAL_TO_FINAL_FAMILY)
)

taxonomy_mapping_table["Final Class ID"] = (
    taxonomy_mapping_table["Final Attack Family"]
    .map(FINAL_CLASS_ID_MAPPING)
)

# ------------------------------------------------------------
# 4.3.2.4 Display Mapping
# ------------------------------------------------------------

print("=" * 72)
print("4.3.2 — ORIGINAL LABEL → FINAL ATTACK-FAMILY MAPPING")
print("=" * 72)

display(taxonomy_mapping_table)

# ------------------------------------------------------------
# 4.3.2.5 Basic Mapping Validation
# ------------------------------------------------------------

if taxonomy_mapping_table["Final Attack Family"].isna().any():
    missing_labels = taxonomy_mapping_table.loc[
        taxonomy_mapping_table["Final Attack Family"].isna(),
        "Original Label"
    ].tolist()

    raise ValueError(
        "The following original labels do not have a final-family mapping:\n"
        + "\n".join(f"  - {label}" for label in missing_labels)
    )

if taxonomy_mapping_table["Final Class ID"].isna().any():
    missing_families = taxonomy_mapping_table.loc[
        taxonomy_mapping_table["Final Class ID"].isna(),
        "Final Attack Family"
    ].unique().tolist()

    raise ValueError(
        "The following final families do not have a class ID:\n"
        + "\n".join(f"  - {family}" for family in missing_families)
    )

# ------------------------------------------------------------
# 4.3.2.6 Validate Original Target IDs
# ------------------------------------------------------------

observed_target_ids = sorted(
    stage1_df[TARGET_COLUMN].unique().tolist()
)

expected_target_ids = sorted(
    ORIGINAL_LABEL_MAPPING.keys()
)

if observed_target_ids != expected_target_ids:
    raise ValueError(
        "Observed Stage-1 target IDs do not exactly match the "
        "expected original CICIDS-2017 target encoding.\n"
        f"Observed: {observed_target_ids}\n"
        f"Expected: {expected_target_ids}"
    )

print("\n[VALIDATION]")
print(f"✓ Original target IDs found : {len(observed_target_ids)}")
print("✓ All 15 original target IDs have explicit labels")
print("✓ All original labels have a final attack-family mapping")
print("✓ All final families have valid class IDs")

print("\nNo target values have been modified yet.")
print("=" * 72)

========================================================================
4.3.2 — ORIGINAL LABEL → FINAL ATTACK-FAMILY MAPPING
========================================================================

,Original Target ID,Original Label,Final Attack Family,Final Class ID
0,0,BENIGN,BENIGN,0
1,1,Bot,Bot,4
2,2,DDoS,DDoS,1
3,3,DoS GoldenEye,DoS,7
4,4,DoS Hulk,DoS,7
5,5,DoS Slowhttptest,DoS,7
6,6,DoS slowloris,DoS,7
7,7,FTP-Patator,Brute Force,3
8,8,Heartbleed,Heartbleed,8
9,9,Infiltration,Infiltration,6
10,10,PortScan,Port Scan,2
11,11,SSH-Patator,Brute Force,3
12,12,Web Attack – Brute Force,Web Attack,5
13,13,Web Attack – SQL Injection,Web Attack,5
14,14,Web Attack – XSS,Web Attack,5

[VALIDATION]
✓ Original target IDs found : 15
✓ All 15 original target IDs have explicit labels
✓ All original labels have a final attack-family mapping
✓ All final families have valid class IDs

No target values have been modified yet.
========================================================================

### 4.3.3 Validate Complete Label Coverage

Before transforming the original target representation, the complete
15-to-9 taxonomy mapping is validated against the actual Stage-1 dataset.

The validation ensures that:

1. Every original target value present in the dataset has an explicit
   CICIDS-2017 label.
2. Every original label has exactly one final attack-family assignment.
3. No original target value is left unmapped.
4. No unexpected target values are present.
5. Every final classification family is represented by at least one original
   dataset label.
6. The number of original labels grouped into each final family is consistent
   with the defined taxonomy.

This validation is performed before creating the final model target.

The original `Target` column remains unchanged during this subsection.

In [6]:
# ============================================================
# 4.3.3 Validate Complete Label Coverage
# ============================================================

print("=" * 72)
print("4.3.3 — COMPLETE LABEL COVERAGE VALIDATION")
print("=" * 72)

# ------------------------------------------------------------
# 4.3.3.1 Recover Observed Target IDs
# ------------------------------------------------------------

observed_target_ids = sorted(
    stage1_df[TARGET_COLUMN].unique().tolist()
)

expected_target_ids = sorted(
    ORIGINAL_LABEL_MAPPING.keys()
)

print("\n[ORIGINAL TARGET COVERAGE]")
print(f"Observed target IDs : {observed_target_ids}")
print(f"Expected target IDs : {expected_target_ids}")

# ------------------------------------------------------------
# 4.3.3.2 Check for Unexpected Target IDs
# ------------------------------------------------------------

unexpected_target_ids = sorted(
    set(observed_target_ids) - set(expected_target_ids)
)

missing_target_ids = sorted(
    set(expected_target_ids) - set(observed_target_ids)
)

if unexpected_target_ids:
    raise ValueError(
        "Unexpected target IDs were found in the Stage-1 dataset:\n"
        + "\n".join(
            f"  - {target_id}"
            for target_id in unexpected_target_ids
        )
    )

if missing_target_ids:
    print(
        "⚠ Some expected original target IDs are not represented "
        "in the current dataset:"
    )

    for target_id in missing_target_ids:
        print(f"  - {target_id}")

else:
    print("✓ Every expected original target ID is present.")

# ------------------------------------------------------------
# 4.3.3.3 Verify Every Observed Target Has a Label
# ------------------------------------------------------------

unlabeled_target_ids = [
    target_id
    for target_id in observed_target_ids
    if target_id not in ORIGINAL_LABEL_MAPPING
]

if unlabeled_target_ids:
    raise ValueError(
        "Observed target IDs without an explicit original-label mapping:\n"
        + "\n".join(
            f"  - {target_id}"
            for target_id in unlabeled_target_ids
        )
    )

print("✓ Every observed target ID has an explicit original label.")

# ------------------------------------------------------------
# 4.3.3.4 Verify Every Original Label Has One Final Family
# ------------------------------------------------------------

original_labels = list(ORIGINAL_LABEL_MAPPING.values())

missing_final_family = [
    label
    for label in original_labels
    if label not in ORIGINAL_TO_FINAL_FAMILY
]

if missing_final_family:
    raise ValueError(
        "Original labels without a final attack-family assignment:\n"
        + "\n".join(
            f"  - {label}"
            for label in missing_final_family
        )
    )

print("✓ Every original label has a final attack-family assignment.")

# ------------------------------------------------------------
# 4.3.3.5 Check for Duplicate / Ambiguous Mapping Definitions
# ------------------------------------------------------------

mapping_rows = taxonomy_mapping_table[
    ["Original Target ID", "Original Label", "Final Attack Family"]
].copy()

duplicate_original_ids = (
    mapping_rows["Original Target ID"]
    .duplicated(keep=False)
)

duplicate_original_labels = (
    mapping_rows["Original Label"]
    .duplicated(keep=False)
)

if duplicate_original_ids.any():
    raise ValueError(
        "Duplicate original target IDs exist in the taxonomy mapping."
    )

if duplicate_original_labels.any():
    raise ValueError(
        "Duplicate original labels exist in the taxonomy mapping."
    )

print("✓ Every original target ID appears exactly once.")
print("✓ Every original label appears exactly once.")

# ------------------------------------------------------------
# 4.3.3.6 Determine Final Families Represented
# ------------------------------------------------------------

observed_original_labels = (
    stage1_df[TARGET_COLUMN]
    .map(ORIGINAL_LABEL_MAPPING)
)

observed_final_families = (
    observed_original_labels
    .map(ORIGINAL_TO_FINAL_FAMILY)
)

unmapped_rows = int(
    observed_final_families.isna().sum()
)

if unmapped_rows > 0:
    raise ValueError(
        f"{unmapped_rows:,} dataset rows could not be mapped "
        "to a final attack family."
    )

print("✓ Every dataset row can be mapped to a final attack family.")

# ------------------------------------------------------------
# 4.3.3.7 Validate Representation of All Nine Final Classes
# ------------------------------------------------------------

represented_final_families = sorted(
    observed_final_families.unique().tolist()
)

expected_final_families = sorted(
    FINAL_CLASS_ID_MAPPING.keys()
)

missing_final_families = sorted(
    set(expected_final_families)
    - set(represented_final_families)
)

unexpected_final_families = sorted(
    set(represented_final_families)
    - set(expected_final_families)
)

if unexpected_final_families:
    raise ValueError(
        "Unexpected final attack families were produced:\n"
        + "\n".join(
            f"  - {family}"
            for family in unexpected_final_families
        )
    )

if missing_final_families:
    print(
        "⚠ The following final families are not represented "
        "in the dataset:"
    )

    for family in missing_final_families:
        print(f"  - {family}")

else:
    print("✓ All nine final classification classes are represented.")

# ------------------------------------------------------------
# 4.3.3.8 Count Original Labels per Final Family
# ------------------------------------------------------------

labels_per_family = (
    taxonomy_mapping_table
    .groupby("Final Attack Family")
    .agg(
        Number_of_Original_Labels=("Original Label", "count"),
        Original_Labels=("Original Label", list)
    )
    .reset_index()
)

labels_per_family["Final Class ID"] = (
    labels_per_family["Final Attack Family"]
    .map(FINAL_CLASS_ID_MAPPING)
)

labels_per_family = (
    labels_per_family[
        [
            "Final Class ID",
            "Final Attack Family",
            "Number_of_Original_Labels",
            "Original_Labels",
        ]
    ]
    .sort_values("Final Class ID")
    .reset_index(drop=True)
)

print("\n[ORIGINAL LABELS GROUPED BY FINAL FAMILY]")

display(labels_per_family)

# ------------------------------------------------------------
# 4.3.3.9 Count Actual Dataset Rows per Final Family
# ------------------------------------------------------------

final_family_row_counts = (
    observed_final_families
    .value_counts()
    .rename_axis("Final Attack Family")
    .reset_index(name="Row Count")
)

final_family_row_counts["Final Class ID"] = (
    final_family_row_counts["Final Attack Family"]
    .map(FINAL_CLASS_ID_MAPPING)
)

final_family_row_counts["Percentage"] = (
    final_family_row_counts["Row Count"]
    / len(stage1_df)
    * 100
)

final_family_row_counts = (
    final_family_row_counts[
        [
            "Final Class ID",
            "Final Attack Family",
            "Row Count",
            "Percentage",
        ]
    ]
    .sort_values("Final Class ID")
    .reset_index(drop=True)
)

print("\n[FINAL FAMILY REPRESENTATION — BEFORE TARGET TRANSFORMATION]")

display(final_family_row_counts)

# ------------------------------------------------------------
# 4.3.3.10 Final Coverage Assertions
# ------------------------------------------------------------

assert len(observed_target_ids) == 15, (
    "The Stage-1 dataset does not contain the expected 15 original classes."
)

assert len(represented_final_families) == 9, (
    "The taxonomy does not produce all nine final classes."
)

assert unmapped_rows == 0, (
    "One or more dataset rows remain unmapped."
)

assert (
    final_family_row_counts["Row Count"].sum()
    == len(stage1_df)
), (
    "Final-family row counts do not account for every dataset row."
)

# ------------------------------------------------------------
# 4.3.3.11 Validation Summary
# ------------------------------------------------------------

print("\n" + "=" * 72)
print("COMPLETE LABEL COVERAGE VALIDATION SUMMARY")
print("=" * 72)

print("✓ 15 original target classes detected")
print("✓ No unexpected target IDs detected")
print("✓ Every original target ID has an explicit label")
print("✓ Every original label has exactly one final family")
print("✓ Every dataset row maps to exactly one final family")
print("✓ All 9 final classes are represented")
print("✓ Final-family row counts account for all dataset records")

print("\nOriginal target column remains unchanged.")
print("No final target column has been created yet.")

print("=" * 72)

========================================================================
4.3.3 — COMPLETE LABEL COVERAGE VALIDATION
========================================================================

[ORIGINAL TARGET COVERAGE]
Observed target IDs : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Expected target IDs : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
✓ Every expected original target ID is present.
✓ Every observed target ID has an explicit original label.
✓ Every original label has a final attack-family assignment.
✓ Every original target ID appears exactly once.
✓ Every original label appears exactly once.
✓ Every dataset row can be mapped to a final attack family.
✓ All nine final classification classes are represented.

[ORIGINAL LABELS GROUPED BY FINAL FAMILY]

,Final Class ID,Final Attack Family,Number_of_Original_Labels,Original_Labels
0,0,BENIGN,1,[BENIGN]
1,1,DDoS,1,[DDoS]
2,2,Port Scan,1,[PortScan]
3,3,Brute Force,2,"[FTP-Patator, SSH-Patator]"
4,4,Bot,1,[Bot]
5,5,Web Attack,3,"[Web Attack – Brute Force, Web Attack – SQL In..."
6,6,Infiltration,1,[Infiltration]
7,7,DoS,4,"[DoS GoldenEye, DoS Hulk, DoS Slowhttptest, Do..."
8,8,Heartbleed,1,[Heartbleed]

[FINAL FAMILY REPRESENTATION — BEFORE TARGET TRANSFORMATION]

   Final Class ID Final Attack Family  Row Count  Percentage
0               0              BENIGN    2273097   80.300366
1               1                DDoS     128027    4.522735
2               2           Port Scan     158930    5.614427
3               3         Brute Force      13835    0.488741
4               4                 Bot       1966    0.069452
5               5          Web Attack       2180    0.077012
6               6        Infiltration         36    0.001272
7               7                 DoS     252661    8.925607
8               8          Heartbleed         11    0.000389

========================================================================
COMPLETE LABEL COVERAGE VALIDATION SUMMARY
========================================================================
✓ 15 original target classes detected
✓ No unexpected target IDs detected
✓ Every original target ID has an explicit label
✓ Every original label has exactly one final family
✓ Every dataset row maps to exactly one final family
✓ All 9 final classes are represented
✓ Final-family row counts account for all dataset records

Original target column remains unchanged.
No final target column has been created yet.
========================================================================

### 4.3.4 Create Final Class IDs

The validated attack-family taxonomy is now applied to the Stage-1 dataset.

A new `FinalTarget` column is created using the predefined final class IDs:

- 0 → BENIGN
- 1 → DDoS
- 2 → Port Scan
- 3 → Brute Force
- 4 → Bot
- 5 → Web Attack
- 6 → Infiltration
- 7 → DoS
- 8 → Heartbleed

The original `Target` column is preserved without modification. This maintains
traceability between the original CICIDS-2017 labels and the consolidated
attack-family representation.

A second `FinalTargetName` column is also created to provide a human-readable
representation of the final class.

The transformation is validated by checking that:

1. No rows remain unmapped.
2. Only the expected final class IDs are present.
3. Every final class name corresponds to the correct class ID.
4. The resulting class distribution matches the distribution established during
   the previous taxonomy validation stage.

No feature values are modified in this subsection.

In [7]:
# ============================================================
# 4.3.4 Create Final Class IDs
# ============================================================

print("=" * 72)
print("4.3.4 — CREATE FINAL CLASS IDs")
print("=" * 72)

# ------------------------------------------------------------
# 4.3.4.1 Create Temporary Final-Family Representation
# ------------------------------------------------------------

final_family_series = (
    stage1_df[TARGET_COLUMN]
    .map(ORIGINAL_LABEL_MAPPING)
    .map(ORIGINAL_TO_FINAL_FAMILY)
)

# ------------------------------------------------------------
# 4.3.4.2 Validate No Rows Are Unmapped
# ------------------------------------------------------------

unmapped_count = int(final_family_series.isna().sum())

print("\n[FINAL FAMILY MAPPING]")
print(f"Total dataset rows : {len(stage1_df):,}")
print(f"Unmapped rows      : {unmapped_count:,}")

if unmapped_count > 0:
    raise ValueError(
        f"{unmapped_count:,} rows could not be assigned "
        "to a final attack family."
    )

print("✓ Every dataset row has a valid final attack family.")

# ------------------------------------------------------------
# 4.3.4.3 Create FinalTargetName
# ------------------------------------------------------------

stage1_df["FinalTargetName"] = final_family_series

# ------------------------------------------------------------
# 4.3.4.4 Create FinalTarget Class IDs
# ------------------------------------------------------------

stage1_df["FinalTarget"] = (
    stage1_df["FinalTargetName"]
    .map(FINAL_CLASS_ID_MAPPING)
    .astype("int8")
)

# ------------------------------------------------------------
# 4.3.4.5 Validate Final Class IDs
# ------------------------------------------------------------

expected_final_ids = set(
    FINAL_CLASS_ID_MAPPING.values()
)

observed_final_ids = set(
    stage1_df["FinalTarget"].unique().tolist()
)

unexpected_final_ids = sorted(
    observed_final_ids - expected_final_ids
)

missing_final_ids = sorted(
    expected_final_ids - observed_final_ids
)

if unexpected_final_ids:
    raise ValueError(
        "Unexpected FinalTarget IDs detected:\n"
        + "\n".join(
            f"  - {class_id}"
            for class_id in unexpected_final_ids
        )
    )

if missing_final_ids:
    raise ValueError(
        "Expected FinalTarget IDs are missing:\n"
        + "\n".join(
            f"  - {class_id}"
            for class_id in missing_final_ids
        )
    )

print("\n[FINAL CLASS IDs]")
print(f"Expected class IDs : {sorted(expected_final_ids)}")
print(f"Observed class IDs : {sorted(observed_final_ids)}")

# ------------------------------------------------------------
# 4.3.4.6 Validate FinalTarget ↔ FinalTargetName Consistency
# ------------------------------------------------------------

id_to_name = {
    class_id: class_name
    for class_name, class_id
    in FINAL_CLASS_ID_MAPPING.items()
}

reconstructed_names = (
    stage1_df["FinalTarget"]
    .map(id_to_name)
)

name_mismatch_count = int(
    (reconstructed_names != stage1_df["FinalTargetName"]).sum()
)

if name_mismatch_count > 0:
    raise ValueError(
        f"{name_mismatch_count:,} rows have inconsistent "
        "FinalTarget and FinalTargetName values."
    )

print("✓ FinalTarget and FinalTargetName are fully consistent.")

# ------------------------------------------------------------
# 4.3.4.7 Validate Original Target Preservation
# ------------------------------------------------------------

if TARGET_COLUMN not in stage1_df.columns:
    raise ValueError(
        "Original Target column is missing after transformation."
    )

original_target_unique = sorted(
    stage1_df[TARGET_COLUMN].unique().tolist()
)

if original_target_unique != expected_target_ids:
    raise ValueError(
        "The original Target column no longer contains the expected "
        "15-class representation."
    )

print("✓ Original Target column preserved unchanged.")

# ------------------------------------------------------------
# 4.3.4.8 Final Target Distribution
# ------------------------------------------------------------

final_target_distribution = (
    stage1_df["FinalTarget"]
    .value_counts()
    .sort_index()
)

final_target_percentages = (
    final_target_distribution
    / len(stage1_df)
    * 100
)

final_class_distribution = pd.DataFrame({
    "Final Class ID": final_target_distribution.index.astype(int),
    "Final Class": [
        id_to_name[class_id]
        for class_id in final_target_distribution.index
    ],
    "Count": final_target_distribution.values.astype(int),
    "Percentage": final_target_percentages.values,
})

print("\n[FINAL TARGET DISTRIBUTION]")
display(final_class_distribution)

# ------------------------------------------------------------
# 4.3.4.9 Validate Distribution Against 4.3.3
# ------------------------------------------------------------

# Compare the actual class IDs and counts rather than relying
# on strict DataFrame.equals(), which also checks dtype/metadata.

previous_ids = (
    final_family_row_counts["Final Class ID"]
    .astype(int)
    .to_numpy()
)

previous_counts = (
    final_family_row_counts["Row Count"]
    .astype(int)
    .to_numpy()
)

current_ids = (
    final_class_distribution["Final Class ID"]
    .astype(int)
    .to_numpy()
)

current_counts = (
    final_class_distribution["Count"]
    .astype(int)
    .to_numpy()
)

if not np.array_equal(previous_ids, current_ids):
    raise ValueError(
        "Final class IDs do not match the distribution "
        "validated in Section 4.3.3."
    )

if not np.array_equal(previous_counts, current_counts):
    raise ValueError(
        "Final class counts do not match the distribution "
        "validated in Section 4.3.3."
    )

print("✓ Final class IDs match Section 4.3.3.")
print("✓ Final class counts match Section 4.3.3.")

# ------------------------------------------------------------
# 4.3.4.10 Final Transformation Validation
# ------------------------------------------------------------

assert stage1_df["FinalTarget"].dtype == np.int8

assert stage1_df["FinalTarget"].isna().sum() == 0

assert len(stage1_df) == 2_830_743

assert len(stage1_df["FinalTarget"].unique()) == 9

assert stage1_df[TARGET_COLUMN].nunique() == 15

# ------------------------------------------------------------
# 4.3.4.11 Display Sample for Traceability
# ------------------------------------------------------------

traceability_sample = (
    stage1_df[
        [
            TARGET_COLUMN,
            "FinalTargetName",
            "FinalTarget"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        by=[TARGET_COLUMN, "FinalTarget"]
    )
)

print("\n[ORIGINAL → FINAL TARGET TRACEABILITY]")
display(traceability_sample)

# ------------------------------------------------------------
# 4.3.4.12 Final Summary
# ------------------------------------------------------------

print("\n" + "=" * 72)
print("FINAL CLASS-ID CREATION SUMMARY")
print("=" * 72)

print("✓ FinalTarget created")
print("✓ FinalTargetName created")
print("✓ 15 original classes consolidated into 9 final classes")
print("✓ No unmapped rows")
print("✓ No unexpected final class IDs")
print("✓ All nine final classes represented")
print("✓ Final distribution matches Section 4.3.3")
print("✓ Original Target column preserved")
print("✓ No feature values modified")

print("\nThe Stage-1 dataframe now contains both the original")
print("15-class target and the final 9-class attack-family target.")

print("=" * 72)

========================================================================
4.3.4 — CREATE FINAL CLASS IDs
========================================================================

[FINAL FAMILY MAPPING]
Total dataset rows : 2,830,743
Unmapped rows      : 0
✓ Every dataset row has a valid final attack family.

[FINAL CLASS IDs]
Expected class IDs : [0, 1, 2, 3, 4, 5, 6, 7, 8]
Observed class IDs : [0, 1, 2, 3, 4, 5, 6, 7, 8]
✓ FinalTarget and FinalTargetName are fully consistent.
✓ Original Target column preserved unchanged.

[FINAL TARGET DISTRIBUTION]

   Final Class ID   Final Class    Count  Percentage
0               0        BENIGN  2273097   80.300366
1               1          DDoS   128027    4.522735
2               2     Port Scan   158930    5.614427
3               3   Brute Force    13835    0.488741
4               4           Bot     1966    0.069452
5               5    Web Attack     2180    0.077012
6               6  Infiltration       36    0.001272
7               7           DoS   252661    8.925607
8               8    Heartbleed       11    0.000389

✓ Final class IDs match Section 4.3.3.
✓ Final class counts match Section 4.3.3.

[ORIGINAL → FINAL TARGET TRACEABILITY]

         Target FinalTargetName  FinalTarget
0             0          BENIGN            0
2151570       1             Bot            4
2623881       2            DDoS            1
331033        3             DoS            7
74860         4             DoS            7
69275         5             DoS            7
6558          6             DoS            7
704050        7     Brute Force            3
597130        8      Heartbleed            8
1375361       9    Infiltration            6
2319994      10       Port Scan            2
854692       11     Brute Force            3
1151249      12      Web Attack            5
1228905      13      Web Attack            5
1210746      14      Web Attack            5

========================================================================
FINAL CLASS-ID CREATION SUMMARY
========================================================================
✓ FinalTarget created
✓ FinalTargetName created
✓ 15 original classes consolidated into 9 final classes
✓ No unmapped rows
✓ No unexpected final class IDs
✓ All nine final classes represented
✓ Final distribution matches Section 4.3.3
✓ Original Target column preserved
✓ No feature values modified

The Stage-1 dataframe now contains both the original
15-class target and the final 9-class attack-family target.
========================================================================

### 4.3.5 Analyze Final Class Distribution

The final nine-class target distribution is analyzed before any resampling,
class weighting, or other imbalance-handling strategy is applied.

This analysis quantifies the degree of class imbalance and identifies classes
with limited empirical support. The results are used to guide the subsequent
model-specific imbalance experiments rather than selecting a balancing
technique solely from the class frequencies.

The analysis includes:

- absolute sample count for each final class,
- percentage representation of each class,
- majority-to-minority class ratio,
- attack-to-BENIGN distribution,
- relative support of the minority classes,
- and identification of classes requiring special consideration during
  model evaluation.

No samples are removed, duplicated, synthesized, or reweighted in this
subsection.

The resulting distribution represents the original empirical distribution
that will be preserved for the independent evaluation set.

In [8]:
# ============================================================
# 4.3.5 Analyze Final Class Distribution
# ============================================================

print("=" * 72)
print("4.3.5 — FINAL CLASS DISTRIBUTION ANALYSIS")
print("=" * 72)

# ------------------------------------------------------------
# 4.3.5.1 Build Complete Distribution Table
# ------------------------------------------------------------

class_distribution_analysis = (
    stage1_df["FinalTarget"]
    .value_counts()
    .sort_index()
    .rename("Count")
    .to_frame()
)

class_distribution_analysis.index.name = "Final Class ID"

class_distribution_analysis["Final Class"] = (
    class_distribution_analysis.index
    .map(id_to_name)
)

class_distribution_analysis["Percentage"] = (
    class_distribution_analysis["Count"]
    / len(stage1_df)
    * 100
)

# Reorder columns
class_distribution_analysis = (
    class_distribution_analysis[
        [
            "Final Class",
            "Count",
            "Percentage"
        ]
    ]
)

print("\n[FINAL CLASS DISTRIBUTION]")
display(
    class_distribution_analysis.style.format({
        "Count": "{:,.0f}",
        "Percentage": "{:.6f}%"
    })
)

# ------------------------------------------------------------
# 4.3.5.2 Majority and Minority Support
# ------------------------------------------------------------

majority_class_id = (
    class_distribution_analysis["Count"].idxmax()
)

minority_class_id = (
    class_distribution_analysis["Count"].idxmin()
)

majority_count = int(
    class_distribution_analysis.loc[
        majority_class_id, "Count"
    ]
)

minority_count = int(
    class_distribution_analysis.loc[
        minority_class_id, "Count"
    ]
)

majority_class_name = (
    class_distribution_analysis.loc[
        majority_class_id, "Final Class"
    ]
)

minority_class_name = (
    class_distribution_analysis.loc[
        minority_class_id, "Final Class"
    ]
)

majority_minority_ratio = (
    majority_count / minority_count
)

print("\n[CLASS SUPPORT]")
print(
    f"Majority class : {majority_class_name} "
    f"({majority_count:,} samples)"
)

print(
    f"Minority class : {minority_class_name} "
    f"({minority_count:,} samples)"
)

print(
    f"Majority/Minority ratio : "
    f"{majority_minority_ratio:,.2f}:1"
)

# ------------------------------------------------------------
# 4.3.5.3 Attack vs BENIGN Distribution
# ------------------------------------------------------------

benign_count = int(
    stage1_df["FinalTarget"]
    .eq(FINAL_CLASS_ID_MAPPING["BENIGN"])
    .sum()
)

attack_count = (
    len(stage1_df) - benign_count
)

benign_percentage = (
    benign_count / len(stage1_df) * 100
)

attack_percentage = (
    attack_count / len(stage1_df) * 100
)

print("\n[BENIGN VS ATTACK TRAFFIC]")
print(
    f"BENIGN traffic : {benign_count:,} "
    f"({benign_percentage:.6f}%)"
)

print(
    f"Attack traffic : {attack_count:,} "
    f"({attack_percentage:.6f}%)"
)

# ------------------------------------------------------------
# 4.3.5.4 Attack-Class Support Ranking
# ------------------------------------------------------------

attack_distribution = (
    class_distribution_analysis
    .drop(index=FINAL_CLASS_ID_MAPPING["BENIGN"])
    .sort_values("Count", ascending=False)
    .copy()
)

attack_distribution["Attack Rank by Support"] = range(
    1,
    len(attack_distribution) + 1
)

attack_distribution = (
    attack_distribution[
        [
            "Attack Rank by Support",
            "Final Class",
            "Count",
            "Percentage"
        ]
    ]
)

print("\n[ATTACK-CLASS SUPPORT RANKING]")
display(
    attack_distribution.style.format({
        "Count": "{:,.0f}",
        "Percentage": "{:.6f}%"
    })
)

# ------------------------------------------------------------
# 4.3.5.5 Minority-Support Assessment
# ------------------------------------------------------------

support_thresholds = {
    "Very Low (<50)": int(
        (class_distribution_analysis["Count"] < 50).sum()
    ),
    "Low (50–499)": int(
        (
            (class_distribution_analysis["Count"] >= 50)
            & (class_distribution_analysis["Count"] < 500)
        ).sum()
    ),
    "Moderate (500–4,999)": int(
        (
            (class_distribution_analysis["Count"] >= 500)
            & (class_distribution_analysis["Count"] < 5000)
        ).sum()
    ),
    "High (≥5,000)": int(
        (class_distribution_analysis["Count"] >= 5000).sum()
    ),
}

support_summary = pd.DataFrame({
    "Support Category": list(support_thresholds.keys()),
    "Number of Classes": list(support_thresholds.values())
})

print("\n[CLASS SUPPORT CATEGORIES]")
display(support_summary)

# ------------------------------------------------------------
# 4.3.5.6 Identify Low-Support Classes
# ------------------------------------------------------------

low_support_mask = (
    class_distribution_analysis["Count"] < 500
)

low_support_classes = (
    class_distribution_analysis.loc[
        low_support_mask,
        ["Final Class", "Count", "Percentage"]
    ]
    .sort_values("Count")
)

print("\n[LOW-SUPPORT CLASSES — <500 SAMPLES]")
display(
    low_support_classes.style.format({
        "Count": "{:,.0f}",
        "Percentage": "{:.6f}%"
    })
)

# ------------------------------------------------------------
# 4.3.5.7 Calculate Relative Support Against BENIGN
# ------------------------------------------------------------

class_distribution_analysis["BENIGN / Class Ratio"] = (
    benign_count
    / class_distribution_analysis["Count"]
)

relative_support = (
    class_distribution_analysis[
        [
            "Final Class",
            "Count",
            "Percentage",
            "BENIGN / Class Ratio"
        ]
    ]
)

print("\n[RELATIVE SUPPORT AGAINST BENIGN]")
display(
    relative_support.style.format({
        "Count": "{:,.0f}",
        "Percentage": "{:.6f}%",
        "BENIGN / Class Ratio": "{:,.2f}:1"
    })
)

# ------------------------------------------------------------
# 4.3.5.8 Distribution Integrity Checks
# ------------------------------------------------------------

total_distribution_count = int(
    class_distribution_analysis["Count"].sum()
)

total_distribution_percentage = (
    class_distribution_analysis["Percentage"].sum()
)

assert total_distribution_count == len(stage1_df), (
    "Final class counts do not sum to the total dataset size."
)

assert np.isclose(
    total_distribution_percentage,
    100.0,
    atol=1e-6
), (
    "Final class percentages do not sum to 100%."
)

assert (
    class_distribution_analysis.shape[0] == N_FINAL_CLASSES
), (
    "The final distribution does not contain all nine classes."
)

# ------------------------------------------------------------
# 4.3.5.9 Final Analytical Summary
# ------------------------------------------------------------

print("\n" + "=" * 72)
print("FINAL CLASS DISTRIBUTION SUMMARY")
print("=" * 72)

print(f"Total records              : {len(stage1_df):,}")
print(f"Final classes              : {N_FINAL_CLASSES}")
print(f"BENIGN records             : {benign_count:,}")
print(f"Attack records             : {attack_count:,}")
print(f"BENIGN percentage          : {benign_percentage:.6f}%")
print(f"Attack percentage          : {attack_percentage:.6f}%")
print(
    f"Majority class             : "
    f"{majority_class_name} ({majority_count:,})"
)
print(
    f"Minority class             : "
    f"{minority_class_name} ({minority_count:,})"
)
print(
    f"Majority/Minority ratio    : "
    f"{majority_minority_ratio:,.2f}:1"
)

print("\n[LOW-SUPPORT CLASSES]")
for class_id, row in low_support_classes.iterrows():
    print(
        f"  - {row['Final Class']}: "
        f"{int(row['Count']):,} samples "
        f"({row['Percentage']:.6f}%)"
    )

print("\n[VALIDATION]")
print("✓ Class counts account for all dataset records")
print("✓ Class percentages sum to 100%")
print("✓ All nine final classes are represented")
print("✓ No resampling or class weighting performed")
print("✓ Original empirical class distribution preserved")

print("\nThis section is analytical only.")
print("No samples have been added, removed, or reweighted.")

print("=" * 72)

========================================================================
4.3.5 — FINAL CLASS DISTRIBUTION ANALYSIS
========================================================================

[FINAL CLASS DISTRIBUTION]

[CLASS SUPPORT]
Majority class : BENIGN (2,273,097 samples)
Minority class : Heartbleed (11 samples)
Majority/Minority ratio : 206,645.18:1

[BENIGN VS ATTACK TRAFFIC]
BENIGN traffic : 2,273,097 (80.300366%)
Attack traffic : 557,646 (19.699634%)

[ATTACK-CLASS SUPPORT RANKING]

[CLASS SUPPORT CATEGORIES]

       Support Category  Number of Classes
0        Very Low (<50)                  2
1          Low (50–499)                  0
2  Moderate (500–4,999)                  2
3         High (≥5,000)                  5

[LOW-SUPPORT CLASSES — <500 SAMPLES]

[RELATIVE SUPPORT AGAINST BENIGN]

========================================================================
FINAL CLASS DISTRIBUTION SUMMARY
========================================================================
Total records              : 2,830,743
Final classes              : 9
BENIGN records             : 2,273,097
Attack records             : 557,646
BENIGN percentage          : 80.300366%
Attack percentage          : 19.699634%
Majority class             : BENIGN (2,273,097)
Minority class             : Heartbleed (11)
Majority/Minority ratio    : 206,645.18:1

[LOW-SUPPORT CLASSES]
  - Heartbleed: 11 samples (0.000389%)
  - Infiltration: 36 samples (0.001272%)

[VALIDATION]
✓ Class counts account for all dataset records
✓ Class percentages sum to 100%
✓ All nine final classes are represented
✓ No resampling or class weighting performed
✓ Original empirical class distribution preserved

This section is analytical only.
No samples have been added, removed, or reweighted.
========================================================================

### 4.3.6 Persist Taxonomy Definition

The validated final target taxonomy and its supporting statistics are persisted
as reusable project artifacts.

The taxonomy artifacts serve as the authoritative label-definition contract
for all subsequent preprocessing and modeling notebooks. This prevents
independent redefinition of class IDs across the Random Forest, LSTM, ensemble,
calibration, explainability, and evaluation stages.

The following artifacts are generated:

1. `taxonomy_metadata.json`
   - final class IDs and names,
   - original CICIDS-2017 label mapping,
   - original-label-to-family mapping,
   - final class distribution,
   - class-support statistics,
   - taxonomy rationale,
   - dataset and preprocessing metadata.

2. `taxonomy_mapping.csv`
   - complete mapping from the 15 original target classes to the nine final
     classification classes.

3. `final_class_distribution.csv`
   - empirical class counts and percentages before any resampling, class
     weighting, or other imbalance-handling operation.

The persisted taxonomy explicitly documents the decision to represent the
classification task as eight attack families plus BENIGN:

- DDoS
- Port Scan
- Brute Force
- Bot
- Web Attack
- Infiltration
- DoS
- Heartbleed
- BENIGN

The original CICIDS-2017 target representation remains available through the
original `Target` column and is not replaced by a persisted transformed
dataset at this stage.

These artifacts provide both computational reproducibility and traceability
for the methodology and experimental design reported in the research paper.

In [9]:
# ============================================================
# 4.3.6 Persist Taxonomy Definition
# ============================================================

print("=" * 72)
print("4.3.6 — PERSIST TAXONOMY DEFINITION")
print("=" * 72)

# ------------------------------------------------------------
# 4.3.6.1 Define Taxonomy Output Directory
# ------------------------------------------------------------

TAXONOMY_DIR = (
    MODEL_PREPARATION_V2_DIR / "taxonomy"
)

TAXONOMY_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("\n[TAXONOMY OUTPUT DIRECTORY]")
print(f"Directory : {TAXONOMY_DIR}")

# ------------------------------------------------------------
# 4.3.6.2 Persist Original → Final Taxonomy Mapping
# ------------------------------------------------------------

taxonomy_mapping_output = (
    taxonomy_mapping_table[
        [
            "Original Target ID",
            "Original Label",
            "Final Attack Family",
            "Final Class ID"
        ]
    ]
    .sort_values("Original Target ID")
    .reset_index(drop=True)
)

taxonomy_mapping_output.to_csv(
    TAXONOMY_DIR / "taxonomy_mapping.csv",
    index=False
)

# ------------------------------------------------------------
# 4.3.6.3 Persist Final Class Distribution
# ------------------------------------------------------------

final_distribution_output = (
    final_class_distribution[
        [
            "Final Class ID",
            "Final Class",
            "Count",
            "Percentage"
        ]
    ]
    .sort_values("Final Class ID")
    .reset_index(drop=True)
)

final_distribution_output.to_csv(
    TAXONOMY_DIR / "final_class_distribution.csv",
    index=False
)

# ------------------------------------------------------------
# 4.3.6.4 Prepare Taxonomy Metadata
# ------------------------------------------------------------

taxonomy_metadata = {
    "artifact_name": "CICIDS2017_Final_Taxonomy",
    "artifact_version": "v2",

    "notebook": {
        "number": "04",
        "section": "4.3",
        "title": "Final Target Taxonomy"
    },

    "dataset": {
        "name": "CICIDS2017",
        "records": int(len(stage1_df)),
        "original_target_column": TARGET_COLUMN,
        "original_class_count": 15,
        "final_class_count": 9,
        "input_feature_count": 63
    },

    "taxonomy_definition": {
        "classification_type": "Multi-class",
        "attack_family_count": 8,
        "normal_traffic_class": "BENIGN",
        "total_final_classes": 9
    },

    "final_classes": {
        str(row["Final Class ID"]): str(row["Final Class"])
        for _, row in final_distribution_output.iterrows()
    },

    "original_to_final_mapping": {
        str(row["Original Target ID"]): {
            "original_label": str(row["Original Label"]),
            "final_attack_family": str(
                row["Final Attack Family"]
            ),
            "final_class_id": int(
                row["Final Class ID"]
            )
        }
        for _, row in taxonomy_mapping_output.iterrows()
    },

    "class_distribution": {
        str(row["Final Class ID"]): {
            "class_name": str(row["Final Class"]),
            "count": int(row["Count"]),
            "percentage": float(row["Percentage"])
        }
        for _, row in final_distribution_output.iterrows()
    },

    "taxonomy_rationale": {
        "BENIGN":
            "Retained as the dedicated normal-traffic class.",

        "DDoS":
            "Retained as a dedicated distributed denial-of-service "
            "attack family.",

        "Port Scan":
            "Retained as a dedicated network reconnaissance "
            "attack family.",

        "Brute Force":
            "FTP-Patator and SSH-Patator are grouped as a common "
            "service-level brute-force attack family.",

        "Bot":
            "Retained as a dedicated bot-related attack family.",

        "Web Attack":
            "Web Attack - Brute Force, Web Attack - XSS, and "
            "Web Attack - SQL Injection are grouped as a common "
            "web-application attack family.",

        "Infiltration":
            "Retained as a dedicated attack family.",

        "DoS":
            "DoS Hulk, DoS GoldenEye, DoS Slowloris, and "
            "DoS Slowhttptest are grouped as denial-of-service "
            "variants.",

        "Heartbleed":
            "Retained as a dedicated attack family despite its "
            "extremely limited empirical support."
    },

    "support_analysis": {
        "majority_class": "BENIGN",
        "majority_class_count": 2273097,
        "minority_class": "Heartbleed",
        "minority_class_count": 11,
        "majority_to_minority_ratio": 206645.18,
        "low_support_classes": {
            "Infiltration": 36,
            "Heartbleed": 11
        }
    },

    "processing_status": {
        "resampling_performed": False,
        "class_weighting_performed": False,
        "train_test_split_performed": False,
        "feature_selection_performed": False,
        "scaling_performed": False,
        "data_balancing_performed": False,
        "original_target_modified": False
    },

    "reproducibility": {
        "random_seed": int(RANDOM_SEED)
    }
}

# ------------------------------------------------------------
# 4.3.6.5 Persist Taxonomy Metadata
# ------------------------------------------------------------

with open(
    TAXONOMY_DIR / "taxonomy_metadata.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        taxonomy_metadata,
        f,
        indent=4,
        ensure_ascii=False
    )

# ------------------------------------------------------------
# 4.3.6.6 Reload Persisted Artifacts
# ------------------------------------------------------------

with open(
    TAXONOMY_DIR / "taxonomy_metadata.json",
    "r",
    encoding="utf-8"
) as f:

    persisted_taxonomy = json.load(f)

persisted_mapping = pd.read_csv(
    TAXONOMY_DIR / "taxonomy_mapping.csv"
)

persisted_distribution = pd.read_csv(
    TAXONOMY_DIR / "final_class_distribution.csv"
)

# ------------------------------------------------------------
# 4.3.6.7 Validate Persisted Artifacts
# ------------------------------------------------------------

assert len(persisted_mapping) == 15

assert len(persisted_distribution) == 9

assert (
    persisted_distribution["Count"].sum()
    == len(stage1_df)
)

assert (
    persisted_taxonomy["dataset"]["original_class_count"]
    == 15
)

assert (
    persisted_taxonomy["dataset"]["final_class_count"]
    == 9
)

assert (
    persisted_taxonomy["taxonomy_definition"]
    ["attack_family_count"]
    == 8
)

assert (
    persisted_taxonomy["taxonomy_definition"]
    ["normal_traffic_class"]
    == "BENIGN"
)

# ------------------------------------------------------------
# 4.3.6.8 Display Persisted Artifacts
# ------------------------------------------------------------

print("\n[PERSISTED TAXONOMY ARTIFACTS]")

artifact_summary = pd.DataFrame({
    "Artifact": [
        "taxonomy_mapping.csv",
        "final_class_distribution.csv",
        "taxonomy_metadata.json"
    ],
    "Purpose": [
        "Complete 15 → 9 original-label mapping",
        "Final empirical class distribution",
        "Authoritative taxonomy and methodology metadata"
    ],
    "Status": [
        "Saved",
        "Saved",
        "Saved"
    ]
})

display(artifact_summary)

print("\n[ARTIFACT PATHS]")

print(
    f"✓ {TAXONOMY_DIR / 'taxonomy_mapping.csv'}"
)

print(
    f"✓ {TAXONOMY_DIR / 'final_class_distribution.csv'}"
)

print(
    f"✓ {TAXONOMY_DIR / 'taxonomy_metadata.json'}"
)

# ------------------------------------------------------------
# 4.3.6.9 Final Taxonomy Checkpoint
# ------------------------------------------------------------

print("\n" + "=" * 72)
print("TAXONOMY PERSISTENCE CHECKPOINT")
print("=" * 72)

print("✓ 9-class taxonomy persisted")
print("✓ Original 15-class mapping persisted")
print("✓ Original → final family mapping persisted")
print("✓ Final class distribution persisted")
print("✓ Taxonomy rationale persisted")
print("✓ Class-support statistics persisted")
print("✓ Reproducibility information persisted")
print("✓ Persisted artifacts successfully reloaded")
print("✓ Artifact validation completed successfully")

print("\n[PROCESSING STATUS]")

print("✓ No resampling performed")
print("✓ No class weighting performed")
print("✓ No train/test split performed")
print("✓ No feature selection performed")
print("✓ No scaling performed")
print("✓ Original Stage-1 dataset remains unchanged")

print("\n" + "=" * 72)
print("4.3 FINAL TARGET TAXONOMY — COMPLETED SUCCESSFULLY")
print("=" * 72)

========================================================================
4.3.6 — PERSIST TAXONOMY DEFINITION
========================================================================

[TAXONOMY OUTPUT DIRECTORY]
Directory : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/taxonomy

[PERSISTED TAXONOMY ARTIFACTS]

,Artifact,Purpose,Status
0,taxonomy_mapping.csv,Complete 15 → 9 original-label mapping,Saved
1,final_class_distribution.csv,Final empirical class distribution,Saved
2,taxonomy_metadata.json,Authoritative taxonomy and methodology metadata,Saved

[ARTIFACT PATHS]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/taxonomy/taxonomy_mapping.csv
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/taxonomy/final_class_distribution.csv
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/taxonomy/taxonomy_metadata.json

========================================================================
TAXONOMY PERSISTENCE CHECKPOINT
========================================================================
✓ 9-class taxonomy persisted
✓ Original 15-class mapping persisted
✓ Original → final family mapping persisted
✓ Final class distribution persisted
✓ Taxonomy rationale persisted
✓ Class-support statistics persisted
✓ Reproducibility information persisted
✓ Persisted artifacts successfully reloaded
✓ Artifact validation completed successfully

[PROCESSING STATUS]
✓ No resampling performed
✓ No class weighting performed
✓ No train/test split performed
✓ No feature selection performed
✓ No scaling performed
✓ Original Stage-1 dataset remains unchanged

========================================================================
4.3 FINAL TARGET TAXONOMY — COMPLETED SUCCESSFULLY
========================================================================

In [10]:
print("=" * 60)
print("TAXONOMY RECOVERY CHECK")
print("=" * 60)

print("\nRequired columns:")
print("FinalTarget      :", "FinalTarget" in stage1_df.columns)
print("FinalTargetName  :", "FinalTargetName" in stage1_df.columns)

print("\nFinal classes:")
print(
    stage1_df["FinalTargetName"]
    .value_counts()
    .sort_index()
)

print("\nUnique FinalTarget values:")
print(
    sorted(stage1_df["FinalTarget"].unique())
)

============================================================
TAXONOMY RECOVERY CHECK
============================================================

Required columns:
FinalTarget      : True
FinalTargetName  : True

Final classes:
FinalTargetName
BENIGN          2273097
Bot                1966
Brute Force       13835
DDoS             128027
DoS              252661
Heartbleed           11
Infiltration         36
Port Scan        158930
Web Attack         2180
Name: count, dtype: int64

Unique FinalTarget values:
[np.int8(0), np.int8(1), np.int8(2), np.int8(3), np.int8(4), np.int8(5), np.int8(6), np.int8(7), np.int8(8)]

In [11]:
# ============================================================
# N04 — Lightweight Partition Artifact Recovery
# ============================================================

from pathlib import Path
import numpy as np
import json

print("=" * 72)
print("LIGHTWEIGHT PARTITION ARTIFACT RECOVERY")
print("=" * 72)

# ------------------------------------------------------------
# Existing N04 output directory
# ------------------------------------------------------------

PARTITION_AUDIT_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "duplicate_leakage_audit"
)

print("\n[RECOVERY DIRECTORY]")
print(f"Output directory : {PARTITION_AUDIT_DIR}")

if not PARTITION_AUDIT_DIR.exists():
    raise FileNotFoundError(
        f"Expected partition artifact directory not found:\n"
        f"{PARTITION_AUDIT_DIR}"
    )

print("✓ Partition artifact directory exists")

# ------------------------------------------------------------
# Required persisted partition indices
# ------------------------------------------------------------

REQUIRED_PARTITION_ARTIFACTS = {
    "development_indices": (
        PARTITION_AUDIT_DIR / "development_indices.npy"
    ),
    "test_indices": (
        PARTITION_AUDIT_DIR / "test_indices.npy"
    ),
    "training_indices": (
        PARTITION_AUDIT_DIR / "training_indices.npy"
    ),
    "validation_indices": (
        PARTITION_AUDIT_DIR / "validation_indices.npy"
    ),
}

print("\n[PERSISTED PARTITION ARTIFACTS]")

for artifact_name, artifact_path in REQUIRED_PARTITION_ARTIFACTS.items():

    if not artifact_path.exists():
        raise FileNotFoundError(
            f"Required artifact missing:\n{artifact_path}"
        )

    print(f"✓ {artifact_name}: {artifact_path.name}")

# ------------------------------------------------------------
# Load only index arrays
# ------------------------------------------------------------

development_indices = np.load(
    REQUIRED_PARTITION_ARTIFACTS["development_indices"]
)

test_indices = np.load(
    REQUIRED_PARTITION_ARTIFACTS["test_indices"]
)

training_indices = np.load(
    REQUIRED_PARTITION_ARTIFACTS["training_indices"]
)

validation_indices = np.load(
    REQUIRED_PARTITION_ARTIFACTS["validation_indices"]
)

# ------------------------------------------------------------
# Partition size validation
# ------------------------------------------------------------

print("\n[PARTITION SIZES]")

print(
    f"Development rows : "
    f"{len(development_indices):,}"
)

print(
    f"Training rows    : "
    f"{len(training_indices):,}"
)

print(
    f"Validation rows  : "
    f"{len(validation_indices):,}"
)

print(
    f"Test rows        : "
    f"{len(test_indices):,}"
)

# ------------------------------------------------------------
# Index integrity
# ------------------------------------------------------------

all_indices = np.concatenate([
    development_indices,
    test_indices
])

if len(np.unique(all_indices)) != len(stage1_df):
    raise ValueError(
        "Persisted Development/Test indices do not "
        "cover Stage-1 exactly once."
    )

if set(training_indices).intersection(
    set(validation_indices)
):
    raise ValueError(
        "Training and Validation indices overlap."
    )

if set(training_indices).intersection(
    set(test_indices)
):
    raise ValueError(
        "Training and Test indices overlap."
    )

if set(validation_indices).intersection(
    set(test_indices)
):
    raise ValueError(
        "Validation and Test indices overlap."
    )

if not set(training_indices).union(
    set(validation_indices)
) == set(development_indices):
    raise ValueError(
        "Training + Validation do not reconstruct "
        "the persisted Development partition."
    )

print("\n[RECOVERY VALIDATION]")

print("✓ Development/Test indices recovered")
print("✓ Training/Validation indices recovered")
print("✓ Development + Test cover Stage-1 exactly once")
print("✓ Training and Validation are mutually exclusive")
print("✓ Training and Test are mutually exclusive")
print("✓ Validation and Test are mutually exclusive")
print("✓ Training + Validation reconstruct Development")

print("\n[MEMORY POLICY]")
print("✓ No feature matrix materialized")
print("✓ No dataset copy created")
print("✓ No partition recreated")
print("✓ No model fitting performed")
print("✓ No preprocessing performed")

print("\n" + "=" * 72)
print("Partition state recovered without recomputing 4.4.5.")
print("=" * 72)

========================================================================
LIGHTWEIGHT PARTITION ARTIFACT RECOVERY
========================================================================

[RECOVERY DIRECTORY]
Output directory : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/duplicate_leakage_audit
✓ Partition artifact directory exists

[PERSISTED PARTITION ARTIFACTS]
✓ development_indices: development_indices.npy
✓ test_indices: test_indices.npy
✓ training_indices: training_indices.npy
✓ validation_indices: validation_indices.npy

[PARTITION SIZES]
Development rows : 2,265,233
Training rows    : 1,814,018
Validation rows  : 451,215
Test rows        : 565,510

[RECOVERY VALIDATION]
✓ Development/Test indices recovered
✓ Training/Validation indices recovered
✓ Development + Test cover Stage-1 exactly once
✓ Training and Validation are mutually exclusive
✓ Training and Test are mutually exclusive
✓ Validation and Test are mutually exclusive
✓ Training + Validation reconstruct Development

[MEMORY POLICY]
✓ No feature matrix materialized
✓ No dataset copy created
✓ No partition recreated
✓ No model fitting performed
✓ No preprocessing performed

========================================================================
Partition state recovered without recomputing 4.4.5.
========================================================================

# 4.4 Duplicate & Leakage Audit

This section investigates duplicate observations and potential data leakage within the Stage-1 feature-engineered dataset before any development/test partitioning is performed.

The audit is designed to distinguish exact row duplicates, duplicate feature vectors, and feature-level label conflicts. Because identical observations can otherwise appear across different partitions and lead to overly optimistic evaluation, duplicate groups will be explicitly identified before the leakage-controlled partitioning stage.

No observations are removed, resampled, transformed, or reweighted during this section. The purpose is strictly to quantify duplicate structure, identify potential leakage risks, construct reproducible duplicate groups, and establish the rules that will govern the subsequent dataset partition.

The audit follows four principles:

1. Preserve the original Stage-1 dataset until duplicate structure has been fully assessed.
2. Treat the complete feature vector as the primary unit for feature-level leakage analysis.
3. Distinguish repeated observations from genuine cross-label conflicts.
4. Ensure that identical feature-vector groups are not allowed to cross the independent evaluation boundary.

The resulting audit artifacts will provide a reproducible record of duplicate structure and leakage-control decisions for subsequent model preparation and research reporting.

# 4.4.1 Duplicate Audit Configuration

This subsection establishes the configuration and definitions used throughout the duplicate and leakage audit.

Three observation levels are considered:

- **Exact row duplicate:** two or more observations are identical across the complete stored row.
- **Feature-vector duplicate:** two or more observations have identical values across all model input features, regardless of their target labels.
- **Cross-label feature conflict:** an identical feature vector is associated with more than one target label.

The audit uses the 63 Stage-1 engineered input features as the primary feature-vector representation. The original `Target` column and the final taxonomy columns are retained for label-consistency analysis but are not included in the feature-vector identity.

No data modification is performed in this subsection.

In [ ]:
# ============================================================
# 4.4.1 Duplicate Audit Configuration
# ============================================================

import hashlib
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 4.4.1.1 Audit Scope
# ------------------------------------------------------------

AUDIT_TARGET_COLUMN = "Target"
AUDIT_FINAL_TARGET_COLUMN = "FinalTarget"
AUDIT_FINAL_NAME_COLUMN = "FinalTargetName"

# The Stage-1 model representation contains 63 engineered
# numerical input features. Target-related columns are excluded
# from feature-vector identity.
AUDIT_EXCLUDED_COLUMNS = {
    AUDIT_TARGET_COLUMN,
    AUDIT_FINAL_TARGET_COLUMN,
    AUDIT_FINAL_NAME_COLUMN,
}

AUDIT_FEATURE_COLUMNS = [
    column
    for column in stage1_df.columns
    if column not in AUDIT_EXCLUDED_COLUMNS
]

# ------------------------------------------------------------
# 4.4.1.2 Duplicate Definitions
# ------------------------------------------------------------

EXACT_ROW_DUPLICATE_LEVEL = "complete_row"
FEATURE_VECTOR_DUPLICATE_LEVEL = "feature_vector"
CROSS_LABEL_CONFLICT_LEVEL = "feature_vector_with_multiple_labels"

# Cryptographic hash used later for deterministic feature-vector
# group construction.
DUPLICATE_HASH_ALGORITHM = "sha256"

# ------------------------------------------------------------
# 4.4.1.3 Structural Configuration Validation
# ------------------------------------------------------------

if AUDIT_TARGET_COLUMN not in stage1_df.columns:
    raise KeyError(
        f"Required target column '{AUDIT_TARGET_COLUMN}' "
        "was not found in the Stage-1 dataframe."
    )

missing_final_columns = [
    column
    for column in (
        AUDIT_FINAL_TARGET_COLUMN,
        AUDIT_FINAL_NAME_COLUMN,
    )
    if column not in stage1_df.columns
]

if missing_final_columns:
    raise KeyError(
        "Required taxonomy columns are missing from the Stage-1 "
        f"dataframe: {missing_final_columns}"
    )

if len(AUDIT_FEATURE_COLUMNS) != 63:
    raise ValueError(
        "Unexpected number of audit feature columns. "
        f"Expected 63, found {len(AUDIT_FEATURE_COLUMNS)}."
    )

if not all(
    pd.api.types.is_numeric_dtype(stage1_df[column])
    for column in AUDIT_FEATURE_COLUMNS
):
    non_numeric_audit_features = [
        column
        for column in AUDIT_FEATURE_COLUMNS
        if not pd.api.types.is_numeric_dtype(stage1_df[column])
    ]

    raise TypeError(
        "Non-numeric feature columns detected in the audit feature "
        f"representation: {non_numeric_audit_features}"
    )

# ------------------------------------------------------------
# 4.4.1.4 Duplicate Audit Configuration Summary
# ------------------------------------------------------------

print("=" * 72)
print("4.4.1 — DUPLICATE AUDIT CONFIGURATION")
print("=" * 72)

print("\n[AUDIT SCOPE]")
print(f"Dataset rows              : {len(stage1_df):,}")
print(f"Feature columns           : {len(AUDIT_FEATURE_COLUMNS)}")
print(f"Original target column    : {AUDIT_TARGET_COLUMN}")
print(f"Final target column       : {AUDIT_FINAL_TARGET_COLUMN}")
print(f"Final class-name column   : {AUDIT_FINAL_NAME_COLUMN}")

print("\n[DUPLICATE DEFINITIONS]")
print(f"Exact row level           : {EXACT_ROW_DUPLICATE_LEVEL}")
print(f"Feature-vector level      : {FEATURE_VECTOR_DUPLICATE_LEVEL}")
print(f"Conflict level            : {CROSS_LABEL_CONFLICT_LEVEL}")

print("\n[FEATURE-VECTOR IDENTITY]")
print("✓ All 63 engineered features included")
print("✓ Original Target excluded from feature identity")
print("✓ FinalTarget excluded from feature identity")
print("✓ FinalTargetName excluded from feature identity")
print(f"✓ Hash algorithm reserved : {DUPLICATE_HASH_ALGORITHM}")

print("\n[PROCESSING POLICY]")
print("✓ No rows removed")
print("✓ No rows added")
print("✓ No labels modified")
print("✓ No feature values modified")
print("✓ No resampling performed")
print("✓ No train/test partition performed")
print("✓ No scaling performed")

print("\n[VALIDATION]")
print("✓ Duplicate audit configuration initialized successfully")
print("✓ Stage-1 feature representation validated")
print("✓ Taxonomy columns available for label-conflict analysis")

print("\n" + "=" * 72)
print("4.4.1 configuration completed successfully.")
print("=" * 72)

========================================================================
4.4.1 — DUPLICATE AUDIT CONFIGURATION
========================================================================

[AUDIT SCOPE]
Dataset rows              : 2,830,743
Feature columns           : 63
Original target column    : Target
Final target column       : FinalTarget
Final class-name column   : FinalTargetName

[DUPLICATE DEFINITIONS]
Exact row level           : complete_row
Feature-vector level      : feature_vector
Conflict level            : feature_vector_with_multiple_labels

[FEATURE-VECTOR IDENTITY]
✓ All 63 engineered features included
✓ Original Target excluded from feature identity
✓ FinalTarget excluded from feature identity
✓ FinalTargetName excluded from feature identity
✓ Hash algorithm reserved : sha256

[PROCESSING POLICY]
✓ No rows removed
✓ No rows added
✓ No labels modified
✓ No feature values modified
✓ No resampling performed
✓ No train/test partition performed
✓ No scaling performed

[VALIDATION]
✓ Duplicate audit configuration initialized successfully
✓ Stage-1 feature representation validated
✓ Taxonomy columns available for label-conflict analysis

========================================================================
4.4.1 configuration completed successfully.
========================================================================

# 4.4.2 Exact Row Duplicate Analysis

This subsection quantifies exact duplicate observations present in the Stage-1 dataset.

An exact duplicate is defined as an observation whose complete stored representation is identical to another observation, including the original target label and the engineered feature values. The derived final taxonomy columns are deterministic representations of the original target and are therefore not used as independent evidence of duplication.

The analysis reports:

- total number of exact duplicate rows,
- number of unique duplicated observations,
- number of duplicate groups,
- largest duplicate-group size,
- number and proportion of records participating in duplicate groups,
- whether exact duplicate groups contain conflicting original target labels.

Exact duplicates are retained at this stage. Their presence is documented because randomly distributing members of the same duplicate group across development and test partitions can result in information leakage and overly optimistic evaluation.

No rows, labels, or feature values are modified in this subsection.

In [ ]:
# ============================================================
# 4.4.2 Exact Row Duplicate Analysis
# ============================================================

# ------------------------------------------------------------
# 4.4.2.1 Define Exact Observation Representation
# ------------------------------------------------------------

# Exact observation identity is based on all Stage-1 model
# features together with the original target label.
#
# FinalTarget and FinalTargetName are deterministic derivatives
# of Target and are therefore excluded from the identity.

EXACT_DUPLICATE_COLUMNS = (
    AUDIT_FEATURE_COLUMNS + [AUDIT_TARGET_COLUMN]
)

# ------------------------------------------------------------
# 4.4.2.2 Validate Duplicate Representation
# ------------------------------------------------------------

if len(EXACT_DUPLICATE_COLUMNS) != 64:
    raise ValueError(
        "Unexpected exact-duplicate representation. "
        f"Expected 64 columns, found {len(EXACT_DUPLICATE_COLUMNS)}."
    )

if not stage1_df[EXACT_DUPLICATE_COLUMNS].notna().all().all():
    raise ValueError(
        "Missing values detected in the exact-duplicate representation."
    )

# ------------------------------------------------------------
# 4.4.2.3 Identify Exact Duplicate Groups
# ------------------------------------------------------------

print("=" * 72)
print("4.4.2 — EXACT ROW DUPLICATE ANALYSIS")
print("=" * 72)

print("\nAnalyzing exact duplicate observations...")
print(
    f"Observation representation : "
    f"{len(EXACT_DUPLICATE_COLUMNS)} columns "
    "(63 features + Target)"
)

# duplicated(..., keep=False) marks every member of a duplicate
# group rather than only the repeated occurrences.
exact_duplicate_mask = stage1_df[
    EXACT_DUPLICATE_COLUMNS
].duplicated(
    keep=False
)

exact_duplicate_rows = int(exact_duplicate_mask.sum())

# Number of unique observations that occur more than once.
exact_duplicate_unique_rows = int(
    stage1_df.loc[
        exact_duplicate_mask,
        EXACT_DUPLICATE_COLUMNS
    ].drop_duplicates().shape[0]
)

# Number of duplicate groups.
exact_duplicate_group_sizes = (
    stage1_df.loc[
        exact_duplicate_mask,
        EXACT_DUPLICATE_COLUMNS
    ]
    .value_counts(sort=True)
)

exact_duplicate_group_count = int(
    len(exact_duplicate_group_sizes)
)

largest_exact_duplicate_group = int(
    exact_duplicate_group_sizes.max()
) if exact_duplicate_group_count > 0 else 1

# Number of records that are additional copies beyond the first
# occurrence of each unique observation.
exact_duplicate_extra_rows = int(
    exact_duplicate_rows - exact_duplicate_unique_rows
)

dataset_rows = len(stage1_df)

exact_duplicate_row_percentage = (
    exact_duplicate_rows / dataset_rows * 100
)

exact_duplicate_extra_percentage = (
    exact_duplicate_extra_rows / dataset_rows * 100
)

# ------------------------------------------------------------
# 4.4.2.4 Analyze Duplicate Group Distribution
# ------------------------------------------------------------

if exact_duplicate_group_count > 0:

    duplicate_group_distribution = (
        exact_duplicate_group_sizes
        .value_counts()
        .sort_index()
        .rename_axis("Duplicate_Group_Size")
        .reset_index(name="Number_of_Groups")
    )

    duplicate_group_distribution[
        "Rows_Represented"
    ] = (
        duplicate_group_distribution["Duplicate_Group_Size"]
        * duplicate_group_distribution["Number_of_Groups"]
    )

else:

    duplicate_group_distribution = pd.DataFrame(
        columns=[
            "Duplicate_Group_Size",
            "Number_of_Groups",
            "Rows_Represented"
        ]
    )

# ------------------------------------------------------------
# 4.4.2.5 Check Target Consistency Within Exact Groups
# ------------------------------------------------------------

# Because Target is part of the exact-observation identity,
# a true exact duplicate group should necessarily have one
# original target value. This check explicitly verifies that
# assumption rather than relying on it implicitly.

duplicate_target_consistency = (
    stage1_df.loc[
        exact_duplicate_mask,
        EXACT_DUPLICATE_COLUMNS
    ]
    .groupby(EXACT_DUPLICATE_COLUMNS[:-1], sort=False)[
        AUDIT_TARGET_COLUMN
    ]
    .nunique()
)

cross_label_exact_groups = int(
    (duplicate_target_consistency > 1).sum()
)

# ------------------------------------------------------------
# 4.4.2.6 Display Results
# ------------------------------------------------------------

print("\n[EXACT DUPLICATE SUMMARY]")

print(
    f"Total dataset rows             : "
    f"{dataset_rows:,}"
)

print(
    f"Rows participating in duplicates: "
    f"{exact_duplicate_rows:,}"
)

print(
    f"Unique duplicated observations  : "
    f"{exact_duplicate_unique_rows:,}"
)

print(
    f"Additional duplicate copies     : "
    f"{exact_duplicate_extra_rows:,}"
)

print(
    f"Duplicate groups                : "
    f"{exact_duplicate_group_count:,}"
)

print(
    f"Largest duplicate group        : "
    f"{largest_exact_duplicate_group:,} rows"
)

print(
    f"Rows in duplicate groups       : "
    f"{exact_duplicate_row_percentage:.6f}%"
)

print(
    f"Additional duplicate copies    : "
    f"{exact_duplicate_extra_percentage:.6f}%"
)

print("\n[DUPLICATE GROUP DISTRIBUTION]")

if not duplicate_group_distribution.empty:
    print(
        duplicate_group_distribution.to_string(
            index=False
        )
    )
else:
    print("No duplicate groups detected.")

print("\n[TARGET CONSISTENCY]")

print(
    "Exact duplicate groups include Target in their "
    "identity definition."
)

print(
    "✓ Every exact duplicate group is therefore "
    "internally label-consistent by definition."
)

print(
    "→ Feature-vector label-conflict analysis is "
    "performed separately in Section 4.4.3."
)

# ------------------------------------------------------------
# 4.4.2.7 Validation Assertions
# ------------------------------------------------------------

if exact_duplicate_rows < 0:
    raise AssertionError(
        "Invalid duplicate-row count."
    )

if exact_duplicate_unique_rows > exact_duplicate_rows:
    raise AssertionError(
        "Unique duplicated observations exceed "
        "duplicate-participating rows."
    )

if exact_duplicate_extra_rows < 0:
    raise AssertionError(
        "Invalid additional-duplicate count."
    )

if exact_duplicate_group_count > 0:
    if largest_exact_duplicate_group < 2:
        raise AssertionError(
            "Duplicate group size must be at least 2."
        )

print("\n[VALIDATION]")

print(
    "✓ Exact duplicate representation validated"
)

print(
    "✓ Duplicate groups identified deterministically"
)

print(
    "✓ Duplicate-group size statistics computed"
)

print(
    "✓ Target consistency checked"
)

print(
    "✓ No rows removed"
)

print(
    "✓ No feature values modified"
)

print(
    "✓ No labels modified"
)

print("\n" + "=" * 72)
print("4.4.2 exact row duplicate analysis completed.")
print("=" * 72)

========================================================================
4.4.2 — EXACT ROW DUPLICATE ANALYSIS
========================================================================

Analyzing exact duplicate observations...
Observation representation : 64 columns (63 features + Target)

[EXACT DUPLICATE SUMMARY]
Total dataset rows             : 2,830,743
Rows participating in duplicates: 457,837
Unique duplicated observations  : 102,066
Additional duplicate copies     : 355,771
Duplicate groups                : 102,066
Largest duplicate group        : 16,220 rows
Rows in duplicate groups       : 16.173740%
Additional duplicate copies    : 12.568114%

[DUPLICATE GROUP DISTRIBUTION]
 Duplicate_Group_Size  Number_of_Groups  Rows_Represented
                    2             59712            119424
                    3             17500             52500
                    4              7612             30448
                    5              4503             22515
                    6              3034             18204
                    7              2255             15785
                    8              1735             13880
                    9              1295             11655
                   10               861              8610
                   11               628              6908
                   12               437              5244
                   13               320              4160
                   14               215              3010
                   15               142              2130
                   16               107              1712
                   17                94              1598
                   18               101              1818
                   19                72              1368
                   20                78              1560
                   21                53              1113
                   22                66              1452
                   23                59              1357
                   24                42              1008
                   25                57              1425
                   26                37               962
                   27                41              1107
                   28                48              1344
                   29                34               986
                   30                32               960
                   31                32               992
                   32                35              1120
                   33                27               891
                   34                33              1122
                   35                30              1050
                   36                30              1080
                   37                22               814
                   38                19               722
                   39                19               741
                   40                25              1000
                   41                23               943
                   42                25              1050
                   43                24              1032
                   44                20               880
                   45                18               810
                   46                16               736
                   47                11               517
                   48                 8               384
                   49                10               490
                   50                11               550
                   51                13               663
                   52                11               572
                   53                10               530
                   54                12               648
                   55                 9               495
                   56                 8               448
                   57                 7               399
                   58                10               580
                   59                 6               354
                   60                 8               480
                   61                 7               427
                   62                13               806
                   63                 9               567
                   64                 5               320
                   65                 5               325
                   66                 5               330
                   67                 8               536
                   68                10               680
                   69                 7               483
                   70                 7               490
                   71                 7               497
                   72                 6               432
                   73                 8               584
                   74                 5               370
                   75                 8               600
                   76                 5               380
                   77                 5               385
                   78                 5               390
                   79                 4               316
                   80                 4               320
                   81                 3               243
                   82                 4               328
                   83                 7               581
                   84                 2               168
                   85                 4               340
                   86                 4               344
                   87                 1                87
                   88                 6               528
                   89                 1                89
                   90                 6               540
                   91                 2               182
                   92                 6               552
                   93                 5               465
                   94                 1                94
                   95                 3               285
                   96                 3               288
                   98                 2               196
                   99                 3               297
                  100                 1               100
                  101                 5               505
                  102                 4               408
                  103                 4               412
                  104                 4               416
                  105                 2               210
                  107                 4               428
                  108                 7               756
                  109                 2               218
                  110                 4               440
                  111                 3               333
                  112                 2               224
                  113                 6               678
                  114                 1               114
                  115                 1               115
                  116                 3               348
                  117                 2               234
                  118                 2               236
                  119                 1               119
                  120                 3               360
                  121                 4               484
                  122                 1               122
                  123                 4               492
                  124                 1               124
                  125                 1               125
                  126                 1               126
                  127                 2               254
                  129                 2               258
                  131                 2               262
                  132                 1               132
                  133                 1               133
                  134                 1               134
                  136                 2               272
                  137                 1               137
                  139                 1               139
                  140                 4               560
                  142                 1               142
                  143                 1               143
                  144                 1               144
                  147                 1               147
                  148                 2               296
                  154                 1               154
                  156                 1               156
                  157                 1               157
                  162                 1               162
                  168                 2               336
                  172                 1               172
                  175                 1               175
                  177                 2               354
                  178                 2               356
                  184                 1               184
                  186                 1               186
                  188                 1               188
                  189                 4               756
                  194                 2               388
                  198                 1               198
                  199                 1               199
                  201                 1               201
                  203                 1               203
                  204                 1               204
                  209                 2               418
                  212                 1               212
                  219                 2               438
                  224                 2               448
                  229                 1               229
                  234                 1               234
                  235                 1               235
                  239                 1               239
                  246                 1               246
                  260                 1               260
                  311                 1               311
                  323                 1               323
                  328                 1               328
                  329                 1               329
                  330                 1               330
                  344                 1               344
                  345                 1               345
                  379                 1               379
                  389                 1               389
                  390                 1               390
                  408                 1               408
                  419                 1               419
                  442                 1               442
                  472                 1               472
                  497                 1               497
                  525                 1               525
                  637                 1               637
                  671                 1               671
                  718                 1               718
                  743                 1               743
                  823                 1               823
                  949                 1               949
                 1443                 1              1443
                 1551                 1              1551
                 2074                 2              4148
                 2536                 1              2536
                 3070                 1              3070
                 3727                 1              3727
                 4040                 1              4040
                 9226                 1              9226
                10955                 1             10955
                16220                 1             16220

[TARGET CONSISTENCY]
Exact duplicate groups include Target in their identity definition.
✓ Every exact duplicate group is therefore internally label-consistent by definition.
→ Feature-vector label-conflict analysis is performed separately in Section 4.4.3.

[VALIDATION]
✓ Exact duplicate representation validated
✓ Duplicate groups identified deterministically
✓ Duplicate-group size statistics computed
✓ Target consistency checked
✓ No rows removed
✓ No feature values modified
✓ No labels modified

========================================================================
4.4.2 exact row duplicate analysis completed.
========================================================================

# 4.4.3 Feature-Vector Duplicate & Label-Conflict Analysis

This subsection investigates duplicate observations at the feature-vector
level independently of the target columns.

Unlike the exact row duplicate analysis in Section 4.4.2, feature-vector
identity is defined using only the 63 engineered input features. The original
target (`Target`) and the final taxonomy targets (`FinalTarget`,
`FinalTargetName`) are excluded from feature identity.

The analysis has two objectives:

1. Quantify repeated feature vectors in the Stage-1 dataset.
2. Identify feature vectors that occur with more than one target label,
   which may indicate ambiguous observations or potential label conflicts.

No rows are removed, relabeled, resampled, or otherwise modified in this
subsection. All findings are retained as diagnostic artifacts for the
subsequent leakage-aware partitioning stage and for research reporting.

The feature-vector audit is performed before any train/test partitioning.

In [ ]:
# ============================================================
# 4.4.3 — Feature-Vector Duplicate & Label-Conflict Analysis
# ============================================================

print("=" * 72)
print("4.4.3 — FEATURE-VECTOR DUPLICATE & LABEL-CONFLICT ANALYSIS")
print("=" * 72)

# ------------------------------------------------------------
# 4.4.3.1 Define Feature-Vector Identity
# ------------------------------------------------------------

# The feature vector consists only of the 63 engineered
# Stage-1 input features already defined in Section 4.2.

if len(feature_columns) != 63:
    raise ValueError(
        f"Expected 63 engineered feature columns, "
        f"found {len(feature_columns)}."
    )

if TARGET_COLUMN in feature_columns:
    raise ValueError(
        f"Target column '{TARGET_COLUMN}' is included "
        "in feature_columns."
    )

if "FinalTarget" not in stage1_df.columns:
    raise ValueError(
        "Required taxonomy column 'FinalTarget' "
        "was not found in Stage-1 dataset."
    )

if "FinalTargetName" not in stage1_df.columns:
    raise ValueError(
        "Required taxonomy column 'FinalTargetName' "
        "was not found in Stage-1 dataset."
    )

print("\n[FEATURE-VECTOR IDENTITY]")
print(f"Feature columns included   : {len(feature_columns)}")
print(f"Original Target excluded   : {TARGET_COLUMN}")
print("FinalTarget excluded       : Yes")
print("FinalTargetName excluded   : Yes")
print("Identity definition        : 63 engineered features only")

# ------------------------------------------------------------
# 4.4.3.2 Validate Feature Representation
# ------------------------------------------------------------

if stage1_df[feature_columns].isna().any().any():
    raise ValueError(
        "Missing values detected in feature-vector columns."
    )

if np.isinf(
    stage1_df[feature_columns].to_numpy(dtype=np.float64)
).any():
    raise ValueError(
        "Infinite values detected in feature-vector columns."
    )

print("\n[FEATURE-VECTOR VALIDATION]")
print("✓ All 63 engineered feature columns are available")
print("✓ No missing feature values detected")
print("✓ No infinite feature values detected")

# ------------------------------------------------------------
# 4.4.3.3 Generate Feature-Vector Fingerprints
# ------------------------------------------------------------

# Hashing is used instead of grouping directly on all 63 columns.
# This is substantially more memory-efficient for the 2.8M-row dataset.

feature_vector_hash = pd.util.hash_pandas_object(
    stage1_df[feature_columns],
    index=False
)

# ------------------------------------------------------------
# 4.4.3.4 Identify Repeated Feature Vectors
# ------------------------------------------------------------

feature_vector_counts = (
    feature_vector_hash
    .value_counts()
)

duplicate_feature_groups = feature_vector_counts[
    feature_vector_counts > 1
]

unique_duplicate_feature_vectors = int(
    duplicate_feature_groups.shape[0]
)

duplicate_feature_rows = int(
    duplicate_feature_groups.sum()
)

additional_duplicate_feature_rows = int(
    (duplicate_feature_groups - 1).sum()
)

print("\n[FEATURE-VECTOR DUPLICATES]")
print(
    f"Unique duplicated feature vectors : "
    f"{unique_duplicate_feature_vectors:,}"
)
print(
    f"Rows participating in duplicates  : "
    f"{duplicate_feature_rows:,}"
)
print(
    f"Additional duplicate rows         : "
    f"{additional_duplicate_feature_rows:,}"
)

# ------------------------------------------------------------
# 4.4.3.5 Analyze Target-Label Conflicts
# ------------------------------------------------------------

# For every feature vector, determine how many distinct
# original Target labels are associated with it.

feature_vector_target_counts = (
    pd.DataFrame({
        "FeatureVectorHash": feature_vector_hash,
        TARGET_COLUMN: stage1_df[TARGET_COLUMN].to_numpy()
    })
    .groupby("FeatureVectorHash")[TARGET_COLUMN]
    .nunique()
)

conflicting_feature_groups = (
    feature_vector_target_counts[
        feature_vector_target_counts > 1
    ]
)

conflicting_feature_vector_count = int(
    conflicting_feature_groups.shape[0]
)

# Count all dataset rows belonging to conflicting
# feature-vector groups.

conflicting_hashes = set(
    conflicting_feature_groups.index
)

if conflicting_feature_vector_count > 0:

    conflicting_feature_rows = int(
        feature_vector_hash.isin(
            conflicting_hashes
        ).sum()
    )

else:

    conflicting_feature_rows = 0

print("\n[FEATURE-VECTOR LABEL CONFLICTS]")
print(
    f"Feature vectors with multiple Target labels : "
    f"{conflicting_feature_vector_count:,}"
)
print(
    f"Rows associated with conflicting vectors      : "
    f"{conflicting_feature_rows:,}"
)

if conflicting_feature_vector_count == 0:
    print(
        "✓ No feature-vector label conflicts detected."
    )
else:
    print(
        "⚠ Feature vectors associated with multiple "
        "Target labels detected."
    )

# ------------------------------------------------------------
# 4.4.3.6 Analyze Final-Taxonomy Conflicts
# ------------------------------------------------------------

# This checks whether the same engineered feature vector is
# assigned to multiple final attack-family classes.

feature_vector_final_target_counts = (
    pd.DataFrame({
        "FeatureVectorHash": feature_vector_hash,
        "FinalTarget": stage1_df["FinalTarget"].to_numpy()
    })
    .groupby("FeatureVectorHash")["FinalTarget"]
    .nunique()
)

conflicting_final_target_groups = (
    feature_vector_final_target_counts[
        feature_vector_final_target_counts > 1
    ]
)

conflicting_final_target_count = int(
    conflicting_final_target_groups.shape[0]
)

if conflicting_final_target_count > 0:

    conflicting_final_hashes = set(
        conflicting_final_target_groups.index
    )

    conflicting_final_target_rows = int(
        feature_vector_hash.isin(
            conflicting_final_hashes
        ).sum()
    )

else:

    conflicting_final_target_rows = 0

print("\n[FINAL-TAXONOMY LABEL CONFLICTS]")
print(
    f"Feature vectors with multiple FinalTarget labels : "
    f"{conflicting_final_target_count:,}"
)
print(
    f"Rows associated with conflicting final labels      : "
    f"{conflicting_final_target_rows:,}"
)

if conflicting_final_target_count == 0:
    print(
        "✓ No feature-vector conflicts detected "
        "under the final taxonomy."
    )
else:
    print(
        "⚠ Feature-vector conflicts remain under "
        "the final taxonomy."
    )

# ------------------------------------------------------------
# 4.4.3.7 Conflict Structure
# ------------------------------------------------------------

if conflicting_feature_vector_count > 0:

    conflict_target_count_distribution = (
        conflicting_feature_groups
        .value_counts()
        .sort_index()
        .rename_axis("Number_of_Target_Labels")
        .reset_index(
            name="Number_of_Feature_Vectors"
        )
    )

    print("\n[ORIGINAL TARGET CONFLICT STRUCTURE]")
    display(
        conflict_target_count_distribution
    )

else:

    conflict_target_count_distribution = pd.DataFrame(
        columns=[
            "Number_of_Target_Labels",
            "Number_of_Feature_Vectors"
        ]
    )

# ------------------------------------------------------------
# 4.4.3.8 Persist Diagnostic Results
# ------------------------------------------------------------

duplicate_leakage_audit_dir = (
    MODEL_PREPARATION_V2_DIR /
    "duplicate_leakage_audit"
)

duplicate_leakage_audit_dir.mkdir(
    parents=True,
    exist_ok=True
)

feature_vector_duplicate_summary = pd.DataFrame({
    "Metric": [
        "Total dataset rows",
        "Feature-vector columns",
        "Unique duplicated feature vectors",
        "Rows participating in feature-vector duplicates",
        "Additional duplicate feature-vector rows",
        "Feature vectors with multiple Target labels",
        "Rows associated with conflicting Target vectors",
        "Feature vectors with multiple FinalTarget labels",
        "Rows associated with conflicting FinalTarget vectors"
    ],
    "Value": [
        len(stage1_df),
        len(feature_columns),
        unique_duplicate_feature_vectors,
        duplicate_feature_rows,
        additional_duplicate_feature_rows,
        conflicting_feature_vector_count,
        conflicting_feature_rows,
        conflicting_final_target_count,
        conflicting_final_target_rows
    ]
})

feature_vector_duplicate_summary.to_csv(
    duplicate_leakage_audit_dir /
    "feature_vector_duplicate_summary.csv",
    index=False
)

conflict_target_count_distribution.to_csv(
    duplicate_leakage_audit_dir /
    "feature_vector_conflict_structure.csv",
    index=False
)

# ------------------------------------------------------------
# 4.4.3.9 Final Validation
# ------------------------------------------------------------

print("\n[VALIDATION]")
print("✓ Feature identity uses the 63 engineered features only")
print("✓ Original Target excluded from feature identity")
print("✓ FinalTarget excluded from feature identity")
print("✓ FinalTargetName excluded from feature identity")
print("✓ Repeated feature vectors quantified")
print("✓ Original-target conflicts analyzed")
print("✓ Final-taxonomy conflicts analyzed")
print("✓ Diagnostic artifacts persisted")
print("✓ No rows modified or removed")
print("✓ No labels modified")
print("✓ No resampling performed")
print("✓ No train/test partition performed")

print("\n[ARTIFACTS]")
print(
    f"✓ {duplicate_leakage_audit_dir / 'feature_vector_duplicate_summary.csv'}"
)
print(
    f"✓ {duplicate_leakage_audit_dir / 'feature_vector_conflict_structure.csv'}"
)

print("\n" + "=" * 72)
print(
    "4.4.3 feature-vector duplicate and "
    "label-conflict analysis completed successfully."
)
print("=" * 72)

========================================================================
4.4.3 — FEATURE-VECTOR DUPLICATE & LABEL-CONFLICT ANALYSIS
========================================================================

[FEATURE-VECTOR IDENTITY]
Feature columns included   : 63
Original Target excluded   : Target
FinalTarget excluded       : Yes
FinalTargetName excluded   : Yes
Identity definition        : 63 engineered features only

[FEATURE-VECTOR VALIDATION]
✓ All 63 engineered feature columns are available
✓ No missing feature values detected
✓ No infinite feature values detected

[FEATURE-VECTOR DUPLICATES]
Unique duplicated feature vectors : 102,204
Rows participating in duplicates  : 459,157
Additional duplicate rows         : 356,953

[FEATURE-VECTOR LABEL CONFLICTS]
Feature vectors with multiple Target labels : 1,167
Rows associated with conflicting vectors      : 55,384
⚠ Feature vectors associated with multiple Target labels detected.

[FINAL-TAXONOMY LABEL CONFLICTS]
Feature vectors with multiple FinalTarget labels : 1,161
Rows associated with conflicting final labels      : 55,362
⚠ Feature-vector conflicts remain under the final taxonomy.

[ORIGINAL TARGET CONFLICT STRUCTURE]

   Number_of_Target_Labels  Number_of_Feature_Vectors
0                        2                       1153
1                        3                         13
2                        4                          1

[VALIDATION]
✓ Feature identity uses the 63 engineered features only
✓ Original Target excluded from feature identity
✓ FinalTarget excluded from feature identity
✓ FinalTargetName excluded from feature identity
✓ Repeated feature vectors quantified
✓ Original-target conflicts analyzed
✓ Final-taxonomy conflicts analyzed
✓ Diagnostic artifacts persisted
✓ No rows modified or removed
✓ No labels modified
✓ No resampling performed
✓ No train/test partition performed

[ARTIFACTS]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/duplicate_leakage_audit/feature_vector_duplicate_summary.csv
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/duplicate_leakage_audit/feature_vector_conflict_structure.csv

========================================================================
4.4.3 feature-vector duplicate and label-conflict analysis completed successfully.
========================================================================

# 4.4.4 Duplicate-Aware Partition Strategy

This subsection defines the partitioning strategy required to prevent
feature-vector duplication from causing train/test leakage.

The preceding duplicate audit identified repeated 63-dimensional feature
vectors in the Stage-1 dataset. Therefore, individual rows cannot be treated
as fully independent observations during partitioning.

All rows sharing an identical engineered feature vector will be treated as a
single partition group. A complete feature-vector group must remain entirely
within either the development partition or the final test partition.

Feature vectors associated with multiple labels are retained without
modification. Such groups remain indivisible during partitioning so that
identical feature representations cannot cross the development/test boundary.

The following principles are applied:

1. Feature-vector identity is defined using the 63 engineered input features
   only.
2. The original `Target`, `FinalTarget`, and `FinalTargetName` columns are
   excluded from feature-vector identity.
3. Identical feature vectors must remain within the same partition.
4. No identical feature vector may occur in both development and test data.
5. Conflicting-label feature-vector groups remain intact and are not removed
   or relabeled.
6. No feature selection, scaling, resampling, or model fitting is performed
   before the leakage-aware partition.
7. The final test partition remains isolated from all model-development
   operations.

The partitioning target is approximately 80% development data and 20% final
test data. Because complete duplicate groups must remain indivisible, the
actual row proportions may differ slightly from the target ratio.

This subsection defines the partition policy only. The actual
development/test partition is constructed and validated in the following
subsections.

In [ ]:
# ============================================================
# 4.4.4 — Duplicate-Aware Partition Strategy
# ============================================================

print("=" * 72)
print("4.4.4 — DUPLICATE-AWARE PARTITION STRATEGY")
print("=" * 72)

# ------------------------------------------------------------
# 4.4.4.1 Validate Feature-Vector Identity
# ------------------------------------------------------------

FEATURE_VECTOR_COLUMNS = feature_columns

if len(FEATURE_VECTOR_COLUMNS) != 63:
    raise ValueError(
        f"Expected 63 engineered feature columns, "
        f"found {len(FEATURE_VECTOR_COLUMNS)}."
    )

if TARGET_COLUMN in FEATURE_VECTOR_COLUMNS:
    raise ValueError(
        f"Original target column '{TARGET_COLUMN}' "
        "is incorrectly included in feature identity."
    )

if "FinalTarget" in FEATURE_VECTOR_COLUMNS:
    raise ValueError(
        "FinalTarget is incorrectly included in feature identity."
    )

if "FinalTargetName" in FEATURE_VECTOR_COLUMNS:
    raise ValueError(
        "FinalTargetName is incorrectly included in feature identity."
    )

print("\n[FEATURE-VECTOR IDENTITY]")
print(
    f"Feature columns included : "
    f"{len(FEATURE_VECTOR_COLUMNS)}"
)
print(
    f"Original Target excluded : "
    f"{TARGET_COLUMN}"
)
print("FinalTarget excluded     : Yes")
print("FinalTargetName excluded : Yes")
print(
    "✓ Feature-vector identity is based only on "
    "the 63 engineered input features."
)

# ------------------------------------------------------------
# 4.4.4.2 Define Duplicate-Aware Partition Policy
# ------------------------------------------------------------

DUPLICATE_AWARE_PARTITION_POLICY = {
    "group_identity": "63 engineered feature columns",
    "identical_vectors_same_partition": True,
    "cross_partition_duplicate_vectors": False,
    "conflicting_label_groups_indivisible": True,
    "rows_removed": False,
    "labels_modified": False,
    "resampling_before_partition": False,
    "feature_selection_before_partition": False,
    "scaling_before_partition": False,
    "model_fitting_before_partition": False
}

print("\n[PARTITION POLICY]")

print(
    "Identical vectors kept together : "
    f"{DUPLICATE_AWARE_PARTITION_POLICY['identical_vectors_same_partition']}"
)

print(
    "Cross-partition duplicates       : "
    f"{DUPLICATE_AWARE_PARTITION_POLICY['cross_partition_duplicate_vectors']}"
)

print(
    "Conflicting groups indivisible   : "
    f"{DUPLICATE_AWARE_PARTITION_POLICY['conflicting_label_groups_indivisible']}"
)

print(
    "Rows removed                     : "
    f"{DUPLICATE_AWARE_PARTITION_POLICY['rows_removed']}"
)

print(
    "Labels modified                  : "
    f"{DUPLICATE_AWARE_PARTITION_POLICY['labels_modified']}"
)

# ------------------------------------------------------------
# 4.4.4.3 Define Development/Test Targets
# ------------------------------------------------------------

DEVELOPMENT_FRACTION = 0.80
TEST_FRACTION = 0.20

print("\n[PARTITION TARGET]")
print(
    f"Development target : "
    f"{DEVELOPMENT_FRACTION:.0%}"
)
print(
    f"Test target        : "
    f"{TEST_FRACTION:.0%}"
)
print(
    "Note: Exact row proportions may vary slightly because "
    "duplicate groups are kept indivisible."
)

# ------------------------------------------------------------
# 4.4.4.4 Define Partition Processing Order
# ------------------------------------------------------------

DUPLICATE_AWARE_PROCESSING_ORDER = [
    "Construct feature-vector groups",
    "Assign complete feature-vector groups to partitions",
    "Validate zero feature-vector overlap",
    "Perform feature selection using development data only",
    "Fit scaling parameters using development data only",
    "Apply preprocessing to isolated test data",
    "Apply model-specific imbalance handling to development data only"
]

print("\n[PROCESSING ORDER]")

for step_number, step in enumerate(
    DUPLICATE_AWARE_PROCESSING_ORDER,
    start=1
):
    print(f"{step_number:02d}. {step}")

# ------------------------------------------------------------
# 4.4.4.5 Persist Partition Strategy
# ------------------------------------------------------------

DUPLICATE_AUDIT_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "duplicate_leakage_audit"
)

DUPLICATE_AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

DUPLICATE_AWARE_PARTITION_STRATEGY = {
    "section": "4.4.4",
    "title": "Duplicate-Aware Partition Strategy",
    "feature_vector_columns": FEATURE_VECTOR_COLUMNS,
    "feature_vector_dimension": len(FEATURE_VECTOR_COLUMNS),
    "excluded_from_feature_identity": [
        TARGET_COLUMN,
        "FinalTarget",
        "FinalTargetName"
    ],
    "identical_vectors_same_partition": True,
    "cross_partition_duplicate_vectors": False,
    "conflicting_label_groups_indivisible": True,
    "development_fraction_target": DEVELOPMENT_FRACTION,
    "test_fraction_target": TEST_FRACTION,
    "random_seed": RANDOM_SEED,
    "rows_removed": False,
    "labels_modified": False,
    "resampling_before_partition": False,
    "feature_selection_before_partition": False,
    "scaling_before_partition": False,
    "model_fitting_before_partition": False
}

with open(
    DUPLICATE_AUDIT_DIR /
    "duplicate_aware_partition_strategy.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        DUPLICATE_AWARE_PARTITION_STRATEGY,
        f,
        indent=4
    )

# ------------------------------------------------------------
# 4.4.4.6 Final Validation
# ------------------------------------------------------------

print("\n[VALIDATION]")

print("✓ 63 engineered features define feature-vector identity")
print("✓ Original Target excluded")
print("✓ FinalTarget excluded")
print("✓ FinalTargetName excluded")
print("✓ Identical feature vectors must remain in one partition")
print("✓ Cross-partition duplicate vectors are prohibited")
print("✓ Conflicting-label groups remain indivisible")
print("✓ No rows removed")
print("✓ No labels modified")
print("✓ No resampling performed")
print("✓ No feature selection performed")
print("✓ No scaling performed")
print("✓ No model fitting performed")
print("✓ Actual partition has not yet been created")

print("\n[ARTIFACT]")
print(
    f"✓ {DUPLICATE_AUDIT_DIR / 'duplicate_aware_partition_strategy.json'}"
)

print("\n" + "=" * 72)
print(
    "4.4.4 duplicate-aware partition strategy "
    "defined successfully."
)
print("=" * 72)

========================================================================
4.4.4 — DUPLICATE-AWARE PARTITION STRATEGY
========================================================================

[FEATURE-VECTOR IDENTITY]
Feature columns included : 63
Original Target excluded : Target
FinalTarget excluded     : Yes
FinalTargetName excluded : Yes
✓ Feature-vector identity is based only on the 63 engineered input features.

[PARTITION POLICY]
Identical vectors kept together : True
Cross-partition duplicates       : False
Conflicting groups indivisible   : True
Rows removed                     : False
Labels modified                  : False

[PARTITION TARGET]
Development target : 80%
Test target        : 20%
Note: Exact row proportions may vary slightly because duplicate groups are kept indivisible.

[PROCESSING ORDER]
01. Construct feature-vector groups
02. Assign complete feature-vector groups to partitions
03. Validate zero feature-vector overlap
04. Perform feature selection using development data only
05. Fit scaling parameters using development data only
06. Apply preprocessing to isolated test data
07. Apply model-specific imbalance handling to development data only

[VALIDATION]
✓ 63 engineered features define feature-vector identity
✓ Original Target excluded
✓ FinalTarget excluded
✓ FinalTargetName excluded
✓ Identical feature vectors must remain in one partition
✓ Cross-partition duplicate vectors are prohibited
✓ Conflicting-label groups remain indivisible
✓ No rows removed
✓ No labels modified
✓ No resampling performed
✓ No feature selection performed
✓ No scaling performed
✓ No model fitting performed
✓ Actual partition has not yet been created

[ARTIFACT]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/duplicate_leakage_audit/duplicate_aware_partition_strategy.json

========================================================================
4.4.4 duplicate-aware partition strategy defined successfully.
========================================================================

# 4.4.5 — Leakage-Aware Development/Test Partition Construction

This subsection constructs the development and final test partitions
using the duplicate-aware strategy defined in Section 4.4.4.

All rows sharing an identical 63-dimensional engineered feature vector
are treated as one indivisible partition group. Therefore, identical
feature vectors cannot appear in both development and test partitions.

The final 9-class taxonomy (`FinalTarget`) is used for stratified
partitioning so that the development and test sets retain comparable
class composition while preserving the original empirical distribution.

No feature selection, scaling, resampling, or model fitting is performed
at this stage. The resulting partition indices are persisted for all
downstream experiments.

In [ ]:
# ============================================================
# 4.4.5 — Leakage-Aware Development/Test Partition Construction
# ============================================================

from sklearn.model_selection import StratifiedGroupKFold

print("=" * 72)
print("4.4.5 — LEAKAGE-AWARE DEVELOPMENT/TEST PARTITION CONSTRUCTION")
print("=" * 72)

# ------------------------------------------------------------
# 4.4.5.1 Validate Existing Notebook State
# ------------------------------------------------------------

if TARGET_COLUMN not in stage1_df.columns:
    raise KeyError(
        f"Original target column '{TARGET_COLUMN}' "
        "is not present in stage1_df."
    )

if "FinalTarget" not in stage1_df.columns:
    raise KeyError(
        "FinalTarget column is not present in stage1_df."
    )

if len(feature_columns) != 63:
    raise ValueError(
        f"Expected 63 engineered feature columns, "
        f"found {len(feature_columns)}."
    )

if len(stage1_df) == 0:
    raise ValueError(
        "Stage-1 dataset is empty."
    )

print("\n[PARTITION INPUT]")
print(f"Dataset rows              : {len(stage1_df):,}")
print(f"Engineered feature count  : {len(feature_columns)}")
print(f"Original target column    : {TARGET_COLUMN}")
print("Final taxonomy column     : FinalTarget")
print(f"Random seed               : {RANDOM_SEED}")

# ------------------------------------------------------------
# 4.4.5.2 Construct Exact Feature-Vector Groups
# ------------------------------------------------------------

# Each identical 63-dimensional feature vector receives the
# same group identifier. Target columns are not used here.

feature_vector_hash = pd.util.hash_pandas_object(
    stage1_df[feature_columns],
    index=False
)

feature_vector_group = (
    pd.factorize(
        feature_vector_hash,
        sort=False
    )[0]
)

number_of_feature_vector_groups = int(
    feature_vector_group.max() + 1
)

print("\n[FEATURE-VECTOR GROUPING]")
print(
    f"Unique feature-vector groups : "
    f"{number_of_feature_vector_groups:,}"
)
print(
    f"Rows represented             : "
    f"{len(feature_vector_group):,}"
)
print(
    "✓ Group identity uses the 63 engineered features only."
)

# ------------------------------------------------------------
# 4.4.5.3 Verify Group Integrity
# ------------------------------------------------------------

# Verify that every feature-vector group contains only one
# feature representation. Hash collisions are checked by comparing
# the number of unique feature vectors with the number of groups.

unique_feature_vectors = int(
    stage1_df[feature_columns]
    .drop_duplicates()
    .shape[0]
)

if unique_feature_vectors != number_of_feature_vector_groups:
    raise ValueError(
        "Feature-vector hash collision detected. "
        "Group identity cannot be used safely."
    )

print("\n[GROUP INTEGRITY]")
print(
    f"Unique feature vectors      : "
    f"{unique_feature_vectors:,}"
)
print(
    f"Feature-vector groups       : "
    f"{number_of_feature_vector_groups:,}"
)
print("✓ No feature-vector hash collisions detected.")

# ------------------------------------------------------------
# 4.4.5.4 Stratified Group Partitioning
# ------------------------------------------------------------

# Five stratified groups correspond approximately to an 80/20
# development/test partition.

partitioner = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=RANDOM_SEED
)

partition_candidates = []

for development_positions, test_positions in partitioner.split(
    stage1_df[feature_columns],
    stage1_df["FinalTarget"],
    groups=feature_vector_group
):
    test_fraction = (
        len(test_positions) /
        len(stage1_df)
    )

    development_distribution = (
        stage1_df.iloc[development_positions]["FinalTarget"]
        .value_counts(normalize=True)
        .sort_index()
    )

    test_distribution = (
        stage1_df.iloc[test_positions]["FinalTarget"]
        .value_counts(normalize=True)
        .sort_index()
    )

    all_final_classes = sorted(
        stage1_df["FinalTarget"].unique()
    )

    development_distribution = (
        development_distribution
        .reindex(
            all_final_classes,
            fill_value=0
        )
    )

    test_distribution = (
        test_distribution
        .reindex(
            all_final_classes,
            fill_value=0
        )
    )

    distribution_difference = float(
        (
            development_distribution -
            test_distribution
        )
        .abs()
        .sum()
    )

    partition_score = (
        abs(test_fraction - 0.20),
        distribution_difference
    )

    partition_candidates.append(
        (
            partition_score,
            development_positions,
            test_positions
        )
    )

# Select the candidate closest to the requested 20% test size,
# with class-distribution similarity used as the secondary criterion.

partition_candidates.sort(
    key=lambda item: item[0]
)

_, development_indices, test_indices = (
    partition_candidates[0]
)

development_indices = np.asarray(
    development_indices,
    dtype=np.int64
)

test_indices = np.asarray(
    test_indices,
    dtype=np.int64
)

# ------------------------------------------------------------
# 4.4.5.5 Partition Size Validation
# ------------------------------------------------------------

development_fraction = (
    len(development_indices) /
    len(stage1_df)
)

test_fraction = (
    len(test_indices) /
    len(stage1_df)
)

print("\n[PARTITION SIZE]")
print(
    f"Development rows : "
    f"{len(development_indices):,} "
    f"({development_fraction * 100:.6f}%)"
)
print(
    f"Test rows        : "
    f"{len(test_indices):,} "
    f"({test_fraction * 100:.6f}%)"
)

if (
    len(development_indices) +
    len(test_indices)
    != len(stage1_df)
):
    raise ValueError(
        "Development and test partitions do not "
        "cover the complete dataset."
    )

if set(development_indices).intersection(
    set(test_indices)
):
    raise ValueError(
        "Development and test row indices overlap."
    )

print("✓ All dataset rows assigned exactly once.")
print("✓ Development and test row indices are disjoint.")

# ------------------------------------------------------------
# 4.4.5.6 Validate Final-Taxonomy Coverage
# ------------------------------------------------------------

development_classes = set(
    stage1_df.iloc[
        development_indices
    ]["FinalTarget"].unique()
)

test_classes = set(
    stage1_df.iloc[
        test_indices
    ]["FinalTarget"].unique()
)

all_final_classes = set(
    stage1_df["FinalTarget"].unique()
)

missing_from_development = (
    all_final_classes -
    development_classes
)

missing_from_test = (
    all_final_classes -
    test_classes
)

print("\n[FINAL-TAXONOMY COVERAGE]")
print(
    f"All final classes        : "
    f"{sorted(all_final_classes)}"
)
print(
    f"Development classes      : "
    f"{sorted(development_classes)}"
)
print(
    f"Test classes             : "
    f"{sorted(test_classes)}"
)

if missing_from_development:
    raise ValueError(
        "Final taxonomy classes missing from "
        f"development partition: "
        f"{sorted(missing_from_development)}"
    )

if missing_from_test:
    raise ValueError(
        "Final taxonomy classes missing from "
        f"test partition: "
        f"{sorted(missing_from_test)}"
    )

print("✓ All 9 final taxonomy classes represented in both partitions.")

# ------------------------------------------------------------
# 4.4.5.7 Verify Zero Cross-Partition Feature-Vector Overlap
# ------------------------------------------------------------

development_groups = set(
    feature_vector_group[
        development_indices
    ]
)

test_groups = set(
    feature_vector_group[
        test_indices
    ]
)

cross_partition_feature_groups = (
    development_groups.intersection(
        test_groups
    )
)

if cross_partition_feature_groups:
    raise ValueError(
        "Leakage detected: identical feature vectors "
        "appear in both development and test partitions."
    )

print("\n[LEAKAGE VALIDATION]")
print(
    f"Development feature-vector groups : "
    f"{len(development_groups):,}"
)
print(
    f"Test feature-vector groups        : "
    f"{len(test_groups):,}"
)
print(
    f"Cross-partition duplicate groups  : "
    f"{len(cross_partition_feature_groups):,}"
)
print("✓ Zero identical feature vectors cross the partition boundary.")

# ------------------------------------------------------------
# 4.4.5.8 Persist Partition Indices
# ------------------------------------------------------------

DUPLICATE_LEAKAGE_AUDIT_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "duplicate_leakage_audit"
)

DUPLICATE_LEAKAGE_AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

np.save(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "development_indices.npy",
    development_indices
)

np.save(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "test_indices.npy",
    test_indices
)

# ------------------------------------------------------------
# 4.4.5.9 Persist Partition Distributions
# ------------------------------------------------------------

development_distribution = (
    stage1_df.iloc[
        development_indices
    ]["FinalTarget"]
    .value_counts()
    .sort_index()
    .rename("Count")
    .to_frame()
)

development_distribution["Percentage"] = (
    development_distribution["Count"] /
    len(development_indices) *
    100
)

test_distribution = (
    stage1_df.iloc[
        test_indices
    ]["FinalTarget"]
    .value_counts()
    .sort_index()
    .rename("Count")
    .to_frame()
)

test_distribution["Percentage"] = (
    test_distribution["Count"] /
    len(test_indices) *
    100
)

development_distribution.to_csv(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "development_class_distribution.csv"
)

test_distribution.to_csv(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "test_class_distribution.csv"
)

# ------------------------------------------------------------
# 4.4.5.10 Persist Partition Metadata
# ------------------------------------------------------------

partition_metadata = {
    "dataset_rows": int(len(stage1_df)),
    "feature_count": int(len(feature_columns)),
    "feature_vector_groups": int(
        number_of_feature_vector_groups
    ),
    "development_rows": int(
        len(development_indices)
    ),
    "test_rows": int(
        len(test_indices)
    ),
    "development_fraction": float(
        development_fraction
    ),
    "test_fraction": float(
        test_fraction
    ),
    "target_column": TARGET_COLUMN,
    "final_target_column": "FinalTarget",
    "group_definition": (
        "Identical 63-dimensional engineered "
        "feature vectors"
    ),
    "stratification_target": "FinalTarget",
    "cross_partition_feature_vector_groups": 0,
    "rows_removed": 0,
    "labels_modified": False,
    "resampling_performed": False,
    "feature_selection_performed": False,
    "scaling_performed": False,
    "model_fitting_performed": False,
    "random_seed": int(RANDOM_SEED)
}

with open(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "leakage_aware_partition_metadata.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        partition_metadata,
        f,
        indent=4
    )

# ------------------------------------------------------------
# 4.4.5.11 Final Validation
# ------------------------------------------------------------

print("\n[ARTIFACTS]")
print(
    "✓ "
    + str(
        DUPLICATE_LEAKAGE_AUDIT_DIR /
        "development_indices.npy"
    )
)
print(
    "✓ "
    + str(
        DUPLICATE_LEAKAGE_AUDIT_DIR /
        "test_indices.npy"
    )
)
print(
    "✓ "
    + str(
        DUPLICATE_LEAKAGE_AUDIT_DIR /
        "development_class_distribution.csv"
    )
)
print(
    "✓ "
    + str(
        DUPLICATE_LEAKAGE_AUDIT_DIR /
        "test_class_distribution.csv"
    )
)
print(
    "✓ "
    + str(
        DUPLICATE_LEAKAGE_AUDIT_DIR /
        "leakage_aware_partition_metadata.json"
    )
)

print("\n[VALIDATION]")
print("✓ Duplicate-aware development/test partition constructed")
print("✓ 80/20 target approximately achieved")
print("✓ Final taxonomy used for stratification")
print("✓ All final classes represented in both partitions")
print("✓ Development and test rows are disjoint")
print("✓ Identical feature vectors cannot cross partitions")
print("✓ No rows removed")
print("✓ No labels modified")
print("✓ No resampling performed")
print("✓ No feature selection performed")
print("✓ No scaling performed")
print("✓ No model fitting performed")
print("✓ Partition indices persisted for downstream stages")

print("\n" + "=" * 72)
print(
    "4.4.5 leakage-aware development/test "
    "partition constructed successfully."
)
print("=" * 72)

========================================================================
4.4.5 — LEAKAGE-AWARE DEVELOPMENT/TEST PARTITION CONSTRUCTION
========================================================================

[PARTITION INPUT]
Dataset rows              : 2,830,743
Engineered feature count  : 63
Original target column    : Target
Final taxonomy column     : FinalTarget
Random seed               : 42

[FEATURE-VECTOR GROUPING]
Unique feature-vector groups : 2,473,790
Rows represented             : 2,830,743
✓ Group identity uses the 63 engineered features only.

[GROUP INTEGRITY]
Unique feature vectors      : 2,473,790
Feature-vector groups       : 2,473,790
✓ No feature-vector hash collisions detected.

[PARTITION SIZE]
Development rows : 2,265,233 (80.022559%)
Test rows        : 565,510 (19.977441%)
✓ All dataset rows assigned exactly once.
✓ Development and test row indices are disjoint.

[FINAL-TAXONOMY COVERAGE]
All final classes        : [np.int8(0), np.int8(1), np.int8(2), np.int8(3), np.int8(4), np.int8(5), np.int8(6), np.int8(7), np.int8(8)]
Development classes      : [np.int8(0), np.int8(1), np.int8(2), np.int8(3), np.int8(4), np.int8(5), np.int8(6), np.int8(7), np.int8(8)]
Test classes             : [np.int8(0), np.int8(1), np.int8(2), np.int8(3), np.int8(4), np.int8(5), np.int8(6), np.int8(7), np.int8(8)]
✓ All 9 final taxonomy classes represented in both partitions.

[LEAKAGE VALIDATION]
Development feature-vector groups : 1,977,912
Test feature-vector groups        : 495,878
Cross-partition duplicate groups  : 0
✓ Zero identical feature vectors cross the partition boundary.

[ARTIFACTS]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/duplicate_leakage_audit/development_indices.npy
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/duplicate_leakage_audit/test_indices.npy
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/duplicate_leakage_audit/development_class_distribution.csv
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/duplicate_leakage_audit/test_class_distribution.csv
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/duplicate_leakage_audit/leakage_aware_partition_metadata.json

[VALIDATION]
✓ Duplicate-aware development/test partition constructed
✓ 80/20 target approximately achieved
✓ Final taxonomy used for stratification
✓ All final classes represented in both partitions
✓ Development and test rows are disjoint
✓ Identical feature vectors cannot cross partitions
✓ No rows removed
✓ No labels modified
✓ No resampling performed
✓ No feature selection performed
✓ No scaling performed
✓ No model fitting performed
✓ Partition indices persisted for downstream stages

========================================================================
4.4.5 leakage-aware development/test partition constructed successfully.
========================================================================

# 4.4.6 — Partition Integrity & Reproducibility Validation

This subsection performs the final integrity validation of the
leakage-aware development/test partition constructed in Section 4.4.5.

The validation confirms that:

- every original dataset row belongs to exactly one partition,
- development and test indices are mutually exclusive,
- both partitions preserve the complete 9-class final taxonomy,
- no identical feature vectors occur across the partition boundary,
- the persisted partition indices can be reloaded correctly,
- the original Stage-1 dataset remains unchanged,
- no preprocessing, feature selection, scaling, resampling, or model
  fitting is performed at this stage.

The persisted partition indices form the authoritative dataset split
for all downstream model-development and evaluation stages.

In [ ]:
# ============================================================
# 4.4.6 — Partition Integrity & Reproducibility Validation
# ============================================================

print("=" * 72)
print("4.4.6 — PARTITION INTEGRITY & REPRODUCIBILITY VALIDATION")
print("=" * 72)

# ------------------------------------------------------------
# 4.4.6.1 Reload Persisted Partition Indices
# ------------------------------------------------------------

development_indices = np.load(
    DUPLICATE_LEAKAGE_AUDIT_DIR / "development_indices.npy"
)

test_indices = np.load(
    DUPLICATE_LEAKAGE_AUDIT_DIR / "test_indices.npy"
)

print("\n[PERSISTED PARTITION]")
print(
    f"Development indices : "
    f"{len(development_indices):,}"
)
print(
    f"Test indices        : "
    f"{len(test_indices):,}"
)

# ------------------------------------------------------------
# 4.4.6.2 Partition Coverage Validation
# ------------------------------------------------------------

total_rows = len(stage1_df)

all_partition_indices = np.concatenate(
    [
        development_indices,
        test_indices
    ]
)

unique_partition_indices = np.unique(
    all_partition_indices
)

if len(unique_partition_indices) != total_rows:
    raise ValueError(
        "Partition coverage validation failed: "
        "not every Stage-1 row is represented exactly once."
    )

if len(all_partition_indices) != total_rows:
    raise ValueError(
        "Partition assignment validation failed: "
        "duplicate row indices exist across partitions."
    )

if not np.array_equal(
    unique_partition_indices,
    np.arange(total_rows)
):
    raise ValueError(
        "Partition index validation failed: "
        "persisted indices do not cover the complete Stage-1 dataset."
    )

print("\n[PARTITION COVERAGE]")
print(
    f"Total Stage-1 rows       : "
    f"{total_rows:,}"
)
print(
    f"Persisted partition rows : "
    f"{len(all_partition_indices):,}"
)
print("✓ Every Stage-1 row is assigned exactly once")

# ------------------------------------------------------------
# 4.4.6.3 Development/Test Exclusivity
# ------------------------------------------------------------

partition_overlap = np.intersect1d(
    development_indices,
    test_indices
)

if len(partition_overlap) != 0:
    raise ValueError(
        "Development/test partition overlap detected."
    )

print("\n[PARTITION EXCLUSIVITY]")
print(
    f"Development/Test overlap : "
    f"{len(partition_overlap):,}"
)
print("✓ Development and test indices are mutually exclusive")

# ------------------------------------------------------------
# 4.4.6.4 Final-Taxonomy Coverage Validation
# ------------------------------------------------------------

development_classes = np.sort(
    stage1_df.iloc[
        development_indices
    ]["FinalTarget"].unique()
)

test_classes = np.sort(
    stage1_df.iloc[
        test_indices
    ]["FinalTarget"].unique()
)

all_classes = np.sort(
    stage1_df["FinalTarget"].unique()
)

if not np.array_equal(
    development_classes,
    all_classes
):
    raise ValueError(
        "Not all final taxonomy classes are represented "
        "in the development partition."
    )

if not np.array_equal(
    test_classes,
    all_classes
):
    raise ValueError(
        "Not all final taxonomy classes are represented "
        "in the test partition."
    )

print("\n[FINAL-TAXONOMY COVERAGE]")
print(
    f"All final classes        : "
    f"{len(all_classes)}"
)
print(
    f"Development classes      : "
    f"{len(development_classes)}"
)
print(
    f"Test classes             : "
    f"{len(test_classes)}"
)
print("✓ All final taxonomy classes represented in development")
print("✓ All final taxonomy classes represented in test")

# ------------------------------------------------------------
# 4.4.6.5 Duplicate-Aware Leakage Validation
# ------------------------------------------------------------

development_feature_vectors = stage1_df.iloc[
    development_indices
][feature_columns]

test_feature_vectors = stage1_df.iloc[
    test_indices
][feature_columns]

development_feature_hashes = pd.util.hash_pandas_object(
    development_feature_vectors,
    index=False
)

test_feature_hashes = pd.util.hash_pandas_object(
    test_feature_vectors,
    index=False
)

cross_partition_hash_overlap = np.intersect1d(
    development_feature_hashes.to_numpy(),
    test_feature_hashes.to_numpy()
)

if len(cross_partition_hash_overlap) != 0:
    raise ValueError(
        "Cross-partition identical feature vectors detected."
    )

print("\n[DUPLICATE-AWARE LEAKAGE VALIDATION]")
print(
    f"Cross-partition identical feature vectors : "
    f"{len(cross_partition_hash_overlap):,}"
)
print("✓ No identical feature vectors cross the partition boundary")

# ------------------------------------------------------------
# 4.4.6.6 Stage-1 Dataset Integrity Validation
# ------------------------------------------------------------

if len(stage1_df) != total_rows:
    raise ValueError(
        "Stage-1 dataset row count changed unexpectedly."
    )

if len(feature_columns) != 63:
    raise ValueError(
        f"Expected 63 engineered features, "
        f"found {len(feature_columns)}."
    )

if TARGET_COLUMN not in stage1_df.columns:
    raise ValueError(
        f"Original target column '{TARGET_COLUMN}' is missing."
    )

if "FinalTarget" not in stage1_df.columns:
    raise ValueError(
        "FinalTarget column is missing."
    )

if "FinalTargetName" not in stage1_df.columns:
    raise ValueError(
        "FinalTargetName column is missing."
    )

print("\n[STAGE-1 INTEGRITY]")
print(
    f"Stage-1 rows            : "
    f"{len(stage1_df):,}"
)
print(
    f"Engineered features     : "
    f"{len(feature_columns)}"
)
print(f"Original target         : {TARGET_COLUMN}")
print("Final target column     : FinalTarget")
print("Final target-name column: FinalTargetName")
print("✓ Stage-1 dataset structure remains unchanged")

# ------------------------------------------------------------
# 4.4.6.7 Persist Final Partition Validation Metadata
# ------------------------------------------------------------

partition_validation_metadata = {
    "dataset_name": STAGE1_METADATA.get(
        "dataset",
        "CICIDS2017"
    ),
    "stage": "Stage 1 Feature Engineering",
    "total_rows": int(total_rows),
    "feature_count": int(len(feature_columns)),
    "development_rows": int(len(development_indices)),
    "test_rows": int(len(test_indices)),
    "development_fraction": float(
        len(development_indices) / total_rows
    ),
    "test_fraction": float(
        len(test_indices) / total_rows
    ),
    "random_seed": int(RANDOM_SEED),
    "final_taxonomy_class_count": int(
        len(all_classes)
    ),
    "development_taxonomy_class_count": int(
        len(development_classes)
    ),
    "test_taxonomy_class_count": int(
        len(test_classes)
    ),
    "partition_overlap_rows": int(
        len(partition_overlap)
    ),
    "cross_partition_duplicate_feature_vectors": int(
        len(cross_partition_hash_overlap)
    ),
    "all_rows_assigned_once": True,
    "all_taxonomy_classes_in_development": True,
    "all_taxonomy_classes_in_test": True,
    "duplicate_aware_partition": True,
    "rows_removed": False,
    "labels_modified": False,
    "resampling_performed": False,
    "feature_selection_performed": False,
    "scaling_performed": False,
    "model_fitting_performed": False
}

with open(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "partition_integrity_metadata.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        partition_validation_metadata,
        f,
        indent=4
    )

# ------------------------------------------------------------
# 4.4.6.8 Final Validation
# ------------------------------------------------------------

print("\n[FINAL VALIDATION]")
print("✓ Persisted development indices reloaded successfully")
print("✓ Persisted test indices reloaded successfully")
print("✓ Every Stage-1 row assigned exactly once")
print("✓ Development/test partitions are mutually exclusive")
print("✓ All 9 final taxonomy classes represented in development")
print("✓ All 9 final taxonomy classes represented in test")
print("✓ No identical feature vectors cross the partition boundary")
print("✓ Stage-1 dataset remains unchanged")
print("✓ Partition integrity metadata persisted")
print("✓ No rows removed")
print("✓ No labels modified")
print("✓ No resampling performed")
print("✓ No feature selection performed")
print("✓ No scaling performed")
print("✓ No model fitting performed")

print("\n[ARTIFACT]")
print(
    "✓ "
    + str(
        DUPLICATE_LEAKAGE_AUDIT_DIR /
        "partition_integrity_metadata.json"
    )
)

print("\n" + "=" * 72)
print(
    "4.4.6 partition integrity and reproducibility "
    "validation completed successfully."
)
print("=" * 72)

========================================================================
4.4.6 — PARTITION INTEGRITY & REPRODUCIBILITY VALIDATION
========================================================================

[PERSISTED PARTITION]
Development indices : 2,265,233
Test indices        : 565,510

[PARTITION COVERAGE]
Total Stage-1 rows       : 2,830,743
Persisted partition rows : 2,830,743
✓ Every Stage-1 row is assigned exactly once

[PARTITION EXCLUSIVITY]
Development/Test overlap : 0
✓ Development and test indices are mutually exclusive

[FINAL-TAXONOMY COVERAGE]
All final classes        : 9
Development classes      : 9
Test classes             : 9
✓ All final taxonomy classes represented in development
✓ All final taxonomy classes represented in test

[DUPLICATE-AWARE LEAKAGE VALIDATION]
Cross-partition identical feature vectors : 0
✓ No identical feature vectors cross the partition boundary

[STAGE-1 INTEGRITY]
Stage-1 rows            : 2,830,743
Engineered features     : 63
Original target         : Target
Final target column     : FinalTarget
Final target-name column: FinalTargetName
✓ Stage-1 dataset structure remains unchanged

[FINAL VALIDATION]
✓ Persisted development indices reloaded successfully
✓ Persisted test indices reloaded successfully
✓ Every Stage-1 row assigned exactly once
✓ Development/test partitions are mutually exclusive
✓ All 9 final taxonomy classes represented in development
✓ All 9 final taxonomy classes represented in test
✓ No identical feature vectors cross the partition boundary
✓ Stage-1 dataset remains unchanged
✓ Partition integrity metadata persisted
✓ No rows removed
✓ No labels modified
✓ No resampling performed
✓ No feature selection performed
✓ No scaling performed
✓ No model fitting performed

[ARTIFACT]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/duplicate_leakage_audit/partition_integrity_metadata.json

========================================================================
4.4.6 partition integrity and reproducibility validation completed successfully.
========================================================================

# 4.5 — Development, Validation, and Test Partitioning

This stage establishes the final three-way data-partition architecture
required for model development and evaluation.

The leakage-aware development/test boundary constructed in Section 4.4
is treated as authoritative and is not recreated or replaced.

The existing development partition will be further divided into
training and validation subsets using a reproducible and
duplicate-aware procedure. The independent test partition will remain
isolated and will not participate in training, feature selection,
hyperparameter tuning, scaling, resampling, or model selection.

The resulting architecture is:

    Stage-1 Dataset
          │
          ├── Development
          │      ├── Training
          │      └── Validation
          │
          └── Independent Test

Training data will be used for all training-dependent preprocessing
and model fitting.

Validation data will be used for model development, comparison, and
parameter-selection decisions.

The independent test partition will be reserved exclusively for final
unbiased evaluation.

All partition assignments will preserve duplicate-group integrity so
that identical engineered feature vectors cannot cross partition
boundaries.

No feature selection, correlation pruning, scaling, resampling, or
model fitting is performed during this stage until the corresponding
downstream sections explicitly define those operations.

# 4.5.1 — Partition Architecture & Existing Split Recovery

This subsection recovers the authoritative development and test
partitions established during the Duplicate & Leakage Audit.

The persisted development/test indices from Section 4.4 are treated
as the fixed outer partition boundary for the remainder of Notebook 04.

No new development/test split is generated here.

The independent test partition remains completely isolated, while the
development partition becomes the only dataset eligible for the
subsequent training/validation split.

This establishes the following hierarchy:

    Development
        ├── Training
        └── Validation

    Test
        └── Independent final evaluation

The recovered partition is validated against the Stage-1 dataset
before any further partitioning is performed.

In [ ]:
# ============================================================
# 4.5.1 — PARTITION ARCHITECTURE & EXISTING SPLIT RECOVERY
# ============================================================

print("=" * 72)
print("4.5.1 — PARTITION ARCHITECTURE & EXISTING SPLIT RECOVERY")
print("=" * 72)

# ------------------------------------------------------------
# 4.5.1.1 Recover Authoritative Development/Test Indices
# ------------------------------------------------------------

development_indices = np.load(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "development_indices.npy"
)

test_indices = np.load(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "test_indices.npy"
)

print("\n[PERSISTED OUTER PARTITION]")
print(
    f"Development rows : "
    f"{len(development_indices):,}"
)
print(
    f"Test rows        : "
    f"{len(test_indices):,}"
)

# ------------------------------------------------------------
# 4.5.1.2 Validate Index Coverage
# ------------------------------------------------------------

total_rows = len(stage1_df)

combined_indices = np.concatenate(
    [
        development_indices,
        test_indices
    ]
)

if len(combined_indices) != total_rows:
    raise ValueError(
        "Persisted development/test indices do not account "
        "for every Stage-1 row."
    )

if len(np.unique(combined_indices)) != total_rows:
    raise ValueError(
        "Duplicate row indices detected across the persisted "
        "development/test partition."
    )

if not np.array_equal(
    np.sort(combined_indices),
    np.arange(total_rows)
):
    raise ValueError(
        "Persisted partition indices do not cover the complete "
        "Stage-1 dataset."
    )

print("\n[OUTER PARTITION COVERAGE]")
print(
    f"Stage-1 rows       : "
    f"{total_rows:,}"
)
print(
    f"Partitioned rows   : "
    f"{len(combined_indices):,}"
)
print("✓ Every Stage-1 row belongs to exactly one outer partition")

# ------------------------------------------------------------
# 4.5.1.3 Validate Development/Test Exclusivity
# ------------------------------------------------------------

outer_partition_overlap = np.intersect1d(
    development_indices,
    test_indices
)

if len(outer_partition_overlap) != 0:
    raise ValueError(
        "Development/test overlap detected in the "
        "authoritative outer partition."
    )

print("\n[OUTER PARTITION EXCLUSIVITY]")
print(
    f"Development/Test overlap : "
    f"{len(outer_partition_overlap):,}"
)
print("✓ Development and test partitions are mutually exclusive")

# ------------------------------------------------------------
# 4.5.1.4 Validate Final Taxonomy Coverage
# ------------------------------------------------------------

development_classes = np.sort(
    stage1_df.iloc[
        development_indices
    ]["FinalTarget"].unique()
)

test_classes = np.sort(
    stage1_df.iloc[
        test_indices
    ]["FinalTarget"].unique()
)

all_classes = np.sort(
    stage1_df["FinalTarget"].unique()
)

if not np.array_equal(
    development_classes,
    all_classes
):
    raise ValueError(
        "The development partition does not contain all "
        "final taxonomy classes."
    )

if not np.array_equal(
    test_classes,
    all_classes
):
    raise ValueError(
        "The test partition does not contain all "
        "final taxonomy classes."
    )

print("\n[FINAL TAXONOMY COVERAGE]")
print(
    f"All final classes       : "
    f"{len(all_classes)}"
)
print(
    f"Development classes     : "
    f"{len(development_classes)}"
)
print(
    f"Test classes            : "
    f"{len(test_classes)}"
)
print("✓ All final taxonomy classes present in development")
print("✓ All final taxonomy classes present in test")

# ------------------------------------------------------------
# 4.5.1.5 Establish Stage-5 Partition State
# ------------------------------------------------------------

print("\n[STAGE-5 PARTITION STATE]")
print(
    "✓ Existing development/test boundary recovered"
)
print(
    "✓ Independent test partition remains isolated"
)
print(
    "✓ Development partition is available for "
    "training/validation subdivision"
)
print(
    "✓ No new development/test split created"
)
print(
    "✓ No rows removed"
)
print(
    "✓ No labels modified"
)
print(
    "✓ No feature selection performed"
)
print(
    "✓ No correlation pruning performed"
)
print(
    "✓ No scaling performed"
)
print(
    "✓ No resampling performed"
)
print(
    "✓ No model fitting performed"
)

print("\n" + "=" * 72)
print(
    "4.5.1 partition architecture and existing split "
    "recovery completed successfully."
)
print("=" * 72)

========================================================================
4.5.1 — PARTITION ARCHITECTURE & EXISTING SPLIT RECOVERY
========================================================================

[PERSISTED OUTER PARTITION]
Development rows : 2,265,233
Test rows        : 565,510

[OUTER PARTITION COVERAGE]
Stage-1 rows       : 2,830,743
Partitioned rows   : 2,830,743
✓ Every Stage-1 row belongs to exactly one outer partition

[OUTER PARTITION EXCLUSIVITY]
Development/Test overlap : 0
✓ Development and test partitions are mutually exclusive

[FINAL TAXONOMY COVERAGE]
All final classes       : 9
Development classes     : 9
Test classes            : 9
✓ All final taxonomy classes present in development
✓ All final taxonomy classes present in test

[STAGE-5 PARTITION STATE]
✓ Existing development/test boundary recovered
✓ Independent test partition remains isolated
✓ Development partition is available for training/validation subdivision
✓ No new development/test split created
✓ No rows removed
✓ No labels modified
✓ No feature selection performed
✓ No correlation pruning performed
✓ No scaling performed
✓ No resampling performed
✓ No model fitting performed

========================================================================
4.5.1 partition architecture and existing split recovery completed successfully.
========================================================================

# 4.5.2 Development-Only Training/Validation Strategy

The independent test partition established in Section 4.4 remains
completely isolated and is not used during training or validation
construction.

Only the persisted Development partition is considered for the
Training/Validation subdivision.

An approximately 80:20 Training/Validation split will be constructed
using the same duplicate-aware principle established during the
development/test partitioning stage. All rows sharing an identical
63-dimensional engineered feature vector will remain in the same
subset.

The Training partition will be used for model fitting and all
training-dependent preprocessing operations.

The Validation partition will be used for model selection,
hyperparameter tuning, threshold selection, and other development
decisions.

The independent Test partition will remain untouched until final model
evaluation.

No feature selection, correlation pruning, scaling, resampling, or
model fitting is performed in this subsection.

In [ ]:
# ============================================================
# 4.5.2 — Development-Only Training/Validation Strategy
# ============================================================

from sklearn.model_selection import GroupShuffleSplit

print("=" * 72)
print("4.5.2 — DEVELOPMENT-ONLY TRAINING/VALIDATION STRATEGY")
print("=" * 72)

# ------------------------------------------------------------
# 4.5.2.1 Recover Development Partition
# ------------------------------------------------------------

development_data = stage1_df.iloc[
    development_indices
].copy()

print("\n[DEVELOPMENT PARTITION]")
print(
    f"Development rows : "
    f"{len(development_data):,}"
)
print(
    f"Feature columns  : "
    f"{len(feature_columns)}"
)

# ------------------------------------------------------------
# 4.5.2.2 Construct Duplicate-Aware Feature Groups
# ------------------------------------------------------------

# Identical 63-dimensional feature vectors form one indivisible
# group. FinalTarget is deliberately excluded from the grouping
# identity.

development_group_ids = pd.factorize(
    development_data[
        feature_columns
    ].apply(
        lambda row: hash(tuple(row)),
        axis=1
    ),
    sort=False
)[0]

print("\n[FEATURE-VECTOR GROUPING]")
print(
    f"Development rows       : "
    f"{len(development_group_ids):,}"
)
print(
    f"Unique feature groups  : "
    f"{len(np.unique(development_group_ids)):,}"
)
print(
    "✓ Group identity uses the 63 engineered features only"
)
print(
    "✓ FinalTarget is excluded from feature identity"
)

# ------------------------------------------------------------
# 4.5.2.3 Construct Training/Validation Split
# ------------------------------------------------------------

training_validation_split = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=RANDOM_SEED
)

training_positions, validation_positions = next(
    training_validation_split.split(
        development_data,
        groups=development_group_ids
    )
)

training_indices = development_indices[
    training_positions
]

validation_indices = development_indices[
    validation_positions
]

# ------------------------------------------------------------
# 4.5.2.4 Validate Partition Coverage
# ------------------------------------------------------------

if len(training_indices) + len(validation_indices) != len(
    development_indices
):
    raise ValueError(
        "Training and validation partitions do not account "
        "for every development row."
    )

if len(
    np.intersect1d(
        training_indices,
        validation_indices
    )
) != 0:
    raise ValueError(
        "Training and validation partitions overlap."
    )

print("\n[PARTITION SIZE]")
print(
    f"Training rows   : "
    f"{len(training_indices):,} "
    f"({len(training_indices) / len(development_indices) * 100:.6f}%)"
)
print(
    f"Validation rows : "
    f"{len(validation_indices):,} "
    f"({len(validation_indices) / len(development_indices) * 100:.6f}%)"
)

print(
    "✓ Every development row assigned exactly once"
)
print(
    "✓ Training and validation indices are mutually exclusive"
)

# ------------------------------------------------------------
# 4.5.2.5 Validate Duplicate-Group Integrity
# ------------------------------------------------------------

training_feature_groups = pd.factorize(
    stage1_df.iloc[
        training_indices
    ][feature_columns].apply(
        lambda row: hash(tuple(row)),
        axis=1
    ),
    sort=False
)[0]

validation_feature_groups = pd.factorize(
    stage1_df.iloc[
        validation_indices
    ][feature_columns].apply(
        lambda row: hash(tuple(row)),
        axis=1
    ),
    sort=False
)[0]

training_group_hashes = set(
    stage1_df.iloc[
        training_indices
    ][feature_columns].apply(
        lambda row: hash(tuple(row)),
        axis=1
    )
)

validation_group_hashes = set(
    stage1_df.iloc[
        validation_indices
    ][feature_columns].apply(
        lambda row: hash(tuple(row)),
        axis=1
    )
)

cross_partition_groups = (
    training_group_hashes &
    validation_group_hashes
)

if len(cross_partition_groups) != 0:
    raise ValueError(
        "Identical feature vectors detected across "
        "training and validation partitions."
    )

print("\n[DUPLICATE-AWARE VALIDATION]")
print(
    f"Training/Validation shared feature vectors : "
    f"{len(cross_partition_groups):,}"
)
print(
    "✓ Identical feature vectors cannot cross the "
    "training/validation boundary"
)

# ------------------------------------------------------------
# 4.5.2.6 Validate Final Taxonomy Coverage
# ------------------------------------------------------------

all_development_classes = np.sort(
    development_data["FinalTarget"].unique()
)

training_classes = np.sort(
    stage1_df.iloc[
        training_indices
    ]["FinalTarget"].unique()
)

validation_classes = np.sort(
    stage1_df.iloc[
        validation_indices
    ]["FinalTarget"].unique()
)

print("\n[FINAL TAXONOMY COVERAGE]")
print(
    f"Development classes : "
    f"{len(all_development_classes)}"
)
print(
    f"Training classes    : "
    f"{len(training_classes)}"
)
print(
    f"Validation classes  : "
    f"{len(validation_classes)}"
)

if not np.array_equal(
    training_classes,
    all_development_classes
):
    raise ValueError(
        "Not all final taxonomy classes are represented "
        "in the training partition."
    )

if not np.array_equal(
    validation_classes,
    all_development_classes
):
    raise ValueError(
        "Not all final taxonomy classes are represented "
        "in the validation partition."
    )

print(
    "✓ All final taxonomy classes represented in training"
)
print(
    "✓ All final taxonomy classes represented in validation"
)

# ------------------------------------------------------------
# 4.5.2.7 Validate Test Isolation
# ------------------------------------------------------------

if len(
    np.intersect1d(
        training_indices,
        test_indices
    )
) != 0:
    raise ValueError(
        "Training and independent test partitions overlap."
    )

if len(
    np.intersect1d(
        validation_indices,
        test_indices
    )
) != 0:
    raise ValueError(
        "Validation and independent test partitions overlap."
    )

print("\n[TEST ISOLATION]")
print(
    "✓ Training and independent test partitions are disjoint"
)
print(
    "✓ Validation and independent test partitions are disjoint"
)

# ------------------------------------------------------------
# 4.5.2.8 Persist Training/Validation Partition Indices
# ------------------------------------------------------------

np.save(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "training_indices.npy",
    training_indices
)

np.save(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "validation_indices.npy",
    validation_indices
)

partition_metadata = {
    "stage": "4.5.2",
    "strategy": "development_only_duplicate_aware_split",
    "development_rows": int(len(development_indices)),
    "training_rows": int(len(training_indices)),
    "validation_rows": int(len(validation_indices)),
    "target_validation_fraction": 0.20,
    "random_seed": int(RANDOM_SEED),
    "feature_count": int(len(feature_columns)),
    "grouping_basis": "63 engineered feature vectors",
    "test_partition_used": False,
    "rows_removed": False,
    "labels_modified": False,
    "resampling_performed": False
}

with open(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "training_validation_partition_metadata.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        partition_metadata,
        f,
        indent=2
    )

print("\n[ARTIFACTS]")
print(
    "✓ training_indices.npy persisted"
)
print(
    "✓ validation_indices.npy persisted"
)
print(
    "✓ training_validation_partition_metadata.json persisted"
)

# ------------------------------------------------------------
# 4.5.2.9 Final Validation
# ------------------------------------------------------------

print("\n[FINAL VALIDATION]")
print(
    "✓ Training/validation split performed only "
    "inside Development"
)
print(
    "✓ Independent Test partition remained untouched"
)
print(
    "✓ Approximately 80:20 training/validation target achieved"
)
print(
    "✓ Duplicate feature vectors remain indivisible"
)
print(
    "✓ All final taxonomy classes represented in both subsets"
)
print(
    "✓ No rows removed"
)
print(
    "✓ No labels modified"
)
print(
    "✓ No feature selection performed"
)
print(
    "✓ No scaling performed"
)
print(
    "✓ No resampling performed"
)
print(
    "✓ No model fitting performed"
)

print("\n" + "=" * 72)
print(
    "4.5.2 development-only training/validation strategy "
    "completed successfully."
)
print("=" * 72)

========================================================================
4.5.2 — DEVELOPMENT-ONLY TRAINING/VALIDATION STRATEGY
========================================================================

[DEVELOPMENT PARTITION]
Development rows : 2,265,233
Feature columns  : 63

[FEATURE-VECTOR GROUPING]
Development rows       : 2,265,233
Unique feature groups  : 1,977,912
✓ Group identity uses the 63 engineered features only
✓ FinalTarget is excluded from feature identity

[PARTITION SIZE]
Training rows   : 1,814,018 (80.080857%)
Validation rows : 451,215 (19.919143%)
✓ Every development row assigned exactly once
✓ Training and validation indices are mutually exclusive

[DUPLICATE-AWARE VALIDATION]
Training/Validation shared feature vectors : 0
✓ Identical feature vectors cannot cross the training/validation boundary

[FINAL TAXONOMY COVERAGE]
Development classes : 9
Training classes    : 9
Validation classes  : 9
✓ All final taxonomy classes represented in training
✓ All final taxonomy classes represented in validation

[TEST ISOLATION]
✓ Training and independent test partitions are disjoint
✓ Validation and independent test partitions are disjoint

[ARTIFACTS]
✓ training_indices.npy persisted
✓ validation_indices.npy persisted
✓ training_validation_partition_metadata.json persisted

[FINAL VALIDATION]
✓ Training/validation split performed only inside Development
✓ Independent Test partition remained untouched
✓ Approximately 80:20 training/validation target achieved
✓ Duplicate feature vectors remain indivisible
✓ All final taxonomy classes represented in both subsets
✓ No rows removed
✓ No labels modified
✓ No feature selection performed
✓ No scaling performed
✓ No resampling performed
✓ No model fitting performed

========================================================================
4.5.2 development-only training/validation strategy completed successfully.
========================================================================

# 4.5.3 Duplicate-Aware Training/Validation Construction

The Training and Validation subsets are derived exclusively from the
Development partition established in the preceding subsections.

Because identical engineered feature vectors may occur multiple times
within the Development data, duplicate-group integrity must be preserved
during the Training/Validation construction.

All rows sharing the same 63-dimensional engineered feature vector are
therefore treated as one indivisible feature-vector group.

This subsection independently verifies that:

- repeated feature vectors remain entirely within Training or Validation;
- no identical feature vector occurs across the Training/Validation
  boundary;
- duplicate groups contained within each partition are quantified;
- the persisted partition indices reproduce the intended grouping.

No rows are removed, labels are modified, or feature values are changed.
No feature selection, scaling, resampling, or model fitting is performed.

In [ ]:
# ============================================================
# 4.5.3 — Duplicate-Aware Training/Validation Construction
# ============================================================

print("=" * 72)
print("4.5.3 — DUPLICATE-AWARE TRAINING/VALIDATION CONSTRUCTION")
print("=" * 72)

# ------------------------------------------------------------
# 4.5.3.1 Recover Persisted Training/Validation Indices
# ------------------------------------------------------------

training_indices = np.load(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "training_indices.npy"
)

validation_indices = np.load(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "validation_indices.npy"
)

print("\n[PERSISTED PARTITIONS]")
print(
    f"Training rows   : {len(training_indices):,}"
)
print(
    f"Validation rows : {len(validation_indices):,}"
)

# ------------------------------------------------------------
# 4.5.3.2 Construct Exact Feature-Vector Signatures
# ------------------------------------------------------------

training_feature_hashes = pd.util.hash_pandas_object(
    stage1_df.iloc[
        training_indices
    ][feature_columns],
    index=False
)

validation_feature_hashes = pd.util.hash_pandas_object(
    stage1_df.iloc[
        validation_indices
    ][feature_columns],
    index=False
)

print("\n[FEATURE-VECTOR IDENTITY]")
print(
    f"Feature columns used : {len(feature_columns)}"
)
print(
    "✓ Only the 63 engineered features define "
    "feature-vector identity"
)
print(
    "✓ Target columns are excluded from feature identity"
)

# ------------------------------------------------------------
# 4.5.3.3 Quantify Duplicate Groups Within Each Partition
# ------------------------------------------------------------

training_group_sizes = (
    training_feature_hashes
    .value_counts()
)

validation_group_sizes = (
    validation_feature_hashes
    .value_counts()
)

training_duplicate_groups = (
    training_group_sizes[
        training_group_sizes > 1
    ]
)

validation_duplicate_groups = (
    validation_group_sizes[
        validation_group_sizes > 1
    ]
)

training_duplicate_rows = int(
    training_duplicate_groups.sum()
)

validation_duplicate_rows = int(
    validation_duplicate_groups.sum()
)

training_additional_duplicate_rows = int(
    (training_duplicate_groups - 1).sum()
)

validation_additional_duplicate_rows = int(
    (validation_duplicate_groups - 1).sum()
)

print("\n[WITHIN-PARTITION DUPLICATES]")
print(
    f"Training duplicate groups       : "
    f"{len(training_duplicate_groups):,}"
)
print(
    f"Training duplicate rows         : "
    f"{training_duplicate_rows:,}"
)
print(
    f"Training additional duplicate rows : "
    f"{training_additional_duplicate_rows:,}"
)

print(
    f"Validation duplicate groups     : "
    f"{len(validation_duplicate_groups):,}"
)
print(
    f"Validation duplicate rows       : "
    f"{validation_duplicate_rows:,}"
)
print(
    f"Validation additional duplicate rows : "
    f"{validation_additional_duplicate_rows:,}"
)

# ------------------------------------------------------------
# 4.5.3.4 Verify Zero Cross-Partition Feature-Vector Overlap
# ------------------------------------------------------------

training_feature_groups = set(
    training_feature_hashes.unique()
)

validation_feature_groups = set(
    validation_feature_hashes.unique()
)

cross_partition_feature_groups = (
    training_feature_groups &
    validation_feature_groups
)

if len(cross_partition_feature_groups) != 0:
    raise ValueError(
        "Identical feature vectors detected across the "
        "Training/Validation boundary."
    )

print("\n[CROSS-PARTITION DUPLICATE VALIDATION]")
print(
    f"Training/Validation shared feature vectors : "
    f"{len(cross_partition_feature_groups):,}"
)
print(
    "✓ No identical engineered feature vectors cross "
    "the Training/Validation boundary"
)

# ------------------------------------------------------------
# 4.5.3.5 Validate Training/Validation Coverage
# ------------------------------------------------------------

if (
    len(training_indices) +
    len(validation_indices)
) != len(development_indices):
    raise ValueError(
        "Training and Validation do not account for every "
        "Development row."
    )

if len(
    np.intersect1d(
        training_indices,
        validation_indices
    )
) != 0:
    raise ValueError(
        "Training and Validation row indices overlap."
    )

print("\n[DEVELOPMENT COVERAGE]")
print(
    f"Development rows       : "
    f"{len(development_indices):,}"
)
print(
    f"Training + Validation  : "
    f"{len(training_indices) + len(validation_indices):,}"
)
print(
    "✓ Every Development row belongs to exactly one "
    "inner partition"
)

# ------------------------------------------------------------
# 4.5.3.6 Persist Duplicate-Aware Diagnostics
# ------------------------------------------------------------

duplicate_partition_summary = pd.DataFrame({
    "Partition": [
        "Training",
        "Validation"
    ],
    "Rows": [
        len(training_indices),
        len(validation_indices)
    ],
    "Unique_Feature_Vectors": [
        len(training_feature_groups),
        len(validation_feature_groups)
    ],
    "Duplicate_Feature_Vector_Groups": [
        len(training_duplicate_groups),
        len(validation_duplicate_groups)
    ],
    "Rows_In_Duplicate_Groups": [
        training_duplicate_rows,
        validation_duplicate_rows
    ],
    "Additional_Duplicate_Rows": [
        training_additional_duplicate_rows,
        validation_additional_duplicate_rows
    ]
})

duplicate_partition_summary.to_csv(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "training_validation_duplicate_summary.csv",
    index=False
)

cross_partition_summary = pd.DataFrame({
    "Metric": [
        "Training feature-vector groups",
        "Validation feature-vector groups",
        "Shared feature-vector groups",
        "Training duplicate groups",
        "Validation duplicate groups",
        "Training rows in duplicate groups",
        "Validation rows in duplicate groups"
    ],
    "Value": [
        len(training_feature_groups),
        len(validation_feature_groups),
        len(cross_partition_feature_groups),
        len(training_duplicate_groups),
        len(validation_duplicate_groups),
        training_duplicate_rows,
        validation_duplicate_rows
    ]
})

cross_partition_summary.to_csv(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "training_validation_leakage_summary.csv",
    index=False
)

print("\n[ARTIFACTS]")
print(
    "✓ training_validation_duplicate_summary.csv persisted"
)
print(
    "✓ training_validation_leakage_summary.csv persisted"
)

# ------------------------------------------------------------
# 4.5.3.7 Final Validation
# ------------------------------------------------------------

print("\n[FINAL VALIDATION]")
print(
    "✓ Training and Validation recovered from persisted indices"
)
print(
    "✓ Duplicate groups quantified independently "
    "within both partitions"
)
print(
    "✓ Zero shared feature-vector groups detected"
)
print(
    "✓ Every Development row assigned exactly once"
)
print(
    "✓ Training/Validation partitions remain mutually exclusive"
)
print(
    "✓ No rows removed"
)
print(
    "✓ No labels modified"
)
print(
    "✓ No feature values modified"
)
print(
    "✓ No feature selection performed"
)
print(
    "✓ No scaling performed"
)
print(
    "✓ No resampling performed"
)
print(
    "✓ No model fitting performed"
)

print("\n" + "=" * 72)
print(
    "4.5.3 duplicate-aware training/validation construction "
    "completed successfully."
)
print("=" * 72)

========================================================================
4.5.3 — DUPLICATE-AWARE TRAINING/VALIDATION CONSTRUCTION
========================================================================

[PERSISTED PARTITIONS]
Training rows   : 1,814,018
Validation rows : 451,215

[FEATURE-VECTOR IDENTITY]
Feature columns used : 63
✓ Only the 63 engineered features define feature-vector identity
✓ Target columns are excluded from feature identity

[WITHIN-PARTITION DUPLICATES]
Training duplicate groups       : 65,390
Training duplicate rows         : 297,079
Training additional duplicate rows : 231,689
Validation duplicate groups     : 16,234
Validation duplicate rows       : 71,866
Validation additional duplicate rows : 55,632

[CROSS-PARTITION DUPLICATE VALIDATION]
Training/Validation shared feature vectors : 0
✓ No identical engineered feature vectors cross the Training/Validation boundary

[DEVELOPMENT COVERAGE]
Development rows       : 2,265,233
Training + Validation  : 2,265,233
✓ Every Development row belongs to exactly one inner partition

[ARTIFACTS]
✓ training_validation_duplicate_summary.csv persisted
✓ training_validation_leakage_summary.csv persisted

[FINAL VALIDATION]
✓ Training and Validation recovered from persisted indices
✓ Duplicate groups quantified independently within both partitions
✓ Zero shared feature-vector groups detected
✓ Every Development row assigned exactly once
✓ Training/Validation partitions remain mutually exclusive
✓ No rows removed
✓ No labels modified
✓ No feature values modified
✓ No feature selection performed
✓ No scaling performed
✓ No resampling performed
✓ No model fitting performed

========================================================================
4.5.3 duplicate-aware training/validation construction completed successfully.
========================================================================

# 4.5.4 Partition Distribution Analysis

This subsection analyzes the final taxonomy distribution across the
Training, Validation, and independent Test partitions.

The purpose is to verify that all nine final taxonomy classes are
represented across the three partitions and to quantify the empirical
class distribution within each partition.

The analysis reports both absolute class counts and relative
percentages, allowing the distribution of the Training and Validation
subsets to be compared with the independently isolated Test partition.

No class balancing, resampling, weighting, or label modification is
performed in this subsection.

The independent Test partition remains untouched and is used only for
distribution analysis at this stage.

In [ ]:
# ============================================================
# 4.5.4 — Partition Distribution Analysis
# ============================================================

print("=" * 72)
print("4.5.4 — PARTITION DISTRIBUTION ANALYSIS")
print("=" * 72)

# ------------------------------------------------------------
# 4.5.4.1 Recover Persisted Partition Indices
# ------------------------------------------------------------

training_indices = np.load(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "training_indices.npy"
)

validation_indices = np.load(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "validation_indices.npy"
)

test_indices = np.load(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "test_indices.npy"
)

print("\n[PARTITIONS]")
print(
    f"Training rows   : {len(training_indices):,}"
)
print(
    f"Validation rows : {len(validation_indices):,}"
)
print(
    f"Test rows       : {len(test_indices):,}"
)

# ------------------------------------------------------------
# 4.5.4.2 Define Final Taxonomy Reference
# ------------------------------------------------------------

final_taxonomy_labels = {
    0: "BENIGN",
    1: "DDoS",
    2: "Port Scan",
    3: "Brute Force",
    4: "Bot",
    5: "Web Attack",
    6: "Infiltration",
    7: "DoS",
    8: "Heartbleed"
}

all_final_classes = np.sort(
    stage1_df["FinalTarget"].unique()
)

if not np.array_equal(
    all_final_classes,
    np.array(list(final_taxonomy_labels.keys()))
):
    raise ValueError(
        "Final taxonomy classes do not match the "
        "persisted 9-class taxonomy definition."
    )

# ------------------------------------------------------------
# 4.5.4.3 Construct Partition Class Distributions
# ------------------------------------------------------------

partition_indices = {
    "Training": training_indices,
    "Validation": validation_indices,
    "Test": test_indices
}

partition_distribution_rows = []

for partition_name, indices in partition_indices.items():

    partition_targets = stage1_df.iloc[
        indices
    ]["FinalTarget"]

    class_counts = (
        partition_targets
        .value_counts()
        .reindex(
            all_final_classes,
            fill_value=0
        )
        .sort_index()
    )

    class_percentages = (
        class_counts /
        len(indices) *
        100
    )

    for class_id in all_final_classes:

        partition_distribution_rows.append({
            "Partition": partition_name,
            "FinalTarget": int(class_id),
            "FinalTargetName": final_taxonomy_labels[
                int(class_id)
            ],
            "Count": int(
                class_counts.loc[class_id]
            ),
            "Percentage": float(
                class_percentages.loc[class_id]
            )
        })

partition_distribution = pd.DataFrame(
    partition_distribution_rows
)

# ------------------------------------------------------------
# 4.5.4.4 Display Training Distribution
# ------------------------------------------------------------

print("\n[TRAINING DISTRIBUTION]")

display(
    partition_distribution[
        partition_distribution["Partition"] == "Training"
    ][
        [
            "FinalTarget",
            "FinalTargetName",
            "Count",
            "Percentage"
        ]
    ].reset_index(drop=True)
)

# ------------------------------------------------------------
# 4.5.4.5 Display Validation Distribution
# ------------------------------------------------------------

print("\n[VALIDATION DISTRIBUTION]")

display(
    partition_distribution[
        partition_distribution["Partition"] == "Validation"
    ][
        [
            "FinalTarget",
            "FinalTargetName",
            "Count",
            "Percentage"
        ]
    ].reset_index(drop=True)
)

# ------------------------------------------------------------
# 4.5.4.6 Display Test Distribution
# ------------------------------------------------------------

print("\n[TEST DISTRIBUTION]")

display(
    partition_distribution[
        partition_distribution["Partition"] == "Test"
    ][
        [
            "FinalTarget",
            "FinalTargetName",
            "Count",
            "Percentage"
        ]
    ].reset_index(drop=True)
)

# ------------------------------------------------------------
# 4.5.4.7 Verify Class Coverage
# ------------------------------------------------------------

print("\n[CLASS COVERAGE]")

for partition_name, indices in partition_indices.items():

    partition_classes = np.sort(
        stage1_df.iloc[
            indices
        ]["FinalTarget"].unique()
    )

    if not np.array_equal(
        partition_classes,
        all_final_classes
    ):
        raise ValueError(
            f"{partition_name} does not contain "
            "all final taxonomy classes."
        )

    print(
        f"✓ {partition_name} contains all "
        f"{len(all_final_classes)} final taxonomy classes"
    )

# ------------------------------------------------------------
# 4.5.4.8 Compare Partition Percentages
# ------------------------------------------------------------

distribution_comparison = (
    partition_distribution
    .pivot(
        index=[
            "FinalTarget",
            "FinalTargetName"
        ],
        columns="Partition",
        values="Percentage"
    )
    .reset_index()
)

distribution_comparison["Training_vs_Test_Difference"] = (
    distribution_comparison["Training"] -
    distribution_comparison["Test"]
)

distribution_comparison["Validation_vs_Test_Difference"] = (
    distribution_comparison["Validation"] -
    distribution_comparison["Test"]
)

print("\n[DISTRIBUTION COMPARISON]")
display(
    distribution_comparison
)

# ------------------------------------------------------------
# 4.5.4.9 Quantify Partition Size Ratios
# ------------------------------------------------------------

partition_sizes = pd.DataFrame({
    "Partition": [
        "Training",
        "Validation",
        "Test"
    ],
    "Rows": [
        len(training_indices),
        len(validation_indices),
        len(test_indices)
    ]
})

partition_sizes["Dataset_Percentage"] = (
    partition_sizes["Rows"] /
    len(stage1_df) *
    100
)

print("\n[PARTITION SIZE SUMMARY]")
display(
    partition_sizes
)

# ------------------------------------------------------------
# 4.5.4.10 Persist Distribution Artifacts
# ------------------------------------------------------------

partition_distribution.to_csv(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "partition_class_distribution.csv",
    index=False
)

distribution_comparison.to_csv(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "partition_distribution_comparison.csv",
    index=False
)

partition_sizes.to_csv(
    DUPLICATE_LEAKAGE_AUDIT_DIR /
    "partition_size_summary.csv",
    index=False
)

print("\n[ARTIFACTS]")
print(
    "✓ partition_class_distribution.csv persisted"
)
print(
    "✓ partition_distribution_comparison.csv persisted"
)
print(
    "✓ partition_size_summary.csv persisted"
)

# ------------------------------------------------------------
# 4.5.4.11 Final Validation
# ------------------------------------------------------------

print("\n[FINAL VALIDATION]")
print(
    "✓ Training distribution analyzed"
)
print(
    "✓ Validation distribution analyzed"
)
print(
    "✓ Independent Test distribution analyzed"
)
print(
    "✓ All 9 final taxonomy classes represented "
    "in every partition"
)
print(
    "✓ Absolute class counts persisted"
)
print(
    "✓ Relative class percentages persisted"
)
print(
    "✓ Cross-partition distribution comparison persisted"
)
print(
    "✓ No rows removed"
)
print(
    "✓ No labels modified"
)
print(
    "✓ No resampling performed"
)
print(
    "✓ No class weighting performed"
)
print(
    "✓ No feature selection performed"
)
print(
    "✓ No scaling performed"
)
print(
    "✓ No model fitting performed"
)

print("\n" + "=" * 72)
print(
    "4.5.4 partition distribution analysis "
    "completed successfully."
)
print("=" * 72)

========================================================================
4.5.4 — PARTITION DISTRIBUTION ANALYSIS
========================================================================

[PARTITIONS]
Training rows   : 1,814,018
Validation rows : 451,215
Test rows       : 565,510

[TRAINING DISTRIBUTION]

   FinalTarget FinalTargetName    Count  Percentage
0            0          BENIGN  1448197   79.833662
1            1            DDoS    81968    4.518588
2            2       Port Scan   101723    5.607607
3            3     Brute Force     9325    0.514052
4            4             Bot     1270    0.070010
5            5      Web Attack     1389    0.076570
6            6    Infiltration       15    0.000827
7            7             DoS   170125    9.378352
8            8      Heartbleed        6    0.000331

[VALIDATION DISTRIBUTION]

   FinalTarget FinalTargetName   Count  Percentage
0            0          BENIGN  369501   81.890230
1            1            DDoS   20458    4.533980
2            2       Port Scan   25261    5.598440
3            3     Brute Force    1862    0.412664
4            4             Bot     297    0.065822
5            5      Web Attack     363    0.080449
6            6    Infiltration      13    0.002881
7            7             DoS   33456    7.414647
8            8      Heartbleed       4    0.000886

[TEST DISTRIBUTION]

   FinalTarget FinalTargetName   Count  Percentage
0            0          BENIGN  455399   80.528903
1            1            DDoS   25601    4.527064
2            2       Port Scan   31946    5.649060
3            3     Brute Force    2648    0.468250
4            4             Bot     399    0.070556
5            5      Web Attack     428    0.075684
6            6    Infiltration       8    0.001415
7            7             DoS   49080    8.678892
8            8      Heartbleed       1    0.000177

[CLASS COVERAGE]
✓ Training contains all 9 final taxonomy classes
✓ Validation contains all 9 final taxonomy classes
✓ Test contains all 9 final taxonomy classes

[DISTRIBUTION COMPARISON]

Partition,FinalTarget,FinalTargetName,Test,Training,Validation,Training_vs_Test_Difference,Validation_vs_Test_Difference
0,0,BENIGN,80.528903,79.833662,81.890230,-0.695241,1.361327
1,1,DDoS,4.527064,4.518588,4.533980,-0.008476,0.006916
2,2,Port Scan,5.649060,5.607607,5.598440,-0.041453,-0.050620
3,3,Brute Force,0.468250,0.514052,0.412664,0.045802,-0.055586
4,4,Bot,0.070556,0.070010,0.065822,-0.000545,-0.004734
5,5,Web Attack,0.075684,0.076570,0.080449,0.000886,0.004766
6,6,Infiltration,0.001415,0.000827,0.002881,-0.000588,0.001466
7,7,DoS,8.678892,9.378352,7.414647,0.699461,-1.264245
8,8,Heartbleed,0.000177,0.000331,0.000886,0.000154,0.000710

[PARTITION SIZE SUMMARY]

    Partition     Rows  Dataset_Percentage
0    Training  1814018           64.082751
1  Validation   451215           15.939808
2        Test   565510           19.977441

[ARTIFACTS]
✓ partition_class_distribution.csv persisted
✓ partition_distribution_comparison.csv persisted
✓ partition_size_summary.csv persisted

[FINAL VALIDATION]
✓ Training distribution analyzed
✓ Validation distribution analyzed
✓ Independent Test distribution analyzed
✓ All 9 final taxonomy classes represented in every partition
✓ Absolute class counts persisted
✓ Relative class percentages persisted
✓ Cross-partition distribution comparison persisted
✓ No rows removed
✓ No labels modified
✓ No resampling performed
✓ No class weighting performed
✓ No feature selection performed
✓ No scaling performed
✓ No model fitting performed

========================================================================
4.5.4 partition distribution analysis completed successfully.
========================================================================

# 4.5.5 Final Train/Validation/Test Leakage Validation

This subsection performs the final integrity check across the Training, Validation, and independent Test partitions. It verifies complete row coverage, mutual exclusivity of partition indices, absence of identical engineered feature vectors across partition boundaries, and representation of all final taxonomy classes in each partition.

The independent Test partition remains completely isolated from all training and validation preparation. No rows, labels, feature values, preprocessing parameters, resampling, feature selection, or model fitting are performed in this subsection.

The validation results are persisted as a reproducibility artifact for downstream model development and research documentation.

In [ ]:
# ============================================================
# 4.5.5 — Final Train/Validation/Test Leakage Validation
# ============================================================

print("=" * 72)
print("4.5.5 — FINAL TRAIN/VALIDATION/TEST LEAKAGE VALIDATION")
print("=" * 72)

# ------------------------------------------------------------
# 4.5.5.1 Partition Coverage
# ------------------------------------------------------------

print("\n[PARTITION COVERAGE]")

stage1_row_count = len(stage1_df)

training_count = len(training_indices)
validation_count = len(validation_indices)
test_count = len(test_indices)

partitioned_row_count = (
    training_count +
    validation_count +
    test_count
)

print(f"Stage-1 rows          : {stage1_row_count:,}")
print(f"Training rows         : {training_count:,}")
print(f"Validation rows       : {validation_count:,}")
print(f"Test rows             : {test_count:,}")
print(f"Partitioned rows      : {partitioned_row_count:,}")

if partitioned_row_count != stage1_row_count:
    raise ValueError(
        "Partition coverage mismatch: "
        "training + validation + test rows do not equal Stage-1 rows."
    )

print("✓ Every Stage-1 row is represented exactly once")

# ------------------------------------------------------------
# 4.5.5.2 Index-Level Exclusivity
# ------------------------------------------------------------

print("\n[INDEX-LEVEL EXCLUSIVITY]")

training_set = set(training_indices.tolist())
validation_set = set(validation_indices.tolist())
test_set = set(test_indices.tolist())

training_validation_overlap = len(
    training_set.intersection(validation_set)
)

training_test_overlap = len(
    training_set.intersection(test_set)
)

validation_test_overlap = len(
    validation_set.intersection(test_set)
)

print(
    f"Training/Validation index overlap : "
    f"{training_validation_overlap:,}"
)

print(
    f"Training/Test index overlap       : "
    f"{training_test_overlap:,}"
)

print(
    f"Validation/Test index overlap     : "
    f"{validation_test_overlap:,}"
)

if (
    training_validation_overlap != 0
    or training_test_overlap != 0
    or validation_test_overlap != 0
):
    raise ValueError(
        "Partition index overlap detected."
    )

print("✓ All three partitions are mutually exclusive")

# ------------------------------------------------------------
# 4.5.5.3 Feature-Vector Leakage Validation
# ------------------------------------------------------------

print("\n[FEATURE-VECTOR LEAKAGE VALIDATION]")

if len(feature_columns) != 63:
    raise ValueError(
        f"Expected 63 engineered feature columns, "
        f"found {len(feature_columns)}."
    )

print(
    f"Feature-vector identity : "
    f"{len(feature_columns)} engineered features"
)

training_feature_hashes = pd.util.hash_pandas_object(
    stage1_df.loc[
        training_indices,
        feature_columns
    ],
    index=False
)

validation_feature_hashes = pd.util.hash_pandas_object(
    stage1_df.loc[
        validation_indices,
        feature_columns
    ],
    index=False
)

test_feature_hashes = pd.util.hash_pandas_object(
    stage1_df.loc[
        test_indices,
        feature_columns
    ],
    index=False
)

training_validation_feature_overlap = len(
    set(training_feature_hashes)
    .intersection(set(validation_feature_hashes))
)

training_test_feature_overlap = len(
    set(training_feature_hashes)
    .intersection(set(test_feature_hashes))
)

validation_test_feature_overlap = len(
    set(validation_feature_hashes)
    .intersection(set(test_feature_hashes))
)

print(
    f"Training/Validation shared feature vectors : "
    f"{training_validation_feature_overlap:,}"
)

print(
    f"Training/Test shared feature vectors       : "
    f"{training_test_feature_overlap:,}"
)

print(
    f"Validation/Test shared feature vectors     : "
    f"{validation_test_feature_overlap:,}"
)

if (
    training_validation_feature_overlap != 0
    or training_test_feature_overlap != 0
    or validation_test_feature_overlap != 0
):
    raise ValueError(
        "Identical engineered feature vectors detected "
        "across partition boundaries."
    )

print(
    "✓ No identical engineered feature vectors cross "
    "any partition boundary"
)

# ------------------------------------------------------------
# 4.5.5.4 Final Taxonomy Coverage
# ------------------------------------------------------------

print("\n[FINAL TAXONOMY COVERAGE]")

training_classes = set(
    stage1_df.loc[
        training_indices,
        "FinalTarget"
    ].unique()
)

validation_classes = set(
    stage1_df.loc[
        validation_indices,
        "FinalTarget"
    ].unique()
)

test_classes = set(
    stage1_df.loc[
        test_indices,
        "FinalTarget"
    ].unique()
)

all_final_classes = set(
    stage1_df["FinalTarget"].unique()
)

print(
    f"All final taxonomy classes : "
    f"{len(all_final_classes)}"
)

print(
    f"Training classes           : "
    f"{len(training_classes)}"
)

print(
    f"Validation classes         : "
    f"{len(validation_classes)}"
)

print(
    f"Test classes               : "
    f"{len(test_classes)}"
)

if training_classes != all_final_classes:
    raise ValueError(
        "Training partition does not contain all final taxonomy classes."
    )

if validation_classes != all_final_classes:
    raise ValueError(
        "Validation partition does not contain all final taxonomy classes."
    )

if test_classes != all_final_classes:
    raise ValueError(
        "Test partition does not contain all final taxonomy classes."
    )

print("✓ All final taxonomy classes represented in training")
print("✓ All final taxonomy classes represented in validation")
print("✓ All final taxonomy classes represented in test")

# ------------------------------------------------------------
# 4.5.5.5 Independent Test Isolation
# ------------------------------------------------------------

print("\n[INDEPENDENT TEST ISOLATION]")

print("✓ Test partition remains isolated")
print("✓ No test-based preprocessing performed")
print("✓ No test-based feature selection performed")
print("✓ No test-based resampling performed")
print("✓ No model fitting performed")

# ------------------------------------------------------------
# 4.5.5.6 Persist Final Leakage Validation Metadata
# ------------------------------------------------------------

final_leakage_validation_metadata = {
    "stage": "4.5.5",
    "purpose": "Final train/validation/test leakage validation",
    "dataset_rows": int(stage1_row_count),
    "training_rows": int(training_count),
    "validation_rows": int(validation_count),
    "test_rows": int(test_count),
    "feature_count": int(len(feature_columns)),
    "final_taxonomy_class_count": int(len(all_final_classes)),
    "index_overlap": {
        "training_validation": int(
            training_validation_overlap
        ),
        "training_test": int(
            training_test_overlap
        ),
        "validation_test": int(
            validation_test_overlap
        )
    },
    "feature_vector_overlap": {
        "training_validation": int(
            training_validation_feature_overlap
        ),
        "training_test": int(
            training_test_feature_overlap
        ),
        "validation_test": int(
            validation_test_feature_overlap
        )
    },
    "taxonomy_coverage": {
        "training": int(len(training_classes)),
        "validation": int(len(validation_classes)),
        "test": int(len(test_classes))
    },
    "processing_status": {
        "rows_removed": False,
        "labels_modified": False,
        "feature_values_modified": False,
        "feature_selection_performed": False,
        "scaling_performed": False,
        "resampling_performed": False,
        "model_fitting_performed": False
    },
    "validation_status": "PASSED"
}

with open(
    MODEL_PREPARATION_V2_DIR /
    "final_train_validation_test_leakage_validation.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        final_leakage_validation_metadata,
        f,
        indent=4
    )

# ------------------------------------------------------------
# 4.5.5.7 Final Validation
# ------------------------------------------------------------

print("\n[FINAL VALIDATION]")

print("✓ Stage-1 row coverage verified")
print("✓ Training/Validation indices are mutually exclusive")
print("✓ Training/Test indices are mutually exclusive")
print("✓ Validation/Test indices are mutually exclusive")
print("✓ No identical feature vectors cross partition boundaries")
print("✓ All final taxonomy classes represented in training")
print("✓ All final taxonomy classes represented in validation")
print("✓ All final taxonomy classes represented in test")
print("✓ Independent test partition remains isolated")
print("✓ No rows removed")
print("✓ No labels modified")
print("✓ No feature values modified")
print("✓ No feature selection performed")
print("✓ No scaling performed")
print("✓ No resampling performed")
print("✓ No model fitting performed")
print("✓ Final leakage-validation metadata persisted")

print("\n[ARTIFACT]")
print(
    "✓ " +
    str(
        MODEL_PREPARATION_V2_DIR /
        "final_train_validation_test_leakage_validation.json"
    )
)

print("\n" + "=" * 72)
print(
    "4.5.5 final train/validation/test leakage validation "
    "completed successfully."
)
print("=" * 72)

========================================================================
4.5.5 — FINAL TRAIN/VALIDATION/TEST LEAKAGE VALIDATION
========================================================================

[PARTITION COVERAGE]
Stage-1 rows          : 2,830,743
Training rows         : 1,814,018
Validation rows       : 451,215
Test rows             : 565,510
Partitioned rows      : 2,830,743
✓ Every Stage-1 row is represented exactly once

[INDEX-LEVEL EXCLUSIVITY]
Training/Validation index overlap : 0
Training/Test index overlap       : 0
Validation/Test index overlap     : 0
✓ All three partitions are mutually exclusive

[FEATURE-VECTOR LEAKAGE VALIDATION]
Feature-vector identity : 63 engineered features
Training/Validation shared feature vectors : 0
Training/Test shared feature vectors       : 0
Validation/Test shared feature vectors     : 0
✓ No identical engineered feature vectors cross any partition boundary

[FINAL TAXONOMY COVERAGE]
All final taxonomy classes : 9
Training classes           : 9
Validation classes         : 9
Test classes               : 9
✓ All final taxonomy classes represented in training
✓ All final taxonomy classes represented in validation
✓ All final taxonomy classes represented in test

[INDEPENDENT TEST ISOLATION]
✓ Test partition remains isolated
✓ No test-based preprocessing performed
✓ No test-based feature selection performed
✓ No test-based resampling performed
✓ No model fitting performed

[FINAL VALIDATION]
✓ Stage-1 row coverage verified
✓ Training/Validation indices are mutually exclusive
✓ Training/Test indices are mutually exclusive
✓ Validation/Test indices are mutually exclusive
✓ No identical feature vectors cross partition boundaries
✓ All final taxonomy classes represented in training
✓ All final taxonomy classes represented in validation
✓ All final taxonomy classes represented in test
✓ Independent test partition remains isolated
✓ No rows removed
✓ No labels modified
✓ No feature values modified
✓ No feature selection performed
✓ No scaling performed
✓ No resampling performed
✓ No model fitting performed
✓ Final leakage-validation metadata persisted

[ARTIFACT]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/final_train_validation_test_leakage_validation.json

========================================================================
4.5.5 final train/validation/test leakage validation completed successfully.
========================================================================

# 4.5.6 Partition Artifact Persistence & Reproducibility

This subsection finalizes the development, validation, and test partitioning stage by persisting the complete partition configuration, index artifacts, distribution summaries, leakage-validation results, and reproducibility metadata.

The persisted artifacts provide a reproducible record of the partition architecture established in Sections 4.5.1–4.5.5. The independent test partition remains isolated and is not used for feature selection, preprocessing fitting, resampling, or model development.

No new data transformation, feature selection, scaling, resampling, or model fitting is performed in this subsection.

In [ ]:
# ============================================================
# 4.5.6 — Partition Artifact Persistence & Reproducibility
# ============================================================

import json
import hashlib
from pathlib import Path
import numpy as np

print("=" * 72)
print("4.5.6 — PARTITION ARTIFACT PERSISTENCE & REPRODUCIBILITY")
print("=" * 72)

# ------------------------------------------------------------
# 4.5.6.1 Define Existing Partition Artifact Paths
# ------------------------------------------------------------

PARTITION_ARTIFACT_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "duplicate_leakage_audit"
)

DEVELOPMENT_INDICES_PATH = (
    PARTITION_ARTIFACT_DIR /
    "development_indices.npy"
)

TEST_INDICES_PATH = (
    PARTITION_ARTIFACT_DIR /
    "test_indices.npy"
)

TRAINING_INDICES_PATH = (
    PARTITION_ARTIFACT_DIR /
    "training_indices.npy"
)

VALIDATION_INDICES_PATH = (
    PARTITION_ARTIFACT_DIR /
    "validation_indices.npy"
)

# Existing metadata and analysis artifacts
EXISTING_PARTITION_ARTIFACTS = [
    PARTITION_ARTIFACT_DIR /
    "duplicate_aware_partition_strategy.json",

    PARTITION_ARTIFACT_DIR /
    "leakage_aware_partition_metadata.json",

    PARTITION_ARTIFACT_DIR /
    "partition_integrity_metadata.json",

    PARTITION_ARTIFACT_DIR /
    "development_class_distribution.csv",

    PARTITION_ARTIFACT_DIR /
    "test_class_distribution.csv",

    PARTITION_ARTIFACT_DIR /
    "training_validation_partition_metadata.json",

    PARTITION_ARTIFACT_DIR /
    "training_validation_duplicate_summary.csv",

    PARTITION_ARTIFACT_DIR /
    "training_validation_leakage_summary.csv",

    PARTITION_ARTIFACT_DIR /
    "partition_class_distribution.csv",

    PARTITION_ARTIFACT_DIR /
    "partition_distribution_comparison.csv",

    PARTITION_ARTIFACT_DIR /
    "partition_size_summary.csv",

    PARTITION_ARTIFACT_DIR /
    "final_train_validation_test_leakage_validation.json",
]

# ------------------------------------------------------------
# 4.5.6.2 Validate Required Partition Artifacts
# ------------------------------------------------------------

required_partition_files = {
    "Development indices": DEVELOPMENT_INDICES_PATH,
    "Test indices": TEST_INDICES_PATH,
    "Training indices": TRAINING_INDICES_PATH,
    "Validation indices": VALIDATION_INDICES_PATH,
}

missing_partition_files = [
    name
    for name, path in required_partition_files.items()
    if not path.is_file()
]

if missing_partition_files:
    raise FileNotFoundError(
        "Required partition artifacts are missing:\n"
        + "\n".join(
            f"  - {name}"
            for name in missing_partition_files
        )
    )

print("\n[PARTITION ARTIFACTS]")
print("✓ Development indices found")
print("✓ Test indices found")
print("✓ Training indices found")
print("✓ Validation indices found")

# ------------------------------------------------------------
# 4.5.6.3 Reload Persisted Partition Indices
# ------------------------------------------------------------

development_indices = np.load(
    DEVELOPMENT_INDICES_PATH
)

test_indices = np.load(
    TEST_INDICES_PATH
)

training_indices = np.load(
    TRAINING_INDICES_PATH
)

validation_indices = np.load(
    VALIDATION_INDICES_PATH
)

print("\n[PERSISTED PARTITION SIZES]")
print(
    f"Development rows : "
    f"{len(development_indices):,}"
)
print(
    f"Training rows    : "
    f"{len(training_indices):,}"
)
print(
    f"Validation rows  : "
    f"{len(validation_indices):,}"
)
print(
    f"Test rows        : "
    f"{len(test_indices):,}"
)

# ------------------------------------------------------------
# 4.5.6.4 Reproducibility Integrity Checks
# ------------------------------------------------------------

if len(
    np.intersect1d(
        training_indices,
        validation_indices
    )
) != 0:
    raise ValueError(
        "Training and validation indices overlap."
    )

if len(
    np.intersect1d(
        training_indices,
        test_indices
    )
) != 0:
    raise ValueError(
        "Training and test indices overlap."
    )

if len(
    np.intersect1d(
        validation_indices,
        test_indices
    )
) != 0:
    raise ValueError(
        "Validation and test indices overlap."
    )

if len(
    np.intersect1d(
        development_indices,
        test_indices
    )
) != 0:
    raise ValueError(
        "Development and test indices overlap."
    )

if not np.array_equal(
    np.sort(
        np.concatenate(
            [
                training_indices,
                validation_indices
            ]
        )
    ),
    np.sort(development_indices)
):
    raise ValueError(
        "Training + validation indices do not "
        "reconstruct the persisted development partition."
    )

partition_row_count = (
    len(training_indices)
    + len(validation_indices)
    + len(test_indices)
)

if partition_row_count != len(
    development_indices
) + len(test_indices):
    raise ValueError(
        "Persisted partition row counts are inconsistent."
    )

print("\n[REPRODUCIBILITY VALIDATION]")
print("✓ Training indices reloaded successfully")
print("✓ Validation indices reloaded successfully")
print("✓ Development indices reloaded successfully")
print("✓ Test indices reloaded successfully")
print("✓ Training and validation are mutually exclusive")
print("✓ Training and test are mutually exclusive")
print("✓ Validation and test are mutually exclusive")
print("✓ Training + validation reconstruct Development")
print("✓ Persisted partition sizes are internally consistent")

# ------------------------------------------------------------
# 4.5.6.5 Compute Artifact Checksums
# ------------------------------------------------------------

def sha256_file(path):
    sha256 = hashlib.sha256()

    with open(path, "rb") as f:
        for chunk in iter(
            lambda: f.read(1024 * 1024),
            b""
        ):
            sha256.update(chunk)

    return sha256.hexdigest()


artifact_manifest = {}

for path in required_partition_files.values():

    artifact_manifest[str(path)] = {
        "exists": path.is_file(),
        "size_bytes": path.stat().st_size,
        "sha256": sha256_file(path)
    }

# Include existing Stage-5 metadata/analysis artifacts
for path in EXISTING_PARTITION_ARTIFACTS:

    if path.is_file():
        artifact_manifest[str(path)] = {
            "exists": True,
            "size_bytes": path.stat().st_size,
            "sha256": sha256_file(path)
        }

# ------------------------------------------------------------
# 4.5.6.6 Persist Reproducibility Metadata
# ------------------------------------------------------------

partition_reproducibility_metadata = {
    "notebook_stage": "4.5",
    "stage_name": (
        "Development, Validation, and Test Partitioning"
    ),
    "final_subsection": (
        "4.5.6 Partition Artifact Persistence & Reproducibility"
    ),

    "random_seed": int(RANDOM_SEED),

    "source_stage": "Stage-1 feature-engineered dataset",
    "source_dataset_path": str(STAGE1_DATA_PATH),

    "target_column": str(TARGET_COLUMN),

    "feature_count": 63,

    "partition_architecture": {
        "development_rows": int(
            len(development_indices)
        ),
        "training_rows": int(
            len(training_indices)
        ),
        "validation_rows": int(
            len(validation_indices)
        ),
        "test_rows": int(
            len(test_indices)
        ),
        "development_target_fraction": 0.80,
        "training_target_fraction_within_development": 0.80,
        "validation_target_fraction_within_development": 0.20,
        "test_target_fraction": 0.20
    },

    "leakage_control": {
        "duplicate_aware": True,
        "feature_vector_identity": (
            "63 engineered features only"
        ),
        "cross_partition_identical_feature_vectors": 0,
        "test_partition_isolated": True
    },

    "processing_policy": {
        "rows_removed": False,
        "labels_modified": False,
        "feature_values_modified": False,
        "feature_selection_performed": False,
        "correlation_pruning_performed": False,
        "scaling_performed": False,
        "resampling_performed": False,
        "model_fitting_performed": False
    },

    "downstream_policy": {
        "feature_selection": (
            "Training data only"
        ),
        "scaling": (
            "Fit on Training data only; "
            "apply to Validation and Test"
        ),
        "imbalance_handling": (
            "Training data only; "
            "model-specific strategy"
        ),
        "test_usage": (
            "Independent final evaluation only"
        )
    },

    "artifact_manifest": artifact_manifest
}

REPRODUCIBILITY_METADATA_PATH = (
    MODEL_PREPARATION_V2_DIR /
    "partition_reproducibility_metadata.json"
)

with open(
    REPRODUCIBILITY_METADATA_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        partition_reproducibility_metadata,
        f,
        indent=4
    )

# ------------------------------------------------------------
# 4.5.6.7 Persist Stage-5 Completion Record
# ------------------------------------------------------------

STAGE5_COMPLETION_RECORD = (
    MODEL_PREPARATION_V2_DIR /
    "stage5_partitioning_completion.json"
)

stage5_completion_record = {
    "stage": "4.5",
    "name": (
        "Development, Validation, and Test Partitioning"
    ),
    "status": "completed",

    "completed_subsections": [
        "4.5.1 Partition Architecture & Existing Split Recovery",
        "4.5.2 Development-Only Training/Validation Strategy",
        "4.5.3 Duplicate-Aware Training/Validation Construction",
        "4.5.4 Partition Distribution Analysis",
        "4.5.5 Final Train/Validation/Test Leakage Validation",
        "4.5.6 Partition Artifact Persistence & Reproducibility"
    ],

    "final_partition": {
        "development_rows": int(
            len(development_indices)
        ),
        "training_rows": int(
            len(training_indices)
        ),
        "validation_rows": int(
            len(validation_indices)
        ),
        "test_rows": int(
            len(test_indices)
        )
    },

    "final_guarantees": [
        "All Stage-1 rows assigned exactly once",
        "Training, validation, and test partitions are mutually exclusive",
        "Identical feature vectors cannot cross partition boundaries",
        "All 9 final taxonomy classes are represented in every partition",
        "Independent test partition remains isolated",
        "No rows removed",
        "No labels modified",
        "No feature values modified",
        "No feature selection performed",
        "No scaling performed",
        "No resampling performed",
        "No model fitting performed"
    ],

    "random_seed": int(RANDOM_SEED)
}

with open(
    STAGE5_COMPLETION_RECORD,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        stage5_completion_record,
        f,
        indent=4
    )

# ------------------------------------------------------------
# 4.5.6.8 Final Stage Validation
# ------------------------------------------------------------

print("\n[ARTIFACT PERSISTENCE]")

print(
    "✓ Partition reproducibility metadata persisted"
)

print(
    f"✓ {REPRODUCIBILITY_METADATA_PATH}"
)

print(
    "✓ Stage-5 completion record persisted"
)

print(
    f"✓ {STAGE5_COMPLETION_RECORD}"
)

print(
    f"✓ {len(artifact_manifest)} partition artifacts "
    f"recorded with SHA-256 checksums"
)

print("\n[FINAL STAGE 4.5 VALIDATION]")
print("✓ Development partition persisted")
print("✓ Training partition persisted")
print("✓ Validation partition persisted")
print("✓ Independent Test partition persisted")
print("✓ Partition relationships verified")
print("✓ Reproducibility metadata persisted")
print("✓ Artifact checksums persisted")
print("✓ Stage-5 completion record persisted")
print("✓ No data transformation performed")
print("✓ No model development performed")
print("✓ Independent Test remains isolated")

print("\n" + "=" * 72)
print(
    "4.5.6 partition artifact persistence and "
    "reproducibility completed successfully."
)
print("=" * 72)

========================================================================
4.5.6 — PARTITION ARTIFACT PERSISTENCE & REPRODUCIBILITY
========================================================================

[PARTITION ARTIFACTS]
✓ Development indices found
✓ Test indices found
✓ Training indices found
✓ Validation indices found

[PERSISTED PARTITION SIZES]
Development rows : 2,265,233
Training rows    : 1,814,018
Validation rows  : 451,215
Test rows        : 565,510

[REPRODUCIBILITY VALIDATION]
✓ Training indices reloaded successfully
✓ Validation indices reloaded successfully
✓ Development indices reloaded successfully
✓ Test indices reloaded successfully
✓ Training and validation are mutually exclusive
✓ Training and test are mutually exclusive
✓ Validation and test are mutually exclusive
✓ Training + validation reconstruct Development
✓ Persisted partition sizes are internally consistent

[ARTIFACT PERSISTENCE]
✓ Partition reproducibility metadata persisted
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/partition_reproducibility_metadata.json
✓ Stage-5 completion record persisted
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/stage5_partitioning_completion.json
✓ 15 partition artifacts recorded with SHA-256 checksums

[FINAL STAGE 4.5 VALIDATION]
✓ Development partition persisted
✓ Training partition persisted
✓ Validation partition persisted
✓ Independent Test partition persisted
✓ Partition relationships verified
✓ Reproducibility metadata persisted
✓ Artifact checksums persisted
✓ Stage-5 completion record persisted
✓ No data transformation performed
✓ No model development performed
✓ Independent Test remains isolated

========================================================================
4.5.6 partition artifact persistence and reproducibility completed successfully.
========================================================================

# 4.6 Training-Only Feature Selection

This stage performs feature selection on the 63 engineered features produced in Stage 1. The objective is to reduce unnecessary or redundant features while preserving the information required for reliable intrusion classification.

Feature-selection decisions are made using the Training partition only. The Validation and independent Test partitions remain isolated and are never used to determine which features are retained or removed. This maintains the leakage-free partitioning established in Section 4.5.

The feature-selection process follows two main criteria:

1. Standard-deviation filtering to identify features with negligible variation.
2. Correlation pruning to remove highly redundant features.

The resulting feature set will be applied consistently to Training, Validation, and Test data. The selected features, removed features, thresholds, and diagnostic results will be persisted for reproducibility and for use by the downstream Random Forest, LSTM, and ensemble models.

No scaling, resampling, class balancing, or model training is performed in this stage.

## 4.6.1 Feature Selection Configuration & Training Boundary

This subsection defines the feature-selection configuration and establishes the Training partition as the only source of information for feature-selection decisions.

The initial feature space consists of the 63 engineered features from Stage 1. The original `Target`, `FinalTarget`, and `FinalTargetName` columns are excluded from all feature-selection calculations.

The Training partition established in Section 4.5 will be used to calculate feature variability and pairwise correlations. The resulting decisions will later be applied unchanged to the Validation and independent Test partitions.

The feature-selection procedure will use standard-deviation filtering followed by correlation pruning. Thresholds and configuration parameters are explicitly recorded so that the process can be reproduced in later model-development stages.

No features are removed in this subsection. It only establishes the feature-selection boundary and configuration required for the subsequent statistical analysis.

In [12]:
# ============================================================
# 4.6.1 — Feature Selection Configuration & Training Boundary
# ============================================================

print("=" * 72)
print("4.6.1 — FEATURE SELECTION CONFIGURATION & TRAINING BOUNDARY")
print("=" * 72)

# ------------------------------------------------------------
# 4.6.1.1 Recover Persisted Partition Indices
# ------------------------------------------------------------

PARTITION_ARTIFACT_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "duplicate_leakage_audit"
)

DEVELOPMENT_INDICES_PATH = (
    PARTITION_ARTIFACT_DIR /
    "development_indices.npy"
)

TRAINING_INDICES_PATH = (
    PARTITION_ARTIFACT_DIR /
    "training_indices.npy"
)

VALIDATION_INDICES_PATH = (
    PARTITION_ARTIFACT_DIR /
    "validation_indices.npy"
)

TEST_INDICES_PATH = (
    PARTITION_ARTIFACT_DIR /
    "test_indices.npy"
)

required_partition_paths = {
    "Development": DEVELOPMENT_INDICES_PATH,
    "Training": TRAINING_INDICES_PATH,
    "Validation": VALIDATION_INDICES_PATH,
    "Test": TEST_INDICES_PATH
}

missing_partition_paths = [
    name
    for name, path in required_partition_paths.items()
    if not path.is_file()
]

if missing_partition_paths:
    raise FileNotFoundError(
        "Required persisted partition artifacts are missing:\n"
        + "\n".join(
            f"  - {name}"
            for name in missing_partition_paths
        )
    )

development_indices = np.load(
    DEVELOPMENT_INDICES_PATH
)

training_indices = np.load(
    TRAINING_INDICES_PATH
)

validation_indices = np.load(
    VALIDATION_INDICES_PATH
)

test_indices = np.load(
    TEST_INDICES_PATH
)

# ------------------------------------------------------------
# 4.6.1.2 Define Feature-Selection Input Space
# ------------------------------------------------------------

FEATURE_SELECTION_INPUT_COLUMNS = list(
    feature_columns
)

if len(FEATURE_SELECTION_INPUT_COLUMNS) != 63:
    raise ValueError(
        "Feature-selection input must contain exactly "
        f"63 engineered features, found "
        f"{len(FEATURE_SELECTION_INPUT_COLUMNS)}."
    )

if TARGET_COLUMN in FEATURE_SELECTION_INPUT_COLUMNS:
    raise ValueError(
        f"Original target column '{TARGET_COLUMN}' "
        "must not be part of the feature-selection input."
    )

if "FinalTarget" in FEATURE_SELECTION_INPUT_COLUMNS:
    raise ValueError(
        "FinalTarget must not be part of the "
        "feature-selection input."
    )

if "FinalTargetName" in FEATURE_SELECTION_INPUT_COLUMNS:
    raise ValueError(
        "FinalTargetName must not be part of the "
        "feature-selection input."
    )

# ------------------------------------------------------------
# 4.6.1.3 Establish Training-Only Selection Boundary
# ------------------------------------------------------------

FEATURE_SELECTION_FIT_INDICES = training_indices.copy()

FEATURE_SELECTION_VALIDATION_INDICES = (
    validation_indices.copy()
)

FEATURE_SELECTION_TEST_INDICES = (
    test_indices.copy()
)

if len(
    np.intersect1d(
        FEATURE_SELECTION_FIT_INDICES,
        FEATURE_SELECTION_VALIDATION_INDICES
    )
) != 0:
    raise ValueError(
        "Training and Validation indices overlap."
    )

if len(
    np.intersect1d(
        FEATURE_SELECTION_FIT_INDICES,
        FEATURE_SELECTION_TEST_INDICES
    )
) != 0:
    raise ValueError(
        "Training and Test indices overlap."
    )

if len(
    np.intersect1d(
        FEATURE_SELECTION_VALIDATION_INDICES,
        FEATURE_SELECTION_TEST_INDICES
    )
) != 0:
    raise ValueError(
        "Validation and Test indices overlap."
    )

# ------------------------------------------------------------
# 4.6.1.4 Feature-Selection Policy
# ------------------------------------------------------------

FEATURE_SELECTION_POLICY = {
    "input_feature_count": len(
        FEATURE_SELECTION_INPUT_COLUMNS
    ),
    "feature_identity": (
        "63 engineered features from Stage-1"
    ),
    "fit_partition": "Training",
    "validation_partition": "Validation",
    "test_partition": "Independent Test",
    "selection_fit_scope": (
        "Training data only"
    ),
    "standard_deviation_filtering": True,
    "correlation_pruning": True,
    "validation_used_for_selection": False,
    "test_used_for_selection": False,
    "scaling_performed": False,
    "resampling_performed": False,
    "model_fitting_performed": False,
    "stage1_dataset_modified": False,
    "random_seed": int(RANDOM_SEED)
}

# ------------------------------------------------------------
# 4.6.1.5 Persist Configuration Metadata
# ------------------------------------------------------------

FEATURE_SELECTION_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "feature_selection"
)

FEATURE_SELECTION_DIR.mkdir(
    parents=True,
    exist_ok=True
)

FEATURE_SELECTION_CONFIG_PATH = (
    FEATURE_SELECTION_DIR /
    "feature_selection_configuration.json"
)

feature_selection_configuration = {
    "stage": "4.6",
    "subsection": "4.6.1",
    "name": (
        "Feature Selection Configuration & "
        "Training Boundary"
    ),

    "input_dataset": {
        "stage": "Stage-1",
        "rows": int(len(stage1_df)),
        "engineered_feature_count": int(
            len(FEATURE_SELECTION_INPUT_COLUMNS)
        ),
        "target_column": TARGET_COLUMN,
        "final_target_column": "FinalTarget",
        "final_target_name_column": "FinalTargetName"
    },

    "partition_sizes": {
        "development_rows": int(
            len(development_indices)
        ),
        "training_rows": int(
            len(training_indices)
        ),
        "validation_rows": int(
            len(validation_indices)
        ),
        "test_rows": int(
            len(test_indices)
        )
    },

    "feature_selection_boundary": {
        "fit_partition": "Training",
        "validation_partition": "Validation",
        "test_partition": "Independent Test",
        "training_only_fit": True,
        "validation_used_for_selection": False,
        "test_used_for_selection": False
    },

    "feature_selection_policy": {
        "standard_deviation_filtering": True,
        "correlation_pruning": True,
        "scaling": False,
        "resampling": False,
        "model_fitting": False,
        "stage1_dataset_modified": False
    },

    "input_features": (
        FEATURE_SELECTION_INPUT_COLUMNS
    ),

    "random_seed": int(RANDOM_SEED)
}

with open(
    FEATURE_SELECTION_CONFIG_PATH,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        feature_selection_configuration,
        f,
        indent=4
    )

# ------------------------------------------------------------
# 4.6.1.6 Final Validation
# ------------------------------------------------------------

print("\n[FEATURE-SELECTION INPUT]")

print(
    f"Stage-1 rows              : "
    f"{len(stage1_df):,}"
)

print(
    f"Input engineered features : "
    f"{len(FEATURE_SELECTION_INPUT_COLUMNS)}"
)

print(
    f"Training rows             : "
    f"{len(training_indices):,}"
)

print(
    f"Validation rows           : "
    f"{len(validation_indices):,}"
)

print(
    f"Test rows                 : "
    f"{len(test_indices):,}"
)

print("\n[TRAINING BOUNDARY]")

print(
    "✓ Feature-selection fitting is restricted to Training"
)

print(
    "✓ Validation is excluded from feature-selection fitting"
)

print(
    "✓ Independent Test is excluded from feature-selection fitting"
)

print(
    "✓ Original Target is excluded from the feature space"
)

print(
    "✓ FinalTarget is excluded from the feature space"
)

print(
    "✓ FinalTargetName is excluded from the feature space"
)

print(
    "✓ All 63 engineered features are available as inputs"
)

print("\n[PROCESSING STATUS]")

print(
    "✓ No feature removal performed"
)

print(
    "✓ No correlation pruning performed"
)

print(
    "✓ No scaling performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ Stage-1 dataset remains unchanged"
)

print("\n[ARTIFACT]")

print(
    f"✓ {FEATURE_SELECTION_CONFIG_PATH}"
)

print("\n" + "=" * 72)
print(
    "4.6.1 feature-selection configuration and "
    "training boundary established successfully."
)
print("=" * 72)

========================================================================
4.6.1 — FEATURE SELECTION CONFIGURATION & TRAINING BOUNDARY
========================================================================

[FEATURE-SELECTION INPUT]
Stage-1 rows              : 2,830,743
Input engineered features : 63
Training rows             : 1,814,018
Validation rows           : 451,215
Test rows                 : 565,510

[TRAINING BOUNDARY]
✓ Feature-selection fitting is restricted to Training
✓ Validation is excluded from feature-selection fitting
✓ Independent Test is excluded from feature-selection fitting
✓ Original Target is excluded from the feature space
✓ FinalTarget is excluded from the feature space
✓ FinalTargetName is excluded from the feature space
✓ All 63 engineered features are available as inputs

[PROCESSING STATUS]
✓ No feature removal performed
✓ No correlation pruning performed
✓ No scaling performed
✓ No resampling performed
✓ No model fitting performed
✓ Stage-1 dataset remains unchanged

[ARTIFACT]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_selection/feature_selection_configuration.json

========================================================================
4.6.1 feature-selection configuration and training boundary established successfully.
========================================================================

## 4.6.2 Training-Only Standard Deviation Analysis

This subsection analyzes the variability of all 63 engineered features using the Training partition only.

The purpose is to identify features with zero or extremely low variation that may provide little discriminatory information and can therefore be considered for removal. Standard deviation is calculated exclusively from the Training data so that the independent Validation and Test partitions do not influence feature-selection decisions.

The analysis records the standard deviation of every feature, identifies exact zero-variance features, and summarizes the overall variability of the feature space. No features are removed at this stage.

The results will be used in the following subsection to establish and apply the final standard-deviation filtering rule. The original Stage-1 dataset and all partition assignments remain unchanged.

In [13]:
# ============================================================
# 4.6.2 — Training-Only Standard Deviation Analysis
# ============================================================

print("=" * 72)
print("4.6.2 — TRAINING-ONLY STANDARD DEVIATION ANALYSIS")
print("=" * 72)

# ------------------------------------------------------------
# 4.6.2.1 Recover Training Feature Data
# ------------------------------------------------------------

training_features = stage1_df.loc[
    training_indices,
    feature_columns
].copy()

if training_features.shape[1] != 63:
    raise ValueError(
        f"Expected 63 engineered features, "
        f"found {training_features.shape[1]}."
    )

if training_features.shape[0] != len(training_indices):
    raise ValueError(
        "Training feature rows do not match "
        "the persisted Training partition."
    )

# ------------------------------------------------------------
# 4.6.2.2 Calculate Training-Only Standard Deviations
# ------------------------------------------------------------

training_std = training_features.std(
    axis=0,
    ddof=0
)

training_std_summary = (
    training_std
    .sort_values()
    .rename("Standard_Deviation")
    .reset_index()
    .rename(columns={"index": "Feature"})
)

# ------------------------------------------------------------
# 4.6.2.3 Identify Zero-Variance Features
# ------------------------------------------------------------

zero_variance_features = training_std[
    training_std == 0
].index.tolist()

zero_variance_count = len(
    zero_variance_features
)

# ------------------------------------------------------------
# 4.6.2.4 Variability Summary
# ------------------------------------------------------------

print("\n[TRAINING FEATURE SPACE]")
print(f"Training rows        : {len(training_features):,}")
print(f"Engineered features  : {len(feature_columns)}")

print("\n[STANDARD DEVIATION SUMMARY]")
print(
    f"Minimum standard deviation : "
    f"{training_std.min():.12g}"
)
print(
    f"Median standard deviation  : "
    f"{training_std.median():.12g}"
)
print(
    f"Maximum standard deviation : "
    f"{training_std.max():.12g}"
)

print("\n[ZERO-VARIANCE ANALYSIS]")
print(
    f"Zero-variance features : "
    f"{zero_variance_count}"
)

if zero_variance_count > 0:
    print("\nFeatures with zero variance:")
    for feature in zero_variance_features:
        print(f"  - {feature}")
else:
    print("✓ No exact zero-variance features detected.")

# ------------------------------------------------------------
# 4.6.2.5 Display Lowest-Variance Features
# ------------------------------------------------------------

print("\n[LOWEST-VARIANCE FEATURES]")
display(
    training_std_summary.head(15)
)

# ------------------------------------------------------------
# 4.6.2.6 Persist Standard Deviation Diagnostics
# ------------------------------------------------------------

training_std_summary.to_csv(
    MODEL_PREPARATION_V2_DIR /
    "feature_selection" /
    "training_feature_standard_deviation.csv",
    index=False
)

# ------------------------------------------------------------
# 4.6.2.7 Final Validation
# ------------------------------------------------------------

print("\n[VALIDATION]")
print("✓ Standard deviations calculated using Training data only")
print("✓ All 63 engineered features analyzed")
print("✓ Zero-variance features explicitly identified")
print("✓ Validation data excluded from feature-selection analysis")
print("✓ Independent Test data excluded from feature-selection analysis")
print("✓ No features removed")
print("✓ No feature values modified")
print("✓ No scaling performed")
print("✓ No resampling performed")
print("✓ No model fitting performed")
print("✓ Stage-1 dataset remains unchanged")

print("\n[ARTIFACT]")
print(
    "✓ "
    + str(
        MODEL_PREPARATION_V2_DIR /
        "feature_selection" /
        "training_feature_standard_deviation.csv"
    )
)

print("\n" + "=" * 72)
print(
    "4.6.2 training-only standard deviation analysis "
    "completed successfully."
)
print("=" * 72)

========================================================================
4.6.2 — TRAINING-ONLY STANDARD DEVIATION ANALYSIS
========================================================================

[TRAINING FEATURE SPACE]
Training rows        : 1,814,018
Engineered features  : 63

[STANDARD DEVIATION SUMMARY]
Minimum standard deviation : 0.00990530599966
Median standard deviation  : 3.11514665413
Maximum standard deviation : 18274.2521305

[ZERO-VARIANCE ANALYSIS]
Zero-variance features : 0
✓ No exact zero-variance features detected.

[LOWEST-VARIANCE FEATURES]

                   Feature  Standard_Deviation
0            Fwd URG Flags            0.009905
1           RST Flag Count            0.015448
2           ECE Flag Count            0.015466
3           FIN Flag Count            0.174249
4            Fwd PSH Flags            0.211248
5           URG Flag Count            0.292513
6            Down/Up Ratio            0.366390
7           PSH Flag Count            0.457135
8           ACK Flag Count            0.466920
9        Total Fwd Packets            0.768988
10        act_data_pkt_fwd            0.822133
11  Total Backward Packets            0.912385
12       Fwd Header Length            0.977485
13  Fwd Packet Length Mean            1.658507
14    Avg Fwd Segment Size            1.658507

[VALIDATION]
✓ Standard deviations calculated using Training data only
✓ All 63 engineered features analyzed
✓ Zero-variance features explicitly identified
✓ Validation data excluded from feature-selection analysis
✓ Independent Test data excluded from feature-selection analysis
✓ No features removed
✓ No feature values modified
✓ No scaling performed
✓ No resampling performed
✓ No model fitting performed
✓ Stage-1 dataset remains unchanged

[ARTIFACT]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_selection/training_feature_standard_deviation.csv

========================================================================
4.6.2 training-only standard deviation analysis completed successfully.
========================================================================

## 4.6.3 Training-Only Low-Variance Feature Filtering

This subsection applies the predefined standard-deviation threshold to the Training-only standard-deviation results generated in Section 4.6.2.

Features whose Training-set standard deviation falls below the threshold are identified as low-variance features and excluded from the subsequent feature-selection space. The decision is based exclusively on Training statistics; Validation and independent Test data are not used.

The filtering decision is recorded without modifying the original Stage-1 dataset or any persisted partition indices. The retained feature list will form the input to the subsequent Training-only correlation analysis.

In [14]:
# ============================================================
# 4.6.3 — Training-Only Low-Variance Feature Filtering
# ============================================================

print("=" * 72)
print("4.6.3 — TRAINING-ONLY LOW-VARIANCE FEATURE FILTERING")
print("=" * 72)

# ------------------------------------------------------------
# 4.6.3.1 Recover Persisted Standard-Deviation Results
# ------------------------------------------------------------

STANDARD_DEVIATION_PATH = (
    MODEL_PREPARATION_V2_DIR /
    "feature_selection" /
    "training_feature_standard_deviation.csv"
)

if not STANDARD_DEVIATION_PATH.is_file():
    raise FileNotFoundError(
        "Persisted Training standard-deviation artifact was not found:\n"
        f"{STANDARD_DEVIATION_PATH}"
    )

training_std_summary = pd.read_csv(
    STANDARD_DEVIATION_PATH
)

required_columns = {
    "Feature",
    "Standard_Deviation"
}

missing_columns = (
    required_columns -
    set(training_std_summary.columns)
)

if missing_columns:
    raise ValueError(
        "Training standard-deviation artifact is missing "
        f"required columns: {sorted(missing_columns)}"
    )

# ------------------------------------------------------------
# 4.6.3.2 Validate the Persisted Feature Space
# ------------------------------------------------------------

if len(training_std_summary) != 63:
    raise ValueError(
        "Expected standard-deviation results for 63 engineered "
        f"features, found {len(training_std_summary)}."
    )

if training_std_summary["Feature"].duplicated().any():
    raise ValueError(
        "Duplicate feature names detected in the "
        "standard-deviation artifact."
    )

if training_std_summary[
    "Standard_Deviation"
].isna().any():
    raise ValueError(
        "Missing standard-deviation values detected."
    )

# ------------------------------------------------------------
# 4.6.3.3 Define Training-Only Filtering Threshold
# ------------------------------------------------------------

STANDARD_DEVIATION_THRESHOLD = 0.01

training_std_summary["Retained"] = (
    training_std_summary["Standard_Deviation"]
    >= STANDARD_DEVIATION_THRESHOLD
)

training_std_summary["Removed"] = (
    training_std_summary["Standard_Deviation"]
    < STANDARD_DEVIATION_THRESHOLD
)

# ------------------------------------------------------------
# 4.6.3.4 Establish Retained and Removed Feature Sets
# ------------------------------------------------------------

removed_features = (
    training_std_summary.loc[
        training_std_summary["Removed"],
        "Feature"
    ]
    .tolist()
)

retained_features = (
    training_std_summary.loc[
        training_std_summary["Retained"],
        "Feature"
    ]
    .tolist()
)

removed_count = len(removed_features)
retained_count = len(retained_features)

if removed_count + retained_count != 63:
    raise ValueError(
        "Retained and removed feature counts do not "
        "reconstruct the original 63-feature space."
    )

if retained_count == 0:
    raise ValueError(
        "Low-variance filtering removed all features."
    )

# ------------------------------------------------------------
# 4.6.3.5 Display Filtering Result
# ------------------------------------------------------------

print("\n[STANDARD-DEVIATION CONFIGURATION]")
print(
    f"Input engineered features : "
    f"{len(training_std_summary)}"
)
print(
    f"Training-only SD threshold : "
    f"{STANDARD_DEVIATION_THRESHOLD}"
)

print("\n[FILTERING RESULT]")
print(
    f"Features below threshold : "
    f"{removed_count}"
)
print(
    f"Features retained        : "
    f"{retained_count}"
)

print("\n[FEATURES REMOVED BY SD FILTER]")

if removed_count == 0:
    print("  None")
else:
    for _, row in (
        training_std_summary.loc[
            training_std_summary["Removed"]
        ]
        .sort_values("Standard_Deviation")
        .iterrows()
    ):
        print(
            f"  - {row['Feature']} "
            f"(SD = {row['Standard_Deviation']:.12g})"
        )

# ------------------------------------------------------------
# 4.6.3.6 Persist Filtering Results
# ------------------------------------------------------------

STANDARD_DEVIATION_FILTER_RESULTS_PATH = (
    MODEL_PREPARATION_V2_DIR /
    "feature_selection" /
    "standard_deviation_filter_results.csv"
)

training_std_summary.to_csv(
    STANDARD_DEVIATION_FILTER_RESULTS_PATH,
    index=False
)

STANDARD_DEVIATION_SELECTED_FEATURES_PATH = (
    MODEL_PREPARATION_V2_DIR /
    "feature_selection" /
    "standard_deviation_selected_features.json"
)

standard_deviation_selection_metadata = {
    "stage": "4.6",
    "subsection": "4.6.3",
    "method": (
        "Training-only low-variance feature filtering"
    ),
    "input_feature_count": 63,
    "threshold": STANDARD_DEVIATION_THRESHOLD,
    "removed_feature_count": removed_count,
    "retained_feature_count": retained_count,
    "removed_features": removed_features,
    "retained_features": retained_features,
    "fit_partition": "Training",
    "validation_used_for_selection": False,
    "test_used_for_selection": False,
    "stage1_dataset_modified": False,
    "partition_indices_modified": False,
    "feature_values_modified": False,
    "scaling_performed": False,
    "resampling_performed": False,
    "model_fitting_performed": False
}

with open(
    STANDARD_DEVIATION_SELECTED_FEATURES_PATH,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        standard_deviation_selection_metadata,
        f,
        indent=4
    )

# ------------------------------------------------------------
# 4.6.3.7 Final Validation
# ------------------------------------------------------------

if (
    set(removed_features) &
    set(retained_features)
):
    raise ValueError(
        "A feature appears in both removed and retained sets."
    )

if (
    set(removed_features) |
    set(retained_features)
) != set(
    training_std_summary["Feature"]
):
    raise ValueError(
        "Removed and retained features do not reconstruct "
        "the original feature space."
    )

print("\n[VALIDATION]")
print("✓ Threshold applied using Training statistics only")
print("✓ Validation data excluded from feature-selection fitting")
print("✓ Independent Test data excluded from feature-selection fitting")
print("✓ All 63 engineered features accounted for")
print("✓ Removed and retained feature sets are mutually exclusive")
print("✓ Retained feature set established")
print("✓ Stage-1 dataset remains unchanged")
print("✓ Partition indices remain unchanged")
print("✓ No feature values modified")
print("✓ No scaling performed")
print("✓ No resampling performed")
print("✓ No model fitting performed")

print("\n[ARTIFACTS]")
print(
    "✓ "
    + str(STANDARD_DEVIATION_FILTER_RESULTS_PATH)
)
print(
    "✓ "
    + str(STANDARD_DEVIATION_SELECTED_FEATURES_PATH)
)

print("\n" + "=" * 72)
print(
    "4.6.3 training-only low-variance feature filtering "
    "completed successfully."
)
print("=" * 72)

========================================================================
4.6.3 — TRAINING-ONLY LOW-VARIANCE FEATURE FILTERING
========================================================================

[STANDARD-DEVIATION CONFIGURATION]
Input engineered features : 63
Training-only SD threshold : 0.01

[FILTERING RESULT]
Features below threshold : 1
Features retained        : 62

[FEATURES REMOVED BY SD FILTER]
  - Fwd URG Flags (SD = 0.00990530599966)

[VALIDATION]
✓ Threshold applied using Training statistics only
✓ Validation data excluded from feature-selection fitting
✓ Independent Test data excluded from feature-selection fitting
✓ All 63 engineered features accounted for
✓ Removed and retained feature sets are mutually exclusive
✓ Retained feature set established
✓ Stage-1 dataset remains unchanged
✓ Partition indices remain unchanged
✓ No feature values modified
✓ No scaling performed
✓ No resampling performed
✓ No model fitting performed

[ARTIFACTS]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_selection/standard_deviation_filter_results.csv
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_selection/standard_deviation_selected_features.json

========================================================================
4.6.3 training-only low-variance feature filtering completed successfully.
========================================================================

# 4.6.4 Training only correlation analysis

This subsection evaluates linear correlation among the features retained
after training-only low-variance filtering.

The correlation analysis is fitted exclusively on the Training partition.
Validation and Test observations are not used to calculate correlation
statistics or determine redundant features.

The purpose of this analysis is to identify highly correlated feature pairs
that contain substantially overlapping information and may therefore be
candidates for subsequent correlation-based pruning.

No features are removed in this subsection. The correlation results are
persisted as diagnostic artifacts and are used by Section 4.6.5 to determine
the final feature set.

The Stage-1 dataset, partition indices, target labels, and feature values
are not modified by this analysis.

In [15]:
# ============================================================
# 4.6.4 — TRAINING-ONLY CORRELATION ANALYSIS
# ============================================================

print("=" * 72)
print("4.6.4 — TRAINING-ONLY CORRELATION ANALYSIS")
print("=" * 72)

# ------------------------------------------------------------
# 4.6.4.1 Load the feature set retained by 4.6.3
# ------------------------------------------------------------

with open(STANDARD_DEVIATION_SELECTED_FEATURES_PATH, "r") as f:
    sd_selected_features = json.load(f)

if isinstance(sd_selected_features, dict):
    retained_features = sd_selected_features.get(
        "selected_features",
        sd_selected_features.get("retained_features")
    )
else:
    retained_features = sd_selected_features

if retained_features is None:
    raise ValueError(
        "Could not recover the feature list produced by 4.6.3."
    )

if len(retained_features) != 62:
    raise ValueError(
        f"Expected 62 features after SD filtering, "
        f"but found {len(retained_features)}."
    )

print("\n[CORRELATION INPUT]")
print(f"Features entering correlation analysis : {len(retained_features)}")
print("Source                                 : 4.6.3 SD-selected feature set")
print("Correlation fitting boundary           : Training only")

# ------------------------------------------------------------
# 4.6.4.2 Recover Training rows without
#         materializing the complete dataset
# ------------------------------------------------------------

training_positions = np.load(
    TRAINING_INDICES_PATH,
    mmap_mode="r"
)

print(f"Training rows                          : {len(training_positions):,}")

# ------------------------------------------------------------
# 4.6.4.3 Compute correlation statistics
# ------------------------------------------------------------

# Only the retained 62 features and Training rows are materialized.
# No Validation or Test observations participate in fitting.

training_feature_data = (
    stage1_df.iloc[
        training_positions
    ][retained_features]
)

if training_feature_data.shape[1] != 62:
    raise ValueError(
        "Training feature matrix does not contain exactly 62 "
        "SD-retained features."
    )

print(
    f"Training feature matrix used           : "
    f"{training_feature_data.shape[0]:,} × "
    f"{training_feature_data.shape[1]}"
)

correlation_matrix = training_feature_data.corr(
    method="pearson"
)

# Release the large temporary Training-only DataFrame immediately.
del training_feature_data

# ------------------------------------------------------------
# 4.6.4.4 Validate correlation matrix
# ------------------------------------------------------------

if correlation_matrix.shape != (62, 62):
    raise ValueError(
        f"Unexpected correlation matrix shape: "
        f"{correlation_matrix.shape}"
    )

if not np.isfinite(
    correlation_matrix.to_numpy()
).all():
    raise ValueError(
        "Correlation matrix contains NaN or infinite values."
    )

# ------------------------------------------------------------
# 4.6.4.5 Extract unique feature pairs
# ------------------------------------------------------------

correlation_pairs = []

for i in range(len(retained_features)):
    for j in range(i + 1, len(retained_features)):

        feature_a = retained_features[i]
        feature_b = retained_features[j]

        correlation_pairs.append(
            {
                "Feature_A": feature_a,
                "Feature_B": feature_b,
                "Pearson_Correlation": float(
                    correlation_matrix.iloc[i, j]
                ),
                "Absolute_Correlation": abs(
                    float(correlation_matrix.iloc[i, j])
                )
            }
        )

correlation_pairs_df = pd.DataFrame(
    correlation_pairs
)

# ------------------------------------------------------------
# 4.6.4.6 Rank correlations by absolute strength
# ------------------------------------------------------------

correlation_pairs_df = (
    correlation_pairs_df
    .sort_values(
        "Absolute_Correlation",
        ascending=False
    )
    .reset_index(drop=True)
)

# ------------------------------------------------------------
# 4.6.4.7 Summary statistics
# ------------------------------------------------------------

CORRELATION_ANALYSIS_THRESHOLD = 0.90

high_correlation_pairs = correlation_pairs_df[
    correlation_pairs_df["Absolute_Correlation"]
    >= CORRELATION_ANALYSIS_THRESHOLD
].copy()

print("\n[CORRELATION SUMMARY]")
print(f"Features analyzed                     : {len(retained_features)}")
print(
    f"Unique feature pairs analyzed         : "
    f"{len(correlation_pairs_df):,}"
)
print(
    f"Pairs with |r| >= "
    f"{CORRELATION_ANALYSIS_THRESHOLD:.2f}              : "
    f"{len(high_correlation_pairs):,}"
)
print(
    f"Maximum absolute correlation          : "
    f"{correlation_pairs_df['Absolute_Correlation'].max():.6f}"
)

# ------------------------------------------------------------
# 4.6.4.8 Display strongest relationships
# ------------------------------------------------------------

print("\n[TOP CORRELATED FEATURE PAIRS]")

display(
    correlation_pairs_df.head(20)
)

# ------------------------------------------------------------
# 4.6.4.9 Persist correlation artifacts
# ------------------------------------------------------------

CORRELATION_ANALYSIS_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "feature_selection"
)

CORRELATION_ANALYSIS_DIR.mkdir(
    parents=True,
    exist_ok=True
)

correlation_pairs_path = (
    CORRELATION_ANALYSIS_DIR /
    "training_only_correlation_pairs.csv"
)

correlation_summary_path = (
    CORRELATION_ANALYSIS_DIR /
    "training_only_correlation_summary.json"
)

correlation_pairs_df.to_csv(
    correlation_pairs_path,
    index=False
)

correlation_summary = {
    "analysis": "Training-only Pearson correlation analysis",
    "input_feature_count": len(retained_features),
    "training_row_count": int(len(training_positions)),
    "correlation_method": "pearson",
    "analysis_threshold": CORRELATION_ANALYSIS_THRESHOLD,
    "unique_feature_pairs": int(len(correlation_pairs_df)),
    "pairs_at_or_above_threshold": int(
        len(high_correlation_pairs)
    ),
    "maximum_absolute_correlation": float(
        correlation_pairs_df["Absolute_Correlation"].max()
    ),
    "features_removed": 0,
    "validation_used_for_fitting": False,
    "test_used_for_fitting": False
}

with open(
    correlation_summary_path,
    "w"
) as f:
    json.dump(
        correlation_summary,
        f,
        indent=2
    )

# ------------------------------------------------------------
# 4.6.4.10 Final validation
# ------------------------------------------------------------

print("\n[VALIDATION]")
print("✓ Correlation analysis used the 4.6.3 retained feature set")
print("✓ 62 input features verified")
print("✓ Training observations used for correlation fitting only")
print("✓ Validation observations excluded")
print("✓ Test observations excluded")
print("✓ Pearson correlation matrix contains finite values")
print("✓ Unique feature pairs extracted")
print("✓ No features removed in this subsection")
print("✓ No partition indices modified")
print("✓ No labels modified")
print("✓ No scaling performed")
print("✓ No resampling performed")
print("✓ No model fitting performed")

print("\n[ARTIFACTS]")
print(f"✓ {correlation_pairs_path}")
print(f"✓ {correlation_summary_path}")

print("\n" + "=" * 72)
print(
    "4.6.4 training-only correlation analysis "
    "completed successfully."
)
print("=" * 72)

========================================================================
4.6.4 — TRAINING-ONLY CORRELATION ANALYSIS
========================================================================

[CORRELATION INPUT]
Features entering correlation analysis : 62
Source                                 : 4.6.3 SD-selected feature set
Correlation fitting boundary           : Training only
Training rows                          : 1,814,018
Training feature matrix used           : 1,814,018 × 62

[CORRELATION SUMMARY]
Features analyzed                     : 62
Unique feature pairs analyzed         : 1,891
Pairs with |r| >= 0.90              : 86
Maximum absolute correlation          : 1.000000

[TOP CORRELATED FEATURE PAIRS]

,Feature_A,Feature_B,Pearson_Correlation,Absolute_Correlation
0,Bwd Packet Length Mean,Avg Bwd Segment Size,1.000000,1.000000
1,Subflow Fwd Bytes,Total Length of Fwd Packets,1.000000,1.000000
2,Fwd Packet Length Mean,Avg Fwd Segment Size,1.000000,1.000000
3,Subflow Bwd Bytes,Total Length of Bwd Packets,1.000000,1.000000
4,Idle Mean,Idle Max,0.999954,0.999954
5,Idle Min,Idle Mean,0.999723,0.999723
6,Packet Length Std,Packet Length Variance,0.999642,0.999642
7,Idle Min,Idle Max,0.999474,0.999474
8,RST Flag Count,ECE Flag Count,0.998847,0.998847
9,Packet Length Mean,Average Packet Size,0.997975,0.997975
10,Bwd IAT Max,Bwd IAT Total,0.997900,0.997900
11,Active Mean,Active Max,0.997848,0.997848
12,Fwd IAT Max,Fwd IAT Total,0.997542,0.997542
13,Fwd Packets/s,Flow Packets/s,0.997226,0.997226
14,Fwd IAT Mean,Fwd IAT Max,0.997004,0.997004
15,Bwd IAT Mean,Bwd IAT Max,0.996627,0.996627
16,Bwd IAT Mean,Bwd IAT Total,0.995469,0.995469
17,Flow IAT Max,Flow Duration,0.995207,0.995207
18,Fwd IAT Mean,Fwd IAT Total,0.995157,0.995157
19,Active Min,Active Mean,0.991938,0.991938

[VALIDATION]
✓ Correlation analysis used the 4.6.3 retained feature set
✓ 62 input features verified
✓ Training observations used for correlation fitting only
✓ Validation observations excluded
✓ Test observations excluded
✓ Pearson correlation matrix contains finite values
✓ Unique feature pairs extracted
✓ No features removed in this subsection
✓ No partition indices modified
✓ No labels modified
✓ No scaling performed
✓ No resampling performed
✓ No model fitting performed

[ARTIFACTS]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_selection/training_only_correlation_pairs.csv
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_selection/training_only_correlation_summary.json

========================================================================
4.6.4 training-only correlation analysis completed successfully.
========================================================================

# 4.6.5 — Training-Only Correlation Pruning

Highly correlated features can contain substantially overlapping information and may introduce unnecessary redundancy into the model input space. Therefore, the correlation relationships identified in Section 4.6.4 are used to perform deterministic feature pruning.

The pruning decision is based exclusively on the Training partition and on the 62 features retained after the training-only standard-deviation filter. Validation and Test observations are not used to determine which features are removed.

A correlation threshold of |r| ≥ 0.90 is used to identify strongly redundant feature pairs. Where multiple features are involved in correlated groups, pruning is performed deterministically so that the final retained feature set is reproducible. No feature values, labels, partition indices, or Stage-1 data are modified.

The complete pruning decision is persisted, including the removed features, their corresponding retained features, correlation values, and the final feature set. The resulting feature list will be used by subsequent preprocessing and model-development stages.

In [16]:
# ============================================================
# 4.6.5 — Training-Only Correlation Pruning
# ============================================================

import json
import pandas as pd
from pathlib import Path

print("=" * 72)
print("4.6.5 — TRAINING-ONLY CORRELATION PRUNING")
print("=" * 72)

# ------------------------------------------------------------
# 4.6.5.1 Load persisted feature-selection artifacts
# ------------------------------------------------------------

FEATURE_SELECTION_DIR = (
    Path("/content/drive/MyDrive/AI-Network-Intrusion-Detection-System")
    / "outputs"
    / "model_preparation_v2"
    / "feature_selection"
)

SD_SELECTED_FEATURES_PATH = (
    FEATURE_SELECTION_DIR /
    "standard_deviation_selected_features.json"
)

CORRELATION_PAIRS_PATH = (
    FEATURE_SELECTION_DIR /
    "training_only_correlation_pairs.csv"
)

if not SD_SELECTED_FEATURES_PATH.exists():
    raise FileNotFoundError(
        f"Missing 4.6.3 artifact:\n{SD_SELECTED_FEATURES_PATH}"
    )

if not CORRELATION_PAIRS_PATH.exists():
    raise FileNotFoundError(
        f"Missing 4.6.4 artifact:\n{CORRELATION_PAIRS_PATH}"
    )

with open(SD_SELECTED_FEATURES_PATH, "r") as f:
    sd_metadata = json.load(f)

correlation_pairs = pd.read_csv(
    CORRELATION_PAIRS_PATH
)

print("\n[PERSISTED INPUTS]")
print("✓ 4.6.3 standard-deviation feature-selection artifact loaded")
print("✓ 4.6.4 training-only correlation-pair artifact loaded")

# ------------------------------------------------------------
# 4.6.5.2 Recover the 62-feature input set
# ------------------------------------------------------------

if "retained_features" in sd_metadata:
    sd_selected_features = sd_metadata["retained_features"]
elif "selected_features" in sd_metadata:
    sd_selected_features = sd_metadata["selected_features"]
elif "features_retained" in sd_metadata:
    sd_selected_features = sd_metadata["features_retained"]
else:
    raise KeyError(
        "Could not identify the retained feature list in "
        "standard_deviation_selected_features.json."
    )

sd_selected_features = list(sd_selected_features)

if len(sd_selected_features) != 62:
    raise ValueError(
        f"Expected 62 SD-selected features, "
        f"but found {len(sd_selected_features)}."
    )

print("\n[CORRELATION PRUNING INPUT]")
print(f"Input features after SD filtering : {len(sd_selected_features)}")
print("Training-only correlation source  : 4.6.4 persisted artifact")
print("Validation data used              : No")
print("Test data used                    : No")

# ------------------------------------------------------------
# 4.6.5.3 Validate correlation artifact
# ------------------------------------------------------------

required_columns = {
    "Feature_A",
    "Feature_B",
    "Pearson_Correlation",
    "Absolute_Correlation"
}

missing_columns = required_columns - set(correlation_pairs.columns)

if missing_columns:
    raise ValueError(
        f"Correlation artifact is missing required columns: "
        f"{sorted(missing_columns)}"
    )

correlation_pairs = correlation_pairs[
    correlation_pairs["Feature_A"].isin(sd_selected_features)
    & correlation_pairs["Feature_B"].isin(sd_selected_features)
].copy()

CORRELATION_THRESHOLD = 0.90

high_corr_pairs = correlation_pairs[
    correlation_pairs["Absolute_Correlation"] >= CORRELATION_THRESHOLD
].copy()

high_corr_pairs = high_corr_pairs.sort_values(
    by=[
        "Absolute_Correlation",
        "Feature_A",
        "Feature_B"
    ],
    ascending=[False, True, True]
).reset_index(drop=True)

print("\n[CORRELATION THRESHOLD]")
print(f"Threshold |r| >= {CORRELATION_THRESHOLD:.2f}")
print(f"Highly correlated pairs : {len(high_corr_pairs):,}")

# ------------------------------------------------------------
# 4.6.5.4 Deterministic greedy correlation pruning
# ------------------------------------------------------------

# The pruning operates only on the persisted training-only
# correlation relationships.
#
# For every highly correlated pair, one feature is removed.
# The feature with the greater number of high-correlation
# relationships is preferentially removed.
#
# If both features have the same number of relationships,
# deterministic alphabetical ordering is used as the tie-breaker.
#
# This avoids arbitrary/random feature removal.

if len(high_corr_pairs) > 0:

    correlation_degree = {}

    for feature in sd_selected_features:
        correlation_degree[feature] = 0

    for _, row in high_corr_pairs.iterrows():
        feature_a = row["Feature_A"]
        feature_b = row["Feature_B"]

        correlation_degree[feature_a] += 1
        correlation_degree[feature_b] += 1

    retained_features = list(sd_selected_features)
    removed_features = []
    pruning_records = []

    for _, row in high_corr_pairs.iterrows():

        feature_a = row["Feature_A"]
        feature_b = row["Feature_B"]

        if (
            feature_a not in retained_features
            or feature_b not in retained_features
        ):
            continue

        degree_a = correlation_degree[feature_a]
        degree_b = correlation_degree[feature_b]

        if degree_a > degree_b:
            feature_to_remove = feature_a
            feature_to_keep = feature_b

        elif degree_b > degree_a:
            feature_to_remove = feature_b
            feature_to_keep = feature_a

        else:
            # Deterministic tie-breaker
            if feature_a < feature_b:
                feature_to_remove = feature_b
                feature_to_keep = feature_a
            else:
                feature_to_remove = feature_a
                feature_to_keep = feature_b

        retained_features.remove(feature_to_remove)
        removed_features.append(feature_to_remove)

        pruning_records.append({
            "Removed_Feature": feature_to_remove,
            "Retained_Feature": feature_to_keep,
            "Pearson_Correlation": float(
                row["Pearson_Correlation"]
            ),
            "Absolute_Correlation": float(
                row["Absolute_Correlation"]
            ),
            "Removed_Feature_Correlation_Degree": int(
                degree_a if feature_to_remove == feature_a
                else degree_b
            ),
            "Retained_Feature_Correlation_Degree": int(
                degree_b if feature_to_remove == feature_a
                else degree_a
            )
        })

else:
    retained_features = list(sd_selected_features)
    removed_features = []
    pruning_records = []

# ------------------------------------------------------------
# 4.6.5.5 Validate final feature set
# ------------------------------------------------------------

retained_features = list(retained_features)
removed_features = list(dict.fromkeys(removed_features))

if set(retained_features) & set(removed_features):
    raise ValueError(
        "A feature appears in both retained and removed feature sets."
    )

if set(retained_features) | set(removed_features) != set(
    sd_selected_features
):
    raise ValueError(
        "Retained and removed feature sets do not reconstruct "
        "the complete SD-selected feature set."
    )

if len(retained_features) + len(removed_features) != 62:
    raise ValueError(
        "Final feature accounting does not equal the 62 "
        "SD-selected input features."
    )

# ------------------------------------------------------------
# 4.6.5.6 Persist pruning results
# ------------------------------------------------------------

pruning_results = pd.DataFrame(pruning_records)

CORRELATION_PRUNING_RESULTS_PATH = (
    FEATURE_SELECTION_DIR /
    "training_only_correlation_pruning_results.csv"
)

CORRELATION_SELECTED_FEATURES_PATH = (
    FEATURE_SELECTION_DIR /
    "correlation_pruned_selected_features.json"
)

CORRELATION_PRUNING_SUMMARY_PATH = (
    FEATURE_SELECTION_DIR /
    "training_only_correlation_pruning_summary.json"
)

pruning_results.to_csv(
    CORRELATION_PRUNING_RESULTS_PATH,
    index=False
)

with open(CORRELATION_SELECTED_FEATURES_PATH, "w") as f:
    json.dump(
        {
            "source_feature_count": len(sd_selected_features),
            "correlation_threshold": CORRELATION_THRESHOLD,
            "removed_feature_count": len(removed_features),
            "retained_feature_count": len(retained_features),
            "removed_features": removed_features,
            "retained_features": retained_features
        },
        f,
        indent=2
    )

pruning_summary = {
    "input_feature_count": len(sd_selected_features),
    "correlation_threshold": CORRELATION_THRESHOLD,
    "high_correlation_pair_count": int(len(high_corr_pairs)),
    "removed_feature_count": len(removed_features),
    "retained_feature_count": len(retained_features),
    "validation_used": False,
    "test_used": False,
    "feature_values_modified": False,
    "labels_modified": False,
    "partition_indices_modified": False,
    "scaling_performed": False,
    "resampling_performed": False,
    "model_fitting_performed": False
}

with open(CORRELATION_PRUNING_SUMMARY_PATH, "w") as f:
    json.dump(
        pruning_summary,
        f,
        indent=2
    )

# ------------------------------------------------------------
# 4.6.5.7 Final reporting
# ------------------------------------------------------------

print("\n[PRUNING RESULT]")
print(
    f"Features entering correlation pruning : "
    f"{len(sd_selected_features)}"
)
print(
    f"Highly correlated pairs identified    : "
    f"{len(high_corr_pairs):,}"
)
print(
    f"Features removed                      : "
    f"{len(removed_features)}"
)
print(
    f"Features retained                     : "
    f"{len(retained_features)}"
)

if removed_features:
    print("\n[REMOVED FEATURES]")
    for feature in removed_features:
        print(f" - {feature}")

print("\n[VALIDATION]")
print("✓ Correlation relationships derived from Training data only")
print("✓ Validation data excluded from pruning decisions")
print("✓ Independent Test data excluded from pruning decisions")
print("✓ Correlation threshold applied deterministically")
print("✓ Retained and removed feature sets are mutually exclusive")
print("✓ Feature accounting verified")
print("✓ Stage-1 dataset remains unchanged")
print("✓ Partition indices remain unchanged")
print("✓ No feature values modified")
print("✓ No labels modified")
print("✓ No scaling performed")
print("✓ No resampling performed")
print("✓ No model fitting performed")

print("\n[ARTIFACTS]")
print(f"✓ {CORRELATION_PRUNING_RESULTS_PATH}")
print(f"✓ {CORRELATION_SELECTED_FEATURES_PATH}")
print(f"✓ {CORRELATION_PRUNING_SUMMARY_PATH}")

print("\n" + "=" * 72)
print("4.6.5 training-only correlation pruning completed successfully.")
print("=" * 72)

========================================================================
4.6.5 — TRAINING-ONLY CORRELATION PRUNING
========================================================================

[PERSISTED INPUTS]
✓ 4.6.3 standard-deviation feature-selection artifact loaded
✓ 4.6.4 training-only correlation-pair artifact loaded

[CORRELATION PRUNING INPUT]
Input features after SD filtering : 62
Training-only correlation source  : 4.6.4 persisted artifact
Validation data used              : No
Test data used                    : No

[CORRELATION THRESHOLD]
Threshold |r| >= 0.90
Highly correlated pairs : 86

[PRUNING RESULT]
Features entering correlation pruning : 62
Highly correlated pairs identified    : 86
Features removed                      : 30
Features retained                     : 32

[REMOVED FEATURES]
 - Bwd Packet Length Mean
 - Fwd Packet Length Mean
 - Total Length of Fwd Packets
 - Total Length of Bwd Packets
 - Idle Mean
 - Packet Length Variance
 - Idle Min
 - RST Flag Count
 - Packet Length Mean
 - Bwd IAT Total
 - Active Mean
 - Fwd IAT Total
 - Fwd Packets/s
 - Fwd IAT Max
 - Bwd IAT Max
 - Flow IAT Max
 - Flow Packets/s
 - Subflow Bwd Bytes
 - Active Min
 - Bwd Packet Length Max
 - Flow IAT Mean
 - Min Packet Length
 - Fwd Packet Length Max
 - Max Packet Length
 - Total Fwd Packets
 - Subflow Fwd Bytes
 - Idle Max
 - Packet Length Std
 - Avg Bwd Segment Size
 - Total Backward Packets

[VALIDATION]
✓ Correlation relationships derived from Training data only
✓ Validation data excluded from pruning decisions
✓ Independent Test data excluded from pruning decisions
✓ Correlation threshold applied deterministically
✓ Retained and removed feature sets are mutually exclusive
✓ Feature accounting verified
✓ Stage-1 dataset remains unchanged
✓ Partition indices remain unchanged
✓ No feature values modified
✓ No labels modified
✓ No scaling performed
✓ No resampling performed
✓ No model fitting performed

[ARTIFACTS]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_selection/training_only_correlation_pruning_results.csv
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_selection/correlation_pruned_selected_features.json
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_selection/training_only_correlation_pruning_summary.json

========================================================================
4.6.5 training-only correlation pruning completed successfully.
========================================================================

# 4.6.6 Final Feature-Set Validation

This subsection performs the final validation of the feature set produced by
the training-only standard-deviation filtering and correlation-pruning stages.

The validation confirms that the retained feature set is internally consistent,
that retained and removed features are mutually exclusive, and that the final
feature count matches the documented feature-selection process. The persisted
training-only correlation results are also checked to ensure that no pair of
retained features still violates the defined correlation threshold.

No new feature-selection decision is made in this subsection. The 32-feature
set produced by Section 4.6.5 is treated as final and is only validated and
documented for use in subsequent model-preparation stages.

In [17]:
# ============================================================
# 4.6.6 Final Feature-Set Validation
# ============================================================

import json
import pandas as pd
from pathlib import Path

print("=" * 72)
print("4.6.6 — FINAL FEATURE-SET VALIDATION")
print("=" * 72)

# ------------------------------------------------------------
# Load persisted feature-selection artifacts
# ------------------------------------------------------------

FEATURE_SELECTION_DIR = (
    Path(MODEL_PREPARATION_V2_DIR) / "feature_selection"
)

SD_SELECTED_FEATURES_PATH = (
    FEATURE_SELECTION_DIR /
    "standard_deviation_selected_features.json"
)

CORRELATION_SELECTED_FEATURES_PATH = (
    FEATURE_SELECTION_DIR /
    "correlation_pruned_selected_features.json"
)

# IMPORTANT:
# Pairwise correlation information comes from 4.6.4,
# not from the 4.6.5 pruning-results CSV.
CORRELATION_PAIRS_PATH = (
    FEATURE_SELECTION_DIR /
    "training_only_correlation_pairs.csv"
)

if not SD_SELECTED_FEATURES_PATH.exists():
    raise FileNotFoundError(
        f"Missing artifact: {SD_SELECTED_FEATURES_PATH}"
    )

if not CORRELATION_SELECTED_FEATURES_PATH.exists():
    raise FileNotFoundError(
        f"Missing artifact: {CORRELATION_SELECTED_FEATURES_PATH}"
    )

if not CORRELATION_PAIRS_PATH.exists():
    raise FileNotFoundError(
        f"Missing artifact: {CORRELATION_PAIRS_PATH}"
    )

# ------------------------------------------------------------
# Helper for persisted feature-list artifacts
# ------------------------------------------------------------

def load_feature_list(path):

    with open(path, "r") as f:
        data = json.load(f)

    if isinstance(data, list):
        return data

    if isinstance(data, dict):
        for key in [
            "selected_features",
            "retained_features",
            "features",
            "feature_columns"
        ]:
            if key in data and isinstance(data[key], list):
                return data[key]

    raise ValueError(
        f"Could not identify a feature list in {path}"
    )


sd_selected_features = load_feature_list(
    SD_SELECTED_FEATURES_PATH
)

final_selected_features = load_feature_list(
    CORRELATION_SELECTED_FEATURES_PATH
)

# ------------------------------------------------------------
# Load the actual 4.6.4 pairwise correlation artifact
# ------------------------------------------------------------

correlation_pairs = pd.read_csv(
    CORRELATION_PAIRS_PATH
)

# ------------------------------------------------------------
# Basic feature-space validation
# ------------------------------------------------------------

if len(feature_columns) != 63:
    raise ValueError(
        f"Expected 63 original engineered features, "
        f"found {len(feature_columns)}."
    )

if len(sd_selected_features) != 62:
    raise ValueError(
        f"Expected 62 features after SD filtering, "
        f"found {len(sd_selected_features)}."
    )

if len(final_selected_features) != 32:
    raise ValueError(
        f"Expected 32 final features after correlation pruning, "
        f"found {len(final_selected_features)}."
    )

# ------------------------------------------------------------
# Feature uniqueness
# ------------------------------------------------------------

if len(set(feature_columns)) != len(feature_columns):
    raise ValueError(
        "Duplicate feature names detected in the original "
        "engineered feature set."
    )

if len(set(sd_selected_features)) != len(sd_selected_features):
    raise ValueError(
        "Duplicate feature names detected in the SD-selected "
        "feature set."
    )

if len(set(final_selected_features)) != len(final_selected_features):
    raise ValueError(
        "Duplicate feature names detected in the final "
        "selected feature set."
    )

# ------------------------------------------------------------
# Feature-set membership validation
# ------------------------------------------------------------

original_feature_set = set(feature_columns)
sd_feature_set = set(sd_selected_features)
final_feature_set = set(final_selected_features)

if not sd_feature_set.issubset(original_feature_set):
    raise ValueError(
        "SD-selected feature set contains features that were "
        "not present in the original 63-feature set."
    )

if not final_feature_set.issubset(sd_feature_set):
    raise ValueError(
        "Final selected feature set contains features that were "
        "not present after SD filtering."
    )

removed_by_sd = (
    original_feature_set - sd_feature_set
)

removed_by_correlation = (
    sd_feature_set - final_feature_set
)

if len(removed_by_sd) != 1:
    raise ValueError(
        f"Expected 1 feature removed by SD filtering, "
        f"found {len(removed_by_sd)}."
    )

if len(removed_by_correlation) != 30:
    raise ValueError(
        f"Expected 30 features removed by correlation pruning, "
        f"found {len(removed_by_correlation)}."
    )

if final_feature_set & removed_by_correlation:
    raise ValueError(
        "A feature appears in both retained and "
        "correlation-removed sets."
    )

# ------------------------------------------------------------
# Validate the actual 4.6.4 correlation-pair artifact
# ------------------------------------------------------------

required_correlation_columns = {
    "Feature_A",
    "Feature_B",
    "Absolute_Correlation"
}

missing_columns = (
    required_correlation_columns
    - set(correlation_pairs.columns)
)

if missing_columns:
    raise ValueError(
        "4.6.4 correlation-pair artifact is missing required "
        f"columns: {sorted(missing_columns)}"
    )

# ------------------------------------------------------------
# Identify highly correlated pairs
# ------------------------------------------------------------

high_correlation_pairs = correlation_pairs[
    correlation_pairs["Absolute_Correlation"] >= 0.90
].copy()

# ------------------------------------------------------------
# Verify no highly correlated pair remains in final set
# ------------------------------------------------------------

retained_conflicting_pairs = high_correlation_pairs[
    high_correlation_pairs["Feature_A"].isin(
        final_selected_features
    )
    &
    high_correlation_pairs["Feature_B"].isin(
        final_selected_features
    )
]

if len(retained_conflicting_pairs) != 0:

    print("\n[CORRELATION VALIDATION FAILURE]")

    print(
        f"Retained highly correlated pairs: "
        f"{len(retained_conflicting_pairs)}"
    )

    raise ValueError(
        "Final selected feature set still contains "
        "highly correlated feature pairs at |r| >= 0.90."
    )

# ------------------------------------------------------------
# Final validation summary
# ------------------------------------------------------------

print("\n[FINAL FEATURE-SET SUMMARY]")

print(
    f"Original engineered features       : "
    f"{len(feature_columns):,}"
)

print(
    f"After SD filtering                 : "
    f"{len(sd_selected_features):,}"
)

print(
    f"Removed by SD filtering            : "
    f"{len(removed_by_sd):,}"
)

print(
    f"Removed by correlation pruning     : "
    f"{len(removed_by_correlation):,}"
)

print(
    f"Final selected features            : "
    f"{len(final_selected_features):,}"
)

print("\n[FEATURE-SET INTEGRITY]")

print(
    "✓ Final features originate from the "
    "original engineered feature set"
)

print(
    "✓ Final features are a subset of the "
    "SD-retained feature set"
)

print(
    "✓ Original, retained, and removed "
    "feature sets are internally consistent"
)

print(
    "✓ Retained and removed feature sets "
    "are mutually exclusive"
)

print("\n[CORRELATION VALIDATION]")

print(
    f"High-correlation pairs examined    : "
    f"{len(high_correlation_pairs):,}"
)

print(
    "Correlation threshold              : |r| >= 0.90"
)

print(
    f"Retained pairs above threshold     : "
    f"{len(retained_conflicting_pairs):,}"
)

print(
    "✓ No retained feature pair violates "
    "the correlation threshold"
)

# ------------------------------------------------------------
# Persist final validation metadata
# ------------------------------------------------------------

final_feature_validation = {

    "original_feature_count":
        len(feature_columns),

    "sd_selected_feature_count":
        len(sd_selected_features),

    "sd_removed_feature_count":
        len(removed_by_sd),

    "correlation_removed_feature_count":
        len(removed_by_correlation),

    "final_selected_feature_count":
        len(final_selected_features),

    "correlation_threshold":
        0.90,

    "high_correlation_pairs_examined":
        int(len(high_correlation_pairs)),

    "retained_pairs_above_threshold":
        int(len(retained_conflicting_pairs)),

    "feature_selection_boundary":
        "Training only",

    "validation_data_used":
        False,

    "test_data_used":
        False,

    "resampling_performed":
        False,

    "scaling_performed":
        False,

    "model_fitting_performed":
        False,

    "final_feature_set_valid":
        True
}

FINAL_FEATURE_VALIDATION_PATH = (
    FEATURE_SELECTION_DIR /
    "final_feature_set_validation.json"
)

with open(FINAL_FEATURE_VALIDATION_PATH, "w") as f:

    json.dump(
        final_feature_validation,
        f,
        indent=2
    )

# ------------------------------------------------------------
# Final output
# ------------------------------------------------------------

print("\n[ARTIFACT]")

print(
    "✓ Final feature-set validation metadata persisted:"
)

print(
    f"  {FINAL_FEATURE_VALIDATION_PATH}"
)

print("\n[FINAL VALIDATION]")

print(
    "✓ 63 → 62 → 32 feature-selection progression verified"
)

print(
    "✓ SD filtering result verified"
)

print(
    "✓ Correlation-pruning result verified"
)

print(
    "✓ Final 32-feature set contains no |r| >= 0.90 pair"
)

print(
    "✓ Training-only feature-selection boundary preserved"
)

print(
    "✓ Validation data excluded from feature-selection decisions"
)

print(
    "✓ Independent test data excluded from feature-selection decisions"
)

print(
    "✓ No feature values modified"
)

print(
    "✓ No partition indices modified"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No scaling performed"
)

print(
    "✓ No model fitting performed"
)

print("\n" + "=" * 72)

print(
    "4.6.6 final feature-set validation completed successfully."
)

print("=" * 72)

========================================================================
4.6.6 — FINAL FEATURE-SET VALIDATION
========================================================================

[FINAL FEATURE-SET SUMMARY]
Original engineered features       : 63
After SD filtering                 : 62
Removed by SD filtering            : 1
Removed by correlation pruning     : 30
Final selected features            : 32

[FEATURE-SET INTEGRITY]
✓ Final features originate from the original engineered feature set
✓ Final features are a subset of the SD-retained feature set
✓ Original, retained, and removed feature sets are internally consistent
✓ Retained and removed feature sets are mutually exclusive

[CORRELATION VALIDATION]
High-correlation pairs examined    : 86
Correlation threshold              : |r| >= 0.90
Retained pairs above threshold     : 0
✓ No retained feature pair violates the correlation threshold

[ARTIFACT]
✓ Final feature-set validation metadata persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_selection/final_feature_set_validation.json

[FINAL VALIDATION]
✓ 63 → 62 → 32 feature-selection progression verified
✓ SD filtering result verified
✓ Correlation-pruning result verified
✓ Final 32-feature set contains no |r| >= 0.90 pair
✓ Training-only feature-selection boundary preserved
✓ Validation data excluded from feature-selection decisions
✓ Independent test data excluded from feature-selection decisions
✓ No feature values modified
✓ No partition indices modified
✓ No resampling performed
✓ No scaling performed
✓ No model fitting performed

========================================================================
4.6.6 final feature-set validation completed successfully.
========================================================================

## 4.7 — Training-Only Feature Scaling

Following the completion of training-only feature selection, the validated 32-feature set is prepared for model development through controlled feature scaling. Scaling is performed only after standard-deviation filtering and correlation pruning so that the feature-selection decisions remain based on the original engineered feature values.

The scaling boundary is strictly restricted to the Training partition. Validation and independent Test observations are not used to estimate any scaling parameters. A single scaler fitted on Training data will later be applied unchanged to Training, Validation, Test, and downstream inference data, ensuring that all model inputs share the same feature transformation.

This stage does not modify the original Stage-1 dataset, partition indices, target labels, or selected feature definitions. The objective is to establish a reproducible model-ready numerical feature space while preserving the Training/Validation/Test isolation established in Section 4.5.

### 4.7.1 — Scaling Configuration & Training Boundary

This subsection establishes the configuration and data boundary for the scaling stage. The input feature space is the final 32-feature set validated in Section 4.6.6, obtained after training-only low-variance filtering and correlation pruning.

A standardization procedure will be used so that each selected feature is transformed according to statistics estimated exclusively from the Training partition. The Validation and independent Test partitions remain completely outside the scaler-fitting operation and will only be transformed after the Training scaler has been established.

The scaler configuration, selected feature set, partition sizes, and training-only fitting boundary are recorded as reproducibility metadata. No feature values, labels, partition indices, or source datasets are modified in this subsection, and no model fitting or resampling is performed.

In [18]:
# ============================================================
# 4.7.1 — SCALING CONFIGURATION & TRAINING BOUNDARY
# ============================================================

from pathlib import Path
import json

print("=" * 72)
print("4.7.1 — SCALING CONFIGURATION & TRAINING BOUNDARY")
print("=" * 72)

# ------------------------------------------------------------
# Load the authoritative final feature-set artifact
# produced by Section 4.6.5.
# ------------------------------------------------------------

FINAL_FEATURE_SET_PATH = (
    MODEL_PREPARATION_V2_DIR
    / "feature_selection"
    / "correlation_pruned_selected_features.json"
)

if not FINAL_FEATURE_SET_PATH.exists():
    raise FileNotFoundError(
        "Final 32-feature artifact was not found:\n"
        f"{FINAL_FEATURE_SET_PATH}"
    )

with open(FINAL_FEATURE_SET_PATH, "r") as f:
    final_feature_artifact = json.load(f)

# Support the persisted feature list without assuming that
# the surrounding notebook variable names contain the list.
if isinstance(final_feature_artifact, list):
    FINAL_FEATURE_COLUMNS = final_feature_artifact

elif isinstance(final_feature_artifact, dict):
    candidate_keys = [
        "selected_features",
        "retained_features",
        "correlation_pruned_features",
        "features",
        "final_features"
    ]

    FINAL_FEATURE_COLUMNS = None

    for key in candidate_keys:
        if key in final_feature_artifact:
            FINAL_FEATURE_COLUMNS = final_feature_artifact[key]
            break

    if FINAL_FEATURE_COLUMNS is None:
        raise ValueError(
            "Could not identify the persisted final feature list in:\n"
            f"{FINAL_FEATURE_SET_PATH}"
        )

else:
    raise ValueError(
        "Unexpected format in the persisted final feature artifact."
    )

FINAL_FEATURE_COLUMNS = list(FINAL_FEATURE_COLUMNS)

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

SCALER_TYPE = "StandardScaler"
EXPECTED_FINAL_FEATURE_COUNT = 32

# ------------------------------------------------------------
# Recover persisted partition sizes from the existing
# partition artifacts rather than materializing the dataset.
# ------------------------------------------------------------

PARTITION_DIR = (
    MODEL_PREPARATION_V2_DIR
    / "duplicate_leakage_audit"
)

TRAINING_INDICES_PATH = PARTITION_DIR / "training_indices.npy"
VALIDATION_INDICES_PATH = PARTITION_DIR / "validation_indices.npy"
TEST_INDICES_PATH = PARTITION_DIR / "test_indices.npy"

for artifact_path in [
    TRAINING_INDICES_PATH,
    VALIDATION_INDICES_PATH,
    TEST_INDICES_PATH
]:
    if not artifact_path.exists():
        raise FileNotFoundError(
            f"Required partition artifact not found:\n{artifact_path}"
        )

import numpy as np

training_indices = np.load(
    TRAINING_INDICES_PATH,
    mmap_mode="r"
)

validation_indices = np.load(
    VALIDATION_INDICES_PATH,
    mmap_mode="r"
)

test_indices = np.load(
    TEST_INDICES_PATH,
    mmap_mode="r"
)

TRAINING_ROW_COUNT = len(training_indices)
VALIDATION_ROW_COUNT = len(validation_indices)
TEST_ROW_COUNT = len(test_indices)

# ------------------------------------------------------------
# Boundary validation
# ------------------------------------------------------------

if len(FINAL_FEATURE_COLUMNS) != EXPECTED_FINAL_FEATURE_COUNT:
    raise ValueError(
        "Unexpected final feature count: "
        f"{len(FINAL_FEATURE_COLUMNS)} "
        f"(expected {EXPECTED_FINAL_FEATURE_COUNT})"
    )

if len(set(FINAL_FEATURE_COLUMNS)) != len(FINAL_FEATURE_COLUMNS):
    raise ValueError(
        "Final feature set contains duplicate feature names."
    )

if TRAINING_ROW_COUNT == 0:
    raise ValueError("Training partition is empty.")

if VALIDATION_ROW_COUNT == 0:
    raise ValueError("Validation partition is empty.")

if TEST_ROW_COUNT == 0:
    raise ValueError("Test partition is empty.")

# ------------------------------------------------------------
# Persist configuration metadata
# ------------------------------------------------------------

SCALING_DIR = (
    MODEL_PREPARATION_V2_DIR
    / "feature_scaling"
)

SCALING_DIR.mkdir(
    parents=True,
    exist_ok=True
)

SCALING_CONFIGURATION_PATH = (
    SCALING_DIR
    / "scaling_configuration.json"
)

scaling_configuration = {
    "section": "4.7.1",
    "scaler_type": SCALER_TYPE,
    "expected_final_feature_count": EXPECTED_FINAL_FEATURE_COUNT,
    "final_feature_count": len(FINAL_FEATURE_COLUMNS),
    "final_feature_source": str(FINAL_FEATURE_SET_PATH),
    "training_rows": TRAINING_ROW_COUNT,
    "validation_rows": VALIDATION_ROW_COUNT,
    "test_rows": TEST_ROW_COUNT,
    "scaler_fit_boundary": "Training partition only",
    "validation_used_for_scaler_fitting": False,
    "test_used_for_scaler_fitting": False,
    "feature_selection_completed_before_scaling": True,
    "resampling_performed": False,
    "model_fitting_performed": False
}

with open(
    SCALING_CONFIGURATION_PATH,
    "w"
) as f:
    json.dump(
        scaling_configuration,
        f,
        indent=2
    )

# ------------------------------------------------------------
# Output
# ------------------------------------------------------------

print("\n[SCALING INPUT]")
print(f"Final selected features : {len(FINAL_FEATURE_COLUMNS)}")
print(f"Scaler configuration    : {SCALER_TYPE}")

print("\n[PARTITION BOUNDARY]")
print(f"Training rows           : {TRAINING_ROW_COUNT:,}")
print(f"Validation rows         : {VALIDATION_ROW_COUNT:,}")
print(f"Test rows               : {TEST_ROW_COUNT:,}")

print("\n[TRAINING-ONLY FITTING RULE]")
print("✓ Scaler parameters will be fitted using Training data only")
print("✓ Validation data excluded from scaler fitting")
print("✓ Independent Test data excluded from scaler fitting")
print("✓ Final 32-feature set comes from Section 4.6")
print("✓ Feature-selection decisions are already finalized")
print("✓ No partition indices modified")
print("✓ No labels modified")
print("✓ No resampling performed")
print("✓ No model fitting performed")
print("✓ No large feature matrix materialized in this subsection")

print("\n[ARTIFACT]")
print(
    "✓ "
    + str(SCALING_CONFIGURATION_PATH)
)

print("\n" + "=" * 72)
print(
    "4.7.1 scaling configuration and "
    "training boundary established successfully."
)
print("=" * 72)

========================================================================
4.7.1 — SCALING CONFIGURATION & TRAINING BOUNDARY
========================================================================

[SCALING INPUT]
Final selected features : 32
Scaler configuration    : StandardScaler

[PARTITION BOUNDARY]
Training rows           : 1,814,018
Validation rows         : 451,215
Test rows               : 565,510

[TRAINING-ONLY FITTING RULE]
✓ Scaler parameters will be fitted using Training data only
✓ Validation data excluded from scaler fitting
✓ Independent Test data excluded from scaler fitting
✓ Final 32-feature set comes from Section 4.6
✓ Feature-selection decisions are already finalized
✓ No partition indices modified
✓ No labels modified
✓ No resampling performed
✓ No model fitting performed
✓ No large feature matrix materialized in this subsection

[ARTIFACT]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/scaling_configuration.json

========================================================================
4.7.1 scaling configuration and training boundary established successfully.
========================================================================

## 4.7.2 Training-Only Scaler Fitting

This subsection fits the feature-scaling transformation using the final
32-feature set established in Section 4.6.

The scaler is fitted exclusively on the Training partition. Validation and
Independent Test observations are not used to estimate any scaling
parameters, ensuring that information from either evaluation partition
cannot influence the preprocessing transformation.

StandardScaler is used so that each selected feature is centered using the
Training mean and scaled according to the Training standard deviation. The
fitted scaler will later be applied unchanged to the Training, Validation,
Test, and deployment/inference data.

Because the Training partition contains more than 1.8 million observations,
the scaler is fitted incrementally in memory-controlled chunks rather than
materializing the complete Training feature matrix at once.

No feature-selection decisions, partition assignments, labels, or feature
values in the persisted Stage-1 dataset are modified in this subsection.
Only the scaler parameters and fitting metadata are persisted for subsequent
model-preparation stages.

In [19]:
# ============================================================
# 4.7.2 — TRAINING-ONLY SCALER FITTING
# ============================================================

import json
import joblib
import numpy as np
from sklearn.preprocessing import StandardScaler

print("=" * 72)
print("4.7.2 — TRAINING-ONLY SCALER FITTING")
print("=" * 72)

# ------------------------------------------------------------
# 4.7.2.1 Recover Final Feature Set
# ------------------------------------------------------------

FINAL_FEATURE_SET_PATH = (
    FEATURE_SELECTION_DIR /
    "correlation_pruned_selected_features.json"
)

if not FINAL_FEATURE_SET_PATH.is_file():
    raise FileNotFoundError(
        "Final selected-feature artifact is missing:\n"
        f"{FINAL_FEATURE_SET_PATH}"
    )

with open(
    FINAL_FEATURE_SET_PATH,
    "r",
    encoding="utf-8"
) as f:
    final_feature_metadata = json.load(f)

if isinstance(final_feature_metadata, list):

    final_selected_features = list(
        final_feature_metadata
    )

elif isinstance(final_feature_metadata, dict):

    final_selected_features = None

    for key in [
        "selected_features",
        "retained_features",
        "features",
        "feature_columns"
    ]:

        if (
            key in final_feature_metadata
            and isinstance(
                final_feature_metadata[key],
                list
            )
        ):
            final_selected_features = list(
                final_feature_metadata[key]
            )
            break

    if final_selected_features is None:
        raise ValueError(
            "Could not identify the final selected-feature list "
            "in correlation_pruned_selected_features.json."
        )

else:

    raise ValueError(
        "Unexpected format in final selected-feature artifact."
    )


# ------------------------------------------------------------
# 4.7.2.2 Validate Final Feature Set
# ------------------------------------------------------------

if len(final_selected_features) != 32:
    raise ValueError(
        "Expected exactly 32 final selected features, "
        f"found {len(final_selected_features)}."
    )

if len(set(final_selected_features)) != 32:
    raise ValueError(
        "Duplicate feature names detected in the final "
        "selected feature set."
    )

if not set(final_selected_features).issubset(
    set(feature_columns)
):
    raise ValueError(
        "Final selected feature set contains features "
        "outside the original engineered feature space."
    )


# ------------------------------------------------------------
# 4.7.2.3 Validate Training Boundary
# ------------------------------------------------------------

if len(training_indices) != 1_814_018:
    raise ValueError(
        "Unexpected Training partition size. "
        f"Expected 1,814,018 rows, found "
        f"{len(training_indices):,}."
    )

if len(validation_indices) != 451_215:
    raise ValueError(
        "Unexpected Validation partition size. "
        f"Expected 451,215 rows, found "
        f"{len(validation_indices):,}."
    )

if len(test_indices) != 565_510:
    raise ValueError(
        "Unexpected Test partition size. "
        f"Expected 565,510 rows, found "
        f"{len(test_indices):,}."
    )


# ------------------------------------------------------------
# 4.7.2.4 Confirm Partition Exclusivity
# ------------------------------------------------------------

if len(
    np.intersect1d(
        training_indices,
        validation_indices
    )
) != 0:

    raise ValueError(
        "Training and Validation indices overlap."
    )

if len(
    np.intersect1d(
        training_indices,
        test_indices
    )
) != 0:

    raise ValueError(
        "Training and Test indices overlap."
    )

if len(
    np.intersect1d(
        validation_indices,
        test_indices
    )
) != 0:

    raise ValueError(
        "Validation and Test indices overlap."
    )


# ------------------------------------------------------------
# 4.7.2.5 Initialize Training-Only StandardScaler
# ------------------------------------------------------------

training_scaler = StandardScaler()

SCALER_CHUNK_SIZE = 100_000

training_row_count = len(training_indices)

print("\n[SCALER CONFIGURATION]")

print(
    f"Final selected features : "
    f"{len(final_selected_features)}"
)

print(
    "Scaler                  : StandardScaler"
)

print(
    "Fitting partition       : Training only"
)

print(
    f"Training rows            : "
    f"{training_row_count:,}"
)

print(
    f"Chunk size               : "
    f"{SCALER_CHUNK_SIZE:,}"
)


# ------------------------------------------------------------
# 4.7.2.6 Incremental Training-Only Fitting
# ------------------------------------------------------------

print("\n[TRAINING-ONLY FITTING]")

processed_rows = 0

for start in range(
    0,
    training_row_count,
    SCALER_CHUNK_SIZE
):

    end = min(
        start + SCALER_CHUNK_SIZE,
        training_row_count
    )

    chunk_indices = training_indices[
        start:end
    ]

    chunk = stage1_df.loc[
        chunk_indices,
        final_selected_features
    ].to_numpy(
        dtype=np.float64,
        copy=True
    )

    if not np.isfinite(chunk).all():
        raise ValueError(
            "Non-finite values detected in a Training "
            "scaler-fitting chunk."
        )

    training_scaler.partial_fit(chunk)

    processed_rows += len(chunk_indices)

    del chunk

    if (
        processed_rows == training_row_count
        or processed_rows % (
            SCALER_CHUNK_SIZE * 5
        ) == 0
    ):

        print(
            f"  Processed "
            f"{processed_rows:,} / "
            f"{training_row_count:,} Training rows"
        )


# ------------------------------------------------------------
# 4.7.2.7 Validate Fitted Scaler Parameters
# ------------------------------------------------------------

if not hasattr(
    training_scaler,
    "mean_"
):

    raise ValueError(
        "Scaler fitting did not produce mean parameters."
    )

if not hasattr(
    training_scaler,
    "scale_"
):

    raise ValueError(
        "Scaler fitting did not produce scale parameters."
    )

if not hasattr(
    training_scaler,
    "var_"
):

    raise ValueError(
        "Scaler fitting did not produce variance parameters."
    )

if training_scaler.n_features_in_ != 32:
    raise ValueError(
        "Unexpected scaler feature count. "
        f"Expected 32, found "
        f"{training_scaler.n_features_in_}."
    )

if training_scaler.n_samples_seen_ != training_row_count:
    raise ValueError(
        "Scaler did not observe the expected number of "
        "Training observations."
    )

if not np.isfinite(
    training_scaler.mean_
).all():

    raise ValueError(
        "Non-finite values detected in fitted scaler means."
    )

if not np.isfinite(
    training_scaler.scale_
).all():

    raise ValueError(
        "Non-finite values detected in fitted scaler scales."
    )


# ------------------------------------------------------------
# 4.7.2.8 Persist Fitted Scaler
# ------------------------------------------------------------

SCALER_PATH = (
    MODEL_PREPARATION_V2_DIR /
    "feature_scaling" /
    "training_only_standard_scaler.joblib"
)

SCALER_PATH.parent.mkdir(
    parents=True,
    exist_ok=True
)

joblib.dump(
    training_scaler,
    SCALER_PATH
)


# ------------------------------------------------------------
# 4.7.2.9 Persist Scaler Metadata
# ------------------------------------------------------------

SCALER_METADATA_PATH = (
    MODEL_PREPARATION_V2_DIR /
    "feature_scaling" /
    "training_only_scaler_metadata.json"
)

scaler_metadata = {

    "stage": "4.7",

    "subsection": "4.7.2",

    "name": (
        "Training-Only Scaler Fitting"
    ),

    "scaler_type": "StandardScaler",

    "fit_partition": "Training",

    "validation_used_for_fitting": False,

    "test_used_for_fitting": False,

    "training_row_count": int(
        training_row_count
    ),

    "validation_row_count": int(
        len(validation_indices)
    ),

    "test_row_count": int(
        len(test_indices)
    ),

    "feature_count": int(
        len(final_selected_features)
    ),

    "features": final_selected_features,

    "chunk_size": int(
        SCALER_CHUNK_SIZE
    ),

    "samples_seen_by_scaler": int(
        training_scaler.n_samples_seen_
    ),

    "stage1_dataset_modified": False,

    "partition_indices_modified": False,

    "labels_modified": False,

    "feature_selection_modified": False,

    "resampling_performed": False,

    "model_fitting_performed": False
}

with open(
    SCALER_METADATA_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        scaler_metadata,
        f,
        indent=4
    )


# ------------------------------------------------------------
# 4.7.2.10 Final Validation Output
# ------------------------------------------------------------

print("\n[SCALER FITTING RESULT]")

print(
    f"Features fitted          : "
    f"{training_scaler.n_features_in_}"
)

print(
    f"Training samples seen    : "
    f"{training_scaler.n_samples_seen_:,}"
)

print(
    "Validation used          : No"
)

print(
    "Test used                : No"
)

print(
    "✓ Scaler fitted using Training data only"
)

print(
    "✓ All 32 final features included"
)

print(
    "✓ Scaler parameters are finite"
)

print(
    "✓ Training partition size verified"
)

print(
    "✓ Validation partition excluded"
)

print(
    "✓ Independent Test partition excluded"
)

print(
    "✓ No partition indices modified"
)

print(
    "✓ No labels modified"
)

print(
    "✓ No feature-selection decisions modified"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ Stage-1 dataset remains unchanged"
)


# ------------------------------------------------------------
# 4.7.2.11 Artifact Persistence
# ------------------------------------------------------------

print("\n[ARTIFACTS]")

print(
    f"✓ Fitted scaler persisted:\n"
    f"  {SCALER_PATH}"
)

print(
    f"✓ Scaler metadata persisted:\n"
    f"  {SCALER_METADATA_PATH}"
)

print("\n" + "=" * 72)

print(
    "4.7.2 training-only scaler fitting "
    "completed successfully."
)

print("=" * 72)

========================================================================
4.7.2 — TRAINING-ONLY SCALER FITTING
========================================================================

[SCALER CONFIGURATION]
Final selected features : 32
Scaler                  : StandardScaler
Fitting partition       : Training only
Training rows            : 1,814,018
Chunk size               : 100,000

[TRAINING-ONLY FITTING]
  Processed 500,000 / 1,814,018 Training rows
  Processed 1,000,000 / 1,814,018 Training rows
  Processed 1,500,000 / 1,814,018 Training rows
  Processed 1,814,018 / 1,814,018 Training rows

[SCALER FITTING RESULT]
Features fitted          : 32
Training samples seen    : 1,814,018
Validation used          : No
Test used                : No
✓ Scaler fitted using Training data only
✓ All 32 final features included
✓ Scaler parameters are finite
✓ Training partition size verified
✓ Validation partition excluded
✓ Independent Test partition excluded
✓ No partition indices modified
✓ No labels modified
✓ No feature-selection decisions modified
✓ No resampling performed
✓ No model fitting performed
✓ Stage-1 dataset remains unchanged

[ARTIFACTS]
✓ Fitted scaler persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/training_only_standard_scaler.joblib
✓ Scaler metadata persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/training_only_scaler_metadata.json

========================================================================
4.7.2 training-only scaler fitting completed successfully.
========================================================================

# 4.7.3 Partition-Wise Feature Transformation

This subsection applies the StandardScaler fitted exclusively on the Training
partition in Section 4.7.2 to all three model-development partitions.

The same fitted scaler and the same final 32-feature ordering are used for
Training, Validation, and the independent Test partition. No scaler fitting
or parameter estimation is performed on Validation or Test observations.

To maintain memory efficiency, each partition is transformed incrementally
in fixed-size chunks. The resulting scaled feature matrices are persisted
as partition-specific artifacts so that later model-training stages can
reuse the exact same preprocessing outputs without repeating the
transformation.

The transformation does not modify the original Stage-1 dataset, partition
indices, labels, or final feature-selection decisions. The independent Test
partition remains isolated and is transformed only after the Training-fitted
scaler has already been fixed.

All three transformed partitions retain their original row counts and the
same 32-feature ordering established in Section 4.6.

In [20]:
# ============================================================
# 4.7.3 — PARTITION-WISE FEATURE TRANSFORMATION
# ============================================================

import json
import numpy as np
from numpy.lib.format import open_memmap

print("=" * 72)
print("4.7.3 — PARTITION-WISE FEATURE TRANSFORMATION")
print("=" * 72)


# ------------------------------------------------------------
# 4.7.3.1 Recover / Validate Final Feature Set
# ------------------------------------------------------------

FINAL_FEATURE_SET_PATH = (
    FEATURE_SELECTION_DIR /
    "correlation_pruned_selected_features.json"
)

if not FINAL_FEATURE_SET_PATH.is_file():
    raise FileNotFoundError(
        "Final selected-feature artifact is missing:\n"
        f"{FINAL_FEATURE_SET_PATH}"
    )

with open(
    FINAL_FEATURE_SET_PATH,
    "r",
    encoding="utf-8"
) as f:
    final_feature_metadata = json.load(f)


if isinstance(final_feature_metadata, list):

    final_selected_features = list(
        final_feature_metadata
    )

elif isinstance(final_feature_metadata, dict):

    final_selected_features = None

    for key in [
        "selected_features",
        "retained_features",
        "features",
        "feature_columns"
    ]:

        if (
            key in final_feature_metadata
            and isinstance(
                final_feature_metadata[key],
                list
            )
        ):
            final_selected_features = list(
                final_feature_metadata[key]
            )
            break

    if final_selected_features is None:
        raise ValueError(
            "Could not identify the final selected-feature "
            "list in the persisted feature artifact."
        )

else:

    raise ValueError(
        "Unexpected format in final selected-feature artifact."
    )


if len(final_selected_features) != 32:
    raise ValueError(
        "Expected 32 final selected features, "
        f"found {len(final_selected_features)}."
    )


# ------------------------------------------------------------
# 4.7.3.2 Load the Persisted Training-Fitted Scaler
# ------------------------------------------------------------

SCALER_PATH = (
    MODEL_PREPARATION_V2_DIR /
    "feature_scaling" /
    "training_only_standard_scaler.joblib"
)

if not SCALER_PATH.is_file():
    raise FileNotFoundError(
        "Training-only scaler artifact is missing:\n"
        f"{SCALER_PATH}"
    )

training_scaler = joblib.load(
    SCALER_PATH
)

if training_scaler.n_features_in_ != 32:
    raise ValueError(
        "Persisted scaler does not contain the expected "
        f"32 features. Found "
        f"{training_scaler.n_features_in_}."
    )


# ------------------------------------------------------------
# 4.7.3.3 Partition Validation
# ------------------------------------------------------------

PARTITIONS = {
    "Training": training_indices,
    "Validation": validation_indices,
    "Test": test_indices
}

EXPECTED_PARTITION_SIZES = {
    "Training": 1_814_018,
    "Validation": 451_215,
    "Test": 565_510
}


for partition_name, partition_indices in PARTITIONS.items():

    expected_size = EXPECTED_PARTITION_SIZES[
        partition_name
    ]

    if len(partition_indices) != expected_size:
        raise ValueError(
            f"{partition_name} partition size mismatch. "
            f"Expected {expected_size:,}, found "
            f"{len(partition_indices):,}."
        )


# ------------------------------------------------------------
# 4.7.3.4 Transformation Configuration
# ------------------------------------------------------------

SCALING_CHUNK_SIZE = 100_000

SCALING_OUTPUT_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "feature_scaling"
)

SCALING_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

SCALED_OUTPUT_PATHS = {

    "Training":
        SCALING_OUTPUT_DIR /
        "X_train_scaled.npy",

    "Validation":
        SCALING_OUTPUT_DIR /
        "X_validation_scaled.npy",

    "Test":
        SCALING_OUTPUT_DIR /
        "X_test_scaled.npy"
}


print("\n[TRANSFORMATION CONFIGURATION]")

print(
    f"Final selected features : "
    f"{len(final_selected_features)}"
)

print(
    "Scaler                  : "
    "Training-fitted StandardScaler"
)

print(
    "Transformation mode     : "
    "Partition-wise chunked"
)

print(
    f"Chunk size               : "
    f"{SCALING_CHUNK_SIZE:,}"
)

print(
    "Output dtype             : float32"
)


# ------------------------------------------------------------
# 4.7.3.5 Partition-Wise Transformation Function
# ------------------------------------------------------------

def transform_and_persist_partition(
    partition_name,
    partition_indices,
    output_path
):

    row_count = len(partition_indices)

    # Create disk-backed .npy array.
    # This avoids keeping the complete scaled partition in RAM.
    scaled_output = open_memmap(
        output_path,
        mode="w+",
        dtype=np.float32,
        shape=(
            row_count,
            len(final_selected_features)
        )
    )

    processed_rows = 0

    print(
        f"\n[{partition_name.upper()} TRANSFORMATION]"
    )

    for start in range(
        0,
        row_count,
        SCALING_CHUNK_SIZE
    ):

        end = min(
            start + SCALING_CHUNK_SIZE,
            row_count
        )

        chunk_indices = partition_indices[
            start:end
        ]

        # Read only the current partition chunk.
        feature_chunk = stage1_df.loc[
            chunk_indices,
            final_selected_features
        ].to_numpy(
            dtype=np.float64,
            copy=True
        )

        if not np.isfinite(
            feature_chunk
        ).all():

            del feature_chunk
            del scaled_output

            raise ValueError(
                f"Non-finite values detected in the "
                f"{partition_name} transformation chunk."
            )

        # IMPORTANT:
        # transform() only applies the already-fitted
        # Training scaler. It does NOT refit it.
        scaled_chunk = training_scaler.transform(
            feature_chunk
        )

        if not np.isfinite(
            scaled_chunk
        ).all():

            del feature_chunk
            del scaled_chunk
            del scaled_output

            raise ValueError(
                f"Non-finite scaled values detected in "
                f"the {partition_name} partition."
            )

        scaled_output[
            start:end,
            :
        ] = scaled_chunk.astype(
            np.float32,
            copy=False
        )

        processed_rows += (
            end - start
        )

        del feature_chunk
        del scaled_chunk

        if (
            processed_rows == row_count
            or processed_rows % (
                SCALING_CHUNK_SIZE * 5
            ) == 0
        ):

            print(
                f"  Processed "
                f"{processed_rows:,} / "
                f"{row_count:,} rows"
            )

    # Flush data to disk.
    scaled_output.flush()

    del scaled_output

    print(
        f"  ✓ {partition_name} transformation completed"
    )

    print(
        f"  ✓ Persisted: {output_path}"
    )


# ------------------------------------------------------------
# 4.7.3.6 Transform Training Partition
# ------------------------------------------------------------

transform_and_persist_partition(
    "Training",
    training_indices,
    SCALED_OUTPUT_PATHS["Training"]
)


# ------------------------------------------------------------
# 4.7.3.7 Transform Validation Partition
# ------------------------------------------------------------

transform_and_persist_partition(
    "Validation",
    validation_indices,
    SCALED_OUTPUT_PATHS["Validation"]
)


# ------------------------------------------------------------
# 4.7.3.8 Transform Independent Test Partition
# ------------------------------------------------------------

transform_and_persist_partition(
    "Test",
    test_indices,
    SCALED_OUTPUT_PATHS["Test"]
)


# ------------------------------------------------------------
# 4.7.3.9 Persist Transformation Metadata
# ------------------------------------------------------------

SCALING_TRANSFORMATION_METADATA_PATH = (
    SCALING_OUTPUT_DIR /
    "partition_wise_transformation_metadata.json"
)

transformation_metadata = {

    "stage": "4.7",

    "subsection": "4.7.3",

    "name": (
        "Partition-Wise Feature Transformation"
    ),

    "scaler_type": "StandardScaler",

    "scaler_source": str(
        SCALER_PATH
    ),

    "scaler_fit_partition": "Training",

    "feature_count": int(
        len(final_selected_features)
    ),

    "features": final_selected_features,

    "chunk_size": int(
        SCALING_CHUNK_SIZE
    ),

    "output_dtype": "float32",

    "partitions": {

        "Training": {
            "rows": int(
                len(training_indices)
            ),
            "output": str(
                SCALED_OUTPUT_PATHS["Training"]
            ),
            "used_for_scaler_fitting": True
        },

        "Validation": {
            "rows": int(
                len(validation_indices)
            ),
            "output": str(
                SCALED_OUTPUT_PATHS["Validation"]
            ),
            "used_for_scaler_fitting": False
        },

        "Test": {
            "rows": int(
                len(test_indices)
            ),
            "output": str(
                SCALED_OUTPUT_PATHS["Test"]
            ),
            "used_for_scaler_fitting": False
        }
    },

    "validation_used_for_scaler_fitting": False,

    "test_used_for_scaler_fitting": False,

    "stage1_dataset_modified": False,

    "partition_indices_modified": False,

    "labels_modified": False,

    "feature_selection_modified": False,

    "resampling_performed": False,

    "model_fitting_performed": False
}

with open(
    SCALING_TRANSFORMATION_METADATA_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        transformation_metadata,
        f,
        indent=4
    )


# ------------------------------------------------------------
# 4.7.3.10 Final Validation
# ------------------------------------------------------------

print("\n[FINAL TRANSFORMATION VALIDATION]")

for partition_name, output_path in (
    SCALED_OUTPUT_PATHS.items()
):

    if not output_path.is_file():

        raise FileNotFoundError(
            f"Scaled {partition_name} artifact "
            "was not created."
        )

    # Lightweight memory-mapped inspection.
    scaled_data = np.load(
        output_path,
        mmap_mode="r"
    )

    expected_rows = EXPECTED_PARTITION_SIZES[
        partition_name
    ]

    if scaled_data.shape != (
        expected_rows,
        32
    ):

        del scaled_data

        raise ValueError(
            f"{partition_name} scaled shape mismatch. "
            f"Expected "
            f"({expected_rows}, 32), found "
            f"{scaled_data.shape}."
        )

    # Check finite values in chunks without loading
    # the entire scaled matrix into RAM.
    finite_check = True

    for start in range(
        0,
        expected_rows,
        SCALING_CHUNK_SIZE
    ):

        end = min(
            start + SCALING_CHUNK_SIZE,
            expected_rows
        )

        if not np.isfinite(
            scaled_data[start:end]
        ).all():

            finite_check = False
            break

    del scaled_data

    if not finite_check:

        raise ValueError(
            f"Non-finite values found in persisted "
            f"{partition_name} scaled data."
        )

    print(
        f"✓ {partition_name}: "
        f"{expected_rows:,} × 32"
    )


print(
    "\n✓ Same Training-fitted scaler applied to "
    "all partitions"
)

print(
    "✓ Training was not refitted during transformation"
)

print(
    "✓ Validation was transformed without fitting"
)

print(
    "✓ Independent Test was transformed without fitting"
)

print(
    "✓ All scaled values are finite"
)

print(
    "✓ Feature count remains 32"
)

print(
    "✓ Partition row counts remain unchanged"
)

print(
    "✓ Stage-1 dataset remains unchanged"
)

print(
    "✓ Partition indices remain unchanged"
)

print(
    "✓ Labels remain unchanged"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No model fitting performed"
)


print("\n[ARTIFACTS]")

for partition_name, output_path in (
    SCALED_OUTPUT_PATHS.items()
):

    print(
        f"✓ {partition_name} scaled data:\n"
        f"  {output_path}"
    )

print(
    f"✓ Transformation metadata:\n"
    f"  {SCALING_TRANSFORMATION_METADATA_PATH}"
)


print("\n" + "=" * 72)

print(
    "4.7.3 partition-wise feature transformation "
    "completed successfully."
)

print("=" * 72)

========================================================================
4.7.3 — PARTITION-WISE FEATURE TRANSFORMATION
========================================================================

[TRANSFORMATION CONFIGURATION]
Final selected features : 32
Scaler                  : Training-fitted StandardScaler
Transformation mode     : Partition-wise chunked
Chunk size               : 100,000
Output dtype             : float32

[TRAINING TRANSFORMATION]
  Processed 500,000 / 1,814,018 rows
  Processed 1,000,000 / 1,814,018 rows
  Processed 1,500,000 / 1,814,018 rows
  Processed 1,814,018 / 1,814,018 rows
  ✓ Training transformation completed
  ✓ Persisted: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/X_train_scaled.npy

[VALIDATION TRANSFORMATION]
  Processed 451,215 / 451,215 rows
  ✓ Validation transformation completed
  ✓ Persisted: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/X_validation_scaled.npy

[TEST TRANSFORMATION]
  Processed 500,000 / 565,510 rows
  Processed 565,510 / 565,510 rows
  ✓ Test transformation completed
  ✓ Persisted: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/X_test_scaled.npy

[FINAL TRANSFORMATION VALIDATION]
✓ Training: 1,814,018 × 32
✓ Validation: 451,215 × 32
✓ Test: 565,510 × 32

✓ Same Training-fitted scaler applied to all partitions
✓ Training was not refitted during transformation
✓ Validation was transformed without fitting
✓ Independent Test was transformed without fitting
✓ All scaled values are finite
✓ Feature count remains 32
✓ Partition row counts remain unchanged
✓ Stage-1 dataset remains unchanged
✓ Partition indices remain unchanged
✓ Labels remain unchanged
✓ No resampling performed
✓ No model fitting performed

[ARTIFACTS]
✓ Training scaled data:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/X_train_scaled.npy
✓ Validation scaled data:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/X_validation_scaled.npy
✓ Test scaled data:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/X_test_scaled.npy
✓ Transformation metadata:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/partition_wise_transformation_metadata.json

========================================================================
4.7.3 partition-wise feature transformation completed successfully.
========================================================================

# 4.7.4 — Scaled Feature-Space Validation

This subsection validates the persisted scaled feature space produced in
Section 4.7.3. The purpose is to confirm that the final 32-feature
representation has been transformed consistently across the Training,
Validation, and independent Test partitions using the single
Training-fitted StandardScaler.

Validation is performed on the persisted artifacts rather than refitting
or recreating the scaling pipeline. The checks verify partition shapes,
feature dimensionality, finite values, feature-order consistency, and the
expected statistical behaviour of the Training-scaled feature space.

The Training partition is expected to have approximately zero mean and
unit standard deviation because the scaler was fitted on Training data.
Validation and Test partitions are not expected to have zero mean or unit
variance, since they are independent observations transformed using the
Training-fitted scaler.

To avoid unnecessary memory consumption, the persisted NumPy arrays are
validated using memory mapping and chunk-wise statistical calculations.
No partition data are modified, no scaler parameters are refitted, and no
model training or resampling is performed.

Successful completion establishes that the persisted scaled feature space
is internally consistent and ready for subsequent model-preparation and
training stages.

In [21]:
# ============================================================
# 4.7.4 — SCALED FEATURE-SPACE VALIDATION
# ============================================================

import json
import numpy as np
from pathlib import Path

print("=" * 72)
print("4.7.4 — SCALED FEATURE-SPACE VALIDATION")
print("=" * 72)

# ------------------------------------------------------------
# 4.7.4.1 Persisted artifact paths
# ------------------------------------------------------------

SCALING_DIR = MODEL_PREPARATION_V2_DIR / "feature_scaling"

X_TRAIN_SCALED_PATH = SCALING_DIR / "X_train_scaled.npy"
X_VALIDATION_SCALED_PATH = SCALING_DIR / "X_validation_scaled.npy"
X_TEST_SCALED_PATH = SCALING_DIR / "X_test_scaled.npy"

SCALER_METADATA_PATH = (
    SCALING_DIR / "training_only_scaler_metadata.json"
)

TRANSFORMATION_METADATA_PATH = (
    SCALING_DIR / "partition_wise_transformation_metadata.json"
)

required_paths = [
    X_TRAIN_SCALED_PATH,
    X_VALIDATION_SCALED_PATH,
    X_TEST_SCALED_PATH,
    SCALER_METADATA_PATH,
    TRANSFORMATION_METADATA_PATH,
]

missing_paths = [
    str(path)
    for path in required_paths
    if not path.exists()
]

if missing_paths:
    raise FileNotFoundError(
        "Required persisted scaling artifacts are missing:\n"
        + "\n".join(missing_paths)
    )

print("\n[PERSISTED ARTIFACTS]")
print("✓ Training scaled data found")
print("✓ Validation scaled data found")
print("✓ Test scaled data found")
print("✓ Training-only scaler metadata found")
print("✓ Partition-wise transformation metadata found")


# ------------------------------------------------------------
# 4.7.4.2 Memory-mapped loading
# ------------------------------------------------------------

# Memory mapping prevents the complete arrays from being copied
# into RAM during validation.

X_train_scaled = np.load(
    X_TRAIN_SCALED_PATH,
    mmap_mode="r"
)

X_validation_scaled = np.load(
    X_VALIDATION_SCALED_PATH,
    mmap_mode="r"
)

X_test_scaled = np.load(
    X_TEST_SCALED_PATH,
    mmap_mode="r"
)

print("\n[SCALED FEATURE-SPACE SHAPES]")
print(
    f"Training   : {X_train_scaled.shape}"
)
print(
    f"Validation : {X_validation_scaled.shape}"
)
print(
    f"Test       : {X_test_scaled.shape}"
)


# ------------------------------------------------------------
# 4.7.4.3 Expected partition dimensions
# ------------------------------------------------------------

EXPECTED_TRAIN_ROWS = 1_814_018
EXPECTED_VALIDATION_ROWS = 451_215
EXPECTED_TEST_ROWS = 565_510
EXPECTED_FEATURES = 32

expected_shapes = {
    "Training": (
        EXPECTED_TRAIN_ROWS,
        EXPECTED_FEATURES
    ),
    "Validation": (
        EXPECTED_VALIDATION_ROWS,
        EXPECTED_FEATURES
    ),
    "Test": (
        EXPECTED_TEST_ROWS,
        EXPECTED_FEATURES
    ),
}

actual_shapes = {
    "Training": X_train_scaled.shape,
    "Validation": X_validation_scaled.shape,
    "Test": X_test_scaled.shape,
}

for partition_name in expected_shapes:
    if actual_shapes[partition_name] != expected_shapes[partition_name]:
        raise ValueError(
            f"{partition_name} scaled shape mismatch: "
            f"expected {expected_shapes[partition_name]}, "
            f"found {actual_shapes[partition_name]}"
        )

print("\n[DIMENSION VALIDATION]")
print("✓ Training shape verified")
print("✓ Validation shape verified")
print("✓ Test shape verified")
print("✓ All partitions contain exactly 32 final features")


# ------------------------------------------------------------
# 4.7.4.4 Data type and finite-value validation
# ------------------------------------------------------------

print("\n[DATA INTEGRITY VALIDATION]")

for partition_name, array in [
    ("Training", X_train_scaled),
    ("Validation", X_validation_scaled),
    ("Test", X_test_scaled),
]:

    if not np.issubdtype(array.dtype, np.floating):
        raise TypeError(
            f"{partition_name} scaled array is not floating-point: "
            f"{array.dtype}"
        )

    finite = True

    # Check in chunks so no full-size temporary matrix is created.
    chunk_size = 100_000

    for start in range(0, array.shape[0], chunk_size):
        end = min(start + chunk_size, array.shape[0])
        chunk = array[start:end]

        if not np.isfinite(chunk).all():
            finite = False
            break

    if not finite:
        raise ValueError(
            f"Non-finite values detected in {partition_name} "
            "scaled data."
        )

    print(
        f"✓ {partition_name} contains only finite "
        f"{array.dtype} values"
    )


# ------------------------------------------------------------
# 4.7.4.5 Chunk-wise Training statistical validation
# ------------------------------------------------------------

# The Training partition was used to fit StandardScaler.
# Therefore its transformed features should have approximately:
# mean = 0
# standard deviation = 1

def chunked_mean_std(array, chunk_size=100_000):
    """
    Calculate per-feature mean and standard deviation without
    materializing the complete array in RAM.
    """

    n_rows = array.shape[0]
    n_features = array.shape[1]

    total_count = 0
    total_sum = np.zeros(n_features, dtype=np.float64)
    total_sum_sq = np.zeros(n_features, dtype=np.float64)

    for start in range(0, n_rows, chunk_size):
        end = min(start + chunk_size, n_rows)

        chunk = np.asarray(
            array[start:end],
            dtype=np.float64
        )

        total_count += chunk.shape[0]
        total_sum += chunk.sum(axis=0)
        total_sum_sq += np.square(chunk).sum(axis=0)

    mean = total_sum / total_count

    variance = (
        total_sum_sq / total_count
    ) - np.square(mean)

    variance = np.maximum(variance, 0.0)

    std = np.sqrt(variance)

    return mean, std


print("\n[TRAINING SCALED STATISTICS]")

training_mean, training_std = chunked_mean_std(
    X_train_scaled
)

max_abs_training_mean = float(
    np.max(np.abs(training_mean))
)

max_training_std_error = float(
    np.max(np.abs(training_std - 1.0))
)

print(
    f"Maximum absolute Training feature mean : "
    f"{max_abs_training_mean:.8f}"
)

print(
    f"Maximum absolute Training std. error  : "
    f"{max_training_std_error:.8f}"
)

# Numerical tolerance for persisted float32 transformed data.
if max_abs_training_mean > 1e-4:
    raise ValueError(
        "Training scaled feature means exceed the expected "
        "numerical tolerance."
    )

if max_training_std_error > 1e-4:
    raise ValueError(
        "Training scaled feature standard deviations exceed "
        "the expected numerical tolerance."
    )

print(
    "✓ Training features have approximately zero mean"
)

print(
    "✓ Training features have approximately unit standard deviation"
)


# ------------------------------------------------------------
# 4.7.4.6 Validation/Test statistical sanity check
# ------------------------------------------------------------

# Validation and Test must NOT be required to have mean 0/std 1.
# They were transformed using the Training-fitted scaler.

validation_mean, validation_std = chunked_mean_std(
    X_validation_scaled
)

test_mean, test_std = chunked_mean_std(
    X_test_scaled
)

print("\n[VALIDATION / TEST STATISTICAL SANITY CHECK]")

print(
    f"Validation mean range : "
    f"[{validation_mean.min():.6f}, "
    f"{validation_mean.max():.6f}]"
)

print(
    f"Validation std range  : "
    f"[{validation_std.min():.6f}, "
    f"{validation_std.max():.6f}]"
)

print(
    f"Test mean range       : "
    f"[{test_mean.min():.6f}, "
    f"{test_mean.max():.6f}]"
)

print(
    f"Test std range        : "
    f"[{test_std.min():.6f}, "
    f"{test_std.max():.6f}]"
)

print(
    "✓ Validation statistics checked without refitting the scaler"
)

print(
    "✓ Test statistics checked without refitting the scaler"
)


# ------------------------------------------------------------
# 4.7.4.7 Metadata consistency validation
# ------------------------------------------------------------

with open(
    SCALER_METADATA_PATH,
    "r",
    encoding="utf-8"
) as f:
    scaler_metadata = json.load(f)

with open(
    TRANSFORMATION_METADATA_PATH,
    "r",
    encoding="utf-8"
) as f:
    transformation_metadata = json.load(f)

print("\n[METADATA VALIDATION]")

# Confirm that the persisted metadata records the expected
# final feature dimensionality.

metadata_text = json.dumps(
    scaler_metadata
).lower()

transformation_text = json.dumps(
    transformation_metadata
).lower()

if "32" not in metadata_text:
    print(
        "⚠ Training scaler metadata does not explicitly "
        "contain the feature count as text."
    )
else:
    print(
        "✓ Training scaler metadata contains the final "
        "32-feature configuration"
    )

if "32" not in transformation_text:
    print(
        "⚠ Transformation metadata does not explicitly "
        "contain the feature count as text."
    )
else:
    print(
        "✓ Transformation metadata contains the final "
        "32-feature configuration"
    )


# ------------------------------------------------------------
# 4.7.4.8 Final validation summary
# ------------------------------------------------------------

print("\n[FINAL VALIDATION]")

print("✓ Persisted Training scaled artifact verified")
print("✓ Persisted Validation scaled artifact verified")
print("✓ Persisted Test scaled artifact verified")
print("✓ Training/Validation/Test row counts preserved")
print("✓ Final feature count remains 32")
print("✓ All scaled values are finite")
print("✓ Training scaled means are approximately zero")
print("✓ Training scaled standard deviations are approximately one")
print("✓ Validation and Test were transformed without refitting")
print("✓ No partition indices modified")
print("✓ No labels modified")
print("✓ No feature-selection decisions modified")
print("✓ No resampling performed")
print("✓ No model fitting performed")
print("✓ No Stage-1 data modified")
print("✓ Validation performed using persisted artifacts only")

print("\n[ARTIFACTS VALIDATED]")
print(f"✓ {X_TRAIN_SCALED_PATH}")
print(f"✓ {X_VALIDATION_SCALED_PATH}")
print(f"✓ {X_TEST_SCALED_PATH}")
print(f"✓ {SCALER_METADATA_PATH}")
print(f"✓ {TRANSFORMATION_METADATA_PATH}")

print("\n" + "=" * 72)
print(
    "4.7.4 scaled feature-space validation completed successfully."
)
print("=" * 72)

========================================================================
4.7.4 — SCALED FEATURE-SPACE VALIDATION
========================================================================

[PERSISTED ARTIFACTS]
✓ Training scaled data found
✓ Validation scaled data found
✓ Test scaled data found
✓ Training-only scaler metadata found
✓ Partition-wise transformation metadata found

[SCALED FEATURE-SPACE SHAPES]
Training   : (1814018, 32)
Validation : (451215, 32)
Test       : (565510, 32)

[DIMENSION VALIDATION]
✓ Training shape verified
✓ Validation shape verified
✓ Test shape verified
✓ All partitions contain exactly 32 final features

[DATA INTEGRITY VALIDATION]
✓ Training contains only finite float32 values
✓ Validation contains only finite float32 values
✓ Test contains only finite float32 values

[TRAINING SCALED STATISTICS]
Maximum absolute Training feature mean : 0.00000002
Maximum absolute Training std. error  : 0.00000006
✓ Training features have approximately zero mean
✓ Training features have approximately unit standard deviation

[VALIDATION / TEST STATISTICAL SANITY CHECK]
Validation mean range : [-0.046849, 0.101986]
Validation std range  : [0.973388, 1.240239]
Test mean range       : [-0.019536, 0.034523]
Test std range        : [0.990070, 1.088353]
✓ Validation statistics checked without refitting the scaler
✓ Test statistics checked without refitting the scaler

[METADATA VALIDATION]
✓ Training scaler metadata contains the final 32-feature configuration
✓ Transformation metadata contains the final 32-feature configuration

[FINAL VALIDATION]
✓ Persisted Training scaled artifact verified
✓ Persisted Validation scaled artifact verified
✓ Persisted Test scaled artifact verified
✓ Training/Validation/Test row counts preserved
✓ Final feature count remains 32
✓ All scaled values are finite
✓ Training scaled means are approximately zero
✓ Training scaled standard deviations are approximately one
✓ Validation and Test were transformed without refitting
✓ No partition indices modified
✓ No labels modified
✓ No feature-selection decisions modified
✓ No resampling performed
✓ No model fitting performed
✓ No Stage-1 data modified
✓ Validation performed using persisted artifacts only

[ARTIFACTS VALIDATED]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/X_train_scaled.npy
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/X_validation_scaled.npy
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/X_test_scaled.npy
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/training_only_scaler_metadata.json
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/partition_wise_transformation_metadata.json

========================================================================
4.7.4 scaled feature-space validation completed successfully.
========================================================================

# 4.7.5 Scaler & Model-Ready Feature Artifact Persistence

This subsection finalizes the preprocessing artifacts produced in
Section 4.7 for downstream model development.

The training-fitted StandardScaler, the transformed Training,
Validation, and independent Test feature matrices, and the final
32-feature configuration are recorded as the model-ready feature
space.

The persisted artifacts preserve the exact feature order and
preprocessing configuration required by the Random Forest, LSTM,
ensemble, explainability, and later inference pipelines. The
Training, Validation, and Test partitions remain unchanged, and
the independent Test partition is not used for any fitting or
feature-selection decision.

Only previously persisted artifacts are inspected and documented in
this subsection. No large Stage-1 dataset is reloaded, no additional
transformation is performed, and no model is trained. A compact
metadata manifest is persisted to provide a reproducible reference
for all downstream stages.

In [22]:
# ============================================================
# 4.7.5 — SCALER & MODEL-READY FEATURE ARTIFACT PERSISTENCE
# ============================================================

import json
from pathlib import Path
import numpy as np


print("=" * 72)
print("4.7.5 — SCALER & MODEL-READY FEATURE ARTIFACT PERSISTENCE")
print("=" * 72)


# ------------------------------------------------------------
# 4.7.5.1 Persisted Artifact Paths
# ------------------------------------------------------------

SCALING_DIR = MODEL_PREPARATION_V2_DIR / "feature_scaling"

TRAINING_SCALED_PATH = (
    SCALING_DIR / "X_train_scaled.npy"
)

VALIDATION_SCALED_PATH = (
    SCALING_DIR / "X_validation_scaled.npy"
)

TEST_SCALED_PATH = (
    SCALING_DIR / "X_test_scaled.npy"
)

SCALER_PATH = (
    SCALING_DIR / "training_only_standard_scaler.joblib"
)

SCALER_METADATA_PATH = (
    SCALING_DIR / "training_only_scaler_metadata.json"
)

TRANSFORMATION_METADATA_PATH = (
    SCALING_DIR / "partition_wise_transformation_metadata.json"
)

FINAL_FEATURE_VALIDATION_PATH = (
    MODEL_PREPARATION_V2_DIR
    / "feature_selection"
    / "final_feature_set_validation.json"
)

FINAL_FEATURE_ORDER_PATH = (
    MODEL_PREPARATION_V2_DIR
    / "feature_selection"
    / "correlation_pruned_selected_features.json"
)

MODEL_READY_METADATA_PATH = (
    SCALING_DIR / "model_ready_feature_artifacts.json"
)


# ------------------------------------------------------------
# 4.7.5.2 Confirm Required Artifacts Exist
# ------------------------------------------------------------

required_artifacts = {
    "Training scaled data": TRAINING_SCALED_PATH,
    "Validation scaled data": VALIDATION_SCALED_PATH,
    "Test scaled data": TEST_SCALED_PATH,
    "Training-only scaler": SCALER_PATH,
    "Scaler metadata": SCALER_METADATA_PATH,
    "Transformation metadata": TRANSFORMATION_METADATA_PATH,
    "Final feature validation": FINAL_FEATURE_VALIDATION_PATH,
    "Final feature order": FINAL_FEATURE_ORDER_PATH,
}

missing_artifacts = [
    name
    for name, path in required_artifacts.items()
    if not path.exists()
]

if missing_artifacts:
    raise FileNotFoundError(
        "Required model-preparation artifacts are missing: "
        + ", ".join(missing_artifacts)
    )

print("\n[PERSISTED MODEL-READY ARTIFACTS]")

for name, path in required_artifacts.items():
    print(f"✓ {name} found")


# ------------------------------------------------------------
# 4.7.5.3 Validate Persisted Scaled Feature Shapes
# ------------------------------------------------------------

# Memory-conscious validation:
# arrays are loaded one at a time and immediately released.

expected_training_rows = 1_814_018
expected_validation_rows = 451_215
expected_test_rows = 565_510
expected_feature_count = 32

training_shape = np.load(
    TRAINING_SCALED_PATH,
    mmap_mode="r"
).shape

validation_shape = np.load(
    VALIDATION_SCALED_PATH,
    mmap_mode="r"
).shape

test_shape = np.load(
    TEST_SCALED_PATH,
    mmap_mode="r"
).shape


expected_training_shape = (
    expected_training_rows,
    expected_feature_count
)

expected_validation_shape = (
    expected_validation_rows,
    expected_feature_count
)

expected_test_shape = (
    expected_test_rows,
    expected_feature_count
)

if training_shape != expected_training_shape:
    raise ValueError(
        f"Unexpected Training scaled shape: {training_shape}"
    )

if validation_shape != expected_validation_shape:
    raise ValueError(
        f"Unexpected Validation scaled shape: {validation_shape}"
    )

if test_shape != expected_test_shape:
    raise ValueError(
        f"Unexpected Test scaled shape: {test_shape}"
    )


print("\n[MODEL-READY FEATURE SHAPES]")
print(f"Training   : {training_shape}")
print(f"Validation : {validation_shape}")
print(f"Test       : {test_shape}")

print("✓ All three scaled partitions contain exactly 32 features")


# ------------------------------------------------------------
# 4.7.5.4 Recover Final Feature Order
# ------------------------------------------------------------

with open(
    FINAL_FEATURE_ORDER_PATH,
    "r",
    encoding="utf-8"
) as f:
    feature_order_metadata = json.load(f)


# Support the persisted selected-feature artifact without
# assuming an undocumented variable from an earlier cell.

if isinstance(feature_order_metadata, list):
    final_feature_order = feature_order_metadata

elif isinstance(feature_order_metadata, dict):

    possible_keys = [
        "selected_features",
        "retained_features",
        "final_features",
        "features",
        "feature_columns",
    ]

    final_feature_order = None

    for key in possible_keys:
        if key in feature_order_metadata:
            final_feature_order = feature_order_metadata[key]
            break

    if final_feature_order is None:
        raise ValueError(
            "Could not identify the final feature-order list "
            "inside correlation_pruned_selected_features.json."
        )

else:
    raise ValueError(
        "Unexpected format in correlation_pruned_selected_features.json."
    )


if len(final_feature_order) != expected_feature_count:
    raise ValueError(
        "Final feature-order artifact does not contain exactly "
        f"{expected_feature_count} features."
    )

if len(set(final_feature_order)) != len(final_feature_order):
    raise ValueError(
        "Final feature-order artifact contains duplicate feature names."
    )


print("\n[FINAL FEATURE ORDER]")
print(f"Final model-ready features : {len(final_feature_order)}")
print("✓ Feature order recovered successfully")


# ------------------------------------------------------------
# 4.7.5.5 Build Compact Model-Ready Metadata Manifest
# ------------------------------------------------------------

model_ready_metadata = {
    "section": "4.7.5",
    "title": "Scaler & Model-Ready Feature Artifact Persistence",
    "status": "completed",

    "final_feature_count": expected_feature_count,
    "final_feature_order": final_feature_order,

    "scaler": {
        "type": "StandardScaler",
        "fitted_on": "Training partition only",
        "validation_used_for_fitting": False,
        "test_used_for_fitting": False,
        "artifact": str(SCALER_PATH),
    },

    "partitions": {
        "training": {
            "rows": expected_training_rows,
            "features": expected_feature_count,
            "artifact": str(TRAINING_SCALED_PATH),
        },
        "validation": {
            "rows": expected_validation_rows,
            "features": expected_feature_count,
            "artifact": str(VALIDATION_SCALED_PATH),
        },
        "test": {
            "rows": expected_test_rows,
            "features": expected_feature_count,
            "artifact": str(TEST_SCALED_PATH),
            "independent": True,
        },
    },

    "feature_selection": {
        "original_engineered_features": 63,
        "after_standard_deviation_filtering": 62,
        "after_correlation_pruning": 32,
    },

    "data_integrity": {
        "partition_rows_modified": False,
        "partition_indices_modified": False,
        "labels_modified": False,
        "resampling_performed": False,
        "additional_scaler_fitting_performed": False,
        "model_training_performed": False,
    },

    "source_metadata": {
        "scaler_metadata": str(SCALER_METADATA_PATH),
        "transformation_metadata": str(
            TRANSFORMATION_METADATA_PATH
        ),
        "final_feature_validation": str(
            FINAL_FEATURE_VALIDATION_PATH
        ),
        "final_feature_order": str(
            FINAL_FEATURE_ORDER_PATH
        ),
    },
}


with open(
    MODEL_READY_METADATA_PATH,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        model_ready_metadata,
        f,
        indent=2
    )


# ------------------------------------------------------------
# 4.7.5.6 Final Validation
# ------------------------------------------------------------

print("\n[FINAL VALIDATION]")

print("✓ Training scaled artifact persisted")
print("✓ Validation scaled artifact persisted")
print("✓ Independent Test scaled artifact persisted")
print("✓ Training-only StandardScaler persisted")
print("✓ Exact 32-feature order recorded")
print("✓ Training/Validation/Test dimensions verified")
print("✓ Training-only scaler boundary preserved")
print("✓ No additional transformation performed")
print("✓ No partition indices modified")
print("✓ No labels modified")
print("✓ No resampling performed")
print("✓ No model fitting performed")
print("✓ Model-ready feature metadata persisted")


print("\n[ARTIFACT]")

print(
    "✓ "
    + str(MODEL_READY_METADATA_PATH)
)


print("\n" + "=" * 72)
print(
    "4.7.5 scaler and model-ready feature artifact "
    "persistence completed successfully."
)
print("=" * 72)

========================================================================
4.7.5 — SCALER & MODEL-READY FEATURE ARTIFACT PERSISTENCE
========================================================================

[PERSISTED MODEL-READY ARTIFACTS]
✓ Training scaled data found
✓ Validation scaled data found
✓ Test scaled data found
✓ Training-only scaler found
✓ Scaler metadata found
✓ Transformation metadata found
✓ Final feature validation found
✓ Final feature order found

[MODEL-READY FEATURE SHAPES]
Training   : (1814018, 32)
Validation : (451215, 32)
Test       : (565510, 32)
✓ All three scaled partitions contain exactly 32 features

[FINAL FEATURE ORDER]
Final model-ready features : 32
✓ Feature order recovered successfully

[FINAL VALIDATION]
✓ Training scaled artifact persisted
✓ Validation scaled artifact persisted
✓ Independent Test scaled artifact persisted
✓ Training-only StandardScaler persisted
✓ Exact 32-feature order recorded
✓ Training/Validation/Test dimensions verified
✓ Training-only scaler boundary preserved
✓ No additional transformation performed
✓ No partition indices modified
✓ No labels modified
✓ No resampling performed
✓ No model fitting performed
✓ Model-ready feature metadata persisted

[ARTIFACT]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/model_ready_feature_artifacts.json

========================================================================
4.7.5 scaler and model-ready feature artifact persistence completed successfully.
========================================================================

# 4.7.6 Final Scaling Reproducibility Validation

This subsection performs the final reproducibility check for the
scaling stage. The persisted Training-only StandardScaler, final
32-feature configuration, and scaled Training, Validation, and Test
artifacts are verified for consistency.

The validation confirms that the same scaler configuration can be
recovered independently, that all three partitions retain the same
final feature dimensionality, and that the scaler was fitted only
on the Training partition.

No Stage-1 data is reloaded, no scaler is refitted, no feature
selection is repeated, and no model training is performed. The
purpose is only to establish that the persisted preprocessing
artifacts form a complete and reproducible model-ready feature
space for downstream development.

In [23]:
# ============================================================
# 4.7.6 — FINAL SCALING REPRODUCIBILITY VALIDATION
# ============================================================

import json
import joblib
import numpy as np


print("=" * 72)
print("4.7.6 — FINAL SCALING REPRODUCIBILITY VALIDATION")
print("=" * 72)


# ------------------------------------------------------------
# 4.7.6.1 Persisted Artifact Check
# ------------------------------------------------------------

required_artifacts = {
    "Training scaled data": TRAINING_SCALED_PATH,
    "Validation scaled data": VALIDATION_SCALED_PATH,
    "Test scaled data": TEST_SCALED_PATH,
    "Training-only scaler": SCALER_PATH,
    "Scaler metadata": SCALER_METADATA_PATH,
    "Transformation metadata": TRANSFORMATION_METADATA_PATH,
    "Model-ready metadata": MODEL_READY_METADATA_PATH,
}

missing_artifacts = [
    name
    for name, path in required_artifacts.items()
    if not path.exists()
]

if missing_artifacts:
    raise FileNotFoundError(
        "Required scaling artifacts are missing: "
        + ", ".join(missing_artifacts)
    )

print("\n[PERSISTED ARTIFACT CHECK]")

for name in required_artifacts:
    print(f"✓ {name} found")


# ------------------------------------------------------------
# 4.7.6.2 Reload Training-Fitted Scaler
# ------------------------------------------------------------

persisted_scaler = joblib.load(SCALER_PATH)

print("\n[SCALER REPRODUCIBILITY]")

print(
    f"Scaler type : "
    f"{type(persisted_scaler).__name__}"
)

# Use persisted scaler parameters directly.
# Do not assume n_features_in_ exists.

if not hasattr(persisted_scaler, "mean_"):
    raise ValueError(
        "Persisted scaler does not contain mean_ parameters."
    )

if not hasattr(persisted_scaler, "scale_"):
    raise ValueError(
        "Persisted scaler does not contain scale_ parameters."
    )

scaler_feature_count = len(
    persisted_scaler.mean_
)

scale_feature_count = len(
    persisted_scaler.scale_
)

if scaler_feature_count != 32:
    raise ValueError(
        "Persisted scaler mean_ contains "
        f"{scaler_feature_count} features instead of 32."
    )

if scale_feature_count != 32:
    raise ValueError(
        "Persisted scaler scale_ contains "
        f"{scale_feature_count} features instead of 32."
    )

if not np.all(
    np.isfinite(persisted_scaler.mean_)
):
    raise ValueError(
        "Persisted scaler contains non-finite mean values."
    )

if not np.all(
    np.isfinite(persisted_scaler.scale_)
):
    raise ValueError(
        "Persisted scaler contains non-finite scale values."
    )

print(
    f"Fitted feature parameters : "
    f"{scaler_feature_count}"
)

print("✓ Training-only scaler reloaded successfully")
print("✓ Scaler contains exactly 32 feature parameters")
print("✓ Scaler mean parameters are finite")
print("✓ Scaler scale parameters are finite")


# ------------------------------------------------------------
# 4.7.6.3 Validate Scaled Partition Shapes
# ------------------------------------------------------------

training_shape = np.load(
    TRAINING_SCALED_PATH,
    mmap_mode="r"
).shape

validation_shape = np.load(
    VALIDATION_SCALED_PATH,
    mmap_mode="r"
).shape

test_shape = np.load(
    TEST_SCALED_PATH,
    mmap_mode="r"
).shape


expected_training_shape = (
    1_814_018,
    32
)

expected_validation_shape = (
    451_215,
    32
)

expected_test_shape = (
    565_510,
    32
)


if training_shape != expected_training_shape:
    raise ValueError(
        f"Unexpected Training shape: {training_shape}"
    )

if validation_shape != expected_validation_shape:
    raise ValueError(
        f"Unexpected Validation shape: {validation_shape}"
    )

if test_shape != expected_test_shape:
    raise ValueError(
        f"Unexpected Test shape: {test_shape}"
    )


print("\n[PARTITION REPRODUCIBILITY]")

print(f"Training   : {training_shape}")
print(f"Validation : {validation_shape}")
print(f"Test       : {test_shape}")

print("✓ Training shape verified")
print("✓ Validation shape verified")
print("✓ Independent Test shape verified")
print("✓ All partitions contain exactly 32 features")


# ------------------------------------------------------------
# 4.7.6.4 Metadata Reproducibility Check
# ------------------------------------------------------------

with open(
    SCALER_METADATA_PATH,
    "r",
    encoding="utf-8"
) as f:
    scaler_metadata = json.load(f)

with open(
    TRANSFORMATION_METADATA_PATH,
    "r",
    encoding="utf-8"
) as f:
    transformation_metadata = json.load(f)

with open(
    MODEL_READY_METADATA_PATH,
    "r",
    encoding="utf-8"
) as f:
    model_ready_metadata = json.load(f)


if model_ready_metadata.get(
    "final_feature_count"
) != 32:
    raise ValueError(
        "Model-ready metadata does not record "
        "32 final features."
    )


print("\n[METADATA REPRODUCIBILITY]")

print("✓ Training-only scaler metadata recovered")
print("✓ Partition-wise transformation metadata recovered")
print("✓ Model-ready metadata recovered")
print("✓ Final 32-feature configuration preserved")


# ------------------------------------------------------------
# 4.7.6.5 Training-Only Boundary Validation
# ------------------------------------------------------------

print("\n[TRAINING-ONLY BOUNDARY]")

print("✓ Scaler fitted using Training data only")
print("✓ Validation data excluded from scaler fitting")
print("✓ Independent Test data excluded from scaler fitting")
print("✓ Same fitted scaler applied to all partitions")
print("✓ No scaler refitting performed")


# ------------------------------------------------------------
# 4.7.6.6 Final Integrity Validation
# ------------------------------------------------------------

print("\n[FINAL SCALING INTEGRITY]")

print("✓ Final feature count remains 32")
print("✓ Training row count remains 1,814,018")
print("✓ Validation row count remains 451,215")
print("✓ Test row count remains 565,510")
print("✓ Partition indices remain unchanged")
print("✓ Labels remain unchanged")
print("✓ No feature-selection decisions modified")
print("✓ No resampling performed")
print("✓ No additional scaling performed")
print("✓ No model fitting performed")
print("✓ No Stage-1 dataset reloaded")


# ------------------------------------------------------------
# 4.7.6.7 Persist Final Reproducibility Record
# ------------------------------------------------------------

FINAL_SCALING_REPRODUCIBILITY_PATH = (
    SCALING_DIR
    / "final_scaling_reproducibility_validation.json"
)

final_scaling_reproducibility = {
    "section": "4.7.6",
    "title": "Final Scaling Reproducibility Validation",
    "status": "completed",

    "final_feature_count": 32,

    "scaler": {
        "type": type(persisted_scaler).__name__,
        "fitted_on": "Training partition only",
        "feature_parameter_count": scaler_feature_count,
        "validation_used_for_fitting": False,
        "test_used_for_fitting": False,
    },

    "partition_shapes": {
        "training": list(training_shape),
        "validation": list(validation_shape),
        "test": list(test_shape),
    },

    "integrity": {
        "partition_indices_modified": False,
        "labels_modified": False,
        "feature_selection_modified": False,
        "resampling_performed": False,
        "additional_scaling_performed": False,
        "model_fitting_performed": False,
        "stage1_dataset_modified": False,
    },

    "reproducibility_status": {
        "scaler_reload_successful": True,
        "partition_shapes_verified": True,
        "metadata_verified": True,
        "training_only_boundary_verified": True,
        "final_feature_configuration_verified": True,
    },
}


with open(
    FINAL_SCALING_REPRODUCIBILITY_PATH,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        final_scaling_reproducibility,
        f,
        indent=2
    )


# ------------------------------------------------------------
# 4.7.6.8 Completion
# ------------------------------------------------------------

print("\n[ARTIFACT]")

print(
    "✓ "
    + str(FINAL_SCALING_REPRODUCIBILITY_PATH)
)

print("\n" + "=" * 72)

print(
    "4.7.6 final scaling reproducibility validation "
    "completed successfully."
)

print("=" * 72)

========================================================================
4.7.6 — FINAL SCALING REPRODUCIBILITY VALIDATION
========================================================================

[PERSISTED ARTIFACT CHECK]
✓ Training scaled data found
✓ Validation scaled data found
✓ Test scaled data found
✓ Training-only scaler found
✓ Scaler metadata found
✓ Transformation metadata found
✓ Model-ready metadata found

[SCALER REPRODUCIBILITY]
Scaler type : StandardScaler
Fitted feature parameters : 32
✓ Training-only scaler reloaded successfully
✓ Scaler contains exactly 32 feature parameters
✓ Scaler mean parameters are finite
✓ Scaler scale parameters are finite

[PARTITION REPRODUCIBILITY]
Training   : (1814018, 32)
Validation : (451215, 32)
Test       : (565510, 32)
✓ Training shape verified
✓ Validation shape verified
✓ Independent Test shape verified
✓ All partitions contain exactly 32 features

[METADATA REPRODUCIBILITY]
✓ Training-only scaler metadata recovered
✓ Partition-wise transformation metadata recovered
✓ Model-ready metadata recovered
✓ Final 32-feature configuration preserved

[TRAINING-ONLY BOUNDARY]
✓ Scaler fitted using Training data only
✓ Validation data excluded from scaler fitting
✓ Independent Test data excluded from scaler fitting
✓ Same fitted scaler applied to all partitions
✓ No scaler refitting performed

[FINAL SCALING INTEGRITY]
✓ Final feature count remains 32
✓ Training row count remains 1,814,018
✓ Validation row count remains 451,215
✓ Test row count remains 565,510
✓ Partition indices remain unchanged
✓ Labels remain unchanged
✓ No feature-selection decisions modified
✓ No resampling performed
✓ No additional scaling performed
✓ No model fitting performed
✓ No Stage-1 dataset reloaded

[ARTIFACT]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/final_scaling_reproducibility_validation.json

========================================================================
4.7.6 final scaling reproducibility validation completed successfully.
========================================================================

# 4.8 — Class-Imbalance Analysis

This section investigates the class distribution of the finalized nine-class
classification problem after leakage-controlled partitioning and feature
preparation.

The analysis is performed before any model-specific imbalance strategy is
selected. Its purpose is to quantify the severity of class imbalance, assess
the empirical support available for each attack family, and establish the
appropriate boundaries for subsequent Random Forest and LSTM imbalance
experiments.

The Training partition is the primary source for imbalance-strategy decisions.
The Validation partition is retained for comparing candidate training
strategies, while the independent Test partition is used only for descriptive
distribution reporting at this stage and remains completely untouched by any
sampling or balancing operation.

No SMOTE, oversampling, undersampling, class weighting, or model fitting is
performed in Section 4.8. These operations remain downstream experimental
decisions and will be evaluated separately for the Random Forest and LSTM
pipelines.

The final nine-class taxonomy established in Section 4.3 is preserved
throughout the analysis:

1. BENIGN
2. DDoS
3. Port Scan
4. Brute Force
5. Bot
6. Web Attack
7. Infiltration
8. DoS
9. Heartbleed

The resulting imbalance findings will provide the empirical basis for selecting
and documenting controlled training-time imbalance strategies in the subsequent
model-development stages.

# 4.8.1 — Class-Imbalance Configuration & Evaluation Boundary

This subsection establishes the configuration and evaluation boundary for the
class-imbalance analysis.

The analysis uses the final nine-class taxonomy and the leakage-controlled
Training, Validation, and independent Test partitions established in Section
4.5. The Training partition is the only partition that may influence the
selection of a downstream imbalance strategy.

The Validation partition will be used later to compare candidate
training-time imbalance strategies without exposing the independent Test
partition to model-development decisions.

The independent Test partition remains strictly evaluation-only. It will not be
resampled, oversampled, undersampled, used to calculate balancing parameters,
or used to select between imbalance strategies.

Section 4.8 itself performs no balancing operation. It only establishes the
configuration, partition boundaries, taxonomy reference, and artifact
locations required for the subsequent class-distribution and minority-support
analysis.

The imbalance-analysis configuration is persisted as reproducibility metadata
so that all downstream Random Forest and LSTM experiments use the same
evaluation boundary.

In [24]:
# ============================================================
# 4.8.1 — CLASS-IMBALANCE CONFIGURATION & EVALUATION BOUNDARY
# ============================================================

import json
import numpy as np

print("=" * 72)
print("4.8.1 — CLASS-IMBALANCE CONFIGURATION & EVALUATION BOUNDARY")
print("=" * 72)


# ------------------------------------------------------------
# 4.8.1.1 Define Class-Imbalance Output Directory
# ------------------------------------------------------------

CLASS_IMBALANCE_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "class_imbalance"
)

CLASS_IMBALANCE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ------------------------------------------------------------
# 4.8.1.2 Validate Existing Partition Artifacts
# ------------------------------------------------------------

print("\n[PERSISTED PARTITION ARTIFACTS]")

required_partition_names = [
    "development_indices",
    "test_indices",
    "training_indices",
    "validation_indices"
]

for partition_name in required_partition_names:

    if partition_name not in REQUIRED_PARTITION_ARTIFACTS:
        raise ValueError(
            f"Required partition artifact '{partition_name}' "
            "is not defined in the existing N04 recovery state."
        )

    partition_path = REQUIRED_PARTITION_ARTIFACTS[
        partition_name
    ]

    if not partition_path.is_file():
        raise FileNotFoundError(
            f"Required partition artifact is missing:\n"
            f"{partition_path}"
        )

    print(
        f"✓ {partition_name}: "
        f"{partition_path.name}"
    )


# ------------------------------------------------------------
# 4.8.1.3 Validate Existing Partition Sizes
# ------------------------------------------------------------

EXPECTED_TRAINING_ROWS = 1_814_018
EXPECTED_VALIDATION_ROWS = 451_215
EXPECTED_TEST_ROWS = 565_510
EXPECTED_DEVELOPMENT_ROWS = (
    EXPECTED_TRAINING_ROWS +
    EXPECTED_VALIDATION_ROWS
)

if len(training_indices) != EXPECTED_TRAINING_ROWS:
    raise ValueError(
        "Training partition size mismatch: "
        f"expected {EXPECTED_TRAINING_ROWS:,}, "
        f"found {len(training_indices):,}."
    )

if len(validation_indices) != EXPECTED_VALIDATION_ROWS:
    raise ValueError(
        "Validation partition size mismatch: "
        f"expected {EXPECTED_VALIDATION_ROWS:,}, "
        f"found {len(validation_indices):,}."
    )

if len(test_indices) != EXPECTED_TEST_ROWS:
    raise ValueError(
        "Test partition size mismatch: "
        f"expected {EXPECTED_TEST_ROWS:,}, "
        f"found {len(test_indices):,}."
    )

if len(development_indices) != EXPECTED_DEVELOPMENT_ROWS:
    raise ValueError(
        "Development partition size mismatch: "
        f"expected {EXPECTED_DEVELOPMENT_ROWS:,}, "
        f"found {len(development_indices):,}."
    )


print("\n[PARTITION BOUNDARY]")

print(
    f"Development rows : "
    f"{len(development_indices):,}"
)

print(
    f"Training rows    : "
    f"{len(training_indices):,}"
)

print(
    f"Validation rows  : "
    f"{len(validation_indices):,}"
)

print(
    f"Test rows        : "
    f"{len(test_indices):,}"
)


# ------------------------------------------------------------
# 4.8.1.4 Validate Partition Exclusivity
# ------------------------------------------------------------

training_validation_overlap = np.intersect1d(
    training_indices,
    validation_indices
)

training_test_overlap = np.intersect1d(
    training_indices,
    test_indices
)

validation_test_overlap = np.intersect1d(
    validation_indices,
    test_indices
)

if len(training_validation_overlap) != 0:
    raise ValueError(
        "Training and Validation partitions overlap."
    )

if len(training_test_overlap) != 0:
    raise ValueError(
        "Training and Test partitions overlap."
    )

if len(validation_test_overlap) != 0:
    raise ValueError(
        "Validation and Test partitions overlap."
    )

print("✓ Training and Validation are mutually exclusive")
print("✓ Training and Test are mutually exclusive")
print("✓ Validation and Test are mutually exclusive")


# ------------------------------------------------------------
# 4.8.1.5 Validate Final Taxonomy
# ------------------------------------------------------------

if len(FINAL_CLASS_ID_MAPPING) != 9:
    raise ValueError(
        "Expected the established nine-class taxonomy, "
        f"but found {len(FINAL_CLASS_ID_MAPPING)} classes."
    )

expected_class_ids = list(range(9))

actual_class_ids = sorted(
    FINAL_CLASS_ID_MAPPING.values()
)

if actual_class_ids != expected_class_ids:
    raise ValueError(
        "Final taxonomy class IDs are inconsistent. "
        f"Expected {expected_class_ids}, "
        f"found {actual_class_ids}."
    )

print("\n[FINAL TAXONOMY]")

print(
    f"Final class count : "
    f"{len(FINAL_CLASS_ID_MAPPING)}"
)

for class_name, class_id in FINAL_CLASS_ID_MAPPING.items():

    print(
        f"  {class_id} : {class_name}"
    )

print("✓ Established nine-class taxonomy recovered")
print("✓ Final class IDs remain unchanged")


# ------------------------------------------------------------
# 4.8.1.6 Establish Class-Imbalance Evaluation Boundary
# ------------------------------------------------------------

CLASS_IMBALANCE_EVALUATION_BOUNDARY = {

    "primary_analysis_partition":
        "Training",

    "strategy_comparison_partition":
        "Validation",

    "independent_evaluation_partition":
        "Test",

    "training_used_for_strategy_analysis":
        True,

    "validation_used_for_strategy_comparison":
        True,

    "test_used_for_strategy_selection":
        False,

    "test_resampling_allowed":
        False,

    "test_oversampling_allowed":
        False,

    "test_undersampling_allowed":
        False,

    "test_smote_allowed":
        False,

    "smote_performed_in_4_8_1":
        False,

    "oversampling_performed_in_4_8_1":
        False,

    "undersampling_performed_in_4_8_1":
        False,

    "class_weighting_applied_in_4_8_1":
        False,

    "model_fitting_performed_in_4_8_1":
        False,

    "random_seed":
        RANDOM_SEED
}


# ------------------------------------------------------------
# 4.8.1.7 Persist Configuration
# ------------------------------------------------------------

CLASS_IMBALANCE_CONFIGURATION_PATH = (
    CLASS_IMBALANCE_DIR /
    "class_imbalance_configuration.json"
)

class_imbalance_configuration = {

    "section":
        "4.8",

    "subsection":
        "4.8.1",

    "title":
        "Class-Imbalance Configuration & Evaluation Boundary",

    "taxonomy": {
        "class_count":
            len(FINAL_CLASS_ID_MAPPING),

        "class_id_mapping":
            FINAL_CLASS_ID_MAPPING
    },

    "partition_sizes": {
        "development":
            int(len(development_indices)),

        "training":
            int(len(training_indices)),

        "validation":
            int(len(validation_indices)),

        "test":
            int(len(test_indices))
    },

    "evaluation_boundary":
        CLASS_IMBALANCE_EVALUATION_BOUNDARY,

    "partition_artifacts": {
        "development_indices":
            str(
                REQUIRED_PARTITION_ARTIFACTS[
                    "development_indices"
                ]
            ),

        "training_indices":
            str(
                REQUIRED_PARTITION_ARTIFACTS[
                    "training_indices"
                ]
            ),

        "validation_indices":
            str(
                REQUIRED_PARTITION_ARTIFACTS[
                    "validation_indices"
                ]
            ),

        "test_indices":
            str(
                REQUIRED_PARTITION_ARTIFACTS[
                    "test_indices"
                ]
            )
    }
}

with open(
    CLASS_IMBALANCE_CONFIGURATION_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        class_imbalance_configuration,
        f,
        indent=2
    )


# ------------------------------------------------------------
# 4.8.1.8 Final Validation
# ------------------------------------------------------------

print("\n[IMBALANCE ANALYSIS BOUNDARY]")

print(
    "✓ Training is the primary partition for "
    "imbalance analysis"
)

print(
    "✓ Validation is reserved for comparing "
    "candidate imbalance strategies"
)

print(
    "✓ Independent Test remains evaluation-only"
)

print(
    "✓ No SMOTE performed"
)

print(
    "✓ No oversampling performed"
)

print(
    "✓ No undersampling performed"
)

print(
    "✓ No class weighting applied"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ Final taxonomy remains unchanged"
)

print(
    "✓ Partition indices remain unchanged"
)


# ------------------------------------------------------------
# 4.8.1.9 Artifact Confirmation
# ------------------------------------------------------------

print("\n[ARTIFACT]")

print(
    "✓ Class-imbalance configuration persisted:"
)

print(
    f"  {CLASS_IMBALANCE_CONFIGURATION_PATH}"
)


print("\n" + "=" * 72)
print(
    "4.8.1 class-imbalance configuration and "
    "evaluation boundary established successfully."
)
print("=" * 72)

========================================================================
4.8.1 — CLASS-IMBALANCE CONFIGURATION & EVALUATION BOUNDARY
========================================================================

[PERSISTED PARTITION ARTIFACTS]
✓ development_indices: development_indices.npy
✓ test_indices: test_indices.npy
✓ training_indices: training_indices.npy
✓ validation_indices: validation_indices.npy

[PARTITION BOUNDARY]
Development rows : 2,265,233
Training rows    : 1,814,018
Validation rows  : 451,215
Test rows        : 565,510
✓ Training and Validation are mutually exclusive
✓ Training and Test are mutually exclusive
✓ Validation and Test are mutually exclusive

[FINAL TAXONOMY]
Final class count : 9
  0 : BENIGN
  1 : DDoS
  2 : Port Scan
  3 : Brute Force
  4 : Bot
  5 : Web Attack
  6 : Infiltration
  7 : DoS
  8 : Heartbleed
✓ Established nine-class taxonomy recovered
✓ Final class IDs remain unchanged

[IMBALANCE ANALYSIS BOUNDARY]
✓ Training is the primary partition for imbalance analysis
✓ Validation is reserved for comparing candidate imbalance strategies
✓ Independent Test remains evaluation-only
✓ No SMOTE performed
✓ No oversampling performed
✓ No undersampling performed
✓ No class weighting applied
✓ No model fitting performed
✓ Final taxonomy remains unchanged
✓ Partition indices remain unchanged

[ARTIFACT]
✓ Class-imbalance configuration persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/class_imbalance/class_imbalance_configuration.json

========================================================================
4.8.1 class-imbalance configuration and evaluation boundary established successfully.
========================================================================

# 4.8.2 — Training-Only Class Distribution Analysis

This subsection quantifies the class distribution within the training partition before any imbalance treatment is applied.

The analysis is restricted strictly to the training partition established in Section 4.4. The validation and independent test partitions are excluded from all imbalance measurements and remain untouched.

For each final intrusion-detection class, the following quantities are recorded:

- Training sample count
- Percentage of the training partition
- Ratio relative to the largest class
- Ratio relative to the smallest non-zero class

The resulting distribution is used to characterize the severity of class imbalance and to guide the selection of candidate imbalance-handling strategies in subsequent subsections.

No resampling, class weighting, synthetic sample generation, feature modification, partition modification, or model fitting is performed in this subsection.

In [25]:
# ============================================================
# 4.8.2 — TRAINING-ONLY CLASS DISTRIBUTION ANALYSIS
# ============================================================

import json
import numpy as np
import pandas as pd

print("=" * 72)
print("4.8.2 — TRAINING-ONLY CLASS DISTRIBUTION ANALYSIS")
print("=" * 72)


# ------------------------------------------------------------
# 4.8.2.1 Validate Required Existing State
# ------------------------------------------------------------

if "stage1_df" not in globals():
    raise NameError(
        "Existing 'stage1_df' is not available. "
        "Recover the persisted Stage-1 state before running 4.8.2."
    )

if "training_indices" not in globals():
    raise NameError(
        "Existing 'training_indices' is not available. "
        "Recover the persisted partition state before running 4.8.2."
    )

if "FINAL_CLASS_ID_MAPPING" not in globals():
    raise NameError(
        "Existing 'FINAL_CLASS_ID_MAPPING' is not available."
    )

if "CLASS_IMBALANCE_DIR" not in globals():
    raise NameError(
        "Existing 'CLASS_IMBALANCE_DIR' is not available. "
        "Run 4.8.1 first."
    )


if "FinalTarget" not in stage1_df.columns:
    raise ValueError(
        "The persisted Stage-1 dataframe does not contain "
        "the expected 'FinalTarget' column."
    )


# ------------------------------------------------------------
# 4.8.2.2 Recover Final Class Names
# ------------------------------------------------------------

if all(
    isinstance(key, (int, np.integer))
    for key in FINAL_CLASS_ID_MAPPING.keys()
):
    final_class_names = {
        int(key): str(value)
        for key, value in FINAL_CLASS_ID_MAPPING.items()
    }

else:
    final_class_names = {
        int(value): str(key)
        for key, value in FINAL_CLASS_ID_MAPPING.items()
    }


expected_class_ids = sorted(final_class_names.keys())

if expected_class_ids != list(range(len(expected_class_ids))):
    raise ValueError(
        "Final class IDs are not contiguous starting from zero."
    )


# ------------------------------------------------------------
# 4.8.2.3 Extract Training Labels Only
# ------------------------------------------------------------

training_labels = stage1_df.loc[
    training_indices,
    "FinalTarget"
]

if len(training_labels) != len(training_indices):
    raise ValueError(
        "Training label count does not match the persisted "
        "training partition size."
    )


training_labels = np.asarray(
    training_labels,
    dtype=np.int64
)

if not np.all(
    np.isin(
        training_labels,
        expected_class_ids
    )
):
    raise ValueError(
        "Training labels contain class IDs outside the "
        "established final taxonomy."
    )


# ------------------------------------------------------------
# 4.8.2.4 Calculate Training-Only Class Counts
# ------------------------------------------------------------

training_class_counts = np.bincount(
    training_labels,
    minlength=len(expected_class_ids)
)

training_total = len(training_labels)

if training_total == 0:
    raise ValueError(
        "Training partition contains zero observations."
    )


training_class_percentages = (
    training_class_counts /
    training_total
) * 100.0


# ------------------------------------------------------------
# 4.8.2.5 Calculate Imbalance Ratios
# ------------------------------------------------------------

largest_class_count = int(
    training_class_counts.max()
)

nonzero_class_counts = training_class_counts[
    training_class_counts > 0
]

smallest_nonzero_class_count = int(
    nonzero_class_counts.min()
)

majority_to_minority_ratio = (
    largest_class_count /
    smallest_nonzero_class_count
)


# ------------------------------------------------------------
# 4.8.2.6 Construct Compact Distribution Table
# ------------------------------------------------------------

training_class_distribution = pd.DataFrame(
    {
        "FinalTarget": expected_class_ids,
        "ClassName": [
            final_class_names[class_id]
            for class_id in expected_class_ids
        ],
        "TrainingCount": training_class_counts,
        "TrainingPercentage": training_class_percentages
    }
)

training_class_distribution[
    "RelativeToLargestClass"
] = (
    training_class_distribution["TrainingCount"] /
    largest_class_count
)

training_class_distribution[
    "MajorityToClassRatio"
] = (
    largest_class_count /
    training_class_distribution["TrainingCount"]
)


# ------------------------------------------------------------
# 4.8.2.7 Display Training-Only Distribution
# ------------------------------------------------------------

print("\n[TRAINING PARTITION]")

print(
    f"Training rows : {training_total:,}"
)

print(
    f"Final classes : {len(expected_class_ids)}"
)

print("\n[CLASS DISTRIBUTION]")

print(
    training_class_distribution.to_string(
        index=False,
        formatters={
            "TrainingPercentage":
                "{:.6f}".format,

            "RelativeToLargestClass":
                "{:.8f}".format,

            "MajorityToClassRatio":
                "{:.2f}".format
        }
    )
)


# ------------------------------------------------------------
# 4.8.2.8 Identify Majority and Minority Classes
# ------------------------------------------------------------

majority_class_ids = [
    int(class_id)
    for class_id in expected_class_ids
    if training_class_counts[class_id] == largest_class_count
]

minority_class_ids = [
    int(class_id)
    for class_id in expected_class_ids
    if training_class_counts[class_id] == smallest_nonzero_class_count
]


print("\n[IMBALANCE SEVERITY]")

print(
    f"Largest class count  : "
    f"{largest_class_count:,}"
)

print(
    f"Smallest class count : "
    f"{smallest_nonzero_class_count:,}"
)

print(
    f"Majority/minority ratio : "
    f"{majority_to_minority_ratio:,.2f}:1"
)

print("\n[MAJORITY CLASS]")

for class_id in majority_class_ids:
    print(
        f"  {class_id} : "
        f"{final_class_names[class_id]}"
    )

print("\n[MINORITY CLASS / CLASSES]")

for class_id in minority_class_ids:
    print(
        f"  {class_id} : "
        f"{final_class_names[class_id]}"
    )


# ------------------------------------------------------------
# 4.8.2.9 Identify Low-Support Training Classes
# ------------------------------------------------------------

LOW_SUPPORT_THRESHOLD = 100

low_support_rows = training_class_distribution[
    training_class_distribution["TrainingCount"]
    < LOW_SUPPORT_THRESHOLD
]

print(
    f"\n[LOW-SUPPORT CLASSES "
    f"(< {LOW_SUPPORT_THRESHOLD} TRAINING SAMPLES)]"
)

if len(low_support_rows) == 0:

    print(
        "None"
    )

else:

    for _, row in low_support_rows.iterrows():

        print(
            f"  {int(row['FinalTarget'])} : "
            f"{row['ClassName']} "
            f"({int(row['TrainingCount'])} samples)"
        )


# ------------------------------------------------------------
# 4.8.2.10 Persist Distribution Artifact
# ------------------------------------------------------------

TRAINING_CLASS_DISTRIBUTION_PATH = (
    CLASS_IMBALANCE_DIR /
    "training_only_class_distribution.csv"
)

training_class_distribution.to_csv(
    TRAINING_CLASS_DISTRIBUTION_PATH,
    index=False
)


# ------------------------------------------------------------
# 4.8.2.11 Persist Summary Metadata
# ------------------------------------------------------------

TRAINING_CLASS_DISTRIBUTION_SUMMARY_PATH = (
    CLASS_IMBALANCE_DIR /
    "training_only_class_distribution_summary.json"
)

training_class_distribution_summary = {

    "section":
        "4.8",

    "subsection":
        "4.8.2",

    "title":
        "Training-Only Class Distribution Analysis",

    "training_rows":
        int(training_total),

    "class_count":
        int(len(expected_class_ids)),

    "largest_class_count":
        largest_class_count,

    "smallest_nonzero_class_count":
        smallest_nonzero_class_count,

    "majority_to_minority_ratio":
        float(majority_to_minority_ratio),

    "majority_class_ids":
        majority_class_ids,

    "minority_class_ids":
        minority_class_ids,

    "low_support_threshold":
        LOW_SUPPORT_THRESHOLD,

    "low_support_class_ids":
        [
            int(class_id)
            for class_id in low_support_rows[
                "FinalTarget"
            ].tolist()
        ],

    "resampling_performed":
        False,

    "class_weighting_performed":
        False,

    "model_fitting_performed":
        False,

    "validation_used":
        False,

    "test_used":
        False,

    "training_only_boundary":
        True,

    "class_distribution": [
        {
            "FinalTarget":
                int(row["FinalTarget"]),

            "ClassName":
                str(row["ClassName"]),

            "TrainingCount":
                int(row["TrainingCount"]),

            "TrainingPercentage":
                float(row["TrainingPercentage"])
        }

        for _, row
        in training_class_distribution.iterrows()
    ]
}

with open(
    TRAINING_CLASS_DISTRIBUTION_SUMMARY_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        training_class_distribution_summary,
        f,
        indent=2
    )


# ------------------------------------------------------------
# 4.8.2.12 Final Validation
# ------------------------------------------------------------

print("\n[VALIDATION]")

print(
    "✓ Training partition used exclusively"
)

print(
    "✓ Validation observations excluded"
)

print(
    "✓ Independent Test observations excluded"
)

print(
    "✓ Final nine-class taxonomy preserved"
)

print(
    "✓ Training sample count verified"
)

print(
    "✓ All final classes accounted for"
)

print(
    "✓ Class counts sum to total training rows"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No class weighting performed"
)

print(
    "✓ No feature values modified"
)

print(
    "✓ No partition indices modified"
)

print(
    "✓ No model fitting performed"
)


# ------------------------------------------------------------
# 4.8.2.13 Artifact Confirmation
# ------------------------------------------------------------

print("\n[ARTIFACTS]")

print(
    "✓ Training-only class distribution persisted:"
)

print(
    f"  {TRAINING_CLASS_DISTRIBUTION_PATH}"
)

print(
    "✓ Training-only imbalance summary persisted:"
)

print(
    f"  {TRAINING_CLASS_DISTRIBUTION_SUMMARY_PATH}"
)


print("\n" + "=" * 72)
print(
    "4.8.2 training-only class distribution analysis "
    "completed successfully."
)
print("=" * 72)

========================================================================
4.8.2 — TRAINING-ONLY CLASS DISTRIBUTION ANALYSIS
========================================================================

[TRAINING PARTITION]
Training rows : 1,814,018
Final classes : 9

[CLASS DISTRIBUTION]
 FinalTarget    ClassName  TrainingCount TrainingPercentage RelativeToLargestClass MajorityToClassRatio
           0       BENIGN        1448197          79.833662             1.00000000                 1.00
           1         DDoS          81968           4.518588             0.05660003                17.67
           2    Port Scan         101723           5.607607             0.07024113                14.24
           3  Brute Force           9325           0.514052             0.00643904               155.30
           4          Bot           1270           0.070010             0.00087695              1140.31
           5   Web Attack           1389           0.076570             0.00095912              1042.62
           6 Infiltration             15           0.000827             0.00001036             96546.47
           7          DoS         170125           9.378352             0.11747366                 8.51
           8   Heartbleed              6           0.000331             0.00000414            241366.17

[IMBALANCE SEVERITY]
Largest class count  : 1,448,197
Smallest class count : 6
Majority/minority ratio : 241,366.17:1

[MAJORITY CLASS]
  0 : BENIGN

[MINORITY CLASS / CLASSES]
  8 : Heartbleed

[LOW-SUPPORT CLASSES (< 100 TRAINING SAMPLES)]
  6 : Infiltration (15 samples)
  8 : Heartbleed (6 samples)

[VALIDATION]
✓ Training partition used exclusively
✓ Validation observations excluded
✓ Independent Test observations excluded
✓ Final nine-class taxonomy preserved
✓ Training sample count verified
✓ All final classes accounted for
✓ Class counts sum to total training rows
✓ No resampling performed
✓ No class weighting performed
✓ No feature values modified
✓ No partition indices modified
✓ No model fitting performed

[ARTIFACTS]
✓ Training-only class distribution persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/class_imbalance/training_only_class_distribution.csv
✓ Training-only imbalance summary persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/class_imbalance/training_only_class_distribution_summary.json

========================================================================
4.8.2 training-only class distribution analysis completed successfully.
========================================================================

# 4.8.3 — Validation and Test Distribution Analysis

This subsection quantifies the final class distribution within the validation and independent test partitions.

The persisted partition indices established during the leakage-aware partitioning stage are used directly. No partition is recreated and no observations are moved between partitions.

For each final intrusion-detection class, the validation and test distributions are recorded using:

- Number of observations
- Percentage of the corresponding partition
- Presence or absence of the class within the partition

The validation partition remains available for downstream comparison of candidate imbalance-handling strategies, while the independent test partition remains reserved exclusively for final model evaluation.

No resampling, class weighting, feature modification, partition modification, or model fitting is performed in this subsection.

In [26]:
# ============================================================
# 4.8.3 — VALIDATION AND TEST DISTRIBUTION ANALYSIS
# ============================================================

import json
import numpy as np
import pandas as pd

print("=" * 72)
print("4.8.3 — VALIDATION AND TEST DISTRIBUTION ANALYSIS")
print("=" * 72)


# ------------------------------------------------------------
# 4.8.3.1 Validate Existing Notebook State
# ------------------------------------------------------------

if "stage1_df" not in globals():
    raise NameError(
        "Existing 'stage1_df' is not available."
    )

if "validation_indices" not in globals():
    raise NameError(
        "Existing 'validation_indices' is not available."
    )

if "test_indices" not in globals():
    raise NameError(
        "Existing 'test_indices' is not available."
    )

if "FINAL_CLASS_ID_MAPPING" not in globals():
    raise NameError(
        "Existing 'FINAL_CLASS_ID_MAPPING' is not available."
    )

if "CLASS_IMBALANCE_DIR" not in globals():
    raise NameError(
        "Existing 'CLASS_IMBALANCE_DIR' is not available. "
        "Run 4.8.1 first."
    )

if "FinalTarget" not in stage1_df.columns:
    raise ValueError(
        "Required 'FinalTarget' column is not present "
        "in stage1_df."
    )


# ------------------------------------------------------------
# 4.8.3.2 Recover Final Taxonomy
# ------------------------------------------------------------

if all(
    isinstance(key, (int, np.integer))
    for key in FINAL_CLASS_ID_MAPPING.keys()
):

    final_class_names = {
        int(key): str(value)
        for key, value in FINAL_CLASS_ID_MAPPING.items()
    }

else:

    final_class_names = {
        int(value): str(key)
        for key, value in FINAL_CLASS_ID_MAPPING.items()
    }


final_class_ids = sorted(
    final_class_names.keys()
)

expected_class_count = len(
    final_class_ids
)

if expected_class_ids != list(
    range(expected_class_count)
):

    raise ValueError(
        "Final taxonomy IDs are not contiguous "
        "starting from zero."
    )


# ------------------------------------------------------------
# 4.8.3.3 Extract Validation and Test Labels
# ------------------------------------------------------------

validation_labels = np.asarray(
    stage1_df.loc[
        validation_indices,
        "FinalTarget"
    ],
    dtype=np.int64
)

test_labels = np.asarray(
    stage1_df.loc[
        test_indices,
        "FinalTarget"
    ],
    dtype=np.int64
)


if len(validation_labels) != len(
    validation_indices
):

    raise ValueError(
        "Validation label count does not match "
        "the persisted validation partition."
    )


if len(test_labels) != len(
    test_indices
):

    raise ValueError(
        "Test label count does not match "
        "the persisted test partition."
    )


# ------------------------------------------------------------
# 4.8.3.4 Validate Class IDs
# ------------------------------------------------------------

if not np.all(
    np.isin(
        validation_labels,
        final_class_ids
    )
):

    raise ValueError(
        "Validation partition contains class IDs "
        "outside the final taxonomy."
    )


if not np.all(
    np.isin(
        test_labels,
        final_class_ids
    )
):

    raise ValueError(
        "Test partition contains class IDs "
        "outside the final taxonomy."
    )


# ------------------------------------------------------------
# 4.8.3.5 Calculate Validation Distribution
# ------------------------------------------------------------

validation_total = len(
    validation_labels
)

validation_counts = np.bincount(
    validation_labels,
    minlength=expected_class_count
)

validation_percentages = (
    validation_counts /
    validation_total
) * 100.0


validation_class_distribution = pd.DataFrame(
    {
        "FinalTarget": final_class_ids,

        "ClassName": [
            final_class_names[class_id]
            for class_id in final_class_ids
        ],

        "ValidationCount":
            validation_counts,

        "ValidationPercentage":
            validation_percentages
    }
)


validation_class_distribution[
    "Present"
] = (
    validation_class_distribution[
        "ValidationCount"
    ] > 0
)


# ------------------------------------------------------------
# 4.8.3.6 Calculate Independent Test Distribution
# ------------------------------------------------------------

test_total = len(
    test_labels
)

test_counts = np.bincount(
    test_labels,
    minlength=expected_class_count
)

test_percentages = (
    test_counts /
    test_total
) * 100.0


test_class_distribution = pd.DataFrame(
    {
        "FinalTarget": final_class_ids,

        "ClassName": [
            final_class_names[class_id]
            for class_id in final_class_ids
        ],

        "TestCount":
            test_counts,

        "TestPercentage":
            test_percentages
    }
)


test_class_distribution[
    "Present"
] = (
    test_class_distribution[
        "TestCount"
    ] > 0
)


# ------------------------------------------------------------
# 4.8.3.7 Display Validation Distribution
# ------------------------------------------------------------

print("\n[VALIDATION PARTITION]")

print(
    f"Validation rows : "
    f"{validation_total:,}"
)

print(
    f"Final classes   : "
    f"{expected_class_count}"
)

print("\n[VALIDATION CLASS DISTRIBUTION]")

print(
    validation_class_distribution.to_string(
        index=False,
        formatters={
            "ValidationPercentage":
                "{:.6f}".format
        }
    )
)


# ------------------------------------------------------------
# 4.8.3.8 Display Test Distribution
# ------------------------------------------------------------

print("\n[INDEPENDENT TEST PARTITION]")

print(
    f"Test rows : "
    f"{test_total:,}"
)

print(
    f"Final classes : "
    f"{expected_class_count}"
)

print("\n[TEST CLASS DISTRIBUTION]")

print(
    test_class_distribution.to_string(
        index=False,
        formatters={
            "TestPercentage":
                "{:.6f}".format
        }
    )
)


# ------------------------------------------------------------
# 4.8.3.9 Check Class Presence
# ------------------------------------------------------------

validation_missing_classes = (
    validation_class_distribution.loc[
        ~validation_class_distribution["Present"],
        "FinalTarget"
    ]
    .astype(int)
    .tolist()
)

test_missing_classes = (
    test_class_distribution.loc[
        ~test_class_distribution["Present"],
        "FinalTarget"
    ]
    .astype(int)
    .tolist()
)


print("\n[CLASS PRESENCE]")

if len(validation_missing_classes) == 0:

    print(
        "✓ All final classes are represented "
        "in the validation partition."
    )

else:

    print(
        "⚠ Validation classes with zero observations:"
    )

    for class_id in validation_missing_classes:

        print(
            f"  {class_id} : "
            f"{final_class_names[class_id]}"
        )


if len(test_missing_classes) == 0:

    print(
        "✓ All final classes are represented "
        "in the independent test partition."
    )

else:

    print(
        "⚠ Test classes with zero observations:"
    )

    for class_id in test_missing_classes:

        print(
            f"  {class_id} : "
            f"{final_class_names[class_id]}"
        )


# ------------------------------------------------------------
# 4.8.3.10 Persist Validation Distribution
# ------------------------------------------------------------

VALIDATION_CLASS_DISTRIBUTION_PATH = (
    CLASS_IMBALANCE_DIR /
    "validation_class_distribution.csv"
)

validation_class_distribution.to_csv(
    VALIDATION_CLASS_DISTRIBUTION_PATH,
    index=False
)


# ------------------------------------------------------------
# 4.8.3.11 Persist Test Distribution
# ------------------------------------------------------------

TEST_CLASS_DISTRIBUTION_PATH = (
    CLASS_IMBALANCE_DIR /
    "test_class_distribution.csv"
)

test_class_distribution.to_csv(
    TEST_CLASS_DISTRIBUTION_PATH,
    index=False
)


# ------------------------------------------------------------
# 4.8.3.12 Final Validation
# ------------------------------------------------------------

print("\n[VALIDATION]")

print(
    "✓ Persisted validation indices used directly"
)

print(
    "✓ Persisted independent test indices used directly"
)

print(
    "✓ Validation partition was not recreated"
)

print(
    "✓ Independent test partition was not recreated"
)

print(
    "✓ Final nine-class taxonomy preserved"
)

print(
    "✓ Validation class counts verified"
)

print(
    "✓ Test class counts verified"
)

print(
    "✓ Validation and test observations were "
    "not used for resampling"
)

print(
    "✓ No class weighting performed"
)

print(
    "✓ No feature values modified"
)

print(
    "✓ No partition indices modified"
)

print(
    "✓ No model fitting performed"
)


# ------------------------------------------------------------
# 4.8.3.13 Artifact Confirmation
# ------------------------------------------------------------

print("\n[ARTIFACTS]")

print(
    "✓ Validation distribution persisted:"
)

print(
    f"  {VALIDATION_CLASS_DISTRIBUTION_PATH}"
)

print(
    "✓ Independent test distribution persisted:"
)

print(
    f"  {TEST_CLASS_DISTRIBUTION_PATH}"
)


print("\n" + "=" * 72)

print(
    "4.8.3 validation and test distribution analysis "
    "completed successfully."
)

print("=" * 72)

========================================================================
4.8.3 — VALIDATION AND TEST DISTRIBUTION ANALYSIS
========================================================================

[VALIDATION PARTITION]
Validation rows : 451,215
Final classes   : 9

[VALIDATION CLASS DISTRIBUTION]
 FinalTarget    ClassName  ValidationCount ValidationPercentage  Present
           0       BENIGN           369501            81.890230     True
           1         DDoS            20458             4.533980     True
           2    Port Scan            25261             5.598440     True
           3  Brute Force             1862             0.412664     True
           4          Bot              297             0.065822     True
           5   Web Attack              363             0.080449     True
           6 Infiltration               13             0.002881     True
           7          DoS            33456             7.414647     True
           8   Heartbleed                4             0.000886     True

[INDEPENDENT TEST PARTITION]
Test rows : 565,510
Final classes : 9

[TEST CLASS DISTRIBUTION]
 FinalTarget    ClassName  TestCount TestPercentage  Present
           0       BENIGN     455399      80.528903     True
           1         DDoS      25601       4.527064     True
           2    Port Scan      31946       5.649060     True
           3  Brute Force       2648       0.468250     True
           4          Bot        399       0.070556     True
           5   Web Attack        428       0.075684     True
           6 Infiltration          8       0.001415     True
           7          DoS      49080       8.678892     True
           8   Heartbleed          1       0.000177     True

[CLASS PRESENCE]
✓ All final classes are represented in the validation partition.
✓ All final classes are represented in the independent test partition.

[VALIDATION]
✓ Persisted validation indices used directly
✓ Persisted independent test indices used directly
✓ Validation partition was not recreated
✓ Independent test partition was not recreated
✓ Final nine-class taxonomy preserved
✓ Validation class counts verified
✓ Test class counts verified
✓ Validation and test observations were not used for resampling
✓ No class weighting performed
✓ No feature values modified
✓ No partition indices modified
✓ No model fitting performed

[ARTIFACTS]
✓ Validation distribution persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/class_imbalance/validation_class_distribution.csv
✓ Independent test distribution persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/class_imbalance/test_class_distribution.csv

========================================================================
4.8.3 validation and test distribution analysis completed successfully.
========================================================================

# 4.8.4 — Minority-Class Support Assessment

This subsection assesses the amount of class-specific evidence available across the training, validation, and independent test partitions.

The persisted class-distribution artifacts from Sections 4.8.2 and 4.8.3 are used to evaluate:

- Training support for each final class
- Validation support for each final class
- Independent test support for each final class
- Total observations available across all partitions
- Relative representation of each class in the training partition
- Identification of low-support and extremely low-support classes
- Whether any class is absent from a required partition

A class with fewer than 100 training observations is treated as a low-support class for experimental planning. Classes with extremely small absolute support are separately identified because synthetic oversampling cannot create additional independent observations.

This assessment is descriptive only. No resampling, class weighting, partition modification, feature modification, or model fitting is performed.

In [27]:
# ============================================================
# 4.8.4 — MINORITY-CLASS SUPPORT ASSESSMENT
# ============================================================

import json
import numpy as np
import pandas as pd

print("=" * 72)
print("4.8.4 — MINORITY-CLASS SUPPORT ASSESSMENT")
print("=" * 72)


# ------------------------------------------------------------
# 4.8.4.1 Load Persisted Class-Distribution Artifacts
# ------------------------------------------------------------

if "CLASS_IMBALANCE_DIR" not in globals():
    raise NameError(
        "Existing 'CLASS_IMBALANCE_DIR' is not available. "
        "Run Section 4.8.1 first."
    )


training_distribution_path = (
    CLASS_IMBALANCE_DIR /
    "training_only_class_distribution.csv"
)

validation_distribution_path = (
    CLASS_IMBALANCE_DIR /
    "validation_class_distribution.csv"
)

test_distribution_path = (
    CLASS_IMBALANCE_DIR /
    "test_class_distribution.csv"
)


required_distribution_paths = [
    training_distribution_path,
    validation_distribution_path,
    test_distribution_path
]


for artifact_path in required_distribution_paths:

    if not artifact_path.exists():

        raise FileNotFoundError(
            f"Required class-distribution artifact is missing: "
            f"{artifact_path}"
        )


training_distribution = pd.read_csv(
    training_distribution_path
)

validation_distribution = pd.read_csv(
    validation_distribution_path
)

test_distribution = pd.read_csv(
    test_distribution_path
)


print("\n[PERSISTED INPUT ARTIFACTS]")

print(
    "✓ Training-only class distribution found"
)

print(
    "✓ Validation class distribution found"
)

print(
    "✓ Independent test class distribution found"
)


# ------------------------------------------------------------
# 4.8.4.2 Validate Required Columns
# ------------------------------------------------------------

required_training_columns = {
    "FinalTarget",
    "ClassName",
    "TrainingCount",
    "TrainingPercentage"
}

required_validation_columns = {
    "FinalTarget",
    "ClassName",
    "ValidationCount",
    "ValidationPercentage"
}

required_test_columns = {
    "FinalTarget",
    "ClassName",
    "TestCount",
    "TestPercentage"
}


if not required_training_columns.issubset(
    training_distribution.columns
):

    raise ValueError(
        "Training class-distribution artifact is missing "
        "required columns."
    )


if not required_validation_columns.issubset(
    validation_distribution.columns
):

    raise ValueError(
        "Validation class-distribution artifact is missing "
        "required columns."
    )


if not required_test_columns.issubset(
    test_distribution.columns
):

    raise ValueError(
        "Test class-distribution artifact is missing "
        "required columns."
    )


# ------------------------------------------------------------
# 4.8.4.3 Establish Final Class Set
# ------------------------------------------------------------

training_class_ids = set(
    training_distribution["FinalTarget"]
    .astype(int)
)

validation_class_ids = set(
    validation_distribution["FinalTarget"]
    .astype(int)
)

test_class_ids = set(
    test_distribution["FinalTarget"]
    .astype(int)
)


if not (
    training_class_ids
    == validation_class_ids
    == test_class_ids
):

    raise ValueError(
        "Training, validation, and test distributions "
        "do not contain the same final class IDs."
    )


final_class_ids = sorted(
    training_class_ids
)


# ------------------------------------------------------------
# 4.8.4.4 Build Minority-Support Assessment
# ------------------------------------------------------------

support_assessment = training_distribution[
    [
        "FinalTarget",
        "ClassName",
        "TrainingCount",
        "TrainingPercentage"
    ]
].copy()


support_assessment = support_assessment.merge(
    validation_distribution[
        [
            "FinalTarget",
            "ValidationCount",
            "ValidationPercentage"
        ]
    ],
    on="FinalTarget",
    how="inner"
)


support_assessment = support_assessment.merge(
    test_distribution[
        [
            "FinalTarget",
            "TestCount",
            "TestPercentage"
        ]
    ],
    on="FinalTarget",
    how="inner"
)


support_assessment["FinalTarget"] = (
    support_assessment["FinalTarget"]
    .astype(int)
)


support_assessment["TrainingCount"] = (
    support_assessment["TrainingCount"]
    .astype(int)
)

support_assessment["ValidationCount"] = (
    support_assessment["ValidationCount"]
    .astype(int)
)

support_assessment["TestCount"] = (
    support_assessment["TestCount"]
    .astype(int)
)


support_assessment["TotalCount"] = (
    support_assessment["TrainingCount"]
    + support_assessment["ValidationCount"]
    + support_assessment["TestCount"]
)


support_assessment["MinimumPartitionCount"] = (
    support_assessment[
        [
            "TrainingCount",
            "ValidationCount",
            "TestCount"
        ]
    ].min(axis=1)
)


support_assessment["TrainingToTotalRatio"] = (
    support_assessment["TrainingCount"]
    /
    support_assessment["TotalCount"]
)


# ------------------------------------------------------------
# 4.8.4.5 Define Support Categories
# ------------------------------------------------------------

LOW_SUPPORT_THRESHOLD = 100
EXTREME_SUPPORT_THRESHOLD = 10


def classify_support(training_count, total_count):

    if total_count < EXTREME_SUPPORT_THRESHOLD:

        return "Extremely Low Support"

    if training_count < EXTREME_SUPPORT_THRESHOLD:

        return "Extremely Low Training Support"

    if training_count < LOW_SUPPORT_THRESHOLD:

        return "Low Training Support"

    return "Adequate Training Support"


support_assessment["SupportCategory"] = [
    classify_support(
        training_count,
        total_count
    )
    for training_count, total_count
    in zip(
        support_assessment["TrainingCount"],
        support_assessment["TotalCount"]
    )
]


support_assessment["ValidationPresent"] = (
    support_assessment["ValidationCount"] > 0
)

support_assessment["TestPresent"] = (
    support_assessment["TestCount"] > 0
)


# ------------------------------------------------------------
# 4.8.4.6 Order Classes by Training Support
# ------------------------------------------------------------

support_assessment = (
    support_assessment
    .sort_values(
        by="TrainingCount",
        ascending=True
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 4.8.4.7 Display Support Assessment
# ------------------------------------------------------------

print("\n[MINORITY-CLASS SUPPORT ASSESSMENT]")

print(
    support_assessment[
        [
            "FinalTarget",
            "ClassName",
            "TrainingCount",
            "ValidationCount",
            "TestCount",
            "TotalCount",
            "MinimumPartitionCount",
            "SupportCategory"
        ]
    ].to_string(index=False)
)


# ------------------------------------------------------------
# 4.8.4.8 Identify Low-Support Classes
# ------------------------------------------------------------

low_support_classes = (
    support_assessment[
        support_assessment["TrainingCount"]
        < LOW_SUPPORT_THRESHOLD
    ]
    .copy()
)


extreme_support_classes = (
    support_assessment[
        support_assessment["TrainingCount"]
        < EXTREME_SUPPORT_THRESHOLD
    ]
    .copy()
)


print("\n[LOW-SUPPORT CLASSES]")

print(
    f"Training support threshold : "
    f"< {LOW_SUPPORT_THRESHOLD} observations"
)

if len(low_support_classes) == 0:

    print(
        "✓ No classes fall below the low-support threshold."
    )

else:

    for _, row in low_support_classes.iterrows():

        print(
            f"- {int(row['FinalTarget'])} : "
            f"{row['ClassName']} "
            f"({int(row['TrainingCount'])} training, "
            f"{int(row['ValidationCount'])} validation, "
            f"{int(row['TestCount'])} test)"
        )


print("\n[EXTREMELY LOW-SUPPORT CLASSES]")

print(
    f"Training support threshold : "
    f"< {EXTREME_SUPPORT_THRESHOLD} observations"
)

if len(extreme_support_classes) == 0:

    print(
        "✓ No classes fall below the extremely-low "
        "training-support threshold."
    )

else:

    for _, row in extreme_support_classes.iterrows():

        print(
            f"- {int(row['FinalTarget'])} : "
            f"{row['ClassName']} "
            f"({int(row['TrainingCount'])} training, "
            f"{int(row['ValidationCount'])} validation, "
            f"{int(row['TestCount'])} test)"
        )


# ------------------------------------------------------------
# 4.8.4.9 Partition-Presence Validation
# ------------------------------------------------------------

missing_validation = (
    support_assessment[
        ~support_assessment["ValidationPresent"]
    ]
)

missing_test = (
    support_assessment[
        ~support_assessment["TestPresent"]
    ]
)


print("\n[PARTITION SUPPORT VALIDATION]")

if len(missing_validation) == 0:

    print(
        "✓ Every final class has validation observations."
    )

else:

    print(
        "⚠ Classes missing from validation:"
    )

    for _, row in missing_validation.iterrows():

        print(
            f"  {int(row['FinalTarget'])} : "
            f"{row['ClassName']}"
        )


if len(missing_test) == 0:

    print(
        "✓ Every final class has independent test observations."
    )

else:

    print(
        "⚠ Classes missing from independent test:"
    )

    for _, row in missing_test.iterrows():

        print(
            f"  {int(row['FinalTarget'])} : "
            f"{row['ClassName']}"
        )


# ------------------------------------------------------------
# 4.8.4.10 Persist Minority Support Analysis
# ------------------------------------------------------------

MINORITY_SUPPORT_ANALYSIS_PATH = (
    CLASS_IMBALANCE_DIR /
    "minority_support_analysis.csv"
)


support_assessment.to_csv(
    MINORITY_SUPPORT_ANALYSIS_PATH,
    index=False
)


# ------------------------------------------------------------
# 4.8.4.11 Final Validation
# ------------------------------------------------------------

print("\n[VALIDATION]")

print(
    "✓ Training distribution loaded from persisted artifact"
)

print(
    "✓ Validation distribution loaded from persisted artifact"
)

print(
    "✓ Independent test distribution loaded from persisted artifact"
)

print(
    "✓ Same final class set verified across all partitions"
)

print(
    "✓ Training, validation, and test counts retained unchanged"
)

print(
    "✓ Low-support classes identified"
)

print(
    "✓ Extremely low-support classes identified"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No class weighting performed"
)

print(
    "✓ No feature values modified"
)

print(
    "✓ No partition indices modified"
)

print(
    "✓ No labels modified"
)

print(
    "✓ No model fitting performed"
)


# ------------------------------------------------------------
# 4.8.4.12 Artifact Confirmation
# ------------------------------------------------------------

print("\n[ARTIFACT]")

print(
    "✓ Minority support analysis persisted:"
)

print(
    f"  {MINORITY_SUPPORT_ANALYSIS_PATH}"
)


print("\n" + "=" * 72)

print(
    "4.8.4 minority-class support assessment "
    "completed successfully."
)

print("=" * 72)

========================================================================
4.8.4 — MINORITY-CLASS SUPPORT ASSESSMENT
========================================================================

[PERSISTED INPUT ARTIFACTS]
✓ Training-only class distribution found
✓ Validation class distribution found
✓ Independent test class distribution found

[MINORITY-CLASS SUPPORT ASSESSMENT]
 FinalTarget    ClassName  TrainingCount  ValidationCount  TestCount  TotalCount  MinimumPartitionCount                SupportCategory
           8   Heartbleed              6                4          1          11                      1 Extremely Low Training Support
           6 Infiltration             15               13          8          36                      8           Low Training Support
           4          Bot           1270              297        399        1966                    297      Adequate Training Support
           5   Web Attack           1389              363        428        2180                    363      Adequate Training Support
           3  Brute Force           9325             1862       2648       13835                   1862      Adequate Training Support
           1         DDoS          81968            20458      25601      128027                  20458      Adequate Training Support
           2    Port Scan         101723            25261      31946      158930                  25261      Adequate Training Support
           7          DoS         170125            33456      49080      252661                  33456      Adequate Training Support
           0       BENIGN        1448197           369501     455399     2273097                 369501      Adequate Training Support

[LOW-SUPPORT CLASSES]
Training support threshold : < 100 observations
- 8 : Heartbleed (6 training, 4 validation, 1 test)
- 6 : Infiltration (15 training, 13 validation, 8 test)

[EXTREMELY LOW-SUPPORT CLASSES]
Training support threshold : < 10 observations
- 8 : Heartbleed (6 training, 4 validation, 1 test)

[PARTITION SUPPORT VALIDATION]
✓ Every final class has validation observations.
✓ Every final class has independent test observations.

[VALIDATION]
✓ Training distribution loaded from persisted artifact
✓ Validation distribution loaded from persisted artifact
✓ Independent test distribution loaded from persisted artifact
✓ Same final class set verified across all partitions
✓ Training, validation, and test counts retained unchanged
✓ Low-support classes identified
✓ Extremely low-support classes identified
✓ No resampling performed
✓ No class weighting performed
✓ No feature values modified
✓ No partition indices modified
✓ No labels modified
✓ No model fitting performed

[ARTIFACT]
✓ Minority support analysis persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/class_imbalance/minority_support_analysis.csv

========================================================================
4.8.4 minority-class support assessment completed successfully.
========================================================================

# 4.8.5 — Imbalance Severity & Training Implications

This subsection interprets the class distributions established in Sections 4.8.2–4.8.4 and documents the implications of the observed class imbalance for downstream model training.

The analysis is based on the persisted training, validation, and independent test class-distribution artifacts. No samples are added, removed, duplicated, synthesized, or reweighted in this subsection.

The assessment focuses on:

- majority-to-minority class imbalance,
- relative representation of each final class,
- training support available for minority classes,
- classes with extremely limited empirical support,
- the difference between training imbalance and evaluation imbalance,
- and implications for Random Forest and LSTM model development.

The independent test partition remains untouched and is not used to select an imbalance-handling strategy.

The observed imbalance is treated as a property of the dataset rather than as a preprocessing error. Therefore, the common evaluation partitions retain their original class distributions.

The results of this analysis are used to define the requirements for the controlled imbalance experiments performed in the downstream model-training stages. Candidate strategies may include class-weighted learning, controlled random oversampling, and controlled SMOTE-based approaches. No strategy is declared optimal at this stage.

In particular, extremely low-support classes must be interpreted cautiously. Synthetic oversampling cannot create genuinely independent observations for classes with very few original samples, and therefore any apparent improvement for such classes must be evaluated together with class-wise precision, recall, F1-score, confusion patterns, and support.

No model is fitted in this subsection.

In [28]:
# ============================================================
# 4.8.5 — IMBALANCE SEVERITY & TRAINING IMPLICATIONS
# ============================================================

from pathlib import Path
import json
import numpy as np
import pandas as pd

print("=" * 72)
print("4.8.5 — IMBALANCE SEVERITY & TRAINING IMPLICATIONS")
print("=" * 72)


# ------------------------------------------------------------
# 4.8.5.1 Load Persisted Class-Distribution Artifacts
# ------------------------------------------------------------

CLASS_IMBALANCE_DIR = Path(
    "/content/drive/MyDrive/"
    "AI-Network-Intrusion-Detection-System/"
    "outputs/model_preparation_v2/class_imbalance"
)

# IMPORTANT:
# 4.8.2 persisted the training artifact using this exact name.
TRAINING_DISTRIBUTION_PATH = (
    CLASS_IMBALANCE_DIR /
    "training_only_class_distribution.csv"
)

VALIDATION_DISTRIBUTION_PATH = (
    CLASS_IMBALANCE_DIR /
    "validation_class_distribution.csv"
)

TEST_DISTRIBUTION_PATH = (
    CLASS_IMBALANCE_DIR /
    "test_class_distribution.csv"
)

required_files = {
    "Training distribution": TRAINING_DISTRIBUTION_PATH,
    "Validation distribution": VALIDATION_DISTRIBUTION_PATH,
    "Test distribution": TEST_DISTRIBUTION_PATH
}

missing_files = [
    name
    for name, path in required_files.items()
    if not path.is_file()
]

if missing_files:
    raise FileNotFoundError(
        "Required class-distribution artifacts are missing:\n"
        + "\n".join(
            f"  - {name}: {required_files[name]}"
            for name in missing_files
        )
    )

print("\n[PERSISTED INPUT ARTIFACTS]")
print("✓ Training-only class distribution found")
print("✓ Validation class distribution found")
print("✓ Independent test class distribution found")


# ------------------------------------------------------------
# 4.8.5.2 Load Distributions
# ------------------------------------------------------------

training_distribution = pd.read_csv(
    TRAINING_DISTRIBUTION_PATH
)

validation_distribution = pd.read_csv(
    VALIDATION_DISTRIBUTION_PATH
)

test_distribution = pd.read_csv(
    TEST_DISTRIBUTION_PATH
)

print("\n[INPUT DISTRIBUTIONS]")
print(
    f"Training rows represented   : "
    f"{training_distribution['TrainingCount'].sum():,}"
)

print(
    f"Validation rows represented : "
    f"{validation_distribution['ValidationCount'].sum():,}"
)

print(
    f"Test rows represented       : "
    f"{test_distribution['TestCount'].sum():,}"
)


# ------------------------------------------------------------
# 4.8.5.3 Validate Final Taxonomy
# ------------------------------------------------------------

training_classes = set(
    training_distribution["FinalTarget"]
)

validation_classes = set(
    validation_distribution["FinalTarget"]
)

test_classes = set(
    test_distribution["FinalTarget"]
)

if not (
    training_classes
    == validation_classes
    == test_classes
):
    raise ValueError(
        "Training, validation, and test class sets are inconsistent."
    )

print("\n[TAXONOMY VALIDATION]")
print(
    f"Final classes represented : "
    f"{len(training_classes)}"
)

print(
    "✓ Training, validation, and test use the same final taxonomy"
)


# ------------------------------------------------------------
# 4.8.5.4 Build Cross-Partition Imbalance Summary
# ------------------------------------------------------------

summary = training_distribution[
    [
        "FinalTarget",
        "ClassName",
        "TrainingCount",
        "TrainingPercentage",
        "MajorityToClassRatio"
    ]
].copy()

summary = summary.merge(
    validation_distribution[
        [
            "FinalTarget",
            "ValidationCount",
            "ValidationPercentage"
        ]
    ],
    on="FinalTarget",
    how="left",
    validate="one_to_one"
)

summary = summary.merge(
    test_distribution[
        [
            "FinalTarget",
            "TestCount",
            "TestPercentage"
        ]
    ],
    on="FinalTarget",
    how="left",
    validate="one_to_one"
)

summary["TotalCount"] = (
    summary["TrainingCount"]
    + summary["ValidationCount"]
    + summary["TestCount"]
)

summary["MinimumPartitionCount"] = (
    summary[
        [
            "TrainingCount",
            "ValidationCount",
            "TestCount"
        ]
    ].min(axis=1)
)

summary["TrainingShareOfLargestClass"] = (
    summary["TrainingCount"]
    / summary["TrainingCount"].max()
)

summary["TrainingSupportCategory"] = np.select(
    [
        summary["TrainingCount"] < 10,
        summary["TrainingCount"] < 100,
        summary["TrainingCount"] < 500,
        summary["TrainingCount"] < 5000
    ],
    [
        "Extremely Low",
        "Very Low",
        "Low",
        "Moderate"
    ],
    default="High"
)

summary = summary.sort_values(
    "TrainingCount",
    ascending=True
).reset_index(drop=True)

print("\n[IMBALANCE SEVERITY TABLE]")

display(summary)


# ------------------------------------------------------------
# 4.8.5.5 Quantify Overall Imbalance Severity
# ------------------------------------------------------------

largest_training_count = int(
    summary["TrainingCount"].max()
)

smallest_training_count = int(
    summary["TrainingCount"].min()
)

training_majority_minority_ratio = (
    largest_training_count
    / smallest_training_count
)

low_support_count = int(
    (
        summary["TrainingCount"] < 100
    ).sum()
)

extremely_low_support_count = int(
    (
        summary["TrainingCount"] < 10
    ).sum()
)

print("\n[OVERALL IMBALANCE SEVERITY]")

print(
    f"Largest training class : "
    f"{largest_training_count:,} samples"
)

print(
    f"Smallest training class : "
    f"{smallest_training_count:,} samples"
)

print(
    f"Training majority/minority ratio : "
    f"{training_majority_minority_ratio:,.2f}:1"
)

print(
    f"Classes with <100 training samples : "
    f"{low_support_count}"
)

print(
    f"Classes with <10 training samples : "
    f"{extremely_low_support_count}"
)


# ------------------------------------------------------------
# 4.8.5.6 Identify Low-Support Classes
# ------------------------------------------------------------

very_low_support = summary[
    summary["TrainingCount"] < 100
].copy()

extremely_low_support = summary[
    summary["TrainingCount"] < 10
].copy()

print("\n[VERY LOW-SUPPORT TRAINING CLASSES]")

if len(very_low_support) == 0:
    print("None")
else:
    for _, row in very_low_support.iterrows():
        print(
            f"  - {row['ClassName']}: "
            f"{int(row['TrainingCount']):,} training | "
            f"{int(row['ValidationCount']):,} validation | "
            f"{int(row['TestCount']):,} test"
        )

print("\n[EXTREMELY LOW-SUPPORT TRAINING CLASSES]")

if len(extremely_low_support) == 0:
    print("None")
else:
    for _, row in extremely_low_support.iterrows():
        print(
            f"  - {row['ClassName']}: "
            f"{int(row['TrainingCount']):,} training | "
            f"{int(row['ValidationCount']):,} validation | "
            f"{int(row['TestCount']):,} test"
        )


# ------------------------------------------------------------
# 4.8.5.7 Training Implications
# ------------------------------------------------------------

training_implications = [
    "Accuracy must not be used as the sole model-quality measure.",
    "Macro-averaged precision, recall, and F1-score should be reported.",
    "Per-class metrics must be interpreted together with class support.",
    "Random Forest and LSTM may require different imbalance strategies.",
    "Any imbalance strategy must operate on training/development data only.",
    "Validation data may be used to compare candidate strategies.",
    "The independent test partition must remain untouched until final evaluation.",
    "Extremely rare classes require cautious interpretation because synthetic "
    "sampling cannot create genuinely independent observations."
]

print("\n[TRAINING IMPLICATIONS]")

for implication in training_implications:
    print(f"  • {implication}")


# ------------------------------------------------------------
# 4.8.5.8 Integrity Validation
# ------------------------------------------------------------

assert (
    summary["TrainingCount"].sum()
    == training_distribution["TrainingCount"].sum()
)

assert (
    summary["ValidationCount"].sum()
    == validation_distribution["ValidationCount"].sum()
)

assert (
    summary["TestCount"].sum()
    == test_distribution["TestCount"].sum()
)

assert len(training_classes) == 9

assert (
    summary["MinimumPartitionCount"] > 0
).all()

print("\n[VALIDATION]")
print("✓ Training distribution preserved")
print("✓ Validation distribution preserved")
print("✓ Independent test distribution preserved")
print("✓ All nine final classes accounted for")
print("✓ Every class has observations in all three partitions")
print("✓ Imbalance severity quantified")
print("✓ Low-support classes identified")
print("✓ No resampling performed")
print("✓ No class weighting performed")
print("✓ No feature values modified")
print("✓ No partition indices modified")
print("✓ No model fitting performed")


# ------------------------------------------------------------
# 4.8.5.9 Persist Class-Imbalance Summary
# ------------------------------------------------------------

CLASS_IMBALANCE_SUMMARY_PATH = (
    CLASS_IMBALANCE_DIR /
    "class_imbalance_summary.csv"
)

summary.to_csv(
    CLASS_IMBALANCE_SUMMARY_PATH,
    index=False
)

print("\n[ARTIFACT]")
print("✓ Class-imbalance summary persisted:")
print(
    f"  {CLASS_IMBALANCE_SUMMARY_PATH}"
)


# ------------------------------------------------------------
# 4.8.5.10 Persist Severity Metadata
# ------------------------------------------------------------

CLASS_IMBALANCE_SEVERITY_METADATA_PATH = (
    CLASS_IMBALANCE_DIR /
    "class_imbalance_severity_metadata.json"
)

severity_metadata = {
    "subsection":
        "4.8.5 — Imbalance Severity & Training Implications",

    "final_class_count":
        int(len(training_classes)),

    "largest_training_class_count":
        largest_training_count,

    "smallest_training_class_count":
        smallest_training_count,

    "training_majority_minority_ratio":
        float(training_majority_minority_ratio),

    "classes_below_100_training_samples":
        low_support_count,

    "classes_below_10_training_samples":
        extremely_low_support_count,

    "very_low_support_classes":
        very_low_support["ClassName"].tolist(),

    "extremely_low_support_classes":
        extremely_low_support["ClassName"].tolist(),

    "resampling_applied":
        False,

    "class_weighting_applied":
        False,

    "smote_applied":
        False,

    "model_fitting_performed":
        False,

    "independent_test_modified":
        False,

    "candidate_downstream_strategies": [
        "class-weighted learning",
        "controlled random oversampling",
        "controlled SMOTE"
    ],

    "training_implications":
        training_implications
}

with open(
    CLASS_IMBALANCE_SEVERITY_METADATA_PATH,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        severity_metadata,
        f,
        indent=4
    )

print(
    "✓ Imbalance severity metadata persisted:"
)

print(
    f"  {CLASS_IMBALANCE_SEVERITY_METADATA_PATH}"
)


# ------------------------------------------------------------
# 4.8.5.11 Completion
# ------------------------------------------------------------

print("\n" + "=" * 72)
print(
    "4.8.5 imbalance severity and training implications "
    "completed successfully."
)
print("=" * 72)

========================================================================
4.8.5 — IMBALANCE SEVERITY & TRAINING IMPLICATIONS
========================================================================

[PERSISTED INPUT ARTIFACTS]
✓ Training-only class distribution found
✓ Validation class distribution found
✓ Independent test class distribution found

[INPUT DISTRIBUTIONS]
Training rows represented   : 1,814,018
Validation rows represented : 451,215
Test rows represented       : 565,510

[TAXONOMY VALIDATION]
Final classes represented : 9
✓ Training, validation, and test use the same final taxonomy

[IMBALANCE SEVERITY TABLE]

,FinalTarget,ClassName,TrainingCount,TrainingPercentage,MajorityToClassRatio,ValidationCount,ValidationPercentage,TestCount,TestPercentage,TotalCount,MinimumPartitionCount,TrainingShareOfLargestClass,TrainingSupportCategory
0,8,Heartbleed,6,0.000331,241366.166667,4,0.000886,1,0.000177,11,1,0.000004,Extremely Low
1,6,Infiltration,15,0.000827,96546.466667,13,0.002881,8,0.001415,36,8,0.000010,Very Low
2,4,Bot,1270,0.070010,1140.312598,297,0.065822,399,0.070556,1966,297,0.000877,Moderate
3,5,Web Attack,1389,0.076570,1042.618431,363,0.080449,428,0.075684,2180,363,0.000959,Moderate
4,3,Brute Force,9325,0.514052,155.302627,1862,0.412664,2648,0.468250,13835,1862,0.006439,High
5,1,DDoS,81968,4.518588,17.667834,20458,4.533980,25601,4.527064,128027,20458,0.056600,High
6,2,Port Scan,101723,5.607607,14.236672,25261,5.598440,31946,5.649060,158930,25261,0.070241,High
7,7,DoS,170125,9.378352,8.512547,33456,7.414647,49080,8.678892,252661,33456,0.117474,High
8,0,BENIGN,1448197,79.833662,1.000000,369501,81.890230,455399,80.528903,2273097,369501,1.000000,High

[OVERALL IMBALANCE SEVERITY]
Largest training class : 1,448,197 samples
Smallest training class : 6 samples
Training majority/minority ratio : 241,366.17:1
Classes with <100 training samples : 2
Classes with <10 training samples : 1

[VERY LOW-SUPPORT TRAINING CLASSES]
  - Heartbleed: 6 training | 4 validation | 1 test
  - Infiltration: 15 training | 13 validation | 8 test

[EXTREMELY LOW-SUPPORT TRAINING CLASSES]
  - Heartbleed: 6 training | 4 validation | 1 test

[TRAINING IMPLICATIONS]
  • Accuracy must not be used as the sole model-quality measure.
  • Macro-averaged precision, recall, and F1-score should be reported.
  • Per-class metrics must be interpreted together with class support.
  • Random Forest and LSTM may require different imbalance strategies.
  • Any imbalance strategy must operate on training/development data only.
  • Validation data may be used to compare candidate strategies.
  • The independent test partition must remain untouched until final evaluation.
  • Extremely rare classes require cautious interpretation because synthetic sampling cannot create genuinely independent observations.

[VALIDATION]
✓ Training distribution preserved
✓ Validation distribution preserved
✓ Independent test distribution preserved
✓ All nine final classes accounted for
✓ Every class has observations in all three partitions
✓ Imbalance severity quantified
✓ Low-support classes identified
✓ No resampling performed
✓ No class weighting performed
✓ No feature values modified
✓ No partition indices modified
✓ No model fitting performed

[ARTIFACT]
✓ Class-imbalance summary persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/class_imbalance/class_imbalance_summary.csv
✓ Imbalance severity metadata persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/class_imbalance/class_imbalance_severity_metadata.json

========================================================================
4.8.5 imbalance severity and training implications completed successfully.
========================================================================

# 4.8.6 Class-Imbalance Analysis Persistence

This subsection performs the final persistence and integrity validation
for the class-imbalance analysis completed in Sections 4.8.1–4.8.5.

The purpose is to confirm that the training, validation, and independent
test class distributions, minority-support assessment, and imbalance
severity findings have been persisted consistently under the
model_preparation_v2 class-imbalance artifact directory.

This subsection does not perform any new resampling, class weighting,
label modification, partitioning, feature transformation, or model fitting.

The independent test partition remains untouched. The persisted findings
will be used to design the controlled downstream imbalance experiments
for Random Forest and LSTM training.

Final class-imbalance artifacts include:

- training_class_distribution.csv
- validation_class_distribution.csv
- test_class_distribution.csv
- class_imbalance_summary.csv
- minority_support_analysis.csv
- class_imbalance_severity_metadata.json

The final validation checks artifact existence, class coverage, row-count
consistency, taxonomy consistency, and preservation of the evaluation
boundary.

In [29]:
# ============================================================
# 4.8.6 Class-Imbalance Analysis Persistence
# ============================================================

print("=" * 72)
print("4.8.6 — CLASS-IMBALANCE ANALYSIS PERSISTENCE")
print("=" * 72)

# ------------------------------------------------------------
# 4.8.6.1 Required Persisted Artifacts
# ------------------------------------------------------------

required_class_imbalance_artifacts = [
    TRAINING_CLASS_DISTRIBUTION_PATH,
    VALIDATION_CLASS_DISTRIBUTION_PATH,
    TEST_CLASS_DISTRIBUTION_PATH,
    CLASS_IMBALANCE_SUMMARY_PATH,
    MINORITY_SUPPORT_ANALYSIS_PATH,
    CLASS_IMBALANCE_SEVERITY_METADATA_PATH,
]

missing_artifacts = [
    path for path in required_class_imbalance_artifacts
    if not path.exists()
]

if missing_artifacts:
    raise FileNotFoundError(
        "Required class-imbalance artifacts are missing:\n"
        + "\n".join(str(path) for path in missing_artifacts)
    )

print("\n[PERSISTED ARTIFACT CHECK]")

print("✓ Training class distribution found")
print("✓ Validation class distribution found")
print("✓ Test class distribution found")
print("✓ Class-imbalance summary found")
print("✓ Minority-support analysis found")
print("✓ Imbalance-severity metadata found")


# ------------------------------------------------------------
# 4.8.6.2 Reload Persisted Distribution Artifacts
# ------------------------------------------------------------

training_distribution = pd.read_csv(
    TRAINING_CLASS_DISTRIBUTION_PATH
)

validation_distribution = pd.read_csv(
    VALIDATION_CLASS_DISTRIBUTION_PATH
)

test_distribution = pd.read_csv(
    TEST_CLASS_DISTRIBUTION_PATH
)

class_imbalance_summary = pd.read_csv(
    CLASS_IMBALANCE_SUMMARY_PATH
)

minority_support_analysis = pd.read_csv(
    MINORITY_SUPPORT_ANALYSIS_PATH
)


# ------------------------------------------------------------
# 4.8.6.3 Class-Taxonomy Validation
# ------------------------------------------------------------

expected_final_classes = set(
    range(9)
)

for distribution_name, distribution_df in [
    ("Training", training_distribution),
    ("Validation", validation_distribution),
    ("Test", test_distribution),
]:

    if "FinalTarget" not in distribution_df.columns:
        raise ValueError(
            f"{distribution_name} distribution is missing "
            "'FinalTarget'."
        )

    if "ClassName" not in distribution_df.columns:
        raise ValueError(
            f"{distribution_name} distribution is missing "
            "'ClassName'."
        )

    observed_classes = set(
        distribution_df["FinalTarget"].astype(int)
    )

    if observed_classes != expected_final_classes:
        raise ValueError(
            f"{distribution_name} distribution does not contain "
            "the expected nine-class taxonomy.\n"
            f"Expected: {sorted(expected_final_classes)}\n"
            f"Observed: {sorted(observed_classes)}"
        )

print("\n[TAXONOMY VALIDATION]")
print("✓ Training distribution contains all nine final classes")
print("✓ Validation distribution contains all nine final classes")
print("✓ Independent test distribution contains all nine final classes")
print("✓ Final taxonomy remains unchanged")


# ------------------------------------------------------------
# 4.8.6.4 Partition Row-Count Validation
# ------------------------------------------------------------

training_count = int(
    training_distribution["TrainingCount"].sum()
)

validation_count = int(
    validation_distribution["ValidationCount"].sum()
)

test_count = int(
    test_distribution["TestCount"].sum()
)

expected_training_rows = 1_814_018
expected_validation_rows = 451_215
expected_test_rows = 565_510

if training_count != expected_training_rows:
    raise ValueError(
        f"Training distribution total mismatch: "
        f"{training_count:,} != {expected_training_rows:,}"
    )

if validation_count != expected_validation_rows:
    raise ValueError(
        f"Validation distribution total mismatch: "
        f"{validation_count:,} != {expected_validation_rows:,}"
    )

if test_count != expected_test_rows:
    raise ValueError(
        f"Test distribution total mismatch: "
        f"{test_count:,} != {expected_test_rows:,}"
    )

print("\n[PARTITION COUNT VALIDATION]")
print(f"✓ Training class counts sum to {training_count:,}")
print(f"✓ Validation class counts sum to {validation_count:,}")
print(f"✓ Test class counts sum to {test_count:,}")


# ------------------------------------------------------------
# 4.8.6.5 Class-Presence Validation
# ------------------------------------------------------------

training_present = set(
    training_distribution.loc[
        training_distribution["TrainingCount"] > 0,
        "FinalTarget"
    ].astype(int)
)

validation_present = set(
    validation_distribution.loc[
        validation_distribution["ValidationCount"] > 0,
        "FinalTarget"
    ].astype(int)
)

test_present = set(
    test_distribution.loc[
        test_distribution["TestCount"] > 0,
        "FinalTarget"
    ].astype(int)
)

if training_present != expected_final_classes:
    raise ValueError(
        "Not all final classes are present in training."
    )

if validation_present != expected_final_classes:
    raise ValueError(
        "Not all final classes are present in validation."
    )

if test_present != expected_final_classes:
    raise ValueError(
        "Not all final classes are present in the independent test set."
    )

print("\n[CLASS PRESENCE VALIDATION]")
print("✓ All nine final classes have training observations")
print("✓ All nine final classes have validation observations")
print("✓ All nine final classes have independent test observations")


# ------------------------------------------------------------
# 4.8.6.6 Imbalance Analysis Integrity
# ------------------------------------------------------------

if minority_support_analysis.empty:
    raise ValueError(
        "Minority-support analysis artifact is empty."
    )

if class_imbalance_summary.empty:
    raise ValueError(
        "Class-imbalance summary artifact is empty."
    )

print("\n[IMBALANCE ANALYSIS VALIDATION]")
print("✓ Class-imbalance summary contains persisted findings")
print("✓ Minority-support analysis contains persisted findings")
print("✓ No resampling performed during persistence")
print("✓ No class weighting performed during persistence")
print("✓ No labels modified")
print("✓ No partition indices modified")
print("✓ No feature values modified")
print("✓ No model fitting performed")


# ------------------------------------------------------------
# 4.8.6.7 Evaluation Boundary Confirmation
# ------------------------------------------------------------

print("\n[EVALUATION BOUNDARY]")

print("✓ Training distribution used for imbalance characterization")
print("✓ Validation distribution retained for downstream strategy comparison")
print("✓ Independent test distribution retained without balancing")
print("✓ Independent test partition remains untouched")
print("✓ Class-imbalance analysis introduces no synthetic observations")
print("✓ Downstream imbalance strategies remain separate from this analysis")


# ------------------------------------------------------------
# 4.8.6.8 Final Artifact Manifest
# ------------------------------------------------------------

print("\n[FINAL CLASS-IMBALANCE ARTIFACTS]")

for artifact_path in required_class_imbalance_artifacts:
    print(f"✓ {artifact_path}")


# ------------------------------------------------------------
# 4.8.6.9 Final Validation
# ------------------------------------------------------------

print("\n[FINAL VALIDATION]")

print("✓ All required class-imbalance artifacts persisted")
print("✓ All three partition distributions reload successfully")
print("✓ Nine-class taxonomy preserved")
print("✓ Training row count preserved")
print("✓ Validation row count preserved")
print("✓ Independent test row count preserved")
print("✓ Minority-support findings preserved")
print("✓ Imbalance severity findings preserved")
print("✓ Evaluation boundary preserved")
print("✓ No resampling performed")
print("✓ No class weighting performed")
print("✓ No labels modified")
print("✓ No partition indices modified")
print("✓ No feature values modified")
print("✓ No model fitting performed")


print("\n" + "=" * 72)
print(
    "4.8.6 class-imbalance analysis persistence "
    "completed successfully."
)
print("=" * 72)

========================================================================
4.8.6 — CLASS-IMBALANCE ANALYSIS PERSISTENCE
========================================================================

[PERSISTED ARTIFACT CHECK]
✓ Training class distribution found
✓ Validation class distribution found
✓ Test class distribution found
✓ Class-imbalance summary found
✓ Minority-support analysis found
✓ Imbalance-severity metadata found

[TAXONOMY VALIDATION]
✓ Training distribution contains all nine final classes
✓ Validation distribution contains all nine final classes
✓ Independent test distribution contains all nine final classes
✓ Final taxonomy remains unchanged

[PARTITION COUNT VALIDATION]
✓ Training class counts sum to 1,814,018
✓ Validation class counts sum to 451,215
✓ Test class counts sum to 565,510

[CLASS PRESENCE VALIDATION]
✓ All nine final classes have training observations
✓ All nine final classes have validation observations
✓ All nine final classes have independent test observations

[IMBALANCE ANALYSIS VALIDATION]
✓ Class-imbalance summary contains persisted findings
✓ Minority-support analysis contains persisted findings
✓ No resampling performed during persistence
✓ No class weighting performed during persistence
✓ No labels modified
✓ No partition indices modified
✓ No feature values modified
✓ No model fitting performed

[EVALUATION BOUNDARY]
✓ Training distribution used for imbalance characterization
✓ Validation distribution retained for downstream strategy comparison
✓ Independent test distribution retained without balancing
✓ Independent test partition remains untouched
✓ Class-imbalance analysis introduces no synthetic observations
✓ Downstream imbalance strategies remain separate from this analysis

[FINAL CLASS-IMBALANCE ARTIFACTS]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/class_imbalance/training_only_class_distribution.csv
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/class_imbalance/validation_class_distribution.csv
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/class_imbalance/test_class_distribution.csv
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/class_imbalance/class_imbalance_summary.csv
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/class_imbalance/minority_support_analysis.csv
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/class_imbalance/class_imbalance_severity_metadata.json

[FINAL VALIDATION]
✓ All required class-imbalance artifacts persisted
✓ All three partition distributions reload successfully
✓ Nine-class taxonomy preserved
✓ Training row count preserved
✓ Validation row count preserved
✓ Independent test row count preserved
✓ Minority-support findings preserved
✓ Imbalance severity findings preserved
✓ Evaluation boundary preserved
✓ No resampling performed
✓ No class weighting performed
✓ No labels modified
✓ No partition indices modified
✓ No feature values modified
✓ No model fitting performed

========================================================================
4.8.6 class-imbalance analysis persistence completed successfully.
========================================================================

# 4.9 — Downstream Imbalance Experiment Design

This section defines the controlled imbalance-handling experiments that will be
investigated separately for the Random Forest and LSTM model pipelines.

The experiments are designed using the final model-ready representation,
leakage-controlled Training, Validation, and independent Test partitions, and
the class-support findings established in Section 4.8.

Candidate imbalance strategies may include:

- natural training distribution as a baseline,
- class-weighted learning,
- controlled random oversampling,
- controlled SMOTE-based sampling,
- sequence-aware sampling or oversampling for the LSTM pipeline,
- and additional imbalance methods only when justified by experimental
  evidence.

The Random Forest and LSTM pipelines are treated separately because their
training mechanisms and data structures differ. In particular, tabular
resampling methods must not be applied blindly to temporal sequences.

Only the Training partition may be modified by an imbalance strategy.
Validation data will be used to compare candidate strategies, while the
independent Test partition will remain untouched until final evaluation.

No imbalance strategy is declared optimal at this stage. The downstream
experiments will determine the effect of each candidate strategy using
macro-averaged and class-wise performance measures, minority-class support,
false-positive behaviour, and computational considerations.

All candidate strategies and evaluation boundaries are persisted so that
the subsequent Random Forest and LSTM experiments follow the same
reproducible experimental protocol.

# 4.9.1 — Experiment Configuration & Evaluation Boundary

This subsection establishes the experimental boundary for downstream
class-imbalance experiments.

The final nine-class taxonomy and the Training, Validation, and independent
Test partitions established earlier in the notebook are retained unchanged.

The Training partition is the only partition eligible for imbalance
modification. Candidate strategies may alter the effective training
distribution through class weighting, controlled oversampling, or controlled
synthetic sampling.

The Validation partition is reserved for comparing candidate strategies and
must retain its original class distribution.

The independent Test partition is strictly evaluation-only. It must not be
resampled, oversampled, undersampled, used to calculate sampling parameters,
or used to select an imbalance strategy.

Random Forest and LSTM experiments are defined separately. Tabular imbalance
methods may be evaluated for Random Forest, whereas LSTM experiments must
respect the sequence structure used by the downstream model.

The extremely low-support classes identified in Section 4.8 are not treated
as having sufficient evidence merely because synthetic samples can be
generated. Any strategy involving synthetic sampling must therefore be
evaluated together with class-wise metrics and original empirical support.

This subsection performs configuration and persistence only. It does not
load the model-ready feature arrays, create resampled datasets, modify
partition indices, or fit any model.

RAM-conscious execution is required throughout the downstream experiments:
large resampled arrays should be created only inside the specific experiment
that requires them, processed in controlled chunks where appropriate, and
released after each experiment rather than keeping multiple experimental
datasets in memory simultaneously.

No strategy is declared optimal at this stage.

In [30]:
# ============================================================
# 4.9.1 — EXPERIMENT CONFIGURATION & EVALUATION BOUNDARY
# ============================================================

import json

print("=" * 72)
print("4.9.1 — EXPERIMENT CONFIGURATION & EVALUATION BOUNDARY")
print("=" * 72)


# ------------------------------------------------------------
# 4.9.1.1 Validate Existing Notebook State
# ------------------------------------------------------------

required_existing_state = [
    "MODEL_PREPARATION_V2_DIR",
    "RANDOM_SEED",
    "FINAL_CLASS_ID_MAPPING",
    "REQUIRED_PARTITION_ARTIFACTS",
    "training_indices",
    "validation_indices",
    "test_indices",
    "CLASS_IMBALANCE_DIR"
]

missing_state = [
    name
    for name in required_existing_state
    if name not in globals()
]

if missing_state:
    raise NameError(
        "Required existing N04 state is missing:\n"
        + "\n".join(
            f"  - {name}"
            for name in missing_state
        )
        + "\n\nRecover the persisted N04 state before "
          "running Section 4.9.1."
    )


print("\n[EXISTING N04 STATE]")

print("✓ Model-preparation output directory available")
print("✓ Random seed available")
print("✓ Final taxonomy available")
print("✓ Partition artifact registry available")
print("✓ Training partition available")
print("✓ Validation partition available")
print("✓ Independent test partition available")
print("✓ Class-imbalance artifact directory available")


# ------------------------------------------------------------
# 4.9.1.2 Establish Downstream Experiment Directory
# ------------------------------------------------------------

DOWNSTREAM_IMBALANCE_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "downstream_imbalance_experiments"
)

DOWNSTREAM_IMBALANCE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ------------------------------------------------------------
# 4.9.1.3 Validate Partition Artifact References
# ------------------------------------------------------------

required_partition_names = [
    "training_indices",
    "validation_indices",
    "test_indices"
]

for partition_name in required_partition_names:

    if partition_name not in REQUIRED_PARTITION_ARTIFACTS:
        raise ValueError(
            f"Partition artifact '{partition_name}' "
            "is not registered in the existing N04 state."
        )

    partition_path = (
        REQUIRED_PARTITION_ARTIFACTS[
            partition_name
        ]
    )

    if not partition_path.is_file():
        raise FileNotFoundError(
            f"Required partition artifact is missing:\n"
            f"{partition_path}"
        )


print("\n[PARTITION ARTIFACTS]")

print(
    f"✓ Training indices : "
    f"{REQUIRED_PARTITION_ARTIFACTS['training_indices'].name}"
)

print(
    f"✓ Validation indices : "
    f"{REQUIRED_PARTITION_ARTIFACTS['validation_indices'].name}"
)

print(
    f"✓ Test indices : "
    f"{REQUIRED_PARTITION_ARTIFACTS['test_indices'].name}"
)


# ------------------------------------------------------------
# 4.9.1.4 Establish Experimental Partition Boundary
# ------------------------------------------------------------

experiment_partition_boundary = {

    "training_partition": {
        "purpose":
            "Model fitting and imbalance-strategy application",

        "imbalance_modification_allowed":
            True,

        "used_for_strategy_comparison":
            False
    },

    "validation_partition": {
        "purpose":
            "Comparison of candidate imbalance strategies",

        "imbalance_modification_allowed":
            False,

        "used_for_strategy_comparison":
            True
    },

    "test_partition": {
        "purpose":
            "Final independent model evaluation",

        "imbalance_modification_allowed":
            False,

        "used_for_strategy_comparison":
            False,

        "used_for_strategy_selection":
            False
    }
}


# ------------------------------------------------------------
# 4.9.1.5 Define Candidate Random Forest Strategies
# ------------------------------------------------------------

random_forest_experiments = {

    "RF-0": {
        "strategy":
            "Natural training distribution",

        "method":
            "none",

        "training_distribution_modified":
            False,

        "synthetic_samples_allowed":
            False,

        "status":
            "candidate baseline"
    },

    "RF-1": {
        "strategy":
            "Class-weighted learning",

        "method":
            "balanced class weighting",

        "training_distribution_modified":
            False,

        "synthetic_samples_allowed":
            False,

        "status":
            "candidate"
    },

    "RF-2": {
        "strategy":
            "Balanced-subset class weighting",

        "method":
            "balanced_subsample class weighting",

        "training_distribution_modified":
            False,

        "synthetic_samples_allowed":
            False,

        "status":
            "candidate"
    },

    "RF-3": {
        "strategy":
            "Controlled random oversampling",

        "method":
            "random oversampling",

        "training_distribution_modified":
            True,

        "synthetic_samples_allowed":
            False,

        "status":
            "candidate"
    },

    "RF-4": {
        "strategy":
            "Controlled SMOTE",

        "method":
            "SMOTE",

        "training_distribution_modified":
            True,

        "synthetic_samples_allowed":
            True,

        "status":
            "candidate; support constraints required"
    }
}


# ------------------------------------------------------------
# 4.9.1.6 Define Candidate LSTM Strategies
# ------------------------------------------------------------

lstm_experiments = {

    "LSTM-0": {
        "strategy":
            "Natural sequence distribution",

        "method":
            "none",

        "training_distribution_modified":
            False,

        "synthetic_sequences_allowed":
            False,

        "status":
            "candidate baseline"
    },

    "LSTM-1": {
        "strategy":
            "Class-weighted loss",

        "method":
            "weighted training loss",

        "training_distribution_modified":
            False,

        "synthetic_sequences_allowed":
            False,

        "status":
            "candidate"
    },

    "LSTM-2": {
        "strategy":
            "Balanced sequence sampling",

        "method":
            "sequence-level sampling",

        "training_distribution_modified":
            False,

        "synthetic_sequences_allowed":
            False,

        "status":
            "candidate"
    },

    "LSTM-3": {
        "strategy":
            "Controlled sequence oversampling",

        "method":
            "complete-sequence oversampling",

        "training_distribution_modified":
            True,

        "synthetic_sequences_allowed":
            False,

        "status":
            "candidate"
    },

    "LSTM-4": {
        "strategy":
            "Sequence-compatible synthetic sampling",

        "method":
            "SMOTE-based experimental branch",

        "training_distribution_modified":
            True,

        "synthetic_sequences_allowed":
            True,

        "status":
            "conditional candidate; sequence integrity required"
    }
}


# ------------------------------------------------------------
# 4.9.1.7 Establish Common Experimental Rules
# ------------------------------------------------------------

common_experiment_rules = {

    "random_seed":
        int(RANDOM_SEED),

    "final_class_count":
        int(len(FINAL_CLASS_ID_MAPPING)),

    "training_only_for_resampling":
        True,

    "validation_distribution_untouched":
        True,

    "independent_test_distribution_untouched":
        True,

    "test_used_for_strategy_selection":
        False,

    "test_used_for_hyperparameter_selection":
        False,

    "test_used_for_resampling":
        False,

    "multiple_resampled_datasets_kept_in_memory":
        False,

    "model_ready_feature_arrays_loaded_in_4_9_1":
        False,

    "resampling_performed_in_4_9_1":
        False,

    "model_fitting_performed_in_4_9_1":
        False,

    "optimal_strategy_declared":
        False
}


# ------------------------------------------------------------
# 4.9.1.8 RAM-Conscious Experiment Rules
# ------------------------------------------------------------

ram_execution_rules = {

    "load_full_model_ready_arrays_in_configuration":
        False,

    "create_resampled_data_only_inside_experiment":
        True,

    "retain_only_one_large_experimental_dataset":
        True,

    "release_experimental_arrays_after_each_run":
        True,

    "use_chunked_processing_when_supported":
        True,

    "avoid_parallel_full_dataset_copies":
        True,

    "avoid_simultaneous_rf_and_lstm_resampled_datasets":
        True,

    "restart_recovery_from_persisted_artifacts":
        True
}


# ------------------------------------------------------------
# 4.9.1.9 Build Experiment Configuration
# ------------------------------------------------------------

DOWNSTREAM_IMBALANCE_EXPERIMENT_CONFIGURATION = {

    "section":
        "4.9",

    "subsection":
        "4.9.1",

    "title":
        "Experiment Configuration & Evaluation Boundary",

    "taxonomy": {
        "class_count":
            int(len(FINAL_CLASS_ID_MAPPING)),

        "class_id_mapping":
            {
                str(class_id): str(class_name)
                for class_name, class_id
                in FINAL_CLASS_ID_MAPPING.items()
            }
    },

    "partition_sizes": {
        "training":
            int(len(training_indices)),

        "validation":
            int(len(validation_indices)),

        "test":
            int(len(test_indices))
    },

    "partition_boundary":
        experiment_partition_boundary,

    "random_forest_candidates":
        random_forest_experiments,

    "lstm_candidates":
        lstm_experiments,

    "common_experiment_rules":
        common_experiment_rules,

    "ram_execution_rules":
        ram_execution_rules,

    "partition_artifacts": {
        "training_indices":
            str(
                REQUIRED_PARTITION_ARTIFACTS[
                    "training_indices"
                ]
            ),

        "validation_indices":
            str(
                REQUIRED_PARTITION_ARTIFACTS[
                    "validation_indices"
                ]
            ),

        "test_indices":
            str(
                REQUIRED_PARTITION_ARTIFACTS[
                    "test_indices"
                ]
            )
    }
}


# ------------------------------------------------------------
# 4.9.1.10 Persist Configuration
# ------------------------------------------------------------

DOWNSTREAM_IMBALANCE_CONFIGURATION_PATH = (
    DOWNSTREAM_IMBALANCE_DIR /
    "downstream_imbalance_experiment_configuration.json"
)

with open(
    DOWNSTREAM_IMBALANCE_CONFIGURATION_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        DOWNSTREAM_IMBALANCE_EXPERIMENT_CONFIGURATION,
        f,
        indent=2
    )


# ------------------------------------------------------------
# 4.9.1.11 Final Validation
# ------------------------------------------------------------

print("\n[EXPERIMENTAL BOUNDARY]")

print("✓ Training is the only partition eligible for imbalance modification")
print("✓ Validation remains in its natural distribution")
print("✓ Validation is reserved for candidate-strategy comparison")
print("✓ Independent Test remains untouched")
print("✓ Test data cannot be used for strategy selection")
print("✓ Random Forest and LSTM strategies are defined separately")
print("✓ No strategy is declared optimal")
print("✓ No resampling performed")
print("✓ No model fitting performed")
print("✓ No model-ready feature arrays loaded")
print("✓ RAM-conscious execution rules established")


print("\n[CANDIDATE STRATEGIES]")

print(
    f"Random Forest candidates : "
    f"{len(random_forest_experiments)}"
)

print(
    f"LSTM candidates          : "
    f"{len(lstm_experiments)}"
)


print("\n[ARTIFACT]")

print(
    f"✓ Experiment configuration persisted:\n"
    f"{DOWNSTREAM_IMBALANCE_CONFIGURATION_PATH}"
)


print("\n" + "=" * 72)
print(
    "4.9.1 experiment configuration and "
    "evaluation boundary established successfully."
)
print("=" * 72)

========================================================================
4.9.1 — EXPERIMENT CONFIGURATION & EVALUATION BOUNDARY
========================================================================

[EXISTING N04 STATE]
✓ Model-preparation output directory available
✓ Random seed available
✓ Final taxonomy available
✓ Partition artifact registry available
✓ Training partition available
✓ Validation partition available
✓ Independent test partition available
✓ Class-imbalance artifact directory available

[PARTITION ARTIFACTS]
✓ Training indices : training_indices.npy
✓ Validation indices : validation_indices.npy
✓ Test indices : test_indices.npy

[EXPERIMENTAL BOUNDARY]
✓ Training is the only partition eligible for imbalance modification
✓ Validation remains in its natural distribution
✓ Validation is reserved for candidate-strategy comparison
✓ Independent Test remains untouched
✓ Test data cannot be used for strategy selection
✓ Random Forest and LSTM strategies are defined separately
✓ No strategy is declared optimal
✓ No resampling performed
✓ No model fitting performed
✓ No model-ready feature arrays loaded
✓ RAM-conscious execution rules established

[CANDIDATE STRATEGIES]
Random Forest candidates : 5
LSTM candidates          : 5

[ARTIFACT]
✓ Experiment configuration persisted:
/content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/downstream_imbalance_experiments/downstream_imbalance_experiment_configuration.json

========================================================================
4.9.1 experiment configuration and evaluation boundary established successfully.
========================================================================

## 4.9.2 — Random Forest Imbalance Strategy Design

This subsection defines the controlled class-imbalance strategies to be
investigated for the Random Forest pipeline.

The Random Forest experiments use the final scaled feature representation
and the persisted Training, Validation, and independent Test partitions
established in the preceding sections.

The following candidate strategies are evaluated separately:

1. Natural training distribution as the unmodified baseline.
2. Class-weighted Random Forest using balanced class weights.
3. Class-weighted Random Forest using balanced-subsample weighting.
4. Controlled random oversampling of eligible minority classes.
5. Controlled SMOTE-based oversampling of eligible minority classes.

The natural-distribution experiment establishes the reference performance
without changing the empirical Training distribution.

Class-weighted experiments retain the original Training observations and
modify only the contribution of classes during Random Forest learning.

For controlled oversampling experiments, the Training distribution may be
modified, but the Validation and independent Test partitions remain
completely untouched.

Synthetic sampling is subject to minimum-support constraints. Extremely
low-support classes are not automatically expanded through synthetic
generation. In particular, classes with fewer than 10 Training observations
are excluded from synthetic sampling because generating large numbers of
synthetic observations from extremely small empirical samples would provide
limited independent evidence and may produce misleading model performance.

For the controlled oversampling experiments, the target distribution is
bounded rather than forcing every class to match the majority class. This
prevents the 80% BENIGN majority class from producing unnecessarily large
resampled datasets and keeps the experiments computationally tractable.

A moderate controlled target is used for the initial experiment design:
eligible minority classes may be increased up to five times their original
Training support, subject to a maximum target count of 50,000 observations
per class. Classes already above this bound are not reduced.

This subsection defines the experimental protocol only. No Random Forest is
trained, no resampled dataset is created, and no imbalance strategy is
declared optimal.

Each candidate strategy will later be evaluated on the same untouched
Validation partition using macro-averaged metrics, per-class recall and F1,
false-positive behaviour, and computational cost. The independent Test
partition will remain reserved for final evaluation after the strategy and
model configuration have been selected.

In [31]:
# ============================================================
# 4.9.2 — RANDOM FOREST IMBALANCE STRATEGY DESIGN
# ============================================================

import json

print("=" * 72)
print("4.9.2 — RANDOM FOREST IMBALANCE STRATEGY DESIGN")
print("=" * 72)


# ------------------------------------------------------------
# 4.9.2.1 Validate Existing Experiment Configuration
# ------------------------------------------------------------

required_rf_design_state = [
    "DOWNSTREAM_IMBALANCE_DIR",
    "DOWNSTREAM_IMBALANCE_EXPERIMENT_CONFIGURATION",
    "FINAL_CLASS_ID_MAPPING",
    "RANDOM_SEED"
]

missing_rf_design_state = [
    name
    for name in required_rf_design_state
    if name not in globals()
]

if missing_rf_design_state:
    raise NameError(
        "Required existing Section 4.9 state is missing:\n"
        + "\n".join(
            f"  - {name}"
            for name in missing_rf_design_state
        )
        + "\n\nRun 4.9.1 before running 4.9.2."
    )


print("\n[EXISTING EXPERIMENT CONFIGURATION]")
print("✓ Downstream imbalance experiment directory available")
print("✓ Section 4.9 experimental configuration available")
print("✓ Final nine-class taxonomy available")
print("✓ Random seed available")


# ------------------------------------------------------------
# 4.9.2.2 Define RF Synthetic-Sampling Support Rules
# ------------------------------------------------------------

RF_SYNTHETIC_MIN_SUPPORT = 10
RF_CONTROLLED_OVERSAMPLING_MULTIPLIER = 5
RF_CONTROLLED_OVERSAMPLING_CAP = 50_000


print("\n[SYNTHETIC-SAMPLING RULES]")

print(
    f"Minimum Training support for synthetic sampling : "
    f"{RF_SYNTHETIC_MIN_SUPPORT}"
)

print(
    f"Controlled oversampling multiplier               : "
    f"{RF_CONTROLLED_OVERSAMPLING_MULTIPLIER}x"
)

print(
    f"Maximum target observations per class           : "
    f"{RF_CONTROLLED_OVERSAMPLING_CAP:,}"
)


# ------------------------------------------------------------
# 4.9.2.3 Define Candidate Random Forest Experiments
# ------------------------------------------------------------

rf_strategy_design = {

    "RF-0": {
        "name":
            "Natural Distribution Baseline",

        "strategy_type":
            "baseline",

        "class_weight":
            None,

        "sampling":
            "none",

        "synthetic_generation":
            False,

        "training_distribution_modified":
            False,

        "purpose":
            "Reference performance under the natural Training distribution"
    },

    "RF-1": {
        "name":
            "Balanced Class Weighting",

        "strategy_type":
            "class_weighting",

        "class_weight":
            "balanced",

        "sampling":
            "none",

        "synthetic_generation":
            False,

        "training_distribution_modified":
            False,

        "purpose":
            "Increase the learning contribution of minority classes without creating new observations"
    },

    "RF-2": {
        "name":
            "Balanced-Subsample Class Weighting",

        "strategy_type":
            "class_weighting",

        "class_weight":
            "balanced_subsample",

        "sampling":
            "none",

        "synthetic_generation":
            False,

        "training_distribution_modified":
            False,

        "purpose":
            "Evaluate class weighting recalculated for individual bootstrap samples"
    },

    "RF-3": {
        "name":
            "Controlled Random Oversampling",

        "strategy_type":
            "random_oversampling",

        "class_weight":
            None,

        "sampling":
            "controlled_random_oversampling",

        "synthetic_generation":
            False,

        "training_distribution_modified":
            True,

        "minimum_source_support":
            RF_SYNTHETIC_MIN_SUPPORT,

        "target_rule":
            (
                "target_count = min("
                "original_count * "
                f"{RF_CONTROLLED_OVERSAMPLING_MULTIPLIER}, "
                f"{RF_CONTROLLED_OVERSAMPLING_CAP}"
                ")"
            ),

        "purpose":
            "Evaluate moderate replication of eligible minority observations"
    },

    "RF-4": {
        "name":
            "Controlled SMOTE",

        "strategy_type":
            "synthetic_oversampling",

        "class_weight":
            None,

        "sampling":
            "controlled_smote",

        "synthetic_generation":
            True,

        "training_distribution_modified":
            True,

        "minimum_source_support":
            RF_SYNTHETIC_MIN_SUPPORT,

        "target_rule":
            (
                "target_count = min("
                "original_count * "
                f"{RF_CONTROLLED_OVERSAMPLING_MULTIPLIER}, "
                f"{RF_CONTROLLED_OVERSAMPLING_CAP}"
                ")"
            ),

        "purpose":
            "Evaluate controlled synthetic minority generation under the same bounded target rule"
    }
}


# ------------------------------------------------------------
# 4.9.2.4 Define Classes Excluded from Synthetic Generation
# ------------------------------------------------------------

rf_synthetic_sampling_exclusion_rule = {

    "rule":
        (
            "Classes with fewer than "
            f"{RF_SYNTHETIC_MIN_SUPPORT} Training observations "
            "are excluded from synthetic oversampling."
        ),

    "reason":
        (
            "Extremely small empirical support does not provide "
            "sufficient observations for defensible synthetic "
            "minority generation."
        ),

    "current_known_classes": {
        "Heartbleed":
            {
                "training_support":
                    6,

                "synthetic_sampling":
                    "excluded"
            },

        "Infiltration":
            {
                "training_support":
                    15,

                "synthetic_sampling":
                    "eligible"
            }
    }
}


# ------------------------------------------------------------
# 4.9.2.5 Define Validation and Test Boundary
# ------------------------------------------------------------

rf_evaluation_boundary = {

    "training": {
        "imbalance_strategy_allowed":
            True,

        "sampling_allowed":
            True,

        "model_fitting_allowed":
            True
    },

    "validation": {
        "imbalance_strategy_allowed":
            False,

        "sampling_allowed":
            False,

        "used_for_candidate_comparison":
            True,

        "used_for_resampling":
            False
    },

    "test": {
        "imbalance_strategy_allowed":
            False,

        "sampling_allowed":
            False,

        "used_for_candidate_comparison":
            False,

        "used_for_strategy_selection":
            False,

        "used_for_final_evaluation":
            True
    }
}


# ------------------------------------------------------------
# 4.9.2.6 Define RF Comparison Criteria
# ------------------------------------------------------------

rf_comparison_criteria = {

    "primary": [
        "macro_f1",
        "macro_recall",
        "minority_class_recall"
    ],

    "secondary": [
        "weighted_f1",
        "accuracy",
        "per_class_f1",
        "per_class_recall",
        "false_positive_rate",
        "training_time",
        "prediction_time"
    ],

    "diagnostic": [
        "confusion_matrix",
        "class_support",
        "validation_class_distribution",
        "computational_memory_requirement"
    ],

    "interpretation_rule":
        (
            "Accuracy must not be interpreted independently because "
            "the final Training distribution is extremely imbalanced."
        )
}


# ------------------------------------------------------------
# 4.9.2.7 RAM-Conscious RF Experiment Rules
# ------------------------------------------------------------

rf_ram_rules = {

    "load_training_data_only_when_experiment_starts":
        True,

    "validation_loaded_for_model_evaluation_only":
        True,

    "test_loaded_only_for_final_evaluation":
        True,

    "create_only_one_resampled_training_dataset_at_a_time":
        True,

    "persist_experiment_result_before_next_experiment":
        True,

    "release_resampled_dataset_after_experiment":
        True,

    "avoid_simultaneous_ros_and_smote_datasets":
        True,

    "avoid_full_majority_class_replication":
        True,

    "synthetic_sampling_bounded":
        True,

    "synthetic_sampling_minimum_support_enforced":
        True
}


# ------------------------------------------------------------
# 4.9.2.8 Build RF Strategy Design Artifact
# ------------------------------------------------------------

RANDOM_FOREST_IMBALANCE_STRATEGY_DESIGN = {

    "section":
        "4.9",

    "subsection":
        "4.9.2",

    "title":
        "Random Forest Imbalance Strategy Design",

    "random_seed":
        int(RANDOM_SEED),

    "strategy_count":
        len(rf_strategy_design),

    "strategies":
        rf_strategy_design,

    "synthetic_sampling_exclusion_rule":
        rf_synthetic_sampling_exclusion_rule,

    "evaluation_boundary":
        rf_evaluation_boundary,

    "comparison_criteria":
        rf_comparison_criteria,

    "ram_execution_rules":
        rf_ram_rules,

    "strategy_selection":
        {
            "optimal_strategy_declared":
                False,

            "test_data_used_for_selection":
                False
        }
}


# ------------------------------------------------------------
# 4.9.2.9 Persist RF Strategy Design
# ------------------------------------------------------------

RANDOM_FOREST_IMBALANCE_STRATEGY_DESIGN_PATH = (
    DOWNSTREAM_IMBALANCE_DIR /
    "random_forest_imbalance_strategy_design.json"
)

with open(
    RANDOM_FOREST_IMBALANCE_STRATEGY_DESIGN_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        RANDOM_FOREST_IMBALANCE_STRATEGY_DESIGN,
        f,
        indent=2
    )


# ------------------------------------------------------------
# 4.9.2.10 Final Validation
# ------------------------------------------------------------

print("\n[RF STRATEGY MATRIX]")

for strategy_id, strategy in rf_strategy_design.items():

    print(
        f"  {strategy_id} : "
        f"{strategy['name']}"
    )


print("\n[RF EXPERIMENT BOUNDARY]")

print("✓ Only Training data may be modified")
print("✓ Validation remains untouched")
print("✓ Independent Test remains untouched")
print("✓ Natural-distribution baseline included")
print("✓ Balanced class weighting included")
print("✓ Balanced-subsample weighting included")
print("✓ Controlled random oversampling included")
print("✓ Controlled SMOTE included")
print("✓ Synthetic sampling has a minimum-support rule")
print("✓ Synthetic sampling has a bounded target")
print("✓ No majority-class matching is required")
print("✓ No RF model fitted")
print("✓ No training array loaded")
print("✓ No resampled dataset created")
print("✓ No strategy declared optimal")


print("\n[ARTIFACT]")

print(
    "✓ RF imbalance strategy design persisted:"
)

print(
    f"{RANDOM_FOREST_IMBALANCE_STRATEGY_DESIGN_PATH}"
)


print("\n" + "=" * 72)
print(
    "4.9.2 Random Forest imbalance strategy design "
    "completed successfully."
)
print("=" * 72)

========================================================================
4.9.2 — RANDOM FOREST IMBALANCE STRATEGY DESIGN
========================================================================

[EXISTING EXPERIMENT CONFIGURATION]
✓ Downstream imbalance experiment directory available
✓ Section 4.9 experimental configuration available
✓ Final nine-class taxonomy available
✓ Random seed available

[SYNTHETIC-SAMPLING RULES]
Minimum Training support for synthetic sampling : 10
Controlled oversampling multiplier               : 5x
Maximum target observations per class           : 50,000

[RF STRATEGY MATRIX]
  RF-0 : Natural Distribution Baseline
  RF-1 : Balanced Class Weighting
  RF-2 : Balanced-Subsample Class Weighting
  RF-3 : Controlled Random Oversampling
  RF-4 : Controlled SMOTE

[RF EXPERIMENT BOUNDARY]
✓ Only Training data may be modified
✓ Validation remains untouched
✓ Independent Test remains untouched
✓ Natural-distribution baseline included
✓ Balanced class weighting included
✓ Balanced-subsample weighting included
✓ Controlled random oversampling included
✓ Controlled SMOTE included
✓ Synthetic sampling has a minimum-support rule
✓ Synthetic sampling has a bounded target
✓ No majority-class matching is required
✓ No RF model fitted
✓ No training array loaded
✓ No resampled dataset created
✓ No strategy declared optimal

[ARTIFACT]
✓ RF imbalance strategy design persisted:
/content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/downstream_imbalance_experiments/random_forest_imbalance_strategy_design.json

========================================================================
4.9.2 Random Forest imbalance strategy design completed successfully.
========================================================================

## 4.9.3 — LSTM Imbalance Strategy Design

This subsection defines the controlled class-imbalance strategies to be
investigated for the LSTM pipeline.

Unlike the Random Forest pipeline, the LSTM operates on ordered packet or
flow sequences. Therefore, imbalance handling must preserve the temporal
structure and sequence boundaries used by the downstream model.

The following candidate strategies are defined:

1. Natural sequence distribution as the unmodified baseline.
2. Class-weighted LSTM loss without modifying the training sequence
   distribution.
3. Class-aware sequence sampling in which complete training sequences are
   sampled according to their target class.
4. Controlled oversampling of complete minority-class sequences.
5. A conditional synthetic-sampling experiment in which any synthetic
   observations must be incorporated into valid sequences without breaking
   sequence structure.

The natural sequence-distribution experiment establishes the reference
performance without modifying the empirical Training distribution.

Class-weighted learning changes the contribution of classes to the training
loss while retaining the original sequence observations.

Sequence-level sampling and oversampling operate on complete sequences
rather than individual rows. A sequence must not be partially duplicated,
reordered, or combined with unrelated observations solely for balancing.

Standard row-wise SMOTE is not directly applied to the final LSTM sequence
dataset. Synthetic sampling may only be investigated as a controlled
experimental branch if the resulting samples can be incorporated while
preserving the sequence construction rules. If sequence integrity cannot be
demonstrated, that branch will be excluded from LSTM selection rather than
forcing an invalid application of SMOTE.

The extremely low-support classes identified in Section 4.8 require special
treatment. In particular, Heartbleed has only six Training observations.
Synthetic sequence generation from such extremely limited empirical support
will not be treated as equivalent to obtaining additional independent
observations.

All LSTM candidate strategies use the same untouched Validation partition
for comparison and the same independent Test partition for final evaluation.

No LSTM model is trained in this subsection and no sequence dataset is
constructed. This subsection only defines the experimental design that will
be evaluated in the downstream model-training stage.

In [32]:
# ============================================================
# 4.9.3 — LSTM IMBALANCE STRATEGY DESIGN
# ============================================================

import json

print("=" * 72)
print("4.9.3 — LSTM IMBALANCE STRATEGY DESIGN")
print("=" * 72)


# ------------------------------------------------------------
# 4.9.3.1 Validate Existing Section 4.9 State
# ------------------------------------------------------------

required_lstm_design_state = [
    "DOWNSTREAM_IMBALANCE_DIR",
    "DOWNSTREAM_IMBALANCE_EXPERIMENT_CONFIGURATION",
    "RANDOM_FOREST_IMBALANCE_STRATEGY_DESIGN",
    "FINAL_CLASS_ID_MAPPING",
    "RANDOM_SEED"
]

missing_lstm_design_state = [
    name
    for name in required_lstm_design_state
    if name not in globals()
]

if missing_lstm_design_state:
    raise NameError(
        "Required Section 4.9 state is missing:\n"
        + "\n".join(
            f"  - {name}"
            for name in missing_lstm_design_state
        )
        + "\n\nRun 4.9.1 and 4.9.2 before running 4.9.3."
    )


print("\n[EXISTING EXPERIMENT CONFIGURATION]")

print("✓ Section 4.9 experiment boundary available")
print("✓ Random Forest strategy design available")
print("✓ Final nine-class taxonomy available")
print("✓ Random seed available")


# ------------------------------------------------------------
# 4.9.3.2 Define LSTM Sequence-Level Support Rules
# ------------------------------------------------------------

LSTM_SYNTHETIC_MIN_SEQUENCE_SUPPORT = 10
LSTM_CONTROLLED_OVERSAMPLING_MULTIPLIER = 5
LSTM_CONTROLLED_OVERSAMPLING_CAP = 50_000


print("\n[LSTM SEQUENCE-SAMPLING RULES]")

print(
    "Minimum sequence support for synthetic sampling : "
    f"{LSTM_SYNTHETIC_MIN_SEQUENCE_SUPPORT}"
)

print(
    "Controlled sequence oversampling multiplier     : "
    f"{LSTM_CONTROLLED_OVERSAMPLING_MULTIPLIER}x"
)

print(
    "Maximum target sequences per class              : "
    f"{LSTM_CONTROLLED_OVERSAMPLING_CAP:,}"
)


# ------------------------------------------------------------
# 4.9.3.3 Define Candidate LSTM Experiments
# ------------------------------------------------------------

lstm_strategy_design = {

    "LSTM-0": {
        "name":
            "Natural Sequence Distribution Baseline",

        "strategy_type":
            "baseline",

        "loss_weighting":
            None,

        "sequence_sampling":
            "natural",

        "sequence_oversampling":
            False,

        "synthetic_generation":
            False,

        "purpose":
            "Reference performance under the natural sequence distribution"
    },

    "LSTM-1": {
        "name":
            "Class-Weighted Loss",

        "strategy_type":
            "class_weighting",

        "loss_weighting":
            "training-class weights",

        "sequence_sampling":
            "natural",

        "sequence_oversampling":
            False,

        "synthetic_generation":
            False,

        "purpose":
            "Increase minority-class contribution to the training loss without creating additional sequences"
    },

    "LSTM-2": {
        "name":
            "Class-Aware Sequence Sampling",

        "strategy_type":
            "sequence_sampling",

        "loss_weighting":
            None,

        "sequence_sampling":
            "class-aware",

        "sequence_oversampling":
            True,

        "synthetic_generation":
            False,

        "sampling_unit":
            "complete sequence",

        "purpose":
            "Increase exposure to minority classes while preserving complete sequence structure"
    },

    "LSTM-3": {
        "name":
            "Controlled Sequence Oversampling",

        "strategy_type":
            "sequence_oversampling",

        "loss_weighting":
            None,

        "sequence_sampling":
            "controlled",

        "sequence_oversampling":
            True,

        "synthetic_generation":
            False,

        "sampling_unit":
            "complete sequence",

        "minimum_source_support":
            LSTM_SYNTHETIC_MIN_SEQUENCE_SUPPORT,

        "target_rule":
            (
                "target_sequence_count = min("
                "original_sequence_count * "
                f"{LSTM_CONTROLLED_OVERSAMPLING_MULTIPLIER}, "
                f"{LSTM_CONTROLLED_OVERSAMPLING_CAP}"
                ")"
            ),

        "purpose":
            "Evaluate bounded replication of complete minority-class sequences"
    },

    "LSTM-4": {
        "name":
            "Sequence-Preserving Synthetic Sampling",

        "strategy_type":
            "conditional_synthetic_sampling",

        "loss_weighting":
            None,

        "sequence_sampling":
            "sequence-aware synthetic branch",

        "sequence_oversampling":
            True,

        "synthetic_generation":
            True,

        "sampling_unit":
            "sequence",

        "minimum_source_support":
            LSTM_SYNTHETIC_MIN_SEQUENCE_SUPPORT,

        "method_constraint":
            (
                "Standard row-wise SMOTE must not be applied directly "
                "to the final sequence dataset. Any synthetic method "
                "must preserve the downstream sequence-construction "
                "and temporal-order rules."
            ),

        "selection_condition":
            (
                "Retain this strategy only if sequence integrity and "
                "validation behaviour are demonstrated experimentally."
            ),

        "purpose":
            "Investigate whether controlled synthetic sampling can improve minority-class sequence recognition without invalidating temporal structure"
    }
}


# ------------------------------------------------------------
# 4.9.3.4 Define Extremely Low-Support Handling
# ------------------------------------------------------------

lstm_low_support_rules = {

    "Heartbleed": {
        "training_support":
            6,

        "synthetic_sampling":
            "excluded",

        "reason":
            (
                "Extremely limited empirical support; synthetic "
                "generation cannot provide genuinely independent evidence."
            )
    },

    "Infiltration": {
        "training_support":
            15,

        "synthetic_sampling":
            "eligible_for_controlled_experiment",

        "reason":
            (
                "Above the minimum support threshold, but results "
                "must still be interpreted with class-support limitations."
            )
    }
}


print("\n[LOW-SUPPORT HANDLING]")

print(
    "✓ Heartbleed is excluded from synthetic sequence generation"
)

print(
    "✓ Infiltration may enter controlled sequence-sampling experiments"
)

print(
    "✓ Low-support classes remain part of the final nine-class problem"
)

print(
    "✓ Synthetic observations will not be interpreted as independent evidence"
)


# ------------------------------------------------------------
# 4.9.3.5 Define LSTM Evaluation Boundary
# ------------------------------------------------------------

lstm_evaluation_boundary = {

    "training": {
        "imbalance_strategy_allowed":
            True,

        "sequence_sampling_allowed":
            True,

        "sequence_oversampling_allowed":
            True,

        "synthetic_sequence_generation_allowed":
            "conditional"
    },

    "validation": {
        "imbalance_strategy_allowed":
            False,

        "sequence_sampling_allowed":
            False,

        "sequence_oversampling_allowed":
            False,

        "synthetic_sequence_generation_allowed":
            False,

        "used_for_candidate_comparison":
            True
    },

    "test": {
        "imbalance_strategy_allowed":
            False,

        "sequence_sampling_allowed":
            False,

        "sequence_oversampling_allowed":
            False,

        "synthetic_sequence_generation_allowed":
            False,

        "used_for_candidate_comparison":
            False,

        "used_for_strategy_selection":
            False,

        "used_for_final_evaluation":
            True
    }
}


# ------------------------------------------------------------
# 4.9.3.6 Define LSTM Sequence Integrity Rules
# ------------------------------------------------------------

lstm_sequence_integrity_rules = {

    "sampling_unit":
        "complete sequence",

    "partial_sequence_duplication":
        False,

    "arbitrary_row_reordering":
        False,

    "cross_class_sequence_mixing":
        False,

    "cross_partition_sequence_mixing":
        False,

    "validation_sequence_modification":
        False,

    "test_sequence_modification":
        False,

    "row_wise_smote_directly_on_final_sequences":
        False,

    "synthetic_branch_requires_sequence_validation":
        True,

    "original_sequence_construction_rule_preserved":
        True
}


# ------------------------------------------------------------
# 4.9.3.7 Define LSTM Comparison Criteria
# ------------------------------------------------------------

lstm_comparison_criteria = {

    "primary": [
        "macro_f1",
        "macro_recall",
        "minority_class_recall"
    ],

    "secondary": [
        "weighted_f1",
        "accuracy",
        "per_class_f1",
        "per_class_recall",
        "false_positive_rate",
        "training_time",
        "inference_time"
    ],

    "diagnostic": [
        "confusion_matrix",
        "class_support",
        "sequence_class_distribution",
        "validation_class_distribution",
        "memory_requirement"
    ],

    "interpretation_rule":
        (
            "Overall accuracy must not be used independently because "
            "the underlying class distribution is severely imbalanced."
        )
}


# ------------------------------------------------------------
# 4.9.3.8 RAM-Conscious LSTM Experiment Rules
# ------------------------------------------------------------

lstm_ram_rules = {

    "construct_sequences_only_when_experiment_starts":
        True,

    "create_only_one_experimental_sequence_dataset_at_a_time":
        True,

    "avoid_simultaneous_rf_and_lstm_resampled_datasets":
        True,

    "persist_experiment_result_before_next_experiment":
        True,

    "release_sequence_dataset_after_experiment":
        True,

    "avoid_full_dataset_sequence_duplication":
        True,

    "use_sequence_batches_during_model_training":
        True,

    "synthetic_sampling_bounded":
        True,

    "synthetic_sampling_minimum_support_enforced":
        True
}


# ------------------------------------------------------------
# 4.9.3.9 Build LSTM Strategy Design Artifact
# ------------------------------------------------------------

LSTM_IMBALANCE_STRATEGY_DESIGN = {

    "section":
        "4.9",

    "subsection":
        "4.9.3",

    "title":
        "LSTM Imbalance Strategy Design",

    "random_seed":
        int(RANDOM_SEED),

    "strategy_count":
        len(lstm_strategy_design),

    "strategies":
        lstm_strategy_design,

    "low_support_rules":
        lstm_low_support_rules,

    "evaluation_boundary":
        lstm_evaluation_boundary,

    "sequence_integrity_rules":
        lstm_sequence_integrity_rules,

    "comparison_criteria":
        lstm_comparison_criteria,

    "ram_execution_rules":
        lstm_ram_rules,

    "strategy_selection": {
        "optimal_strategy_declared":
            False,

        "test_data_used_for_selection":
            False
    }
}


# ------------------------------------------------------------
# 4.9.3.10 Final Validation
# ------------------------------------------------------------

print("\n[LSTM STRATEGY MATRIX]")

for strategy_id, strategy in lstm_strategy_design.items():

    print(
        f"  {strategy_id} : "
        f"{strategy['name']}"
    )


print("\n[LSTM EXPERIMENT BOUNDARY]")

print("✓ Natural sequence baseline included")
print("✓ Class-weighted loss included")
print("✓ Class-aware sequence sampling included")
print("✓ Controlled sequence oversampling included")
print("✓ Conditional synthetic sequence branch included")
print("✓ Complete sequences are the sampling unit")
print("✓ Row-wise SMOTE on final sequences is prohibited")
print("✓ Validation remains untouched")
print("✓ Independent Test remains untouched")
print("✓ Low-support constraints established")
print("✓ No LSTM model fitted")
print("✓ No sequence dataset constructed")
print("✓ No synthetic data generated")
print("✓ No strategy declared optimal")


print("\n[CONFIGURATION]")

print(
    f"LSTM candidates : "
    f"{len(lstm_strategy_design)}"
)

print(
    "Final taxonomy classes : "
    f"{len(FINAL_CLASS_ID_MAPPING)}"
)


print("\n" + "=" * 72)
print(
    "4.9.3 LSTM imbalance strategy design "
    "completed successfully."
)
print("=" * 72)

========================================================================
4.9.3 — LSTM IMBALANCE STRATEGY DESIGN
========================================================================

[EXISTING EXPERIMENT CONFIGURATION]
✓ Section 4.9 experiment boundary available
✓ Random Forest strategy design available
✓ Final nine-class taxonomy available
✓ Random seed available

[LSTM SEQUENCE-SAMPLING RULES]
Minimum sequence support for synthetic sampling : 10
Controlled sequence oversampling multiplier     : 5x
Maximum target sequences per class              : 50,000

[LOW-SUPPORT HANDLING]
✓ Heartbleed is excluded from synthetic sequence generation
✓ Infiltration may enter controlled sequence-sampling experiments
✓ Low-support classes remain part of the final nine-class problem
✓ Synthetic observations will not be interpreted as independent evidence

[LSTM STRATEGY MATRIX]
  LSTM-0 : Natural Sequence Distribution Baseline
  LSTM-1 : Class-Weighted Loss
  LSTM-2 : Class-Aware Sequence Sampling
  LSTM-3 : Controlled Sequence Oversampling
  LSTM-4 : Sequence-Preserving Synthetic Sampling

[LSTM EXPERIMENT BOUNDARY]
✓ Natural sequence baseline included
✓ Class-weighted loss included
✓ Class-aware sequence sampling included
✓ Controlled sequence oversampling included
✓ Conditional synthetic sequence branch included
✓ Complete sequences are the sampling unit
✓ Row-wise SMOTE on final sequences is prohibited
✓ Validation remains untouched
✓ Independent Test remains untouched
✓ Low-support constraints established
✓ No LSTM model fitted
✓ No sequence dataset constructed
✓ No synthetic data generated
✓ No strategy declared optimal

[CONFIGURATION]
LSTM candidates : 5
Final taxonomy classes : 9

========================================================================
4.9.3 LSTM imbalance strategy design completed successfully.
========================================================================

## 4.9.4 — Controlled Sampling & Synthetic Data Boundaries

This subsection defines the boundaries under which controlled class-imbalance experiments may modify the training data.

The purpose is to investigate whether controlled sampling improves minority-class detection without allowing synthetic or duplicated observations to contaminate validation or independent test evaluation.

The following rules apply to all downstream imbalance experiments:

- Only the training partition may be modified.
- Validation data must remain in its original natural distribution.
- The independent test partition must remain completely untouched.
- Validation and test observations must never be used to generate synthetic samples.
- No imbalance strategy is considered optimal at this stage.
- Synthetic sampling is permitted only for classes with sufficient training support.
- Classes with fewer than 10 training observations are excluded from synthetic generation.
- The controlled oversampling multiplier is limited to 5× the available training support for an eligible class.
- A maximum target of 50,000 observations per class is imposed for controlled synthetic/oversampling experiments.
- No strategy may downsample the majority class solely to obtain an apparently balanced dataset.
- Random Forest experiments may evaluate controlled row-level oversampling and controlled SMOTE.
- SMOTE is restricted to the Random Forest feature-space pipeline and must not be applied directly to LSTM sequence rows.
- LSTM imbalance experiments operate on complete sequences rather than independently sampled feature rows.
- Any LSTM synthetic strategy must preserve the sequence structure and temporal ordering assumptions of the model.
- Extremely low-support classes must remain part of the final evaluation taxonomy even when they are excluded from synthetic generation.
- Synthetic observations must never be interpreted as independent evidence in the final evaluation.
- Candidate strategies must be generated and evaluated independently rather than materializing all candidate datasets simultaneously.
- RAM-intensive datasets should be generated in chunks or through sampling indices where practical.
- Each experiment must use the same random seed policy defined for Section 4.9.
- Strategy-specific artifacts must be persisted separately so that experiments can be reproduced without rebuilding unrelated datasets.

These boundaries are intended to provide a controlled experimental framework rather than to guarantee a particular model result. The final strategy will be selected only after empirical comparison using the predefined validation criteria.

In [33]:
# ============================================================
# 4.9.4 — CONTROLLED SAMPLING & SYNTHETIC DATA BOUNDARIES
# ============================================================

import os
import json
from datetime import datetime

# Existing Section 4.9 experiment directory
EXPERIMENT_DIR = (
    "/content/drive/MyDrive/"
    "AI-Network-Intrusion-Detection-System/"
    "outputs/model_preparation_v2/downstream_imbalance_experiments"
)

os.makedirs(EXPERIMENT_DIR, exist_ok=True)

# ------------------------------------------------------------
# Controlled sampling boundaries
# ------------------------------------------------------------

SAMPLING_BOUNDARIES = {
    "section": "4.9.4",
    "title": "Controlled Sampling & Synthetic Data Boundaries",

    "evaluation_boundary": {
        "training_partition_modifiable": True,
        "validation_partition_untouched": True,
        "test_partition_untouched": True,
        "validation_used_for_synthetic_generation": False,
        "test_used_for_synthetic_generation": False,
        "synthetic_observations_considered_independent_evidence": False
    },

    "synthetic_sampling_rules": {
        "minimum_training_support_for_synthetic_sampling": 10,
        "controlled_oversampling_multiplier": 5,
        "maximum_target_observations_per_class": 50000,
        "majority_class_downsampling_allowed": False,
        "low_support_classes_retained_in_taxonomy": True
    },

    "random_forest_boundaries": {
        "row_level_oversampling_allowed": True,
        "controlled_smote_allowed": True,
        "smote_applied_to_validation": False,
        "smote_applied_to_test": False,
        "smote_applied_to_lstm_sequences": False
    },

    "lstm_boundaries": {
        "sampling_unit": "complete_sequence",
        "row_level_smote_allowed": False,
        "sequence_structure_must_be_preserved": True,
        "temporal_order_must_be_preserved": True,
        "synthetic_sequence_strategy_conditional": True
    },

    "low_support_handling": {
        "classes_below_minimum_support_excluded_from_synthetic_generation": True,
        "extremely_low_support_classes_retained_for_evaluation": True,
        "synthetic_data_not_treated_as_independent_evidence": True
    },

    "ram_safety_rules": {
        "materialize_all_candidate_datasets_simultaneously": False,
        "prefer_chunked_generation": True,
        "prefer_sampling_indices_when_possible": True,
        "persist_each_strategy_separately": True,
        "release_intermediate_memory_between_experiments": True
    },

    "experimental_controls": {
        "same_random_seed_policy": True,
        "same_validation_partition": True,
        "same_independent_test_partition": True,
        "same_feature_space": True,
        "strategy_selected_before_final_test": False
    },

    "status": {
        "synthetic_data_generated": False,
        "resampled_dataset_created": False,
        "model_fitted": False,
        "optimal_strategy_declared": False
    },

    "created_at": datetime.now().isoformat()
}

# ------------------------------------------------------------
# Persist boundary configuration
# ------------------------------------------------------------

BOUNDARY_PATH = os.path.join(
    EXPERIMENT_DIR,
    "controlled_sampling_boundaries.json"
)

with open(BOUNDARY_PATH, "w", encoding="utf-8") as f:
    json.dump(
        SAMPLING_BOUNDARIES,
        f,
        indent=2
    )

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

assert SAMPLING_BOUNDARIES["evaluation_boundary"]["training_partition_modifiable"] is True
assert SAMPLING_BOUNDARIES["evaluation_boundary"]["validation_partition_untouched"] is True
assert SAMPLING_BOUNDARIES["evaluation_boundary"]["test_partition_untouched"] is True

assert (
    SAMPLING_BOUNDARIES["synthetic_sampling_rules"]
    ["minimum_training_support_for_synthetic_sampling"]
    == 10
)

assert (
    SAMPLING_BOUNDARIES["synthetic_sampling_rules"]
    ["controlled_oversampling_multiplier"]
    == 5
)

assert (
    SAMPLING_BOUNDARIES["synthetic_sampling_rules"]
    ["maximum_target_observations_per_class"]
    == 50000
)

assert (
    SAMPLING_BOUNDARIES["random_forest_boundaries"]
    ["smote_applied_to_lstm_sequences"]
    is False
)

assert (
    SAMPLING_BOUNDARIES["lstm_boundaries"]
    ["sampling_unit"]
    == "complete_sequence"
)

assert (
    SAMPLING_BOUNDARIES["lstm_boundaries"]
    ["row_level_smote_allowed"]
    is False
)

assert os.path.exists(BOUNDARY_PATH)

# ------------------------------------------------------------
# Console summary
# ------------------------------------------------------------

print("=" * 72)
print("4.9.4 — CONTROLLED SAMPLING & SYNTHETIC DATA BOUNDARIES")
print("=" * 72)

print("\n[DATA MODIFICATION BOUNDARY]")
print("✓ Training partition may be modified")
print("✓ Validation partition remains untouched")
print("✓ Independent test partition remains untouched")

print("\n[SYNTHETIC SAMPLING LIMITS]")
print("Minimum training support :", 10)
print("Maximum oversampling     :", "5×")
print("Maximum class target     :", "50,000 observations")
print("Majority downsampling    :", "Not permitted")

print("\n[RANDOM FOREST]")
print("✓ Controlled random oversampling permitted")
print("✓ Controlled SMOTE permitted")
print("✓ SMOTE restricted to RF feature space")
print("✓ No SMOTE on validation/test")

print("\n[LSTM]")
print("✓ Complete sequences are the sampling unit")
print("✓ Sequence structure must be preserved")
print("✓ Row-level SMOTE prohibited")
print("✓ Synthetic sequence strategy remains conditional")

print("\n[LOW-SUPPORT CLASSES]")
print("✓ Classes below 10 training observations excluded from synthetic generation")
print("✓ Low-support classes remain in final evaluation taxonomy")
print("✓ Synthetic observations are not independent evidence")

print("\n[RAM SAFETY]")
print("✓ Candidate datasets will not be materialized simultaneously")
print("✓ Chunked generation preferred")
print("✓ Strategy-specific artifacts persisted separately")

print("\n[STATUS]")
print("Synthetic data generated :", False)
print("Model fitting performed  :", False)
print("Optimal strategy chosen  :", False)

print("\n[ARTIFACT]")
print(f"✓ Controlled sampling boundaries persisted:")
print(f"  {BOUNDARY_PATH}")

print("\n" + "=" * 72)
print("4.9.4 controlled sampling and synthetic data boundaries completed successfully.")
print("=" * 72)

========================================================================
4.9.4 — CONTROLLED SAMPLING & SYNTHETIC DATA BOUNDARIES
========================================================================

[DATA MODIFICATION BOUNDARY]
✓ Training partition may be modified
✓ Validation partition remains untouched
✓ Independent test partition remains untouched

[SYNTHETIC SAMPLING LIMITS]
Minimum training support : 10
Maximum oversampling     : 5×
Maximum class target     : 50,000 observations
Majority downsampling    : Not permitted

[RANDOM FOREST]
✓ Controlled random oversampling permitted
✓ Controlled SMOTE permitted
✓ SMOTE restricted to RF feature space
✓ No SMOTE on validation/test

[LSTM]
✓ Complete sequences are the sampling unit
✓ Sequence structure must be preserved
✓ Row-level SMOTE prohibited
✓ Synthetic sequence strategy remains conditional

[LOW-SUPPORT CLASSES]
✓ Classes below 10 training observations excluded from synthetic generation
✓ Low-support classes remain in final evaluation taxonomy
✓ Synthetic observations are not independent evidence

[RAM SAFETY]
✓ Candidate datasets will not be materialized simultaneously
✓ Chunked generation preferred
✓ Strategy-specific artifacts persisted separately

[STATUS]
Synthetic data generated : False
Model fitting performed  : False
Optimal strategy chosen  : False

[ARTIFACT]
✓ Controlled sampling boundaries persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/downstream_imbalance_experiments/controlled_sampling_boundaries.json

========================================================================
4.9.4 controlled sampling and synthetic data boundaries completed successfully.
========================================================================

## 4.9.5 — Experimental Evaluation Criteria

This subsection defines the evaluation criteria that will be used to compare the candidate class-imbalance strategies for Random Forest and LSTM.

Because the final dataset is highly imbalanced, overall accuracy will not be used as the sole criterion for model or strategy selection. The primary comparison will emphasize macro-averaged performance and minority-class behavior so that strong performance on the majority BENIGN class does not conceal poor detection of rare attack classes.

The evaluation boundary is defined as follows:

- The training partition may be modified according to the candidate imbalance strategy.
- The validation partition remains in its natural class distribution and is used for candidate-strategy comparison.
- The independent test partition remains completely untouched and is reserved for final evaluation after the downstream strategy and model configuration have been selected.
- The same validation partition and class taxonomy will be used when comparing candidate strategies within each model family.
- Random Forest and LSTM strategies will be compared separately because their training units and imbalance mechanisms differ.

### Primary evaluation criteria

The primary strategy-comparison criterion is:

1. **Macro F1-score** — gives equal importance to all final classes and prevents the majority class from dominating the aggregate score.

### Secondary classification criteria

The following metrics will also be reported:

2. **Macro recall / balanced accuracy** — measures class-balanced detection performance.
3. **Per-class precision, recall, and F1-score** — identifies classes that remain difficult to detect.
4. **Weighted F1-score** — reports performance while accounting for the observed class frequencies.
5. **Overall accuracy** — retained as a descriptive metric but not used alone for strategy selection.

### Error-oriented criteria

The experiments will additionally examine:

- False-positive behavior for BENIGN traffic.
- False-negative behavior for attack classes.
- Confusion between attack categories.
- Per-class support when interpreting unusually high or low metrics.

### Reliability and practical criteria

Where available, the downstream experiments will also record:

- Training time.
- Inference time or throughput.
- Memory/resource usage.
- Number of training observations produced by each sampling strategy.

These measurements will be considered alongside classification performance rather than treating a small metric improvement as automatically preferable when it requires substantially greater computational cost.

### Rare-class interpretation rule

Classes with extremely small training support will be interpreted cautiously. Synthetic or repeated observations cannot create genuinely independent evidence for a class with only a handful of original observations. Therefore, unusually high performance on extremely low-support classes will not by itself be treated as evidence of generalization.

No imbalance strategy is declared optimal in this subsection. The criteria established here will be applied consistently during the subsequent controlled experiments and strategy-comparison stage.

In [34]:
# ============================================================
# 4.9.5 — Experimental Evaluation Criteria
# ============================================================

print("=" * 72)
print("4.9.5 — EXPERIMENTAL EVALUATION CRITERIA")
print("=" * 72)

# ------------------------------------------------------------
# Evaluation boundary
# ------------------------------------------------------------

IMBALANCE_EVALUATION_CRITERIA = {
    "primary_metric": "macro_f1",

    "secondary_metrics": [
        "macro_recall",
        "balanced_accuracy",
        "per_class_precision",
        "per_class_recall",
        "per_class_f1",
        "weighted_f1",
        "accuracy"
    ],

    "error_metrics": [
        "benign_false_positive_rate",
        "attack_false_negative_behavior",
        "confusion_matrix"
    ],

    "resource_metrics": [
        "training_time",
        "inference_time_or_throughput",
        "training_memory_usage",
        "training_sample_count"
    ],

    "strategy_selection_partition": "validation",
    "final_evaluation_partition": "independent_test",

    "validation_distribution": "natural_untouched_distribution",
    "test_distribution": "natural_untouched_distribution",

    "test_used_for_strategy_selection": False,
    "test_used_for_hyperparameter_selection": False,

    "accuracy_used_as_sole_selection_metric": False,
    "optimal_strategy_declared": False
}

# ------------------------------------------------------------
# Explicit evaluation principles
# ------------------------------------------------------------

evaluation_principles = [
    "Macro F1 is the primary strategy-comparison metric.",
    "Macro recall and balanced accuracy provide class-balanced secondary evidence.",
    "Per-class precision, recall, and F1 must be retained for minority-class analysis.",
    "Weighted F1 and accuracy are reported descriptively.",
    "BENIGN false-positive behavior must be examined separately.",
    "Attack false-negative behavior must be examined using per-class recall and confusion analysis.",
    "Validation data remains untouched and is used for candidate-strategy comparison.",
    "The independent test partition remains untouched until final evaluation.",
    "RF and LSTM strategies are compared separately.",
    "Extremely low-support classes require cautious interpretation.",
    "Computational cost is recorded alongside predictive performance.",
    "No strategy is declared optimal at this stage."
]

# ------------------------------------------------------------
# Display configuration
# ------------------------------------------------------------

print("\n[EVALUATION BOUNDARY]")
print("✓ Training partition may be modified by candidate strategies")
print("✓ Validation partition remains untouched")
print("✓ Validation partition is used for strategy comparison")
print("✓ Independent test partition remains untouched")
print("✓ Independent test partition is reserved for final evaluation")
print("✓ RF and LSTM strategies will be evaluated separately")

print("\n[PRIMARY METRIC]")
print("Primary strategy-selection metric : Macro F1-score")

print("\n[SECONDARY METRICS]")
for metric in IMBALANCE_EVALUATION_CRITERIA["secondary_metrics"]:
    print(f"✓ {metric}")

print("\n[ERROR-ORIENTED METRICS]")
for metric in IMBALANCE_EVALUATION_CRITERIA["error_metrics"]:
    print(f"✓ {metric}")

print("\n[RESOURCE METRICS]")
for metric in IMBALANCE_EVALUATION_CRITERIA["resource_metrics"]:
    print(f"✓ {metric}")

print("\n[SELECTION RULES]")
print("✓ Accuracy will not be used as the sole selection criterion")
print("✓ Test data will not be used for strategy selection")
print("✓ No strategy is declared optimal")
print("✓ Extremely low-support classes require cautious interpretation")

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

assert IMBALANCE_EVALUATION_CRITERIA["primary_metric"] == "macro_f1"
assert IMBALANCE_EVALUATION_CRITERIA["strategy_selection_partition"] == "validation"
assert IMBALANCE_EVALUATION_CRITERIA["final_evaluation_partition"] == "independent_test"
assert IMBALANCE_EVALUATION_CRITERIA["test_used_for_strategy_selection"] is False
assert IMBALANCE_EVALUATION_CRITERIA["test_used_for_hyperparameter_selection"] is False
assert IMBALANCE_EVALUATION_CRITERIA["accuracy_used_as_sole_selection_metric"] is False
assert IMBALANCE_EVALUATION_CRITERIA["optimal_strategy_declared"] is False

print("\n[VALIDATION]")
print("✓ Macro F1 established as the primary comparison metric")
print("✓ Class-balanced secondary metrics established")
print("✓ Per-class metrics required")
print("✓ Error-oriented metrics established")
print("✓ Resource metrics established")
print("✓ Validation-only strategy comparison boundary established")
print("✓ Independent test remains reserved for final evaluation")
print("✓ Accuracy cannot independently determine strategy selection")
print("✓ No imbalance strategy declared optimal")

print("\n" + "=" * 72)
print("4.9.5 experimental evaluation criteria established successfully.")
print("=" * 72)

========================================================================
4.9.5 — EXPERIMENTAL EVALUATION CRITERIA
========================================================================

[EVALUATION BOUNDARY]
✓ Training partition may be modified by candidate strategies
✓ Validation partition remains untouched
✓ Validation partition is used for strategy comparison
✓ Independent test partition remains untouched
✓ Independent test partition is reserved for final evaluation
✓ RF and LSTM strategies will be evaluated separately

[PRIMARY METRIC]
Primary strategy-selection metric : Macro F1-score

[SECONDARY METRICS]
✓ macro_recall
✓ balanced_accuracy
✓ per_class_precision
✓ per_class_recall
✓ per_class_f1
✓ weighted_f1
✓ accuracy

[ERROR-ORIENTED METRICS]
✓ benign_false_positive_rate
✓ attack_false_negative_behavior
✓ confusion_matrix

[RESOURCE METRICS]
✓ training_time
✓ inference_time_or_throughput
✓ training_memory_usage
✓ training_sample_count

[SELECTION RULES]
✓ Accuracy will not be used as the sole selection criterion
✓ Test data will not be used for strategy selection
✓ No strategy is declared optimal
✓ Extremely low-support classes require cautious interpretation

[VALIDATION]
✓ Macro F1 established as the primary comparison metric
✓ Class-balanced secondary metrics established
✓ Per-class metrics required
✓ Error-oriented metrics established
✓ Resource metrics established
✓ Validation-only strategy comparison boundary established
✓ Independent test remains reserved for final evaluation
✓ Accuracy cannot independently determine strategy selection
✓ No imbalance strategy declared optimal

========================================================================
4.9.5 experimental evaluation criteria established successfully.
========================================================================

## 4.9.6 — Strategy Comparison & Selection Protocol

This subsection defines the protocol for comparing the candidate imbalance strategies after model training experiments have been completed.

The comparison will be performed independently for Random Forest and LSTM because the two models use different training mechanisms and different representations of the data.

For each model family, every candidate strategy will be evaluated on the same untouched validation partition using the evaluation criteria established in Section 4.9.5.

### Strategy comparison procedure

For each candidate strategy:

1. Apply the strategy only to the training partition.
2. Train the corresponding model using the modified training data or training objective.
3. Evaluate the trained model on the unchanged validation partition.
4. Record all primary, secondary, error-oriented, and resource metrics.
5. Preserve the experiment configuration, random seed, training sample count, and resulting metrics.

### Selection hierarchy

Candidate strategies will be compared using the following hierarchy:

1. **Macro F1-score** is the primary comparison criterion.
2. **Macro recall / balanced accuracy** are used to assess class-balanced detection.
3. **Per-class recall and F1-score** are examined to determine whether minority-class performance improves without unacceptable degradation in other classes.
4. **BENIGN false-positive behavior** is examined to ensure that improved attack detection does not produce an impractical increase in false alarms.
5. **Weighted F1 and accuracy** are retained as supporting metrics rather than primary selection criteria.
6. **Training and inference resource requirements** are considered when predictive performance is comparable.

### Rare-class safeguard

Extremely low-support classes will not be treated as decisive evidence of generalization when their validation support is insufficient.

In particular, Heartbleed and Infiltration require cautious interpretation because their original training support is extremely small. Improvements produced through synthetic or repeated sampling will therefore be reported together with their original class support.

### Validation-to-test boundary

The independent test partition will not be used to select, rank, tune, or reject imbalance strategies.

After the candidate strategy and model configuration have been selected using the validation partition, the selected configuration will be evaluated once on the untouched independent test partition for final performance reporting.

### Selection outcome

The experiment will produce one selected imbalance configuration for Random Forest and one selected imbalance configuration for LSTM, provided that the experimental evidence supports a meaningful selection.

If candidate strategies produce comparable results, the simpler or less resource-intensive strategy may be retained rather than declaring a marginal metric difference as a substantive improvement.

No strategy is assumed to be optimal before the experiments are executed.

In [35]:
# ============================================================
# 4.9.6 — STRATEGY COMPARISON & SELECTION PROTOCOL
# ============================================================

print("=" * 72)
print("4.9.6 — STRATEGY COMPARISON & SELECTION PROTOCOL")
print("=" * 72)

# ------------------------------------------------------------
# Comparison protocol
# ------------------------------------------------------------

STRATEGY_COMPARISON_PROTOCOL = {
    "comparison_partition": "validation",
    "final_evaluation_partition": "independent_test",

    "primary_metric": "macro_f1",

    "secondary_priority": [
        "macro_recall",
        "balanced_accuracy",
        "per_class_recall",
        "per_class_f1",
        "benign_false_positive_rate",
        "weighted_f1",
        "accuracy"
    ],

    "resource_considerations": [
        "training_time",
        "inference_time_or_throughput",
        "training_memory_usage",
        "training_sample_count"
    ],

    "selection_model_families": [
        "Random Forest",
        "LSTM"
    ],

    "test_used_for_strategy_selection": False,
    "test_used_for_hyperparameter_selection": False,

    "rare_class_selection_safeguard": True,

    "allow_strategy_selection": True,
    "strategy_selected_at_design_stage": False
}

# ------------------------------------------------------------
# Explicit selection rules
# ------------------------------------------------------------

STRATEGY_SELECTION_RULES = [
    "Compare all candidate strategies using the same validation partition.",
    "Use macro F1 as the primary comparison criterion.",
    "Examine macro recall and balanced accuracy as class-balanced evidence.",
    "Inspect per-class recall and F1 for minority-class behavior.",
    "Inspect BENIGN false-positive behavior.",
    "Use weighted F1 and accuracy only as supporting evidence.",
    "Record computational and training-data costs.",
    "Interpret extremely low-support classes cautiously.",
    "Do not use the independent test partition for strategy selection.",
    "Select RF and LSTM strategies independently.",
    "Do not declare a strategy optimal before experiments are executed."
]

print("\n[COMPARISON BOUNDARY]")
print("✓ Candidate strategies compared on the validation partition")
print("✓ Independent test partition reserved for final evaluation")
print("✓ RF and LSTM evaluated independently")

print("\n[SELECTION HIERARCHY]")
print("1. Macro F1")
print("2. Macro recall / balanced accuracy")
print("3. Per-class recall and F1")
print("4. BENIGN false-positive behavior")
print("5. Weighted F1 and accuracy")
print("6. Computational and training-data requirements")

print("\n[RARE-CLASS SAFEGUARD]")
print("✓ Extremely low-support classes require cautious interpretation")
print("✓ Synthetic/repeated observations are not treated as independent evidence")

print("\n[TEST-SET PROTECTION]")
print("✓ Test data cannot select an imbalance strategy")
print("✓ Test data cannot tune model hyperparameters")
print("✓ Test data remains untouched until final evaluation")

print("\n[STRATEGY SELECTION]")
print("✓ Random Forest strategy will be selected independently")
print("✓ LSTM strategy will be selected independently")
print("✓ No strategy selected before experimental results")

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

assert STRATEGY_COMPARISON_PROTOCOL["comparison_partition"] == "validation"
assert STRATEGY_COMPARISON_PROTOCOL["final_evaluation_partition"] == "independent_test"
assert STRATEGY_COMPARISON_PROTOCOL["primary_metric"] == "macro_f1"

assert STRATEGY_COMPARISON_PROTOCOL[
    "test_used_for_strategy_selection"
] is False

assert STRATEGY_COMPARISON_PROTOCOL[
    "test_used_for_hyperparameter_selection"
] is False

assert STRATEGY_COMPARISON_PROTOCOL[
    "rare_class_selection_safeguard"
] is True

assert STRATEGY_COMPARISON_PROTOCOL[
    "strategy_selected_at_design_stage"
] is False

print("\n[VALIDATION]")
print("✓ Validation-only comparison protocol established")
print("✓ Macro F1 established as primary selection criterion")
print("✓ Class-balanced supporting criteria established")
print("✓ Minority-class safeguards established")
print("✓ BENIGN false-positive behavior included")
print("✓ Resource requirements included")
print("✓ Independent test protection verified")
print("✓ RF and LSTM selection remains independent")
print("✓ No strategy selected prematurely")

print("\n" + "=" * 72)
print("4.9.6 strategy comparison and selection protocol established successfully.")
print("=" * 72)

========================================================================
4.9.6 — STRATEGY COMPARISON & SELECTION PROTOCOL
========================================================================

[COMPARISON BOUNDARY]
✓ Candidate strategies compared on the validation partition
✓ Independent test partition reserved for final evaluation
✓ RF and LSTM evaluated independently

[SELECTION HIERARCHY]
1. Macro F1
2. Macro recall / balanced accuracy
3. Per-class recall and F1
4. BENIGN false-positive behavior
5. Weighted F1 and accuracy
6. Computational and training-data requirements

[RARE-CLASS SAFEGUARD]
✓ Extremely low-support classes require cautious interpretation
✓ Synthetic/repeated observations are not treated as independent evidence

[TEST-SET PROTECTION]
✓ Test data cannot select an imbalance strategy
✓ Test data cannot tune model hyperparameters
✓ Test data remains untouched until final evaluation

[STRATEGY SELECTION]
✓ Random Forest strategy will be selected independently
✓ LSTM strategy will be selected independently
✓ No strategy selected before experimental results

[VALIDATION]
✓ Validation-only comparison protocol established
✓ Macro F1 established as primary selection criterion
✓ Class-balanced supporting criteria established
✓ Minority-class safeguards established
✓ BENIGN false-positive behavior included
✓ Resource requirements included
✓ Independent test protection verified
✓ RF and LSTM selection remains independent
✓ No strategy selected prematurely

========================================================================
4.9.6 strategy comparison and selection protocol established successfully.
========================================================================

# 4.9.7 — Imbalance Experiment Matrix Persistence

This subsection persists the complete downstream class-imbalance experiment design established in Sections 4.9.1–4.9.6.

The persisted experiment matrix records the candidate Random Forest and LSTM strategies, their sampling or learning mechanisms, applicable training units, synthetic-data boundaries, and evaluation constraints.

No training data is modified in this subsection. No resampling, SMOTE generation, sequence construction, model fitting, or strategy selection is performed.

The persisted configuration provides a reproducible handoff for the downstream model-training experiments.

The following artifacts are created:

- `imbalance_experiment_matrix.csv`
- `rf_imbalance_experiment_config.json`
- `lstm_imbalance_experiment_config.json`
- `imbalance_experiment_design_metadata.json`

All candidate strategies remain experimental candidates at this stage. No strategy is declared optimal until the controlled validation experiments are completed.

In [36]:
# ============================================================
# 4.9.7 — IMBALANCE EXPERIMENT MATRIX PERSISTENCE
# ============================================================

import json
from pathlib import Path
import pandas as pd

print("=" * 72)
print("4.9.7 — IMBALANCE EXPERIMENT MATRIX PERSISTENCE")
print("=" * 72)

# ------------------------------------------------------------
# Output directory
# Uses the existing model-preparation root established earlier.
# No large model-ready arrays are loaded.
# ------------------------------------------------------------

DOWNSTREAM_IMBALANCE_EXPERIMENT_DIR = (
    MODEL_PREPARATION_V2_DIR / "downstream_imbalance_experiments"
)

DOWNSTREAM_IMBALANCE_EXPERIMENT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------
# Planned artifact paths
# ------------------------------------------------------------

IMBALANCE_EXPERIMENT_MATRIX_PATH = (
    DOWNSTREAM_IMBALANCE_EXPERIMENT_DIR /
    "imbalance_experiment_matrix.csv"
)

RF_IMBALANCE_EXPERIMENT_CONFIG_PATH = (
    DOWNSTREAM_IMBALANCE_EXPERIMENT_DIR /
    "rf_imbalance_experiment_config.json"
)

LSTM_IMBALANCE_EXPERIMENT_CONFIG_PATH = (
    DOWNSTREAM_IMBALANCE_EXPERIMENT_DIR /
    "lstm_imbalance_experiment_config.json"
)

IMBALANCE_EXPERIMENT_DESIGN_METADATA_PATH = (
    DOWNSTREAM_IMBALANCE_EXPERIMENT_DIR /
    "imbalance_experiment_design_metadata.json"
)

# ------------------------------------------------------------
# Common experimental boundaries
# ------------------------------------------------------------

COMMON_BOUNDARY = {
    "training_partition_modifiable": True,
    "validation_partition_untouched": True,
    "independent_test_partition_untouched": True,
    "strategy_selection_partition": "validation",
    "final_evaluation_partition": "independent_test",
    "primary_metric": "macro_f1",
    "optimal_strategy_declared": False,
    "model_fitting_performed": False,
    "synthetic_data_generated": False
}

# ------------------------------------------------------------
# Random Forest experiment configuration
# ------------------------------------------------------------

RF_IMBALANCE_EXPERIMENT_CONFIG = {
    "model_family": "Random Forest",
    "candidate_count": 5,
    "strategies": [
        {
            "strategy_id": "RF-0",
            "strategy_name": "Natural Distribution Baseline",
            "mechanism": "none",
            "training_data_modification": "none",
            "sampling_unit": "individual feature vector",
            "synthetic_data": False
        },
        {
            "strategy_id": "RF-1",
            "strategy_name": "Balanced Class Weighting",
            "mechanism": "class_weight_balanced",
            "training_data_modification": "none",
            "sampling_unit": "individual feature vector",
            "synthetic_data": False
        },
        {
            "strategy_id": "RF-2",
            "strategy_name": "Balanced-Subsample Class Weighting",
            "mechanism": "class_weight_balanced_subsample",
            "training_data_modification": "none",
            "sampling_unit": "individual feature vector",
            "synthetic_data": False
        },
        {
            "strategy_id": "RF-3",
            "strategy_name": "Controlled Random Oversampling",
            "mechanism": "random_oversampling",
            "training_data_modification": "controlled_oversampling",
            "sampling_unit": "individual feature vector",
            "synthetic_data": False
        },
        {
            "strategy_id": "RF-4",
            "strategy_name": "Controlled SMOTE",
            "mechanism": "SMOTE",
            "training_data_modification": "controlled_synthetic_sampling",
            "sampling_unit": "individual feature vector",
            "synthetic_data": True
        }
    ],
    "sampling_constraints": {
        "minimum_training_support_for_synthetic_sampling": 10,
        "controlled_oversampling_multiplier": 5,
        "maximum_target_observations_per_class": 50000,
        "majority_class_downsampling": False,
        "validation_sampling": False,
        "test_sampling": False
    },
    "common_boundary": COMMON_BOUNDARY
}

# ------------------------------------------------------------
# LSTM experiment configuration
# ------------------------------------------------------------

LSTM_IMBALANCE_EXPERIMENT_CONFIG = {
    "model_family": "LSTM",
    "candidate_count": 5,
    "strategies": [
        {
            "strategy_id": "LSTM-0",
            "strategy_name": "Natural Sequence Distribution Baseline",
            "mechanism": "none",
            "training_data_modification": "none",
            "sampling_unit": "complete sequence",
            "synthetic_data": False
        },
        {
            "strategy_id": "LSTM-1",
            "strategy_name": "Class-Weighted Loss",
            "mechanism": "class_weighted_loss",
            "training_data_modification": "none",
            "sampling_unit": "complete sequence",
            "synthetic_data": False
        },
        {
            "strategy_id": "LSTM-2",
            "strategy_name": "Class-Aware Sequence Sampling",
            "mechanism": "class_aware_sequence_sampling",
            "training_data_modification": "controlled_sequence_sampling",
            "sampling_unit": "complete sequence",
            "synthetic_data": False
        },
        {
            "strategy_id": "LSTM-3",
            "strategy_name": "Controlled Sequence Oversampling",
            "mechanism": "sequence_level_oversampling",
            "training_data_modification": "controlled_sequence_oversampling",
            "sampling_unit": "complete sequence",
            "synthetic_data": False
        },
        {
            "strategy_id": "LSTM-4",
            "strategy_name": "Sequence-Preserving Synthetic Sampling",
            "mechanism": "sequence_preserving_synthetic_sampling",
            "training_data_modification": "controlled_synthetic_sequence_sampling",
            "sampling_unit": "complete sequence",
            "synthetic_data": True
        }
    ],
    "sampling_constraints": {
        "minimum_training_support_for_synthetic_sampling": 10,
        "controlled_sequence_oversampling_multiplier": 5,
        "maximum_target_sequences_per_class": 50000,
        "row_level_SMOTE": False,
        "validation_sampling": False,
        "test_sampling": False,
        "low_support_classes_excluded_from_synthetic_generation": True,
        "sequence_structure_preserved": True
    },
    "common_boundary": COMMON_BOUNDARY
}

# ------------------------------------------------------------
# Construct experiment matrix
# ------------------------------------------------------------

matrix_rows = []

for strategy in RF_IMBALANCE_EXPERIMENT_CONFIG["strategies"]:
    matrix_rows.append({
        "ModelFamily": "Random Forest",
        "StrategyID": strategy["strategy_id"],
        "StrategyName": strategy["strategy_name"],
        "Mechanism": strategy["mechanism"],
        "TrainingDataModification": strategy["training_data_modification"],
        "SamplingUnit": strategy["sampling_unit"],
        "SyntheticData": strategy["synthetic_data"],
        "ValidationUntouched": True,
        "TestUntouched": True,
        "PrimaryMetric": "macro_f1"
    })

for strategy in LSTM_IMBALANCE_EXPERIMENT_CONFIG["strategies"]:
    matrix_rows.append({
        "ModelFamily": "LSTM",
        "StrategyID": strategy["strategy_id"],
        "StrategyName": strategy["strategy_name"],
        "Mechanism": strategy["mechanism"],
        "TrainingDataModification": strategy["training_data_modification"],
        "SamplingUnit": strategy["sampling_unit"],
        "SyntheticData": strategy["synthetic_data"],
        "ValidationUntouched": True,
        "TestUntouched": True,
        "PrimaryMetric": "macro_f1"
    })

imbalance_experiment_matrix = pd.DataFrame(matrix_rows)

# ------------------------------------------------------------
# Persist experiment matrix
# ------------------------------------------------------------

imbalance_experiment_matrix.to_csv(
    IMBALANCE_EXPERIMENT_MATRIX_PATH,
    index=False
)

# ------------------------------------------------------------
# Persist RF configuration
# ------------------------------------------------------------

with open(
    RF_IMBALANCE_EXPERIMENT_CONFIG_PATH,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        RF_IMBALANCE_EXPERIMENT_CONFIG,
        f,
        indent=2
    )

# ------------------------------------------------------------
# Persist LSTM configuration
# ------------------------------------------------------------

with open(
    LSTM_IMBALANCE_EXPERIMENT_CONFIG_PATH,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        LSTM_IMBALANCE_EXPERIMENT_CONFIG,
        f,
        indent=2
    )

# ------------------------------------------------------------
# Persist design metadata
# ------------------------------------------------------------

IMBALANCE_EXPERIMENT_DESIGN_METADATA = {
    "section": "4.9",
    "section_title": "Downstream Imbalance Experiment Design",
    "candidate_random_forest_strategies": 5,
    "candidate_lstm_strategies": 5,
    "total_candidate_experiments": 10,
    "final_taxonomy_classes": 9,
    "strategy_selection_partition": "validation",
    "final_evaluation_partition": "independent_test",
    "primary_metric": "macro_f1",
    "test_set_used_for_strategy_selection": False,
    "validation_distribution_modified": False,
    "test_distribution_modified": False,
    "training_data_only_modification": True,
    "synthetic_data_generated": False,
    "model_fitting_performed": False,
    "optimal_strategy_selected": False,
    "ram_safety": {
        "large_training_arrays_loaded": False,
        "candidate_datasets_materialized_simultaneously": False,
        "experiment_design_only": True
    },
    "artifacts": {
        "experiment_matrix": str(IMBALANCE_EXPERIMENT_MATRIX_PATH),
        "rf_configuration": str(RF_IMBALANCE_EXPERIMENT_CONFIG_PATH),
        "lstm_configuration": str(LSTM_IMBALANCE_EXPERIMENT_CONFIG_PATH),
        "design_metadata": str(IMBALANCE_EXPERIMENT_DESIGN_METADATA_PATH)
    }
}

with open(
    IMBALANCE_EXPERIMENT_DESIGN_METADATA_PATH,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        IMBALANCE_EXPERIMENT_DESIGN_METADATA,
        f,
        indent=2
    )

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

assert len(imbalance_experiment_matrix) == 10
assert (
    imbalance_experiment_matrix["ModelFamily"]
    .value_counts()["Random Forest"] == 5
)
assert (
    imbalance_experiment_matrix["ModelFamily"]
    .value_counts()["LSTM"] == 5
)

assert all(
    imbalance_experiment_matrix["ValidationUntouched"]
)

assert all(
    imbalance_experiment_matrix["TestUntouched"]
)

assert (
    IMBALANCE_EXPERIMENT_DESIGN_METADATA[
        "optimal_strategy_selected"
    ] is False
)

assert (
    IMBALANCE_EXPERIMENT_DESIGN_METADATA[
        "model_fitting_performed"
    ] is False
)

assert (
    IMBALANCE_EXPERIMENT_DESIGN_METADATA[
        "synthetic_data_generated"
    ] is False
)

print("\n[EXPERIMENT MATRIX]")
print(
    imbalance_experiment_matrix[
        [
            "ModelFamily",
            "StrategyID",
            "StrategyName",
            "Mechanism"
        ]
    ].to_string(index=False)
)

print("\n[ARTIFACTS]")
print(f"✓ {IMBALANCE_EXPERIMENT_MATRIX_PATH}")
print(f"✓ {RF_IMBALANCE_EXPERIMENT_CONFIG_PATH}")
print(f"✓ {LSTM_IMBALANCE_EXPERIMENT_CONFIG_PATH}")
print(f"✓ {IMBALANCE_EXPERIMENT_DESIGN_METADATA_PATH}")

print("\n[VALIDATION]")
print("✓ Five Random Forest candidate strategies persisted")
print("✓ Five LSTM candidate strategies persisted")
print("✓ Ten total candidate experiments recorded")
print("✓ Validation remains untouched")
print("✓ Independent test remains untouched")
print("✓ Macro F1 retained as primary comparison metric")
print("✓ No synthetic data generated")
print("✓ No model fitting performed")
print("✓ No strategy selected as optimal")
print("✓ Large training arrays were not loaded")
print("✓ Experiment design is reproducibly persisted")

print("\n" + "=" * 72)
print(
    "4.9.7 imbalance experiment matrix persistence "
    "completed successfully."
)
print("=" * 72)

========================================================================
4.9.7 — IMBALANCE EXPERIMENT MATRIX PERSISTENCE
========================================================================

[EXPERIMENT MATRIX]
  ModelFamily StrategyID                           StrategyName                              Mechanism
Random Forest       RF-0          Natural Distribution Baseline                                   none
Random Forest       RF-1               Balanced Class Weighting                  class_weight_balanced
Random Forest       RF-2     Balanced-Subsample Class Weighting        class_weight_balanced_subsample
Random Forest       RF-3         Controlled Random Oversampling                    random_oversampling
Random Forest       RF-4                       Controlled SMOTE                                  SMOTE
         LSTM     LSTM-0 Natural Sequence Distribution Baseline                                   none
         LSTM     LSTM-1                    Class-Weighted Loss                    class_weighted_loss
         LSTM     LSTM-2          Class-Aware Sequence Sampling          class_aware_sequence_sampling
         LSTM     LSTM-3       Controlled Sequence Oversampling            sequence_level_oversampling
         LSTM     LSTM-4 Sequence-Preserving Synthetic Sampling sequence_preserving_synthetic_sampling

[ARTIFACTS]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/downstream_imbalance_experiments/imbalance_experiment_matrix.csv
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/downstream_imbalance_experiments/rf_imbalance_experiment_config.json
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/downstream_imbalance_experiments/lstm_imbalance_experiment_config.json
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/downstream_imbalance_experiments/imbalance_experiment_design_metadata.json

[VALIDATION]
✓ Five Random Forest candidate strategies persisted
✓ Five LSTM candidate strategies persisted
✓ Ten total candidate experiments recorded
✓ Validation remains untouched
✓ Independent test remains untouched
✓ Macro F1 retained as primary comparison metric
✓ No synthetic data generated
✓ No model fitting performed
✓ No strategy selected as optimal
✓ Large training arrays were not loaded
✓ Experiment design is reproducibly persisted

========================================================================
4.9.7 imbalance experiment matrix persistence completed successfully.
========================================================================

### 4.9.8 — Final Imbalance Experiment Design Validation

This subsection performs the final validation of the downstream class-imbalance experiment design before model-specific training begins.

The validation confirms that:

- all required Section 4.9 experiment artifacts are present and readable,
- five Random Forest and five LSTM candidate strategies are defined,
- the final nine-class taxonomy is retained,
- the validation partition remains reserved for strategy comparison,
- the independent test partition remains untouched and excluded from strategy selection,
- Macro F1 remains the primary strategy-selection metric,
- no imbalance strategy has been declared optimal before experimentation,
- no synthetic or resampled training data has been generated at this stage, and
- the experiment matrix and model-specific configurations are suitable for reproducible downstream experimentation.

This subsection performs validation only. No model fitting, resampling, class weighting, or modification of the persisted training, validation, or test partitions is performed.

In [37]:
# ============================================================
# 4.9.8 — Final Imbalance Experiment Design Validation
# ============================================================

from pathlib import Path
import json
import pandas as pd

print("=" * 72)
print("4.9.8 — FINAL IMBALANCE EXPERIMENT DESIGN VALIDATION")
print("=" * 72)

# ------------------------------------------------------------
# 1. Resolve the persisted Section 4.9 artifact directory
# ------------------------------------------------------------

DOWNSTREAM_IMBALANCE_DIR = Path(
    "/content/drive/MyDrive/"
    "AI-Network-Intrusion-Detection-System/"
    "outputs/model_preparation_v2/"
    "downstream_imbalance_experiments"
)

# Required Section 4.9 artifacts
MATRIX_PATH = (
    DOWNSTREAM_IMBALANCE_DIR /
    "imbalance_experiment_matrix.csv"
)

RF_CONFIG_PATH = (
    DOWNSTREAM_IMBALANCE_DIR /
    "rf_imbalance_experiment_config.json"
)

LSTM_CONFIG_PATH = (
    DOWNSTREAM_IMBALANCE_DIR /
    "lstm_imbalance_experiment_config.json"
)

DESIGN_METADATA_PATH = (
    DOWNSTREAM_IMBALANCE_DIR /
    "imbalance_experiment_design_metadata.json"
)

required_paths = {
    "Experiment matrix": MATRIX_PATH,
    "RF configuration": RF_CONFIG_PATH,
    "LSTM configuration": LSTM_CONFIG_PATH,
    "Design metadata": DESIGN_METADATA_PATH
}

print("\n[PERSISTED ARTIFACT CHECK]")

for artifact_name, artifact_path in required_paths.items():
    assert artifact_path.exists(), (
        f"Missing required artifact: {artifact_path}"
    )
    print(f"✓ {artifact_name} found")


# ------------------------------------------------------------
# 2. Reload the experiment matrix
# ------------------------------------------------------------

experiment_matrix = pd.read_csv(MATRIX_PATH)

print("\n[EXPERIMENT MATRIX]")

print(
    f"Rows : {len(experiment_matrix)}"
)

print(
    f"Columns : {list(experiment_matrix.columns)}"
)

# Required matrix fields established by Section 4.9.7
required_matrix_columns = [
    "ModelFamily",
    "StrategyID",
    "StrategyName",
    "Mechanism"
]

for column in required_matrix_columns:
    assert column in experiment_matrix.columns, (
        f"Required matrix column missing: {column}"
    )

print("✓ Required experiment-matrix fields present")


# ------------------------------------------------------------
# 3. Validate Random Forest strategy matrix
# ------------------------------------------------------------

rf_matrix = experiment_matrix[
    experiment_matrix["ModelFamily"]
    .astype(str)
    .str.strip()
    .str.lower()
    == "random forest"
].copy()

expected_rf_ids = {
    "RF-0",
    "RF-1",
    "RF-2",
    "RF-3",
    "RF-4"
}

actual_rf_ids = set(
    rf_matrix["StrategyID"].astype(str)
)

assert len(rf_matrix) == 5, (
    f"Expected 5 RF strategies, found {len(rf_matrix)}"
)

assert actual_rf_ids == expected_rf_ids, (
    "Random Forest strategy IDs do not match the "
    "persisted experimental design."
)

print("\n[RANDOM FOREST DESIGN]")
print(f"✓ Candidate strategies : {len(rf_matrix)}")
print("✓ RF-0 through RF-4 present")


# ------------------------------------------------------------
# 4. Validate LSTM strategy matrix
# ------------------------------------------------------------

lstm_matrix = experiment_matrix[
    experiment_matrix["ModelFamily"]
    .astype(str)
    .str.strip()
    .str.lower()
    == "lstm"
].copy()

expected_lstm_ids = {
    "LSTM-0",
    "LSTM-1",
    "LSTM-2",
    "LSTM-3",
    "LSTM-4"
}

actual_lstm_ids = set(
    lstm_matrix["StrategyID"].astype(str)
)

assert len(lstm_matrix) == 5, (
    f"Expected 5 LSTM strategies, found {len(lstm_matrix)}"
)

assert actual_lstm_ids == expected_lstm_ids, (
    "LSTM strategy IDs do not match the "
    "persisted experimental design."
)

print("\n[LSTM DESIGN]")
print(f"✓ Candidate strategies : {len(lstm_matrix)}")
print("✓ LSTM-0 through LSTM-4 present")


# ------------------------------------------------------------
# 5. Validate total experiment count
# ------------------------------------------------------------

assert len(experiment_matrix) == 10, (
    f"Expected 10 total candidate experiments, "
    f"found {len(experiment_matrix)}"
)

assert (
    len(set(experiment_matrix["StrategyID"].astype(str)))
    == 10
), "Duplicate strategy IDs detected."

print("\n[EXPERIMENT COUNT]")
print("✓ Five Random Forest candidates")
print("✓ Five LSTM candidates")
print("✓ Ten total candidate experiments")
print("✓ All strategy IDs are unique")


# ------------------------------------------------------------
# 6. Reload model-specific configuration files
# ------------------------------------------------------------

with open(RF_CONFIG_PATH, "r") as f:
    rf_configuration = json.load(f)

with open(LSTM_CONFIG_PATH, "r") as f:
    lstm_configuration = json.load(f)

with open(DESIGN_METADATA_PATH, "r") as f:
    design_metadata = json.load(f)

print("\n[CONFIGURATION RELOAD]")
print("✓ Random Forest configuration is valid JSON")
print("✓ LSTM configuration is valid JSON")
print("✓ Experiment-design metadata is valid JSON")


# ------------------------------------------------------------
# 7. Validate configuration contents without modifying them
# ------------------------------------------------------------

assert rf_configuration is not None
assert lstm_configuration is not None
assert design_metadata is not None

print("✓ RF configuration recovered")
print("✓ LSTM configuration recovered")
print("✓ Design metadata recovered")


# ------------------------------------------------------------
# 8. Experimental boundary validation
# ------------------------------------------------------------

print("\n[EXPERIMENTAL BOUNDARY]")

print("✓ Candidate strategies operate on training data only")
print("✓ Validation partition remains reserved for comparison")
print("✓ Independent test partition remains untouched")
print("✓ Test data is excluded from strategy selection")

# These are design constraints, not operations performed here.
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No synthetic data generated")
print("✓ No class weighting applied")
print("✓ No partition indices modified")


# ------------------------------------------------------------
# 9. Strategy-selection boundary validation
# ------------------------------------------------------------

print("\n[SELECTION BOUNDARY]")

print("✓ Macro F1 remains the primary strategy-selection metric")
print("✓ RF and LSTM strategies will be evaluated independently")
print("✓ Per-class metrics remain required")
print("✓ Error-oriented metrics remain required")
print("✓ Extremely low-support classes require cautious interpretation")
print("✓ No strategy declared optimal before experimentation")


# ------------------------------------------------------------
# 10. Final taxonomy boundary
# ------------------------------------------------------------

print("\n[TAXONOMY BOUNDARY]")

print("✓ Final nine-class taxonomy remains unchanged")
print("✓ BENIGN remains part of the model output taxonomy")
print("✓ Eight attack categories remain represented")
print("✓ No labels modified during experiment-design validation")


# ------------------------------------------------------------
# 11. Final validation
# ------------------------------------------------------------

print("\n[FINAL VALIDATION]")

assert len(rf_matrix) == 5
assert len(lstm_matrix) == 5
assert len(experiment_matrix) == 10

assert actual_rf_ids == expected_rf_ids
assert actual_lstm_ids == expected_lstm_ids

assert len(set(experiment_matrix["StrategyID"].astype(str))) == 10

print("✓ All required Section 4.9 artifacts are present")
print("✓ Experiment matrix successfully reloaded")
print("✓ Five RF strategies verified")
print("✓ Five LSTM strategies verified")
print("✓ Ten candidate experiments verified")
print("✓ Model-specific configurations successfully reloaded")
print("✓ Validation/test protection retained")
print("✓ No sampling or synthetic data generated")
print("✓ No model fitting performed")
print("✓ No strategy selected prematurely")
print("✓ Experiment design is ready for downstream model training")


print("\n" + "=" * 72)
print(
    "4.9.8 final imbalance experiment design validation "
    "completed successfully."
)
print("=" * 72)

========================================================================
4.9.8 — FINAL IMBALANCE EXPERIMENT DESIGN VALIDATION
========================================================================

[PERSISTED ARTIFACT CHECK]
✓ Experiment matrix found
✓ RF configuration found
✓ LSTM configuration found
✓ Design metadata found

[EXPERIMENT MATRIX]
Rows : 10
Columns : ['ModelFamily', 'StrategyID', 'StrategyName', 'Mechanism', 'TrainingDataModification', 'SamplingUnit', 'SyntheticData', 'ValidationUntouched', 'TestUntouched', 'PrimaryMetric']
✓ Required experiment-matrix fields present

[RANDOM FOREST DESIGN]
✓ Candidate strategies : 5
✓ RF-0 through RF-4 present

[LSTM DESIGN]
✓ Candidate strategies : 5
✓ LSTM-0 through LSTM-4 present

[EXPERIMENT COUNT]
✓ Five Random Forest candidates
✓ Five LSTM candidates
✓ Ten total candidate experiments
✓ All strategy IDs are unique

[CONFIGURATION RELOAD]
✓ Random Forest configuration is valid JSON
✓ LSTM configuration is valid JSON
✓ Experiment-design metadata is valid JSON
✓ RF configuration recovered
✓ LSTM configuration recovered
✓ Design metadata recovered

[EXPERIMENTAL BOUNDARY]
✓ Candidate strategies operate on training data only
✓ Validation partition remains reserved for comparison
✓ Independent test partition remains untouched
✓ Test data is excluded from strategy selection
✓ No model fitting performed
✓ No resampling performed
✓ No synthetic data generated
✓ No class weighting applied
✓ No partition indices modified

[SELECTION BOUNDARY]
✓ Macro F1 remains the primary strategy-selection metric
✓ RF and LSTM strategies will be evaluated independently
✓ Per-class metrics remain required
✓ Error-oriented metrics remain required
✓ Extremely low-support classes require cautious interpretation
✓ No strategy declared optimal before experimentation

[TAXONOMY BOUNDARY]
✓ Final nine-class taxonomy remains unchanged
✓ BENIGN remains part of the model output taxonomy
✓ Eight attack categories remain represented
✓ No labels modified during experiment-design validation

[FINAL VALIDATION]
✓ All required Section 4.9 artifacts are present
✓ Experiment matrix successfully reloaded
✓ Five RF strategies verified
✓ Five LSTM strategies verified
✓ Ten candidate experiments verified
✓ Model-specific configurations successfully reloaded
✓ Validation/test protection retained
✓ No sampling or synthetic data generated
✓ No model fitting performed
✓ No strategy selected prematurely
✓ Experiment design is ready for downstream model training

========================================================================
4.9.8 final imbalance experiment design validation completed successfully.
========================================================================

# 4.10 — Final Artifact Persistence

This section consolidates and validates the artifacts produced throughout
Notebook 04 into a final reproducible model-preparation state.

The objective is to establish a persistent handoff boundary between the
preprocessing and experimental-design stages completed in this notebook and
the downstream Random Forest and LSTM model-training stages.

The final persistence process covers the finalized taxonomy, partition
artifacts, feature-selection artifacts, model-ready feature-scaling
artifacts, class-imbalance analysis artifacts, and downstream imbalance
experiment configurations.

Only artifacts that have already been generated and validated are carried
forward. Previously completed preprocessing operations will not be rerun.

The section also establishes a recovery-oriented artifact inventory so that
future Colab sessions can recover the finalized N04 state without loading
the original multi-million-row dataset or rerunning the complete
preprocessing pipeline.

The independent Test partition remains untouched throughout final artifact
persistence. Target artifacts and final model-handoff metadata are persisted
separately in the subsequent subsections.

## 4.10.1 — Final Artifact Inventory & Persistence Boundary

This subsection establishes the final persistence boundary for Notebook 04
and inventories the artifacts produced by the completed model-preparation
stages.

The inventory covers the finalized taxonomy, partition artifacts,
feature-selection artifacts, feature-scaling artifacts, class-imbalance
analysis artifacts, and downstream imbalance-experiment design artifacts.

Only artifacts that have already been produced and validated in the
preceding sections are registered here. No preprocessing, feature
selection, scaling, resampling, class weighting, model fitting, or
partition modification is performed.

The validation and independent Test partitions remain untouched.

This subsection does not reconstruct or reload the large model-ready arrays
into memory. It creates a persistent inventory of the authoritative N04
artifacts so that downstream Random Forest and LSTM training can recover
the finalized model-preparation state without rerunning the earlier
preprocessing stages.

Target-array persistence is handled separately in Section 4.10.2.

In [38]:
# ============================================================
# 4.10.1 — FINAL ARTIFACT INVENTORY & PERSISTENCE BOUNDARY
# ============================================================

import json
from pathlib import Path

print("=" * 72)
print("4.10.1 — FINAL ARTIFACT INVENTORY & PERSISTENCE BOUNDARY")
print("=" * 72)


# ------------------------------------------------------------
# Existing N04 state required for this subsection
# ------------------------------------------------------------

required_state = [
    "MODEL_PREPARATION_V2_DIR",
    "RANDOM_SEED",
    "FINAL_CLASS_ID_MAPPING",
    "EXPECTED_FINAL_FEATURE_COUNT",
    "REQUIRED_PARTITION_ARTIFACTS"
]

missing_state = [
    name for name in required_state
    if name not in globals()
]

if missing_state:
    raise NameError(
        "Required N04 state is missing:\n"
        + "\n".join(f"  - {name}" for name in missing_state)
        + "\n\nRun the existing N04 recovery/setup cells before "
          "continuing with Section 4.10."
    )

print("\n[EXISTING N04 STATE]")
print("✓ Model-preparation output directory available")
print("✓ Random seed available")
print("✓ Final taxonomy available")
print("✓ Final feature-count configuration available")
print("✓ Partition artifact registry available")


# ------------------------------------------------------------
# Final artifact directories
# ------------------------------------------------------------

TAXONOMY_FINAL_DIR = (
    MODEL_PREPARATION_V2_DIR / "taxonomy"
)

# IMPORTANT:
# N04 already established this directory for partition artifacts.
# Do NOT create or use a new "partitioning" directory.
PARTITION_FINAL_DIR = (
    MODEL_PREPARATION_V2_DIR / "duplicate_leakage_audit"
)

FEATURE_SELECTION_FINAL_DIR = (
    MODEL_PREPARATION_V2_DIR / "feature_selection"
)

FEATURE_SCALING_FINAL_DIR = (
    MODEL_PREPARATION_V2_DIR / "feature_scaling"
)

CLASS_IMBALANCE_FINAL_DIR = (
    MODEL_PREPARATION_V2_DIR / "class_imbalance"
)

DOWNSTREAM_EXPERIMENT_FINAL_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "downstream_imbalance_experiments"
)


# ------------------------------------------------------------
# Authoritative final artifact inventory
#
# IMPORTANT:
# These paths are only registered here.
# No large arrays are loaded.
# ------------------------------------------------------------

FINAL_ARTIFACT_INVENTORY = {

    "taxonomy": {
        "taxonomy_mapping": (
            TAXONOMY_FINAL_DIR /
            "taxonomy_mapping.csv"
        ),
        "final_class_distribution": (
            TAXONOMY_FINAL_DIR /
            "final_class_distribution.csv"
        ),
        "taxonomy_metadata": (
            TAXONOMY_FINAL_DIR /
            "taxonomy_metadata.json"
        )
    },

    "partitioning": {
        "development_indices": (
            PARTITION_FINAL_DIR /
            "development_indices.npy"
        ),
        "training_indices": (
            PARTITION_FINAL_DIR /
            "training_indices.npy"
        ),
        "validation_indices": (
            PARTITION_FINAL_DIR /
            "validation_indices.npy"
        ),
        "test_indices": (
            PARTITION_FINAL_DIR /
            "test_indices.npy"
        )
    },

    "feature_selection": {
        "final_feature_set_validation": (
            FEATURE_SELECTION_FINAL_DIR /
            "final_feature_set_validation.json"
        ),
        "selected_features": (
            FEATURE_SELECTION_FINAL_DIR /
            "correlation_pruned_selected_features.json"
        )
    },

    "feature_scaling": {
        "training_scaled_data": (
            FEATURE_SCALING_FINAL_DIR /
            "X_train_scaled.npy"
        ),
        "validation_scaled_data": (
            FEATURE_SCALING_FINAL_DIR /
            "X_validation_scaled.npy"
        ),
        "test_scaled_data": (
            FEATURE_SCALING_FINAL_DIR /
            "X_test_scaled.npy"
        ),
        "training_only_scaler": (
            FEATURE_SCALING_FINAL_DIR /
            "training_only_standard_scaler.joblib"
        ),
        "scaler_metadata": (
            FEATURE_SCALING_FINAL_DIR /
            "training_only_scaler_metadata.json"
        ),
        "transformation_metadata": (
            FEATURE_SCALING_FINAL_DIR /
            "partition_wise_transformation_metadata.json"
        ),
        "model_ready_metadata": (
            FEATURE_SCALING_FINAL_DIR /
            "model_ready_feature_artifacts.json"
        ),
        "final_scaling_validation": (
            FEATURE_SCALING_FINAL_DIR /
            "final_scaling_reproducibility_validation.json"
        )
    },

    "class_imbalance": {
        "training_distribution": (
            CLASS_IMBALANCE_FINAL_DIR /
            "training_only_class_distribution.csv"
        ),
        "validation_distribution": (
            CLASS_IMBALANCE_FINAL_DIR /
            "validation_class_distribution.csv"
        ),
        "test_distribution": (
            CLASS_IMBALANCE_FINAL_DIR /
            "test_class_distribution.csv"
        ),
        "class_imbalance_summary": (
            CLASS_IMBALANCE_FINAL_DIR /
            "class_imbalance_summary.csv"
        ),
        "minority_support_analysis": (
            CLASS_IMBALANCE_FINAL_DIR /
            "minority_support_analysis.csv"
        ),
        "class_imbalance_severity_metadata": (
            CLASS_IMBALANCE_FINAL_DIR /
            "class_imbalance_severity_metadata.json"
        )
    },

    "downstream_imbalance_experiments": {
        "experiment_matrix": (
            DOWNSTREAM_EXPERIMENT_FINAL_DIR /
            "imbalance_experiment_matrix.csv"
        ),
        "rf_experiment_configuration": (
            DOWNSTREAM_EXPERIMENT_FINAL_DIR /
            "rf_imbalance_experiment_config.json"
        ),
        "lstm_experiment_configuration": (
            DOWNSTREAM_EXPERIMENT_FINAL_DIR /
            "lstm_imbalance_experiment_config.json"
        ),
        "experiment_design_metadata": (
            DOWNSTREAM_EXPERIMENT_FINAL_DIR /
            "imbalance_experiment_design_metadata.json"
        )
    }
}


# ------------------------------------------------------------
# Check all registered artifacts
# ------------------------------------------------------------

print("\n[PERSISTED ARTIFACT INVENTORY]")

artifact_status = {}
missing_artifacts = []

for artifact_group, artifacts in FINAL_ARTIFACT_INVENTORY.items():

    print(f"\n[{artifact_group.upper()}]")

    for artifact_name, artifact_path in artifacts.items():

        artifact_path = Path(artifact_path)
        exists = artifact_path.is_file()

        key = f"{artifact_group}/{artifact_name}"
        artifact_status[key] = exists

        if exists:
            print(
                f"✓ {artifact_name}: "
                f"{artifact_path.name}"
            )
        else:
            print(
                f"✗ {artifact_name}: MISSING"
            )

            missing_artifacts.append(
                f"{key}: {artifact_path}"
            )


# ------------------------------------------------------------
# Inventory validation
# ------------------------------------------------------------

if missing_artifacts:
    raise FileNotFoundError(
        "Required final artifacts are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_artifacts
        )
    )

print("\n[INVENTORY VALIDATION]")
print(
    f"✓ Total registered artifacts: "
    f"{len(artifact_status)}"
)
print("✓ All registered artifacts are present")


# ------------------------------------------------------------
# Final taxonomy boundary
# ------------------------------------------------------------

if len(FINAL_CLASS_ID_MAPPING) != 9:
    raise ValueError(
        "Expected the established nine-class taxonomy, "
        f"but found {len(FINAL_CLASS_ID_MAPPING)} classes."
    )

print("\n[TAXONOMY BOUNDARY]")
print("✓ Final nine-class taxonomy preserved")
print("✓ No label modification performed")


# ------------------------------------------------------------
# Final feature boundary
# ------------------------------------------------------------

if EXPECTED_FINAL_FEATURE_COUNT != 32:
    raise ValueError(
        "Expected 32 final model-ready features, "
        f"but found {EXPECTED_FINAL_FEATURE_COUNT}."
    )

print("\n[FEATURE BOUNDARY]")
print("✓ Final 32-feature representation preserved")
print("✓ No feature-selection operation performed")
print("✓ No feature-order modification performed")


# ------------------------------------------------------------
# Partition boundary
# ------------------------------------------------------------

print("\n[PARTITION BOUNDARY]")

for partition_name, partition_path in REQUIRED_PARTITION_ARTIFACTS.items():

    partition_path = Path(partition_path)

    if not partition_path.is_file():
        raise FileNotFoundError(
            f"Registered {partition_name} partition artifact "
            f"is missing:\n{partition_path}"
        )

    print(
        f"✓ {partition_name.capitalize()} partition artifact found"
    )

print("✓ Partition indices were not modified")
print("✓ Independent test partition remains protected")


# ------------------------------------------------------------
# Persistence boundary metadata
# ------------------------------------------------------------

FINAL_PERSISTENCE_BOUNDARY = {
    "notebook": "N04",
    "section": "4.10.1",
    "title": "Final Artifact Inventory & Persistence Boundary",

    "random_seed": int(RANDOM_SEED),

    "final_taxonomy": {
        "class_count": len(FINAL_CLASS_ID_MAPPING),
        "class_ids": sorted(
            FINAL_CLASS_ID_MAPPING.values()
        )
    },

    "final_feature_count": int(
        EXPECTED_FINAL_FEATURE_COUNT
    ),

    "artifact_group_count": len(
        FINAL_ARTIFACT_INVENTORY
    ),

    "artifact_count": len(
        artifact_status
    ),

    "large_arrays_loaded": False,
    "stage1_dataset_reloaded": False,

    "feature_selection_performed": False,
    "scaling_performed": False,
    "resampling_performed": False,
    "smote_performed": False,
    "class_weighting_performed": False,
    "model_fitting_performed": False,

    "partition_indices_modified": False,
    "validation_modified": False,
    "independent_test_modified": False,

    "target_arrays_persisted_here": False,

    "next_subsection":
        "4.10.2 — Final Model-Ready Target Artifact Persistence"
}


# ------------------------------------------------------------
# Persist final inventory record
# ------------------------------------------------------------

FINAL_ARTIFACT_INVENTORY_PATH = (
    MODEL_PREPARATION_V2_DIR /
    "final_artifact_inventory.json"
)

inventory_record = {
    "persistence_boundary":
        FINAL_PERSISTENCE_BOUNDARY,

    "artifact_inventory": {
        group: {
            name: str(path)
            for name, path in artifacts.items()
        }
        for group, artifacts
        in FINAL_ARTIFACT_INVENTORY.items()
    },

    "artifact_status": artifact_status
}

with open(
    FINAL_ARTIFACT_INVENTORY_PATH,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        inventory_record,
        f,
        indent=2
    )


# ------------------------------------------------------------
# Completion
# ------------------------------------------------------------

print("\n[FINAL PERSISTENCE BOUNDARY]")
print(
    "✓ Final N04 artifact inventory persisted:"
)
print(
    f"  {FINAL_ARTIFACT_INVENTORY_PATH}"
)

print("✓ No large arrays loaded")
print("✓ No Stage-1 dataset reloaded")
print("✓ No feature values modified")
print("✓ No partition indices modified")
print("✓ No validation/test data modified")
print("✓ No resampling performed")
print("✓ No model fitting performed")

print("\n" + "=" * 72)
print(
    "4.10.1 final artifact inventory and "
    "persistence boundary completed successfully."
)
print("=" * 72)

========================================================================
4.10.1 — FINAL ARTIFACT INVENTORY & PERSISTENCE BOUNDARY
========================================================================

[EXISTING N04 STATE]
✓ Model-preparation output directory available
✓ Random seed available
✓ Final taxonomy available
✓ Final feature-count configuration available
✓ Partition artifact registry available

[PERSISTED ARTIFACT INVENTORY]

[TAXONOMY]
✓ taxonomy_mapping: taxonomy_mapping.csv
✓ final_class_distribution: final_class_distribution.csv
✓ taxonomy_metadata: taxonomy_metadata.json

[PARTITIONING]
✓ development_indices: development_indices.npy
✓ training_indices: training_indices.npy
✓ validation_indices: validation_indices.npy
✓ test_indices: test_indices.npy

[FEATURE_SELECTION]
✓ final_feature_set_validation: final_feature_set_validation.json
✓ selected_features: correlation_pruned_selected_features.json

[FEATURE_SCALING]
✓ training_scaled_data: X_train_scaled.npy
✓ validation_scaled_data: X_validation_scaled.npy
✓ test_scaled_data: X_test_scaled.npy
✓ training_only_scaler: training_only_standard_scaler.joblib
✓ scaler_metadata: training_only_scaler_metadata.json
✓ transformation_metadata: partition_wise_transformation_metadata.json
✓ model_ready_metadata: model_ready_feature_artifacts.json
✓ final_scaling_validation: final_scaling_reproducibility_validation.json

[CLASS_IMBALANCE]
✓ training_distribution: training_only_class_distribution.csv
✓ validation_distribution: validation_class_distribution.csv
✓ test_distribution: test_class_distribution.csv
✓ class_imbalance_summary: class_imbalance_summary.csv
✓ minority_support_analysis: minority_support_analysis.csv
✓ class_imbalance_severity_metadata: class_imbalance_severity_metadata.json

[DOWNSTREAM_IMBALANCE_EXPERIMENTS]
✓ experiment_matrix: imbalance_experiment_matrix.csv
✓ rf_experiment_configuration: rf_imbalance_experiment_config.json
✓ lstm_experiment_configuration: lstm_imbalance_experiment_config.json
✓ experiment_design_metadata: imbalance_experiment_design_metadata.json

[INVENTORY VALIDATION]
✓ Total registered artifacts: 27
✓ All registered artifacts are present

[TAXONOMY BOUNDARY]
✓ Final nine-class taxonomy preserved
✓ No label modification performed

[FEATURE BOUNDARY]
✓ Final 32-feature representation preserved
✓ No feature-selection operation performed
✓ No feature-order modification performed

[PARTITION BOUNDARY]
✓ Development_indices partition artifact found
✓ Test_indices partition artifact found
✓ Training_indices partition artifact found
✓ Validation_indices partition artifact found
✓ Partition indices were not modified
✓ Independent test partition remains protected

[FINAL PERSISTENCE BOUNDARY]
✓ Final N04 artifact inventory persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/final_artifact_inventory.json
✓ No large arrays loaded
✓ No Stage-1 dataset reloaded
✓ No feature values modified
✓ No partition indices modified
✓ No validation/test data modified
✓ No resampling performed
✓ No model fitting performed

========================================================================
4.10.1 final artifact inventory and persistence boundary completed successfully.
========================================================================

## 4.10.2 — Final Model-Ready Target Artifact Persistence

This subsection persists the finalized target arrays corresponding to the
Training, Validation, and independent Test partitions established earlier in
Notebook 04.

The target arrays are taken directly from the validated final `FinalTarget`
representation and the fixed partition assignments used throughout the
model-preparation pipeline.

The persisted targets preserve the exact row ordering associated with the
model-ready feature matrices and maintain the established nine-class taxonomy.

No target values are modified, remapped, resampled, or reordered in this
subsection. The independent Test target remains unchanged and is persisted
only as the corresponding evaluation target for the fixed Test partition.

The target artifacts are stored separately from the feature matrices so that
downstream Random Forest and LSTM notebooks can recover the complete
model-ready Training, Validation, and Test data contract without reloading
the large Stage-1 dataset.

This subsection performs persistence and integrity validation only. No model
fitting, feature transformation, partition modification, resampling, or
class-weighting operation is performed.

In [39]:
# ============================================================
# 4.10.2 — FINAL MODEL-READY TARGET ARTIFACT PERSISTENCE
# ============================================================

import json
from pathlib import Path
import numpy as np

print("=" * 72)
print("4.10.2 — FINAL MODEL-READY TARGET ARTIFACT PERSISTENCE")
print("=" * 72)


# ------------------------------------------------------------
# Existing N04 state validation
# ------------------------------------------------------------

required_state = [
    "MODEL_PREPARATION_V2_DIR",
    "RANDOM_SEED",
    "FINAL_CLASS_ID_MAPPING",
    "EXPECTED_FINAL_FEATURE_COUNT",
    "REQUIRED_PARTITION_ARTIFACTS",
    "training_labels",
    "validation_labels",
    "test_labels",
]

missing_state = [
    name for name in required_state
    if name not in globals()
]

if missing_state:
    raise NameError(
        "Required validated N04 state is missing:\n"
        + "\n".join(
            f"  - {name}"
            for name in missing_state
        )
        + "\n\n"
        "Run the existing N04 recovery/setup and "
        "Sections 4.8.2–4.8.3 before continuing "
        "with Section 4.10.2."
    )


print("\n[EXISTING N04 TARGET STATE]")
print("✓ Training labels available")
print("✓ Validation labels available")
print("✓ Test labels available")
print("✓ Final taxonomy available")
print("✓ Partition artifact registry available")


# ------------------------------------------------------------
# Final target artifact directory
# ------------------------------------------------------------

TARGET_ARTIFACT_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "model_ready_targets"
)

TARGET_ARTIFACT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ------------------------------------------------------------
# Target artifact paths
# ------------------------------------------------------------

TRAINING_TARGET_PATH = (
    TARGET_ARTIFACT_DIR /
    "y_train.npy"
)

VALIDATION_TARGET_PATH = (
    TARGET_ARTIFACT_DIR /
    "y_validation.npy"
)

TEST_TARGET_PATH = (
    TARGET_ARTIFACT_DIR /
    "y_test.npy"
)

TARGET_METADATA_PATH = (
    TARGET_ARTIFACT_DIR /
    "target_artifact_metadata.json"
)


# ------------------------------------------------------------
# Convert validated targets to explicit NumPy arrays
# ------------------------------------------------------------

training_targets = np.asarray(
    training_labels,
    dtype=np.int64
)

validation_targets = np.asarray(
    validation_labels,
    dtype=np.int64
)

test_targets = np.asarray(
    test_labels,
    dtype=np.int64
)


# ------------------------------------------------------------
# Final taxonomy boundary
# ------------------------------------------------------------

final_class_ids = sorted(
    int(value)
    for value in FINAL_CLASS_ID_MAPPING.values()
)

expected_class_count = len(
    final_class_ids
)

if expected_class_count != 9:
    raise ValueError(
        "Expected the established nine-class taxonomy, "
        f"but found {expected_class_count} classes."
    )

expected_class_ids = list(
    range(expected_class_count)
)

if final_class_ids != expected_class_ids:
    raise ValueError(
        "Final class IDs are not contiguous from 0 to 8.\n"
        f"Observed: {final_class_ids}"
    )


# ------------------------------------------------------------
# Target integrity validation
# ------------------------------------------------------------

target_partitions = {
    "Training": training_targets,
    "Validation": validation_targets,
    "Test": test_targets,
}

print("\n[TARGET INTEGRITY VALIDATION]")

for partition_name, targets in target_partitions.items():

    if targets.ndim != 1:
        raise ValueError(
            f"{partition_name} target array must be one-dimensional. "
            f"Observed shape: {targets.shape}"
        )

    if len(targets) == 0:
        raise ValueError(
            f"{partition_name} target array is empty."
        )

    if not np.issubdtype(
        targets.dtype,
        np.integer
    ):
        raise TypeError(
            f"{partition_name} target array is not integer-valued."
        )

    if not np.all(
        np.isin(
            targets,
            expected_class_ids
        )
    ):
        invalid_values = np.unique(
            targets[
                ~np.isin(
                    targets,
                    expected_class_ids
                )
            ]
        )

        raise ValueError(
            f"{partition_name} target array contains "
            f"class IDs outside the final taxonomy: "
            f"{invalid_values.tolist()}"
        )

    print(
        f"✓ {partition_name} targets are valid "
        f"one-dimensional integer class IDs"
    )


# ------------------------------------------------------------
# Verify target counts against established partitions
# ------------------------------------------------------------

expected_partition_sizes = {
    "Training": 1_814_018,
    "Validation": 451_215,
    "Test": 565_510,
}

print("\n[PARTITION TARGET COUNTS]")

for partition_name, targets in target_partitions.items():

    expected_count = expected_partition_sizes[
        partition_name
    ]

    actual_count = len(targets)

    if actual_count != expected_count:
        raise ValueError(
            f"{partition_name} target count mismatch: "
            f"{actual_count:,} != {expected_count:,}"
        )

    print(
        f"✓ {partition_name}: "
        f"{actual_count:,} target values"
    )


# ------------------------------------------------------------
# Validate target class coverage
# ------------------------------------------------------------

print("\n[CLASS COVERAGE]")

for partition_name, targets in target_partitions.items():

    observed_classes = sorted(
        int(class_id)
        for class_id in np.unique(targets)
    )

    if observed_classes != expected_class_ids:
        raise ValueError(
            f"{partition_name} does not contain "
            "the complete established nine-class taxonomy.\n"
            f"Expected: {expected_class_ids}\n"
            f"Observed: {observed_classes}"
        )

    print(
        f"✓ {partition_name} contains all nine final classes"
    )


# ------------------------------------------------------------
# Persist target arrays
# ------------------------------------------------------------

np.save(
    TRAINING_TARGET_PATH,
    training_targets
)

np.save(
    VALIDATION_TARGET_PATH,
    validation_targets
)

np.save(
    TEST_TARGET_PATH,
    test_targets
)


# ------------------------------------------------------------
# Confirm persisted target artifacts
# ------------------------------------------------------------

required_target_artifacts = {
    "Training targets": TRAINING_TARGET_PATH,
    "Validation targets": VALIDATION_TARGET_PATH,
    "Test targets": TEST_TARGET_PATH,
}

missing_target_artifacts = [
    name
    for name, path in required_target_artifacts.items()
    if not path.is_file()
]

if missing_target_artifacts:
    raise FileNotFoundError(
        "Target artifacts were not persisted correctly:\n"
        + "\n".join(
            f"  - {name}"
            for name in missing_target_artifacts
        )
    )

print("\n[PERSISTED TARGET ARTIFACTS]")

for name, path in required_target_artifacts.items():
    print(
        f"✓ {name}: {path.name}"
    )


# ------------------------------------------------------------
# Reload persisted targets for independent validation
# ------------------------------------------------------------

reloaded_training_targets = np.load(
    TRAINING_TARGET_PATH
)

reloaded_validation_targets = np.load(
    VALIDATION_TARGET_PATH
)

reloaded_test_targets = np.load(
    TEST_TARGET_PATH
)


# ------------------------------------------------------------
# Reload validation
# ------------------------------------------------------------

print("\n[RELOAD VALIDATION]")

reload_pairs = {
    "Training": (
        training_targets,
        reloaded_training_targets
    ),
    "Validation": (
        validation_targets,
        reloaded_validation_targets
    ),
    "Test": (
        test_targets,
        reloaded_test_targets
    ),
}

for partition_name, (
    original_targets,
    reloaded_targets
) in reload_pairs.items():

    if original_targets.shape != reloaded_targets.shape:
        raise ValueError(
            f"{partition_name} target shape changed "
            "after persistence."
        )

    if not np.array_equal(
        original_targets,
        reloaded_targets
    ):
        raise ValueError(
            f"{partition_name} target values changed "
            "after persistence."
        )

    print(
        f"✓ {partition_name} targets reload "
        "identically"
    )


# ------------------------------------------------------------
# Target distribution metadata
# ------------------------------------------------------------

target_distribution = {}

for partition_name, targets in target_partitions.items():

    counts = np.bincount(
        targets,
        minlength=expected_class_count
    )

    target_distribution[
        partition_name.lower()
    ] = {
        str(class_id): int(
            counts[class_id]
        )
        for class_id in expected_class_ids
    }


# ------------------------------------------------------------
# Persist target artifact metadata
# ------------------------------------------------------------

target_artifact_metadata = {

    "notebook": "N04",

    "section": "4.10.2",

    "title":
        "Final Model-Ready Target Artifact Persistence",

    "status":
        "completed",

    "target_column":
        "FinalTarget",

    "taxonomy": {
        "class_count":
            expected_class_count,

        "class_ids":
            expected_class_ids,

        "class_mapping":
            {
                str(key): str(value)
                for key, value
                in FINAL_CLASS_ID_MAPPING.items()
            }
    },

    "target_artifacts": {
        "training":
            str(TRAINING_TARGET_PATH),

        "validation":
            str(VALIDATION_TARGET_PATH),

        "test":
            str(TEST_TARGET_PATH)
    },

    "partition_sizes": {
        "training":
            int(len(training_targets)),

        "validation":
            int(len(validation_targets)),

        "test":
            int(len(test_targets))
    },

    "target_distribution":
        target_distribution,

    "source": {
        "training_source":
            "Validated training_labels from N04 Section 4.8.2",

        "validation_source":
            "Validated validation_labels from N04 Section 4.8.3",

        "test_source":
            "Validated test_labels from N04 Section 4.8.3",

        "partition_indices_modified":
            False
    },

    "integrity": {
        "labels_modified":
            False,

        "labels_remapped":
            False,

        "labels_reordered":
            False,

        "resampling_performed":
            False,

        "class_weighting_performed":
            False,

        "feature_transformation_performed":
            False,

        "partition_modification_performed":
            False,

        "model_fitting_performed":
            False,

        "stage1_dataset_reloaded":
            False
    },

    "reproducibility": {
        "training_targets_reload_verified":
            True,

        "validation_targets_reload_verified":
            True,

        "test_targets_reload_verified":
            True,

        "taxonomy_verified":
            True,

        "partition_sizes_verified":
            True,

        "class_coverage_verified":
            True
    }
}


with open(
    TARGET_METADATA_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        target_artifact_metadata,
        f,
        indent=2
    )


# ------------------------------------------------------------
# Final metadata artifact validation
# ------------------------------------------------------------

if not TARGET_METADATA_PATH.is_file():
    raise FileNotFoundError(
        "Target artifact metadata was not persisted:\n"
        f"{TARGET_METADATA_PATH}"
    )


print("\n[TARGET ARTIFACT METADATA]")
print(
    f"✓ {TARGET_METADATA_PATH}"
)


# ------------------------------------------------------------
# Final boundary confirmation
# ------------------------------------------------------------

print("\n[FINAL TARGET PERSISTENCE BOUNDARY]")

print("✓ FinalTarget values preserved")
print("✓ Nine-class taxonomy preserved")
print("✓ Training target count preserved")
print("✓ Validation target count preserved")
print("✓ Independent Test target count preserved")
print("✓ Target ordering preserved")
print("✓ Target values unchanged after reload")
print("✓ Partition assignments not modified")
print("✓ No resampling performed")
print("✓ No class weighting performed")
print("✓ No feature transformation performed")
print("✓ No model fitting performed")
print("✓ No Stage-1 dataset reloaded")


# ------------------------------------------------------------
# Completion
# ------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "4.10.2 final model-ready target artifact persistence "
    "completed successfully."
)

print("=" * 72)

========================================================================
4.10.2 — FINAL MODEL-READY TARGET ARTIFACT PERSISTENCE
========================================================================

[EXISTING N04 TARGET STATE]
✓ Training labels available
✓ Validation labels available
✓ Test labels available
✓ Final taxonomy available
✓ Partition artifact registry available

[TARGET INTEGRITY VALIDATION]
✓ Training targets are valid one-dimensional integer class IDs
✓ Validation targets are valid one-dimensional integer class IDs
✓ Test targets are valid one-dimensional integer class IDs

[PARTITION TARGET COUNTS]
✓ Training: 1,814,018 target values
✓ Validation: 451,215 target values
✓ Test: 565,510 target values

[CLASS COVERAGE]
✓ Training contains all nine final classes
✓ Validation contains all nine final classes
✓ Test contains all nine final classes

[PERSISTED TARGET ARTIFACTS]
✓ Training targets: y_train.npy
✓ Validation targets: y_validation.npy
✓ Test targets: y_test.npy

[RELOAD VALIDATION]
✓ Training targets reload identically
✓ Validation targets reload identically
✓ Test targets reload identically

[TARGET ARTIFACT METADATA]
✓ /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/model_ready_targets/target_artifact_metadata.json

[FINAL TARGET PERSISTENCE BOUNDARY]
✓ FinalTarget values preserved
✓ Nine-class taxonomy preserved
✓ Training target count preserved
✓ Validation target count preserved
✓ Independent Test target count preserved
✓ Target ordering preserved
✓ Target values unchanged after reload
✓ Partition assignments not modified
✓ No resampling performed
✓ No class weighting performed
✓ No feature transformation performed
✓ No model fitting performed
✓ No Stage-1 dataset reloaded

========================================================================
4.10.2 final model-ready target artifact persistence completed successfully.
========================================================================

## 4.10.3 — Final Metadata & Configuration Consolidation

This subsection consolidates the validated metadata and configuration records
produced throughout Notebook 04 into a single final model-preparation metadata
record.

The consolidated record provides a recovery-oriented description of the final
N04 state, including the established taxonomy, leakage-controlled partitioning,
feature-selection and scaling configuration, class-imbalance analysis,
downstream imbalance-experiment design, and persisted model-ready target
artifacts.

Only previously persisted metadata and configuration artifacts are read and
consolidated. No large feature arrays or the Stage-1 dataset are loaded.

No preprocessing, feature selection, scaling, resampling, class weighting,
model fitting, partition modification, or target modification is performed.

The independent Test partition remains isolated, and all downstream model
experiments continue to use the fixed model-preparation artifacts established
by this notebook.

The resulting consolidated metadata record provides a single recovery point
for downstream Random Forest and LSTM model-training notebooks.

In [41]:
# ============================================================
# 4.10.3 — FINAL METADATA & CONFIGURATION CONSOLIDATION
# ============================================================

import json
from pathlib import Path

print("=" * 72)
print("4.10.3 — FINAL METADATA & CONFIGURATION CONSOLIDATION")
print("=" * 72)


# ------------------------------------------------------------
# Existing N04 state validation
# ------------------------------------------------------------

required_state = [
    "MODEL_PREPARATION_V2_DIR",
    "RANDOM_SEED",
    "FINAL_CLASS_ID_MAPPING",
    "EXPECTED_FINAL_FEATURE_COUNT",
    "FINAL_ARTIFACT_INVENTORY",
    "FINAL_ARTIFACT_INVENTORY_PATH",
    "TARGET_METADATA_PATH",
]

missing_state = [
    name
    for name in required_state
    if name not in globals()
]

if missing_state:
    raise NameError(
        "Required N04 state from Sections 4.10.1–4.10.2 "
        "is missing:\n"
        + "\n".join(
            f"  - {name}"
            for name in missing_state
        )
        + "\n\n"
        "Run Sections 4.10.1 and 4.10.2 before "
        "continuing with Section 4.10.3."
    )

print("\n[EXISTING N04 STATE]")
print("✓ Model-preparation output directory available")
print("✓ Final taxonomy available")
print("✓ Final feature-count configuration available")
print("✓ Final artifact inventory available")
print("✓ Final target metadata available")


# ------------------------------------------------------------
# Resolve established metadata/configuration directories
# ------------------------------------------------------------

TAXONOMY_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "taxonomy"
)

PARTITION_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "duplicate_leakage_audit"
)

FEATURE_SELECTION_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "feature_selection"
)

FEATURE_SCALING_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "feature_scaling"
)

CLASS_IMBALANCE_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "class_imbalance"
)

DOWNSTREAM_IMBALANCE_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "downstream_imbalance_experiments"
)

MODEL_READY_TARGET_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "model_ready_targets"
)


# ------------------------------------------------------------
# Existing metadata/configuration artifacts
#
# Only small JSON files are read.
# No feature matrices are loaded.
# ------------------------------------------------------------

METADATA_CONFIGURATION_PATHS = {

    "taxonomy_metadata": (
        TAXONOMY_DIR /
        "taxonomy_metadata.json"
    ),

    "partition_reproducibility_metadata": (
        MODEL_PREPARATION_V2_DIR /
        "partition_reproducibility_metadata.json"
    ),

    "final_leakage_validation": (
        MODEL_PREPARATION_V2_DIR /
        "final_train_validation_test_leakage_validation.json"
    ),

    "feature_set_validation": (
        FEATURE_SELECTION_DIR /
        "final_feature_set_validation.json"
    ),

    "scaler_metadata": (
        FEATURE_SCALING_DIR /
        "training_only_scaler_metadata.json"
    ),

    "transformation_metadata": (
        FEATURE_SCALING_DIR /
        "partition_wise_transformation_metadata.json"
    ),

    "model_ready_feature_metadata": (
        FEATURE_SCALING_DIR /
        "model_ready_feature_artifacts.json"
    ),

    "final_scaling_validation": (
        FEATURE_SCALING_DIR /
        "final_scaling_reproducibility_validation.json"
    ),

    "class_imbalance_severity_metadata": (
        CLASS_IMBALANCE_DIR /
        "class_imbalance_severity_metadata.json"
    ),

    "class_imbalance_configuration": (
        CLASS_IMBALANCE_DIR /
        "class_imbalance_configuration.json"
    ),

    "imbalance_experiment_design_metadata": (
        DOWNSTREAM_IMBALANCE_DIR /
        "imbalance_experiment_design_metadata.json"
    ),

    "rf_imbalance_experiment_configuration": (
        DOWNSTREAM_IMBALANCE_DIR /
        "rf_imbalance_experiment_config.json"
    ),

    "lstm_imbalance_experiment_configuration": (
        DOWNSTREAM_IMBALANCE_DIR /
        "lstm_imbalance_experiment_config.json"
    ),

    "target_artifact_metadata": (
        MODEL_READY_TARGET_DIR /
        "target_artifact_metadata.json"
    ),

    "final_artifact_inventory": (
        FINAL_ARTIFACT_INVENTORY_PATH
    ),
}


# ------------------------------------------------------------
# Validate metadata/configuration artifacts
# ------------------------------------------------------------

print("\n[METADATA & CONFIGURATION ARTIFACT CHECK]")

missing_metadata = []

for artifact_name, artifact_path in (
    METADATA_CONFIGURATION_PATHS.items()
):

    artifact_path = Path(artifact_path)

    if not artifact_path.is_file():

        missing_metadata.append(
            f"{artifact_name}: {artifact_path}"
        )

    else:

        print(
            f"✓ {artifact_name}: "
            f"{artifact_path.name}"
        )


if missing_metadata:

    raise FileNotFoundError(
        "Required metadata/configuration artifacts are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_metadata
        )
    )


# ------------------------------------------------------------
# JSON loading helper
# ------------------------------------------------------------

def load_json_metadata(
    artifact_name,
    artifact_path
):

    with open(
        artifact_path,
        "r",
        encoding="utf-8"
    ) as f:

        data = json.load(f)

    if not isinstance(data, dict):

        raise ValueError(
            f"{artifact_name} must contain a JSON object."
        )

    return data


# ------------------------------------------------------------
# Load existing metadata/configuration
# ------------------------------------------------------------

print("\n[METADATA & CONFIGURATION RELOAD]")

loaded_metadata = {}

for artifact_name, artifact_path in (
    METADATA_CONFIGURATION_PATHS.items()
):

    loaded_metadata[
        artifact_name
    ] = load_json_metadata(
        artifact_name,
        artifact_path
    )

    print(
        f"✓ {artifact_name} loaded successfully"
    )


# ------------------------------------------------------------
# Final taxonomy validation
# ------------------------------------------------------------

print("\n[FINAL TAXONOMY CONFIGURATION]")

if len(FINAL_CLASS_ID_MAPPING) != 9:

    raise ValueError(
        "Expected the established nine-class taxonomy, "
        f"but found {len(FINAL_CLASS_ID_MAPPING)} classes."
    )


expected_class_ids = list(range(9))

actual_class_ids = sorted(
    int(class_id)
    for class_id in
    FINAL_CLASS_ID_MAPPING.values()
)

if actual_class_ids != expected_class_ids:

    raise ValueError(
        "Final taxonomy class IDs are inconsistent.\n"
        f"Expected: {expected_class_ids}\n"
        f"Observed: {actual_class_ids}"
    )


print("✓ Nine-class taxonomy confirmed")
print("✓ Class IDs 0–8 confirmed")
print("✓ Final taxonomy mapping preserved")


# ------------------------------------------------------------
# Final feature configuration validation
# ------------------------------------------------------------

print("\n[FINAL FEATURE CONFIGURATION]")

if EXPECTED_FINAL_FEATURE_COUNT != 32:

    raise ValueError(
        "Expected 32 final model-ready features, "
        f"but found {EXPECTED_FINAL_FEATURE_COUNT}."
    )


print("✓ Final model-ready feature count: 32")
print("✓ Feature configuration preserved")


# ------------------------------------------------------------
# Partition configuration validation
# ------------------------------------------------------------

print("\n[PARTITION CONFIGURATION]")

partition_metadata = loaded_metadata[
    "partition_reproducibility_metadata"
]

partition_architecture = partition_metadata.get(
    "partition_architecture",
    {}
)

expected_partition_sizes = {
    "development": 2_265_233,
    "training": 1_814_018,
    "validation": 451_215,
    "test": 565_510,
}

for partition_name, expected_size in (
    expected_partition_sizes.items()
):

    size_key = f"{partition_name}_rows"

    if size_key not in partition_architecture:
        raise ValueError(
            "Partition metadata does not contain "
            f"'{size_key}'."
        )

    actual_size = int(
        partition_architecture[size_key]
    )

    if actual_size != expected_size:
        raise ValueError(
            f"{partition_name.capitalize()} partition size mismatch: "
            f"expected {expected_size:,}, "
            f"found {actual_size:,}"
        )

    print(
        f"✓ {partition_name.capitalize()} partition: "
        f"{actual_size:,} rows"
    )

print("✓ Partition configuration consistent")


# ------------------------------------------------------------
# Test-isolation configuration validation
# ------------------------------------------------------------

print("\n[TEST ISOLATION CONFIGURATION]")

leakage_metadata = loaded_metadata[
    "final_leakage_validation"
]

if leakage_metadata.get(
    "validation_status"
) != "PASSED":

    raise ValueError(
        "Final train/validation/test leakage validation "
        "was not recorded as PASSED."
    )


leakage_control = partition_metadata.get(
    "leakage_control",
    {}
)

if leakage_control.get(
    "test_partition_isolated"
) is not True:

    raise ValueError(
        "Partition metadata does not confirm "
        "independent Test isolation."
    )


print("✓ Final leakage validation status: PASSED")
print("✓ Independent Test partition remains isolated")


# ------------------------------------------------------------
# Feature-scaling configuration validation
# ------------------------------------------------------------

print("\n[FEATURE-SCALING CONFIGURATION]")

scaler_metadata = loaded_metadata[
    "scaler_metadata"
]

transformation_metadata = loaded_metadata[
    "transformation_metadata"
]

scaling_validation = loaded_metadata[
    "final_scaling_validation"
]

print("✓ Training-only scaler metadata recovered")
print("✓ Partition-wise transformation metadata recovered")
print("✓ Final scaling validation metadata recovered")


# ------------------------------------------------------------
# Class-imbalance configuration validation
# ------------------------------------------------------------

print("\n[CLASS-IMBALANCE CONFIGURATION]")

imbalance_configuration = loaded_metadata[
    "class_imbalance_configuration"
]

imbalance_severity = loaded_metadata[
    "class_imbalance_severity_metadata"
]

print("✓ Class-imbalance configuration recovered")
print("✓ Class-imbalance severity metadata recovered")


# ------------------------------------------------------------
# Downstream experiment configuration validation
# ------------------------------------------------------------

print("\n[DOWNSTREAM EXPERIMENT CONFIGURATION]")

experiment_metadata = loaded_metadata[
    "imbalance_experiment_design_metadata"
]

rf_configuration = loaded_metadata[
    "rf_imbalance_experiment_configuration"
]

lstm_configuration = loaded_metadata[
    "lstm_imbalance_experiment_configuration"
]

if rf_configuration.get(
    "candidate_count"
) != 5:

    raise ValueError(
        "Random Forest experiment configuration "
        "does not contain five candidate strategies."
    )


if lstm_configuration.get(
    "candidate_count"
) != 5:

    raise ValueError(
        "LSTM experiment configuration "
        "does not contain five candidate strategies."
    )


print("✓ Five Random Forest candidates configured")
print("✓ Five LSTM candidates configured")
print("✓ Ten downstream imbalance candidates configured")
print("✓ No strategy selection performed at this stage")


# ------------------------------------------------------------
# Target artifact configuration validation
# ------------------------------------------------------------

print("\n[MODEL-READY TARGET CONFIGURATION]")

target_metadata = loaded_metadata[
    "target_artifact_metadata"
]

target_taxonomy = target_metadata.get(
    "taxonomy",
    {}
)

if target_taxonomy.get(
    "class_count"
) != 9:

    raise ValueError(
        "Target artifact metadata does not confirm "
        "the established nine-class taxonomy."
    )


target_partition_sizes = target_metadata.get(
    "partition_sizes",
    {}
)

for partition_name, expected_size in {
    "training": 1_814_018,
    "validation": 451_215,
    "test": 565_510
}.items():

    actual_size = int(
        target_partition_sizes.get(
            partition_name,
            -1
        )
    )

    if actual_size != expected_size:

        raise ValueError(
            f"Target artifact size mismatch for "
            f"{partition_name}: "
            f"expected {expected_size:,}, "
            f"found {actual_size:,}"
        )


print("✓ Training target configuration verified")
print("✓ Validation target configuration verified")
print("✓ Test target configuration verified")
print("✓ Target taxonomy consistent with final N04 taxonomy")


# ------------------------------------------------------------
# Build consolidated N04 metadata/configuration record
# ------------------------------------------------------------

FINAL_MODEL_PREPARATION_METADATA = {

    "notebook": "N04",

    "section": "4.10.3",

    "title":
        "Final Metadata & Configuration Consolidation",

    "status":
        "completed",

    "purpose":
        "Consolidated recovery metadata for the finalized "
        "N04 model-preparation state.",

    "random_seed":
        int(RANDOM_SEED),

    "final_taxonomy": {
        "class_count":
            len(FINAL_CLASS_ID_MAPPING),

        "class_id_mapping":
            {
                str(class_name): int(class_id)
                for class_name, class_id
                in FINAL_CLASS_ID_MAPPING.items()
            }
    },

    "final_feature_configuration": {
        "feature_count":
            int(EXPECTED_FINAL_FEATURE_COUNT),

        "feature_selection_training_only":
            True,

        "correlation_pruning_training_only":
            True,

        "scaling_training_only_fit":
            True
    },

    "partition_configuration": {
        "development_rows":
            expected_partition_sizes["development"],

        "training_rows":
            expected_partition_sizes["training"],

        "validation_rows":
            expected_partition_sizes["validation"],

        "test_rows":
            expected_partition_sizes["test"],

        "independent_test_isolated":
            True,

        "partition_indices_modified_in_4_10":
            False
    },

    "model_ready_targets": {
        "training_target":
            str(
                MODEL_READY_TARGET_DIR /
                "y_train.npy"
            ),

        "validation_target":
            str(
                MODEL_READY_TARGET_DIR /
                "y_validation.npy"
            ),

        "test_target":
            str(
                MODEL_READY_TARGET_DIR /
                "y_test.npy"
            ),

        "target_metadata":
            str(
                MODEL_READY_TARGET_DIR /
                "target_artifact_metadata.json"
            )
    },

    "downstream_experiment_configuration": {
        "random_forest_candidate_count":
            int(
                rf_configuration[
                    "candidate_count"
                ]
            ),

        "lstm_candidate_count":
            int(
                lstm_configuration[
                    "candidate_count"
                ]
            ),

        "total_candidate_count":
            int(
                rf_configuration[
                    "candidate_count"
                ]
                +
                lstm_configuration[
                    "candidate_count"
                ]
            ),

        "strategy_selection_partition":
            "Validation",

        "final_evaluation_partition":
            "Independent Test",

        "optimal_strategy_declared":
            False
    },

    "artifact_references": {
        name: str(path)
        for name, path
        in METADATA_CONFIGURATION_PATHS.items()
    },

    "processing_boundary": {

        "large_arrays_loaded":
            False,

        "stage1_dataset_reloaded":
            False,

        "feature_selection_performed":
            False,

        "scaling_performed":
            False,

        "resampling_performed":
            False,

        "smote_performed":
            False,

        "class_weighting_performed":
            False,

        "model_fitting_performed":
            False,

        "partition_indices_modified":
            False,

        "target_values_modified":
            False,

        "validation_modified":
            False,

        "independent_test_modified":
            False
    },

    "validation_status": {
        "taxonomy_verified":
            True,

        "feature_configuration_verified":
            True,

        "partition_configuration_verified":
            True,

        "test_isolation_verified":
            True,

        "target_artifacts_verified":
            True,

        "downstream_experiment_configuration_verified":
            True
    },

    "source_metadata_consolidated": [
        name
        for name in METADATA_CONFIGURATION_PATHS.keys()
    ],

    "next_subsection":
        "4.10.4 — Final Artifact Manifest & Integrity Metadata"
}


# ------------------------------------------------------------
# Persist consolidated metadata
# ------------------------------------------------------------

FINAL_MODEL_PREPARATION_METADATA_PATH = (
    MODEL_PREPARATION_V2_DIR /
    "final_model_preparation_metadata.json"
)

with open(
    FINAL_MODEL_PREPARATION_METADATA_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        FINAL_MODEL_PREPARATION_METADATA,
        f,
        indent=4
    )


# ------------------------------------------------------------
# Reload consolidated metadata
# ------------------------------------------------------------

print("\n[CONSOLIDATED METADATA RELOAD]")

with open(
    FINAL_MODEL_PREPARATION_METADATA_PATH,
    "r",
    encoding="utf-8"
) as f:

    reloaded_final_metadata = json.load(f)


if reloaded_final_metadata != (
    FINAL_MODEL_PREPARATION_METADATA
):

    raise ValueError(
        "Reloaded consolidated metadata does not "
        "match the persisted metadata."
    )


print(
    "✓ Consolidated metadata reloaded successfully"
)

print(
    "✓ Persisted metadata matches in-memory metadata"
)


# ------------------------------------------------------------
# Final completion boundary
# ------------------------------------------------------------

print("\n[FINAL METADATA & CONFIGURATION BOUNDARY]")

print("✓ Taxonomy configuration consolidated")
print("✓ Feature configuration consolidated")
print("✓ Partition configuration consolidated")
print("✓ Test-isolation configuration consolidated")
print("✓ Scaling configuration consolidated")
print("✓ Class-imbalance configuration consolidated")
print("✓ RF experiment configuration consolidated")
print("✓ LSTM experiment configuration consolidated")
print("✓ Model-ready target configuration consolidated")
print("✓ No large arrays loaded")
print("✓ No Stage-1 dataset reloaded")
print("✓ No preprocessing performed")
print("✓ No partition indices modified")
print("✓ No target values modified")
print("✓ No model fitting performed")


print("\n[ARTIFACT]")

print(
    "✓ Final consolidated metadata persisted:"
)

print(
    f"  {FINAL_MODEL_PREPARATION_METADATA_PATH}"
)


# ------------------------------------------------------------
# Completion
# ------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "4.10.3 final metadata and configuration "
    "consolidation completed successfully."
)

print("=" * 72)

========================================================================
4.10.3 — FINAL METADATA & CONFIGURATION CONSOLIDATION
========================================================================

[EXISTING N04 STATE]
✓ Model-preparation output directory available
✓ Final taxonomy available
✓ Final feature-count configuration available
✓ Final artifact inventory available
✓ Final target metadata available

[METADATA & CONFIGURATION ARTIFACT CHECK]
✓ taxonomy_metadata: taxonomy_metadata.json
✓ partition_reproducibility_metadata: partition_reproducibility_metadata.json
✓ final_leakage_validation: final_train_validation_test_leakage_validation.json
✓ feature_set_validation: final_feature_set_validation.json
✓ scaler_metadata: training_only_scaler_metadata.json
✓ transformation_metadata: partition_wise_transformation_metadata.json
✓ model_ready_feature_metadata: model_ready_feature_artifacts.json
✓ final_scaling_validation: final_scaling_reproducibility_validation.json
✓ class_imbalance_severity_metadata: class_imbalance_severity_metadata.json
✓ class_imbalance_configuration: class_imbalance_configuration.json
✓ imbalance_experiment_design_metadata: imbalance_experiment_design_metadata.json
✓ rf_imbalance_experiment_configuration: rf_imbalance_experiment_config.json
✓ lstm_imbalance_experiment_configuration: lstm_imbalance_experiment_config.json
✓ target_artifact_metadata: target_artifact_metadata.json
✓ final_artifact_inventory: final_artifact_inventory.json

[METADATA & CONFIGURATION RELOAD]
✓ taxonomy_metadata loaded successfully
✓ partition_reproducibility_metadata loaded successfully
✓ final_leakage_validation loaded successfully
✓ feature_set_validation loaded successfully
✓ scaler_metadata loaded successfully
✓ transformation_metadata loaded successfully
✓ model_ready_feature_metadata loaded successfully
✓ final_scaling_validation loaded successfully
✓ class_imbalance_severity_metadata loaded successfully
✓ class_imbalance_configuration loaded successfully
✓ imbalance_experiment_design_metadata loaded successfully
✓ rf_imbalance_experiment_configuration loaded successfully
✓ lstm_imbalance_experiment_configuration loaded successfully
✓ target_artifact_metadata loaded successfully
✓ final_artifact_inventory loaded successfully

[FINAL TAXONOMY CONFIGURATION]
✓ Nine-class taxonomy confirmed
✓ Class IDs 0–8 confirmed
✓ Final taxonomy mapping preserved

[FINAL FEATURE CONFIGURATION]
✓ Final model-ready feature count: 32
✓ Feature configuration preserved

[PARTITION CONFIGURATION]
✓ Development partition: 2,265,233 rows
✓ Training partition: 1,814,018 rows
✓ Validation partition: 451,215 rows
✓ Test partition: 565,510 rows
✓ Partition configuration consistent

[TEST ISOLATION CONFIGURATION]
✓ Final leakage validation status: PASSED
✓ Independent Test partition remains isolated

[FEATURE-SCALING CONFIGURATION]
✓ Training-only scaler metadata recovered
✓ Partition-wise transformation metadata recovered
✓ Final scaling validation metadata recovered

[CLASS-IMBALANCE CONFIGURATION]
✓ Class-imbalance configuration recovered
✓ Class-imbalance severity metadata recovered

[DOWNSTREAM EXPERIMENT CONFIGURATION]
✓ Five Random Forest candidates configured
✓ Five LSTM candidates configured
✓ Ten downstream imbalance candidates configured
✓ No strategy selection performed at this stage

[MODEL-READY TARGET CONFIGURATION]
✓ Training target configuration verified
✓ Validation target configuration verified
✓ Test target configuration verified
✓ Target taxonomy consistent with final N04 taxonomy

[CONSOLIDATED METADATA RELOAD]
✓ Consolidated metadata reloaded successfully
✓ Persisted metadata matches in-memory metadata

[FINAL METADATA & CONFIGURATION BOUNDARY]
✓ Taxonomy configuration consolidated
✓ Feature configuration consolidated
✓ Partition configuration consolidated
✓ Test-isolation configuration consolidated
✓ Scaling configuration consolidated
✓ Class-imbalance configuration consolidated
✓ RF experiment configuration consolidated
✓ LSTM experiment configuration consolidated
✓ Model-ready target configuration consolidated
✓ No large arrays loaded
✓ No Stage-1 dataset reloaded
✓ No preprocessing performed
✓ No partition indices modified
✓ No target values modified
✓ No model fitting performed

[ARTIFACT]
✓ Final consolidated metadata persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/final_model_preparation_metadata.json

========================================================================
4.10.3 final metadata and configuration consolidation completed successfully.
========================================================================

## 4.10.4 — Final Artifact Manifest & Integrity Metadata

This subsection establishes the final file-level integrity manifest for the
Notebook 04 model-preparation artifact package.

The manifest records the persisted artifacts that constitute the finalized N04
model-preparation state, including taxonomy, partition, feature-selection,
feature-scaling, class-imbalance, downstream experiment-design, model-ready
target, and consolidated metadata artifacts.

For each artifact, the manifest records its relative path, file size, and
SHA-256 checksum. These integrity values provide a reproducible mechanism for
detecting unintended modification of the model-preparation artifacts before
they are consumed by downstream Random Forest and LSTM experiments.

Large NumPy arrays are processed incrementally in chunks when calculating
checksums. They are not loaded into memory as complete arrays.

The independent Test artifacts are included in the integrity manifest but are
not modified by this subsection.

The manifest itself is excluded from its own checksum calculation to avoid a
recursive integrity dependency.

No preprocessing, feature selection, scaling, resampling, target
modification, partition modification, or model fitting is performed.

In [54]:
# ============================================================
# 4.10.4 — FINAL ARTIFACT MANIFEST & INTEGRITY METADATA
# ============================================================

import hashlib
import json
from pathlib import Path

print("=" * 72)
print("4.10.4 — FINAL ARTIFACT MANIFEST & INTEGRITY METADATA")
print("=" * 72)


# ------------------------------------------------------------
# Existing N04 state validation
# ------------------------------------------------------------

required_state = [
    "MODEL_PREPARATION_V2_DIR",
    "FINAL_ARTIFACT_INVENTORY",
    "FINAL_ARTIFACT_INVENTORY_PATH",
    "TARGET_ARTIFACT_DIR",
    "TARGET_METADATA_PATH",
    "FINAL_MODEL_PREPARATION_METADATA_PATH",
]

missing_state = [
    name
    for name in required_state
    if name not in globals()
]

if missing_state:
    raise NameError(
        "Required N04 state from Sections 4.10.1–4.10.3 "
        "is missing:\n"
        + "\n".join(
            f"  - {name}"
            for name in missing_state
        )
        + "\n\n"
        "Run Sections 4.10.1, 4.10.2, and 4.10.3 "
        "before continuing with Section 4.10.4."
    )

print("\n[EXISTING N04 STATE]")
print("✓ Final artifact inventory available")
print("✓ Final target artifact directory available")
print("✓ Final target metadata available")
print("✓ Consolidated model-preparation metadata available")


# ------------------------------------------------------------
# Final manifest path
# ------------------------------------------------------------

FINAL_ARTIFACT_MANIFEST_PATH = (
    MODEL_PREPARATION_V2_DIR /
    "final_artifact_manifest.json"
)


# ------------------------------------------------------------
# Build complete artifact registry
#
# FINAL_ARTIFACT_INVENTORY contains the 27 core artifacts
# established in Section 4.10.1.
#
# The following artifacts were created subsequently by
# Sections 4.10.1–4.10.3 and are added explicitly.
# ------------------------------------------------------------

MANIFEST_ARTIFACTS = {}

for artifact_group, artifacts in (
    FINAL_ARTIFACT_INVENTORY.items()
):

    for artifact_name, artifact_path in artifacts.items():

        manifest_key = (
            f"{artifact_group}/{artifact_name}"
        )

        MANIFEST_ARTIFACTS[
            manifest_key
        ] = Path(artifact_path)


# Section 4.10.1 inventory record
MANIFEST_ARTIFACTS[
    "final_metadata/final_artifact_inventory"
] = Path(
    FINAL_ARTIFACT_INVENTORY_PATH
)


# Section 4.10.2 target artifacts
MANIFEST_ARTIFACTS[
    "model_ready_targets/y_train"
] = (
    TARGET_ARTIFACT_DIR /
    "y_train.npy"
)

MANIFEST_ARTIFACTS[
    "model_ready_targets/y_validation"
] = (
    TARGET_ARTIFACT_DIR /
    "y_validation.npy"
)

MANIFEST_ARTIFACTS[
    "model_ready_targets/y_test"
] = (
    TARGET_ARTIFACT_DIR /
    "y_test.npy"
)

MANIFEST_ARTIFACTS[
    "model_ready_targets/target_artifact_metadata"
] = (
    TARGET_METADATA_PATH
)


# Section 4.10.3 consolidated metadata
MANIFEST_ARTIFACTS[
    "final_metadata/final_model_preparation_metadata"
] = Path(
    FINAL_MODEL_PREPARATION_METADATA_PATH
)

# ------------------------------------------------------------
# Additional authoritative N04 configuration artifacts
#
# These artifacts were generated by earlier N04 stages and
# are required for complete recovery of the finalized
# model-preparation configuration.
# ------------------------------------------------------------

MANIFEST_ARTIFACTS[
    "partitioning/partition_reproducibility_metadata"
] = (
    MODEL_PREPARATION_V2_DIR /
    "partition_reproducibility_metadata.json"
)

MANIFEST_ARTIFACTS[
    "partitioning/final_leakage_validation"
] = (
    MODEL_PREPARATION_V2_DIR /
    "final_train_validation_test_leakage_validation.json"
)

MANIFEST_ARTIFACTS[
    "class_imbalance/class_imbalance_configuration"
] = (
    MODEL_PREPARATION_V2_DIR /
    "class_imbalance" /
    "class_imbalance_configuration.json"
)

# ------------------------------------------------------------
# Manifest self-exclusion
# ------------------------------------------------------------

MANIFEST_ARTIFACTS.pop(
    "final_metadata/final_artifact_manifest",
    None
)


print("\n[MANIFEST ARTIFACT REGISTRY]")
print(
    f"✓ Registered artifacts: "
    f"{len(MANIFEST_ARTIFACTS)}"
)

print(
    "✓ Manifest file excluded from its own checksum"
)


# ------------------------------------------------------------
# Verify all registered artifacts exist
# ------------------------------------------------------------

print("\n[ARTIFACT EXISTENCE VALIDATION]")

missing_artifacts = []

for manifest_key, artifact_path in (
    MANIFEST_ARTIFACTS.items()
):

    artifact_path = Path(artifact_path)

    if not artifact_path.is_file():

        missing_artifacts.append(
            f"{manifest_key}: {artifact_path}"
        )


if missing_artifacts:

    raise FileNotFoundError(
        "The following registered artifacts are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_artifacts
        )
    )


print(
    f"✓ All {len(MANIFEST_ARTIFACTS)} "
    "registered artifacts are present"
)


# ------------------------------------------------------------
# SHA-256 helper
#
# Files are processed incrementally so that large .npy files
# are never loaded completely into RAM.
# ------------------------------------------------------------

def calculate_sha256(
    file_path,
    chunk_size=1024 * 1024
):

    sha256 = hashlib.sha256()

    with open(
        file_path,
        "rb"
    ) as file:

        while True:

            chunk = file.read(
                chunk_size
            )

            if not chunk:
                break

            sha256.update(chunk)

    return sha256.hexdigest()


# ------------------------------------------------------------
# Generate integrity records
# ------------------------------------------------------------

print("\n[SHA-256 INTEGRITY CALCULATION]")
print(
    "Processing artifacts incrementally; "
    "large arrays are not loaded into RAM."
)

manifest_entries = []

for index, (
    manifest_key,
    artifact_path
) in enumerate(
    MANIFEST_ARTIFACTS.items(),
    start=1
):

    artifact_path = Path(
        artifact_path
    )

    relative_path = artifact_path.relative_to(
        MODEL_PREPARATION_V2_DIR
    )

    file_size = artifact_path.stat().st_size

    sha256_digest = calculate_sha256(
        artifact_path
    )

    manifest_entries.append(
        {
            "artifact_id": index,
            "artifact_key": manifest_key,
            "relative_path": str(
                relative_path
            ),
            "file_size_bytes": int(
                file_size
            ),
            "sha256": sha256_digest
        }
    )

    print(
        f"✓ [{index:02d}/{len(MANIFEST_ARTIFACTS):02d}] "
        f"{relative_path}"
    )


# ------------------------------------------------------------
# Final manifest structure
# ------------------------------------------------------------

FINAL_ARTIFACT_MANIFEST = {

    "notebook": "N04",

    "section": "4.10.4",

    "title":
        "Final Artifact Manifest & Integrity Metadata",

    "status":
        "completed",

    "integrity_algorithm":
        "SHA-256",

    "chunk_size_bytes":
        1024 * 1024,

    "artifact_count":
        len(manifest_entries),

    "manifest_self_excluded":
        True,

    "artifact_root":
        str(
            MODEL_PREPARATION_V2_DIR
        ),

    "artifacts":
        manifest_entries,

    "integrity_boundary": {

        "large_arrays_loaded":
            False,

        "stage1_dataset_reloaded":
            False,

        "feature_values_modified":
            False,

        "target_values_modified":
            False,

        "partition_indices_modified":
            False,

        "validation_modified":
            False,

        "independent_test_modified":
            False,

        "resampling_performed":
            False,

        "class_weighting_performed":
            False,

        "model_fitting_performed":
            False
    },

    "purpose":
        "Provide file-level integrity metadata for the finalized "
        "Notebook 04 model-preparation artifact package.",

    "next_subsection":
        "4.10.5 — Final Persistence Validation"
}


# ------------------------------------------------------------
# Persist manifest
# ------------------------------------------------------------

with open(
    FINAL_ARTIFACT_MANIFEST_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        FINAL_ARTIFACT_MANIFEST,
        f,
        indent=4
    )


print("\n[MANIFEST PERSISTENCE]")

print(
    "✓ Final artifact manifest persisted:"
)

print(
    f"  {FINAL_ARTIFACT_MANIFEST_PATH}"
)


# ------------------------------------------------------------
# Reload manifest
# ------------------------------------------------------------

with open(
    FINAL_ARTIFACT_MANIFEST_PATH,
    "r",
    encoding="utf-8"
) as f:

    reloaded_manifest = json.load(f)


# ------------------------------------------------------------
# Manifest structural validation
# ------------------------------------------------------------

print("\n[MANIFEST STRUCTURAL VALIDATION]")

if reloaded_manifest.get(
    "integrity_algorithm"
) != "SHA-256":

    raise ValueError(
        "Manifest integrity algorithm is not SHA-256."
    )


if reloaded_manifest.get(
    "artifact_count"
) != len(MANIFEST_ARTIFACTS):

    raise ValueError(
        "Manifest artifact count does not match "
        "the registered artifact count."
    )


if len(
    reloaded_manifest.get(
        "artifacts",
        []
    )
) != len(MANIFEST_ARTIFACTS):

    raise ValueError(
        "Manifest artifact entries are incomplete."
    )


print("✓ SHA-256 integrity algorithm recorded")
print("✓ Artifact count validated")
print("✓ Manifest entries validated")
print("✓ Manifest self-exclusion recorded")


# ------------------------------------------------------------
# Verify every checksum is well-formed
# ------------------------------------------------------------

print("\n[CHECKSUM FORMAT VALIDATION]")

for entry in reloaded_manifest[
    "artifacts"
]:

    digest = entry.get(
        "sha256"
    )

    if not isinstance(
        digest,
        str
    ):

        raise ValueError(
            "Invalid SHA-256 value for "
            f"{entry.get('relative_path')}"
        )

    if len(digest) != 64:

        raise ValueError(
            "SHA-256 digest must contain "
            f"64 hexadecimal characters: "
            f"{entry.get('relative_path')}"
        )

    try:
        int(
            digest,
            16
        )

    except ValueError:

        raise ValueError(
            "SHA-256 digest contains "
            f"non-hexadecimal characters: "
            f"{entry.get('relative_path')}"
        )


print(
    f"✓ {len(reloaded_manifest['artifacts'])} "
    "SHA-256 checksums are correctly formatted"
)


# ------------------------------------------------------------
# Verify persisted file sizes against manifest
# ------------------------------------------------------------

print("\n[FILE-SIZE VALIDATION]")

size_mismatches = []

for entry in reloaded_manifest[
    "artifacts"
]:

    artifact_path = (
        MODEL_PREPARATION_V2_DIR /
        entry["relative_path"]
    )

    actual_size = artifact_path.stat().st_size

    recorded_size = int(
        entry["file_size_bytes"]
    )

    if actual_size != recorded_size:

        size_mismatches.append(
            (
                entry["relative_path"],
                recorded_size,
                actual_size
            )
        )


if size_mismatches:

    raise ValueError(
        "File-size mismatch detected:\n"
        + "\n".join(
            f"  - {path}: recorded={recorded}, "
            f"actual={actual}"
            for path, recorded, actual
            in size_mismatches
        )
    )


print(
    f"✓ File sizes verified for "
    f"{len(reloaded_manifest['artifacts'])} artifacts"
)


# ------------------------------------------------------------
# Final integrity boundary
# ------------------------------------------------------------

print("\n[FINAL INTEGRITY BOUNDARY]")

print(
    "✓ Complete N04 artifact package registered"
)

print(
    "✓ File sizes recorded"
)

print(
    "✓ SHA-256 checksums recorded"
)

print(
    "✓ Large arrays processed in chunks"
)

print(
    "✓ No large arrays loaded into memory"
)

print(
    "✓ Manifest successfully reloaded"
)

print(
    "✓ Manifest structure validated"
)

print(
    "✓ Checksum formats validated"
)

print(
    "✓ File sizes validated"
)

print(
    "✓ Independent Test artifacts remain unmodified"
)

print(
    "✓ No preprocessing performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No model fitting performed"
)


# ------------------------------------------------------------
# Completion
# ------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "4.10.4 final artifact manifest and "
    "integrity metadata completed successfully."
)

print("=" * 72)

========================================================================
4.10.4 — FINAL ARTIFACT MANIFEST & INTEGRITY METADATA
========================================================================

[EXISTING N04 STATE]
✓ Final artifact inventory available
✓ Final target artifact directory available
✓ Final target metadata available
✓ Consolidated model-preparation metadata available

[MANIFEST ARTIFACT REGISTRY]
✓ Registered artifacts: 36
✓ Manifest file excluded from its own checksum

[ARTIFACT EXISTENCE VALIDATION]
✓ All 36 registered artifacts are present

[SHA-256 INTEGRITY CALCULATION]
Processing artifacts incrementally; large arrays are not loaded into RAM.
✓ [01/36] taxonomy/taxonomy_mapping.csv
✓ [02/36] taxonomy/final_class_distribution.csv
✓ [03/36] taxonomy/taxonomy_metadata.json
✓ [04/36] duplicate_leakage_audit/development_indices.npy
✓ [05/36] duplicate_leakage_audit/training_indices.npy
✓ [06/36] duplicate_leakage_audit/validation_indices.npy
✓ [07/36] duplicate_leakage_audit/test_indices.npy
✓ [08/36] feature_selection/final_feature_set_validation.json
✓ [09/36] feature_selection/correlation_pruned_selected_features.json
✓ [10/36] feature_scaling/X_train_scaled.npy
✓ [11/36] feature_scaling/X_validation_scaled.npy
✓ [12/36] feature_scaling/X_test_scaled.npy
✓ [13/36] feature_scaling/training_only_standard_scaler.joblib
✓ [14/36] feature_scaling/training_only_scaler_metadata.json
✓ [15/36] feature_scaling/partition_wise_transformation_metadata.json
✓ [16/36] feature_scaling/model_ready_feature_artifacts.json
✓ [17/36] feature_scaling/final_scaling_reproducibility_validation.json
✓ [18/36] class_imbalance/training_only_class_distribution.csv
✓ [19/36] class_imbalance/validation_class_distribution.csv
✓ [20/36] class_imbalance/test_class_distribution.csv
✓ [21/36] class_imbalance/class_imbalance_summary.csv
✓ [22/36] class_imbalance/minority_support_analysis.csv
✓ [23/36] class_imbalance/class_imbalance_severity_metadata.json
✓ [24/36] downstream_imbalance_experiments/imbalance_experiment_matrix.csv
✓ [25/36] downstream_imbalance_experiments/rf_imbalance_experiment_config.json
✓ [26/36] downstream_imbalance_experiments/lstm_imbalance_experiment_config.json
✓ [27/36] downstream_imbalance_experiments/imbalance_experiment_design_metadata.json
✓ [28/36] final_artifact_inventory.json
✓ [29/36] model_ready_targets/y_train.npy
✓ [30/36] model_ready_targets/y_validation.npy
✓ [31/36] model_ready_targets/y_test.npy
✓ [32/36] model_ready_targets/target_artifact_metadata.json
✓ [33/36] final_model_preparation_metadata.json
✓ [34/36] partition_reproducibility_metadata.json
✓ [35/36] final_train_validation_test_leakage_validation.json
✓ [36/36] class_imbalance/class_imbalance_configuration.json

[MANIFEST PERSISTENCE]
✓ Final artifact manifest persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/final_artifact_manifest.json

[MANIFEST STRUCTURAL VALIDATION]
✓ SHA-256 integrity algorithm recorded
✓ Artifact count validated
✓ Manifest entries validated
✓ Manifest self-exclusion recorded

[CHECKSUM FORMAT VALIDATION]
✓ 36 SHA-256 checksums are correctly formatted

[FILE-SIZE VALIDATION]
✓ File sizes verified for 36 artifacts

[FINAL INTEGRITY BOUNDARY]
✓ Complete N04 artifact package registered
✓ File sizes recorded
✓ SHA-256 checksums recorded
✓ Large arrays processed in chunks
✓ No large arrays loaded into memory
✓ Manifest successfully reloaded
✓ Manifest structure validated
✓ Checksum formats validated
✓ File sizes validated
✓ Independent Test artifacts remain unmodified
✓ No preprocessing performed
✓ No resampling performed
✓ No model fitting performed

========================================================================
4.10.4 final artifact manifest and integrity metadata completed successfully.
========================================================================

# 4.10.5 — Final Persistence Validation

This subsection performs the final validation gate for the Notebook 04
artifact-persistence stage.

The validation confirms that the complete persisted N04 model-preparation
package is internally consistent and recoverable from its saved artifacts.
The final artifact inventory, model-ready target metadata, consolidated
model-preparation metadata, and file-level integrity manifest are checked
together.

The validation confirms the established nine-class taxonomy, 32-feature
model-ready representation, fixed Development/Training/Validation/Test
partition structure, independent Test isolation, model-ready target
artifacts, downstream Random Forest and LSTM experiment configuration, and
presence of all registered artifacts.

The SHA-256 values recorded in the final artifact manifest are independently
recomputed from the persisted files and compared against the recorded
checksums. Large files are processed incrementally so that the complete
feature matrices are not loaded into memory.

No preprocessing, feature selection, scaling, resampling, class weighting,
partition modification, target modification, or model fitting is performed.

A successful completion of this subsection establishes Section 4.10 as the
final persistent and integrity-validated model-preparation boundary for
downstream Random Forest and LSTM model-training notebooks.

In [55]:
# ============================================================
# 4.10.5 — FINAL PERSISTENCE VALIDATION
# ============================================================

import hashlib
import json
from pathlib import Path

print("=" * 72)
print("4.10.5 — FINAL PERSISTENCE VALIDATION")
print("=" * 72)


# ------------------------------------------------------------
# 4.10.5.1 Existing N04 recovery state
# ------------------------------------------------------------

required_state = [
    "MODEL_PREPARATION_V2_DIR"
]

missing_state = [
    name
    for name in required_state
    if name not in globals()
]

if missing_state:
    raise NameError(
        "Required N04 recovery state is missing:\n"
        + "\n".join(
            f"  - {name}"
            for name in missing_state
        )
        + "\n\n"
        "Run the existing N04 setup/recovery cell before "
        "continuing with Section 4.10.5."
    )

print("\n[EXISTING N04 RECOVERY STATE]")
print("✓ Model-preparation output directory available")


# ------------------------------------------------------------
# 4.10.5.2 Final persisted artifact paths
# ------------------------------------------------------------

FINAL_ARTIFACT_INVENTORY_PATH = (
    MODEL_PREPARATION_V2_DIR /
    "final_artifact_inventory.json"
)

FINAL_MODEL_PREPARATION_METADATA_PATH = (
    MODEL_PREPARATION_V2_DIR /
    "final_model_preparation_metadata.json"
)

FINAL_ARTIFACT_MANIFEST_PATH = (
    MODEL_PREPARATION_V2_DIR /
    "final_artifact_manifest.json"
)

TARGET_ARTIFACT_METADATA_PATH = (
    MODEL_PREPARATION_V2_DIR /
    "model_ready_targets" /
    "target_artifact_metadata.json"
)


# ------------------------------------------------------------
# 4.10.5.3 Required final control artifacts
# ------------------------------------------------------------

CONTROL_ARTIFACTS = {
    "Final artifact inventory":
        FINAL_ARTIFACT_INVENTORY_PATH,

    "Final model-preparation metadata":
        FINAL_MODEL_PREPARATION_METADATA_PATH,

    "Final artifact manifest":
        FINAL_ARTIFACT_MANIFEST_PATH,

    "Target artifact metadata":
        TARGET_ARTIFACT_METADATA_PATH,
}


print("\n[FINAL CONTROL ARTIFACT CHECK]")

missing_control_artifacts = []

for artifact_name, artifact_path in (
    CONTROL_ARTIFACTS.items()
):

    if not artifact_path.is_file():

        missing_control_artifacts.append(
            f"{artifact_name}: {artifact_path}"
        )

    else:

        print(
            f"✓ {artifact_name}: "
            f"{artifact_path.name}"
        )


if missing_control_artifacts:
    raise FileNotFoundError(
        "Required final control artifacts are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_control_artifacts
        )
    )


# ------------------------------------------------------------
# 4.10.5.4 JSON loading
# ------------------------------------------------------------

def load_json_file(
    file_path,
    artifact_name
):

    with open(
        file_path,
        "r",
        encoding="utf-8"
    ) as f:

        data = json.load(f)

    if not isinstance(data, dict):

        raise ValueError(
            f"{artifact_name} must contain a JSON object."
        )

    return data


final_inventory = load_json_file(
    FINAL_ARTIFACT_INVENTORY_PATH,
    "Final artifact inventory"
)

final_metadata = load_json_file(
    FINAL_MODEL_PREPARATION_METADATA_PATH,
    "Final model-preparation metadata"
)

final_manifest = load_json_file(
    FINAL_ARTIFACT_MANIFEST_PATH,
    "Final artifact manifest"
)

target_metadata = load_json_file(
    TARGET_ARTIFACT_METADATA_PATH,
    "Target artifact metadata"
)


print("\n[FINAL CONTROL ARTIFACT RELOAD]")
print("✓ Final artifact inventory loaded")
print("✓ Final model-preparation metadata loaded")
print("✓ Final artifact manifest loaded")
print("✓ Target artifact metadata loaded")


# ------------------------------------------------------------
# 4.10.5.5 Final taxonomy validation
# ------------------------------------------------------------

print("\n[FINAL TAXONOMY VALIDATION]")

taxonomy_config = final_metadata.get(
    "final_taxonomy",
    {}
)

taxonomy_class_count = int(
    taxonomy_config.get(
        "class_count",
        -1
    )
)

if taxonomy_class_count != 9:
    raise ValueError(
        "Final metadata does not confirm "
        "the established nine-class taxonomy."
    )

class_mapping = taxonomy_config.get(
    "class_id_mapping",
    {}
)

if len(class_mapping) != 9:
    raise ValueError(
        "Final taxonomy mapping does not contain "
        "exactly nine classes."
    )

observed_class_ids = sorted(
    int(class_id)
    for class_id in class_mapping.values()
)

if observed_class_ids != list(range(9)):
    raise ValueError(
        "Final taxonomy class IDs are inconsistent.\n"
        f"Observed: {observed_class_ids}"
    )

print("✓ Nine-class taxonomy confirmed")
print("✓ Class IDs 0–8 confirmed")
print("✓ Final taxonomy mapping confirmed")


# ------------------------------------------------------------
# 4.10.5.6 Final feature configuration validation
# ------------------------------------------------------------

print("\n[FINAL FEATURE CONFIGURATION VALIDATION]")

feature_configuration = final_metadata.get(
    "final_feature_configuration",
    {}
)

final_feature_count = int(
    feature_configuration.get(
        "feature_count",
        -1
    )
)

if final_feature_count != 32:
    raise ValueError(
        "Final metadata does not confirm "
        "the established 32-feature representation."
    )

if feature_configuration.get(
    "feature_selection_training_only"
) is not True:

    raise ValueError(
        "Training-only feature-selection boundary "
        "is not confirmed."
    )

if feature_configuration.get(
    "correlation_pruning_training_only"
) is not True:

    raise ValueError(
        "Training-only correlation-pruning boundary "
        "is not confirmed."
    )

if feature_configuration.get(
    "scaling_training_only_fit"
) is not True:

    raise ValueError(
        "Training-only scaling boundary "
        "is not confirmed."
    )

print("✓ Final 32-feature representation confirmed")
print("✓ Training-only feature selection confirmed")
print("✓ Training-only correlation pruning confirmed")
print("✓ Training-only scaler fitting confirmed")


# ------------------------------------------------------------
# 4.10.5.7 Partition configuration validation
# ------------------------------------------------------------

print("\n[PARTITION CONFIGURATION VALIDATION]")

partition_configuration = final_metadata.get(
    "partition_configuration",
    {}
)

expected_partition_sizes = {
    "development_rows": 2_265_233,
    "training_rows": 1_814_018,
    "validation_rows": 451_215,
    "test_rows": 565_510,
}

for key, expected_size in (
    expected_partition_sizes.items()
):

    actual_size = int(
        partition_configuration.get(
            key,
            -1
        )
    )

    if actual_size != expected_size:

        raise ValueError(
            f"Partition size mismatch for {key}: "
            f"expected {expected_size:,}, "
            f"found {actual_size:,}"
        )

    print(
        f"✓ {key}: {actual_size:,}"
    )

if partition_configuration.get(
    "independent_test_isolated"
) is not True:

    raise ValueError(
        "Independent Test isolation is not confirmed."
    )

if partition_configuration.get(
    "partition_indices_modified_in_4_10"
) is not False:

    raise ValueError(
        "Partition modification boundary is not confirmed."
    )

print("✓ Partition configuration confirmed")
print("✓ Independent Test isolation confirmed")
print("✓ No partition modification recorded")


# ------------------------------------------------------------
# 4.10.5.8 Target artifact validation
# ------------------------------------------------------------

print("\n[MODEL-READY TARGET VALIDATION]")

target_taxonomy = target_metadata.get(
    "taxonomy",
    {}
)

if int(
    target_taxonomy.get(
        "class_count",
        -1
    )
) != 9:

    raise ValueError(
        "Target artifacts do not confirm "
        "the nine-class taxonomy."
    )

target_partition_sizes = target_metadata.get(
    "partition_sizes",
    {}
)

expected_target_sizes = {
    "training": 1_814_018,
    "validation": 451_215,
    "test": 565_510,
}

for partition_name, expected_size in (
    expected_target_sizes.items()
):

    actual_size = int(
        target_partition_sizes.get(
            partition_name,
            -1
        )
    )

    if actual_size != expected_size:

        raise ValueError(
            f"Target size mismatch for "
            f"{partition_name}: "
            f"expected {expected_size:,}, "
            f"found {actual_size:,}"
        )

    print(
        f"✓ {partition_name.capitalize()} target: "
        f"{actual_size:,}"
    )

print("✓ Model-ready target configuration confirmed")


# ------------------------------------------------------------
# 4.10.5.9 Downstream experiment validation
# ------------------------------------------------------------

print("\n[DOWNSTREAM EXPERIMENT VALIDATION]")

experiment_configuration = final_metadata.get(
    "downstream_experiment_configuration",
    {}
)

rf_candidate_count = int(
    experiment_configuration.get(
        "random_forest_candidate_count",
        -1
    )
)

lstm_candidate_count = int(
    experiment_configuration.get(
        "lstm_candidate_count",
        -1
    )
)

total_candidate_count = int(
    experiment_configuration.get(
        "total_candidate_count",
        -1
    )
)

if rf_candidate_count != 5:
    raise ValueError(
        "Expected five Random Forest imbalance candidates."
    )

if lstm_candidate_count != 5:
    raise ValueError(
        "Expected five LSTM imbalance candidates."
    )

if total_candidate_count != 10:
    raise ValueError(
        "Expected ten total downstream imbalance candidates."
    )

if experiment_configuration.get(
    "strategy_selection_partition"
) != "Validation":

    raise ValueError(
        "Downstream strategy selection boundary "
        "is not recorded as Validation."
    )

if experiment_configuration.get(
    "final_evaluation_partition"
) != "Independent Test":

    raise ValueError(
        "Final evaluation boundary is not recorded "
        "as the independent Test partition."
    )

if experiment_configuration.get(
    "optimal_strategy_declared"
) is not False:

    raise ValueError(
        "An optimal imbalance strategy was prematurely declared."
    )

print("✓ Five RF candidates confirmed")
print("✓ Five LSTM candidates confirmed")
print("✓ Ten total candidates confirmed")
print("✓ Validation reserved for strategy comparison")
print("✓ Independent Test reserved for final evaluation")
print("✓ No strategy selected prematurely")


# ------------------------------------------------------------
# 4.10.5.10 Final artifact inventory validation
# ------------------------------------------------------------

print("\n[FINAL ARTIFACT INVENTORY VALIDATION]")

inventory_artifact_groups = final_inventory.get(
    "artifact_inventory",
    {}
)

if not inventory_artifact_groups:
    raise ValueError(
        "Final artifact inventory is empty."
    )

inventory_paths = []

for artifact_group, artifacts in (
    inventory_artifact_groups.items()
):

    for artifact_name, artifact_path in (
        artifacts.items()
    ):

        artifact_path = Path(
            artifact_path
        )

        if not artifact_path.is_file():

            raise FileNotFoundError(
                "Inventory artifact is missing:\n"
                f"{artifact_path}"
            )

        inventory_paths.append(
            artifact_path.resolve()
        )

print(
    f"✓ {len(inventory_paths)} core N04 artifacts "
    "confirmed present"
)


# ------------------------------------------------------------
# 4.10.5.11 Manifest validation
# ------------------------------------------------------------

print("\n[FINAL MANIFEST VALIDATION]")

manifest_entries = final_manifest.get(
    "artifacts",
    []
)

recorded_manifest_count = int(
    final_manifest.get(
        "artifact_count",
        -1
    )
)

if recorded_manifest_count != len(
    manifest_entries
):

    raise ValueError(
        "Manifest artifact count does not match "
        "its artifact entries."
    )

if recorded_manifest_count != 36:

    raise ValueError(
        "Expected the established 36-artifact final "
        f"manifest, found {recorded_manifest_count}."
    )

if final_manifest.get(
    "integrity_algorithm"
) != "SHA-256":

    raise ValueError(
        "Final manifest is not using SHA-256."
    )

if final_manifest.get(
    "manifest_self_excluded"
) is not True:

    raise ValueError(
        "Manifest self-exclusion is not confirmed."
    )

print(
    f"✓ Final manifest contains "
    f"{recorded_manifest_count} artifacts"
)

print("✓ SHA-256 integrity algorithm confirmed")
print("✓ Manifest self-exclusion confirmed")


# ------------------------------------------------------------
# 4.10.5.12 Confirm all inventory artifacts appear in manifest
# ------------------------------------------------------------

manifest_relative_paths = {
    (
        MODEL_PREPARATION_V2_DIR /
        entry["relative_path"]
    ).resolve()
    for entry in manifest_entries
}

missing_from_manifest = [
    path
    for path in inventory_paths
    if path not in manifest_relative_paths
]

if missing_from_manifest:

    raise ValueError(
        "Core inventory artifacts missing from "
        "the final integrity manifest:\n"
        + "\n".join(
            f"  - {path}"
            for path in missing_from_manifest
        )
    )

print(
    "✓ All core inventory artifacts are represented "
    "in the final manifest"
)


# ------------------------------------------------------------
# 4.10.5.13 Independent SHA-256 verification
#
# Large files are streamed in chunks.
# ------------------------------------------------------------

print("\n[FINAL SHA-256 INTEGRITY VERIFICATION]")

def calculate_sha256(
    file_path,
    chunk_size=1024 * 1024
):

    digest = hashlib.sha256()

    with open(
        file_path,
        "rb"
    ) as file:

        while True:

            chunk = file.read(
                chunk_size
            )

            if not chunk:
                break

            digest.update(chunk)

    return digest.hexdigest()


checksum_failures = []

for index, entry in enumerate(
    manifest_entries,
    start=1
):

    artifact_path = (
        MODEL_PREPARATION_V2_DIR /
        entry["relative_path"]
    )

    if not artifact_path.is_file():

        checksum_failures.append(
            (
                entry["relative_path"],
                "FILE_MISSING"
            )
        )

        continue

    actual_size = artifact_path.stat().st_size

    recorded_size = int(
        entry["file_size_bytes"]
    )

    if actual_size != recorded_size:

        checksum_failures.append(
            (
                entry["relative_path"],
                "FILE_SIZE_MISMATCH"
            )
        )

        continue

    actual_sha256 = calculate_sha256(
        artifact_path
    )

    recorded_sha256 = entry[
        "sha256"
    ]

    if actual_sha256 != recorded_sha256:

        checksum_failures.append(
            (
                entry["relative_path"],
                "SHA256_MISMATCH"
            )
        )

    else:

        print(
            f"✓ [{index:02d}/{recorded_manifest_count:02d}] "
            f"{entry['relative_path']}"
        )


if checksum_failures:

    raise ValueError(
        "Final artifact integrity validation failed:\n"
        + "\n".join(
            f"  - {path}: {reason}"
            for path, reason
            in checksum_failures
        )
    )

print(
    f"✓ SHA-256 verified for all "
    f"{recorded_manifest_count} artifacts"
)


# ------------------------------------------------------------
# 4.10.5.14 Final processing-boundary validation
# ------------------------------------------------------------

print("\n[FINAL PROCESSING BOUNDARY VALIDATION]")

processing_boundary = final_metadata.get(
    "processing_boundary",
    {}
)

required_false_flags = [
    "large_arrays_loaded",
    "stage1_dataset_reloaded",
    "feature_selection_performed",
    "scaling_performed",
    "resampling_performed",
    "smote_performed",
    "class_weighting_performed",
    "model_fitting_performed",
    "partition_indices_modified",
    "target_values_modified",
    "validation_modified",
    "independent_test_modified",
]

for flag_name in required_false_flags:

    if processing_boundary.get(
        flag_name
    ) is not False:

        raise ValueError(
            f"Processing boundary violation: "
            f"{flag_name} is not False."
        )

    print(
        f"✓ {flag_name}: False"
    )


# ------------------------------------------------------------
# 4.10.5.15 Final persistence status
# ------------------------------------------------------------

print("\n[FINAL PERSISTENCE STATUS]")

print("✓ Final artifact inventory is complete")
print("✓ Final model-preparation metadata is consistent")
print("✓ Final target metadata is consistent")
print("✓ Final taxonomy is consistent")
print("✓ Final 32-feature configuration is consistent")
print("✓ Partition structure is consistent")
print("✓ Independent Test isolation is confirmed")
print("✓ Downstream experiment configuration is consistent")
print("✓ All 36 manifest artifacts are present")
print("✓ All 36 artifact file sizes are unchanged")
print("✓ All 36 SHA-256 checksums match")
print("✓ No N04 processing boundary was violated")


# ------------------------------------------------------------
# Final completion
# ------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "4.10.5 final persistence validation "
    "completed successfully."
)

print(
    "SECTION 4.10 — FINAL ARTIFACT PERSISTENCE "
    "COMPLETED AND VALIDATED."
)

print("=" * 72)

========================================================================
4.10.5 — FINAL PERSISTENCE VALIDATION
========================================================================

[EXISTING N04 RECOVERY STATE]
✓ Model-preparation output directory available

[FINAL CONTROL ARTIFACT CHECK]
✓ Final artifact inventory: final_artifact_inventory.json
✓ Final model-preparation metadata: final_model_preparation_metadata.json
✓ Final artifact manifest: final_artifact_manifest.json
✓ Target artifact metadata: target_artifact_metadata.json

[FINAL CONTROL ARTIFACT RELOAD]
✓ Final artifact inventory loaded
✓ Final model-preparation metadata loaded
✓ Final artifact manifest loaded
✓ Target artifact metadata loaded

[FINAL TAXONOMY VALIDATION]
✓ Nine-class taxonomy confirmed
✓ Class IDs 0–8 confirmed
✓ Final taxonomy mapping confirmed

[FINAL FEATURE CONFIGURATION VALIDATION]
✓ Final 32-feature representation confirmed
✓ Training-only feature selection confirmed
✓ Training-only correlation pruning confirmed
✓ Training-only scaler fitting confirmed

[PARTITION CONFIGURATION VALIDATION]
✓ development_rows: 2,265,233
✓ training_rows: 1,814,018
✓ validation_rows: 451,215
✓ test_rows: 565,510
✓ Partition configuration confirmed
✓ Independent Test isolation confirmed
✓ No partition modification recorded

[MODEL-READY TARGET VALIDATION]
✓ Training target: 1,814,018
✓ Validation target: 451,215
✓ Test target: 565,510
✓ Model-ready target configuration confirmed

[DOWNSTREAM EXPERIMENT VALIDATION]
✓ Five RF candidates confirmed
✓ Five LSTM candidates confirmed
✓ Ten total candidates confirmed
✓ Validation reserved for strategy comparison
✓ Independent Test reserved for final evaluation
✓ No strategy selected prematurely

[FINAL ARTIFACT INVENTORY VALIDATION]
✓ 27 core N04 artifacts confirmed present

[FINAL MANIFEST VALIDATION]
✓ Final manifest contains 36 artifacts
✓ SHA-256 integrity algorithm confirmed
✓ Manifest self-exclusion confirmed
✓ All core inventory artifacts are represented in the final manifest

[FINAL SHA-256 INTEGRITY VERIFICATION]
✓ [01/36] taxonomy/taxonomy_mapping.csv
✓ [02/36] taxonomy/final_class_distribution.csv
✓ [03/36] taxonomy/taxonomy_metadata.json
✓ [04/36] duplicate_leakage_audit/development_indices.npy
✓ [05/36] duplicate_leakage_audit/training_indices.npy
✓ [06/36] duplicate_leakage_audit/validation_indices.npy
✓ [07/36] duplicate_leakage_audit/test_indices.npy
✓ [08/36] feature_selection/final_feature_set_validation.json
✓ [09/36] feature_selection/correlation_pruned_selected_features.json
✓ [10/36] feature_scaling/X_train_scaled.npy
✓ [11/36] feature_scaling/X_validation_scaled.npy
✓ [12/36] feature_scaling/X_test_scaled.npy
✓ [13/36] feature_scaling/training_only_standard_scaler.joblib
✓ [14/36] feature_scaling/training_only_scaler_metadata.json
✓ [15/36] feature_scaling/partition_wise_transformation_metadata.json
✓ [16/36] feature_scaling/model_ready_feature_artifacts.json
✓ [17/36] feature_scaling/final_scaling_reproducibility_validation.json
✓ [18/36] class_imbalance/training_only_class_distribution.csv
✓ [19/36] class_imbalance/validation_class_distribution.csv
✓ [20/36] class_imbalance/test_class_distribution.csv
✓ [21/36] class_imbalance/class_imbalance_summary.csv
✓ [22/36] class_imbalance/minority_support_analysis.csv
✓ [23/36] class_imbalance/class_imbalance_severity_metadata.json
✓ [24/36] downstream_imbalance_experiments/imbalance_experiment_matrix.csv
✓ [25/36] downstream_imbalance_experiments/rf_imbalance_experiment_config.json
✓ [26/36] downstream_imbalance_experiments/lstm_imbalance_experiment_config.json
✓ [27/36] downstream_imbalance_experiments/imbalance_experiment_design_metadata.json
✓ [28/36] final_artifact_inventory.json
✓ [29/36] model_ready_targets/y_train.npy
✓ [30/36] model_ready_targets/y_validation.npy
✓ [31/36] model_ready_targets/y_test.npy
✓ [32/36] model_ready_targets/target_artifact_metadata.json
✓ [33/36] final_model_preparation_metadata.json
✓ [34/36] partition_reproducibility_metadata.json
✓ [35/36] final_train_validation_test_leakage_validation.json
✓ [36/36] class_imbalance/class_imbalance_configuration.json
✓ SHA-256 verified for all 36 artifacts

[FINAL PROCESSING BOUNDARY VALIDATION]
✓ large_arrays_loaded: False
✓ stage1_dataset_reloaded: False
✓ feature_selection_performed: False
✓ scaling_performed: False
✓ resampling_performed: False
✓ smote_performed: False
✓ class_weighting_performed: False
✓ model_fitting_performed: False
✓ partition_indices_modified: False
✓ target_values_modified: False
✓ validation_modified: False
✓ independent_test_modified: False

[FINAL PERSISTENCE STATUS]
✓ Final artifact inventory is complete
✓ Final model-preparation metadata is consistent
✓ Final target metadata is consistent
✓ Final taxonomy is consistent
✓ Final 32-feature configuration is consistent
✓ Partition structure is consistent
✓ Independent Test isolation is confirmed
✓ Downstream experiment configuration is consistent
✓ All 36 manifest artifacts are present
✓ All 36 artifact file sizes are unchanged
✓ All 36 SHA-256 checksums match
✓ No N04 processing boundary was violated

========================================================================
4.10.5 final persistence validation completed successfully.
SECTION 4.10 — FINAL ARTIFACT PERSISTENCE COMPLETED AND VALIDATED.
========================================================================

# 4.11 — Artifact Reload & Validation

This section validates the recoverability of the finalized Notebook 04
model-preparation state from its persisted artifacts.

The objective is to demonstrate that the model-preparation configuration can
be reconstructed from the saved N04 artifacts without rerunning the preceding
preprocessing, feature-selection, feature-scaling, class-imbalance, or
partitioning stages.

The reload and validation process is performed incrementally so that the
downstream model-training stages can recover the finalized N04 state without
requiring the original Stage-1 dataset or the complete preprocessing history
to be held in memory.

The validation covers cold-start artifact recovery, model-ready feature
dimensions and feature ordering, target and partition integrity, scaler
reproducibility, downstream Random Forest and LSTM experiment configuration,
and final model-preparation consistency.

No model training is performed in this section. The independent Test
partition remains protected throughout the recovery and validation process.

## 4.11.1 — Cold-Start Artifact Recovery

This subsection establishes a cold-start recovery boundary for the finalized
Notebook 04 model-preparation state.

The recovery process loads the authoritative persisted metadata and
configuration artifacts directly from the model-preparation output directory
rather than relying on large in-memory arrays or previously executed
preprocessing cells.

The recovery includes the final artifact inventory, final model-preparation
metadata, final artifact integrity manifest, model-ready target metadata, and
the principal configuration artifacts required by downstream model-training
stages.

The persisted artifacts are checked for existence and successfully reloaded
as independent recovery inputs.

No Stage-1 dataset is reloaded, no large model-ready feature matrix is loaded,
and no preprocessing, resampling, partition modification, target
modification, or model fitting is performed.

Successful completion establishes that the finalized N04 configuration is
recoverable from its persistent artifact boundary and can be used as the
starting point for the subsequent validation subsections.

In [56]:
# ============================================================
# 4.11.1 — COLD-START ARTIFACT RECOVERY
# ============================================================

import json
from pathlib import Path

print("=" * 72)
print("4.11.1 — COLD-START ARTIFACT RECOVERY")
print("=" * 72)


# ------------------------------------------------------------
# 1. Establish independent cold-start recovery boundary
# ------------------------------------------------------------

# Reconstruct the N04 artifact location directly from the
# persistent Google Drive project root.
#
# This intentionally does not depend on MODEL_PREPARATION_V2_DIR
# or any other previously created N04 variable.

RECOVERY_PROJECT_ROOT = Path(
    "/content/drive/MyDrive/"
    "AI-Network-Intrusion-Detection-System"
)

RECOVERY_OUTPUTS_DIR = (
    RECOVERY_PROJECT_ROOT /
    "outputs"
)

RECOVERY_MODEL_PREPARATION_V2_DIR = (
    RECOVERY_OUTPUTS_DIR /
    "model_preparation_v2"
)


if not RECOVERY_PROJECT_ROOT.is_dir():

    raise FileNotFoundError(
        "Project root was not found:\n"
        f"{RECOVERY_PROJECT_ROOT}"
    )


if not RECOVERY_OUTPUTS_DIR.is_dir():

    raise FileNotFoundError(
        "Project outputs directory was not found:\n"
        f"{RECOVERY_OUTPUTS_DIR}"
    )


if not RECOVERY_MODEL_PREPARATION_V2_DIR.is_dir():

    raise FileNotFoundError(
        "N04 model-preparation output directory "
        "was not found:\n"
        f"{RECOVERY_MODEL_PREPARATION_V2_DIR}"
    )


print("\n[COLD-START RECOVERY BOUNDARY]")

print(
    "✓ Project root recovered from persistent path:"
)

print(
    f"  {RECOVERY_PROJECT_ROOT}"
)

print(
    "✓ Outputs directory recovered:"
)

print(
    f"  {RECOVERY_OUTPUTS_DIR}"
)

print(
    "✓ N04 model-preparation directory recovered:"
)

print(
    f"  {RECOVERY_MODEL_PREPARATION_V2_DIR}"
)


# ------------------------------------------------------------
# 2. Define authoritative persisted recovery artifacts
# ------------------------------------------------------------

recovery_artifacts = {

    "final_artifact_inventory":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "final_artifact_inventory.json",

    "final_model_preparation_metadata":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "final_model_preparation_metadata.json",

    "final_artifact_manifest":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "final_artifact_manifest.json",

    "target_artifact_metadata":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "model_ready_targets" /
        "target_artifact_metadata.json",

    "taxonomy_metadata":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "taxonomy" /
        "taxonomy_metadata.json",

    "partition_reproducibility_metadata":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "partition_reproducibility_metadata.json",

    "final_leakage_validation":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "final_train_validation_test_leakage_validation.json",

    "feature_set_validation":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "feature_selection" /
        "final_feature_set_validation.json",

    "selected_features":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "feature_selection" /
        "correlation_pruned_selected_features.json",

    "training_scaler_metadata":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "feature_scaling" /
        "training_only_scaler_metadata.json",

    "transformation_metadata":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "feature_scaling" /
        "partition_wise_transformation_metadata.json",

    "model_ready_feature_metadata":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "feature_scaling" /
        "model_ready_feature_artifacts.json",

    "final_scaling_validation":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "feature_scaling" /
        "final_scaling_reproducibility_validation.json",

    "class_imbalance_configuration":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "class_imbalance" /
        "class_imbalance_configuration.json",

    "class_imbalance_severity_metadata":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "class_imbalance" /
        "class_imbalance_severity_metadata.json",

    "imbalance_experiment_design_metadata":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "downstream_imbalance_experiments" /
        "imbalance_experiment_design_metadata.json",

    "rf_imbalance_experiment_configuration":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "downstream_imbalance_experiments" /
        "rf_imbalance_experiment_config.json",

    "lstm_imbalance_experiment_configuration":
        RECOVERY_MODEL_PREPARATION_V2_DIR /
        "downstream_imbalance_experiments" /
        "lstm_imbalance_experiment_config.json",
}


# ------------------------------------------------------------
# 3. Persisted artifact existence validation
# ------------------------------------------------------------

print("\n[PERSISTED RECOVERY ARTIFACT CHECK]")

missing_artifacts = []

for artifact_name, artifact_path in (
    recovery_artifacts.items()
):

    if not artifact_path.is_file():

        missing_artifacts.append(
            f"{artifact_name}: {artifact_path}"
        )

    else:

        print(
            f"✓ {artifact_name}: "
            f"{artifact_path.name}"
        )


if missing_artifacts:

    raise FileNotFoundError(
        "Cold-start recovery cannot continue because "
        "required persisted artifacts are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_artifacts
        )
    )


print(
    f"\n✓ All {len(recovery_artifacts)} "
    "required recovery artifacts are present"
)


# ------------------------------------------------------------
# 4. Independent JSON reload
# ------------------------------------------------------------

def load_recovery_json(
    artifact_name,
    artifact_path
):

    with open(
        artifact_path,
        "r",
        encoding="utf-8"
    ) as file:

        data = json.load(file)

    if not isinstance(
        data,
        dict
    ):

        raise ValueError(
            f"{artifact_name} does not contain "
            "a JSON object."
        )

    return data


print("\n[COLD-START METADATA RELOAD]")

recovered_artifacts = {}

for artifact_name, artifact_path in (
    recovery_artifacts.items()
):

    recovered_artifacts[
        artifact_name
    ] = load_recovery_json(
        artifact_name,
        artifact_path
    )

    print(
        f"✓ {artifact_name} loaded successfully"
    )


# ------------------------------------------------------------
# 5. Recovery independence validation
# ------------------------------------------------------------

print("\n[RECOVERY INDEPENDENCE VALIDATION]")

print(
    "✓ Recovery metadata loaded directly from persisted files"
)

print(
    "✓ No Stage-1 dataset loaded"
)

print(
    "✓ No model-ready feature matrix loaded"
)

print(
    "✓ No preprocessing operation performed"
)

print(
    "✓ No feature-selection operation performed"
)

print(
    "✓ No scaling operation performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No partition modification performed"
)

print(
    "✓ No target modification performed"
)

print(
    "✓ No model fitting performed"
)


# ------------------------------------------------------------
# 6. Validate recovered control artifacts
# ------------------------------------------------------------

print("\n[RECOVERED CONTROL ARTIFACT VALIDATION]")

required_recovery_objects = [
    "final_artifact_inventory",
    "final_model_preparation_metadata",
    "final_artifact_manifest",
    "target_artifact_metadata",
    "taxonomy_metadata",
    "partition_reproducibility_metadata",
    "final_leakage_validation",
    "feature_set_validation",
    "selected_features",
    "training_scaler_metadata",
    "transformation_metadata",
    "model_ready_feature_metadata",
    "final_scaling_validation",
    "class_imbalance_configuration",
    "class_imbalance_severity_metadata",
    "imbalance_experiment_design_metadata",
    "rf_imbalance_experiment_configuration",
    "lstm_imbalance_experiment_configuration",
]

for object_name in required_recovery_objects:

    if object_name not in recovered_artifacts:

        raise ValueError(
            "Recovered artifact missing from "
            f"recovery state: {object_name}"
        )

    if not isinstance(
        recovered_artifacts[object_name],
        dict
    ):

        raise ValueError(
            f"Recovered artifact '{object_name}' "
            "is not a dictionary."
        )


print(
    f"✓ {len(required_recovery_objects)} "
    "persisted recovery objects available"
)


# ------------------------------------------------------------
# 7. Final artifact manifest recovery check
# ------------------------------------------------------------

print("\n[FINAL MANIFEST RECOVERY CHECK]")

manifest = recovered_artifacts[
    "final_artifact_manifest"
]

if manifest.get(
    "integrity_algorithm"
) != "SHA-256":

    raise ValueError(
        "Recovered final artifact manifest does not "
        "specify SHA-256 integrity."
    )

manifest_entries = manifest.get(
    "artifacts",
    []
)

if len(
    manifest_entries
) != 36:

    raise ValueError(
        "Recovered final artifact manifest does not "
        "contain the expected 36 artifacts."
    )

if manifest.get(
    "manifest_self_excluded"
) is not True:

    raise ValueError(
        "Recovered manifest does not preserve "
        "manifest self-exclusion."
    )

print(
    "✓ SHA-256 manifest recovered"
)

print(
    "✓ 36 manifest artifacts recovered"
)

print(
    "✓ Manifest self-exclusion confirmed"
)


# ------------------------------------------------------------
# 8. Target artifact recovery check
# ------------------------------------------------------------

print("\n[TARGET ARTIFACT RECOVERY CHECK]")

target_metadata = recovered_artifacts[
    "target_artifact_metadata"
]

target_directory = (
    RECOVERY_MODEL_PREPARATION_V2_DIR /
    "model_ready_targets"
)

required_target_files = {
    "training": target_directory / "y_train.npy",
    "validation": target_directory / "y_validation.npy",
    "test": target_directory / "y_test.npy",
}

for partition_name, target_path in (
    required_target_files.items()
):

    if not target_path.is_file():

        raise FileNotFoundError(
            f"Recovered target artifact missing: "
            f"{target_path}"
        )

    print(
        f"✓ {partition_name.capitalize()} target artifact "
        f"available: {target_path.name}"
    )

print(
    "✓ Model-ready target artifacts recoverable"
)


# ------------------------------------------------------------
# 9. Cold-start recovery summary
# ------------------------------------------------------------

print("\n[COLD-START RECOVERY SUMMARY]")

print(
    "✓ N04 persistent artifact boundary located"
)

print(
    "✓ Required metadata artifacts recovered"
)

print(
    "✓ Final integrity manifest recovered"
)

print(
    "✓ Taxonomy configuration recovered"
)

print(
    "✓ Partition configuration recovered"
)

print(
    "✓ Feature-selection configuration recovered"
)

print(
    "✓ Feature-scaling configuration recovered"
)

print(
    "✓ Class-imbalance configuration recovered"
)

print(
    "✓ RF experiment configuration recovered"
)

print(
    "✓ LSTM experiment configuration recovered"
)

print(
    "✓ Model-ready target artifacts located"
)

print(
    "✓ Recovery completed without Stage-1 reload"
)

print(
    "✓ Recovery completed without large feature-array loading"
)

print(
    "✓ Recovery completed without preprocessing"
)

print(
    "✓ Recovery completed without model fitting"
)


# ------------------------------------------------------------
# 10. Completion
# ------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "4.11.1 cold-start artifact recovery "
    "completed successfully."
)

print("=" * 72)

========================================================================
4.11.1 — COLD-START ARTIFACT RECOVERY
========================================================================

[COLD-START RECOVERY BOUNDARY]
✓ Project root recovered from persistent path:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System
✓ Outputs directory recovered:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs
✓ N04 model-preparation directory recovered:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2

[PERSISTED RECOVERY ARTIFACT CHECK]
✓ final_artifact_inventory: final_artifact_inventory.json
✓ final_model_preparation_metadata: final_model_preparation_metadata.json
✓ final_artifact_manifest: final_artifact_manifest.json
✓ target_artifact_metadata: target_artifact_metadata.json
✓ taxonomy_metadata: taxonomy_metadata.json
✓ partition_reproducibility_metadata: partition_reproducibility_metadata.json
✓ final_leakage_validation: final_train_validation_test_leakage_validation.json
✓ feature_set_validation: final_feature_set_validation.json
✓ selected_features: correlation_pruned_selected_features.json
✓ training_scaler_metadata: training_only_scaler_metadata.json
✓ transformation_metadata: partition_wise_transformation_metadata.json
✓ model_ready_feature_metadata: model_ready_feature_artifacts.json
✓ final_scaling_validation: final_scaling_reproducibility_validation.json
✓ class_imbalance_configuration: class_imbalance_configuration.json
✓ class_imbalance_severity_metadata: class_imbalance_severity_metadata.json
✓ imbalance_experiment_design_metadata: imbalance_experiment_design_metadata.json
✓ rf_imbalance_experiment_configuration: rf_imbalance_experiment_config.json
✓ lstm_imbalance_experiment_configuration: lstm_imbalance_experiment_config.json

✓ All 18 required recovery artifacts are present

[COLD-START METADATA RELOAD]
✓ final_artifact_inventory loaded successfully
✓ final_model_preparation_metadata loaded successfully
✓ final_artifact_manifest loaded successfully
✓ target_artifact_metadata loaded successfully
✓ taxonomy_metadata loaded successfully
✓ partition_reproducibility_metadata loaded successfully
✓ final_leakage_validation loaded successfully
✓ feature_set_validation loaded successfully
✓ selected_features loaded successfully
✓ training_scaler_metadata loaded successfully
✓ transformation_metadata loaded successfully
✓ model_ready_feature_metadata loaded successfully
✓ final_scaling_validation loaded successfully
✓ class_imbalance_configuration loaded successfully
✓ class_imbalance_severity_metadata loaded successfully
✓ imbalance_experiment_design_metadata loaded successfully
✓ rf_imbalance_experiment_configuration loaded successfully
✓ lstm_imbalance_experiment_configuration loaded successfully

[RECOVERY INDEPENDENCE VALIDATION]
✓ Recovery metadata loaded directly from persisted files
✓ No Stage-1 dataset loaded
✓ No model-ready feature matrix loaded
✓ No preprocessing operation performed
✓ No feature-selection operation performed
✓ No scaling operation performed
✓ No resampling performed
✓ No partition modification performed
✓ No target modification performed
✓ No model fitting performed

[RECOVERED CONTROL ARTIFACT VALIDATION]
✓ 18 persisted recovery objects available

[FINAL MANIFEST RECOVERY CHECK]
✓ SHA-256 manifest recovered
✓ 36 manifest artifacts recovered
✓ Manifest self-exclusion confirmed

[TARGET ARTIFACT RECOVERY CHECK]
✓ Training target artifact available: y_train.npy
✓ Validation target artifact available: y_validation.npy
✓ Test target artifact available: y_test.npy
✓ Model-ready target artifacts recoverable

[COLD-START RECOVERY SUMMARY]
✓ N04 persistent artifact boundary located
✓ Required metadata artifacts recovered
✓ Final integrity manifest recovered
✓ Taxonomy configuration recovered
✓ Partition configuration recovered
✓ Feature-selection configuration recovered
✓ Feature-scaling configuration recovered
✓ Class-imbalance configuration recovered
✓ RF experiment configuration recovered
✓ LSTM experiment configuration recovered
✓ Model-ready target artifacts located
✓ Recovery completed without Stage-1 reload
✓ Recovery completed without large feature-array loading
✓ Recovery completed without preprocessing
✓ Recovery completed without model fitting

========================================================================
4.11.1 cold-start artifact recovery completed successfully.
========================================================================

## 4.11.2 — Shape & Feature-Order Validation

This subsection validates the dimensional consistency and feature-order
integrity of the persisted model-ready feature space recovered in Section
4.11.1.

The validation checks the persisted Training, Validation, and independent Test
feature artifacts against the established partition sizes and final
32-feature configuration. It also compares the authoritative final feature
order across the persisted selected-feature artifact, training-only scaler
metadata, partition-wise transformation metadata, and model-ready feature
metadata.

The purpose is to establish that all three model-development partitions use
the same 32 features in the same order and that the persisted feature
artifacts are structurally consistent for downstream Random Forest, LSTM,
ensemble, explainability, and inference stages.

Large feature matrices are not loaded into memory. Their dimensions are
inspected using NumPy memory mapping, while feature-order and configuration
checks are performed using the small persisted JSON metadata artifacts.

No Stage-1 dataset is reloaded, no feature selection is repeated, no scaling
or transformation is performed, no partition or target is modified, no
resampling is performed, and no model fitting is performed.

Successful completion establishes that the recovered model-ready feature
space has consistent dimensions and an identical feature ordering across
Training, Validation, and independent Test partitions.

In [57]:
# ============================================================
# 4.11.2 — SHAPE & FEATURE-ORDER VALIDATION
# ============================================================

import json
import numpy as np
from pathlib import Path

print("=" * 72)
print("4.11.2 — SHAPE & FEATURE-ORDER VALIDATION")
print("=" * 72)


# ------------------------------------------------------------
# 1. Validate required cold-start recovery state
# ------------------------------------------------------------

required_recovery_objects = [
    "feature_set_validation",
    "selected_features",
    "training_scaler_metadata",
    "transformation_metadata",
    "model_ready_feature_metadata",
]

missing_recovery_objects = [
    object_name
    for object_name in required_recovery_objects
    if object_name not in recovered_artifacts
]

if missing_recovery_objects:

    raise ValueError(
        "Required 4.11.1 recovery objects are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_recovery_objects
        )
    )

print("\n[RECOVERY STATE]")
print(
    "✓ Required feature-selection and feature-scaling "
    "metadata recovered"
)


# ------------------------------------------------------------
# 2. Reconstruct established model-ready artifact paths
# ------------------------------------------------------------

RECOVERY_FEATURE_SELECTION_DIR = (
    RECOVERY_MODEL_PREPARATION_V2_DIR /
    "feature_selection"
)

RECOVERY_FEATURE_SCALING_DIR = (
    RECOVERY_MODEL_PREPARATION_V2_DIR /
    "feature_scaling"
)


TRAINING_SCALED_PATH = (
    RECOVERY_FEATURE_SCALING_DIR /
    "X_train_scaled.npy"
)

VALIDATION_SCALED_PATH = (
    RECOVERY_FEATURE_SCALING_DIR /
    "X_validation_scaled.npy"
)

TEST_SCALED_PATH = (
    RECOVERY_FEATURE_SCALING_DIR /
    "X_test_scaled.npy"
)


SELECTED_FEATURES_PATH = (
    RECOVERY_FEATURE_SELECTION_DIR /
    "correlation_pruned_selected_features.json"
)

SCALER_METADATA_PATH = (
    RECOVERY_FEATURE_SCALING_DIR /
    "training_only_scaler_metadata.json"
)

TRANSFORMATION_METADATA_PATH = (
    RECOVERY_FEATURE_SCALING_DIR /
    "partition_wise_transformation_metadata.json"
)

MODEL_READY_METADATA_PATH = (
    RECOVERY_FEATURE_SCALING_DIR /
    "model_ready_feature_artifacts.json"
)


required_paths = {
    "Training scaled feature artifact":
        TRAINING_SCALED_PATH,

    "Validation scaled feature artifact":
        VALIDATION_SCALED_PATH,

    "Test scaled feature artifact":
        TEST_SCALED_PATH,

    "Selected-feature artifact":
        SELECTED_FEATURES_PATH,

    "Training-only scaler metadata":
        SCALER_METADATA_PATH,

    "Partition-wise transformation metadata":
        TRANSFORMATION_METADATA_PATH,

    "Model-ready feature metadata":
        MODEL_READY_METADATA_PATH,
}


print("\n[PERSISTED ARTIFACT CHECK]")

missing_paths = []

for artifact_name, artifact_path in required_paths.items():

    if not artifact_path.is_file():

        missing_paths.append(
            f"{artifact_name}: {artifact_path}"
        )

    else:

        print(
            f"✓ {artifact_name}: "
            f"{artifact_path.name}"
        )


if missing_paths:

    raise FileNotFoundError(
        "Required model-ready artifacts are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_paths
        )
    )


# ------------------------------------------------------------
# 3. Expected final model-ready configuration
# ------------------------------------------------------------

EXPECTED_FEATURE_COUNT = 32

EXPECTED_PARTITION_SHAPES = {

    "Training": (
        1_814_018,
        EXPECTED_FEATURE_COUNT
    ),

    "Validation": (
        451_215,
        EXPECTED_FEATURE_COUNT
    ),

    "Test": (
        565_510,
        EXPECTED_FEATURE_COUNT
    ),
}


# ------------------------------------------------------------
# 4. Memory-conscious partition shape validation
# ------------------------------------------------------------

print("\n[PARTITION SHAPE VALIDATION]")

partition_paths = {

    "Training":
        TRAINING_SCALED_PATH,

    "Validation":
        VALIDATION_SCALED_PATH,

    "Test":
        TEST_SCALED_PATH,
}


actual_partition_shapes = {}

for partition_name, partition_path in (
    partition_paths.items()
):

    # Memory mapping inspects the persisted NumPy array
    # without loading the complete feature matrix into RAM.
    mapped_array = np.load(
        partition_path,
        mmap_mode="r"
    )

    actual_shape = tuple(
        mapped_array.shape
    )

    actual_partition_shapes[
        partition_name
    ] = actual_shape

    expected_shape = (
        EXPECTED_PARTITION_SHAPES[
            partition_name
        ]
    )

    if actual_shape != expected_shape:

        del mapped_array

        raise ValueError(
            f"{partition_name} feature shape mismatch: "
            f"expected {expected_shape}, "
            f"found {actual_shape}"
        )

    print(
        f"✓ {partition_name:<10} : "
        f"{actual_shape}"
    )

    del mapped_array


print(
    "✓ Training, Validation, and Test dimensions "
    "match the established model-ready configuration"
)

print(
    f"✓ All partitions contain exactly "
    f"{EXPECTED_FEATURE_COUNT} features"
)


# ------------------------------------------------------------
# 5. Load persisted feature-order metadata
# ------------------------------------------------------------

def load_json_file(
    artifact_name,
    artifact_path
):

    with open(
        artifact_path,
        "r",
        encoding="utf-8"
    ) as file:

        data = json.load(file)

    if not isinstance(
        data,
        (dict, list)
    ):

        raise ValueError(
            f"{artifact_name} has an unexpected "
            "JSON structure."
        )

    return data


selected_feature_metadata = load_json_file(
    "selected-feature artifact",
    SELECTED_FEATURES_PATH
)

scaler_metadata = load_json_file(
    "training-only scaler metadata",
    SCALER_METADATA_PATH
)

transformation_metadata = load_json_file(
    "partition-wise transformation metadata",
    TRANSFORMATION_METADATA_PATH
)

model_ready_metadata = load_json_file(
    "model-ready feature metadata",
    MODEL_READY_METADATA_PATH
)


# ------------------------------------------------------------
# 6. Recover authoritative feature-order lists
# ------------------------------------------------------------

def recover_feature_list(
    artifact_name,
    metadata,
    possible_keys
):

    if isinstance(
        metadata,
        list
    ):

        feature_list = metadata

    else:

        feature_list = None

        for key in possible_keys:

            candidate = metadata.get(
                key
            )

            if isinstance(
                candidate,
                list
            ):

                feature_list = candidate
                break

        if feature_list is None:

            raise ValueError(
                f"Could not identify the feature-order list "
                f"in {artifact_name}."
            )

    feature_list = list(
        feature_list
    )

    if len(
        feature_list
    ) != EXPECTED_FEATURE_COUNT:

        raise ValueError(
            f"{artifact_name} contains "
            f"{len(feature_list)} features instead of "
            f"{EXPECTED_FEATURE_COUNT}."
        )

    if len(
        set(feature_list)
    ) != len(feature_list):

        raise ValueError(
            f"{artifact_name} contains duplicate "
            "feature names."
        )

    return feature_list


selected_feature_order = recover_feature_list(
    "correlation_pruned_selected_features.json",
    selected_feature_metadata,
    [
        "selected_features",
        "retained_features",
        "final_features",
        "features",
        "feature_columns",
    ]
)


scaler_feature_order = recover_feature_list(
    "training_only_scaler_metadata.json",
    scaler_metadata,
    [
        "features",
        "selected_features",
        "retained_features",
        "feature_columns",
    ]
)


transformation_feature_order = recover_feature_list(
    "partition_wise_transformation_metadata.json",
    transformation_metadata,
    [
        "features",
        "selected_features",
        "retained_features",
        "feature_columns",
    ]
)


model_ready_feature_order = recover_feature_list(
    "model_ready_feature_artifacts.json",
    model_ready_metadata,
    [
        "final_feature_order",
        "selected_features",
        "retained_features",
        "features",
        "feature_columns",
    ]
)


# ------------------------------------------------------------
# 7. Cross-artifact feature-order validation
# ------------------------------------------------------------

print("\n[FEATURE-ORDER VALIDATION]")

feature_order_artifacts = {

    "Selected-feature artifact":
        selected_feature_order,

    "Training-only scaler metadata":
        scaler_feature_order,

    "Partition-wise transformation metadata":
        transformation_feature_order,

    "Model-ready feature metadata":
        model_ready_feature_order,
}


authoritative_feature_order = (
    selected_feature_order
)


for artifact_name, feature_order in (
    feature_order_artifacts.items()
):

    if feature_order != authoritative_feature_order:

        mismatch_positions = []

        for position, (
            expected_feature,
            observed_feature
        ) in enumerate(
            zip(
                authoritative_feature_order,
                feature_order
            )
        ):

            if expected_feature != observed_feature:

                mismatch_positions.append(
                    (
                        position,
                        expected_feature,
                        observed_feature
                    )
                )

        raise ValueError(
            f"{artifact_name} feature order does not "
            "match the authoritative selected-feature order.\n"
            f"First mismatches: "
            f"{mismatch_positions[:5]}"
        )

    print(
        f"✓ {artifact_name} matches "
        "the authoritative feature order"
    )


print(
    f"✓ Exact feature order preserved across "
    f"{len(feature_order_artifacts)} persisted artifacts"
)


# ------------------------------------------------------------
# 8. Validate feature-count metadata
# ------------------------------------------------------------

print("\n[FEATURE-COUNT METADATA VALIDATION]")

metadata_feature_counts = {

    "Training-only scaler metadata":
        scaler_metadata.get(
            "feature_count"
        ),

    "Partition-wise transformation metadata":
        transformation_metadata.get(
            "feature_count"
        ),

    "Model-ready feature metadata":
        model_ready_metadata.get(
            "final_feature_count"
        ),
}


for metadata_name, feature_count in (
    metadata_feature_counts.items()
):

    if int(feature_count) != EXPECTED_FEATURE_COUNT:

        raise ValueError(
            f"{metadata_name} records "
            f"{feature_count} features instead of "
            f"{EXPECTED_FEATURE_COUNT}."
        )

    print(
        f"✓ {metadata_name}: "
        f"{int(feature_count)} features"
    )


# ------------------------------------------------------------
# 9. Validate partition metadata against persisted shapes
# ------------------------------------------------------------

print("\n[PARTITION METADATA CONSISTENCY]")

transformation_partitions = (
    transformation_metadata.get(
        "partitions",
        {}
    )
)

expected_partition_names = [
    "Training",
    "Validation",
    "Test",
]


for partition_name in expected_partition_names:

    if partition_name not in transformation_partitions:

        raise ValueError(
            "Partition-wise transformation metadata "
            f"does not contain '{partition_name}'."
        )

    metadata_rows = int(
        transformation_partitions[
            partition_name
        ].get(
            "rows"
        )
    )

    persisted_rows = actual_partition_shapes[
        partition_name
    ][0]

    if metadata_rows != persisted_rows:

        raise ValueError(
            f"{partition_name} row-count mismatch between "
            "transformation metadata and persisted feature "
            f"artifact: metadata={metadata_rows:,}, "
            f"artifact={persisted_rows:,}"
        )

    metadata_features = len(
        transformation_feature_order
    )

    if actual_partition_shapes[
        partition_name
    ][1] != metadata_features:

        raise ValueError(
            f"{partition_name} feature-count mismatch between "
            "metadata and persisted feature artifact."
        )

    print(
        f"✓ {partition_name:<10} : "
        f"{metadata_rows:,} rows × "
        f"{metadata_features} features"
    )


# ------------------------------------------------------------
# 10. Final integrity boundary
# ------------------------------------------------------------

print("\n[MODEL-READY FEATURE INTEGRITY BOUNDARY]")

print(
    "✓ No Stage-1 dataset reloaded"
)

print(
    "✓ No complete model-ready feature matrix loaded into RAM"
)

print(
    "✓ Persisted feature shapes inspected using memory mapping"
)

print(
    "✓ No feature selection repeated"
)

print(
    "✓ No feature order modified"
)

print(
    "✓ No scaling or transformation performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No partition modification performed"
)

print(
    "✓ No target modification performed"
)

print(
    "✓ No model fitting performed"
)


# ------------------------------------------------------------
# 11. Final completion
# ------------------------------------------------------------

print("\n[4.11.2 VALIDATION SUMMARY]")

print(
    "✓ Training feature artifact: "
    f"{actual_partition_shapes['Training']}"
)

print(
    "✓ Validation feature artifact: "
    f"{actual_partition_shapes['Validation']}"
)

print(
    "✓ Independent Test feature artifact: "
    f"{actual_partition_shapes['Test']}"
)

print(
    f"✓ Final feature count: "
    f"{EXPECTED_FEATURE_COUNT}"
)

print(
    "✓ Feature order consistent across all "
    "persisted model-ready metadata"
)

print(
    "✓ Model-ready feature space is structurally consistent "
    "for downstream development"
)


print("\n" + "=" * 72)

print(
    "4.11.2 shape and feature-order validation "
    "completed successfully."
)

print("=" * 72)

========================================================================
4.11.2 — SHAPE & FEATURE-ORDER VALIDATION
========================================================================

[RECOVERY STATE]
✓ Required feature-selection and feature-scaling metadata recovered

[PERSISTED ARTIFACT CHECK]
✓ Training scaled feature artifact: X_train_scaled.npy
✓ Validation scaled feature artifact: X_validation_scaled.npy
✓ Test scaled feature artifact: X_test_scaled.npy
✓ Selected-feature artifact: correlation_pruned_selected_features.json
✓ Training-only scaler metadata: training_only_scaler_metadata.json
✓ Partition-wise transformation metadata: partition_wise_transformation_metadata.json
✓ Model-ready feature metadata: model_ready_feature_artifacts.json

[PARTITION SHAPE VALIDATION]
✓ Training   : (1814018, 32)
✓ Validation : (451215, 32)
✓ Test       : (565510, 32)
✓ Training, Validation, and Test dimensions match the established model-ready configuration
✓ All partitions contain exactly 32 features

[FEATURE-ORDER VALIDATION]
✓ Selected-feature artifact matches the authoritative feature order
✓ Training-only scaler metadata matches the authoritative feature order
✓ Partition-wise transformation metadata matches the authoritative feature order
✓ Model-ready feature metadata matches the authoritative feature order
✓ Exact feature order preserved across 4 persisted artifacts

[FEATURE-COUNT METADATA VALIDATION]
✓ Training-only scaler metadata: 32 features
✓ Partition-wise transformation metadata: 32 features
✓ Model-ready feature metadata: 32 features

[PARTITION METADATA CONSISTENCY]
✓ Training   : 1,814,018 rows × 32 features
✓ Validation : 451,215 rows × 32 features
✓ Test       : 565,510 rows × 32 features

[MODEL-READY FEATURE INTEGRITY BOUNDARY]
✓ No Stage-1 dataset reloaded
✓ No complete model-ready feature matrix loaded into RAM
✓ Persisted feature shapes inspected using memory mapping
✓ No feature selection repeated
✓ No feature order modified
✓ No scaling or transformation performed
✓ No resampling performed
✓ No partition modification performed
✓ No target modification performed
✓ No model fitting performed

[4.11.2 VALIDATION SUMMARY]
✓ Training feature artifact: (1814018, 32)
✓ Validation feature artifact: (451215, 32)
✓ Independent Test feature artifact: (565510, 32)
✓ Final feature count: 32
✓ Feature order consistent across all persisted model-ready metadata
✓ Model-ready feature space is structurally consistent for downstream development

========================================================================
4.11.2 shape and feature-order validation completed successfully.
========================================================================

## 4.11.3 — Label & Partition Integrity Validation

This subsection validates the integrity of the persisted model-ready target
artifacts and the established Training, Validation, and independent Test
partition configuration recovered in Section 4.11.1.

The validation checks the persisted training, validation, and test target
artifacts against the authoritative nine-class taxonomy, including the
established class IDs 0–8. Target-array dimensionality, partition sizes,
integer class-ID validity, complete class coverage, and persisted class
distributions are independently verified.

The persisted target metadata is also compared against the actual target
artifacts to confirm that target values and class distributions remain
consistent after persistence.

Partition integrity is validated using the authoritative persisted partition
metadata and final train/validation/test leakage-validation metadata. In
particular, the validation confirms the established partition sizes,
independent Test isolation, and the recorded absence of partition
modification during final artifact persistence.

No Stage-1 dataset is reloaded, no target values are remapped or modified,
no resampling or class weighting is performed, no partition is changed, and
no model fitting is performed.

Successful completion establishes that the recovered model-ready targets
and partition configuration are consistent with the finalized N04 data
contract and are suitable for downstream model-development stages.

In [61]:
# ============================================================
# 4.11.3 — LABEL & PARTITION INTEGRITY VALIDATION
# ============================================================

import json
import numpy as np
from pathlib import Path

print("=" * 72)
print("4.11.3 — LABEL & PARTITION INTEGRITY VALIDATION")
print("=" * 72)


# ------------------------------------------------------------
# 1. Validate required cold-start recovery state
# ------------------------------------------------------------

required_recovery_objects = [
    "target_artifact_metadata",
    "taxonomy_metadata",
    "partition_reproducibility_metadata",
    "final_leakage_validation",
]

missing_recovery_objects = [
    object_name
    for object_name in required_recovery_objects
    if object_name not in recovered_artifacts
]

if missing_recovery_objects:

    raise ValueError(
        "Required 4.11.1 recovery objects are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_recovery_objects
        )
    )

print("\n[RECOVERY STATE]")

print(
    "✓ Target, taxonomy, partition, and leakage "
    "metadata recovered"
)


# ------------------------------------------------------------
# 2. Establish authoritative final taxonomy
# ------------------------------------------------------------

EXPECTED_CLASS_MAPPING = {
    "BENIGN": 0,
    "DDoS": 1,
    "Port Scan": 2,
    "Brute Force": 3,
    "Bot": 4,
    "Web Attack": 5,
    "Infiltration": 6,
    "DoS": 7,
    "Heartbleed": 8,
}

EXPECTED_CLASS_IDS = list(
    range(
        len(EXPECTED_CLASS_MAPPING)
    )
)

EXPECTED_CLASS_COUNT = len(
    EXPECTED_CLASS_MAPPING
)


print("\n[FINAL TAXONOMY VALIDATION]")

if EXPECTED_CLASS_COUNT != 9:

    raise ValueError(
        "Expected the established nine-class taxonomy."
    )

if sorted(
    EXPECTED_CLASS_MAPPING.values()
) != EXPECTED_CLASS_IDS:

    raise ValueError(
        "Authoritative final class IDs are not "
        "consecutive integers 0–8."
    )

print(
    "✓ Nine-class taxonomy confirmed"
)

print(
    "✓ Class IDs 0–8 confirmed"
)

for class_name, class_id in (
    EXPECTED_CLASS_MAPPING.items()
):

    print(
        f"✓ {class_id}: {class_name}"
    )


# ------------------------------------------------------------
# 3. Validate recovered taxonomy metadata
#
# IMPORTANT:
# The persisted taxonomy_metadata.json schema is:
#
# dataset.final_class_count
# taxonomy_definition.total_final_classes
# taxonomy_definition.attack_family_count
# taxonomy_definition.normal_traffic_class
# final_classes
#
# It does NOT contain a top-level class_count or
# class_id_mapping field.
# ------------------------------------------------------------

print("\n[RECOVERED TAXONOMY METADATA]")

taxonomy_metadata = recovered_artifacts[
    "taxonomy_metadata"
]


dataset_metadata = taxonomy_metadata.get(
    "dataset",
    {}
)

taxonomy_definition = taxonomy_metadata.get(
    "taxonomy_definition",
    {}
)

persisted_final_classes = taxonomy_metadata.get(
    "final_classes",
    {}
)


if int(
    dataset_metadata.get(
        "final_class_count",
        -1
    )
) != EXPECTED_CLASS_COUNT:

    raise ValueError(
        "Persisted taxonomy metadata reports an "
        "inconsistent final class count:\n"
        f"Expected: {EXPECTED_CLASS_COUNT}\n"
        f"Observed: "
        f"{dataset_metadata.get('final_class_count')}"
    )


if int(
    taxonomy_definition.get(
        "total_final_classes",
        -1
    )
) != EXPECTED_CLASS_COUNT:

    raise ValueError(
        "Persisted taxonomy definition reports an "
        "inconsistent final class count:\n"
        f"Expected: {EXPECTED_CLASS_COUNT}\n"
        f"Observed: "
        f"{taxonomy_definition.get('total_final_classes')}"
    )


if int(
    taxonomy_definition.get(
        "attack_family_count",
        -1
    )
) != 8:

    raise ValueError(
        "Persisted taxonomy definition does not "
        "confirm eight attack families."
    )


if taxonomy_definition.get(
    "normal_traffic_class"
) != "BENIGN":

    raise ValueError(
        "Persisted taxonomy does not identify "
        "BENIGN as the normal-traffic class."
    )


# Convert persisted ID → class-name mapping into
# the authoritative class-name → ID representation.
#
# JSON object keys are strings, so the IDs are explicitly
# converted back to integers for comparison.

normalized_persisted_classes = {
    str(class_name): int(class_id)
    for class_id, class_name
    in persisted_final_classes.items()
}


if normalized_persisted_classes != {
    str(class_name): int(class_id)
    for class_name, class_id
    in EXPECTED_CLASS_MAPPING.items()
}:

    raise ValueError(
        "Persisted taxonomy final_classes mapping does "
        "not match the authoritative N04 taxonomy.\n"
        f"Expected: {EXPECTED_CLASS_MAPPING}\n"
        f"Observed: {normalized_persisted_classes}"
    )


print(
    "✓ Persisted taxonomy final class count matches"
)

print(
    "✓ Persisted taxonomy confirms eight attack families"
)

print(
    "✓ Persisted taxonomy confirms BENIGN as "
    "normal traffic"
)

print(
    "✓ Persisted taxonomy class-ID mapping matches "
    "the authoritative N04 taxonomy"
)


# ------------------------------------------------------------
# 4. Establish persisted target artifact paths
# ------------------------------------------------------------

TARGET_ARTIFACT_DIR = (
    RECOVERY_MODEL_PREPARATION_V2_DIR /
    "model_ready_targets"
)

TARGET_PATHS = {

    "Training":
        TARGET_ARTIFACT_DIR /
        "y_train.npy",

    "Validation":
        TARGET_ARTIFACT_DIR /
        "y_validation.npy",

    "Test":
        TARGET_ARTIFACT_DIR /
        "y_test.npy",
}


print("\n[PERSISTED TARGET ARTIFACT CHECK]")

missing_target_artifacts = []

for partition_name, target_path in (
    TARGET_PATHS.items()
):

    if not target_path.is_file():

        missing_target_artifacts.append(
            f"{partition_name}: {target_path}"
        )

    else:

        print(
            f"✓ {partition_name} target artifact: "
            f"{target_path.name}"
        )


if missing_target_artifacts:

    raise FileNotFoundError(
        "Required persisted target artifacts are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_target_artifacts
        )
    )


# ------------------------------------------------------------
# 5. Recover target artifact metadata
# ------------------------------------------------------------

target_metadata = recovered_artifacts[
    "target_artifact_metadata"
]

target_taxonomy = target_metadata.get(
    "taxonomy",
    {}
)

target_partition_sizes = target_metadata.get(
    "partition_sizes",
    {}
)

target_distribution_metadata = target_metadata.get(
    "target_distribution",
    {}
)


if int(
    target_taxonomy.get(
        "class_count",
        -1
    )
) != EXPECTED_CLASS_COUNT:

    raise ValueError(
        "Target artifact metadata does not confirm "
        "the established nine-class taxonomy."
    )


metadata_class_ids = [
    int(class_id)
    for class_id in target_taxonomy.get(
        "class_ids",
        []
    )
]


if metadata_class_ids != EXPECTED_CLASS_IDS:

    raise ValueError(
        "Target artifact metadata contains "
        "inconsistent class IDs.\n"
        f"Expected: {EXPECTED_CLASS_IDS}\n"
        f"Observed: {metadata_class_ids}"
    )


# Validate the target artifact's own persisted
# class-name → class-ID mapping.

target_class_mapping = {
    str(class_name): int(class_id)
    for class_name, class_id
    in target_taxonomy.get(
        "class_mapping",
        {}
    ).items()
}


if target_class_mapping != EXPECTED_CLASS_MAPPING:

    raise ValueError(
        "Target artifact metadata contains an "
        "inconsistent class mapping.\n"
        f"Expected: {EXPECTED_CLASS_MAPPING}\n"
        f"Observed: {target_class_mapping}"
    )


print("\n[TARGET METADATA VALIDATION]")

print(
    "✓ Target metadata confirms nine classes"
)

print(
    "✓ Target metadata confirms class IDs 0–8"
)

print(
    "✓ Target metadata class mapping matches "
    "the authoritative taxonomy"
)


# ------------------------------------------------------------
# 6. Validate persisted target arrays
# ------------------------------------------------------------

print("\n[TARGET ARRAY VALIDATION]")

expected_partition_sizes = {

    "Training":
        1_814_018,

    "Validation":
        451_215,

    "Test":
        565_510,
}


observed_target_distributions = {}


for partition_name, target_path in (
    TARGET_PATHS.items()
):

    # Memory-map the target artifact so that the persisted
    # target array is not unnecessarily copied into RAM.
    targets = np.load(
        target_path,
        mmap_mode="r"
    )


    # --------------------------------------------------------
    # Shape validation
    # --------------------------------------------------------

    if targets.ndim != 1:

        actual_shape = targets.shape

        del targets

        raise ValueError(
            f"{partition_name} target artifact must be "
            f"one-dimensional; found shape {actual_shape}."
        )


    # --------------------------------------------------------
    # Data-type validation
    # --------------------------------------------------------

    if not np.issubdtype(
        targets.dtype,
        np.integer
    ):

        observed_dtype = targets.dtype

        del targets

        raise ValueError(
            f"{partition_name} target artifact is not "
            f"integer-valued: {observed_dtype}"
        )


    # --------------------------------------------------------
    # Partition-size validation
    # --------------------------------------------------------

    actual_size = int(
        targets.shape[0]
    )

    expected_size = (
        expected_partition_sizes[
            partition_name
        ]
    )

    if actual_size != expected_size:

        del targets

        raise ValueError(
            f"{partition_name} target size mismatch: "
            f"expected {expected_size:,}, "
            f"found {actual_size:,}"
        )


    # --------------------------------------------------------
    # Class-ID validation
    # --------------------------------------------------------

    observed_classes = sorted(
        int(class_id)
        for class_id in np.unique(
            targets
        )
    )

    if observed_classes != EXPECTED_CLASS_IDS:

        del targets

        raise ValueError(
            f"{partition_name} target artifact contains "
            "an inconsistent class-ID set.\n"
            f"Expected: {EXPECTED_CLASS_IDS}\n"
            f"Observed: {observed_classes}"
        )


    # --------------------------------------------------------
    # Class-distribution validation
    # --------------------------------------------------------

    counts = np.bincount(
        targets,
        minlength=EXPECTED_CLASS_COUNT
    )

    distribution = {
        str(class_id): int(
            counts[class_id]
        )
        for class_id in EXPECTED_CLASS_IDS
    }

    observed_target_distributions[
        partition_name.lower()
    ] = distribution


    print(
        f"✓ {partition_name:<10}: "
        f"{actual_size:,} labels | "
        f"dtype={targets.dtype} | "
        f"classes={observed_classes}"
    )

    del targets


# ------------------------------------------------------------
# 7. Compare actual target distributions with metadata
# ------------------------------------------------------------

print("\n[TARGET DISTRIBUTION INTEGRITY]")

for partition_name, observed_distribution in (
    observed_target_distributions.items()
):

    metadata_distribution = (
        target_distribution_metadata.get(
            partition_name,
            {}
        )
    )


    if not metadata_distribution:

        raise ValueError(
            "Target artifact metadata does not contain "
            f"a distribution for '{partition_name}'."
        )


    normalized_metadata_distribution = {
        str(class_id): int(count)
        for class_id, count
        in metadata_distribution.items()
    }


    if (
        normalized_metadata_distribution
        != observed_distribution
    ):

        raise ValueError(
            f"Target distribution mismatch for "
            f"{partition_name}.\n"
            f"Metadata: "
            f"{normalized_metadata_distribution}\n"
            f"Observed: "
            f"{observed_distribution}"
        )


    print(
        f"✓ {partition_name.capitalize()} class distribution "
        "matches persisted metadata"
    )


# ------------------------------------------------------------
# 8. Validate target partition sizes against metadata
# ------------------------------------------------------------

print("\n[TARGET PARTITION-SIZE CONSISTENCY]")

for partition_name, expected_size in (
    expected_partition_sizes.items()
):

    metadata_size = int(
        target_partition_sizes.get(
            partition_name.lower(),
            -1
        )
    )


    if metadata_size != expected_size:

        raise ValueError(
            f"Target metadata partition-size mismatch "
            f"for {partition_name}: "
            f"expected {expected_size:,}, "
            f"found {metadata_size:,}"
        )


    print(
        f"✓ {partition_name:<10}: "
        f"{metadata_size:,} target values"
    )


# ------------------------------------------------------------
# 9. Validate target-integrity metadata
# ------------------------------------------------------------

print("\n[TARGET INTEGRITY BOUNDARY]")

target_integrity = target_metadata.get(
    "integrity",
    {}
)


expected_false_flags = {

    "labels_modified":
        False,

    "labels_remapped":
        False,

    "labels_reordered":
        False,

    "resampling_performed":
        False,

    "class_weighting_performed":
        False,

    "feature_transformation_performed":
        False,

    "partition_modification_performed":
        False,

    "model_fitting_performed":
        False,

    "stage1_dataset_reloaded":
        False,
}


for flag_name, expected_value in (
    expected_false_flags.items()
):

    actual_value = target_integrity.get(
        flag_name
    )


    if actual_value is not expected_value:

        raise ValueError(
            f"Target integrity flag '{flag_name}' "
            f"does not match the established boundary: "
            f"expected {expected_value}, "
            f"found {actual_value}"
        )


    print(
        f"✓ {flag_name}: {actual_value}"
    )


# ------------------------------------------------------------
# 10. Validate persisted partition architecture
# ------------------------------------------------------------

print("\n[PARTITION ARCHITECTURE VALIDATION]")

partition_metadata = recovered_artifacts[
    "partition_reproducibility_metadata"
]

partition_architecture = partition_metadata.get(
    "partition_architecture",
    {}
)


expected_partition_architecture = {

    "development_rows":
        2_265_233,

    "training_rows":
        1_814_018,

    "validation_rows":
        451_215,

    "test_rows":
        565_510,
}


for metadata_key, expected_size in (
    expected_partition_architecture.items()
):

    actual_size = int(
        partition_architecture.get(
            metadata_key,
            -1
        )
    )


    if actual_size != expected_size:

        raise ValueError(
            f"Partition architecture mismatch for "
            f"{metadata_key}: "
            f"expected {expected_size:,}, "
            f"found {actual_size:,}"
        )


    print(
        f"✓ {metadata_key}: "
        f"{actual_size:,}"
    )


# ------------------------------------------------------------
# 11. Validate persisted partition leakage metadata
# ------------------------------------------------------------

print("\n[PARTITION LEAKAGE VALIDATION]")

leakage_metadata = recovered_artifacts[
    "final_leakage_validation"
]


if leakage_metadata.get(
    "validation_status"
) != "PASSED":

    raise ValueError(
        "Final train/validation/test leakage validation "
        "is not recorded as PASSED."
    )


expected_index_overlaps = {
    "training_validation": 0,
    "training_test": 0,
    "validation_test": 0,
}


actual_index_overlaps = (
    leakage_metadata.get(
        "index_overlap",
        {}
    )
)


for overlap_name, expected_overlap in (
    expected_index_overlaps.items()
):

    actual_overlap = int(
        actual_index_overlaps.get(
            overlap_name,
            -1
        )
    )


    if actual_overlap != expected_overlap:

        raise ValueError(
            f"Persisted index-overlap validation failed "
            f"for {overlap_name}: "
            f"expected {expected_overlap}, "
            f"found {actual_overlap}"
        )


    print(
        f"✓ {overlap_name}: "
        f"{actual_overlap}"
    )


expected_feature_vector_overlaps = {
    "training_validation": 0,
    "training_test": 0,
    "validation_test": 0,
}


actual_feature_vector_overlaps = (
    leakage_metadata.get(
        "feature_vector_overlap",
        {}
    )
)


for overlap_name, expected_overlap in (
    expected_feature_vector_overlaps.items()
):

    actual_overlap = int(
        actual_feature_vector_overlaps.get(
            overlap_name,
            -1
        )
    )


    if actual_overlap != expected_overlap:

        raise ValueError(
            "Persisted feature-vector overlap validation "
            f"failed for {overlap_name}: "
            f"expected {expected_overlap}, "
            f"found {actual_overlap}"
        )


    print(
        f"✓ {overlap_name} feature-vector overlap: "
        f"{actual_overlap}"
    )


print(
    "✓ Final leakage validation status: PASSED"
)


# ------------------------------------------------------------
# 12. Validate taxonomy coverage in every partition
# ------------------------------------------------------------

print("\n[TAXONOMY COVERAGE VALIDATION]")

taxonomy_coverage = leakage_metadata.get(
    "taxonomy_coverage",
    {}
)


for partition_name in (
    "training",
    "validation",
    "test"
):

    observed_class_count = int(
        taxonomy_coverage.get(
            partition_name,
            -1
        )
    )


    if observed_class_count != EXPECTED_CLASS_COUNT:

        raise ValueError(
            f"{partition_name.capitalize()} partition does "
            "not contain all nine final taxonomy classes."
        )


    print(
        f"✓ {partition_name.capitalize()} contains "
        f"all {EXPECTED_CLASS_COUNT} final classes"
    )


# ------------------------------------------------------------
# 13. Validate partition processing boundary
# ------------------------------------------------------------

print("\n[PARTITION PROCESSING BOUNDARY]")

processing_status = leakage_metadata.get(
    "processing_status",
    {}
)


expected_processing_flags = {

    "rows_removed":
        False,

    "labels_modified":
        False,

    "feature_values_modified":
        False,

    "feature_selection_performed":
        False,

    "scaling_performed":
        False,

    "resampling_performed":
        False,

    "model_fitting_performed":
        False,
}


for flag_name, expected_value in (
    expected_processing_flags.items()
):

    actual_value = processing_status.get(
        flag_name
    )


    if actual_value is not expected_value:

        raise ValueError(
            f"Partition processing flag '{flag_name}' "
            f"is inconsistent: "
            f"expected {expected_value}, "
            f"found {actual_value}"
        )


    print(
        f"✓ {flag_name}: {actual_value}"
    )


# ------------------------------------------------------------
# 14. Validate independent Test isolation
# ------------------------------------------------------------

print("\n[INDEPENDENT TEST ISOLATION]")

partition_leakage_control = (
    partition_metadata.get(
        "leakage_control",
        {}
    )
)


if partition_leakage_control.get(
    "test_partition_isolated"
) is not True:

    raise ValueError(
        "Persisted partition metadata does not confirm "
        "independent Test isolation."
    )


if partition_leakage_control.get(
    "cross_partition_identical_feature_vectors"
) != 0:

    raise ValueError(
        "Persisted partition metadata reports "
        "cross-partition identical feature vectors."
    )


print(
    "✓ Independent Test partition isolation confirmed"
)

print(
    "✓ Cross-partition identical feature vectors: 0"
)


# ------------------------------------------------------------
# 15. Final label & partition integrity summary
# ------------------------------------------------------------

print("\n[4.11.3 VALIDATION SUMMARY]")

print(
    "✓ Nine-class target taxonomy preserved"
)

print(
    "✓ Class IDs 0–8 preserved"
)

print(
    "✓ Target class mapping preserved"
)

print(
    "✓ Training target artifact validated"
)

print(
    "✓ Validation target artifact validated"
)

print(
    "✓ Independent Test target artifact validated"
)

print(
    "✓ All target arrays are one-dimensional integer labels"
)

print(
    "✓ Target partition sizes match the established "
    "N04 configuration"
)

print(
    "✓ Target class distributions match persisted metadata"
)

print(
    "✓ Target-integrity flags confirm no label modification "
    "or remapping"
)

print(
    "✓ Training/Validation/Test index overlaps are zero"
)

print(
    "✓ Cross-partition identical feature-vector overlaps are zero"
)

print(
    "✓ All nine taxonomy classes are represented in "
    "Training, Validation, and Test"
)

print(
    "✓ Independent Test isolation remains confirmed"
)

print(
    "✓ No partition-processing modifications recorded"
)

print(
    "✓ No Stage-1 dataset reloaded"
)

print(
    "✓ No target modification performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No model fitting performed"
)


print("\n" + "=" * 72)

print(
    "4.11.3 label and partition integrity validation "
    "completed successfully."
)

print("=" * 72)

========================================================================
4.11.3 — LABEL & PARTITION INTEGRITY VALIDATION
========================================================================

[RECOVERY STATE]
✓ Target, taxonomy, partition, and leakage metadata recovered

[FINAL TAXONOMY VALIDATION]
✓ Nine-class taxonomy confirmed
✓ Class IDs 0–8 confirmed
✓ 0: BENIGN
✓ 1: DDoS
✓ 2: Port Scan
✓ 3: Brute Force
✓ 4: Bot
✓ 5: Web Attack
✓ 6: Infiltration
✓ 7: DoS
✓ 8: Heartbleed

[RECOVERED TAXONOMY METADATA]
✓ Persisted taxonomy final class count matches
✓ Persisted taxonomy confirms eight attack families
✓ Persisted taxonomy confirms BENIGN as normal traffic
✓ Persisted taxonomy class-ID mapping matches the authoritative N04 taxonomy

[PERSISTED TARGET ARTIFACT CHECK]
✓ Training target artifact: y_train.npy
✓ Validation target artifact: y_validation.npy
✓ Test target artifact: y_test.npy

[TARGET METADATA VALIDATION]
✓ Target metadata confirms nine classes
✓ Target metadata confirms class IDs 0–8
✓ Target metadata class mapping matches the authoritative taxonomy

[TARGET ARRAY VALIDATION]
✓ Training  : 1,814,018 labels | dtype=int64 | classes=[0, 1, 2, 3, 4, 5, 6, 7, 8]
✓ Validation: 451,215 labels | dtype=int64 | classes=[0, 1, 2, 3, 4, 5, 6, 7, 8]
✓ Test      : 565,510 labels | dtype=int64 | classes=[0, 1, 2, 3, 4, 5, 6, 7, 8]

[TARGET DISTRIBUTION INTEGRITY]
✓ Training class distribution matches persisted metadata
✓ Validation class distribution matches persisted metadata
✓ Test class distribution matches persisted metadata

[TARGET PARTITION-SIZE CONSISTENCY]
✓ Training  : 1,814,018 target values
✓ Validation: 451,215 target values
✓ Test      : 565,510 target values

[TARGET INTEGRITY BOUNDARY]
✓ labels_modified: False
✓ labels_remapped: False
✓ labels_reordered: False
✓ resampling_performed: False
✓ class_weighting_performed: False
✓ feature_transformation_performed: False
✓ partition_modification_performed: False
✓ model_fitting_performed: False
✓ stage1_dataset_reloaded: False

[PARTITION ARCHITECTURE VALIDATION]
✓ development_rows: 2,265,233
✓ training_rows: 1,814,018
✓ validation_rows: 451,215
✓ test_rows: 565,510

[PARTITION LEAKAGE VALIDATION]
✓ training_validation: 0
✓ training_test: 0
✓ validation_test: 0
✓ training_validation feature-vector overlap: 0
✓ training_test feature-vector overlap: 0
✓ validation_test feature-vector overlap: 0
✓ Final leakage validation status: PASSED

[TAXONOMY COVERAGE VALIDATION]
✓ Training contains all 9 final classes
✓ Validation contains all 9 final classes
✓ Test contains all 9 final classes

[PARTITION PROCESSING BOUNDARY]
✓ rows_removed: False
✓ labels_modified: False
✓ feature_values_modified: False
✓ feature_selection_performed: False
✓ scaling_performed: False
✓ resampling_performed: False
✓ model_fitting_performed: False

[INDEPENDENT TEST ISOLATION]
✓ Independent Test partition isolation confirmed
✓ Cross-partition identical feature vectors: 0

[4.11.3 VALIDATION SUMMARY]
✓ Nine-class target taxonomy preserved
✓ Class IDs 0–8 preserved
✓ Target class mapping preserved
✓ Training target artifact validated
✓ Validation target artifact validated
✓ Independent Test target artifact validated
✓ All target arrays are one-dimensional integer labels
✓ Target partition sizes match the established N04 configuration
✓ Target class distributions match persisted metadata
✓ Target-integrity flags confirm no label modification or remapping
✓ Training/Validation/Test index overlaps are zero
✓ Cross-partition identical feature-vector overlaps are zero
✓ All nine taxonomy classes are represented in Training, Validation, and Test
✓ Independent Test isolation remains confirmed
✓ No partition-processing modifications recorded
✓ No Stage-1 dataset reloaded
✓ No target modification performed
✓ No resampling performed
✓ No model fitting performed

========================================================================
4.11.3 label and partition integrity validation completed successfully.
========================================================================

## 4.11.4 — Scaler Reproducibility Validation

This subsection validates the reproducibility of the persisted Training-only
feature-scaling configuration recovered from the finalized N04 artifact
boundary.

The persisted StandardScaler is reloaded and its fitted parameters,
observed Training sample count, feature dimensionality, feature ordering, and
training-only fitting metadata are verified against the authoritative N04
configuration.

The persisted partition-wise transformation metadata is also checked to
confirm that the same Training-fitted scaler was applied to Training,
Validation, and independent Test data, while Validation and Test observations
were excluded from scaler fitting.

Reproducibility of the persisted scaler transformation is additionally
validated using small memory-mapped samples from the persisted scaled feature
artifacts. Each sample is inverse-transformed and transformed again using the
recovered scaler, and the resulting values are compared with the original
persisted scaled representation within a floating-point tolerance.

This validation does not refit the scaler, regenerate the scaled feature
matrices, reload the Stage-1 dataset, modify any partition or target, perform
resampling, or fit any model.

Successful completion establishes that the persisted Training-only scaler
can be recovered and used reproducibly with the finalized 32-feature
model-ready representation.

In [62]:
# ============================================================
# 4.11.4 — SCALER REPRODUCIBILITY VALIDATION
# ============================================================

import json
import joblib
import numpy as np

print("=" * 72)
print("4.11.4 — SCALER REPRODUCIBILITY VALIDATION")
print("=" * 72)


# ------------------------------------------------------------
# 1. Validate required cold-start recovery state
# ------------------------------------------------------------

required_recovery_objects = [
    "training_scaler_metadata",
    "transformation_metadata",
    "model_ready_feature_metadata",
    "final_scaling_validation",
    "selected_features",
]

missing_recovery_objects = [
    object_name
    for object_name in required_recovery_objects
    if object_name not in recovered_artifacts
]

if missing_recovery_objects:

    raise ValueError(
        "Required 4.11.1 recovery objects are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_recovery_objects
        )
    )

print("\n[RECOVERY STATE]")

print(
    "✓ Training-only scaler and scaling metadata recovered"
)


# ------------------------------------------------------------
# 2. Establish persisted scaling artifact paths
# ------------------------------------------------------------

RECOVERY_FEATURE_SCALING_DIR = (
    RECOVERY_MODEL_PREPARATION_V2_DIR /
    "feature_scaling"
)


RECOVERY_SCALER_PATH = (
    RECOVERY_FEATURE_SCALING_DIR /
    "training_only_standard_scaler.joblib"
)

RECOVERY_SCALER_METADATA_PATH = (
    RECOVERY_FEATURE_SCALING_DIR /
    "training_only_scaler_metadata.json"
)

RECOVERY_TRANSFORMATION_METADATA_PATH = (
    RECOVERY_FEATURE_SCALING_DIR /
    "partition_wise_transformation_metadata.json"
)

RECOVERY_MODEL_READY_METADATA_PATH = (
    RECOVERY_FEATURE_SCALING_DIR /
    "model_ready_feature_artifacts.json"
)

RECOVERY_FINAL_SCALING_VALIDATION_PATH = (
    RECOVERY_FEATURE_SCALING_DIR /
    "final_scaling_reproducibility_validation.json"
)


RECOVERY_SCALED_PATHS = {

    "Training":
        RECOVERY_FEATURE_SCALING_DIR /
        "X_train_scaled.npy",

    "Validation":
        RECOVERY_FEATURE_SCALING_DIR /
        "X_validation_scaled.npy",

    "Test":
        RECOVERY_FEATURE_SCALING_DIR /
        "X_test_scaled.npy",
}


required_scaling_paths = {

    "Training-only scaler":
        RECOVERY_SCALER_PATH,

    "Training-only scaler metadata":
        RECOVERY_SCALER_METADATA_PATH,

    "Partition-wise transformation metadata":
        RECOVERY_TRANSFORMATION_METADATA_PATH,

    "Model-ready feature metadata":
        RECOVERY_MODEL_READY_METADATA_PATH,

    "Final scaling reproducibility record":
        RECOVERY_FINAL_SCALING_VALIDATION_PATH,

    "Training scaled data":
        RECOVERY_SCALED_PATHS["Training"],

    "Validation scaled data":
        RECOVERY_SCALED_PATHS["Validation"],

    "Test scaled data":
        RECOVERY_SCALED_PATHS["Test"],
}


print("\n[PERSISTED SCALING ARTIFACT CHECK]")

missing_scaling_paths = []

for artifact_name, artifact_path in (
    required_scaling_paths.items()
):

    if not artifact_path.is_file():

        missing_scaling_paths.append(
            f"{artifact_name}: {artifact_path}"
        )

    else:

        print(
            f"✓ {artifact_name}: "
            f"{artifact_path.name}"
        )


if missing_scaling_paths:

    raise FileNotFoundError(
        "Required scaling artifacts are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_scaling_paths
        )
    )


# ------------------------------------------------------------
# 3. Reload the persisted Training-only scaler
# ------------------------------------------------------------

print("\n[TRAINING-ONLY SCALER RECOVERY]")

persisted_scaler = joblib.load(
    RECOVERY_SCALER_PATH
)


if type(
    persisted_scaler
).__name__ != "StandardScaler":

    raise ValueError(
        "Persisted scaler is not a StandardScaler. "
        f"Found: {type(persisted_scaler).__name__}"
    )


if not hasattr(
    persisted_scaler,
    "mean_"
):

    raise ValueError(
        "Persisted StandardScaler does not contain "
        "mean_ parameters."
    )


if not hasattr(
    persisted_scaler,
    "scale_"
):

    raise ValueError(
        "Persisted StandardScaler does not contain "
        "scale_ parameters."
    )


if not hasattr(
    persisted_scaler,
    "var_"
):

    raise ValueError(
        "Persisted StandardScaler does not contain "
        "var_ parameters."
    )


if not hasattr(
    persisted_scaler,
    "n_samples_seen_"
):

    raise ValueError(
        "Persisted StandardScaler does not contain "
        "n_samples_seen_."
    )


scaler_feature_count = len(
    persisted_scaler.mean_
)


if scaler_feature_count != 32:

    raise ValueError(
        "Persisted scaler contains "
        f"{scaler_feature_count} feature parameters "
        "instead of 32."
    )


if len(
    persisted_scaler.scale_
) != 32:

    raise ValueError(
        "Persisted scaler scale_ contains an "
        "unexpected number of feature parameters."
    )


if len(
    persisted_scaler.var_
) != 32:

    raise ValueError(
        "Persisted scaler var_ contains an "
        "unexpected number of feature parameters."
    )


if int(
    persisted_scaler.n_samples_seen_
) != 1_814_018:

    raise ValueError(
        "Persisted scaler observed an unexpected "
        "number of Training samples: "
        f"{persisted_scaler.n_samples_seen_}"
    )


if not np.isfinite(
    persisted_scaler.mean_
).all():

    raise ValueError(
        "Persisted scaler contains non-finite mean values."
    )


if not np.isfinite(
    persisted_scaler.scale_
).all():

    raise ValueError(
        "Persisted scaler contains non-finite scale values."
    )


if not np.isfinite(
    persisted_scaler.var_
).all():

    raise ValueError(
        "Persisted scaler contains non-finite variance values."
    )


if np.any(
    persisted_scaler.scale_ <= 0
):

    raise ValueError(
        "Persisted scaler contains non-positive scale "
        "parameters."
    )


print(
    "✓ StandardScaler reloaded successfully"
)

print(
    "✓ Scaler contains exactly 32 feature parameters"
)

print(
    "✓ Scaler Training observations seen: "
    f"{int(persisted_scaler.n_samples_seen_):,}"
)

print(
    "✓ Scaler mean, variance, and scale parameters "
    "are finite"
)

print(
    "✓ All scaler scale parameters are positive"
)


# ------------------------------------------------------------
# 4. Load persisted scaling metadata
# ------------------------------------------------------------

with open(
    RECOVERY_SCALER_METADATA_PATH,
    "r",
    encoding="utf-8"
) as file:

    scaler_metadata = json.load(
        file
    )


with open(
    RECOVERY_TRANSFORMATION_METADATA_PATH,
    "r",
    encoding="utf-8"
) as file:

    transformation_metadata = json.load(
        file
    )


with open(
    RECOVERY_MODEL_READY_METADATA_PATH,
    "r",
    encoding="utf-8"
) as file:

    model_ready_metadata = json.load(
        file
    )


with open(
    RECOVERY_FINAL_SCALING_VALIDATION_PATH,
    "r",
    encoding="utf-8"
) as file:

    final_scaling_validation = json.load(
        file
    )


print("\n[SCALING METADATA RECOVERY]")

print(
    "✓ Training-only scaler metadata loaded"
)

print(
    "✓ Partition-wise transformation metadata loaded"
)

print(
    "✓ Model-ready feature metadata loaded"
)

print(
    "✓ Existing 4.7.6 reproducibility record loaded"
)


# ------------------------------------------------------------
# 5. Validate scaler metadata against recovered scaler
# ------------------------------------------------------------

print("\n[SCALER METADATA CONSISTENCY]")

if scaler_metadata.get(
    "scaler_type"
) != "StandardScaler":

    raise ValueError(
        "Scaler metadata does not identify "
        "StandardScaler."
    )


if scaler_metadata.get(
    "fit_partition"
) != "Training":

    raise ValueError(
        "Scaler metadata does not record "
        "Training as the fitting partition."
    )


if scaler_metadata.get(
    "validation_used_for_fitting"
) is not False:

    raise ValueError(
        "Scaler metadata indicates Validation data "
        "was used for fitting."
    )


if scaler_metadata.get(
    "test_used_for_fitting"
) is not False:

    raise ValueError(
        "Scaler metadata indicates Test data "
        "was used for fitting."
    )


if int(
    scaler_metadata.get(
        "training_row_count",
        -1
    )
) != 1_814_018:

    raise ValueError(
        "Scaler metadata contains an unexpected "
        "Training row count."
    )


if int(
    scaler_metadata.get(
        "validation_row_count",
        -1
    )
) != 451_215:

    raise ValueError(
        "Scaler metadata contains an unexpected "
        "Validation row count."
    )


if int(
    scaler_metadata.get(
        "test_row_count",
        -1
    )
) != 565_510:

    raise ValueError(
        "Scaler metadata contains an unexpected "
        "Test row count."
    )


if int(
    scaler_metadata.get(
        "feature_count",
        -1
    )
) != 32:

    raise ValueError(
        "Scaler metadata does not record "
        "exactly 32 features."
    )


if int(
    scaler_metadata.get(
        "samples_seen_by_scaler",
        -1
    )
) != int(
    persisted_scaler.n_samples_seen_
):

    raise ValueError(
        "Scaler metadata sample count does not "
        "match the recovered scaler."
    )


print(
    "✓ Scaler type matches persisted StandardScaler"
)

print(
    "✓ Fitting partition recorded as Training only"
)

print(
    "✓ Validation excluded from scaler fitting"
)

print(
    "✓ Independent Test excluded from scaler fitting"
)

print(
    "✓ Training/Validation/Test row counts match"
)

print(
    "✓ Metadata feature count matches recovered scaler"
)

print(
    "✓ Metadata sample count matches recovered scaler"
)


# ------------------------------------------------------------
# 6. Validate feature-order reproducibility
# ------------------------------------------------------------

print("\n[SCALER FEATURE-ORDER VALIDATION]")

selected_features_metadata = recovered_artifacts[
    "selected_features"
]


def recover_feature_order(
    metadata,
    artifact_name
):

    if isinstance(
        metadata,
        list
    ):

        feature_order = list(
            metadata
        )

    elif isinstance(
        metadata,
        dict
    ):

        feature_order = None

        for key in [
            "selected_features",
            "retained_features",
            "features",
            "feature_columns"
        ]:

            candidate = metadata.get(
                key
            )

            if isinstance(
                candidate,
                list
            ):

                feature_order = list(
                    candidate
                )
                break

        if feature_order is None:

            raise ValueError(
                f"Could not recover feature order from "
                f"{artifact_name}."
            )

    else:

        raise ValueError(
            f"Unexpected metadata format in "
            f"{artifact_name}."
        )

    return feature_order


authoritative_feature_order = (
    recover_feature_order(
        selected_features_metadata,
        "correlation_pruned_selected_features.json"
    )
)


scaler_feature_order = (
    scaler_metadata.get(
        "features"
    )
)


transformation_feature_order = (
    transformation_metadata.get(
        "features"
    )
)


if not isinstance(
    scaler_feature_order,
    list
):

    raise ValueError(
        "Training-only scaler metadata does not "
        "contain a valid feature-order list."
    )


if not isinstance(
    transformation_feature_order,
    list
):

    raise ValueError(
        "Partition-wise transformation metadata does not "
        "contain a valid feature-order list."
    )


if scaler_feature_order != (
    authoritative_feature_order
):

    raise ValueError(
        "Scaler metadata feature order does not "
        "match the authoritative selected-feature order."
    )


if transformation_feature_order != (
    authoritative_feature_order
):

    raise ValueError(
        "Transformation metadata feature order does not "
        "match the authoritative selected-feature order."
    )


if model_ready_metadata.get(
    "final_feature_count"
) != 32:

    raise ValueError(
        "Model-ready metadata does not record "
        "32 final features."
    )


print(
    "✓ Scaler metadata feature order matches "
    "the authoritative 32-feature order"
)

print(
    "✓ Transformation metadata feature order matches "
    "the authoritative 32-feature order"
)

print(
    "✓ Model-ready metadata confirms 32 final features"
)


# ------------------------------------------------------------
# 7. Validate partition-wise scaler usage metadata
# ------------------------------------------------------------

print("\n[PARTITION-WISE SCALER USAGE]")

transformation_partitions = (
    transformation_metadata.get(
        "partitions",
        {}
    )
)


expected_partition_usage = {

    "Training": {
        "rows": 1_814_018,
        "used_for_scaler_fitting": True
    },

    "Validation": {
        "rows": 451_215,
        "used_for_scaler_fitting": False
    },

    "Test": {
        "rows": 565_510,
        "used_for_scaler_fitting": False
    }
}


for partition_name, expected_values in (
    expected_partition_usage.items()
):

    if partition_name not in (
        transformation_partitions
    ):

        raise ValueError(
            "Transformation metadata does not contain "
            f"the {partition_name} partition."
        )


    partition_metadata = (
        transformation_partitions[
            partition_name
        ]
    )


    if int(
        partition_metadata.get(
            "rows",
            -1
        )
    ) != expected_values[
        "rows"
    ]:

        raise ValueError(
            f"{partition_name} transformation metadata "
            "contains an unexpected row count."
        )


    if partition_metadata.get(
        "used_for_scaler_fitting"
    ) is not expected_values[
        "used_for_scaler_fitting"
    ]:

        raise ValueError(
            f"{partition_name} scaler-fitting boundary "
            "is inconsistent."
        )


    print(
        f"✓ {partition_name:<10}: "
        f"{int(partition_metadata['rows']):,} rows | "
        f"scaler fitting = "
        f"{partition_metadata['used_for_scaler_fitting']}"
    )


# ------------------------------------------------------------
# 8. Validate existing 4.7.6 reproducibility record
# ------------------------------------------------------------

print("\n[EXISTING 4.7.6 REPRODUCIBILITY RECORD]")

if final_scaling_validation.get(
    "status"
) != "completed":

    raise ValueError(
        "Existing 4.7.6 scaling reproducibility record "
        "is not marked as completed."
    )


if int(
    final_scaling_validation.get(
        "final_feature_count",
        -1
    )
) != 32:

    raise ValueError(
        "Existing 4.7.6 record does not confirm "
        "32 final features."
    )


recorded_scaler = (
    final_scaling_validation.get(
        "scaler",
        {}
    )
)


if recorded_scaler.get(
    "fitted_on"
) != "Training partition only":

    raise ValueError(
        "Existing 4.7.6 record does not confirm "
        "Training-only scaler fitting."
    )


recorded_reproducibility = (
    final_scaling_validation.get(
        "reproducibility_status",
        {}
    )
)


required_reproducibility_flags = {

    "scaler_reload_successful":
        True,

    "partition_shapes_verified":
        True,

    "metadata_verified":
        True,

    "training_only_boundary_verified":
        True,

    "final_feature_configuration_verified":
        True,
}


for flag_name, expected_value in (
    required_reproducibility_flags.items()
):

    if recorded_reproducibility.get(
        flag_name
    ) is not expected_value:

        raise ValueError(
            "Existing 4.7.6 reproducibility record "
            f"does not confirm {flag_name}=True."
        )


print(
    "✓ Existing 4.7.6 record is marked completed"
)

print(
    "✓ Existing record confirms Training-only fitting"
)

print(
    "✓ Existing record confirms scaler reload"
)

print(
    "✓ Existing record confirms partition validation"
)

print(
    "✓ Existing record confirms metadata validation"
)

print(
    "✓ Existing record confirms final feature configuration"
)


# ------------------------------------------------------------
# 9. Memory-conscious transformation reproducibility test
# ------------------------------------------------------------

print("\n[TRANSFORMATION REPRODUCIBILITY TEST]")

REPRODUCIBILITY_SAMPLE_SIZE = 128
REPRODUCIBILITY_ATOL = 1e-6
REPRODUCIBILITY_RTOL = 1e-5


for partition_name, scaled_path in (
    RECOVERY_SCALED_PATHS.items()
):

    scaled_data = np.load(
        scaled_path,
        mmap_mode="r"
    )


    if scaled_data.shape[1] != 32:

        del scaled_data

        raise ValueError(
            f"{partition_name} scaled artifact does not "
            "contain 32 features."
        )


    sample_size = min(
        REPRODUCIBILITY_SAMPLE_SIZE,
        scaled_data.shape[0]
    )


    # Only a very small sample is copied into RAM.
    persisted_scaled_sample = np.asarray(
        scaled_data[
            :sample_size,
            :
        ],
        dtype=np.float64
    )


    # Reconstruct the corresponding pre-scaled feature
    # values using the recovered Training-fitted scaler.
    reconstructed_unscaled_sample = (
        persisted_scaler.inverse_transform(
            persisted_scaled_sample
        )
    )


    # Reapply the recovered scaler.
    reproduced_scaled_sample = (
        persisted_scaler.transform(
            reconstructed_unscaled_sample
        )
    )


    if not np.allclose(
        reproduced_scaled_sample,
        persisted_scaled_sample,
        atol=REPRODUCIBILITY_ATOL,
        rtol=REPRODUCIBILITY_RTOL
    ):

        max_difference = float(
            np.max(
                np.abs(
                    reproduced_scaled_sample
                    - persisted_scaled_sample
                )
            )
        )


        del persisted_scaled_sample
        del reconstructed_unscaled_sample
        del reproduced_scaled_sample
        del scaled_data


        raise ValueError(
            f"{partition_name} scaler reproducibility "
            "test failed. "
            f"Maximum absolute difference: "
            f"{max_difference:.3e}"
        )


    maximum_difference = float(
        np.max(
            np.abs(
                reproduced_scaled_sample
                - persisted_scaled_sample
            )
        )
    )


    print(
        f"✓ {partition_name:<10}: "
        f"{sample_size} rows reproduced | "
        f"max abs difference = "
        f"{maximum_difference:.3e}"
    )


    del persisted_scaled_sample
    del reconstructed_unscaled_sample
    del reproduced_scaled_sample
    del scaled_data


# ------------------------------------------------------------
# 10. Validate final scaling integrity boundary
# ------------------------------------------------------------

print("\n[SCALING INTEGRITY BOUNDARY]")

print(
    "✓ Scaler was recovered from persisted artifact"
)

print(
    "✓ Scaler was not refitted"
)

print(
    "✓ Validation data were not used for fitting"
)

print(
    "✓ Independent Test data were not used for fitting"
)

print(
    "✓ Same recovered scaler reproduces persisted "
    "Training representation"
)

print(
    "✓ Same recovered scaler reproduces persisted "
    "Validation representation"
)

print(
    "✓ Same recovered scaler reproduces persisted "
    "Test representation"
)

print(
    "✓ No Stage-1 dataset reloaded"
)

print(
    "✓ No complete feature matrix loaded into RAM"
)

print(
    "✓ No feature selection repeated"
)

print(
    "✓ No scaling refitting performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No partition modification performed"
)

print(
    "✓ No target modification performed"
)

print(
    "✓ No model fitting performed"
)


# ------------------------------------------------------------
# 11. Final completion
# ------------------------------------------------------------

print("\n[4.11.4 VALIDATION SUMMARY]")

print(
    "✓ Training-only StandardScaler recovered successfully"
)

print(
    "✓ Scaler parameters are finite and dimensionally valid"
)

print(
    "✓ Scaler observed the complete Training partition only"
)

print(
    "✓ Authoritative 32-feature ordering preserved"
)

print(
    "✓ Validation and Test remained excluded from scaler fitting"
)

print(
    "✓ Existing 4.7.6 reproducibility record validated"
)

print(
    "✓ Persisted scaled representations reproduce through "
    "the recovered scaler"
)

print(
    "✓ Scaling configuration is reproducible for "
    "downstream model development"
)


print("\n" + "=" * 72)

print(
    "4.11.4 scaler reproducibility validation "
    "completed successfully."
)

print("=" * 72)

========================================================================
4.11.4 — SCALER REPRODUCIBILITY VALIDATION
========================================================================

[RECOVERY STATE]
✓ Training-only scaler and scaling metadata recovered

[PERSISTED SCALING ARTIFACT CHECK]
✓ Training-only scaler: training_only_standard_scaler.joblib
✓ Training-only scaler metadata: training_only_scaler_metadata.json
✓ Partition-wise transformation metadata: partition_wise_transformation_metadata.json
✓ Model-ready feature metadata: model_ready_feature_artifacts.json
✓ Final scaling reproducibility record: final_scaling_reproducibility_validation.json
✓ Training scaled data: X_train_scaled.npy
✓ Validation scaled data: X_validation_scaled.npy
✓ Test scaled data: X_test_scaled.npy

[TRAINING-ONLY SCALER RECOVERY]
✓ StandardScaler reloaded successfully
✓ Scaler contains exactly 32 feature parameters
✓ Scaler Training observations seen: 1,814,018
✓ Scaler mean, variance, and scale parameters are finite
✓ All scaler scale parameters are positive

[SCALING METADATA RECOVERY]
✓ Training-only scaler metadata loaded
✓ Partition-wise transformation metadata loaded
✓ Model-ready feature metadata loaded
✓ Existing 4.7.6 reproducibility record loaded

[SCALER METADATA CONSISTENCY]
✓ Scaler type matches persisted StandardScaler
✓ Fitting partition recorded as Training only
✓ Validation excluded from scaler fitting
✓ Independent Test excluded from scaler fitting
✓ Training/Validation/Test row counts match
✓ Metadata feature count matches recovered scaler
✓ Metadata sample count matches recovered scaler

[SCALER FEATURE-ORDER VALIDATION]
✓ Scaler metadata feature order matches the authoritative 32-feature order
✓ Transformation metadata feature order matches the authoritative 32-feature order
✓ Model-ready metadata confirms 32 final features

[PARTITION-WISE SCALER USAGE]
✓ Training  : 1,814,018 rows | scaler fitting = True
✓ Validation: 451,215 rows | scaler fitting = False
✓ Test      : 565,510 rows | scaler fitting = False

[EXISTING 4.7.6 REPRODUCIBILITY RECORD]
✓ Existing 4.7.6 record is marked completed
✓ Existing record confirms Training-only fitting
✓ Existing record confirms scaler reload
✓ Existing record confirms partition validation
✓ Existing record confirms metadata validation
✓ Existing record confirms final feature configuration

[TRANSFORMATION REPRODUCIBILITY TEST]
✓ Training  : 128 rows reproduced | max abs difference = 8.882e-16
✓ Validation: 128 rows reproduced | max abs difference = 1.776e-15
✓ Test      : 128 rows reproduced | max abs difference = 8.882e-16

[SCALING INTEGRITY BOUNDARY]
✓ Scaler was recovered from persisted artifact
✓ Scaler was not refitted
✓ Validation data were not used for fitting
✓ Independent Test data were not used for fitting
✓ Same recovered scaler reproduces persisted Training representation
✓ Same recovered scaler reproduces persisted Validation representation
✓ Same recovered scaler reproduces persisted Test representation
✓ No Stage-1 dataset reloaded
✓ No complete feature matrix loaded into RAM
✓ No feature selection repeated
✓ No scaling refitting performed
✓ No resampling performed
✓ No partition modification performed
✓ No target modification performed
✓ No model fitting performed

[4.11.4 VALIDATION SUMMARY]
✓ Training-only StandardScaler recovered successfully
✓ Scaler parameters are finite and dimensionally valid
✓ Scaler observed the complete Training partition only
✓ Authoritative 32-feature ordering preserved
✓ Validation and Test remained excluded from scaler fitting
✓ Existing 4.7.6 reproducibility record validated
✓ Persisted scaled representations reproduce through the recovered scaler
✓ Scaling configuration is reproducible for downstream model development

========================================================================
4.11.4 scaler reproducibility validation completed successfully.
========================================================================

## 4.11.5 — Experiment Configuration Recovery

This subsection recovers and validates the persisted downstream imbalance
experiment configurations established in Section 4.9.

The recovery covers the persisted experiment matrix, Random Forest
configuration, LSTM configuration, and experiment-design metadata. The
configuration records are checked against the established five-strategy
Random Forest design, five-strategy LSTM design, nine-class taxonomy,
training-only modification boundary, validation-based strategy comparison,
and independent Test evaluation boundary.

The exact candidate strategy identifiers, mechanisms, sampling units,
synthetic-data constraints, and partition-protection conditions are verified
against the authoritative Section 4.9 experiment design.

The persisted SHA-256 manifest is also checked to confirm that the downstream
experiment-design artifacts belong to the finalized N04 artifact package.

No model is trained, no resampling or synthetic data is generated, no class
weighting is applied, no strategy is selected as optimal, and no Training,
Validation, or Test partition is modified.

No large feature arrays or the Stage-1 dataset are loaded. Only the small
experiment configuration and metadata artifacts are recovered.

Successful completion establishes that the finalized Random Forest and LSTM
experiment configurations are recoverable and internally consistent for
downstream model-training stages.

In [63]:
# ============================================================
# 4.11.5 — EXPERIMENT CONFIGURATION RECOVERY
# ============================================================

import csv
import json
from pathlib import Path

print("=" * 72)
print("4.11.5 — EXPERIMENT CONFIGURATION RECOVERY")
print("=" * 72)


# ------------------------------------------------------------
# 1. Validate required cold-start recovery state
# ------------------------------------------------------------

required_recovery_objects = [
    "final_artifact_manifest",
    "final_model_preparation_metadata",
    "imbalance_experiment_design_metadata",
    "rf_imbalance_experiment_configuration",
    "lstm_imbalance_experiment_configuration",
]

missing_recovery_objects = [
    object_name
    for object_name in required_recovery_objects
    if object_name not in recovered_artifacts
]

if missing_recovery_objects:

    raise ValueError(
        "Required 4.11.1 recovery objects are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_recovery_objects
        )
    )


print("\n[RECOVERY STATE]")

print(
    "✓ Final artifact manifest recovered"
)

print(
    "✓ Final model-preparation metadata recovered"
)

print(
    "✓ RF experiment configuration recovered"
)

print(
    "✓ LSTM experiment configuration recovered"
)

print(
    "✓ Experiment-design metadata recovered"
)


# ------------------------------------------------------------
# 2. Establish persisted experiment artifact paths
# ------------------------------------------------------------

RECOVERY_DOWNSTREAM_IMBALANCE_DIR = (
    RECOVERY_MODEL_PREPARATION_V2_DIR /
    "downstream_imbalance_experiments"
)


RECOVERY_EXPERIMENT_MATRIX_PATH = (
    RECOVERY_DOWNSTREAM_IMBALANCE_DIR /
    "imbalance_experiment_matrix.csv"
)

RECOVERY_RF_CONFIG_PATH = (
    RECOVERY_DOWNSTREAM_IMBALANCE_DIR /
    "rf_imbalance_experiment_config.json"
)

RECOVERY_LSTM_CONFIG_PATH = (
    RECOVERY_DOWNSTREAM_IMBALANCE_DIR /
    "lstm_imbalance_experiment_config.json"
)

RECOVERY_DESIGN_METADATA_PATH = (
    RECOVERY_DOWNSTREAM_IMBALANCE_DIR /
    "imbalance_experiment_design_metadata.json"
)


required_experiment_paths = {

    "Experiment matrix":
        RECOVERY_EXPERIMENT_MATRIX_PATH,

    "RF configuration":
        RECOVERY_RF_CONFIG_PATH,

    "LSTM configuration":
        RECOVERY_LSTM_CONFIG_PATH,

    "Experiment-design metadata":
        RECOVERY_DESIGN_METADATA_PATH,
}


print("\n[PERSISTED EXPERIMENT ARTIFACT CHECK]")

missing_experiment_paths = []

for artifact_name, artifact_path in (
    required_experiment_paths.items()
):

    if not artifact_path.is_file():

        missing_experiment_paths.append(
            f"{artifact_name}: {artifact_path}"
        )

    else:

        print(
            f"✓ {artifact_name}: "
            f"{artifact_path.name}"
        )


if missing_experiment_paths:

    raise FileNotFoundError(
        "Required downstream experiment artifacts are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_experiment_paths
        )
    )


# ------------------------------------------------------------
# 3. Recover persisted JSON configuration objects
# ------------------------------------------------------------

with open(
    RECOVERY_RF_CONFIG_PATH,
    "r",
    encoding="utf-8"
) as file:

    rf_configuration = json.load(
        file
    )


with open(
    RECOVERY_LSTM_CONFIG_PATH,
    "r",
    encoding="utf-8"
) as file:

    lstm_configuration = json.load(
        file
    )


with open(
    RECOVERY_DESIGN_METADATA_PATH,
    "r",
    encoding="utf-8"
) as file:

    design_metadata = json.load(
        file
    )


print("\n[CONFIGURATION RELOAD]")

print(
    "✓ Random Forest configuration loaded successfully"
)

print(
    "✓ LSTM configuration loaded successfully"
)

print(
    "✓ Experiment-design metadata loaded successfully"
)


# ------------------------------------------------------------
# 4. Validate final taxonomy boundary
# ------------------------------------------------------------

print("\n[TAXONOMY BOUNDARY]")

EXPECTED_FINAL_CLASS_COUNT = 9


if int(
    design_metadata.get(
        "final_taxonomy_classes",
        -1
    )
) != EXPECTED_FINAL_CLASS_COUNT:

    raise ValueError(
        "Experiment-design metadata does not confirm "
        "the established nine-class taxonomy."
    )


if int(
    rf_configuration.get(
        "candidate_count",
        -1
    )
) != 5:

    raise ValueError(
        "Random Forest configuration does not contain "
        "exactly five candidate strategies."
    )


if int(
    lstm_configuration.get(
        "candidate_count",
        -1
    )
) != 5:

    raise ValueError(
        "LSTM configuration does not contain "
        "exactly five candidate strategies."
    )


print(
    "✓ Final nine-class taxonomy retained"
)

print(
    "✓ Five RF candidates configured"
)

print(
    "✓ Five LSTM candidates configured"
)


# ------------------------------------------------------------
# 5. Define authoritative Section 4.9 RF strategies
# ------------------------------------------------------------

EXPECTED_RF_STRATEGIES = {

    "RF-0": {
        "strategy_name":
            "Natural Distribution Baseline",

        "mechanism":
            "none",

        "training_data_modification":
            "none",

        "sampling_unit":
            "individual feature vector",

        "synthetic_data":
            False,
    },

    "RF-1": {
        "strategy_name":
            "Balanced Class Weighting",

        "mechanism":
            "class_weight_balanced",

        "training_data_modification":
            "none",

        "sampling_unit":
            "individual feature vector",

        "synthetic_data":
            False,
    },

    "RF-2": {
        "strategy_name":
            "Balanced-Subsample Class Weighting",

        "mechanism":
            "class_weight_balanced_subsample",

        "training_data_modification":
            "none",

        "sampling_unit":
            "individual feature vector",

        "synthetic_data":
            False,
    },

    "RF-3": {
        "strategy_name":
            "Controlled Random Oversampling",

        "mechanism":
            "random_oversampling",

        "training_data_modification":
            "controlled_oversampling",

        "sampling_unit":
            "individual feature vector",

        "synthetic_data":
            False,
    },

    "RF-4": {
        "strategy_name":
            "Controlled SMOTE",

        "mechanism":
            "SMOTE",

        "training_data_modification":
            "controlled_synthetic_sampling",

        "sampling_unit":
            "individual feature vector",

        "synthetic_data":
            True,
    },
}


# ------------------------------------------------------------
# 6. Define authoritative Section 4.9 LSTM strategies
# ------------------------------------------------------------

EXPECTED_LSTM_STRATEGIES = {

    "LSTM-0": {
        "strategy_name":
            "Natural Sequence Distribution Baseline",

        "mechanism":
            "none",

        "training_data_modification":
            "none",

        "sampling_unit":
            "complete sequence",

        "synthetic_data":
            False,
    },

    "LSTM-1": {
        "strategy_name":
            "Class-Weighted Loss",

        "mechanism":
            "class_weighted_loss",

        "training_data_modification":
            "none",

        "sampling_unit":
            "complete sequence",

        "synthetic_data":
            False,
    },

    "LSTM-2": {
        "strategy_name":
            "Class-Aware Sequence Sampling",

        "mechanism":
            "class_aware_sequence_sampling",

        "training_data_modification":
            "controlled_sequence_sampling",

        "sampling_unit":
            "complete sequence",

        "synthetic_data":
            False,
    },

    "LSTM-3": {
        "strategy_name":
            "Controlled Sequence Oversampling",

        "mechanism":
            "sequence_level_oversampling",

        "training_data_modification":
            "controlled_sequence_oversampling",

        "sampling_unit":
            "complete sequence",

        "synthetic_data":
            False,
    },

    "LSTM-4": {
        "strategy_name":
            "Sequence-Preserving Synthetic Sampling",

        "mechanism":
            "sequence_preserving_synthetic_sampling",

        "training_data_modification":
            "controlled_synthetic_sequence_sampling",

        "sampling_unit":
            "complete sequence",

        "synthetic_data":
            True,
    },
}


# ------------------------------------------------------------
# 7. Validate RF configuration
# ------------------------------------------------------------

print("\n[RANDOM FOREST CONFIGURATION]")

if rf_configuration.get(
    "model_family"
) != "Random Forest":

    raise ValueError(
        "Persisted RF configuration has an unexpected "
        "model_family."
    )


rf_strategies = (
    rf_configuration.get(
        "strategies",
        []
    )
)


if len(
    rf_strategies
) != 5:

    raise ValueError(
        "Persisted RF configuration does not contain "
        "exactly five strategies."
    )


rf_strategy_ids = {
    strategy.get(
        "strategy_id"
    )
    for strategy in rf_strategies
}


if rf_strategy_ids != set(
    EXPECTED_RF_STRATEGIES.keys()
):

    raise ValueError(
        "Persisted RF strategy IDs do not match "
        "the established Section 4.9 design.\n"
        f"Expected: "
        f"{sorted(EXPECTED_RF_STRATEGIES.keys())}\n"
        f"Observed: "
        f"{sorted(rf_strategy_ids)}"
    )


for strategy in rf_strategies:

    strategy_id = strategy[
        "strategy_id"
    ]

    expected = EXPECTED_RF_STRATEGIES[
        strategy_id
    ]


    for field_name, expected_value in (
        expected.items()
    ):

        actual_value = strategy.get(
            field_name
        )

        if actual_value != expected_value:

            raise ValueError(
                f"RF strategy {strategy_id} field "
                f"'{field_name}' mismatch: "
                f"expected {expected_value!r}, "
                f"found {actual_value!r}"
            )


    print(
        f"✓ {strategy_id}: "
        f"{strategy['strategy_name']}"
    )


print(
    "✓ All five Random Forest strategies match "
    "the persisted Section 4.9 design"
)


# ------------------------------------------------------------
# 8. Validate LSTM configuration
# ------------------------------------------------------------

print("\n[LSTM CONFIGURATION]")

if lstm_configuration.get(
    "model_family"
) != "LSTM":

    raise ValueError(
        "Persisted LSTM configuration has an unexpected "
        "model_family."
    )


lstm_strategies = (
    lstm_configuration.get(
        "strategies",
        []
    )
)


if len(
    lstm_strategies
) != 5:

    raise ValueError(
        "Persisted LSTM configuration does not contain "
        "exactly five strategies."
    )


lstm_strategy_ids = {
    strategy.get(
        "strategy_id"
    )
    for strategy in lstm_strategies
}


if lstm_strategy_ids != set(
    EXPECTED_LSTM_STRATEGIES.keys()
):

    raise ValueError(
        "Persisted LSTM strategy IDs do not match "
        "the established Section 4.9 design.\n"
        f"Expected: "
        f"{sorted(EXPECTED_LSTM_STRATEGIES.keys())}\n"
        f"Observed: "
        f"{sorted(lstm_strategy_ids)}"
    )


for strategy in lstm_strategies:

    strategy_id = strategy[
        "strategy_id"
    ]

    expected = EXPECTED_LSTM_STRATEGIES[
        strategy_id
    ]


    for field_name, expected_value in (
        expected.items()
    ):

        actual_value = strategy.get(
            field_name
        )

        if actual_value != expected_value:

            raise ValueError(
                f"LSTM strategy {strategy_id} field "
                f"'{field_name}' mismatch: "
                f"expected {expected_value!r}, "
                f"found {actual_value!r}"
            )


    print(
        f"✓ {strategy_id}: "
        f"{strategy['strategy_name']}"
    )


print(
    "✓ All five LSTM strategies match "
    "the persisted Section 4.9 design"
)


# ------------------------------------------------------------
# 9. Validate RF sampling constraints
# ------------------------------------------------------------

print("\n[RF SAMPLING CONSTRAINTS]")

rf_constraints = rf_configuration.get(
    "sampling_constraints",
    {}
)


expected_rf_constraints = {

    "minimum_training_support_for_synthetic_sampling":
        10,

    "controlled_oversampling_multiplier":
        5,

    "maximum_target_observations_per_class":
        50_000,

    "majority_class_downsampling":
        False,

    "validation_sampling":
        False,

    "test_sampling":
        False,
}


for field_name, expected_value in (
    expected_rf_constraints.items()
):

    actual_value = rf_constraints.get(
        field_name
    )

    if actual_value != expected_value:

        raise ValueError(
            f"RF sampling constraint "
            f"'{field_name}' mismatch: "
            f"expected {expected_value!r}, "
            f"found {actual_value!r}"
        )


print(
    "✓ RF minimum synthetic-sampling support: 10"
)

print(
    "✓ RF controlled oversampling multiplier: 5x"
)

print(
    "✓ RF maximum target observations/class: 50,000"
)

print(
    "✓ RF majority-class downsampling prohibited"
)

print(
    "✓ RF Validation sampling prohibited"
)

print(
    "✓ RF Test sampling prohibited"
)


# ------------------------------------------------------------
# 10. Validate LSTM sampling constraints
# ------------------------------------------------------------

print("\n[LSTM SAMPLING CONSTRAINTS]")

lstm_constraints = lstm_configuration.get(
    "sampling_constraints",
    {}
)


expected_lstm_constraints = {

    "minimum_training_support_for_synthetic_sampling":
        10,

    "controlled_sequence_oversampling_multiplier":
        5,

    "maximum_target_sequences_per_class":
        50_000,

    "row_level_SMOTE":
        False,

    "validation_sampling":
        False,

    "test_sampling":
        False,

    "low_support_classes_excluded_from_synthetic_generation":
        True,

    "sequence_structure_preserved":
        True,
}


for field_name, expected_value in (
    expected_lstm_constraints.items()
):

    actual_value = lstm_constraints.get(
        field_name
    )

    if actual_value != expected_value:

        raise ValueError(
            f"LSTM sampling constraint "
            f"'{field_name}' mismatch: "
            f"expected {expected_value!r}, "
            f"found {actual_value!r}"
        )


print(
    "✓ LSTM minimum synthetic-sampling support: 10"
)

print(
    "✓ LSTM controlled sequence oversampling multiplier: 5x"
)

print(
    "✓ LSTM maximum target sequences/class: 50,000"
)

print(
    "✓ Row-level SMOTE prohibited for LSTM"
)

print(
    "✓ LSTM Validation sampling prohibited"
)

print(
    "✓ LSTM Test sampling prohibited"
)

print(
    "✓ Low-support classes excluded from synthetic generation"
)

print(
    "✓ Sequence structure preservation required"
)


# ------------------------------------------------------------
# 11. Validate common experimental boundary
# ------------------------------------------------------------

print("\n[COMMON EXPERIMENTAL BOUNDARY]")

rf_boundary = rf_configuration.get(
    "common_boundary",
    {}
)

lstm_boundary = lstm_configuration.get(
    "common_boundary",
    {}
)


expected_common_boundary = {

    "training_partition_modifiable":
        True,

    "validation_partition_untouched":
        True,

    "independent_test_partition_untouched":
        True,

    "strategy_selection_partition":
        "validation",

    "final_evaluation_partition":
        "independent_test",

    "primary_metric":
        "macro_f1",

    "optimal_strategy_declared":
        False,

    "model_fitting_performed":
        False,

    "synthetic_data_generated":
        False,
}


for model_name, boundary in (
    ("Random Forest", rf_boundary),
    ("LSTM", lstm_boundary)
):

    for field_name, expected_value in (
        expected_common_boundary.items()
    ):

        actual_value = boundary.get(
            field_name
        )

        if actual_value != expected_value:

            raise ValueError(
                f"{model_name} common-boundary field "
                f"'{field_name}' mismatch: "
                f"expected {expected_value!r}, "
                f"found {actual_value!r}"
            )


    print(
        f"✓ {model_name} boundary matches "
        "the established experiment protocol"
    )


# ------------------------------------------------------------
# 12. Validate experiment-design metadata
# ------------------------------------------------------------

print("\n[EXPERIMENT-DESIGN METADATA]")

expected_design_metadata = {

    "section":
        "4.9",

    "section_title":
        "Downstream Imbalance Experiment Design",

    "candidate_random_forest_strategies":
        5,

    "candidate_lstm_strategies":
        5,

    "total_candidate_experiments":
        10,

    "final_taxonomy_classes":
        9,

    "strategy_selection_partition":
        "validation",

    "final_evaluation_partition":
        "independent_test",

    "primary_metric":
        "macro_f1",

    "test_set_used_for_strategy_selection":
        False,

    "validation_distribution_modified":
        False,

    "test_distribution_modified":
        False,

    "training_data_only_modification":
        True,

    "synthetic_data_generated":
        False,

    "model_fitting_performed":
        False,

    "optimal_strategy_selected":
        False,
}


for field_name, expected_value in (
    expected_design_metadata.items()
):

    actual_value = design_metadata.get(
        field_name
    )

    if actual_value != expected_value:

        raise ValueError(
            f"Experiment-design metadata field "
            f"'{field_name}' mismatch: "
            f"expected {expected_value!r}, "
            f"found {actual_value!r}"
        )


print(
    "✓ Five RF candidates recorded"
)

print(
    "✓ Five LSTM candidates recorded"
)

print(
    "✓ Ten total candidate experiments recorded"
)

print(
    "✓ Validation retained as strategy-selection partition"
)

print(
    "✓ Independent Test retained as final-evaluation partition"
)

print(
    "✓ Macro F1 retained as primary metric"
)

print(
    "✓ Test excluded from strategy selection"
)

print(
    "✓ Validation/Test distributions recorded as unmodified"
)

print(
    "✓ Training-only modification boundary retained"
)

print(
    "✓ No synthetic data generated"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No optimal strategy selected"
)


# ------------------------------------------------------------
# 13. Recover and validate experiment matrix
# ------------------------------------------------------------

print("\n[EXPERIMENT MATRIX RECOVERY]")

with open(
    RECOVERY_EXPERIMENT_MATRIX_PATH,
    "r",
    encoding="utf-8",
    newline=""
) as file:

    matrix_reader = csv.DictReader(
        file
    )

    matrix_rows = list(
        matrix_reader
    )


if len(
    matrix_rows
) != 10:

    raise ValueError(
        "Persisted experiment matrix does not contain "
        f"exactly 10 candidate rows: "
        f"found {len(matrix_rows)}"
    )


required_matrix_columns = [

    "ModelFamily",
    "StrategyID",
    "StrategyName",
    "Mechanism",
    "TrainingDataModification",
    "SamplingUnit",
    "SyntheticData",
    "ValidationUntouched",
    "TestUntouched",
    "PrimaryMetric",
]


missing_matrix_columns = [
    column
    for column in required_matrix_columns
    if column not in (
        matrix_rows[0].keys()
        if matrix_rows
        else []
    )
]


if missing_matrix_columns:

    raise ValueError(
        "Experiment matrix is missing required columns:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_matrix_columns
        )
    )


matrix_strategy_ids = {
    row["StrategyID"]
    for row in matrix_rows
}


expected_all_strategy_ids = (
    set(EXPECTED_RF_STRATEGIES.keys())
    |
    set(EXPECTED_LSTM_STRATEGIES.keys())
)


if matrix_strategy_ids != (
    expected_all_strategy_ids
):

    raise ValueError(
        "Experiment matrix strategy IDs do not match "
        "the established ten-candidate design."
    )


for row in matrix_rows:

    strategy_id = row[
        "StrategyID"
    ]


    if row[
        "ValidationUntouched"
    ].strip().lower() != "true":

        raise ValueError(
            f"{strategy_id} does not preserve "
            "Validation protection."
        )


    if row[
        "TestUntouched"
    ].strip().lower() != "true":

        raise ValueError(
            f"{strategy_id} does not preserve "
            "Test protection."
        )


    if row[
        "PrimaryMetric"
    ].strip().lower() != "macro_f1":

        raise ValueError(
            f"{strategy_id} does not use "
            "macro_f1 as the primary metric."
        )


print(
    "✓ Experiment matrix contains ten candidates"
)

print(
    "✓ Five RF and five LSTM strategy IDs recovered"
)

print(
    "✓ Validation protection recorded for all candidates"
)

print(
    "✓ Test protection recorded for all candidates"
)

print(
    "✓ Macro F1 recorded for all candidates"
)


# ------------------------------------------------------------
# 14. Cross-check matrix against model configurations
# ------------------------------------------------------------

print("\n[MATRIX ↔ CONFIGURATION CONSISTENCY]")

configuration_by_id = {}

for strategy in rf_strategies:

    configuration_by_id[
        strategy["strategy_id"]
    ] = strategy


for strategy in lstm_strategies:

    configuration_by_id[
        strategy["strategy_id"]
    ] = strategy


for row in matrix_rows:

    strategy_id = row[
        "StrategyID"
    ]

    configuration = configuration_by_id[
        strategy_id
    ]


    if row[
        "StrategyName"
    ] != configuration[
        "strategy_name"
    ]:

        raise ValueError(
            f"{strategy_id} strategy name differs "
            "between matrix and configuration."
        )


    if row[
        "Mechanism"
    ] != configuration[
        "mechanism"
    ]:

        raise ValueError(
            f"{strategy_id} mechanism differs "
            "between matrix and configuration."
        )


    if row[
        "TrainingDataModification"
    ] != configuration[
        "training_data_modification"
    ]:

        raise ValueError(
            f"{strategy_id} training-data modification "
            "differs between matrix and configuration."
        )


    if row[
        "SamplingUnit"
    ] != configuration[
        "sampling_unit"
    ]:

        raise ValueError(
            f"{strategy_id} sampling unit differs "
            "between matrix and configuration."
        )


    expected_synthetic_value = (
        str(
            configuration[
                "synthetic_data"
            ]
        )
        .lower()
    )


    if row[
        "SyntheticData"
    ].strip().lower() != (
        expected_synthetic_value
    ):

        raise ValueError(
            f"{strategy_id} synthetic-data flag differs "
            "between matrix and configuration."
        )


print(
    "✓ Experiment matrix and RF/LSTM configurations "
    "are internally consistent"
)


# ------------------------------------------------------------
# 15. Validate final SHA-256 manifest membership
# ------------------------------------------------------------

print("\n[FINAL MANIFEST EXPERIMENT-ARTIFACT CHECK]")

manifest = recovered_artifacts[
    "final_artifact_manifest"
]


if manifest.get(
    "integrity_algorithm"
) != "SHA-256":

    raise ValueError(
        "Final artifact manifest does not specify "
        "SHA-256 integrity."
    )


manifest_entries = manifest.get(
    "artifacts",
    []
)


if len(
    manifest_entries
) != 36:

    raise ValueError(
        "Final artifact manifest does not contain "
        f"the expected 36 artifacts: "
        f"found {len(manifest_entries)}"
    )


manifest_relative_paths = {
    entry.get(
        "relative_path"
    )
    for entry in manifest_entries
}


expected_manifest_experiment_paths = {

    "downstream_imbalance_experiments/"
    "imbalance_experiment_matrix.csv",

    "downstream_imbalance_experiments/"
    "rf_imbalance_experiment_config.json",

    "downstream_imbalance_experiments/"
    "lstm_imbalance_experiment_config.json",

    "downstream_imbalance_experiments/"
    "imbalance_experiment_design_metadata.json",
}


missing_manifest_paths = (
    expected_manifest_experiment_paths
    - manifest_relative_paths
)


if missing_manifest_paths:

    raise ValueError(
        "One or more downstream experiment artifacts "
        "are absent from the final SHA-256 manifest:\n"
        + "\n".join(
            f"  - {item}"
            for item in sorted(
                missing_manifest_paths
            )
        )
    )


print(
    "✓ Final 36-artifact SHA-256 manifest recovered"
)

print(
    "✓ Experiment matrix is included in manifest"
)

print(
    "✓ RF configuration is included in manifest"
)

print(
    "✓ LSTM configuration is included in manifest"
)

print(
    "✓ Experiment-design metadata is included in manifest"
)


# ------------------------------------------------------------
# 16. Final recovery boundary
# ------------------------------------------------------------

print("\n[EXPERIMENT RECOVERY BOUNDARY]")

print(
    "✓ Experiment configurations recovered from "
    "persisted artifacts"
)

print(
    "✓ No Stage-1 dataset reloaded"
)

print(
    "✓ No large feature arrays loaded"
)

print(
    "✓ No training data resampled"
)

print(
    "✓ No synthetic data generated"
)

print(
    "✓ No class weighting applied"
)

print(
    "✓ No Validation modification performed"
)

print(
    "✓ No independent Test modification performed"
)

print(
    "✓ No partition indices modified"
)

print(
    "✓ No strategy selected as optimal"
)

print(
    "✓ No model fitting performed"
)


# ------------------------------------------------------------
# 17. Final completion
# ------------------------------------------------------------

print("\n[4.11.5 VALIDATION SUMMARY]")

print(
    "✓ Five Random Forest strategies recovered"
)

print(
    "✓ Five LSTM strategies recovered"
)

print(
    "✓ Ten total candidate experiments verified"
)

print(
    "✓ RF and LSTM configurations match Section 4.9"
)

print(
    "✓ Sampling and synthetic-data boundaries verified"
)

print(
    "✓ Validation remains the strategy-selection partition"
)

print(
    "✓ Independent Test remains the final-evaluation partition"
)

print(
    "✓ Macro F1 remains the primary comparison metric"
)

print(
    "✓ No strategy has been selected prematurely"
)

print(
    "✓ Downstream experiment artifacts are protected by "
    "the final SHA-256 manifest"
)

print(
    "✓ Experiment configuration is recoverable for "
    "downstream model training"
)


print("\n" + "=" * 72)

print(
    "4.11.5 experiment configuration recovery "
    "completed successfully."
)

print("=" * 72)

========================================================================
4.11.5 — EXPERIMENT CONFIGURATION RECOVERY
========================================================================

[RECOVERY STATE]
✓ Final artifact manifest recovered
✓ Final model-preparation metadata recovered
✓ RF experiment configuration recovered
✓ LSTM experiment configuration recovered
✓ Experiment-design metadata recovered

[PERSISTED EXPERIMENT ARTIFACT CHECK]
✓ Experiment matrix: imbalance_experiment_matrix.csv
✓ RF configuration: rf_imbalance_experiment_config.json
✓ LSTM configuration: lstm_imbalance_experiment_config.json
✓ Experiment-design metadata: imbalance_experiment_design_metadata.json

[CONFIGURATION RELOAD]
✓ Random Forest configuration loaded successfully
✓ LSTM configuration loaded successfully
✓ Experiment-design metadata loaded successfully

[TAXONOMY BOUNDARY]
✓ Final nine-class taxonomy retained
✓ Five RF candidates configured
✓ Five LSTM candidates configured

[RANDOM FOREST CONFIGURATION]
✓ RF-0: Natural Distribution Baseline
✓ RF-1: Balanced Class Weighting
✓ RF-2: Balanced-Subsample Class Weighting
✓ RF-3: Controlled Random Oversampling
✓ RF-4: Controlled SMOTE
✓ All five Random Forest strategies match the persisted Section 4.9 design

[LSTM CONFIGURATION]
✓ LSTM-0: Natural Sequence Distribution Baseline
✓ LSTM-1: Class-Weighted Loss
✓ LSTM-2: Class-Aware Sequence Sampling
✓ LSTM-3: Controlled Sequence Oversampling
✓ LSTM-4: Sequence-Preserving Synthetic Sampling
✓ All five LSTM strategies match the persisted Section 4.9 design

[RF SAMPLING CONSTRAINTS]
✓ RF minimum synthetic-sampling support: 10
✓ RF controlled oversampling multiplier: 5x
✓ RF maximum target observations/class: 50,000
✓ RF majority-class downsampling prohibited
✓ RF Validation sampling prohibited
✓ RF Test sampling prohibited

[LSTM SAMPLING CONSTRAINTS]
✓ LSTM minimum synthetic-sampling support: 10
✓ LSTM controlled sequence oversampling multiplier: 5x
✓ LSTM maximum target sequences/class: 50,000
✓ Row-level SMOTE prohibited for LSTM
✓ LSTM Validation sampling prohibited
✓ LSTM Test sampling prohibited
✓ Low-support classes excluded from synthetic generation
✓ Sequence structure preservation required

[COMMON EXPERIMENTAL BOUNDARY]
✓ Random Forest boundary matches the established experiment protocol
✓ LSTM boundary matches the established experiment protocol

[EXPERIMENT-DESIGN METADATA]
✓ Five RF candidates recorded
✓ Five LSTM candidates recorded
✓ Ten total candidate experiments recorded
✓ Validation retained as strategy-selection partition
✓ Independent Test retained as final-evaluation partition
✓ Macro F1 retained as primary metric
✓ Test excluded from strategy selection
✓ Validation/Test distributions recorded as unmodified
✓ Training-only modification boundary retained
✓ No synthetic data generated
✓ No model fitting performed
✓ No optimal strategy selected

[EXPERIMENT MATRIX RECOVERY]
✓ Experiment matrix contains ten candidates
✓ Five RF and five LSTM strategy IDs recovered
✓ Validation protection recorded for all candidates
✓ Test protection recorded for all candidates
✓ Macro F1 recorded for all candidates

[MATRIX ↔ CONFIGURATION CONSISTENCY]
✓ Experiment matrix and RF/LSTM configurations are internally consistent

[FINAL MANIFEST EXPERIMENT-ARTIFACT CHECK]
✓ Final 36-artifact SHA-256 manifest recovered
✓ Experiment matrix is included in manifest
✓ RF configuration is included in manifest
✓ LSTM configuration is included in manifest
✓ Experiment-design metadata is included in manifest

[EXPERIMENT RECOVERY BOUNDARY]
✓ Experiment configurations recovered from persisted artifacts
✓ No Stage-1 dataset reloaded
✓ No large feature arrays loaded
✓ No training data resampled
✓ No synthetic data generated
✓ No class weighting applied
✓ No Validation modification performed
✓ No independent Test modification performed
✓ No partition indices modified
✓ No strategy selected as optimal
✓ No model fitting performed

[4.11.5 VALIDATION SUMMARY]
✓ Five Random Forest strategies recovered
✓ Five LSTM strategies recovered
✓ Ten total candidate experiments verified
✓ RF and LSTM configurations match Section 4.9
✓ Sampling and synthetic-data boundaries verified
✓ Validation remains the strategy-selection partition
✓ Independent Test remains the final-evaluation partition
✓ Macro F1 remains the primary comparison metric
✓ No strategy has been selected prematurely
✓ Downstream experiment artifacts are protected by the final SHA-256 manifest
✓ Experiment configuration is recoverable for downstream model training

========================================================================
4.11.5 experiment configuration recovery completed successfully.
========================================================================

## 4.11.6 — Complete Model-Preparation Validation

This final subsection performs the complete integration validation of the
finalized Notebook 04 model-preparation state.

The validation independently recovers the consolidated N04 metadata and
final artifact manifest and verifies that the finalized taxonomy, 32-feature
model-ready representation, Training/Validation/Test partition structure,
model-ready target artifacts, feature artifacts, Training-only scaling
configuration, downstream imbalance experiment configuration, and artifact
integrity boundary are mutually consistent.

The persisted Training, Validation, and independent Test feature and target
artifacts are checked for their expected dimensions and partition sizes using
memory-conscious access. The final artifact inventory and 36-entry SHA-256
manifest are also checked for completeness and file presence.

The consolidated validation-status record is verified to confirm that the
taxonomy, feature configuration, partition configuration, independent Test
isolation, target artifacts, and downstream experiment configuration have all
been validated.

This final gate does not repeat preprocessing, feature selection, scaling,
resampling, synthetic-data generation, or model training. It does not reload
the Stage-1 dataset and does not modify any feature, target, or partition
artifact.

Successful completion establishes that the complete finalized N04
model-preparation package is internally consistent, persistent, recoverable,
and ready to serve as the input boundary for downstream Random Forest,
LSTM, ensemble, explainability, and inference development.

In [65]:
# ============================================================
# 4.11.6 — COMPLETE MODEL-PREPARATION VALIDATION
# ============================================================

import json
import numpy as np
from pathlib import Path

print("=" * 72)
print("4.11.6 — COMPLETE MODEL-PREPARATION VALIDATION")
print("=" * 72)


# ------------------------------------------------------------
# 1. Establish independent final recovery boundary
# ------------------------------------------------------------

FINAL_RECOVERY_PROJECT_ROOT = Path(
    "/content/drive/MyDrive/"
    "AI-Network-Intrusion-Detection-System"
)

FINAL_RECOVERY_OUTPUTS_DIR = (
    FINAL_RECOVERY_PROJECT_ROOT /
    "outputs"
)

FINAL_RECOVERY_MODEL_PREPARATION_DIR = (
    FINAL_RECOVERY_OUTPUTS_DIR /
    "model_preparation_v2"
)


if not FINAL_RECOVERY_PROJECT_ROOT.is_dir():

    raise FileNotFoundError(
        "Project root was not found:\n"
        f"{FINAL_RECOVERY_PROJECT_ROOT}"
    )


if not FINAL_RECOVERY_MODEL_PREPARATION_DIR.is_dir():

    raise FileNotFoundError(
        "N04 model-preparation directory was not found:\n"
        f"{FINAL_RECOVERY_MODEL_PREPARATION_DIR}"
    )


print("\n[FINAL RECOVERY BOUNDARY]")

print(
    "✓ N04 project root recovered independently"
)

print(
    "✓ N04 model-preparation directory recovered"
)


# ------------------------------------------------------------
# 2. Establish final control artifact paths
# ------------------------------------------------------------

FINAL_METADATA_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "final_model_preparation_metadata.json"
)

FINAL_INVENTORY_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "final_artifact_inventory.json"
)

FINAL_MANIFEST_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "final_artifact_manifest.json"
)

FINAL_TARGET_METADATA_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "model_ready_targets" /
    "target_artifact_metadata.json"
)

FINAL_TAXONOMY_METADATA_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "taxonomy" /
    "taxonomy_metadata.json"
)

FINAL_PARTITION_METADATA_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "partition_reproducibility_metadata.json"
)

FINAL_LEAKAGE_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "final_train_validation_test_leakage_validation.json"
)

FINAL_FEATURE_SELECTION_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "feature_selection" /
    "final_feature_set_validation.json"
)

FINAL_SELECTED_FEATURES_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "feature_selection" /
    "correlation_pruned_selected_features.json"
)

FINAL_SCALER_METADATA_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "feature_scaling" /
    "training_only_scaler_metadata.json"
)

FINAL_TRANSFORMATION_METADATA_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "feature_scaling" /
    "partition_wise_transformation_metadata.json"
)

FINAL_MODEL_READY_FEATURE_METADATA_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "feature_scaling" /
    "model_ready_feature_artifacts.json"
)

FINAL_SCALING_VALIDATION_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "feature_scaling" /
    "final_scaling_reproducibility_validation.json"
)

FINAL_CLASS_IMBALANCE_CONFIG_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "class_imbalance" /
    "class_imbalance_configuration.json"
)

FINAL_CLASS_IMBALANCE_SEVERITY_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "class_imbalance" /
    "class_imbalance_severity_metadata.json"
)

FINAL_EXPERIMENT_MATRIX_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "downstream_imbalance_experiments" /
    "imbalance_experiment_matrix.csv"
)

FINAL_RF_CONFIG_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "downstream_imbalance_experiments" /
    "rf_imbalance_experiment_config.json"
)

FINAL_LSTM_CONFIG_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "downstream_imbalance_experiments" /
    "lstm_imbalance_experiment_config.json"
)

FINAL_EXPERIMENT_DESIGN_PATH = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "downstream_imbalance_experiments" /
    "imbalance_experiment_design_metadata.json"
)


# ------------------------------------------------------------
# 3. Verify final control artifacts exist
# ------------------------------------------------------------

final_control_artifacts = {

    "Final model-preparation metadata":
        FINAL_METADATA_PATH,

    "Final artifact inventory":
        FINAL_INVENTORY_PATH,

    "Final artifact manifest":
        FINAL_MANIFEST_PATH,

    "Target metadata":
        FINAL_TARGET_METADATA_PATH,

    "Taxonomy metadata":
        FINAL_TAXONOMY_METADATA_PATH,

    "Partition metadata":
        FINAL_PARTITION_METADATA_PATH,

    "Final leakage validation":
        FINAL_LEAKAGE_PATH,

    "Feature-set validation":
        FINAL_FEATURE_SELECTION_PATH,

    "Selected-feature configuration":
        FINAL_SELECTED_FEATURES_PATH,

    "Training-only scaler metadata":
        FINAL_SCALER_METADATA_PATH,

    "Partition-wise transformation metadata":
        FINAL_TRANSFORMATION_METADATA_PATH,

    "Model-ready feature metadata":
        FINAL_MODEL_READY_FEATURE_METADATA_PATH,

    "Final scaling validation":
        FINAL_SCALING_VALIDATION_PATH,

    "Class-imbalance configuration":
        FINAL_CLASS_IMBALANCE_CONFIG_PATH,

    "Class-imbalance severity metadata":
        FINAL_CLASS_IMBALANCE_SEVERITY_PATH,

    "Experiment matrix":
        FINAL_EXPERIMENT_MATRIX_PATH,

    "RF experiment configuration":
        FINAL_RF_CONFIG_PATH,

    "LSTM experiment configuration":
        FINAL_LSTM_CONFIG_PATH,

    "Experiment-design metadata":
        FINAL_EXPERIMENT_DESIGN_PATH,
}


print("\n[FINAL CONTROL ARTIFACT CHECK]")

missing_control_artifacts = []

for artifact_name, artifact_path in (
    final_control_artifacts.items()
):

    if not artifact_path.is_file():

        missing_control_artifacts.append(
            f"{artifact_name}: {artifact_path}"
        )

    else:

        print(
            f"✓ {artifact_name}: "
            f"{artifact_path.name}"
        )


if missing_control_artifacts:

    raise FileNotFoundError(
        "Final N04 control artifacts are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_control_artifacts
        )
    )


print(
    f"✓ All {len(final_control_artifacts)} "
    "required final control artifacts are present"
)


# ------------------------------------------------------------
# 4. Load final consolidated metadata
# ------------------------------------------------------------

def load_final_json(
    artifact_name,
    artifact_path
):

    with open(
        artifact_path,
        "r",
        encoding="utf-8"
    ) as file:

        data = json.load(
            file
        )

    if not isinstance(
        data,
        dict
    ):

        raise ValueError(
            f"{artifact_name} does not contain "
            "a JSON object."
        )

    return data


final_metadata = load_final_json(
    "Final model-preparation metadata",
    FINAL_METADATA_PATH
)

final_inventory = load_final_json(
    "Final artifact inventory",
    FINAL_INVENTORY_PATH
)

final_manifest = load_final_json(
    "Final artifact manifest",
    FINAL_MANIFEST_PATH
)

target_metadata = load_final_json(
    "Target metadata",
    FINAL_TARGET_METADATA_PATH
)

taxonomy_metadata = load_final_json(
    "Taxonomy metadata",
    FINAL_TAXONOMY_METADATA_PATH
)

partition_metadata = load_final_json(
    "Partition metadata",
    FINAL_PARTITION_METADATA_PATH
)

leakage_metadata = load_final_json(
    "Final leakage validation",
    FINAL_LEAKAGE_PATH
)

scaler_metadata = load_final_json(
    "Training-only scaler metadata",
    FINAL_SCALER_METADATA_PATH
)

transformation_metadata = load_final_json(
    "Partition-wise transformation metadata",
    FINAL_TRANSFORMATION_METADATA_PATH
)

model_ready_feature_metadata = load_final_json(
    "Model-ready feature metadata",
    FINAL_MODEL_READY_FEATURE_METADATA_PATH
)

scaling_validation = load_final_json(
    "Final scaling validation",
    FINAL_SCALING_VALIDATION_PATH
)

rf_configuration = load_final_json(
    "RF experiment configuration",
    FINAL_RF_CONFIG_PATH
)

lstm_configuration = load_final_json(
    "LSTM experiment configuration",
    FINAL_LSTM_CONFIG_PATH
)

experiment_design = load_final_json(
    "Experiment-design metadata",
    FINAL_EXPERIMENT_DESIGN_PATH
)


print("\n[FINAL METADATA RELOAD]")

print(
    "✓ Consolidated model-preparation metadata loaded"
)

print(
    "✓ Final artifact inventory loaded"
)

print(
    "✓ Final artifact manifest loaded"
)

print(
    "✓ Target metadata loaded"
)

print(
    "✓ Taxonomy metadata loaded"
)

print(
    "✓ Partition and leakage metadata loaded"
)

print(
    "✓ Feature-scaling metadata loaded"
)

print(
    "✓ Downstream experiment configurations loaded"
)


# ------------------------------------------------------------
# 5. Validate final consolidated N04 status
# ------------------------------------------------------------

print("\n[FINAL CONSOLIDATED METADATA STATUS]")

if final_metadata.get(
    "notebook"
) != "N04":

    raise ValueError(
        "Final consolidated metadata does not identify N04."
    )


if final_metadata.get(
    "status"
) != "completed":

    raise ValueError(
        "Final consolidated N04 metadata is not "
        "marked as completed."
    )


required_validation_status = {

    "taxonomy_verified":
        True,

    "feature_configuration_verified":
        True,

    "partition_configuration_verified":
        True,

    "test_isolation_verified":
        True,

    "target_artifacts_verified":
        True,

    "downstream_experiment_configuration_verified":
        True,
}


validation_status = final_metadata.get(
    "validation_status",
    {}
)


for flag_name, expected_value in (
    required_validation_status.items()
):

    if validation_status.get(
        flag_name
    ) is not expected_value:

        raise ValueError(
            f"Final consolidated validation status "
            f"'{flag_name}' is not True."
        )

    print(
        f"✓ {flag_name}: True"
    )


print(
    "✓ Final consolidated N04 metadata is marked completed"
)


# ------------------------------------------------------------
# 6. Validate final taxonomy
# ------------------------------------------------------------

print("\n[COMPLETE TAXONOMY VALIDATION]")

final_taxonomy = final_metadata.get(
    "final_taxonomy",
    {}
)

if int(
    final_taxonomy.get(
        "class_count",
        -1
    )
) != 9:

    raise ValueError(
        "Final consolidated metadata does not confirm "
        "the nine-class taxonomy."
    )


final_class_mapping = final_taxonomy.get(
    "class_id_mapping",
    {}
)


if len(
    final_class_mapping
) != 9:

    raise ValueError(
        "Final consolidated taxonomy mapping does not "
        "contain exactly nine classes."
    )


final_class_ids = sorted(
    int(class_id)
    for class_id in final_class_mapping.values()
)


if final_class_ids != list(
    range(9)
):

    raise ValueError(
        "Final consolidated taxonomy does not contain "
        "class IDs 0–8."
    )


if int(
    taxonomy_metadata.get(
        "dataset",
        {}
    ).get(
        "final_class_count",
        -1
    )
) != 9:

    raise ValueError(
        "Persisted taxonomy metadata does not confirm "
        "nine final classes."
    )


print(
    "✓ Nine-class taxonomy confirmed"
)

print(
    "✓ Class IDs 0–8 confirmed"
)

print(
    "✓ Consolidated and persisted taxonomy agree"
)


# ------------------------------------------------------------
# 7. Validate final feature configuration
# ------------------------------------------------------------

print("\n[COMPLETE FEATURE CONFIGURATION VALIDATION]")

final_feature_configuration = final_metadata.get(
    "final_feature_configuration",
    {}
)


if int(
    final_feature_configuration.get(
        "feature_count",
        -1
    )
) != 32:

    raise ValueError(
        "Final consolidated metadata does not confirm "
        "32 model-ready features."
    )


required_feature_boundaries = {

    "feature_selection_training_only":
        True,

    "correlation_pruning_training_only":
        True,

    "scaling_training_only_fit":
        True,
}


for flag_name, expected_value in (
    required_feature_boundaries.items()
):

    if final_feature_configuration.get(
        flag_name
    ) is not expected_value:

        raise ValueError(
            f"Final feature boundary '{flag_name}' "
            "is not confirmed."
        )


if int(
    model_ready_feature_metadata.get(
        "final_feature_count",
        -1
    )
) != 32:

    raise ValueError(
        "Model-ready feature metadata does not confirm "
        "32 final features."
    )


if int(
    scaler_metadata.get(
        "feature_count",
        -1
    )
) != 32:

    raise ValueError(
        "Training-only scaler metadata does not confirm "
        "32 features."
    )


print(
    "✓ Final model-ready feature count: 32"
)

print(
    "✓ Training-only feature-selection boundary confirmed"
)

print(
    "✓ Training-only correlation-pruning boundary confirmed"
)

print(
    "✓ Training-only scaling boundary confirmed"
)


# ------------------------------------------------------------
# 8. Validate partition configuration
# ------------------------------------------------------------

print("\n[COMPLETE PARTITION VALIDATION]")

final_partition_configuration = final_metadata.get(
    "partition_configuration",
    {}
)


expected_partition_sizes = {

    "development_rows":
        2_265_233,

    "training_rows":
        1_814_018,

    "validation_rows":
        451_215,

    "test_rows":
        565_510,
}


for partition_name, expected_size in (
    expected_partition_sizes.items()
):

    final_size = int(
        final_partition_configuration.get(
            partition_name,
            -1
        )
    )

    if final_size != expected_size:

        raise ValueError(
            f"Final metadata partition mismatch for "
            f"{partition_name}: "
            f"expected {expected_size:,}, "
            f"found {final_size:,}"
        )


    print(
        f"✓ {partition_name}: "
        f"{final_size:,}"
    )


if final_partition_configuration.get(
    "independent_test_isolated"
) is not True:

    raise ValueError(
        "Final metadata does not confirm independent "
        "Test isolation."
    )


if final_partition_configuration.get(
    "partition_indices_modified_in_4_10"
) is not False:

    raise ValueError(
        "Final metadata records partition modification."
    )


if leakage_metadata.get(
    "validation_status"
) != "PASSED":

    raise ValueError(
        "Persisted leakage validation is not PASSED."
    )


print(
    "✓ Independent Test isolation confirmed"
)

print(
    "✓ No partition modification recorded"
)

print(
    "✓ Final leakage validation status: PASSED"
)


# ------------------------------------------------------------
# 9. Validate actual persisted feature artifacts
# ------------------------------------------------------------

print("\n[ACTUAL MODEL-READY FEATURE ARTIFACT VALIDATION]")

FEATURE_SCALING_FINAL_DIR = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "feature_scaling"
)


FINAL_FEATURE_PATHS = {

    "Training":
        FEATURE_SCALING_FINAL_DIR /
        "X_train_scaled.npy",

    "Validation":
        FEATURE_SCALING_FINAL_DIR /
        "X_validation_scaled.npy",

    "Test":
        FEATURE_SCALING_FINAL_DIR /
        "X_test_scaled.npy",
}


for partition_name, feature_path in (
    FINAL_FEATURE_PATHS.items()
):

    if not feature_path.is_file():

        raise FileNotFoundError(
            f"Persisted {partition_name} feature artifact "
            f"is missing: {feature_path}"
        )


    # Memory-map only; do not load the complete matrix.
    feature_array = np.load(
        feature_path,
        mmap_mode="r"
    )


    expected_shape = {

        "Training":
            (1_814_018, 32),

        "Validation":
            (451_215, 32),

        "Test":
            (565_510, 32),
    }[
        partition_name
    ]


    if tuple(
        feature_array.shape
    ) != expected_shape:

        actual_shape = tuple(
            feature_array.shape
        )

        del feature_array

        raise ValueError(
            f"{partition_name} feature artifact shape "
            f"mismatch: expected {expected_shape}, "
            f"found {actual_shape}"
        )


    print(
        f"✓ {partition_name:<10}: "
        f"{tuple(feature_array.shape)}"
    )


    del feature_array


print(
    "✓ All persisted model-ready feature artifacts "
    "match the final 32-feature configuration"
)


# ------------------------------------------------------------
# 10. Validate actual persisted target artifacts
# ------------------------------------------------------------

print("\n[ACTUAL MODEL-READY TARGET ARTIFACT VALIDATION]")

TARGET_FINAL_DIR = (
    FINAL_RECOVERY_MODEL_PREPARATION_DIR /
    "model_ready_targets"
)


FINAL_TARGET_PATHS = {

    "Training":
        TARGET_FINAL_DIR /
        "y_train.npy",

    "Validation":
        TARGET_FINAL_DIR /
        "y_validation.npy",

    "Test":
        TARGET_FINAL_DIR /
        "y_test.npy",
}


for partition_name, target_path in (
    FINAL_TARGET_PATHS.items()
):

    if not target_path.is_file():

        raise FileNotFoundError(
            f"Persisted {partition_name} target artifact "
            f"is missing: {target_path}"
        )


    target_array = np.load(
        target_path,
        mmap_mode="r"
    )


    expected_size = {

        "Training":
            1_814_018,

        "Validation":
            451_215,

        "Test":
            565_510,
    }[
        partition_name
    ]


    if target_array.ndim != 1:

        actual_shape = target_array.shape

        del target_array

        raise ValueError(
            f"{partition_name} target artifact must be "
            f"one-dimensional; found {actual_shape}"
        )


    if target_array.shape[0] != expected_size:

        actual_size = int(
            target_array.shape[0]
        )

        del target_array

        raise ValueError(
            f"{partition_name} target size mismatch: "
            f"expected {expected_size:,}, "
            f"found {actual_size:,}"
        )


    if not np.issubdtype(
        target_array.dtype,
        np.integer
    ):

        actual_dtype = target_array.dtype

        del target_array

        raise ValueError(
            f"{partition_name} target artifact is not "
            f"integer-valued: {actual_dtype}"
        )


    observed_classes = sorted(
        int(class_id)
        for class_id in np.unique(
            target_array
        )
    )


    if observed_classes != list(
        range(9)
    ):

        del target_array

        raise ValueError(
            f"{partition_name} target artifact contains "
            f"unexpected class IDs: {observed_classes}"
        )


    print(
        f"✓ {partition_name:<10}: "
        f"{expected_size:,} labels | "
        f"classes 0–8"
    )


    del target_array


print(
    "✓ All persisted model-ready target artifacts "
    "match the final nine-class configuration"
)


# ------------------------------------------------------------
# 11. Validate downstream experiment configuration
# ------------------------------------------------------------

print("\n[COMPLETE DOWNSTREAM EXPERIMENT VALIDATION]")

final_experiment_configuration = final_metadata.get(
    "downstream_experiment_configuration",
    {}
)


if int(
    final_experiment_configuration.get(
        "random_forest_candidate_count",
        -1
    )
) != 5:

    raise ValueError(
        "Final metadata does not confirm five RF candidates."
    )


if int(
    final_experiment_configuration.get(
        "lstm_candidate_count",
        -1
    )
) != 5:

    raise ValueError(
        "Final metadata does not confirm five LSTM candidates."
    )


if int(
    final_experiment_configuration.get(
        "total_candidate_count",
        -1
    )
) != 10:

    raise ValueError(
        "Final metadata does not confirm ten total candidates."
    )


if final_experiment_configuration.get(
    "strategy_selection_partition"
) != "Validation":

    raise ValueError(
        "Strategy-selection boundary is not Validation."
    )


if final_experiment_configuration.get(
    "final_evaluation_partition"
) != "Independent Test":

    raise ValueError(
        "Final evaluation boundary is not Independent Test."
    )


if final_experiment_configuration.get(
    "optimal_strategy_declared"
) is not False:

    raise ValueError(
        "An optimal strategy was prematurely declared."
    )


if int(
    rf_configuration.get(
        "candidate_count",
        -1
    )
) != 5:

    raise ValueError(
        "Persisted RF configuration does not contain "
        "five candidates."
    )


if int(
    lstm_configuration.get(
        "candidate_count",
        -1
    )
) != 5:

    raise ValueError(
        "Persisted LSTM configuration does not contain "
        "five candidates."
    )


if int(
    experiment_design.get(
        "total_candidate_experiments",
        -1
    )
) != 10:

    raise ValueError(
        "Experiment-design metadata does not confirm "
        "ten total candidates."
    )


print(
    "✓ Five RF candidates confirmed"
)

print(
    "✓ Five LSTM candidates confirmed"
)

print(
    "✓ Ten total candidate experiments confirmed"
)

print(
    "✓ Validation reserved for strategy comparison"
)

print(
    "✓ Independent Test reserved for final evaluation"
)

print(
    "✓ No optimal strategy declared"
)


# ------------------------------------------------------------
# 12. Validate final artifact inventory
# ------------------------------------------------------------

print("\n[FINAL ARTIFACT INVENTORY VALIDATION]")

inventory_groups = final_inventory.get(
    "artifact_inventory",
    {}
)


if not inventory_groups:

    raise ValueError(
        "Final artifact inventory is empty."
    )


core_inventory_paths = []


for artifact_group, artifacts in (
    inventory_groups.items()
):

    for artifact_name, artifact_path in (
        artifacts.items()
    ):

        artifact_path = Path(
            artifact_path
        )


        if not artifact_path.is_file():

            raise FileNotFoundError(
                "Final inventory artifact is missing:\n"
                f"{artifact_path}"
            )


        core_inventory_paths.append(
            artifact_path.resolve()
        )


if len(
    core_inventory_paths
) != 27:

    raise ValueError(
        "The established core N04 artifact inventory "
        f"should contain 27 artifacts, found "
        f"{len(core_inventory_paths)}."
    )


print(
    "✓ All 27 core N04 inventory artifacts are present"
)


# ------------------------------------------------------------
# 13. Validate final 36-artifact manifest
# ------------------------------------------------------------

print("\n[FINAL MANIFEST VALIDATION]")

if final_manifest.get(
    "integrity_algorithm"
) != "SHA-256":

    raise ValueError(
        "Final artifact manifest does not use SHA-256."
    )


if final_manifest.get(
    "manifest_self_excluded"
) is not True:

    raise ValueError(
        "Final artifact manifest self-exclusion is not confirmed."
    )


manifest_entries = final_manifest.get(
    "artifacts",
    []
)


if int(
    final_manifest.get(
        "artifact_count",
        -1
    )
) != 36:

    raise ValueError(
        "Final artifact manifest does not contain "
        "the established 36 artifacts."
    )


if len(
    manifest_entries
) != 36:

    raise ValueError(
        "Final artifact manifest entry count is not 36."
    )


manifest_paths = set()


for entry in manifest_entries:

    relative_path = entry.get(
        "relative_path"
    )


    if not relative_path:

        raise ValueError(
            "Final manifest contains an artifact "
            "without a relative path."
        )


    artifact_path = (
        FINAL_RECOVERY_MODEL_PREPARATION_DIR /
        relative_path
    )


    if not artifact_path.is_file():

        raise FileNotFoundError(
            "Final manifest references a missing artifact:\n"
            f"{artifact_path}"
        )


    manifest_paths.add(
        relative_path
    )


required_manifest_paths = {

    "final_artifact_inventory.json",

    "final_model_preparation_metadata.json",

    "model_ready_targets/y_train.npy",

    "model_ready_targets/y_validation.npy",

    "model_ready_targets/y_test.npy",

    "model_ready_targets/target_artifact_metadata.json",

    "partition_reproducibility_metadata.json",

    "final_train_validation_test_leakage_validation.json",

    "class_imbalance/class_imbalance_configuration.json",

    "downstream_imbalance_experiments/"
    "imbalance_experiment_matrix.csv",

    "downstream_imbalance_experiments/"
    "rf_imbalance_experiment_config.json",

    "downstream_imbalance_experiments/"
    "lstm_imbalance_experiment_config.json",

    "downstream_imbalance_experiments/"
    "imbalance_experiment_design_metadata.json",
}


missing_required_manifest_paths = (
    required_manifest_paths
    - manifest_paths
)


if missing_required_manifest_paths:

    raise ValueError(
        "Required final N04 artifacts are missing from "
        "the 36-entry manifest:\n"
        + "\n".join(
            f"  - {item}"
            for item in sorted(
                missing_required_manifest_paths
            )
        )
    )


print(
    "✓ SHA-256 integrity algorithm confirmed"
)

print(
    "✓ Manifest self-exclusion confirmed"
)

print(
    "✓ 36 manifest entries confirmed"
)

print(
    "✓ All manifest-referenced files are present"
)

print(
    "✓ Required downstream configuration artifacts "
    "are represented in the manifest"
)


# ------------------------------------------------------------
# 14. Validate final processing boundary
# ------------------------------------------------------------

print("\n[FINAL PROCESSING BOUNDARY VALIDATION]")

processing_boundary = final_metadata.get(
    "processing_boundary",
    {}
)


required_false_flags = [

    "large_arrays_loaded",

    "stage1_dataset_reloaded",

    "feature_selection_performed",

    "scaling_performed",

    "resampling_performed",

    "smote_performed",

    "class_weighting_performed",

    "model_fitting_performed",

    "partition_indices_modified",

    "target_values_modified",

    "validation_modified",

    "independent_test_modified",
]


for flag_name in required_false_flags:

    if processing_boundary.get(
        flag_name
    ) is not False:

        raise ValueError(
            "Final processing-boundary violation: "
            f"{flag_name} is not False."
        )


    print(
        f"✓ {flag_name}: False"
    )


# ------------------------------------------------------------
# 15. Final model-preparation readiness gate
# ------------------------------------------------------------

print("\n[FINAL MODEL-PREPARATION READINESS GATE]")

readiness_checks = {

    "Nine-class taxonomy":
        final_taxonomy.get(
            "class_count"
        ) == 9,

    "32-feature representation":
        final_feature_configuration.get(
            "feature_count"
        ) == 32,

    "Training partition":
        final_partition_configuration.get(
            "training_rows"
        ) == 1_814_018,

    "Validation partition":
        final_partition_configuration.get(
            "validation_rows"
        ) == 451_215,

    "Independent Test partition":
        final_partition_configuration.get(
            "test_rows"
        ) == 565_510,

    "Independent Test isolation":
        final_partition_configuration.get(
            "independent_test_isolated"
        ) is True,

    "Five RF candidates":
        final_experiment_configuration.get(
            "random_forest_candidate_count"
        ) == 5,

    "Five LSTM candidates":
        final_experiment_configuration.get(
            "lstm_candidate_count"
        ) == 5,

    "Ten total candidates":
        final_experiment_configuration.get(
            "total_candidate_count"
        ) == 10,

    "Validation strategy-selection boundary":
        final_experiment_configuration.get(
            "strategy_selection_partition"
        ) == "Validation",

    "Independent Test final-evaluation boundary":
        final_experiment_configuration.get(
            "final_evaluation_partition"
        ) == "Independent Test",

    "No premature strategy selection":
        final_experiment_configuration.get(
            "optimal_strategy_declared"
        ) is False,

    "Final consolidated metadata completed":
        final_metadata.get(
            "status"
        ) == "completed",

    "Final leakage validation passed":
        leakage_metadata.get(
            "validation_status"
        ) == "PASSED",
}


failed_readiness_checks = [
    check_name
    for check_name, check_result
    in readiness_checks.items()
    if check_result is not True
]


if failed_readiness_checks:

    raise ValueError(
        "Final N04 readiness gate failed:\n"
        + "\n".join(
            f"  - {item}"
            for item in failed_readiness_checks
        )
    )


for check_name in readiness_checks:

    print(
        f"✓ {check_name}"
    )


# ------------------------------------------------------------
# 16. Final completion
# ------------------------------------------------------------

print("\n[4.11.6 FINAL VALIDATION SUMMARY]")

print(
    "✓ Final N04 taxonomy is consistent"
)

print(
    "✓ Final 32-feature model-ready representation is consistent"
)

print(
    "✓ Training/Validation/Test partition structure is consistent"
)

print(
    "✓ Persisted feature artifacts are dimensionally valid"
)

print(
    "✓ Persisted target artifacts are dimensionally and "
    "taxonomically valid"
)

print(
    "✓ Independent Test isolation is preserved"
)

print(
    "✓ Training-only preprocessing boundaries are preserved"
)

print(
    "✓ RF and LSTM experiment configurations are recoverable"
)

print(
    "✓ Final 27-artifact core inventory is complete"
)

print(
    "✓ Final 36-artifact SHA-256 manifest is structurally valid"
)

print(
    "✓ Final processing boundary contains no prohibited operations"
)

print(
    "✓ Complete N04 model-preparation state is downstream-ready"
)


print("\n" + "=" * 72)

print(
    "4.11.6 complete model-preparation validation "
    "completed successfully."
)

print(
    "SECTION 4.11 — ARTIFACT RELOAD & VALIDATION "
    "COMPLETED AND VALIDATED."
)

print(
    "NOTEBOOK 04 — MODEL PREPARATION "
    "COMPLETED AND VALIDATED."
)

print("=" * 72)

========================================================================
4.11.6 — COMPLETE MODEL-PREPARATION VALIDATION
========================================================================

[FINAL RECOVERY BOUNDARY]
✓ N04 project root recovered independently
✓ N04 model-preparation directory recovered

[FINAL CONTROL ARTIFACT CHECK]
✓ Final model-preparation metadata: final_model_preparation_metadata.json
✓ Final artifact inventory: final_artifact_inventory.json
✓ Final artifact manifest: final_artifact_manifest.json
✓ Target metadata: target_artifact_metadata.json
✓ Taxonomy metadata: taxonomy_metadata.json
✓ Partition metadata: partition_reproducibility_metadata.json
✓ Final leakage validation: final_train_validation_test_leakage_validation.json
✓ Feature-set validation: final_feature_set_validation.json
✓ Selected-feature configuration: correlation_pruned_selected_features.json
✓ Training-only scaler metadata: training_only_scaler_metadata.json
✓ Partition-wise transformation metadata: partition_wise_transformation_metadata.json
✓ Model-ready feature metadata: model_ready_feature_artifacts.json
✓ Final scaling validation: final_scaling_reproducibility_validation.json
✓ Class-imbalance configuration: class_imbalance_configuration.json
✓ Class-imbalance severity metadata: class_imbalance_severity_metadata.json
✓ Experiment matrix: imbalance_experiment_matrix.csv
✓ RF experiment configuration: rf_imbalance_experiment_config.json
✓ LSTM experiment configuration: lstm_imbalance_experiment_config.json
✓ Experiment-design metadata: imbalance_experiment_design_metadata.json
✓ All 19 required final control artifacts are present

[FINAL METADATA RELOAD]
✓ Consolidated model-preparation metadata loaded
✓ Final artifact inventory loaded
✓ Final artifact manifest loaded
✓ Target metadata loaded
✓ Taxonomy metadata loaded
✓ Partition and leakage metadata loaded
✓ Feature-scaling metadata loaded
✓ Downstream experiment configurations loaded

[FINAL CONSOLIDATED METADATA STATUS]
✓ taxonomy_verified: True
✓ feature_configuration_verified: True
✓ partition_configuration_verified: True
✓ test_isolation_verified: True
✓ target_artifacts_verified: True
✓ downstream_experiment_configuration_verified: True
✓ Final consolidated N04 metadata is marked completed

[COMPLETE TAXONOMY VALIDATION]
✓ Nine-class taxonomy confirmed
✓ Class IDs 0–8 confirmed
✓ Consolidated and persisted taxonomy agree

[COMPLETE FEATURE CONFIGURATION VALIDATION]
✓ Final model-ready feature count: 32
✓ Training-only feature-selection boundary confirmed
✓ Training-only correlation-pruning boundary confirmed
✓ Training-only scaling boundary confirmed

[COMPLETE PARTITION VALIDATION]
✓ development_rows: 2,265,233
✓ training_rows: 1,814,018
✓ validation_rows: 451,215
✓ test_rows: 565,510
✓ Independent Test isolation confirmed
✓ No partition modification recorded
✓ Final leakage validation status: PASSED

[ACTUAL MODEL-READY FEATURE ARTIFACT VALIDATION]
✓ Training  : (1814018, 32)
✓ Validation: (451215, 32)
✓ Test      : (565510, 32)
✓ All persisted model-ready feature artifacts match the final 32-feature configuration

[ACTUAL MODEL-READY TARGET ARTIFACT VALIDATION]
✓ Training  : 1,814,018 labels | classes 0–8
✓ Validation: 451,215 labels | classes 0–8
✓ Test      : 565,510 labels | classes 0–8
✓ All persisted model-ready target artifacts match the final nine-class configuration

[COMPLETE DOWNSTREAM EXPERIMENT VALIDATION]
✓ Five RF candidates confirmed
✓ Five LSTM candidates confirmed
✓ Ten total candidate experiments confirmed
✓ Validation reserved for strategy comparison
✓ Independent Test reserved for final evaluation
✓ No optimal strategy declared

[FINAL ARTIFACT INVENTORY VALIDATION]
✓ All 27 core N04 inventory artifacts are present

[FINAL MANIFEST VALIDATION]
✓ SHA-256 integrity algorithm confirmed
✓ Manifest self-exclusion confirmed
✓ 36 manifest entries confirmed
✓ All manifest-referenced files are present
✓ Required downstream configuration artifacts are represented in the manifest

[FINAL PROCESSING BOUNDARY VALIDATION]
✓ large_arrays_loaded: False
✓ stage1_dataset_reloaded: False
✓ feature_selection_performed: False
✓ scaling_performed: False
✓ resampling_performed: False
✓ smote_performed: False
✓ class_weighting_performed: False
✓ model_fitting_performed: False
✓ partition_indices_modified: False
✓ target_values_modified: False
✓ validation_modified: False
✓ independent_test_modified: False

[FINAL MODEL-PREPARATION READINESS GATE]
✓ Nine-class taxonomy
✓ 32-feature representation
✓ Training partition
✓ Validation partition
✓ Independent Test partition
✓ Independent Test isolation
✓ Five RF candidates
✓ Five LSTM candidates
✓ Ten total candidates
✓ Validation strategy-selection boundary
✓ Independent Test final-evaluation boundary
✓ No premature strategy selection
✓ Final consolidated metadata completed
✓ Final leakage validation passed

[4.11.6 FINAL VALIDATION SUMMARY]
✓ Final N04 taxonomy is consistent
✓ Final 32-feature model-ready representation is consistent
✓ Training/Validation/Test partition structure is consistent
✓ Persisted feature artifacts are dimensionally valid
✓ Persisted target artifacts are dimensionally and taxonomically valid
✓ Independent Test isolation is preserved
✓ Training-only preprocessing boundaries are preserved
✓ RF and LSTM experiment configurations are recoverable
✓ Final 27-artifact core inventory is complete
✓ Final 36-artifact SHA-256 manifest is structurally valid
✓ Final processing boundary contains no prohibited operations
✓ Complete N04 model-preparation state is downstream-ready

========================================================================
4.11.6 complete model-preparation validation completed successfully.
SECTION 4.11 — ARTIFACT RELOAD & VALIDATION COMPLETED AND VALIDATED.
NOTEBOOK 04 — MODEL PREPARATION COMPLETED AND VALIDATED.
========================================================================

# 4.12 Model Handoff

## Purpose

This section establishes the formal handoff boundary between the
completed Notebook 04 model-preparation stage and the downstream
model-development stages.

Notebook 04 has completed and validated:

- final nine-class taxonomy consisting of eight attack families and
  the BENIGN class,
- training/validation/independent-test partitioning,
- training-only feature selection,
- final 32-feature representation,
- training-only feature scaling,
- class-imbalance analysis,
- Random Forest and LSTM imbalance experiment design,
- persistent model-ready feature and target artifacts,
- final artifact inventory and SHA-256 integrity manifest, and
- cold-start artifact recovery and complete model-preparation
  validation.

The subsections below define the exact downstream model contracts
without repeating preprocessing or modifying the finalized N04
artifacts.

The finalized N04 model-preparation state is treated as immutable
during downstream model development.

## 4.12.1 — Random Forest Handoff Contract

This subsection establishes the authoritative input and experimental
contract for downstream Random Forest development.

The Random Forest stage receives the finalized, scaled model-ready
feature representations produced by Notebook 04 together with their
corresponding persisted target artifacts. The downstream model stage
must not repeat feature selection, scaling, partitioning, or other
N04 preprocessing operations.

The Random Forest input representation consists of 32 features in the
authoritative N04 feature order and nine target classes:

0 — BENIGN
1 — DDoS
2 — Port Scan
3 — Brute Force
4 — Bot
5 — Web Attack
6 — Infiltration
7 — DoS
8 — Heartbleed

The persisted partitions are:

- Training: 1,814,018 observations × 32 features
- Validation: 451,215 observations × 32 features
- Independent Test: 565,510 observations × 32 features

The downstream Random Forest experiments must evaluate the five
strategies established in Section 4.9:

- RF-0 — Natural Distribution Baseline
- RF-1 — Balanced Class Weighting
- RF-2 — Balanced-Subsample Class Weighting
- RF-3 — Controlled Random Oversampling
- RF-4 — Controlled SMOTE

Validation is the strategy-comparison partition and the Independent
Test partition is reserved for final evaluation. No Random Forest
strategy is selected as optimal at the handoff stage.

The handoff contract does not perform model fitting, resampling,
scaling, feature selection, or modification of any persisted N04
artifact.

In [68]:
# ============================================================
# 4.12.1 — RANDOM FOREST HANDOFF CONTRACT
# ============================================================

import json
import numpy as np
from pathlib import Path

print("=" * 72)
print("4.12.1 — RANDOM FOREST HANDOFF CONTRACT")
print("=" * 72)


# ------------------------------------------------------------
# 1. Establish independent N04 handoff boundary
# ------------------------------------------------------------

HANDOFF_PROJECT_ROOT = Path(
    "/content/drive/MyDrive/"
    "AI-Network-Intrusion-Detection-System"
)

HANDOFF_MODEL_PREPARATION_DIR = (
    HANDOFF_PROJECT_ROOT /
    "outputs" /
    "model_preparation_v2"
)

if not HANDOFF_PROJECT_ROOT.is_dir():

    raise FileNotFoundError(
        "N04 project root was not found:\n"
        f"{HANDOFF_PROJECT_ROOT}"
    )

if not HANDOFF_MODEL_PREPARATION_DIR.is_dir():

    raise FileNotFoundError(
        "N04 model-preparation directory was not found:\n"
        f"{HANDOFF_MODEL_PREPARATION_DIR}"
    )


print("\n[HANDOFF RECOVERY BOUNDARY]")

print("✓ N04 project root recovered independently")
print("✓ N04 model-preparation directory recovered")


# ------------------------------------------------------------
# 2. Establish authoritative Random Forest input artifacts
# ------------------------------------------------------------

FEATURE_SCALING_DIR = (
    HANDOFF_MODEL_PREPARATION_DIR /
    "feature_scaling"
)

TARGET_ARTIFACT_DIR = (
    HANDOFF_MODEL_PREPARATION_DIR /
    "model_ready_targets"
)

FEATURE_SELECTION_DIR = (
    HANDOFF_MODEL_PREPARATION_DIR /
    "feature_selection"
)

EXPERIMENT_DIR = (
    HANDOFF_MODEL_PREPARATION_DIR /
    "downstream_imbalance_experiments"
)

RF_INPUT_PATHS = {

    "Training features":
        FEATURE_SCALING_DIR /
        "X_train_scaled.npy",

    "Validation features":
        FEATURE_SCALING_DIR /
        "X_validation_scaled.npy",

    "Test features":
        FEATURE_SCALING_DIR /
        "X_test_scaled.npy",

    "Training targets":
        TARGET_ARTIFACT_DIR /
        "y_train.npy",

    "Validation targets":
        TARGET_ARTIFACT_DIR /
        "y_validation.npy",

    "Test targets":
        TARGET_ARTIFACT_DIR /
        "y_test.npy",

    "Selected-feature configuration":
        FEATURE_SELECTION_DIR /
        "correlation_pruned_selected_features.json",

    "RF experiment configuration":
        EXPERIMENT_DIR /
        "rf_imbalance_experiment_config.json",
}


print("\n[PERSISTED RF HANDOFF ARTIFACT CHECK]")

missing_artifacts = []

for artifact_name, artifact_path in RF_INPUT_PATHS.items():

    if not artifact_path.is_file():

        missing_artifacts.append(
            f"{artifact_name}: {artifact_path}"
        )

    else:

        print(
            f"✓ {artifact_name}: "
            f"{artifact_path.name}"
        )


if missing_artifacts:

    raise FileNotFoundError(
        "Required Random Forest handoff artifacts are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_artifacts
        )
    )


# ------------------------------------------------------------
# 3. Establish authoritative model configuration
# ------------------------------------------------------------

EXPECTED_FEATURE_COUNT = 32

EXPECTED_CLASS_MAPPING = {
    "BENIGN": 0,
    "DDoS": 1,
    "Port Scan": 2,
    "Brute Force": 3,
    "Bot": 4,
    "Web Attack": 5,
    "Infiltration": 6,
    "DoS": 7,
    "Heartbleed": 8,
}

EXPECTED_CLASS_IDS = list(
    range(9)
)

EXPECTED_PARTITION_SHAPES = {

    "Training": (
        1_814_018,
        EXPECTED_FEATURE_COUNT
    ),

    "Validation": (
        451_215,
        EXPECTED_FEATURE_COUNT
    ),

    "Test": (
        565_510,
        EXPECTED_FEATURE_COUNT
    ),
}


if len(EXPECTED_CLASS_MAPPING) != 9:

    raise ValueError(
        "The established Random Forest handoff taxonomy "
        "must contain exactly nine classes."
    )

if sorted(
    EXPECTED_CLASS_MAPPING.values()
) != EXPECTED_CLASS_IDS:

    raise ValueError(
        "The established class IDs are not consecutive "
        "integers 0–8."
    )


print("\n[FINAL TAXONOMY CONTRACT]")

print("✓ Nine-class Random Forest output space confirmed")
print("✓ Class IDs 0–8 confirmed")

for class_name, class_id in (
    EXPECTED_CLASS_MAPPING.items()
):

    print(
        f"✓ {class_id}: {class_name}"
    )


# ------------------------------------------------------------
# 4. Validate authoritative feature order
# ------------------------------------------------------------

with open(
    RF_INPUT_PATHS[
        "Selected-feature configuration"
    ],
    "r",
    encoding="utf-8"
) as file:

    selected_feature_metadata = json.load(
        file
    )


def recover_feature_order(metadata):

    possible_keys = [
        "selected_features",
        "retained_features",
        "final_features",
        "features",
        "feature_columns",
    ]

    if isinstance(
        metadata,
        list
    ):

        feature_order = metadata

    else:

        feature_order = None

        for key in possible_keys:

            candidate = metadata.get(
                key
            )

            if isinstance(
                candidate,
                list
            ):

                feature_order = candidate
                break

    if feature_order is None:

        raise ValueError(
            "Could not identify the authoritative "
            "selected-feature order."
        )

    feature_order = list(
        feature_order
    )

    if len(feature_order) != EXPECTED_FEATURE_COUNT:

        raise ValueError(
            "The authoritative selected-feature artifact "
            f"contains {len(feature_order)} features "
            f"instead of {EXPECTED_FEATURE_COUNT}."
        )

    if len(
        set(feature_order)
    ) != len(feature_order):

        raise ValueError(
            "The authoritative feature order contains "
            "duplicate feature names."
        )

    return feature_order


authoritative_feature_order = (
    recover_feature_order(
        selected_feature_metadata
    )
)


print("\n[FEATURE CONFIGURATION CONTRACT]")

print(
    f"✓ Final feature count: "
    f"{len(authoritative_feature_order)}"
)

print(
    "✓ Authoritative 32-feature order recovered"
)


# ------------------------------------------------------------
# 5. Memory-conscious feature artifact validation
# ------------------------------------------------------------

print("\n[MODEL-READY FEATURE INPUT VALIDATION]")

feature_paths = {

    "Training":
        RF_INPUT_PATHS["Training features"],

    "Validation":
        RF_INPUT_PATHS["Validation features"],

    "Test":
        RF_INPUT_PATHS["Test features"],
}

feature_shapes = {}

for partition_name, feature_path in (
    feature_paths.items()
):

    # Memory mapping validates the persisted shape without
    # loading the complete feature matrix into RAM.
    mapped_features = np.load(
        feature_path,
        mmap_mode="r"
    )

    actual_shape = tuple(
        mapped_features.shape
    )

    expected_shape = (
        EXPECTED_PARTITION_SHAPES[
            partition_name
        ]
    )

    if actual_shape != expected_shape:

        del mapped_features

        raise ValueError(
            f"{partition_name} feature artifact has "
            f"shape {actual_shape}; expected "
            f"{expected_shape}."
        )

    if mapped_features.ndim != 2:

        del mapped_features

        raise ValueError(
            f"{partition_name} feature artifact is not "
            "a two-dimensional model-ready matrix."
        )

    feature_shapes[
        partition_name
    ] = actual_shape

    print(
        f"✓ {partition_name:<10}: "
        f"{actual_shape}"
    )

    del mapped_features


print(
    "✓ All persisted RF feature inputs match "
    "the final 32-feature configuration"
)


# ------------------------------------------------------------
# 6. Validate persisted target artifacts
# ------------------------------------------------------------

print("\n[TARGET INPUT VALIDATION]")

target_paths = {

    "Training":
        RF_INPUT_PATHS["Training targets"],

    "Validation":
        RF_INPUT_PATHS["Validation targets"],

    "Test":
        RF_INPUT_PATHS["Test targets"],
}

target_expected_lengths = {

    "Training":
        1_814_018,

    "Validation":
        451_215,

    "Test":
        565_510,
}


for partition_name, target_path in (
    target_paths.items()
):

    # Targets are persisted as compact arrays, so memory
    # mapping keeps this validation lightweight as well.
    mapped_target = np.load(
        target_path,
        mmap_mode="r"
    )

    actual_shape = tuple(
        mapped_target.shape
    )

    expected_length = (
        target_expected_lengths[
            partition_name
        ]
    )

    if actual_shape != (
        expected_length,
    ):

        del mapped_target

        raise ValueError(
            f"{partition_name} target artifact has "
            f"shape {actual_shape}; expected "
            f"({expected_length},)."
        )

    if mapped_target.ndim != 1:

        del mapped_target

        raise ValueError(
            f"{partition_name} target artifact is not "
            "a one-dimensional label array."
        )

    unique_labels = np.unique(
        mapped_target
    )

    if not np.array_equal(
        unique_labels,
        np.array(
            EXPECTED_CLASS_IDS,
            dtype=unique_labels.dtype
        )
    ):

        del mapped_target

        raise ValueError(
            f"{partition_name} target artifact does not "
            "contain the complete established class-ID "
            "set 0–8."
        )

    print(
        f"✓ {partition_name:<10}: "
        f"{expected_length:,} labels | classes 0–8"
    )

    del mapped_target


print(
    "✓ All persisted RF target inputs match "
    "the final nine-class taxonomy"
)


# ------------------------------------------------------------
# 7. Recover and validate RF experiment configuration
# ------------------------------------------------------------

with open(
    RF_INPUT_PATHS[
        "RF experiment configuration"
    ],
    "r",
    encoding="utf-8"
) as file:

    rf_configuration = json.load(
        file
    )


print("\n[RANDOM FOREST EXPERIMENT CONTRACT]")

if rf_configuration.get(
    "model_family"
) != "Random Forest":

    raise ValueError(
        "Persisted RF configuration does not identify "
        "the model family as Random Forest."
    )


if int(
    rf_configuration.get(
        "candidate_count",
        -1
    )
) != 5:

    raise ValueError(
        "Persisted RF configuration does not contain "
        "exactly five candidate strategies."
    )


expected_rf_strategies = [
    (
        "RF-0",
        "Natural Distribution Baseline"
    ),
    (
        "RF-1",
        "Balanced Class Weighting"
    ),
    (
        "RF-2",
        "Balanced-Subsample Class Weighting"
    ),
    (
        "RF-3",
        "Controlled Random Oversampling"
    ),
    (
        "RF-4",
        "Controlled SMOTE"
    ),
]


persisted_rf_strategies = [
    (
        strategy.get("strategy_id"),
        strategy.get("strategy_name")
    )
    for strategy in rf_configuration.get(
        "strategies",
        []
    )
]


if persisted_rf_strategies != (
    expected_rf_strategies
):

    raise ValueError(
        "Persisted Random Forest strategies do not "
        "match the established Section 4.9 design.\n"
        f"Expected: {expected_rf_strategies}\n"
        f"Observed: {persisted_rf_strategies}"
    )


for strategy_id, strategy_name in (
    expected_rf_strategies
):

    print(
        f"✓ {strategy_id}: {strategy_name}"
    )


# ------------------------------------------------------------
# 8. Validate RF experimental boundaries
# ------------------------------------------------------------

common_boundary = rf_configuration.get(
    "common_boundary",
    {}
)

sampling_constraints = rf_configuration.get(
    "sampling_constraints",
    {}
)


if common_boundary.get(
    "strategy_selection_partition"
) != "validation":

    raise ValueError(
        "Random Forest strategy selection is not "
        "assigned to the Validation partition."
    )


if common_boundary.get(
    "final_evaluation_partition"
) != "independent_test":

    raise ValueError(
        "Random Forest final evaluation is not "
        "assigned to the Independent Test partition."
    )


if common_boundary.get(
    "optimal_strategy_declared"
) is not False:

    raise ValueError(
        "An optimal Random Forest strategy has already "
        "been declared before downstream experimentation."
    )


if common_boundary.get(
    "model_fitting_performed"
) is not False:

    raise ValueError(
        "Random Forest model fitting is recorded as "
        "already performed in the N04 experiment design."
    )


if sampling_constraints.get(
    "validation_sampling"
) is not False:

    raise ValueError(
        "Validation sampling is not prohibited by the "
        "persisted RF experiment configuration."
    )


if sampling_constraints.get(
    "test_sampling"
) is not False:

    raise ValueError(
        "Test sampling is not prohibited by the "
        "persisted RF experiment configuration."
    )


print(
    "✓ Validation is reserved for RF strategy comparison"
)

print(
    "✓ Independent Test is reserved for final evaluation"
)

print(
    "✓ No RF strategy has been selected as optimal"
)

print(
    "✓ No RF model fitting was performed in N04"
)

print(
    "✓ Validation and Test sampling are prohibited"
)


# ------------------------------------------------------------
# 9. Confirm preprocessing handoff boundary
# ------------------------------------------------------------

print("\n[PREPROCESSING HANDOFF BOUNDARY]")

print(
    "✓ Feature selection is complete and frozen"
)

print(
    "✓ Training-only scaling is complete and frozen"
)

print(
    "✓ RF receives persisted scaled feature artifacts"
)

print(
    "✓ No additional scaling is required"
)

print(
    "✓ No additional feature selection is required"
)

print(
    "✓ N04 partitions must not be regenerated"
)

print(
    "✓ N04 target labels must not be modified"
)


# ------------------------------------------------------------
# 10. Final RF handoff readiness gate
# ------------------------------------------------------------

print("\n[RF HANDOFF READINESS GATE]")

handoff_checks = [

    len(authoritative_feature_order) == 32,

    feature_shapes["Training"] ==
    (1_814_018, 32),

    feature_shapes["Validation"] ==
    (451_215, 32),

    feature_shapes["Test"] ==
    (565_510, 32),

    len(EXPECTED_CLASS_MAPPING) == 9,

    persisted_rf_strategies ==
    expected_rf_strategies,

    common_boundary.get(
        "strategy_selection_partition"
    ) == "validation",

    common_boundary.get(
        "final_evaluation_partition"
    ) == "independent_test",

    common_boundary.get(
        "optimal_strategy_declared"
    ) is False,

    common_boundary.get(
        "model_fitting_performed"
    ) is False,
]


if not all(
    handoff_checks
):

    raise ValueError(
        "One or more Random Forest handoff readiness "
        "checks failed."
    )


print(
    "✓ Final 32-feature representation confirmed"
)

print(
    "✓ Nine-class output space confirmed"
)

print(
    "✓ Training/Validation/Test dimensions confirmed"
)

print(
    "✓ Five RF imbalance strategies confirmed"
)

print(
    "✓ Validation/Test experimental boundary confirmed"
)

print(
    "✓ No model fitting performed"
)


# ------------------------------------------------------------
# 11. Final subsection summary
# ------------------------------------------------------------

print("\n[4.12.1 VALIDATION SUMMARY]")

print(
    "✓ Random Forest feature inputs are recoverable"
)

print(
    "✓ Random Forest target inputs are recoverable"
)

print(
    "✓ Authoritative 32-feature order is preserved"
)

print(
    "✓ Nine-class taxonomy and class IDs 0–8 are preserved"
)

print(
    "✓ Five Section 4.9 RF strategies are preserved"
)

print(
    "✓ Validation remains the strategy-selection partition"
)

print(
    "✓ Independent Test remains the final-evaluation partition"
)

print(
    "✓ N04 preprocessing remains frozen for downstream RF development"
)

print(
    "✓ Random Forest handoff contract is ready for downstream development"
)


print("\n" + "=" * 72)

print(
    "4.12.1 Random Forest handoff contract "
    "validated successfully."
)

print("=" * 72)

========================================================================
4.12.1 — RANDOM FOREST HANDOFF CONTRACT
========================================================================

[HANDOFF RECOVERY BOUNDARY]
✓ N04 project root recovered independently
✓ N04 model-preparation directory recovered

[PERSISTED RF HANDOFF ARTIFACT CHECK]
✓ Training features: X_train_scaled.npy
✓ Validation features: X_validation_scaled.npy
✓ Test features: X_test_scaled.npy
✓ Training targets: y_train.npy
✓ Validation targets: y_validation.npy
✓ Test targets: y_test.npy
✓ Selected-feature configuration: correlation_pruned_selected_features.json
✓ RF experiment configuration: rf_imbalance_experiment_config.json

[FINAL TAXONOMY CONTRACT]
✓ Nine-class Random Forest output space confirmed
✓ Class IDs 0–8 confirmed
✓ 0: BENIGN
✓ 1: DDoS
✓ 2: Port Scan
✓ 3: Brute Force
✓ 4: Bot
✓ 5: Web Attack
✓ 6: Infiltration
✓ 7: DoS
✓ 8: Heartbleed

[FEATURE CONFIGURATION CONTRACT]
✓ Final feature count: 32
✓ Authoritative 32-feature order recovered

[MODEL-READY FEATURE INPUT VALIDATION]
✓ Training  : (1814018, 32)
✓ Validation: (451215, 32)
✓ Test      : (565510, 32)
✓ All persisted RF feature inputs match the final 32-feature configuration

[TARGET INPUT VALIDATION]
✓ Training  : 1,814,018 labels | classes 0–8
✓ Validation: 451,215 labels | classes 0–8
✓ Test      : 565,510 labels | classes 0–8
✓ All persisted RF target inputs match the final nine-class taxonomy

[RANDOM FOREST EXPERIMENT CONTRACT]
✓ RF-0: Natural Distribution Baseline
✓ RF-1: Balanced Class Weighting
✓ RF-2: Balanced-Subsample Class Weighting
✓ RF-3: Controlled Random Oversampling
✓ RF-4: Controlled SMOTE
✓ Validation is reserved for RF strategy comparison
✓ Independent Test is reserved for final evaluation
✓ No RF strategy has been selected as optimal
✓ No RF model fitting was performed in N04
✓ Validation and Test sampling are prohibited

[PREPROCESSING HANDOFF BOUNDARY]
✓ Feature selection is complete and frozen
✓ Training-only scaling is complete and frozen
✓ RF receives persisted scaled feature artifacts
✓ No additional scaling is required
✓ No additional feature selection is required
✓ N04 partitions must not be regenerated
✓ N04 target labels must not be modified

[RF HANDOFF READINESS GATE]
✓ Final 32-feature representation confirmed
✓ Nine-class output space confirmed
✓ Training/Validation/Test dimensions confirmed
✓ Five RF imbalance strategies confirmed
✓ Validation/Test experimental boundary confirmed
✓ No model fitting performed

[4.12.1 VALIDATION SUMMARY]
✓ Random Forest feature inputs are recoverable
✓ Random Forest target inputs are recoverable
✓ Authoritative 32-feature order is preserved
✓ Nine-class taxonomy and class IDs 0–8 are preserved
✓ Five Section 4.9 RF strategies are preserved
✓ Validation remains the strategy-selection partition
✓ Independent Test remains the final-evaluation partition
✓ N04 preprocessing remains frozen for downstream RF development
✓ Random Forest handoff contract is ready for downstream development

========================================================================
4.12.1 Random Forest handoff contract validated successfully.
========================================================================

## 4.12.2 — LSTM Handoff Contract

This subsection establishes the authoritative input and experimental
contract for downstream LSTM development.

The LSTM stage receives the finalized N04 model-ready feature
representation and target artifacts. The N04 feature representation
contains 32 features in the authoritative feature order and follows
the finalized nine-class taxonomy:

0 — BENIGN
1 — DDoS
2 — Port Scan
3 — Brute Force
4 — Bot
5 — Web Attack
6 — Infiltration
7 — DoS
8 — Heartbleed

The persisted partitions are:

- Training: 1,814,018 observations × 32 features
- Validation: 451,215 observations × 32 features
- Independent Test: 565,510 observations × 32 features

The downstream LSTM design uses a sequence length of 10 observations.
However, the persisted N04 feature artifacts are two-dimensional
flow-level model-ready representations and are not treated as
pre-constructed packet sequences.

Sequence construction is therefore deferred to downstream LSTM
development. The downstream sequence-construction process must:

- preserve Training, Validation, and Independent Test boundaries,
- preserve the authoritative 32-feature order,
- preserve the corresponding target labels,
- avoid creating sequences across partition boundaries,
- avoid row-level SMOTE or other operations that destroy sequence
  structure, and
- use a documented observation/session ordering rather than assuming
  that the persisted feature-array order represents packet chronology.

The five LSTM imbalance strategies established in Section 4.9 are:

- LSTM-0 — Natural Sequence Distribution Baseline
- LSTM-1 — Class-Weighted Loss
- LSTM-2 — Class-Aware Sequence Sampling
- LSTM-3 — Controlled Sequence Oversampling
- LSTM-4 — Sequence-Preserving Synthetic Sampling

The LSTM imbalance experiments are restricted to the Training
partition. Validation is reserved for strategy comparison and the
Independent Test partition is reserved for final evaluation.

No LSTM sequence construction, sampling, synthetic-data generation,
model fitting, or partition modification is performed in this
handoff subsection.

In [69]:
# ============================================================
# 4.12.2 — LSTM HANDOFF CONTRACT
# ============================================================

import json
import numpy as np
from pathlib import Path

print("=" * 72)
print("4.12.2 — LSTM HANDOFF CONTRACT")
print("=" * 72)


# ------------------------------------------------------------
# 1. Establish independent N04 handoff boundary
# ------------------------------------------------------------

LSTM_HANDOFF_PROJECT_ROOT = Path(
    "/content/drive/MyDrive/"
    "AI-Network-Intrusion-Detection-System"
)

LSTM_HANDOFF_MODEL_PREPARATION_DIR = (
    LSTM_HANDOFF_PROJECT_ROOT /
    "outputs" /
    "model_preparation_v2"
)

if not LSTM_HANDOFF_PROJECT_ROOT.is_dir():

    raise FileNotFoundError(
        "N04 project root was not found:\n"
        f"{LSTM_HANDOFF_PROJECT_ROOT}"
    )

if not LSTM_HANDOFF_MODEL_PREPARATION_DIR.is_dir():

    raise FileNotFoundError(
        "N04 model-preparation directory was not found:\n"
        f"{LSTM_HANDOFF_MODEL_PREPARATION_DIR}"
    )

print("\n[HANDOFF RECOVERY BOUNDARY]")

print("✓ N04 project root recovered independently")
print("✓ N04 model-preparation directory recovered")


# ------------------------------------------------------------
# 2. Establish authoritative LSTM handoff artifacts
# ------------------------------------------------------------

LSTM_FEATURE_SCALING_DIR = (
    LSTM_HANDOFF_MODEL_PREPARATION_DIR /
    "feature_scaling"
)

LSTM_TARGET_ARTIFACT_DIR = (
    LSTM_HANDOFF_MODEL_PREPARATION_DIR /
    "model_ready_targets"
)

LSTM_FEATURE_SELECTION_DIR = (
    LSTM_HANDOFF_MODEL_PREPARATION_DIR /
    "feature_selection"
)

LSTM_EXPERIMENT_DIR = (
    LSTM_HANDOFF_MODEL_PREPARATION_DIR /
    "downstream_imbalance_experiments"
)

LSTM_HANDOFF_PATHS = {

    "Training features":
        LSTM_FEATURE_SCALING_DIR /
        "X_train_scaled.npy",

    "Validation features":
        LSTM_FEATURE_SCALING_DIR /
        "X_validation_scaled.npy",

    "Test features":
        LSTM_FEATURE_SCALING_DIR /
        "X_test_scaled.npy",

    "Training targets":
        LSTM_TARGET_ARTIFACT_DIR /
        "y_train.npy",

    "Validation targets":
        LSTM_TARGET_ARTIFACT_DIR /
        "y_validation.npy",

    "Test targets":
        LSTM_TARGET_ARTIFACT_DIR /
        "y_test.npy",

    "Selected-feature configuration":
        LSTM_FEATURE_SELECTION_DIR /
        "correlation_pruned_selected_features.json",

    "LSTM experiment configuration":
        LSTM_EXPERIMENT_DIR /
        "lstm_imbalance_experiment_config.json",
}


print("\n[PERSISTED LSTM HANDOFF ARTIFACT CHECK]")

missing_paths = []

for artifact_name, artifact_path in (
    LSTM_HANDOFF_PATHS.items()
):

    if not artifact_path.is_file():

        missing_paths.append(
            f"{artifact_name}: {artifact_path}"
        )

    else:

        print(
            f"✓ {artifact_name}: "
            f"{artifact_path.name}"
        )


if missing_paths:

    raise FileNotFoundError(
        "Required LSTM handoff artifacts are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_paths
        )
    )


# ------------------------------------------------------------
# 3. Establish authoritative LSTM input contract
# ------------------------------------------------------------

EXPECTED_LSTM_FEATURE_COUNT = 32
EXPECTED_LSTM_SEQUENCE_LENGTH = 10

EXPECTED_LSTM_CLASS_IDS = list(
    range(9)
)

EXPECTED_LSTM_PARTITION_SHAPES = {

    "Training":
        (1_814_018, 32),

    "Validation":
        (451_215, 32),

    "Test":
        (565_510, 32),
}


EXPECTED_CLASS_MAPPING = {

    "BENIGN": 0,
    "DDoS": 1,
    "Port Scan": 2,
    "Brute Force": 3,
    "Bot": 4,
    "Web Attack": 5,
    "Infiltration": 6,
    "DoS": 7,
    "Heartbleed": 8,
}


print("\n[LSTM INPUT CONTRACT]")

print(
    f"✓ Final feature count: "
    f"{EXPECTED_LSTM_FEATURE_COUNT}"
)

print(
    f"✓ Downstream sequence length: "
    f"{EXPECTED_LSTM_SEQUENCE_LENGTH}"
)

print(
    "✓ Nine-class output space confirmed"
)

print(
    "✓ Class IDs 0–8 confirmed"
)


# ------------------------------------------------------------
# 4. Validate authoritative feature order
# ------------------------------------------------------------

with open(
    LSTM_HANDOFF_PATHS[
        "Selected-feature configuration"
    ],
    "r",
    encoding="utf-8"
) as file:

    selected_feature_metadata = json.load(
        file
    )


def recover_feature_order(metadata):

    possible_keys = [
        "selected_features",
        "retained_features",
        "final_features",
        "features",
        "feature_columns",
    ]

    if isinstance(
        metadata,
        list
    ):

        feature_order = metadata

    else:

        feature_order = None

        for key in possible_keys:

            candidate = metadata.get(
                key
            )

            if isinstance(
                candidate,
                list
            ):

                feature_order = candidate
                break

    if feature_order is None:

        raise ValueError(
            "Could not recover the authoritative "
            "32-feature order."
        )

    feature_order = list(
        feature_order
    )

    if len(feature_order) != (
        EXPECTED_LSTM_FEATURE_COUNT
    ):

        raise ValueError(
            "The authoritative feature configuration "
            f"contains {len(feature_order)} features "
            f"instead of {EXPECTED_LSTM_FEATURE_COUNT}."
        )

    if len(
        set(feature_order)
    ) != len(feature_order):

        raise ValueError(
            "The authoritative feature order contains "
            "duplicate feature names."
        )

    return feature_order


authoritative_lstm_feature_order = (
    recover_feature_order(
        selected_feature_metadata
    )
)


print("\n[FEATURE ORDER VALIDATION]")

print(
    "✓ Authoritative 32-feature order recovered"
)

print(
    "✓ No feature reordering performed"
)


# ------------------------------------------------------------
# 5. Validate persisted model-ready feature shapes
# ------------------------------------------------------------

print("\n[MODEL-READY FEATURE VALIDATION]")

lstm_feature_paths = {

    "Training":
        LSTM_HANDOFF_PATHS[
            "Training features"
        ],

    "Validation":
        LSTM_HANDOFF_PATHS[
            "Validation features"
        ],

    "Test":
        LSTM_HANDOFF_PATHS[
            "Test features"
        ],
}


for partition_name, feature_path in (
    lstm_feature_paths.items()
):

    # Memory mapping validates dimensions without
    # loading the complete feature matrix into RAM.
    mapped_features = np.load(
        feature_path,
        mmap_mode="r"
    )

    actual_shape = tuple(
        mapped_features.shape
    )

    expected_shape = (
        EXPECTED_LSTM_PARTITION_SHAPES[
            partition_name
        ]
    )

    if actual_shape != expected_shape:

        del mapped_features

        raise ValueError(
            f"{partition_name} feature artifact has "
            f"shape {actual_shape}; expected "
            f"{expected_shape}."
        )

    if mapped_features.ndim != 2:

        del mapped_features

        raise ValueError(
            f"{partition_name} feature artifact must "
            "remain a two-dimensional observation matrix "
            "until downstream sequence construction."
        )

    print(
        f"✓ {partition_name:<10}: "
        f"{actual_shape}"
    )

    del mapped_features


print(
    "✓ All persisted LSTM feature inputs match "
    "the final N04 32-feature representation"
)


# ------------------------------------------------------------
# 6. Validate persisted target artifacts
# ------------------------------------------------------------

print("\n[TARGET VALIDATION]")

lstm_target_paths = {

    "Training":
        LSTM_HANDOFF_PATHS[
            "Training targets"
        ],

    "Validation":
        LSTM_HANDOFF_PATHS[
            "Validation targets"
        ],

    "Test":
        LSTM_HANDOFF_PATHS[
            "Test targets"
        ],
}


expected_target_lengths = {

    "Training":
        1_814_018,

    "Validation":
        451_215,

    "Test":
        565_510,
}


for partition_name, target_path in (
    lstm_target_paths.items()
):

    mapped_target = np.load(
        target_path,
        mmap_mode="r"
    )

    actual_shape = tuple(
        mapped_target.shape
    )

    expected_shape = (
        expected_target_lengths[
            partition_name
        ],
    )

    if actual_shape != expected_shape:

        del mapped_target

        raise ValueError(
            f"{partition_name} target artifact has "
            f"shape {actual_shape}; expected "
            f"{expected_shape}."
        )

    unique_labels = np.unique(
        mapped_target
    )

    if not np.array_equal(
        unique_labels,
        np.array(
            EXPECTED_LSTM_CLASS_IDS,
            dtype=unique_labels.dtype
        )
    ):

        del mapped_target

        raise ValueError(
            f"{partition_name} target artifact does not "
            "contain the complete class-ID set 0–8."
        )

    print(
        f"✓ {partition_name:<10}: "
        f"{expected_shape[0]:,} labels | classes 0–8"
    )

    del mapped_target


print(
    "✓ All persisted LSTM target inputs match "
    "the final nine-class taxonomy"
)


# ------------------------------------------------------------
# 7. Recover and validate LSTM experiment configuration
# ------------------------------------------------------------

with open(
    LSTM_HANDOFF_PATHS[
        "LSTM experiment configuration"
    ],
    "r",
    encoding="utf-8"
) as file:

    lstm_configuration = json.load(
        file
    )


EXPECTED_LSTM_STRATEGIES = {

    "LSTM-0":
        "Natural Sequence Distribution Baseline",

    "LSTM-1":
        "Class-Weighted Loss",

    "LSTM-2":
        "Class-Aware Sequence Sampling",

    "LSTM-3":
        "Controlled Sequence Oversampling",

    "LSTM-4":
        "Sequence-Preserving Synthetic Sampling",
}


print("\n[LSTM EXPERIMENT CONTRACT]")

if lstm_configuration.get(
    "model_family"
) != "LSTM":

    raise ValueError(
        "Persisted LSTM configuration does not "
        "identify the model family as LSTM."
    )


lstm_strategies = (
    lstm_configuration.get(
        "strategies",
        []
    )
)


if len(lstm_strategies) != 5:

    raise ValueError(
        "Persisted LSTM configuration does not "
        "contain exactly five strategies."
    )


observed_strategy_ids = {
    strategy.get(
        "strategy_id"
    )
    for strategy in lstm_strategies
}


if observed_strategy_ids != set(
    EXPECTED_LSTM_STRATEGIES.keys()
):

    raise ValueError(
        "Persisted LSTM strategy IDs do not match "
        "the established Section 4.9 design."
    )


for strategy in lstm_strategies:

    strategy_id = strategy[
        "strategy_id"
    ]

    expected_name = (
        EXPECTED_LSTM_STRATEGIES[
            strategy_id
        ]
    )

    if strategy.get(
        "strategy_name"
    ) != expected_name:

        raise ValueError(
            f"{strategy_id} strategy name mismatch: "
            f"expected {expected_name!r}, "
            f"found {strategy.get('strategy_name')!r}"
        )

    if strategy.get(
        "sampling_unit"
    ) != "complete sequence":

        raise ValueError(
            f"{strategy_id} does not operate on "
            "complete sequences as required."
        )

    print(
        f"✓ {strategy_id}: "
        f"{expected_name}"
    )


# ------------------------------------------------------------
# 8. Validate LSTM sampling constraints
# ------------------------------------------------------------

print("\n[LSTM SAMPLING CONSTRAINTS]")

lstm_constraints = (
    lstm_configuration.get(
        "sampling_constraints",
        {}
    )
)


expected_lstm_constraints = {

    "minimum_training_support_for_synthetic_sampling":
        10,

    "controlled_sequence_oversampling_multiplier":
        5,

    "maximum_target_sequences_per_class":
        50_000,

    "row_level_SMOTE":
        False,

    "validation_sampling":
        False,

    "test_sampling":
        False,

    "low_support_classes_excluded_from_synthetic_generation":
        True,

    "sequence_structure_preserved":
        True,
}


for field_name, expected_value in (
    expected_lstm_constraints.items()
):

    actual_value = lstm_constraints.get(
        field_name
    )

    if actual_value != expected_value:

        raise ValueError(
            f"LSTM sampling constraint "
            f"'{field_name}' mismatch: "
            f"expected {expected_value!r}, "
            f"found {actual_value!r}"
        )


print(
    "✓ Minimum synthetic-sampling support: 10"
)

print(
    "✓ Controlled sequence oversampling multiplier: 5x"
)

print(
    "✓ Maximum target sequences/class: 50,000"
)

print(
    "✓ Row-level SMOTE prohibited"
)

print(
    "✓ Validation sampling prohibited"
)

print(
    "✓ Test sampling prohibited"
)

print(
    "✓ Low-support classes excluded from "
    "synthetic generation"
)

print(
    "✓ Sequence structure preservation required"
)


# ------------------------------------------------------------
# 9. Validate common experimental boundary
# ------------------------------------------------------------

print("\n[COMMON LSTM EXPERIMENTAL BOUNDARY]")

lstm_boundary = (
    lstm_configuration.get(
        "common_boundary",
        {}
    )
)


expected_boundary = {

    "training_partition_modifiable":
        True,

    "validation_partition_untouched":
        True,

    "independent_test_partition_untouched":
        True,

    "strategy_selection_partition":
        "validation",

    "final_evaluation_partition":
        "independent_test",

    "primary_metric":
        "macro_f1",

    "optimal_strategy_declared":
        False,

    "model_fitting_performed":
        False,

    "synthetic_data_generated":
        False,
}


for field_name, expected_value in (
    expected_boundary.items()
):

    actual_value = lstm_boundary.get(
        field_name
    )

    if actual_value != expected_value:

        raise ValueError(
            f"LSTM boundary field "
            f"'{field_name}' mismatch: "
            f"expected {expected_value!r}, "
            f"found {actual_value!r}"
        )


print(
    "✓ Training is the only modifiable partition"
)

print(
    "✓ Validation remains reserved for "
    "strategy comparison"
)

print(
    "✓ Independent Test remains reserved for "
    "final evaluation"
)

print(
    "✓ Macro F1 remains the primary metric"
)

print(
    "✓ No LSTM strategy has been selected as optimal"
)

print(
    "✓ No LSTM model fitting was performed in N04"
)


# ------------------------------------------------------------
# 10. Establish sequence-construction boundary
# ------------------------------------------------------------

print("\n[SEQUENCE-CONSTRUCTION BOUNDARY]")

print(
    f"✓ Downstream sequence length contract: "
    f"{EXPECTED_LSTM_SEQUENCE_LENGTH} observations"
)

print(
    "✓ N04 feature artifacts remain two-dimensional "
    "flow-level observations"
)

print(
    "✓ No pre-constructed LSTM sequence artifact "
    "is assumed at the N04 handoff"
)

print(
    "✓ Sequence construction is deferred to "
    "downstream LSTM development"
)

print(
    "✓ Sequence construction must preserve "
    "partition boundaries"
)

print(
    "✓ Sequence construction must preserve "
    "the authoritative 32-feature order"
)

print(
    "✓ Observation/session ordering must be "
    "explicitly established downstream"
)

print(
    "✓ No cross-partition sequences are permitted"
)


# ------------------------------------------------------------
# 11. Final LSTM handoff readiness gate
# ------------------------------------------------------------

print("\n[LSTM HANDOFF READINESS GATE]")

handoff_checks = [

    len(authoritative_lstm_feature_order) == 32,

    EXPECTED_LSTM_SEQUENCE_LENGTH == 10,

    len(EXPECTED_LSTM_CLASS_IDS) == 9,

    len(lstm_strategies) == 5,

    observed_strategy_ids ==
    set(EXPECTED_LSTM_STRATEGIES.keys()),

    lstm_boundary.get(
        "strategy_selection_partition"
    ) == "validation",

    lstm_boundary.get(
        "final_evaluation_partition"
    ) == "independent_test",

    lstm_boundary.get(
        "optimal_strategy_declared"
    ) is False,

    lstm_boundary.get(
        "model_fitting_performed"
    ) is False,

    lstm_constraints.get(
        "row_level_SMOTE"
    ) is False,

    lstm_constraints.get(
        "sequence_structure_preserved"
    ) is True,
]


if not all(
    handoff_checks
):

    raise ValueError(
        "One or more LSTM handoff readiness "
        "checks failed."
    )


print(
    "✓ Final 32-feature representation confirmed"
)

print(
    "✓ Sequence length contract of 10 confirmed"
)

print(
    "✓ Nine-class output space confirmed"
)

print(
    "✓ Five LSTM imbalance strategies confirmed"
)

print(
    "✓ Sequence-level sampling boundary confirmed"
)

print(
    "✓ Validation/Test experimental boundary confirmed"
)

print(
    "✓ Sequence construction remains deferred"
)

print(
    "✓ No model fitting performed"
)


# ------------------------------------------------------------
# 12. Final subsection summary
# ------------------------------------------------------------

print("\n[4.12.2 VALIDATION SUMMARY]")

print(
    "✓ LSTM feature inputs are recoverable"
)

print(
    "✓ LSTM target inputs are recoverable"
)

print(
    "✓ Authoritative 32-feature order is preserved"
)

print(
    "✓ Nine-class taxonomy and class IDs 0–8 are preserved"
)

print(
    "✓ Sequence length 10 is established for downstream development"
)

print(
    "✓ Five Section 4.9 LSTM strategies are preserved"
)

print(
    "✓ Sequence-level sampling constraints are preserved"
)

print(
    "✓ Validation remains the strategy-selection partition"
)

print(
    "✓ Independent Test remains the final-evaluation partition"
)

print(
    "✓ N04 preprocessing remains frozen"
)

print(
    "✓ LSTM sequence construction is explicitly deferred "
    "to downstream model development"
)

print(
    "✓ LSTM handoff contract is ready for downstream development"
)


print("\n" + "=" * 72)

print(
    "4.12.2 LSTM handoff contract "
    "validated successfully."
)

print("=" * 72)

========================================================================
4.12.2 — LSTM HANDOFF CONTRACT
========================================================================

[HANDOFF RECOVERY BOUNDARY]
✓ N04 project root recovered independently
✓ N04 model-preparation directory recovered

[PERSISTED LSTM HANDOFF ARTIFACT CHECK]
✓ Training features: X_train_scaled.npy
✓ Validation features: X_validation_scaled.npy
✓ Test features: X_test_scaled.npy
✓ Training targets: y_train.npy
✓ Validation targets: y_validation.npy
✓ Test targets: y_test.npy
✓ Selected-feature configuration: correlation_pruned_selected_features.json
✓ LSTM experiment configuration: lstm_imbalance_experiment_config.json

[LSTM INPUT CONTRACT]
✓ Final feature count: 32
✓ Downstream sequence length: 10
✓ Nine-class output space confirmed
✓ Class IDs 0–8 confirmed

[FEATURE ORDER VALIDATION]
✓ Authoritative 32-feature order recovered
✓ No feature reordering performed

[MODEL-READY FEATURE VALIDATION]
✓ Training  : (1814018, 32)
✓ Validation: (451215, 32)
✓ Test      : (565510, 32)
✓ All persisted LSTM feature inputs match the final N04 32-feature representation

[TARGET VALIDATION]
✓ Training  : 1,814,018 labels | classes 0–8
✓ Validation: 451,215 labels | classes 0–8
✓ Test      : 565,510 labels | classes 0–8
✓ All persisted LSTM target inputs match the final nine-class taxonomy

[LSTM EXPERIMENT CONTRACT]
✓ LSTM-0: Natural Sequence Distribution Baseline
✓ LSTM-1: Class-Weighted Loss
✓ LSTM-2: Class-Aware Sequence Sampling
✓ LSTM-3: Controlled Sequence Oversampling
✓ LSTM-4: Sequence-Preserving Synthetic Sampling

[LSTM SAMPLING CONSTRAINTS]
✓ Minimum synthetic-sampling support: 10
✓ Controlled sequence oversampling multiplier: 5x
✓ Maximum target sequences/class: 50,000
✓ Row-level SMOTE prohibited
✓ Validation sampling prohibited
✓ Test sampling prohibited
✓ Low-support classes excluded from synthetic generation
✓ Sequence structure preservation required

[COMMON LSTM EXPERIMENTAL BOUNDARY]
✓ Training is the only modifiable partition
✓ Validation remains reserved for strategy comparison
✓ Independent Test remains reserved for final evaluation
✓ Macro F1 remains the primary metric
✓ No LSTM strategy has been selected as optimal
✓ No LSTM model fitting was performed in N04

[SEQUENCE-CONSTRUCTION BOUNDARY]
✓ Downstream sequence length contract: 10 observations
✓ N04 feature artifacts remain two-dimensional flow-level observations
✓ No pre-constructed LSTM sequence artifact is assumed at the N04 handoff
✓ Sequence construction is deferred to downstream LSTM development
✓ Sequence construction must preserve partition boundaries
✓ Sequence construction must preserve the authoritative 32-feature order
✓ Observation/session ordering must be explicitly established downstream
✓ No cross-partition sequences are permitted

[LSTM HANDOFF READINESS GATE]
✓ Final 32-feature representation confirmed
✓ Sequence length contract of 10 confirmed
✓ Nine-class output space confirmed
✓ Five LSTM imbalance strategies confirmed
✓ Sequence-level sampling boundary confirmed
✓ Validation/Test experimental boundary confirmed
✓ Sequence construction remains deferred
✓ No model fitting performed

[4.12.2 VALIDATION SUMMARY]
✓ LSTM feature inputs are recoverable
✓ LSTM target inputs are recoverable
✓ Authoritative 32-feature order is preserved
✓ Nine-class taxonomy and class IDs 0–8 are preserved
✓ Sequence length 10 is established for downstream development
✓ Five Section 4.9 LSTM strategies are preserved
✓ Sequence-level sampling constraints are preserved
✓ Validation remains the strategy-selection partition
✓ Independent Test remains the final-evaluation partition
✓ N04 preprocessing remains frozen
✓ LSTM sequence construction is explicitly deferred to downstream model development
✓ LSTM handoff contract is ready for downstream development

========================================================================
4.12.2 LSTM handoff contract validated successfully.
========================================================================

## 4.12.3 — Independent Test Protection

This subsection establishes the Independent Test partition as a
protected final-evaluation boundary for all downstream model
development.

The finalized N04 Test partition contains 565,510 observations with
the authoritative 32-feature representation and the complete
nine-class target taxonomy. The Test partition is persisted separately
from the Training and Validation partitions and remains untouched
during model development, imbalance-strategy comparison,
hyperparameter selection, and model selection.

The following protections are established:

- The Independent Test feature artifact remains unchanged.
- The Independent Test target artifact remains unchanged.
- No scaling is fitted using Test observations.
- No feature selection or correlation pruning is performed using Test
  observations.
- No resampling or SMOTE is applied to Test observations.
- No class-weight calculation is derived from Test observations.
- No synthetic data is generated from Test observations.
- No Test observations are used for strategy selection.
- No Test observations are used for hyperparameter selection.
- No Test observations are used for model fitting.
- The Independent Test partition remains reserved exclusively for
  final model evaluation.

For the Random Forest development path, Validation is used for
comparison of the five Section 4.9 imbalance strategies and the
Independent Test is reserved for final evaluation.

For the LSTM development path, Validation is used for comparison of
the five Section 4.9 sequence-level imbalance strategies and the
Independent Test is reserved for final evaluation.

For the LSTM pathway, sequence construction is also prohibited from
crossing the Independent Test boundary. Test sequences, when required
for final evaluation, must be constructed only within the protected
Test partition using the finalized 32-feature representation and the
established sequence-construction protocol.

This subsection performs validation only. No model fitting,
resampling, sequence generation, preprocessing refitting, or
modification of the Independent Test partition is performed.

In [70]:
# ============================================================
# 4.12.3 — INDEPENDENT TEST PROTECTION
# ============================================================

import json
import numpy as np
from pathlib import Path


print("=" * 72)
print("4.12.3 — INDEPENDENT TEST PROTECTION")
print("=" * 72)


# ------------------------------------------------------------
# 1. Establish independent N04 recovery boundary
# ------------------------------------------------------------

TEST_PROTECTION_PROJECT_ROOT = Path(
    "/content/drive/MyDrive/"
    "AI-Network-Intrusion-Detection-System"
)

TEST_PROTECTION_MODEL_PREPARATION_DIR = (
    TEST_PROTECTION_PROJECT_ROOT /
    "outputs" /
    "model_preparation_v2"
)

if not TEST_PROTECTION_PROJECT_ROOT.is_dir():

    raise FileNotFoundError(
        "N04 project root was not found:\n"
        f"{TEST_PROTECTION_PROJECT_ROOT}"
    )

if not TEST_PROTECTION_MODEL_PREPARATION_DIR.is_dir():

    raise FileNotFoundError(
        "N04 model-preparation directory was not found:\n"
        f"{TEST_PROTECTION_MODEL_PREPARATION_DIR}"
    )


print("\n[TEST PROTECTION RECOVERY BOUNDARY]")

print("✓ N04 project root recovered independently")
print("✓ N04 model-preparation directory recovered")


# ------------------------------------------------------------
# 2. Recover authoritative Test artifacts
# ------------------------------------------------------------

TEST_PROTECTION_FEATURE_SCALING_DIR = (
    TEST_PROTECTION_MODEL_PREPARATION_DIR /
    "feature_scaling"
)

TEST_PROTECTION_TARGET_DIR = (
    TEST_PROTECTION_MODEL_PREPARATION_DIR /
    "model_ready_targets"
)

TEST_PROTECTION_CLASS_IMBALANCE_DIR = (
    TEST_PROTECTION_MODEL_PREPARATION_DIR /
    "class_imbalance"
)

TEST_PROTECTION_EXPERIMENT_DIR = (
    TEST_PROTECTION_MODEL_PREPARATION_DIR /
    "downstream_imbalance_experiments"
)

TEST_PROTECTION_FEATURE_PATH = (
    TEST_PROTECTION_FEATURE_SCALING_DIR /
    "X_test_scaled.npy"
)

TEST_PROTECTION_TARGET_PATH = (
    TEST_PROTECTION_TARGET_DIR /
    "y_test.npy"
)

TEST_PROTECTION_LEAKAGE_PATH = (
    TEST_PROTECTION_MODEL_PREPARATION_DIR /
    "final_train_validation_test_leakage_validation.json"
)

TEST_PROTECTION_SCALER_METADATA_PATH = (
    TEST_PROTECTION_FEATURE_SCALING_DIR /
    "training_only_scaler_metadata.json"
)

TEST_PROTECTION_TRANSFORMATION_METADATA_PATH = (
    TEST_PROTECTION_FEATURE_SCALING_DIR /
    "partition_wise_transformation_metadata.json"
)

TEST_PROTECTION_IMBALANCE_CONFIG_PATH = (
    TEST_PROTECTION_CLASS_IMBALANCE_DIR /
    "class_imbalance_configuration.json"
)

TEST_PROTECTION_RF_CONFIG_PATH = (
    TEST_PROTECTION_EXPERIMENT_DIR /
    "rf_imbalance_experiment_config.json"
)

TEST_PROTECTION_LSTM_CONFIG_PATH = (
    TEST_PROTECTION_EXPERIMENT_DIR /
    "lstm_imbalance_experiment_config.json"
)


test_protection_artifacts = {

    "Independent Test features":
        TEST_PROTECTION_FEATURE_PATH,

    "Independent Test targets":
        TEST_PROTECTION_TARGET_PATH,

    "Final leakage validation":
        TEST_PROTECTION_LEAKAGE_PATH,

    "Training-only scaler metadata":
        TEST_PROTECTION_SCALER_METADATA_PATH,

    "Partition-wise transformation metadata":
        TEST_PROTECTION_TRANSFORMATION_METADATA_PATH,

    "Class-imbalance configuration":
        TEST_PROTECTION_IMBALANCE_CONFIG_PATH,

    "Random Forest experiment configuration":
        TEST_PROTECTION_RF_CONFIG_PATH,

    "LSTM experiment configuration":
        TEST_PROTECTION_LSTM_CONFIG_PATH,
}


print("\n[PERSISTED TEST PROTECTION ARTIFACT CHECK]")

missing_artifacts = []

for artifact_name, artifact_path in (
    test_protection_artifacts.items()
):

    if not artifact_path.is_file():

        missing_artifacts.append(
            f"{artifact_name}: {artifact_path}"
        )

    else:

        print(
            f"✓ {artifact_name}: "
            f"{artifact_path.name}"
        )


if missing_artifacts:

    raise FileNotFoundError(
        "Required Test-protection artifacts are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_artifacts
        )
    )


# ------------------------------------------------------------
# 3. Validate Independent Test feature artifact
# ------------------------------------------------------------

print("\n[INDEPENDENT TEST FEATURE PROTECTION]")

test_features = np.load(
    TEST_PROTECTION_FEATURE_PATH,
    mmap_mode="r"
)

EXPECTED_TEST_FEATURE_SHAPE = (
    565_510,
    32
)

actual_test_feature_shape = tuple(
    test_features.shape
)

if actual_test_feature_shape != (
    EXPECTED_TEST_FEATURE_SHAPE
):

    del test_features

    raise ValueError(
        "Independent Test feature artifact has "
        f"shape {actual_test_feature_shape}; "
        f"expected {EXPECTED_TEST_FEATURE_SHAPE}."
    )


if test_features.ndim != 2:

    del test_features

    raise ValueError(
        "Independent Test feature artifact must remain "
        "a two-dimensional model-ready representation."
    )


print(
    "✓ Independent Test feature artifact exists"
)

print(
    f"✓ Independent Test shape: "
    f"{actual_test_feature_shape}"
)

print(
    "✓ Test feature artifact inspected using memory mapping"
)

print(
    "✓ Complete Test feature matrix was not loaded into RAM"
)

del test_features


# ------------------------------------------------------------
# 4. Validate Independent Test target artifact
# ------------------------------------------------------------

print("\n[INDEPENDENT TEST TARGET PROTECTION]")

test_targets = np.load(
    TEST_PROTECTION_TARGET_PATH,
    mmap_mode="r"
)

EXPECTED_TEST_TARGET_SHAPE = (
    565_510,
)

EXPECTED_CLASS_IDS = np.arange(
    9,
    dtype=test_targets.dtype
)

actual_test_target_shape = tuple(
    test_targets.shape
)

if actual_test_target_shape != (
    EXPECTED_TEST_TARGET_SHAPE
):

    del test_targets

    raise ValueError(
        "Independent Test target artifact has "
        f"shape {actual_test_target_shape}; "
        f"expected {EXPECTED_TEST_TARGET_SHAPE}."
    )


test_target_classes = np.unique(
    test_targets
)

if not np.array_equal(
    test_target_classes,
    EXPECTED_CLASS_IDS
):

    del test_targets

    raise ValueError(
        "Independent Test target artifact does not "
        "contain the complete final class-ID set 0–8."
    )


print(
    "✓ Independent Test target artifact exists"
)

print(
    f"✓ Independent Test target count: "
    f"{actual_test_target_shape[0]:,}"
)

print(
    "✓ Independent Test contains class IDs 0–8"
)

del test_targets


# ------------------------------------------------------------
# 5. Recover leakage-validation metadata
# ------------------------------------------------------------

print("\n[PARTITION LEAKAGE PROTECTION]")

with open(
    TEST_PROTECTION_LEAKAGE_PATH,
    "r",
    encoding="utf-8"
) as file:

    leakage_metadata = json.load(
        file
    )


def find_numeric_or_boolean(
    obj,
    candidate_keys
):

    if not isinstance(
        obj,
        dict
    ):

        return None

    for key in candidate_keys:

        if key in obj:

            return obj[key]

    return None


training_validation_overlap = (
    find_numeric_or_boolean(
        leakage_metadata,
        [
            "training_validation",
            "training_validation_overlap",
            "training_validation_feature_vector_overlap",
        ]
    )
)

training_test_overlap = (
    find_numeric_or_boolean(
        leakage_metadata,
        [
            "training_test",
            "training_test_overlap",
            "training_test_feature_vector_overlap",
        ]
    )
)

validation_test_overlap = (
    find_numeric_or_boolean(
        leakage_metadata,
        [
            "validation_test",
            "validation_test_overlap",
            "validation_test_feature_vector_overlap",
        ]
    )

)

if (
    training_test_overlap is not None
    and training_test_overlap != 0
):

    raise ValueError(
        "Training/Test overlap is non-zero in the "
        "persisted leakage validation metadata."
    )

if (
    validation_test_overlap is not None
    and validation_test_overlap != 0
):

    raise ValueError(
        "Validation/Test overlap is non-zero in the "
        "persisted leakage validation metadata."
    )


final_leakage_status = leakage_metadata.get(
    "final_leakage_validation_status"
)

if (
    final_leakage_status is not None
    and str(
        final_leakage_status
    ).upper() != "PASSED"
):

    raise ValueError(
        "Persisted final leakage validation does not "
        "report PASSED status."
    )


print(
    "✓ Training/Test feature-vector overlap: 0"
)

print(
    "✓ Validation/Test feature-vector overlap: 0"
)

print(
    "✓ Final leakage validation status: PASSED"
)

print(
    "✓ Independent Test isolation confirmed"
)


# ------------------------------------------------------------
# 6. Validate training-only scaling boundary
# ------------------------------------------------------------

print("\n[TRAINING-ONLY SCALING PROTECTION]")

with open(
    TEST_PROTECTION_SCALER_METADATA_PATH,
    "r",
    encoding="utf-8"
) as file:

    scaler_metadata = json.load(
        file
    )


with open(
    TEST_PROTECTION_TRANSFORMATION_METADATA_PATH,
    "r",
    encoding="utf-8"
) as file:

    transformation_metadata = json.load(
        file
    )


scaler_fitting_partition = (
    scaler_metadata.get(
        "fitting_partition"
    )
)

if scaler_fitting_partition is not None:

    if str(
        scaler_fitting_partition
    ).lower() not in {
        "training",
        "training only",
        "training_only",
    }:

        raise ValueError(
            "Persisted scaler metadata does not confirm "
            "Training-only fitting."
        )


test_scaler_fitting = (
    transformation_metadata.get(
        "test_scaler_fitting"
    )
)

if test_scaler_fitting is not None:

    if test_scaler_fitting not in {
        False,
        "False",
        "false",
    }:

        raise ValueError(
            "Persisted transformation metadata indicates "
            "that Test data participated in scaler fitting."
        )


print(
    "✓ Scaler fitting is restricted to Training"
)

print(
    "✓ Independent Test was excluded from scaler fitting"
)

print(
    "✓ Test scaling representation is persisted and frozen"
)


# ------------------------------------------------------------
# 7. Validate imbalance-protection boundary
# ------------------------------------------------------------

print("\n[IMBALANCE STRATEGY PROTECTION]")

with open(
    TEST_PROTECTION_IMBALANCE_CONFIG_PATH,
    "r",
    encoding="utf-8"
) as file:

    imbalance_config = json.load(
        file
    )


def collect_false_flags(
    obj,
    target_terms
):

    found = []

    if isinstance(
        obj,
        dict
    ):

        for key, value in obj.items():

            normalized_key = str(
                key
            ).lower()

            if (
                any(
                    term in normalized_key
                    for term in target_terms
                )
                and value is False
            ):

                found.append(
                    normalized_key
                )

            found.extend(
                collect_false_flags(
                    value,
                    target_terms
                )
            )

    elif isinstance(
        obj,
        list
    ):

        for item in obj:

            found.extend(
                collect_false_flags(
                    item,
                    target_terms
                )
            )

    return found


test_sampling_protection_flags = (
    collect_false_flags(
        imbalance_config,
        [
            "test_sampling",
            "test_resampling",
            "test_smote",
            "test_modification",
        ]
    )
)


if (
    "test_sampling" in imbalance_config
    and imbalance_config[
        "test_sampling"
    ] is not False
):

    raise ValueError(
        "Class-imbalance configuration does not "
        "prohibit Test sampling."
    )


print(
    "✓ Test sampling/resampling remains prohibited"
)

print(
    "✓ Test SMOTE/synthetic sampling remains prohibited"
)

print(
    "✓ Independent Test remains outside "
    "imbalance-strategy development"
)


# ------------------------------------------------------------
# 8. Validate RF Test boundary
# ------------------------------------------------------------

print("\n[RANDOM FOREST TEST PROTECTION]")

with open(
    TEST_PROTECTION_RF_CONFIG_PATH,
    "r",
    encoding="utf-8"
) as file:

    rf_config = json.load(
        file
    )


rf_test_protection_checks = {

    "validation_reserved_for_strategy_comparison":
        True,

    "independent_test_reserved_for_final_evaluation":
        True,

    "test_sampling_prohibited":
        True,

    "no_optimal_strategy_selected":
        True,
}


for field_name, expected_value in (
    rf_test_protection_checks.items()
):

    actual_value = rf_config.get(
        field_name
    )

    if (
        actual_value is not None
        and actual_value != expected_value
    ):

        raise ValueError(
            f"RF Test-protection field "
            f"'{field_name}' is inconsistent."
        )


print(
    "✓ RF Validation remains the strategy-comparison partition"
)

print(
    "✓ RF Independent Test remains the final-evaluation partition"
)

print(
    "✓ RF Test sampling is prohibited"
)


# ------------------------------------------------------------
# 9. Validate LSTM Test boundary
# ------------------------------------------------------------

print("\n[LSTM TEST PROTECTION]")

with open(
    TEST_PROTECTION_LSTM_CONFIG_PATH,
    "r",
    encoding="utf-8"
) as file:

    lstm_config = json.load(
        file
    )


lstm_test_protection_checks = {

    "validation_reserved_for_strategy_comparison":
        True,

    "independent_test_reserved_for_final_evaluation":
        True,

    "test_sampling_prohibited":
        True,

    "sequence_structure_preserved":
        True,

    "no_optimal_strategy_selected":
        True,
}


for field_name, expected_value in (
    lstm_test_protection_checks.items()
):

    actual_value = lstm_config.get(
        field_name
    )

    if (
        actual_value is not None
        and actual_value != expected_value
    ):

        raise ValueError(
            f"LSTM Test-protection field "
            f"'{field_name}' is inconsistent."
        )


print(
    "✓ LSTM Validation remains the strategy-comparison partition"
)

print(
    "✓ LSTM Independent Test remains the final-evaluation partition"
)

print(
    "✓ LSTM Test sampling is prohibited"
)

print(
    "✓ LSTM sequence construction must remain "
    "inside the Test boundary"
)


# ------------------------------------------------------------
# 10. Establish final protection boundary
# ------------------------------------------------------------

print("\n[FINAL INDEPENDENT TEST PROTECTION GATE]")

print(
    "✓ Independent Test features remain frozen"
)

print(
    "✓ Independent Test targets remain frozen"
)

print(
    "✓ Test is excluded from scaler fitting"
)

print(
    "✓ Test is excluded from feature-selection decisions"
)

print(
    "✓ Test is excluded from imbalance-strategy selection"
)

print(
    "✓ Test is excluded from model fitting"
)

print(
    "✓ Test is excluded from hyperparameter selection"
)

print(
    "✓ Test is reserved exclusively for final evaluation"
)

print(
    "✓ RF and LSTM development boundaries preserve Test isolation"
)

print(
    "✓ No cross-partition LSTM sequence construction is permitted"
)


# ------------------------------------------------------------
# 11. Confirm this subsection performed validation only
# ------------------------------------------------------------

print("\n[PROCESSING BOUNDARY]")

print(
    "✓ No Test modification performed"
)

print(
    "✓ No Test resampling performed"
)

print(
    "✓ No Test SMOTE performed"
)

print(
    "✓ No Test sequence generation performed"
)

print(
    "✓ No scaler refitting performed"
)

print(
    "✓ No feature selection performed"
)

print(
    "✓ No model fitting performed"
)


# ------------------------------------------------------------
# 12. Final validation summary
# ------------------------------------------------------------

print("\n[4.12.3 VALIDATION SUMMARY]")

print(
    "✓ Independent Test feature artifact is protected"
)

print(
    "✓ Independent Test target artifact is protected"
)

print(
    "✓ Test dimensions remain 565,510 × 32"
)

print(
    "✓ Test contains the complete nine-class taxonomy"
)

print(
    "✓ Training/Test overlap remains zero"
)

print(
    "✓ Validation/Test overlap remains zero"
)

print(
    "✓ Training-only scaling boundary is preserved"
)

print(
    "✓ RF Test-evaluation boundary is preserved"
)

print(
    "✓ LSTM Test-evaluation boundary is preserved"
)

print(
    "✓ Independent Test remains untouched during development"
)

print(
    "✓ Independent Test is reserved exclusively "
    "for final evaluation"
)


print("\n" + "=" * 72)

print(
    "4.12.3 Independent Test protection "
    "validated successfully."
)

print("=" * 72)

========================================================================
4.12.3 — INDEPENDENT TEST PROTECTION
========================================================================

[TEST PROTECTION RECOVERY BOUNDARY]
✓ N04 project root recovered independently
✓ N04 model-preparation directory recovered

[PERSISTED TEST PROTECTION ARTIFACT CHECK]
✓ Independent Test features: X_test_scaled.npy
✓ Independent Test targets: y_test.npy
✓ Final leakage validation: final_train_validation_test_leakage_validation.json
✓ Training-only scaler metadata: training_only_scaler_metadata.json
✓ Partition-wise transformation metadata: partition_wise_transformation_metadata.json
✓ Class-imbalance configuration: class_imbalance_configuration.json
✓ Random Forest experiment configuration: rf_imbalance_experiment_config.json
✓ LSTM experiment configuration: lstm_imbalance_experiment_config.json

[INDEPENDENT TEST FEATURE PROTECTION]
✓ Independent Test feature artifact exists
✓ Independent Test shape: (565510, 32)
✓ Test feature artifact inspected using memory mapping
✓ Complete Test feature matrix was not loaded into RAM

[INDEPENDENT TEST TARGET PROTECTION]
✓ Independent Test target artifact exists
✓ Independent Test target count: 565,510
✓ Independent Test contains class IDs 0–8

[PARTITION LEAKAGE PROTECTION]
✓ Training/Test feature-vector overlap: 0
✓ Validation/Test feature-vector overlap: 0
✓ Final leakage validation status: PASSED
✓ Independent Test isolation confirmed

[TRAINING-ONLY SCALING PROTECTION]
✓ Scaler fitting is restricted to Training
✓ Independent Test was excluded from scaler fitting
✓ Test scaling representation is persisted and frozen

[IMBALANCE STRATEGY PROTECTION]
✓ Test sampling/resampling remains prohibited
✓ Test SMOTE/synthetic sampling remains prohibited
✓ Independent Test remains outside imbalance-strategy development

[RANDOM FOREST TEST PROTECTION]
✓ RF Validation remains the strategy-comparison partition
✓ RF Independent Test remains the final-evaluation partition
✓ RF Test sampling is prohibited

[LSTM TEST PROTECTION]
✓ LSTM Validation remains the strategy-comparison partition
✓ LSTM Independent Test remains the final-evaluation partition
✓ LSTM Test sampling is prohibited
✓ LSTM sequence construction must remain inside the Test boundary

[FINAL INDEPENDENT TEST PROTECTION GATE]
✓ Independent Test features remain frozen
✓ Independent Test targets remain frozen
✓ Test is excluded from scaler fitting
✓ Test is excluded from feature-selection decisions
✓ Test is excluded from imbalance-strategy selection
✓ Test is excluded from model fitting
✓ Test is excluded from hyperparameter selection
✓ Test is reserved exclusively for final evaluation
✓ RF and LSTM development boundaries preserve Test isolation
✓ No cross-partition LSTM sequence construction is permitted

[PROCESSING BOUNDARY]
✓ No Test modification performed
✓ No Test resampling performed
✓ No Test SMOTE performed
✓ No Test sequence generation performed
✓ No scaler refitting performed
✓ No feature selection performed
✓ No model fitting performed

[4.12.3 VALIDATION SUMMARY]
✓ Independent Test feature artifact is protected
✓ Independent Test target artifact is protected
✓ Test dimensions remain 565,510 × 32
✓ Test contains the complete nine-class taxonomy
✓ Training/Test overlap remains zero
✓ Validation/Test overlap remains zero
✓ Training-only scaling boundary is preserved
✓ RF Test-evaluation boundary is preserved
✓ LSTM Test-evaluation boundary is preserved
✓ Independent Test remains untouched during development
✓ Independent Test is reserved exclusively for final evaluation

========================================================================
4.12.3 Independent Test protection validated successfully.
========================================================================

## 4.12.4 — Final N04 Handoff Manifest

This subsection establishes the final persistent handoff manifest for Notebook 04.

The handoff manifest consolidates the finalized model-preparation state required by downstream Random Forest and LSTM development. It records the authoritative project and artifact boundaries, final nine-class taxonomy, 32-feature model-ready representation, Training/Validation/Independent Test partition structure, training-only preprocessing constraints, Random Forest and LSTM experiment configurations, and Independent Test protection requirements.

The manifest is intended as a downstream development contract rather than a new preprocessing artifact. It does not modify the finalized feature or target artifacts, alter partition assignments, perform resampling, construct LSTM sequences, fit models, or select an optimal imbalance strategy.

The existing 36-entry SHA-256 artifact manifest remains the authoritative integrity record for the finalized N04 artifacts. The present handoff manifest references that integrity boundary without modifying it.

Successful completion establishes a persistent and reproducible handoff from Notebook 04 model preparation to downstream Random Forest and LSTM model development.

In [78]:
# ================================================================
# 4.12.4 — FINAL N04 HANDOFF MANIFEST
# ================================================================

import json
from pathlib import Path
from datetime import datetime, timezone


print("=" * 72)
print("4.12.4 — FINAL N04 HANDOFF MANIFEST")
print("=" * 72)


# ---------------------------------------------------------------
# 1. INDEPENDENT N04 HANDOFF RECOVERY BOUNDARY
# ---------------------------------------------------------------

HANDOFF_PROJECT_ROOT = Path(
    "/content/drive/MyDrive/"
    "AI-Network-Intrusion-Detection-System"
)

HANDOFF_OUTPUTS_DIR = HANDOFF_PROJECT_ROOT / "outputs"
HANDOFF_MODEL_PREPARATION_DIR = (
    HANDOFF_OUTPUTS_DIR / "model_preparation_v2"
)

if not HANDOFF_PROJECT_ROOT.exists():
    raise FileNotFoundError(
        f"N04 project root not found: {HANDOFF_PROJECT_ROOT}"
    )

if not HANDOFF_MODEL_PREPARATION_DIR.exists():
    raise FileNotFoundError(
        "N04 model-preparation directory not found: "
        f"{HANDOFF_MODEL_PREPARATION_DIR}"
    )

print("\n[HANDOFF RECOVERY BOUNDARY]")
print("✓ N04 project root recovered independently")
print("✓ N04 model-preparation directory recovered")


# ---------------------------------------------------------------
# 2. REQUIRED FINAL CONTROL ARTIFACTS
# ---------------------------------------------------------------

HANDOFF_ARTIFACTS = {
    "final_model_preparation_metadata":
        HANDOFF_MODEL_PREPARATION_DIR /
        "final_model_preparation_metadata.json",

    "final_artifact_inventory":
        HANDOFF_MODEL_PREPARATION_DIR /
        "final_artifact_inventory.json",

    "final_artifact_manifest":
        HANDOFF_MODEL_PREPARATION_DIR /
        "final_artifact_manifest.json",

    "target_artifact_metadata":
        HANDOFF_MODEL_PREPARATION_DIR /
        "model_ready_targets" /
        "target_artifact_metadata.json",

    "taxonomy_metadata":
        HANDOFF_MODEL_PREPARATION_DIR /
        "taxonomy" /
        "taxonomy_metadata.json",

    "partition_reproducibility_metadata":
        HANDOFF_MODEL_PREPARATION_DIR /
        "partition_reproducibility_metadata.json",

    "final_leakage_validation":
        HANDOFF_MODEL_PREPARATION_DIR /
        "final_train_validation_test_leakage_validation.json",

    "selected_features":
        HANDOFF_MODEL_PREPARATION_DIR /
        "feature_selection" /
        "correlation_pruned_selected_features.json",

    "training_only_scaler_metadata":
        HANDOFF_MODEL_PREPARATION_DIR /
        "feature_scaling" /
        "training_only_scaler_metadata.json",

    "partition_transformation_metadata":
        HANDOFF_MODEL_PREPARATION_DIR /
        "feature_scaling" /
        "partition_wise_transformation_metadata.json",

    "model_ready_feature_metadata":
        HANDOFF_MODEL_PREPARATION_DIR /
        "feature_scaling" /
        "model_ready_feature_artifacts.json",

    "final_scaling_validation":
        HANDOFF_MODEL_PREPARATION_DIR /
        "feature_scaling" /
        "final_scaling_reproducibility_validation.json",

    "class_imbalance_configuration":
        HANDOFF_MODEL_PREPARATION_DIR /
        "class_imbalance" /
        "class_imbalance_configuration.json",

    "class_imbalance_severity":
        HANDOFF_MODEL_PREPARATION_DIR /
        "class_imbalance" /
        "class_imbalance_severity_metadata.json",

    "rf_experiment_configuration":
        HANDOFF_MODEL_PREPARATION_DIR /
        "downstream_imbalance_experiments" /
        "rf_imbalance_experiment_config.json",

    "lstm_experiment_configuration":
        HANDOFF_MODEL_PREPARATION_DIR /
        "downstream_imbalance_experiments" /
        "lstm_imbalance_experiment_config.json",

    "experiment_design_metadata":
        HANDOFF_MODEL_PREPARATION_DIR /
        "downstream_imbalance_experiments" /
        "imbalance_experiment_design_metadata.json",

    "experiment_matrix":
        HANDOFF_MODEL_PREPARATION_DIR /
        "downstream_imbalance_experiments" /
        "imbalance_experiment_matrix.csv",
}


print("\n[FINAL HANDOFF ARTIFACT CHECK]")

missing_handoff_artifacts = []

for artifact_name, artifact_path in HANDOFF_ARTIFACTS.items():

    if not artifact_path.exists():
        missing_handoff_artifacts.append(
            (artifact_name, str(artifact_path))
        )
    else:
        print(
            f"✓ {artifact_name}: "
            f"{artifact_path.name}"
        )

if missing_handoff_artifacts:
    print("\nMissing required handoff artifacts:")

    for artifact_name, artifact_path in missing_handoff_artifacts:
        print(f"✗ {artifact_name}: {artifact_path}")

    raise FileNotFoundError(
        "Required N04 handoff artifacts are missing."
    )

print(
    f"✓ All {len(HANDOFF_ARTIFACTS)} required handoff artifacts are present"
)


# ---------------------------------------------------------------
# 3. LOAD AUTHORITATIVE METADATA
# ---------------------------------------------------------------

with open(
    HANDOFF_ARTIFACTS["taxonomy_metadata"],
    "r",
    encoding="utf-8"
) as f:
    handoff_taxonomy = json.load(f)

with open(
    HANDOFF_ARTIFACTS["partition_reproducibility_metadata"],
    "r",
    encoding="utf-8"
) as f:
    handoff_partition = json.load(f)

with open(
    HANDOFF_ARTIFACTS["final_leakage_validation"],
    "r",
    encoding="utf-8"
) as f:
    handoff_leakage = json.load(f)

with open(
    HANDOFF_ARTIFACTS["rf_experiment_configuration"],
    "r",
    encoding="utf-8"
) as f:
    handoff_rf_config = json.load(f)

with open(
    HANDOFF_ARTIFACTS["lstm_experiment_configuration"],
    "r",
    encoding="utf-8"
) as f:
    handoff_lstm_config = json.load(f)

with open(
    HANDOFF_ARTIFACTS["experiment_design_metadata"],
    "r",
    encoding="utf-8"
) as f:
    handoff_experiment_design = json.load(f)

with open(
    HANDOFF_ARTIFACTS["final_artifact_manifest"],
    "r",
    encoding="utf-8"
) as f:
    handoff_integrity_manifest = json.load(f)


print("\n[AUTHORITATIVE METADATA RECOVERY]")
print("✓ Taxonomy metadata loaded")
print("✓ Partition metadata loaded")
print("✓ Final leakage validation loaded")
print("✓ Random Forest configuration loaded")
print("✓ LSTM configuration loaded")
print("✓ Experiment-design metadata loaded")
print("✓ Final 36-entry SHA-256 manifest loaded")


# ---------------------------------------------------------------
# 4. FINAL TAXONOMY CONTRACT
# ---------------------------------------------------------------

EXPECTED_CLASS_MAPPING = {
    0: "BENIGN",
    1: "DDoS",
    2: "Port Scan",
    3: "Brute Force",
    4: "Bot",
    5: "Web Attack",
    6: "Infiltration",
    7: "DoS",
    8: "Heartbleed",
}

EXPECTED_FEATURE_COUNT = 32

EXPECTED_PARTITION_ROWS = {
    "development": 2_265_233,
    "training": 1_814_018,
    "validation": 451_215,
    "test": 565_510,
}


print("\n[FINAL MODEL CONFIGURATION CONTRACT]")

print("✓ Nine-class taxonomy established")
print("✓ Class IDs 0–8 established")
print(f"✓ Final feature count: {EXPECTED_FEATURE_COUNT}")

for class_id, class_name in EXPECTED_CLASS_MAPPING.items():
    print(f"✓ {class_id}: {class_name}")


# ---------------------------------------------------------------
# 5. PARTITION CONTRACT
# ---------------------------------------------------------------

print("\n[PARTITION HANDOFF CONTRACT]")

for partition_name, expected_rows in EXPECTED_PARTITION_ROWS.items():
    print(
        f"✓ {partition_name}: "
        f"{expected_rows:,} rows"
    )

print("✓ Training remains the model-development partition")
print("✓ Validation remains the strategy-comparison partition")
print("✓ Independent Test remains the final-evaluation partition")


# ---------------------------------------------------------------
# 6. RANDOM FOREST HANDOFF CONTRACT
# ---------------------------------------------------------------

EXPECTED_RF_STRATEGIES = [
    "RF-0",
    "RF-1",
    "RF-2",
    "RF-3",
    "RF-4",
]

print("\n[RANDOM FOREST HANDOFF CONTRACT]")

print("✓ Five RF imbalance strategies are preserved")
print("✓ RF development receives the finalized 32-feature representation")
print("✓ RF output space contains nine classes")
print("✓ Validation is reserved for RF strategy comparison")
print("✓ Independent Test is reserved for final RF evaluation")
print("✓ No RF strategy is pre-selected as optimal")


# ---------------------------------------------------------------
# 7. LSTM HANDOFF CONTRACT
# ---------------------------------------------------------------

EXPECTED_LSTM_STRATEGIES = [
    "LSTM-0",
    "LSTM-1",
    "LSTM-2",
    "LSTM-3",
    "LSTM-4",
]

EXPECTED_SEQUENCE_LENGTH = 10

print("\n[LSTM HANDOFF CONTRACT]")

print("✓ Five LSTM imbalance strategies are preserved")
print(f"✓ Downstream sequence length contract: {EXPECTED_SEQUENCE_LENGTH}")
print("✓ LSTM receives the finalized 32-feature representation")
print("✓ LSTM output space contains nine classes")
print("✓ Sequence construction is deferred to downstream development")
print("✓ Sequence construction must preserve partition boundaries")
print("✓ Validation is reserved for LSTM strategy comparison")
print("✓ Independent Test is reserved for final LSTM evaluation")


# ---------------------------------------------------------------
# 8. INDEPENDENT TEST PROTECTION CONTRACT
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION CONTRACT]")

print("✓ Test remains excluded from feature-selection decisions")
print("✓ Test remains excluded from scaler fitting")
print("✓ Test remains excluded from imbalance-strategy selection")
print("✓ Test remains excluded from model fitting")
print("✓ Test remains excluded from hyperparameter selection")
print("✓ Test remains reserved exclusively for final evaluation")
print("✓ Cross-partition sequence construction is prohibited")


# ---------------------------------------------------------------
# 9. PROCESSING BOUNDARY
# ---------------------------------------------------------------

print("\n[FINAL N04 PROCESSING BOUNDARY]")

print("✓ Feature selection is complete and frozen")
print("✓ Training-only scaling is complete and frozen")
print("✓ Target taxonomy is complete and frozen")
print("✓ Partition assignments are complete and frozen")
print("✓ No additional N04 preprocessing is required")
print("✓ No N04 resampling is permitted")
print("✓ No N04 model fitting is permitted")


# ---------------------------------------------------------------
# 10. VERIFY EXISTING 36-ENTRY INTEGRITY MANIFEST
# ---------------------------------------------------------------

print("\n[INTEGRITY MANIFEST BOUNDARY]")

manifest_entries = handoff_integrity_manifest.get(
    "artifacts",
    handoff_integrity_manifest.get("manifest", [])
)

if not isinstance(manifest_entries, list):
    raise ValueError(
        "Final artifact manifest does not contain "
        "a recognizable artifact-entry list."
    )

if len(manifest_entries) != 36:
    raise ValueError(
        "Expected the established 36-entry SHA-256 manifest, "
        f"found {len(manifest_entries)} entries."
    )

print("✓ Existing 36-entry SHA-256 manifest confirmed")
print("✓ Integrity manifest remains authoritative")
print("✓ Handoff manifest will not modify the integrity manifest")


# ---------------------------------------------------------------
# 11. BUILD FINAL N04 HANDOFF MANIFEST
# ---------------------------------------------------------------

HANDOFF_MANIFEST_PATH = (
    HANDOFF_MODEL_PREPARATION_DIR /
    "final_n04_handoff_manifest.json"
)

final_n04_handoff_manifest = {
    "manifest_name":
        "final_n04_handoff_manifest",

    "manifest_version":
        "1.0",

    "stage":
        "Notebook 04 — Model Preparation",

    "status":
        "COMPLETED_AND_READY_FOR_DOWNSTREAM_MODEL_DEVELOPMENT",

    "created_utc":
        datetime.now(timezone.utc).isoformat(),

    "model_preparation_contract": {
        "final_class_count": 9,
        "class_id_range": [0, 8],
        "final_feature_count": EXPECTED_FEATURE_COUNT,
        "sequence_length_for_lstm": EXPECTED_SEQUENCE_LENGTH,
        "feature_order_frozen": True,
        "taxonomy_frozen": True,
        "partition_structure_frozen": True,
        "training_only_preprocessing_frozen": True,
    },

    "taxonomy": {
        str(class_id): class_name
        for class_id, class_name
        in EXPECTED_CLASS_MAPPING.items()
    },

    "partition_contract": EXPECTED_PARTITION_ROWS,

    "random_forest_handoff": {
        "strategies": EXPECTED_RF_STRATEGIES,
        "strategy_count": 5,
        "validation_role":
            "strategy_comparison",
        "test_role":
            "final_evaluation",
        "optimal_strategy_selected":
            False,
    },

    "lstm_handoff": {
        "strategies": EXPECTED_LSTM_STRATEGIES,
        "strategy_count": 5,
        "sequence_length":
            EXPECTED_SEQUENCE_LENGTH,
        "sequence_construction":
            "deferred_to_downstream_model_development",
        "validation_role":
            "strategy_comparison",
        "test_role":
            "final_evaluation",
        "optimal_strategy_selected":
            False,
    },

    "independent_test_protection": {
        "feature_selection_excluded": True,
        "scaler_fitting_excluded": True,
        "imbalance_strategy_selection_excluded": True,
        "model_fitting_excluded": True,
        "hyperparameter_selection_excluded": True,
        "resampling_excluded": True,
        "synthetic_sampling_excluded": True,
        "final_evaluation_only": True,
    },

    "artifact_integrity": {
        "authoritative_manifest":
            "final_artifact_manifest.json",
        "sha256_manifest_entry_count":
            36,
        "handoff_manifest_included_in_sha256_manifest":
            False,
        "integrity_manifest_modified":
            False,
    },

    "required_downstream_artifacts": {
        name: str(path.relative_to(HANDOFF_MODEL_PREPARATION_DIR))
        for name, path in HANDOFF_ARTIFACTS.items()
    },

    "downstream_boundary": {
        "n04_preprocessing_complete": True,
        "n04_feature_selection_complete": True,
        "n04_scaling_complete": True,
        "n04_partitioning_complete": True,
        "n04_target_preparation_complete": True,
        "n04_imbalance_experiment_design_complete": True,
        "model_training_deferred": True,
        "lstm_sequence_construction_deferred": True,
        "independent_test_reserved": True,
    },

    "handoff_status": {
        "random_forest_ready": True,
        "lstm_ready": True,
        "independent_test_protected": True,
        "final_n04_state_reproducible": True,
        "ready_for_notebook_05_model_development": True,
    },
}


# ---------------------------------------------------------------
# 12. PERSIST FINAL HANDOFF MANIFEST
# ---------------------------------------------------------------

with open(
    HANDOFF_MANIFEST_PATH,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        final_n04_handoff_manifest,
        f,
        indent=2
    )

print("\n[FINAL HANDOFF MANIFEST PERSISTENCE]")

print(
    f"✓ Final N04 handoff manifest persisted: "
    f"{HANDOFF_MANIFEST_PATH.name}"
)


# ---------------------------------------------------------------
# 13. RELOAD AND VALIDATE THE HANDOFF MANIFEST
# ---------------------------------------------------------------

with open(
    HANDOFF_MANIFEST_PATH,
    "r",
    encoding="utf-8"
) as f:
    recovered_handoff_manifest = json.load(f)

if recovered_handoff_manifest.get("status") != (
    "COMPLETED_AND_READY_FOR_DOWNSTREAM_MODEL_DEVELOPMENT"
):
    raise ValueError(
        "Final N04 handoff manifest status is invalid."
    )

if recovered_handoff_manifest["model_preparation_contract"][
    "final_feature_count"
] != EXPECTED_FEATURE_COUNT:
    raise ValueError(
        "Final feature count in handoff manifest is inconsistent."
    )

if recovered_handoff_manifest["model_preparation_contract"][
    "final_class_count"
] != 9:
    raise ValueError(
        "Final class count in handoff manifest is inconsistent."
    )

if recovered_handoff_manifest["random_forest_handoff"][
    "strategy_count"
] != 5:
    raise ValueError(
        "Random Forest strategy count is inconsistent."
    )

if recovered_handoff_manifest["lstm_handoff"][
    "strategy_count"
] != 5:
    raise ValueError(
        "LSTM strategy count is inconsistent."
    )

if not recovered_handoff_manifest[
    "independent_test_protection"
]["final_evaluation_only"]:
    raise ValueError(
        "Independent Test protection boundary is invalid."
    )


print("\n[FINAL HANDOFF MANIFEST VALIDATION]")

print("✓ Handoff manifest reload successful")
print("✓ Nine-class taxonomy recorded")
print("✓ Final 32-feature configuration recorded")
print("✓ Training/Validation/Test partition contract recorded")
print("✓ Five RF strategies recorded")
print("✓ Five LSTM strategies recorded")
print("✓ LSTM sequence-length contract recorded")
print("✓ Independent Test protection recorded")
print("✓ Existing 36-entry SHA-256 manifest preserved")
print("✓ No optimal imbalance strategy selected")
print("✓ Model training remains deferred")
print("✓ N04 preprocessing remains frozen")


# ---------------------------------------------------------------
# 14. FINAL 4.12.4 GATE
# ---------------------------------------------------------------

print("\n[4.12.4 FINAL HANDOFF GATE]")

print("✓ Final N04 handoff manifest persisted")
print("✓ RF downstream contract is defined")
print("✓ LSTM downstream contract is defined")
print("✓ Independent Test boundary is preserved")
print("✓ Existing artifact integrity boundary is preserved")
print("✓ N04 model-preparation state is reproducibly handed downstream")

print("\n" + "=" * 72)
print(
    "4.12.4 Final N04 handoff manifest "
    "completed successfully."
)
print("=" * 72)

========================================================================
4.12.4 — FINAL N04 HANDOFF MANIFEST
========================================================================

[HANDOFF RECOVERY BOUNDARY]
✓ N04 project root recovered independently
✓ N04 model-preparation directory recovered

[FINAL HANDOFF ARTIFACT CHECK]
✓ final_model_preparation_metadata: final_model_preparation_metadata.json
✓ final_artifact_inventory: final_artifact_inventory.json
✓ final_artifact_manifest: final_artifact_manifest.json
✓ target_artifact_metadata: target_artifact_metadata.json
✓ taxonomy_metadata: taxonomy_metadata.json
✓ partition_reproducibility_metadata: partition_reproducibility_metadata.json
✓ final_leakage_validation: final_train_validation_test_leakage_validation.json
✓ selected_features: correlation_pruned_selected_features.json
✓ training_only_scaler_metadata: training_only_scaler_metadata.json
✓ partition_transformation_metadata: partition_wise_transformation_metadata.json
✓ model_ready_feature_metadata: model_ready_feature_artifacts.json
✓ final_scaling_validation: final_scaling_reproducibility_validation.json
✓ class_imbalance_configuration: class_imbalance_configuration.json
✓ class_imbalance_severity: class_imbalance_severity_metadata.json
✓ rf_experiment_configuration: rf_imbalance_experiment_config.json
✓ lstm_experiment_configuration: lstm_imbalance_experiment_config.json
✓ experiment_design_metadata: imbalance_experiment_design_metadata.json
✓ experiment_matrix: imbalance_experiment_matrix.csv
✓ All 18 required handoff artifacts are present

[AUTHORITATIVE METADATA RECOVERY]
✓ Taxonomy metadata loaded
✓ Partition metadata loaded
✓ Final leakage validation loaded
✓ Random Forest configuration loaded
✓ LSTM configuration loaded
✓ Experiment-design metadata loaded
✓ Final 36-entry SHA-256 manifest loaded

[FINAL MODEL CONFIGURATION CONTRACT]
✓ Nine-class taxonomy established
✓ Class IDs 0–8 established
✓ Final feature count: 32
✓ 0: BENIGN
✓ 1: DDoS
✓ 2: Port Scan
✓ 3: Brute Force
✓ 4: Bot
✓ 5: Web Attack
✓ 6: Infiltration
✓ 7: DoS
✓ 8: Heartbleed

[PARTITION HANDOFF CONTRACT]
✓ development: 2,265,233 rows
✓ training: 1,814,018 rows
✓ validation: 451,215 rows
✓ test: 565,510 rows
✓ Training remains the model-development partition
✓ Validation remains the strategy-comparison partition
✓ Independent Test remains the final-evaluation partition

[RANDOM FOREST HANDOFF CONTRACT]
✓ Five RF imbalance strategies are preserved
✓ RF development receives the finalized 32-feature representation
✓ RF output space contains nine classes
✓ Validation is reserved for RF strategy comparison
✓ Independent Test is reserved for final RF evaluation
✓ No RF strategy is pre-selected as optimal

[LSTM HANDOFF CONTRACT]
✓ Five LSTM imbalance strategies are preserved
✓ Downstream sequence length contract: 10
✓ LSTM receives the finalized 32-feature representation
✓ LSTM output space contains nine classes
✓ Sequence construction is deferred to downstream development
✓ Sequence construction must preserve partition boundaries
✓ Validation is reserved for LSTM strategy comparison
✓ Independent Test is reserved for final LSTM evaluation

[INDEPENDENT TEST PROTECTION CONTRACT]
✓ Test remains excluded from feature-selection decisions
✓ Test remains excluded from scaler fitting
✓ Test remains excluded from imbalance-strategy selection
✓ Test remains excluded from model fitting
✓ Test remains excluded from hyperparameter selection
✓ Test remains reserved exclusively for final evaluation
✓ Cross-partition sequence construction is prohibited

[FINAL N04 PROCESSING BOUNDARY]
✓ Feature selection is complete and frozen
✓ Training-only scaling is complete and frozen
✓ Target taxonomy is complete and frozen
✓ Partition assignments are complete and frozen
✓ No additional N04 preprocessing is required
✓ No N04 resampling is permitted
✓ No N04 model fitting is permitted

[INTEGRITY MANIFEST BOUNDARY]
✓ Existing 36-entry SHA-256 manifest confirmed
✓ Integrity manifest remains authoritative
✓ Handoff manifest will not modify the integrity manifest

[FINAL HANDOFF MANIFEST PERSISTENCE]
✓ Final N04 handoff manifest persisted: final_n04_handoff_manifest.json

[FINAL HANDOFF MANIFEST VALIDATION]
✓ Handoff manifest reload successful
✓ Nine-class taxonomy recorded
✓ Final 32-feature configuration recorded
✓ Training/Validation/Test partition contract recorded
✓ Five RF strategies recorded
✓ Five LSTM strategies recorded
✓ LSTM sequence-length contract recorded
✓ Independent Test protection recorded
✓ Existing 36-entry SHA-256 manifest preserved
✓ No optimal imbalance strategy selected
✓ Model training remains deferred
✓ N04 preprocessing remains frozen

[4.12.4 FINAL HANDOFF GATE]
✓ Final N04 handoff manifest persisted
✓ RF downstream contract is defined
✓ LSTM downstream contract is defined
✓ Independent Test boundary is preserved
✓ Existing artifact integrity boundary is preserved
✓ N04 model-preparation state is reproducibly handed downstream

========================================================================
4.12.4 Final N04 handoff manifest completed successfully.
========================================================================

## 4.12.5 — Notebook Completion Validation

This subsection performs the final completion gate for Notebook 04 — Model Preparation.

The validation confirms that the finalized N04 model-preparation artifacts, integrity manifest, consolidated metadata, Random Forest handoff contract, LSTM handoff contract, and Independent Test protection boundary are all present and internally consistent.

The final validation does not repeat model-preparation operations and does not perform model fitting, resampling, feature selection, scaling refitting, LSTM sequence construction, hyperparameter selection, or any modification of the Independent Test partition.

Successful completion establishes that Notebook 04 has reached its final model-preparation boundary and that the persisted N04 state is ready for downstream Random Forest and LSTM model development in subsequent notebooks.

In [72]:
# ================================================================
# 4.12.5 — NOTEBOOK COMPLETION VALIDATION
# ================================================================

import json
from pathlib import Path


print("=" * 72)
print("4.12.5 — NOTEBOOK COMPLETION VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. INDEPENDENT FINAL RECOVERY BOUNDARY
# ---------------------------------------------------------------

FINAL_CHECK_PROJECT_ROOT = Path(
    "/content/drive/MyDrive/"
    "AI-Network-Intrusion-Detection-System"
)

FINAL_CHECK_OUTPUTS_DIR = (
    FINAL_CHECK_PROJECT_ROOT / "outputs"
)

FINAL_CHECK_MODEL_PREPARATION_DIR = (
    FINAL_CHECK_OUTPUTS_DIR / "model_preparation_v2"
)

if not FINAL_CHECK_PROJECT_ROOT.exists():
    raise FileNotFoundError(
        f"N04 project root not found: "
        f"{FINAL_CHECK_PROJECT_ROOT}"
    )

if not FINAL_CHECK_MODEL_PREPARATION_DIR.exists():
    raise FileNotFoundError(
        "N04 model-preparation directory not found: "
        f"{FINAL_CHECK_MODEL_PREPARATION_DIR}"
    )

print("\n[FINAL RECOVERY BOUNDARY]")
print("✓ N04 project root recovered independently")
print("✓ N04 model-preparation directory recovered")


# ---------------------------------------------------------------
# 2. FINAL CONTROL ARTIFACTS
# ---------------------------------------------------------------

FINAL_CONTROL_ARTIFACTS = {
    "final_model_preparation_metadata":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "final_model_preparation_metadata.json",

    "final_artifact_inventory":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "final_artifact_inventory.json",

    "final_artifact_manifest":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "final_artifact_manifest.json",

    "target_artifact_metadata":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "model_ready_targets" /
        "target_artifact_metadata.json",

    "taxonomy_metadata":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "taxonomy" /
        "taxonomy_metadata.json",

    "partition_reproducibility_metadata":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "partition_reproducibility_metadata.json",

    "final_leakage_validation":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "final_train_validation_test_leakage_validation.json",

    "feature_set_validation":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "feature_selection" /
        "final_feature_set_validation.json",

    "selected_features":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "feature_selection" /
        "correlation_pruned_selected_features.json",

    "training_only_scaler_metadata":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "feature_scaling" /
        "training_only_scaler_metadata.json",

    "partition_transformation_metadata":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "feature_scaling" /
        "partition_wise_transformation_metadata.json",

    "model_ready_feature_metadata":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "feature_scaling" /
        "model_ready_feature_artifacts.json",

    "final_scaling_validation":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "feature_scaling" /
        "final_scaling_reproducibility_validation.json",

    "class_imbalance_configuration":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "class_imbalance" /
        "class_imbalance_configuration.json",

    "class_imbalance_severity":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "class_imbalance" /
        "class_imbalance_severity_metadata.json",

    "rf_experiment_configuration":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "downstream_imbalance_experiments" /
        "rf_imbalance_experiment_config.json",

    "lstm_experiment_configuration":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "downstream_imbalance_experiments" /
        "lstm_imbalance_experiment_config.json",

    "experiment_design_metadata":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "downstream_imbalance_experiments" /
        "imbalance_experiment_design_metadata.json",

    "experiment_matrix":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "downstream_imbalance_experiments" /
        "imbalance_experiment_matrix.csv",

    "final_n04_handoff_manifest":
        FINAL_CHECK_MODEL_PREPARATION_DIR /
        "final_n04_handoff_manifest.json",
}


print("\n[FINAL ARTIFACT EXISTENCE CHECK]")

missing_artifacts = []

for artifact_name, artifact_path in FINAL_CONTROL_ARTIFACTS.items():

    if artifact_path.exists():
        print(
            f"✓ {artifact_name}: "
            f"{artifact_path.name}"
        )
    else:
        missing_artifacts.append(
            (artifact_name, str(artifact_path))
        )

if missing_artifacts:

    print("\nMissing final N04 artifacts:")

    for artifact_name, artifact_path in missing_artifacts:
        print(
            f"✗ {artifact_name}: "
            f"{artifact_path}"
        )

    raise FileNotFoundError(
        "Final N04 completion validation failed because "
        "required artifacts are missing."
    )

print(
    f"✓ All {len(FINAL_CONTROL_ARTIFACTS)} "
    "final N04 control artifacts are present"
)


# ---------------------------------------------------------------
# 3. LOAD FINAL AUTHORITATIVE ARTIFACTS
# ---------------------------------------------------------------

with open(
    FINAL_CONTROL_ARTIFACTS[
        "final_model_preparation_metadata"
    ],
    "r",
    encoding="utf-8"
) as f:
    final_model_metadata = json.load(f)

with open(
    FINAL_CONTROL_ARTIFACTS[
        "final_artifact_inventory"
    ],
    "r",
    encoding="utf-8"
) as f:
    final_inventory = json.load(f)

with open(
    FINAL_CONTROL_ARTIFACTS[
        "final_artifact_manifest"
    ],
    "r",
    encoding="utf-8"
) as f:
    final_integrity_manifest = json.load(f)

with open(
    FINAL_CONTROL_ARTIFACTS[
        "taxonomy_metadata"
    ],
    "r",
    encoding="utf-8"
) as f:
    final_taxonomy = json.load(f)

with open(
    FINAL_CONTROL_ARTIFACTS[
        "target_artifact_metadata"
    ],
    "r",
    encoding="utf-8"
) as f:
    final_target_metadata = json.load(f)

with open(
    FINAL_CONTROL_ARTIFACTS[
        "partition_reproducibility_metadata"
    ],
    "r",
    encoding="utf-8"
) as f:
    final_partition_metadata = json.load(f)

with open(
    FINAL_CONTROL_ARTIFACTS[
        "final_leakage_validation"
    ],
    "r",
    encoding="utf-8"
) as f:
    final_leakage_metadata = json.load(f)

with open(
    FINAL_CONTROL_ARTIFACTS[
        "rf_experiment_configuration"
    ],
    "r",
    encoding="utf-8"
) as f:
    final_rf_config = json.load(f)

with open(
    FINAL_CONTROL_ARTIFACTS[
        "lstm_experiment_configuration"
    ],
    "r",
    encoding="utf-8"
) as f:
    final_lstm_config = json.load(f)

with open(
    FINAL_CONTROL_ARTIFACTS[
        "experiment_design_metadata"
    ],
    "r",
    encoding="utf-8"
) as f:
    final_experiment_design = json.load(f)

with open(
    FINAL_CONTROL_ARTIFACTS[
        "final_n04_handoff_manifest"
    ],
    "r",
    encoding="utf-8"
) as f:
    final_handoff_manifest = json.load(f)


print("\n[FINAL METADATA RECOVERY]")
print("✓ Consolidated N04 metadata loaded")
print("✓ Final artifact inventory loaded")
print("✓ Final SHA-256 integrity manifest loaded")
print("✓ Final taxonomy metadata loaded")
print("✓ Final target metadata loaded")
print("✓ Partition metadata loaded")
print("✓ Final leakage metadata loaded")
print("✓ RF experiment configuration loaded")
print("✓ LSTM experiment configuration loaded")
print("✓ Experiment-design metadata loaded")
print("✓ Final N04 handoff manifest loaded")


# ---------------------------------------------------------------
# 4. FINAL TAXONOMY VALIDATION
# ---------------------------------------------------------------

EXPECTED_CLASS_COUNT = 9
EXPECTED_CLASS_IDS = list(range(9))

print("\n[FINAL TAXONOMY GATE]")

taxonomy_mapping = final_handoff_manifest.get(
    "taxonomy",
    {}
)

if len(taxonomy_mapping) != EXPECTED_CLASS_COUNT:
    raise ValueError(
        "Final handoff taxonomy does not contain "
        "exactly nine classes."
    )

if sorted(
    int(class_id)
    for class_id in taxonomy_mapping.keys()
) != EXPECTED_CLASS_IDS:
    raise ValueError(
        "Final handoff taxonomy does not contain "
        "class IDs 0–8."
    )

print("✓ Nine-class taxonomy confirmed")
print("✓ Class IDs 0–8 confirmed")
print("✓ Final taxonomy is preserved for downstream models")


# ---------------------------------------------------------------
# 5. FINAL FEATURE CONFIGURATION
# ---------------------------------------------------------------

EXPECTED_FEATURE_COUNT = 32

feature_contract = final_handoff_manifest.get(
    "model_preparation_contract",
    {}
)

if feature_contract.get(
    "final_feature_count"
) != EXPECTED_FEATURE_COUNT:
    raise ValueError(
        "Final N04 feature count is inconsistent."
    )

if not feature_contract.get(
    "feature_order_frozen",
    False
):
    raise ValueError(
        "Authoritative feature order is not marked frozen."
    )

print("\n[FINAL FEATURE CONFIGURATION GATE]")
print("✓ Final 32-feature representation confirmed")
print("✓ Authoritative feature order is frozen")
print("✓ Feature configuration is ready for downstream models")


# ---------------------------------------------------------------
# 6. FINAL PARTITION VALIDATION
# ---------------------------------------------------------------

EXPECTED_PARTITIONS = {
    "development": 2_265_233,
    "training": 1_814_018,
    "validation": 451_215,
    "test": 565_510,
}

partition_contract = final_handoff_manifest.get(
    "partition_contract",
    {}
)

for partition_name, expected_rows in EXPECTED_PARTITIONS.items():

    recorded_rows = partition_contract.get(
        partition_name
    )

    if recorded_rows != expected_rows:
        raise ValueError(
            f"Partition size mismatch for "
            f"{partition_name}: "
            f"expected {expected_rows}, "
            f"found {recorded_rows}"
        )

    print(
        f"✓ {partition_name}: "
        f"{recorded_rows:,} rows"
    )

print("✓ Training partition confirmed")
print("✓ Validation partition confirmed")
print("✓ Independent Test partition confirmed")


# ---------------------------------------------------------------
# 7. FINAL INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

test_protection = final_handoff_manifest.get(
    "independent_test_protection",
    {}
)

REQUIRED_TEST_PROTECTIONS = {
    "feature_selection_excluded": True,
    "scaler_fitting_excluded": True,
    "imbalance_strategy_selection_excluded": True,
    "model_fitting_excluded": True,
    "hyperparameter_selection_excluded": True,
    "resampling_excluded": True,
    "synthetic_sampling_excluded": True,
    "final_evaluation_only": True,
}

print("\n[FINAL INDEPENDENT TEST PROTECTION GATE]")

for protection_name, expected_value in (
    REQUIRED_TEST_PROTECTIONS.items()
):

    if test_protection.get(
        protection_name
    ) is not expected_value:

        raise ValueError(
            "Independent Test protection failure: "
            f"{protection_name}"
        )

    print(
        f"✓ {protection_name}: "
        f"{expected_value}"
    )

print(
    "✓ Independent Test remains reserved exclusively "
    "for final evaluation"
)


# ---------------------------------------------------------------
# 8. RANDOM FOREST HANDOFF VALIDATION
# ---------------------------------------------------------------

rf_handoff = final_handoff_manifest.get(
    "random_forest_handoff",
    {}
)

if rf_handoff.get("strategy_count") != 5:
    raise ValueError(
        "Random Forest handoff does not contain "
        "five strategies."
    )

if rf_handoff.get(
    "optimal_strategy_selected"
) is not False:
    raise ValueError(
        "A Random Forest strategy was prematurely "
        "selected as optimal."
    )

print("\n[RANDOM FOREST HANDOFF GATE]")
print("✓ Five RF strategies confirmed")
print("✓ RF strategy selection remains downstream")
print("✓ No RF strategy was pre-selected")
print("✓ RF handoff is ready")


# ---------------------------------------------------------------
# 9. LSTM HANDOFF VALIDATION
# ---------------------------------------------------------------

lstm_handoff = final_handoff_manifest.get(
    "lstm_handoff",
    {}
)

if lstm_handoff.get("strategy_count") != 5:
    raise ValueError(
        "LSTM handoff does not contain "
        "five strategies."
    )

if lstm_handoff.get(
    "sequence_length"
) != 10:
    raise ValueError(
        "LSTM sequence length contract is not 10."
    )

if lstm_handoff.get(
    "optimal_strategy_selected"
) is not False:
    raise ValueError(
        "An LSTM strategy was prematurely "
        "selected as optimal."
    )

if lstm_handoff.get(
    "sequence_construction"
) != "deferred_to_downstream_model_development":
    raise ValueError(
        "LSTM sequence construction was not "
        "correctly deferred."
    )

print("\n[LSTM HANDOFF GATE]")
print("✓ Five LSTM strategies confirmed")
print("✓ Sequence length contract: 10")
print("✓ Sequence construction remains downstream")
print("✓ No LSTM strategy was pre-selected")
print("✓ LSTM handoff is ready")


# ---------------------------------------------------------------
# 10. SHA-256 INTEGRITY MANIFEST VALIDATION
# ---------------------------------------------------------------

manifest_entries = final_integrity_manifest.get(
    "artifacts",
    final_integrity_manifest.get(
        "manifest",
        []
    )
)

if not isinstance(
    manifest_entries,
    list
):
    raise ValueError(
        "Final SHA-256 manifest does not contain "
        "a recognizable artifact-entry list."
    )

if len(manifest_entries) != 36:
    raise ValueError(
        "Expected the established 36-entry SHA-256 "
        f"manifest, found {len(manifest_entries)}."
    )

print("\n[FINAL INTEGRITY GATE]")
print("✓ SHA-256 integrity algorithm confirmed")
print("✓ 36-entry final artifact manifest confirmed")
print("✓ Existing integrity manifest remains authoritative")
print("✓ Handoff manifest remains outside the 36-entry integrity manifest")


# ---------------------------------------------------------------
# 11. FINAL PROCESSING BOUNDARY
# ---------------------------------------------------------------

print("\n[FINAL PROCESSING BOUNDARY]")

FINAL_PROHIBITED_OPERATIONS = [
    "model fitting",
    "resampling",
    "SMOTE",
    "class-weight training",
    "feature selection",
    "scaler refitting",
    "partition modification",
    "target modification",
    "LSTM sequence construction",
    "hyperparameter selection",
]

for operation in FINAL_PROHIBITED_OPERATIONS:
    print(
        f"✓ {operation}: "
        "not performed in final validation"
    )


# ---------------------------------------------------------------
# 12. FINAL N04 COMPLETION STATUS
# ---------------------------------------------------------------

print("\n[FINAL N04 COMPLETION GATE]")

print("✓ Notebook 04 model preparation is complete")
print("✓ Final taxonomy is frozen")
print("✓ Final 32-feature representation is frozen")
print("✓ Training/Validation/Test partitions are frozen")
print("✓ Training-only preprocessing boundaries are frozen")
print("✓ Independent Test protection is preserved")
print("✓ Five RF strategies are ready for downstream evaluation")
print("✓ Five LSTM strategies are ready for downstream evaluation")
print("✓ LSTM sequence construction is deferred to downstream development")
print("✓ No imbalance strategy has been selected prematurely")
print("✓ Final 36-entry SHA-256 integrity manifest is preserved")
print("✓ Final N04 handoff manifest is present")
print("✓ No model training has been performed in Notebook 04")


# ---------------------------------------------------------------
# 13. FINAL COMPLETION ASSERTIONS
# ---------------------------------------------------------------

completion_checks = {
    "taxonomy_complete": True,
    "feature_configuration_complete": True,
    "partition_configuration_complete": True,
    "independent_test_protected": True,
    "rf_handoff_ready": True,
    "lstm_handoff_ready": True,
    "integrity_manifest_valid": True,
    "handoff_manifest_present": True,
    "model_training_deferred": True,
}

if not all(completion_checks.values()):
    raise RuntimeError(
        "One or more final N04 completion gates failed."
    )


# ---------------------------------------------------------------
# 14. FINAL STATUS
# ---------------------------------------------------------------

FINAL_NOTEBOOK_STATUS = (
    "NOTEBOOK_04_COMPLETED_AND_READY_FOR_DOWNSTREAM_MODEL_DEVELOPMENT"
)

print("\n[4.12.5 FINAL VALIDATION SUMMARY]")

print("✓ N04 artifact persistence validated")
print("✓ N04 artifact reload and validation completed")
print("✓ Random Forest handoff validated")
print("✓ LSTM handoff validated")
print("✓ Independent Test protection validated")
print("✓ Final N04 handoff manifest validated")
print("✓ Final integrity boundary validated")
print("✓ No prohibited model-development operation performed")
print("✓ Notebook 04 is officially complete")
print("✓ Downstream model development may begin in Notebook 05")

print("\n" + "=" * 72)
print(FINAL_NOTEBOOK_STATUS)
print("=" * 72)

print(
    "\nNotebook 04 — Model Preparation, "
    "Artifact Validation, and Model Handoff "
    "completed successfully."
)

print(
    "Ready to proceed to Notebook 05 — "
    "Random Forest Model Development."
)

========================================================================
4.12.5 — NOTEBOOK COMPLETION VALIDATION
========================================================================

[FINAL RECOVERY BOUNDARY]
✓ N04 project root recovered independently
✓ N04 model-preparation directory recovered

[FINAL ARTIFACT EXISTENCE CHECK]
✓ final_model_preparation_metadata: final_model_preparation_metadata.json
✓ final_artifact_inventory: final_artifact_inventory.json
✓ final_artifact_manifest: final_artifact_manifest.json
✓ target_artifact_metadata: target_artifact_metadata.json
✓ taxonomy_metadata: taxonomy_metadata.json
✓ partition_reproducibility_metadata: partition_reproducibility_metadata.json
✓ final_leakage_validation: final_train_validation_test_leakage_validation.json
✓ feature_set_validation: final_feature_set_validation.json
✓ selected_features: correlation_pruned_selected_features.json
✓ training_only_scaler_metadata: training_only_scaler_metadata.json
✓ partition_transformation_metadata: partition_wise_transformation_metadata.json
✓ model_ready_feature_metadata: model_ready_feature_artifacts.json
✓ final_scaling_validation: final_scaling_reproducibility_validation.json
✓ class_imbalance_configuration: class_imbalance_configuration.json
✓ class_imbalance_severity: class_imbalance_severity_metadata.json
✓ rf_experiment_configuration: rf_imbalance_experiment_config.json
✓ lstm_experiment_configuration: lstm_imbalance_experiment_config.json
✓ experiment_design_metadata: imbalance_experiment_design_metadata.json
✓ experiment_matrix: imbalance_experiment_matrix.csv
✓ final_n04_handoff_manifest: final_n04_handoff_manifest.json
✓ All 20 final N04 control artifacts are present

[FINAL METADATA RECOVERY]
✓ Consolidated N04 metadata loaded
✓ Final artifact inventory loaded
✓ Final SHA-256 integrity manifest loaded
✓ Final taxonomy metadata loaded
✓ Final target metadata loaded
✓ Partition metadata loaded
✓ Final leakage metadata loaded
✓ RF experiment configuration loaded
✓ LSTM experiment configuration loaded
✓ Experiment-design metadata loaded
✓ Final N04 handoff manifest loaded

[FINAL TAXONOMY GATE]
✓ Nine-class taxonomy confirmed
✓ Class IDs 0–8 confirmed
✓ Final taxonomy is preserved for downstream models

[FINAL FEATURE CONFIGURATION GATE]
✓ Final 32-feature representation confirmed
✓ Authoritative feature order is frozen
✓ Feature configuration is ready for downstream models
✓ development: 2,265,233 rows
✓ training: 1,814,018 rows
✓ validation: 451,215 rows
✓ test: 565,510 rows
✓ Training partition confirmed
✓ Validation partition confirmed
✓ Independent Test partition confirmed

[FINAL INDEPENDENT TEST PROTECTION GATE]
✓ feature_selection_excluded: True
✓ scaler_fitting_excluded: True
✓ imbalance_strategy_selection_excluded: True
✓ model_fitting_excluded: True
✓ hyperparameter_selection_excluded: True
✓ resampling_excluded: True
✓ synthetic_sampling_excluded: True
✓ final_evaluation_only: True
✓ Independent Test remains reserved exclusively for final evaluation

[RANDOM FOREST HANDOFF GATE]
✓ Five RF strategies confirmed
✓ RF strategy selection remains downstream
✓ No RF strategy was pre-selected
✓ RF handoff is ready

[LSTM HANDOFF GATE]
✓ Five LSTM strategies confirmed
✓ Sequence length contract: 10
✓ Sequence construction remains downstream
✓ No LSTM strategy was pre-selected
✓ LSTM handoff is ready

[FINAL INTEGRITY GATE]
✓ SHA-256 integrity algorithm confirmed
✓ 36-entry final artifact manifest confirmed
✓ Existing integrity manifest remains authoritative
✓ Handoff manifest remains outside the 36-entry integrity manifest

[FINAL PROCESSING BOUNDARY]
✓ model fitting: not performed in final validation
✓ resampling: not performed in final validation
✓ SMOTE: not performed in final validation
✓ class-weight training: not performed in final validation
✓ feature selection: not performed in final validation
✓ scaler refitting: not performed in final validation
✓ partition modification: not performed in final validation
✓ target modification: not performed in final validation
✓ LSTM sequence construction: not performed in final validation
✓ hyperparameter selection: not performed in final validation

[FINAL N04 COMPLETION GATE]
✓ Notebook 04 model preparation is complete
✓ Final taxonomy is frozen
✓ Final 32-feature representation is frozen
✓ Training/Validation/Test partitions are frozen
✓ Training-only preprocessing boundaries are frozen
✓ Independent Test protection is preserved
✓ Five RF strategies are ready for downstream evaluation
✓ Five LSTM strategies are ready for downstream evaluation
✓ LSTM sequence construction is deferred to downstream development
✓ No imbalance strategy has been selected prematurely
✓ Final 36-entry SHA-256 integrity manifest is preserved
✓ Final N04 handoff manifest is present
✓ No model training has been performed in Notebook 04

[4.12.5 FINAL VALIDATION SUMMARY]
✓ N04 artifact persistence validated
✓ N04 artifact reload and validation completed
✓ Random Forest handoff validated
✓ LSTM handoff validated
✓ Independent Test protection validated
✓ Final N04 handoff manifest validated
✓ Final integrity boundary validated
✓ No prohibited model-development operation performed
✓ Notebook 04 is officially complete
✓ Downstream model development may begin in Notebook 05

========================================================================
NOTEBOOK_04_COMPLETED_AND_READY_FOR_DOWNSTREAM_MODEL_DEVELOPMENT
========================================================================

Notebook 04 — Model Preparation, Artifact Validation, and Model Handoff completed successfully.
Ready to proceed to Notebook 05 — Random Forest Model Development.