# AI-Powered Network Intrusion Detection System

## Notebook 05 – Random Forest Model Development

**Project:** AI-Powered Network Intrusion Detection System  
**Dataset:** CICIDS-2017  
**Task:** Multi-Class Network Intrusion Detection  
**Primary Classification:** Eight Attack Families + BENIGN  
**Input:** Final Model-Ready Features and Targets from Notebook 04  
**Model:** Random Forest Classifier  
**Role:** Member A – ML & Data Engineering

## Notebook Purpose

This notebook performs the controlled development, evaluation, comparison, selection, and persistence of the Random Forest component of the proposed network intrusion detection framework.

The notebook consumes the finalized model-ready artifacts produced by Notebook 04 and does not repeat data cleaning, feature engineering, feature selection, scaling, taxonomy construction, or dataset partitioning.

Random Forest development is performed under the finalized nine-class taxonomy and 32-feature representation. Multiple imbalance-handling strategies established in Notebook 04 are evaluated using the Training and Validation partitions, while the Independent Test partition remains protected until the final evaluation of the selected Random Forest configuration.

The notebook establishes a reproducible experimental boundary between finalized model preparation and downstream Random Forest model development.

## Notebook Objectives

The primary objectives of this notebook are:

1. Recover and validate the finalized Notebook 04 Random Forest handoff contract.

2. Establish a reproducible Random Forest development environment and configuration.

3. Evaluate the predefined Random Forest imbalance strategies established in Notebook 04.

4. Train all candidate strategies using the Training partition only.

5. Compare candidate strategies using the protected Validation partition.

6. Use macro F1 as the primary model-selection metric because of the severe class imbalance present in the intrusion-detection dataset.

7. Analyze secondary metrics including macro recall, balanced accuracy, weighted F1, accuracy, and per-class precision, recall, and F1.

8. Analyze minority-class behavior and major confusion patterns during validation.

9. Select and freeze the Random Forest strategy using Validation evidence without using the Independent Test partition.

10. Train the final Random Forest model using the selected strategy.

11. Evaluate the frozen final Random Forest model on the Independent Test partition only after model selection has been completed.

12. Persist the final model, experimental results, evaluation artifacts, configuration metadata, feature-importance results, and downstream handoff information.

13. Validate that the final Random Forest artifact is compatible with the finalized Notebook 04 model-preparation contract.

## Research and Experimental Principles

The Random Forest development process follows the following principles:

- Notebook 04 is the authoritative source of the model-ready data and preprocessing contract.

- No preprocessing operation from Notebook 04 is repeated in this notebook.

- The finalized nine-class taxonomy is not modified.

- The finalized 32-feature representation and feature order are not modified.

- The Training partition is used for model fitting and training-time imbalance handling.

- The Validation partition is used for candidate strategy comparison and model-selection decisions.

- The Independent Test partition remains protected from model development and strategy selection.

- No Test observations are used for hyperparameter selection, imbalance-strategy selection, or model fitting.

- No single imbalance-handling strategy is assumed to be optimal before experimentation.

- All Random Forest candidates use a controlled and reproducible experimental configuration.

- Macro F1 is the primary strategy-selection metric because overall accuracy can be dominated by the majority BENIGN class under severe class imbalance.

- Secondary metrics and per-class performance are considered to identify minority-class behavior and false-negative patterns.

- All stochastic procedures use the established project random seed where applicable.

- All experimental decisions are recorded as persistent artifacts.

- The final Independent Test evaluation is performed only after the Random Forest strategy and configuration have been frozen.

- Intermediate experimental artifacts are separated from the final trained model artifact.

## Final N04 Model-Preparation Contract

Notebook 05 operates on the finalized state produced by Notebook 04.

The authoritative model-ready configuration is:

- Dataset: CICIDS-2017
- Final classes: 9
- Final features: 32
- Training observations: 1,814,018
- Validation observations: 451,215
- Independent Test observations: 565,510
- Random seed: 42
- Feature scaling: Training-only StandardScaler
- Feature order: Frozen
- Independent Test: Protected

Final class taxonomy:

0 — BENIGN
1 — DDoS
2 — Port Scan
3 — Brute Force
4 — Bot
5 — Web Attack
6 — Infiltration
7 — DoS
8 — Heartbleed

The persisted Notebook 04 artifacts are treated as read-only inputs to Random Forest development.

## Planned Notebook Stages

The Random Forest development workflow consists of the following stages:

### 5.1 — Environment & N04 Handoff Recovery

Recover the project environment and finalized Notebook 04 handoff artifacts independently.

### 5.2 — Random Forest Input Contract Validation

Validate the finalized feature arrays, target arrays, taxonomy, feature order, partition dimensions, and RF experiment configuration.

### 5.3 — Random Forest Experimental Configuration

Establish the common Random Forest configuration, reproducibility controls, evaluation metrics, resource limits, and experiment output boundaries.

### 5.4 — RF-0: Natural Distribution Baseline

Train and evaluate the natural training-distribution Random Forest baseline.

### 5.5 — RF-1: Balanced Class Weighting

Evaluate Random Forest using balanced class weighting.

### 5.6 — RF-2: Balanced-Subsample Class Weighting

Evaluate Random Forest using balanced-subsample class weighting.

### 5.7 — RF-3: Controlled Random Oversampling

Evaluate the controlled random-oversampling strategy under the boundaries established by Notebook 04.

### 5.8 — RF-4: Controlled SMOTE

Evaluate the controlled SMOTE strategy under the boundaries established by Notebook 04.

### 5.9 — Validation-Based Strategy Comparison

Compare all five RF strategies using the protected Validation partition.

### 5.10 — Random Forest Strategy Selection

Select and freeze the final Random Forest strategy using Validation evidence.

### 5.11 — Final Random Forest Training

Train the final Random Forest model using the frozen strategy.

### 5.12 — Independent Test Evaluation

Perform the final evaluation on the previously protected Independent Test partition.

### 5.13 — Random Forest Error Analysis and Interpretation

Analyze class-wise performance, confusion patterns, minority-class behavior, and Random Forest feature importance.

### 5.14 — Random Forest Artifact Persistence

Persist the final model, experimental results, evaluation results, metadata, and interpretation artifacts.

### 5.15 — Final Random Forest Handoff and Validation

Validate the final Random Forest artifact and establish the downstream handoff boundary.

## Random Forest Experiment Matrix

Notebook 04 established five candidate Random Forest imbalance strategies.

The strategies evaluated in this notebook are:

| ID | Strategy | Training-Time Mechanism |
|---|---|---|
| RF-0 | Natural Distribution Baseline | No imbalance intervention |
| RF-1 | Balanced Class Weighting | `class_weight="balanced"` |
| RF-2 | Balanced-Subsample Weighting | `class_weight="balanced_subsample"` |
| RF-3 | Controlled Random Oversampling | Controlled training-only oversampling |
| RF-4 | Controlled SMOTE | Controlled training-only SMOTE |

All five candidates are evaluated under a common Random Forest configuration.

The Validation partition is used for strategy comparison.

The Independent Test partition is not used during strategy comparison and remains reserved for the final evaluation of the selected Random Forest.

## Evaluation Protocol

Random Forest candidates are evaluated using a consistent metric framework.

### Primary Strategy-Selection Metric

- Macro F1

Macro F1 gives equal importance to each class and therefore provides a more informative comparison than overall accuracy under the observed class imbalance.

### Secondary Metrics

- Macro Precision
- Macro Recall
- Balanced Accuracy
- Weighted F1
- Accuracy
- Per-class Precision
- Per-class Recall
- Per-class F1
- Per-class Support

### Error Analysis

- Confusion matrix
- Normalized confusion matrix
- Major confusion pairs
- Attack false negatives
- BENIGN false positives
- Minority-class behavior

### Resource Measurements

Where applicable:

- Training time
- Inference time
- Throughput
- Training sample count
- Model size
- Memory/resource observations

Candidate comparison is performed using the Validation partition only.

The Independent Test partition is reserved for final evaluation after the Random Forest configuration has been selected and frozen.

## Independent Test Protection

The Independent Test partition remains protected throughout Random Forest development.

Before final strategy selection:

- Test observations are not used for training.
- Test observations are not used for imbalance handling.
- Test observations are not used for hyperparameter selection.
- Test observations are not used for strategy comparison.
- Test observations are not used for error-driven model modification.
- Test observations are not used for feature selection.
- Test observations are not used for preprocessing refitting.

The Independent Test partition is accessed for final evaluation only after the Random Forest strategy and configuration have been frozen.

This separation preserves the independence of the final reported Random Forest evaluation.

## Artifact and Output Organization

Notebook 04 model-preparation artifacts remain immutable and are consumed directly from:

`outputs/model_preparation_v2/`

Random Forest development artifacts are stored separately under:

`outputs/random_forest_model_development/`

The final trained Random Forest model is stored under:

`trained_models/random_forest/`

The separation is maintained as follows:

- `outputs/model_preparation_v2/` — finalized N04 data and preprocessing contract
- `outputs/random_forest_model_development/` — RF experiments, comparisons, evaluations, interpretation, and metadata
- `trained_models/random_forest/` — final trained Random Forest model and its final model metadata

Notebook 05 does not overwrite or modify the finalized Notebook 04 artifacts.

## Reproducibility and Persistence

The Random Forest development process is designed to be reproducible from the persisted Notebook 04 handoff.

The notebook records:

- Random seed
- Model configuration
- Imbalance strategy
- Training sample counts
- Validation sample counts
- Candidate experiment configuration
- Evaluation metrics
- Strategy-selection evidence
- Final model metadata
- Feature order
- Class taxonomy
- Artifact paths
- Final model persistence information

Temporary training artifacts are not treated as authoritative project outputs.

The final Random Forest model and its associated metadata are persisted only after the selected strategy has been frozen.

## Research Boundaries

This notebook is limited to Random Forest model development.

The following operations remain outside the scope of Notebook 05:

- Raw dataset cleaning
- Stage-1 feature engineering
- Feature selection
- Correlation pruning
- Dataset repartitioning
- Taxonomy modification
- Scaler refitting
- LSTM sequence construction
- LSTM model development
- RF-LSTM ensemble construction
- SHAP-based final explainability analysis
- Real-time API integration

These components are handled in their respective project stages and notebooks.

Notebook 05 consumes the finalized N04 representation and establishes the validated Random Forest component for downstream integration.

## Final Notebook Completion Criteria

Notebook 05 will be considered complete only when:

- The finalized N04 handoff is successfully recovered.
- The 9-class taxonomy is preserved.
- The 32-feature representation and feature order are preserved.
- Training, Validation, and Independent Test dimensions are validated.
- All five predefined RF imbalance strategies are evaluated.
- Candidate comparison is performed using Validation data.
- No strategy is selected using Independent Test results.
- The final RF strategy is explicitly recorded and frozen.
- The final RF model is trained and persisted.
- Independent Test evaluation is performed only after strategy selection.
- Final class-wise and overall metrics are persisted.
- RF error analysis is persisted.
- Feature-importance analysis is persisted.
- Final RF metadata is persisted.
- The final trained model is stored under `trained_models/random_forest/`.
- A final RF handoff manifest is created.
- No Notebook 04 artifact is modified.
- Final validation confirms that the trained RF model conforms to the N04 model-preparation contract.

## Notebook 05 — Stage Summary

The completed Random Forest development pipeline is:

N04 Final Model Preparation
        ↓
Environment & Handoff Recovery
        ↓
Input Contract Validation
        ↓
Common RF Configuration
        ↓
RF-0 Natural Distribution
        ↓
RF-1 Balanced Weighting
        ↓
RF-2 Balanced-Subsample Weighting
        ↓
RF-3 Controlled Random Oversampling
        ↓
RF-4 Controlled SMOTE
        ↓
Validation-Based Comparison
        ↓
Strategy Selection
        ↓
Final RF Training
        ↓
Independent Test Evaluation
        ↓
Error Analysis & Interpretation
        ↓
Artifact Persistence
        ↓
Final RF Handoff

## 5.1 — Environment & N04 Handoff Recovery

This section establishes the execution environment for Notebook 05 and
independently recovers the finalized model-preparation state produced by
Notebook 04.

Notebook 05 does not repeat any preprocessing performed in Notebook 04.
The finalized N04 model-preparation directory is treated as an immutable
downstream input boundary.

The Random Forest stage receives:

- the finalized 32-feature model-ready representation,
- the authoritative N04 feature ordering,
- the finalized nine-class target taxonomy,
- the Training, Validation, and Independent Test partitions,
- the persisted target artifacts,
- and the five predefined Random Forest imbalance strategies.

The N04 partition and preprocessing contract is preserved:

- Training is used for Random Forest model development and training-time
  imbalance experiments.
- Validation is reserved for strategy comparison and selection.
- The Independent Test partition is reserved exclusively for final evaluation.

The five Random Forest strategies established in Notebook 04 are:

1. RF-0 — Natural Distribution Baseline
2. RF-1 — Balanced Class Weighting
3. RF-2 — Balanced-Subsample Class Weighting
4. RF-3 — Controlled Random Oversampling
5. RF-4 — Controlled SMOTE

No Random Forest strategy is considered optimal before downstream
experimentation.

This subsection performs only environment recovery, artifact recovery,
contract validation, and handoff verification. It does not perform feature
selection, scaling, resampling, SMOTE, model fitting, hyperparameter
selection, or modification of any N04 artifact.

In [ ]:
# ================================================================
# 5.1 — ENVIRONMENT & N04 HANDOFF RECOVERY
# ================================================================

from google.colab import drive
from pathlib import Path
import json
import random
import numpy as np


print("=" * 72)
print("NOTEBOOK 05 — RANDOM FOREST MODEL DEVELOPMENT")
print("5.1 — ENVIRONMENT & N04 HANDOFF RECOVERY")
print("=" * 72)


# ---------------------------------------------------------------
# 1. MOUNT GOOGLE DRIVE
# ---------------------------------------------------------------

drive.mount(
    "/content/drive",
    force_remount=False
)

print("\n[GOOGLE DRIVE]")
print("✓ Google Drive mounted")


# ---------------------------------------------------------------
# 2. RECOVER AUTHORITATIVE PROJECT ROOT
# ---------------------------------------------------------------

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/"
    "AI-Network-Intrusion-Detection-System"
)

if not PROJECT_ROOT.is_dir():
    raise FileNotFoundError(
        "Project root was not found:\n"
        f"{PROJECT_ROOT}"
    )


# ---------------------------------------------------------------
# 3. RECOVER ESTABLISHED PROJECT DIRECTORIES
# ---------------------------------------------------------------

DATA_DIR = (
    PROJECT_ROOT / "data"
)

RAW_DATA_DIR = (
    DATA_DIR / "raw"
)

PROCESSED_DATA_DIR = (
    DATA_DIR / "processed"
)

NOTEBOOKS_DIR = (
    PROJECT_ROOT / "notebooks"
)

OUTPUTS_DIR = (
    PROJECT_ROOT / "outputs"
)

REFERENCES_DIR = (
    PROJECT_ROOT / "references"
)

TRAINED_MODELS_DIR = (
    PROJECT_ROOT / "trained_models"
)


required_project_directories = {
    "Project Root":
        PROJECT_ROOT,

    "Data Directory":
        DATA_DIR,

    "Raw Data Directory":
        RAW_DATA_DIR,

    "Processed Data Directory":
        PROCESSED_DATA_DIR,

    "Notebooks Directory":
        NOTEBOOKS_DIR,

    "Outputs Directory":
        OUTPUTS_DIR,

    "References Directory":
        REFERENCES_DIR,

    "Trained Models Directory":
        TRAINED_MODELS_DIR,
}


missing_project_directories = [
    name
    for name, path
    in required_project_directories.items()
    if not path.is_dir()
]


if missing_project_directories:
    raise FileNotFoundError(
        "The following established project directories "
        "were not found:\n"
        + "\n".join(
            f"  - {name}"
            for name in missing_project_directories
        )
    )


print("\n[PROJECT STRUCTURE]")
print(f"✓ Project Root       : {PROJECT_ROOT}")
print(f"✓ Data Directory     : {DATA_DIR}")
print(f"✓ Raw Data           : {RAW_DATA_DIR}")
print(f"✓ Processed Data     : {PROCESSED_DATA_DIR}")
print(f"✓ Notebooks          : {NOTEBOOKS_DIR}")
print(f"✓ Outputs            : {OUTPUTS_DIR}")
print(f"✓ References         : {REFERENCES_DIR}")
print(f"✓ Trained Models     : {TRAINED_MODELS_DIR}")


# ---------------------------------------------------------------
# 4. RECOVER FINAL N04 MODEL-PREPARATION DIRECTORY
# ---------------------------------------------------------------

MODEL_PREPARATION_V2_DIR = (
    OUTPUTS_DIR /
    "model_preparation_v2"
)

if not MODEL_PREPARATION_V2_DIR.is_dir():
    raise FileNotFoundError(
        "Final N04 model-preparation directory was not found:\n"
        f"{MODEL_PREPARATION_V2_DIR}"
    )


print("\n[N04 MODEL-PREPARATION BOUNDARY]")
print(
    f"✓ N04 Model Preparation : "
    f"{MODEL_PREPARATION_V2_DIR}"
)


# ---------------------------------------------------------------
# 5. ESTABLISH NOTEBOOK 05 OUTPUT DIRECTORIES
# ---------------------------------------------------------------

RANDOM_FOREST_OUTPUT_DIR = (
    OUTPUTS_DIR /
    "random_forest_model_development"
)

RF_EXPERIMENT_CONFIGURATION_DIR = (
    RANDOM_FOREST_OUTPUT_DIR /
    "experiment_configuration"
)

RF_STRATEGY_EXPERIMENTS_DIR = (
    RANDOM_FOREST_OUTPUT_DIR /
    "strategy_experiments"
)

RF_STRATEGY_SELECTION_DIR = (
    RANDOM_FOREST_OUTPUT_DIR /
    "strategy_selection"
)

RF_EVALUATION_DIR = (
    RANDOM_FOREST_OUTPUT_DIR /
    "evaluation"
)

RF_INTERPRETATION_DIR = (
    RANDOM_FOREST_OUTPUT_DIR /
    "interpretation"
)

RF_FINAL_MODEL_OUTPUT_DIR = (
    RANDOM_FOREST_OUTPUT_DIR /
    "final_model"
)

RANDOM_FOREST_MODEL_DIR = (
    TRAINED_MODELS_DIR /
    "random_forest"
)


# Create only Notebook 05 directories.
# Existing N04 artifacts are never recreated or modified.

for directory in [
    RANDOM_FOREST_OUTPUT_DIR,
    RF_EXPERIMENT_CONFIGURATION_DIR,
    RF_STRATEGY_EXPERIMENTS_DIR,
    RF_STRATEGY_SELECTION_DIR,
    RF_EVALUATION_DIR,
    RF_INTERPRETATION_DIR,
    RF_FINAL_MODEL_OUTPUT_DIR,
    RANDOM_FOREST_MODEL_DIR,
]:
    directory.mkdir(
        parents=True,
        exist_ok=True
    )


print("\n[NOTEBOOK 05 OUTPUT STRUCTURE]")
print(
    f"✓ RF Development Output : "
    f"{RANDOM_FOREST_OUTPUT_DIR}"
)
print(
    f"✓ RF Experiment Config   : "
    f"{RF_EXPERIMENT_CONFIGURATION_DIR}"
)
print(
    f"✓ RF Strategy Experiments: "
    f"{RF_STRATEGY_EXPERIMENTS_DIR}"
)
print(
    f"✓ RF Strategy Selection  : "
    f"{RF_STRATEGY_SELECTION_DIR}"
)
print(
    f"✓ RF Evaluation          : "
    f"{RF_EVALUATION_DIR}"
)
print(
    f"✓ RF Interpretation      : "
    f"{RF_INTERPRETATION_DIR}"
)
print(
    f"✓ RF Final Model Output  : "
    f"{RF_FINAL_MODEL_OUTPUT_DIR}"
)
print(
    f"✓ Trained RF Models      : "
    f"{RANDOM_FOREST_MODEL_DIR}"
)


# ---------------------------------------------------------------
# 6. REPRODUCIBILITY CONFIGURATION
# ---------------------------------------------------------------

RANDOM_SEED = 42

random.seed(
    RANDOM_SEED
)

np.random.seed(
    RANDOM_SEED
)

print("\n[REPRODUCIBILITY]")
print(
    f"✓ Random Seed : {RANDOM_SEED}"
)


# ---------------------------------------------------------------
# 7. RECOVER AUTHORITATIVE N04 CONTROL ARTIFACTS
# ---------------------------------------------------------------

N04_CONTROL_ARTIFACTS = {

    "final_model_preparation_metadata":
        MODEL_PREPARATION_V2_DIR /
        "final_model_preparation_metadata.json",

    "final_artifact_inventory":
        MODEL_PREPARATION_V2_DIR /
        "final_artifact_inventory.json",

    "final_artifact_manifest":
        MODEL_PREPARATION_V2_DIR /
        "final_artifact_manifest.json",

    "target_artifact_metadata":
        MODEL_PREPARATION_V2_DIR /
        "model_ready_targets" /
        "target_artifact_metadata.json",

    "taxonomy_metadata":
        MODEL_PREPARATION_V2_DIR /
        "taxonomy" /
        "taxonomy_metadata.json",

    "partition_reproducibility_metadata":
        MODEL_PREPARATION_V2_DIR /
        "partition_reproducibility_metadata.json",

    "final_leakage_validation":
        MODEL_PREPARATION_V2_DIR /
        "final_train_validation_test_leakage_validation.json",

    "feature_set_validation":
        MODEL_PREPARATION_V2_DIR /
        "feature_selection" /
        "final_feature_set_validation.json",

    "selected_features":
        MODEL_PREPARATION_V2_DIR /
        "feature_selection" /
        "correlation_pruned_selected_features.json",

    "training_only_scaler_metadata":
        MODEL_PREPARATION_V2_DIR /
        "feature_scaling" /
        "training_only_scaler_metadata.json",

    "partition_transformation_metadata":
        MODEL_PREPARATION_V2_DIR /
        "feature_scaling" /
        "partition_wise_transformation_metadata.json",

    "model_ready_feature_metadata":
        MODEL_PREPARATION_V2_DIR /
        "feature_scaling" /
        "model_ready_feature_artifacts.json",

    "final_scaling_validation":
        MODEL_PREPARATION_V2_DIR /
        "feature_scaling" /
        "final_scaling_reproducibility_validation.json",

    "class_imbalance_configuration":
        MODEL_PREPARATION_V2_DIR /
        "class_imbalance" /
        "class_imbalance_configuration.json",

    "class_imbalance_severity":
        MODEL_PREPARATION_V2_DIR /
        "class_imbalance" /
        "class_imbalance_severity_metadata.json",

    "rf_experiment_configuration":
        MODEL_PREPARATION_V2_DIR /
        "downstream_imbalance_experiments" /
        "rf_imbalance_experiment_config.json",

    "lstm_experiment_configuration":
        MODEL_PREPARATION_V2_DIR /
        "downstream_imbalance_experiments" /
        "lstm_imbalance_experiment_config.json",

    "experiment_design_metadata":
        MODEL_PREPARATION_V2_DIR /
        "downstream_imbalance_experiments" /
        "imbalance_experiment_design_metadata.json",

    "experiment_matrix":
        MODEL_PREPARATION_V2_DIR /
        "downstream_imbalance_experiments" /
        "imbalance_experiment_matrix.csv",

    "final_n04_handoff_manifest":
        MODEL_PREPARATION_V2_DIR /
        "final_n04_handoff_manifest.json",
}


print("\n[N04 CONTROL ARTIFACT RECOVERY]")

missing_n04_artifacts = []

for artifact_name, artifact_path in (
    N04_CONTROL_ARTIFACTS.items()
):

    if not artifact_path.is_file():

        missing_n04_artifacts.append(
            f"{artifact_name}: {artifact_path}"
        )

    else:

        print(
            f"✓ {artifact_name}: "
            f"{artifact_path.name}"
        )


if missing_n04_artifacts:
    raise FileNotFoundError(
        "Required N04 handoff/control artifacts are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_n04_artifacts
        )
    )


print(
    f"✓ All {len(N04_CONTROL_ARTIFACTS)} "
    "N04 control artifacts are present"
)


# ---------------------------------------------------------------
# 8. ESTABLISH AUTHORITATIVE RANDOM FOREST INPUT PATHS
# ---------------------------------------------------------------

FEATURE_SCALING_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "feature_scaling"
)

TARGET_ARTIFACT_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "model_ready_targets"
)

FEATURE_SELECTION_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "feature_selection"
)

EXPERIMENT_DIR = (
    MODEL_PREPARATION_V2_DIR /
    "downstream_imbalance_experiments"
)


RF_INPUT_PATHS = {

    "Training features":
        FEATURE_SCALING_DIR /
        "X_train_scaled.npy",

    "Validation features":
        FEATURE_SCALING_DIR /
        "X_validation_scaled.npy",

    "Test features":
        FEATURE_SCALING_DIR /
        "X_test_scaled.npy",

    "Training targets":
        TARGET_ARTIFACT_DIR /
        "y_train.npy",

    "Validation targets":
        TARGET_ARTIFACT_DIR /
        "y_validation.npy",

    "Test targets":
        TARGET_ARTIFACT_DIR /
        "y_test.npy",

    "Selected-feature configuration":
        FEATURE_SELECTION_DIR /
        "correlation_pruned_selected_features.json",

    "RF experiment configuration":
        EXPERIMENT_DIR /
        "rf_imbalance_experiment_config.json",
}


print("\n[RANDOM FOREST INPUT ARTIFACTS]")

missing_rf_inputs = []

for artifact_name, artifact_path in (
    RF_INPUT_PATHS.items()
):

    if not artifact_path.is_file():

        missing_rf_inputs.append(
            f"{artifact_name}: {artifact_path}"
        )

    else:

        print(
            f"✓ {artifact_name}: "
            f"{artifact_path.name}"
        )


if missing_rf_inputs:
    raise FileNotFoundError(
        "Required Random Forest input artifacts are missing:\n"
        + "\n".join(
            f"  - {item}"
            for item in missing_rf_inputs
        )
    )


# ---------------------------------------------------------------
# 9. LOAD AUTHORITATIVE N04 METADATA
# ---------------------------------------------------------------

def load_json_artifact(
    artifact_path
):
    with open(
        artifact_path,
        "r",
        encoding="utf-8"
    ) as file:
        return json.load(file)


N04_FINAL_MODEL_METADATA = load_json_artifact(
    N04_CONTROL_ARTIFACTS[
        "final_model_preparation_metadata"
    ]
)

N04_FINAL_INVENTORY = load_json_artifact(
    N04_CONTROL_ARTIFACTS[
        "final_artifact_inventory"
    ]
)

N04_FINAL_INTEGRITY_MANIFEST = load_json_artifact(
    N04_CONTROL_ARTIFACTS[
        "final_artifact_manifest"
    ]
)

N04_TAXONOMY_METADATA = load_json_artifact(
    N04_CONTROL_ARTIFACTS[
        "taxonomy_metadata"
    ]
)

N04_PARTITION_METADATA = load_json_artifact(
    N04_CONTROL_ARTIFACTS[
        "partition_reproducibility_metadata"
    ]
)

N04_LEAKAGE_METADATA = load_json_artifact(
    N04_CONTROL_ARTIFACTS[
        "final_leakage_validation"
    ]
)

N04_RF_CONFIGURATION = load_json_artifact(
    N04_CONTROL_ARTIFACTS[
        "rf_experiment_configuration"
    ]
)

N04_EXPERIMENT_DESIGN = load_json_artifact(
    N04_CONTROL_ARTIFACTS[
        "experiment_design_metadata"
    ]
)

N04_FINAL_HANDOFF_MANIFEST = load_json_artifact(
    N04_CONTROL_ARTIFACTS[
        "final_n04_handoff_manifest"
    ]
)

N04_SELECTED_FEATURE_METADATA = load_json_artifact(
    N04_CONTROL_ARTIFACTS[
        "selected_features"
    ]
)


print("\n[N04 AUTHORITATIVE METADATA]")
print("✓ Final model-preparation metadata loaded")
print("✓ Final artifact inventory loaded")
print("✓ Final SHA-256 integrity manifest loaded")
print("✓ Final taxonomy metadata loaded")
print("✓ Partition metadata loaded")
print("✓ Leakage-validation metadata loaded")
print("✓ Random Forest experiment configuration loaded")
print("✓ Experiment-design metadata loaded")
print("✓ Final N04 handoff manifest loaded")
print("✓ Authoritative selected-feature metadata loaded")


# ---------------------------------------------------------------
# 10. FINAL N04 TAXONOMY CONTRACT
# ---------------------------------------------------------------

EXPECTED_FEATURE_COUNT = 32

EXPECTED_CLASS_MAPPING = {
    "BENIGN": 0,
    "DDoS": 1,
    "Port Scan": 2,
    "Brute Force": 3,
    "Bot": 4,
    "Web Attack": 5,
    "Infiltration": 6,
    "DoS": 7,
    "Heartbleed": 8,
}

EXPECTED_CLASS_IDS = list(
    range(9)
)

EXPECTED_PARTITION_SHAPES = {

    "Training":
        (
            1_814_018,
            EXPECTED_FEATURE_COUNT
        ),

    "Validation":
        (
            451_215,
            EXPECTED_FEATURE_COUNT
        ),

    "Test":
        (
            565_510,
            EXPECTED_FEATURE_COUNT
        ),
}


if len(EXPECTED_CLASS_MAPPING) != 9:
    raise ValueError(
        "N04 Random Forest taxonomy must contain exactly "
        "nine classes."
    )

if sorted(
    EXPECTED_CLASS_MAPPING.values()
) != EXPECTED_CLASS_IDS:
    raise ValueError(
        "N04 class IDs must be consecutive integers 0–8."
    )


print("\n[N04 TAXONOMY CONTRACT]")

for class_name, class_id in (
    EXPECTED_CLASS_MAPPING.items()
):

    print(
        f"✓ {class_id}: {class_name}"
    )


# ---------------------------------------------------------------
# 11. RECOVER AUTHORITATIVE FEATURE ORDER
# ---------------------------------------------------------------

def recover_feature_order(
    metadata
):

    possible_keys = [
        "selected_features",
        "retained_features",
        "final_features",
        "features",
        "feature_columns",
    ]

    if isinstance(
        metadata,
        list
    ):

        feature_order = metadata

    else:

        feature_order = None

        for key in possible_keys:

            candidate = metadata.get(
                key
            )

            if isinstance(
                candidate,
                list
            ):

                feature_order = candidate
                break

    if feature_order is None:
        raise ValueError(
            "Could not identify the authoritative "
            "N04 selected-feature order."
        )

    feature_order = list(
        feature_order
    )

    if len(feature_order) != EXPECTED_FEATURE_COUNT:
        raise ValueError(
            "The authoritative N04 selected-feature artifact "
            f"contains {len(feature_order)} features instead of "
            f"{EXPECTED_FEATURE_COUNT}."
        )

    if len(set(feature_order)) != len(feature_order):
        raise ValueError(
            "The authoritative N04 feature order contains "
            "duplicate feature names."
        )

    return feature_order


authoritative_feature_order = recover_feature_order(
    N04_SELECTED_FEATURE_METADATA
)


print("\n[FEATURE ORDER CONTRACT]")
print(
    f"✓ Final feature count: "
    f"{len(authoritative_feature_order)}"
)
print("✓ Authoritative N04 feature order recovered")
print("✓ No feature reordering performed")


# ---------------------------------------------------------------
# 12. MEMORY-CONSCIOUS MODEL-READY FEATURE VALIDATION
# ---------------------------------------------------------------

print("\n[MODEL-READY FEATURE VALIDATION]")

feature_shapes = {}

for partition_name, feature_path in {

    "Training":
        RF_INPUT_PATHS["Training features"],

    "Validation":
        RF_INPUT_PATHS["Validation features"],

    "Test":
        RF_INPUT_PATHS["Test features"],

}.items():

    mapped_features = np.load(
        feature_path,
        mmap_mode="r"
    )

    actual_shape = tuple(
        mapped_features.shape
    )

    expected_shape = EXPECTED_PARTITION_SHAPES[
        partition_name
    ]

    if actual_shape != expected_shape:

        del mapped_features

        raise ValueError(
            f"{partition_name} feature artifact has "
            f"shape {actual_shape}; expected "
            f"{expected_shape}."
        )

    if mapped_features.ndim != 2:

        del mapped_features

        raise ValueError(
            f"{partition_name} feature artifact is not "
            "a two-dimensional model-ready matrix."
        )

    feature_shapes[
        partition_name
    ] = actual_shape

    print(
        f"✓ {partition_name:<10}: "
        f"{actual_shape}"
    )

    del mapped_features


print(
    "✓ Training, Validation, and Test feature "
    "artifacts match the N04 contract"
)
print(
    "✓ Feature matrices inspected using memory mapping"
)
print(
    "✓ Complete feature matrices were not loaded into RAM"
)


# ---------------------------------------------------------------
# 13. VALIDATE TARGET ARTIFACTS
# ---------------------------------------------------------------

print("\n[TARGET ARTIFACT VALIDATION]")

target_expected_lengths = {
    "Training": 1_814_018,
    "Validation": 451_215,
    "Test": 565_510,
}


for partition_name, target_path in {

    "Training":
        RF_INPUT_PATHS["Training targets"],

    "Validation":
        RF_INPUT_PATHS["Validation targets"],

    "Test":
        RF_INPUT_PATHS["Test targets"],

}.items():

    mapped_target = np.load(
        target_path,
        mmap_mode="r"
    )

    actual_shape = tuple(
        mapped_target.shape
    )

    expected_shape = (
        target_expected_lengths[
            partition_name
        ],
    )

    if actual_shape != expected_shape:

        del mapped_target

        raise ValueError(
            f"{partition_name} target artifact has "
            f"shape {actual_shape}; expected "
            f"{expected_shape}."
        )

    if mapped_target.ndim != 1:

        del mapped_target

        raise ValueError(
            f"{partition_name} target artifact is not "
            "a one-dimensional label array."
        )

    unique_labels = np.unique(
        mapped_target
    )

    expected_labels = np.array(
        EXPECTED_CLASS_IDS,
        dtype=unique_labels.dtype
    )

    if not np.array_equal(
        unique_labels,
        expected_labels
    ):

        del mapped_target

        raise ValueError(
            f"{partition_name} target artifact does not "
            "contain the complete class-ID set 0–8."
        )

    print(
        f"✓ {partition_name:<10}: "
        f"{actual_shape[0]:,} labels | classes 0–8"
    )

    del mapped_target


print(
    "✓ All N04 target artifacts match the "
    "nine-class taxonomy"
)


# ---------------------------------------------------------------
# 14. VALIDATE RANDOM FOREST EXPERIMENT CONTRACT
# ---------------------------------------------------------------

print("\n[RANDOM FOREST EXPERIMENT CONTRACT]")

if N04_RF_CONFIGURATION.get(
    "model_family"
) != "Random Forest":

    raise ValueError(
        "N04 RF configuration does not identify "
        "the model family as Random Forest."
    )


if int(
    N04_RF_CONFIGURATION.get(
        "candidate_count",
        -1
    )
) != 5:

    raise ValueError(
        "N04 RF configuration does not contain "
        "exactly five candidate strategies."
    )


EXPECTED_RF_STRATEGIES = [
    (
        "RF-0",
        "Natural Distribution Baseline"
    ),
    (
        "RF-1",
        "Balanced Class Weighting"
    ),
    (
        "RF-2",
        "Balanced-Subsample Class Weighting"
    ),
    (
        "RF-3",
        "Controlled Random Oversampling"
    ),
    (
        "RF-4",
        "Controlled SMOTE"
    ),
]


persisted_rf_strategies = [
    (
        strategy.get("strategy_id"),
        strategy.get("strategy_name")
    )
    for strategy in N04_RF_CONFIGURATION.get(
        "strategies",
        []
    )
]


if persisted_rf_strategies != EXPECTED_RF_STRATEGIES:
    raise ValueError(
        "Persisted N04 Random Forest strategies do not "
        "match the established Section 4.9 design.\n"
        f"Expected: {EXPECTED_RF_STRATEGIES}\n"
        f"Observed: {persisted_rf_strategies}"
    )


for strategy_id, strategy_name in (
    EXPECTED_RF_STRATEGIES
):

    print(
        f"✓ {strategy_id}: {strategy_name}"
    )


# ---------------------------------------------------------------
# 15. VALIDATE RF EXPERIMENTAL BOUNDARIES
# ---------------------------------------------------------------

common_boundary = N04_RF_CONFIGURATION.get(
    "common_boundary",
    {}
)

sampling_constraints = N04_RF_CONFIGURATION.get(
    "sampling_constraints",
    {}
)


if common_boundary.get(
    "strategy_selection_partition"
) != "validation":

    raise ValueError(
        "N04 RF strategy selection is not assigned "
        "to the Validation partition."
    )


if common_boundary.get(
    "final_evaluation_partition"
) != "independent_test":

    raise ValueError(
        "N04 RF final evaluation is not assigned "
        "to the Independent Test partition."
    )


if common_boundary.get(
    "optimal_strategy_declared"
) is not False:

    raise ValueError(
        "An optimal RF strategy has already been "
        "declared in the N04 experiment configuration."
    )


if common_boundary.get(
    "model_fitting_performed"
) is not False:

    raise ValueError(
        "N04 RF configuration incorrectly records "
        "model fitting as already performed."
    )


if sampling_constraints.get(
    "validation_sampling"
) is not False:

    raise ValueError(
        "N04 RF configuration does not prohibit "
        "Validation sampling."
    )


if sampling_constraints.get(
    "test_sampling"
) is not False:

    raise ValueError(
        "N04 RF configuration does not prohibit "
        "Test sampling."
    )


print(
    "✓ Validation reserved for RF strategy comparison"
)
print(
    "✓ Independent Test reserved for final evaluation"
)
print(
    "✓ No RF strategy pre-selected as optimal"
)
print(
    "✓ No RF model fitting performed in N04"
)
print(
    "✓ Validation sampling prohibited"
)
print(
    "✓ Test sampling prohibited"
)


# ---------------------------------------------------------------
# 16. VALIDATE FINAL N04 HANDOFF MANIFEST
# ---------------------------------------------------------------

print("\n[FINAL N04 HANDOFF MANIFEST]")

if N04_FINAL_HANDOFF_MANIFEST.get(
    "status"
) != (
    "COMPLETED_AND_READY_FOR_DOWNSTREAM_MODEL_DEVELOPMENT"
):

    raise ValueError(
        "Final N04 handoff manifest does not indicate "
        "completed downstream readiness."
    )


model_preparation_contract = (
    N04_FINAL_HANDOFF_MANIFEST.get(
        "model_preparation_contract",
        {}
    )
)

if model_preparation_contract.get(
    "final_class_count"
) != 9:

    raise ValueError(
        "N04 handoff manifest does not record "
        "the final nine-class taxonomy."
    )


if model_preparation_contract.get(
    "class_id_range"
) != [0, 8]:

    raise ValueError(
        "N04 handoff manifest does not record "
        "class IDs 0–8."
    )


if model_preparation_contract.get(
    "final_feature_count"
) != EXPECTED_FEATURE_COUNT:

    raise ValueError(
        "N04 handoff manifest does not record "
        "the final 32-feature representation."
    )


if model_preparation_contract.get(
    "feature_order_frozen"
) is not True:

    raise ValueError(
        "N04 feature order is not marked as frozen."
    )


if model_preparation_contract.get(
    "taxonomy_frozen"
) is not True:

    raise ValueError(
        "N04 taxonomy is not marked as frozen."
    )


if model_preparation_contract.get(
    "partition_structure_frozen"
) is not True:

    raise ValueError(
        "N04 partition structure is not marked as frozen."
    )


print(
    "✓ N04 handoff status confirms downstream readiness"
)
print(
    "✓ Nine-class taxonomy is frozen"
)
print(
    "✓ Final 32-feature representation is frozen"
)
print(
    "✓ Feature order is frozen"
)
print(
    "✓ Partition structure is frozen"
)


# ---------------------------------------------------------------
# 17. VALIDATE INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION]")

test_protection = (
    N04_FINAL_HANDOFF_MANIFEST.get(
        "independent_test_protection",
        {}
    )
)

required_test_protections = {

    "feature_selection_excluded":
        True,

    "scaler_fitting_excluded":
        True,

    "imbalance_strategy_selection_excluded":
        True,

    "model_fitting_excluded":
        True,

    "hyperparameter_selection_excluded":
        True,

    "resampling_excluded":
        True,

    "synthetic_sampling_excluded":
        True,

    "final_evaluation_only":
        True,
}


for protection_name, expected_value in (
    required_test_protections.items()
):

    if test_protection.get(
        protection_name
    ) is not expected_value:

        raise ValueError(
            "Independent Test protection failure: "
            f"{protection_name}"
        )

    print(
        f"✓ {protection_name}: "
        f"{expected_value}"
    )


# ---------------------------------------------------------------
# 18. VALIDATE N04 INTEGRITY MANIFEST BOUNDARY
# ---------------------------------------------------------------

print("\n[N04 INTEGRITY MANIFEST]")

manifest_entries = N04_FINAL_INTEGRITY_MANIFEST.get(
    "artifacts",
    N04_FINAL_INTEGRITY_MANIFEST.get(
        "manifest",
        []
    )
)


if not isinstance(
    manifest_entries,
    list
):

    raise ValueError(
        "N04 SHA-256 manifest does not contain "
        "a recognizable artifact-entry list."
    )


if len(manifest_entries) != 36:

    raise ValueError(
        "Expected the established 36-entry N04 "
        f"SHA-256 manifest, found {len(manifest_entries)}."
    )


artifact_integrity = (
    N04_FINAL_HANDOFF_MANIFEST.get(
        "artifact_integrity",
        {}
    )
)


if artifact_integrity.get(
    "authoritative_manifest"
) != "final_artifact_manifest.json":

    raise ValueError(
        "N04 handoff does not identify "
        "final_artifact_manifest.json as authoritative."
    )


if artifact_integrity.get(
    "sha256_manifest_entry_count"
) != 36:

    raise ValueError(
        "N04 handoff does not record the expected "
        "36-entry SHA-256 manifest."
    )


if artifact_integrity.get(
    "handoff_manifest_included_in_sha256_manifest"
) is not False:

    raise ValueError(
        "Final N04 handoff manifest must remain "
        "outside the 36-entry integrity manifest."
    )


if artifact_integrity.get(
    "integrity_manifest_modified"
) is not False:

    raise ValueError(
        "N04 integrity manifest is not marked "
        "as unmodified."
    )


print(
    "✓ Authoritative N04 SHA-256 manifest confirmed"
)
print(
    "✓ 36 integrity entries confirmed"
)
print(
    "✓ Final handoff manifest remains outside "
    "the integrity manifest"
)
print(
    "✓ N04 integrity boundary preserved"
)


# ---------------------------------------------------------------
# 19. DOWNSTREAM PROCESSING BOUNDARY
# ---------------------------------------------------------------

print("\n[DOWNSTREAM PROCESSING BOUNDARY]")

print(
    "✓ N04 feature selection remains frozen"
)
print(
    "✓ N04 training-only scaling remains frozen"
)
print(
    "✓ N04 taxonomy remains frozen"
)
print(
    "✓ N04 partition assignments remain frozen"
)
print(
    "✓ N04 target artifacts remain authoritative"
)
print(
    "✓ No N04 preprocessing will be repeated"
)
print(
    "✓ No N04 artifact will be modified"
)


# ---------------------------------------------------------------
# 20. FINAL 5.1 READINESS GATE
# ---------------------------------------------------------------

handoff_readiness_checks = {

    "project_root_valid":
        PROJECT_ROOT.is_dir(),

    "n04_model_preparation_valid":
        MODEL_PREPARATION_V2_DIR.is_dir(),

    "n04_control_artifacts_present":
        all(
            path.is_file()
            for path in N04_CONTROL_ARTIFACTS.values()
        ),

    "rf_input_artifacts_present":
        all(
            path.is_file()
            for path in RF_INPUT_PATHS.values()
        ),

    "feature_count_valid":
        len(authoritative_feature_order) == 32,

    "training_shape_valid":
        feature_shapes["Training"]
        == (1_814_018, 32),

    "validation_shape_valid":
        feature_shapes["Validation"]
        == (451_215, 32),

    "test_shape_valid":
        feature_shapes["Test"]
        == (565_510, 32),

    "class_count_valid":
        len(EXPECTED_CLASS_MAPPING) == 9,

    "rf_strategy_count_valid":
        len(persisted_rf_strategies) == 5,

    "validation_boundary_valid":
        common_boundary.get(
            "strategy_selection_partition"
        ) == "validation",

    "test_boundary_valid":
        common_boundary.get(
            "final_evaluation_partition"
        ) == "independent_test",

    "no_rf_strategy_preselected":
        common_boundary.get(
            "optimal_strategy_declared"
        ) is False,

    "independent_test_protected":
        all(
            test_protection.get(
                key
            ) is value
            for key, value
            in required_test_protections.items()
        ),

    "integrity_manifest_valid":
        len(manifest_entries) == 36,
}


if not all(
    handoff_readiness_checks.values()
):

    failed_checks = [
        name
        for name, passed
        in handoff_readiness_checks.items()
        if not passed
    ]

    raise RuntimeError(
        "Notebook 05 environment/N04 handoff recovery failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 21. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)
print("5.1 — ENVIRONMENT & N04 HANDOFF RECOVERY COMPLETED")
print("=" * 72)

print("\n[FINAL STATUS]")

print(
    "✓ Google Drive mounted"
)
print(
    "✓ Project structure recovered"
)
print(
    "✓ Notebook 05 output structure initialized"
)
print(
    "✓ Final N04 model-preparation directory recovered"
)
print(
    "✓ All N04 control artifacts verified"
)
print(
    "✓ Random Forest input artifacts verified"
)
print(
    "✓ Final 32-feature representation confirmed"
)
print(
    "✓ Nine-class taxonomy confirmed"
)
print(
    "✓ Training/Validation/Test shapes confirmed"
)
print(
    "✓ Authoritative feature order recovered"
)
print(
    "✓ Five Random Forest strategies confirmed"
)
print(
    "✓ Validation reserved for strategy comparison"
)
print(
    "✓ Independent Test reserved for final evaluation"
)
print(
    "✓ Independent Test protection verified"
)
print(
    "✓ N04 36-entry integrity boundary verified"
)
print(
    "✓ No preprocessing or model fitting performed"
)

print(
    "\nNotebook 05 is ready to proceed to "
    "5.2 — Random Forest Input Contract Validation."
)

========================================================================
NOTEBOOK 05 — RANDOM FOREST MODEL DEVELOPMENT
5.1 — ENVIRONMENT & N04 HANDOFF RECOVERY
========================================================================
Mounted at /content/drive

[GOOGLE DRIVE]
✓ Google Drive mounted

[PROJECT STRUCTURE]
✓ Project Root       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System
✓ Data Directory     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/data
✓ Raw Data           : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/data/raw
✓ Processed Data     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/data/processed
✓ Notebooks          : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/notebooks
✓ Outputs            : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs
✓ References         : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/references
✓ Trained Models     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models

[N04 MODEL-PREPARATION BOUNDARY]
✓ N04 Model Preparation : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2

[NOTEBOOK 05 OUTPUT STRUCTURE]
✓ RF Development Output : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development
✓ RF Experiment Config   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/experiment_configuration
✓ RF Strategy Experiments: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments
✓ RF Strategy Selection  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_selection
✓ RF Evaluation          : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation
✓ RF Interpretation      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation
✓ RF Final Model Output  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/final_model
✓ Trained RF Models      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models/random_forest

[REPRODUCIBILITY]
✓ Random Seed : 42

[N04 CONTROL ARTIFACT RECOVERY]
✓ final_model_preparation_metadata: final_model_preparation_metadata.json
✓ final_artifact_inventory: final_artifact_inventory.json
✓ final_artifact_manifest: final_artifact_manifest.json
✓ target_artifact_metadata: target_artifact_metadata.json
✓ taxonomy_metadata: taxonomy_metadata.json
✓ partition_reproducibility_metadata: partition_reproducibility_metadata.json
✓ final_leakage_validation: final_train_validation_test_leakage_validation.json
✓ feature_set_validation: final_feature_set_validation.json
✓ selected_features: correlation_pruned_selected_features.json
✓ training_only_scaler_metadata: training_only_scaler_metadata.json
✓ partition_transformation_metadata: partition_wise_transformation_metadata.json
✓ model_ready_feature_metadata: model_ready_feature_artifacts.json
✓ final_scaling_validation: final_scaling_reproducibility_validation.json
✓ class_imbalance_configuration: class_imbalance_configuration.json
✓ class_imbalance_severity: class_imbalance_severity_metadata.json
✓ rf_experiment_configuration: rf_imbalance_experiment_config.json
✓ lstm_experiment_configuration: lstm_imbalance_experiment_config.json
✓ experiment_design_metadata: imbalance_experiment_design_metadata.json
✓ experiment_matrix: imbalance_experiment_matrix.csv
✓ final_n04_handoff_manifest: final_n04_handoff_manifest.json
✓ All 20 N04 control artifacts are present

[RANDOM FOREST INPUT ARTIFACTS]
✓ Training features: X_train_scaled.npy
✓ Validation features: X_validation_scaled.npy
✓ Test features: X_test_scaled.npy
✓ Training targets: y_train.npy
✓ Validation targets: y_validation.npy
✓ Test targets: y_test.npy
✓ Selected-feature configuration: correlation_pruned_selected_features.json
✓ RF experiment configuration: rf_imbalance_experiment_config.json

[N04 AUTHORITATIVE METADATA]
✓ Final model-preparation metadata loaded
✓ Final artifact inventory loaded
✓ Final SHA-256 integrity manifest loaded
✓ Final taxonomy metadata loaded
✓ Partition metadata loaded
✓ Leakage-validation metadata loaded
✓ Random Forest experiment configuration loaded
✓ Experiment-design metadata loaded
✓ Final N04 handoff manifest loaded
✓ Authoritative selected-feature metadata loaded

[N04 TAXONOMY CONTRACT]
✓ 0: BENIGN
✓ 1: DDoS
✓ 2: Port Scan
✓ 3: Brute Force
✓ 4: Bot
✓ 5: Web Attack
✓ 6: Infiltration
✓ 7: DoS
✓ 8: Heartbleed

[FEATURE ORDER CONTRACT]
✓ Final feature count: 32
✓ Authoritative N04 feature order recovered
✓ No feature reordering performed

[MODEL-READY FEATURE VALIDATION]
✓ Training  : (1814018, 32)
✓ Validation: (451215, 32)
✓ Test      : (565510, 32)
✓ Training, Validation, and Test feature artifacts match the N04 contract
✓ Feature matrices inspected using memory mapping
✓ Complete feature matrices were not loaded into RAM

[TARGET ARTIFACT VALIDATION]
✓ Training  : 1,814,018 labels | classes 0–8
✓ Validation: 451,215 labels | classes 0–8
✓ Test      : 565,510 labels | classes 0–8
✓ All N04 target artifacts match the nine-class taxonomy

[RANDOM FOREST EXPERIMENT CONTRACT]
✓ RF-0: Natural Distribution Baseline
✓ RF-1: Balanced Class Weighting
✓ RF-2: Balanced-Subsample Class Weighting
✓ RF-3: Controlled Random Oversampling
✓ RF-4: Controlled SMOTE
✓ Validation reserved for RF strategy comparison
✓ Independent Test reserved for final evaluation
✓ No RF strategy pre-selected as optimal
✓ No RF model fitting performed in N04
✓ Validation sampling prohibited
✓ Test sampling prohibited

[FINAL N04 HANDOFF MANIFEST]
✓ N04 handoff status confirms downstream readiness
✓ Nine-class taxonomy is frozen
✓ Final 32-feature representation is frozen
✓ Feature order is frozen
✓ Partition structure is frozen

[INDEPENDENT TEST PROTECTION]
✓ feature_selection_excluded: True
✓ scaler_fitting_excluded: True
✓ imbalance_strategy_selection_excluded: True
✓ model_fitting_excluded: True
✓ hyperparameter_selection_excluded: True
✓ resampling_excluded: True
✓ synthetic_sampling_excluded: True
✓ final_evaluation_only: True

[N04 INTEGRITY MANIFEST]
✓ Authoritative N04 SHA-256 manifest confirmed
✓ 36 integrity entries confirmed
✓ Final handoff manifest remains outside the integrity manifest
✓ N04 integrity boundary preserved

[DOWNSTREAM PROCESSING BOUNDARY]
✓ N04 feature selection remains frozen
✓ N04 training-only scaling remains frozen
✓ N04 taxonomy remains frozen
✓ N04 partition assignments remain frozen
✓ N04 target artifacts remain authoritative
✓ No N04 preprocessing will be repeated
✓ No N04 artifact will be modified

========================================================================
5.1 — ENVIRONMENT & N04 HANDOFF RECOVERY COMPLETED
========================================================================

[FINAL STATUS]
✓ Google Drive mounted
✓ Project structure recovered
✓ Notebook 05 output structure initialized
✓ Final N04 model-preparation directory recovered
✓ All N04 control artifacts verified
✓ Random Forest input artifacts verified
✓ Final 32-feature representation confirmed
✓ Nine-class taxonomy confirmed
✓ Training/Validation/Test shapes confirmed
✓ Authoritative feature order recovered
✓ Five Random Forest strategies confirmed
✓ Validation reserved for strategy comparison
✓ Independent Test reserved for final evaluation
✓ Independent Test protection verified
✓ N04 36-entry integrity boundary verified
✓ No preprocessing or model fitting performed

Notebook 05 is ready to proceed to 5.2 — Random Forest Input Contract Validation.

## 5.2 — Random Forest Input Contract Validation

This section formally validates that the finalized model-ready artifacts
recovered from Notebook 04 satisfy the input contract required for
Random Forest model development.

The validation is performed against the immutable N04 model-preparation
boundary established in Section 4.12.1.

The Random Forest input contract consists of:

- 32 finalized model-ready features in the authoritative N04 feature order.
- Nine finalized target classes.
- Training, Validation, and Independent Test partitions with fixed
  observation counts.
- Corresponding feature and target artifacts for each partition.
- A common feature-space representation across all partitions.

The validation is divided into structural, feature-order, numerical,
taxonomy, partition-role, and final readiness checks.

No preprocessing, feature selection, scaling, resampling, model fitting,
hyperparameter tuning, or independent Test evaluation is performed in
this section.

### 5.2.1 — Input Artifact and Shape Validation

This subsection validates the structural integrity of the persisted
Random Forest input artifacts recovered from Notebook 04.

The following model-ready feature and target artifacts are validated:

- Training features and targets
- Validation features and targets
- Independent Test features and targets

The expected model-ready feature representation is:

- Training: 1,814,018 × 32
- Validation: 451,215 × 32
- Independent Test: 565,510 × 32

Each feature artifact must be a two-dimensional numerical matrix with
exactly 32 columns, while each corresponding target artifact must be a
one-dimensional array containing the same number of observations.

This subsection validates only artifact structure and dimensional
alignment. Target class semantics, feature ordering, numerical integrity,
and experimental partition roles are validated in subsequent
subsections.

Large feature matrices are inspected using memory mapping so that the
complete Training, Validation, or Test matrix is not unnecessarily
loaded into RAM.

No data values are modified during this validation.

In [ ]:
# ================================================================
# 5.2.1 — INPUT ARTIFACT AND SHAPE VALIDATION
# ================================================================

import numpy as np

print("=" * 72)
print("5.2.1 — INPUT ARTIFACT AND SHAPE VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. Define the authoritative RF partition structure
# ---------------------------------------------------------------

RF_PARTITION_EXPECTATIONS = {

    "Training": {
        "feature_path": RF_INPUT_PATHS["Training features"],
        "target_path": RF_INPUT_PATHS["Training targets"],
        "expected_feature_shape": (
            1_814_018,
            32
        ),
        "expected_target_shape": (
            1_814_018,
        ),
    },

    "Validation": {
        "feature_path": RF_INPUT_PATHS["Validation features"],
        "target_path": RF_INPUT_PATHS["Validation targets"],
        "expected_feature_shape": (
            451_215,
            32
        ),
        "expected_target_shape": (
            451_215,
        ),
    },

    "Test": {
        "feature_path": RF_INPUT_PATHS["Test features"],
        "target_path": RF_INPUT_PATHS["Test targets"],
        "expected_feature_shape": (
            565_510,
            32
        ),
        "expected_target_shape": (
            565_510,
        ),
    },
}


print("\n[AUTHORITATIVE PARTITION EXPECTATIONS]")

for partition_name, expectation in (
    RF_PARTITION_EXPECTATIONS.items()
):

    print(
        f"✓ {partition_name:<10} "
        f"X = {expectation['expected_feature_shape']} | "
        f"y = {expectation['expected_target_shape']}"
    )


# ---------------------------------------------------------------
# 2. Validate persisted artifact existence and non-zero size
# ---------------------------------------------------------------

print("\n[PERSISTED INPUT ARTIFACT CHECK]")

for partition_name, expectation in (
    RF_PARTITION_EXPECTATIONS.items()
):

    feature_path = expectation[
        "feature_path"
    ]

    target_path = expectation[
        "target_path"
    ]

    if not feature_path.is_file():

        raise FileNotFoundError(
            f"{partition_name} feature artifact was not found:\n"
            f"{feature_path}"
        )

    if not target_path.is_file():

        raise FileNotFoundError(
            f"{partition_name} target artifact was not found:\n"
            f"{target_path}"
        )

    if feature_path.stat().st_size == 0:

        raise ValueError(
            f"{partition_name} feature artifact is empty:\n"
            f"{feature_path}"
        )

    if target_path.stat().st_size == 0:

        raise ValueError(
            f"{partition_name} target artifact is empty:\n"
            f"{target_path}"
        )

    print(
        f"✓ {partition_name:<10} "
        "feature and target artifacts present and non-empty"
    )


# ---------------------------------------------------------------
# 3. Validate feature artifact dimensionality and shape
# ---------------------------------------------------------------

print("\n[FEATURE ARTIFACT SHAPE VALIDATION]")

RF_FEATURE_SHAPES = {}

RF_FEATURE_DTYPES = {}

for partition_name, expectation in (
    RF_PARTITION_EXPECTATIONS.items()
):

    feature_path = expectation[
        "feature_path"
    ]

    # Memory mapping allows structural inspection without loading
    # the complete persisted matrix into RAM.
    mapped_features = np.load(
        feature_path,
        mmap_mode="r"
    )

    actual_shape = tuple(
        mapped_features.shape
    )

    expected_shape = expectation[
        "expected_feature_shape"
    ]

    if mapped_features.ndim != 2:

        del mapped_features

        raise ValueError(
            f"{partition_name} feature artifact must be "
            "two-dimensional.\n"
            f"Observed ndim: {len(actual_shape)}"
        )

    if actual_shape != expected_shape:

        del mapped_features

        raise ValueError(
            f"{partition_name} feature shape mismatch.\n"
            f"Expected: {expected_shape}\n"
            f"Observed: {actual_shape}"
        )

    RF_FEATURE_SHAPES[
        partition_name
    ] = actual_shape

    RF_FEATURE_DTYPES[
        partition_name
    ] = mapped_features.dtype

    print(
        f"✓ {partition_name:<10} "
        f"shape = {actual_shape} | "
        f"dtype = {mapped_features.dtype}"
    )

    del mapped_features


# ---------------------------------------------------------------
# 4. Validate target artifact dimensionality and shape
# ---------------------------------------------------------------

print("\n[TARGET ARTIFACT SHAPE VALIDATION]")

RF_TARGET_SHAPES = {}

RF_TARGET_DTYPES = {}

for partition_name, expectation in (
    RF_PARTITION_EXPECTATIONS.items()
):

    target_path = expectation[
        "target_path"
    ]

    mapped_target = np.load(
        target_path,
        mmap_mode="r"
    )

    actual_shape = tuple(
        mapped_target.shape
    )

    expected_shape = expectation[
        "expected_target_shape"
    ]

    if mapped_target.ndim != 1:

        del mapped_target

        raise ValueError(
            f"{partition_name} target artifact must be "
            "one-dimensional.\n"
            f"Observed shape: {actual_shape}"
        )

    if actual_shape != expected_shape:

        del mapped_target

        raise ValueError(
            f"{partition_name} target shape mismatch.\n"
            f"Expected: {expected_shape}\n"
            f"Observed: {actual_shape}"
        )

    RF_TARGET_SHAPES[
        partition_name
    ] = actual_shape

    RF_TARGET_DTYPES[
        partition_name
    ] = mapped_target.dtype

    print(
        f"✓ {partition_name:<10} "
        f"shape = {actual_shape} | "
        f"dtype = {mapped_target.dtype}"
    )

    del mapped_target


# ---------------------------------------------------------------
# 5. Validate X/y observation alignment
# ---------------------------------------------------------------

print("\n[X/Y OBSERVATION ALIGNMENT]")

for partition_name, expectation in (
    RF_PARTITION_EXPECTATIONS.items()
):

    feature_rows = RF_FEATURE_SHAPES[
        partition_name
    ][0]

    target_rows = RF_TARGET_SHAPES[
        partition_name
    ][0]

    if feature_rows != target_rows:

        raise ValueError(
            f"{partition_name} X/y observation-count mismatch.\n"
            f"Feature rows: {feature_rows:,}\n"
            f"Target rows : {target_rows:,}"
        )

    print(
        f"✓ {partition_name:<10} "
        f"{feature_rows:,} feature rows = "
        f"{target_rows:,} target labels"
    )


# ---------------------------------------------------------------
# 6. Validate common feature dimensionality
# ---------------------------------------------------------------

print("\n[COMMON FEATURE-SPACE DIMENSION]")

feature_counts = {
    partition_name:
        shape[1]
    for partition_name, shape
    in RF_FEATURE_SHAPES.items()
}

if len(
    set(feature_counts.values())
) != 1:

    raise ValueError(
        "Training, Validation, and Test partitions "
        "do not share the same feature dimensionality.\n"
        f"Observed feature counts: {feature_counts}"
    )


common_feature_count = next(
    iter(feature_counts.values())
)

if common_feature_count != 32:

    raise ValueError(
        "The Random Forest input feature space must "
        f"contain exactly 32 features; observed "
        f"{common_feature_count}."
    )


print(
    f"✓ Common feature dimensionality: "
    f"{common_feature_count}"
)
print(
    "✓ Training, Validation, and Test use the "
    "same 32-dimensional feature space"
)


# ---------------------------------------------------------------
# 7. Validate partition-specific expected observations
# ---------------------------------------------------------------

print("\n[PARTITION OBSERVATION COUNTS]")

expected_observation_counts = {
    "Training": 1_814_018,
    "Validation": 451_215,
    "Test": 565_510,
}

for partition_name, expected_count in (
    expected_observation_counts.items()
):

    observed_count = RF_FEATURE_SHAPES[
        partition_name
    ][0]

    if observed_count != expected_count:

        raise ValueError(
            f"{partition_name} observation count mismatch.\n"
            f"Expected: {expected_count:,}\n"
            f"Observed: {observed_count:,}"
        )

    print(
        f"✓ {partition_name:<10}: "
        f"{observed_count:,} observations"
    )


# ---------------------------------------------------------------
# 8. Confirm no artifact modification occurred
# ---------------------------------------------------------------

print("\n[READ-ONLY VALIDATION BOUNDARY]")

print(
    "✓ Feature artifacts were opened in read-only "
    "memory-mapped mode"
)

print(
    "✓ Target artifacts were opened in read-only "
    "memory-mapped mode"
)

print(
    "✓ No feature values were modified"
)

print(
    "✓ No target values were modified"
)

print(
    "✓ No preprocessing was performed"
)

print(
    "✓ No resampling was performed"
)

print(
    "✓ No Random Forest model was fitted"
)


# ---------------------------------------------------------------
# 9. Final subsection validation gate
# ---------------------------------------------------------------

RF_5_2_1_VALIDATION = {

    "training_feature_shape":
        RF_FEATURE_SHAPES["Training"]
        == (1_814_018, 32),

    "validation_feature_shape":
        RF_FEATURE_SHAPES["Validation"]
        == (451_215, 32),

    "test_feature_shape":
        RF_FEATURE_SHAPES["Test"]
        == (565_510, 32),

    "training_target_shape":
        RF_TARGET_SHAPES["Training"]
        == (1_814_018,),

    "validation_target_shape":
        RF_TARGET_SHAPES["Validation"]
        == (451_215,),

    "test_target_shape":
        RF_TARGET_SHAPES["Test"]
        == (565_510,),

    "training_xy_alignment":
        RF_FEATURE_SHAPES["Training"][0]
        == RF_TARGET_SHAPES["Training"][0],

    "validation_xy_alignment":
        RF_FEATURE_SHAPES["Validation"][0]
        == RF_TARGET_SHAPES["Validation"][0],

    "test_xy_alignment":
        RF_FEATURE_SHAPES["Test"][0]
        == RF_TARGET_SHAPES["Test"][0],

    "common_feature_count":
        common_feature_count == 32,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_2_1_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.2.1 Input Artifact and Shape Validation failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 10. Completion status
# ---------------------------------------------------------------

print("\n" + "=" * 72)
print("5.2.1 — INPUT ARTIFACT AND SHAPE VALIDATION PASSED")
print("=" * 72)

print(
    "\n✓ All RF feature artifacts have the expected shapes"
)
print(
    "✓ All RF target artifacts have the expected shapes"
)
print(
    "✓ X/y observation counts are aligned"
)
print(
    "✓ All partitions contain exactly 32 features"
)
print(
    "✓ Training, Validation, and Test dimensions are consistent"
)
print(
    "✓ No persisted N04 artifact was modified"
)

print(
    "\nREADY FOR 5.2.2 — FEATURE ORDER AND "
    "NUMERICAL INTEGRITY VALIDATION"
)

========================================================================
5.2.1 — INPUT ARTIFACT AND SHAPE VALIDATION
========================================================================

[AUTHORITATIVE PARTITION EXPECTATIONS]
✓ Training   X = (1814018, 32) | y = (1814018,)
✓ Validation X = (451215, 32) | y = (451215,)
✓ Test       X = (565510, 32) | y = (565510,)

[PERSISTED INPUT ARTIFACT CHECK]
✓ Training   feature and target artifacts present and non-empty
✓ Validation feature and target artifacts present and non-empty
✓ Test       feature and target artifacts present and non-empty

[FEATURE ARTIFACT SHAPE VALIDATION]
✓ Training   shape = (1814018, 32) | dtype = float32
✓ Validation shape = (451215, 32) | dtype = float32
✓ Test       shape = (565510, 32) | dtype = float32

[TARGET ARTIFACT SHAPE VALIDATION]
✓ Training   shape = (1814018,) | dtype = int64
✓ Validation shape = (451215,) | dtype = int64
✓ Test       shape = (565510,) | dtype = int64

[X/Y OBSERVATION ALIGNMENT]
✓ Training   1,814,018 feature rows = 1,814,018 target labels
✓ Validation 451,215 feature rows = 451,215 target labels
✓ Test       565,510 feature rows = 565,510 target labels

[COMMON FEATURE-SPACE DIMENSION]
✓ Common feature dimensionality: 32
✓ Training, Validation, and Test use the same 32-dimensional feature space

[PARTITION OBSERVATION COUNTS]
✓ Training  : 1,814,018 observations
✓ Validation: 451,215 observations
✓ Test      : 565,510 observations

[READ-ONLY VALIDATION BOUNDARY]
✓ Feature artifacts were opened in read-only memory-mapped mode
✓ Target artifacts were opened in read-only memory-mapped mode
✓ No feature values were modified
✓ No target values were modified
✓ No preprocessing was performed
✓ No resampling was performed
✓ No Random Forest model was fitted

========================================================================
5.2.1 — INPUT ARTIFACT AND SHAPE VALIDATION PASSED
========================================================================

✓ All RF feature artifacts have the expected shapes
✓ All RF target artifacts have the expected shapes
✓ X/y observation counts are aligned
✓ All partitions contain exactly 32 features
✓ Training, Validation, and Test dimensions are consistent
✓ No persisted N04 artifact was modified

READY FOR 5.2.2 — FEATURE ORDER AND NUMERICAL INTEGRITY VALIDATION

### 5.2.2 — Feature Order and Numerical Integrity Validation

This subsection validates the finalized 32-feature representation and its
numerical integrity before Random Forest model development begins.

The authoritative feature order established by Notebook 04 is treated as
immutable. The order recorded by the selected-feature configuration is
cross-validated against the feature-order metadata stored by the
training-only scaler, partition-wise transformation process, and final
model-ready feature artifact.

The validation confirms that:

- Exactly 32 features are present in the finalized feature contract.
- The authoritative feature names are unique.
- The selected-feature order is preserved by the scaler metadata.
- The selected-feature order is preserved by the partition-wise
  transformation metadata.
- The selected-feature order is preserved by the model-ready feature
  metadata.
- Training, Validation, and Independent Test artifacts use the same
  finalized feature dimensionality.
- The persisted model-ready feature arrays use the expected floating-point
  representation.
- No NaN or infinite values are present in any model-ready feature
  partition.
- Numerical values remain unchanged because the artifacts are inspected
  read-only.

Because the model-ready feature arrays contain millions of observations,
numerical integrity is checked using memory-mapped arrays and bounded
row-wise chunks rather than loading complete partitions into RAM.

A chunk-wise numerical scan provides the same complete-partition coverage
for finite-value validation while substantially reducing peak memory
usage.

No feature transformation, feature reordering, scaling, resampling,
model fitting, or artifact modification is performed in this subsection.

In [ ]:
# ================================================================
# 5.2.2 — FEATURE ORDER AND NUMERICAL INTEGRITY VALIDATION
# ================================================================

import json
import numpy as np


print("=" * 72)
print("5.2.2 — FEATURE ORDER AND NUMERICAL INTEGRITY VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. Recover authoritative N04 feature-order metadata
# ---------------------------------------------------------------

print("\n[FEATURE-ORDER METADATA RECOVERY]")


selected_feature_metadata = load_json_artifact(
    N04_CONTROL_ARTIFACTS[
        "selected_features"
    ]
)

training_scaler_metadata = load_json_artifact(
    N04_CONTROL_ARTIFACTS[
        "training_only_scaler_metadata"
    ]
)

partition_transformation_metadata = load_json_artifact(
    N04_CONTROL_ARTIFACTS[
        "partition_transformation_metadata"
    ]
)

model_ready_feature_metadata = load_json_artifact(
    N04_CONTROL_ARTIFACTS[
        "model_ready_feature_metadata"
    ]
)


print(
    "✓ Selected-feature metadata loaded"
)

print(
    "✓ Training-only scaler metadata loaded"
)

print(
    "✓ Partition-wise transformation metadata loaded"
)

print(
    "✓ Model-ready feature metadata loaded"
)


# ---------------------------------------------------------------
# 2. Recover the authoritative selected-feature order
# ---------------------------------------------------------------

def recover_n04_feature_order(
    metadata,
    artifact_name
):
    """
    Recover the feature order using the same metadata conventions
    established by Notebook 04.
    """

    if isinstance(
        metadata,
        list
    ):

        feature_order = list(
            metadata
        )

    elif isinstance(
        metadata,
        dict
    ):

        feature_order = None

        for key in [
            "selected_features",
            "retained_features",
            "features",
            "feature_columns",
        ]:

            candidate = metadata.get(
                key
            )

            if isinstance(
                candidate,
                list
            ):

                feature_order = list(
                    candidate
                )

                break

        if feature_order is None:

            raise ValueError(
                "Could not recover feature order from "
                f"{artifact_name}."
            )

    else:

        raise ValueError(
            f"Unexpected metadata format in "
            f"{artifact_name}."
        )

    return feature_order


RF_FEATURE_ORDER = recover_n04_feature_order(
    selected_feature_metadata,
    "correlation_pruned_selected_features.json"
)


if len(
    RF_FEATURE_ORDER
) != 32:

    raise ValueError(
        "Authoritative N04 feature order contains "
        f"{len(RF_FEATURE_ORDER)} features instead of 32."
    )


if len(
    set(RF_FEATURE_ORDER)
) != len(
    RF_FEATURE_ORDER
):

    raise ValueError(
        "Authoritative N04 feature order contains "
        "duplicate feature names."
    )


if not all(
    isinstance(
        feature_name,
        str
    )
    and feature_name.strip()
    for feature_name in RF_FEATURE_ORDER
):

    raise ValueError(
        "Authoritative N04 feature order contains "
        "invalid or empty feature names."
    )


print(
    f"✓ Authoritative feature order contains "
    f"{len(RF_FEATURE_ORDER)} unique features"
)

print(
    "✓ No duplicate feature names detected"
)


# ---------------------------------------------------------------
# 3. Validate feature-order preservation across N04 metadata
# ---------------------------------------------------------------

print("\n[FEATURE-ORDER CONSISTENCY]")

scaler_feature_order = (
    training_scaler_metadata.get(
        "features"
    )
)

transformation_feature_order = (
    partition_transformation_metadata.get(
        "features"
    )

)

model_ready_feature_order = (
    model_ready_feature_metadata.get(
        "final_feature_order"
    )
)


if not isinstance(
    scaler_feature_order,
    list
):

    raise ValueError(
        "Training-only scaler metadata does not contain "
        "a valid feature-order list."
    )


if not isinstance(
    transformation_feature_order,
    list
):

    raise ValueError(
        "Partition-wise transformation metadata does not "
        "contain a valid feature-order list."
    )


if not isinstance(
    model_ready_feature_order,
    list
):

    raise ValueError(
        "Model-ready feature metadata does not contain "
        "a valid final_feature_order list."
    )


if scaler_feature_order != RF_FEATURE_ORDER:

    raise ValueError(
        "Training-only scaler feature order does not "
        "match the authoritative N04 feature order."
    )


if transformation_feature_order != RF_FEATURE_ORDER:

    raise ValueError(
        "Partition-wise transformation feature order does "
        "not match the authoritative N04 feature order."
    )


if model_ready_feature_order != RF_FEATURE_ORDER:

    raise ValueError(
        "Model-ready feature order does not match the "
        "authoritative N04 feature order."
    )


print(
    "✓ Selected-feature order = scaler metadata order"
)

print(
    "✓ Selected-feature order = transformation metadata order"
)

print(
    "✓ Selected-feature order = model-ready metadata order"
)

print(
    "✓ N04 feature-order chain is internally consistent"
)


# ---------------------------------------------------------------
# 4. Validate model-ready feature-count metadata
# ---------------------------------------------------------------

print("\n[MODEL-READY FEATURE COUNT CONTRACT]")

model_ready_feature_count = (
    model_ready_feature_metadata.get(
        "final_feature_count"
    )
)

if int(
    model_ready_feature_count
) != 32:

    raise ValueError(
        "Model-ready feature metadata records "
        f"{model_ready_feature_count} features instead of 32."
    )


if len(
    model_ready_feature_order
) != int(
    model_ready_feature_count
):

    raise ValueError(
        "Model-ready feature count does not match "
        "its recorded feature order."
    )


print(
    "✓ Model-ready metadata confirms 32 final features"
)

print(
    "✓ Model-ready feature count matches feature order"
)


# ---------------------------------------------------------------
# 5. Numerical integrity configuration
# ---------------------------------------------------------------

print("\n[NUMERICAL INTEGRITY CONFIGURATION]")


# The model-ready N04 artifacts are persisted as float32.
EXPECTED_FEATURE_DTYPE = np.dtype(
    "float32"
)

# The complete arrays are not loaded into RAM.
# 100,000 rows × 32 float32 values ≈ 12.8 MB per chunk.
NUMERICAL_SCAN_CHUNK_ROWS = 100_000


print(
    f"✓ Expected feature dtype: "
    f"{EXPECTED_FEATURE_DTYPE}"
)

print(
    f"✓ Numerical scan chunk size: "
    f"{NUMERICAL_SCAN_CHUNK_ROWS:,} rows"
)

print(
    "✓ Complete feature matrices will remain memory-mapped"
)


# ---------------------------------------------------------------
# 6. Define memory-conscious numerical scan
# ---------------------------------------------------------------

def scan_feature_artifact_numerical_integrity(
    feature_path,
    partition_name,
    chunk_rows=100_000
):
    """
    Scan an N04 model-ready feature artifact in bounded chunks.

    The complete .npy array remains memory-mapped. Only one bounded
    chunk is inspected at a time.

    Returns numerical summary information without creating a full
    in-memory copy of the feature matrix.
    """

    mapped_features = np.load(
        feature_path,
        mmap_mode="r"
    )

    try:

        if mapped_features.ndim != 2:

            raise ValueError(
                f"{partition_name} feature artifact must be "
                "two-dimensional."
            )


        if mapped_features.dtype != (
            EXPECTED_FEATURE_DTYPE
        ):

            raise ValueError(
                f"{partition_name} feature artifact has dtype "
                f"{mapped_features.dtype}; expected "
                f"{EXPECTED_FEATURE_DTYPE}."
            )


        row_count = mapped_features.shape[0]

        column_count = mapped_features.shape[1]


        if column_count != 32:

            raise ValueError(
                f"{partition_name} feature artifact contains "
                f"{column_count} columns instead of 32."
            )


        non_finite_count = 0

        minimum_value = np.inf

        maximum_value = -np.inf

        maximum_absolute_value = 0.0

        scanned_rows = 0


        for start_row in range(
            0,
            row_count,
            chunk_rows
        ):

            end_row = min(
                start_row + chunk_rows,
                row_count
            )


            chunk = mapped_features[
                start_row:end_row
            ]


            # The finite-value mask is restricted to the current
            # bounded chunk rather than the complete dataset.
            finite_mask = np.isfinite(
                chunk
            )


            current_non_finite_count = (
                finite_mask.size
                - np.count_nonzero(
                    finite_mask
                )
            )


            non_finite_count += (
                current_non_finite_count
            )


            if chunk.size > 0:

                chunk_minimum = float(
                    np.min(
                        chunk
                    )
                )

                chunk_maximum = float(
                    np.max(
                        chunk
                    )
                )

                chunk_maximum_absolute = float(
                    np.max(
                        np.abs(
                            chunk
                        )
                    )
                )


                minimum_value = min(
                    minimum_value,
                    chunk_minimum
                )

                maximum_value = max(
                    maximum_value,
                    chunk_maximum
                )

                maximum_absolute_value = max(
                    maximum_absolute_value,
                    chunk_maximum_absolute
                )


            scanned_rows += (
                end_row - start_row
            )


            # Release the temporary finite mask before
            # processing the next chunk.
            del finite_mask
            del chunk


        if scanned_rows != row_count:

            raise RuntimeError(
                f"{partition_name} numerical scan covered "
                f"{scanned_rows:,} rows instead of "
                f"{row_count:,}."
            )


        if non_finite_count != 0:

            raise ValueError(
                f"{partition_name} feature artifact contains "
                f"{non_finite_count:,} NaN/inf values."
            )


        return {
            "partition": partition_name,
            "rows_scanned": int(scanned_rows),
            "features": int(column_count),
            "dtype": str(mapped_features.dtype),
            "non_finite_values": int(
                non_finite_count
            ),
            "minimum": float(
                minimum_value
            ),
            "maximum": float(
                maximum_value
            ),
            "maximum_absolute_value": float(
                maximum_absolute_value
            ),
        }

    finally:

        del mapped_features


# ---------------------------------------------------------------
# 7. Scan Training, Validation, and Test numerically
# ---------------------------------------------------------------

print("\n[CHUNK-WISE NUMERICAL INTEGRITY SCAN]")

RF_NUMERICAL_INTEGRITY_SUMMARY = {}


for partition_name, feature_path in {

    "Training":
        RF_INPUT_PATHS["Training features"],

    "Validation":
        RF_INPUT_PATHS["Validation features"],

    "Test":
        RF_INPUT_PATHS["Test features"],

}.items():

    print(
        f"\nScanning {partition_name}..."
    )

    summary = (
        scan_feature_artifact_numerical_integrity(
            feature_path,
            partition_name,
            chunk_rows=NUMERICAL_SCAN_CHUNK_ROWS
        )
    )

    RF_NUMERICAL_INTEGRITY_SUMMARY[
        partition_name
    ] = summary


    print(
        f"✓ {partition_name:<10} "
        f"{summary['rows_scanned']:,} rows scanned"
    )

    print(
        f"  dtype              : "
        f"{summary['dtype']}"
    )

    print(
        f"  non-finite values  : "
        f"{summary['non_finite_values']:,}"
    )

    print(
        f"  minimum            : "
        f"{summary['minimum']:.6g}"
    )

    print(
        f"  maximum            : "
        f"{summary['maximum']:.6g}"
    )

    print(
        f"  maximum |value|    : "
        f"{summary['maximum_absolute_value']:.6g}"
    )


# ---------------------------------------------------------------
# 8. Confirm complete numerical coverage
# ---------------------------------------------------------------

print("\n[NUMERICAL COVERAGE VALIDATION]")

expected_rows_by_partition = {
    "Training": 1_814_018,
    "Validation": 451_215,
    "Test": 565_510,
}


for partition_name, expected_rows in (
    expected_rows_by_partition.items()
):

    observed_rows = (
        RF_NUMERICAL_INTEGRITY_SUMMARY[
            partition_name
        ]["rows_scanned"]
    )

    if observed_rows != expected_rows:

        raise ValueError(
            f"{partition_name} numerical scan did not "
            "cover the complete persisted partition."
        )

    non_finite_values = (
        RF_NUMERICAL_INTEGRITY_SUMMARY[
            partition_name
        ]["non_finite_values"]
    )

    if non_finite_values != 0:

        raise ValueError(
            f"{partition_name} contains "
            f"{non_finite_values:,} non-finite values."
        )

    print(
        f"✓ {partition_name:<10} "
        f"{observed_rows:,} rows completely scanned | "
        f"0 non-finite values"
    )


# ---------------------------------------------------------------
# 9. Confirm feature dtype consistency
# ---------------------------------------------------------------

print("\n[FEATURE DTYPE CONSISTENCY]")

observed_dtypes = {
    partition_name:
        summary["dtype"]
    for partition_name, summary
    in RF_NUMERICAL_INTEGRITY_SUMMARY.items()
}


if set(
    observed_dtypes.values()
) != {
    str(EXPECTED_FEATURE_DTYPE)
}:

    raise ValueError(
        "Training, Validation, and Test do not all use "
        f"the expected {EXPECTED_FEATURE_DTYPE} representation.\n"
        f"Observed: {observed_dtypes}"
    )


print(
    "✓ Training, Validation, and Test all use float32"
)


# ---------------------------------------------------------------
# 10. Establish the validated RF feature contract
# ---------------------------------------------------------------

RF_FEATURE_CONTRACT = {

    "feature_count":
        len(RF_FEATURE_ORDER),

    "feature_order":
        list(RF_FEATURE_ORDER),

    "dtype":
        str(EXPECTED_FEATURE_DTYPE),

    "numerical_integrity":
        "all finite",

    "numerical_scan_chunk_rows":
        NUMERICAL_SCAN_CHUNK_ROWS,

    "partition_shapes":
        {
            partition_name:
                list(
                    RF_FEATURE_SHAPES[
                        partition_name
                    ]
                )
            for partition_name
            in RF_FEATURE_SHAPES
        },
}


# ---------------------------------------------------------------
# 11. Final 5.2.2 validation gate
# ---------------------------------------------------------------

RF_5_2_2_VALIDATION = {

    "authoritative_feature_count":
        len(RF_FEATURE_ORDER) == 32,

    "feature_names_unique":
        len(
            set(RF_FEATURE_ORDER)
        ) == 32,

    "scaler_feature_order_matches":
        scaler_feature_order == RF_FEATURE_ORDER,

    "transformation_feature_order_matches":
        transformation_feature_order == RF_FEATURE_ORDER,

    "model_ready_feature_order_matches":
        model_ready_feature_order == RF_FEATURE_ORDER,

    "model_ready_feature_count_matches":
        int(
            model_ready_feature_count
        ) == 32,

    "training_dtype_valid":
        RF_NUMERICAL_INTEGRITY_SUMMARY[
            "Training"
        ]["dtype"] == "float32",

    "validation_dtype_valid":
        RF_NUMERICAL_INTEGRITY_SUMMARY[
            "Validation"
        ]["dtype"] == "float32",

    "test_dtype_valid":
        RF_NUMERICAL_INTEGRITY_SUMMARY[
            "Test"
        ]["dtype"] == "float32",

    "training_all_finite":
        RF_NUMERICAL_INTEGRITY_SUMMARY[
            "Training"
        ]["non_finite_values"] == 0,

    "validation_all_finite":
        RF_NUMERICAL_INTEGRITY_SUMMARY[
            "Validation"
        ]["non_finite_values"] == 0,

    "test_all_finite":
        RF_NUMERICAL_INTEGRITY_SUMMARY[
            "Test"
        ]["non_finite_values"] == 0,

    "complete_training_scan":
        RF_NUMERICAL_INTEGRITY_SUMMARY[
            "Training"
        ]["rows_scanned"]
        == 1_814_018,

    "complete_validation_scan":
        RF_NUMERICAL_INTEGRITY_SUMMARY[
            "Validation"
        ]["rows_scanned"]
        == 451_215,

    "complete_test_scan":
        RF_NUMERICAL_INTEGRITY_SUMMARY[
            "Test"
        ]["rows_scanned"]
        == 565_510,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_2_2_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.2.2 Feature Order and Numerical Integrity "
        "Validation failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 12. Final status
# ---------------------------------------------------------------

print("\n" + "=" * 72)
print(
    "5.2.2 — FEATURE ORDER AND NUMERICAL "
    "INTEGRITY VALIDATION PASSED"
)
print("=" * 72)

print(
    "\n✓ Authoritative 32-feature order confirmed"
)

print(
    "✓ Scaler feature order matches N04 feature order"
)

print(
    "✓ Transformation feature order matches N04 feature order"
)

print(
    "✓ Model-ready feature order matches N04 feature order"
)

print(
    "✓ Training, Validation, and Test use float32"
)

print(
    "✓ Complete Training partition scanned"
)

print(
    "✓ Complete Validation partition scanned"
)

print(
    "✓ Complete Independent Test partition scanned"
)

print(
    "✓ No NaN or infinite values detected"
)

print(
    "✓ Numerical validation performed without "
    "loading complete matrices into RAM"
)

print(
    "✓ No feature transformation or reordering performed"
)

print(
    "\nREADY FOR 5.2.3 — TARGET AND CLASS-TAXONOMY VALIDATION"
)

========================================================================
5.2.2 — FEATURE ORDER AND NUMERICAL INTEGRITY VALIDATION
========================================================================

[FEATURE-ORDER METADATA RECOVERY]
✓ Selected-feature metadata loaded
✓ Training-only scaler metadata loaded
✓ Partition-wise transformation metadata loaded
✓ Model-ready feature metadata loaded
✓ Authoritative feature order contains 32 unique features
✓ No duplicate feature names detected

[FEATURE-ORDER CONSISTENCY]
✓ Selected-feature order = scaler metadata order
✓ Selected-feature order = transformation metadata order
✓ Selected-feature order = model-ready metadata order
✓ N04 feature-order chain is internally consistent

[MODEL-READY FEATURE COUNT CONTRACT]
✓ Model-ready metadata confirms 32 final features
✓ Model-ready feature count matches feature order

[NUMERICAL INTEGRITY CONFIGURATION]
✓ Expected feature dtype: float32
✓ Numerical scan chunk size: 100,000 rows
✓ Complete feature matrices will remain memory-mapped

[CHUNK-WISE NUMERICAL INTEGRITY SCAN]

Scanning Training...
✓ Training   1,814,018 rows scanned
  dtype              : float32
  non-finite values  : 0
  minimum            : -4.40194
  maximum            : 64.6434
  maximum |value|    : 64.6434

Scanning Validation...
✓ Validation 451,215 rows scanned
  dtype              : float32
  non-finite values  : 0
  minimum            : -4.40194
  maximum            : 64.6434
  maximum |value|    : 64.6434

Scanning Test...
✓ Test       565,510 rows scanned
  dtype              : float32
  non-finite values  : 0
  minimum            : -4.40194
  maximum            : 64.6434
  maximum |value|    : 64.6434

[NUMERICAL COVERAGE VALIDATION]
✓ Training   1,814,018 rows completely scanned | 0 non-finite values
✓ Validation 451,215 rows completely scanned | 0 non-finite values
✓ Test       565,510 rows completely scanned | 0 non-finite values

[FEATURE DTYPE CONSISTENCY]
✓ Training, Validation, and Test all use float32

========================================================================
5.2.2 — FEATURE ORDER AND NUMERICAL INTEGRITY VALIDATION PASSED
========================================================================

✓ Authoritative 32-feature order confirmed
✓ Scaler feature order matches N04 feature order
✓ Transformation feature order matches N04 feature order
✓ Model-ready feature order matches N04 feature order
✓ Training, Validation, and Test use float32
✓ Complete Training partition scanned
✓ Complete Validation partition scanned
✓ Complete Independent Test partition scanned
✓ No NaN or infinite values detected
✓ Numerical validation performed without loading complete matrices into RAM
✓ No feature transformation or reordering performed

READY FOR 5.2.3 — TARGET AND CLASS-TAXONOMY VALIDATION

### 5.2.3 — Target and Class-Taxonomy Validation

This subsection validates the target-label representation and finalized
classification taxonomy established by Notebook 04.

Notebook 04 consolidated the original CICIDS-2017 attack labels into
eight attack families while retaining BENIGN traffic as a separate
normal-traffic class. The resulting Random Forest classification task
contains nine final classes.

The authoritative class-ID mapping is:

| Class ID | Final Class |
|---:|---|
| 0 | BENIGN |
| 1 | DDoS |
| 2 | Port Scan |
| 3 | Brute Force |
| 4 | Bot |
| 5 | Web Attack |
| 6 | Infiltration |
| 7 | DoS |
| 8 | Heartbleed |

This subsection verifies that the persisted Training, Validation, and
Independent Test target artifacts conform to this finalized taxonomy.

The validation confirms that:

- All target artifacts use the expected integer representation.
- Only class IDs 0–8 are present.
- All nine finalized classes are represented.
- The same class-ID taxonomy is used across Training, Validation, and
  Independent Test partitions.
- Target observation counts remain aligned with their corresponding
  feature partitions.
- Class-support counts are calculated for each partition.
- No target values are modified or remapped during validation.

Because the target arrays contain millions of observations, the complete
arrays are inspected using read-only memory mapping and bounded chunks.
Class-support counts are accumulated incrementally, avoiding unnecessary
RAM usage.

This subsection performs no resampling, class weighting, class merging,
label transformation, model fitting, or Test-set evaluation.

In [ ]:
# ================================================================
# 5.2.3 — TARGET AND CLASS-TAXONOMY VALIDATION
# ================================================================

import numpy as np


print("=" * 72)
print("5.2.3 — TARGET AND CLASS-TAXONOMY VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. Establish the authoritative N04 class taxonomy
# ---------------------------------------------------------------

print("\n[AUTHORITATIVE N04 CLASS TAXONOMY]")


RF_CLASS_MAPPING = {
    0: "BENIGN",
    1: "DDoS",
    2: "Port Scan",
    3: "Brute Force",
    4: "Bot",
    5: "Web Attack",
    6: "Infiltration",
    7: "DoS",
    8: "Heartbleed",
}


EXPECTED_RF_CLASS_IDS = np.arange(
    0,
    9,
    dtype=np.int64
)


if len(RF_CLASS_MAPPING) != 9:

    raise ValueError(
        "The Random Forest taxonomy must contain "
        "exactly nine classes."
    )


if list(
    RF_CLASS_MAPPING.keys()
) != list(
    range(9)
):

    raise ValueError(
        "Random Forest class IDs must be consecutive "
        "integers from 0 through 8."
    )


for class_id, class_name in (
    RF_CLASS_MAPPING.items()
):

    print(
        f"✓ {class_id}: {class_name}"
    )


# ---------------------------------------------------------------
# 2. Cross-check against the N04 taxonomy contract
# ---------------------------------------------------------------

print("\n[N04 TAXONOMY CONTRACT CROSS-CHECK]")


# Notebook 04 stores EXPECTED_CLASS_MAPPING in the form:
#
#     class_name -> class_id
#
# Notebook 05 uses:
#
#     class_id -> class_name
#
# Normalize the N04 mapping before comparison so that both
# representations describe the same authoritative taxonomy.

if not isinstance(
    EXPECTED_CLASS_MAPPING,
    dict
):

    raise ValueError(
        "N04 EXPECTED_CLASS_MAPPING is not a dictionary."
    )


N04_CLASS_MAPPING_BY_ID = {
    int(class_id): str(class_name)
    for class_name, class_id
    in EXPECTED_CLASS_MAPPING.items()
}


if N04_CLASS_MAPPING_BY_ID != RF_CLASS_MAPPING:

    raise ValueError(
        "Notebook 05 Random Forest taxonomy does not match "
        "the authoritative N04 taxonomy contract.\n"
        f"N04 contract normalized: "
        f"{N04_CLASS_MAPPING_BY_ID}\n"
        f"RF contract: {RF_CLASS_MAPPING}"
    )


print(
    "✓ N04 taxonomy normalized from class-name → class-ID"
)

print(
    "✓ RF taxonomy compared using class-ID → class-name"
)

print(
    "✓ RF taxonomy matches the N04 class-ID mapping"
)

print(
    "✓ No class IDs were redefined in Notebook 05"
)


# ---------------------------------------------------------------
# 3. Target validation configuration
# ---------------------------------------------------------------

print("\n[TARGET VALIDATION CONFIGURATION]")


EXPECTED_TARGET_DTYPE = np.dtype(
    "int64"
)

TARGET_SCAN_CHUNK_SIZE = 250_000


print(
    f"✓ Expected target dtype: "
    f"{EXPECTED_TARGET_DTYPE}"
)

print(
    f"✓ Target scan chunk size: "
    f"{TARGET_SCAN_CHUNK_SIZE:,} labels"
)

print(
    "✓ Complete target arrays will remain memory-mapped"
)


# ---------------------------------------------------------------
# 4. Memory-conscious target scanner
# ---------------------------------------------------------------

def validate_target_partition(
    target_path,
    partition_name,
    expected_rows,
    chunk_size=250_000
):
    """
    Validate a persisted N04 target artifact using bounded,
    read-only chunks.

    Returns class-support counts and validation metadata without
    loading the complete target array into RAM.
    """

    mapped_target = np.load(
        target_path,
        mmap_mode="r"
    )

    try:

        # -------------------------------------------------------
        # Basic structural validation
        # -------------------------------------------------------

        if mapped_target.ndim != 1:

            raise ValueError(
                f"{partition_name} target artifact must be "
                "one-dimensional."
            )


        if mapped_target.shape != (
            expected_rows,
        ):

            raise ValueError(
                f"{partition_name} target shape mismatch.\n"
                f"Expected: {(expected_rows,)}\n"
                f"Observed: {mapped_target.shape}"
            )


        if mapped_target.dtype != (
            EXPECTED_TARGET_DTYPE
        ):

            raise ValueError(
                f"{partition_name} target dtype mismatch.\n"
                f"Expected: {EXPECTED_TARGET_DTYPE}\n"
                f"Observed: {mapped_target.dtype}"
            )


        # -------------------------------------------------------
        # Incremental class-support counting
        # -------------------------------------------------------

        class_counts = {
            class_id: 0
            for class_id
            in RF_CLASS_MAPPING
        }


        invalid_label_count = 0

        non_integer_observation_count = 0

        scanned_rows = 0


        for start_row in range(
            0,
            expected_rows,
            chunk_size
        ):

            end_row = min(
                start_row + chunk_size,
                expected_rows
            )


            chunk = mapped_target[
                start_row:end_row
            ]


            # ---------------------------------------------------
            # Since the persisted dtype is int64, labels are
            # inherently integer-valued. This check confirms
            # that property without converting the full target.
            # ---------------------------------------------------

            if not np.issubdtype(
                chunk.dtype,
                np.integer
            ):

                non_integer_observation_count += (
                    chunk.size
                )


            # ---------------------------------------------------
            # Count only the expected nine class IDs.
            # Any remaining labels are invalid.
            # ---------------------------------------------------

            unique_values, counts = np.unique(
                chunk,
                return_counts=True
            )


            for value, count in zip(
                unique_values,
                counts
            ):

                value = int(
                    value
                )

                count = int(
                    count
                )


                if value in class_counts:

                    class_counts[
                        value
                    ] += count

                else:

                    invalid_label_count += count


            scanned_rows += (
                end_row - start_row
            )


            del unique_values
            del counts
            del chunk


        # -------------------------------------------------------
        # Complete coverage check
        # -------------------------------------------------------

        if scanned_rows != expected_rows:

            raise RuntimeError(
                f"{partition_name} target scan covered "
                f"{scanned_rows:,} rows instead of "
                f"{expected_rows:,}."
            )


        # -------------------------------------------------------
        # Invalid-label check
        # -------------------------------------------------------

        if invalid_label_count != 0:

            raise ValueError(
                f"{partition_name} contains "
                f"{invalid_label_count:,} labels outside "
                "the finalized class-ID range 0–8."
            )


        # -------------------------------------------------------
        # Integer representation check
        # -------------------------------------------------------

        if non_integer_observation_count != 0:

            raise ValueError(
                f"{partition_name} contains "
                f"{non_integer_observation_count:,} "
                "non-integer target observations."
            )


        # -------------------------------------------------------
        # All nine classes must be represented
        # -------------------------------------------------------

        missing_classes = [
            class_id
            for class_id, count
            in class_counts.items()
            if count == 0
        ]


        if missing_classes:

            raise ValueError(
                f"{partition_name} is missing expected "
                f"class IDs: {missing_classes}"
            )


        return {
            "partition": partition_name,
            "rows_scanned": int(
                scanned_rows
            ),
            "dtype": str(
                mapped_target.dtype
            ),
            "invalid_labels": int(
                invalid_label_count
            ),
            "non_integer_observations": int(
                non_integer_observation_count
            ),
            "class_counts": {
                int(class_id): int(count)
                for class_id, count
                in class_counts.items()
            },
        }


    finally:

        del mapped_target


# ---------------------------------------------------------------
# 5. Validate all three target partitions
# ---------------------------------------------------------------

print("\n[CHUNK-WISE TARGET TAXONOMY SCAN]")


RF_TARGET_VALIDATION_SUMMARY = {}


RF_TARGET_EXPECTATIONS = {

    "Training": {
        "path":
            RF_INPUT_PATHS[
                "Training targets"
            ],
        "rows":
            1_814_018,
    },

    "Validation": {
        "path":
            RF_INPUT_PATHS[
                "Validation targets"
            ],
        "rows":
            451_215,
    },

    "Test": {
        "path":
            RF_INPUT_PATHS[
                "Test targets"
            ],
        "rows":
            565_510,
    },
}


for partition_name, expectation in (
    RF_TARGET_EXPECTATIONS.items()
):

    print(
        f"\nScanning {partition_name}..."
    )


    validation_summary = (
        validate_target_partition(
            target_path=expectation["path"],
            partition_name=partition_name,
            expected_rows=expectation["rows"],
            chunk_size=TARGET_SCAN_CHUNK_SIZE
        )
    )


    RF_TARGET_VALIDATION_SUMMARY[
        partition_name
    ] = validation_summary


    print(
        f"✓ {partition_name:<10} "
        f"{validation_summary['rows_scanned']:,} "
        "labels scanned"
    )

    print(
        f"  dtype              : "
        f"{validation_summary['dtype']}"
    )

    print(
        f"  invalid labels     : "
        f"{validation_summary['invalid_labels']:,}"
    )

    print(
        f"  non-integer labels : "
        f"{validation_summary['non_integer_observations']:,}"
    )


# ---------------------------------------------------------------
# 6. Display finalized class support by partition
# ---------------------------------------------------------------

print("\n[FINALIZED CLASS SUPPORT]")

for partition_name, summary in (
    RF_TARGET_VALIDATION_SUMMARY.items()
):

    print(
        f"\n{partition_name}"
    )

    total_labels = sum(
        summary["class_counts"].values()
    )


    for class_id, class_name in (
        RF_CLASS_MAPPING.items()
    ):

        count = summary[
            "class_counts"
        ][class_id]

        percentage = (
            count / total_labels
        ) * 100.0


        print(
            f"  {class_id}: "
            f"{class_name:<15} "
            f"{count:>10,} "
            f"({percentage:>8.4f}%)"
        )


# ---------------------------------------------------------------
# 7. Verify class-support totals
# ---------------------------------------------------------------

print("\n[CLASS-SUPPORT TOTAL VALIDATION]")


for partition_name, summary in (
    RF_TARGET_VALIDATION_SUMMARY.items()
):

    expected_rows = RF_TARGET_EXPECTATIONS[
        partition_name
    ]["rows"]


    observed_class_total = sum(
        summary["class_counts"].values()
    )


    if observed_class_total != expected_rows:

        raise ValueError(
            f"{partition_name} class-support total mismatch.\n"
            f"Expected: {expected_rows:,}\n"
            f"Observed: {observed_class_total:,}"
        )


    print(
        f"✓ {partition_name:<10} "
        f"class-support total = "
        f"{observed_class_total:,}"
    )


# ---------------------------------------------------------------
# 8. Verify identical taxonomy across all partitions
# ---------------------------------------------------------------

print("\n[CROSS-PARTITION TAXONOMY CONSISTENCY]")


partition_class_id_sets = {}


for partition_name, summary in (
    RF_TARGET_VALIDATION_SUMMARY.items()
):

    partition_class_id_sets[
        partition_name
    ] = set(
        summary["class_counts"].keys()
    )


for partition_name, class_id_set in (
    partition_class_id_sets.items()
):

    if class_id_set != set(
        RF_CLASS_MAPPING.keys()
    ):

        raise ValueError(
            f"{partition_name} does not contain the "
            "complete finalized class-ID set."
        )


    print(
        f"✓ {partition_name:<10} "
        "uses class IDs 0–8"
    )


# ---------------------------------------------------------------
# 9. Verify target/feature observation alignment
# ---------------------------------------------------------------

print("\n[TARGET / FEATURE OBSERVATION ALIGNMENT]")


for partition_name in (
    "Training",
    "Validation",
    "Test"
):

    feature_rows = RF_FEATURE_SHAPES[
        partition_name
    ][0]

    target_rows = RF_TARGET_VALIDATION_SUMMARY[
        partition_name
    ]["rows_scanned"]


    if feature_rows != target_rows:

        raise ValueError(
            f"{partition_name} feature/target alignment "
            "failed.\n"
            f"Feature rows: {feature_rows:,}\n"
            f"Target rows : {target_rows:,}"
        )


    print(
        f"✓ {partition_name:<10} "
        f"X rows = y rows = "
        f"{target_rows:,}"
    )


# ---------------------------------------------------------------
# 10. Build the validated class metadata
# ---------------------------------------------------------------

RF_VALIDATED_CLASS_METADATA = {

    "class_count":
        len(RF_CLASS_MAPPING),

    "class_id_mapping":
        {
            str(class_id): class_name
            for class_id, class_name
            in RF_CLASS_MAPPING.items()
        },

    "class_ids":
        [
            int(class_id)
            for class_id
            in RF_CLASS_MAPPING.keys()
        ],

    "partition_class_support":
        {
            partition_name: {
                str(class_id): int(count)
                for class_id, count
                in summary["class_counts"].items()
            }
            for partition_name, summary
            in RF_TARGET_VALIDATION_SUMMARY.items()
        },
}


# ---------------------------------------------------------------
# 11. Final 5.2.3 validation gate
# ---------------------------------------------------------------

RF_5_2_3_VALIDATION = {

    "nine_class_taxonomy":
        len(RF_CLASS_MAPPING) == 9,

    "class_ids_0_to_8":
        list(
            RF_CLASS_MAPPING.keys()
        ) == list(
            range(9)
        ),

    "taxonomy_matches_n04":
        RF_CLASS_MAPPING == N04_CLASS_MAPPING_BY_ID,

    "training_target_dtype":
        RF_TARGET_VALIDATION_SUMMARY[
            "Training"
        ]["dtype"] == "int64",

    "validation_target_dtype":
        RF_TARGET_VALIDATION_SUMMARY[
            "Validation"
        ]["dtype"] == "int64",

    "test_target_dtype":
        RF_TARGET_VALIDATION_SUMMARY[
            "Test"
        ]["dtype"] == "int64",

    "training_no_invalid_labels":
        RF_TARGET_VALIDATION_SUMMARY[
            "Training"
        ]["invalid_labels"] == 0,

    "validation_no_invalid_labels":
        RF_TARGET_VALIDATION_SUMMARY[
            "Validation"
        ]["invalid_labels"] == 0,

    "test_no_invalid_labels":
        RF_TARGET_VALIDATION_SUMMARY[
            "Test"
        ]["invalid_labels"] == 0,

    "training_complete_scan":
        RF_TARGET_VALIDATION_SUMMARY[
            "Training"
        ]["rows_scanned"] == 1_814_018,

    "validation_complete_scan":
        RF_TARGET_VALIDATION_SUMMARY[
            "Validation"
        ]["rows_scanned"] == 451_215,

    "test_complete_scan":
        RF_TARGET_VALIDATION_SUMMARY[
            "Test"
        ]["rows_scanned"] == 565_510,

    "training_all_classes_present":
        set(
            RF_TARGET_VALIDATION_SUMMARY[
                "Training"
            ]["class_counts"].keys()
        ) == set(
            RF_CLASS_MAPPING.keys()
        ),

    "validation_all_classes_present":
        set(
            RF_TARGET_VALIDATION_SUMMARY[
                "Validation"
            ]["class_counts"].keys()
        ) == set(
            RF_CLASS_MAPPING.keys()
        ),

    "test_all_classes_present":
        set(
            RF_TARGET_VALIDATION_SUMMARY[
                "Test"
            ]["class_counts"].keys()
        ) == set(
            RF_CLASS_MAPPING.keys()
        ),

    "training_xy_alignment":
        RF_FEATURE_SHAPES[
            "Training"
        ][0]
        == RF_TARGET_VALIDATION_SUMMARY[
            "Training"
        ]["rows_scanned"],

    "validation_xy_alignment":
        RF_FEATURE_SHAPES[
            "Validation"
        ][0]
        == RF_TARGET_VALIDATION_SUMMARY[
            "Validation"
        ]["rows_scanned"],

    "test_xy_alignment":
        RF_FEATURE_SHAPES[
            "Test"
        ][0]
        == RF_TARGET_VALIDATION_SUMMARY[
            "Test"
        ]["rows_scanned"],
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_2_3_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.2.3 Target and Class-Taxonomy Validation failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 12. Final status
# ---------------------------------------------------------------

print("\n" + "=" * 72)
print(
    "5.2.3 — TARGET AND CLASS-TAXONOMY "
    "VALIDATION PASSED"
)
print("=" * 72)

print(
    "\n✓ Final nine-class taxonomy confirmed"
)

print(
    "✓ Class IDs 0–8 confirmed"
)

print(
    "✓ N04 and N05 class mappings are identical"
)

print(
    "✓ Training, Validation, and Test targets "
    "use int64 labels"
)

print(
    "✓ Complete target partitions scanned"
)

print(
    "✓ No invalid class IDs detected"
)

print(
    "✓ All nine classes represented in every partition"
)

print(
    "✓ Feature/target observation counts remain aligned"
)

print(
    "✓ Class-support counts recorded without "
    "loading complete target arrays into RAM"
)

print(
    "✓ No labels were modified or remapped"
)

print(
    "\nREADY FOR 5.2.4 — "
    "TRAINING/VALIDATION/TEST ROLE VALIDATION"
)

========================================================================
5.2.3 — TARGET AND CLASS-TAXONOMY VALIDATION
========================================================================

[AUTHORITATIVE N04 CLASS TAXONOMY]
✓ 0: BENIGN
✓ 1: DDoS
✓ 2: Port Scan
✓ 3: Brute Force
✓ 4: Bot
✓ 5: Web Attack
✓ 6: Infiltration
✓ 7: DoS
✓ 8: Heartbleed

[N04 TAXONOMY CONTRACT CROSS-CHECK]
✓ N04 taxonomy normalized from class-name → class-ID
✓ RF taxonomy compared using class-ID → class-name
✓ RF taxonomy matches the N04 class-ID mapping
✓ No class IDs were redefined in Notebook 05

[TARGET VALIDATION CONFIGURATION]
✓ Expected target dtype: int64
✓ Target scan chunk size: 250,000 labels
✓ Complete target arrays will remain memory-mapped

[CHUNK-WISE TARGET TAXONOMY SCAN]

Scanning Training...
✓ Training   1,814,018 labels scanned
  dtype              : int64
  invalid labels     : 0
  non-integer labels : 0

Scanning Validation...
✓ Validation 451,215 labels scanned
  dtype              : int64
  invalid labels     : 0
  non-integer labels : 0

Scanning Test...
✓ Test       565,510 labels scanned
  dtype              : int64
  invalid labels     : 0
  non-integer labels : 0

[FINALIZED CLASS SUPPORT]

Training
  0: BENIGN           1,448,197 ( 79.8337%)
  1: DDoS                81,968 (  4.5186%)
  2: Port Scan          101,723 (  5.6076%)
  3: Brute Force          9,325 (  0.5141%)
  4: Bot                  1,270 (  0.0700%)
  5: Web Attack           1,389 (  0.0766%)
  6: Infiltration            15 (  0.0008%)
  7: DoS                170,125 (  9.3784%)
  8: Heartbleed               6 (  0.0003%)

Validation
  0: BENIGN             369,501 ( 81.8902%)
  1: DDoS                20,458 (  4.5340%)
  2: Port Scan           25,261 (  5.5984%)
  3: Brute Force          1,862 (  0.4127%)
  4: Bot                    297 (  0.0658%)
  5: Web Attack             363 (  0.0804%)
  6: Infiltration            13 (  0.0029%)
  7: DoS                 33,456 (  7.4146%)
  8: Heartbleed               4 (  0.0009%)

Test
  0: BENIGN             455,399 ( 80.5289%)
  1: DDoS                25,601 (  4.5271%)
  2: Port Scan           31,946 (  5.6491%)
  3: Brute Force          2,648 (  0.4682%)
  4: Bot                    399 (  0.0706%)
  5: Web Attack             428 (  0.0757%)
  6: Infiltration             8 (  0.0014%)
  7: DoS                 49,080 (  8.6789%)
  8: Heartbleed               1 (  0.0002%)

[CLASS-SUPPORT TOTAL VALIDATION]
✓ Training   class-support total = 1,814,018
✓ Validation class-support total = 451,215
✓ Test       class-support total = 565,510

[CROSS-PARTITION TAXONOMY CONSISTENCY]
✓ Training   uses class IDs 0–8
✓ Validation uses class IDs 0–8
✓ Test       uses class IDs 0–8

[TARGET / FEATURE OBSERVATION ALIGNMENT]
✓ Training   X rows = y rows = 1,814,018
✓ Validation X rows = y rows = 451,215
✓ Test       X rows = y rows = 565,510

========================================================================
5.2.3 — TARGET AND CLASS-TAXONOMY VALIDATION PASSED
========================================================================

✓ Final nine-class taxonomy confirmed
✓ Class IDs 0–8 confirmed
✓ N04 and N05 class mappings are identical
✓ Training, Validation, and Test targets use int64 labels
✓ Complete target partitions scanned
✓ No invalid class IDs detected
✓ All nine classes represented in every partition
✓ Feature/target observation counts remain aligned
✓ Class-support counts recorded without loading complete target arrays into RAM
✓ No labels were modified or remapped

READY FOR 5.2.4 — TRAINING/VALIDATION/TEST ROLE VALIDATION

### 5.2.4 — Training/Validation/Test Role Validation

This subsection establishes and validates the experimental role assigned to
each model-ready partition by Notebook 04 and the Random Forest development
protocol.

The partition roles are fixed as follows:

| Partition | Authorized Role |
|---|---|
| Training | Random Forest model fitting and training-only imbalance experiments |
| Validation | RF strategy comparison and final strategy/configuration selection |
| Independent Test | Final evaluation of the selected Random Forest model only |

The Training partition is the only partition available for model fitting and
training-time resampling or class-balancing operations.

The Validation partition is reserved for controlled comparison of the
predefined Random Forest imbalance strategies. It must not be used to fit
candidate models, generate synthetic samples, or otherwise modify the
training distribution.

The Independent Test partition is protected from model development. It is
not used for feature selection, preprocessing fitting, imbalance-strategy
selection, hyperparameter selection, model fitting, or intermediate
performance analysis. It is evaluated only after the Random Forest strategy
and final configuration have been frozen.

This subsection verifies the partition sizes, role assignments, and
independent-test protection conditions established by Notebook 04.

No feature values or target values are modified, no resampling is performed,
and no Random Forest model is fitted in this subsection.

In [ ]:
# ================================================================
# 5.2.4 — TRAINING / VALIDATION / TEST ROLE VALIDATION
# ================================================================

print("=" * 72)
print("5.2.4 — TRAINING/VALIDATION/TEST ROLE VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. Establish the authoritative partition-role contract
# ---------------------------------------------------------------

print("\n[AUTHORITATIVE PARTITION ROLE CONTRACT]")


RF_PARTITION_ROLE_CONTRACT = {

    "Training": {
        "role":
            "model_fitting_and_training_only_imbalance_experiments",

        "allowed_for_model_fitting":
            True,

        "allowed_for_strategy_comparison":
            False,

        "allowed_for_strategy_selection":
            False,

        "allowed_for_final_test_evaluation":
            False,
    },

    "Validation": {
        "role":
            "strategy_comparison_and_selection",

        "allowed_for_model_fitting":
            False,

        "allowed_for_strategy_comparison":
            True,

        "allowed_for_strategy_selection":
            True,

        "allowed_for_final_test_evaluation":
            False,
    },

    "Test": {
        "role":
            "independent_final_evaluation_only",

        "allowed_for_model_fitting":
            False,

        "allowed_for_strategy_comparison":
            False,

        "allowed_for_strategy_selection":
            False,

        "allowed_for_final_test_evaluation":
            True,
    },
}


for partition_name, contract in (
    RF_PARTITION_ROLE_CONTRACT.items()
):

    print(
        f"✓ {partition_name:<10} "
        f"{contract['role']}"
    )


# ---------------------------------------------------------------
# 2. Validate authoritative partition sizes
# ---------------------------------------------------------------

print("\n[PARTITION SIZE CONTRACT]")


EXPECTED_RF_PARTITION_ROWS = {

    "Training":
        1_814_018,

    "Validation":
        451_215,

    "Test":
        565_510,
}


for partition_name, expected_rows in (
    EXPECTED_RF_PARTITION_ROWS.items()
):

    observed_feature_rows = (
        RF_FEATURE_SHAPES[
            partition_name
        ][0]
    )

    observed_target_rows = (
        RF_TARGET_VALIDATION_SUMMARY[
            partition_name
        ]["rows_scanned"]
    )


    if observed_feature_rows != expected_rows:

        raise ValueError(
            f"{partition_name} feature partition size "
            "does not match the authoritative contract.\n"
            f"Expected: {expected_rows:,}\n"
            f"Observed: {observed_feature_rows:,}"
        )


    if observed_target_rows != expected_rows:

        raise ValueError(
            f"{partition_name} target partition size "
            "does not match the authoritative contract.\n"
            f"Expected: {expected_rows:,}\n"
            f"Observed: {observed_target_rows:,}"
        )


    print(
        f"✓ {partition_name:<10} "
        f"{expected_rows:,} observations"
    )


# ---------------------------------------------------------------
# 3. Validate fixed partition dimensionality
# ---------------------------------------------------------------

print("\n[PARTITION DIMENSIONALITY CONTRACT]")


for partition_name in (
    "Training",
    "Validation",
    "Test"
):

    observed_shape = tuple(
        RF_FEATURE_SHAPES[
            partition_name
        ]
    )


    expected_shape = (
        EXPECTED_RF_PARTITION_ROWS[
            partition_name
        ],
        32,
    )


    if observed_shape != expected_shape:

        raise ValueError(
            f"{partition_name} feature shape does not "
            "match the RF handoff contract.\n"
            f"Expected: {expected_shape}\n"
            f"Observed: {observed_shape}"
        )


    print(
        f"✓ {partition_name:<10} "
        f"shape = {observed_shape}"
    )


# ---------------------------------------------------------------
# 4. Validate the Training partition role
# ---------------------------------------------------------------

print("\n[TRAINING ROLE VALIDATION]")


training_contract = (
    RF_PARTITION_ROLE_CONTRACT[
        "Training"
    ]
)


if not training_contract[
    "allowed_for_model_fitting"
]:

    raise RuntimeError(
        "Training partition is not authorized for "
        "model fitting."
    )


if training_contract[
    "allowed_for_strategy_comparison"
]:

    raise RuntimeError(
        "Training partition has an invalid role "
        "configuration."
    )


print(
    "✓ Training is authorized for Random Forest model fitting"
)

print(
    "✓ Training is the authorized partition for "
    "training-only imbalance operations"
)

print(
    "✓ Training is not the strategy-selection partition"
)


# ---------------------------------------------------------------
# 5. Validate the Validation partition role
# ---------------------------------------------------------------

print("\n[VALIDATION ROLE VALIDATION]")


validation_contract = (
    RF_PARTITION_ROLE_CONTRACT[
        "Validation"
    ]
)


if validation_contract[
    "allowed_for_model_fitting"
]:

    raise RuntimeError(
        "Validation partition must not be used as a "
        "model-fitting partition."
    )


if not validation_contract[
    "allowed_for_strategy_comparison"
]:

    raise RuntimeError(
        "Validation partition is not authorized for "
        "strategy comparison."
    )


if not validation_contract[
    "allowed_for_strategy_selection"
]:

    raise RuntimeError(
        "Validation partition is not authorized for "
        "strategy selection."
    )


print(
    "✓ Validation is reserved for RF strategy comparison"
)

print(
    "✓ Validation is authorized for strategy selection"
)

print(
    "✓ Validation is excluded from direct model fitting"
)


# ---------------------------------------------------------------
# 6. Validate the Independent Test role
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST ROLE VALIDATION]")


test_contract = (
    RF_PARTITION_ROLE_CONTRACT[
        "Test"
    ]
)


if test_contract[
    "allowed_for_model_fitting"
]:

    raise RuntimeError(
        "Independent Test partition is incorrectly "
        "authorized for model fitting."
    )


if test_contract[
    "allowed_for_strategy_comparison"
]:

    raise RuntimeError(
        "Independent Test partition is incorrectly "
        "authorized for strategy comparison."
    )


if test_contract[
    "allowed_for_strategy_selection"
]:

    raise RuntimeError(
        "Independent Test partition is incorrectly "
        "authorized for strategy selection."
    )


if not test_contract[
    "allowed_for_final_test_evaluation"
]:

    raise RuntimeError(
        "Independent Test partition is not authorized "
        "for final evaluation."
    )


print(
    "✓ Independent Test is excluded from model fitting"
)

print(
    "✓ Independent Test is excluded from strategy comparison"
)

print(
    "✓ Independent Test is excluded from strategy selection"
)

print(
    "✓ Independent Test is reserved for final evaluation"
)


# ---------------------------------------------------------------
# 7. Validate the RF strategy-selection boundary
# ---------------------------------------------------------------

print("\n[RF STRATEGY-SELECTION BOUNDARY]")


EXPECTED_RF_STRATEGY_COUNT = 5


if (
    "RF_5_2_3_VALIDATION"
    not in globals()
):

    raise RuntimeError(
        "Required preceding validation state "
        "RF_5_2_3_VALIDATION is unavailable."
    )


RF_STRATEGY_SELECTION_BOUNDARY = {

    "candidate_strategy_count":
        EXPECTED_RF_STRATEGY_COUNT,

    "strategy_comparison_partition":
        "Validation",

    "strategy_selection_partition":
        "Validation",

    "model_fitting_partition":
        "Training",

    "independent_test_partition":
        "Test",

    "test_used_for_strategy_selection":
        False,

    "test_used_for_model_fitting":
        False,
}


print(
    "✓ Five predefined RF strategies are evaluated "
    "using the Training/Validation boundary"
)

print(
    "✓ Validation is the strategy-comparison partition"
)

print(
    "✓ Validation is the strategy-selection partition"
)

print(
    "✓ Test is excluded from strategy selection"
)


# ---------------------------------------------------------------
# 8. Validate the independent-test protection boundary
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION BOUNDARY]")


RF_TEST_PROTECTION_CONTRACT = {

    "feature_selection_excluded":
        True,

    "scaler_fitting_excluded":
        True,

    "imbalance_strategy_selection_excluded":
        True,

    "model_fitting_excluded":
        True,

    "hyperparameter_selection_excluded":
        True,

    "intermediate_evaluation_excluded":
        True,

    "final_evaluation_allowed":
        True,
}


for protection_name, protection_status in (
    RF_TEST_PROTECTION_CONTRACT.items()
):

    if not protection_status:

        raise RuntimeError(
            "Independent Test protection contract "
            f"failed: {protection_name}"
        )


    print(
        f"✓ {protection_name}: "
        f"{protection_status}"
    )


# ---------------------------------------------------------------
# 9. Validate that this subsection performs no model operation
# ---------------------------------------------------------------

print("\n[MODEL-DEVELOPMENT BOUNDARY]")


RF_5_2_4_MODEL_OPERATION_FLAGS = {

    "model_fitting_performed":
        False,

    "resampling_performed":
        False,

    "synthetic_sampling_performed":
        False,

    "class_weight_training_performed":
        False,

    "strategy_selected":
        False,

    "test_evaluated":
        False,
}


for operation_name, operation_status in (
    RF_5_2_4_MODEL_OPERATION_FLAGS.items()
):

    if operation_status:

        raise RuntimeError(
            f"Invalid model-development operation detected: "
            f"{operation_name}"
        )


    print(
        f"✓ {operation_name}: "
        f"{operation_status}"
    )


# ---------------------------------------------------------------
# 10. Final role-validation contract
# ---------------------------------------------------------------

RF_5_2_4_VALIDATION = {

    "training_rows_correct":
        EXPECTED_RF_PARTITION_ROWS[
            "Training"
        ] == 1_814_018,

    "validation_rows_correct":
        EXPECTED_RF_PARTITION_ROWS[
            "Validation"
        ] == 451_215,

    "test_rows_correct":
        EXPECTED_RF_PARTITION_ROWS[
            "Test"
        ] == 565_510,

    "training_has_32_features":
        RF_FEATURE_SHAPES[
            "Training"
        ][1] == 32,

    "validation_has_32_features":
        RF_FEATURE_SHAPES[
            "Validation"
        ][1] == 32,

    "test_has_32_features":
        RF_FEATURE_SHAPES[
            "Test"
        ][1] == 32,

    "training_authorized_for_fitting":
        RF_PARTITION_ROLE_CONTRACT[
            "Training"
        ]["allowed_for_model_fitting"],

    "validation_reserved_for_comparison":
        RF_PARTITION_ROLE_CONTRACT[
            "Validation"
        ]["allowed_for_strategy_comparison"],

    "validation_reserved_for_selection":
        RF_PARTITION_ROLE_CONTRACT[
            "Validation"
        ]["allowed_for_strategy_selection"],

    "test_excluded_from_fitting":
        not RF_PARTITION_ROLE_CONTRACT[
            "Test"
        ]["allowed_for_model_fitting"],

    "test_excluded_from_comparison":
        not RF_PARTITION_ROLE_CONTRACT[
            "Test"
        ]["allowed_for_strategy_comparison"],

    "test_excluded_from_selection":
        not RF_PARTITION_ROLE_CONTRACT[
            "Test"
        ]["allowed_for_strategy_selection"],

    "test_reserved_for_final_evaluation":
        RF_PARTITION_ROLE_CONTRACT[
            "Test"
        ]["allowed_for_final_test_evaluation"],

    "test_feature_selection_excluded":
        RF_TEST_PROTECTION_CONTRACT[
            "feature_selection_excluded"
        ],

    "test_scaler_fitting_excluded":
        RF_TEST_PROTECTION_CONTRACT[
            "scaler_fitting_excluded"
        ],

    "test_imbalance_selection_excluded":
        RF_TEST_PROTECTION_CONTRACT[
            "imbalance_strategy_selection_excluded"
        ],

    "test_model_fitting_excluded":
        RF_TEST_PROTECTION_CONTRACT[
            "model_fitting_excluded"
        ],

    "test_hyperparameter_selection_excluded":
        RF_TEST_PROTECTION_CONTRACT[
            "hyperparameter_selection_excluded"
        ],

    "test_intermediate_evaluation_excluded":
        RF_TEST_PROTECTION_CONTRACT[
            "intermediate_evaluation_excluded"
        ],

    "no_model_fitting":
        not RF_5_2_4_MODEL_OPERATION_FLAGS[
            "model_fitting_performed"
        ],

    "no_resampling":
        not RF_5_2_4_MODEL_OPERATION_FLAGS[
            "resampling_performed"
        ],

    "no_synthetic_sampling":
        not RF_5_2_4_MODEL_OPERATION_FLAGS[
            "synthetic_sampling_performed"
        ],

    "no_strategy_selected":
        not RF_5_2_4_MODEL_OPERATION_FLAGS[
            "strategy_selected"
        ],

    "test_not_evaluated":
        not RF_5_2_4_MODEL_OPERATION_FLAGS[
            "test_evaluated"
        ],
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_2_4_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.2.4 Training/Validation/Test Role Validation failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 11. Final status
# ---------------------------------------------------------------

print("\n" + "=" * 72)
print(
    "5.2.4 — TRAINING/VALIDATION/TEST ROLE VALIDATION PASSED"
)
print("=" * 72)

print(
    "\n✓ Training reserved for model fitting and "
    "training-only imbalance experiments"
)

print(
    "✓ Validation reserved for RF strategy comparison "
    "and selection"
)

print(
    "✓ Independent Test excluded from model development"
)

print(
    "✓ Independent Test reserved for final evaluation only"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No strategy selected"
)

print(
    "✓ Test partition not evaluated"
)

print(
    "\nREADY FOR 5.2.5 — Model-Ready Feature Consistency Validation"
)

========================================================================
5.2.4 — TRAINING/VALIDATION/TEST ROLE VALIDATION
========================================================================

[AUTHORITATIVE PARTITION ROLE CONTRACT]
✓ Training   model_fitting_and_training_only_imbalance_experiments
✓ Validation strategy_comparison_and_selection
✓ Test       independent_final_evaluation_only

[PARTITION SIZE CONTRACT]
✓ Training   1,814,018 observations
✓ Validation 451,215 observations
✓ Test       565,510 observations

[PARTITION DIMENSIONALITY CONTRACT]
✓ Training   shape = (1814018, 32)
✓ Validation shape = (451215, 32)
✓ Test       shape = (565510, 32)

[TRAINING ROLE VALIDATION]
✓ Training is authorized for Random Forest model fitting
✓ Training is the authorized partition for training-only imbalance operations
✓ Training is not the strategy-selection partition

[VALIDATION ROLE VALIDATION]
✓ Validation is reserved for RF strategy comparison
✓ Validation is authorized for strategy selection
✓ Validation is excluded from direct model fitting

[INDEPENDENT TEST ROLE VALIDATION]
✓ Independent Test is excluded from model fitting
✓ Independent Test is excluded from strategy comparison
✓ Independent Test is excluded from strategy selection
✓ Independent Test is reserved for final evaluation

[RF STRATEGY-SELECTION BOUNDARY]
✓ Five predefined RF strategies are evaluated using the Training/Validation boundary
✓ Validation is the strategy-comparison partition
✓ Validation is the strategy-selection partition
✓ Test is excluded from strategy selection

[INDEPENDENT TEST PROTECTION BOUNDARY]
✓ feature_selection_excluded: True
✓ scaler_fitting_excluded: True
✓ imbalance_strategy_selection_excluded: True
✓ model_fitting_excluded: True
✓ hyperparameter_selection_excluded: True
✓ intermediate_evaluation_excluded: True
✓ final_evaluation_allowed: True

[MODEL-DEVELOPMENT BOUNDARY]
✓ model_fitting_performed: False
✓ resampling_performed: False
✓ synthetic_sampling_performed: False
✓ class_weight_training_performed: False
✓ strategy_selected: False
✓ test_evaluated: False

========================================================================
5.2.4 — TRAINING/VALIDATION/TEST ROLE VALIDATION PASSED
========================================================================

✓ Training reserved for model fitting and training-only imbalance experiments
✓ Validation reserved for RF strategy comparison and selection
✓ Independent Test excluded from model development
✓ Independent Test reserved for final evaluation only
✓ No model fitting performed
✓ No resampling performed
✓ No strategy selected
✓ Test partition not evaluated

READY FOR 5.2.5 — Model-Ready Feature Consistency Validation

### 5.2.5 — Model-Ready Feature Consistency Validation

This subsection validates the internal consistency of the persisted
model-ready feature representation handed off by Notebook 04 to the
Random Forest development stage.

The model-ready feature artifacts for Training, Validation, and Independent
Test must represent the same finalized 32-dimensional feature space and must
remain consistent with the authoritative N04 feature-selection, scaling, and
partition-wise transformation metadata.

The validation confirms that:

- Training, Validation, and Independent Test feature artifacts exist and
  correspond to the expected model-ready partitions.
- All three feature artifacts contain exactly 32 features.
- All three artifacts use the same `float32` representation.
- The authoritative feature order is consistent across the selected-feature,
  scaler, transformation, and model-ready metadata.
- The model-ready feature metadata records the expected feature count and
  feature order.
- The persisted feature artifact shapes agree with the N04 model-ready
  partition contract.
- The Training, Validation, and Test artifacts therefore represent the same
  model-input feature space.
- No feature transformation, reordering, rescaling, copying, or resampling is
  performed during this validation.

Numerical finite-value integrity was already established in Section 5.2.2.
Therefore, this subsection does not unnecessarily repeat a complete
multi-million-row numerical scan. Instead, it validates the model-ready
representation and its metadata contract while keeping the large arrays
memory-mapped and read-only.

The Independent Test artifact is inspected only for contract consistency and
is not used for model development, strategy selection, or performance
evaluation.

In [ ]:
# ================================================================
# 5.2.5 — MODEL-READY FEATURE CONSISTENCY VALIDATION
# ================================================================

print("=" * 72)
print("5.2.5 — MODEL-READY FEATURE CONSISTENCY VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. Establish the authoritative model-ready feature contract
# ---------------------------------------------------------------

print("\n[AUTHORITATIVE MODEL-READY FEATURE CONTRACT]")


EXPECTED_MODEL_READY_FEATURE_COUNT = 32
EXPECTED_MODEL_READY_DTYPE = np.dtype("float32")

EXPECTED_MODEL_READY_SHAPES = {
    "Training": (1_814_018, 32),
    "Validation": (451_215, 32),
    "Test": (565_510, 32),
}


if len(RF_FEATURE_ORDER) != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "The authoritative RF feature order does not contain "
        "the expected 32 features."
    )


print(
    f"✓ Expected feature count: "
    f"{EXPECTED_MODEL_READY_FEATURE_COUNT}"
)

print(
    f"✓ Expected feature dtype: "
    f"{EXPECTED_MODEL_READY_DTYPE}"
)

print(
    "✓ Authoritative model-ready feature order recovered"
)


# ---------------------------------------------------------------
# 2. Validate model-ready metadata
# ---------------------------------------------------------------

print("\n[MODEL-READY METADATA VALIDATION]")


metadata_feature_count = int(
    model_ready_feature_metadata[
        "final_feature_count"
    ]
)

metadata_feature_order = list(
    model_ready_feature_metadata[
        "final_feature_order"
    ]
)


if metadata_feature_count != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "Model-ready metadata feature count does not match "
        "the RF handoff contract.\n"
        f"Expected: {EXPECTED_MODEL_READY_FEATURE_COUNT}\n"
        f"Observed: {metadata_feature_count}"
    )


if metadata_feature_order != (
    RF_FEATURE_ORDER
):

    raise ValueError(
        "Model-ready metadata feature order does not match "
        "the authoritative N04 feature order."
    )


if len(
    metadata_feature_order
) != len(
    set(metadata_feature_order)
):

    raise ValueError(
        "Model-ready metadata contains duplicate feature names."
    )


print(
    "✓ Model-ready metadata confirms 32 features"
)

print(
    "✓ Model-ready metadata feature order matches "
    "the authoritative N04 feature order"
)

print(
    "✓ Model-ready metadata contains unique feature names"
)


# ---------------------------------------------------------------
# 3. Validate consistency with the N04 scaler contract
# ---------------------------------------------------------------

print("\n[N04 SCALER CONTRACT CONSISTENCY]")


if list(
    training_scaler_metadata["features"]
) != RF_FEATURE_ORDER:

    raise ValueError(
        "Training-only scaler feature order does not match "
        "the authoritative model-ready feature order."
    )


scaler_feature_count = len(
    training_scaler_metadata["features"]
)


if scaler_feature_count != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "Training-only scaler metadata does not contain "
        "the expected 32 features."
    )


print(
    "✓ Training-only scaler uses the same 32-feature order"
)

print(
    "✓ Model-ready feature contract is consistent with "
    "the N04 training-only scaler"
)


# ---------------------------------------------------------------
# 4. Validate consistency with partition-wise transformation
# ---------------------------------------------------------------

print(
    "\n[N04 PARTITION-WISE TRANSFORMATION "
    "CONTRACT CONSISTENCY]"
)


if list(
    partition_transformation_metadata["features"]
) != RF_FEATURE_ORDER:

    raise ValueError(
        "Partition-wise transformation feature order does "
        "not match the authoritative model-ready feature order."
    )


transformation_feature_count = len(
    partition_transformation_metadata[
        "features"
    ]
)


if transformation_feature_count != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "Partition-wise transformation metadata does not "
        "contain the expected 32 features."
    )


print(
    "✓ Partition-wise transformation uses the same "
    "32-feature order"
)

print(
    "✓ Model-ready feature contract is consistent with "
    "the N04 partition-wise transformation"
)


# ---------------------------------------------------------------
# 5. Validate persisted model-ready feature artifacts
# ---------------------------------------------------------------

print("\n[PERSISTED MODEL-READY FEATURE ARTIFACTS]")


RF_MODEL_READY_ARTIFACT_SUMMARY = {}


for partition_name, expected_shape in (
    EXPECTED_MODEL_READY_SHAPES.items()
):

    feature_path = RF_INPUT_PATHS[
        f"{partition_name} features"
    ]


    mapped_features = np.load(
        feature_path,
        mmap_mode="r"
    )


    try:

        observed_shape = tuple(
            mapped_features.shape
        )

        observed_dtype = mapped_features.dtype


        if observed_shape != expected_shape:

            raise ValueError(
                f"{partition_name} model-ready feature "
                "shape mismatch.\n"
                f"Expected: {expected_shape}\n"
                f"Observed: {observed_shape}"
            )


        if observed_dtype != (
            EXPECTED_MODEL_READY_DTYPE
        ):

            raise ValueError(
                f"{partition_name} model-ready feature "
                "dtype mismatch.\n"
                f"Expected: {EXPECTED_MODEL_READY_DTYPE}\n"
                f"Observed: {observed_dtype}"
            )


        RF_MODEL_READY_ARTIFACT_SUMMARY[
            partition_name
        ] = {

            "shape":
                observed_shape,

            "dtype":
                str(observed_dtype),

            "feature_count":
                int(observed_shape[1]),

            "observation_count":
                int(observed_shape[0]),
        }


    finally:

        del mapped_features


    print(
        f"✓ {partition_name:<10} "
        f"shape = {observed_shape} | "
        f"dtype = {observed_dtype}"
    )


# ---------------------------------------------------------------
# 6. Validate common model-input dimensionality
# ---------------------------------------------------------------

print("\n[COMMON MODEL-INPUT FEATURE SPACE]")


observed_feature_counts = {
    partition_name:
        summary["feature_count"]
    for partition_name, summary
    in RF_MODEL_READY_ARTIFACT_SUMMARY.items()
}


if set(
    observed_feature_counts.values()
) != {
    EXPECTED_MODEL_READY_FEATURE_COUNT
}:

    raise ValueError(
        "Training, Validation, and Test do not all "
        "use the same 32-dimensional feature space."
    )


print(
    "✓ Training, Validation, and Test all use "
    "the same 32-dimensional feature space"
)


# ---------------------------------------------------------------
# 7. Validate common numerical representation
# ---------------------------------------------------------------

print("\n[COMMON NUMERICAL REPRESENTATION]")


observed_dtypes = {
    partition_name:
        summary["dtype"]
    for partition_name, summary
    in RF_MODEL_READY_ARTIFACT_SUMMARY.items()
}


if set(
    observed_dtypes.values()
) != {
    str(EXPECTED_MODEL_READY_DTYPE)
}:

    raise ValueError(
        "Training, Validation, and Test do not all use "
        "the same float32 representation."
    )


print(
    "✓ Training, Validation, and Test all use float32"
)


# ---------------------------------------------------------------
# 8. Validate partition sizes against the model-ready contract
# ---------------------------------------------------------------

print("\n[MODEL-READY PARTITION SIZE CONSISTENCY]")


for partition_name, expected_shape in (
    EXPECTED_MODEL_READY_SHAPES.items()
):

    observed_shape = RF_MODEL_READY_ARTIFACT_SUMMARY[
        partition_name
    ]["shape"]


    if observed_shape[0] != expected_shape[0]:

        raise ValueError(
            f"{partition_name} observation count does "
            "not match the N04 model-ready contract."
        )


    print(
        f"✓ {partition_name:<10} "
        f"{observed_shape[0]:,} observations"
    )


# ---------------------------------------------------------------
# 9. Cross-check against the feature artifacts already
#    validated in Sections 5.2.1 and 5.2.2
# ---------------------------------------------------------------

print("\n[PREVIOUSLY VALIDATED FEATURE ARTIFACT "
      "CONSISTENCY]")


for partition_name in (
    "Training",
    "Validation",
    "Test"
):

    current_shape = (
        RF_MODEL_READY_ARTIFACT_SUMMARY[
            partition_name
        ]["shape"]
    )

    previously_validated_shape = tuple(
        RF_FEATURE_SHAPES[
            partition_name
        ]
    )


    if current_shape != (
        previously_validated_shape
    ):

        raise ValueError(
            f"{partition_name} model-ready artifact shape "
            "differs from the shape established in 5.2.1."
        )


    print(
        f"✓ {partition_name:<10} "
        "artifact shape remains consistent with "
        "5.2.1/5.2.2 validation"
    )


# ---------------------------------------------------------------
# 10. Confirm no model-ready artifact modification occurred
# ---------------------------------------------------------------

print("\n[READ-ONLY MODEL-READY BOUNDARY]")


print(
    "✓ Feature artifacts opened using read-only memory mapping"
)

print(
    "✓ No feature values were modified"
)

print(
    "✓ No feature ordering was modified"
)

print(
    "✓ No scaling or transformation was performed"
)

print(
    "✓ No resampling was performed"
)

print(
    "✓ No model was fitted"
)

print(
    "✓ Independent Test was inspected only for "
    "contract consistency"
)


# ---------------------------------------------------------------
# 11. Build consolidated model-ready consistency contract
# ---------------------------------------------------------------

RF_MODEL_READY_CONSISTENCY_CONTRACT = {

    "feature_count":
        EXPECTED_MODEL_READY_FEATURE_COUNT,

    "feature_order":
        list(RF_FEATURE_ORDER),

    "dtype":
        str(EXPECTED_MODEL_READY_DTYPE),

    "training_shape":
        list(
            RF_MODEL_READY_ARTIFACT_SUMMARY[
                "Training"
            ]["shape"]
        ),

    "validation_shape":
        list(
            RF_MODEL_READY_ARTIFACT_SUMMARY[
                "Validation"
            ]["shape"]
        ),

    "test_shape":
        list(
            RF_MODEL_READY_ARTIFACT_SUMMARY[
                "Test"
            ]["shape"]
        ),

    "selected_feature_order_consistent":
        True,

    "scaler_feature_order_consistent":
        True,

    "transformation_feature_order_consistent":
        True,

    "model_ready_metadata_consistent":
        True,

    "partition_feature_space_consistent":
        True,
}


# ---------------------------------------------------------------
# 12. Final 5.2.5 validation gate
# ---------------------------------------------------------------

RF_5_2_5_VALIDATION = {

    "metadata_feature_count_correct":
        metadata_feature_count == 32,

    "metadata_feature_order_correct":
        metadata_feature_order == RF_FEATURE_ORDER,

    "scaler_feature_order_correct":
        list(
            training_scaler_metadata[
                "features"
            ]
        ) == RF_FEATURE_ORDER,

    "transformation_feature_order_correct":
        list(
            partition_transformation_metadata[
                "features"
            ]
        ) == RF_FEATURE_ORDER,

    "training_shape_correct":
        RF_MODEL_READY_ARTIFACT_SUMMARY[
            "Training"
        ]["shape"] == (
            1_814_018,
            32
        ),

    "validation_shape_correct":
        RF_MODEL_READY_ARTIFACT_SUMMARY[
            "Validation"
        ]["shape"] == (
            451_215,
            32
        ),

    "test_shape_correct":
        RF_MODEL_READY_ARTIFACT_SUMMARY[
            "Test"
        ]["shape"] == (
            565_510,
            32
        ),

    "training_dtype_correct":
        RF_MODEL_READY_ARTIFACT_SUMMARY[
            "Training"
        ]["dtype"] == "float32",

    "validation_dtype_correct":
        RF_MODEL_READY_ARTIFACT_SUMMARY[
            "Validation"
        ]["dtype"] == "float32",

    "test_dtype_correct":
        RF_MODEL_READY_ARTIFACT_SUMMARY[
            "Test"
        ]["dtype"] == "float32",

    "all_partitions_same_feature_count":
        all(
            summary["feature_count"] == 32
            for summary
            in RF_MODEL_READY_ARTIFACT_SUMMARY.values()
        ),

    "all_partitions_same_dtype":
        len(
            set(
                observed_dtypes.values()
            )
        ) == 1,

    "all_shapes_match_previous_validation":
        all(
            tuple(
                RF_MODEL_READY_ARTIFACT_SUMMARY[
                    partition_name
                ]["shape"]
            )
            == tuple(
                RF_FEATURE_SHAPES[
                    partition_name
                ]
            )
            for partition_name in (
                "Training",
                "Validation",
                "Test"
            )
        ),
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_2_5_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.2.5 Model-Ready Feature Consistency "
        "Validation failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 13. Final status
# ---------------------------------------------------------------

print("\n" + "=" * 72)
print(
    "5.2.5 — MODEL-READY FEATURE CONSISTENCY "
    "VALIDATION PASSED"
)
print("=" * 72)

print(
    "\n✓ N04 selected-feature contract is consistent"
)

print(
    "✓ N04 scaler feature contract is consistent"
)

print(
    "✓ N04 transformation feature contract is consistent"
)

print(
    "✓ Model-ready metadata is consistent"
)

print(
    "✓ Training, Validation, and Test share the "
    "same 32-feature representation"
)

print(
    "✓ Training, Validation, and Test share "
    "the same float32 representation"
)

print(
    "✓ Persisted partition shapes match the "
    "N04 model-ready contract"
)

print(
    "✓ No model-ready artifact was modified"
)

print(
    "✓ No additional full-dataset numerical scan "
    "was required"
)

print(
    "\nREADY FOR 5.2.6 — RANDOM FOREST READINESS GATE"
)

========================================================================
5.2.5 — MODEL-READY FEATURE CONSISTENCY VALIDATION
========================================================================

[AUTHORITATIVE MODEL-READY FEATURE CONTRACT]
✓ Expected feature count: 32
✓ Expected feature dtype: float32
✓ Authoritative model-ready feature order recovered

[MODEL-READY METADATA VALIDATION]
✓ Model-ready metadata confirms 32 features
✓ Model-ready metadata feature order matches the authoritative N04 feature order
✓ Model-ready metadata contains unique feature names

[N04 SCALER CONTRACT CONSISTENCY]
✓ Training-only scaler uses the same 32-feature order
✓ Model-ready feature contract is consistent with the N04 training-only scaler

[N04 PARTITION-WISE TRANSFORMATION CONTRACT CONSISTENCY]
✓ Partition-wise transformation uses the same 32-feature order
✓ Model-ready feature contract is consistent with the N04 partition-wise transformation

[PERSISTED MODEL-READY FEATURE ARTIFACTS]
✓ Training   shape = (1814018, 32) | dtype = float32
✓ Validation shape = (451215, 32) | dtype = float32
✓ Test       shape = (565510, 32) | dtype = float32

[COMMON MODEL-INPUT FEATURE SPACE]
✓ Training, Validation, and Test all use the same 32-dimensional feature space

[COMMON NUMERICAL REPRESENTATION]
✓ Training, Validation, and Test all use float32

[MODEL-READY PARTITION SIZE CONSISTENCY]
✓ Training   1,814,018 observations
✓ Validation 451,215 observations
✓ Test       565,510 observations

[PREVIOUSLY VALIDATED FEATURE ARTIFACT CONSISTENCY]
✓ Training   artifact shape remains consistent with 5.2.1/5.2.2 validation
✓ Validation artifact shape remains consistent with 5.2.1/5.2.2 validation
✓ Test       artifact shape remains consistent with 5.2.1/5.2.2 validation

[READ-ONLY MODEL-READY BOUNDARY]
✓ Feature artifacts opened using read-only memory mapping
✓ No feature values were modified
✓ No feature ordering was modified
✓ No scaling or transformation was performed
✓ No resampling was performed
✓ No model was fitted
✓ Independent Test was inspected only for contract consistency

========================================================================
5.2.5 — MODEL-READY FEATURE CONSISTENCY VALIDATION PASSED
========================================================================

✓ N04 selected-feature contract is consistent
✓ N04 scaler feature contract is consistent
✓ N04 transformation feature contract is consistent
✓ Model-ready metadata is consistent
✓ Training, Validation, and Test share the same 32-feature representation
✓ Training, Validation, and Test share the same float32 representation
✓ Persisted partition shapes match the N04 model-ready contract
✓ No model-ready artifact was modified
✓ No additional full-dataset numerical scan was required

READY FOR 5.2.6 — RANDOM FOREST READINESS GATE

### 5.2.6 — Random Forest Readiness Gate

This subsection provides the final readiness gate for the Random Forest
input contract established across Sections 5.2.1–5.2.5.

The gate consolidates the validated N04 handoff conditions required for
Random Forest model development, including:

- Presence and dimensional consistency of the model-ready feature and target
  artifacts.
- The finalized 32-feature representation and frozen feature order.
- Numerical and dtype consistency established by the preceding validation
  stages.
- The authoritative nine-class target taxonomy.
- Correct alignment of Training, Validation, and Independent Test partitions.
- Correct experimental roles for Training, Validation, and Test.
- Protection of the Independent Test partition from model development and
  strategy selection.
- Availability of the five predefined Random Forest imbalance strategies.
- Confirmation that no Random Forest model has been fitted during input
  validation.

The Training partition is authorized for Random Forest fitting and
training-only imbalance operations.

The Validation partition is reserved for comparison and selection among the
predefined Random Forest strategies.

The Independent Test partition remains protected until final evaluation after
the Random Forest strategy and configuration have been frozen.

This readiness gate does not modify any N04 artifact, does not perform
resampling or preprocessing, does not fit a model, and does not evaluate the
Independent Test partition.

A successful gate authorizes progression to Section 5.3 — Random Forest
Experimental Configuration.

In [ ]:
# ================================================================
# 5.2.6 — RANDOM FOREST READINESS GATE
# ================================================================

print("=" * 72)
print("5.2.6 — RANDOM FOREST READINESS GATE")
print("=" * 72)


# ---------------------------------------------------------------
# 1. PRECEDING VALIDATION STATE CHECK
# ---------------------------------------------------------------

print("\n[PRECEDING VALIDATION STATE CHECK]")


for validation_name, validation_state in (

    (
        "5.2.1_input_artifact_shape_validation",
        RF_5_2_1_VALIDATION
    ),

    (
        "5.2.2_feature_order_numerical_integrity_validation",
        RF_5_2_2_VALIDATION
    ),

    (
        "5.2.3_target_taxonomy_validation",
        RF_5_2_3_VALIDATION
    ),

    (
        "5.2.4_partition_role_validation",
        RF_5_2_4_VALIDATION
    ),

    (
        "5.2.5_model_ready_consistency_validation",
        RF_5_2_5_VALIDATION
    ),

):

    if not isinstance(
        validation_state,
        dict
    ):

        raise TypeError(
            f"{validation_name} is not a validation dictionary."
        )


    if not all(
        validation_state.values()
    ):

        raise RuntimeError(
            f"{validation_name} contains one or more "
            "failed validation checks."
        )


    print(
        f"✓ {validation_name} passed"
    )


# ---------------------------------------------------------------
# 2. FINAL FEATURE-SPACE CONTRACT
# ---------------------------------------------------------------

print("\n[FINAL FEATURE-SPACE CONTRACT]")


if len(
    RF_FEATURE_ORDER
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise RuntimeError(
        "Final RF feature count does not match "
        "the established N04 model-ready contract."
    )


if len(
    set(RF_FEATURE_ORDER)
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise RuntimeError(
        "Final RF feature order contains duplicate "
        "feature names."
    )


if RF_MODEL_READY_CONSISTENCY_CONTRACT[
    "feature_count"
] != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise RuntimeError(
        "RF model-ready consistency contract reports "
        "an incorrect feature count."
    )


if RF_MODEL_READY_CONSISTENCY_CONTRACT[
    "dtype"
] != str(
    EXPECTED_MODEL_READY_DTYPE
):

    raise RuntimeError(
        "RF model-ready consistency contract reports "
        "an incorrect feature dtype."
    )


print(
    f"✓ Final RF feature count = "
    f"{EXPECTED_MODEL_READY_FEATURE_COUNT}"
)

print(
    "✓ Final RF feature order is unique and frozen"
)

print(
    f"✓ Final RF model-ready dtype = "
    f"{EXPECTED_MODEL_READY_DTYPE}"
)


# ---------------------------------------------------------------
# 3. FINAL PARTITION CONTRACT
# ---------------------------------------------------------------

print("\n[FINAL PARTITION CONTRACT]")


if EXPECTED_RF_PARTITION_ROWS[
    "Training"
] != 1_814_018:

    raise RuntimeError(
        "Training partition size does not match "
        "the authoritative RF contract."
    )


if EXPECTED_RF_PARTITION_ROWS[
    "Validation"
] != 451_215:

    raise RuntimeError(
        "Validation partition size does not match "
        "the authoritative RF contract."
    )


if EXPECTED_RF_PARTITION_ROWS[
    "Test"
] != 565_510:

    raise RuntimeError(
        "Test partition size does not match "
        "the authoritative RF contract."
    )


print(
    "✓ Training    1,814,018 × 32"
)

print(
    "✓ Validation    451,215 × 32"
)

print(
    "✓ Test          565,510 × 32"
)


# ---------------------------------------------------------------
# 4. FINAL TARGET / TAXONOMY CONTRACT
# ---------------------------------------------------------------

print("\n[FINAL TARGET/TAXONOMY CONTRACT]")


if len(
    RF_CLASS_MAPPING
) != 9:

    raise RuntimeError(
        "RF taxonomy does not contain exactly nine classes."
    )


if list(
    RF_CLASS_MAPPING.keys()
) != list(
    EXPECTED_RF_CLASS_IDS
):

    raise RuntimeError(
        "RF class IDs do not match the authoritative "
        "0–8 class-ID contract."
    )


if RF_CLASS_MAPPING != N04_CLASS_MAPPING_BY_ID:

    raise RuntimeError(
        "RF taxonomy does not match the authoritative "
        "N04 taxonomy."
    )


print(
    "✓ Nine-class taxonomy confirmed"
)

for class_id, class_name in (
    RF_CLASS_MAPPING.items()
):

    print(
        f"✓ {class_id}: {class_name}"
    )


# ---------------------------------------------------------------
# 5. TRAINING / VALIDATION / TEST ROLE CONTRACT
# ---------------------------------------------------------------

print(
    "\n[TRAINING / VALIDATION / TEST ROLE CONTRACT]"
)


if not RF_5_2_4_VALIDATION[
    "training_authorized_for_fitting"
]:

    raise RuntimeError(
        "Training is not authorized for Random Forest fitting."
    )


if not RF_5_2_4_VALIDATION[
    "validation_reserved_for_comparison"
]:

    raise RuntimeError(
        "Validation is not reserved for RF strategy comparison."
    )


if not RF_5_2_4_VALIDATION[
    "validation_reserved_for_selection"
]:

    raise RuntimeError(
        "Validation is not reserved for RF strategy selection."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_fitting"
]:

    raise RuntimeError(
        "Independent Test is not protected from model fitting."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_comparison"
]:

    raise RuntimeError(
        "Independent Test is not protected from strategy comparison."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_selection"
]:

    raise RuntimeError(
        "Independent Test is not protected from strategy selection."
    )


if not RF_5_2_4_VALIDATION[
    "test_reserved_for_final_evaluation"
]:

    raise RuntimeError(
        "Independent Test is not reserved for final evaluation."
    )


print(
    "✓ Training reserved for model fitting"
)

print(
    "✓ Validation reserved for strategy comparison"
)

print(
    "✓ Validation reserved for strategy selection"
)

print(
    "✓ Independent Test excluded from model fitting"
)

print(
    "✓ Independent Test excluded from strategy comparison"
)

print(
    "✓ Independent Test excluded from strategy selection"
)

print(
    "✓ Independent Test reserved for final evaluation"
)


# ---------------------------------------------------------------
# 6. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION]")


if not RF_TEST_PROTECTION_CONTRACT[
    "feature_selection_excluded"
]:

    raise RuntimeError(
        "Independent Test was not excluded from "
        "feature selection."
    )


if not RF_TEST_PROTECTION_CONTRACT[
    "scaler_fitting_excluded"
]:

    raise RuntimeError(
        "Independent Test was not excluded from "
        "scaler fitting."
    )


if not RF_TEST_PROTECTION_CONTRACT[
    "imbalance_strategy_selection_excluded"
]:

    raise RuntimeError(
        "Independent Test was not excluded from "
        "imbalance strategy selection."
    )


if not RF_TEST_PROTECTION_CONTRACT[
    "model_fitting_excluded"
]:

    raise RuntimeError(
        "Independent Test was not excluded from "
        "model fitting."
    )


if not RF_TEST_PROTECTION_CONTRACT[
    "hyperparameter_selection_excluded"
]:

    raise RuntimeError(
        "Independent Test was not excluded from "
        "hyperparameter selection."
    )


if not RF_TEST_PROTECTION_CONTRACT[
    "intermediate_evaluation_excluded"
]:

    raise RuntimeError(
        "Independent Test was not excluded from "
        "intermediate evaluation."
    )


if not RF_TEST_PROTECTION_CONTRACT[
    "final_evaluation_allowed"
]:

    raise RuntimeError(
        "Independent Test is not authorized for "
        "final evaluation."
    )


print(
    "✓ Feature selection excluded"
)

print(
    "✓ Scaler fitting excluded"
)

print(
    "✓ Imbalance strategy selection excluded"
)

print(
    "✓ Model fitting excluded"
)

print(
    "✓ Hyperparameter selection excluded"
)

print(
    "✓ Intermediate evaluation excluded"
)

print(
    "✓ Final evaluation remains authorized"
)


# ---------------------------------------------------------------
# 7. RANDOM FOREST STRATEGY CONTRACT
# ---------------------------------------------------------------

print("\n[RANDOM FOREST STRATEGY CONTRACT]")


if EXPECTED_RF_STRATEGY_COUNT != 5:

    raise RuntimeError(
        "Expected RF strategy count is not five."
    )


if len(
    EXPECTED_RF_STRATEGIES
) != EXPECTED_RF_STRATEGY_COUNT:

    raise RuntimeError(
        "The established RF strategy configuration "
        "does not contain five strategies."
    )


if int(
    N04_RF_CONFIGURATION.get(
        "candidate_count",
        -1
    )
) != EXPECTED_RF_STRATEGY_COUNT:

    raise RuntimeError(
        "Persisted N04 RF configuration does not "
        "contain five candidate strategies."
    )


if N04_RF_CONFIGURATION.get(
    "model_family"
) != "Random Forest":

    raise RuntimeError(
        "Persisted N04 experiment configuration is not "
        "identified as Random Forest."
    )


print(
    "✓ RF-0 — Natural Distribution Baseline"
)

print(
    "✓ RF-1 — Balanced Class Weighting"
)

print(
    "✓ RF-2 — Balanced-Subsample Class Weighting"
)

print(
    "✓ RF-3 — Controlled Random Oversampling"
)

print(
    "✓ RF-4 — Controlled SMOTE"
)

print(
    "✓ Five predefined RF strategies confirmed"
)


# ---------------------------------------------------------------
# 8. STRATEGY-SELECTION BOUNDARY
# ---------------------------------------------------------------

print("\n[STRATEGY-SELECTION BOUNDARY]")


if RF_STRATEGY_SELECTION_BOUNDARY[
    "strategy_comparison_partition"
] != "Validation":

    raise RuntimeError(
        "RF strategy comparison is not assigned "
        "to the Validation partition."
    )


if RF_STRATEGY_SELECTION_BOUNDARY[
    "strategy_selection_partition"
] != "Validation":

    raise RuntimeError(
        "RF strategy selection is not assigned "
        "to the Validation partition."
    )


if RF_STRATEGY_SELECTION_BOUNDARY[
    "model_fitting_partition"
] != "Training":

    raise RuntimeError(
        "RF model fitting is not assigned "
        "to the Training partition."
    )


if RF_STRATEGY_SELECTION_BOUNDARY[
    "independent_test_partition"
] != "Test":

    raise RuntimeError(
        "Independent Test partition is not correctly "
        "identified."
    )


if RF_STRATEGY_SELECTION_BOUNDARY[
    "test_used_for_strategy_selection"
]:

    raise RuntimeError(
        "Independent Test is incorrectly marked as "
        "used for strategy selection."
    )


if RF_STRATEGY_SELECTION_BOUNDARY[
    "test_used_for_model_fitting"
]:

    raise RuntimeError(
        "Independent Test is incorrectly marked as "
        "used for model fitting."
    )


print(
    "✓ Training is the model-fitting partition"
)

print(
    "✓ Validation is the strategy-comparison partition"
)

print(
    "✓ Validation is the strategy-selection partition"
)

print(
    "✓ Test is excluded from strategy selection"
)

print(
    "✓ Test is excluded from model fitting"
)


# ---------------------------------------------------------------
# 9. MODEL-DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[MODEL-DEVELOPMENT BOUNDARY]")


if RF_5_2_4_MODEL_OPERATION_FLAGS[
    "model_fitting_performed"
]:

    raise RuntimeError(
        "Random Forest model fitting occurred "
        "during input validation."
    )


if RF_5_2_4_MODEL_OPERATION_FLAGS[
    "resampling_performed"
]:

    raise RuntimeError(
        "Resampling occurred during input validation."
    )


if RF_5_2_4_MODEL_OPERATION_FLAGS[
    "synthetic_sampling_performed"
]:

    raise RuntimeError(
        "Synthetic sampling occurred during input validation."
    )


if RF_5_2_4_MODEL_OPERATION_FLAGS[
    "class_weight_training_performed"
]:

    raise RuntimeError(
        "Class-weight training occurred during "
        "input validation."
    )


if RF_5_2_4_MODEL_OPERATION_FLAGS[
    "strategy_selected"
]:

    raise RuntimeError(
        "An RF strategy was selected during "
        "input validation."
    )


if RF_5_2_4_MODEL_OPERATION_FLAGS[
    "test_evaluated"
]:

    raise RuntimeError(
        "Independent Test was evaluated during "
        "input validation."
    )


print(
    "✓ No Random Forest model has been fitted"
)

print(
    "✓ No resampling has been performed"
)

print(
    "✓ No synthetic sampling has been performed"
)

print(
    "✓ No class-weight training has been performed"
)

print(
    "✓ No RF strategy has been selected"
)

print(
    "✓ Independent Test has not been evaluated"
)


# ---------------------------------------------------------------
# 10. FINAL READINESS GATE
# ---------------------------------------------------------------

print("\n[FINAL RF READINESS GATE]")


print(
    "✓ Input artifact and shape validation passed"
)

print(
    "✓ Feature order and numerical integrity validation passed"
)

print(
    "✓ Target and class-taxonomy validation passed"
)

print(
    "✓ Training/Validation/Test role validation passed"
)

print(
    "✓ Model-ready feature consistency validation passed"
)

print(
    "✓ Nine-class taxonomy confirmed"
)

print(
    "✓ 32-feature model-ready representation confirmed"
)

print(
    "✓ Training partition authorized for model development"
)

print(
    "✓ Validation partition reserved for strategy selection"
)

print(
    "✓ Independent Test remains protected"
)

print(
    "✓ Five RF strategies available for controlled comparison"
)

print(
    "✓ No RF strategy preselected"
)

print(
    "✓ No model fitting or resampling performed"
)


print("\n" + "=" * 72)
print(
    "5.2.6 — RANDOM FOREST READINESS GATE PASSED"
)
print("=" * 72)

print(
    "\nRANDOM FOREST INPUT CONTRACT VALIDATED"
)

print(
    "READY FOR 5.3 — RANDOM FOREST EXPERIMENTAL CONFIGURATION"
)

print("=" * 72)

========================================================================
5.2.6 — RANDOM FOREST READINESS GATE
========================================================================

[PRECEDING VALIDATION STATE CHECK]
✓ 5.2.1_input_artifact_shape_validation passed
✓ 5.2.2_feature_order_numerical_integrity_validation passed
✓ 5.2.3_target_taxonomy_validation passed
✓ 5.2.4_partition_role_validation passed
✓ 5.2.5_model_ready_consistency_validation passed

[FINAL FEATURE-SPACE CONTRACT]
✓ Final RF feature count = 32
✓ Final RF feature order is unique and frozen
✓ Final RF model-ready dtype = float32

[FINAL PARTITION CONTRACT]
✓ Training    1,814,018 × 32
✓ Validation    451,215 × 32
✓ Test          565,510 × 32

[FINAL TARGET/TAXONOMY CONTRACT]
✓ Nine-class taxonomy confirmed
✓ 0: BENIGN
✓ 1: DDoS
✓ 2: Port Scan
✓ 3: Brute Force
✓ 4: Bot
✓ 5: Web Attack
✓ 6: Infiltration
✓ 7: DoS
✓ 8: Heartbleed

[TRAINING / VALIDATION / TEST ROLE CONTRACT]
✓ Training reserved for model fitting
✓ Validation reserved for strategy comparison
✓ Validation reserved for strategy selection
✓ Independent Test excluded from model fitting
✓ Independent Test excluded from strategy comparison
✓ Independent Test excluded from strategy selection
✓ Independent Test reserved for final evaluation

[INDEPENDENT TEST PROTECTION]
✓ Feature selection excluded
✓ Scaler fitting excluded
✓ Imbalance strategy selection excluded
✓ Model fitting excluded
✓ Hyperparameter selection excluded
✓ Intermediate evaluation excluded
✓ Final evaluation remains authorized

[RANDOM FOREST STRATEGY CONTRACT]
✓ RF-0 — Natural Distribution Baseline
✓ RF-1 — Balanced Class Weighting
✓ RF-2 — Balanced-Subsample Class Weighting
✓ RF-3 — Controlled Random Oversampling
✓ RF-4 — Controlled SMOTE
✓ Five predefined RF strategies confirmed

[STRATEGY-SELECTION BOUNDARY]
✓ Training is the model-fitting partition
✓ Validation is the strategy-comparison partition
✓ Validation is the strategy-selection partition
✓ Test is excluded from strategy selection
✓ Test is excluded from model fitting

[MODEL-DEVELOPMENT BOUNDARY]
✓ No Random Forest model has been fitted
✓ No resampling has been performed
✓ No synthetic sampling has been performed
✓ No class-weight training has been performed
✓ No RF strategy has been selected
✓ Independent Test has not been evaluated

[FINAL RF READINESS GATE]
✓ Input artifact and shape validation passed
✓ Feature order and numerical integrity validation passed
✓ Target and class-taxonomy validation passed
✓ Training/Validation/Test role validation passed
✓ Model-ready feature consistency validation passed
✓ Nine-class taxonomy confirmed
✓ 32-feature model-ready representation confirmed
✓ Training partition authorized for model development
✓ Validation partition reserved for strategy selection
✓ Independent Test remains protected
✓ Five RF strategies available for controlled comparison
✓ No RF strategy preselected
✓ No model fitting or resampling performed

========================================================================
5.2.6 — RANDOM FOREST READINESS GATE PASSED
========================================================================

RANDOM FOREST INPUT CONTRACT VALIDATED
READY FOR 5.3 — RANDOM FOREST EXPERIMENTAL CONFIGURATION
========================================================================

## 5.3 — Random Forest Experimental Configuration

This section establishes the common experimental configuration used by all
Random Forest candidates evaluated in Notebook 05.

The configuration is applied consistently across RF-0 through RF-4 so that
differences in validation performance can be attributed to the investigated
imbalance-handling strategy rather than unrelated model settings.

The configuration includes:

- Common Random Forest hyperparameters.
- The established project random seed.
- A common feature-space and nine-class output contract.
- Consistent computational settings across candidate strategies.
- Separation between model configuration and strategy-specific imbalance
  handling.

The Random Forest model is configured once at the experimental level.
Strategy-specific changes such as class weighting, controlled oversampling,
and controlled SMOTE are introduced only within their respective experimental
stages.

No model is fitted in this section.

No Training, Validation, or Independent Test observations are modified,
resampled, or loaded into RAM solely for configuration purposes.

The Independent Test partition remains completely excluded from all
configuration decisions.

### 5.3.1 — Common Random Forest Model Configuration

This subsection defines the common Random Forest model configuration shared
by RF-0 through RF-4.

The purpose is to ensure that all five imbalance strategies are compared under
the same underlying Random Forest model structure. Only the imbalance-handling
mechanism is allowed to vary between strategy experiments.

The common configuration uses:

- 100 decision trees.
- Square-root feature selection at each split.
- No fixed maximum tree depth.
- Bootstrap sampling enabled by the Random Forest implementation.
- Full available CPU parallelism through `n_jobs=-1`.
- The established project random seed (`RANDOM_SEED = 42`).

The class-weight parameter is deliberately not fixed here because it is a
strategy-specific experimental variable:

- RF-0 uses no class weighting.
- RF-1 uses balanced class weighting.
- RF-2 uses balanced-subsample class weighting.
- RF-3 uses controlled random oversampling.
- RF-4 uses controlled SMOTE.

Therefore, the common configuration defines the underlying Random Forest
structure while imbalance handling remains isolated to the individual
strategy experiments.

No model fitting is performed in this subsection.

In [ ]:
# ================================================================
# 5.3.1 — COMMON RANDOM FOREST MODEL CONFIGURATION
# ================================================================

from sklearn.ensemble import RandomForestClassifier


print("=" * 72)
print("5.3.1 — COMMON RANDOM FOREST MODEL CONFIGURATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. COMMON RANDOM FOREST CONFIGURATION
# ---------------------------------------------------------------

print("\n[COMMON RANDOM FOREST CONFIGURATION]")


RF_COMMON_CONFIGURATION = {
    "n_estimators": 100,
    "max_features": "sqrt",
    "max_depth": None,
    "bootstrap": True,
    "n_jobs": -1,
    "random_state": RANDOM_SEED,
}


print(
    f"✓ Number of trees        : "
    f"{RF_COMMON_CONFIGURATION['n_estimators']}"
)

print(
    f"✓ Max features           : "
    f"{RF_COMMON_CONFIGURATION['max_features']}"
)

print(
    f"✓ Max depth              : "
    f"{RF_COMMON_CONFIGURATION['max_depth']}"
)

print(
    f"✓ Bootstrap sampling     : "
    f"{RF_COMMON_CONFIGURATION['bootstrap']}"
)

print(
    f"✓ CPU parallelism        : "
    f"{RF_COMMON_CONFIGURATION['n_jobs']}"
)

print(
    f"✓ Random seed            : "
    f"{RF_COMMON_CONFIGURATION['random_state']}"
)


# ---------------------------------------------------------------
# 2. STRATEGY-SPECIFIC PARAMETERS REMAIN SEPARATE
# ---------------------------------------------------------------

print("\n[STRATEGY-SPECIFIC PARAMETER BOUNDARY]")

print(
    "✓ Class weighting is not fixed in the common configuration"
)

print(
    "✓ RF-0 will use the natural class distribution"
)

print(
    "✓ RF-1 will use balanced class weighting"
)

print(
    "✓ RF-2 will use balanced-subsample class weighting"
)

print(
    "✓ RF-3 will use controlled random oversampling"
)

print(
    "✓ RF-4 will use controlled SMOTE"
)


# ---------------------------------------------------------------
# 3. VERIFY COMMON CONFIGURATION AGAINST PROJECT CONTRACT
# ---------------------------------------------------------------

print("\n[COMMON CONFIGURATION VALIDATION]")


if RF_COMMON_CONFIGURATION[
    "random_state"
] != RANDOM_SEED:

    raise RuntimeError(
        "Random Forest random_state does not match "
        "the established project RANDOM_SEED."
    )


if RF_COMMON_CONFIGURATION[
    "n_estimators"
] != 100:

    raise RuntimeError(
        "Unexpected number of Random Forest trees."
    )


if RF_COMMON_CONFIGURATION[
    "max_features"
] != "sqrt":

    raise RuntimeError(
        "Unexpected Random Forest max_features configuration."
    )


if RF_COMMON_CONFIGURATION[
    "max_depth"
] is not None:

    raise RuntimeError(
        "Unexpected Random Forest max_depth configuration."
    )


if RF_COMMON_CONFIGURATION[
    "bootstrap"
] is not True:

    raise RuntimeError(
        "Random Forest bootstrap sampling must remain enabled."
    )


if RF_COMMON_CONFIGURATION[
    "n_jobs"
] != -1:

    raise RuntimeError(
        "Random Forest CPU parallelism configuration is incorrect."
    )


print("✓ Common Random Forest configuration is valid")
print("✓ Established project random seed is preserved")
print("✓ Strategy-specific imbalance parameters remain separate")


# ---------------------------------------------------------------
# 4. CONFIGURATION OBJECT CONSTRUCTION CHECK
# ---------------------------------------------------------------

print("\n[MODEL CONSTRUCTION CHECK]")


RF_COMMON_MODEL = RandomForestClassifier(
    **RF_COMMON_CONFIGURATION
)


if not isinstance(
    RF_COMMON_MODEL,
    RandomForestClassifier
):

    raise TypeError(
        "RF_COMMON_MODEL was not created as a "
        "RandomForestClassifier."
    )


print(
    "✓ RandomForestClassifier configuration object "
    "created successfully"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No Training observations loaded into RAM"
)

print(
    "✓ No Validation observations loaded into RAM"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 5. FINAL SUBSECTION VALIDATION
# ---------------------------------------------------------------

print("\n" + "=" * 72)
print(
    "5.3.1 — COMMON RANDOM FOREST MODEL CONFIGURATION PASSED"
)
print("=" * 72)

print(
    "\nREADY FOR 5.3.2 — REPRODUCIBILITY AND RANDOM-SEED CONTROL"
)

========================================================================
5.3.1 — COMMON RANDOM FOREST MODEL CONFIGURATION
========================================================================

[COMMON RANDOM FOREST CONFIGURATION]
✓ Number of trees        : 100
✓ Max features           : sqrt
✓ Max depth              : None
✓ Bootstrap sampling     : True
✓ CPU parallelism        : -1
✓ Random seed            : 42

[STRATEGY-SPECIFIC PARAMETER BOUNDARY]
✓ Class weighting is not fixed in the common configuration
✓ RF-0 will use the natural class distribution
✓ RF-1 will use balanced class weighting
✓ RF-2 will use balanced-subsample class weighting
✓ RF-3 will use controlled random oversampling
✓ RF-4 will use controlled SMOTE

[COMMON CONFIGURATION VALIDATION]
✓ Common Random Forest configuration is valid
✓ Established project random seed is preserved
✓ Strategy-specific imbalance parameters remain separate

[MODEL CONSTRUCTION CHECK]
✓ RandomForestClassifier configuration object created successfully
✓ No model fitting performed
✓ No Training observations loaded into RAM
✓ No Validation observations loaded into RAM
✓ Independent Test remains untouched

========================================================================
5.3.1 — COMMON RANDOM FOREST MODEL CONFIGURATION PASSED
========================================================================

READY FOR 5.3.2 — REPRODUCIBILITY AND RANDOM-SEED CONTROL

### 5.3.2 — Reproducibility and Random-State Configuration

This subsection establishes and validates the reproducibility controls for
Random Forest model development.

The project-level random seed established during Notebook 04 is retained as
the authoritative seed for Notebook 05. The same seed is propagated to the
common Random Forest configuration so that candidate experiments can be
reproduced under the same experimental conditions.

The reproducibility configuration includes:

- Preservation of the established project random seed (`RANDOM_SEED = 42`).
- Consistent use of the seed in the common Random Forest configuration.
- Consistent seed assignment in the instantiated Random Forest model.
- Reproducible NumPy and Python random-state initialization for downstream
  experimental operations.

Random-state control is established before model fitting or imbalance
experiments begin.

No Training, Validation, or Independent Test observations are loaded or
modified in this subsection.

No Random Forest model is fitted in this subsection.

In [ ]:
# ================================================================
# 5.3.2 — REPRODUCIBILITY AND RANDOM-STATE CONFIGURATION
# ================================================================

import random
import numpy as np


print("=" * 72)
print("5.3.2 — REPRODUCIBILITY AND RANDOM-STATE CONFIGURATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. PROJECT RANDOM-SEED VALIDATION
# ---------------------------------------------------------------

print("\n[PROJECT RANDOM-SEED VALIDATION]")

print(f"✓ Established project random seed : {RANDOM_SEED}")

if RANDOM_SEED != 42:
    raise RuntimeError(
        "The established project RANDOM_SEED does not match "
        "the validated Notebook 04 seed of 42."
    )

print("✓ RANDOM_SEED = 42 confirmed")


# ---------------------------------------------------------------
# 2. COMMON RF RANDOM-STATE VALIDATION
# ---------------------------------------------------------------

print("\n[COMMON RF RANDOM-STATE VALIDATION]")

if RF_COMMON_CONFIGURATION["random_state"] != RANDOM_SEED:
    raise RuntimeError(
        "Random Forest random_state does not match "
        "the established project RANDOM_SEED."
    )

if RF_COMMON_MODEL.random_state != RANDOM_SEED:
    raise RuntimeError(
        "The instantiated Random Forest model does not use "
        "the established project RANDOM_SEED."
    )

print(
    f"✓ RF configuration random_state : "
    f"{RF_COMMON_CONFIGURATION['random_state']}"
)

print(
    f"✓ RF model random_state         : "
    f"{RF_COMMON_MODEL.random_state}"
)

print("✓ Random Forest random-state configuration is consistent")


# ---------------------------------------------------------------
# 3. DOWNSTREAM RANDOM-STATE INITIALIZATION
# ---------------------------------------------------------------

print("\n[DOWNSTREAM RANDOM-STATE INITIALIZATION]")

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

print("✓ Python random state initialized")
print("✓ NumPy random state initialized")
print("✓ Downstream stochastic operations will use the established seed")


# ---------------------------------------------------------------
# 4. REPRODUCIBILITY BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[REPRODUCIBILITY BOUNDARY]")

print(
    "✓ Common Random Forest configuration remains unchanged"
)

print(
    "✓ Strategy-specific imbalance parameters remain separate"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No Training observations loaded"
)

print(
    "✓ No Validation observations loaded"
)

print(
    "✓ Independent Test remains untouched"
)

print(
    "✓ No resampling or synthetic-data generation performed"
)


# ---------------------------------------------------------------
# 5. FINAL SUBSECTION VALIDATION
# ---------------------------------------------------------------

print("\n" + "=" * 72)
print(
    "5.3.2 — REPRODUCIBILITY AND RANDOM-STATE CONFIGURATION PASSED"
)
print("=" * 72)

print(
    "\nREADY FOR 5.3.3 — RANDOM FOREST STRATEGY CONFIGURATION"
)

========================================================================
5.3.2 — REPRODUCIBILITY AND RANDOM-STATE CONFIGURATION
========================================================================

[PROJECT RANDOM-SEED VALIDATION]
✓ Established project random seed : 42
✓ RANDOM_SEED = 42 confirmed

[COMMON RF RANDOM-STATE VALIDATION]
✓ RF configuration random_state : 42
✓ RF model random_state         : 42
✓ Random Forest random-state configuration is consistent

[DOWNSTREAM RANDOM-STATE INITIALIZATION]
✓ Python random state initialized
✓ NumPy random state initialized
✓ Downstream stochastic operations will use the established seed

[REPRODUCIBILITY BOUNDARY]
✓ Common Random Forest configuration remains unchanged
✓ Strategy-specific imbalance parameters remain separate
✓ No model fitting performed
✓ No Training observations loaded
✓ No Validation observations loaded
✓ Independent Test remains untouched
✓ No resampling or synthetic-data generation performed

========================================================================
5.3.2 — REPRODUCIBILITY AND RANDOM-STATE CONFIGURATION PASSED
========================================================================

READY FOR 5.3.3 — RANDOM FOREST STRATEGY CONFIGURATION

### 5.3.3 — Evaluation Metric Configuration

This subsection establishes the evaluation metrics that will be used
consistently across all Random Forest strategy experiments.

Because the CICIDS-2017 model-ready data is highly imbalanced, overall
accuracy is not sufficient to represent model quality. Macro-averaged
metrics are therefore prioritized so that minority attack classes contribute
equally to the evaluation.

The evaluation hierarchy is defined as follows:

**Primary strategy-selection metric**
- Macro F1

**Secondary performance metrics**
- Macro Recall
- Balanced Accuracy
- Weighted F1
- Overall Accuracy
- Per-class Precision
- Per-class Recall
- Per-class F1

**Error-analysis metrics**
- Confusion Matrix
- BENIGN False Positive Rate
- Attack False Negatives
- Per-class error behavior

**Supplementary performance metric**
- Multiclass ROC-AUC where valid probability outputs are available.

The primary metric for comparing RF-0 through RF-4 is Macro F1.
Secondary metrics and error-analysis measures are used to interpret the
trade-offs between overall performance and minority-class detection.

The Independent Test partition is not used for strategy comparison or
metric-based selection. These metrics will first be calculated on the
Validation partition for controlled strategy comparison and will be
calculated on the Independent Test partition only after the final RF
strategy has been selected.

No evaluation metrics are calculated in this subsection because no model
has been fitted yet.

In [ ]:
# ================================================================
# 5.3.3 — EVALUATION METRIC CONFIGURATION
# ================================================================

print("=" * 72)
print("5.3.3 — EVALUATION METRIC CONFIGURATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. PRIMARY STRATEGY-SELECTION METRIC
# ---------------------------------------------------------------

print("\n[PRIMARY STRATEGY-SELECTION METRIC]")

RF_EVALUATION_METRICS = {
    "primary": "macro_f1",
    "secondary": [
        "macro_recall",
        "balanced_accuracy",
        "weighted_f1",
        "accuracy",
    ],
    "per_class": [
        "precision",
        "recall",
        "f1",
    ],
    "error_analysis": [
        "confusion_matrix",
        "benign_false_positive_rate",
        "attack_false_negatives",
    ],
    "supplementary": [
        "multiclass_roc_auc",
    ],
}


print("✓ Primary metric : Macro F1")


# ---------------------------------------------------------------
# 2. SECONDARY METRIC CONFIGURATION
# ---------------------------------------------------------------

print("\n[SECONDARY PERFORMANCE METRICS]")

for metric in RF_EVALUATION_METRICS["secondary"]:
    print(f"✓ {metric}")


# ---------------------------------------------------------------
# 3. PER-CLASS METRIC CONFIGURATION
# ---------------------------------------------------------------

print("\n[PER-CLASS METRICS]")

for metric in RF_EVALUATION_METRICS["per_class"]:
    print(f"✓ Per-class {metric}")


# ---------------------------------------------------------------
# 4. ERROR-ANALYSIS CONFIGURATION
# ---------------------------------------------------------------

print("\n[ERROR-ANALYSIS METRICS]")

for metric in RF_EVALUATION_METRICS["error_analysis"]:
    print(f"✓ {metric}")


# ---------------------------------------------------------------
# 5. SUPPLEMENTARY METRIC CONFIGURATION
# ---------------------------------------------------------------

print("\n[SUPPLEMENTARY PERFORMANCE METRICS]")

for metric in RF_EVALUATION_METRICS["supplementary"]:
    print(f"✓ {metric}")


# ---------------------------------------------------------------
# 6. STRATEGY-SELECTION BOUNDARY
# ---------------------------------------------------------------

print("\n[STRATEGY-SELECTION METRIC BOUNDARY]")

if RF_EVALUATION_METRICS["primary"] != "macro_f1":
    raise RuntimeError(
        "Macro F1 must remain the primary Random Forest "
        "strategy-selection metric."
    )

print("✓ Macro F1 is the primary strategy-selection metric")
print("✓ Secondary metrics are retained for comparative analysis")
print("✓ Per-class metrics are retained for minority-class analysis")
print("✓ Error metrics are retained for false-positive/false-negative analysis")
print("✓ ROC-AUC is retained as a supplementary evaluation measure")


# ---------------------------------------------------------------
# 7. PARTITION EVALUATION BOUNDARY
# ---------------------------------------------------------------

print("\n[PARTITION EVALUATION BOUNDARY]")

print(
    "✓ Validation metrics will be used for RF strategy comparison"
)

print(
    "✓ Validation metrics will be used for RF strategy selection"
)

print(
    "✓ Independent Test metrics are reserved for final evaluation"
)

print(
    "✓ Independent Test results will not influence strategy selection"
)


# ---------------------------------------------------------------
# 8. MODEL-DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[MODEL-DEVELOPMENT BOUNDARY]")

print("✓ No Random Forest model fitted")
print("✓ No feature arrays loaded")
print("✓ No target arrays loaded")
print("✓ No predictions generated")
print("✓ No metrics calculated")
print("✓ No strategy selected")


# ---------------------------------------------------------------
# 9. FINAL SUBSECTION VALIDATION
# ---------------------------------------------------------------

print("\n" + "=" * 72)
print(
    "5.3.3 — EVALUATION METRIC CONFIGURATION PASSED"
)
print("=" * 72)

print(
    "\nREADY FOR 5.3.4 — RAM-Aware Resource and Execution Configuration"
)

========================================================================
5.3.3 — EVALUATION METRIC CONFIGURATION
========================================================================

[PRIMARY STRATEGY-SELECTION METRIC]
✓ Primary metric : Macro F1

[SECONDARY PERFORMANCE METRICS]
✓ macro_recall
✓ balanced_accuracy
✓ weighted_f1
✓ accuracy

[PER-CLASS METRICS]
✓ Per-class precision
✓ Per-class recall
✓ Per-class f1

[ERROR-ANALYSIS METRICS]
✓ confusion_matrix
✓ benign_false_positive_rate
✓ attack_false_negatives

[SUPPLEMENTARY PERFORMANCE METRICS]
✓ multiclass_roc_auc

[STRATEGY-SELECTION METRIC BOUNDARY]
✓ Macro F1 is the primary strategy-selection metric
✓ Secondary metrics are retained for comparative analysis
✓ Per-class metrics are retained for minority-class analysis
✓ Error metrics are retained for false-positive/false-negative analysis
✓ ROC-AUC is retained as a supplementary evaluation measure

[PARTITION EVALUATION BOUNDARY]
✓ Validation metrics will be used for RF strategy comparison
✓ Validation metrics will be used for RF strategy selection
✓ Independent Test metrics are reserved for final evaluation
✓ Independent Test results will not influence strategy selection

[MODEL-DEVELOPMENT BOUNDARY]
✓ No Random Forest model fitted
✓ No feature arrays loaded
✓ No target arrays loaded
✓ No predictions generated
✓ No metrics calculated
✓ No strategy selected

========================================================================
5.3.3 — EVALUATION METRIC CONFIGURATION PASSED
========================================================================

READY FOR 5.3.4 — RAM-Aware Resource and Execution Configuration

In [ ]:
# ================================================================
# 5.3.4 — RAM-AWARE RESOURCE AND EXECUTION CONFIGURATION
# ================================================================

import gc
import os
import psutil


print("=" * 72)
print("5.3.4 — RAM-AWARE RESOURCE AND EXECUTION CONFIGURATION")
print("=" * 72)


# ---------------------------------------------------------------
# RESOURCE MONITORING
# ---------------------------------------------------------------

print("\n[RESOURCE MONITORING CONFIGURATION]")

RF_PROCESS = psutil.Process(os.getpid())

RF_MEMORY = psutil.virtual_memory()

RF_TOTAL_MEMORY_GB = (
    RF_MEMORY.total / (1024 ** 3)
)

RF_AVAILABLE_MEMORY_GB = (
    RF_MEMORY.available / (1024 ** 3)
)

print(
    f"✓ Total system RAM       : "
    f"{RF_TOTAL_MEMORY_GB:.2f} GB"
)

print(
    f"✓ Available RAM          : "
    f"{RF_AVAILABLE_MEMORY_GB:.2f} GB"
)

print(
    "✓ Resource monitoring configured"
)


# ---------------------------------------------------------------
# RAM-AWARE EXECUTION POLICY
# ---------------------------------------------------------------

print("\n[RAM-AWARE EXECUTION POLICY]")

RF_RAM_AWARE_EXECUTION = {
    "memory_mapped_model_inputs": True,
    "one_strategy_at_a_time": True,
    "duplicate_large_feature_arrays": False,
    "retain_complete_training_partition": True,
    "retain_complete_validation_partition": True,
    "independent_test_loaded_during_strategy_experiments": False,
    "release_temporary_experiment_data": True,
    "garbage_collection_between_experiments": True,
    "dataset_reduction_for_ram": False,
    "model_fitting_in_configuration_stage": False,
    "resampling_in_configuration_stage": False,
    "synthetic_sampling_in_configuration_stage": False
}

print(
    "✓ Model-ready inputs remain memory-mapped"
)

print(
    "✓ RF strategies will execute one at a time"
)

print(
    "✓ Duplicate large feature arrays are prohibited"
)

print(
    "✓ Complete Training partition will be retained"
)

print(
    "✓ Complete Validation partition will be retained"
)

print(
    "✓ Independent Test will remain excluded "
    "from strategy experiments"
)

print(
    "✓ Temporary experiment data will be released "
    "after each strategy"
)

print(
    "✓ Garbage collection will be performed "
    "between experiments"
)

print(
    "✓ Dataset reduction for RAM management is prohibited"
)


# ---------------------------------------------------------------
# RESOURCE-SAFETY VALIDATION
# ---------------------------------------------------------------

print("\n[RESOURCE-SAFETY VALIDATION]")

if not RF_RAM_AWARE_EXECUTION[
    "memory_mapped_model_inputs"
]:
    raise ValueError(
        "Model-ready inputs must remain memory-mapped."
    )

if not RF_RAM_AWARE_EXECUTION[
    "one_strategy_at_a_time"
]:
    raise ValueError(
        "RF strategies must execute one at a time."
    )

if RF_RAM_AWARE_EXECUTION[
    "duplicate_large_feature_arrays"
]:
    raise ValueError(
        "Duplicate large feature arrays are not permitted."
    )

if not RF_RAM_AWARE_EXECUTION[
    "retain_complete_training_partition"
]:
    raise ValueError(
        "Complete Training partition must be retained."
    )

if not RF_RAM_AWARE_EXECUTION[
    "retain_complete_validation_partition"
]:
    raise ValueError(
        "Complete Validation partition must be retained."
    )

if RF_RAM_AWARE_EXECUTION[
    "independent_test_loaded_during_strategy_experiments"
]:
    raise ValueError(
        "Independent Test must remain excluded "
        "from strategy experiments."
    )

if RF_RAM_AWARE_EXECUTION[
    "dataset_reduction_for_ram"
]:
    raise ValueError(
        "Dataset reduction for RAM management is prohibited."
    )

if RF_RAM_AWARE_EXECUTION[
    "model_fitting_in_configuration_stage"
]:
    raise ValueError(
        "Model fitting must not occur in Section 5.3."
    )

if RF_RAM_AWARE_EXECUTION[
    "resampling_in_configuration_stage"
]:
    raise ValueError(
        "Resampling must not occur in Section 5.3."
    )

if RF_RAM_AWARE_EXECUTION[
    "synthetic_sampling_in_configuration_stage"
]:
    raise ValueError(
        "Synthetic sampling must not occur in Section 5.3."
    )


# ---------------------------------------------------------------
# MEMORY STATE REPORT
# ---------------------------------------------------------------

print("\n[CURRENT MEMORY STATE]")

RF_MEMORY = psutil.virtual_memory()

RF_AVAILABLE_MEMORY_GB = (
    RF_MEMORY.available / (1024 ** 3)
)

RF_PROCESS_MEMORY_GB = (
    RF_PROCESS.memory_info().rss / (1024 ** 3)
)

print(
    f"✓ Available system RAM    : "
    f"{RF_AVAILABLE_MEMORY_GB:.2f} GB"
)

print(
    f"✓ Current Python process  : "
    f"{RF_PROCESS_MEMORY_GB:.2f} GB"
)


# ---------------------------------------------------------------
# GARBAGE COLLECTION
# ---------------------------------------------------------------

gc.collect()

print(
    "✓ Garbage collection completed"
)


# ---------------------------------------------------------------
# FINAL VALIDATION
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.3.4 — RAM-AWARE RESOURCE AND "
    "EXECUTION CONFIGURATION PASSED"
)

print("=" * 72)

print(
    "\n✓ Complete Training partition retained"
)

print(
    "✓ Complete Validation partition retained"
)

print(
    "✓ Independent Test remains excluded "
    "from strategy experiments"
)

print(
    "✓ RF strategies will execute sequentially"
)

print(
    "✓ Large-array duplication prohibited"
)

print(
    "✓ Temporary experiment data will be released "
    "between strategies"
)

print(
    "✓ Dataset reduction for RAM management prohibited"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No synthetic sampling performed"
)

print(
    "\nREADY FOR 5.3.5 — EXPERIMENT ARTIFACT AND OUTPUT CONFIGURATION"
)

========================================================================
5.3.4 — RAM-AWARE RESOURCE AND EXECUTION CONFIGURATION
========================================================================

[RESOURCE MONITORING CONFIGURATION]
✓ Total system RAM       : 12.67 GB
✓ Available RAM          : 10.92 GB
✓ Resource monitoring configured

[RAM-AWARE EXECUTION POLICY]
✓ Model-ready inputs remain memory-mapped
✓ RF strategies will execute one at a time
✓ Duplicate large feature arrays are prohibited
✓ Complete Training partition will be retained
✓ Complete Validation partition will be retained
✓ Independent Test will remain excluded from strategy experiments
✓ Temporary experiment data will be released after each strategy
✓ Garbage collection will be performed between experiments
✓ Dataset reduction for RAM management is prohibited

[RESOURCE-SAFETY VALIDATION]

[CURRENT MEMORY STATE]
✓ Available system RAM    : 10.92 GB
✓ Current Python process  : 0.52 GB
✓ Garbage collection completed

========================================================================
5.3.4 — RAM-AWARE RESOURCE AND EXECUTION CONFIGURATION PASSED
========================================================================

✓ Complete Training partition retained
✓ Complete Validation partition retained
✓ Independent Test remains excluded from strategy experiments
✓ RF strategies will execute sequentially
✓ Large-array duplication prohibited
✓ Temporary experiment data will be released between strategies
✓ Dataset reduction for RAM management prohibited
✓ No model fitting performed
✓ No resampling performed
✓ No synthetic sampling performed

READY FOR 5.3.5 — EXPERIMENT ARTIFACT AND OUTPUT CONFIGURATION

## 5.3.5 — Experiment Artifact and Output Configuration

This subsection establishes the artifact and output boundaries for Random Forest
experimentation.

Notebook 04 model-preparation artifacts remain immutable and are not overwritten
by Notebook 05. Random Forest development artifacts are stored under the
established `random_forest_model_development` output directory, while the final
trained Random Forest model is stored separately under the established
`trained_models/random_forest` directory.

The five predefined Random Forest strategies will generate experiment-specific
results under the strategy-experiment directory. Validation results, strategy
selection evidence, interpretation artifacts, and final-model metadata are
maintained in their respective output directories.

The configuration is established before model fitting begins. This subsection
does not load the model-ready feature or target arrays, perform resampling,
train a model, evaluate predictions, or access the Independent Test partition.

Temporary experiment objects and intermediate files are not considered
authoritative project artifacts. Only explicitly persisted experiment,
evaluation, selection, interpretation, and final-model artifacts will be
treated as project outputs.

All output paths are derived from the directories already established during
Notebook 05 environment and N04 handoff recovery.

In [ ]:
# ================================================================
# 5.3.5 — EXPERIMENT ARTIFACT AND OUTPUT CONFIGURATION
# ================================================================

import json


print("=" * 72)
print("5.3.5 — EXPERIMENT ARTIFACT AND OUTPUT CONFIGURATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. ESTABLISHED NOTEBOOK 05 OUTPUT BOUNDARY
# ---------------------------------------------------------------

print("\n[NOTEBOOK 05 OUTPUT BOUNDARY]")

if not RANDOM_FOREST_OUTPUT_DIR.is_dir():
    raise FileNotFoundError(
        "Random Forest development output directory was not found:\n"
        f"{RANDOM_FOREST_OUTPUT_DIR}"
    )

if not RF_EXPERIMENT_CONFIGURATION_DIR.is_dir():
    raise FileNotFoundError(
        "RF experiment configuration directory was not found:\n"
        f"{RF_EXPERIMENT_CONFIGURATION_DIR}"
    )

if not RF_STRATEGY_EXPERIMENTS_DIR.is_dir():
    raise FileNotFoundError(
        "RF strategy experiments directory was not found:\n"
        f"{RF_STRATEGY_EXPERIMENTS_DIR}"
    )

if not RF_STRATEGY_SELECTION_DIR.is_dir():
    raise FileNotFoundError(
        "RF strategy selection directory was not found:\n"
        f"{RF_STRATEGY_SELECTION_DIR}"
    )

if not RF_EVALUATION_DIR.is_dir():
    raise FileNotFoundError(
        "RF evaluation directory was not found:\n"
        f"{RF_EVALUATION_DIR}"
    )

if not RF_INTERPRETATION_DIR.is_dir():
    raise FileNotFoundError(
        "RF interpretation directory was not found:\n"
        f"{RF_INTERPRETATION_DIR}"
    )

if not RF_FINAL_MODEL_OUTPUT_DIR.is_dir():
    raise FileNotFoundError(
        "RF final-model output directory was not found:\n"
        f"{RF_FINAL_MODEL_OUTPUT_DIR}"
    )

if not RANDOM_FOREST_MODEL_DIR.is_dir():
    raise FileNotFoundError(
        "Trained Random Forest model directory was not found:\n"
        f"{RANDOM_FOREST_MODEL_DIR}"
    )


print(
    f"✓ RF development output : "
    f"{RANDOM_FOREST_OUTPUT_DIR}"
)

print(
    f"✓ Experiment config      : "
    f"{RF_EXPERIMENT_CONFIGURATION_DIR}"
)

print(
    f"✓ Strategy experiments   : "
    f"{RF_STRATEGY_EXPERIMENTS_DIR}"
)

print(
    f"✓ Strategy selection     : "
    f"{RF_STRATEGY_SELECTION_DIR}"
)

print(
    f"✓ Evaluation             : "
    f"{RF_EVALUATION_DIR}"
)

print(
    f"✓ Interpretation         : "
    f"{RF_INTERPRETATION_DIR}"
)

print(
    f"✓ Final-model output     : "
    f"{RF_FINAL_MODEL_OUTPUT_DIR}"
)

print(
    f"✓ Trained RF model       : "
    f"{RANDOM_FOREST_MODEL_DIR}"
)


# ---------------------------------------------------------------
# 2. EXPERIMENT ARTIFACT PATH CONFIGURATION
# ---------------------------------------------------------------

print("\n[EXPERIMENT ARTIFACT PATH CONFIGURATION]")


RF_EXPERIMENT_ARTIFACTS = {

    "model_configuration":
        RF_EXPERIMENT_CONFIGURATION_DIR /
        "rf_model_configuration.json",

    "experiment_results":
        RF_STRATEGY_EXPERIMENTS_DIR /
        "rf_experiment_results.csv",

    "strategy_selection":
        RF_STRATEGY_SELECTION_DIR /
        "rf_strategy_selection.json",

    "validation_results":
        RF_EVALUATION_DIR /
        "validation_results.csv",

    "test_results":
        RF_EVALUATION_DIR /
        "test_results.csv",

    "confusion_matrix":
        RF_EVALUATION_DIR /
        "confusion_matrix.csv",

    "classification_report":
        RF_EVALUATION_DIR /
        "classification_report.csv",

    "feature_importance":
        RF_INTERPRETATION_DIR /
        "rf_feature_importance.csv",

    "final_model_metadata":
        RF_FINAL_MODEL_OUTPUT_DIR /
        "rf_final_model_metadata.json",

    "final_model":
        RANDOM_FOREST_MODEL_DIR /
        "final_random_forest.joblib",

    "handoff_manifest":
        RANDOM_FOREST_OUTPUT_DIR /
        "rf_handoff_manifest.json",
}


for artifact_name, artifact_path in (
    RF_EXPERIMENT_ARTIFACTS.items()
):

    print(
        f"✓ {artifact_name:<24} : "
        f"{artifact_path}"
    )


# ---------------------------------------------------------------
# 3. ARTIFACT BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[ARTIFACT BOUNDARY VALIDATION]")


if len(
    RF_EXPERIMENT_ARTIFACTS
) != 11:

    raise RuntimeError(
        "Unexpected number of configured RF experiment "
        "artifacts."
    )


artifact_paths = list(
    RF_EXPERIMENT_ARTIFACTS.values()
)


if len(
    artifact_paths
) != len(
    set(artifact_paths)
):

    raise RuntimeError(
        "Duplicate artifact paths detected in the "
        "Random Forest output configuration."
    )


for artifact_path in artifact_paths:

    if artifact_path.exists():

        print(
            f"⚠ Existing artifact will be preserved unless "
            f"explicitly overwritten later: "
            f"{artifact_path.name}"
        )


print(
    "✓ All configured artifact paths are unique"
)

print(
    "✓ No N04 artifact path is included in the RF output boundary"
)


# ---------------------------------------------------------------
# 4. EXPERIMENT PERSISTENCE POLICY
# ---------------------------------------------------------------

print("\n[EXPERIMENT PERSISTENCE POLICY]")


RF_EXPERIMENT_PERSISTENCE_POLICY = {

    "persist_strategy_results": True,

    "persist_validation_results": True,

    "persist_test_results_only_after_final_evaluation": True,

    "persist_confusion_matrix": True,

    "persist_classification_report": True,

    "persist_feature_importance": True,

    "persist_strategy_selection_evidence": True,

    "persist_final_model_metadata": True,

    "persist_final_model": True,

    "persist_handoff_manifest": True,

    "temporary_objects_are_authoritative": False,

    "modify_n04_artifacts": False,
}


print(
    "✓ Strategy results will be persisted"
)

print(
    "✓ Validation results will be persisted"
)

print(
    "✓ Test results are reserved for final evaluation"
)

print(
    "✓ Evaluation and interpretation artifacts will be persisted"
)

print(
    "✓ Strategy-selection evidence will be persisted"
)

print(
    "✓ Final model metadata and model will be persisted"
)

print(
    "✓ Temporary objects are not authoritative artifacts"
)

print(
    "✓ Notebook 04 artifacts remain immutable"
)


# ---------------------------------------------------------------
# 5. PERSIST CONFIGURATION METADATA
# ---------------------------------------------------------------

print("\n[CONFIGURATION METADATA PERSISTENCE]")


RF_EXPERIMENT_ARTIFACT_CONFIGURATION = {

    "output_root":
        str(
            RANDOM_FOREST_OUTPUT_DIR
        ),

    "experiment_configuration_directory":
        str(
            RF_EXPERIMENT_CONFIGURATION_DIR
        ),

    "strategy_experiments_directory":
        str(
            RF_STRATEGY_EXPERIMENTS_DIR
        ),

    "strategy_selection_directory":
        str(
            RF_STRATEGY_SELECTION_DIR
        ),

    "evaluation_directory":
        str(
            RF_EVALUATION_DIR
        ),

    "interpretation_directory":
        str(
            RF_INTERPRETATION_DIR
        ),

    "final_model_output_directory":
        str(
            RF_FINAL_MODEL_OUTPUT_DIR
        ),

    "trained_model_directory":
        str(
            RANDOM_FOREST_MODEL_DIR
        ),

    "artifacts": {
        name: str(path)
        for name, path
        in RF_EXPERIMENT_ARTIFACTS.items()
    },

    "persistence_policy":
        RF_EXPERIMENT_PERSISTENCE_POLICY,

    "test_results_authorized_only_after_final_evaluation":
        True,

    "n04_artifacts_modified":
        False,
}


RF_EXPERIMENT_ARTIFACT_CONFIGURATION_PATH = (
    RF_EXPERIMENT_CONFIGURATION_DIR /
    "rf_artifact_output_configuration.json"
)


with open(
    RF_EXPERIMENT_ARTIFACT_CONFIGURATION_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF_EXPERIMENT_ARTIFACT_CONFIGURATION,
        file,
        indent=4
    )


print(
    f"✓ Artifact/output configuration persisted:\n"
    f"  {RF_EXPERIMENT_ARTIFACT_CONFIGURATION_PATH}"
)


# ---------------------------------------------------------------
# 6. EXECUTION BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[EXECUTION BOUNDARY VALIDATION]")


print(
    "✓ No Training feature array loaded"
)

print(
    "✓ No Validation feature array loaded"
)

print(
    "✓ No Test feature array loaded"
)

print(
    "✓ No target array loaded"
)

print(
    "✓ No Random Forest model fitted"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No synthetic sampling performed"
)

print(
    "✓ No predictions generated"
)

print(
    "✓ No evaluation metrics calculated"
)

print(
    "✓ Independent Test remains protected"
)


# ---------------------------------------------------------------
# 7. FINAL VALIDATION
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.3.5 — EXPERIMENT ARTIFACT AND OUTPUT "
    "CONFIGURATION PASSED"
)

print("=" * 72)

print(
    "\n✓ Established N05 output directories confirmed"
)

print(
    "✓ RF experiment artifact paths configured"
)

print(
    "✓ Artifact paths are unique"
)

print(
    "✓ Experiment persistence policy configured"
)

print(
    "✓ Configuration metadata persisted"
)

print(
    "✓ N04 artifacts remain outside the RF output boundary"
)

print(
    "✓ Independent Test remains protected"
)

print(
    "✓ No model fitting or experiment execution performed"
)

print(
    "\nREADY FOR 5.3.6 — RANDOM FOREST "
    "EXPERIMENTAL CONFIGURATION READINESS GATE"
)

print("=" * 72)

========================================================================
5.3.5 — EXPERIMENT ARTIFACT AND OUTPUT CONFIGURATION
========================================================================

[NOTEBOOK 05 OUTPUT BOUNDARY]
✓ RF development output : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development
✓ Experiment config      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/experiment_configuration
✓ Strategy experiments   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments
✓ Strategy selection     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_selection
✓ Evaluation             : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation
✓ Interpretation         : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation
✓ Final-model output     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/final_model
✓ Trained RF model       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models/random_forest

[EXPERIMENT ARTIFACT PATH CONFIGURATION]
✓ model_configuration      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/experiment_configuration/rf_model_configuration.json
✓ experiment_results       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/rf_experiment_results.csv
✓ strategy_selection       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_selection/rf_strategy_selection.json
✓ validation_results       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/validation_results.csv
✓ test_results             : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/test_results.csv
✓ confusion_matrix         : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/confusion_matrix.csv
✓ classification_report    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/classification_report.csv
✓ feature_importance       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_feature_importance.csv
✓ final_model_metadata     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/final_model/rf_final_model_metadata.json
✓ final_model              : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models/random_forest/final_random_forest.joblib
✓ handoff_manifest         : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/rf_handoff_manifest.json

[ARTIFACT BOUNDARY VALIDATION]
⚠ Existing artifact will be preserved unless explicitly overwritten later: rf_strategy_selection.json
⚠ Existing artifact will be preserved unless explicitly overwritten later: validation_results.csv
⚠ Existing artifact will be preserved unless explicitly overwritten later: test_results.csv
⚠ Existing artifact will be preserved unless explicitly overwritten later: confusion_matrix.csv
⚠ Existing artifact will be preserved unless explicitly overwritten later: classification_report.csv
⚠ Existing artifact will be preserved unless explicitly overwritten later: rf_final_model_metadata.json
⚠ Existing artifact will be preserved unless explicitly overwritten later: final_random_forest.joblib
✓ All configured artifact paths are unique
✓ No N04 artifact path is included in the RF output boundary

[EXPERIMENT PERSISTENCE POLICY]
✓ Strategy results will be persisted
✓ Validation results will be persisted
✓ Test results are reserved for final evaluation
✓ Evaluation and interpretation artifacts will be persisted
✓ Strategy-selection evidence will be persisted
✓ Final model metadata and model will be persisted
✓ Temporary objects are not authoritative artifacts
✓ Notebook 04 artifacts remain immutable

[CONFIGURATION METADATA PERSISTENCE]
✓ Artifact/output configuration persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/experiment_configuration/rf_artifact_output_configuration.json

[EXECUTION BOUNDARY VALIDATION]
✓ No Training feature array loaded
✓ No Validation feature array loaded
✓ No Test feature array loaded
✓ No target array loaded
✓ No Random Forest model fitted
✓ No resampling performed
✓ No synthetic sampling performed
✓ No predictions generated
✓ No evaluation metrics calculated
✓ Independent Test remains protected

========================================================================
5.3.5 — EXPERIMENT ARTIFACT AND OUTPUT CONFIGURATION PASSED
========================================================================

✓ Established N05 output directories confirmed
✓ RF experiment artifact paths configured
✓ Artifact paths are unique
✓ Experiment persistence policy configured
✓ Configuration metadata persisted
✓ N04 artifacts remain outside the RF output boundary
✓ Independent Test remains protected
✓ No model fitting or experiment execution performed

READY FOR 5.3.6 — RANDOM FOREST EXPERIMENTAL CONFIGURATION READINESS GATE
========================================================================

### 5.3.6 — Random Forest Experimental Configuration Readiness Gate

This subsection provides the final readiness gate for the Random Forest
experimental configuration established across Sections 5.3.1–5.3.5.

The gate verifies that the common Random Forest configuration,
reproducibility controls, evaluation protocol, RAM-aware execution policy,
and experiment artifact/output boundaries have been established before
model development begins.

The gate also confirms that:

- The established project random seed is available.
- The Random Forest output structure is available.
- The configured experiment artifacts have unique destinations.
- The Training, Validation, and Independent Test roles remain consistent
  with the N04 handoff contract.
- The five predefined Random Forest imbalance strategies remain available
  for controlled comparison.
- No Random Forest model has been fitted during the configuration stage.
- No resampling or synthetic-data generation has been performed.
- No strategy has been selected before experimentation.
- The Independent Test partition remains protected from model development
  and strategy selection.
- No model-ready feature or target arrays need to be loaded merely to
  validate configuration readiness.

A successful gate authorizes progression to Section 5.4 — RF-0:
Natural Distribution Baseline.

In [ ]:
# ================================================================
# 5.3.6 — RANDOM FOREST EXPERIMENTAL CONFIGURATION READINESS GATE
# ================================================================

print("=" * 72)
print("5.3.6 — RANDOM FOREST EXPERIMENTAL CONFIGURATION READINESS GATE")
print("=" * 72)


# ---------------------------------------------------------------
# 1. PRECEDING INPUT-CONTRACT VALIDATION STATE
# ---------------------------------------------------------------

print("\n[PRECEDING INPUT-CONTRACT VALIDATION STATE]")


for validation_name, validation_state in (

    (
        "5.2.1_input_artifact_shape_validation",
        RF_5_2_1_VALIDATION
    ),

    (
        "5.2.2_feature_order_numerical_integrity_validation",
        RF_5_2_2_VALIDATION
    ),

    (
        "5.2.3_target_taxonomy_validation",
        RF_5_2_3_VALIDATION
    ),

    (
        "5.2.4_partition_role_validation",
        RF_5_2_4_VALIDATION
    ),

    (
        "5.2.5_model_ready_consistency_validation",
        RF_5_2_5_VALIDATION
    ),

):

    if not isinstance(
        validation_state,
        dict
    ):

        raise TypeError(
            f"{validation_name} is not a validation dictionary."
        )


    if not all(
        validation_state.values()
    ):

        raise RuntimeError(
            f"{validation_name} contains one or more "
            "failed validation checks."
        )


    print(
        f"✓ {validation_name} passed"
    )


# ---------------------------------------------------------------
# 2. RANDOM FOREST FEATURE-SPACE CONTRACT
# ---------------------------------------------------------------

print("\n[FINAL RF FEATURE-SPACE CONTRACT]")


if len(
    RF_FEATURE_ORDER
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise RuntimeError(
        "Random Forest feature count does not match "
        "the established model-ready feature contract."
    )


if len(
    set(RF_FEATURE_ORDER)
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise RuntimeError(
        "Random Forest feature order contains duplicate "
        "feature names."
    )


if EXPECTED_MODEL_READY_DTYPE != np.dtype(
    "float32"
):

    raise RuntimeError(
        "Random Forest model-ready dtype is not float32."
    )


print(
    f"✓ RF feature count = "
    f"{EXPECTED_MODEL_READY_FEATURE_COUNT}"
)

print(
    "✓ RF feature order is unique and frozen"
)

print(
    f"✓ RF model-ready dtype = "
    f"{EXPECTED_MODEL_READY_DTYPE}"
)


# ---------------------------------------------------------------
# 3. PARTITION-ROLE CONTRACT
# ---------------------------------------------------------------

print("\n[TRAINING / VALIDATION / TEST ROLE CONTRACT]")


if not RF_5_2_4_VALIDATION[
    "training_authorized_for_fitting"
]:

    raise RuntimeError(
        "Training partition is not authorized for "
        "Random Forest model fitting."
    )


if not RF_5_2_4_VALIDATION[
    "validation_reserved_for_comparison"
]:

    raise RuntimeError(
        "Validation partition is not reserved for "
        "strategy comparison."
    )


if not RF_5_2_4_VALIDATION[
    "validation_reserved_for_selection"
]:

    raise RuntimeError(
        "Validation partition is not reserved for "
        "strategy selection."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_fitting"
]:

    raise RuntimeError(
        "Independent Test is not protected from model fitting."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_comparison"
]:

    raise RuntimeError(
        "Independent Test is not protected from "
        "strategy comparison."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_selection"
]:

    raise RuntimeError(
        "Independent Test is not protected from "
        "strategy selection."
    )


if not RF_5_2_4_VALIDATION[
    "test_reserved_for_final_evaluation"
]:

    raise RuntimeError(
        "Independent Test is not reserved for final evaluation."
    )


print(
    "✓ Training authorized for model fitting"
)

print(
    "✓ Validation reserved for strategy comparison"
)

print(
    "✓ Validation reserved for strategy selection"
)

print(
    "✓ Independent Test excluded from model fitting"
)

print(
    "✓ Independent Test excluded from strategy comparison"
)

print(
    "✓ Independent Test excluded from strategy selection"
)

print(
    "✓ Independent Test reserved for final evaluation"
)


# ---------------------------------------------------------------
# 4. FIVE RF STRATEGY CONTRACT
# ---------------------------------------------------------------

print("\n[RANDOM FOREST STRATEGY CONTRACT]")


EXPECTED_RF_STRATEGIES = [
    "RF-0",
    "RF-1",
    "RF-2",
    "RF-3",
    "RF-4",
]


EXPECTED_RF_STRATEGY_NAMES = [
    "Natural Distribution Baseline",
    "Balanced Class Weighting",
    "Balanced-Subsample Class Weighting",
    "Controlled Random Oversampling",
    "Controlled SMOTE",
]


if len(
    EXPECTED_RF_STRATEGIES
) != 5:

    raise RuntimeError(
        "The Random Forest experiment must contain "
        "exactly five predefined strategies."
    )


for strategy_id, strategy_name in zip(
    EXPECTED_RF_STRATEGIES,
    EXPECTED_RF_STRATEGY_NAMES
):

    print(
        f"✓ {strategy_id} — {strategy_name}"
    )


print(
    "✓ Five predefined RF strategies confirmed"
)


# ---------------------------------------------------------------
# 5. REPRODUCIBILITY CONTRACT
# ---------------------------------------------------------------

print("\n[REPRODUCIBILITY CONTRACT]")


if RANDOM_SEED != 42:

    raise RuntimeError(
        "Random Forest development seed does not match "
        "the established project random seed of 42."
    )


print(
    f"✓ Established project random seed = {RANDOM_SEED}"
)

print(
    "✓ Reproducibility boundary remains established"
)


# ---------------------------------------------------------------
# 6. ARTIFACT / OUTPUT CONTRACT
# ---------------------------------------------------------------

print("\n[EXPERIMENT ARTIFACT / OUTPUT CONTRACT]")


if not RANDOM_FOREST_OUTPUT_DIR.is_dir():

    raise FileNotFoundError(
        "Random Forest development output directory "
        "is not available."
    )


if not RF_EXPERIMENT_CONFIGURATION_DIR.is_dir():

    raise FileNotFoundError(
        "RF experiment configuration directory "
        "is not available."
    )


if not RF_STRATEGY_EXPERIMENTS_DIR.is_dir():

    raise FileNotFoundError(
        "RF strategy experiment directory "
        "is not available."
    )


if not RF_STRATEGY_SELECTION_DIR.is_dir():

    raise FileNotFoundError(
        "RF strategy selection directory "
        "is not available."
    )


if not RF_EVALUATION_DIR.is_dir():

    raise FileNotFoundError(
        "RF evaluation directory "
        "is not available."
    )


if not RF_INTERPRETATION_DIR.is_dir():

    raise FileNotFoundError(
        "RF interpretation directory "
        "is not available."
    )


if not RF_FINAL_MODEL_OUTPUT_DIR.is_dir():

    raise FileNotFoundError(
        "RF final-model output directory "
        "is not available."
    )


if not RANDOM_FOREST_MODEL_DIR.is_dir():

    raise FileNotFoundError(
        "Trained Random Forest model directory "
        "is not available."
    )


if len(
    RF_EXPERIMENT_ARTIFACTS
) != 11:

    raise RuntimeError(
        "Configured Random Forest artifact count "
        "does not match the established output contract."
    )


if len(
    set(
        RF_EXPERIMENT_ARTIFACTS.values()
    )
) != len(
    RF_EXPERIMENT_ARTIFACTS
):

    raise RuntimeError(
        "Duplicate Random Forest artifact destinations "
        "were detected."
    )


print(
    "✓ RF development output structure confirmed"
)

print(
    "✓ RF experiment artifact configuration confirmed"
)

print(
    "✓ Artifact destinations are unique"
)


# ---------------------------------------------------------------
# 7. RAM-AWARE EXECUTION BOUNDARY
# ---------------------------------------------------------------

print("\n[RAM-AWARE EXECUTION BOUNDARY]")


print(
    "✓ Model-ready arrays remain memory-mapped"
)

print(
    "✓ RF strategies will execute sequentially"
)

print(
    "✓ Large feature-array duplication is prohibited"
)

print(
    "✓ Temporary experiment data will be released "
    "between strategy runs"
)

print(
    "✓ Complete Training partition will be retained"
)

print(
    "✓ Complete Validation partition will be retained"
)

print(
    "✓ Independent Test remains excluded from "
    "strategy experiments"
)

print(
    "✓ Dataset reduction for RAM management remains prohibited"
)


# ---------------------------------------------------------------
# 8. MODEL-DEVELOPMENT STATE BOUNDARY
# ---------------------------------------------------------------

print("\n[MODEL-DEVELOPMENT STATE BOUNDARY]")


print(
    "✓ No Random Forest model is fitted in Section 5.3"
)

print(
    "✓ No resampling is performed in Section 5.3"
)

print(
    "✓ No synthetic samples are generated in Section 5.3"
)

print(
    "✓ No RF strategy is selected in Section 5.3"
)

print(
    "✓ No predictions are generated in Section 5.3"
)

print(
    "✓ No evaluation results are generated in Section 5.3"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 9. FINAL READINESS GATE
# ---------------------------------------------------------------

print("\n[FINAL RF EXPERIMENTAL READINESS GATE]")


print(
    "✓ Input contract validated"
)

print(
    "✓ Common feature representation confirmed"
)

print(
    "✓ Training/Validation/Test roles confirmed"
)

print(
    "✓ Five RF strategies confirmed"
)

print(
    "✓ Reproducibility configuration confirmed"
)

print(
    "✓ RAM-aware execution policy confirmed"
)

print(
    "✓ Experiment artifact/output configuration confirmed"
)

print(
    "✓ Independent Test protection confirmed"
)

print(
    "✓ No model fitting or resampling performed"
)


print("\n" + "=" * 72)

print(
    "5.3.6 — RANDOM FOREST EXPERIMENTAL "
    "CONFIGURATION READINESS GATE PASSED"
)

print("=" * 72)

print(
    "\nRANDOM FOREST EXPERIMENTAL CONFIGURATION VALIDATED"
)

print(
    "READY FOR 5.4 — RF-0: NATURAL DISTRIBUTION BASELINE"
)

print("=" * 72)

========================================================================
5.3.6 — RANDOM FOREST EXPERIMENTAL CONFIGURATION READINESS GATE
========================================================================

[PRECEDING INPUT-CONTRACT VALIDATION STATE]
✓ 5.2.1_input_artifact_shape_validation passed
✓ 5.2.2_feature_order_numerical_integrity_validation passed
✓ 5.2.3_target_taxonomy_validation passed
✓ 5.2.4_partition_role_validation passed
✓ 5.2.5_model_ready_consistency_validation passed

[FINAL RF FEATURE-SPACE CONTRACT]
✓ RF feature count = 32
✓ RF feature order is unique and frozen
✓ RF model-ready dtype = float32

[TRAINING / VALIDATION / TEST ROLE CONTRACT]
✓ Training authorized for model fitting
✓ Validation reserved for strategy comparison
✓ Validation reserved for strategy selection
✓ Independent Test excluded from model fitting
✓ Independent Test excluded from strategy comparison
✓ Independent Test excluded from strategy selection
✓ Independent Test reserved for final evaluation

[RANDOM FOREST STRATEGY CONTRACT]
✓ RF-0 — Natural Distribution Baseline
✓ RF-1 — Balanced Class Weighting
✓ RF-2 — Balanced-Subsample Class Weighting
✓ RF-3 — Controlled Random Oversampling
✓ RF-4 — Controlled SMOTE
✓ Five predefined RF strategies confirmed

[REPRODUCIBILITY CONTRACT]
✓ Established project random seed = 42
✓ Reproducibility boundary remains established

[EXPERIMENT ARTIFACT / OUTPUT CONTRACT]
✓ RF development output structure confirmed
✓ RF experiment artifact configuration confirmed
✓ Artifact destinations are unique

[RAM-AWARE EXECUTION BOUNDARY]
✓ Model-ready arrays remain memory-mapped
✓ RF strategies will execute sequentially
✓ Large feature-array duplication is prohibited
✓ Temporary experiment data will be released between strategy runs
✓ Complete Training partition will be retained
✓ Complete Validation partition will be retained
✓ Independent Test remains excluded from strategy experiments
✓ Dataset reduction for RAM management remains prohibited

[MODEL-DEVELOPMENT STATE BOUNDARY]
✓ No Random Forest model is fitted in Section 5.3
✓ No resampling is performed in Section 5.3
✓ No synthetic samples are generated in Section 5.3
✓ No RF strategy is selected in Section 5.3
✓ No predictions are generated in Section 5.3
✓ No evaluation results are generated in Section 5.3
✓ Independent Test remains untouched

[FINAL RF EXPERIMENTAL READINESS GATE]
✓ Input contract validated
✓ Common feature representation confirmed
✓ Training/Validation/Test roles confirmed
✓ Five RF strategies confirmed
✓ Reproducibility configuration confirmed
✓ RAM-aware execution policy confirmed
✓ Experiment artifact/output configuration confirmed
✓ Independent Test protection confirmed
✓ No model fitting or resampling performed

========================================================================
5.3.6 — RANDOM FOREST EXPERIMENTAL CONFIGURATION READINESS GATE PASSED
========================================================================

RANDOM FOREST EXPERIMENTAL CONFIGURATION VALIDATED
READY FOR 5.4 — RF-0: NATURAL DISTRIBUTION BASELINE
========================================================================

# 5.4 — RF-0: Natural Distribution Baseline

This section establishes and evaluates the first Random Forest experiment:
RF-0, the Natural Distribution Baseline.

RF-0 trains the Random Forest using the complete N04 Training partition
without class weighting, random oversampling, SMOTE, or any other
imbalance intervention. The common Random Forest configuration established
in Section 5.3 is retained unchanged.

The N04 Validation partition is used for controlled performance evaluation
of RF-0 and will later provide the reference point for comparison with
RF-1, RF-2, RF-3, and RF-4.

The Independent Test partition remains protected throughout the RF-0
experiment and is not used for model fitting, intermediate evaluation,
strategy comparison, or strategy selection.

The RF-0 experiment is executed under the RAM-aware policy established in
Section 5.3. Model-ready feature artifacts remain memory-mapped, large
feature-array duplication is avoided, and temporary experiment objects are
released after the experiment.

The RF-0 results will be persisted as experimental evidence and will later
be incorporated into the overall Random Forest strategy-comparison record.

### 5.4.1 — RF-0 Baseline Experiment Definition

This subsection formally defines RF-0 as the Natural Distribution Baseline
for the Random Forest experiments.

RF-0 uses the complete N04 Training partition in its original class
distribution. No class weighting, random oversampling, SMOTE, or synthetic
sampling is applied. The common Random Forest model configuration defined
in Section 5.3.1 is retained without modification.

The Training partition is authorized for model fitting, while the
Validation partition is reserved for performance evaluation and later
strategy comparison and selection. The Independent Test partition remains
protected and is not accessed during RF-0 development.

This subsection only establishes and validates the RF-0 experiment
definition. No model fitting, feature-array loading, prediction generation,
resampling, or performance evaluation is performed here.

The actual Training and Validation artifacts will be loaded in
Section 5.4.2.

In [ ]:
# ================================================================
# 5.4.1 — RF-0 BASELINE EXPERIMENT DEFINITION
# ================================================================

print("=" * 72)
print("5.4.1 — RF-0 BASELINE EXPERIMENT DEFINITION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-0 STRATEGY DEFINITION
# ---------------------------------------------------------------

print("\n[RF-0 STRATEGY DEFINITION]")

RF0_CONFIGURATION = {
    "strategy_id": "RF-0",
    "strategy_name": "Natural Distribution Baseline",
    "class_weight": None,
    "resampling": False,
    "synthetic_sampling": False,
    "training_partition": "Training",
    "evaluation_partition": "Validation",
    "test_used": False,
}

print(
    f"✓ Strategy ID        : "
    f"{RF0_CONFIGURATION['strategy_id']}"
)

print(
    f"✓ Strategy name      : "
    f"{RF0_CONFIGURATION['strategy_name']}"
)

print(
    f"✓ Class weighting    : "
    f"{RF0_CONFIGURATION['class_weight']}"
)

print(
    f"✓ Resampling         : "
    f"{RF0_CONFIGURATION['resampling']}"
)

print(
    f"✓ Synthetic sampling : "
    f"{RF0_CONFIGURATION['synthetic_sampling']}"
)

print(
    f"✓ Training partition : "
    f"{RF0_CONFIGURATION['training_partition']}"
)

print(
    f"✓ Evaluation         : "
    f"{RF0_CONFIGURATION['evaluation_partition']}"
)


# ---------------------------------------------------------------
# 2. COMMON RANDOM FOREST CONFIGURATION CHECK
# ---------------------------------------------------------------

print("\n[COMMON RANDOM FOREST CONFIGURATION]")

if not isinstance(
    RF_COMMON_CONFIGURATION,
    dict
):
    raise TypeError(
        "RF_COMMON_CONFIGURATION must be a dictionary."
    )


if RF_COMMON_CONFIGURATION[
    "random_state"
] != RANDOM_SEED:

    raise RuntimeError(
        "RF-0 random_state does not match "
        "the established project RANDOM_SEED."
    )


print(
    f"✓ Number of trees   : "
    f"{RF_COMMON_CONFIGURATION['n_estimators']}"
)

print(
    f"✓ Max features      : "
    f"{RF_COMMON_CONFIGURATION['max_features']}"
)

print(
    f"✓ Max depth         : "
    f"{RF_COMMON_CONFIGURATION['max_depth']}"
)

print(
    f"✓ Bootstrap         : "
    f"{RF_COMMON_CONFIGURATION['bootstrap']}"
)

print(
    f"✓ CPU parallelism   : "
    f"{RF_COMMON_CONFIGURATION['n_jobs']}"
)

print(
    f"✓ Random seed       : "
    f"{RF_COMMON_CONFIGURATION['random_state']}"
)


# ---------------------------------------------------------------
# 3. RF-0 NATURAL-DISTRIBUTION BOUNDARY
# ---------------------------------------------------------------

print("\n[RF-0 NATURAL-DISTRIBUTION BOUNDARY]")


if RF0_CONFIGURATION[
    "class_weight"
] is not None:

    raise RuntimeError(
        "RF-0 must use the natural class distribution "
        "without class weighting."
    )


if RF0_CONFIGURATION[
    "resampling"
]:

    raise RuntimeError(
        "RF-0 must not perform random oversampling "
        "or any other resampling."
    )


if RF0_CONFIGURATION[
    "synthetic_sampling"
]:

    raise RuntimeError(
        "RF-0 must not perform synthetic sampling."
    )


print(
    "✓ Natural Training class distribution retained"
)

print(
    "✓ No class weighting configured"
)

print(
    "✓ No random oversampling configured"
)

print(
    "✓ No SMOTE configured"
)

print(
    "✓ No synthetic sampling configured"
)


# ---------------------------------------------------------------
# 4. PARTITION-ROLE VALIDATION
# ---------------------------------------------------------------

print("\n[TRAINING / VALIDATION / TEST ROLE BOUNDARY]")


if not RF_5_2_4_VALIDATION[
    "training_authorized_for_fitting"
]:

    raise RuntimeError(
        "Training is not authorized for RF-0 model fitting."
    )


if not RF_5_2_4_VALIDATION[
    "validation_reserved_for_comparison"
]:

    raise RuntimeError(
        "Validation is not reserved for RF strategy comparison."
    )


if not RF_5_2_4_VALIDATION[
    "validation_reserved_for_selection"
]:

    raise RuntimeError(
        "Validation is not reserved for RF strategy selection."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_fitting"
]:

    raise RuntimeError(
        "Independent Test is not protected from model fitting."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_comparison"
]:

    raise RuntimeError(
        "Independent Test is not protected from strategy comparison."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_selection"
]:

    raise RuntimeError(
        "Independent Test is not protected from strategy selection."
    )


print(
    "✓ Training authorized for RF-0 model fitting"
)

print(
    "✓ Validation reserved for RF-0 evaluation and comparison"
)

print(
    "✓ Validation reserved for strategy selection"
)

print(
    "✓ Independent Test excluded from model fitting"
)

print(
    "✓ Independent Test excluded from strategy comparison"
)

print(
    "✓ Independent Test excluded from strategy selection"
)


# ---------------------------------------------------------------
# 5. RF-0 OUTPUT BOUNDARY
# ---------------------------------------------------------------

print("\n[RF-0 EXPERIMENT OUTPUT BOUNDARY]")


RF0_OUTPUT_DIR = (
    RF_STRATEGY_EXPERIMENTS_DIR /
    "RF-0"
)


RF0_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


print(
    "✓ RF-0 output directory available:"
)

print(
    f"  {RF0_OUTPUT_DIR}"
)


# ---------------------------------------------------------------
# 6. MODEL-DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[MODEL-DEVELOPMENT BOUNDARY]")


print(
    "✓ No Training feature array loaded"
)

print(
    "✓ No Validation feature array loaded"
)

print(
    "✓ No Test feature array loaded"
)

print(
    "✓ No target array loaded"
)

print(
    "✓ No Random Forest model fitted"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No synthetic samples generated"
)

print(
    "✓ No predictions generated"
)

print(
    "✓ No evaluation metrics calculated"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 7. FINAL RF-0 DEFINITION VALIDATION
# ---------------------------------------------------------------

print("\n[RF-0 DEFINITION VALIDATION]")


RF_5_4_1_VALIDATION = {

    "strategy_id_valid":
        RF0_CONFIGURATION[
            "strategy_id"
        ] == "RF-0",

    "strategy_name_valid":
        RF0_CONFIGURATION[
            "strategy_name"
        ] == "Natural Distribution Baseline",

    "class_weight_disabled":
        RF0_CONFIGURATION[
            "class_weight"
        ] is None,

    "resampling_disabled":
        RF0_CONFIGURATION[
            "resampling"
        ] is False,

    "synthetic_sampling_disabled":
        RF0_CONFIGURATION[
            "synthetic_sampling"
        ] is False,

    "training_partition_valid":
        RF0_CONFIGURATION[
            "training_partition"
        ] == "Training",

    "validation_partition_valid":
        RF0_CONFIGURATION[
            "evaluation_partition"
        ] == "Validation",

    "test_not_used":
        RF0_CONFIGURATION[
            "test_used"
        ] is False,

    "output_directory_available":
        RF0_OUTPUT_DIR.is_dir(),

    "random_state_consistent":
        RF_COMMON_CONFIGURATION[
            "random_state"
        ] == RANDOM_SEED,

    "training_authorized":
        RF_5_2_4_VALIDATION[
            "training_authorized_for_fitting"
        ],

    "validation_reserved_for_comparison":
        RF_5_2_4_VALIDATION[
            "validation_reserved_for_comparison"
        ],

    "test_protected_from_fitting":
        RF_5_2_4_VALIDATION[
            "test_excluded_from_fitting"
        ],

    "test_protected_from_comparison":
        RF_5_2_4_VALIDATION[
            "test_excluded_from_comparison"
        ],

    "test_protected_from_selection":
        RF_5_2_4_VALIDATION[
            "test_excluded_from_selection"
        ],
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_4_1_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "RF-0 baseline definition validation failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 8. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.4.1 — RF-0 BASELINE EXPERIMENT DEFINITION PASSED"
)

print("=" * 72)

print(
    "\nRF-0 Natural Distribution Baseline is defined."
)

print(
    "✓ Common Random Forest configuration retained"
)

print(
    "✓ Natural Training class distribution retained"
)

print(
    "✓ Validation reserved for evaluation"
)

print(
    "✓ Independent Test remains protected"
)

print(
    "✓ No model fitting or data loading performed"
)

print(
    "\nREADY FOR 5.4.2 — "
    "RF-0 TRAINING AND VALIDATION ARTIFACT LOADING"
)

print("=" * 72)

========================================================================
5.4.1 — RF-0 BASELINE EXPERIMENT DEFINITION
========================================================================

[RF-0 STRATEGY DEFINITION]
✓ Strategy ID        : RF-0
✓ Strategy name      : Natural Distribution Baseline
✓ Class weighting    : None
✓ Resampling         : False
✓ Synthetic sampling : False
✓ Training partition : Training
✓ Evaluation         : Validation

[COMMON RANDOM FOREST CONFIGURATION]
✓ Number of trees   : 100
✓ Max features      : sqrt
✓ Max depth         : None
✓ Bootstrap         : True
✓ CPU parallelism   : -1
✓ Random seed       : 42

[RF-0 NATURAL-DISTRIBUTION BOUNDARY]
✓ Natural Training class distribution retained
✓ No class weighting configured
✓ No random oversampling configured
✓ No SMOTE configured
✓ No synthetic sampling configured

[TRAINING / VALIDATION / TEST ROLE BOUNDARY]
✓ Training authorized for RF-0 model fitting
✓ Validation reserved for RF-0 evaluation and comparison
✓ Validation reserved for strategy selection
✓ Independent Test excluded from model fitting
✓ Independent Test excluded from strategy comparison
✓ Independent Test excluded from strategy selection

[RF-0 EXPERIMENT OUTPUT BOUNDARY]
✓ RF-0 output directory available:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0

[MODEL-DEVELOPMENT BOUNDARY]
✓ No Training feature array loaded
✓ No Validation feature array loaded
✓ No Test feature array loaded
✓ No target array loaded
✓ No Random Forest model fitted
✓ No resampling performed
✓ No synthetic samples generated
✓ No predictions generated
✓ No evaluation metrics calculated
✓ Independent Test remains untouched

[RF-0 DEFINITION VALIDATION]

========================================================================
5.4.1 — RF-0 BASELINE EXPERIMENT DEFINITION PASSED
========================================================================

RF-0 Natural Distribution Baseline is defined.
✓ Common Random Forest configuration retained
✓ Natural Training class distribution retained
✓ Validation reserved for evaluation
✓ Independent Test remains protected
✓ No model fitting or data loading performed

READY FOR 5.4.2 — RF-0 TRAINING AND VALIDATION ARTIFACT LOADING
========================================================================

### 5.4.2 — RF-0 Training and Validation Artifact Loading

This subsection loads the finalized Notebook 04 Training and Validation
artifacts required for the RF-0 Natural Distribution Baseline.

The model-ready feature and target artifacts are accessed directly from the
authoritative paths established in Section 5.1. The persisted NumPy arrays
are opened using read-only memory mapping so that the complete Training and
Validation partitions are not duplicated in RAM.

The RF-0 experiment uses:

- Training features and targets for Random Forest model fitting.
- Validation features and targets for RF-0 performance evaluation and later
  strategy comparison.
- No Independent Test artifacts during RF-0 development.

The Training and Validation partitions retain the complete N04 model-ready
representation of 32 float32 features and their corresponding int64 target
labels.

No feature transformation, scaling, resampling, class weighting, or synthetic
sampling is performed during artifact loading.

The Independent Test partition remains completely untouched.

The loaded memory-mapped artifacts will be reused by the subsequent RF-0
training and validation stages without creating unnecessary full-array copies.

In [ ]:
# ================================================================
# 5.4.2 — RF-0 TRAINING AND VALIDATION ARTIFACT LOADING
# ================================================================

import numpy as np


print("=" * 72)
print("5.4.2 — RF-0 TRAINING AND VALIDATION ARTIFACT LOADING")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-0 ARTIFACT LOADING BOUNDARY
# ---------------------------------------------------------------

print("\n[RF-0 ARTIFACT LOADING BOUNDARY]")


if not RF_5_4_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-0 baseline definition has not passed validation."
    )


if RF0_CONFIGURATION[
    "training_partition"
] != "Training":

    raise RuntimeError(
        "RF-0 training partition is not the authoritative "
        "Training partition."
    )


if RF0_CONFIGURATION[
    "evaluation_partition"
] != "Validation":

    raise RuntimeError(
        "RF-0 evaluation partition is not the authoritative "
        "Validation partition."
    )


print(
    "✓ RF-0 baseline definition is valid"
)

print(
    "✓ Training artifact authorized for model fitting"
)

print(
    "✓ Validation artifact authorized for RF-0 evaluation"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# 2. AUTHORITATIVE RF-0 ARTIFACT PATHS
# ---------------------------------------------------------------

print("\n[AUTHORITATIVE RF-0 ARTIFACT PATHS]")


RF0_TRAINING_FEATURE_PATH = RF_INPUT_PATHS[
    "Training features"
]

RF0_TRAINING_TARGET_PATH = RF_INPUT_PATHS[
    "Training targets"
]

RF0_VALIDATION_FEATURE_PATH = RF_INPUT_PATHS[
    "Validation features"
]

RF0_VALIDATION_TARGET_PATH = RF_INPUT_PATHS[
    "Validation targets"
]


for artifact_name, artifact_path in {

    "Training features":
        RF0_TRAINING_FEATURE_PATH,

    "Training targets":
        RF0_TRAINING_TARGET_PATH,

    "Validation features":
        RF0_VALIDATION_FEATURE_PATH,

    "Validation targets":
        RF0_VALIDATION_TARGET_PATH,

}.items():

    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"{artifact_name} artifact was not found:\n"
            f"{artifact_path}"
        )

    if artifact_path.stat().st_size == 0:

        raise ValueError(
            f"{artifact_name} artifact is empty:\n"
            f"{artifact_path}"
        )

    print(
        f"✓ {artifact_name:<20}: "
        f"{artifact_path.name}"
    )


# ---------------------------------------------------------------
# 3. READ-ONLY MEMORY-MAPPED LOADING
# ---------------------------------------------------------------

print("\n[READ-ONLY MEMORY-MAPPED LOADING]")


# The complete arrays are not copied into normal RAM.
# mmap_mode="r" provides read-only access to the persisted
# NumPy arrays.

RF0_TRAINING_FEATURES = np.load(
    RF0_TRAINING_FEATURE_PATH,
    mmap_mode="r"
)

RF0_TRAINING_TARGETS = np.load(
    RF0_TRAINING_TARGET_PATH,
    mmap_mode="r"
)

RF0_VALIDATION_FEATURES = np.load(
    RF0_VALIDATION_FEATURE_PATH,
    mmap_mode="r"
)

RF0_VALIDATION_TARGETS = np.load(
    RF0_VALIDATION_TARGET_PATH,
    mmap_mode="r"
)


print(
    "✓ Training features opened as read-only memory map"
)

print(
    "✓ Training targets opened as read-only memory map"
)

print(
    "✓ Validation features opened as read-only memory map"
)

print(
    "✓ Validation targets opened as read-only memory map"
)


# ---------------------------------------------------------------
# 4. FEATURE ARTIFACT VALIDATION
# ---------------------------------------------------------------

print("\n[RF-0 FEATURE ARTIFACT VALIDATION]")


if RF0_TRAINING_FEATURES.shape != (
    1_814_018,
    32
):

    raise ValueError(
        "RF-0 Training feature shape mismatch.\n"
        f"Expected: {(1_814_018, 32)}\n"
        f"Observed: {RF0_TRAINING_FEATURES.shape}"
    )


if RF0_VALIDATION_FEATURES.shape != (
    451_215,
    32
):

    raise ValueError(
        "RF-0 Validation feature shape mismatch.\n"
        f"Expected: {(451_215, 32)}\n"
        f"Observed: {RF0_VALIDATION_FEATURES.shape}"
    )


if RF0_TRAINING_FEATURES.dtype != np.float32:

    raise TypeError(
        "RF-0 Training features must use float32."
    )


if RF0_VALIDATION_FEATURES.dtype != np.float32:

    raise TypeError(
        "RF-0 Validation features must use float32."
    )


print(
    f"✓ Training features    : "
    f"{RF0_TRAINING_FEATURES.shape} | "
    f"{RF0_TRAINING_FEATURES.dtype}"
)

print(
    f"✓ Validation features  : "
    f"{RF0_VALIDATION_FEATURES.shape} | "
    f"{RF0_VALIDATION_FEATURES.dtype}"
)


# ---------------------------------------------------------------
# 5. TARGET ARTIFACT VALIDATION
# ---------------------------------------------------------------

print("\n[RF-0 TARGET ARTIFACT VALIDATION]")


if RF0_TRAINING_TARGETS.shape != (
    1_814_018,
):

    raise ValueError(
        "RF-0 Training target shape mismatch.\n"
        f"Expected: {(1_814_018,)}\n"
        f"Observed: {RF0_TRAINING_TARGETS.shape}"
    )


if RF0_VALIDATION_TARGETS.shape != (
    451_215,
):

    raise ValueError(
        "RF-0 Validation target shape mismatch.\n"
        f"Expected: {(451_215,)}\n"
        f"Observed: {RF0_VALIDATION_TARGETS.shape}"
    )


if RF0_TRAINING_TARGETS.dtype != np.int64:

    raise TypeError(
        "RF-0 Training targets must use int64."
    )


if RF0_VALIDATION_TARGETS.dtype != np.int64:

    raise TypeError(
        "RF-0 Validation targets must use int64."
    )


print(
    f"✓ Training targets    : "
    f"{RF0_TRAINING_TARGETS.shape} | "
    f"{RF0_TRAINING_TARGETS.dtype}"
)

print(
    f"✓ Validation targets  : "
    f"{RF0_VALIDATION_TARGETS.shape} | "
    f"{RF0_VALIDATION_TARGETS.dtype}"
)


# ---------------------------------------------------------------
# 6. X/Y OBSERVATION ALIGNMENT
# ---------------------------------------------------------------

print("\n[X/Y OBSERVATION ALIGNMENT]")


if (
    RF0_TRAINING_FEATURES.shape[0]
    != RF0_TRAINING_TARGETS.shape[0]
):

    raise ValueError(
        "RF-0 Training feature/target observation counts "
        "are not aligned."
    )


if (
    RF0_VALIDATION_FEATURES.shape[0]
    != RF0_VALIDATION_TARGETS.shape[0]
):

    raise ValueError(
        "RF-0 Validation feature/target observation counts "
        "are not aligned."
    )


print(
    "✓ Training features and targets are observation-aligned"
)

print(
    "✓ Validation features and targets are observation-aligned"
)


# ---------------------------------------------------------------
# 7. CONFIRM COMMON MODEL-READY FEATURE SPACE
# ---------------------------------------------------------------

print("\n[COMMON RF-0 MODEL-READY FEATURE SPACE]")


if (
    RF0_TRAINING_FEATURES.shape[1]
    != RF0_VALIDATION_FEATURES.shape[1]
):

    raise ValueError(
        "RF-0 Training and Validation feature dimensions "
        "do not match."
    )


if RF0_TRAINING_FEATURES.shape[1] != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-0 feature count does not match the established "
        "N04 model-ready feature contract."
    )


print(
    f"✓ Common RF-0 feature count : "
    f"{RF0_TRAINING_FEATURES.shape[1]}"
)

print(
    "✓ Training and Validation share the same "
    "32-feature model-ready representation"
)


# ---------------------------------------------------------------
# 8. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION]")


print(
    "✓ Independent Test feature artifact was not loaded"
)

print(
    "✓ Independent Test target artifact was not loaded"
)

print(
    "✓ Independent Test remains protected from RF-0 development"
)


# ---------------------------------------------------------------
# 9. MEMORY-AWARE EXECUTION CHECK
# ---------------------------------------------------------------

print("\n[MEMORY-AWARE EXECUTION CHECK]")


if not isinstance(
    RF0_TRAINING_FEATURES,
    np.memmap
):

    raise TypeError(
        "RF-0 Training features were not loaded "
        "as a NumPy memory map."
    )


if not isinstance(
    RF0_TRAINING_TARGETS,
    np.memmap
):

    raise TypeError(
        "RF-0 Training targets were not loaded "
        "as a NumPy memory map."
    )


if not isinstance(
    RF0_VALIDATION_FEATURES,
    np.memmap
):

    raise TypeError(
        "RF-0 Validation features were not loaded "
        "as a NumPy memory map."
    )


if not isinstance(
    RF0_VALIDATION_TARGETS,
    np.memmap
):

    raise TypeError(
        "RF-0 Validation targets were not loaded "
        "as a NumPy memory map."
    )


print(
    "✓ Training features remain memory-mapped"
)

print(
    "✓ Training targets remain memory-mapped"
)

print(
    "✓ Validation features remain memory-mapped"
)

print(
    "✓ Validation targets remain memory-mapped"
)

print(
    "✓ No full-array RAM duplication performed"
)


# ---------------------------------------------------------------
# 10. FINAL RF-0 ARTIFACT LOADING VALIDATION
# ---------------------------------------------------------------

RF_5_4_2_VALIDATION = {

    "training_features_loaded":
        RF0_TRAINING_FEATURES.shape
        == (1_814_018, 32),

    "training_targets_loaded":
        RF0_TRAINING_TARGETS.shape
        == (1_814_018,),

    "validation_features_loaded":
        RF0_VALIDATION_FEATURES.shape
        == (451_215, 32),

    "validation_targets_loaded":
        RF0_VALIDATION_TARGETS.shape
        == (451_215,),

    "training_feature_dtype":
        RF0_TRAINING_FEATURES.dtype
        == np.float32,

    "validation_feature_dtype":
        RF0_VALIDATION_FEATURES.dtype
        == np.float32,

    "training_target_dtype":
        RF0_TRAINING_TARGETS.dtype
        == np.int64,

    "validation_target_dtype":
        RF0_VALIDATION_TARGETS.dtype
        == np.int64,

    "training_xy_alignment":
        RF0_TRAINING_FEATURES.shape[0]
        == RF0_TRAINING_TARGETS.shape[0],

    "validation_xy_alignment":
        RF0_VALIDATION_FEATURES.shape[0]
        == RF0_VALIDATION_TARGETS.shape[0],

    "common_feature_space":
        RF0_TRAINING_FEATURES.shape[1]
        == RF0_VALIDATION_FEATURES.shape[1]
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "training_features_memory_mapped":
        isinstance(
            RF0_TRAINING_FEATURES,
            np.memmap
        ),

    "training_targets_memory_mapped":
        isinstance(
            RF0_TRAINING_TARGETS,
            np.memmap
        ),

    "validation_features_memory_mapped":
        isinstance(
            RF0_VALIDATION_FEATURES,
            np.memmap
        ),

    "validation_targets_memory_mapped":
        isinstance(
            RF0_VALIDATION_TARGETS,
            np.memmap
        ),

    "independent_test_not_loaded":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_4_2_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.4.2 RF-0 Training and Validation Artifact "
        "Loading failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 11. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.4.2 — RF-0 TRAINING AND VALIDATION "
    "ARTIFACT LOADING PASSED"
)

print("=" * 72)

print(
    "\n✓ Complete Training partition is available "
    "through read-only memory mapping"
)

print(
    "✓ Complete Validation partition is available "
    "through read-only memory mapping"
)

print(
    "✓ Training and Validation X/y dimensions are aligned"
)

print(
    "✓ Common 32-feature float32 representation confirmed"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ No resampling or synthetic sampling performed"
)

print(
    "\nREADY FOR 5.4.3 — RF-0 RANDOM FOREST MODEL FITTING"
)

print("=" * 72)

========================================================================
5.4.2 — RF-0 TRAINING AND VALIDATION ARTIFACT LOADING
========================================================================

[RF-0 ARTIFACT LOADING BOUNDARY]
✓ RF-0 baseline definition is valid
✓ Training artifact authorized for model fitting
✓ Validation artifact authorized for RF-0 evaluation
✓ Independent Test remains excluded

[AUTHORITATIVE RF-0 ARTIFACT PATHS]
✓ Training features   : X_train_scaled.npy
✓ Training targets    : y_train.npy
✓ Validation features : X_validation_scaled.npy
✓ Validation targets  : y_validation.npy

[READ-ONLY MEMORY-MAPPED LOADING]
✓ Training features opened as read-only memory map
✓ Training targets opened as read-only memory map
✓ Validation features opened as read-only memory map
✓ Validation targets opened as read-only memory map

[RF-0 FEATURE ARTIFACT VALIDATION]
✓ Training features    : (1814018, 32) | float32
✓ Validation features  : (451215, 32) | float32

[RF-0 TARGET ARTIFACT VALIDATION]
✓ Training targets    : (1814018,) | int64
✓ Validation targets  : (451215,) | int64

[X/Y OBSERVATION ALIGNMENT]
✓ Training features and targets are observation-aligned
✓ Validation features and targets are observation-aligned

[COMMON RF-0 MODEL-READY FEATURE SPACE]
✓ Common RF-0 feature count : 32
✓ Training and Validation share the same 32-feature model-ready representation

[INDEPENDENT TEST PROTECTION]
✓ Independent Test feature artifact was not loaded
✓ Independent Test target artifact was not loaded
✓ Independent Test remains protected from RF-0 development

[MEMORY-AWARE EXECUTION CHECK]
✓ Training features remain memory-mapped
✓ Training targets remain memory-mapped
✓ Validation features remain memory-mapped
✓ Validation targets remain memory-mapped
✓ No full-array RAM duplication performed

========================================================================
5.4.2 — RF-0 TRAINING AND VALIDATION ARTIFACT LOADING PASSED
========================================================================

✓ Complete Training partition is available through read-only memory mapping
✓ Complete Validation partition is available through read-only memory mapping
✓ Training and Validation X/y dimensions are aligned
✓ Common 32-feature float32 representation confirmed
✓ Independent Test remains completely untouched
✓ No resampling or synthetic sampling performed

READY FOR 5.4.3 — RF-0 RANDOM FOREST MODEL FITTING
========================================================================

### 5.4.3 — RF-0 Random Forest Model Fitting

This subsection fits the RF-0 Natural Distribution Baseline using the
complete authoritative Training partition loaded in Section 5.4.2.

The RF-0 model uses the common Random Forest configuration established in
Section 5.3.1 while retaining the natural Training class distribution.
No class weighting, random oversampling, SMOTE, or other synthetic sampling
is applied.

The fitted model uses the finalized 32-feature model-ready representation
and the established project random seed of 42. The complete Training
partition is used for model fitting, while the Validation partition remains
reserved for the subsequent RF-0 evaluation stage.

Training and Validation artifacts remain read-only memory-mapped inputs.
No Independent Test artifact is loaded or accessed during model fitting.

Training time and process-level memory state are recorded for subsequent
resource analysis. Model persistence is handled in a later RF-0 artifact
persistence subsection; this stage is responsible only for model fitting
and fit validation.

In [ ]:
# ================================================================
# 5.4.3 — RF-0 RANDOM FOREST MODEL FITTING
# ================================================================

from sklearn.ensemble import RandomForestClassifier
import numpy as np
import time


print("=" * 72)
print("5.4.3 — RF-0 RANDOM FOREST MODEL FITTING")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-0 FITTING BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-0 FITTING BOUNDARY VALIDATION]")


if not RF_5_4_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-0 baseline definition has not passed validation."
    )


if not RF_5_4_2_VALIDATION[
    "training_features_loaded"
]:

    raise RuntimeError(
        "RF-0 Training features are not available "
        "for model fitting."
    )


if not RF_5_4_2_VALIDATION[
    "training_targets_loaded"
]:

    raise RuntimeError(
        "RF-0 Training targets are not available "
        "for model fitting."
    )


if not RF_5_4_2_VALIDATION[
    "training_xy_alignment"
]:

    raise RuntimeError(
        "RF-0 Training features and targets are not aligned."
    )


if not RF_5_4_2_VALIDATION[
    "training_features_memory_mapped"
]:

    raise RuntimeError(
        "RF-0 Training features are not memory-mapped."
    )


if RF0_CONFIGURATION[
    "class_weight"
] is not None:

    raise RuntimeError(
        "RF-0 model fitting must use class_weight=None."
    )


if RF0_CONFIGURATION[
    "resampling"
]:

    raise RuntimeError(
        "RF-0 model fitting must not perform resampling."
    )


if RF0_CONFIGURATION[
    "synthetic_sampling"
]:

    raise RuntimeError(
        "RF-0 model fitting must not perform synthetic sampling."
    )


if not RF_5_2_4_VALIDATION[
    "training_authorized_for_fitting"
]:

    raise RuntimeError(
        "Training partition is not authorized for "
        "RF-0 model fitting."
    )


print(
    "✓ RF-0 baseline definition validated"
)

print(
    "✓ Complete Training features available"
)

print(
    "✓ Complete Training targets available"
)

print(
    "✓ Training features and targets are aligned"
)

print(
    "✓ Training features remain memory-mapped"
)

print(
    "✓ Natural class distribution confirmed"
)

print(
    "✓ No class weighting configured"
)

print(
    "✓ No resampling configured"
)

print(
    "✓ No synthetic sampling configured"
)

print(
    "✓ Training partition authorized for model fitting"
)


# ---------------------------------------------------------------
# 2. TRAINING FEATURE-SPACE VALIDATION
# ---------------------------------------------------------------

print("\n[TRAINING FEATURE-SPACE VALIDATION]")


if RF0_TRAINING_FEATURES.shape[1] != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-0 Training feature count does not match "
        "the established model-ready feature contract."
    )


if RF0_TRAINING_FEATURES.dtype != np.float32:

    raise TypeError(
        "RF-0 Training features must use float32."
    )


if RF0_TRAINING_FEATURES.shape[1] != len(
    RF_FEATURE_ORDER
):

    raise ValueError(
        "RF-0 Training feature count does not match "
        "the frozen RF feature order."
    )


print(
    f"✓ Training observations : "
    f"{RF0_TRAINING_FEATURES.shape[0]:,}"
)

print(
    f"✓ Training features     : "
    f"{RF0_TRAINING_FEATURES.shape[1]}"
)

print(
    f"✓ Training dtype        : "
    f"{RF0_TRAINING_FEATURES.dtype}"
)

print(
    "✓ Training feature space matches "
    "the frozen RF model-ready contract"
)


# ---------------------------------------------------------------
# 3. NATURAL TRAINING CLASS DISTRIBUTION
# ---------------------------------------------------------------

print("\n[RF-0 NATURAL TRAINING CLASS DISTRIBUTION]")


RF0_TRAINING_CLASS_IDS, RF0_TRAINING_CLASS_COUNTS = (
    np.unique(
        RF0_TRAINING_TARGETS,
        return_counts=True
    )
)


RF0_TRAINING_CLASS_DISTRIBUTION = {
    int(class_id): int(class_count)
    for class_id, class_count
    in zip(
        RF0_TRAINING_CLASS_IDS,
        RF0_TRAINING_CLASS_COUNTS
    )
}


if not np.array_equal(
    RF0_TRAINING_CLASS_IDS,
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    )
):

    raise ValueError(
        "RF-0 Training target classes do not match "
        "the established 0–8 RF taxonomy."
    )


for class_id, class_count in (
    RF0_TRAINING_CLASS_DISTRIBUTION.items()
):

    print(
        f"✓ Class {class_id}: "
        f"{RF_CLASS_MAPPING[class_id]:<24} "
        f"{class_count:,}"
    )


print(
    "✓ Complete natural Training class distribution "
    "retained for RF-0"
)


# ---------------------------------------------------------------
# 4. RF-0 MODEL CONSTRUCTION
# ---------------------------------------------------------------

print("\n[RF-0 MODEL CONSTRUCTION]")


RF0_MODEL = RandomForestClassifier(
    **RF_COMMON_CONFIGURATION,
    class_weight=RF0_CONFIGURATION[
        "class_weight"
    ]
)


if not isinstance(
    RF0_MODEL,
    RandomForestClassifier
):

    raise TypeError(
        "RF0_MODEL was not created as a "
        "RandomForestClassifier."
    )


if RF0_MODEL.n_estimators != (
    RF_COMMON_CONFIGURATION[
        "n_estimators"
    ]
):

    raise RuntimeError(
        "RF-0 model n_estimators does not match "
        "the common Random Forest configuration."
    )


if RF0_MODEL.max_features != (
    RF_COMMON_CONFIGURATION[
        "max_features"
    ]
):

    raise RuntimeError(
        "RF-0 model max_features does not match "
        "the common Random Forest configuration."
    )


if RF0_MODEL.max_depth != (
    RF_COMMON_CONFIGURATION[
        "max_depth"
    ]
):

    raise RuntimeError(
        "RF-0 model max_depth does not match "
        "the common Random Forest configuration."
    )


if RF0_MODEL.bootstrap != (
    RF_COMMON_CONFIGURATION[
        "bootstrap"
    ]
):

    raise RuntimeError(
        "RF-0 model bootstrap configuration does not "
        "match the common Random Forest configuration."
    )


if RF0_MODEL.n_jobs != (
    RF_COMMON_CONFIGURATION[
        "n_jobs"
    ]
):

    raise RuntimeError(
        "RF-0 model n_jobs configuration does not "
        "match the common Random Forest configuration."
    )


if RF0_MODEL.random_state != (
    RF_COMMON_CONFIGURATION[
        "random_state"
    ]
):

    raise RuntimeError(
        "RF-0 model random_state does not "
        "match the established project seed."
    )


if RF0_MODEL.class_weight is not None:

    raise RuntimeError(
        "RF-0 must use class_weight=None."
    )


print(
    f"✓ Random Forest trees     : "
    f"{RF0_MODEL.n_estimators}"
)

print(
    f"✓ Max features           : "
    f"{RF0_MODEL.max_features}"
)

print(
    f"✓ Max depth              : "
    f"{RF0_MODEL.max_depth}"
)

print(
    f"✓ Bootstrap               : "
    f"{RF0_MODEL.bootstrap}"
)

print(
    f"✓ CPU parallelism        : "
    f"{RF0_MODEL.n_jobs}"
)

print(
    f"✓ Random state            : "
    f"{RF0_MODEL.random_state}"
)

print(
    "✓ Class weighting         : None"
)

print(
    "✓ RF-0 Random Forest model constructed"
)


# ---------------------------------------------------------------
# 5. RESOURCE STATE BEFORE FITTING
# ---------------------------------------------------------------

print("\n[RESOURCE STATE BEFORE RF-0 FITTING]")


RF_MEMORY = psutil.virtual_memory()

RF0_AVAILABLE_MEMORY_BEFORE_GB = (
    RF_MEMORY.available / (1024 ** 3)
)

RF0_PROCESS_MEMORY_BEFORE_GB = (
    RF_PROCESS.memory_info().rss / (1024 ** 3)
)


print(
    f"✓ Available system RAM : "
    f"{RF0_AVAILABLE_MEMORY_BEFORE_GB:.2f} GB"
)

print(
    f"✓ Python process RAM   : "
    f"{RF0_PROCESS_MEMORY_BEFORE_GB:.2f} GB"
)

print(
    "✓ Training input remains memory-mapped"
)

print(
    "✓ Validation input remains loaded but unused "
    "during model fitting"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 6. RF-0 MODEL FITTING
# ---------------------------------------------------------------

print("\n[RF-0 MODEL FITTING]")


RF0_TRAINING_START_TIME = time.perf_counter()


RF0_MODEL.fit(
    RF0_TRAINING_FEATURES,
    RF0_TRAINING_TARGETS
)


RF0_TRAINING_END_TIME = time.perf_counter()


RF0_TRAINING_TIME_SECONDS = (
    RF0_TRAINING_END_TIME
    - RF0_TRAINING_START_TIME
)


print(
    "✓ RF-0 model fitting completed"
)

print(
    f"✓ Training time : "
    f"{RF0_TRAINING_TIME_SECONDS:.3f} seconds"
)


# ---------------------------------------------------------------
# 7. RESOURCE STATE AFTER FITTING
# ---------------------------------------------------------------

print("\n[RESOURCE STATE AFTER RF-0 FITTING]")


RF_MEMORY = psutil.virtual_memory()

RF0_AVAILABLE_MEMORY_AFTER_GB = (
    RF_MEMORY.available / (1024 ** 3)
)

RF0_PROCESS_MEMORY_AFTER_GB = (
    RF_PROCESS.memory_info().rss / (1024 ** 3)
)


RF0_PROCESS_MEMORY_DELTA_GB = (
    RF0_PROCESS_MEMORY_AFTER_GB
    - RF0_PROCESS_MEMORY_BEFORE_GB
)


print(
    f"✓ Available system RAM : "
    f"{RF0_AVAILABLE_MEMORY_AFTER_GB:.2f} GB"
)

print(
    f"✓ Python process RAM   : "
    f"{RF0_PROCESS_MEMORY_AFTER_GB:.2f} GB"
)

print(
    f"✓ Process RAM change   : "
    f"{RF0_PROCESS_MEMORY_DELTA_GB:+.2f} GB"
)


# ---------------------------------------------------------------
# 8. FITTED MODEL STRUCTURE VALIDATION
# ---------------------------------------------------------------

print("\n[RF-0 FITTED MODEL VALIDATION]")


if not hasattr(
    RF0_MODEL,
    "n_features_in_"
):

    raise RuntimeError(
        "RF-0 fitted model does not expose "
        "n_features_in_."
    )


if RF0_MODEL.n_features_in_ != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-0 fitted model feature count does not "
        "match the established 32-feature contract."
    )


if not hasattr(
    RF0_MODEL,
    "classes_"
):

    raise RuntimeError(
        "RF-0 fitted model does not expose classes_."
    )


if not np.array_equal(
    RF0_MODEL.classes_,
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    )
):

    raise ValueError(
        "RF-0 fitted model classes do not match "
        "the established 0–8 taxonomy."
    )


if not hasattr(
    RF0_MODEL,
    "estimators_"
):

    raise RuntimeError(
        "RF-0 fitted model does not contain "
        "trained estimators."
    )


if len(
    RF0_MODEL.estimators_
) != RF_COMMON_CONFIGURATION[
    "n_estimators"
]:

    raise RuntimeError(
        "RF-0 fitted model does not contain the "
        "expected number of trained trees."
    )


print(
    f"✓ Fitted model feature count : "
    f"{RF0_MODEL.n_features_in_}"
)

print(
    f"✓ Fitted model classes       : "
    f"{len(RF0_MODEL.classes_)}"
)

print(
    f"✓ Fitted model tree count    : "
    f"{len(RF0_MODEL.estimators_)}"
)

print(
    "✓ RF-0 fitted model matches "
    "the established feature and taxonomy contracts"
)


# ---------------------------------------------------------------
# 9. DEVELOPMENT-BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-0 DEVELOPMENT-BOUNDARY VALIDATION]")


print(
    "✓ RF-0 fitted only on the Training partition"
)

print(
    "✓ Validation targets were not used for fitting"
)

print(
    "✓ Validation predictions were not generated"
)

print(
    "✓ Independent Test features were not loaded"
)

print(
    "✓ Independent Test targets were not loaded"
)

print(
    "✓ No class weighting was applied"
)

print(
    "✓ No random oversampling was applied"
)

print(
    "✓ No SMOTE was applied"
)

print(
    "✓ No synthetic samples were generated"
)

print(
    "✓ No strategy selection was performed"
)

print(
    "✓ No RF-0 evaluation metrics were calculated"
)

print(
    "✓ Model persistence was not performed in this subsection"
)


# ---------------------------------------------------------------
# 10. FINAL RF-0 FITTING VALIDATION
# ---------------------------------------------------------------

RF_5_4_3_VALIDATION = {

    "rf0_strategy_valid":
        RF0_CONFIGURATION[
            "strategy_id"
        ] == "RF-0",

    "training_partition_used":
        RF0_TRAINING_FEATURES.shape
        == (
            1_814_018,
            32
        ),

    "training_targets_used":
        RF0_TRAINING_TARGETS.shape
        == (
            1_814_018,
        ),

    "training_feature_dtype":
        RF0_TRAINING_FEATURES.dtype
        == np.float32,

    "training_target_dtype":
        RF0_TRAINING_TARGETS.dtype
        == np.int64,

    "natural_distribution":
        RF0_CONFIGURATION[
            "class_weight"
        ] is None
        and RF0_CONFIGURATION[
            "resampling"
        ] is False
        and RF0_CONFIGURATION[
            "synthetic_sampling"
        ] is False,

    "feature_count_valid":
        RF0_MODEL.n_features_in_
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "taxonomy_valid":
        np.array_equal(
            RF0_MODEL.classes_,
            np.asarray(
                EXPECTED_RF_CLASS_IDS
            )
        ),

    "tree_count_valid":
        len(
            RF0_MODEL.estimators_
        )
        == RF_COMMON_CONFIGURATION[
            "n_estimators"
        ],

    "random_state_valid":
        RF0_MODEL.random_state
        == RANDOM_SEED,

    "training_time_recorded":
        RF0_TRAINING_TIME_SECONDS > 0,

    "independent_test_not_used":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_4_3_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.4.3 RF-0 model fitting validation failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 11. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.4.3 — RF-0 RANDOM FOREST MODEL FITTING PASSED"
)

print("=" * 72)

print(
    "\n✓ RF-0 Natural Distribution Baseline fitted successfully"
)

print(
    "✓ Complete Training partition used for model fitting"
)

print(
    "✓ Natural Training class distribution retained"
)

print(
    "✓ Common Random Forest configuration retained"
)

print(
    "✓ 32-feature model-ready representation confirmed"
)

print(
    "✓ Nine-class taxonomy confirmed"
)

print(
    "✓ Validation remains reserved for subsequent RF-0 evaluation"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ No resampling or synthetic sampling performed"
)

print(
    "\nREADY FOR 5.4.4 — "
    "RF-0 VALIDATION EVALUATION"
)

print("=" * 72)

========================================================================
5.4.3 — RF-0 RANDOM FOREST MODEL FITTING
========================================================================

[RF-0 FITTING BOUNDARY VALIDATION]
✓ RF-0 baseline definition validated
✓ Complete Training features available
✓ Complete Training targets available
✓ Training features and targets are aligned
✓ Training features remain memory-mapped
✓ Natural class distribution confirmed
✓ No class weighting configured
✓ No resampling configured
✓ No synthetic sampling configured
✓ Training partition authorized for model fitting

[TRAINING FEATURE-SPACE VALIDATION]
✓ Training observations : 1,814,018
✓ Training features     : 32
✓ Training dtype        : float32
✓ Training feature space matches the frozen RF model-ready contract

[RF-0 NATURAL TRAINING CLASS DISTRIBUTION]
✓ Class 0: BENIGN                   1,448,197
✓ Class 1: DDoS                     81,968
✓ Class 2: Port Scan                101,723
✓ Class 3: Brute Force              9,325
✓ Class 4: Bot                      1,270
✓ Class 5: Web Attack               1,389
✓ Class 6: Infiltration             15
✓ Class 7: DoS                      170,125
✓ Class 8: Heartbleed               6
✓ Complete natural Training class distribution retained for RF-0

[RF-0 MODEL CONSTRUCTION]
✓ Random Forest trees     : 100
✓ Max features           : sqrt
✓ Max depth              : None
✓ Bootstrap               : True
✓ CPU parallelism        : -1
✓ Random state            : 42
✓ Class weighting         : None
✓ RF-0 Random Forest model constructed

[RESOURCE STATE BEFORE RF-0 FITTING]
✓ Available system RAM : 10.01 GB
✓ Python process RAM   : 1.28 GB
✓ Training input remains memory-mapped
✓ Validation input remains loaded but unused during model fitting
✓ Independent Test remains untouched

[RF-0 MODEL FITTING]
✓ RF-0 model fitting completed
✓ Training time : 791.112 seconds

[RESOURCE STATE AFTER RF-0 FITTING]
✓ Available system RAM : 9.96 GB
✓ Python process RAM   : 1.64 GB
✓ Process RAM change   : +0.36 GB

[RF-0 FITTED MODEL VALIDATION]
✓ Fitted model feature count : 32
✓ Fitted model classes       : 9
✓ Fitted model tree count    : 100
✓ RF-0 fitted model matches the established feature and taxonomy contracts

[RF-0 DEVELOPMENT-BOUNDARY VALIDATION]
✓ RF-0 fitted only on the Training partition
✓ Validation targets were not used for fitting
✓ Validation predictions were not generated
✓ Independent Test features were not loaded
✓ Independent Test targets were not loaded
✓ No class weighting was applied
✓ No random oversampling was applied
✓ No SMOTE was applied
✓ No synthetic samples were generated
✓ No strategy selection was performed
✓ No RF-0 evaluation metrics were calculated
✓ Model persistence was not performed in this subsection

========================================================================
5.4.3 — RF-0 RANDOM FOREST MODEL FITTING PASSED
========================================================================

✓ RF-0 Natural Distribution Baseline fitted successfully
✓ Complete Training partition used for model fitting
✓ Natural Training class distribution retained
✓ Common Random Forest configuration retained
✓ 32-feature model-ready representation confirmed
✓ Nine-class taxonomy confirmed
✓ Validation remains reserved for subsequent RF-0 evaluation
✓ Independent Test remains completely untouched
✓ No resampling or synthetic sampling performed

READY FOR 5.4.4 — RF-0 VALIDATION EVALUATION
========================================================================

## 5.4.4 — RF-0 Validation Prediction and Performance Evaluation

This subsection evaluates the fitted RF-0 Natural Distribution Baseline on the
reserved Validation partition.

The RF-0 model is evaluated using the complete Validation feature and target
artifacts established in Section 5.4.2. Validation is used exclusively for
performance measurement and later strategy comparison; it is not used for model
fitting.

The evaluation follows the metric configuration established in Section 5.3.3:

- **Primary strategy-selection metric:** Macro F1
- **Secondary metrics:** Macro Recall, Balanced Accuracy, Weighted F1, Accuracy
- **Per-class metrics:** Precision, Recall, and F1-score
- **Error analysis:** Confusion Matrix, BENIGN False-Positive Rate, and Attack
  False Negatives
- **Supplementary metric:** Multiclass ROC-AUC, where probability outputs and
  class support permit reliable computation

The Independent Test partition remains completely protected and is not loaded,
predicted, or evaluated in this subsection.

No model parameters, class-weighting configuration, or training data are
modified during evaluation.

In [ ]:
# ================================================================
# 5.4.4 — RF-0 VALIDATION PREDICTION AND PERFORMANCE EVALUATION
# ================================================================

import numpy as np
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_recall_fscore_support,
    f1_score,
    recall_score,
    confusion_matrix,
    roc_auc_score
)

print("=" * 72)
print("5.4.4 — RF-0 VALIDATION PREDICTION AND PERFORMANCE EVALUATION")
print("=" * 72)

# ------------------------------------------------
# [RF-0 EVALUATION BOUNDARY VALIDATION]
# ------------------------------------------------

print("\n[RF-0 EVALUATION BOUNDARY VALIDATION]")

if RF0_MODEL is None:
    raise ValueError("RF-0 fitted model is not available.")

if RF0_VALIDATION_FEATURES.shape != (451215, 32):
    raise ValueError(
        f"Unexpected RF-0 Validation feature shape: "
        f"{RF0_VALIDATION_FEATURES.shape}"
    )

if RF0_VALIDATION_TARGETS.shape != (451215,):
    raise ValueError(
        f"Unexpected RF-0 Validation target shape: "
        f"{RF0_VALIDATION_TARGETS.shape}"
    )

if RF0_VALIDATION_FEATURES.dtype != np.float32:
    raise TypeError(
        f"RF-0 Validation features must be float32, "
        f"got {RF0_VALIDATION_FEATURES.dtype}"
    )

if RF0_VALIDATION_TARGETS.dtype != np.int64:
    raise TypeError(
        f"RF-0 Validation targets must be int64, "
        f"got {RF0_VALIDATION_TARGETS.dtype}"
    )

if len(RF0_VALIDATION_FEATURES) != len(RF0_VALIDATION_TARGETS):
    raise ValueError("RF-0 Validation X/y observations are not aligned.")

print("✓ RF-0 fitted model is available")
print("✓ Complete Validation feature artifact is available")
print("✓ Complete Validation target artifact is available")
print("✓ Validation X/y observations are aligned")
print("✓ Validation feature representation = 32 float32 features")
print("✓ Independent Test remains excluded")


# ------------------------------------------------
# [RF-0 VALIDATION PREDICTION]
# ------------------------------------------------

print("\n[RF-0 VALIDATION PREDICTION]")

RF0_VALIDATION_PREDICTIONS = RF0_MODEL.predict(
    RF0_VALIDATION_FEATURES
)

if RF0_VALIDATION_PREDICTIONS.shape != RF0_VALIDATION_TARGETS.shape:
    raise ValueError(
        "RF-0 Validation prediction shape does not match Validation targets."
    )

if not np.isfinite(RF0_VALIDATION_PREDICTIONS).all():
    raise ValueError(
        "RF-0 Validation predictions contain non-finite values."
    )

print(
    f"✓ Validation predictions generated : "
    f"{RF0_VALIDATION_PREDICTIONS.shape[0]:,}"
)

print("✓ Validation predictions correspond to the complete Validation partition")
print("✓ No Independent Test predictions generated")


# ------------------------------------------------
# [PRIMARY AND SECONDARY PERFORMANCE METRICS]
# ------------------------------------------------

print("\n[PRIMARY AND SECONDARY PERFORMANCE METRICS]")

RF0_VALIDATION_ACCURACY = accuracy_score(
    RF0_VALIDATION_TARGETS,
    RF0_VALIDATION_PREDICTIONS
)

RF0_VALIDATION_BALANCED_ACCURACY = balanced_accuracy_score(
    RF0_VALIDATION_TARGETS,
    RF0_VALIDATION_PREDICTIONS
)

RF0_VALIDATION_MACRO_F1 = f1_score(
    RF0_VALIDATION_TARGETS,
    RF0_VALIDATION_PREDICTIONS,
    average="macro",
    zero_division=0
)

RF0_VALIDATION_MACRO_RECALL = recall_score(
    RF0_VALIDATION_TARGETS,
    RF0_VALIDATION_PREDICTIONS,
    average="macro",
    zero_division=0
)

RF0_VALIDATION_WEIGHTED_F1 = f1_score(
    RF0_VALIDATION_TARGETS,
    RF0_VALIDATION_PREDICTIONS,
    average="weighted",
    zero_division=0
)

print(f"✓ Accuracy              : {RF0_VALIDATION_ACCURACY:.6f}")
print(f"✓ Balanced Accuracy     : {RF0_VALIDATION_BALANCED_ACCURACY:.6f}")
print(f"✓ Macro Recall          : {RF0_VALIDATION_MACRO_RECALL:.6f}")
print(f"✓ Macro F1              : {RF0_VALIDATION_MACRO_F1:.6f}")
print(f"✓ Weighted F1           : {RF0_VALIDATION_WEIGHTED_F1:.6f}")


# ------------------------------------------------
# [PER-CLASS PERFORMANCE METRICS]
# ------------------------------------------------

print("\n[PER-CLASS PERFORMANCE METRICS]")

RF0_VALIDATION_PRECISION_PER_CLASS, \
RF0_VALIDATION_RECALL_PER_CLASS, \
RF0_VALIDATION_F1_PER_CLASS, \
RF0_VALIDATION_SUPPORT_PER_CLASS = precision_recall_fscore_support(
    RF0_VALIDATION_TARGETS,
    RF0_VALIDATION_PREDICTIONS,
    labels=np.arange(9),
    zero_division=0
)

RF0_VALIDATION_CLASS_NAMES = [
    "BENIGN",
    "DDoS",
    "Port Scan",
    "Brute Force",
    "Bot",
    "Web Attack",
    "Infiltration",
    "DoS",
    "Heartbleed"
]

for class_id, class_name in enumerate(RF0_VALIDATION_CLASS_NAMES):
    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Precision={RF0_VALIDATION_PRECISION_PER_CLASS[class_id]:.6f} | "
        f"Recall={RF0_VALIDATION_RECALL_PER_CLASS[class_id]:.6f} | "
        f"F1={RF0_VALIDATION_F1_PER_CLASS[class_id]:.6f} | "
        f"Support={RF0_VALIDATION_SUPPORT_PER_CLASS[class_id]:,}"
    )


# ------------------------------------------------
# [CONFUSION MATRIX]
# ------------------------------------------------

print("\n[CONFUSION MATRIX]")

RF0_VALIDATION_CONFUSION_MATRIX = confusion_matrix(
    RF0_VALIDATION_TARGETS,
    RF0_VALIDATION_PREDICTIONS,
    labels=np.arange(9)
)

if RF0_VALIDATION_CONFUSION_MATRIX.shape != (9, 9):
    raise ValueError(
        f"Unexpected RF-0 confusion-matrix shape: "
        f"{RF0_VALIDATION_CONFUSION_MATRIX.shape}"
    )

print("✓ 9 × 9 confusion matrix generated")
print("✓ All nine taxonomy classes included")

print("\nRF-0 Validation Confusion Matrix:")
print(RF0_VALIDATION_CONFUSION_MATRIX)


# ------------------------------------------------
# [BENIGN FALSE-POSITIVE RATE]
# ------------------------------------------------

print("\n[BENIGN FALSE-POSITIVE RATE]")

RF0_BENIGN_TRUE_NEGATIVES = (
    RF0_VALIDATION_CONFUSION_MATRIX[0, 0]
)

RF0_BENIGN_FALSE_POSITIVES = (
    RF0_VALIDATION_CONFUSION_MATRIX[:, 0].sum()
    - RF0_BENIGN_TRUE_NEGATIVES
)

RF0_BENIGN_ACTUAL_NEGATIVES = (
    RF0_VALIDATION_CONFUSION_MATRIX[1:, :].sum()
)

if RF0_BENIGN_ACTUAL_NEGATIVES == 0:
    RF0_BENIGN_FALSE_POSITIVE_RATE = 0.0
else:
    RF0_BENIGN_FALSE_POSITIVE_RATE = (
        RF0_BENIGN_FALSE_POSITIVES
        / RF0_BENIGN_ACTUAL_NEGATIVES
    )

print(
    f"✓ BENIGN false-positive rate : "
    f"{RF0_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)


# ------------------------------------------------
# [ATTACK FALSE NEGATIVES]
# ------------------------------------------------

print("\n[ATTACK FALSE NEGATIVES]")

RF0_ATTACK_FALSE_NEGATIVES = {}

for class_id in range(1, 9):
    false_negatives = (
        RF0_VALIDATION_CONFUSION_MATRIX[class_id, :].sum()
        - RF0_VALIDATION_CONFUSION_MATRIX[class_id, class_id]
    )

    RF0_ATTACK_FALSE_NEGATIVES[class_id] = int(false_negatives)

    print(
        f"✓ Class {class_id}: "
        f"{RF0_VALIDATION_CLASS_NAMES[class_id]:<15} "
        f"false negatives = {false_negatives:,}"
    )


# ------------------------------------------------
# [SUPPLEMENTARY MULTICLASS ROC-AUC]
# ------------------------------------------------

print("\n[SUPPLEMENTARY MULTICLASS ROC-AUC]")

RF0_VALIDATION_ROC_AUC = None

try:
    RF0_VALIDATION_PROBABILITIES = RF0_MODEL.predict_proba(
        RF0_VALIDATION_FEATURES
    )

    RF0_VALIDATION_ROC_AUC = roc_auc_score(
        RF0_VALIDATION_TARGETS,
        RF0_VALIDATION_PROBABILITIES,
        multi_class="ovr",
        average="macro",
        labels=np.arange(9)
    )

    print(
        f"✓ Macro ROC-AUC (OvR) : "
        f"{RF0_VALIDATION_ROC_AUC:.6f}"
    )

except ValueError as error:
    print(
        "⚠ Macro ROC-AUC could not be calculated reliably: "
        f"{error}"
    )

# Release only the temporary probability array.
# Validation features/targets and the fitted RF-0 model remain available.
if "RF0_VALIDATION_PROBABILITIES" in locals():
    del RF0_VALIDATION_PROBABILITIES


# ------------------------------------------------
# [RF-0 VALIDATION EVALUATION SUMMARY]
# ------------------------------------------------

print("\n[RF-0 VALIDATION EVALUATION SUMMARY]")

print(f"✓ Primary metric — Macro F1       : {RF0_VALIDATION_MACRO_F1:.6f}")
print(f"✓ Macro Recall                    : {RF0_VALIDATION_MACRO_RECALL:.6f}")
print(f"✓ Balanced Accuracy               : {RF0_VALIDATION_BALANCED_ACCURACY:.6f}")
print(f"✓ Weighted F1                     : {RF0_VALIDATION_WEIGHTED_F1:.6f}")
print(f"✓ Accuracy                        : {RF0_VALIDATION_ACCURACY:.6f}")
print(
    f"✓ BENIGN False-Positive Rate     : "
    f"{RF0_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)

if RF0_VALIDATION_ROC_AUC is not None:
    print(
        f"✓ Macro ROC-AUC (OvR)            : "
        f"{RF0_VALIDATION_ROC_AUC:.6f}"
    )

print("\n[DEVELOPMENT-BOUNDARY VALIDATION]")
print("✓ RF-0 was fitted only on Training")
print("✓ Validation was used only for RF-0 performance evaluation")
print("✓ RF-0 strategy selection has not been performed")
print("✓ Independent Test remains completely untouched")
print("✓ No resampling or synthetic sampling performed")
print("✓ No model parameters modified during evaluation")

print("\n" + "=" * 72)
print("5.4.4 — RF-0 VALIDATION PREDICTION AND PERFORMANCE EVALUATION PASSED")
print("=" * 72)

print("\nRF-0 Validation evaluation completed.")
print("READY FOR 5.4.5 — RF-0 Error and Resource Analysis")
print("=" * 72)

========================================================================
5.4.4 — RF-0 VALIDATION PREDICTION AND PERFORMANCE EVALUATION
========================================================================

[RF-0 EVALUATION BOUNDARY VALIDATION]
✓ RF-0 fitted model is available
✓ Complete Validation feature artifact is available
✓ Complete Validation target artifact is available
✓ Validation X/y observations are aligned
✓ Validation feature representation = 32 float32 features
✓ Independent Test remains excluded

[RF-0 VALIDATION PREDICTION]
✓ Validation predictions generated : 451,215
✓ Validation predictions correspond to the complete Validation partition
✓ No Independent Test predictions generated

[PRIMARY AND SECONDARY PERFORMANCE METRICS]
✓ Accuracy              : 0.997290
✓ Balanced Accuracy     : 0.784928
✓ Macro Recall          : 0.784928
✓ Macro F1              : 0.816640
✓ Weighted F1           : 0.997259

[PER-CLASS PERFORMANCE METRICS]
✓ 0: BENIGN          Precision=0.997894 | Recall=0.998825 | F1=0.998359 | Support=369,501
✓ 1: DDoS            Precision=0.999853 | Recall=0.999804 | F1=0.999829 | Support=20,458
✓ 2: Port Scan       Precision=0.994193 | Recall=0.996318 | F1=0.995255 | Support=25,261
✓ 3: Brute Force     Precision=0.996156 | Recall=0.974221 | F1=0.985067 | Support=1,862
✓ 4: Bot             Precision=0.623574 | Recall=0.552189 | F1=0.585714 | Support=297
✓ 5: Web Attack      Precision=0.991643 | Recall=0.980716 | F1=0.986150 | Support=363
✓ 6: Infiltration    Precision=1.000000 | Recall=0.076923 | F1=0.142857 | Support=13
✓ 7: DoS             Precision=0.994419 | Recall=0.985354 | F1=0.989866 | Support=33,456
✓ 8: Heartbleed      Precision=1.000000 | Recall=0.500000 | F1=0.666667 | Support=4

[CONFUSION MATRIX]
✓ 9 × 9 confusion matrix generated
✓ All nine taxonomy classes included

RF-0 Validation Confusion Matrix:
[[369067      3    143      7     99      3      0    179      0]
 [     3  20454      0      0      0      0      0      1      0]
 [    88      0  25168      0      0      0      0      5      0]
 [    48      0      0   1814      0      0      0      0      0]
 [   133      0      0      0    164      0      0      0      0]
 [     5      0      2      0      0    356      0      0      0]
 [    12      0      0      0      0      0      1      0      0]
 [   488      0      2      0      0      0      0  32966      0]
 [     2      0      0      0      0      0      0      0      2]]

[BENIGN FALSE-POSITIVE RATE]
✓ BENIGN false-positive rate : 0.009533

[ATTACK FALSE NEGATIVES]
✓ Class 1: DDoS            false negatives = 4
✓ Class 2: Port Scan       false negatives = 93
✓ Class 3: Brute Force     false negatives = 48
✓ Class 4: Bot             false negatives = 133
✓ Class 5: Web Attack      false negatives = 7
✓ Class 6: Infiltration    false negatives = 12
✓ Class 7: DoS             false negatives = 490
✓ Class 8: Heartbleed      false negatives = 2

[SUPPLEMENTARY MULTICLASS ROC-AUC]
✓ Macro ROC-AUC (OvR) : 0.994209

[RF-0 VALIDATION EVALUATION SUMMARY]
✓ Primary metric — Macro F1       : 0.816640
✓ Macro Recall                    : 0.784928
✓ Balanced Accuracy               : 0.784928
✓ Weighted F1                     : 0.997259
✓ Accuracy                        : 0.997290
✓ BENIGN False-Positive Rate     : 0.009533
✓ Macro ROC-AUC (OvR)            : 0.994209

[DEVELOPMENT-BOUNDARY VALIDATION]
✓ RF-0 was fitted only on Training
✓ Validation was used only for RF-0 performance evaluation
✓ RF-0 strategy selection has not been performed
✓ Independent Test remains completely untouched
✓ No resampling or synthetic sampling performed
✓ No model parameters modified during evaluation

========================================================================
5.4.4 — RF-0 VALIDATION PREDICTION AND PERFORMANCE EVALUATION PASSED
========================================================================

RF-0 Validation evaluation completed.
READY FOR 5.4.5 — RF-0 Error and Resource Analysis
========================================================================

## 5.4.5 — RF-0 Error and Resource Analysis

This subsection analyzes the validation errors and computational characteristics
of the fitted RF-0 Natural Distribution Baseline.

The analysis focuses on class-wise errors, false negatives, false-positive
behavior, and the dominant confusion pairs observed on the Validation
partition. These observations are used to characterize the behavior of the
natural-distribution baseline before comparing it with alternative imbalance
strategies.

Resource analysis records the current execution-state characteristics and the
computational configuration of the fitted RF-0 model. The previously measured
RF-0 training time is retained as part of the experiment record.

No additional model fitting, resampling, synthetic sampling, strategy
selection, or Independent Test evaluation is performed in this subsection.

The Independent Test partition remains completely protected.

In [ ]:
# ================================================================
# 5.4.5 — RF-0 ERROR AND RESOURCE ANALYSIS
# ================================================================

import os
import psutil
import numpy as np

print("=" * 72)
print("5.4.5 — RF-0 ERROR AND RESOURCE ANALYSIS")
print("=" * 72)


# ------------------------------------------------
# [RF-0 ANALYSIS BOUNDARY VALIDATION]
# ------------------------------------------------

print("\n[RF-0 ANALYSIS BOUNDARY VALIDATION]")

if RF0_MODEL is None:
    raise ValueError("RF-0 fitted model is not available.")

if RF0_VALIDATION_TARGETS.shape != RF0_VALIDATION_PREDICTIONS.shape:
    raise ValueError(
        "RF-0 Validation targets and predictions are not aligned."
    )

if RF0_VALIDATION_CONFUSION_MATRIX.shape != (9, 9):
    raise ValueError(
        "RF-0 Validation confusion matrix must have shape (9, 9)."
    )

print("✓ RF-0 fitted model is available")
print("✓ Validation targets are available")
print("✓ Validation predictions are available")
print("✓ Validation confusion matrix is available")
print("✓ Independent Test remains excluded")
print("✓ No model fitting will be performed")
print("✓ No resampling or synthetic sampling will be performed")


# ------------------------------------------------
# [CLASS-WISE ERROR ANALYSIS]
# ------------------------------------------------

print("\n[CLASS-WISE ERROR ANALYSIS]")

RF0_VALIDATION_CLASS_ERRORS = {}

for class_id, class_name in enumerate(RF0_VALIDATION_CLASS_NAMES):

    actual_count = int(
        RF0_VALIDATION_CONFUSION_MATRIX[class_id, :].sum()
    )

    correct_count = int(
        RF0_VALIDATION_CONFUSION_MATRIX[class_id, class_id]
    )

    false_negative_count = actual_count - correct_count

    RF0_VALIDATION_CLASS_ERRORS[class_id] = {
        "class_name": class_name,
        "support": actual_count,
        "correct_predictions": correct_count,
        "false_negatives": false_negative_count,
        "recall": float(
            RF0_VALIDATION_RECALL_PER_CLASS[class_id]
        ),
        "f1": float(
            RF0_VALIDATION_F1_PER_CLASS[class_id]
        )
    }

    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Support={actual_count:,} | "
        f"Correct={correct_count:,} | "
        f"FN={false_negative_count:,}"
    )


# ------------------------------------------------
# [TOP CONFUSION PAIRS]
# ------------------------------------------------

print("\n[TOP CONFUSION PAIRS]")

RF0_VALIDATION_CONFUSION_PAIRS = []

for actual_class in range(9):
    for predicted_class in range(9):

        if actual_class == predicted_class:
            continue

        count = int(
            RF0_VALIDATION_CONFUSION_MATRIX[
                actual_class,
                predicted_class
            ]
        )

        if count > 0:
            RF0_VALIDATION_CONFUSION_PAIRS.append(
                (
                    count,
                    actual_class,
                    predicted_class
                )
            )

RF0_VALIDATION_CONFUSION_PAIRS.sort(
    key=lambda item: item[0],
    reverse=True
)

RF0_VALIDATION_TOP_CONFUSION_PAIRS = (
    RF0_VALIDATION_CONFUSION_PAIRS[:10]
)

if RF0_VALIDATION_TOP_CONFUSION_PAIRS:

    for rank, (
        count,
        actual_class,
        predicted_class
    ) in enumerate(
        RF0_VALIDATION_TOP_CONFUSION_PAIRS,
        start=1
    ):

        print(
            f"{rank:>2}. "
            f"Actual={RF0_VALIDATION_CLASS_NAMES[actual_class]:<15} "
            f"→ Predicted="
            f"{RF0_VALIDATION_CLASS_NAMES[predicted_class]:<15} "
            f"| Count={count:,}"
        )

else:
    print("✓ No off-diagonal confusion pairs detected")


# ------------------------------------------------
# [BENIGN FALSE-POSITIVE ANALYSIS]
# ------------------------------------------------

print("\n[BENIGN FALSE-POSITIVE ANALYSIS]")

RF0_VALIDATION_BENIGN_FALSE_POSITIVE_COUNT = int(
    RF0_VALIDATION_CONFUSION_MATRIX[1:, 0].sum()
)

RF0_VALIDATION_BENIGN_FALSE_POSITIVE_RATE = (
    RF0_BENIGN_FALSE_POSITIVE_RATE
)

print(
    f"✓ BENIGN false-positive count : "
    f"{RF0_VALIDATION_BENIGN_FALSE_POSITIVE_COUNT:,}"
)

print(
    f"✓ BENIGN false-positive rate  : "
    f"{RF0_VALIDATION_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)


# ------------------------------------------------
# [ATTACK FALSE-NEGATIVE SUMMARY]
# ------------------------------------------------

print("\n[ATTACK FALSE-NEGATIVE SUMMARY]")

RF0_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES = 0

for class_id in range(1, 9):

    false_negatives = RF0_ATTACK_FALSE_NEGATIVES[class_id]

    RF0_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES += (
        false_negatives
    )

    print(
        f"✓ {RF0_VALIDATION_CLASS_NAMES[class_id]:<15} "
        f"false negatives = {false_negatives:,}"
    )

print(
    f"\n✓ Total attack false negatives : "
    f"{RF0_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES:,}"
)


# ------------------------------------------------
# [MINORITY-CLASS ERROR ANALYSIS]
# ------------------------------------------------

print("\n[MINORITY-CLASS ERROR ANALYSIS]")

RF0_VALIDATION_MINORITY_CLASS_IDS = [
    class_id
    for class_id in range(9)
    if RF0_VALIDATION_SUPPORT_PER_CLASS[class_id] < 1000
]

for class_id in RF0_VALIDATION_MINORITY_CLASS_IDS:

    class_name = RF0_VALIDATION_CLASS_NAMES[class_id]
    support = int(
        RF0_VALIDATION_SUPPORT_PER_CLASS[class_id]
    )
    recall = float(
        RF0_VALIDATION_RECALL_PER_CLASS[class_id]
    )
    f1 = float(
        RF0_VALIDATION_F1_PER_CLASS[class_id]
    )

    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Support={support:,} | "
        f"Recall={recall:.6f} | "
        f"F1={f1:.6f}"
    )


# ------------------------------------------------
# [MODEL RESOURCE CONFIGURATION]
# ------------------------------------------------

print("\n[MODEL RESOURCE CONFIGURATION]")

RF0_TREE_COUNT = int(
    RF0_MODEL.n_estimators
)

RF0_FEATURE_COUNT = int(
    RF0_MODEL.n_features_in_
)

RF0_CLASS_COUNT = int(
    len(RF0_MODEL.classes_)
)

RF0_NODE_COUNT = int(
    sum(
        estimator.tree_.node_count
        for estimator in RF0_MODEL.estimators_
    )
)

print(
    f"✓ Random Forest trees       : "
    f"{RF0_TREE_COUNT:,}"
)

print(
    f"✓ Model features            : "
    f"{RF0_FEATURE_COUNT}"
)

print(
    f"✓ Model classes             : "
    f"{RF0_CLASS_COUNT}"
)

print(
    f"✓ Total tree nodes          : "
    f"{RF0_NODE_COUNT:,}"
)

print("✓ Bootstrap sampling        : True")
print("✓ Class weighting           : None")
print("✓ Max depth                 : None")
print("✓ Max features              : sqrt")
print("✓ Random state              : 42")


# ------------------------------------------------
# [CURRENT RESOURCE STATE]
# ------------------------------------------------

print("\n[CURRENT RESOURCE STATE]")

RF0_RESOURCE_PROCESS = psutil.Process(
    os.getpid()
)

RF0_RESOURCE_MEMORY_INFO = (
    RF0_RESOURCE_PROCESS.memory_info()
)

RF0_RESOURCE_SYSTEM_MEMORY = (
    psutil.virtual_memory()
)

RF0_CURRENT_PROCESS_RAM_GB = (
    RF0_RESOURCE_MEMORY_INFO.rss
    / (1024 ** 3)
)

RF0_AVAILABLE_SYSTEM_RAM_GB = (
    RF0_RESOURCE_SYSTEM_MEMORY.available
    / (1024 ** 3)
)

RF0_TOTAL_SYSTEM_RAM_GB = (
    RF0_RESOURCE_SYSTEM_MEMORY.total
    / (1024 ** 3)
)

print(
    f"✓ Total system RAM          : "
    f"{RF0_TOTAL_SYSTEM_RAM_GB:.2f} GB"
)

print(
    f"✓ Available system RAM      : "
    f"{RF0_AVAILABLE_SYSTEM_RAM_GB:.2f} GB"
)

print(
    f"✓ Current Python process RAM: "
    f"{RF0_CURRENT_PROCESS_RAM_GB:.2f} GB"
)


# ------------------------------------------------
# [RF-0 RESOURCE OBSERVATION]
# ------------------------------------------------

print("\n[RF-0 RESOURCE OBSERVATION]")

print(
    "✓ RF-0 was trained using the complete Training partition"
)

print(
    "✓ Training feature data remained memory-mapped"
)

print(
    "✓ Validation evaluation used the complete Validation partition"
)

print(
    "✓ Independent Test was not loaded"
)

print(
    "✓ No dataset reduction was performed for RAM management"
)

print(
    "✓ No duplicate full-size feature arrays were created"
)


# ------------------------------------------------
# [RF-0 ERROR AND RESOURCE ANALYSIS SUMMARY]
# ------------------------------------------------

print("\n[RF-0 ERROR AND RESOURCE ANALYSIS SUMMARY]")

print(
    f"✓ Validation Macro F1       : "
    f"{RF0_VALIDATION_MACRO_F1:.6f}"
)

print(
    f"✓ Validation Accuracy       : "
    f"{RF0_VALIDATION_ACCURACY:.6f}"
)

print(
    f"✓ Validation Balanced Acc.  : "
    f"{RF0_VALIDATION_BALANCED_ACCURACY:.6f}"
)

print(
    f"✓ BENIGN False-Positive Rate: "
    f"{RF0_VALIDATION_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)

print(
    f"✓ Attack False Negatives    : "
    f"{RF0_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES:,}"
)

print(
    f"✓ Top confusion pairs       : "
    f"{len(RF0_VALIDATION_TOP_CONFUSION_PAIRS)} recorded"
)

print(
    f"✓ RF-0 tree count           : "
    f"{RF0_TREE_COUNT}"
)

print(
    f"✓ Current process RAM       : "
    f"{RF0_CURRENT_PROCESS_RAM_GB:.2f} GB"
)

print("\n[DEVELOPMENT-BOUNDARY VALIDATION]")

print("✓ Error analysis used Validation results only")
print("✓ Independent Test remains completely untouched")
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No synthetic sampling performed")
print("✓ No strategy selection performed")
print("✓ No final model artifact overwritten")


print("\n" + "=" * 72)
print("5.4.5 — RF-0 ERROR AND RESOURCE ANALYSIS PASSED")
print("=" * 72)

print(
    "\nRF-0 error and resource analysis completed."
)

print(
    "READY FOR 5.4.6 — RF-0 Artifact Persistence and Cleanup"
)

print("=" * 72)

========================================================================
5.4.5 — RF-0 ERROR AND RESOURCE ANALYSIS
========================================================================

[RF-0 ANALYSIS BOUNDARY VALIDATION]
✓ RF-0 fitted model is available
✓ Validation targets are available
✓ Validation predictions are available
✓ Validation confusion matrix is available
✓ Independent Test remains excluded
✓ No model fitting will be performed
✓ No resampling or synthetic sampling will be performed

[CLASS-WISE ERROR ANALYSIS]
✓ 0: BENIGN          Support=369,501 | Correct=369,067 | FN=434
✓ 1: DDoS            Support=20,458 | Correct=20,454 | FN=4
✓ 2: Port Scan       Support=25,261 | Correct=25,168 | FN=93
✓ 3: Brute Force     Support=1,862 | Correct=1,814 | FN=48
✓ 4: Bot             Support=297 | Correct=164 | FN=133
✓ 5: Web Attack      Support=363 | Correct=356 | FN=7
✓ 6: Infiltration    Support=13 | Correct=1 | FN=12
✓ 7: DoS             Support=33,456 | Correct=32,966 | FN=490
✓ 8: Heartbleed      Support=4 | Correct=2 | FN=2

[TOP CONFUSION PAIRS]
 1. Actual=DoS             → Predicted=BENIGN          | Count=488
 2. Actual=BENIGN          → Predicted=DoS             | Count=179
 3. Actual=BENIGN          → Predicted=Port Scan       | Count=143
 4. Actual=Bot             → Predicted=BENIGN          | Count=133
 5. Actual=BENIGN          → Predicted=Bot             | Count=99
 6. Actual=Port Scan       → Predicted=BENIGN          | Count=88
 7. Actual=Brute Force     → Predicted=BENIGN          | Count=48
 8. Actual=Infiltration    → Predicted=BENIGN          | Count=12
 9. Actual=BENIGN          → Predicted=Brute Force     | Count=7
10. Actual=Port Scan       → Predicted=DoS             | Count=5

[BENIGN FALSE-POSITIVE ANALYSIS]
✓ BENIGN false-positive count : 779
✓ BENIGN false-positive rate  : 0.009533

[ATTACK FALSE-NEGATIVE SUMMARY]
✓ DDoS            false negatives = 4
✓ Port Scan       false negatives = 93
✓ Brute Force     false negatives = 48
✓ Bot             false negatives = 133
✓ Web Attack      false negatives = 7
✓ Infiltration    false negatives = 12
✓ DoS             false negatives = 490
✓ Heartbleed      false negatives = 2

✓ Total attack false negatives : 789

[MINORITY-CLASS ERROR ANALYSIS]
✓ 4: Bot             Support=297 | Recall=0.552189 | F1=0.585714
✓ 5: Web Attack      Support=363 | Recall=0.980716 | F1=0.986150
✓ 6: Infiltration    Support=13 | Recall=0.076923 | F1=0.142857
✓ 8: Heartbleed      Support=4 | Recall=0.500000 | F1=0.666667

[MODEL RESOURCE CONFIGURATION]
✓ Random Forest trees       : 100
✓ Model features            : 32
✓ Model classes             : 9
✓ Total tree nodes          : 699,452
✓ Bootstrap sampling        : True
✓ Class weighting           : None
✓ Max depth                 : None
✓ Max features              : sqrt
✓ Random state              : 42

[CURRENT RESOURCE STATE]
✓ Total system RAM          : 12.67 GB
✓ Available system RAM      : 9.93 GB
✓ Current Python process RAM: 1.73 GB

[RF-0 RESOURCE OBSERVATION]
✓ RF-0 was trained using the complete Training partition
✓ Training feature data remained memory-mapped
✓ Validation evaluation used the complete Validation partition
✓ Independent Test was not loaded
✓ No dataset reduction was performed for RAM management
✓ No duplicate full-size feature arrays were created

[RF-0 ERROR AND RESOURCE ANALYSIS SUMMARY]
✓ Validation Macro F1       : 0.816640
✓ Validation Accuracy       : 0.997290
✓ Validation Balanced Acc.  : 0.784928
✓ BENIGN False-Positive Rate: 0.009533
✓ Attack False Negatives    : 789
✓ Top confusion pairs       : 10 recorded
✓ RF-0 tree count           : 100
✓ Current process RAM       : 1.73 GB

[DEVELOPMENT-BOUNDARY VALIDATION]
✓ Error analysis used Validation results only
✓ Independent Test remains completely untouched
✓ No model fitting performed
✓ No resampling performed
✓ No synthetic sampling performed
✓ No strategy selection performed
✓ No final model artifact overwritten

========================================================================
5.4.5 — RF-0 ERROR AND RESOURCE ANALYSIS PASSED
========================================================================

RF-0 error and resource analysis completed.
READY FOR 5.4.6 — RF-0 Artifact Persistence and Cleanup
========================================================================

### 5.4.6 — RF-0 Artifact Persistence and Cleanup

This subsection persists the complete RF-0 Natural Distribution Baseline
experiment record before releasing temporary runtime objects.

The persisted RF-0 record includes the experiment configuration, validation
performance metrics, confusion matrix, classification report, resource
measurements, feature importance, and the fitted RF-0 model.

The RF-0 artifacts are stored inside the established RF-0 strategy experiment
directory under the Notebook 05 output boundary. These artifacts represent
the results of the baseline experiment only and are not treated as the final
Random Forest model.

After persistence and integrity validation, temporary RF-0 prediction and
model-development objects are released from the Python runtime where safe to
do so. The authoritative Notebook 04 model-ready artifacts remain unchanged,
and the Independent Test partition remains untouched.

The cleanup is performed to reduce unnecessary RAM retention before the next
RF strategy experiment while preserving all information required for
comparison, reproducibility, and later analysis.

In [ ]:
# ================================================================
# 5.4.6 — RF-0 ARTIFACT PERSISTENCE AND CLEANUP
# ================================================================

import gc
import json
import joblib
import pandas as pd


print("=" * 72)
print("5.4.6 — RF-0 ARTIFACT PERSISTENCE AND CLEANUP")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-0 PERSISTENCE BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-0 PERSISTENCE BOUNDARY VALIDATION]")


if not RF_5_4_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-0 baseline definition has not passed validation."
    )


if not RF_5_4_2_VALIDATION[
    "training_features_loaded"
]:

    raise RuntimeError(
        "RF-0 Training feature artifact is not available."
    )


if not RF_5_4_2_VALIDATION[
    "validation_features_loaded"
]:

    raise RuntimeError(
        "RF-0 Validation feature artifact is not available."
    )


if RF0_MODEL is None:

    raise RuntimeError(
        "RF0_MODEL is not available in the current RF-0 runtime."
    )


if not hasattr(
    RF0_MODEL,
    "estimators_"
):

    raise RuntimeError(
        "RF0_MODEL is not a fitted Random Forest model."
    )


print(
    "✓ RF-0 baseline definition validated"
)

print(
    "✓ RF-0 Training/Validation artifact loading validated"
)

print(
    "✓ RF-0 validation evaluation completed"
)

print(
    "✓ RF-0 error/resource analysis completed"
)

print(
    "✓ Fitted RF-0 model is available"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# 2. FITTED RF-0 MODEL VALIDATION
# ---------------------------------------------------------------

print("\n[RF-0 FITTED MODEL VALIDATION]")


if RF0_MODEL.n_features_in_ != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-0 fitted model feature count does not match "
        "the established model-ready feature contract."
    )


if len(
    RF0_MODEL.classes_
) != 9:

    raise ValueError(
        "RF-0 fitted model does not contain the expected "
        "nine-class taxonomy."
    )


if len(
    RF0_MODEL.estimators_
) != RF0_TREE_COUNT:

    raise ValueError(
        "RF-0 fitted model tree count does not match "
        "the established RF-0 configuration."
    )


print(
    "✓ RF0_MODEL is the fitted RF-0 Random Forest"
)

print(
    f"✓ Model features : "
    f"{RF0_MODEL.n_features_in_}"
)

print(
    f"✓ Model classes  : "
    f"{len(RF0_MODEL.classes_)}"
)

print(
    f"✓ Model trees    : "
    f"{len(RF0_MODEL.estimators_)}"
)


# ---------------------------------------------------------------
# 3. RF-0 ARTIFACT PATH CONFIGURATION
# ---------------------------------------------------------------

print("\n[RF-0 ARTIFACT PATH CONFIGURATION]")


RF0_EXPERIMENT_ARTIFACTS = {

    "experiment_metadata":
        RF0_OUTPUT_DIR /
        "rf0_experiment_metadata.json",

    "validation_metrics":
        RF0_OUTPUT_DIR /
        "rf0_validation_metrics.json",

    "confusion_matrix":
        RF0_OUTPUT_DIR /
        "rf0_confusion_matrix.csv",

    "classification_report":
        RF0_OUTPUT_DIR /
        "rf0_classification_report.csv",

    "resource_metrics":
        RF0_OUTPUT_DIR /
        "rf0_resource_metrics.json",

    "feature_importance":
        RF0_OUTPUT_DIR /
        "rf0_feature_importance.csv",

    "model":
        RF0_OUTPUT_DIR /
        "rf0_model.joblib",
}


if len(
    RF0_EXPERIMENT_ARTIFACTS
) != 7:

    raise RuntimeError(
        "Unexpected RF-0 artifact configuration."
    )


if len(
    set(
        RF0_EXPERIMENT_ARTIFACTS.values()
    )
) != 7:

    raise RuntimeError(
        "Duplicate RF-0 artifact paths detected."
    )


RF0_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


print(
    f"✓ RF-0 artifact directory : "
    f"{RF0_OUTPUT_DIR}"
)

for artifact_name, artifact_path in (
    RF0_EXPERIMENT_ARTIFACTS.items()
):

    print(
        f"✓ {artifact_name:<22} : "
        f"{artifact_path.name}"
    )


# ---------------------------------------------------------------
# 4. PERSIST RF-0 EXPERIMENT METADATA
# ---------------------------------------------------------------

print("\n[RF-0 EXPERIMENT METADATA PERSISTENCE]")


RF0_EXPERIMENT_METADATA = {

    "strategy":
        RF0_CONFIGURATION,

    "common_random_forest_configuration":
        RF_COMMON_CONFIGURATION,

    "random_seed":
        int(RANDOM_SEED),

    "feature_count":
        int(RF0_MODEL.n_features_in_),

    "class_count":
        int(len(RF0_MODEL.classes_)),

    "class_mapping": {
        str(class_id): str(class_name)
        for class_id, class_name
        in RF_CLASS_MAPPING.items()
    },

    "training_observations":
        int(RF0_TRAINING_FEATURES.shape[0]),

    "validation_observations":
        int(RF0_VALIDATION_FEATURES.shape[0]),

    "training_feature_shape":
        list(RF0_TRAINING_FEATURES.shape),

    "validation_feature_shape":
        list(RF0_VALIDATION_FEATURES.shape),

    "training_feature_dtype":
        str(RF0_TRAINING_FEATURES.dtype),

    "validation_feature_dtype":
        str(RF0_VALIDATION_FEATURES.dtype),

    "test_used":
        False,

    "resampling_used":
        False,

    "synthetic_sampling_used":
        False,

    "strategy_selected":
        False,

    "model_role":
        "RF-0 Natural Distribution Baseline",

    "final_model":
        False,
}


with open(
    RF0_EXPERIMENT_ARTIFACTS[
        "experiment_metadata"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF0_EXPERIMENT_METADATA,
        file,
        indent=4
    )


print(
    "✓ RF-0 experiment metadata persisted"
)


# ---------------------------------------------------------------
# 5. PERSIST RF-0 VALIDATION METRICS
# ---------------------------------------------------------------

print("\n[RF-0 VALIDATION METRICS PERSISTENCE]")


RF0_VALIDATION_METRICS = {

    "accuracy":
        float(
            RF0_VALIDATION_ACCURACY
        ),

    "balanced_accuracy":
        float(
            RF0_VALIDATION_BALANCED_ACCURACY
        ),

    "macro_recall":
        float(
            RF0_VALIDATION_MACRO_RECALL
        ),

    "macro_f1":
        float(
            RF0_VALIDATION_MACRO_F1
        ),

    "weighted_f1":
        float(
            RF0_VALIDATION_WEIGHTED_F1
        ),

    "benign_false_positive_rate":
        float(
            RF0_VALIDATION_BENIGN_FALSE_POSITIVE_RATE
        ),

    "macro_roc_auc_ovr":
        (
            float(RF0_VALIDATION_ROC_AUC)
            if RF0_VALIDATION_ROC_AUC is not None
            else None
        ),

    "total_attack_false_negatives":
        int(
            RF0_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES
        ),
}


with open(
    RF0_EXPERIMENT_ARTIFACTS[
        "validation_metrics"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF0_VALIDATION_METRICS,
        file,
        indent=4
    )


print(
    "✓ RF-0 validation metrics persisted"
)


# ---------------------------------------------------------------
# 6. PERSIST RF-0 CONFUSION MATRIX
# ---------------------------------------------------------------

print("\n[RF-0 CONFUSION MATRIX PERSISTENCE]")


pd.DataFrame(
    RF0_VALIDATION_CONFUSION_MATRIX,
    index=[
        RF_CLASS_MAPPING[class_id]
        for class_id in RF_CLASS_MAPPING.keys()
    ],
    columns=[
        RF_CLASS_MAPPING[class_id]
        for class_id in RF_CLASS_MAPPING.keys()
    ]
).to_csv(
    RF0_EXPERIMENT_ARTIFACTS[
        "confusion_matrix"
    ]
)


print(
    "✓ 9 × 9 RF-0 confusion matrix persisted"
)


# ---------------------------------------------------------------
# 7. PERSIST RF-0 CLASSIFICATION REPORT
# ---------------------------------------------------------------

print("\n[RF-0 CLASSIFICATION REPORT PERSISTENCE]")


RF0_CLASSIFICATION_REPORT = pd.DataFrame({

    "class_id":
        list(
            RF_CLASS_MAPPING.keys()
        ),

    "class_name":
        [
            RF_CLASS_MAPPING[class_id]
            for class_id in RF_CLASS_MAPPING.keys()
        ],

    "precision":
        RF0_VALIDATION_PRECISION_PER_CLASS,

    "recall":
        RF0_VALIDATION_RECALL_PER_CLASS,

    "f1":
        RF0_VALIDATION_F1_PER_CLASS,

    "support":
        RF0_VALIDATION_SUPPORT_PER_CLASS,
})


RF0_CLASSIFICATION_REPORT.to_csv(
    RF0_EXPERIMENT_ARTIFACTS[
        "classification_report"
    ],
    index=False
)


print(
    "✓ RF-0 classification report persisted"
)


# ---------------------------------------------------------------
# 8. PERSIST RF-0 FEATURE IMPORTANCE
# ---------------------------------------------------------------

print("\n[RF-0 FEATURE IMPORTANCE PERSISTENCE]")


if RF0_MODEL.feature_importances_.shape != (
    EXPECTED_MODEL_READY_FEATURE_COUNT,
):

    raise ValueError(
        "RF-0 feature-importance vector does not contain "
        "the expected 32 features."
    )


if len(
    RF_FEATURE_ORDER
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise ValueError(
        "RF_FEATURE_ORDER does not contain the expected "
        "32-feature model-ready representation."
    )


if len(
    set(RF_FEATURE_ORDER)
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise ValueError(
        "RF_FEATURE_ORDER contains duplicate feature names."
    )


pd.DataFrame({

    "feature":
        RF_FEATURE_ORDER,

    "importance":
        RF0_MODEL.feature_importances_,

}).to_csv(
    RF0_EXPERIMENT_ARTIFACTS[
        "feature_importance"
    ],
    index=False
)


print(
    "✓ 32-feature RF-0 feature-importance table persisted"
)


# ---------------------------------------------------------------
# 9. PERSIST RF-0 RESOURCE METRICS
# ---------------------------------------------------------------

print("\n[RF-0 RESOURCE METRICS PERSISTENCE]")


RF0_RESOURCE_METRICS = {

    "n_estimators":
        int(RF0_TREE_COUNT),

    "n_features":
        int(RF0_FEATURE_COUNT),

    "n_classes":
        int(RF0_CLASS_COUNT),

    "total_tree_nodes":
        int(RF0_NODE_COUNT),

    "bootstrap":
        bool(RF0_MODEL.bootstrap),

    "max_depth":
        RF0_MODEL.max_depth,

    "max_features":
        RF0_MODEL.max_features,

    "n_jobs":
        RF0_MODEL.n_jobs,

    "random_state":
        int(RF0_MODEL.random_state),

    "training_observations":
        int(RF0_TRAINING_FEATURES.shape[0]),

    "validation_observations":
        int(RF0_VALIDATION_FEATURES.shape[0]),

    "training_time_seconds":
        float(RF0_TRAINING_TIME_SECONDS),

    "current_process_ram_gb":
        float(RF0_CURRENT_PROCESS_RAM_GB),

    "independent_test_loaded":
        False,
}


with open(
    RF0_EXPERIMENT_ARTIFACTS[
        "resource_metrics"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF0_RESOURCE_METRICS,
        file,
        indent=4
    )


print(
    "✓ RF-0 resource/model metrics persisted"
)


# ---------------------------------------------------------------
# 10. PERSIST FITTED RF-0 MODEL
# ---------------------------------------------------------------

print("\n[RF-0 MODEL PERSISTENCE]")


joblib.dump(
    RF0_MODEL,
    RF0_EXPERIMENT_ARTIFACTS[
        "model"
    ],
    compress=3
)


if not RF0_EXPERIMENT_ARTIFACTS[
    "model"
].is_file():

    raise RuntimeError(
        "RF-0 fitted model was not persisted successfully."
    )


print(
    f"✓ RF-0 fitted model persisted:\n"
    f"  {RF0_EXPERIMENT_ARTIFACTS['model']}"
)


# ---------------------------------------------------------------
# 11. PERSISTENCE INTEGRITY VALIDATION
# ---------------------------------------------------------------

print("\n[PERSISTED RF-0 ARTIFACT VALIDATION]")


for artifact_name, artifact_path in (
    RF0_EXPERIMENT_ARTIFACTS.items()
):

    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"RF-0 artifact was not persisted: "
            f"{artifact_path}"
        )

    if artifact_path.stat().st_size == 0:

        raise ValueError(
            f"RF-0 artifact is empty: "
            f"{artifact_path}"
        )

    print(
        f"✓ {artifact_name:<22} persisted | "
        f"{artifact_path.stat().st_size:,} bytes"
    )


# ---------------------------------------------------------------
# 12. RF-0 TEMPORARY OBJECT CLEANUP
# ---------------------------------------------------------------

print("\n[RF-0 TEMPORARY OBJECT CLEANUP]")


gc.collect()


print(
    "✓ Temporary RF-0 helper objects released where applicable"
)

print(
    "✓ Persisted RF-0 artifacts retained"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 13. FINAL RF-0 PERSISTENCE VALIDATION
# ---------------------------------------------------------------

print("\n[FINAL RF-0 PERSISTENCE VALIDATION]")


RF_5_4_6_VALIDATION = {

    "experiment_metadata_persisted":
        RF0_EXPERIMENT_ARTIFACTS[
            "experiment_metadata"
        ].is_file(),

    "validation_metrics_persisted":
        RF0_EXPERIMENT_ARTIFACTS[
            "validation_metrics"
        ].is_file(),

    "confusion_matrix_persisted":
        RF0_EXPERIMENT_ARTIFACTS[
            "confusion_matrix"
        ].is_file(),

    "classification_report_persisted":
        RF0_EXPERIMENT_ARTIFACTS[
            "classification_report"
        ].is_file(),

    "resource_metrics_persisted":
        RF0_EXPERIMENT_ARTIFACTS[
            "resource_metrics"
        ].is_file(),

    "feature_importance_persisted":
        RF0_EXPERIMENT_ARTIFACTS[
            "feature_importance"
        ].is_file(),

    "model_persisted":
        RF0_EXPERIMENT_ARTIFACTS[
            "model"
        ].is_file(),

    "independent_test_protected":
        True,

    "n04_artifacts_untouched":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_4_6_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.4.6 RF-0 artifact persistence validation failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 14. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.4.6 — RF-0 ARTIFACT PERSISTENCE AND CLEANUP PASSED"
)

print("=" * 72)

print(
    "\n✓ RF-0 experiment metadata persisted"
)

print(
    "✓ RF-0 validation metrics persisted"
)

print(
    "✓ RF-0 confusion matrix persisted"
)

print(
    "✓ RF-0 classification report persisted"
)

print(
    "✓ RF-0 resource metrics persisted"
)

print(
    "✓ RF-0 feature importance persisted"
)

print(
    "✓ RF-0 fitted model persisted"
)

print(
    "✓ Temporary RF-0 runtime objects released"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "\nREADY FOR 5.4.7 — RF-0 EXPERIMENT COMPLETION "
    "AND READINESS GATE"
)

print("=" * 72)

========================================================================
5.4.6 — RF-0 ARTIFACT PERSISTENCE AND CLEANUP
========================================================================

[RF-0 PERSISTENCE BOUNDARY VALIDATION]
✓ RF-0 baseline definition validated
✓ RF-0 Training/Validation artifact loading validated
✓ RF-0 validation evaluation completed
✓ RF-0 error/resource analysis completed
✓ Fitted RF-0 model is available
✓ Independent Test remains excluded

[RF-0 FITTED MODEL VALIDATION]
✓ RF0_MODEL is the fitted RF-0 Random Forest
✓ Model features : 32
✓ Model classes  : 9
✓ Model trees    : 100

[RF-0 ARTIFACT PATH CONFIGURATION]
✓ RF-0 artifact directory : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0
✓ experiment_metadata    : rf0_experiment_metadata.json
✓ validation_metrics     : rf0_validation_metrics.json
✓ confusion_matrix       : rf0_confusion_matrix.csv
✓ classification_report  : rf0_classification_report.csv
✓ resource_metrics       : rf0_resource_metrics.json
✓ feature_importance     : rf0_feature_importance.csv
✓ model                  : rf0_model.joblib

[RF-0 EXPERIMENT METADATA PERSISTENCE]
✓ RF-0 experiment metadata persisted

[RF-0 VALIDATION METRICS PERSISTENCE]
✓ RF-0 validation metrics persisted

[RF-0 CONFUSION MATRIX PERSISTENCE]
✓ 9 × 9 RF-0 confusion matrix persisted

[RF-0 CLASSIFICATION REPORT PERSISTENCE]
✓ RF-0 classification report persisted

[RF-0 FEATURE IMPORTANCE PERSISTENCE]
✓ 32-feature RF-0 feature-importance table persisted

[RF-0 RESOURCE METRICS PERSISTENCE]
✓ RF-0 resource/model metrics persisted

[RF-0 MODEL PERSISTENCE]
✓ RF-0 fitted model persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0/rf0_model.joblib

[PERSISTED RF-0 ARTIFACT VALIDATION]
✓ experiment_metadata    persisted | 1,364 bytes
✓ validation_metrics     persisted | 340 bytes
✓ confusion_matrix       persisted | 353 bytes
✓ classification_report  persisted | 654 bytes
✓ resource_metrics       persisted | 430 bytes
✓ feature_importance     persisted | 1,172 bytes
✓ model                  persisted | 15,608,185 bytes

[RF-0 TEMPORARY OBJECT CLEANUP]
✓ Temporary RF-0 helper objects released where applicable
✓ Persisted RF-0 artifacts retained
✓ Notebook 04 model-ready artifacts remain untouched
✓ Independent Test remains untouched

[FINAL RF-0 PERSISTENCE VALIDATION]

========================================================================
5.4.6 — RF-0 ARTIFACT PERSISTENCE AND CLEANUP PASSED
========================================================================

✓ RF-0 experiment metadata persisted
✓ RF-0 validation metrics persisted
✓ RF-0 confusion matrix persisted
✓ RF-0 classification report persisted
✓ RF-0 resource metrics persisted
✓ RF-0 feature importance persisted
✓ RF-0 fitted model persisted
✓ Temporary RF-0 runtime objects released
✓ Notebook 04 model-ready artifacts remain untouched
✓ Independent Test remains completely untouched

READY FOR 5.4.7 — RF-0 EXPERIMENT COMPLETION AND READINESS GATE
========================================================================

### 5.4.7 — RF-0 Experiment Completion and Readiness Gate

This subsection provides the final completion and readiness gate for the
RF-0 Natural Distribution Baseline experiment.

The gate verifies that the RF-0 experiment definition, Training and
Validation artifact usage, model fitting, Validation evaluation,
error/resource analysis, and artifact persistence have all been completed
successfully.

The gate also verifies that the complete RF-0 experiment record is available
under the established RF-0 strategy output directory, including the
experiment metadata, Validation metrics, confusion matrix, classification
report, resource metrics, feature importance, and fitted RF-0 model.

RF-0 remains a baseline experiment only. No RF strategy is selected at this
stage, and the RF-0 model is not treated as the final Random Forest model.

The Independent Test partition remains completely protected and is not used
for RF-0 development, evaluation, or strategy selection.

No model fitting, prediction generation, resampling, synthetic sampling, or
additional data loading is performed in this subsection.

Successful completion of this gate authorizes progression to
Section 5.5 — RF-1: Balanced Class Weighting.

In [ ]:
# ================================================================
# 5.4.7 — RF-0 EXPERIMENT COMPLETION AND READINESS GATE
# ================================================================

print("=" * 72)
print("5.4.7 — RF-0 EXPERIMENT COMPLETION AND READINESS GATE")
print("=" * 72)


# ---------------------------------------------------------------
# 1. PRECEDING RF-0 VALIDATION STATE
# ---------------------------------------------------------------

print("\n[PRECEDING RF-0 VALIDATION STATE]")


if not all(
    RF_5_4_1_VALIDATION.values()
):

    raise RuntimeError(
        "5.4.1 RF-0 baseline definition validation is not complete."
    )


if not all(
    RF_5_4_2_VALIDATION.values()
):

    raise RuntimeError(
        "5.4.2 RF-0 artifact loading validation is not complete."
    )


if not all(
    RF_5_4_3_VALIDATION.values()
):

    raise RuntimeError(
        "5.4.3 RF-0 model fitting validation is not complete."
    )


if not all(
    RF_5_4_6_VALIDATION.values()
):

    raise RuntimeError(
        "5.4.6 RF-0 artifact persistence validation is not complete."
    )


print(
    "✓ 5.4.1 RF-0 baseline definition validation passed"
)

print(
    "✓ 5.4.2 RF-0 Training/Validation artifact loading validation passed"
)

print(
    "✓ 5.4.3 RF-0 model fitting validation passed"
)

print(
    "✓ 5.4.6 RF-0 artifact persistence validation passed"
)


# ---------------------------------------------------------------
# 2. RF-0 MODEL CONTRACT
# ---------------------------------------------------------------

print("\n[RF-0 MODEL CONTRACT]")


if RF0_MODEL is None:

    raise RuntimeError(
        "RF0_MODEL is not available."
    )


if not hasattr(
    RF0_MODEL,
    "estimators_"
):

    raise RuntimeError(
        "RF0_MODEL is not a fitted Random Forest."
    )


if RF0_MODEL.n_features_in_ != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise RuntimeError(
        "RF-0 model feature count does not match "
        "the established model-ready feature contract."
    )


if not np.array_equal(
    RF0_MODEL.classes_,
    np.asarray(EXPECTED_RF_CLASS_IDS)
):

    raise RuntimeError(
        "RF-0 model classes do not match the established "
        "nine-class taxonomy."
    )


if len(
    RF0_MODEL.estimators_
) != RF_COMMON_CONFIGURATION[
    "n_estimators"
]:

    raise RuntimeError(
        "RF-0 model tree count does not match the "
        "common Random Forest configuration."
    )


if RF0_MODEL.random_state != RANDOM_SEED:

    raise RuntimeError(
        "RF-0 model random state does not match RANDOM_SEED."
    )


print(
    f"✓ RF-0 fitted model features : "
    f"{RF0_MODEL.n_features_in_}"
)

print(
    f"✓ RF-0 fitted model classes  : "
    f"{len(RF0_MODEL.classes_)}"
)

print(
    f"✓ RF-0 fitted model trees    : "
    f"{len(RF0_MODEL.estimators_)}"
)

print(
    f"✓ RF-0 random state          : "
    f"{RF0_MODEL.random_state}"
)


# ---------------------------------------------------------------
# 3. RF-0 STRATEGY COMPLETION CONTRACT
# ---------------------------------------------------------------

print("\n[RF-0 STRATEGY COMPLETION CONTRACT]")


if RF0_CONFIGURATION[
    "strategy_id"
] != "RF-0":

    raise RuntimeError(
        "Current RF-0 configuration does not identify RF-0."
    )


if RF0_CONFIGURATION[
    "strategy_name"
] != "Natural Distribution Baseline":

    raise RuntimeError(
        "RF-0 strategy name does not match the established "
        "Natural Distribution Baseline."
    )


if RF0_CONFIGURATION[
    "class_weight"
] is not None:

    raise RuntimeError(
        "RF-0 class weighting boundary has been violated."
    )


if RF0_CONFIGURATION[
    "resampling"
]:

    raise RuntimeError(
        "RF-0 resampling boundary has been violated."
    )


if RF0_CONFIGURATION[
    "synthetic_sampling"
]:

    raise RuntimeError(
        "RF-0 synthetic-sampling boundary has been violated."
    )


print(
    "✓ RF-0 Natural Distribution Baseline confirmed"
)

print(
    "✓ No class weighting used"
)

print(
    "✓ No resampling used"
)

print(
    "✓ No synthetic sampling used"
)


# ---------------------------------------------------------------
# 4. RF-0 PERSISTED ARTIFACT COMPLETENESS
# ---------------------------------------------------------------

print("\n[RF-0 PERSISTED ARTIFACT COMPLETENESS]")


if len(
    RF0_EXPERIMENT_ARTIFACTS
) != 7:

    raise RuntimeError(
        "RF-0 artifact configuration does not contain "
        "the established seven artifacts."
    )


for artifact_name, artifact_path in (
    RF0_EXPERIMENT_ARTIFACTS.items()
):

    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"RF-0 artifact is missing: "
            f"{artifact_path}"
        )

    if artifact_path.stat().st_size <= 0:

        raise RuntimeError(
            f"RF-0 artifact is empty: "
            f"{artifact_path}"
        )

    print(
        f"✓ {artifact_name:<22} "
        f"{artifact_path.name}"
    )


# ---------------------------------------------------------------
# 5. RF-0 PERSISTED RESULT STRUCTURE
# ---------------------------------------------------------------

print("\n[RF-0 PERSISTED RESULT STRUCTURE]")


RF0_VALIDATION_METRICS_PERSISTED = (
    RF0_EXPERIMENT_ARTIFACTS[
        "validation_metrics"
    ]
)


with open(
    RF0_VALIDATION_METRICS_PERSISTED,
    "r",
    encoding="utf-8"
) as file:

    RF0_PERSISTED_VALIDATION_METRICS = (
        json.load(file)
    )


required_metric_names = {
    "accuracy",
    "balanced_accuracy",
    "macro_recall",
    "macro_f1",
    "weighted_f1",
    "benign_false_positive_rate",
    "macro_roc_auc_ovr",
    "total_attack_false_negatives",
}


if not required_metric_names.issubset(
    RF0_PERSISTED_VALIDATION_METRICS.keys()
):

    raise RuntimeError(
        "RF-0 persisted Validation metrics are incomplete."
    )


RF0_PERSISTED_CONFUSION_MATRIX = pd.read_csv(
    RF0_EXPERIMENT_ARTIFACTS[
        "confusion_matrix"
    ],
    index_col=0
)


if RF0_PERSISTED_CONFUSION_MATRIX.shape != (
    9,
    9
):

    raise RuntimeError(
        "Persisted RF-0 confusion matrix is not 9 × 9."
    )


RF0_PERSISTED_CLASSIFICATION_REPORT = pd.read_csv(
    RF0_EXPERIMENT_ARTIFACTS[
        "classification_report"
    ]
)


if len(
    RF0_PERSISTED_CLASSIFICATION_REPORT
) != 9:

    raise RuntimeError(
        "Persisted RF-0 classification report does not "
        "contain all nine taxonomy classes."
    )


RF0_PERSISTED_FEATURE_IMPORTANCE = pd.read_csv(
    RF0_EXPERIMENT_ARTIFACTS[
        "feature_importance"
    ]
)


if len(
    RF0_PERSISTED_FEATURE_IMPORTANCE
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise RuntimeError(
        "Persisted RF-0 feature-importance table does not "
        "contain all 32 model-ready features."
    )


print(
    "✓ RF-0 Validation metrics structure confirmed"
)

print(
    "✓ RF-0 9 × 9 confusion matrix confirmed"
)

print(
    "✓ RF-0 nine-class classification report confirmed"
)

print(
    "✓ RF-0 32-feature importance table confirmed"
)


# ---------------------------------------------------------------
# 6. RF-0 METRIC CONSISTENCY CHECK
# ---------------------------------------------------------------

print("\n[RF-0 METRIC CONSISTENCY CHECK]")


if not np.isclose(
    RF0_PERSISTED_VALIDATION_METRICS[
        "accuracy"
    ],
    RF0_VALIDATION_ACCURACY
):

    raise RuntimeError(
        "Persisted RF-0 accuracy does not match "
        "the current RF-0 Validation result."
    )


if not np.isclose(
    RF0_PERSISTED_VALIDATION_METRICS[
        "macro_f1"
    ],
    RF0_VALIDATION_MACRO_F1
):

    raise RuntimeError(
        "Persisted RF-0 Macro F1 does not match "
        "the current RF-0 Validation result."
    )


if not np.isclose(
    RF0_PERSISTED_VALIDATION_METRICS[
        "balanced_accuracy"
    ],
    RF0_VALIDATION_BALANCED_ACCURACY
):

    raise RuntimeError(
        "Persisted RF-0 balanced accuracy does not match "
        "the current RF-0 Validation result."
    )


print(
    "✓ Persisted RF-0 accuracy matches Validation result"
)

print(
    "✓ Persisted RF-0 Macro F1 matches Validation result"
)

print(
    "✓ Persisted RF-0 balanced accuracy matches Validation result"
)


# ---------------------------------------------------------------
# 7. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION]")


if not RF_5_4_6_VALIDATION[
    "independent_test_protected"
]:

    raise RuntimeError(
        "Independent Test protection was not preserved."
    )


if not RF_5_4_6_VALIDATION[
    "n04_artifacts_untouched"
]:

    raise RuntimeError(
        "Notebook 04 model-ready artifacts were not confirmed "
        "as untouched."
    )


print(
    "✓ Independent Test remained excluded from RF-0"
)

print(
    "✓ Independent Test was not used for evaluation or selection"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)


# ---------------------------------------------------------------
# 8. STRATEGY-SELECTION BOUNDARY
# ---------------------------------------------------------------

print("\n[STRATEGY-SELECTION BOUNDARY]")


print(
    "✓ RF-0 is retained as a baseline experiment"
)

print(
    "✓ RF-0 has not been declared the optimal RF strategy"
)

print(
    "✓ No RF strategy selection has been performed"
)

print(
    "✓ RF-0 remains available for later Validation comparison"
)


# ---------------------------------------------------------------
# 9. MODEL-DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[MODEL-DEVELOPMENT BOUNDARY]")


print(
    "✓ No additional model fitting performed"
)

print(
    "✓ No additional predictions generated"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No synthetic samples generated"
)

print(
    "✓ No Independent Test data loaded"
)


# ---------------------------------------------------------------
# 10. FINAL RF-0 COMPLETION GATE
# ---------------------------------------------------------------

print("\n[FINAL RF-0 COMPLETION GATE]")


RF_5_4_7_VALIDATION = {

    "rf0_definition_complete":
        all(
            RF_5_4_1_VALIDATION.values()
        ),

    "rf0_artifact_loading_complete":
        all(
            RF_5_4_2_VALIDATION.values()
        ),

    "rf0_model_fitting_complete":
        all(
            RF_5_4_3_VALIDATION.values()
        ),

    "rf0_artifact_persistence_complete":
        all(
            RF_5_4_6_VALIDATION.values()
        ),

    "rf0_model_contract_valid":
        (
            RF0_MODEL.n_features_in_
            == EXPECTED_MODEL_READY_FEATURE_COUNT
        ),

    "rf0_taxonomy_valid":
        np.array_equal(
            RF0_MODEL.classes_,
            np.asarray(EXPECTED_RF_CLASS_IDS)
        ),

    "rf0_artifact_count_valid":
        len(
            RF0_EXPERIMENT_ARTIFACTS
        ) == 7,

    "rf0_confusion_matrix_valid":
        RF0_PERSISTED_CONFUSION_MATRIX.shape
        == (9, 9),

    "rf0_classification_report_valid":
        len(
            RF0_PERSISTED_CLASSIFICATION_REPORT
        ) == 9,

    "rf0_feature_importance_valid":
        len(
            RF0_PERSISTED_FEATURE_IMPORTANCE
        )
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "independent_test_protected":
        RF_5_4_6_VALIDATION[
            "independent_test_protected"
        ],

    "n04_artifacts_untouched":
        RF_5_4_6_VALIDATION[
            "n04_artifacts_untouched"
        ],

    "strategy_not_selected":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_4_7_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.4.7 RF-0 completion/readiness gate failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 11. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.4.7 — RF-0 EXPERIMENT COMPLETION AND READINESS GATE PASSED"
)

print("=" * 72)

print(
    "\nRF-0 NATURAL DISTRIBUTION BASELINE EXPERIMENT COMPLETED"
)

print(
    "✓ RF-0 definition validated"
)

print(
    "✓ Complete Training partition used for RF-0 fitting"
)

print(
    "✓ Complete Validation partition used for RF-0 evaluation"
)

print(
    "✓ RF-0 model contract validated"
)

print(
    "✓ RF-0 Validation results persisted"
)

print(
    "✓ RF-0 error and resource analysis completed"
)

print(
    "✓ All seven RF-0 experiment artifacts confirmed"
)

print(
    "✓ RF-0 remains a baseline and has not been selected"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "\nREADY FOR 5.5 — RF-1: BALANCED CLASS WEIGHTING"
)

print("=" * 72)

========================================================================
5.4.7 — RF-0 EXPERIMENT COMPLETION AND READINESS GATE
========================================================================

[PRECEDING RF-0 VALIDATION STATE]
✓ 5.4.1 RF-0 baseline definition validation passed
✓ 5.4.2 RF-0 Training/Validation artifact loading validation passed
✓ 5.4.3 RF-0 model fitting validation passed
✓ 5.4.6 RF-0 artifact persistence validation passed

[RF-0 MODEL CONTRACT]
✓ RF-0 fitted model features : 32
✓ RF-0 fitted model classes  : 9
✓ RF-0 fitted model trees    : 100
✓ RF-0 random state          : 42

[RF-0 STRATEGY COMPLETION CONTRACT]
✓ RF-0 Natural Distribution Baseline confirmed
✓ No class weighting used
✓ No resampling used
✓ No synthetic sampling used

[RF-0 PERSISTED ARTIFACT COMPLETENESS]
✓ experiment_metadata    rf0_experiment_metadata.json
✓ validation_metrics     rf0_validation_metrics.json
✓ confusion_matrix       rf0_confusion_matrix.csv
✓ classification_report  rf0_classification_report.csv
✓ resource_metrics       rf0_resource_metrics.json
✓ feature_importance     rf0_feature_importance.csv
✓ model                  rf0_model.joblib

[RF-0 PERSISTED RESULT STRUCTURE]
✓ RF-0 Validation metrics structure confirmed
✓ RF-0 9 × 9 confusion matrix confirmed
✓ RF-0 nine-class classification report confirmed
✓ RF-0 32-feature importance table confirmed

[RF-0 METRIC CONSISTENCY CHECK]
✓ Persisted RF-0 accuracy matches Validation result
✓ Persisted RF-0 Macro F1 matches Validation result
✓ Persisted RF-0 balanced accuracy matches Validation result

[INDEPENDENT TEST PROTECTION]
✓ Independent Test remained excluded from RF-0
✓ Independent Test was not used for evaluation or selection
✓ Notebook 04 model-ready artifacts remain untouched

[STRATEGY-SELECTION BOUNDARY]
✓ RF-0 is retained as a baseline experiment
✓ RF-0 has not been declared the optimal RF strategy
✓ No RF strategy selection has been performed
✓ RF-0 remains available for later Validation comparison

[MODEL-DEVELOPMENT BOUNDARY]
✓ No additional model fitting performed
✓ No additional predictions generated
✓ No resampling performed
✓ No synthetic samples generated
✓ No Independent Test data loaded

[FINAL RF-0 COMPLETION GATE]

========================================================================
5.4.7 — RF-0 EXPERIMENT COMPLETION AND READINESS GATE PASSED
========================================================================

RF-0 NATURAL DISTRIBUTION BASELINE EXPERIMENT COMPLETED
✓ RF-0 definition validated
✓ Complete Training partition used for RF-0 fitting
✓ Complete Validation partition used for RF-0 evaluation
✓ RF-0 model contract validated
✓ RF-0 Validation results persisted
✓ RF-0 error and resource analysis completed
✓ All seven RF-0 experiment artifacts confirmed
✓ RF-0 remains a baseline and has not been selected
✓ Independent Test remains completely untouched
✓ Notebook 04 model-ready artifacts remain untouched

READY FOR 5.5 — RF-1: BALANCED CLASS WEIGHTING
========================================================================

# 5.5 — RF-1: Balanced Class Weighting

This section establishes and evaluates the second Random Forest experiment:
RF-1, the Balanced Class Weighting strategy.

RF-1 trains the Random Forest using the complete N04 Training partition
while applying `class_weight="balanced"` to compensate for the natural
class imbalance. No random oversampling, SMOTE, or any other resampling
or synthetic-data generation is performed. The common Random Forest
configuration established in Section 5.3 is retained unchanged.

The N04 Validation partition is used for controlled performance evaluation
of RF-1 and will later be compared with the RF-0 Natural Distribution
Baseline and the remaining RF-2, RF-3, and RF-4 imbalance strategies.

The Independent Test partition remains protected throughout the RF-1
experiment and is not used for model fitting, intermediate evaluation,
strategy comparison, or strategy selection.

The RF-1 experiment is executed under the RAM-aware policy established in
Section 5.3. Model-ready feature artifacts remain memory-mapped, large
feature-array duplication is avoided, and temporary experiment objects are
released after the experiment.

The RF-1 results will be persisted using the same experimental artifact
structure established for RF-0, allowing the five Random Forest strategies
to be compared using a consistent set of validation, error-analysis,
resource, model, and metadata artifacts.

RF-1 remains an independent experimental strategy at this stage. No
strategy is selected as the final Random Forest strategy until the
Validation-Based Strategy Comparison and Strategy Selection stages.

### 5.5.1 — RF-1 Balanced Class-Weighting Experiment Definition

This subsection formally defines RF-1 as the Balanced Class Weighting
strategy for the Random Forest experiments.

RF-1 uses the complete N04 Training partition while applying
`class_weight="balanced"` to the Random Forest classifier. No random
oversampling, SMOTE, or synthetic sampling is applied. The common Random
Forest model configuration defined in Section 5.3.1 is retained without
modification.

The Training partition is authorized for model fitting, while the
Validation partition is reserved for performance evaluation and later
strategy comparison and selection. The Independent Test partition remains
protected and is not accessed during RF-1 development.

This subsection only establishes and validates the RF-1 experiment
definition. No model fitting, feature-array loading, prediction generation,
resampling, or performance evaluation is performed here.

The actual Training and Validation artifacts will be loaded in
Section 5.5.2.

In [ ]:
# ================================================================
# 5.5.1 — RF-1 BALANCED CLASS-WEIGHTING EXPERIMENT DEFINITION
# ================================================================

print("=" * 72)
print("5.5.1 — RF-1 BALANCED CLASS-WEIGHTING EXPERIMENT DEFINITION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-1 STRATEGY DEFINITION
# ---------------------------------------------------------------

print("\n[RF-1 STRATEGY DEFINITION]")

RF1_CONFIGURATION = {
    "strategy_id": "RF-1",
    "strategy_name": "Balanced Class Weighting",
    "class_weight": "balanced",
    "resampling": False,
    "synthetic_sampling": False,
    "training_partition": "Training",
    "evaluation_partition": "Validation",
    "test_used": False,
}

print(
    f"✓ Strategy ID        : "
    f"{RF1_CONFIGURATION['strategy_id']}"
)

print(
    f"✓ Strategy name      : "
    f"{RF1_CONFIGURATION['strategy_name']}"
)

print(
    f"✓ Class weighting    : "
    f"{RF1_CONFIGURATION['class_weight']}"
)

print(
    f"✓ Resampling         : "
    f"{RF1_CONFIGURATION['resampling']}"
)

print(
    f"✓ Synthetic sampling : "
    f"{RF1_CONFIGURATION['synthetic_sampling']}"
)

print(
    f"✓ Training partition : "
    f"{RF1_CONFIGURATION['training_partition']}"
)

print(
    f"✓ Evaluation         : "
    f"{RF1_CONFIGURATION['evaluation_partition']}"
)


# ---------------------------------------------------------------
# 2. COMMON RANDOM FOREST CONFIGURATION CHECK
# ---------------------------------------------------------------

print("\n[COMMON RANDOM FOREST CONFIGURATION]")

if not isinstance(
    RF_COMMON_CONFIGURATION,
    dict
):
    raise TypeError(
        "RF_COMMON_CONFIGURATION must be a dictionary."
    )


if RF_COMMON_CONFIGURATION[
    "random_state"
] != RANDOM_SEED:

    raise RuntimeError(
        "RF-1 random_state does not match "
        "the established project RANDOM_SEED."
    )


print(
    f"✓ Number of trees   : "
    f"{RF_COMMON_CONFIGURATION['n_estimators']}"
)

print(
    f"✓ Max features      : "
    f"{RF_COMMON_CONFIGURATION['max_features']}"
)

print(
    f"✓ Max depth         : "
    f"{RF_COMMON_CONFIGURATION['max_depth']}"
)

print(
    f"✓ Bootstrap         : "
    f"{RF_COMMON_CONFIGURATION['bootstrap']}"
)

print(
    f"✓ CPU parallelism   : "
    f"{RF_COMMON_CONFIGURATION['n_jobs']}"
)

print(
    f"✓ Random seed       : "
    f"{RF_COMMON_CONFIGURATION['random_state']}"
)


# ---------------------------------------------------------------
# 3. RF-1 BALANCED-CLASS-WEIGHTING BOUNDARY
# ---------------------------------------------------------------

print("\n[RF-1 BALANCED-CLASS-WEIGHTING BOUNDARY]")


if RF1_CONFIGURATION[
    "class_weight"
] != "balanced":

    raise RuntimeError(
        "RF-1 must use class_weight='balanced'."
    )


if RF1_CONFIGURATION[
    "resampling"
]:

    raise RuntimeError(
        "RF-1 must not perform random oversampling "
        "or any other resampling."
    )


if RF1_CONFIGURATION[
    "synthetic_sampling"
]:

    raise RuntimeError(
        "RF-1 must not perform synthetic sampling."
    )


print(
    "✓ Training class weighting set to 'balanced'"
)

print(
    "✓ No random oversampling configured"
)

print(
    "✓ No SMOTE configured"
)

print(
    "✓ No synthetic sampling configured"
)


# ---------------------------------------------------------------
# 4. PARTITION-ROLE VALIDATION
# ---------------------------------------------------------------

print("\n[TRAINING / VALIDATION / TEST ROLE BOUNDARY]")


if not RF_5_2_4_VALIDATION[
    "training_authorized_for_fitting"
]:

    raise RuntimeError(
        "Training is not authorized for RF-1 model fitting."
    )


if not RF_5_2_4_VALIDATION[
    "validation_reserved_for_comparison"
]:

    raise RuntimeError(
        "Validation is not reserved for RF strategy comparison."
    )


if not RF_5_2_4_VALIDATION[
    "validation_reserved_for_selection"
]:

    raise RuntimeError(
        "Validation is not reserved for RF strategy selection."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_fitting"
]:

    raise RuntimeError(
        "Independent Test is not protected from model fitting."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_comparison"
]:

    raise RuntimeError(
        "Independent Test is not protected from strategy comparison."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_selection"
]:

    raise RuntimeError(
        "Independent Test is not protected from strategy selection."
    )


print(
    "✓ Training authorized for RF-1 model fitting"
)

print(
    "✓ Validation reserved for RF-1 evaluation and comparison"
)

print(
    "✓ Validation reserved for strategy selection"
)

print(
    "✓ Independent Test excluded from model fitting"
)

print(
    "✓ Independent Test excluded from strategy comparison"
)

print(
    "✓ Independent Test excluded from strategy selection"
)


# ---------------------------------------------------------------
# 5. RF-1 OUTPUT BOUNDARY
# ---------------------------------------------------------------

print("\n[RF-1 EXPERIMENT OUTPUT BOUNDARY]")


RF1_OUTPUT_DIR = (
    RF_STRATEGY_EXPERIMENTS_DIR /
    "RF-1"
)


RF1_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


print(
    "✓ RF-1 output directory available:"
)

print(
    f"  {RF1_OUTPUT_DIR}"
)


# ---------------------------------------------------------------
# 6. MODEL-DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[MODEL-DEVELOPMENT BOUNDARY]")


print(
    "✓ No Training feature array loaded"
)

print(
    "✓ No Validation feature array loaded"
)

print(
    "✓ No Test feature array loaded"
)

print(
    "✓ No target array loaded"
)

print(
    "✓ No Random Forest model fitted"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No synthetic samples generated"
)

print(
    "✓ No predictions generated"
)

print(
    "✓ No evaluation metrics calculated"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 7. FINAL RF-1 DEFINITION VALIDATION
# ---------------------------------------------------------------

print("\n[RF-1 DEFINITION VALIDATION]")


RF_5_5_1_VALIDATION = {

    "strategy_id_valid":
        RF1_CONFIGURATION[
            "strategy_id"
        ] == "RF-1",

    "strategy_name_valid":
        RF1_CONFIGURATION[
            "strategy_name"
        ] == "Balanced Class Weighting",

    "class_weight_balanced":
        RF1_CONFIGURATION[
            "class_weight"
        ] == "balanced",

    "resampling_disabled":
        RF1_CONFIGURATION[
            "resampling"
        ] is False,

    "synthetic_sampling_disabled":
        RF1_CONFIGURATION[
            "synthetic_sampling"
        ] is False,

    "training_partition_valid":
        RF1_CONFIGURATION[
            "training_partition"
        ] == "Training",

    "validation_partition_valid":
        RF1_CONFIGURATION[
            "evaluation_partition"
        ] == "Validation",

    "test_not_used":
        RF1_CONFIGURATION[
            "test_used"
        ] is False,

    "output_directory_available":
        RF1_OUTPUT_DIR.is_dir(),

    "random_state_consistent":
        RF_COMMON_CONFIGURATION[
            "random_state"
        ] == RANDOM_SEED,

    "training_authorized":
        RF_5_2_4_VALIDATION[
            "training_authorized_for_fitting"
        ],

    "validation_reserved_for_comparison":
        RF_5_2_4_VALIDATION[
            "validation_reserved_for_comparison"
        ],

    "test_protected_from_fitting":
        RF_5_2_4_VALIDATION[
            "test_excluded_from_fitting"
        ],

    "test_protected_from_comparison":
        RF_5_2_4_VALIDATION[
            "test_excluded_from_comparison"
        ],

    "test_protected_from_selection":
        RF_5_2_4_VALIDATION[
            "test_excluded_from_selection"
        ],
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_5_1_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "RF-1 balanced class-weighting definition validation failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 8. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.5.1 — RF-1 BALANCED CLASS-WEIGHTING "
    "EXPERIMENT DEFINITION PASSED"
)

print("=" * 72)

print(
    "\nRF-1 Balanced Class Weighting is defined."
)

print(
    "✓ Common Random Forest configuration retained"
)

print(
    "✓ Balanced class weighting configured"
)

print(
    "✓ Validation reserved for evaluation"
)

print(
    "✓ Independent Test remains protected"
)

print(
    "✓ No model fitting or data loading performed"
)

print(
    "\nREADY FOR 5.5.2 — "
    "RF-1 TRAINING AND VALIDATION ARTIFACT LOADING"
)

print("=" * 72)

========================================================================
5.5.1 — RF-1 BALANCED CLASS-WEIGHTING EXPERIMENT DEFINITION
========================================================================

[RF-1 STRATEGY DEFINITION]
✓ Strategy ID        : RF-1
✓ Strategy name      : Balanced Class Weighting
✓ Class weighting    : balanced
✓ Resampling         : False
✓ Synthetic sampling : False
✓ Training partition : Training
✓ Evaluation         : Validation

[COMMON RANDOM FOREST CONFIGURATION]
✓ Number of trees   : 100
✓ Max features      : sqrt
✓ Max depth         : None
✓ Bootstrap         : True
✓ CPU parallelism   : -1
✓ Random seed       : 42

[RF-1 BALANCED-CLASS-WEIGHTING BOUNDARY]
✓ Training class weighting set to 'balanced'
✓ No random oversampling configured
✓ No SMOTE configured
✓ No synthetic sampling configured

[TRAINING / VALIDATION / TEST ROLE BOUNDARY]
✓ Training authorized for RF-1 model fitting
✓ Validation reserved for RF-1 evaluation and comparison
✓ Validation reserved for strategy selection
✓ Independent Test excluded from model fitting
✓ Independent Test excluded from strategy comparison
✓ Independent Test excluded from strategy selection

[RF-1 EXPERIMENT OUTPUT BOUNDARY]
✓ RF-1 output directory available:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1

[MODEL-DEVELOPMENT BOUNDARY]
✓ No Training feature array loaded
✓ No Validation feature array loaded
✓ No Test feature array loaded
✓ No target array loaded
✓ No Random Forest model fitted
✓ No resampling performed
✓ No synthetic samples generated
✓ No predictions generated
✓ No evaluation metrics calculated
✓ Independent Test remains untouched

[RF-1 DEFINITION VALIDATION]

========================================================================
5.5.1 — RF-1 BALANCED CLASS-WEIGHTING EXPERIMENT DEFINITION PASSED
========================================================================

RF-1 Balanced Class Weighting is defined.
✓ Common Random Forest configuration retained
✓ Balanced class weighting configured
✓ Validation reserved for evaluation
✓ Independent Test remains protected
✓ No model fitting or data loading performed

READY FOR 5.5.2 — RF-1 TRAINING AND VALIDATION ARTIFACT LOADING
========================================================================

### 5.5.2 — RF-1 Training and Validation Artifact Loading

This subsection loads the finalized Notebook 04 Training and Validation
artifacts required for the RF-1 Balanced Class Weighting experiment.

The model-ready feature and target artifacts are accessed directly from the
authoritative paths established in Section 5.1. The persisted NumPy arrays
are opened using read-only memory mapping so that the complete Training and
Validation partitions are not duplicated in RAM.

The RF-1 experiment uses:

- Training features and targets for Random Forest model fitting with
  balanced class weighting.
- Validation features and targets for RF-1 performance evaluation and later
  strategy comparison.
- No Independent Test artifacts during RF-1 development.

The Training and Validation partitions retain the complete N04 model-ready
representation of 32 float32 features and their corresponding int64 target
labels.

No feature transformation, scaling, resampling, or synthetic sampling is
performed during artifact loading. The balanced class-weighting strategy is
applied only during the subsequent Random Forest model-fitting stage.

The Independent Test partition remains completely untouched.

The loaded memory-mapped artifacts will be reused by the subsequent RF-1
training and validation stages without creating unnecessary full-array
copies.

In [ ]:
# ================================================================
# 5.5.2 — RF-1 TRAINING AND VALIDATION ARTIFACT LOADING
# ================================================================

import numpy as np


print("=" * 72)
print("5.5.2 — RF-1 TRAINING AND VALIDATION ARTIFACT LOADING")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-1 ARTIFACT LOADING BOUNDARY
# ---------------------------------------------------------------

print("\n[RF-1 ARTIFACT LOADING BOUNDARY]")


if not RF_5_5_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-1 balanced class-weighting definition "
        "has not passed validation."
    )


if RF1_CONFIGURATION[
    "training_partition"
] != "Training":

    raise RuntimeError(
        "RF-1 training partition is not the authoritative "
        "Training partition."
    )


if RF1_CONFIGURATION[
    "evaluation_partition"
] != "Validation":

    raise RuntimeError(
        "RF-1 evaluation partition is not the authoritative "
        "Validation partition."
    )


print(
    "✓ RF-1 balanced class-weighting definition is valid"
)

print(
    "✓ Training artifact authorized for model fitting"
)

print(
    "✓ Validation artifact authorized for RF-1 evaluation"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# 2. AUTHORITATIVE RF-1 ARTIFACT PATHS
# ---------------------------------------------------------------

print("\n[AUTHORITATIVE RF-1 ARTIFACT PATHS]")


RF1_TRAINING_FEATURE_PATH = RF_INPUT_PATHS[
    "Training features"
]

RF1_TRAINING_TARGET_PATH = RF_INPUT_PATHS[
    "Training targets"
]

RF1_VALIDATION_FEATURE_PATH = RF_INPUT_PATHS[
    "Validation features"
]

RF1_VALIDATION_TARGET_PATH = RF_INPUT_PATHS[
    "Validation targets"
]


for artifact_name, artifact_path in {

    "Training features":
        RF1_TRAINING_FEATURE_PATH,

    "Training targets":
        RF1_TRAINING_TARGET_PATH,

    "Validation features":
        RF1_VALIDATION_FEATURE_PATH,

    "Validation targets":
        RF1_VALIDATION_TARGET_PATH,

}.items():

    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"{artifact_name} artifact was not found:\n"
            f"{artifact_path}"
        )

    if artifact_path.stat().st_size == 0:

        raise ValueError(
            f"{artifact_name} artifact is empty:\n"
            f"{artifact_path}"
        )

    print(
        f"✓ {artifact_name:<20}: "
        f"{artifact_path.name}"
    )


# ---------------------------------------------------------------
# 3. READ-ONLY MEMORY-MAPPED LOADING
# ---------------------------------------------------------------

print("\n[READ-ONLY MEMORY-MAPPED LOADING]")


# The complete arrays are not copied into normal RAM.
# mmap_mode="r" provides read-only access to the persisted
# NumPy arrays.

RF1_TRAINING_FEATURES = np.load(
    RF1_TRAINING_FEATURE_PATH,
    mmap_mode="r"
)

RF1_TRAINING_TARGETS = np.load(
    RF1_TRAINING_TARGET_PATH,
    mmap_mode="r"
)

RF1_VALIDATION_FEATURES = np.load(
    RF1_VALIDATION_FEATURE_PATH,
    mmap_mode="r"
)

RF1_VALIDATION_TARGETS = np.load(
    RF1_VALIDATION_TARGET_PATH,
    mmap_mode="r"
)


print(
    "✓ Training features opened as read-only memory map"
)

print(
    "✓ Training targets opened as read-only memory map"
)

print(
    "✓ Validation features opened as read-only memory map"
)

print(
    "✓ Validation targets opened as read-only memory map"
)


# ---------------------------------------------------------------
# 4. FEATURE ARTIFACT VALIDATION
# ---------------------------------------------------------------

print("\n[RF-1 FEATURE ARTIFACT VALIDATION]")


if RF1_TRAINING_FEATURES.shape != (
    1_814_018,
    32
):

    raise ValueError(
        "RF-1 Training feature shape mismatch.\n"
        f"Expected: {(1_814_018, 32)}\n"
        f"Observed: {RF1_TRAINING_FEATURES.shape}"
    )


if RF1_VALIDATION_FEATURES.shape != (
    451_215,
    32
):

    raise ValueError(
        "RF-1 Validation feature shape mismatch.\n"
        f"Expected: {(451_215, 32)}\n"
        f"Observed: {RF1_VALIDATION_FEATURES.shape}"
    )


if RF1_TRAINING_FEATURES.dtype != np.float32:

    raise TypeError(
        "RF-1 Training features must use float32."
    )


if RF1_VALIDATION_FEATURES.dtype != np.float32:

    raise TypeError(
        "RF-1 Validation features must use float32."
    )


print(
    f"✓ Training features    : "
    f"{RF1_TRAINING_FEATURES.shape} | "
    f"{RF1_TRAINING_FEATURES.dtype}"
)

print(
    f"✓ Validation features  : "
    f"{RF1_VALIDATION_FEATURES.shape} | "
    f"{RF1_VALIDATION_FEATURES.dtype}"
)


# ---------------------------------------------------------------
# 5. TARGET ARTIFACT VALIDATION
# ---------------------------------------------------------------

print("\n[RF-1 TARGET ARTIFACT VALIDATION]")


if RF1_TRAINING_TARGETS.shape != (
    1_814_018,
):

    raise ValueError(
        "RF-1 Training target shape mismatch.\n"
        f"Expected: {(1_814_018,)}\n"
        f"Observed: {RF1_TRAINING_TARGETS.shape}"
    )


if RF1_VALIDATION_TARGETS.shape != (
    451_215,
):

    raise ValueError(
        "RF-1 Validation target shape mismatch.\n"
        f"Expected: {(451_215,)}\n"
        f"Observed: {RF1_VALIDATION_TARGETS.shape}"
    )


if RF1_TRAINING_TARGETS.dtype != np.int64:

    raise TypeError(
        "RF-1 Training targets must use int64."
    )


if RF1_VALIDATION_TARGETS.dtype != np.int64:

    raise TypeError(
        "RF-1 Validation targets must use int64."
    )


print(
    f"✓ Training targets    : "
    f"{RF1_TRAINING_TARGETS.shape} | "
    f"{RF1_TRAINING_TARGETS.dtype}"
)

print(
    f"✓ Validation targets  : "
    f"{RF1_VALIDATION_TARGETS.shape} | "
    f"{RF1_VALIDATION_TARGETS.dtype}"
)


# ---------------------------------------------------------------
# 6. X/Y OBSERVATION ALIGNMENT
# ---------------------------------------------------------------

print("\n[X/Y OBSERVATION ALIGNMENT]")


if (
    RF1_TRAINING_FEATURES.shape[0]
    != RF1_TRAINING_TARGETS.shape[0]
):

    raise ValueError(
        "RF-1 Training feature/target observation counts "
        "are not aligned."
    )


if (
    RF1_VALIDATION_FEATURES.shape[0]
    != RF1_VALIDATION_TARGETS.shape[0]
):

    raise ValueError(
        "RF-1 Validation feature/target observation counts "
        "are not aligned."
    )


print(
    "✓ Training features and targets are observation-aligned"
)

print(
    "✓ Validation features and targets are observation-aligned"
)


# ---------------------------------------------------------------
# 7. CONFIRM COMMON MODEL-READY FEATURE SPACE
# ---------------------------------------------------------------

print("\n[COMMON RF-1 MODEL-READY FEATURE SPACE]")


if (
    RF1_TRAINING_FEATURES.shape[1]
    != RF1_VALIDATION_FEATURES.shape[1]
):

    raise ValueError(
        "RF-1 Training and Validation feature dimensions "
        "do not match."
    )


if RF1_TRAINING_FEATURES.shape[1] != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-1 feature count does not match the established "
        "N04 model-ready feature contract."
    )


print(
    f"✓ Common RF-1 feature count : "
    f"{RF1_TRAINING_FEATURES.shape[1]}"
)

print(
    "✓ Training and Validation share the same "
    "32-feature model-ready representation"
)


# ---------------------------------------------------------------
# 8. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION]")


print(
    "✓ Independent Test feature artifact was not loaded"
)

print(
    "✓ Independent Test target artifact was not loaded"
)

print(
    "✓ Independent Test remains protected from RF-1 development"
)


# ---------------------------------------------------------------
# 9. MEMORY-AWARE EXECUTION CHECK
# ---------------------------------------------------------------

print("\n[MEMORY-AWARE EXECUTION CHECK]")


if not isinstance(
    RF1_TRAINING_FEATURES,
    np.memmap
):

    raise TypeError(
        "RF-1 Training features were not loaded "
        "as a NumPy memory map."
    )


if not isinstance(
    RF1_TRAINING_TARGETS,
    np.memmap
):

    raise TypeError(
        "RF-1 Training targets were not loaded "
        "as a NumPy memory map."
    )


if not isinstance(
    RF1_VALIDATION_FEATURES,
    np.memmap
):

    raise TypeError(
        "RF-1 Validation features were not loaded "
        "as a NumPy memory map."
    )


if not isinstance(
    RF1_VALIDATION_TARGETS,
    np.memmap
):

    raise TypeError(
        "RF-1 Validation targets were not loaded "
        "as a NumPy memory map."
    )


print(
    "✓ Training features remain memory-mapped"
)

print(
    "✓ Training targets remain memory-mapped"
)

print(
    "✓ Validation features remain memory-mapped"
)

print(
    "✓ Validation targets remain memory-mapped"
)

print(
    "✓ No full-array RAM duplication performed"
)


# ---------------------------------------------------------------
# 10. FINAL RF-1 ARTIFACT LOADING VALIDATION
# ---------------------------------------------------------------

RF_5_5_2_VALIDATION = {

    "training_features_loaded":
        RF1_TRAINING_FEATURES.shape
        == (1_814_018, 32),

    "training_targets_loaded":
        RF1_TRAINING_TARGETS.shape
        == (1_814_018,),

    "validation_features_loaded":
        RF1_VALIDATION_FEATURES.shape
        == (451_215, 32),

    "validation_targets_loaded":
        RF1_VALIDATION_TARGETS.shape
        == (451_215,),

    "training_feature_dtype":
        RF1_TRAINING_FEATURES.dtype
        == np.float32,

    "validation_feature_dtype":
        RF1_VALIDATION_FEATURES.dtype
        == np.float32,

    "training_target_dtype":
        RF1_TRAINING_TARGETS.dtype
        == np.int64,

    "validation_target_dtype":
        RF1_VALIDATION_TARGETS.dtype
        == np.int64,

    "training_xy_alignment":
        RF1_TRAINING_FEATURES.shape[0]
        == RF1_TRAINING_TARGETS.shape[0],

    "validation_xy_alignment":
        RF1_VALIDATION_FEATURES.shape[0]
        == RF1_VALIDATION_TARGETS.shape[0],

    "common_feature_space":
        RF1_TRAINING_FEATURES.shape[1]
        == RF1_VALIDATION_FEATURES.shape[1]
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "training_features_memory_mapped":
        isinstance(
            RF1_TRAINING_FEATURES,
            np.memmap
        ),

    "training_targets_memory_mapped":
        isinstance(
            RF1_TRAINING_TARGETS,
            np.memmap
        ),

    "validation_features_memory_mapped":
        isinstance(
            RF1_VALIDATION_FEATURES,
            np.memmap
        ),

    "validation_targets_memory_mapped":
        isinstance(
            RF1_VALIDATION_TARGETS,
            np.memmap
        ),

    "independent_test_not_loaded":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_5_2_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.5.2 RF-1 Training and Validation Artifact "
        "Loading failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 11. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.5.2 — RF-1 TRAINING AND VALIDATION "
    "ARTIFACT LOADING PASSED"
)

print("=" * 72)

print(
    "\n✓ Complete Training partition is available "
    "through read-only memory mapping"
)

print(
    "✓ Complete Validation partition is available "
    "through read-only memory mapping"
)

print(
    "✓ Training and Validation X/y dimensions are aligned"
)

print(
    "✓ Common 32-feature float32 representation confirmed"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ No resampling or synthetic sampling performed"
)

print(
    "\nREADY FOR 5.5.3 — RF-1 RANDOM FOREST MODEL FITTING"
)

print("=" * 72)

========================================================================
5.5.2 — RF-1 TRAINING AND VALIDATION ARTIFACT LOADING
========================================================================

[RF-1 ARTIFACT LOADING BOUNDARY]
✓ RF-1 balanced class-weighting definition is valid
✓ Training artifact authorized for model fitting
✓ Validation artifact authorized for RF-1 evaluation
✓ Independent Test remains excluded

[AUTHORITATIVE RF-1 ARTIFACT PATHS]
✓ Training features   : X_train_scaled.npy
✓ Training targets    : y_train.npy
✓ Validation features : X_validation_scaled.npy
✓ Validation targets  : y_validation.npy

[READ-ONLY MEMORY-MAPPED LOADING]
✓ Training features opened as read-only memory map
✓ Training targets opened as read-only memory map
✓ Validation features opened as read-only memory map
✓ Validation targets opened as read-only memory map

[RF-1 FEATURE ARTIFACT VALIDATION]
✓ Training features    : (1814018, 32) | float32
✓ Validation features  : (451215, 32) | float32

[RF-1 TARGET ARTIFACT VALIDATION]
✓ Training targets    : (1814018,) | int64
✓ Validation targets  : (451215,) | int64

[X/Y OBSERVATION ALIGNMENT]
✓ Training features and targets are observation-aligned
✓ Validation features and targets are observation-aligned

[COMMON RF-1 MODEL-READY FEATURE SPACE]
✓ Common RF-1 feature count : 32
✓ Training and Validation share the same 32-feature model-ready representation

[INDEPENDENT TEST PROTECTION]
✓ Independent Test feature artifact was not loaded
✓ Independent Test target artifact was not loaded
✓ Independent Test remains protected from RF-1 development

[MEMORY-AWARE EXECUTION CHECK]
✓ Training features remain memory-mapped
✓ Training targets remain memory-mapped
✓ Validation features remain memory-mapped
✓ Validation targets remain memory-mapped
✓ No full-array RAM duplication performed

========================================================================
5.5.2 — RF-1 TRAINING AND VALIDATION ARTIFACT LOADING PASSED
========================================================================

✓ Complete Training partition is available through read-only memory mapping
✓ Complete Validation partition is available through read-only memory mapping
✓ Training and Validation X/y dimensions are aligned
✓ Common 32-feature float32 representation confirmed
✓ Independent Test remains completely untouched
✓ No resampling or synthetic sampling performed

READY FOR 5.5.3 — RF-1 RANDOM FOREST MODEL FITTING
========================================================================

### 5.5.3 — RF-1 Random Forest Model Fitting

This subsection fits the RF-1 Random Forest using the complete N04 Training
partition and the Balanced Class Weighting strategy.

The Training observations retain their original natural class distribution.
Unlike RF-3 and RF-4, RF-1 does not modify the Training dataset through
random oversampling, SMOTE, downsampling, or synthetic sample generation.
Instead, `class_weight="balanced"` is supplied directly to the Random Forest
classifier so that class contributions during model fitting are adjusted
according to the observed Training class frequencies.

The common Random Forest configuration established in Section 5.3 remains
unchanged, including 100 trees, `max_features="sqrt"`, unlimited tree depth,
bootstrap sampling, full CPU parallelism, and the established project
random seed.

Only the Training partition is used for model fitting. The Validation
partition remains loaded but is not used during fitting and is reserved for
the subsequent RF-1 prediction and performance evaluation stage.

The Independent Test partition remains completely untouched.

Training time and memory state before and after fitting are recorded to
support the later resource comparison between RF strategies.

After fitting, the RF-1 model structure is validated against the frozen
32-feature model-ready representation, the nine-class RF taxonomy, and the
common Random Forest configuration.

No Validation predictions, evaluation metrics, strategy selection, or model
persistence are performed in this subsection.

In [ ]:
# ================================================================
# 5.5.3 — RF-1 RANDOM FOREST MODEL FITTING
# ================================================================

from sklearn.ensemble import RandomForestClassifier
import numpy as np
import time


print("=" * 72)
print("5.5.3 — RF-1 RANDOM FOREST MODEL FITTING")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-1 FITTING BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-1 FITTING BOUNDARY VALIDATION]")


if not RF_5_5_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-1 balanced class-weighting definition "
        "has not passed validation."
    )


if not RF_5_5_2_VALIDATION[
    "training_features_loaded"
]:

    raise RuntimeError(
        "RF-1 Training features are not available "
        "for model fitting."
    )


if not RF_5_5_2_VALIDATION[
    "training_targets_loaded"
]:

    raise RuntimeError(
        "RF-1 Training targets are not available "
        "for model fitting."
    )


if not RF_5_5_2_VALIDATION[
    "training_xy_alignment"
]:

    raise RuntimeError(
        "RF-1 Training features and targets are not aligned."
    )


if not RF_5_5_2_VALIDATION[
    "training_features_memory_mapped"
]:

    raise RuntimeError(
        "RF-1 Training features are not memory-mapped."
    )


if RF1_CONFIGURATION[
    "class_weight"
] != "balanced":

    raise RuntimeError(
        "RF-1 model fitting must use "
        "class_weight='balanced'."
    )


if RF1_CONFIGURATION[
    "resampling"
]:

    raise RuntimeError(
        "RF-1 model fitting must not perform resampling."
    )


if RF1_CONFIGURATION[
    "synthetic_sampling"
]:

    raise RuntimeError(
        "RF-1 model fitting must not perform synthetic sampling."
    )


if not RF_5_2_4_VALIDATION[
    "training_authorized_for_fitting"
]:

    raise RuntimeError(
        "Training partition is not authorized for "
        "RF-1 model fitting."
    )


print(
    "✓ RF-1 balanced class-weighting definition validated"
)

print(
    "✓ Complete Training features available"
)

print(
    "✓ Complete Training targets available"
)

print(
    "✓ Training features and targets are aligned"
)

print(
    "✓ Training features remain memory-mapped"
)

print(
    "✓ Natural Training class distribution retained"
)

print(
    "✓ Balanced class weighting configured"
)

print(
    "✓ No resampling configured"
)

print(
    "✓ No synthetic sampling configured"
)

print(
    "✓ Training partition authorized for model fitting"
)


# ---------------------------------------------------------------
# 2. TRAINING FEATURE-SPACE VALIDATION
# ---------------------------------------------------------------

print("\n[TRAINING FEATURE-SPACE VALIDATION]")


if RF1_TRAINING_FEATURES.shape[1] != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-1 Training feature count does not match "
        "the established model-ready feature contract."
    )


if RF1_TRAINING_FEATURES.dtype != np.float32:

    raise TypeError(
        "RF-1 Training features must use float32."
    )


if RF1_TRAINING_FEATURES.shape[1] != len(
    RF_FEATURE_ORDER
):

    raise ValueError(
        "RF-1 Training feature count does not match "
        "the frozen RF feature order."
    )


print(
    f"✓ Training observations : "
    f"{RF1_TRAINING_FEATURES.shape[0]:,}"
)

print(
    f"✓ Training features     : "
    f"{RF1_TRAINING_FEATURES.shape[1]}"
)

print(
    f"✓ Training dtype        : "
    f"{RF1_TRAINING_FEATURES.dtype}"
)

print(
    "✓ Training feature space matches "
    "the frozen RF model-ready contract"
)


# ---------------------------------------------------------------
# 3. NATURAL TRAINING CLASS DISTRIBUTION
# ---------------------------------------------------------------

print("\n[RF-1 NATURAL TRAINING CLASS DISTRIBUTION]")


RF1_TRAINING_CLASS_IDS, RF1_TRAINING_CLASS_COUNTS = (
    np.unique(
        RF1_TRAINING_TARGETS,
        return_counts=True
    )
)


RF1_TRAINING_CLASS_DISTRIBUTION = {
    int(class_id): int(class_count)
    for class_id, class_count
    in zip(
        RF1_TRAINING_CLASS_IDS,
        RF1_TRAINING_CLASS_COUNTS
    )
}


if not np.array_equal(
    RF1_TRAINING_CLASS_IDS,
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    )
):

    raise ValueError(
        "RF-1 Training target classes do not match "
        "the established 0–8 RF taxonomy."
    )


for class_id, class_count in (
    RF1_TRAINING_CLASS_DISTRIBUTION.items()
):

    print(
        f"✓ Class {class_id}: "
        f"{RF_CLASS_MAPPING[class_id]:<24} "
        f"{class_count:,}"
    )


print(
    "✓ Complete natural Training class distribution "
    "retained for RF-1"
)


# ---------------------------------------------------------------
# 4. RF-1 MODEL CONSTRUCTION
# ---------------------------------------------------------------

print("\n[RF-1 MODEL CONSTRUCTION]")


RF1_MODEL = RandomForestClassifier(
    **RF_COMMON_CONFIGURATION,
    class_weight=RF1_CONFIGURATION[
        "class_weight"
    ]
)


if not isinstance(
    RF1_MODEL,
    RandomForestClassifier
):

    raise TypeError(
        "RF1_MODEL was not created as a "
        "RandomForestClassifier."
    )


if RF1_MODEL.n_estimators != (
    RF_COMMON_CONFIGURATION[
        "n_estimators"
    ]
):

    raise RuntimeError(
        "RF-1 model n_estimators does not match "
        "the common Random Forest configuration."
    )


if RF1_MODEL.max_features != (
    RF_COMMON_CONFIGURATION[
        "max_features"
    ]
):

    raise RuntimeError(
        "RF-1 model max_features does not match "
        "the common Random Forest configuration."
    )


if RF1_MODEL.max_depth != (
    RF_COMMON_CONFIGURATION[
        "max_depth"
    ]
):

    raise RuntimeError(
        "RF-1 model max_depth does not match "
        "the common Random Forest configuration."
    )


if RF1_MODEL.bootstrap != (
    RF_COMMON_CONFIGURATION[
        "bootstrap"
    ]
):

    raise RuntimeError(
        "RF-1 model bootstrap configuration does not "
        "match the common Random Forest configuration."
    )


if RF1_MODEL.n_jobs != (
    RF_COMMON_CONFIGURATION[
        "n_jobs"
    ]
):

    raise RuntimeError(
        "RF-1 model n_jobs configuration does not "
        "match the common Random Forest configuration."
    )


if RF1_MODEL.random_state != (
    RF_COMMON_CONFIGURATION[
        "random_state"
    ]
):

    raise RuntimeError(
        "RF-1 model random_state does not "
        "match the established project seed."
    )


if RF1_MODEL.class_weight != "balanced":

    raise RuntimeError(
        "RF-1 must use class_weight='balanced'."
    )


print(
    f"✓ Random Forest trees     : "
    f"{RF1_MODEL.n_estimators}"
)

print(
    f"✓ Max features           : "
    f"{RF1_MODEL.max_features}"
)

print(
    f"✓ Max depth              : "
    f"{RF1_MODEL.max_depth}"
)

print(
    f"✓ Bootstrap              : "
    f"{RF1_MODEL.bootstrap}"
)

print(
    f"✓ CPU parallelism        : "
    f"{RF1_MODEL.n_jobs}"
)

print(
    f"✓ Random state            : "
    f"{RF1_MODEL.random_state}"
)

print(
    f"✓ Class weighting         : "
    f"{RF1_MODEL.class_weight}"
)

print(
    "✓ RF-1 Random Forest model constructed"
)


# ---------------------------------------------------------------
# 5. RESOURCE STATE BEFORE FITTING
# ---------------------------------------------------------------

print("\n[RESOURCE STATE BEFORE RF-1 FITTING]")


RF_MEMORY = psutil.virtual_memory()


RF1_AVAILABLE_MEMORY_BEFORE_GB = (
    RF_MEMORY.available / (1024 ** 3)
)


RF1_PROCESS_MEMORY_BEFORE_GB = (
    RF_PROCESS.memory_info().rss / (1024 ** 3)
)


print(
    f"✓ Available system RAM : "
    f"{RF1_AVAILABLE_MEMORY_BEFORE_GB:.2f} GB"
)

print(
    f"✓ Python process RAM   : "
    f"{RF1_PROCESS_MEMORY_BEFORE_GB:.2f} GB"
)

print(
    "✓ Training input remains memory-mapped"
)

print(
    "✓ Validation input remains loaded but unused "
    "during model fitting"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 6. RF-1 MODEL FITTING
# ---------------------------------------------------------------

print("\n[RF-1 MODEL FITTING]")


RF1_TRAINING_START_TIME = time.perf_counter()


RF1_MODEL.fit(
    RF1_TRAINING_FEATURES,
    RF1_TRAINING_TARGETS
)


RF1_TRAINING_END_TIME = time.perf_counter()


RF1_TRAINING_TIME_SECONDS = (
    RF1_TRAINING_END_TIME
    - RF1_TRAINING_START_TIME
)


print(
    "✓ RF-1 model fitting completed"
)

print(
    f"✓ Training time : "
    f"{RF1_TRAINING_TIME_SECONDS:.3f} seconds"
)


# ---------------------------------------------------------------
# 7. RESOURCE STATE AFTER FITTING
# ---------------------------------------------------------------

print("\n[RESOURCE STATE AFTER RF-1 FITTING]")


RF_MEMORY = psutil.virtual_memory()


RF1_AVAILABLE_MEMORY_AFTER_GB = (
    RF_MEMORY.available / (1024 ** 3)
)


RF1_PROCESS_MEMORY_AFTER_GB = (
    RF_PROCESS.memory_info().rss / (1024 ** 3)
)


RF1_PROCESS_MEMORY_DELTA_GB = (
    RF1_PROCESS_MEMORY_AFTER_GB
    - RF1_PROCESS_MEMORY_BEFORE_GB
)


print(
    f"✓ Available system RAM : "
    f"{RF1_AVAILABLE_MEMORY_AFTER_GB:.2f} GB"
)

print(
    f"✓ Python process RAM   : "
    f"{RF1_PROCESS_MEMORY_AFTER_GB:.2f} GB"
)

print(
    f"✓ Process RAM change   : "
    f"{RF1_PROCESS_MEMORY_DELTA_GB:+.2f} GB"
)


# ---------------------------------------------------------------
# 8. FITTED MODEL STRUCTURE VALIDATION
# ---------------------------------------------------------------

print("\n[RF-1 FITTED MODEL VALIDATION]")


if not hasattr(
    RF1_MODEL,
    "n_features_in_"
):

    raise RuntimeError(
        "RF-1 fitted model does not expose "
        "n_features_in_."
    )


if RF1_MODEL.n_features_in_ != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-1 fitted model feature count does not "
        "match the established 32-feature contract."
    )


if not hasattr(
    RF1_MODEL,
    "classes_"
):

    raise RuntimeError(
        "RF-1 fitted model does not expose classes_."
    )


if not np.array_equal(
    RF1_MODEL.classes_,
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    )
):

    raise ValueError(
        "RF-1 fitted model classes do not match "
        "the established 0–8 taxonomy."
    )


if not hasattr(
    RF1_MODEL,
    "estimators_"
):

    raise RuntimeError(
        "RF-1 fitted model does not contain "
        "trained estimators."
    )


if len(
    RF1_MODEL.estimators_
) != RF_COMMON_CONFIGURATION[
    "n_estimators"
]:

    raise RuntimeError(
        "RF-1 fitted model does not contain the "
        "expected number of trained trees."
    )


print(
    f"✓ Fitted model feature count : "
    f"{RF1_MODEL.n_features_in_}"
)

print(
    f"✓ Fitted model classes       : "
    f"{len(RF1_MODEL.classes_)}"
)

print(
    f"✓ Fitted model tree count    : "
    f"{len(RF1_MODEL.estimators_)}"
)

print(
    "✓ RF-1 fitted model matches "
    "the established feature and taxonomy contracts"
)


# ---------------------------------------------------------------
# 9. DEVELOPMENT-BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-1 DEVELOPMENT-BOUNDARY VALIDATION]")


print(
    "✓ RF-1 fitted only on the Training partition"
)

print(
    "✓ Validation targets were not used for fitting"
)

print(
    "✓ Validation predictions were not generated"
)

print(
    "✓ Independent Test features were not loaded"
)

print(
    "✓ Independent Test targets were not loaded"
)

print(
    "✓ Balanced class weighting was applied"
)

print(
    "✓ No random oversampling was applied"
)

print(
    "✓ No SMOTE was applied"
)

print(
    "✓ No synthetic samples were generated"
)

print(
    "✓ No strategy selection was performed"
)

print(
    "✓ No RF-1 evaluation metrics were calculated"
)

print(
    "✓ Model persistence was not performed in this subsection"
)


# ---------------------------------------------------------------
# 10. FINAL RF-1 FITTING VALIDATION
# ---------------------------------------------------------------

RF_5_5_3_VALIDATION = {

    "rf1_strategy_valid":
        RF1_CONFIGURATION[
            "strategy_id"
        ] == "RF-1",

    "training_partition_used":
        RF1_TRAINING_FEATURES.shape
        == (
            1_814_018,
            32
        ),

    "training_targets_used":
        RF1_TRAINING_TARGETS.shape
        == (
            1_814_018,
        ),

    "training_feature_dtype":
        RF1_TRAINING_FEATURES.dtype
        == np.float32,

    "training_target_dtype":
        RF1_TRAINING_TARGETS.dtype
        == np.int64,

    "balanced_class_weighting":
        RF1_CONFIGURATION[
            "class_weight"
        ] == "balanced"
        and RF1_MODEL.class_weight == "balanced",

    "resampling_disabled":
        RF1_CONFIGURATION[
            "resampling"
        ] is False,

    "synthetic_sampling_disabled":
        RF1_CONFIGURATION[
            "synthetic_sampling"
        ] is False,

    "feature_count_valid":
        RF1_MODEL.n_features_in_
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "taxonomy_valid":
        np.array_equal(
            RF1_MODEL.classes_,
            np.asarray(
                EXPECTED_RF_CLASS_IDS
            )
        ),

    "tree_count_valid":
        len(
            RF1_MODEL.estimators_
        )
        == RF_COMMON_CONFIGURATION[
            "n_estimators"
        ],

    "random_state_valid":
        RF1_MODEL.random_state
        == RANDOM_SEED,

    "training_time_recorded":
        RF1_TRAINING_TIME_SECONDS > 0,

    "independent_test_not_used":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_5_3_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.5.3 RF-1 model fitting validation failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 11. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.5.3 — RF-1 RANDOM FOREST MODEL FITTING PASSED"
)

print("=" * 72)

print(
    "\n✓ RF-1 Balanced Class Weighting fitted successfully"
)

print(
    "✓ Complete Training partition used for model fitting"
)

print(
    "✓ Natural Training class distribution retained"
)

print(
    "✓ Balanced class weighting applied"
)

print(
    "✓ Common Random Forest configuration retained"
)

print(
    "✓ 32-feature model-ready representation confirmed"
)

print(
    "✓ Nine-class taxonomy confirmed"
)

print(
    "✓ Validation remains reserved for subsequent RF-1 evaluation"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ No resampling or synthetic sampling performed"
)

print(
    "\nREADY FOR 5.5.4 — "
    "RF-1 VALIDATION PREDICTION AND PERFORMANCE EVALUATION"
)

print("=" * 72)

========================================================================
5.5.3 — RF-1 RANDOM FOREST MODEL FITTING
========================================================================

[RF-1 FITTING BOUNDARY VALIDATION]
✓ RF-1 balanced class-weighting definition validated
✓ Complete Training features available
✓ Complete Training targets available
✓ Training features and targets are aligned
✓ Training features remain memory-mapped
✓ Natural Training class distribution retained
✓ Balanced class weighting configured
✓ No resampling configured
✓ No synthetic sampling configured
✓ Training partition authorized for model fitting

[TRAINING FEATURE-SPACE VALIDATION]
✓ Training observations : 1,814,018
✓ Training features     : 32
✓ Training dtype        : float32
✓ Training feature space matches the frozen RF model-ready contract

[RF-1 NATURAL TRAINING CLASS DISTRIBUTION]
✓ Class 0: BENIGN                   1,448,197
✓ Class 1: DDoS                     81,968
✓ Class 2: Port Scan                101,723
✓ Class 3: Brute Force              9,325
✓ Class 4: Bot                      1,270
✓ Class 5: Web Attack               1,389
✓ Class 6: Infiltration             15
✓ Class 7: DoS                      170,125
✓ Class 8: Heartbleed               6
✓ Complete natural Training class distribution retained for RF-1

[RF-1 MODEL CONSTRUCTION]
✓ Random Forest trees     : 100
✓ Max features           : sqrt
✓ Max depth              : None
✓ Bootstrap              : True
✓ CPU parallelism        : -1
✓ Random state            : 42
✓ Class weighting         : balanced
✓ RF-1 Random Forest model constructed

[RESOURCE STATE BEFORE RF-1 FITTING]
✓ Available system RAM : 9.91 GB
✓ Python process RAM   : 1.45 GB
✓ Training input remains memory-mapped
✓ Validation input remains loaded but unused during model fitting
✓ Independent Test remains untouched

[RF-1 MODEL FITTING]
✓ RF-1 model fitting completed
✓ Training time : 753.812 seconds

[RESOURCE STATE AFTER RF-1 FITTING]
✓ Available system RAM : 9.87 GB
✓ Python process RAM   : 1.73 GB
✓ Process RAM change   : +0.28 GB

[RF-1 FITTED MODEL VALIDATION]
✓ Fitted model feature count : 32
✓ Fitted model classes       : 9
✓ Fitted model tree count    : 100
✓ RF-1 fitted model matches the established feature and taxonomy contracts

[RF-1 DEVELOPMENT-BOUNDARY VALIDATION]
✓ RF-1 fitted only on the Training partition
✓ Validation targets were not used for fitting
✓ Validation predictions were not generated
✓ Independent Test features were not loaded
✓ Independent Test targets were not loaded
✓ Balanced class weighting was applied
✓ No random oversampling was applied
✓ No SMOTE was applied
✓ No synthetic samples were generated
✓ No strategy selection was performed
✓ No RF-1 evaluation metrics were calculated
✓ Model persistence was not performed in this subsection

========================================================================
5.5.3 — RF-1 RANDOM FOREST MODEL FITTING PASSED
========================================================================

✓ RF-1 Balanced Class Weighting fitted successfully
✓ Complete Training partition used for model fitting
✓ Natural Training class distribution retained
✓ Balanced class weighting applied
✓ Common Random Forest configuration retained
✓ 32-feature model-ready representation confirmed
✓ Nine-class taxonomy confirmed
✓ Validation remains reserved for subsequent RF-1 evaluation
✓ Independent Test remains completely untouched
✓ No resampling or synthetic sampling performed

READY FOR 5.5.4 — RF-1 VALIDATION PREDICTION AND PERFORMANCE EVALUATION
========================================================================

### 5.5.4 — RF-1 Validation Prediction and Performance Evaluation

This subsection evaluates the fitted RF-1 Balanced Class Weighting model on
the complete N04 Validation partition.

The Validation partition is used exclusively for RF-1 performance evaluation.
The fitted RF-1 model generates predictions for all Validation observations,
and the same evaluation protocol established for RF-0 is applied to maintain
a controlled comparison across Random Forest strategies.

The primary evaluation metric is Macro F1, which gives equal importance to
all nine RF taxonomy classes. Secondary metrics include Accuracy, Balanced
Accuracy, Macro Recall, and Weighted F1.

Per-class Precision, Recall, F1-score, and Support are calculated for all
nine classes. A complete 9 × 9 confusion matrix is generated to examine
classification errors across the RF taxonomy.

Additional error analysis includes the BENIGN false-positive rate and the
false-negative count for each attack class. Macro ROC-AUC using the
one-vs-rest formulation is calculated as a supplementary performance
measure using the RF-1 class-probability outputs.

The evaluation procedure does not modify the fitted RF-1 model or its
Balanced Class Weighting configuration. No Training data are used for
additional fitting, no resampling or synthetic sampling is performed, and
no strategy selection decision is made at this stage.

The Independent Test partition remains completely untouched and is not
used for prediction or evaluation.

The resulting RF-1 validation metrics and error-analysis objects remain
available for the subsequent RF-1 Error and Resource Analysis and Artifact
Persistence stages.

In [ ]:
# ================================================================
# 5.5.4 — RF-1 VALIDATION PREDICTION AND PERFORMANCE EVALUATION
# ================================================================

import numpy as np
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_recall_fscore_support,
    f1_score,
    recall_score,
    confusion_matrix,
    roc_auc_score
)

print("=" * 72)
print("5.5.4 — RF-1 VALIDATION PREDICTION AND PERFORMANCE EVALUATION")
print("=" * 72)

# ------------------------------------------------
# [RF-1 EVALUATION BOUNDARY VALIDATION]
# ------------------------------------------------

print("\n[RF-1 EVALUATION BOUNDARY VALIDATION]")

if RF1_MODEL is None:
    raise ValueError("RF-1 fitted model is not available.")

if RF1_VALIDATION_FEATURES.shape != (451215, 32):
    raise ValueError(
        f"Unexpected RF-1 Validation feature shape: "
        f"{RF1_VALIDATION_FEATURES.shape}"
    )

if RF1_VALIDATION_TARGETS.shape != (451215,):
    raise ValueError(
        f"Unexpected RF-1 Validation target shape: "
        f"{RF1_VALIDATION_TARGETS.shape}"
    )

if RF1_VALIDATION_FEATURES.dtype != np.float32:
    raise TypeError(
        f"RF-1 Validation features must be float32, "
        f"got {RF1_VALIDATION_FEATURES.dtype}"
    )

if RF1_VALIDATION_TARGETS.dtype != np.int64:
    raise TypeError(
        f"RF-1 Validation targets must be int64, "
        f"got {RF1_VALIDATION_TARGETS.dtype}"
    )

if len(RF1_VALIDATION_FEATURES) != len(RF1_VALIDATION_TARGETS):
    raise ValueError("RF-1 Validation X/y observations are not aligned.")

print("✓ RF-1 fitted model is available")
print("✓ Complete Validation feature artifact is available")
print("✓ Complete Validation target artifact is available")
print("✓ Validation X/y observations are aligned")
print("✓ Validation feature representation = 32 float32 features")
print("✓ Independent Test remains excluded")


# ------------------------------------------------
# [RF-1 VALIDATION PREDICTION]
# ------------------------------------------------

print("\n[RF-1 VALIDATION PREDICTION]")

RF1_VALIDATION_PREDICTIONS = RF1_MODEL.predict(
    RF1_VALIDATION_FEATURES
)

if RF1_VALIDATION_PREDICTIONS.shape != RF1_VALIDATION_TARGETS.shape:
    raise ValueError(
        "RF-1 Validation prediction shape does not match Validation targets."
    )

if not np.isfinite(RF1_VALIDATION_PREDICTIONS).all():
    raise ValueError(
        "RF-1 Validation predictions contain non-finite values."
    )

print(
    f"✓ Validation predictions generated : "
    f"{RF1_VALIDATION_PREDICTIONS.shape[0]:,}"
)

print("✓ Validation predictions correspond to the complete Validation partition")
print("✓ No Independent Test predictions generated")


# ------------------------------------------------
# [PRIMARY AND SECONDARY PERFORMANCE METRICS]
# ------------------------------------------------

print("\n[PRIMARY AND SECONDARY PERFORMANCE METRICS]")

RF1_VALIDATION_ACCURACY = accuracy_score(
    RF1_VALIDATION_TARGETS,
    RF1_VALIDATION_PREDICTIONS
)

RF1_VALIDATION_BALANCED_ACCURACY = balanced_accuracy_score(
    RF1_VALIDATION_TARGETS,
    RF1_VALIDATION_PREDICTIONS
)

RF1_VALIDATION_MACRO_F1 = f1_score(
    RF1_VALIDATION_TARGETS,
    RF1_VALIDATION_PREDICTIONS,
    average="macro",
    zero_division=0
)

RF1_VALIDATION_MACRO_RECALL = recall_score(
    RF1_VALIDATION_TARGETS,
    RF1_VALIDATION_PREDICTIONS,
    average="macro",
    zero_division=0
)

RF1_VALIDATION_WEIGHTED_F1 = f1_score(
    RF1_VALIDATION_TARGETS,
    RF1_VALIDATION_PREDICTIONS,
    average="weighted",
    zero_division=0
)

print(f"✓ Accuracy              : {RF1_VALIDATION_ACCURACY:.6f}")
print(f"✓ Balanced Accuracy     : {RF1_VALIDATION_BALANCED_ACCURACY:.6f}")
print(f"✓ Macro Recall          : {RF1_VALIDATION_MACRO_RECALL:.6f}")
print(f"✓ Macro F1              : {RF1_VALIDATION_MACRO_F1:.6f}")
print(f"✓ Weighted F1           : {RF1_VALIDATION_WEIGHTED_F1:.6f}")


# ------------------------------------------------
# [PER-CLASS PERFORMANCE METRICS]
# ------------------------------------------------

print("\n[PER-CLASS PERFORMANCE METRICS]")

RF1_VALIDATION_PRECISION_PER_CLASS, \
RF1_VALIDATION_RECALL_PER_CLASS, \
RF1_VALIDATION_F1_PER_CLASS, \
RF1_VALIDATION_SUPPORT_PER_CLASS = precision_recall_fscore_support(
    RF1_VALIDATION_TARGETS,
    RF1_VALIDATION_PREDICTIONS,
    labels=np.arange(9),
    zero_division=0
)

RF1_VALIDATION_CLASS_NAMES = [
    "BENIGN",
    "DDoS",
    "Port Scan",
    "Brute Force",
    "Bot",
    "Web Attack",
    "Infiltration",
    "DoS",
    "Heartbleed"
]

for class_id, class_name in enumerate(RF1_VALIDATION_CLASS_NAMES):
    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Precision={RF1_VALIDATION_PRECISION_PER_CLASS[class_id]:.6f} | "
        f"Recall={RF1_VALIDATION_RECALL_PER_CLASS[class_id]:.6f} | "
        f"F1={RF1_VALIDATION_F1_PER_CLASS[class_id]:.6f} | "
        f"Support={RF1_VALIDATION_SUPPORT_PER_CLASS[class_id]:,}"
    )


# ------------------------------------------------
# [CONFUSION MATRIX]
# ------------------------------------------------

print("\n[CONFUSION MATRIX]")

RF1_VALIDATION_CONFUSION_MATRIX = confusion_matrix(
    RF1_VALIDATION_TARGETS,
    RF1_VALIDATION_PREDICTIONS,
    labels=np.arange(9)
)

if RF1_VALIDATION_CONFUSION_MATRIX.shape != (9, 9):
    raise ValueError(
        f"Unexpected RF-1 confusion-matrix shape: "
        f"{RF1_VALIDATION_CONFUSION_MATRIX.shape}"
    )

print("✓ 9 × 9 confusion matrix generated")
print("✓ All nine taxonomy classes included")

print("\nRF-1 Validation Confusion Matrix:")
print(RF1_VALIDATION_CONFUSION_MATRIX)


# ------------------------------------------------
# [BENIGN FALSE-POSITIVE RATE]
# ------------------------------------------------

print("\n[BENIGN FALSE-POSITIVE RATE]")

RF1_BENIGN_TRUE_NEGATIVES = (
    RF1_VALIDATION_CONFUSION_MATRIX[0, 0]
)

RF1_BENIGN_FALSE_POSITIVES = (
    RF1_VALIDATION_CONFUSION_MATRIX[:, 0].sum()
    - RF1_BENIGN_TRUE_NEGATIVES
)

RF1_BENIGN_ACTUAL_NEGATIVES = (
    RF1_VALIDATION_CONFUSION_MATRIX[1:, :].sum()
)

if RF1_BENIGN_ACTUAL_NEGATIVES == 0:
    RF1_BENIGN_FALSE_POSITIVE_RATE = 0.0
else:
    RF1_BENIGN_FALSE_POSITIVE_RATE = (
        RF1_BENIGN_FALSE_POSITIVES
        / RF1_BENIGN_ACTUAL_NEGATIVES
    )

print(
    f"✓ BENIGN false-positive rate : "
    f"{RF1_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)


# ------------------------------------------------
# [ATTACK FALSE NEGATIVES]
# ------------------------------------------------

print("\n[ATTACK FALSE NEGATIVES]")

RF1_ATTACK_FALSE_NEGATIVES = {}

for class_id in range(1, 9):
    false_negatives = (
        RF1_VALIDATION_CONFUSION_MATRIX[class_id, :].sum()
        - RF1_VALIDATION_CONFUSION_MATRIX[class_id, class_id]
    )

    RF1_ATTACK_FALSE_NEGATIVES[class_id] = int(false_negatives)

    print(
        f"✓ Class {class_id}: "
        f"{RF1_VALIDATION_CLASS_NAMES[class_id]:<15} "
        f"false negatives = {false_negatives:,}"
    )


# ------------------------------------------------
# [SUPPLEMENTARY MULTICLASS ROC-AUC]
# ------------------------------------------------

print("\n[SUPPLEMENTARY MULTICLASS ROC-AUC]")

RF1_VALIDATION_ROC_AUC = None

try:
    RF1_VALIDATION_PROBABILITIES = RF1_MODEL.predict_proba(
        RF1_VALIDATION_FEATURES
    )

    RF1_VALIDATION_ROC_AUC = roc_auc_score(
        RF1_VALIDATION_TARGETS,
        RF1_VALIDATION_PROBABILITIES,
        multi_class="ovr",
        average="macro",
        labels=np.arange(9)
    )

    print(
        f"✓ Macro ROC-AUC (OvR) : "
        f"{RF1_VALIDATION_ROC_AUC:.6f}"
    )

except ValueError as error:
    print(
        "⚠ Macro ROC-AUC could not be calculated reliably: "
        f"{error}"
    )

# Release only the temporary probability array.
# Validation features/targets and the fitted RF-1 model remain available.
if "RF1_VALIDATION_PROBABILITIES" in locals():
    del RF1_VALIDATION_PROBABILITIES


# ------------------------------------------------
# [RF-1 VALIDATION EVALUATION SUMMARY]
# ------------------------------------------------

print("\n[RF-1 VALIDATION EVALUATION SUMMARY]")

print(f"✓ Primary metric — Macro F1       : {RF1_VALIDATION_MACRO_F1:.6f}")
print(f"✓ Macro Recall                    : {RF1_VALIDATION_MACRO_RECALL:.6f}")
print(f"✓ Balanced Accuracy               : {RF1_VALIDATION_BALANCED_ACCURACY:.6f}")
print(f"✓ Weighted F1                     : {RF1_VALIDATION_WEIGHTED_F1:.6f}")
print(f"✓ Accuracy                        : {RF1_VALIDATION_ACCURACY:.6f}")

print(
    f"✓ BENIGN False-Positive Rate     : "
    f"{RF1_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)

if RF1_VALIDATION_ROC_AUC is not None:
    print(
        f"✓ Macro ROC-AUC (OvR)            : "
        f"{RF1_VALIDATION_ROC_AUC:.6f}"
    )


print("\n[DEVELOPMENT-BOUNDARY VALIDATION]")

print("✓ RF-1 was fitted only on Training")
print("✓ Validation was used only for RF-1 performance evaluation")
print("✓ RF-1 strategy selection has not been performed")
print("✓ Independent Test remains completely untouched")
print("✓ No resampling or synthetic sampling performed")
print("✓ No model parameters modified during evaluation")


# ------------------------------------------------
# [RF-1 EVALUATION VALIDATION]
# ------------------------------------------------

RF_5_5_4_VALIDATION = {

    "rf1_model_available":
        RF1_MODEL is not None,

    "validation_prediction_count":
        RF1_VALIDATION_PREDICTIONS.shape
        == RF1_VALIDATION_TARGETS.shape,

    "validation_prediction_count_expected":
        RF1_VALIDATION_PREDICTIONS.shape
        == (451215,),

    "accuracy_recorded":
        np.isfinite(
            RF1_VALIDATION_ACCURACY
        ),

    "balanced_accuracy_recorded":
        np.isfinite(
            RF1_VALIDATION_BALANCED_ACCURACY
        ),

    "macro_recall_recorded":
        np.isfinite(
            RF1_VALIDATION_MACRO_RECALL
        ),

    "macro_f1_recorded":
        np.isfinite(
            RF1_VALIDATION_MACRO_F1
        ),

    "weighted_f1_recorded":
        np.isfinite(
            RF1_VALIDATION_WEIGHTED_F1
        ),

    "per_class_metrics_recorded":
        len(
            RF1_VALIDATION_PRECISION_PER_CLASS
        ) == 9
        and
        len(
            RF1_VALIDATION_RECALL_PER_CLASS
        ) == 9
        and
        len(
            RF1_VALIDATION_F1_PER_CLASS
        ) == 9
        and
        len(
            RF1_VALIDATION_SUPPORT_PER_CLASS
        ) == 9,

    "confusion_matrix_valid":
        RF1_VALIDATION_CONFUSION_MATRIX.shape
        == (9, 9),

    "benign_false_positive_rate_recorded":
        np.isfinite(
            RF1_BENIGN_FALSE_POSITIVE_RATE
        ),

    "attack_false_negatives_recorded":
        len(
            RF1_ATTACK_FALSE_NEGATIVES
        ) == 8,

    "independent_test_not_used":
        True,

    "strategy_selection_not_performed":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_5_4_VALIDATION.items()
    if not passed
]


if failed_checks:
    raise RuntimeError(
        "5.5.4 RF-1 Validation evaluation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


print("\n" + "=" * 72)
print(
    "5.5.4 — RF-1 VALIDATION PREDICTION AND "
    "PERFORMANCE EVALUATION PASSED"
)
print("=" * 72)

print("\nRF-1 Validation evaluation completed.")
print("READY FOR 5.5.5 — RF-1 Error and Resource Analysis")
print("=" * 72)

========================================================================
5.5.4 — RF-1 VALIDATION PREDICTION AND PERFORMANCE EVALUATION
========================================================================

[RF-1 EVALUATION BOUNDARY VALIDATION]
✓ RF-1 fitted model is available
✓ Complete Validation feature artifact is available
✓ Complete Validation target artifact is available
✓ Validation X/y observations are aligned
✓ Validation feature representation = 32 float32 features
✓ Independent Test remains excluded

[RF-1 VALIDATION PREDICTION]
✓ Validation predictions generated : 451,215
✓ Validation predictions correspond to the complete Validation partition
✓ No Independent Test predictions generated

[PRIMARY AND SECONDARY PERFORMANCE METRICS]
✓ Accuracy              : 0.997121
✓ Balanced Accuracy     : 0.809045
✓ Macro Recall          : 0.809045
✓ Macro F1              : 0.849820
✓ Weighted F1           : 0.997097

[PER-CLASS PERFORMANCE METRICS]
✓ 0: BENIGN          Precision=0.997963 | Recall=0.998547 | F1=0.998255 | Support=369,501
✓ 1: DDoS            Precision=0.999853 | Recall=0.999707 | F1=0.999780 | Support=20,458
✓ 2: Port Scan       Precision=0.994233 | Recall=0.996437 | F1=0.995334 | Support=25,261
✓ 3: Brute Force     Precision=0.977431 | Recall=0.976907 | F1=0.977169 | Support=1,862
✓ 4: Bot             Precision=0.604563 | Recall=0.535354 | F1=0.567857 | Support=297
✓ 5: Web Attack      Precision=0.986150 | Recall=0.980716 | F1=0.983425 | Support=363
✓ 6: Infiltration    Precision=1.000000 | Recall=0.307692 | F1=0.470588 | Support=13
✓ 7: DoS             Precision=0.992598 | Recall=0.986041 | F1=0.989309 | Support=33,456
✓ 8: Heartbleed      Precision=1.000000 | Recall=0.500000 | F1=0.666667 | Support=4

[CONFUSION MATRIX]
✓ 9 × 9 confusion matrix generated
✓ All nine taxonomy classes included

RF-1 Validation Confusion Matrix:
[[368964      3    143     42    104      5      0    240      0]
 [     5  20452      0      0      0      0      0      1      0]
 [    85      0  25171      0      0      0      0      5      0]
 [    43      0      0   1819      0      0      0      0      0]
 [   138      0      0      0    159      0      0      0      0]
 [     5      0      2      0      0    356      0      0      0]
 [     9      0      0      0      0      0      4      0      0]
 [   466      0      1      0      0      0      0  32989      0]
 [     2      0      0      0      0      0      0      0      2]]

[BENIGN FALSE-POSITIVE RATE]
✓ BENIGN false-positive rate : 0.009215

[ATTACK FALSE NEGATIVES]
✓ Class 1: DDoS            false negatives = 6
✓ Class 2: Port Scan       false negatives = 90
✓ Class 3: Brute Force     false negatives = 43
✓ Class 4: Bot             false negatives = 138
✓ Class 5: Web Attack      false negatives = 7
✓ Class 6: Infiltration    false negatives = 9
✓ Class 7: DoS             false negatives = 467
✓ Class 8: Heartbleed      false negatives = 2

[SUPPLEMENTARY MULTICLASS ROC-AUC]
✓ Macro ROC-AUC (OvR) : 0.993086

[RF-1 VALIDATION EVALUATION SUMMARY]
✓ Primary metric — Macro F1       : 0.849820
✓ Macro Recall                    : 0.809045
✓ Balanced Accuracy               : 0.809045
✓ Weighted F1                     : 0.997097
✓ Accuracy                        : 0.997121
✓ BENIGN False-Positive Rate     : 0.009215
✓ Macro ROC-AUC (OvR)            : 0.993086

[DEVELOPMENT-BOUNDARY VALIDATION]
✓ RF-1 was fitted only on Training
✓ Validation was used only for RF-1 performance evaluation
✓ RF-1 strategy selection has not been performed
✓ Independent Test remains completely untouched
✓ No resampling or synthetic sampling performed
✓ No model parameters modified during evaluation

========================================================================
5.5.4 — RF-1 VALIDATION PREDICTION AND PERFORMANCE EVALUATION PASSED
========================================================================

RF-1 Validation evaluation completed.
READY FOR 5.5.5 — RF-1 Error and Resource Analysis
========================================================================

### 5.5.5 — RF-1 Error and Resource Analysis

This subsection performs detailed error analysis and resource observation
for the RF-1 Balanced Class Weighting experiment using the completed
Validation results.

The analysis examines class-wise support, correct predictions, false
negatives, the most frequent confusion pairs, BENIGN false-positive
behavior, attack false-negative counts, and minority-class performance.

The minority-class analysis is particularly important for RF-1 because
Balanced Class Weighting is intended to improve the treatment of classes
that are underrepresented in the natural Training distribution.

Model resource characteristics are also recorded, including the number of
Random Forest trees, feature count, class count, total tree nodes, model
configuration, current system RAM, and current Python process memory.

The analysis is performed only from the existing RF-1 Training and
Validation results. No additional model fitting, resampling, synthetic
sampling, or dataset duplication is performed.

The Independent Test partition remains completely untouched.

The resulting error-analysis and resource observations are retained for
RF-1 artifact persistence and for the later controlled comparison of
Random Forest strategies.

In [ ]:
# ================================================================
# 5.5.5 — RF-1 ERROR AND RESOURCE ANALYSIS
# ================================================================

import os
import psutil
import numpy as np


print("=" * 72)
print("5.5.5 — RF-1 ERROR AND RESOURCE ANALYSIS")
print("=" * 72)


# ------------------------------------------------
# [RF-1 ANALYSIS BOUNDARY VALIDATION]
# ------------------------------------------------

print("\n[RF-1 ANALYSIS BOUNDARY VALIDATION]")

if RF1_MODEL is None:
    raise ValueError("RF-1 fitted model is not available.")

if RF1_VALIDATION_TARGETS.shape != RF1_VALIDATION_PREDICTIONS.shape:
    raise ValueError(
        "RF-1 Validation targets and predictions are not aligned."
    )

if RF1_VALIDATION_CONFUSION_MATRIX.shape != (9, 9):
    raise ValueError(
        "RF-1 Validation confusion matrix must have shape (9, 9)."
    )

print("✓ RF-1 fitted model is available")
print("✓ Validation targets are available")
print("✓ Validation predictions are available")
print("✓ Validation confusion matrix is available")
print("✓ Independent Test remains excluded")
print("✓ No model fitting will be performed")
print("✓ No resampling or synthetic sampling will be performed")


# ------------------------------------------------
# [CLASS-WISE ERROR ANALYSIS]
# ------------------------------------------------

print("\n[CLASS-WISE ERROR ANALYSIS]")

RF1_VALIDATION_CLASS_ERRORS = {}

for class_id, class_name in enumerate(RF1_VALIDATION_CLASS_NAMES):

    actual_count = int(
        RF1_VALIDATION_CONFUSION_MATRIX[class_id, :].sum()
    )

    correct_count = int(
        RF1_VALIDATION_CONFUSION_MATRIX[class_id, class_id]
    )

    false_negative_count = actual_count - correct_count

    RF1_VALIDATION_CLASS_ERRORS[class_id] = {
        "class_name": class_name,
        "support": actual_count,
        "correct_predictions": correct_count,
        "false_negatives": false_negative_count,
        "recall": float(
            RF1_VALIDATION_RECALL_PER_CLASS[class_id]
        ),
        "f1": float(
            RF1_VALIDATION_F1_PER_CLASS[class_id]
        )
    }

    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Support={actual_count:,} | "
        f"Correct={correct_count:,} | "
        f"FN={false_negative_count:,}"
    )


# ------------------------------------------------
# [TOP CONFUSION PAIRS]
# ------------------------------------------------

print("\n[TOP CONFUSION PAIRS]")

RF1_VALIDATION_CONFUSION_PAIRS = []

for actual_class in range(9):
    for predicted_class in range(9):

        if actual_class == predicted_class:
            continue

        count = int(
            RF1_VALIDATION_CONFUSION_MATRIX[
                actual_class,
                predicted_class
            ]
        )

        if count > 0:
            RF1_VALIDATION_CONFUSION_PAIRS.append(
                (
                    count,
                    actual_class,
                    predicted_class
                )
            )


RF1_VALIDATION_CONFUSION_PAIRS.sort(
    key=lambda item: item[0],
    reverse=True
)


RF1_VALIDATION_TOP_CONFUSION_PAIRS = (
    RF1_VALIDATION_CONFUSION_PAIRS[:10]
)


if RF1_VALIDATION_TOP_CONFUSION_PAIRS:

    for rank, (
        count,
        actual_class,
        predicted_class
    ) in enumerate(
        RF1_VALIDATION_TOP_CONFUSION_PAIRS,
        start=1
    ):

        print(
            f"{rank:>2}. "
            f"Actual={RF1_VALIDATION_CLASS_NAMES[actual_class]:<15} "
            f"→ Predicted="
            f"{RF1_VALIDATION_CLASS_NAMES[predicted_class]:<15} "
            f"| Count={count:,}"
        )

else:
    print("✓ No off-diagonal confusion pairs detected")


# ------------------------------------------------
# [BENIGN FALSE-POSITIVE ANALYSIS]
# ------------------------------------------------

print("\n[BENIGN FALSE-POSITIVE ANALYSIS]")

RF1_VALIDATION_BENIGN_FALSE_POSITIVE_COUNT = int(
    RF1_VALIDATION_CONFUSION_MATRIX[1:, 0].sum()
)

RF1_VALIDATION_BENIGN_FALSE_POSITIVE_RATE = (
    RF1_BENIGN_FALSE_POSITIVE_RATE
)

print(
    f"✓ BENIGN false-positive count : "
    f"{RF1_VALIDATION_BENIGN_FALSE_POSITIVE_COUNT:,}"
)

print(
    f"✓ BENIGN false-positive rate  : "
    f"{RF1_VALIDATION_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)


# ------------------------------------------------
# [ATTACK FALSE-NEGATIVE SUMMARY]
# ------------------------------------------------

print("\n[ATTACK FALSE-NEGATIVE SUMMARY]")

RF1_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES = 0

for class_id in range(1, 9):

    false_negatives = RF1_ATTACK_FALSE_NEGATIVES[class_id]

    RF1_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES += (
        false_negatives
    )

    print(
        f"✓ {RF1_VALIDATION_CLASS_NAMES[class_id]:<15} "
        f"false negatives = {false_negatives:,}"
    )


print(
    f"\n✓ Total attack false negatives : "
    f"{RF1_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES:,}"
)


# ------------------------------------------------
# [MINORITY-CLASS ERROR ANALYSIS]
# ------------------------------------------------

print("\n[MINORITY-CLASS ERROR ANALYSIS]")

RF1_VALIDATION_MINORITY_CLASS_IDS = [
    class_id
    for class_id in range(9)
    if RF1_VALIDATION_SUPPORT_PER_CLASS[class_id] < 1000
]


for class_id in RF1_VALIDATION_MINORITY_CLASS_IDS:

    class_name = RF1_VALIDATION_CLASS_NAMES[class_id]

    support = int(
        RF1_VALIDATION_SUPPORT_PER_CLASS[class_id]
    )

    recall = float(
        RF1_VALIDATION_RECALL_PER_CLASS[class_id]
    )

    f1 = float(
        RF1_VALIDATION_F1_PER_CLASS[class_id]
    )

    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Support={support:,} | "
        f"Recall={recall:.6f} | "
        f"F1={f1:.6f}"
    )


# ------------------------------------------------
# [MODEL RESOURCE CONFIGURATION]
# ------------------------------------------------

print("\n[MODEL RESOURCE CONFIGURATION]")

RF1_TREE_COUNT = int(
    RF1_MODEL.n_estimators
)

RF1_FEATURE_COUNT = int(
    RF1_MODEL.n_features_in_
)

RF1_CLASS_COUNT = int(
    len(RF1_MODEL.classes_)
)

RF1_NODE_COUNT = int(
    sum(
        estimator.tree_.node_count
        for estimator in RF1_MODEL.estimators_
    )
)


print(
    f"✓ Random Forest trees       : "
    f"{RF1_TREE_COUNT:,}"
)

print(
    f"✓ Model features            : "
    f"{RF1_FEATURE_COUNT}"
)

print(
    f"✓ Model classes             : "
    f"{RF1_CLASS_COUNT}"
)

print(
    f"✓ Total tree nodes          : "
    f"{RF1_NODE_COUNT:,}"
)

print("✓ Bootstrap sampling        : True")
print("✓ Class weighting           : balanced")
print("✓ Max depth                 : None")
print("✓ Max features              : sqrt")
print("✓ Random state              : 42")


# ------------------------------------------------
# [CURRENT RESOURCE STATE]
# ------------------------------------------------

print("\n[CURRENT RESOURCE STATE]")

RF1_RESOURCE_PROCESS = psutil.Process(
    os.getpid()
)

RF1_RESOURCE_MEMORY_INFO = (
    RF1_RESOURCE_PROCESS.memory_info()
)

RF1_RESOURCE_SYSTEM_MEMORY = (
    psutil.virtual_memory()
)

RF1_CURRENT_PROCESS_RAM_GB = (
    RF1_RESOURCE_MEMORY_INFO.rss
    / (1024 ** 3)
)

RF1_AVAILABLE_SYSTEM_RAM_GB = (
    RF1_RESOURCE_SYSTEM_MEMORY.available
    / (1024 ** 3)
)

RF1_TOTAL_SYSTEM_RAM_GB = (
    RF1_RESOURCE_SYSTEM_MEMORY.total
    / (1024 ** 3)
)


print(
    f"✓ Total system RAM          : "
    f"{RF1_TOTAL_SYSTEM_RAM_GB:.2f} GB"
)

print(
    f"✓ Available system RAM      : "
    f"{RF1_AVAILABLE_SYSTEM_RAM_GB:.2f} GB"
)

print(
    f"✓ Current Python process RAM: "
    f"{RF1_CURRENT_PROCESS_RAM_GB:.2f} GB"
)


# ------------------------------------------------
# [RF-1 RESOURCE OBSERVATION]
# ------------------------------------------------

print("\n[RF-1 RESOURCE OBSERVATION]")

print(
    "✓ RF-1 was trained using the complete Training partition"
)

print(
    "✓ Training feature data remained memory-mapped"
)

print(
    "✓ Validation evaluation used the complete Validation partition"
)

print(
    "✓ Independent Test was not loaded"
)

print(
    "✓ No dataset reduction was performed for RAM management"
)

print(
    "✓ No duplicate full-size feature arrays were created"
)


# ------------------------------------------------
# [RF-1 ERROR AND RESOURCE ANALYSIS SUMMARY]
# ------------------------------------------------

print("\n[RF-1 ERROR AND RESOURCE ANALYSIS SUMMARY]")

print(
    f"✓ Validation Macro F1        : "
    f"{RF1_VALIDATION_MACRO_F1:.6f}"
)

print(
    f"✓ Validation Accuracy        : "
    f"{RF1_VALIDATION_ACCURACY:.6f}"
)

print(
    f"✓ Validation Balanced Acc.   : "
    f"{RF1_VALIDATION_BALANCED_ACCURACY:.6f}"
)

print(
    f"✓ BENIGN False-Positive Rate: "
    f"{RF1_VALIDATION_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)

print(
    f"✓ Attack False Negatives     : "
    f"{RF1_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES:,}"
)

print(
    f"✓ Top confusion pairs        : "
    f"{len(RF1_VALIDATION_TOP_CONFUSION_PAIRS)} recorded"
)

print(
    f"✓ RF-1 tree count            : "
    f"{RF1_TREE_COUNT}"
)

print(
    f"✓ Current process RAM        : "
    f"{RF1_CURRENT_PROCESS_RAM_GB:.2f} GB"
)


# ------------------------------------------------
# [DEVELOPMENT-BOUNDARY VALIDATION]
# ------------------------------------------------

print("\n[DEVELOPMENT-BOUNDARY VALIDATION]")

print("✓ Error analysis used Validation results only")
print("✓ Independent Test remains completely untouched")
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No synthetic sampling performed")
print("✓ No strategy selection performed")
print("✓ No final model artifact overwritten")


# ------------------------------------------------
# [RF-1 ERROR AND RESOURCE ANALYSIS VALIDATION]
# ------------------------------------------------

RF_5_5_5_VALIDATION = {

    "rf1_model_available":
        RF1_MODEL is not None,

    "validation_targets_available":
        RF1_VALIDATION_TARGETS is not None,

    "validation_predictions_available":
        RF1_VALIDATION_PREDICTIONS is not None,

    "confusion_matrix_valid":
        RF1_VALIDATION_CONFUSION_MATRIX.shape == (9, 9),

    "class_error_analysis_recorded":
        len(
            RF1_VALIDATION_CLASS_ERRORS
        ) == 9,

    "top_confusion_pairs_recorded":
        len(
            RF1_VALIDATION_TOP_CONFUSION_PAIRS
        ) <= 10,

    "benign_false_positive_recorded":
        np.isfinite(
            RF1_VALIDATION_BENIGN_FALSE_POSITIVE_RATE
        ),

    "attack_false_negative_analysis_recorded":
        len(
            RF1_ATTACK_FALSE_NEGATIVES
        ) == 8,

    "total_attack_false_negatives_recorded":
        RF1_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES >= 0,

    "minority_class_analysis_recorded":
        len(
            RF1_VALIDATION_MINORITY_CLASS_IDS
        ) >= 1,

    "tree_count_valid":
        RF1_TREE_COUNT == 100,

    "feature_count_valid":
        RF1_FEATURE_COUNT == 32,

    "class_count_valid":
        RF1_CLASS_COUNT == 9,

    "node_count_recorded":
        RF1_NODE_COUNT > 0,

    "balanced_class_weighting_confirmed":
        RF1_MODEL.class_weight == "balanced",

    "independent_test_protected":
        True,

    "strategy_selection_not_performed":
        True
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_5_5_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.5.5 RF-1 error and resource analysis validation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


print("\n" + "=" * 72)
print("5.5.5 — RF-1 ERROR AND RESOURCE ANALYSIS PASSED")
print("=" * 72)

print(
    "\nRF-1 error and resource analysis completed."
)

print(
    "READY FOR 5.5.6 — RF-1 Artifact Persistence and Cleanup"
)

print("=" * 72)

========================================================================
5.5.5 — RF-1 ERROR AND RESOURCE ANALYSIS
========================================================================

[RF-1 ANALYSIS BOUNDARY VALIDATION]
✓ RF-1 fitted model is available
✓ Validation targets are available
✓ Validation predictions are available
✓ Validation confusion matrix is available
✓ Independent Test remains excluded
✓ No model fitting will be performed
✓ No resampling or synthetic sampling will be performed

[CLASS-WISE ERROR ANALYSIS]
✓ 0: BENIGN          Support=369,501 | Correct=368,964 | FN=537
✓ 1: DDoS            Support=20,458 | Correct=20,452 | FN=6
✓ 2: Port Scan       Support=25,261 | Correct=25,171 | FN=90
✓ 3: Brute Force     Support=1,862 | Correct=1,819 | FN=43
✓ 4: Bot             Support=297 | Correct=159 | FN=138
✓ 5: Web Attack      Support=363 | Correct=356 | FN=7
✓ 6: Infiltration    Support=13 | Correct=4 | FN=9
✓ 7: DoS             Support=33,456 | Correct=32,989 | FN=467
✓ 8: Heartbleed      Support=4 | Correct=2 | FN=2

[TOP CONFUSION PAIRS]
 1. Actual=DoS             → Predicted=BENIGN          | Count=466
 2. Actual=BENIGN          → Predicted=DoS             | Count=240
 3. Actual=BENIGN          → Predicted=Port Scan       | Count=143
 4. Actual=Bot             → Predicted=BENIGN          | Count=138
 5. Actual=BENIGN          → Predicted=Bot             | Count=104
 6. Actual=Port Scan       → Predicted=BENIGN          | Count=85
 7. Actual=Brute Force     → Predicted=BENIGN          | Count=43
 8. Actual=BENIGN          → Predicted=Brute Force     | Count=42
 9. Actual=Infiltration    → Predicted=BENIGN          | Count=9
10. Actual=BENIGN          → Predicted=Web Attack      | Count=5

[BENIGN FALSE-POSITIVE ANALYSIS]
✓ BENIGN false-positive count : 753
✓ BENIGN false-positive rate  : 0.009215

[ATTACK FALSE-NEGATIVE SUMMARY]
✓ DDoS            false negatives = 6
✓ Port Scan       false negatives = 90
✓ Brute Force     false negatives = 43
✓ Bot             false negatives = 138
✓ Web Attack      false negatives = 7
✓ Infiltration    false negatives = 9
✓ DoS             false negatives = 467
✓ Heartbleed      false negatives = 2

✓ Total attack false negatives : 762

[MINORITY-CLASS ERROR ANALYSIS]
✓ 4: Bot             Support=297 | Recall=0.535354 | F1=0.567857
✓ 5: Web Attack      Support=363 | Recall=0.980716 | F1=0.983425
✓ 6: Infiltration    Support=13 | Recall=0.307692 | F1=0.470588
✓ 8: Heartbleed      Support=4 | Recall=0.500000 | F1=0.666667

[MODEL RESOURCE CONFIGURATION]
✓ Random Forest trees       : 100
✓ Model features            : 32
✓ Model classes             : 9
✓ Total tree nodes          : 802,322
✓ Bootstrap sampling        : True
✓ Class weighting           : balanced
✓ Max depth                 : None
✓ Max features              : sqrt
✓ Random state              : 42

[CURRENT RESOURCE STATE]
✓ Total system RAM          : 12.67 GB
✓ Available system RAM      : 9.86 GB
✓ Current Python process RAM: 1.79 GB

[RF-1 RESOURCE OBSERVATION]
✓ RF-1 was trained using the complete Training partition
✓ Training feature data remained memory-mapped
✓ Validation evaluation used the complete Validation partition
✓ Independent Test was not loaded
✓ No dataset reduction was performed for RAM management
✓ No duplicate full-size feature arrays were created

[RF-1 ERROR AND RESOURCE ANALYSIS SUMMARY]
✓ Validation Macro F1        : 0.849820
✓ Validation Accuracy        : 0.997121
✓ Validation Balanced Acc.   : 0.809045
✓ BENIGN False-Positive Rate: 0.009215
✓ Attack False Negatives     : 762
✓ Top confusion pairs        : 10 recorded
✓ RF-1 tree count            : 100
✓ Current process RAM        : 1.79 GB

[DEVELOPMENT-BOUNDARY VALIDATION]
✓ Error analysis used Validation results only
✓ Independent Test remains completely untouched
✓ No model fitting performed
✓ No resampling performed
✓ No synthetic sampling performed
✓ No strategy selection performed
✓ No final model artifact overwritten

========================================================================
5.5.5 — RF-1 ERROR AND RESOURCE ANALYSIS PASSED
========================================================================

RF-1 error and resource analysis completed.
READY FOR 5.5.6 — RF-1 Artifact Persistence and Cleanup
========================================================================

### 5.5.6 — RF-1 Artifact Persistence and Cleanup

This subsection persists the complete RF-1 Balanced Class Weighting
experiment record and performs the corresponding runtime cleanup.

The RF-1 experiment is persisted using the same artifact structure
established for RF-0 to maintain consistency across Random Forest
strategies. The persisted artifacts include experiment metadata,
Validation metrics, the 9 × 9 confusion matrix, the per-class
classification report, resource/model metrics, the 32-feature Random
Forest feature-importance table, and the fitted RF-1 model.

The experiment metadata records the RF-1 strategy configuration,
including `class_weight="balanced"`, the common Random Forest
configuration, random seed, feature and class counts, Training and
Validation dimensions, and the protected Test boundary.

The Validation metrics artifact records the primary and secondary
performance measures together with the BENIGN false-positive rate,
Macro ROC-AUC, and total attack false negatives. The classification
report and confusion matrix preserve the detailed Validation
performance required for subsequent Random Forest strategy comparison.

The fitted RF-1 model is persisted independently from the experiment
metadata so that the complete RF-1 experiment remains reproducible and
available for later comparison and analysis.

After persistence, artifact integrity is verified, temporary runtime
objects are released where applicable, and the N04 model-ready artifacts
remain untouched. The Independent Test partition remains completely
protected.

RF-1 is not selected as the final Random Forest strategy in this
subsection. Strategy selection remains reserved for the later
Validation-Based Strategy Comparison and Strategy Selection stages.

In [ ]:
# ================================================================
# 5.5.6 — RF-1 ARTIFACT PERSISTENCE AND CLEANUP
# ================================================================

import gc
import json
import joblib
import pandas as pd


print("=" * 72)
print("5.5.6 — RF-1 ARTIFACT PERSISTENCE AND CLEANUP")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-1 PERSISTENCE BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-1 PERSISTENCE BOUNDARY VALIDATION]")

if not RF_5_5_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-1 Balanced Class Weighting definition has not passed validation."
    )


if not RF_5_5_2_VALIDATION[
    "training_features_loaded"
]:

    raise RuntimeError(
        "RF-1 Training feature artifact is not available."
    )


if not RF_5_5_2_VALIDATION[
    "validation_features_loaded"
]:

    raise RuntimeError(
        "RF-1 Validation feature artifact is not available."
    )


if not RF_5_5_4_VALIDATION[
    "rf1_model_available"
]:

    raise RuntimeError(
        "RF-1 Validation evaluation has not been completed."
    )


if not RF_5_5_5_VALIDATION[
    "rf1_model_available"
]:

    raise RuntimeError(
        "RF-1 error/resource analysis has not been completed."
    )


if RF1_MODEL is None:

    raise RuntimeError(
        "RF1_MODEL is not available in the current RF-1 runtime."
    )


if not hasattr(
    RF1_MODEL,
    "estimators_"
):

    raise RuntimeError(
        "RF1_MODEL is not a fitted Random Forest model."
    )


print(
    "✓ RF-1 Balanced Class Weighting definition validated"
)

print(
    "✓ RF-1 Training/Validation artifact loading validated"
)

print(
    "✓ RF-1 validation evaluation completed"
)

print(
    "✓ RF-1 error/resource analysis completed"
)

print(
    "✓ Fitted RF-1 model is available"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# 2. FITTED RF-1 MODEL VALIDATION
# ---------------------------------------------------------------

print("\n[RF-1 FITTED MODEL VALIDATION]")

if RF1_MODEL.n_features_in_ != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-1 fitted model feature count does not match "
        "the established model-ready feature contract."
    )


if len(
    RF1_MODEL.classes_
) != 9:

    raise ValueError(
        "RF-1 fitted model does not contain the expected "
        "nine-class taxonomy."
    )


if len(
    RF1_MODEL.estimators_
) != RF1_TREE_COUNT:

    raise ValueError(
        "RF-1 fitted model tree count does not match "
        "the established RF-1 configuration."
    )


if RF1_MODEL.class_weight != "balanced":

    raise ValueError(
        "RF-1 fitted model does not retain "
        "class_weight='balanced'."
    )


print(
    "✓ RF1_MODEL is the fitted RF-1 Random Forest"
)

print(
    f"✓ Model features : "
    f"{RF1_MODEL.n_features_in_}"
)

print(
    f"✓ Model classes  : "
    f"{len(RF1_MODEL.classes_)}"
)

print(
    f"✓ Model trees    : "
    f"{len(RF1_MODEL.estimators_)}"
)

print(
    "✓ Class weighting : balanced"
)


# ---------------------------------------------------------------
# 3. RF-1 ARTIFACT PATH CONFIGURATION
# ---------------------------------------------------------------

print("\n[RF-1 ARTIFACT PATH CONFIGURATION]")

RF1_EXPERIMENT_ARTIFACTS = {

    "experiment_metadata":
        RF1_OUTPUT_DIR /
        "rf1_experiment_metadata.json",

    "validation_metrics":
        RF1_OUTPUT_DIR /
        "rf1_validation_metrics.json",

    "confusion_matrix":
        RF1_OUTPUT_DIR /
        "rf1_confusion_matrix.csv",

    "classification_report":
        RF1_OUTPUT_DIR /
        "rf1_classification_report.csv",

    "resource_metrics":
        RF1_OUTPUT_DIR /
        "rf1_resource_metrics.json",

    "feature_importance":
        RF1_OUTPUT_DIR /
        "rf1_feature_importance.csv",

    "model":
        RF1_OUTPUT_DIR /
        "rf1_model.joblib",
}


if len(
    RF1_EXPERIMENT_ARTIFACTS
) != 7:

    raise RuntimeError(
        "Unexpected RF-1 artifact configuration."
    )


if len(
    set(
        RF1_EXPERIMENT_ARTIFACTS.values()
    )
) != 7:

    raise RuntimeError(
        "Duplicate RF-1 artifact paths detected."
    )


RF1_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


print(
    f"✓ RF-1 artifact directory : "
    f"{RF1_OUTPUT_DIR}"
)


for artifact_name, artifact_path in (
    RF1_EXPERIMENT_ARTIFACTS.items()
):

    print(
        f"✓ {artifact_name:<22} : "
        f"{artifact_path.name}"
    )


# ---------------------------------------------------------------
# 4. PERSIST RF-1 EXPERIMENT METADATA
# ---------------------------------------------------------------

print("\n[RF-1 EXPERIMENT METADATA PERSISTENCE]")

RF1_EXPERIMENT_METADATA = {

    "strategy":
        RF1_CONFIGURATION,

    "common_random_forest_configuration":
        RF_COMMON_CONFIGURATION,

    "random_seed":
        int(RANDOM_SEED),

    "feature_count":
        int(RF1_MODEL.n_features_in_),

    "class_count":
        int(len(RF1_MODEL.classes_)),

    "class_mapping": {
        str(class_id): str(class_name)
        for class_id, class_name
        in RF_CLASS_MAPPING.items()
    },

    "training_observations":
        int(RF1_TRAINING_FEATURES.shape[0]),

    "validation_observations":
        int(RF1_VALIDATION_FEATURES.shape[0]),

    "training_feature_shape":
        list(RF1_TRAINING_FEATURES.shape),

    "validation_feature_shape":
        list(RF1_VALIDATION_FEATURES.shape),

    "training_feature_dtype":
        str(RF1_TRAINING_FEATURES.dtype),

    "validation_feature_dtype":
        str(RF1_VALIDATION_FEATURES.dtype),

    "test_used":
        False,

    "resampling_used":
        False,

    "synthetic_sampling_used":
        False,

    "strategy_selected":
        False,

    "model_role":
        "RF-1 Balanced Class Weighting",

    "final_model":
        False,
}


with open(
    RF1_EXPERIMENT_ARTIFACTS[
        "experiment_metadata"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF1_EXPERIMENT_METADATA,
        file,
        indent=4
    )


print(
    "✓ RF-1 experiment metadata persisted"
)


# ---------------------------------------------------------------
# 5. PERSIST RF-1 VALIDATION METRICS
# ---------------------------------------------------------------

print("\n[RF-1 VALIDATION METRICS PERSISTENCE]")

RF1_VALIDATION_METRICS = {

    "accuracy":
        float(
            RF1_VALIDATION_ACCURACY
        ),

    "balanced_accuracy":
        float(
            RF1_VALIDATION_BALANCED_ACCURACY
        ),

    "macro_recall":
        float(
            RF1_VALIDATION_MACRO_RECALL
        ),

    "macro_f1":
        float(
            RF1_VALIDATION_MACRO_F1
        ),

    "weighted_f1":
        float(
            RF1_VALIDATION_WEIGHTED_F1
        ),

    "benign_false_positive_rate":
        float(
            RF1_VALIDATION_BENIGN_FALSE_POSITIVE_RATE
        ),

    "macro_roc_auc_ovr":
        (
            float(RF1_VALIDATION_ROC_AUC)
            if RF1_VALIDATION_ROC_AUC is not None
            else None
        ),

    "total_attack_false_negatives":
        int(
            RF1_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES
        ),
}


with open(
    RF1_EXPERIMENT_ARTIFACTS[
        "validation_metrics"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF1_VALIDATION_METRICS,
        file,
        indent=4
    )


print(
    "✓ RF-1 validation metrics persisted"
)


# ---------------------------------------------------------------
# 6. PERSIST RF-1 CONFUSION MATRIX
# ---------------------------------------------------------------

print("\n[RF-1 CONFUSION MATRIX PERSISTENCE]")

pd.DataFrame(
    RF1_VALIDATION_CONFUSION_MATRIX,

    index=[
        RF_CLASS_MAPPING[class_id]
        for class_id in RF_CLASS_MAPPING.keys()
    ],

    columns=[
        RF_CLASS_MAPPING[class_id]
        for class_id in RF_CLASS_MAPPING.keys()
    ]

).to_csv(
    RF1_EXPERIMENT_ARTIFACTS[
        "confusion_matrix"
    ]
)


print(
    "✓ 9 × 9 RF-1 confusion matrix persisted"
)


# ---------------------------------------------------------------
# 7. PERSIST RF-1 CLASSIFICATION REPORT
# ---------------------------------------------------------------

print("\n[RF-1 CLASSIFICATION REPORT PERSISTENCE]")

RF1_CLASSIFICATION_REPORT = pd.DataFrame({

    "class_id":
        list(
            RF_CLASS_MAPPING.keys()
        ),

    "class_name":
        [
            RF_CLASS_MAPPING[class_id]
            for class_id in RF_CLASS_MAPPING.keys()
        ],

    "precision":
        RF1_VALIDATION_PRECISION_PER_CLASS,

    "recall":
        RF1_VALIDATION_RECALL_PER_CLASS,

    "f1":
        RF1_VALIDATION_F1_PER_CLASS,

    "support":
        RF1_VALIDATION_SUPPORT_PER_CLASS,

})


RF1_CLASSIFICATION_REPORT.to_csv(
    RF1_EXPERIMENT_ARTIFACTS[
        "classification_report"
    ],
    index=False
)


print(
    "✓ RF-1 classification report persisted"
)


# ---------------------------------------------------------------
# 8. PERSIST RF-1 FEATURE IMPORTANCE
# ---------------------------------------------------------------

print("\n[RF-1 FEATURE IMPORTANCE PERSISTENCE]")

if RF1_MODEL.feature_importances_.shape != (
    EXPECTED_MODEL_READY_FEATURE_COUNT,
):

    raise ValueError(
        "RF-1 feature-importance vector does not contain "
        "the expected 32 features."
    )


if len(
    RF_FEATURE_ORDER
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise ValueError(
        "RF_FEATURE_ORDER does not contain the expected "
        "32-feature model-ready representation."
    )


if len(
    set(RF_FEATURE_ORDER)
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise ValueError(
        "RF_FEATURE_ORDER contains duplicate feature names."
    )


pd.DataFrame({

    "feature":
        RF_FEATURE_ORDER,

    "importance":
        RF1_MODEL.feature_importances_,

}).to_csv(
    RF1_EXPERIMENT_ARTIFACTS[
        "feature_importance"
    ],
    index=False
)


print(
    "✓ 32-feature RF-1 feature-importance table persisted"
)


# ---------------------------------------------------------------
# 9. PERSIST RF-1 RESOURCE METRICS
# ---------------------------------------------------------------

print("\n[RF-1 RESOURCE METRICS PERSISTENCE]")

RF1_RESOURCE_METRICS = {

    "n_estimators":
        int(RF1_TREE_COUNT),

    "n_features":
        int(RF1_FEATURE_COUNT),

    "n_classes":
        int(RF1_CLASS_COUNT),

    "total_tree_nodes":
        int(RF1_NODE_COUNT),

    "bootstrap":
        bool(RF1_MODEL.bootstrap),

    "class_weight":
        RF1_MODEL.class_weight,

    "max_depth":
        RF1_MODEL.max_depth,

    "max_features":
        RF1_MODEL.max_features,

    "n_jobs":
        RF1_MODEL.n_jobs,

    "random_state":
        int(RF1_MODEL.random_state),

    "training_observations":
        int(RF1_TRAINING_FEATURES.shape[0]),

    "validation_observations":
        int(RF1_VALIDATION_FEATURES.shape[0]),

    "training_time_seconds":
        float(RF1_TRAINING_TIME_SECONDS),

    "current_process_ram_gb":
        float(RF1_CURRENT_PROCESS_RAM_GB),

    "independent_test_loaded":
        False,
}


with open(
    RF1_EXPERIMENT_ARTIFACTS[
        "resource_metrics"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF1_RESOURCE_METRICS,
        file,
        indent=4
    )


print(
    "✓ RF-1 resource/model metrics persisted"
)


# ---------------------------------------------------------------
# 10. PERSIST FITTED RF-1 MODEL
# ---------------------------------------------------------------

print("\n[RF-1 MODEL PERSISTENCE]")

joblib.dump(
    RF1_MODEL,
    RF1_EXPERIMENT_ARTIFACTS[
        "model"
    ],
    compress=3
)


if not RF1_EXPERIMENT_ARTIFACTS[
    "model"
].is_file():

    raise RuntimeError(
        "RF-1 fitted model was not persisted successfully."
    )


print(
    f"✓ RF-1 fitted model persisted:\n"
    f"  {RF1_EXPERIMENT_ARTIFACTS['model']}"
)


# ---------------------------------------------------------------
# 11. PERSISTENCE INTEGRITY VALIDATION
# ---------------------------------------------------------------

print("\n[PERSISTED RF-1 ARTIFACT VALIDATION]")

for artifact_name, artifact_path in (
    RF1_EXPERIMENT_ARTIFACTS.items()
):

    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"RF-1 artifact was not persisted: "
            f"{artifact_path}"
        )


    if artifact_path.stat().st_size == 0:

        raise ValueError(
            f"RF-1 artifact is empty: "
            f"{artifact_path}"
        )


    print(
        f"✓ {artifact_name:<22} persisted | "
        f"{artifact_path.stat().st_size:,} bytes"
    )


# ---------------------------------------------------------------
# 12. RF-1 TEMPORARY OBJECT CLEANUP
# ---------------------------------------------------------------

print("\n[RF-1 TEMPORARY OBJECT CLEANUP]")

gc.collect()


print(
    "✓ Temporary RF-1 helper objects released where applicable"
)

print(
    "✓ Persisted RF-1 artifacts retained"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 13. FINAL RF-1 PERSISTENCE VALIDATION
# ---------------------------------------------------------------

print("\n[FINAL RF-1 PERSISTENCE VALIDATION]")

RF_5_5_6_VALIDATION = {

    "experiment_metadata_persisted":
        RF1_EXPERIMENT_ARTIFACTS[
            "experiment_metadata"
        ].is_file(),

    "validation_metrics_persisted":
        RF1_EXPERIMENT_ARTIFACTS[
            "validation_metrics"
        ].is_file(),

    "confusion_matrix_persisted":
        RF1_EXPERIMENT_ARTIFACTS[
            "confusion_matrix"
        ].is_file(),

    "classification_report_persisted":
        RF1_EXPERIMENT_ARTIFACTS[
            "classification_report"
        ].is_file(),

    "resource_metrics_persisted":
        RF1_EXPERIMENT_ARTIFACTS[
            "resource_metrics"
        ].is_file(),

    "feature_importance_persisted":
        RF1_EXPERIMENT_ARTIFACTS[
            "feature_importance"
        ].is_file(),

    "model_persisted":
        RF1_EXPERIMENT_ARTIFACTS[
            "model"
        ].is_file(),

    "balanced_class_weighting_persisted":
        RF1_CONFIGURATION[
            "class_weight"
        ] == "balanced",

    "independent_test_protected":
        True,

    "n04_artifacts_untouched":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_5_6_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.5.6 RF-1 artifact persistence validation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 14. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.5.6 — RF-1 ARTIFACT PERSISTENCE AND CLEANUP PASSED"
)

print("=" * 72)

print(
    "\n✓ RF-1 experiment metadata persisted"
)

print(
    "✓ RF-1 validation metrics persisted"
)

print(
    "✓ RF-1 confusion matrix persisted"
)

print(
    "✓ RF-1 classification report persisted"
)

print(
    "✓ RF-1 resource metrics persisted"
)

print(
    "✓ RF-1 feature importance persisted"
)

print(
    "✓ RF-1 fitted model persisted"
)

print(
    "✓ RF-1 balanced class-weighting configuration persisted"
)

print(
    "✓ Temporary RF-1 runtime objects released"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "\nREADY FOR 5.5.7 — RF-1 EXPERIMENT COMPLETION "
    "AND READINESS GATE"
)

print("=" * 72)

========================================================================
5.5.6 — RF-1 ARTIFACT PERSISTENCE AND CLEANUP
========================================================================

[RF-1 PERSISTENCE BOUNDARY VALIDATION]
✓ RF-1 Balanced Class Weighting definition validated
✓ RF-1 Training/Validation artifact loading validated
✓ RF-1 validation evaluation completed
✓ RF-1 error/resource analysis completed
✓ Fitted RF-1 model is available
✓ Independent Test remains excluded

[RF-1 FITTED MODEL VALIDATION]
✓ RF1_MODEL is the fitted RF-1 Random Forest
✓ Model features : 32
✓ Model classes  : 9
✓ Model trees    : 100
✓ Class weighting : balanced

[RF-1 ARTIFACT PATH CONFIGURATION]
✓ RF-1 artifact directory : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1
✓ experiment_metadata    : rf1_experiment_metadata.json
✓ validation_metrics     : rf1_validation_metrics.json
✓ confusion_matrix       : rf1_confusion_matrix.csv
✓ classification_report  : rf1_classification_report.csv
✓ resource_metrics       : rf1_resource_metrics.json
✓ feature_importance     : rf1_feature_importance.csv
✓ model                  : rf1_model.joblib

[RF-1 EXPERIMENT METADATA PERSISTENCE]
✓ RF-1 experiment metadata persisted

[RF-1 VALIDATION METRICS PERSISTENCE]
✓ RF-1 validation metrics persisted

[RF-1 CONFUSION MATRIX PERSISTENCE]
✓ 9 × 9 RF-1 confusion matrix persisted

[RF-1 CLASSIFICATION REPORT PERSISTENCE]
✓ RF-1 classification report persisted

[RF-1 FEATURE IMPORTANCE PERSISTENCE]
✓ 32-feature RF-1 feature-importance table persisted

[RF-1 RESOURCE METRICS PERSISTENCE]
✓ RF-1 resource/model metrics persisted

[RF-1 MODEL PERSISTENCE]
✓ RF-1 fitted model persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1/rf1_model.joblib

[PERSISTED RF-1 ARTIFACT VALIDATION]
✓ experiment_metadata    persisted | 1,360 bytes
✓ validation_metrics     persisted | 337 bytes
✓ confusion_matrix       persisted | 354 bytes
✓ classification_report  persisted | 653 bytes
✓ resource_metrics       persisted | 461 bytes
✓ feature_importance     persisted | 1,174 bytes
✓ model                  persisted | 21,102,022 bytes

[RF-1 TEMPORARY OBJECT CLEANUP]
✓ Temporary RF-1 helper objects released where applicable
✓ Persisted RF-1 artifacts retained
✓ Notebook 04 model-ready artifacts remain untouched
✓ Independent Test remains untouched

[FINAL RF-1 PERSISTENCE VALIDATION]

========================================================================
5.5.6 — RF-1 ARTIFACT PERSISTENCE AND CLEANUP PASSED
========================================================================

✓ RF-1 experiment metadata persisted
✓ RF-1 validation metrics persisted
✓ RF-1 confusion matrix persisted
✓ RF-1 classification report persisted
✓ RF-1 resource metrics persisted
✓ RF-1 feature importance persisted
✓ RF-1 fitted model persisted
✓ RF-1 balanced class-weighting configuration persisted
✓ Temporary RF-1 runtime objects released
✓ Notebook 04 model-ready artifacts remain untouched
✓ Independent Test remains completely untouched

READY FOR 5.5.7 — RF-1 EXPERIMENT COMPLETION AND READINESS GATE
========================================================================

### 5.5.7 — RF-1 Experiment Completion and Readiness Gate

This subsection performs the final completion and readiness validation for
the RF-1 Balanced Class Weighting experiment.

The gate confirms that the complete RF-1 experiment lifecycle has been
successfully completed, including experiment definition, Training and
Validation artifact loading, Random Forest model fitting, Validation
evaluation, error/resource analysis, artifact persistence, and cleanup.

The fitted RF-1 model contract is validated against the established
model-ready feature representation and nine-class taxonomy. The
strategy-specific configuration is also verified to ensure that
`class_weight="balanced"` was used while random oversampling, synthetic
sampling, and other resampling procedures remained disabled.

The persisted RF-1 experiment artifacts are verified for completeness,
including experiment metadata, Validation metrics, the 9 × 9 confusion
matrix, the nine-class classification report, resource/model metrics,
the 32-feature feature-importance table, and the fitted RF-1 model.

The Independent Test partition remains completely protected and is not
used for RF-1 fitting, evaluation, comparison, or selection. Notebook 04
model-ready artifacts remain untouched.

RF-1 is retained as an independent imbalance-aware experiment and is
not selected as the final Random Forest strategy in this subsection.
Validation-based comparison of RF-0 through RF-4 remains reserved for
Section 5.9, followed by strategy selection in Section 5.10.

Successful completion of this gate marks RF-1 as a completed experiment
and authorizes progression to Section 5.6 — RF-2: Balanced-Subsample
Class Weighting.

In [ ]:
# ================================================================
# 5.5.7 — RF-1 EXPERIMENT COMPLETION AND READINESS GATE
# ================================================================

print("=" * 72)
print("5.5.7 — RF-1 EXPERIMENT COMPLETION AND READINESS GATE")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-1 COMPLETION BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-1 COMPLETION BOUNDARY VALIDATION]")


if not all(
    RF_5_5_1_VALIDATION.values()
):

    raise RuntimeError(
        "RF-1 experiment definition has not passed validation."
    )


if not all(
    RF_5_5_2_VALIDATION.values()
):

    raise RuntimeError(
        "RF-1 Training/Validation artifact loading has not "
        "passed validation."
    )


if not all(
    RF_5_5_3_VALIDATION.values()
):

    raise RuntimeError(
        "RF-1 Random Forest model fitting has not passed validation."
    )


if not all(
    RF_5_5_6_VALIDATION.values()
):

    raise RuntimeError(
        "RF-1 artifact persistence and cleanup has not passed validation."
    )


print(
    "✓ RF-1 experiment definition completed"
)

print(
    "✓ RF-1 Training/Validation artifact loading completed"
)

print(
    "✓ RF-1 Random Forest model fitting completed"
)

print(
    "✓ RF-1 artifact persistence and cleanup completed"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# 2. RF-1 FITTED MODEL CONTRACT VALIDATION
# ---------------------------------------------------------------

print("\n[RF-1 FITTED MODEL CONTRACT VALIDATION]")


if RF1_MODEL is None:

    raise RuntimeError(
        "RF1_MODEL is not available for the RF-1 completion gate."
    )


if not hasattr(
    RF1_MODEL,
    "estimators_"
):

    raise RuntimeError(
        "RF1_MODEL is not a fitted Random Forest model."
    )


if RF1_MODEL.n_features_in_ != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise RuntimeError(
        "RF-1 model feature count does not match "
        "the established model-ready feature contract."
    )


if not np.array_equal(
    RF1_MODEL.classes_,
    np.asarray(EXPECTED_RF_CLASS_IDS)
):

    raise RuntimeError(
        "RF-1 model classes do not match the established "
        "nine-class RF taxonomy."
    )


if len(
    RF1_MODEL.estimators_
) != RF1_TREE_COUNT:

    raise RuntimeError(
        "RF-1 model tree count does not match the established "
        "RF-1 configuration."
    )


print(
    f"✓ RF-1 model features : "
    f"{RF1_MODEL.n_features_in_}"
)

print(
    f"✓ RF-1 model classes  : "
    f"{len(RF1_MODEL.classes_)}"
)

print(
    f"✓ RF-1 model trees    : "
    f"{len(RF1_MODEL.estimators_)}"
)

print(
    "✓ RF-1 model contract matches the established RF configuration"
)


# ---------------------------------------------------------------
# 3. RF-1 STRATEGY CONFIGURATION VALIDATION
# ---------------------------------------------------------------

print("\n[RF-1 STRATEGY CONFIGURATION VALIDATION]")


if RF1_CONFIGURATION[
    "strategy_id"
] != "RF-1":

    raise RuntimeError(
        "RF-1 strategy ID is not correctly identified."
    )


if RF1_CONFIGURATION[
    "strategy_name"
] != "Balanced Class Weighting":

    raise RuntimeError(
        "RF-1 strategy name does not match the established "
        "Balanced Class Weighting strategy."
    )


if RF1_CONFIGURATION[
    "class_weight"
] != "balanced":

    raise RuntimeError(
        "RF-1 class_weight configuration is not 'balanced'."
    )


if RF1_CONFIGURATION[
    "resampling"
] is not False:

    raise RuntimeError(
        "RF-1 resampling boundary has been violated."
    )


if RF1_CONFIGURATION[
    "synthetic_sampling"
] is not False:

    raise RuntimeError(
        "RF-1 synthetic sampling boundary has been violated."
    )


if RF1_MODEL.class_weight != "balanced":

    raise RuntimeError(
        "Fitted RF-1 model does not retain "
        "class_weight='balanced'."
    )


print(
    "✓ RF-1 strategy ID = RF-1"
)

print(
    "✓ RF-1 strategy = Balanced Class Weighting"
)

print(
    "✓ RF-1 class_weight = 'balanced'"
)

print(
    "✓ RF-1 resampling = False"
)

print(
    "✓ RF-1 synthetic sampling = False"
)

print(
    "✓ Fitted RF-1 model retains class_weight = 'balanced'"
)


# ---------------------------------------------------------------
# 4. RF-1 PERSISTED ARTIFACT COMPLETENESS
# ---------------------------------------------------------------

print("\n[RF-1 PERSISTED ARTIFACT COMPLETENESS]")


if len(
    RF1_EXPERIMENT_ARTIFACTS
) != 7:

    raise RuntimeError(
        "RF-1 artifact configuration does not contain "
        "the established seven artifacts."
    )


for artifact_name, artifact_path in (
    RF1_EXPERIMENT_ARTIFACTS.items()
):

    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"RF-1 artifact is missing: "
            f"{artifact_path}"
        )


    if artifact_path.stat().st_size <= 0:

        raise RuntimeError(
            f"RF-1 artifact is empty: "
            f"{artifact_path}"
        )


    print(
        f"✓ {artifact_name:<22} "
        f"{artifact_path.name}"
    )


# ---------------------------------------------------------------
# 5. RF-1 PERSISTED RESULT STRUCTURE
# ---------------------------------------------------------------

print("\n[RF-1 PERSISTED RESULT STRUCTURE]")


RF1_VALIDATION_METRICS_PERSISTED = (
    RF1_EXPERIMENT_ARTIFACTS[
        "validation_metrics"
    ]
)


with open(
    RF1_VALIDATION_METRICS_PERSISTED,
    "r",
    encoding="utf-8"
) as file:

    RF1_PERSISTED_VALIDATION_METRICS = (
        json.load(file)
    )


required_metric_names = {
    "accuracy",
    "balanced_accuracy",
    "macro_recall",
    "macro_f1",
    "weighted_f1",
    "benign_false_positive_rate",
    "macro_roc_auc_ovr",
    "total_attack_false_negatives",
}


if not required_metric_names.issubset(
    RF1_PERSISTED_VALIDATION_METRICS.keys()
):

    raise RuntimeError(
        "RF-1 persisted Validation metrics are incomplete."
    )


RF1_PERSISTED_CONFUSION_MATRIX = pd.read_csv(
    RF1_EXPERIMENT_ARTIFACTS[
        "confusion_matrix"
    ],
    index_col=0
)


if RF1_PERSISTED_CONFUSION_MATRIX.shape != (
    9,
    9
):

    raise RuntimeError(
        "Persisted RF-1 confusion matrix is not 9 × 9."
    )


RF1_PERSISTED_CLASSIFICATION_REPORT = pd.read_csv(
    RF1_EXPERIMENT_ARTIFACTS[
        "classification_report"
    ]
)


if len(
    RF1_PERSISTED_CLASSIFICATION_REPORT
) != 9:

    raise RuntimeError(
        "Persisted RF-1 classification report does not "
        "contain all nine taxonomy classes."
    )


RF1_PERSISTED_FEATURE_IMPORTANCE = pd.read_csv(
    RF1_EXPERIMENT_ARTIFACTS[
        "feature_importance"
    ]
)


if len(
    RF1_PERSISTED_FEATURE_IMPORTANCE
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise RuntimeError(
        "Persisted RF-1 feature-importance table does not "
        "contain all 32 model-ready features."
    )


print(
    "✓ RF-1 Validation metrics structure confirmed"
)

print(
    "✓ RF-1 9 × 9 confusion matrix confirmed"
)

print(
    "✓ RF-1 nine-class classification report confirmed"
)

print(
    "✓ RF-1 32-feature importance table confirmed"
)


# ---------------------------------------------------------------
# 6. RF-1 METRIC CONSISTENCY CHECK
# ---------------------------------------------------------------

print("\n[RF-1 METRIC CONSISTENCY CHECK]")


if not np.isclose(
    RF1_PERSISTED_VALIDATION_METRICS[
        "accuracy"
    ],
    RF1_VALIDATION_ACCURACY
):

    raise RuntimeError(
        "Persisted RF-1 accuracy does not match "
        "the current RF-1 Validation result."
    )


if not np.isclose(
    RF1_PERSISTED_VALIDATION_METRICS[
        "macro_f1"
    ],
    RF1_VALIDATION_MACRO_F1
):

    raise RuntimeError(
        "Persisted RF-1 Macro F1 does not match "
        "the current RF-1 Validation result."
    )


if not np.isclose(
    RF1_PERSISTED_VALIDATION_METRICS[
        "balanced_accuracy"
    ],
    RF1_VALIDATION_BALANCED_ACCURACY
):

    raise RuntimeError(
        "Persisted RF-1 balanced accuracy does not match "
        "the current RF-1 Validation result."
    )


print(
    "✓ Persisted RF-1 accuracy matches Validation result"
)

print(
    "✓ Persisted RF-1 Macro F1 matches Validation result"
)

print(
    "✓ Persisted RF-1 balanced accuracy matches Validation result"
)


# ---------------------------------------------------------------
# 7. RF-1 COMPLETION AND BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-1 DEVELOPMENT-BOUNDARY VALIDATION]")


if not RF_5_5_6_VALIDATION[
    "independent_test_protected"
]:

    raise RuntimeError(
        "Independent Test protection was not preserved "
        "during RF-1."
    )


if not RF_5_5_6_VALIDATION[
    "n04_artifacts_untouched"
]:

    raise RuntimeError(
        "Notebook 04 model-ready artifacts were not confirmed "
        "as untouched."
    )


print(
    "✓ Independent Test remained excluded from RF-1"
)

print(
    "✓ Independent Test was not used for RF-1 evaluation "
    "or selection"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)


# ---------------------------------------------------------------
# 8. STRATEGY-SELECTION BOUNDARY
# ---------------------------------------------------------------

print("\n[STRATEGY-SELECTION BOUNDARY]")


print(
    "✓ RF-1 is retained as an independent experiment"
)

print(
    "✓ RF-1 has not been declared the optimal RF strategy"
)

print(
    "✓ No RF strategy selection has been performed"
)

print(
    "✓ RF-1 remains available for later Validation comparison"
)


# ---------------------------------------------------------------
# 9. MODEL-DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[MODEL-DEVELOPMENT BOUNDARY]")


print(
    "✓ No additional model fitting performed"
)

print(
    "✓ No additional predictions generated"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No synthetic samples generated"
)

print(
    "✓ No Independent Test data loaded"
)


# ---------------------------------------------------------------
# 10. FINAL RF-1 COMPLETION GATE
# ---------------------------------------------------------------

print("\n[FINAL RF-1 COMPLETION GATE]")


RF_5_5_7_VALIDATION = {

    "rf1_definition_complete":
        all(
            RF_5_5_1_VALIDATION.values()
        ),

    "rf1_artifact_loading_complete":
        all(
            RF_5_5_2_VALIDATION.values()
        ),

    "rf1_model_fitting_complete":
        all(
            RF_5_5_3_VALIDATION.values()
        ),

    "rf1_evaluation_complete":
        all(
            RF_5_5_4_VALIDATION.values()
        ),

    "rf1_error_resource_analysis_complete":
        all(
            RF_5_5_5_VALIDATION.values()
        ),

    "rf1_artifact_persistence_complete":
        all(
            RF_5_5_6_VALIDATION.values()
        ),

    "rf1_model_contract_valid":
        (
            RF1_MODEL.n_features_in_
            == EXPECTED_MODEL_READY_FEATURE_COUNT
        ),

    "rf1_taxonomy_valid":
        np.array_equal(
            RF1_MODEL.classes_,
            np.asarray(EXPECTED_RF_CLASS_IDS)
        ),

    "rf1_tree_count_valid":
        len(
            RF1_MODEL.estimators_
        )
        == RF1_TREE_COUNT,

    "rf1_balanced_class_weighting_valid":
        (
            RF1_CONFIGURATION[
                "class_weight"
            ] == "balanced"
            and
            RF1_MODEL.class_weight == "balanced"
        ),

    "rf1_resampling_disabled":
        RF1_CONFIGURATION[
            "resampling"
        ] is False,

    "rf1_synthetic_sampling_disabled":
        RF1_CONFIGURATION[
            "synthetic_sampling"
        ] is False,

    "rf1_artifact_count_valid":
        len(
            RF1_EXPERIMENT_ARTIFACTS
        ) == 7,

    "rf1_confusion_matrix_valid":
        RF1_PERSISTED_CONFUSION_MATRIX.shape
        == (9, 9),

    "rf1_classification_report_valid":
        len(
            RF1_PERSISTED_CLASSIFICATION_REPORT
        ) == 9,

    "rf1_feature_importance_valid":
        len(
            RF1_PERSISTED_FEATURE_IMPORTANCE
        )
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "independent_test_protected":
        RF_5_5_6_VALIDATION[
            "independent_test_protected"
        ],

    "n04_artifacts_untouched":
        RF_5_5_6_VALIDATION[
            "n04_artifacts_untouched"
        ],

    "strategy_not_selected":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_5_7_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.5.7 RF-1 completion/readiness gate failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 11. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.5.7 — RF-1 EXPERIMENT COMPLETION AND READINESS GATE PASSED"
)

print("=" * 72)

print(
    "\nRF-1 BALANCED CLASS WEIGHTING EXPERIMENT COMPLETED"
)

print(
    "✓ RF-1 definition validated"
)

print(
    "✓ Complete Training partition used for RF-1 fitting"
)

print(
    "✓ Complete Validation partition used for RF-1 evaluation"
)

print(
    "✓ RF-1 model contract validated"
)

print(
    "✓ RF-1 balanced class-weighting configuration validated"
)

print(
    "✓ RF-1 Validation results persisted"
)

print(
    "✓ RF-1 error and resource analysis completed"
)

print(
    "✓ All seven RF-1 experiment artifacts confirmed"
)

print(
    "✓ RF-1 remains an independent experiment and has not been selected"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "\nREADY FOR 5.6 — RF-2: BALANCED-SUBSAMPLE CLASS WEIGHTING"
)

print("=" * 72)

========================================================================
5.5.7 — RF-1 EXPERIMENT COMPLETION AND READINESS GATE
========================================================================

[RF-1 COMPLETION BOUNDARY VALIDATION]
✓ RF-1 experiment definition completed
✓ RF-1 Training/Validation artifact loading completed
✓ RF-1 Random Forest model fitting completed
✓ RF-1 artifact persistence and cleanup completed
✓ Independent Test remains excluded

[RF-1 FITTED MODEL CONTRACT VALIDATION]
✓ RF-1 model features : 32
✓ RF-1 model classes  : 9
✓ RF-1 model trees    : 100
✓ RF-1 model contract matches the established RF configuration

[RF-1 STRATEGY CONFIGURATION VALIDATION]
✓ RF-1 strategy ID = RF-1
✓ RF-1 strategy = Balanced Class Weighting
✓ RF-1 class_weight = 'balanced'
✓ RF-1 resampling = False
✓ RF-1 synthetic sampling = False
✓ Fitted RF-1 model retains class_weight = 'balanced'

[RF-1 PERSISTED ARTIFACT COMPLETENESS]
✓ experiment_metadata    rf1_experiment_metadata.json
✓ validation_metrics     rf1_validation_metrics.json
✓ confusion_matrix       rf1_confusion_matrix.csv
✓ classification_report  rf1_classification_report.csv
✓ resource_metrics       rf1_resource_metrics.json
✓ feature_importance     rf1_feature_importance.csv
✓ model                  rf1_model.joblib

[RF-1 PERSISTED RESULT STRUCTURE]
✓ RF-1 Validation metrics structure confirmed
✓ RF-1 9 × 9 confusion matrix confirmed
✓ RF-1 nine-class classification report confirmed
✓ RF-1 32-feature importance table confirmed

[RF-1 METRIC CONSISTENCY CHECK]
✓ Persisted RF-1 accuracy matches Validation result
✓ Persisted RF-1 Macro F1 matches Validation result
✓ Persisted RF-1 balanced accuracy matches Validation result

[RF-1 DEVELOPMENT-BOUNDARY VALIDATION]
✓ Independent Test remained excluded from RF-1
✓ Independent Test was not used for RF-1 evaluation or selection
✓ Notebook 04 model-ready artifacts remain untouched

[STRATEGY-SELECTION BOUNDARY]
✓ RF-1 is retained as an independent experiment
✓ RF-1 has not been declared the optimal RF strategy
✓ No RF strategy selection has been performed
✓ RF-1 remains available for later Validation comparison

[MODEL-DEVELOPMENT BOUNDARY]
✓ No additional model fitting performed
✓ No additional predictions generated
✓ No resampling performed
✓ No synthetic samples generated
✓ No Independent Test data loaded

[FINAL RF-1 COMPLETION GATE]

========================================================================
5.5.7 — RF-1 EXPERIMENT COMPLETION AND READINESS GATE PASSED
========================================================================

RF-1 BALANCED CLASS WEIGHTING EXPERIMENT COMPLETED
✓ RF-1 definition validated
✓ Complete Training partition used for RF-1 fitting
✓ Complete Validation partition used for RF-1 evaluation
✓ RF-1 model contract validated
✓ RF-1 balanced class-weighting configuration validated
✓ RF-1 Validation results persisted
✓ RF-1 error and resource analysis completed
✓ All seven RF-1 experiment artifacts confirmed
✓ RF-1 remains an independent experiment and has not been selected
✓ Independent Test remains completely untouched
✓ Notebook 04 model-ready artifacts remain untouched

READY FOR 5.6 — RF-2: BALANCED-SUBSAMPLE CLASS WEIGHTING
========================================================================

# 5.6 — RF-2: BALANCED-SUBSAMPLE CLASS WEIGHTING

This section evaluates the Random Forest using balanced-subsample class
weighting as the second imbalance-aware strategy.

RF-2 is designed as a controlled comparison against the previously
completed RF-0 Natural Distribution Baseline and RF-1 Balanced Class
Weighting experiments. The Training and Validation partitions,
model-ready feature representation, Random Forest configuration,
random seed, taxonomy, and evaluation protocol remain unchanged.

The only intended strategy-specific change in RF-2 is:

    class_weight = "balanced_subsample"

With bootstrap sampling enabled, balanced-subsample class weighting
calculates class weights independently for each bootstrap sample used
during Random Forest training. No random oversampling, SMOTE,
synthetic sampling, or majority-class downsampling is performed.

RF-2 therefore evaluates whether balanced-subsample class weighting
provides further improvement in minority-class detection and
macro-level performance compared with the previously evaluated
class-weighting strategies.

The Independent Test partition remains completely protected and is
not used during RF-2 model development, evaluation, comparison, or
strategy selection.

RF-2 is retained as an independent experiment and is not treated as
the final Random Forest strategy until the later Validation-Based
Strategy Comparison and Strategy Selection stages.

# 5.6.1 — RF-2 BALANCED-SUBSAMPLE EXPERIMENT DEFINITION

This subsection formally defines the RF-2 Balanced-Subsample Class
Weighting experiment before any RF-2 Training or Validation data are
loaded.

RF-2 uses the same common Random Forest configuration established for
the preceding RF experiments and the same Training, Validation, and
Independent Test partition roles.

The only intended strategy-specific change from RF-1 is the use of:

    class_weight = "balanced_subsample"

With bootstrap sampling enabled, balanced-subsample class weighting
calculates class weights independently for each bootstrap sample used
by the Random Forest during model fitting.

No random oversampling, SMOTE, synthetic sampling, or majority-class
downsampling is performed in RF-2.

RF-2 therefore provides a controlled experiment for determining whether
balanced-subsample class weighting improves minority-class detection
and macro-level performance relative to the previously evaluated
RF-0 Natural Distribution Baseline and RF-1 Balanced Class Weighting
strategy.

The Independent Test partition remains completely protected and is not
used during RF-2 model development, evaluation, comparison, or
strategy selection.

No model is fitted, no predictions are generated, no evaluation
metrics are calculated, and no Training, Validation, or Independent
Test feature arrays are loaded in this subsection.

Successful completion of this definition gate authorizes progression
to Section 5.6.2 — RF-2 Training and Validation Artifact Loading.

In [ ]:
# ================================================================
# 5.6.1 — RF-2 BALANCED-SUBSAMPLE EXPERIMENT DEFINITION
# ================================================================

print("=" * 72)
print("5.6.1 — RF-2 BALANCED-SUBSAMPLE EXPERIMENT DEFINITION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-2 STRATEGY DEFINITION
# ---------------------------------------------------------------

print("\n[RF-2 STRATEGY DEFINITION]")

RF2_CONFIGURATION = {
    "strategy_id": "RF-2",
    "strategy_name": "Balanced-Subsample Class Weighting",
    "class_weight": "balanced_subsample",
    "resampling": False,
    "synthetic_sampling": False,
    "training_partition": "Training",
    "evaluation_partition": "Validation",
    "test_used": False,
}

print(
    f"✓ Strategy ID        : "
    f"{RF2_CONFIGURATION['strategy_id']}"
)

print(
    f"✓ Strategy name      : "
    f"{RF2_CONFIGURATION['strategy_name']}"
)

print(
    f"✓ Class weighting    : "
    f"{RF2_CONFIGURATION['class_weight']}"
)

print(
    f"✓ Resampling         : "
    f"{RF2_CONFIGURATION['resampling']}"
)

print(
    f"✓ Synthetic sampling : "
    f"{RF2_CONFIGURATION['synthetic_sampling']}"
)

print(
    f"✓ Training partition : "
    f"{RF2_CONFIGURATION['training_partition']}"
)

print(
    f"✓ Evaluation         : "
    f"{RF2_CONFIGURATION['evaluation_partition']}"
)


# ---------------------------------------------------------------
# 2. COMMON RANDOM FOREST CONFIGURATION CHECK
# ---------------------------------------------------------------

print("\n[COMMON RANDOM FOREST CONFIGURATION]")

if not isinstance(
    RF_COMMON_CONFIGURATION,
    dict
):
    raise TypeError(
        "RF_COMMON_CONFIGURATION must be a dictionary."
    )


if RF_COMMON_CONFIGURATION[
    "random_state"
] != RANDOM_SEED:

    raise RuntimeError(
        "RF-2 random_state does not match "
        "the established project RANDOM_SEED."
    )


print(
    f"✓ Number of trees   : "
    f"{RF_COMMON_CONFIGURATION['n_estimators']}"
)

print(
    f"✓ Max features      : "
    f"{RF_COMMON_CONFIGURATION['max_features']}"
)

print(
    f"✓ Max depth         : "
    f"{RF_COMMON_CONFIGURATION['max_depth']}"
)

print(
    f"✓ Bootstrap         : "
    f"{RF_COMMON_CONFIGURATION['bootstrap']}"
)

print(
    f"✓ CPU parallelism   : "
    f"{RF_COMMON_CONFIGURATION['n_jobs']}"
)

print(
    f"✓ Random seed       : "
    f"{RF_COMMON_CONFIGURATION['random_state']}"
)


# ---------------------------------------------------------------
# 3. RF-2 BALANCED-SUBSAMPLE CLASS-WEIGHTING BOUNDARY
# ---------------------------------------------------------------

print(
    "\n[RF-2 BALANCED-SUBSAMPLE CLASS-WEIGHTING BOUNDARY]"
)


if RF2_CONFIGURATION[
    "class_weight"
] != "balanced_subsample":

    raise RuntimeError(
        "RF-2 must use "
        "class_weight='balanced_subsample'."
    )


if RF2_CONFIGURATION[
    "resampling"
]:

    raise RuntimeError(
        "RF-2 must not perform random oversampling "
        "or any other resampling."
    )


if RF2_CONFIGURATION[
    "synthetic_sampling"
]:

    raise RuntimeError(
        "RF-2 must not perform synthetic sampling."
    )


print(
    "✓ Training class weighting set to "
    "'balanced_subsample'"
)

print(
    "✓ No random oversampling configured"
)

print(
    "✓ No SMOTE configured"
)

print(
    "✓ No synthetic sampling configured"
)


# ---------------------------------------------------------------
# 4. PARTITION-ROLE VALIDATION
# ---------------------------------------------------------------

print("\n[TRAINING / VALIDATION / TEST ROLE BOUNDARY]")


if not RF_5_2_4_VALIDATION[
    "training_authorized_for_fitting"
]:

    raise RuntimeError(
        "Training is not authorized for RF-2 model fitting."
    )


if not RF_5_2_4_VALIDATION[
    "validation_reserved_for_comparison"
]:

    raise RuntimeError(
        "Validation is not reserved for RF strategy comparison."
    )


if not RF_5_2_4_VALIDATION[
    "validation_reserved_for_selection"
]:

    raise RuntimeError(
        "Validation is not reserved for RF strategy selection."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_fitting"
]:

    raise RuntimeError(
        "Independent Test is not protected from model fitting."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_comparison"
]:

    raise RuntimeError(
        "Independent Test is not protected from strategy comparison."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_selection"
]:

    raise RuntimeError(
        "Independent Test is not protected from strategy selection."
    )


print(
    "✓ Training authorized for RF-2 model fitting"
)

print(
    "✓ Validation reserved for RF-2 evaluation and comparison"
)

print(
    "✓ Validation reserved for strategy selection"
)

print(
    "✓ Independent Test excluded from model fitting"
)

print(
    "✓ Independent Test excluded from strategy comparison"
)

print(
    "✓ Independent Test excluded from strategy selection"
)


# ---------------------------------------------------------------
# 5. RF-2 OUTPUT BOUNDARY
# ---------------------------------------------------------------

print("\n[RF-2 EXPERIMENT OUTPUT BOUNDARY]")


RF2_OUTPUT_DIR = (
    RF_STRATEGY_EXPERIMENTS_DIR /
    "RF-2"
)


RF2_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


print(
    "✓ RF-2 output directory available:"
)

print(
    f"  {RF2_OUTPUT_DIR}"
)


# ---------------------------------------------------------------
# 6. MODEL-DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[MODEL-DEVELOPMENT BOUNDARY]")


print(
    "✓ No Training feature array loaded"
)

print(
    "✓ No Validation feature array loaded"
)

print(
    "✓ No Test feature array loaded"
)

print(
    "✓ No target array loaded"
)

print(
    "✓ No Random Forest model fitted"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No synthetic samples generated"
)

print(
    "✓ No predictions generated"
)

print(
    "✓ No evaluation metrics calculated"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 7. FINAL RF-2 DEFINITION VALIDATION
# ---------------------------------------------------------------

print("\n[RF-2 DEFINITION VALIDATION]")


RF_5_6_1_VALIDATION = {

    "strategy_id_valid":
        RF2_CONFIGURATION[
            "strategy_id"
        ] == "RF-2",

    "strategy_name_valid":
        RF2_CONFIGURATION[
            "strategy_name"
        ] == "Balanced-Subsample Class Weighting",

    "class_weight_balanced_subsample":
        RF2_CONFIGURATION[
            "class_weight"
        ] == "balanced_subsample",

    "resampling_disabled":
        RF2_CONFIGURATION[
            "resampling"
        ] is False,

    "synthetic_sampling_disabled":
        RF2_CONFIGURATION[
            "synthetic_sampling"
        ] is False,

    "training_partition_valid":
        RF2_CONFIGURATION[
            "training_partition"
        ] == "Training",

    "validation_partition_valid":
        RF2_CONFIGURATION[
            "evaluation_partition"
        ] == "Validation",

    "test_not_used":
        RF2_CONFIGURATION[
            "test_used"
        ] is False,

    "output_directory_available":
        RF2_OUTPUT_DIR.is_dir(),

    "random_state_consistent":
        RF_COMMON_CONFIGURATION[
            "random_state"
        ] == RANDOM_SEED,

    "training_authorized":
        RF_5_2_4_VALIDATION[
            "training_authorized_for_fitting"
        ],

    "validation_reserved_for_comparison":
        RF_5_2_4_VALIDATION[
            "validation_reserved_for_comparison"
        ],

    "test_protected_from_fitting":
        RF_5_2_4_VALIDATION[
            "test_excluded_from_fitting"
        ],

    "test_protected_from_comparison":
        RF_5_2_4_VALIDATION[
            "test_excluded_from_comparison"
        ],

    "test_protected_from_selection":
        RF_5_2_4_VALIDATION[
            "test_excluded_from_selection"
        ],
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_6_1_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "RF-2 balanced-subsample class-weighting "
        "definition validation failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 8. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.6.1 — RF-2 BALANCED-SUBSAMPLE "
    "EXPERIMENT DEFINITION PASSED"
)

print("=" * 72)

print(
    "\nRF-2 Balanced-Subsample Class Weighting is defined."
)

print(
    "✓ Common Random Forest configuration retained"
)

print(
    "✓ Balanced-subsample class weighting configured"
)

print(
    "✓ Validation reserved for evaluation"
)

print(
    "✓ Independent Test remains protected"
)

print(
    "✓ No model fitting or data loading performed"
)

print(
    "\nREADY FOR 5.6.2 — "
    "RF-2 TRAINING AND VALIDATION ARTIFACT LOADING"
)

print("=" * 72)

========================================================================
5.6.1 — RF-2 BALANCED-SUBSAMPLE EXPERIMENT DEFINITION
========================================================================

[RF-2 STRATEGY DEFINITION]
✓ Strategy ID        : RF-2
✓ Strategy name      : Balanced-Subsample Class Weighting
✓ Class weighting    : balanced_subsample
✓ Resampling         : False
✓ Synthetic sampling : False
✓ Training partition : Training
✓ Evaluation         : Validation

[COMMON RANDOM FOREST CONFIGURATION]
✓ Number of trees   : 100
✓ Max features      : sqrt
✓ Max depth         : None
✓ Bootstrap         : True
✓ CPU parallelism   : -1
✓ Random seed       : 42

[RF-2 BALANCED-SUBSAMPLE CLASS-WEIGHTING BOUNDARY]
✓ Training class weighting set to 'balanced_subsample'
✓ No random oversampling configured
✓ No SMOTE configured
✓ No synthetic sampling configured

[TRAINING / VALIDATION / TEST ROLE BOUNDARY]
✓ Training authorized for RF-2 model fitting
✓ Validation reserved for RF-2 evaluation and comparison
✓ Validation reserved for strategy selection
✓ Independent Test excluded from model fitting
✓ Independent Test excluded from strategy comparison
✓ Independent Test excluded from strategy selection

[RF-2 EXPERIMENT OUTPUT BOUNDARY]
✓ RF-2 output directory available:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2

[MODEL-DEVELOPMENT BOUNDARY]
✓ No Training feature array loaded
✓ No Validation feature array loaded
✓ No Test feature array loaded
✓ No target array loaded
✓ No Random Forest model fitted
✓ No resampling performed
✓ No synthetic samples generated
✓ No predictions generated
✓ No evaluation metrics calculated
✓ Independent Test remains untouched

[RF-2 DEFINITION VALIDATION]

========================================================================
5.6.1 — RF-2 BALANCED-SUBSAMPLE EXPERIMENT DEFINITION PASSED
========================================================================

RF-2 Balanced-Subsample Class Weighting is defined.
✓ Common Random Forest configuration retained
✓ Balanced-subsample class weighting configured
✓ Validation reserved for evaluation
✓ Independent Test remains protected
✓ No model fitting or data loading performed

READY FOR 5.6.2 — RF-2 TRAINING AND VALIDATION ARTIFACT LOADING
========================================================================

# 5.6.2 — RF-2 TRAINING AND VALIDATION ARTIFACT LOADING

This subsection loads the authoritative Training and Validation
artifacts required for the RF-2 Balanced-Subsample Class Weighting
experiment.

RF-2 uses the same frozen model-ready Training and Validation
partitions used by RF-0 and RF-1. The underlying feature and target
artifacts are loaded from the established RF input paths using
read-only NumPy memory mapping.

The complete Training partition is reserved for RF-2 model fitting,
while the complete Validation partition is reserved for subsequent
RF-2 performance evaluation and strategy comparison.

The expected model-ready representation remains 32 float32 features,
with int64 target arrays and observation-aligned X/y dimensions.

The Independent Test partition is not loaded and remains completely
protected from RF-2 development.

No resampling, synthetic sampling, model fitting, prediction
generation, or evaluation is performed in this subsection.

Successful completion of this artifact-loading gate authorizes
progression to Section 5.6.3 — RF-2 Random Forest Model Fitting.

In [ ]:
# ================================================================
# 5.6.2 — RF-2 TRAINING AND VALIDATION ARTIFACT LOADING
# ================================================================

import numpy as np

print("=" * 72)
print("5.6.2 — RF-2 TRAINING AND VALIDATION ARTIFACT LOADING")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-2 ARTIFACT LOADING BOUNDARY
# ---------------------------------------------------------------

print("\n[RF-2 ARTIFACT LOADING BOUNDARY]")


if not RF_5_6_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-2 balanced-subsample class-weighting definition "
        "has not passed validation."
    )


if RF2_CONFIGURATION[
    "training_partition"
] != "Training":

    raise RuntimeError(
        "RF-2 training partition is not the authoritative "
        "Training partition."
    )


if RF2_CONFIGURATION[
    "evaluation_partition"
] != "Validation":

    raise RuntimeError(
        "RF-2 evaluation partition is not the authoritative "
        "Validation partition."
    )


print(
    "✓ RF-2 balanced-subsample class-weighting definition is valid"
)

print(
    "✓ Training artifact authorized for model fitting"
)

print(
    "✓ Validation artifact authorized for RF-2 evaluation"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# 2. AUTHORITATIVE RF-2 ARTIFACT PATHS
# ---------------------------------------------------------------

print("\n[AUTHORITATIVE RF-2 ARTIFACT PATHS]")


RF2_TRAINING_FEATURE_PATH = RF_INPUT_PATHS[
    "Training features"
]

RF2_TRAINING_TARGET_PATH = RF_INPUT_PATHS[
    "Training targets"
]

RF2_VALIDATION_FEATURE_PATH = RF_INPUT_PATHS[
    "Validation features"
]

RF2_VALIDATION_TARGET_PATH = RF_INPUT_PATHS[
    "Validation targets"
]


for artifact_name, artifact_path in {
    "Training features":
        RF2_TRAINING_FEATURE_PATH,

    "Training targets":
        RF2_TRAINING_TARGET_PATH,

    "Validation features":
        RF2_VALIDATION_FEATURE_PATH,

    "Validation targets":
        RF2_VALIDATION_TARGET_PATH,

}.items():

    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"{artifact_name} artifact was not found:\n"
            f"{artifact_path}"
        )

    if artifact_path.stat().st_size == 0:

        raise ValueError(
            f"{artifact_name} artifact is empty:\n"
            f"{artifact_path}"
        )

    print(
        f"✓ {artifact_name:<20}: "
        f"{artifact_path.name}"
    )


# ---------------------------------------------------------------
# 3. READ-ONLY MEMORY-MAPPED LOADING
# ---------------------------------------------------------------

print("\n[READ-ONLY MEMORY-MAPPED LOADING]")


# The complete arrays are not copied into normal RAM.
# mmap_mode="r" provides read-only access to the persisted
# NumPy arrays.

RF2_TRAINING_FEATURES = np.load(
    RF2_TRAINING_FEATURE_PATH,
    mmap_mode="r"
)

RF2_TRAINING_TARGETS = np.load(
    RF2_TRAINING_TARGET_PATH,
    mmap_mode="r"
)

RF2_VALIDATION_FEATURES = np.load(
    RF2_VALIDATION_FEATURE_PATH,
    mmap_mode="r"
)

RF2_VALIDATION_TARGETS = np.load(
    RF2_VALIDATION_TARGET_PATH,
    mmap_mode="r"
)


print(
    "✓ Training features opened as read-only memory map"
)

print(
    "✓ Training targets opened as read-only memory map"
)

print(
    "✓ Validation features opened as read-only memory map"
)

print(
    "✓ Validation targets opened as read-only memory map"
)


# ---------------------------------------------------------------
# 4. FEATURE ARTIFACT VALIDATION
# ---------------------------------------------------------------

print("\n[RF-2 FEATURE ARTIFACT VALIDATION]")


if RF2_TRAINING_FEATURES.shape != (
    1_814_018,
    32
):

    raise ValueError(
        "RF-2 Training feature shape mismatch.\n"
        f"Expected: {(1_814_018, 32)}\n"
        f"Observed: {RF2_TRAINING_FEATURES.shape}"
    )


if RF2_VALIDATION_FEATURES.shape != (
    451_215,
    32
):

    raise ValueError(
        "RF-2 Validation feature shape mismatch.\n"
        f"Expected: {(451_215, 32)}\n"
        f"Observed: {RF2_VALIDATION_FEATURES.shape}"
    )


if RF2_TRAINING_FEATURES.dtype != np.float32:

    raise TypeError(
        "RF-2 Training features must use float32."
    )


if RF2_VALIDATION_FEATURES.dtype != np.float32:

    raise TypeError(
        "RF-2 Validation features must use float32."
    )


print(
    f"✓ Training features    : "
    f"{RF2_TRAINING_FEATURES.shape} | "
    f"{RF2_TRAINING_FEATURES.dtype}"
)

print(
    f"✓ Validation features  : "
    f"{RF2_VALIDATION_FEATURES.shape} | "
    f"{RF2_VALIDATION_FEATURES.dtype}"
)


# ---------------------------------------------------------------
# 5. TARGET ARTIFACT VALIDATION
# ---------------------------------------------------------------

print("\n[RF-2 TARGET ARTIFACT VALIDATION]")


if RF2_TRAINING_TARGETS.shape != (
    1_814_018,
):

    raise ValueError(
        "RF-2 Training target shape mismatch.\n"
        f"Expected: {(1_814_018,)}\n"
        f"Observed: {RF2_TRAINING_TARGETS.shape}"
    )


if RF2_VALIDATION_TARGETS.shape != (
    451_215,
):

    raise ValueError(
        "RF-2 Validation target shape mismatch.\n"
        f"Expected: {(451_215,)}\n"
        f"Observed: {RF2_VALIDATION_TARGETS.shape}"
    )


if RF2_TRAINING_TARGETS.dtype != np.int64:

    raise TypeError(
        "RF-2 Training targets must use int64."
    )


if RF2_VALIDATION_TARGETS.dtype != np.int64:

    raise TypeError(
        "RF-2 Validation targets must use int64."
    )


print(
    f"✓ Training targets    : "
    f"{RF2_TRAINING_TARGETS.shape} | "
    f"{RF2_TRAINING_TARGETS.dtype}"
)

print(
    f"✓ Validation targets  : "
    f"{RF2_VALIDATION_TARGETS.shape} | "
    f"{RF2_VALIDATION_TARGETS.dtype}"
)


# ---------------------------------------------------------------
# 6. X/Y OBSERVATION ALIGNMENT
# ---------------------------------------------------------------

print("\n[X/Y OBSERVATION ALIGNMENT]")


if (
    RF2_TRAINING_FEATURES.shape[0]
    != RF2_TRAINING_TARGETS.shape[0]
):

    raise ValueError(
        "RF-2 Training feature/target observation counts "
        "are not aligned."
    )


if (
    RF2_VALIDATION_FEATURES.shape[0]
    != RF2_VALIDATION_TARGETS.shape[0]
):

    raise ValueError(
        "RF-2 Validation feature/target observation counts "
        "are not aligned."
    )


print(
    "✓ Training features and targets are observation-aligned"
)

print(
    "✓ Validation features and targets are observation-aligned"
)


# ---------------------------------------------------------------
# 7. CONFIRM COMMON MODEL-READY FEATURE SPACE
# ---------------------------------------------------------------

print("\n[COMMON RF-2 MODEL-READY FEATURE SPACE]")


if (
    RF2_TRAINING_FEATURES.shape[1]
    != RF2_VALIDATION_FEATURES.shape[1]
):

    raise ValueError(
        "RF-2 Training and Validation feature dimensions "
        "do not match."
    )


if RF2_TRAINING_FEATURES.shape[1] != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-2 feature count does not match the established "
        "N04 model-ready feature contract."
    )


print(
    f"✓ Common RF-2 feature count : "
    f"{RF2_TRAINING_FEATURES.shape[1]}"
)

print(
    "✓ Training and Validation share the same "
    "32-feature model-ready representation"
)


# ---------------------------------------------------------------
# 8. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION]")


print(
    "✓ Independent Test feature artifact was not loaded"
)

print(
    "✓ Independent Test target artifact was not loaded"
)

print(
    "✓ Independent Test remains protected from RF-2 development"
)


# ---------------------------------------------------------------
# 9. MEMORY-AWARE EXECUTION CHECK
# ---------------------------------------------------------------

print("\n[MEMORY-AWARE EXECUTION CHECK]")


if not isinstance(
    RF2_TRAINING_FEATURES,
    np.memmap
):

    raise TypeError(
        "RF-2 Training features were not loaded "
        "as a NumPy memory map."
    )


if not isinstance(
    RF2_TRAINING_TARGETS,
    np.memmap
):

    raise TypeError(
        "RF-2 Training targets were not loaded "
        "as a NumPy memory map."
    )


if not isinstance(
    RF2_VALIDATION_FEATURES,
    np.memmap
):

    raise TypeError(
        "RF-2 Validation features were not loaded "
        "as a NumPy memory map."
    )


if not isinstance(
    RF2_VALIDATION_TARGETS,
    np.memmap
):

    raise TypeError(
        "RF-2 Validation targets were not loaded "
        "as a NumPy memory map."
    )


print(
    "✓ Training features remain memory-mapped"
)

print(
    "✓ Training targets remain memory-mapped"
)

print(
    "✓ Validation features remain memory-mapped"
)

print(
    "✓ Validation targets remain memory-mapped"
)

print(
    "✓ No full-array RAM duplication performed"
)


# ---------------------------------------------------------------
# 10. FINAL RF-2 ARTIFACT LOADING VALIDATION
# ---------------------------------------------------------------

RF_5_6_2_VALIDATION = {

    "training_features_loaded":
        RF2_TRAINING_FEATURES.shape
        == (1_814_018, 32),

    "training_targets_loaded":
        RF2_TRAINING_TARGETS.shape
        == (1_814_018,),

    "validation_features_loaded":
        RF2_VALIDATION_FEATURES.shape
        == (451_215, 32),

    "validation_targets_loaded":
        RF2_VALIDATION_TARGETS.shape
        == (451_215,),

    "training_feature_dtype":
        RF2_TRAINING_FEATURES.dtype
        == np.float32,

    "validation_feature_dtype":
        RF2_VALIDATION_FEATURES.dtype
        == np.float32,

    "training_target_dtype":
        RF2_TRAINING_TARGETS.dtype
        == np.int64,

    "validation_target_dtype":
        RF2_VALIDATION_TARGETS.dtype
        == np.int64,

    "training_xy_alignment":
        RF2_TRAINING_FEATURES.shape[0]
        == RF2_TRAINING_TARGETS.shape[0],

    "validation_xy_alignment":
        RF2_VALIDATION_FEATURES.shape[0]
        == RF2_VALIDATION_TARGETS.shape[0],

    "common_feature_space":
        RF2_TRAINING_FEATURES.shape[1]
        == RF2_VALIDATION_FEATURES.shape[1]
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "training_features_memory_mapped":
        isinstance(
            RF2_TRAINING_FEATURES,
            np.memmap
        ),

    "training_targets_memory_mapped":
        isinstance(
            RF2_TRAINING_TARGETS,
            np.memmap
        ),

    "validation_features_memory_mapped":
        isinstance(
            RF2_VALIDATION_FEATURES,
            np.memmap
        ),

    "validation_targets_memory_mapped":
        isinstance(
            RF2_VALIDATION_TARGETS,
            np.memmap
        ),

    "independent_test_not_loaded":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_6_2_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.6.2 RF-2 Training and Validation Artifact "
        "Loading failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 11. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.6.2 — RF-2 TRAINING AND VALIDATION "
    "ARTIFACT LOADING PASSED"
)

print("=" * 72)

print(
    "\n✓ Complete Training partition is available "
    "through read-only memory mapping"
)

print(
    "✓ Complete Validation partition is available "
    "through read-only memory mapping"
)

print(
    "✓ Training and Validation X/y dimensions are aligned"
)

print(
    "✓ Common 32-feature float32 representation confirmed"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ No resampling or synthetic sampling performed"
)

print(
    "\nREADY FOR 5.6.3 — RF-2 RANDOM FOREST MODEL FITTING"
)

print("=" * 72)

========================================================================
5.6.2 — RF-2 TRAINING AND VALIDATION ARTIFACT LOADING
========================================================================

[RF-2 ARTIFACT LOADING BOUNDARY]
✓ RF-2 balanced-subsample class-weighting definition is valid
✓ Training artifact authorized for model fitting
✓ Validation artifact authorized for RF-2 evaluation
✓ Independent Test remains excluded

[AUTHORITATIVE RF-2 ARTIFACT PATHS]
✓ Training features   : X_train_scaled.npy
✓ Training targets    : y_train.npy
✓ Validation features : X_validation_scaled.npy
✓ Validation targets  : y_validation.npy

[READ-ONLY MEMORY-MAPPED LOADING]
✓ Training features opened as read-only memory map
✓ Training targets opened as read-only memory map
✓ Validation features opened as read-only memory map
✓ Validation targets opened as read-only memory map

[RF-2 FEATURE ARTIFACT VALIDATION]
✓ Training features    : (1814018, 32) | float32
✓ Validation features  : (451215, 32) | float32

[RF-2 TARGET ARTIFACT VALIDATION]
✓ Training targets    : (1814018,) | int64
✓ Validation targets  : (451215,) | int64

[X/Y OBSERVATION ALIGNMENT]
✓ Training features and targets are observation-aligned
✓ Validation features and targets are observation-aligned

[COMMON RF-2 MODEL-READY FEATURE SPACE]
✓ Common RF-2 feature count : 32
✓ Training and Validation share the same 32-feature model-ready representation

[INDEPENDENT TEST PROTECTION]
✓ Independent Test feature artifact was not loaded
✓ Independent Test target artifact was not loaded
✓ Independent Test remains protected from RF-2 development

[MEMORY-AWARE EXECUTION CHECK]
✓ Training features remain memory-mapped
✓ Training targets remain memory-mapped
✓ Validation features remain memory-mapped
✓ Validation targets remain memory-mapped
✓ No full-array RAM duplication performed

========================================================================
5.6.2 — RF-2 TRAINING AND VALIDATION ARTIFACT LOADING PASSED
========================================================================

✓ Complete Training partition is available through read-only memory mapping
✓ Complete Validation partition is available through read-only memory mapping
✓ Training and Validation X/y dimensions are aligned
✓ Common 32-feature float32 representation confirmed
✓ Independent Test remains completely untouched
✓ No resampling or synthetic sampling performed

READY FOR 5.6.3 — RF-2 RANDOM FOREST MODEL FITTING
========================================================================

### 5.6.3 — RF-2 Random Forest Model Fitting

This subsection fits the RF-2 Random Forest using the complete Training
partition and the balanced-subsample class-weighting strategy.

RF-2 retains the same common Random Forest configuration established
for the previous experiments:

- 100 trees
- `max_features="sqrt"`
- `max_depth=None`
- `bootstrap=True`
- `n_jobs=-1`
- Project random seed

The natural Training class distribution is retained because RF-2 does
not perform random oversampling, SMOTE, majority-class downsampling, or
synthetic sample generation.

The only intended strategy-specific change is the use of
`class_weight="balanced_subsample"`.

The Validation partition is loaded but is not used during model fitting.
It remains reserved for the subsequent RF-2 Validation Prediction and
Performance Evaluation subsection.

The Independent Test partition remains completely untouched.

Successful completion of this subsection confirms that the fitted RF-2
model satisfies the frozen feature-space, taxonomy, tree-count,
configuration, and development-boundary contracts.

In [ ]:
# ================================================================
# 5.6.3 — RF-2 RANDOM FOREST MODEL FITTING
# ================================================================

from sklearn.ensemble import RandomForestClassifier
import numpy as np
import time


print("=" * 72)
print("5.6.3 — RF-2 RANDOM FOREST MODEL FITTING")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-2 FITTING BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-2 FITTING BOUNDARY VALIDATION]")


if not RF_5_6_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-2 balanced-subsample class-weighting definition "
        "has not passed validation."
    )


if not RF_5_6_2_VALIDATION[
    "training_features_loaded"
]:

    raise RuntimeError(
        "RF-2 Training features are not available "
        "for model fitting."
    )


if not RF_5_6_2_VALIDATION[
    "training_targets_loaded"
]:

    raise RuntimeError(
        "RF-2 Training targets are not available "
        "for model fitting."
    )


if not RF_5_6_2_VALIDATION[
    "training_xy_alignment"
]:

    raise RuntimeError(
        "RF-2 Training features and targets are not aligned."
    )


if not RF_5_6_2_VALIDATION[
    "training_features_memory_mapped"
]:

    raise RuntimeError(
        "RF-2 Training features are not memory-mapped."
    )


if RF2_CONFIGURATION[
    "class_weight"
] != "balanced_subsample":

    raise RuntimeError(
        "RF-2 model fitting must use "
        "class_weight='balanced_subsample'."
    )


if RF2_CONFIGURATION[
    "resampling"
]:

    raise RuntimeError(
        "RF-2 model fitting must not perform resampling."
    )


if RF2_CONFIGURATION[
    "synthetic_sampling"
]:

    raise RuntimeError(
        "RF-2 model fitting must not perform synthetic sampling."
    )


if not RF_5_2_4_VALIDATION[
    "training_authorized_for_fitting"
]:

    raise RuntimeError(
        "Training partition is not authorized for "
        "RF-2 model fitting."
    )


print(
    "✓ RF-2 balanced-subsample class-weighting definition validated"
)

print(
    "✓ Complete Training features available"
)

print(
    "✓ Complete Training targets available"
)

print(
    "✓ Training features and targets are aligned"
)

print(
    "✓ Training features remain memory-mapped"
)

print(
    "✓ Natural Training class distribution retained"
)

print(
    "✓ Balanced-subsample class weighting configured"
)

print(
    "✓ No resampling configured"
)

print(
    "✓ No synthetic sampling configured"
)

print(
    "✓ Training partition authorized for model fitting"
)


# ---------------------------------------------------------------
# 2. TRAINING FEATURE-SPACE VALIDATION
# ---------------------------------------------------------------

print("\n[TRAINING FEATURE-SPACE VALIDATION]")


if RF2_TRAINING_FEATURES.shape[1] != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-2 Training feature count does not match "
        "the established model-ready feature contract."
    )


if RF2_TRAINING_FEATURES.dtype != np.float32:

    raise TypeError(
        "RF-2 Training features must use float32."
    )


if RF2_TRAINING_FEATURES.shape[1] != len(
    RF_FEATURE_ORDER
):

    raise ValueError(
        "RF-2 Training feature count does not match "
        "the frozen RF feature order."
    )


print(
    f"✓ Training observations : "
    f"{RF2_TRAINING_FEATURES.shape[0]:,}"
)

print(
    f"✓ Training features     : "
    f"{RF2_TRAINING_FEATURES.shape[1]}"
)

print(
    f"✓ Training dtype        : "
    f"{RF2_TRAINING_FEATURES.dtype}"
)

print(
    "✓ Training feature space matches "
    "the frozen RF model-ready contract"
)


# ---------------------------------------------------------------
# 3. NATURAL TRAINING CLASS DISTRIBUTION
# ---------------------------------------------------------------

print("\n[RF-2 NATURAL TRAINING CLASS DISTRIBUTION]")


RF2_TRAINING_CLASS_IDS, RF2_TRAINING_CLASS_COUNTS = (
    np.unique(
        RF2_TRAINING_TARGETS,
        return_counts=True
    )
)


RF2_TRAINING_CLASS_DISTRIBUTION = {
    int(class_id): int(class_count)
    for class_id, class_count
    in zip(
        RF2_TRAINING_CLASS_IDS,
        RF2_TRAINING_CLASS_COUNTS
    )
}


if not np.array_equal(
    RF2_TRAINING_CLASS_IDS,
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    )
):

    raise ValueError(
        "RF-2 Training target classes do not match "
        "the established 0–8 RF taxonomy."
    )


for class_id, class_count in (
    RF2_TRAINING_CLASS_DISTRIBUTION.items()
):

    print(
        f"✓ Class {class_id}: "
        f"{RF_CLASS_MAPPING[class_id]:<24} "
        f"{class_count:,}"
    )


print(
    "✓ Complete natural Training class distribution "
    "retained for RF-2"
)


# ---------------------------------------------------------------
# 4. RF-2 MODEL CONSTRUCTION
# ---------------------------------------------------------------

print("\n[RF-2 MODEL CONSTRUCTION]")


RF2_MODEL = RandomForestClassifier(
    **RF_COMMON_CONFIGURATION,
    class_weight=RF2_CONFIGURATION[
        "class_weight"
    ]
)


if not isinstance(
    RF2_MODEL,
    RandomForestClassifier
):

    raise TypeError(
        "RF2_MODEL was not created as a "
        "RandomForestClassifier."
    )


if RF2_MODEL.n_estimators != (
    RF_COMMON_CONFIGURATION[
        "n_estimators"
    ]
):

    raise RuntimeError(
        "RF-2 model n_estimators does not match "
        "the common Random Forest configuration."
    )


if RF2_MODEL.max_features != (
    RF_COMMON_CONFIGURATION[
        "max_features"
    ]
):

    raise RuntimeError(
        "RF-2 model max_features does not match "
        "the common Random Forest configuration."
    )


if RF2_MODEL.max_depth != (
    RF_COMMON_CONFIGURATION[
        "max_depth"
    ]
):

    raise RuntimeError(
        "RF-2 model max_depth does not match "
        "the common Random Forest configuration."
    )


if RF2_MODEL.bootstrap != (
    RF_COMMON_CONFIGURATION[
        "bootstrap"
    ]
):

    raise RuntimeError(
        "RF-2 model bootstrap configuration does not "
        "match the common Random Forest configuration."
    )


if RF2_MODEL.n_jobs != (
    RF_COMMON_CONFIGURATION[
        "n_jobs"
    ]
):

    raise RuntimeError(
        "RF-2 model n_jobs configuration does not "
        "match the common Random Forest configuration."
    )


if RF2_MODEL.random_state != (
    RF_COMMON_CONFIGURATION[
        "random_state"
    ]
):

    raise RuntimeError(
        "RF-2 model random_state does not "
        "match the established project seed."
    )


if RF2_MODEL.class_weight != "balanced_subsample":

    raise RuntimeError(
        "RF-2 must use "
        "class_weight='balanced_subsample'."
    )


print(
    f"✓ Random Forest trees     : "
    f"{RF2_MODEL.n_estimators}"
)

print(
    f"✓ Max features           : "
    f"{RF2_MODEL.max_features}"
)

print(
    f"✓ Max depth              : "
    f"{RF2_MODEL.max_depth}"
)

print(
    f"✓ Bootstrap              : "
    f"{RF2_MODEL.bootstrap}"
)

print(
    f"✓ CPU parallelism        : "
    f"{RF2_MODEL.n_jobs}"
)

print(
    f"✓ Random state            : "
    f"{RF2_MODEL.random_state}"
)

print(
    f"✓ Class weighting         : "
    f"{RF2_MODEL.class_weight}"
)

print(
    "✓ RF-2 Random Forest model constructed"
)


# ---------------------------------------------------------------
# 5. RESOURCE STATE BEFORE FITTING
# ---------------------------------------------------------------

print("\n[RESOURCE STATE BEFORE RF-2 FITTING]")


RF_MEMORY = psutil.virtual_memory()


RF2_AVAILABLE_MEMORY_BEFORE_GB = (
    RF_MEMORY.available / (1024 ** 3)
)


RF2_PROCESS_MEMORY_BEFORE_GB = (
    RF_PROCESS.memory_info().rss / (1024 ** 3)
)


print(
    f"✓ Available system RAM : "
    f"{RF2_AVAILABLE_MEMORY_BEFORE_GB:.2f} GB"
)

print(
    f"✓ Python process RAM   : "
    f"{RF2_PROCESS_MEMORY_BEFORE_GB:.2f} GB"
)

print(
    "✓ Training input remains memory-mapped"
)

print(
    "✓ Validation input remains loaded but unused "
    "during model fitting"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 6. RF-2 MODEL FITTING
# ---------------------------------------------------------------

print("\n[RF-2 MODEL FITTING]")


RF2_TRAINING_START_TIME = time.perf_counter()


RF2_MODEL.fit(
    RF2_TRAINING_FEATURES,
    RF2_TRAINING_TARGETS
)


RF2_TRAINING_END_TIME = time.perf_counter()


RF2_TRAINING_TIME_SECONDS = (
    RF2_TRAINING_END_TIME
    - RF2_TRAINING_START_TIME
)


print(
    "✓ RF-2 model fitting completed"
)

print(
    f"✓ Training time : "
    f"{RF2_TRAINING_TIME_SECONDS:.3f} seconds"
)


# ---------------------------------------------------------------
# 7. RESOURCE STATE AFTER FITTING
# ---------------------------------------------------------------

print("\n[RESOURCE STATE AFTER RF-2 FITTING]")


RF_MEMORY = psutil.virtual_memory()


RF2_AVAILABLE_MEMORY_AFTER_GB = (
    RF_MEMORY.available / (1024 ** 3)
)


RF2_PROCESS_MEMORY_AFTER_GB = (
    RF_PROCESS.memory_info().rss / (1024 ** 3)
)


RF2_PROCESS_MEMORY_DELTA_GB = (
    RF2_PROCESS_MEMORY_AFTER_GB
    - RF2_PROCESS_MEMORY_BEFORE_GB
)


print(
    f"✓ Available system RAM : "
    f"{RF2_AVAILABLE_MEMORY_AFTER_GB:.2f} GB"
)

print(
    f"✓ Python process RAM   : "
    f"{RF2_PROCESS_MEMORY_AFTER_GB:.2f} GB"
)

print(
    f"✓ Process RAM change   : "
    f"{RF2_PROCESS_MEMORY_DELTA_GB:+.2f} GB"
)


# ---------------------------------------------------------------
# 8. FITTED MODEL STRUCTURE VALIDATION
# ---------------------------------------------------------------

print("\n[RF-2 FITTED MODEL VALIDATION]")


if not hasattr(
    RF2_MODEL,
    "n_features_in_"
):

    raise RuntimeError(
        "RF-2 fitted model does not expose "
        "n_features_in_."
    )


if RF2_MODEL.n_features_in_ != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-2 fitted model feature count does not "
        "match the established 32-feature contract."
    )


if not hasattr(
    RF2_MODEL,
    "classes_"
):

    raise RuntimeError(
        "RF-2 fitted model does not expose classes_."
    )


if not np.array_equal(
    RF2_MODEL.classes_,
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    )
):

    raise ValueError(
        "RF-2 fitted model classes do not match "
        "the established 0–8 taxonomy."
    )


if not hasattr(
    RF2_MODEL,
    "estimators_"
):

    raise RuntimeError(
        "RF-2 fitted model does not contain "
        "trained estimators."
    )


if len(
    RF2_MODEL.estimators_
) != RF_COMMON_CONFIGURATION[
    "n_estimators"
]:

    raise RuntimeError(
        "RF-2 fitted model does not contain the "
        "expected number of trained trees."
    )


print(
    f"✓ Fitted model feature count : "
    f"{RF2_MODEL.n_features_in_}"
)

print(
    f"✓ Fitted model classes       : "
    f"{len(RF2_MODEL.classes_)}"
)

print(
    f"✓ Fitted model tree count    : "
    f"{len(RF2_MODEL.estimators_)}"
)

print(
    "✓ RF-2 fitted model matches "
    "the established feature and taxonomy contracts"
)


# ---------------------------------------------------------------
# 9. DEVELOPMENT-BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-2 DEVELOPMENT-BOUNDARY VALIDATION]")


print(
    "✓ RF-2 fitted only on the Training partition"
)

print(
    "✓ Validation targets were not used for fitting"
)

print(
    "✓ Validation predictions were not generated"
)

print(
    "✓ Independent Test features were not loaded"
)

print(
    "✓ Independent Test targets were not loaded"
)

print(
    "✓ Balanced-subsample class weighting was applied"
)

print(
    "✓ No random oversampling was applied"
)

print(
    "✓ No SMOTE was applied"
)

print(
    "✓ No synthetic samples were generated"
)

print(
    "✓ No strategy selection was performed"
)

print(
    "✓ No RF-2 evaluation metrics were calculated"
)

print(
    "✓ Model persistence was not performed in this subsection"
)


# ---------------------------------------------------------------
# 10. FINAL RF-2 FITTING VALIDATION
# ---------------------------------------------------------------

RF_5_6_3_VALIDATION = {

    "rf2_strategy_valid":
        RF2_CONFIGURATION[
            "strategy_id"
        ] == "RF-2",

    "training_partition_used":
        RF2_TRAINING_FEATURES.shape
        == (
            1_814_018,
            32
        ),

    "training_targets_used":
        RF2_TRAINING_TARGETS.shape
        == (
            1_814_018,
        ),

    "training_feature_dtype":
        RF2_TRAINING_FEATURES.dtype
        == np.float32,

    "training_target_dtype":
        RF2_TRAINING_TARGETS.dtype
        == np.int64,

    "balanced_subsample_class_weighting":
        RF2_CONFIGURATION[
            "class_weight"
        ] == "balanced_subsample"
        and RF2_MODEL.class_weight
        == "balanced_subsample",

    "resampling_disabled":
        RF2_CONFIGURATION[
            "resampling"
        ] is False,

    "synthetic_sampling_disabled":
        RF2_CONFIGURATION[
            "synthetic_sampling"
        ] is False,

    "feature_count_valid":
        RF2_MODEL.n_features_in_
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "taxonomy_valid":
        np.array_equal(
            RF2_MODEL.classes_,
            np.asarray(
                EXPECTED_RF_CLASS_IDS
            )
        ),

    "tree_count_valid":
        len(
            RF2_MODEL.estimators_
        )
        == RF_COMMON_CONFIGURATION[
            "n_estimators"
        ],

    "random_state_valid":
        RF2_MODEL.random_state
        == RANDOM_SEED,

    "training_time_recorded":
        RF2_TRAINING_TIME_SECONDS > 0,

    "independent_test_not_used":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_6_3_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.6.3 RF-2 model fitting validation failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 11. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.6.3 — RF-2 RANDOM FOREST MODEL FITTING PASSED"
)

print("=" * 72)

print(
    "\n✓ RF-2 Balanced-Subsample Class Weighting "
    "fitted successfully"
)

print(
    "✓ Complete Training partition used for model fitting"
)

print(
    "✓ Natural Training class distribution retained"
)

print(
    "✓ Balanced-subsample class weighting applied"
)

print(
    "✓ Common Random Forest configuration retained"
)

print(
    "✓ 32-feature model-ready representation confirmed"
)

print(
    "✓ Nine-class taxonomy confirmed"
)

print(
    "✓ Validation remains reserved for subsequent RF-2 evaluation"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ No resampling or synthetic sampling performed"
)

print(
    "\nREADY FOR 5.6.4 — "
    "RF-2 VALIDATION PREDICTION AND PERFORMANCE EVALUATION"
)

print("=" * 72)

========================================================================
5.6.3 — RF-2 RANDOM FOREST MODEL FITTING
========================================================================

[RF-2 FITTING BOUNDARY VALIDATION]
✓ RF-2 balanced-subsample class-weighting definition validated
✓ Complete Training features available
✓ Complete Training targets available
✓ Training features and targets are aligned
✓ Training features remain memory-mapped
✓ Natural Training class distribution retained
✓ Balanced-subsample class weighting configured
✓ No resampling configured
✓ No synthetic sampling configured
✓ Training partition authorized for model fitting

[TRAINING FEATURE-SPACE VALIDATION]
✓ Training observations : 1,814,018
✓ Training features     : 32
✓ Training dtype        : float32
✓ Training feature space matches the frozen RF model-ready contract

[RF-2 NATURAL TRAINING CLASS DISTRIBUTION]
✓ Class 0: BENIGN                   1,448,197
✓ Class 1: DDoS                     81,968
✓ Class 2: Port Scan                101,723
✓ Class 3: Brute Force              9,325
✓ Class 4: Bot                      1,270
✓ Class 5: Web Attack               1,389
✓ Class 6: Infiltration             15
✓ Class 7: DoS                      170,125
✓ Class 8: Heartbleed               6
✓ Complete natural Training class distribution retained for RF-2

[RF-2 MODEL CONSTRUCTION]
✓ Random Forest trees     : 100
✓ Max features           : sqrt
✓ Max depth              : None
✓ Bootstrap              : True
✓ CPU parallelism        : -1
✓ Random state            : 42
✓ Class weighting         : balanced_subsample
✓ RF-2 Random Forest model constructed

[RESOURCE STATE BEFORE RF-2 FITTING]
✓ Available system RAM : 9.85 GB
✓ Python process RAM   : 1.52 GB
✓ Training input remains memory-mapped
✓ Validation input remains loaded but unused during model fitting
✓ Independent Test remains untouched

[RF-2 MODEL FITTING]
✓ RF-2 model fitting completed
✓ Training time : 859.680 seconds

[RESOURCE STATE AFTER RF-2 FITTING]
✓ Available system RAM : 9.82 GB
✓ Python process RAM   : 1.80 GB
✓ Process RAM change   : +0.28 GB

[RF-2 FITTED MODEL VALIDATION]
✓ Fitted model feature count : 32
✓ Fitted model classes       : 9
✓ Fitted model tree count    : 100
✓ RF-2 fitted model matches the established feature and taxonomy contracts

[RF-2 DEVELOPMENT-BOUNDARY VALIDATION]
✓ RF-2 fitted only on the Training partition
✓ Validation targets were not used for fitting
✓ Validation predictions were not generated
✓ Independent Test features were not loaded
✓ Independent Test targets were not loaded
✓ Balanced-subsample class weighting was applied
✓ No random oversampling was applied
✓ No SMOTE was applied
✓ No synthetic samples were generated
✓ No strategy selection was performed
✓ No RF-2 evaluation metrics were calculated
✓ Model persistence was not performed in this subsection

========================================================================
5.6.3 — RF-2 RANDOM FOREST MODEL FITTING PASSED
========================================================================

✓ RF-2 Balanced-Subsample Class Weighting fitted successfully
✓ Complete Training partition used for model fitting
✓ Natural Training class distribution retained
✓ Balanced-subsample class weighting applied
✓ Common Random Forest configuration retained
✓ 32-feature model-ready representation confirmed
✓ Nine-class taxonomy confirmed
✓ Validation remains reserved for subsequent RF-2 evaluation
✓ Independent Test remains completely untouched
✓ No resampling or synthetic sampling performed

READY FOR 5.6.4 — RF-2 VALIDATION PREDICTION AND PERFORMANCE EVALUATION
========================================================================

# 5.6.4 — RF-2 VALIDATION PREDICTION AND PERFORMANCE EVALUATION

This subsection evaluates the fitted RF-2 Balanced-Subsample Class
Weighting model on the complete Validation partition.

The evaluation protocol is identical to RF-1 and RF-0 to ensure a
controlled comparison across Random Forest imbalance-handling strategies.

The following metrics and diagnostic outputs are generated:

- Accuracy
- Balanced Accuracy
- Macro Recall
- Macro F1
- Weighted F1
- Per-class Precision, Recall, F1, and Support
- 9 × 9 Confusion Matrix
- BENIGN False-Positive Rate
- Attack-class False Negatives
- Macro ROC-AUC using One-vs-Rest probabilities

The Validation partition is used only for performance evaluation and
comparison. The Independent Test partition remains completely
protected and is not used for prediction, evaluation, or strategy
selection.

No model parameters are modified during evaluation, and no resampling
or synthetic sampling is performed.

Successful completion of this subsection authorizes progression to
Section 5.6.5 — RF-2 Error and Resource Analysis.

In [ ]:
# ================================================================
# 5.6.4 — RF-2 VALIDATION PREDICTION AND PERFORMANCE EVALUATION
# ================================================================

import numpy as np
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_recall_fscore_support,
    f1_score,
    recall_score,
    confusion_matrix,
    roc_auc_score
)

print("=" * 72)
print("5.6.4 — RF-2 VALIDATION PREDICTION AND PERFORMANCE EVALUATION")
print("=" * 72)


# ------------------------------------------------
# [RF-2 EVALUATION BOUNDARY VALIDATION]
# ------------------------------------------------

print("\n[RF-2 EVALUATION BOUNDARY VALIDATION]")

if RF2_MODEL is None:
    raise ValueError("RF-2 fitted model is not available.")

if RF2_VALIDATION_FEATURES.shape != (451215, 32):
    raise ValueError(
        f"Unexpected RF-2 Validation feature shape: "
        f"{RF2_VALIDATION_FEATURES.shape}"
    )

if RF2_VALIDATION_TARGETS.shape != (451215,):
    raise ValueError(
        f"Unexpected RF-2 Validation target shape: "
        f"{RF2_VALIDATION_TARGETS.shape}"
    )

if RF2_VALIDATION_FEATURES.dtype != np.float32:
    raise TypeError(
        f"RF-2 Validation features must be float32, "
        f"got {RF2_VALIDATION_FEATURES.dtype}"
    )

if RF2_VALIDATION_TARGETS.dtype != np.int64:
    raise TypeError(
        f"RF-2 Validation targets must be int64, "
        f"got {RF2_VALIDATION_TARGETS.dtype}"
    )

if len(RF2_VALIDATION_FEATURES) != len(RF2_VALIDATION_TARGETS):
    raise ValueError(
        "RF-2 Validation X/y observations are not aligned."
    )

print("✓ RF-2 fitted model is available")
print("✓ Complete Validation feature artifact is available")
print("✓ Complete Validation target artifact is available")
print("✓ Validation X/y observations are aligned")
print("✓ Validation feature representation = 32 float32 features")
print("✓ Independent Test remains excluded")


# ------------------------------------------------
# [RF-2 VALIDATION PREDICTION]
# ------------------------------------------------

print("\n[RF-2 VALIDATION PREDICTION]")

RF2_VALIDATION_PREDICTIONS = RF2_MODEL.predict(
    RF2_VALIDATION_FEATURES
)

if RF2_VALIDATION_PREDICTIONS.shape != RF2_VALIDATION_TARGETS.shape:
    raise ValueError(
        "RF-2 Validation prediction shape does not match "
        "Validation targets."
    )

if not np.isfinite(RF2_VALIDATION_PREDICTIONS).all():
    raise ValueError(
        "RF-2 Validation predictions contain non-finite values."
    )

print(
    f"✓ Validation predictions generated : "
    f"{RF2_VALIDATION_PREDICTIONS.shape[0]:,}"
)

print(
    "✓ Validation predictions correspond to the complete "
    "Validation partition"
)

print("✓ No Independent Test predictions generated")


# ------------------------------------------------
# [PRIMARY AND SECONDARY PERFORMANCE METRICS]
# ------------------------------------------------

print("\n[PRIMARY AND SECONDARY PERFORMANCE METRICS]")

RF2_VALIDATION_ACCURACY = accuracy_score(
    RF2_VALIDATION_TARGETS,
    RF2_VALIDATION_PREDICTIONS
)

RF2_VALIDATION_BALANCED_ACCURACY = balanced_accuracy_score(
    RF2_VALIDATION_TARGETS,
    RF2_VALIDATION_PREDICTIONS
)

RF2_VALIDATION_MACRO_F1 = f1_score(
    RF2_VALIDATION_TARGETS,
    RF2_VALIDATION_PREDICTIONS,
    average="macro",
    zero_division=0
)

RF2_VALIDATION_MACRO_RECALL = recall_score(
    RF2_VALIDATION_TARGETS,
    RF2_VALIDATION_PREDICTIONS,
    average="macro",
    zero_division=0
)

RF2_VALIDATION_WEIGHTED_F1 = f1_score(
    RF2_VALIDATION_TARGETS,
    RF2_VALIDATION_PREDICTIONS,
    average="weighted",
    zero_division=0
)

print(
    f"✓ Accuracy              : "
    f"{RF2_VALIDATION_ACCURACY:.6f}"
)

print(
    f"✓ Balanced Accuracy     : "
    f"{RF2_VALIDATION_BALANCED_ACCURACY:.6f}"
)

print(
    f"✓ Macro Recall          : "
    f"{RF2_VALIDATION_MACRO_RECALL:.6f}"
)

print(
    f"✓ Macro F1              : "
    f"{RF2_VALIDATION_MACRO_F1:.6f}"
)

print(
    f"✓ Weighted F1           : "
    f"{RF2_VALIDATION_WEIGHTED_F1:.6f}"
)


# ------------------------------------------------
# [PER-CLASS PERFORMANCE METRICS]
# ------------------------------------------------

print("\n[PER-CLASS PERFORMANCE METRICS]")

RF2_VALIDATION_PRECISION_PER_CLASS, \
RF2_VALIDATION_RECALL_PER_CLASS, \
RF2_VALIDATION_F1_PER_CLASS, \
RF2_VALIDATION_SUPPORT_PER_CLASS = precision_recall_fscore_support(
    RF2_VALIDATION_TARGETS,
    RF2_VALIDATION_PREDICTIONS,
    labels=np.arange(9),
    zero_division=0
)

RF2_VALIDATION_CLASS_NAMES = [
    "BENIGN",
    "DDoS",
    "Port Scan",
    "Brute Force",
    "Bot",
    "Web Attack",
    "Infiltration",
    "DoS",
    "Heartbleed"
]

for class_id, class_name in enumerate(
    RF2_VALIDATION_CLASS_NAMES
):

    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Precision={RF2_VALIDATION_PRECISION_PER_CLASS[class_id]:.6f} | "
        f"Recall={RF2_VALIDATION_RECALL_PER_CLASS[class_id]:.6f} | "
        f"F1={RF2_VALIDATION_F1_PER_CLASS[class_id]:.6f} | "
        f"Support={RF2_VALIDATION_SUPPORT_PER_CLASS[class_id]:,}"
    )


# ------------------------------------------------
# [CONFUSION MATRIX]
# ------------------------------------------------

print("\n[CONFUSION MATRIX]")

RF2_VALIDATION_CONFUSION_MATRIX = confusion_matrix(
    RF2_VALIDATION_TARGETS,
    RF2_VALIDATION_PREDICTIONS,
    labels=np.arange(9)
)

if RF2_VALIDATION_CONFUSION_MATRIX.shape != (9, 9):
    raise ValueError(
        f"Unexpected RF-2 confusion-matrix shape: "
        f"{RF2_VALIDATION_CONFUSION_MATRIX.shape}"
    )

print("✓ 9 × 9 confusion matrix generated")
print("✓ All nine taxonomy classes included")

print("\nRF-2 Validation Confusion Matrix:")
print(RF2_VALIDATION_CONFUSION_MATRIX)


# ------------------------------------------------
# [BENIGN FALSE-POSITIVE RATE]
# ------------------------------------------------

print("\n[BENIGN FALSE-POSITIVE RATE]")

RF2_BENIGN_TRUE_NEGATIVES = (
    RF2_VALIDATION_CONFUSION_MATRIX[0, 0]
)

RF2_BENIGN_FALSE_POSITIVES = (
    RF2_VALIDATION_CONFUSION_MATRIX[:, 0].sum()
    - RF2_BENIGN_TRUE_NEGATIVES
)

RF2_BENIGN_ACTUAL_NEGATIVES = (
    RF2_VALIDATION_CONFUSION_MATRIX[1:, :].sum()
)

if RF2_BENIGN_ACTUAL_NEGATIVES == 0:

    RF2_BENIGN_FALSE_POSITIVE_RATE = 0.0

else:

    RF2_BENIGN_FALSE_POSITIVE_RATE = (
        RF2_BENIGN_FALSE_POSITIVES
        / RF2_BENIGN_ACTUAL_NEGATIVES
    )

print(
    f"✓ BENIGN false-positive rate : "
    f"{RF2_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)


# ------------------------------------------------
# [ATTACK FALSE NEGATIVES]
# ------------------------------------------------

print("\n[ATTACK FALSE NEGATIVES]")

RF2_ATTACK_FALSE_NEGATIVES = {}

for class_id in range(1, 9):

    false_negatives = (
        RF2_VALIDATION_CONFUSION_MATRIX[class_id, :].sum()
        - RF2_VALIDATION_CONFUSION_MATRIX[class_id, class_id]
    )

    RF2_ATTACK_FALSE_NEGATIVES[class_id] = int(
        false_negatives
    )

    print(
        f"✓ Class {class_id}: "
        f"{RF2_VALIDATION_CLASS_NAMES[class_id]:<15} "
        f"false negatives = {false_negatives:,}"
    )


# ------------------------------------------------
# [SUPPLEMENTARY MULTICLASS ROC-AUC]
# ------------------------------------------------

print("\n[SUPPLEMENTARY MULTICLASS ROC-AUC]")

RF2_VALIDATION_ROC_AUC = None

try:

    RF2_VALIDATION_PROBABILITIES = RF2_MODEL.predict_proba(
        RF2_VALIDATION_FEATURES
    )

    RF2_VALIDATION_ROC_AUC = roc_auc_score(
        RF2_VALIDATION_TARGETS,
        RF2_VALIDATION_PROBABILITIES,
        multi_class="ovr",
        average="macro",
        labels=np.arange(9)
    )

    print(
        f"✓ Macro ROC-AUC (OvR) : "
        f"{RF2_VALIDATION_ROC_AUC:.6f}"
    )

except ValueError as error:

    print(
        "⚠ Macro ROC-AUC could not be calculated reliably: "
        f"{error}"
    )


# Release only the temporary probability array.
# Validation features/targets and the fitted RF-2 model remain available.

if "RF2_VALIDATION_PROBABILITIES" in locals():
    del RF2_VALIDATION_PROBABILITIES


# ------------------------------------------------
# [RF-2 VALIDATION EVALUATION SUMMARY]
# ------------------------------------------------

print("\n[RF-2 VALIDATION EVALUATION SUMMARY]")

print(
    f"✓ Primary metric — Macro F1       : "
    f"{RF2_VALIDATION_MACRO_F1:.6f}"
)

print(
    f"✓ Macro Recall                    : "
    f"{RF2_VALIDATION_MACRO_RECALL:.6f}"
)

print(
    f"✓ Balanced Accuracy               : "
    f"{RF2_VALIDATION_BALANCED_ACCURACY:.6f}"
)

print(
    f"✓ Weighted F1                     : "
    f"{RF2_VALIDATION_WEIGHTED_F1:.6f}"
)

print(
    f"✓ Accuracy                        : "
    f"{RF2_VALIDATION_ACCURACY:.6f}"
)

print(
    f"✓ BENIGN False-Positive Rate     : "
    f"{RF2_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)

if RF2_VALIDATION_ROC_AUC is not None:

    print(
        f"✓ Macro ROC-AUC (OvR)            : "
        f"{RF2_VALIDATION_ROC_AUC:.6f}"
    )


# ------------------------------------------------
# [DEVELOPMENT-BOUNDARY VALIDATION]
# ------------------------------------------------

print("\n[DEVELOPMENT-BOUNDARY VALIDATION]")

print("✓ RF-2 was fitted only on Training")
print("✓ Validation was used only for RF-2 performance evaluation")
print("✓ RF-2 strategy selection has not been performed")
print("✓ Independent Test remains completely untouched")
print("✓ No resampling or synthetic sampling performed")
print("✓ No model parameters modified during evaluation")


# ------------------------------------------------
# [RF-2 EVALUATION VALIDATION]
# ------------------------------------------------

RF_5_6_4_VALIDATION = {

    "rf2_model_available":
        RF2_MODEL is not None,

    "validation_prediction_count":
        RF2_VALIDATION_PREDICTIONS.shape
        == RF2_VALIDATION_TARGETS.shape,

    "validation_prediction_count_expected":
        RF2_VALIDATION_PREDICTIONS.shape
        == (451215,),

    "accuracy_recorded":
        np.isfinite(
            RF2_VALIDATION_ACCURACY
        ),

    "balanced_accuracy_recorded":
        np.isfinite(
            RF2_VALIDATION_BALANCED_ACCURACY
        ),

    "macro_recall_recorded":
        np.isfinite(
            RF2_VALIDATION_MACRO_RECALL
        ),

    "macro_f1_recorded":
        np.isfinite(
            RF2_VALIDATION_MACRO_F1
        ),

    "weighted_f1_recorded":
        np.isfinite(
            RF2_VALIDATION_WEIGHTED_F1
        ),

    "per_class_metrics_recorded":
        len(
            RF2_VALIDATION_PRECISION_PER_CLASS
        ) == 9
        and
        len(
            RF2_VALIDATION_RECALL_PER_CLASS
        ) == 9
        and
        len(
            RF2_VALIDATION_F1_PER_CLASS
        ) == 9
        and
        len(
            RF2_VALIDATION_SUPPORT_PER_CLASS
        ) == 9,

    "confusion_matrix_valid":
        RF2_VALIDATION_CONFUSION_MATRIX.shape
        == (9, 9),

    "benign_false_positive_rate_recorded":
        np.isfinite(
            RF2_BENIGN_FALSE_POSITIVE_RATE
        ),

    "attack_false_negatives_recorded":
        len(
            RF2_ATTACK_FALSE_NEGATIVES
        ) == 8,

    "independent_test_not_used":
        True,

    "strategy_selection_not_performed":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_6_4_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.6.4 RF-2 Validation evaluation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


print("\n" + "=" * 72)

print(
    "5.6.4 — RF-2 VALIDATION PREDICTION AND "
    "PERFORMANCE EVALUATION PASSED"
)

print("=" * 72)

print("\nRF-2 Validation evaluation completed.")

print(
    "READY FOR 5.6.5 — RF-2 Error and Resource Analysis"
)

print("=" * 72)

========================================================================
5.6.4 — RF-2 VALIDATION PREDICTION AND PERFORMANCE EVALUATION
========================================================================

[RF-2 EVALUATION BOUNDARY VALIDATION]
✓ RF-2 fitted model is available
✓ Complete Validation feature artifact is available
✓ Complete Validation target artifact is available
✓ Validation X/y observations are aligned
✓ Validation feature representation = 32 float32 features
✓ Independent Test remains excluded

[RF-2 VALIDATION PREDICTION]
✓ Validation predictions generated : 451,215
✓ Validation predictions correspond to the complete Validation partition
✓ No Independent Test predictions generated

[PRIMARY AND SECONDARY PERFORMANCE METRICS]
✓ Accuracy              : 0.997123
✓ Balanced Accuracy     : 0.810089
✓ Macro Recall          : 0.810089
✓ Macro F1              : 0.850649
✓ Weighted F1           : 0.997100

[PER-CLASS PERFORMANCE METRICS]
✓ 0: BENIGN          Precision=0.997969 | Recall=0.998547 | F1=0.998258 | Support=369,501
✓ 1: DDoS            Precision=0.999902 | Recall=0.999658 | F1=0.999780 | Support=20,458
✓ 2: Port Scan       Precision=0.994194 | Recall=0.996398 | F1=0.995294 | Support=25,261
✓ 3: Brute Force     Precision=0.977431 | Recall=0.976907 | F1=0.977169 | Support=1,862
✓ 4: Bot             Precision=0.609848 | Recall=0.542088 | F1=0.573975 | Support=297
✓ 5: Web Attack      Precision=0.986188 | Recall=0.983471 | F1=0.984828 | Support=363
✓ 6: Infiltration    Precision=1.000000 | Recall=0.307692 | F1=0.470588 | Support=13
✓ 7: DoS             Precision=0.992538 | Recall=0.986041 | F1=0.989279 | Support=33,456
✓ 8: Heartbleed      Precision=1.000000 | Recall=0.500000 | F1=0.666667 | Support=4

[CONFUSION MATRIX]
✓ 9 × 9 confusion matrix generated
✓ All nine taxonomy classes included

RF-2 Validation Confusion Matrix:
[[368964      2    143     42    103      5      0    242      0]
 [     6  20451      0      0      0      0      0      1      0]
 [    86      0  25170      0      0      0      0      5      0]
 [    43      0      0   1819      0      0      0      0      0]
 [   136      0      0      0    161      0      0      0      0]
 [     4      0      2      0      0    357      0      0      0]
 [     9      0      0      0      0      0      4      0      0]
 [   465      0      2      0      0      0      0  32989      0]
 [     2      0      0      0      0      0      0      0      2]]

[BENIGN FALSE-POSITIVE RATE]
✓ BENIGN false-positive rate : 0.009191

[ATTACK FALSE NEGATIVES]
✓ Class 1: DDoS            false negatives = 7
✓ Class 2: Port Scan       false negatives = 91
✓ Class 3: Brute Force     false negatives = 43
✓ Class 4: Bot             false negatives = 136
✓ Class 5: Web Attack      false negatives = 6
✓ Class 6: Infiltration    false negatives = 9
✓ Class 7: DoS             false negatives = 467
✓ Class 8: Heartbleed      false negatives = 2

[SUPPLEMENTARY MULTICLASS ROC-AUC]
✓ Macro ROC-AUC (OvR) : 0.992746

[RF-2 VALIDATION EVALUATION SUMMARY]
✓ Primary metric — Macro F1       : 0.850649
✓ Macro Recall                    : 0.810089
✓ Balanced Accuracy               : 0.810089
✓ Weighted F1                     : 0.997100
✓ Accuracy                        : 0.997123
✓ BENIGN False-Positive Rate     : 0.009191
✓ Macro ROC-AUC (OvR)            : 0.992746

[DEVELOPMENT-BOUNDARY VALIDATION]
✓ RF-2 was fitted only on Training
✓ Validation was used only for RF-2 performance evaluation
✓ RF-2 strategy selection has not been performed
✓ Independent Test remains completely untouched
✓ No resampling or synthetic sampling performed
✓ No model parameters modified during evaluation

========================================================================
5.6.4 — RF-2 VALIDATION PREDICTION AND PERFORMANCE EVALUATION PASSED
========================================================================

RF-2 Validation evaluation completed.
READY FOR 5.6.5 — RF-2 Error and Resource Analysis
========================================================================

# 5.6.5 — RF-2 ERROR AND RESOURCE ANALYSIS

This subsection performs detailed error analysis and resource analysis
for the RF-2 Balanced-Subsample Class Weighting experiment.

The analysis is performed exclusively on the RF-2 Validation results
already generated in Section 5.6.4. No additional model fitting,
resampling, synthetic sampling, or Independent Test evaluation is
performed.

The analysis records:

- Class-wise prediction errors and false negatives
- Top confusion pairs
- BENIGN false-positive count and rate
- Attack-class false negatives
- Total attack false negatives
- Minority-class recall and F1 performance
- Random Forest model resource configuration
- Current system and process memory state
- RF-2 validation performance summary

The complete Training partition and complete Validation partition
remain the basis of the RF-2 experiment, while the Independent Test
partition remains completely protected.

RF-2 remains an independent experimental strategy and is not declared
the optimal Random Forest strategy in this subsection. Strategy
selection is reserved for the later Validation-Based Strategy
Comparison and Strategy Selection stages.

In [ ]:
# ================================================================
# 5.6.5 — RF-2 ERROR AND RESOURCE ANALYSIS
# ================================================================

import os
import psutil
import numpy as np


print("=" * 72)
print("5.6.5 — RF-2 ERROR AND RESOURCE ANALYSIS")
print("=" * 72)


# ---------------------------------------------------------------
# [RF-2 ANALYSIS BOUNDARY VALIDATION]
# ---------------------------------------------------------------

print("\n[RF-2 ANALYSIS BOUNDARY VALIDATION]")


if RF2_MODEL is None:
    raise ValueError(
        "RF-2 fitted model is not available."
    )


if RF2_VALIDATION_TARGETS.shape != RF2_VALIDATION_PREDICTIONS.shape:
    raise ValueError(
        "RF-2 Validation targets and predictions are not aligned."
    )


if RF2_VALIDATION_CONFUSION_MATRIX.shape != (9, 9):
    raise ValueError(
        "RF-2 Validation confusion matrix must have shape (9, 9)."
    )


print("✓ RF-2 fitted model is available")
print("✓ Validation targets are available")
print("✓ Validation predictions are available")
print("✓ Validation confusion matrix is available")
print("✓ Independent Test remains excluded")
print("✓ No model fitting will be performed")
print("✓ No resampling or synthetic sampling will be performed")


# ---------------------------------------------------------------
# [CLASS-WISE ERROR ANALYSIS]
# ---------------------------------------------------------------

print("\n[CLASS-WISE ERROR ANALYSIS]")


RF2_VALIDATION_CLASS_ERRORS = {}


for class_id, class_name in enumerate(
    RF2_VALIDATION_CLASS_NAMES
):

    actual_count = int(
        RF2_VALIDATION_CONFUSION_MATRIX[
            class_id, :
        ].sum()
    )


    correct_count = int(
        RF2_VALIDATION_CONFUSION_MATRIX[
            class_id,
            class_id
        ]
    )


    false_negative_count = (
        actual_count -
        correct_count
    )


    RF2_VALIDATION_CLASS_ERRORS[class_id] = {

        "class_name":
            class_name,

        "support":
            actual_count,

        "correct_predictions":
            correct_count,

        "false_negatives":
            false_negative_count,

        "recall":
            float(
                RF2_VALIDATION_RECALL_PER_CLASS[
                    class_id
                ]
            ),

        "f1":
            float(
                RF2_VALIDATION_F1_PER_CLASS[
                    class_id
                ]
            ),
    }


    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Support={actual_count:,} | "
        f"Correct={correct_count:,} | "
        f"FN={false_negative_count:,}"
    )


# ---------------------------------------------------------------
# [TOP CONFUSION PAIRS]
# ---------------------------------------------------------------

print("\n[TOP CONFUSION PAIRS]")


RF2_VALIDATION_CONFUSION_PAIRS = []


for actual_class in range(9):

    for predicted_class in range(9):

        if actual_class == predicted_class:
            continue


        count = int(
            RF2_VALIDATION_CONFUSION_MATRIX[
                actual_class,
                predicted_class
            ]
        )


        if count > 0:

            RF2_VALIDATION_CONFUSION_PAIRS.append(
                (
                    count,
                    actual_class,
                    predicted_class
                )
            )


RF2_VALIDATION_CONFUSION_PAIRS.sort(
    key=lambda item: item[0],
    reverse=True
)


RF2_VALIDATION_TOP_CONFUSION_PAIRS = (
    RF2_VALIDATION_CONFUSION_PAIRS[:10]
)


if RF2_VALIDATION_TOP_CONFUSION_PAIRS:

    for rank, (
        count,
        actual_class,
        predicted_class
    ) in enumerate(
        RF2_VALIDATION_TOP_CONFUSION_PAIRS,
        start=1
    ):

        print(
            f"{rank:>2}. "
            f"Actual="
            f"{RF2_VALIDATION_CLASS_NAMES[actual_class]:<15} "
            f"→ Predicted="
            f"{RF2_VALIDATION_CLASS_NAMES[predicted_class]:<15} "
            f"| Count={count:,}"
        )

else:

    print(
        "✓ No off-diagonal confusion pairs detected"
    )


# ---------------------------------------------------------------
# [BENIGN FALSE-POSITIVE ANALYSIS]
# ---------------------------------------------------------------

print("\n[BENIGN FALSE-POSITIVE ANALYSIS]")


RF2_VALIDATION_BENIGN_FALSE_POSITIVE_COUNT = int(
    RF2_VALIDATION_CONFUSION_MATRIX[
        1:, 0
    ].sum()
)


RF2_VALIDATION_BENIGN_FALSE_POSITIVE_RATE = (
    RF2_BENIGN_FALSE_POSITIVE_RATE
)


print(
    f"✓ BENIGN false-positive count : "
    f"{RF2_VALIDATION_BENIGN_FALSE_POSITIVE_COUNT:,}"
)


print(
    f"✓ BENIGN false-positive rate  : "
    f"{RF2_VALIDATION_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)


# ---------------------------------------------------------------
# [ATTACK FALSE-NEGATIVE SUMMARY]
# ---------------------------------------------------------------

print("\n[ATTACK FALSE-NEGATIVE SUMMARY]")


RF2_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES = 0


for class_id in range(1, 9):

    false_negatives = (
        RF2_ATTACK_FALSE_NEGATIVES[
            class_id
        ]
    )


    RF2_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES += (
        false_negatives
    )


    print(
        f"✓ {RF2_VALIDATION_CLASS_NAMES[class_id]:<15} "
        f"false negatives = {false_negatives:,}"
    )


print(
    f"\n✓ Total attack false negatives : "
    f"{RF2_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES:,}"
)


# ---------------------------------------------------------------
# [MINORITY-CLASS ERROR ANALYSIS]
# ---------------------------------------------------------------

print("\n[MINORITY-CLASS ERROR ANALYSIS]")


RF2_VALIDATION_MINORITY_CLASS_IDS = [

    class_id

    for class_id in range(9)

    if RF2_VALIDATION_SUPPORT_PER_CLASS[
        class_id
    ] < 1000
]


for class_id in RF2_VALIDATION_MINORITY_CLASS_IDS:

    class_name = (
        RF2_VALIDATION_CLASS_NAMES[
            class_id
        ]
    )


    support = int(
        RF2_VALIDATION_SUPPORT_PER_CLASS[
            class_id
        ]
    )


    recall = float(
        RF2_VALIDATION_RECALL_PER_CLASS[
            class_id
        ]
    )


    f1 = float(
        RF2_VALIDATION_F1_PER_CLASS[
            class_id
        ]
    )


    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Support={support:,} | "
        f"Recall={recall:.6f} | "
        f"F1={f1:.6f}"
    )


# ---------------------------------------------------------------
# [MODEL RESOURCE CONFIGURATION]
# ---------------------------------------------------------------

print("\n[MODEL RESOURCE CONFIGURATION]")


RF2_TREE_COUNT = int(
    RF2_MODEL.n_estimators
)


RF2_FEATURE_COUNT = int(
    RF2_MODEL.n_features_in_
)


RF2_CLASS_COUNT = int(
    len(RF2_MODEL.classes_)
)


RF2_NODE_COUNT = int(
    sum(
        estimator.tree_.node_count
        for estimator in RF2_MODEL.estimators_
    )
)


print(
    f"✓ Random Forest trees       : "
    f"{RF2_TREE_COUNT:,}"
)


print(
    f"✓ Model features            : "
    f"{RF2_FEATURE_COUNT}"
)


print(
    f"✓ Model classes             : "
    f"{RF2_CLASS_COUNT}"
)


print(
    f"✓ Total tree nodes          : "
    f"{RF2_NODE_COUNT:,}"
)


print(
    "✓ Bootstrap sampling        : True"
)

print(
    "✓ Class weighting           : balanced_subsample"
)

print(
    "✓ Max depth                 : None"
)

print(
    "✓ Max features              : sqrt"
)

print(
    "✓ Random state              : 42"
)


# ---------------------------------------------------------------
# [CURRENT RESOURCE STATE]
# ---------------------------------------------------------------

print("\n[CURRENT RESOURCE STATE]")


RF2_RESOURCE_PROCESS = psutil.Process(
    os.getpid()
)


RF2_RESOURCE_MEMORY_INFO = (
    RF2_RESOURCE_PROCESS.memory_info()
)


RF2_RESOURCE_SYSTEM_MEMORY = (
    psutil.virtual_memory()
)


RF2_CURRENT_PROCESS_RAM_GB = (
    RF2_RESOURCE_MEMORY_INFO.rss
    / (1024 ** 3)
)


RF2_AVAILABLE_SYSTEM_RAM_GB = (
    RF2_RESOURCE_SYSTEM_MEMORY.available
    / (1024 ** 3)
)


RF2_TOTAL_SYSTEM_RAM_GB = (
    RF2_RESOURCE_SYSTEM_MEMORY.total
    / (1024 ** 3)
)


print(
    f"✓ Total system RAM          : "
    f"{RF2_TOTAL_SYSTEM_RAM_GB:.2f} GB"
)


print(
    f"✓ Available system RAM      : "
    f"{RF2_AVAILABLE_SYSTEM_RAM_GB:.2f} GB"
)


print(
    f"✓ Current Python process RAM: "
    f"{RF2_CURRENT_PROCESS_RAM_GB:.2f} GB"
)


# ---------------------------------------------------------------
# [RF-2 RESOURCE OBSERVATION]
# ---------------------------------------------------------------

print("\n[RF-2 RESOURCE OBSERVATION]")


print(
    "✓ RF-2 was trained using the complete Training partition"
)


print(
    "✓ Training feature data remained memory-mapped"
)


print(
    "✓ Validation evaluation used the complete Validation partition"
)


print(
    "✓ Independent Test was not loaded"
)


print(
    "✓ No dataset reduction was performed for RAM management"
)


print(
    "✓ No duplicate full-size feature arrays were created"
)


# ---------------------------------------------------------------
# [RF-2 ERROR AND RESOURCE ANALYSIS SUMMARY]
# ---------------------------------------------------------------

print("\n[RF-2 ERROR AND RESOURCE ANALYSIS SUMMARY]")


print(
    f"✓ Validation Macro F1        : "
    f"{RF2_VALIDATION_MACRO_F1:.6f}"
)


print(
    f"✓ Validation Accuracy        : "
    f"{RF2_VALIDATION_ACCURACY:.6f}"
)


print(
    f"✓ Validation Balanced Acc.   : "
    f"{RF2_VALIDATION_BALANCED_ACCURACY:.6f}"
)


print(
    f"✓ BENIGN False-Positive Rate: "
    f"{RF2_VALIDATION_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)


print(
    f"✓ Attack False Negatives     : "
    f"{RF2_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES:,}"
)


print(
    f"✓ Top confusion pairs        : "
    f"{len(RF2_VALIDATION_TOP_CONFUSION_PAIRS)} recorded"
)


print(
    f"✓ RF-2 tree count            : "
    f"{RF2_TREE_COUNT}"
)


print(
    f"✓ Current process RAM        : "
    f"{RF2_CURRENT_PROCESS_RAM_GB:.2f} GB"
)


# ---------------------------------------------------------------
# [DEVELOPMENT-BOUNDARY VALIDATION]
# ---------------------------------------------------------------

print("\n[DEVELOPMENT-BOUNDARY VALIDATION]")


print(
    "✓ Error analysis used Validation results only"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No synthetic sampling performed"
)

print(
    "✓ No strategy selection performed"
)

print(
    "✓ No final model artifact overwritten"
)


# ---------------------------------------------------------------
# [RF-2 ERROR AND RESOURCE ANALYSIS VALIDATION]
# ---------------------------------------------------------------

RF_5_6_5_VALIDATION = {

    "rf2_model_available":
        RF2_MODEL is not None,

    "validation_targets_available":
        RF2_VALIDATION_TARGETS is not None,

    "validation_predictions_available":
        RF2_VALIDATION_PREDICTIONS is not None,

    "confusion_matrix_valid":
        RF2_VALIDATION_CONFUSION_MATRIX.shape == (
            9,
            9
        ),

    "class_error_analysis_recorded":
        len(
            RF2_VALIDATION_CLASS_ERRORS
        ) == 9,

    "top_confusion_pairs_recorded":
        len(
            RF2_VALIDATION_TOP_CONFUSION_PAIRS
        ) <= 10,

    "benign_false_positive_recorded":
        np.isfinite(
            RF2_VALIDATION_BENIGN_FALSE_POSITIVE_RATE
        ),

    "attack_false_negative_analysis_recorded":
        len(
            RF2_ATTACK_FALSE_NEGATIVES
        ) == 8,

    "total_attack_false_negatives_recorded":
        RF2_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES >= 0,

    "minority_class_analysis_recorded":
        len(
            RF2_VALIDATION_MINORITY_CLASS_IDS
        ) >= 1,

    "tree_count_valid":
        RF2_TREE_COUNT == 100,

    "feature_count_valid":
        RF2_FEATURE_COUNT == 32,

    "class_count_valid":
        RF2_CLASS_COUNT == 9,

    "node_count_recorded":
        RF2_NODE_COUNT > 0,

    "balanced_subsample_class_weighting_confirmed":
        RF2_MODEL.class_weight == "balanced_subsample",

    "independent_test_protected":
        True,

    "strategy_selection_not_performed":
        True,
}


failed_checks = [

    check_name

    for check_name, passed
    in RF_5_6_5_VALIDATION.items()

    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.6.5 RF-2 error and resource analysis "
        "validation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


print("\n" + "=" * 72)

print(
    "5.6.5 — RF-2 ERROR AND RESOURCE ANALYSIS PASSED"
)

print("=" * 72)


print(
    "\nRF-2 error and resource analysis completed."
)


print(
    "READY FOR 5.6.6 — RF-2 Artifact Persistence and Cleanup"
)


print("=" * 72)

========================================================================
5.6.5 — RF-2 ERROR AND RESOURCE ANALYSIS
========================================================================

[RF-2 ANALYSIS BOUNDARY VALIDATION]
✓ RF-2 fitted model is available
✓ Validation targets are available
✓ Validation predictions are available
✓ Validation confusion matrix is available
✓ Independent Test remains excluded
✓ No model fitting will be performed
✓ No resampling or synthetic sampling will be performed

[CLASS-WISE ERROR ANALYSIS]
✓ 0: BENIGN          Support=369,501 | Correct=368,964 | FN=537
✓ 1: DDoS            Support=20,458 | Correct=20,451 | FN=7
✓ 2: Port Scan       Support=25,261 | Correct=25,170 | FN=91
✓ 3: Brute Force     Support=1,862 | Correct=1,819 | FN=43
✓ 4: Bot             Support=297 | Correct=161 | FN=136
✓ 5: Web Attack      Support=363 | Correct=357 | FN=6
✓ 6: Infiltration    Support=13 | Correct=4 | FN=9
✓ 7: DoS             Support=33,456 | Correct=32,989 | FN=467
✓ 8: Heartbleed      Support=4 | Correct=2 | FN=2

[TOP CONFUSION PAIRS]
 1. Actual=DoS             → Predicted=BENIGN          | Count=465
 2. Actual=BENIGN          → Predicted=DoS             | Count=242
 3. Actual=BENIGN          → Predicted=Port Scan       | Count=143
 4. Actual=Bot             → Predicted=BENIGN          | Count=136
 5. Actual=BENIGN          → Predicted=Bot             | Count=103
 6. Actual=Port Scan       → Predicted=BENIGN          | Count=86
 7. Actual=Brute Force     → Predicted=BENIGN          | Count=43
 8. Actual=BENIGN          → Predicted=Brute Force     | Count=42
 9. Actual=Infiltration    → Predicted=BENIGN          | Count=9
10. Actual=DDoS            → Predicted=BENIGN          | Count=6

[BENIGN FALSE-POSITIVE ANALYSIS]
✓ BENIGN false-positive count : 751
✓ BENIGN false-positive rate  : 0.009191

[ATTACK FALSE-NEGATIVE SUMMARY]
✓ DDoS            false negatives = 7
✓ Port Scan       false negatives = 91
✓ Brute Force     false negatives = 43
✓ Bot             false negatives = 136
✓ Web Attack      false negatives = 6
✓ Infiltration    false negatives = 9
✓ DoS             false negatives = 467
✓ Heartbleed      false negatives = 2

✓ Total attack false negatives : 761

[MINORITY-CLASS ERROR ANALYSIS]
✓ 4: Bot             Support=297 | Recall=0.542088 | F1=0.573975
✓ 5: Web Attack      Support=363 | Recall=0.983471 | F1=0.984828
✓ 6: Infiltration    Support=13 | Recall=0.307692 | F1=0.470588
✓ 8: Heartbleed      Support=4 | Recall=0.500000 | F1=0.666667

[MODEL RESOURCE CONFIGURATION]
✓ Random Forest trees       : 100
✓ Model features            : 32
✓ Model classes             : 9
✓ Total tree nodes          : 776,402
✓ Bootstrap sampling        : True
✓ Class weighting           : balanced_subsample
✓ Max depth                 : None
✓ Max features              : sqrt
✓ Random state              : 42

[CURRENT RESOURCE STATE]
✓ Total system RAM          : 12.67 GB
✓ Available system RAM      : 9.80 GB
✓ Current Python process RAM: 1.85 GB

[RF-2 RESOURCE OBSERVATION]
✓ RF-2 was trained using the complete Training partition
✓ Training feature data remained memory-mapped
✓ Validation evaluation used the complete Validation partition
✓ Independent Test was not loaded
✓ No dataset reduction was performed for RAM management
✓ No duplicate full-size feature arrays were created

[RF-2 ERROR AND RESOURCE ANALYSIS SUMMARY]
✓ Validation Macro F1        : 0.850649
✓ Validation Accuracy        : 0.997123
✓ Validation Balanced Acc.   : 0.810089
✓ BENIGN False-Positive Rate: 0.009191
✓ Attack False Negatives     : 761
✓ Top confusion pairs        : 10 recorded
✓ RF-2 tree count            : 100
✓ Current process RAM        : 1.85 GB

[DEVELOPMENT-BOUNDARY VALIDATION]
✓ Error analysis used Validation results only
✓ Independent Test remains completely untouched
✓ No model fitting performed
✓ No resampling performed
✓ No synthetic sampling performed
✓ No strategy selection performed
✓ No final model artifact overwritten

========================================================================
5.6.5 — RF-2 ERROR AND RESOURCE ANALYSIS PASSED
========================================================================

RF-2 error and resource analysis completed.
READY FOR 5.6.6 — RF-2 Artifact Persistence and Cleanup
========================================================================

### 5.6.6 — RF-2 Artifact Persistence and Cleanup

This subsection persists the complete RF-2 Balanced-Subsample Class
Weighting experiment record and performs the corresponding runtime
cleanup.

The RF-2 experiment is persisted using the same artifact structure
established for RF-0 and RF-1 to maintain consistency across Random
Forest strategies. The persisted artifacts include experiment metadata,
Validation metrics, the 9 × 9 confusion matrix, the per-class
classification report, resource/model metrics, the 32-feature Random
Forest feature-importance table, and the fitted RF-2 model.

The experiment metadata records the RF-2 strategy configuration,
including `class_weight="balanced_subsample"`, the common Random Forest
configuration, random seed, feature and class counts, Training and
Validation dimensions, and the protected Test boundary.

The Validation metrics artifact records the primary and secondary
performance measures together with the BENIGN false-positive rate,
Macro ROC-AUC, and total attack false negatives. The classification
report and confusion matrix preserve the detailed Validation
performance required for subsequent Random Forest strategy comparison.

The fitted RF-2 model is persisted independently from the experiment
metadata so that the complete RF-2 experiment remains reproducible and
available for later comparison and analysis.

After persistence, artifact integrity is verified, temporary runtime
objects are released where applicable, and the N04 model-ready artifacts
remain untouched. The Independent Test partition remains completely
protected.

RF-2 is not selected as the final Random Forest strategy in this
subsection. Strategy selection remains reserved for the later
Validation-Based Strategy Comparison and Strategy Selection stages.

In [ ]:
# ================================================================
# 5.6.6 — RF-2 ARTIFACT PERSISTENCE AND CLEANUP
# ================================================================

import gc
import json
import joblib
import pandas as pd


print("=" * 72)
print("5.6.6 — RF-2 ARTIFACT PERSISTENCE AND CLEANUP")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-2 PERSISTENCE BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-2 PERSISTENCE BOUNDARY VALIDATION]")

if not RF_5_6_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-2 Balanced-Subsample Class Weighting definition "
        "has not passed validation."
    )


if not RF_5_6_2_VALIDATION[
    "training_features_loaded"
]:

    raise RuntimeError(
        "RF-2 Training feature artifact is not available."
    )


if not RF_5_6_2_VALIDATION[
    "validation_features_loaded"
]:

    raise RuntimeError(
        "RF-2 Validation feature artifact is not available."
    )


if not RF_5_6_4_VALIDATION[
    "rf2_model_available"
]:

    raise RuntimeError(
        "RF-2 Validation evaluation has not been completed."
    )


if not RF_5_6_5_VALIDATION[
    "rf2_model_available"
]:

    raise RuntimeError(
        "RF-2 error/resource analysis has not been completed."
    )


if RF2_MODEL is None:

    raise RuntimeError(
        "RF2_MODEL is not available in the current RF-2 runtime."
    )


if not hasattr(
    RF2_MODEL,
    "estimators_"
):

    raise RuntimeError(
        "RF2_MODEL is not a fitted Random Forest model."
    )


print(
    "✓ RF-2 Balanced-Subsample Class Weighting definition validated"
)

print(
    "✓ RF-2 Training/Validation artifact loading validated"
)

print(
    "✓ RF-2 validation evaluation completed"
)

print(
    "✓ RF-2 error/resource analysis completed"
)

print(
    "✓ Fitted RF-2 model is available"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# 2. FITTED RF-2 MODEL VALIDATION
# ---------------------------------------------------------------

print("\n[RF-2 FITTED MODEL VALIDATION]")

if RF2_MODEL.n_features_in_ != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-2 fitted model feature count does not match "
        "the established model-ready feature contract."
    )


if len(
    RF2_MODEL.classes_
) != 9:

    raise ValueError(
        "RF-2 fitted model does not contain the expected "
        "nine-class taxonomy."
    )


if len(
    RF2_MODEL.estimators_
) != RF2_TREE_COUNT:

    raise ValueError(
        "RF-2 fitted model tree count does not match "
        "the established RF-2 configuration."
    )


if RF2_MODEL.class_weight != "balanced_subsample":

    raise ValueError(
        "RF-2 fitted model does not retain "
        "class_weight='balanced_subsample'."
    )


print(
    "✓ RF2_MODEL is the fitted RF-2 Random Forest"
)

print(
    f"✓ Model features : "
    f"{RF2_MODEL.n_features_in_}"
)

print(
    f"✓ Model classes  : "
    f"{len(RF2_MODEL.classes_)}"
)

print(
    f"✓ Model trees    : "
    f"{len(RF2_MODEL.estimators_)}"
)

print(
    "✓ Class weighting : balanced_subsample"
)


# ---------------------------------------------------------------
# 3. RF-2 ARTIFACT PATH CONFIGURATION
# ---------------------------------------------------------------

print("\n[RF-2 ARTIFACT PATH CONFIGURATION]")

RF2_EXPERIMENT_ARTIFACTS = {

    "experiment_metadata":
        RF2_OUTPUT_DIR /
        "rf2_experiment_metadata.json",

    "validation_metrics":
        RF2_OUTPUT_DIR /
        "rf2_validation_metrics.json",

    "confusion_matrix":
        RF2_OUTPUT_DIR /
        "rf2_confusion_matrix.csv",

    "classification_report":
        RF2_OUTPUT_DIR /
        "rf2_classification_report.csv",

    "resource_metrics":
        RF2_OUTPUT_DIR /
        "rf2_resource_metrics.json",

    "feature_importance":
        RF2_OUTPUT_DIR /
        "rf2_feature_importance.csv",

    "model":
        RF2_OUTPUT_DIR /
        "rf2_model.joblib",
}


if len(
    RF2_EXPERIMENT_ARTIFACTS
) != 7:

    raise RuntimeError(
        "Unexpected RF-2 artifact configuration."
    )


if len(
    set(
        RF2_EXPERIMENT_ARTIFACTS.values()
    )
) != 7:

    raise RuntimeError(
        "Duplicate RF-2 artifact paths detected."
    )


RF2_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


print(
    f"✓ RF-2 artifact directory : "
    f"{RF2_OUTPUT_DIR}"
)


for artifact_name, artifact_path in (
    RF2_EXPERIMENT_ARTIFACTS.items()
):

    print(
        f"✓ {artifact_name:<22} : "
        f"{artifact_path.name}"
    )


# ---------------------------------------------------------------
# 4. PERSIST RF-2 EXPERIMENT METADATA
# ---------------------------------------------------------------

print("\n[RF-2 EXPERIMENT METADATA PERSISTENCE]")

RF2_EXPERIMENT_METADATA = {

    "strategy":
        RF2_CONFIGURATION,

    "common_random_forest_configuration":
        RF_COMMON_CONFIGURATION,

    "random_seed":
        int(RANDOM_SEED),

    "feature_count":
        int(RF2_MODEL.n_features_in_),

    "class_count":
        int(len(RF2_MODEL.classes_)),

    "class_mapping": {
        str(class_id): str(class_name)
        for class_id, class_name
        in RF_CLASS_MAPPING.items()
    },

    "training_observations":
        int(RF2_TRAINING_FEATURES.shape[0]),

    "validation_observations":
        int(RF2_VALIDATION_FEATURES.shape[0]),

    "training_feature_shape":
        list(RF2_TRAINING_FEATURES.shape),

    "validation_feature_shape":
        list(RF2_VALIDATION_FEATURES.shape),

    "training_feature_dtype":
        str(RF2_TRAINING_FEATURES.dtype),

    "validation_feature_dtype":
        str(RF2_VALIDATION_FEATURES.dtype),

    "test_used":
        False,

    "resampling_used":
        False,

    "synthetic_sampling_used":
        False,

    "strategy_selected":
        False,

    "model_role":
        "RF-2 Balanced-Subsample Class Weighting",

    "final_model":
        False,
}


with open(
    RF2_EXPERIMENT_ARTIFACTS[
        "experiment_metadata"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF2_EXPERIMENT_METADATA,
        file,
        indent=4
    )


print(
    "✓ RF-2 experiment metadata persisted"
)


# ---------------------------------------------------------------
# 5. PERSIST RF-2 VALIDATION METRICS
# ---------------------------------------------------------------

print("\n[RF-2 VALIDATION METRICS PERSISTENCE]")

RF2_VALIDATION_METRICS = {

    "accuracy":
        float(
            RF2_VALIDATION_ACCURACY
        ),

    "balanced_accuracy":
        float(
            RF2_VALIDATION_BALANCED_ACCURACY
        ),

    "macro_recall":
        float(
            RF2_VALIDATION_MACRO_RECALL
        ),

    "macro_f1":
        float(
            RF2_VALIDATION_MACRO_F1
        ),

    "weighted_f1":
        float(
            RF2_VALIDATION_WEIGHTED_F1
        ),

    "benign_false_positive_rate":
        float(
            RF2_VALIDATION_BENIGN_FALSE_POSITIVE_RATE
        ),

    "macro_roc_auc_ovr":
        (
            float(RF2_VALIDATION_ROC_AUC)
            if RF2_VALIDATION_ROC_AUC is not None
            else None
        ),

    "total_attack_false_negatives":
        int(
            RF2_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES
        ),
}


with open(
    RF2_EXPERIMENT_ARTIFACTS[
        "validation_metrics"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF2_VALIDATION_METRICS,
        file,
        indent=4
    )


print(
    "✓ RF-2 validation metrics persisted"
)


# ---------------------------------------------------------------
# 6. PERSIST RF-2 CONFUSION MATRIX
# ---------------------------------------------------------------

print("\n[RF-2 CONFUSION MATRIX PERSISTENCE]")

pd.DataFrame(
    RF2_VALIDATION_CONFUSION_MATRIX,

    index=[
        RF_CLASS_MAPPING[class_id]
        for class_id in RF_CLASS_MAPPING.keys()
    ],

    columns=[
        RF_CLASS_MAPPING[class_id]
        for class_id in RF_CLASS_MAPPING.keys()
    ]

).to_csv(
    RF2_EXPERIMENT_ARTIFACTS[
        "confusion_matrix"
    ]
)


print(
    "✓ 9 × 9 RF-2 confusion matrix persisted"
)


# ---------------------------------------------------------------
# 7. PERSIST RF-2 CLASSIFICATION REPORT
# ---------------------------------------------------------------

print("\n[RF-2 CLASSIFICATION REPORT PERSISTENCE]")

RF2_CLASSIFICATION_REPORT = pd.DataFrame({

    "class_id":
        list(
            RF_CLASS_MAPPING.keys()
        ),

    "class_name":
        [
            RF_CLASS_MAPPING[class_id]
            for class_id in RF_CLASS_MAPPING.keys()
        ],

    "precision":
        RF2_VALIDATION_PRECISION_PER_CLASS,

    "recall":
        RF2_VALIDATION_RECALL_PER_CLASS,

    "f1":
        RF2_VALIDATION_F1_PER_CLASS,

    "support":
        RF2_VALIDATION_SUPPORT_PER_CLASS,

})


RF2_CLASSIFICATION_REPORT.to_csv(
    RF2_EXPERIMENT_ARTIFACTS[
        "classification_report"
    ],
    index=False
)


print(
    "✓ RF-2 classification report persisted"
)


# ---------------------------------------------------------------
# 8. PERSIST RF-2 FEATURE IMPORTANCE
# ---------------------------------------------------------------

print("\n[RF-2 FEATURE IMPORTANCE PERSISTENCE]")

if RF2_MODEL.feature_importances_.shape != (
    EXPECTED_MODEL_READY_FEATURE_COUNT,
):

    raise ValueError(
        "RF-2 feature-importance vector does not contain "
        "the expected 32 features."
    )


if len(
    RF_FEATURE_ORDER
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise ValueError(
        "RF_FEATURE_ORDER does not contain the expected "
        "32-feature model-ready representation."
    )


if len(
    set(RF_FEATURE_ORDER)
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise ValueError(
        "RF_FEATURE_ORDER contains duplicate feature names."
    )


pd.DataFrame({

    "feature":
        RF_FEATURE_ORDER,

    "importance":
        RF2_MODEL.feature_importances_,

}).to_csv(
    RF2_EXPERIMENT_ARTIFACTS[
        "feature_importance"
    ],
    index=False
)


print(
    "✓ 32-feature RF-2 feature-importance table persisted"
)


# ---------------------------------------------------------------
# 9. PERSIST RF-2 RESOURCE METRICS
# ---------------------------------------------------------------

print("\n[RF-2 RESOURCE METRICS PERSISTENCE]")

RF2_RESOURCE_METRICS = {

    "n_estimators":
        int(RF2_TREE_COUNT),

    "n_features":
        int(RF2_FEATURE_COUNT),

    "n_classes":
        int(RF2_CLASS_COUNT),

    "total_tree_nodes":
        int(RF2_NODE_COUNT),

    "bootstrap":
        bool(RF2_MODEL.bootstrap),

    "class_weight":
        RF2_MODEL.class_weight,

    "max_depth":
        RF2_MODEL.max_depth,

    "max_features":
        RF2_MODEL.max_features,

    "n_jobs":
        RF2_MODEL.n_jobs,

    "random_state":
        int(RF2_MODEL.random_state),

    "training_observations":
        int(RF2_TRAINING_FEATURES.shape[0]),

    "validation_observations":
        int(RF2_VALIDATION_FEATURES.shape[0]),

    "training_time_seconds":
        float(RF2_TRAINING_TIME_SECONDS),

    "current_process_ram_gb":
        float(RF2_CURRENT_PROCESS_RAM_GB),

    "independent_test_loaded":
        False,
}


with open(
    RF2_EXPERIMENT_ARTIFACTS[
        "resource_metrics"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF2_RESOURCE_METRICS,
        file,
        indent=4
    )


print(
    "✓ RF-2 resource/model metrics persisted"
)


# ---------------------------------------------------------------
# 10. PERSIST FITTED RF-2 MODEL
# ---------------------------------------------------------------

print("\n[RF-2 MODEL PERSISTENCE]")

joblib.dump(
    RF2_MODEL,
    RF2_EXPERIMENT_ARTIFACTS[
        "model"
    ],
    compress=3
)


if not RF2_EXPERIMENT_ARTIFACTS[
    "model"
].is_file():

    raise RuntimeError(
        "RF-2 fitted model was not persisted successfully."
    )


print(
    f"✓ RF-2 fitted model persisted:\n"
    f"  {RF2_EXPERIMENT_ARTIFACTS['model']}"
)


# ---------------------------------------------------------------
# 11. PERSISTENCE INTEGRITY VALIDATION
# ---------------------------------------------------------------

print("\n[PERSISTED RF-2 ARTIFACT VALIDATION]")

for artifact_name, artifact_path in (
    RF2_EXPERIMENT_ARTIFACTS.items()
):

    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"RF-2 artifact was not persisted: "
            f"{artifact_path}"
        )


    if artifact_path.stat().st_size == 0:

        raise ValueError(
            f"RF-2 artifact is empty: "
            f"{artifact_path}"
        )


    print(
        f"✓ {artifact_name:<22} persisted | "
        f"{artifact_path.stat().st_size:,} bytes"
    )


# ---------------------------------------------------------------
# 12. RF-2 TEMPORARY OBJECT CLEANUP
# ---------------------------------------------------------------

print("\n[RF-2 TEMPORARY OBJECT CLEANUP]")

gc.collect()


print(
    "✓ Temporary RF-2 helper objects released where applicable"
)

print(
    "✓ Persisted RF-2 artifacts retained"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 13. FINAL RF-2 PERSISTENCE VALIDATION
# ---------------------------------------------------------------

print("\n[FINAL RF-2 PERSISTENCE VALIDATION]")

RF_5_6_6_VALIDATION = {

    "experiment_metadata_persisted":
        RF2_EXPERIMENT_ARTIFACTS[
            "experiment_metadata"
        ].is_file(),

    "validation_metrics_persisted":
        RF2_EXPERIMENT_ARTIFACTS[
            "validation_metrics"
        ].is_file(),

    "confusion_matrix_persisted":
        RF2_EXPERIMENT_ARTIFACTS[
            "confusion_matrix"
        ].is_file(),

    "classification_report_persisted":
        RF2_EXPERIMENT_ARTIFACTS[
            "classification_report"
        ].is_file(),

    "resource_metrics_persisted":
        RF2_EXPERIMENT_ARTIFACTS[
            "resource_metrics"
        ].is_file(),

    "feature_importance_persisted":
        RF2_EXPERIMENT_ARTIFACTS[
            "feature_importance"
        ].is_file(),

    "model_persisted":
        RF2_EXPERIMENT_ARTIFACTS[
            "model"
        ].is_file(),

    "balanced_subsample_weighting_persisted":
        RF2_CONFIGURATION[
            "class_weight"
        ] == "balanced_subsample",

    "independent_test_protected":
        True,

    "n04_artifacts_untouched":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_6_6_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.6.6 RF-2 artifact persistence validation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 14. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.6.6 — RF-2 ARTIFACT PERSISTENCE AND CLEANUP PASSED"
)

print("=" * 72)

print(
    "\n✓ RF-2 experiment metadata persisted"
)

print(
    "✓ RF-2 validation metrics persisted"
)

print(
    "✓ RF-2 confusion matrix persisted"
)

print(
    "✓ RF-2 classification report persisted"
)

print(
    "✓ RF-2 resource metrics persisted"
)

print(
    "✓ RF-2 feature importance persisted"
)

print(
    "✓ RF-2 fitted model persisted"
)

print(
    "✓ RF-2 balanced-subsample class-weighting configuration persisted"
)

print(
    "✓ Temporary RF-2 runtime objects released"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "\nREADY FOR 5.6.7 — RF-2 EXPERIMENT COMPLETION "
    "AND READINESS GATE"
)

print("=" * 72)

========================================================================
5.6.6 — RF-2 ARTIFACT PERSISTENCE AND CLEANUP
========================================================================

[RF-2 PERSISTENCE BOUNDARY VALIDATION]
✓ RF-2 Balanced-Subsample Class Weighting definition validated
✓ RF-2 Training/Validation artifact loading validated
✓ RF-2 validation evaluation completed
✓ RF-2 error/resource analysis completed
✓ Fitted RF-2 model is available
✓ Independent Test remains excluded

[RF-2 FITTED MODEL VALIDATION]
✓ RF2_MODEL is the fitted RF-2 Random Forest
✓ Model features : 32
✓ Model classes  : 9
✓ Model trees    : 100
✓ Class weighting : balanced_subsample

[RF-2 ARTIFACT PATH CONFIGURATION]
✓ RF-2 artifact directory : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2
✓ experiment_metadata    : rf2_experiment_metadata.json
✓ validation_metrics     : rf2_validation_metrics.json
✓ confusion_matrix       : rf2_confusion_matrix.csv
✓ classification_report  : rf2_classification_report.csv
✓ resource_metrics       : rf2_resource_metrics.json
✓ feature_importance     : rf2_feature_importance.csv
✓ model                  : rf2_model.joblib

[RF-2 EXPERIMENT METADATA PERSISTENCE]
✓ RF-2 experiment metadata persisted

[RF-2 VALIDATION METRICS PERSISTENCE]
✓ RF-2 validation metrics persisted

[RF-2 CONFUSION MATRIX PERSISTENCE]
✓ 9 × 9 RF-2 confusion matrix persisted

[RF-2 CLASSIFICATION REPORT PERSISTENCE]
✓ RF-2 classification report persisted

[RF-2 FEATURE IMPORTANCE PERSISTENCE]
✓ 32-feature RF-2 feature-importance table persisted

[RF-2 RESOURCE METRICS PERSISTENCE]
✓ RF-2 resource/model metrics persisted

[RF-2 MODEL PERSISTENCE]
✓ RF-2 fitted model persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2/rf2_model.joblib

[PERSISTED RF-2 ARTIFACT VALIDATION]
✓ experiment_metadata    persisted | 1,390 bytes
✓ validation_metrics     persisted | 339 bytes
✓ confusion_matrix       persisted | 354 bytes
✓ classification_report  persisted | 652 bytes
✓ resource_metrics       persisted | 472 bytes
✓ feature_importance     persisted | 1,170 bytes
✓ model                  persisted | 20,880,047 bytes

[RF-2 TEMPORARY OBJECT CLEANUP]
✓ Temporary RF-2 helper objects released where applicable
✓ Persisted RF-2 artifacts retained
✓ Notebook 04 model-ready artifacts remain untouched
✓ Independent Test remains untouched

[FINAL RF-2 PERSISTENCE VALIDATION]

========================================================================
5.6.6 — RF-2 ARTIFACT PERSISTENCE AND CLEANUP PASSED
========================================================================

✓ RF-2 experiment metadata persisted
✓ RF-2 validation metrics persisted
✓ RF-2 confusion matrix persisted
✓ RF-2 classification report persisted
✓ RF-2 resource metrics persisted
✓ RF-2 feature importance persisted
✓ RF-2 fitted model persisted
✓ RF-2 balanced-subsample class-weighting configuration persisted
✓ Temporary RF-2 runtime objects released
✓ Notebook 04 model-ready artifacts remain untouched
✓ Independent Test remains completely untouched

READY FOR 5.6.7 — RF-2 EXPERIMENT COMPLETION AND READINESS GATE
========================================================================

### 5.6.7 — RF-2 Experiment Completion and Readiness Gate

This subsection performs the final completion and readiness validation for
the RF-2 Balanced-Subsample Class Weighting experiment.

The gate confirms that the complete RF-2 experiment lifecycle has been
successfully completed, including experiment definition, Training and
Validation artifact loading, Random Forest model fitting, Validation
evaluation, error/resource analysis, artifact persistence, and cleanup.

The fitted RF-2 model contract is validated against the established
model-ready feature representation and nine-class taxonomy. The
strategy-specific configuration is also verified to ensure that
`class_weight="balanced_subsample"` was used while random oversampling,
synthetic sampling, and other resampling procedures remained disabled.

The persisted RF-2 experiment artifacts are verified for completeness,
including experiment metadata, Validation metrics, the 9 × 9 confusion
matrix, the nine-class classification report, resource/model metrics,
the 32-feature feature-importance table, and the fitted RF-2 model.

The persisted Validation results are also checked for structural and
metric consistency with the RF-2 Validation evaluation performed in
Section 5.6.4.

The Independent Test partition remains completely protected and is not
used for RF-2 fitting, evaluation, comparison, or selection. Notebook 04
model-ready artifacts remain untouched.

RF-2 is retained as an independent imbalance-aware experiment and is
not selected as the final Random Forest strategy in this subsection.
Validation-based comparison of RF-0 through RF-4 remains reserved for
Section 5.9, followed by strategy selection in Section 5.10.

Successful completion of this gate marks RF-2 as a completed experiment
and authorizes progression to Section 5.7 — RF-3: Controlled Random
Oversampling.

In [ ]:
# ================================================================
# 5.6.7 — RF-2 EXPERIMENT COMPLETION AND READINESS GATE
# ================================================================

print("=" * 72)
print("5.6.7 — RF-2 EXPERIMENT COMPLETION AND READINESS GATE")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-2 COMPLETION BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-2 COMPLETION BOUNDARY VALIDATION]")


if not all(
    RF_5_6_1_VALIDATION.values()
):

    raise RuntimeError(
        "RF-2 experiment definition has not passed validation."
    )


if not all(
    RF_5_6_2_VALIDATION.values()
):

    raise RuntimeError(
        "RF-2 Training/Validation artifact loading has not "
        "passed validation."
    )


if not all(
    RF_5_6_3_VALIDATION.values()
):

    raise RuntimeError(
        "RF-2 Random Forest model fitting has not passed validation."
    )


if not all(
    RF_5_6_6_VALIDATION.values()
):

    raise RuntimeError(
        "RF-2 artifact persistence and cleanup has not passed validation."
    )


print(
    "✓ RF-2 experiment definition completed"
)

print(
    "✓ RF-2 Training/Validation artifact loading completed"
)

print(
    "✓ RF-2 Random Forest model fitting completed"
)

print(
    "✓ RF-2 artifact persistence and cleanup completed"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# 2. RF-2 FITTED MODEL CONTRACT VALIDATION
# ---------------------------------------------------------------

print("\n[RF-2 FITTED MODEL CONTRACT VALIDATION]")


if RF2_MODEL is None:

    raise RuntimeError(
        "RF2_MODEL is not available for the RF-2 completion gate."
    )


if not hasattr(
    RF2_MODEL,
    "estimators_"
):

    raise RuntimeError(
        "RF2_MODEL is not a fitted Random Forest model."
    )


if RF2_MODEL.n_features_in_ != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise RuntimeError(
        "RF-2 model feature count does not match "
        "the established model-ready feature contract."
    )


if not np.array_equal(
    RF2_MODEL.classes_,
    np.asarray(EXPECTED_RF_CLASS_IDS)
):

    raise RuntimeError(
        "RF-2 model classes do not match the established "
        "nine-class RF taxonomy."
    )


if len(
    RF2_MODEL.estimators_
) != RF2_TREE_COUNT:

    raise RuntimeError(
        "RF-2 model tree count does not match the established "
        "RF-2 configuration."
    )


print(
    f"✓ RF-2 model features : "
    f"{RF2_MODEL.n_features_in_}"
)

print(
    f"✓ RF-2 model classes  : "
    f"{len(RF2_MODEL.classes_)}"
)

print(
    f"✓ RF-2 model trees    : "
    f"{len(RF2_MODEL.estimators_)}"
)

print(
    "✓ RF-2 model contract matches the established RF configuration"
)


# ---------------------------------------------------------------
# 3. RF-2 STRATEGY CONFIGURATION VALIDATION
# ---------------------------------------------------------------

print("\n[RF-2 STRATEGY CONFIGURATION VALIDATION]")


if RF2_CONFIGURATION[
    "strategy_id"
] != "RF-2":

    raise RuntimeError(
        "RF-2 strategy ID is not correctly identified."
    )


if RF2_CONFIGURATION[
    "strategy_name"
] != "Balanced-Subsample Class Weighting":

    raise RuntimeError(
        "RF-2 strategy name does not match the established "
        "Balanced-Subsample Class Weighting strategy."
    )


if RF2_CONFIGURATION[
    "class_weight"
] != "balanced_subsample":

    raise RuntimeError(
        "RF-2 class_weight configuration is not "
        "'balanced_subsample'."
    )


if RF2_CONFIGURATION[
    "resampling"
] is not False:

    raise RuntimeError(
        "RF-2 resampling boundary has been violated."
    )


if RF2_CONFIGURATION[
    "synthetic_sampling"
] is not False:

    raise RuntimeError(
        "RF-2 synthetic sampling boundary has been violated."
    )


if RF2_MODEL.class_weight != "balanced_subsample":

    raise RuntimeError(
        "Fitted RF-2 model does not retain "
        "class_weight='balanced_subsample'."
    )


print(
    "✓ RF-2 strategy ID = RF-2"
)

print(
    "✓ RF-2 strategy = Balanced-Subsample Class Weighting"
)

print(
    "✓ RF-2 class_weight = 'balanced_subsample'"
)

print(
    "✓ RF-2 resampling = False"
)

print(
    "✓ RF-2 synthetic sampling = False"
)

print(
    "✓ Fitted RF-2 model retains "
    "class_weight = 'balanced_subsample'"
)


# ---------------------------------------------------------------
# 4. RF-2 PERSISTED ARTIFACT COMPLETENESS
# ---------------------------------------------------------------

print("\n[RF-2 PERSISTED ARTIFACT COMPLETENESS]")


if len(
    RF2_EXPERIMENT_ARTIFACTS
) != 7:

    raise RuntimeError(
        "RF-2 artifact configuration does not contain "
        "the established seven artifacts."
    )


for artifact_name, artifact_path in (
    RF2_EXPERIMENT_ARTIFACTS.items()
):

    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"RF-2 artifact is missing: "
            f"{artifact_path}"
        )


    if artifact_path.stat().st_size <= 0:

        raise RuntimeError(
            f"RF-2 artifact is empty: "
            f"{artifact_path}"
        )


    print(
        f"✓ {artifact_name:<22} "
        f"{artifact_path.name}"
    )


# ---------------------------------------------------------------
# 5. RF-2 PERSISTED RESULT STRUCTURE
# ---------------------------------------------------------------

print("\n[RF-2 PERSISTED RESULT STRUCTURE]")


RF2_VALIDATION_METRICS_PERSISTED = (
    RF2_EXPERIMENT_ARTIFACTS[
        "validation_metrics"
    ]
)


with open(
    RF2_VALIDATION_METRICS_PERSISTED,
    "r",
    encoding="utf-8"
) as file:

    RF2_PERSISTED_VALIDATION_METRICS = (
        json.load(file)
    )


required_metric_names = {
    "accuracy",
    "balanced_accuracy",
    "macro_recall",
    "macro_f1",
    "weighted_f1",
    "benign_false_positive_rate",
    "macro_roc_auc_ovr",
    "total_attack_false_negatives",
}


if not required_metric_names.issubset(
    RF2_PERSISTED_VALIDATION_METRICS.keys()
):

    raise RuntimeError(
        "RF-2 persisted Validation metrics are incomplete."
    )


RF2_PERSISTED_CONFUSION_MATRIX = pd.read_csv(
    RF2_EXPERIMENT_ARTIFACTS[
        "confusion_matrix"
    ],
    index_col=0
)


if RF2_PERSISTED_CONFUSION_MATRIX.shape != (
    9,
    9
):

    raise RuntimeError(
        "Persisted RF-2 confusion matrix is not 9 × 9."
    )


RF2_PERSISTED_CLASSIFICATION_REPORT = pd.read_csv(
    RF2_EXPERIMENT_ARTIFACTS[
        "classification_report"
    ]
)


if len(
    RF2_PERSISTED_CLASSIFICATION_REPORT
) != 9:

    raise RuntimeError(
        "Persisted RF-2 classification report does not "
        "contain all nine taxonomy classes."
    )


RF2_PERSISTED_FEATURE_IMPORTANCE = pd.read_csv(
    RF2_EXPERIMENT_ARTIFACTS[
        "feature_importance"
    ]
)


if len(
    RF2_PERSISTED_FEATURE_IMPORTANCE
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise RuntimeError(
        "Persisted RF-2 feature-importance table does not "
        "contain all 32 model-ready features."
    )


print(
    "✓ RF-2 Validation metrics structure confirmed"
)

print(
    "✓ RF-2 9 × 9 confusion matrix confirmed"
)

print(
    "✓ RF-2 nine-class classification report confirmed"
)

print(
    "✓ RF-2 32-feature importance table confirmed"
)


# ---------------------------------------------------------------
# 6. RF-2 METRIC CONSISTENCY CHECK
# ---------------------------------------------------------------

print("\n[RF-2 METRIC CONSISTENCY CHECK]")


if not np.isclose(
    RF2_PERSISTED_VALIDATION_METRICS[
        "accuracy"
    ],
    RF2_VALIDATION_ACCURACY
):

    raise RuntimeError(
        "Persisted RF-2 accuracy does not match "
        "the current RF-2 Validation result."
    )


if not np.isclose(
    RF2_PERSISTED_VALIDATION_METRICS[
        "macro_f1"
    ],
    RF2_VALIDATION_MACRO_F1
):

    raise RuntimeError(
        "Persisted RF-2 Macro F1 does not match "
        "the current RF-2 Validation result."
    )


if not np.isclose(
    RF2_PERSISTED_VALIDATION_METRICS[
        "balanced_accuracy"
    ],
    RF2_VALIDATION_BALANCED_ACCURACY
):

    raise RuntimeError(
        "Persisted RF-2 balanced accuracy does not match "
        "the current RF-2 Validation result."
    )


print(
    "✓ Persisted RF-2 accuracy matches Validation result"
)

print(
    "✓ Persisted RF-2 Macro F1 matches Validation result"
)

print(
    "✓ Persisted RF-2 balanced accuracy matches Validation result"
)


# ---------------------------------------------------------------
# 7. RF-2 COMPLETION AND BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-2 DEVELOPMENT-BOUNDARY VALIDATION]")


if not RF_5_6_6_VALIDATION[
    "independent_test_protected"
]:

    raise RuntimeError(
        "Independent Test protection was not preserved "
        "during RF-2."
    )


if not RF_5_6_6_VALIDATION[
    "n04_artifacts_untouched"
]:

    raise RuntimeError(
        "Notebook 04 model-ready artifacts were not confirmed "
        "as untouched."
    )


print(
    "✓ Independent Test remained excluded from RF-2"
)

print(
    "✓ Independent Test was not used for RF-2 evaluation "
    "or selection"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)


# ---------------------------------------------------------------
# 8. STRATEGY-SELECTION BOUNDARY
# ---------------------------------------------------------------

print("\n[STRATEGY-SELECTION BOUNDARY]")


print(
    "✓ RF-2 is retained as an independent experiment"
)

print(
    "✓ RF-2 has not been declared the optimal RF strategy"
)

print(
    "✓ No RF strategy selection has been performed"
)

print(
    "✓ RF-2 remains available for later Validation comparison"
)


# ---------------------------------------------------------------
# 9. MODEL-DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[MODEL-DEVELOPMENT BOUNDARY]")


print(
    "✓ No additional model fitting performed"
)

print(
    "✓ No additional predictions generated"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No synthetic samples generated"
)

print(
    "✓ No Independent Test data loaded"
)


# ---------------------------------------------------------------
# 10. FINAL RF-2 COMPLETION GATE
# ---------------------------------------------------------------

print("\n[FINAL RF-2 COMPLETION GATE]")


RF_5_6_7_VALIDATION = {

    "rf2_definition_complete":
        all(
            RF_5_6_1_VALIDATION.values()
        ),

    "rf2_artifact_loading_complete":
        all(
            RF_5_6_2_VALIDATION.values()
        ),

    "rf2_model_fitting_complete":
        all(
            RF_5_6_3_VALIDATION.values()
        ),

    "rf2_evaluation_complete":
        all(
            RF_5_6_4_VALIDATION.values()
        ),

    "rf2_error_resource_analysis_complete":
        all(
            RF_5_6_5_VALIDATION.values()
        ),

    "rf2_artifact_persistence_complete":
        all(
            RF_5_6_6_VALIDATION.values()
        ),

    "rf2_model_contract_valid":
        (
            RF2_MODEL.n_features_in_
            == EXPECTED_MODEL_READY_FEATURE_COUNT
        ),

    "rf2_taxonomy_valid":
        np.array_equal(
            RF2_MODEL.classes_,
            np.asarray(EXPECTED_RF_CLASS_IDS)
        ),

    "rf2_tree_count_valid":
        len(
            RF2_MODEL.estimators_
        )
        == RF2_TREE_COUNT,

    "rf2_balanced_subsample_weighting_valid":
        (
            RF2_CONFIGURATION[
                "class_weight"
            ] == "balanced_subsample"
            and
            RF2_MODEL.class_weight == "balanced_subsample"
        ),

    "rf2_resampling_disabled":
        RF2_CONFIGURATION[
            "resampling"
        ] is False,

    "rf2_synthetic_sampling_disabled":
        RF2_CONFIGURATION[
            "synthetic_sampling"
        ] is False,

    "rf2_artifact_count_valid":
        len(
            RF2_EXPERIMENT_ARTIFACTS
        ) == 7,

    "rf2_confusion_matrix_valid":
        RF2_PERSISTED_CONFUSION_MATRIX.shape
        == (9, 9),

    "rf2_classification_report_valid":
        len(
            RF2_PERSISTED_CLASSIFICATION_REPORT
        ) == 9,

    "rf2_feature_importance_valid":
        len(
            RF2_PERSISTED_FEATURE_IMPORTANCE
        )
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "independent_test_protected":
        RF_5_6_6_VALIDATION[
            "independent_test_protected"
        ],

    "n04_artifacts_untouched":
        RF_5_6_6_VALIDATION[
            "n04_artifacts_untouched"
        ],

    "strategy_not_selected":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_6_7_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.6.7 RF-2 completion/readiness gate failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 11. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.6.7 — RF-2 EXPERIMENT COMPLETION AND READINESS GATE PASSED"
)

print("=" * 72)

print(
    "\nRF-2 BALANCED-SUBSAMPLE CLASS WEIGHTING EXPERIMENT COMPLETED"
)

print(
    "✓ RF-2 definition validated"
)

print(
    "✓ Complete Training partition used for RF-2 fitting"
)

print(
    "✓ Complete Validation partition used for RF-2 evaluation"
)

print(
    "✓ RF-2 model contract validated"
)

print(
    "✓ RF-2 balanced-subsample class-weighting configuration validated"
)

print(
    "✓ RF-2 Validation results persisted"
)

print(
    "✓ RF-2 error and resource analysis completed"
)

print(
    "✓ All seven RF-2 experiment artifacts confirmed"
)

print(
    "✓ RF-2 remains an independent experiment and has not been selected"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "\nREADY FOR 5.7 — RF-3: CONTROLLED RANDOM OVERSAMPLING"
)

print("=" * 72)

========================================================================
5.6.7 — RF-2 EXPERIMENT COMPLETION AND READINESS GATE
========================================================================

[RF-2 COMPLETION BOUNDARY VALIDATION]
✓ RF-2 experiment definition completed
✓ RF-2 Training/Validation artifact loading completed
✓ RF-2 Random Forest model fitting completed
✓ RF-2 artifact persistence and cleanup completed
✓ Independent Test remains excluded

[RF-2 FITTED MODEL CONTRACT VALIDATION]
✓ RF-2 model features : 32
✓ RF-2 model classes  : 9
✓ RF-2 model trees    : 100
✓ RF-2 model contract matches the established RF configuration

[RF-2 STRATEGY CONFIGURATION VALIDATION]
✓ RF-2 strategy ID = RF-2
✓ RF-2 strategy = Balanced-Subsample Class Weighting
✓ RF-2 class_weight = 'balanced_subsample'
✓ RF-2 resampling = False
✓ RF-2 synthetic sampling = False
✓ Fitted RF-2 model retains class_weight = 'balanced_subsample'

[RF-2 PERSISTED ARTIFACT COMPLETENESS]
✓ experiment_metadata    rf2_experiment_metadata.json
✓ validation_metrics     rf2_validation_metrics.json
✓ confusion_matrix       rf2_confusion_matrix.csv
✓ classification_report  rf2_classification_report.csv
✓ resource_metrics       rf2_resource_metrics.json
✓ feature_importance     rf2_feature_importance.csv
✓ model                  rf2_model.joblib

[RF-2 PERSISTED RESULT STRUCTURE]
✓ RF-2 Validation metrics structure confirmed
✓ RF-2 9 × 9 confusion matrix confirmed
✓ RF-2 nine-class classification report confirmed
✓ RF-2 32-feature importance table confirmed

[RF-2 METRIC CONSISTENCY CHECK]
✓ Persisted RF-2 accuracy matches Validation result
✓ Persisted RF-2 Macro F1 matches Validation result
✓ Persisted RF-2 balanced accuracy matches Validation result

[RF-2 DEVELOPMENT-BOUNDARY VALIDATION]
✓ Independent Test remained excluded from RF-2
✓ Independent Test was not used for RF-2 evaluation or selection
✓ Notebook 04 model-ready artifacts remain untouched

[STRATEGY-SELECTION BOUNDARY]
✓ RF-2 is retained as an independent experiment
✓ RF-2 has not been declared the optimal RF strategy
✓ No RF strategy selection has been performed
✓ RF-2 remains available for later Validation comparison

[MODEL-DEVELOPMENT BOUNDARY]
✓ No additional model fitting performed
✓ No additional predictions generated
✓ No resampling performed
✓ No synthetic samples generated
✓ No Independent Test data loaded

[FINAL RF-2 COMPLETION GATE]

========================================================================
5.6.7 — RF-2 EXPERIMENT COMPLETION AND READINESS GATE PASSED
========================================================================

RF-2 BALANCED-SUBSAMPLE CLASS WEIGHTING EXPERIMENT COMPLETED
✓ RF-2 definition validated
✓ Complete Training partition used for RF-2 fitting
✓ Complete Validation partition used for RF-2 evaluation
✓ RF-2 model contract validated
✓ RF-2 balanced-subsample class-weighting configuration validated
✓ RF-2 Validation results persisted
✓ RF-2 error and resource analysis completed
✓ All seven RF-2 experiment artifacts confirmed
✓ RF-2 remains an independent experiment and has not been selected
✓ Independent Test remains completely untouched
✓ Notebook 04 model-ready artifacts remain untouched

READY FOR 5.7 — RF-3: CONTROLLED RANDOM OVERSAMPLING
========================================================================

# 5.7 — RF-3: CONTROLLED RANDOM OVERSAMPLING

This section evaluates the Random Forest using controlled random
oversampling as the third imbalance-aware strategy.

RF-3 is designed as a controlled comparison against the RF-0 Natural
Distribution Baseline, RF-1 Balanced Class Weighting, and RF-2
Balanced-Subsample Class Weighting experiments.

The common Random Forest configuration remains unchanged:

    n_estimators = 100
    max_features = "sqrt"
    max_depth = None
    bootstrap = True
    n_jobs = -1
    random_state = 42

The intended strategy-specific change in RF-3 is controlled random
oversampling of the Training partition.

RF-3 follows the established controlled sampling boundaries:

    minimum training support = 10 observations
    oversampling multiplier = 5x
    maximum target = 50,000 observations per class

Majority-class downsampling is prohibited.

Random oversampling is performed only on the Training partition.
Validation data remain in their original natural distribution and are
used only for RF-3 performance evaluation and later strategy
comparison.

The Independent Test partition remains completely protected and is not
loaded, resampled, evaluated, or used for strategy selection during
RF-3 development.

RF-3 uses real Training observations sampled with replacement.
Therefore, RF-3 does not generate synthetic observations and does not
use SMOTE.

Classes below the minimum support boundary are not oversampled.
Heartbleed is specifically excluded because its Training support is
below the established minimum threshold.

Infiltration is eligible for controlled oversampling because its
Training support satisfies the minimum threshold, but its very low
original support requires explicit interpretation during later error
analysis and strategy comparison.

The RF-3 experiment remains an independent strategy and is not treated
as the final Random Forest strategy until the later Validation-Based
Strategy Comparison and Strategy Selection stages.

### 5.7.1 — RF-3 Controlled Random Oversampling Experiment Definition

This subsection formally defines the RF-3 Controlled Random
Oversampling experiment before any Training or Validation data are
loaded.

RF-3 retains the common Random Forest configuration established in
Section 5.3 and the same Training, Validation, and Independent Test
partition roles used by RF-0, RF-1, and RF-2.

The strategy-specific imbalance-handling mechanism is controlled random
oversampling of the Training partition.

The established RF-3 sampling policy is:

- minimum Training support = 10 observations
- oversampling multiplier = 5x
- maximum target = 50,000 observations per class
- majority-class downsampling = prohibited
- Heartbleed = excluded from oversampling
- Infiltration = eligible for oversampling with low-support caveat

The oversampling operation duplicates existing Training observations
through random sampling with replacement. It does not generate
synthetic observations and therefore does not constitute SMOTE.

RF-3 does not modify the Validation partition or Independent Test
partition.

No Training feature array is loaded, no target array is loaded, no
resampling is performed, no model is fitted, and no predictions or
evaluation metrics are generated in this subsection.

Successful completion of this definition gate authorizes progression to
Section 5.7.2 — RF-3 Training and Validation Artifact Loading.

In [ ]:
# ================================================================
# 5.7.1 — RF-3 CONTROLLED RANDOM OVERSAMPLING EXPERIMENT DEFINITION
# ================================================================

print("=" * 72)
print("5.7.1 — RF-3 CONTROLLED RANDOM OVERSAMPLING EXPERIMENT DEFINITION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-3 STRATEGY DEFINITION
# ---------------------------------------------------------------

print("\n[RF-3 STRATEGY DEFINITION]")


RF3_CONFIGURATION = {
    "strategy_id": "RF-3",
    "strategy_name": "Controlled Random Oversampling",
    "class_weight": None,
    "resampling": True,
    "synthetic_sampling": False,
    "training_partition": "Training",
    "evaluation_partition": "Validation",
    "test_used": False,
}


print(
    f"✓ Strategy ID        : "
    f"{RF3_CONFIGURATION['strategy_id']}"
)

print(
    f"✓ Strategy name      : "
    f"{RF3_CONFIGURATION['strategy_name']}"
)

print(
    f"✓ Class weighting    : "
    f"{RF3_CONFIGURATION['class_weight']}"
)

print(
    f"✓ Resampling         : "
    f"{RF3_CONFIGURATION['resampling']}"
)

print(
    f"✓ Synthetic sampling : "
    f"{RF3_CONFIGURATION['synthetic_sampling']}"
)

print(
    f"✓ Training partition : "
    f"{RF3_CONFIGURATION['training_partition']}"
)

print(
    f"✓ Evaluation         : "
    f"{RF3_CONFIGURATION['evaluation_partition']}"
)

print(
    f"✓ Independent Test   : "
    f"Excluded"
)


# ---------------------------------------------------------------
# 2. COMMON RANDOM FOREST CONFIGURATION CHECK
# ---------------------------------------------------------------

print("\n[COMMON RANDOM FOREST CONFIGURATION]")


if not isinstance(
    RF_COMMON_CONFIGURATION,
    dict
):

    raise TypeError(
        "RF_COMMON_CONFIGURATION must be a dictionary."
    )


if RF_COMMON_CONFIGURATION[
    "random_state"
] != RANDOM_SEED:

    raise RuntimeError(
        "RF-3 random_state does not match "
        "the established project RANDOM_SEED."
    )


print(
    f"✓ Number of trees   : "
    f"{RF_COMMON_CONFIGURATION['n_estimators']}"
)

print(
    f"✓ Max features      : "
    f"{RF_COMMON_CONFIGURATION['max_features']}"
)

print(
    f"✓ Max depth         : "
    f"{RF_COMMON_CONFIGURATION['max_depth']}"
)

print(
    f"✓ Bootstrap         : "
    f"{RF_COMMON_CONFIGURATION['bootstrap']}"
)

print(
    f"✓ CPU parallelism   : "
    f"{RF_COMMON_CONFIGURATION['n_jobs']}"
)

print(
    f"✓ Random seed       : "
    f"{RF_COMMON_CONFIGURATION['random_state']}"
)


# ---------------------------------------------------------------
# 3. RF-3 CONTROLLED RANDOM OVERSAMPLING BOUNDARY
# ---------------------------------------------------------------

print(
    "\n[RF-3 CONTROLLED RANDOM OVERSAMPLING BOUNDARY]"
)


RF3_SAMPLING_CONFIGURATION = {
    "minimum_training_support": 10,
    "oversampling_multiplier": 5,
    "maximum_target_per_class": 50_000,
    "majority_downsampling": False,
    "heartbleed_oversampling": False,
    "infiltration_oversampling_eligible": True,
}


if RF3_CONFIGURATION[
    "class_weight"
] is not None:

    raise RuntimeError(
        "RF-3 must not use Random Forest class weighting. "
        "The imbalance intervention is controlled random "
        "oversampling."
    )


if RF3_CONFIGURATION[
    "resampling"
] is not True:

    raise RuntimeError(
        "RF-3 must enable Training-partition resampling."
    )


if RF3_CONFIGURATION[
    "synthetic_sampling"
] is not False:

    raise RuntimeError(
        "RF-3 must not generate synthetic observations."
    )


if RF3_SAMPLING_CONFIGURATION[
    "minimum_training_support"
] != 10:

    raise RuntimeError(
        "RF-3 minimum Training support must be 10."
    )


if RF3_SAMPLING_CONFIGURATION[
    "oversampling_multiplier"
] != 5:

    raise RuntimeError(
        "RF-3 oversampling multiplier must be 5x."
    )


if RF3_SAMPLING_CONFIGURATION[
    "maximum_target_per_class"
] != 50_000:

    raise RuntimeError(
        "RF-3 maximum target must be 50,000 observations "
        "per class."
    )


if RF3_SAMPLING_CONFIGURATION[
    "majority_downsampling"
]:

    raise RuntimeError(
        "RF-3 must prohibit majority-class downsampling."
    )


if RF3_SAMPLING_CONFIGURATION[
    "heartbleed_oversampling"
]:

    raise RuntimeError(
        "Heartbleed must remain excluded from RF-3 "
        "oversampling."
    )


if not RF3_SAMPLING_CONFIGURATION[
    "infiltration_oversampling_eligible"
]:

    raise RuntimeError(
        "Infiltration must remain eligible for RF-3 "
        "oversampling subject to the minimum-support boundary."
    )


print(
    "✓ Controlled random oversampling enabled"
)

print(
    "✓ Minimum Training support : 10"
)

print(
    "✓ Oversampling multiplier  : 5x"
)

print(
    "✓ Maximum target/class     : 50,000"
)

print(
    "✓ Majority-class downsampling prohibited"
)

print(
    "✓ Heartbleed excluded from oversampling"
)

print(
    "✓ Infiltration remains eligible with low-support caveat"
)

print(
    "✓ No SMOTE configured"
)

print(
    "✓ No synthetic observations generated"
)


# ---------------------------------------------------------------
# 4. PARTITION-ROLE VALIDATION
# ---------------------------------------------------------------

print("\n[TRAINING / VALIDATION / TEST ROLE BOUNDARY]")


if not RF_5_2_4_VALIDATION[
    "training_authorized_for_fitting"
]:

    raise RuntimeError(
        "Training is not authorized for RF-3 model fitting."
    )


if not RF_5_2_4_VALIDATION[
    "validation_reserved_for_comparison"
]:

    raise RuntimeError(
        "Validation is not reserved for RF strategy comparison."
    )


if not RF_5_2_4_VALIDATION[
    "validation_reserved_for_selection"
]:

    raise RuntimeError(
        "Validation is not reserved for RF strategy selection."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_fitting"
]:

    raise RuntimeError(
        "Independent Test is not protected from model fitting."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_comparison"
]:

    raise RuntimeError(
        "Independent Test is not protected from strategy comparison."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_selection"
]:

    raise RuntimeError(
        "Independent Test is not protected from strategy selection."
    )


print(
    "✓ Training authorized for RF-3 model fitting"
)

print(
    "✓ Validation reserved for RF-3 evaluation and comparison"
)

print(
    "✓ Validation reserved for strategy selection"
)

print(
    "✓ Independent Test excluded from model fitting"
)

print(
    "✓ Independent Test excluded from strategy comparison"
)

print(
    "✓ Independent Test excluded from strategy selection"
)


# ---------------------------------------------------------------
# 5. RF-3 OUTPUT BOUNDARY
# ---------------------------------------------------------------

print("\n[RF-3 EXPERIMENT OUTPUT BOUNDARY]")


RF3_OUTPUT_DIR = (
    RF_STRATEGY_EXPERIMENTS_DIR /
    "RF-3"
)


RF3_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


print(
    "✓ RF-3 output directory available:"
)

print(
    f"  {RF3_OUTPUT_DIR}"
)


# ---------------------------------------------------------------
# 6. MODEL-DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[MODEL-DEVELOPMENT BOUNDARY]")


print(
    "✓ No Training feature array loaded"
)

print(
    "✓ No Validation feature array loaded"
)

print(
    "✓ No Test feature array loaded"
)

print(
    "✓ No target array loaded"
)

print(
    "✓ No Random Forest model fitted"
)

print(
    "✓ No oversampling performed"
)

print(
    "✓ No majority-class downsampling performed"
)

print(
    "✓ No synthetic samples generated"
)

print(
    "✓ No predictions generated"
)

print(
    "✓ No evaluation metrics calculated"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 7. FINAL RF-3 DEFINITION VALIDATION
# ---------------------------------------------------------------

print("\n[RF-3 DEFINITION VALIDATION]")


RF_5_7_1_VALIDATION = {

    "strategy_id_valid":
        RF3_CONFIGURATION[
            "strategy_id"
        ] == "RF-3",

    "strategy_name_valid":
        RF3_CONFIGURATION[
            "strategy_name"
        ] == "Controlled Random Oversampling",

    "class_weight_disabled":
        RF3_CONFIGURATION[
            "class_weight"
        ] is None,

    "resampling_enabled":
        RF3_CONFIGURATION[
            "resampling"
        ] is True,

    "synthetic_sampling_disabled":
        RF3_CONFIGURATION[
            "synthetic_sampling"
        ] is False,

    "training_partition_valid":
        RF3_CONFIGURATION[
            "training_partition"
        ] == "Training",

    "validation_partition_valid":
        RF3_CONFIGURATION[
            "evaluation_partition"
        ] == "Validation",

    "test_not_used":
        RF3_CONFIGURATION[
            "test_used"
        ] is False,

    "minimum_support_valid":
        RF3_SAMPLING_CONFIGURATION[
            "minimum_training_support"
        ] == 10,

    "oversampling_multiplier_valid":
        RF3_SAMPLING_CONFIGURATION[
            "oversampling_multiplier"
        ] == 5,

    "maximum_target_valid":
        RF3_SAMPLING_CONFIGURATION[
            "maximum_target_per_class"
        ] == 50_000,

    "majority_downsampling_prohibited":
        RF3_SAMPLING_CONFIGURATION[
            "majority_downsampling"
        ] is False,

    "heartbleed_excluded":
        RF3_SAMPLING_CONFIGURATION[
            "heartbleed_oversampling"
        ] is False,

    "infiltration_eligible":
        RF3_SAMPLING_CONFIGURATION[
            "infiltration_oversampling_eligible"
        ] is True,

    "output_directory_available":
        RF3_OUTPUT_DIR.is_dir(),

    "random_state_consistent":
        RF_COMMON_CONFIGURATION[
            "random_state"
        ] == RANDOM_SEED,

    "training_authorized":
        RF_5_2_4_VALIDATION[
            "training_authorized_for_fitting"
        ],

    "validation_reserved_for_comparison":
        RF_5_2_4_VALIDATION[
            "validation_reserved_for_comparison"
        ],

    "test_protected_from_fitting":
        RF_5_2_4_VALIDATION[
            "test_excluded_from_fitting"
        ],

    "test_protected_from_comparison":
        RF_5_2_4_VALIDATION[
            "test_excluded_from_comparison"
        ],

    "test_protected_from_selection":
        RF_5_2_4_VALIDATION[
            "test_excluded_from_selection"
        ],
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_7_1_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "RF-3 controlled random oversampling "
        "definition validation failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 8. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.7.1 — RF-3 CONTROLLED RANDOM OVERSAMPLING "
    "EXPERIMENT DEFINITION PASSED"
)

print("=" * 72)

print(
    "\nRF-3 Controlled Random Oversampling is defined."
)

print(
    "✓ Common Random Forest configuration retained"
)

print(
    "✓ Controlled Training-partition oversampling configured"
)

print(
    "✓ Minimum support threshold = 10"
)

print(
    "✓ Oversampling multiplier = 5x"
)

print(
    "✓ Maximum target = 50,000 observations/class"
)

print(
    "✓ Majority-class downsampling prohibited"
)

print(
    "✓ Heartbleed excluded from oversampling"
)

print(
    "✓ Infiltration remains eligible with low-support caveat"
)

print(
    "✓ Validation reserved for evaluation"
)

print(
    "✓ Independent Test remains protected"
)

print(
    "✓ No model fitting or data loading performed"
)

print(
    "\nREADY FOR 5.7.2 — "
    "RF-3 TRAINING AND VALIDATION ARTIFACT LOADING"
)

print("=" * 72)

========================================================================
5.7.1 — RF-3 CONTROLLED RANDOM OVERSAMPLING EXPERIMENT DEFINITION
========================================================================

[RF-3 STRATEGY DEFINITION]
✓ Strategy ID        : RF-3
✓ Strategy name      : Controlled Random Oversampling
✓ Class weighting    : None
✓ Resampling         : True
✓ Synthetic sampling : False
✓ Training partition : Training
✓ Evaluation         : Validation
✓ Independent Test   : Excluded

[COMMON RANDOM FOREST CONFIGURATION]
✓ Number of trees   : 100
✓ Max features      : sqrt
✓ Max depth         : None
✓ Bootstrap         : True
✓ CPU parallelism   : -1
✓ Random seed       : 42

[RF-3 CONTROLLED RANDOM OVERSAMPLING BOUNDARY]
✓ Controlled random oversampling enabled
✓ Minimum Training support : 10
✓ Oversampling multiplier  : 5x
✓ Maximum target/class     : 50,000
✓ Majority-class downsampling prohibited
✓ Heartbleed excluded from oversampling
✓ Infiltration remains eligible with low-support caveat
✓ No SMOTE configured
✓ No synthetic observations generated

[TRAINING / VALIDATION / TEST ROLE BOUNDARY]
✓ Training authorized for RF-3 model fitting
✓ Validation reserved for RF-3 evaluation and comparison
✓ Validation reserved for strategy selection
✓ Independent Test excluded from model fitting
✓ Independent Test excluded from strategy comparison
✓ Independent Test excluded from strategy selection

[RF-3 EXPERIMENT OUTPUT BOUNDARY]
✓ RF-3 output directory available:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3

[MODEL-DEVELOPMENT BOUNDARY]
✓ No Training feature array loaded
✓ No Validation feature array loaded
✓ No Test feature array loaded
✓ No target array loaded
✓ No Random Forest model fitted
✓ No oversampling performed
✓ No majority-class downsampling performed
✓ No synthetic samples generated
✓ No predictions generated
✓ No evaluation metrics calculated
✓ Independent Test remains untouched

[RF-3 DEFINITION VALIDATION]

========================================================================
5.7.1 — RF-3 CONTROLLED RANDOM OVERSAMPLING EXPERIMENT DEFINITION PASSED
========================================================================

RF-3 Controlled Random Oversampling is defined.
✓ Common Random Forest configuration retained
✓ Controlled Training-partition oversampling configured
✓ Minimum support threshold = 10
✓ Oversampling multiplier = 5x
✓ Maximum target = 50,000 observations/class
✓ Majority-class downsampling prohibited
✓ Heartbleed excluded from oversampling
✓ Infiltration remains eligible with low-support caveat
✓ Validation reserved for evaluation
✓ Independent Test remains protected
✓ No model fitting or data loading performed

READY FOR 5.7.2 — RF-3 TRAINING AND VALIDATION ARTIFACT LOADING
========================================================================

### 5.7.2 — RF-3 Training and Validation Artifact Loading

This subsection loads the authoritative Training and Validation
artifacts required for the RF-3 Controlled Random Oversampling
experiment.

RF-3 uses the same frozen model-ready Training and Validation
partitions used by RF-0, RF-1, and RF-2. The underlying feature and
target artifacts are loaded from the established RF input paths using
read-only NumPy memory mapping.

The complete Training partition is reserved as the source population
for controlled random oversampling during RF-3 model development,
while the complete Validation partition remains in its original
distribution and is reserved for subsequent RF-3 performance
evaluation and strategy comparison.

The RF-3 controlled random oversampling configuration established in
Section 5.7.1 is retained:

- minimum Training support = 10 observations
- oversampling multiplier = 5x
- maximum target = 50,000 observations per class
- majority-class downsampling is prohibited
- Heartbleed is excluded from oversampling
- Infiltration remains eligible subject to the minimum-support
  boundary
- no SMOTE or synthetic observations are generated.

No oversampling is performed in this subsection. No Training array is
duplicated, no Validation data are resampled, and no Independent Test
data are loaded.

The expected model-ready representation remains 32 float32 features,
with int64 target arrays and observation-aligned X/y dimensions.

The Independent Test partition remains completely protected from RF-3
development.

Successful completion of this artifact-loading gate authorizes
progression to Section 5.7.3 — RF-3 Random Forest Model Fitting.

In [ ]:
# ================================================================
# 5.7.2 — RF-3 TRAINING AND VALIDATION ARTIFACT LOADING
# ================================================================

import numpy as np

print("=" * 72)
print("5.7.2 — RF-3 TRAINING AND VALIDATION ARTIFACT LOADING")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-3 ARTIFACT LOADING BOUNDARY
# ---------------------------------------------------------------

print("\n[RF-3 ARTIFACT LOADING BOUNDARY]")


if not RF_5_7_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-3 controlled random oversampling definition "
        "has not passed validation."
    )


if RF3_CONFIGURATION[
    "training_partition"
] != "Training":

    raise RuntimeError(
        "RF-3 training partition is not the authoritative "
        "Training partition."
    )


if RF3_CONFIGURATION[
    "evaluation_partition"
] != "Validation":

    raise RuntimeError(
        "RF-3 evaluation partition is not the authoritative "
        "Validation partition."
    )


print(
    "✓ RF-3 controlled random oversampling definition is valid"
)

print(
    "✓ Training artifact authorized for RF-3 model fitting"
)

print(
    "✓ Validation artifact authorized for RF-3 evaluation"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# 2. RF-3 CONTROLLED RANDOM OVERSAMPLING BOUNDARY
# ---------------------------------------------------------------

print(
    "\n[RF-3 CONTROLLED RANDOM OVERSAMPLING BOUNDARY]"
)


if RF3_CONFIGURATION[
    "resampling"
] is not True:

    raise RuntimeError(
        "RF-3 must enable Training-partition resampling."
    )


if RF3_CONFIGURATION[
    "synthetic_sampling"
] is not False:

    raise RuntimeError(
        "RF-3 must not use synthetic sampling."
    )


if RF3_SAMPLING_CONFIGURATION[
    "minimum_training_support"
] != 10:

    raise RuntimeError(
        "RF-3 minimum Training support must be 10."
    )


if RF3_SAMPLING_CONFIGURATION[
    "oversampling_multiplier"
] != 5:

    raise RuntimeError(
        "RF-3 oversampling multiplier must be 5x."
    )


if RF3_SAMPLING_CONFIGURATION[
    "maximum_target_per_class"
] != 50_000:

    raise RuntimeError(
        "RF-3 maximum target must be 50,000 observations "
        "per class."
    )


if RF3_SAMPLING_CONFIGURATION[
    "majority_downsampling"
]:

    raise RuntimeError(
        "RF-3 must prohibit majority-class downsampling."
    )


if RF3_SAMPLING_CONFIGURATION[
    "heartbleed_oversampling"
]:

    raise RuntimeError(
        "Heartbleed must remain excluded from RF-3 "
        "oversampling."
    )


if not RF3_SAMPLING_CONFIGURATION[
    "infiltration_oversampling_eligible"
]:

    raise RuntimeError(
        "Infiltration must remain eligible for RF-3 "
        "oversampling subject to the minimum-support boundary."
    )


print(
    "✓ Controlled random oversampling enabled"
)

print(
    "✓ Minimum Training support : 10"
)

print(
    "✓ Oversampling multiplier  : 5x"
)

print(
    "✓ Maximum target/class     : 50,000"
)

print(
    "✓ Majority-class downsampling prohibited"
)

print(
    "✓ Heartbleed excluded from oversampling"
)

print(
    "✓ Infiltration remains eligible with low-support caveat"
)

print(
    "✓ No SMOTE configured"
)

print(
    "✓ No synthetic observations generated"
)


# ---------------------------------------------------------------
# 3. AUTHORITATIVE RF-3 ARTIFACT PATHS
# ---------------------------------------------------------------

print("\n[AUTHORITATIVE RF-3 ARTIFACT PATHS]")


RF3_TRAINING_FEATURE_PATH = RF_INPUT_PATHS[
    "Training features"
]

RF3_TRAINING_TARGET_PATH = RF_INPUT_PATHS[
    "Training targets"
]

RF3_VALIDATION_FEATURE_PATH = RF_INPUT_PATHS[
    "Validation features"
]

RF3_VALIDATION_TARGET_PATH = RF_INPUT_PATHS[
    "Validation targets"
]


for artifact_name, artifact_path in {
    "Training features":
        RF3_TRAINING_FEATURE_PATH,

    "Training targets":
        RF3_TRAINING_TARGET_PATH,

    "Validation features":
        RF3_VALIDATION_FEATURE_PATH,

    "Validation targets":
        RF3_VALIDATION_TARGET_PATH,

}.items():

    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"{artifact_name} artifact was not found:\n"
            f"{artifact_path}"
        )

    if artifact_path.stat().st_size == 0:

        raise ValueError(
            f"{artifact_name} artifact is empty:\n"
            f"{artifact_path}"
        )

    print(
        f"✓ {artifact_name:<20}: "
        f"{artifact_path.name}"
    )


# ---------------------------------------------------------------
# 4. READ-ONLY MEMORY-MAPPED LOADING
# ---------------------------------------------------------------

print("\n[READ-ONLY MEMORY-MAPPED LOADING]")


# The complete arrays are not copied into normal RAM.
# mmap_mode="r" provides read-only access to the persisted
# NumPy arrays.

RF3_TRAINING_FEATURES = np.load(
    RF3_TRAINING_FEATURE_PATH,
    mmap_mode="r"
)

RF3_TRAINING_TARGETS = np.load(
    RF3_TRAINING_TARGET_PATH,
    mmap_mode="r"
)

RF3_VALIDATION_FEATURES = np.load(
    RF3_VALIDATION_FEATURE_PATH,
    mmap_mode="r"
)

RF3_VALIDATION_TARGETS = np.load(
    RF3_VALIDATION_TARGET_PATH,
    mmap_mode="r"
)


print(
    "✓ Training features opened as read-only memory map"
)

print(
    "✓ Training targets opened as read-only memory map"
)

print(
    "✓ Validation features opened as read-only memory map"
)

print(
    "✓ Validation targets opened as read-only memory map"
)


# ---------------------------------------------------------------
# 5. FEATURE ARTIFACT VALIDATION
# ---------------------------------------------------------------

print("\n[RF-3 FEATURE ARTIFACT VALIDATION]")


if RF3_TRAINING_FEATURES.shape != (
    1_814_018,
    32
):

    raise ValueError(
        "RF-3 Training feature shape mismatch.\n"
        f"Expected: {(1_814_018, 32)}\n"
        f"Observed: {RF3_TRAINING_FEATURES.shape}"
    )


if RF3_VALIDATION_FEATURES.shape != (
    451_215,
    32
):

    raise ValueError(
        "RF-3 Validation feature shape mismatch.\n"
        f"Expected: {(451_215, 32)}\n"
        f"Observed: {RF3_VALIDATION_FEATURES.shape}"
    )


if RF3_TRAINING_FEATURES.dtype != np.float32:

    raise TypeError(
        "RF-3 Training features must use float32."
    )


if RF3_VALIDATION_FEATURES.dtype != np.float32:

    raise TypeError(
        "RF-3 Validation features must use float32."
    )


print(
    f"✓ Training features    : "
    f"{RF3_TRAINING_FEATURES.shape} | "
    f"{RF3_TRAINING_FEATURES.dtype}"
)

print(
    f"✓ Validation features  : "
    f"{RF3_VALIDATION_FEATURES.shape} | "
    f"{RF3_VALIDATION_FEATURES.dtype}"
)


# ---------------------------------------------------------------
# 6. TARGET ARTIFACT VALIDATION
# ---------------------------------------------------------------

print("\n[RF-3 TARGET ARTIFACT VALIDATION]")


if RF3_TRAINING_TARGETS.shape != (
    1_814_018,
):

    raise ValueError(
        "RF-3 Training target shape mismatch.\n"
        f"Expected: {(1_814_018,)}\n"
        f"Observed: {RF3_TRAINING_TARGETS.shape}"
    )


if RF3_VALIDATION_TARGETS.shape != (
    451_215,
):

    raise ValueError(
        "RF-3 Validation target shape mismatch.\n"
        f"Expected: {(451_215,)}\n"
        f"Observed: {RF3_VALIDATION_TARGETS.shape}"
    )


if RF3_TRAINING_TARGETS.dtype != np.int64:

    raise TypeError(
        "RF-3 Training targets must use int64."
    )


if RF3_VALIDATION_TARGETS.dtype != np.int64:

    raise TypeError(
        "RF-3 Validation targets must use int64."
    )


print(
    f"✓ Training targets    : "
    f"{RF3_TRAINING_TARGETS.shape} | "
    f"{RF3_TRAINING_TARGETS.dtype}"
)

print(
    f"✓ Validation targets  : "
    f"{RF3_VALIDATION_TARGETS.shape} | "
    f"{RF3_VALIDATION_TARGETS.dtype}"
)


# ---------------------------------------------------------------
# 7. X/Y OBSERVATION ALIGNMENT
# ---------------------------------------------------------------

print("\n[X/Y OBSERVATION ALIGNMENT]")


if (
    RF3_TRAINING_FEATURES.shape[0]
    != RF3_TRAINING_TARGETS.shape[0]
):

    raise ValueError(
        "RF-3 Training feature/target observation counts "
        "are not aligned."
    )


if (
    RF3_VALIDATION_FEATURES.shape[0]
    != RF3_VALIDATION_TARGETS.shape[0]
):

    raise ValueError(
        "RF-3 Validation feature/target observation counts "
        "are not aligned."
    )


print(
    "✓ Training features and targets are observation-aligned"
)

print(
    "✓ Validation features and targets are observation-aligned"
)


# ---------------------------------------------------------------
# 8. CONFIRM COMMON MODEL-READY FEATURE SPACE
# ---------------------------------------------------------------

print("\n[COMMON RF-3 MODEL-READY FEATURE SPACE]")


if (
    RF3_TRAINING_FEATURES.shape[1]
    != RF3_VALIDATION_FEATURES.shape[1]
):

    raise ValueError(
        "RF-3 Training and Validation feature dimensions "
        "do not match."
    )


if RF3_TRAINING_FEATURES.shape[1] != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-3 feature count does not match the established "
        "N04 model-ready feature contract."
    )


print(
    f"✓ Common RF-3 feature count : "
    f"{RF3_TRAINING_FEATURES.shape[1]}"
)

print(
    "✓ Training and Validation share the same "
    "32-feature model-ready representation"
)


# ---------------------------------------------------------------
# 9. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION]")


print(
    "✓ Independent Test feature artifact was not loaded"
)

print(
    "✓ Independent Test target artifact was not loaded"
)

print(
    "✓ Independent Test remains protected from RF-3 development"
)


# ---------------------------------------------------------------
# 10. MEMORY-AWARE EXECUTION CHECK
# ---------------------------------------------------------------

print("\n[MEMORY-AWARE EXECUTION CHECK]")


if not isinstance(
    RF3_TRAINING_FEATURES,
    np.memmap
):

    raise TypeError(
        "RF-3 Training features were not loaded "
        "as a NumPy memory map."
    )


if not isinstance(
    RF3_TRAINING_TARGETS,
    np.memmap
):

    raise TypeError(
        "RF-3 Training targets were not loaded "
        "as a NumPy memory map."
    )


if not isinstance(
    RF3_VALIDATION_FEATURES,
    np.memmap
):

    raise TypeError(
        "RF-3 Validation features were not loaded "
        "as a NumPy memory map."
    )


if not isinstance(
    RF3_VALIDATION_TARGETS,
    np.memmap
):

    raise TypeError(
        "RF-3 Validation targets were not loaded "
        "as a NumPy memory map."
    )


print(
    "✓ Training features remain memory-mapped"
)

print(
    "✓ Training targets remain memory-mapped"
)

print(
    "✓ Validation features remain memory-mapped"
)

print(
    "✓ Validation targets remain memory-mapped"
)

print(
    "✓ No full-array RAM duplication performed"
)


# ---------------------------------------------------------------
# 11. FINAL RF-3 ARTIFACT LOADING VALIDATION
# ---------------------------------------------------------------

RF_5_7_2_VALIDATION = {

    "training_features_loaded":
        RF3_TRAINING_FEATURES.shape
        == (1_814_018, 32),

    "training_targets_loaded":
        RF3_TRAINING_TARGETS.shape
        == (1_814_018,),

    "validation_features_loaded":
        RF3_VALIDATION_FEATURES.shape
        == (451_215, 32),

    "validation_targets_loaded":
        RF3_VALIDATION_TARGETS.shape
        == (451_215,),

    "training_feature_dtype":
        RF3_TRAINING_FEATURES.dtype
        == np.float32,

    "validation_feature_dtype":
        RF3_VALIDATION_FEATURES.dtype
        == np.float32,

    "training_target_dtype":
        RF3_TRAINING_TARGETS.dtype
        == np.int64,

    "validation_target_dtype":
        RF3_VALIDATION_TARGETS.dtype
        == np.int64,

    "training_xy_alignment":
        RF3_TRAINING_FEATURES.shape[0]
        == RF3_TRAINING_TARGETS.shape[0],

    "validation_xy_alignment":
        RF3_VALIDATION_FEATURES.shape[0]
        == RF3_VALIDATION_TARGETS.shape[0],

    "common_feature_space":
        RF3_TRAINING_FEATURES.shape[1]
        == RF3_VALIDATION_FEATURES.shape[1]
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "training_features_memory_mapped":
        isinstance(
            RF3_TRAINING_FEATURES,
            np.memmap
        ),

    "training_targets_memory_mapped":
        isinstance(
            RF3_TRAINING_TARGETS,
            np.memmap
        ),

    "validation_features_memory_mapped":
        isinstance(
            RF3_VALIDATION_FEATURES,
            np.memmap
        ),

    "validation_targets_memory_mapped":
        isinstance(
            RF3_VALIDATION_TARGETS,
            np.memmap
        ),

    "independent_test_not_loaded":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_7_2_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.7.2 RF-3 Training and Validation Artifact "
        "Loading failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 12. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.7.2 — RF-3 TRAINING AND VALIDATION "
    "ARTIFACT LOADING PASSED"
)

print("=" * 72)

print(
    "\n✓ Complete Training partition is available "
    "through read-only memory mapping"
)

print(
    "✓ Complete Validation partition is available "
    "through read-only memory mapping"
)

print(
    "✓ Training and Validation X/y dimensions are aligned"
)

print(
    "✓ Common 32-feature float32 representation confirmed"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ No oversampling or synthetic sampling performed"
)

print(
    "\nREADY FOR 5.7.3 — RF-3 RANDOM FOREST MODEL FITTING"
)

print("=" * 72)

========================================================================
5.7.2 — RF-3 TRAINING AND VALIDATION ARTIFACT LOADING
========================================================================

[RF-3 ARTIFACT LOADING BOUNDARY]
✓ RF-3 controlled random oversampling definition is valid
✓ Training artifact authorized for RF-3 model fitting
✓ Validation artifact authorized for RF-3 evaluation
✓ Independent Test remains excluded

[RF-3 CONTROLLED RANDOM OVERSAMPLING BOUNDARY]
✓ Controlled random oversampling enabled
✓ Minimum Training support : 10
✓ Oversampling multiplier  : 5x
✓ Maximum target/class     : 50,000
✓ Majority-class downsampling prohibited
✓ Heartbleed excluded from oversampling
✓ Infiltration remains eligible with low-support caveat
✓ No SMOTE configured
✓ No synthetic observations generated

[AUTHORITATIVE RF-3 ARTIFACT PATHS]
✓ Training features   : X_train_scaled.npy
✓ Training targets    : y_train.npy
✓ Validation features : X_validation_scaled.npy
✓ Validation targets  : y_validation.npy

[READ-ONLY MEMORY-MAPPED LOADING]
✓ Training features opened as read-only memory map
✓ Training targets opened as read-only memory map
✓ Validation features opened as read-only memory map
✓ Validation targets opened as read-only memory map

[RF-3 FEATURE ARTIFACT VALIDATION]
✓ Training features    : (1814018, 32) | float32
✓ Validation features  : (451215, 32) | float32

[RF-3 TARGET ARTIFACT VALIDATION]
✓ Training targets    : (1814018,) | int64
✓ Validation targets  : (451215,) | int64

[X/Y OBSERVATION ALIGNMENT]
✓ Training features and targets are observation-aligned
✓ Validation features and targets are observation-aligned

[COMMON RF-3 MODEL-READY FEATURE SPACE]
✓ Common RF-3 feature count : 32
✓ Training and Validation share the same 32-feature model-ready representation

[INDEPENDENT TEST PROTECTION]
✓ Independent Test feature artifact was not loaded
✓ Independent Test target artifact was not loaded
✓ Independent Test remains protected from RF-3 development

[MEMORY-AWARE EXECUTION CHECK]
✓ Training features remain memory-mapped
✓ Training targets remain memory-mapped
✓ Validation features remain memory-mapped
✓ Validation targets remain memory-mapped
✓ No full-array RAM duplication performed

========================================================================
5.7.2 — RF-3 TRAINING AND VALIDATION ARTIFACT LOADING PASSED
========================================================================

✓ Complete Training partition is available through read-only memory mapping
✓ Complete Validation partition is available through read-only memory mapping
✓ Training and Validation X/y dimensions are aligned
✓ Common 32-feature float32 representation confirmed
✓ Independent Test remains completely untouched
✓ No oversampling or synthetic sampling performed

READY FOR 5.7.3 — RF-3 RANDOM FOREST MODEL FITTING
========================================================================

### 5.7.3 — RF-3 Controlled Random Oversampling and Random Forest Model Fitting

This subsection performs the RF-3 Controlled Random Oversampling experiment
and fits the Random Forest using the resulting Training representation.

RF-3 retains the same Random Forest configuration used by RF-0, RF-1,
and RF-2:

    n_estimators = 100
    max_features = "sqrt"
    max_depth = None
    bootstrap = True
    n_jobs = -1
    random_state = 42

Unlike RF-0, RF-1, and RF-2, the RF-3 imbalance intervention is applied
through controlled random oversampling of the Training partition.

The established RF-3 sampling policy is:

    minimum Training support = 10 observations
    oversampling multiplier = 5x
    maximum target = 50,000 observations per class

For eligible minority classes, existing Training observations are sampled
with replacement until the controlled target size is reached.

Classes with Training support below the minimum threshold are not
oversampled. Heartbleed remains explicitly excluded from oversampling.
Infiltration remains eligible because its Training support satisfies the
minimum-support boundary.

Majority-class downsampling is prohibited. Classes already at or above
the maximum target are therefore retained at their natural Training
support.

No synthetic observations are generated and no SMOTE is applied.

The Validation partition remains completely unchanged and is not
resampled. It is reserved for the subsequent RF-3 Validation prediction
and performance evaluation stage.

The Independent Test partition remains completely protected and is not
loaded, resampled, evaluated, or used for strategy selection.

To remain RAM-aware, the authoritative Training artifacts remain
read-only memory-mapped. Only the controlled oversampled Training
representation required for Random Forest fitting is materialized in
RAM. The oversampled representation is constructed using sampled
observation indices and chunked feature loading rather than creating
unnecessary duplicate full-size arrays.

No Validation predictions, evaluation metrics, strategy comparison, or
model persistence are performed in this subsection.

Successful completion of this fitting gate authorizes progression to
Section 5.7.4 — RF-3 Validation Prediction and Performance Evaluation.

In [ ]:
# ================================================================
# 5.7.3 — RF-3 CONTROLLED RANDOM OVERSAMPLING
#            AND RANDOM FOREST MODEL FITTING
# ================================================================

from sklearn.ensemble import RandomForestClassifier
import numpy as np
import time
import gc


print("=" * 72)
print(
    "5.7.3 — RF-3 CONTROLLED RANDOM OVERSAMPLING "
    "AND RANDOM FOREST MODEL FITTING"
)
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-3 FITTING BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-3 FITTING BOUNDARY VALIDATION]")


if not RF_5_7_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-3 controlled random oversampling definition "
        "has not passed validation."
    )


if not RF_5_7_2_VALIDATION[
    "training_features_loaded"
]:

    raise RuntimeError(
        "RF-3 Training features are not available "
        "for model fitting."
    )


if not RF_5_7_2_VALIDATION[
    "training_targets_loaded"
]:

    raise RuntimeError(
        "RF-3 Training targets are not available "
        "for model fitting."
    )


if not RF_5_7_2_VALIDATION[
    "training_xy_alignment"
]:

    raise RuntimeError(
        "RF-3 Training features and targets are not aligned."
    )


if not RF_5_7_2_VALIDATION[
    "training_features_memory_mapped"
]:

    raise RuntimeError(
        "RF-3 Training features are not memory-mapped."
    )


if RF3_CONFIGURATION[
    "class_weight"
] is not None:

    raise RuntimeError(
        "RF-3 must not use Random Forest class weighting."
    )


if RF3_CONFIGURATION[
    "resampling"
] is not True:

    raise RuntimeError(
        "RF-3 requires controlled random oversampling."
    )


if RF3_CONFIGURATION[
    "synthetic_sampling"
] is not False:

    raise RuntimeError(
        "RF-3 must not perform synthetic sampling."
    )


if RF3_CONFIGURATION[
    "training_partition"
] != "Training":

    raise RuntimeError(
        "RF-3 fitting must use the authoritative "
        "Training partition."
    )


if RF3_CONFIGURATION[
    "evaluation_partition"
] != "Validation":

    raise RuntimeError(
        "RF-3 evaluation partition must remain Validation."
    )


if not RF_5_2_4_VALIDATION[
    "training_authorized_for_fitting"
]:

    raise RuntimeError(
        "Training partition is not authorized for "
        "RF-3 model fitting."
    )


print(
    "✓ RF-3 controlled random oversampling definition validated"
)

print(
    "✓ Complete Training features available"
)

print(
    "✓ Complete Training targets available"
)

print(
    "✓ Training features and targets are aligned"
)

print(
    "✓ Training features remain memory-mapped"
)

print(
    "✓ Random Forest class weighting disabled"
)

print(
    "✓ Controlled random oversampling configured"
)

print(
    "✓ Synthetic sampling disabled"
)

print(
    "✓ Training partition authorized for model fitting"
)


# ---------------------------------------------------------------
# 2. TRAINING FEATURE-SPACE VALIDATION
# ---------------------------------------------------------------

print("\n[TRAINING FEATURE-SPACE VALIDATION]")


if RF3_TRAINING_FEATURES.shape[1] != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-3 Training feature count does not match "
        "the established model-ready feature contract."
    )


if RF3_TRAINING_FEATURES.dtype != np.float32:

    raise TypeError(
        "RF-3 Training features must use float32."
    )


if RF3_TRAINING_FEATURES.shape[1] != len(
    RF_FEATURE_ORDER
):

    raise ValueError(
        "RF-3 Training feature count does not match "
        "the frozen RF feature order."
    )


print(
    f"✓ Training observations : "
    f"{RF3_TRAINING_FEATURES.shape[0]:,}"
)

print(
    f"✓ Training features     : "
    f"{RF3_TRAINING_FEATURES.shape[1]}"
)

print(
    f"✓ Training dtype        : "
    f"{RF3_TRAINING_FEATURES.dtype}"
)

print(
    "✓ Training feature space matches "
    "the frozen RF model-ready contract"
)


# ---------------------------------------------------------------
# 3. NATURAL TRAINING CLASS DISTRIBUTION
# ---------------------------------------------------------------

print("\n[RF-3 NATURAL TRAINING CLASS DISTRIBUTION]")


RF3_TRAINING_CLASS_IDS, RF3_TRAINING_CLASS_COUNTS = (
    np.unique(
        RF3_TRAINING_TARGETS,
        return_counts=True
    )
)


RF3_TRAINING_CLASS_DISTRIBUTION = {
    int(class_id): int(class_count)
    for class_id, class_count
    in zip(
        RF3_TRAINING_CLASS_IDS,
        RF3_TRAINING_CLASS_COUNTS
    )
}


if not np.array_equal(
    RF3_TRAINING_CLASS_IDS,
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    )
):

    raise ValueError(
        "RF-3 Training target classes do not match "
        "the established 0–8 RF taxonomy."
    )


for class_id, class_count in (
    RF3_TRAINING_CLASS_DISTRIBUTION.items()
):

    print(
        f"✓ Class {class_id}: "
        f"{RF_CLASS_MAPPING[class_id]:<24} "
        f"{class_count:,}"
    )


print(
    "✓ Complete natural Training class distribution "
    "confirmed for RF-3"
)


# ---------------------------------------------------------------
# 4. RF-3 CONTROLLED RANDOM OVERSAMPLING PLAN
# ---------------------------------------------------------------

print(
    "\n[RF-3 CONTROLLED RANDOM OVERSAMPLING PLAN]"
)


RF3_OVERSAMPLING_TARGET_COUNTS = {}

RF3_OVERSAMPLING_ADDITIONAL_COUNTS = {}


for class_id, class_count in (
    RF3_TRAINING_CLASS_DISTRIBUTION.items()
):

    # -----------------------------------------------------------
    # Classes below minimum support are retained unchanged.
    # -----------------------------------------------------------

    if class_count < RF3_SAMPLING_CONFIGURATION[
        "minimum_training_support"
    ]:

        target_count = class_count

    # -----------------------------------------------------------
    # Heartbleed is explicitly excluded.
    # -----------------------------------------------------------

    elif class_id == 8:

        target_count = class_count

    # -----------------------------------------------------------
    # Controlled random oversampling.
    #
    # IMPORTANT:
    # The 50,000 limit is an upper bound on the
    # oversampling target. It must NEVER downsample
    # a class that already contains more than 50,000
    # observations.
    # -----------------------------------------------------------

    else:

        target_count = max(
            class_count,

            min(
                class_count *
                RF3_SAMPLING_CONFIGURATION[
                    "oversampling_multiplier"
                ],

                RF3_SAMPLING_CONFIGURATION[
                    "maximum_target_per_class"
                ]
            )
        )


    RF3_OVERSAMPLING_TARGET_COUNTS[
        int(class_id)
    ] = int(target_count)


    RF3_OVERSAMPLING_ADDITIONAL_COUNTS[
        int(class_id)
    ] = int(
        target_count - class_count
    )


for class_id in EXPECTED_RF_CLASS_IDS:

    class_id = int(class_id)

    original_count = (
        RF3_TRAINING_CLASS_DISTRIBUTION[
            class_id
        ]
    )

    target_count = (
        RF3_OVERSAMPLING_TARGET_COUNTS[
            class_id
        ]
    )

    additional_count = (
        RF3_OVERSAMPLING_ADDITIONAL_COUNTS[
            class_id
        ]
    )


    print(
        f"✓ Class {class_id}: "
        f"{RF_CLASS_MAPPING[class_id]:<24} "
        f"Original={original_count:,} | "
        f"Target={target_count:,} | "
        f"Additional={additional_count:,}"
    )


# ---------------------------------------------------------------
# 5. OVERSAMPLING POLICY VALIDATION
# ---------------------------------------------------------------

print(
    "\n[RF-3 OVERSAMPLING POLICY VALIDATION]"
)


if RF3_SAMPLING_CONFIGURATION[
    "majority_downsampling"
] is not False:

    raise RuntimeError(
        "RF-3 majority-class downsampling must remain "
        "prohibited."
    )


for class_id in EXPECTED_RF_CLASS_IDS:

    class_id = int(class_id)

    original_count = (
        RF3_TRAINING_CLASS_DISTRIBUTION[
            class_id
        ]
    )

    target_count = (
        RF3_OVERSAMPLING_TARGET_COUNTS[
            class_id
        ]
    )


    # -----------------------------------------------------------
    # Absolute protection against downsampling.
    # -----------------------------------------------------------

    if target_count < original_count:

        raise RuntimeError(
            "RF-3 would perform prohibited "
            "majority-class downsampling."
        )


    # -----------------------------------------------------------
    # Classes below minimum support must remain unchanged.
    # -----------------------------------------------------------

    if original_count < (
        RF3_SAMPLING_CONFIGURATION[
            "minimum_training_support"
        ]
    ):

        if target_count != original_count:

            raise RuntimeError(
                f"Class {class_id} is below the minimum "
                "support threshold and must not be oversampled."
            )


    # -----------------------------------------------------------
    # Heartbleed must remain unchanged.
    # -----------------------------------------------------------

    if class_id == 8:

        if target_count != original_count:

            raise RuntimeError(
                "Heartbleed was incorrectly included "
                "in RF-3 oversampling."
            )


    # -----------------------------------------------------------
    # Eligible classes may increase up to the configured
    # maximum target, but never below their original support.
    # -----------------------------------------------------------

    if original_count < (
        RF3_SAMPLING_CONFIGURATION[
            "maximum_target_per_class"
        ]
    ):

        expected_upper_bound = min(
            original_count *
            RF3_SAMPLING_CONFIGURATION[
                "oversampling_multiplier"
            ],

            RF3_SAMPLING_CONFIGURATION[
                "maximum_target_per_class"
            ]
        )

        if target_count > expected_upper_bound:

            raise RuntimeError(
                f"RF-3 target for class {class_id} "
                "exceeds the controlled oversampling boundary."
            )


print(
    "✓ Minimum-support boundary respected"
)

print(
    "✓ 5x oversampling multiplier respected"
)

print(
    "✓ 50,000 observations/class cap respected "
    "without downsampling"
)

print(
    "✓ Majority-class downsampling prohibited"
)

print(
    "✓ Heartbleed remains excluded"
)

print(
    "✓ Infiltration remains eligible"
)

print(
    "✓ No SMOTE or synthetic sampling configured"
)


# ---------------------------------------------------------------
# 6. BUILD CONTROLLED OVERSAMPLING INDEX ARRAY
# ---------------------------------------------------------------

print(
    "\n[RF-3 OVERSAMPLED TRAINING INDEX CONSTRUCTION]"
)


RF3_OVERSAMPLING_RANDOM_GENERATOR = (
    np.random.default_rng(
        RANDOM_SEED
    )
)


RF3_TOTAL_ADDITIONAL_OBSERVATIONS = sum(
    RF3_OVERSAMPLING_ADDITIONAL_COUNTS.values()
)


RF3_ADDITIONAL_TRAINING_INDICES = np.empty(
    RF3_TOTAL_ADDITIONAL_OBSERVATIONS,
    dtype=np.int64
)


RF3_INDEX_OFFSET = 0


for class_id in EXPECTED_RF_CLASS_IDS:

    class_id = int(class_id)

    additional_count = (
        RF3_OVERSAMPLING_ADDITIONAL_COUNTS[
            class_id
        ]
    )


    if additional_count <= 0:

        continue


    class_indices = np.flatnonzero(
        RF3_TRAINING_TARGETS == class_id
    )


    if class_indices.size == 0:

        raise RuntimeError(
            f"No Training observations found for "
            f"class {class_id}."
        )


    sampled_indices = (
        RF3_OVERSAMPLING_RANDOM_GENERATOR.choice(
            class_indices,
            size=additional_count,
            replace=True
        )
    )


    next_offset = (
        RF3_INDEX_OFFSET
        +
        additional_count
    )


    RF3_ADDITIONAL_TRAINING_INDICES[
        RF3_INDEX_OFFSET:next_offset
    ] = sampled_indices


    RF3_INDEX_OFFSET = next_offset


print(
    f"✓ Original Training observations : "
    f"{RF3_TRAINING_FEATURES.shape[0]:,}"
)

print(
    f"✓ Additional sampled observations : "
    f"{RF3_TOTAL_ADDITIONAL_OBSERVATIONS:,}"
)


RF3_OVERSAMPLED_TRAINING_OBSERVATIONS = (
    RF3_TRAINING_FEATURES.shape[0]
    +
    RF3_TOTAL_ADDITIONAL_OBSERVATIONS
)


print(
    f"✓ Final RF-3 Training observations : "
    f"{RF3_OVERSAMPLED_TRAINING_OBSERVATIONS:,}"
)


# ---------------------------------------------------------------
# 7. RAM-AWARE OVERSAMPLED TRAINING ALLOCATION
# ---------------------------------------------------------------

print(
    "\n[RF-3 RAM-AWARE OVERSAMPLED TRAINING ALLOCATION]"
)


RF_MEMORY = psutil.virtual_memory()


RF3_AVAILABLE_MEMORY_BEFORE_GB = (
    RF_MEMORY.available /
    (1024 ** 3)
)


RF3_OVERSAMPLED_FEATURE_BYTES = (
    RF3_OVERSAMPLED_TRAINING_OBSERVATIONS
    *
    EXPECTED_MODEL_READY_FEATURE_COUNT
    *
    np.dtype(np.float32).itemsize
)


RF3_OVERSAMPLED_TARGET_BYTES = (
    RF3_OVERSAMPLED_TRAINING_OBSERVATIONS
    *
    np.dtype(np.int64).itemsize
)


RF3_OVERSAMPLED_DATA_GB = (
    (
        RF3_OVERSAMPLED_FEATURE_BYTES
        +
        RF3_OVERSAMPLED_TARGET_BYTES
    )
    /
    (1024 ** 3)
)


print(
    f"✓ Available system RAM : "
    f"{RF3_AVAILABLE_MEMORY_BEFORE_GB:.2f} GB"
)

print(
    f"✓ Estimated oversampled Training data : "
    f"{RF3_OVERSAMPLED_DATA_GB:.3f} GB"
)


RF3_RAM_SAFETY_RESERVE_GB = 2.0


if (
    RF3_OVERSAMPLED_DATA_GB
    +
    RF3_RAM_SAFETY_RESERVE_GB
    >=
    RF3_AVAILABLE_MEMORY_BEFORE_GB
):

    raise MemoryError(
        "Insufficient available RAM for the RF-3 "
        "oversampled Training representation while "
        "maintaining the configured safety reserve."
    )


print(
    f"✓ RAM safety reserve retained : "
    f"{RF3_RAM_SAFETY_RESERVE_GB:.1f} GB"
)


# ---------------------------------------------------------------
# 8. MATERIALIZE OVERSAMPLED TRAINING DATA
# ---------------------------------------------------------------

print(
    "\n[RF-3 OVERSAMPLED TRAINING MATERIALIZATION]"
)


RF3_OVERSAMPLED_TRAINING_FEATURES = np.empty(
    (
        RF3_OVERSAMPLED_TRAINING_OBSERVATIONS,
        EXPECTED_MODEL_READY_FEATURE_COUNT
    ),
    dtype=np.float32
)


RF3_OVERSAMPLED_TRAINING_TARGETS = np.empty(
    RF3_OVERSAMPLED_TRAINING_OBSERVATIONS,
    dtype=np.int64
)


RF3_ORIGINAL_TRAINING_OBSERVATIONS = (
    RF3_TRAINING_FEATURES.shape[0]
)


# ---------------------------------------------------------------
# Copy original Training observations.
# ---------------------------------------------------------------

RF3_OVERSAMPLED_TRAINING_FEATURES[
    :RF3_ORIGINAL_TRAINING_OBSERVATIONS
] = RF3_TRAINING_FEATURES


RF3_OVERSAMPLED_TRAINING_TARGETS[
    :RF3_ORIGINAL_TRAINING_OBSERVATIONS
] = RF3_TRAINING_TARGETS


# ---------------------------------------------------------------
# Append sampled observations in chunks.
# ---------------------------------------------------------------

RF3_ADDITIONAL_FEATURE_OFFSET = (
    RF3_ORIGINAL_TRAINING_OBSERVATIONS
)


RF3_CHUNK_SIZE = 100_000


for chunk_start in range(
    0,
    RF3_ADDITIONAL_TRAINING_INDICES.size,
    RF3_CHUNK_SIZE
):

    chunk_end = min(
        chunk_start + RF3_CHUNK_SIZE,
        RF3_ADDITIONAL_TRAINING_INDICES.size
    )


    source_indices = (
        RF3_ADDITIONAL_TRAINING_INDICES[
            chunk_start:chunk_end
        ]
    )


    destination_start = (
        RF3_ADDITIONAL_FEATURE_OFFSET
        +
        chunk_start
    )


    destination_end = (
        RF3_ADDITIONAL_FEATURE_OFFSET
        +
        chunk_end
    )


    RF3_OVERSAMPLED_TRAINING_FEATURES[
        destination_start:destination_end
    ] = RF3_TRAINING_FEATURES[
        source_indices
    ]


    RF3_OVERSAMPLED_TRAINING_TARGETS[
        destination_start:destination_end
    ] = RF3_TRAINING_TARGETS[
        source_indices
    ]


print(
    "✓ Original Training observations retained"
)

print(
    "✓ Additional observations sampled with replacement"
)

print(
    "✓ Oversampled Training features materialized as float32"
)

print(
    "✓ Oversampled Training targets materialized as int64"
)

print(
    "✓ Chunked materialization used for RAM-aware execution"
)


# ---------------------------------------------------------------
# 9. OVERSAMPLED TRAINING DISTRIBUTION VALIDATION
# ---------------------------------------------------------------

print(
    "\n[RF-3 OVERSAMPLED TRAINING CLASS DISTRIBUTION]"
)


RF3_OVERSAMPLED_CLASS_IDS, RF3_OVERSAMPLED_CLASS_COUNTS = (
    np.unique(
        RF3_OVERSAMPLED_TRAINING_TARGETS,
        return_counts=True
    )
)


RF3_OVERSAMPLED_TRAINING_CLASS_DISTRIBUTION = {
    int(class_id): int(class_count)
    for class_id, class_count
    in zip(
        RF3_OVERSAMPLED_CLASS_IDS,
        RF3_OVERSAMPLED_CLASS_COUNTS
    )
}


if not np.array_equal(
    RF3_OVERSAMPLED_CLASS_IDS,
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    )
):

    raise ValueError(
        "RF-3 oversampled Training targets do not "
        "contain the complete 0–8 RF taxonomy."
    )


for class_id in EXPECTED_RF_CLASS_IDS:

    class_id = int(class_id)

    print(
        f"✓ Class {class_id}: "
        f"{RF_CLASS_MAPPING[class_id]:<24} "
        f"Original="
        f"{RF3_TRAINING_CLASS_DISTRIBUTION[class_id]:,} | "
        f"Final="
        f"{RF3_OVERSAMPLED_TRAINING_CLASS_DISTRIBUTION[class_id]:,}"
    )


for class_id in EXPECTED_RF_CLASS_IDS:

    class_id = int(class_id)

    expected_count = (
        RF3_OVERSAMPLING_TARGET_COUNTS[
            class_id
        ]
    )

    observed_count = (
        RF3_OVERSAMPLED_TRAINING_CLASS_DISTRIBUTION[
            class_id
        ]
    )


    if observed_count != expected_count:

        raise ValueError(
            f"RF-3 class {class_id} target mismatch. "
            f"Expected {expected_count:,}, "
            f"observed {observed_count:,}."
        )


print(
    "✓ Controlled RF-3 Training class distribution confirmed"
)


# ---------------------------------------------------------------
# 10. RF-3 MODEL CONSTRUCTION
# ---------------------------------------------------------------

print("\n[RF-3 MODEL CONSTRUCTION]")


RF3_MODEL = RandomForestClassifier(
    **RF_COMMON_CONFIGURATION,
    class_weight=RF3_CONFIGURATION[
        "class_weight"
    ]
)


if not isinstance(
    RF3_MODEL,
    RandomForestClassifier
):

    raise TypeError(
        "RF3_MODEL was not created as a "
        "RandomForestClassifier."
    )


if RF3_MODEL.n_estimators != (
    RF_COMMON_CONFIGURATION[
        "n_estimators"
    ]
):

    raise RuntimeError(
        "RF-3 model n_estimators does not match "
        "the common Random Forest configuration."
    )


if RF3_MODEL.max_features != (
    RF_COMMON_CONFIGURATION[
        "max_features"
    ]
):

    raise RuntimeError(
        "RF-3 model max_features does not match "
        "the common Random Forest configuration."
    )


if RF3_MODEL.max_depth != (
    RF_COMMON_CONFIGURATION[
        "max_depth"
    ]
):

    raise RuntimeError(
        "RF-3 model max_depth does not match "
        "the common Random Forest configuration."
    )


if RF3_MODEL.bootstrap != (
    RF_COMMON_CONFIGURATION[
        "bootstrap"
    ]
):

    raise RuntimeError(
        "RF-3 model bootstrap configuration does not "
        "match the common Random Forest configuration."
    )


if RF3_MODEL.n_jobs != (
    RF_COMMON_CONFIGURATION[
        "n_jobs"
    ]
):

    raise RuntimeError(
        "RF-3 model n_jobs configuration does not "
        "match the common Random Forest configuration."
    )


if RF3_MODEL.random_state != (
    RF_COMMON_CONFIGURATION[
        "random_state"
    ]
):

    raise RuntimeError(
        "RF-3 model random_state does not "
        "match the established project seed."
    )


if RF3_MODEL.class_weight is not None:

    raise RuntimeError(
        "RF-3 must not use Random Forest class weighting."
    )


print(
    f"✓ Random Forest trees      : "
    f"{RF3_MODEL.n_estimators}"
)

print(
    f"✓ Max features            : "
    f"{RF3_MODEL.max_features}"
)

print(
    f"✓ Max depth               : "
    f"{RF3_MODEL.max_depth}"
)

print(
    f"✓ Bootstrap               : "
    f"{RF3_MODEL.bootstrap}"
)

print(
    f"✓ CPU parallelism         : "
    f"{RF3_MODEL.n_jobs}"
)

print(
    f"✓ Random state            : "
    f"{RF3_MODEL.random_state}"
)

print(
    f"✓ Class weighting         : "
    f"{RF3_MODEL.class_weight}"
)

print(
    "✓ RF-3 Random Forest model constructed"
)


# ---------------------------------------------------------------
# 11. RESOURCE STATE BEFORE FITTING
# ---------------------------------------------------------------

print(
    "\n[RESOURCE STATE BEFORE RF-3 FITTING]"
)


RF_MEMORY = psutil.virtual_memory()


RF3_AVAILABLE_MEMORY_BEFORE_FIT_GB = (
    RF_MEMORY.available /
    (1024 ** 3)
)


RF3_PROCESS_MEMORY_BEFORE_GB = (
    RF_PROCESS.memory_info().rss /
    (1024 ** 3)
)


print(
    f"✓ Available system RAM : "
    f"{RF3_AVAILABLE_MEMORY_BEFORE_FIT_GB:.2f} GB"
)

print(
    f"✓ Python process RAM   : "
    f"{RF3_PROCESS_MEMORY_BEFORE_GB:.2f} GB"
)

print(
    "✓ Authoritative Training source remains memory-mapped"
)

print(
    "✓ Oversampled Training representation materialized "
    "only for RF-3 fitting"
)

print(
    "✓ Validation input remains loaded but unused "
    "during model fitting"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 12. RF-3 MODEL FITTING
# ---------------------------------------------------------------

print("\n[RF-3 MODEL FITTING]")


RF3_TRAINING_START_TIME = (
    time.perf_counter()
)


RF3_MODEL.fit(
    RF3_OVERSAMPLED_TRAINING_FEATURES,
    RF3_OVERSAMPLED_TRAINING_TARGETS
)


RF3_TRAINING_END_TIME = (
    time.perf_counter()
)


RF3_TRAINING_TIME_SECONDS = (
    RF3_TRAINING_END_TIME
    -
    RF3_TRAINING_START_TIME
)


print(
    "✓ RF-3 model fitting completed"
)

print(
    f"✓ Training time : "
    f"{RF3_TRAINING_TIME_SECONDS:.3f} seconds"
)


# ---------------------------------------------------------------
# 13. RESOURCE STATE AFTER FITTING
# ---------------------------------------------------------------

print(
    "\n[RESOURCE STATE AFTER RF-3 FITTING]"
)


RF_MEMORY = psutil.virtual_memory()


RF3_AVAILABLE_MEMORY_AFTER_GB = (
    RF_MEMORY.available /
    (1024 ** 3)
)


RF3_PROCESS_MEMORY_AFTER_GB = (
    RF_PROCESS.memory_info().rss /
    (1024 ** 3)
)


RF3_PROCESS_MEMORY_DELTA_GB = (
    RF3_PROCESS_MEMORY_AFTER_GB
    -
    RF3_PROCESS_MEMORY_BEFORE_GB
)


print(
    f"✓ Available system RAM : "
    f"{RF3_AVAILABLE_MEMORY_AFTER_GB:.2f} GB"
)

print(
    f"✓ Python process RAM   : "
    f"{RF3_PROCESS_MEMORY_AFTER_GB:.2f} GB"
)

print(
    f"✓ Process RAM change   : "
    f"{RF3_PROCESS_MEMORY_DELTA_GB:+.2f} GB"
)


# ---------------------------------------------------------------
# 14. FITTED MODEL STRUCTURE VALIDATION
# ---------------------------------------------------------------

print(
    "\n[RF-3 FITTED MODEL VALIDATION]"
)


if not hasattr(
    RF3_MODEL,
    "n_features_in_"
):

    raise RuntimeError(
        "RF-3 fitted model does not expose n_features_in_."
    )


if RF3_MODEL.n_features_in_ != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-3 fitted model feature count does not "
        "match the established 32-feature contract."
    )


if not hasattr(
    RF3_MODEL,
    "classes_"
):

    raise RuntimeError(
        "RF-3 fitted model does not expose classes_."
    )


if not np.array_equal(
    RF3_MODEL.classes_,
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    )
):

    raise ValueError(
        "RF-3 fitted model classes do not match "
        "the established 0–8 taxonomy."
    )


if not hasattr(
    RF3_MODEL,
    "estimators_"
):

    raise RuntimeError(
        "RF-3 fitted model does not contain trained estimators."
    )


if len(
    RF3_MODEL.estimators_
) != RF_COMMON_CONFIGURATION[
    "n_estimators"
]:

    raise RuntimeError(
        "RF-3 fitted model does not contain the "
        "expected number of trained trees."
    )


print(
    f"✓ Fitted model feature count : "
    f"{RF3_MODEL.n_features_in_}"
)

print(
    f"✓ Fitted model classes       : "
    f"{len(RF3_MODEL.classes_)}"
)

print(
    f"✓ Fitted model tree count    : "
    f"{len(RF3_MODEL.estimators_)}"
)

print(
    "✓ RF-3 fitted model matches "
    "the established feature and taxonomy contracts"
)


# ---------------------------------------------------------------
# 15. DEVELOPMENT-BOUNDARY VALIDATION
# ---------------------------------------------------------------

print(
    "\n[RF-3 DEVELOPMENT-BOUNDARY VALIDATION]"
)


print(
    "✓ RF-3 fitted only using the Training partition"
)

print(
    "✓ Controlled random oversampling applied only "
    "to Training observations"
)

print(
    "✓ Validation targets were not used for fitting"
)

print(
    "✓ Validation predictions were not generated"
)

print(
    "✓ Validation distribution was not modified"
)

print(
    "✓ Independent Test features were not loaded"
)

print(
    "✓ Independent Test targets were not loaded"
)

print(
    "✓ No majority-class downsampling was performed"
)

print(
    "✓ No SMOTE was applied"
)

print(
    "✓ No synthetic samples were generated"
)

print(
    "✓ No strategy selection was performed"
)

print(
    "✓ No RF-3 evaluation metrics were calculated"
)

print(
    "✓ Model persistence was not performed "
    "in this subsection"
)


# ---------------------------------------------------------------
# 16. TEMPORARY OVERSAMPLED DATA CLEANUP
# ---------------------------------------------------------------

print(
    "\n[RF-3 TEMPORARY OVERSAMPLED DATA CLEANUP]"
)


del RF3_OVERSAMPLED_TRAINING_FEATURES
del RF3_OVERSAMPLED_TRAINING_TARGETS
del RF3_ADDITIONAL_TRAINING_INDICES


gc.collect()


print(
    "✓ Temporary oversampled Training feature array released"
)

print(
    "✓ Temporary oversampled Training target array released"
)

print(
    "✓ Temporary oversampling indices released"
)

print(
    "✓ Authoritative Training artifacts remain memory-mapped"
)

print(
    "✓ Validation artifacts remain available"
)

print(
    "✓ RF-3 fitted model retained"
)


# ---------------------------------------------------------------
# 17. FINAL RF-3 FITTING VALIDATION
# ---------------------------------------------------------------

RF_5_7_3_VALIDATION = {

    "rf3_strategy_valid":
        RF3_CONFIGURATION[
            "strategy_id"
        ] == "RF-3",

    "training_partition_used":
        RF3_CONFIGURATION[
            "training_partition"
        ] == "Training",

    "validation_partition_reserved":
        RF3_CONFIGURATION[
            "evaluation_partition"
        ] == "Validation",

    "natural_training_observations":
        RF3_ORIGINAL_TRAINING_OBSERVATIONS
        == 1_814_018,

    "oversampled_training_observations":
        RF3_OVERSAMPLED_TRAINING_OBSERVATIONS
        >= RF3_ORIGINAL_TRAINING_OBSERVATIONS,

    "oversampled_training_feature_count":
        EXPECTED_MODEL_READY_FEATURE_COUNT
        == 32,

    "oversampled_training_class_distribution_valid":
        all(
            RF3_OVERSAMPLED_TRAINING_CLASS_DISTRIBUTION[
                int(class_id)
            ]
            ==
            RF3_OVERSAMPLING_TARGET_COUNTS[
                int(class_id)
            ]
            for class_id
            in EXPECTED_RF_CLASS_IDS
        ),

    "heartbleed_not_oversampled":
        RF3_OVERSAMPLED_TRAINING_CLASS_DISTRIBUTION[
            8
        ]
        ==
        RF3_TRAINING_CLASS_DISTRIBUTION[
            8
        ],

    "majority_downsampling_disabled":
        RF3_SAMPLING_CONFIGURATION[
            "majority_downsampling"
        ]
        is False,

    "synthetic_sampling_disabled":
        RF3_CONFIGURATION[
            "synthetic_sampling"
        ]
        is False,

    "model_class_weight_disabled":
        RF3_MODEL.class_weight is None,

    "feature_count_valid":
        RF3_MODEL.n_features_in_
        ==
        EXPECTED_MODEL_READY_FEATURE_COUNT,

    "taxonomy_valid":
        np.array_equal(
            RF3_MODEL.classes_,
            np.asarray(
                EXPECTED_RF_CLASS_IDS
            )
        ),

    "tree_count_valid":
        len(
            RF3_MODEL.estimators_
        )
        ==
        RF_COMMON_CONFIGURATION[
            "n_estimators"
        ],

    "random_state_valid":
        RF3_MODEL.random_state
        ==
        RANDOM_SEED,

    "training_time_recorded":
        RF3_TRAINING_TIME_SECONDS
        > 0,

    "independent_test_not_used":
        True,
}


failed_checks = [

    check_name

    for check_name, passed
    in RF_5_7_3_VALIDATION.items()

    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.7.3 RF-3 model fitting validation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 18. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.7.3 — RF-3 CONTROLLED RANDOM OVERSAMPLING "
    "AND RANDOM FOREST MODEL FITTING PASSED"
)

print("=" * 72)

print(
    "\n✓ RF-3 Controlled Random Oversampling "
    "performed successfully"
)

print(
    "✓ Complete Training partition retained"
)

print(
    "✓ Eligible minority observations sampled "
    "with replacement"
)

print(
    "✓ Minimum-support boundary respected"
)

print(
    "✓ 5x oversampling multiplier respected"
)

print(
    "✓ 50,000 observations/class cap respected "
    "without downsampling"
)

print(
    "✓ Majority-class downsampling prohibited"
)

print(
    "✓ Heartbleed remained excluded"
)

print(
    "✓ Infiltration remained eligible"
)

print(
    "✓ No SMOTE or synthetic observations generated"
)

print(
    "✓ Common Random Forest configuration retained"
)

print(
    "✓ 32-feature model-ready representation confirmed"
)

print(
    "✓ Nine-class taxonomy confirmed"
)

print(
    "✓ Validation remains reserved for subsequent "
    "RF-3 evaluation"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "\nREADY FOR 5.7.4 — "
    "RF-3 VALIDATION PREDICTION AND PERFORMANCE EVALUATION"
)

print("=" * 72)

========================================================================
5.7.3 — RF-3 CONTROLLED RANDOM OVERSAMPLING AND RANDOM FOREST MODEL FITTING
========================================================================

[RF-3 FITTING BOUNDARY VALIDATION]
✓ RF-3 controlled random oversampling definition validated
✓ Complete Training features available
✓ Complete Training targets available
✓ Training features and targets are aligned
✓ Training features remain memory-mapped
✓ Random Forest class weighting disabled
✓ Controlled random oversampling configured
✓ Synthetic sampling disabled
✓ Training partition authorized for model fitting

[TRAINING FEATURE-SPACE VALIDATION]
✓ Training observations : 1,814,018
✓ Training features     : 32
✓ Training dtype        : float32
✓ Training feature space matches the frozen RF model-ready contract

[RF-3 NATURAL TRAINING CLASS DISTRIBUTION]
✓ Class 0: BENIGN                   1,448,197
✓ Class 1: DDoS                     81,968
✓ Class 2: Port Scan                101,723
✓ Class 3: Brute Force              9,325
✓ Class 4: Bot                      1,270
✓ Class 5: Web Attack               1,389
✓ Class 6: Infiltration             15
✓ Class 7: DoS                      170,125
✓ Class 8: Heartbleed               6
✓ Complete natural Training class distribution confirmed for RF-3

[RF-3 CONTROLLED RANDOM OVERSAMPLING PLAN]
✓ Class 0: BENIGN                   Original=1,448,197 | Target=1,448,197 | Additional=0
✓ Class 1: DDoS                     Original=81,968 | Target=81,968 | Additional=0
✓ Class 2: Port Scan                Original=101,723 | Target=101,723 | Additional=0
✓ Class 3: Brute Force              Original=9,325 | Target=46,625 | Additional=37,300
✓ Class 4: Bot                      Original=1,270 | Target=6,350 | Additional=5,080
✓ Class 5: Web Attack               Original=1,389 | Target=6,945 | Additional=5,556
✓ Class 6: Infiltration             Original=15 | Target=75 | Additional=60
✓ Class 7: DoS                      Original=170,125 | Target=170,125 | Additional=0
✓ Class 8: Heartbleed               Original=6 | Target=6 | Additional=0

[RF-3 OVERSAMPLING POLICY VALIDATION]
✓ Minimum-support boundary respected
✓ 5x oversampling multiplier respected
✓ 50,000 observations/class cap respected without downsampling
✓ Majority-class downsampling prohibited
✓ Heartbleed remains excluded
✓ Infiltration remains eligible
✓ No SMOTE or synthetic sampling configured

[RF-3 OVERSAMPLED TRAINING INDEX CONSTRUCTION]
✓ Original Training observations : 1,814,018
✓ Additional sampled observations : 47,996
✓ Final RF-3 Training observations : 1,862,014

[RF-3 RAM-AWARE OVERSAMPLED TRAINING ALLOCATION]
✓ Available system RAM : 9.82 GB
✓ Estimated oversampled Training data : 0.236 GB
✓ RAM safety reserve retained : 2.0 GB

[RF-3 OVERSAMPLED TRAINING MATERIALIZATION]
✓ Original Training observations retained
✓ Additional observations sampled with replacement
✓ Oversampled Training features materialized as float32
✓ Oversampled Training targets materialized as int64
✓ Chunked materialization used for RAM-aware execution

[RF-3 OVERSAMPLED TRAINING CLASS DISTRIBUTION]
✓ Class 0: BENIGN                   Original=1,448,197 | Final=1,448,197
✓ Class 1: DDoS                     Original=81,968 | Final=81,968
✓ Class 2: Port Scan                Original=101,723 | Final=101,723
✓ Class 3: Brute Force              Original=9,325 | Final=46,625
✓ Class 4: Bot                      Original=1,270 | Final=6,350
✓ Class 5: Web Attack               Original=1,389 | Final=6,945
✓ Class 6: Infiltration             Original=15 | Final=75
✓ Class 7: DoS                      Original=170,125 | Final=170,125
✓ Class 8: Heartbleed               Original=6 | Final=6
✓ Controlled RF-3 Training class distribution confirmed

[RF-3 MODEL CONSTRUCTION]
✓ Random Forest trees      : 100
✓ Max features            : sqrt
✓ Max depth               : None
✓ Bootstrap               : True
✓ CPU parallelism         : -1
✓ Random state            : 42
✓ Class weighting         : None
✓ RF-3 Random Forest model constructed

[RESOURCE STATE BEFORE RF-3 FITTING]
✓ Available system RAM : 9.61 GB
✓ Python process RAM   : 2.02 GB
✓ Authoritative Training source remains memory-mapped
✓ Oversampled Training representation materialized only for RF-3 fitting
✓ Validation input remains loaded but unused during model fitting
✓ Independent Test remains untouched

[RF-3 MODEL FITTING]
✓ RF-3 model fitting completed
✓ Training time : 626.403 seconds

[RESOURCE STATE AFTER RF-3 FITTING]
✓ Available system RAM : 9.56 GB
✓ Python process RAM   : 2.02 GB
✓ Process RAM change   : +0.00 GB

[RF-3 FITTED MODEL VALIDATION]
✓ Fitted model feature count : 32
✓ Fitted model classes       : 9
✓ Fitted model tree count    : 100
✓ RF-3 fitted model matches the established feature and taxonomy contracts

[RF-3 DEVELOPMENT-BOUNDARY VALIDATION]
✓ RF-3 fitted only using the Training partition
✓ Controlled random oversampling applied only to Training observations
✓ Validation targets were not used for fitting
✓ Validation predictions were not generated
✓ Validation distribution was not modified
✓ Independent Test features were not loaded
✓ Independent Test targets were not loaded
✓ No majority-class downsampling was performed
✓ No SMOTE was applied
✓ No synthetic samples were generated
✓ No strategy selection was performed
✓ No RF-3 evaluation metrics were calculated
✓ Model persistence was not performed in this subsection

[RF-3 TEMPORARY OVERSAMPLED DATA CLEANUP]
✓ Temporary oversampled Training feature array released
✓ Temporary oversampled Training target array released
✓ Temporary oversampling indices released
✓ Authoritative Training artifacts remain memory-mapped
✓ Validation artifacts remain available
✓ RF-3 fitted model retained

========================================================================
5.7.3 — RF-3 CONTROLLED RANDOM OVERSAMPLING AND RANDOM FOREST MODEL FITTING PASSED
========================================================================

✓ RF-3 Controlled Random Oversampling performed successfully
✓ Complete Training partition retained
✓ Eligible minority observations sampled with replacement
✓ Minimum-support boundary respected
✓ 5x oversampling multiplier respected
✓ 50,000 observations/class cap respected without downsampling
✓ Majority-class downsampling prohibited
✓ Heartbleed remained excluded
✓ Infiltration remained eligible
✓ No SMOTE or synthetic observations generated
✓ Common Random Forest configuration retained
✓ 32-feature model-ready representation confirmed
✓ Nine-class taxonomy confirmed
✓ Validation remains reserved for subsequent RF-3 evaluation
✓ Independent Test remains completely untouched

READY FOR 5.7.4 — RF-3 VALIDATION PREDICTION AND PERFORMANCE EVALUATION
========================================================================

# 5.7.4 — RF-3 VALIDATION PREDICTION AND PERFORMANCE EVALUATION

This subsection evaluates the RF-3 Random Forest trained using controlled
random oversampling of the Training partition.

The RF-3 model is evaluated exclusively on the complete, original
Validation partition. No oversampling, resampling, synthetic sampling,
or modification of the Validation observations is performed during
evaluation.

The controlled random oversampling applied in Section 5.7.3 is therefore
restricted entirely to the Training partition. The Validation partition
retains its original class distribution and remains directly comparable
with the Validation evaluations of RF-0, RF-1, and RF-2.

The evaluation follows the established Random Forest evaluation protocol,
including:

- Validation predictions over all 451,215 observations
- Accuracy
- Balanced Accuracy
- Macro Recall
- Macro F1
- Weighted F1
- Per-class Precision, Recall, F1, and Support
- Nine-class confusion matrix
- BENIGN false-positive rate
- Attack-class false negatives
- Supplementary multiclass Macro ROC-AUC using One-vs-Rest probabilities

The Independent Test partition remains completely excluded.

No RF strategy selection is performed in this subsection. RF-3 remains
an independent experiment available for the later validation-based
strategy comparison and selection stage.

In [ ]:
# ================================================================
# 5.7.4 — RF-3 VALIDATION PREDICTION AND PERFORMANCE EVALUATION
# ================================================================

import numpy as np
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_recall_fscore_support,
    f1_score,
    recall_score,
    confusion_matrix,
    roc_auc_score
)

print("=" * 72)
print("5.7.4 — RF-3 VALIDATION PREDICTION AND PERFORMANCE EVALUATION")
print("=" * 72)


# ---------------------------------------------------------------
# [RF-3 EVALUATION BOUNDARY VALIDATION]
# ---------------------------------------------------------------

print("\n[RF-3 EVALUATION BOUNDARY VALIDATION]")


if RF3_MODEL is None:

    raise ValueError(
        "RF-3 fitted model is not available."
    )


if RF3_VALIDATION_FEATURES.shape != (451215, 32):

    raise ValueError(
        f"Unexpected RF-3 Validation feature shape: "
        f"{RF3_VALIDATION_FEATURES.shape}"
    )


if RF3_VALIDATION_TARGETS.shape != (451215,):

    raise ValueError(
        f"Unexpected RF-3 Validation target shape: "
        f"{RF3_VALIDATION_TARGETS.shape}"
    )


if RF3_VALIDATION_FEATURES.dtype != np.float32:

    raise TypeError(
        f"RF-3 Validation features must be float32, "
        f"got {RF3_VALIDATION_FEATURES.dtype}"
    )


if RF3_VALIDATION_TARGETS.dtype != np.int64:

    raise TypeError(
        f"RF-3 Validation targets must be int64, "
        f"got {RF3_VALIDATION_TARGETS.dtype}"
    )


if len(RF3_VALIDATION_FEATURES) != len(
    RF3_VALIDATION_TARGETS
):

    raise ValueError(
        "RF-3 Validation X/y observations are not aligned."
    )


print(
    "✓ RF-3 fitted model is available"
)

print(
    "✓ Complete Validation feature artifact is available"
)

print(
    "✓ Complete Validation target artifact is available"
)

print(
    "✓ Validation X/y observations are aligned"
)

print(
    "✓ Validation feature representation = "
    "32 float32 features"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# [RF-3 TRAINING / OVERSAMPLING BOUNDARY]
# ---------------------------------------------------------------

print(
    "\n[RF-3 TRAINING / OVERSAMPLING BOUNDARY]"
)


if RF3_CONFIGURATION[
    "resampling"
] is not True:

    raise RuntimeError(
        "RF-3 controlled random oversampling configuration "
        "is not enabled."
    )


if RF3_CONFIGURATION[
    "synthetic_sampling"
] is not False:

    raise RuntimeError(
        "RF-3 must not use synthetic sampling."
    )


if RF3_CONFIGURATION[
    "class_weight"
] is not None:

    raise RuntimeError(
        "RF-3 must not use Random Forest class weighting."
    )


print(
    "✓ RF-3 controlled random oversampling was a "
    "Training-stage operation"
)

print(
    "✓ Validation data remain in their original distribution"
)

print(
    "✓ No oversampling applied to Validation"
)

print(
    "✓ No synthetic sampling applied to Validation"
)

print(
    "✓ No Random Forest class weighting applied"
)


# ---------------------------------------------------------------
# [RF-3 VALIDATION PREDICTION]
# ---------------------------------------------------------------

print("\n[RF-3 VALIDATION PREDICTION]")


RF3_VALIDATION_PREDICTIONS = RF3_MODEL.predict(
    RF3_VALIDATION_FEATURES
)


if RF3_VALIDATION_PREDICTIONS.shape != (
    RF3_VALIDATION_TARGETS.shape
):

    raise ValueError(
        "RF-3 Validation prediction shape does not match "
        "Validation targets."
    )


if not np.isfinite(
    RF3_VALIDATION_PREDICTIONS
).all():

    raise ValueError(
        "RF-3 Validation predictions contain "
        "non-finite values."
    )


print(
    f"✓ Validation predictions generated : "
    f"{RF3_VALIDATION_PREDICTIONS.shape[0]:,}"
)

print(
    "✓ Validation predictions correspond to the complete "
    "Validation partition"
)

print(
    "✓ No Independent Test predictions generated"
)


# ---------------------------------------------------------------
# [PRIMARY AND SECONDARY PERFORMANCE METRICS]
# ---------------------------------------------------------------

print(
    "\n[PRIMARY AND SECONDARY PERFORMANCE METRICS]"
)


RF3_VALIDATION_ACCURACY = accuracy_score(
    RF3_VALIDATION_TARGETS,
    RF3_VALIDATION_PREDICTIONS
)


RF3_VALIDATION_BALANCED_ACCURACY = (
    balanced_accuracy_score(
        RF3_VALIDATION_TARGETS,
        RF3_VALIDATION_PREDICTIONS
    )
)


RF3_VALIDATION_MACRO_F1 = f1_score(
    RF3_VALIDATION_TARGETS,
    RF3_VALIDATION_PREDICTIONS,
    average="macro",
    zero_division=0
)


RF3_VALIDATION_MACRO_RECALL = recall_score(
    RF3_VALIDATION_TARGETS,
    RF3_VALIDATION_PREDICTIONS,
    average="macro",
    zero_division=0
)


RF3_VALIDATION_WEIGHTED_F1 = f1_score(
    RF3_VALIDATION_TARGETS,
    RF3_VALIDATION_PREDICTIONS,
    average="weighted",
    zero_division=0
)


print(
    f"✓ Accuracy              : "
    f"{RF3_VALIDATION_ACCURACY:.6f}"
)

print(
    f"✓ Balanced Accuracy     : "
    f"{RF3_VALIDATION_BALANCED_ACCURACY:.6f}"
)

print(
    f"✓ Macro Recall          : "
    f"{RF3_VALIDATION_MACRO_RECALL:.6f}"
)

print(
    f"✓ Macro F1              : "
    f"{RF3_VALIDATION_MACRO_F1:.6f}"
)

print(
    f"✓ Weighted F1           : "
    f"{RF3_VALIDATION_WEIGHTED_F1:.6f}"
)


# ---------------------------------------------------------------
# [PER-CLASS PERFORMANCE METRICS]
# ---------------------------------------------------------------

print("\n[PER-CLASS PERFORMANCE METRICS]")


(
    RF3_VALIDATION_PRECISION_PER_CLASS,
    RF3_VALIDATION_RECALL_PER_CLASS,
    RF3_VALIDATION_F1_PER_CLASS,
    RF3_VALIDATION_SUPPORT_PER_CLASS
) = precision_recall_fscore_support(
    RF3_VALIDATION_TARGETS,
    RF3_VALIDATION_PREDICTIONS,
    labels=np.arange(9),
    zero_division=0
)


RF3_VALIDATION_CLASS_NAMES = [
    "BENIGN",
    "DDoS",
    "Port Scan",
    "Brute Force",
    "Bot",
    "Web Attack",
    "Infiltration",
    "DoS",
    "Heartbleed"
]


for class_id, class_name in enumerate(
    RF3_VALIDATION_CLASS_NAMES
):

    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Precision="
        f"{RF3_VALIDATION_PRECISION_PER_CLASS[class_id]:.6f} | "
        f"Recall="
        f"{RF3_VALIDATION_RECALL_PER_CLASS[class_id]:.6f} | "
        f"F1="
        f"{RF3_VALIDATION_F1_PER_CLASS[class_id]:.6f} | "
        f"Support="
        f"{RF3_VALIDATION_SUPPORT_PER_CLASS[class_id]:,}"
    )


# ---------------------------------------------------------------
# [CONFUSION MATRIX]
# ---------------------------------------------------------------

print("\n[CONFUSION MATRIX]")


RF3_VALIDATION_CONFUSION_MATRIX = confusion_matrix(
    RF3_VALIDATION_TARGETS,
    RF3_VALIDATION_PREDICTIONS,
    labels=np.arange(9)
)


if RF3_VALIDATION_CONFUSION_MATRIX.shape != (
    9,
    9
):

    raise ValueError(
        f"Unexpected RF-3 confusion-matrix shape: "
        f"{RF3_VALIDATION_CONFUSION_MATRIX.shape}"
    )


print(
    "✓ 9 × 9 confusion matrix generated"
)

print(
    "✓ All nine taxonomy classes included"
)


print(
    "\nRF-3 Validation Confusion Matrix:"
)

print(
    RF3_VALIDATION_CONFUSION_MATRIX
)


# ---------------------------------------------------------------
# [BENIGN FALSE-POSITIVE RATE]
# ---------------------------------------------------------------

print("\n[BENIGN FALSE-POSITIVE RATE]")


RF3_BENIGN_TRUE_NEGATIVES = (
    RF3_VALIDATION_CONFUSION_MATRIX[0, 0]
)


RF3_BENIGN_FALSE_POSITIVES = (
    RF3_VALIDATION_CONFUSION_MATRIX[:, 0].sum()
    - RF3_BENIGN_TRUE_NEGATIVES
)


RF3_BENIGN_ACTUAL_NEGATIVES = (
    RF3_VALIDATION_CONFUSION_MATRIX[1:, :].sum()
)


if RF3_BENIGN_ACTUAL_NEGATIVES == 0:

    RF3_BENIGN_FALSE_POSITIVE_RATE = 0.0

else:

    RF3_BENIGN_FALSE_POSITIVE_RATE = (
        RF3_BENIGN_FALSE_POSITIVES
        / RF3_BENIGN_ACTUAL_NEGATIVES
    )


print(
    f"✓ BENIGN false-positive rate : "
    f"{RF3_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)


# ---------------------------------------------------------------
# [ATTACK FALSE NEGATIVES]
# ---------------------------------------------------------------

print("\n[ATTACK FALSE NEGATIVES]")


RF3_ATTACK_FALSE_NEGATIVES = {}


for class_id in range(1, 9):

    false_negatives = (
        RF3_VALIDATION_CONFUSION_MATRIX[class_id, :].sum()
        - RF3_VALIDATION_CONFUSION_MATRIX[
            class_id,
            class_id
        ]
    )


    RF3_ATTACK_FALSE_NEGATIVES[class_id] = int(
        false_negatives
    )


    print(
        f"✓ Class {class_id}: "
        f"{RF3_VALIDATION_CLASS_NAMES[class_id]:<15} "
        f"false negatives = {false_negatives:,}"
    )


# ---------------------------------------------------------------
# [SUPPLEMENTARY MULTICLASS ROC-AUC]
# ---------------------------------------------------------------

print("\n[SUPPLEMENTARY MULTICLASS ROC-AUC]")


RF3_VALIDATION_ROC_AUC = None


try:

    RF3_VALIDATION_PROBABILITIES = (
        RF3_MODEL.predict_proba(
            RF3_VALIDATION_FEATURES
        )
    )


    RF3_VALIDATION_ROC_AUC = roc_auc_score(
        RF3_VALIDATION_TARGETS,
        RF3_VALIDATION_PROBABILITIES,
        multi_class="ovr",
        average="macro",
        labels=np.arange(9)
    )


    print(
        f"✓ Macro ROC-AUC (OvR) : "
        f"{RF3_VALIDATION_ROC_AUC:.6f}"
    )


except ValueError as error:

    print(
        "⚠ Macro ROC-AUC could not be calculated reliably: "
        f"{error}"
    )


# Release only the temporary probability array.
# Validation features/targets and the fitted RF-3 model
# remain available.

if "RF3_VALIDATION_PROBABILITIES" in locals():

    del RF3_VALIDATION_PROBABILITIES


# ---------------------------------------------------------------
# [RF-3 VALIDATION EVALUATION SUMMARY]
# ---------------------------------------------------------------

print(
    "\n[RF-3 VALIDATION EVALUATION SUMMARY]"
)


print(
    f"✓ Primary metric — Macro F1       : "
    f"{RF3_VALIDATION_MACRO_F1:.6f}"
)


print(
    f"✓ Macro Recall                    : "
    f"{RF3_VALIDATION_MACRO_RECALL:.6f}"
)


print(
    f"✓ Balanced Accuracy               : "
    f"{RF3_VALIDATION_BALANCED_ACCURACY:.6f}"
)


print(
    f"✓ Weighted F1                     : "
    f"{RF3_VALIDATION_WEIGHTED_F1:.6f}"
)


print(
    f"✓ Accuracy                        : "
    f"{RF3_VALIDATION_ACCURACY:.6f}"
)


print(
    f"✓ BENIGN False-Positive Rate     : "
    f"{RF3_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)


if RF3_VALIDATION_ROC_AUC is not None:

    print(
        f"✓ Macro ROC-AUC (OvR)            : "
        f"{RF3_VALIDATION_ROC_AUC:.6f}"
    )


# ---------------------------------------------------------------
# [DEVELOPMENT-BOUNDARY VALIDATION]
# ---------------------------------------------------------------

print(
    "\n[DEVELOPMENT-BOUNDARY VALIDATION]"
)


print(
    "✓ RF-3 was fitted only on the controlled "
    "Training representation"
)

print(
    "✓ Validation was used only for RF-3 "
    "performance evaluation"
)

print(
    "✓ RF-3 oversampling was restricted to Training"
)

print(
    "✓ Validation distribution was not modified"
)

print(
    "✓ RF-3 strategy selection has not been performed"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ No resampling or synthetic sampling performed "
    "during Validation evaluation"
)

print(
    "✓ No model parameters modified during evaluation"
)


# ---------------------------------------------------------------
# [RF-3 EVALUATION VALIDATION]
# ---------------------------------------------------------------

RF_5_7_4_VALIDATION = {

    "rf3_model_available":
        RF3_MODEL is not None,

    "validation_prediction_count":
        RF3_VALIDATION_PREDICTIONS.shape
        == RF3_VALIDATION_TARGETS.shape,

    "validation_prediction_count_expected":
        RF3_VALIDATION_PREDICTIONS.shape
        == (451215,),

    "accuracy_recorded":
        np.isfinite(
            RF3_VALIDATION_ACCURACY
        ),

    "balanced_accuracy_recorded":
        np.isfinite(
            RF3_VALIDATION_BALANCED_ACCURACY
        ),

    "macro_recall_recorded":
        np.isfinite(
            RF3_VALIDATION_MACRO_RECALL
        ),

    "macro_f1_recorded":
        np.isfinite(
            RF3_VALIDATION_MACRO_F1
        ),

    "weighted_f1_recorded":
        np.isfinite(
            RF3_VALIDATION_WEIGHTED_F1
        ),

    "per_class_metrics_recorded":
        len(
            RF3_VALIDATION_PRECISION_PER_CLASS
        ) == 9
        and
        len(
            RF3_VALIDATION_RECALL_PER_CLASS
        ) == 9
        and
        len(
            RF3_VALIDATION_F1_PER_CLASS
        ) == 9
        and
        len(
            RF3_VALIDATION_SUPPORT_PER_CLASS
        ) == 9,

    "confusion_matrix_valid":
        RF3_VALIDATION_CONFUSION_MATRIX.shape
        == (9, 9),

    "benign_false_positive_rate_recorded":
        np.isfinite(
            RF3_BENIGN_FALSE_POSITIVE_RATE
        ),

    "attack_false_negatives_recorded":
        len(
            RF3_ATTACK_FALSE_NEGATIVES
        ) == 8,

    "oversampling_restricted_to_training":
        RF3_CONFIGURATION[
            "resampling"
        ] is True,

    "synthetic_sampling_disabled":
        RF3_CONFIGURATION[
            "synthetic_sampling"
        ] is False,

    "independent_test_not_used":
        True,

    "strategy_selection_not_performed":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_7_4_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.7.4 RF-3 Validation evaluation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# [FINAL STATUS]
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.7.4 — RF-3 VALIDATION PREDICTION AND "
    "PERFORMANCE EVALUATION PASSED"
)

print("=" * 72)


print(
    "\nRF-3 Validation evaluation completed."
)


print(
    "✓ Controlled oversampling remained restricted "
    "to Training"
)

print(
    "✓ Original Validation partition evaluated without "
    "resampling"
)

print(
    "✓ Complete Validation prediction set evaluated"
)

print(
    "✓ Nine-class performance metrics recorded"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ RF-3 strategy selection has not been performed"
)


print(
    "\nREADY FOR 5.7.5 — "
    "RF-3 Error and Resource Analysis"
)

print("=" * 72)

========================================================================
5.7.4 — RF-3 VALIDATION PREDICTION AND PERFORMANCE EVALUATION
========================================================================

[RF-3 EVALUATION BOUNDARY VALIDATION]
✓ RF-3 fitted model is available
✓ Complete Validation feature artifact is available
✓ Complete Validation target artifact is available
✓ Validation X/y observations are aligned
✓ Validation feature representation = 32 float32 features
✓ Independent Test remains excluded

[RF-3 TRAINING / OVERSAMPLING BOUNDARY]
✓ RF-3 controlled random oversampling was a Training-stage operation
✓ Validation data remain in their original distribution
✓ No oversampling applied to Validation
✓ No synthetic sampling applied to Validation
✓ No Random Forest class weighting applied

[RF-3 VALIDATION PREDICTION]
✓ Validation predictions generated : 451,215
✓ Validation predictions correspond to the complete Validation partition
✓ No Independent Test predictions generated

[PRIMARY AND SECONDARY PERFORMANCE METRICS]
✓ Accuracy              : 0.997241
✓ Balanced Accuracy     : 0.853307
✓ Macro Recall          : 0.853307
✓ Macro F1              : 0.883470
✓ Weighted F1           : 0.997243

[PER-CLASS PERFORMANCE METRICS]
✓ 0: BENIGN          Precision=0.997945 | Recall=0.998714 | F1=0.998329 | Support=369,501
✓ 1: DDoS            Precision=0.999804 | Recall=0.999756 | F1=0.999780 | Support=20,458
✓ 2: Port Scan       Precision=0.994193 | Recall=0.996318 | F1=0.995255 | Support=25,261
✓ 3: Brute Force     Precision=0.995621 | Recall=0.976907 | F1=0.986175 | Support=1,862
✓ 4: Bot             Precision=0.559748 | Recall=0.599327 | F1=0.578862 | Support=297
✓ 5: Web Attack      Precision=0.991713 | Recall=0.988981 | F1=0.990345 | Support=363
✓ 6: Infiltration    Precision=1.000000 | Recall=0.384615 | F1=0.555556 | Support=13
✓ 7: DoS             Precision=0.994478 | Recall=0.985145 | F1=0.989789 | Support=33,456
✓ 8: Heartbleed      Precision=1.000000 | Recall=0.750000 | F1=0.857143 | Support=4

[CONFUSION MATRIX]
✓ 9 × 9 confusion matrix generated
✓ All nine taxonomy classes included

RF-3 Validation Confusion Matrix:
[[369026      4    143      8    140      3      0    177      0]
 [     4  20453      0      0      0      0      0      1      0]
 [    88      0  25168      0      0      0      0      5      0]
 [    43      0      0   1819      0      0      0      0      0]
 [   119      0      0      0    178      0      0      0      0]
 [     2      0      2      0      0    359      0      0      0]
 [     8      0      0      0      0      0      5      0      0]
 [   495      0      2      0      0      0      0  32959      0]
 [     1      0      0      0      0      0      0      0      3]]

[BENIGN FALSE-POSITIVE RATE]
✓ BENIGN false-positive rate : 0.009301

[ATTACK FALSE NEGATIVES]
✓ Class 1: DDoS            false negatives = 5
✓ Class 2: Port Scan       false negatives = 93
✓ Class 3: Brute Force     false negatives = 43
✓ Class 4: Bot             false negatives = 119
✓ Class 5: Web Attack      false negatives = 4
✓ Class 6: Infiltration    false negatives = 8
✓ Class 7: DoS             false negatives = 497
✓ Class 8: Heartbleed      false negatives = 1

[SUPPLEMENTARY MULTICLASS ROC-AUC]
✓ Macro ROC-AUC (OvR) : 0.989372

[RF-3 VALIDATION EVALUATION SUMMARY]
✓ Primary metric — Macro F1       : 0.883470
✓ Macro Recall                    : 0.853307
✓ Balanced Accuracy               : 0.853307
✓ Weighted F1                     : 0.997243
✓ Accuracy                        : 0.997241
✓ BENIGN False-Positive Rate     : 0.009301
✓ Macro ROC-AUC (OvR)            : 0.989372

[DEVELOPMENT-BOUNDARY VALIDATION]
✓ RF-3 was fitted only on the controlled Training representation
✓ Validation was used only for RF-3 performance evaluation
✓ RF-3 oversampling was restricted to Training
✓ Validation distribution was not modified
✓ RF-3 strategy selection has not been performed
✓ Independent Test remains completely untouched
✓ No resampling or synthetic sampling performed during Validation evaluation
✓ No model parameters modified during evaluation

========================================================================
5.7.4 — RF-3 VALIDATION PREDICTION AND PERFORMANCE EVALUATION PASSED
========================================================================

RF-3 Validation evaluation completed.
✓ Controlled oversampling remained restricted to Training
✓ Original Validation partition evaluated without resampling
✓ Complete Validation prediction set evaluated
✓ Nine-class performance metrics recorded
✓ Independent Test remains completely untouched
✓ RF-3 strategy selection has not been performed

READY FOR 5.7.5 — RF-3 Error and Resource Analysis
========================================================================

# 5.7.5 — RF-3 ERROR AND RESOURCE ANALYSIS

This subsection performs detailed error analysis and resource analysis
for the RF-3 Controlled Random Oversampling experiment.

The analysis is performed exclusively using the RF-3 Validation
predictions, Validation targets, Validation confusion matrix, fitted
RF-3 model, and previously recorded RF-3 performance results.

RF-3 controlled random oversampling was applied only to the Training
partition during model fitting. The original Validation partition
remains in its natural distribution and is analyzed without any
oversampling or resampling.

The analysis includes:

- class-wise error analysis
- top confusion-pair analysis
- BENIGN false-positive analysis
- attack false-negative analysis
- minority-class error analysis
- Random Forest resource/model configuration analysis
- current RAM and process-resource observation
- RF-3 performance summary
- development-boundary validation

No additional model fitting, resampling, synthetic sampling,
Validation modification, strategy selection, or Independent Test
evaluation is performed in this subsection.

The Independent Test partition remains completely protected.

The purpose of this subsection is to determine where RF-3 makes
errors, how controlled Training-partition oversampling affected
minority-class detection, and what computational resources were
required, before RF-3 artifacts are persisted and the experiment is
concluded.

In [ ]:
# ================================================================
# 5.7.5 — RF-3 ERROR AND RESOURCE ANALYSIS
# ================================================================

import os
import psutil
import numpy as np


print("=" * 72)
print("5.7.5 — RF-3 ERROR AND RESOURCE ANALYSIS")
print("=" * 72)


# ---------------------------------------------------------------
# [RF-3 ANALYSIS BOUNDARY VALIDATION]
# ---------------------------------------------------------------

print("\n[RF-3 ANALYSIS BOUNDARY VALIDATION]")


if RF3_MODEL is None:

    raise ValueError(
        "RF-3 fitted model is not available."
    )


if RF3_VALIDATION_TARGETS.shape != (
    RF3_VALIDATION_PREDICTIONS.shape
):

    raise ValueError(
        "RF-3 Validation targets and predictions are not aligned."
    )


if RF3_VALIDATION_CONFUSION_MATRIX.shape != (
    9,
    9
):

    raise ValueError(
        "RF-3 Validation confusion matrix must have shape (9, 9)."
    )


print(
    "✓ RF-3 fitted model is available"
)

print(
    "✓ Validation targets are available"
)

print(
    "✓ Validation predictions are available"
)

print(
    "✓ Validation confusion matrix is available"
)

print(
    "✓ Independent Test remains excluded"
)

print(
    "✓ No model fitting will be performed"
)

print(
    "✓ No additional resampling will be performed"
)

print(
    "✓ No synthetic sampling will be performed"
)


# ---------------------------------------------------------------
# [CLASS-WISE ERROR ANALYSIS]
# ---------------------------------------------------------------

print("\n[CLASS-WISE ERROR ANALYSIS]")


RF3_VALIDATION_CLASS_ERRORS = {}


for class_id, class_name in enumerate(
    RF3_VALIDATION_CLASS_NAMES
):

    actual_count = int(
        RF3_VALIDATION_CONFUSION_MATRIX[
            class_id,
            :
        ].sum()
    )


    correct_count = int(
        RF3_VALIDATION_CONFUSION_MATRIX[
            class_id,
            class_id
        ]
    )


    false_negative_count = (
        actual_count -
        correct_count
    )


    RF3_VALIDATION_CLASS_ERRORS[class_id] = {

        "class_name":
            class_name,

        "support":
            actual_count,

        "correct_predictions":
            correct_count,

        "false_negatives":
            false_negative_count,

        "recall":
            float(
                RF3_VALIDATION_RECALL_PER_CLASS[
                    class_id
                ]
            ),

        "f1":
            float(
                RF3_VALIDATION_F1_PER_CLASS[
                    class_id
                ]
            ),
    }


    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Support={actual_count:,} | "
        f"Correct={correct_count:,} | "
        f"FN={false_negative_count:,}"
    )


# ---------------------------------------------------------------
# [TOP CONFUSION PAIRS]
# ---------------------------------------------------------------

print("\n[TOP CONFUSION PAIRS]")


RF3_VALIDATION_CONFUSION_PAIRS = []


for actual_class in range(9):

    for predicted_class in range(9):

        if actual_class == predicted_class:

            continue


        count = int(
            RF3_VALIDATION_CONFUSION_MATRIX[
                actual_class,
                predicted_class
            ]
        )


        if count > 0:

            RF3_VALIDATION_CONFUSION_PAIRS.append(
                (
                    count,
                    actual_class,
                    predicted_class
                )
            )


RF3_VALIDATION_CONFUSION_PAIRS.sort(
    key=lambda item: item[0],
    reverse=True
)


RF3_VALIDATION_TOP_CONFUSION_PAIRS = (
    RF3_VALIDATION_CONFUSION_PAIRS[:10]
)


if RF3_VALIDATION_TOP_CONFUSION_PAIRS:

    for rank, (
        count,
        actual_class,
        predicted_class
    ) in enumerate(
        RF3_VALIDATION_TOP_CONFUSION_PAIRS,
        start=1
    ):

        print(
            f"{rank:>2}. "
            f"Actual="
            f"{RF3_VALIDATION_CLASS_NAMES[actual_class]:<15} "
            f"→ Predicted="
            f"{RF3_VALIDATION_CLASS_NAMES[predicted_class]:<15} "
            f"| Count={count:,}"
        )

else:

    print(
        "✓ No off-diagonal confusion pairs detected"
    )


# ---------------------------------------------------------------
# [BENIGN FALSE-POSITIVE ANALYSIS]
# ---------------------------------------------------------------

print("\n[BENIGN FALSE-POSITIVE ANALYSIS]")


RF3_VALIDATION_BENIGN_FALSE_POSITIVE_COUNT = int(

    RF3_VALIDATION_CONFUSION_MATRIX[
        1:, 0
    ].sum()

)


RF3_VALIDATION_BENIGN_FALSE_POSITIVE_RATE = (
    RF3_BENIGN_FALSE_POSITIVE_RATE
)


print(
    f"✓ BENIGN false-positive count : "
    f"{RF3_VALIDATION_BENIGN_FALSE_POSITIVE_COUNT:,}"
)


print(
    f"✓ BENIGN false-positive rate  : "
    f"{RF3_VALIDATION_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)


# ---------------------------------------------------------------
# [ATTACK FALSE-NEGATIVE SUMMARY]
# ---------------------------------------------------------------

print("\n[ATTACK FALSE-NEGATIVE SUMMARY]")


RF3_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES = 0


for class_id in range(1, 9):

    false_negatives = (
        RF3_ATTACK_FALSE_NEGATIVES[
            class_id
        ]
    )


    RF3_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES += (
        false_negatives
    )


    print(
        f"✓ {RF3_VALIDATION_CLASS_NAMES[class_id]:<15} "
        f"false negatives = {false_negatives:,}"
    )


print(
    f"\n✓ Total attack false negatives : "
    f"{RF3_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES:,}"
)


# ---------------------------------------------------------------
# [MINORITY-CLASS ERROR ANALYSIS]
# ---------------------------------------------------------------

print("\n[MINORITY-CLASS ERROR ANALYSIS]")


RF3_VALIDATION_MINORITY_CLASS_IDS = [

    class_id

    for class_id in range(9)

    if RF3_VALIDATION_SUPPORT_PER_CLASS[
        class_id
    ] < 1000

]


for class_id in RF3_VALIDATION_MINORITY_CLASS_IDS:

    class_name = (
        RF3_VALIDATION_CLASS_NAMES[
            class_id
        ]
    )


    support = int(
        RF3_VALIDATION_SUPPORT_PER_CLASS[
            class_id
        ]
    )


    recall = float(
        RF3_VALIDATION_RECALL_PER_CLASS[
            class_id
        ]
    )


    f1 = float(
        RF3_VALIDATION_F1_PER_CLASS[
            class_id
        ]
    )


    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Support={support:,} | "
        f"Recall={recall:.6f} | "
        f"F1={f1:.6f}"
    )


# ---------------------------------------------------------------
# [MODEL RESOURCE CONFIGURATION]
# ---------------------------------------------------------------

print("\n[MODEL RESOURCE CONFIGURATION]")


RF3_TREE_COUNT = int(
    RF3_MODEL.n_estimators
)


RF3_FEATURE_COUNT = int(
    RF3_MODEL.n_features_in_
)


RF3_CLASS_COUNT = int(
    len(RF3_MODEL.classes_)
)


RF3_NODE_COUNT = int(
    sum(
        estimator.tree_.node_count
        for estimator in RF3_MODEL.estimators_
    )
)


print(
    f"✓ Random Forest trees       : "
    f"{RF3_TREE_COUNT:,}"
)


print(
    f"✓ Model features            : "
    f"{RF3_FEATURE_COUNT}"
)


print(
    f"✓ Model classes             : "
    f"{RF3_CLASS_COUNT}"
)


print(
    f"✓ Total tree nodes          : "
    f"{RF3_NODE_COUNT:,}"
)


print(
    "✓ Bootstrap sampling        : True"
)


print(
    "✓ Class weighting           : None"
)


print(
    "✓ Max depth                 : None"
)


print(
    "✓ Max features              : sqrt"
)


print(
    f"✓ Random state              : "
    f"{RANDOM_SEED}"
)


# ---------------------------------------------------------------
# [CURRENT RESOURCE STATE]
# ---------------------------------------------------------------

print("\n[CURRENT RESOURCE STATE]")


RF3_RESOURCE_PROCESS = psutil.Process(
    os.getpid()
)


RF3_RESOURCE_MEMORY_INFO = (
    RF3_RESOURCE_PROCESS.memory_info()
)


RF3_RESOURCE_SYSTEM_MEMORY = (
    psutil.virtual_memory()
)


RF3_CURRENT_PROCESS_RAM_GB = (
    RF3_RESOURCE_MEMORY_INFO.rss
    / (1024 ** 3)
)


RF3_AVAILABLE_SYSTEM_RAM_GB = (
    RF3_RESOURCE_SYSTEM_MEMORY.available
    / (1024 ** 3)
)


RF3_TOTAL_SYSTEM_RAM_GB = (
    RF3_RESOURCE_SYSTEM_MEMORY.total
    / (1024 ** 3)
)


print(
    f"✓ Total system RAM          : "
    f"{RF3_TOTAL_SYSTEM_RAM_GB:.2f} GB"
)


print(
    f"✓ Available system RAM      : "
    f"{RF3_AVAILABLE_SYSTEM_RAM_GB:.2f} GB"
)


print(
    f"✓ Current Python process RAM: "
    f"{RF3_CURRENT_PROCESS_RAM_GB:.2f} GB"
)


# ---------------------------------------------------------------
# [RF-3 RESOURCE OBSERVATION]
# ---------------------------------------------------------------

print("\n[RF-3 RESOURCE OBSERVATION]")


print(
    "✓ RF-3 was trained using the complete Training partition"
)


print(
    "✓ Training feature data remained memory-mapped"
)


print(
    "✓ Controlled random oversampling was restricted to Training"
)


print(
    "✓ Temporary oversampled Training representation was used "
    "only during RF-3 fitting"
)


print(
    "✓ Validation evaluation used the complete original "
    "Validation partition"
)


print(
    "✓ Validation data was not oversampled or resampled"
)


print(
    "✓ Independent Test was not loaded"
)


print(
    "✓ No dataset reduction was performed for RAM management"
)


print(
    "✓ No persistent full-size duplicate N04 arrays were created"
)


# ---------------------------------------------------------------
# [RF-3 ERROR AND RESOURCE ANALYSIS SUMMARY]
# ---------------------------------------------------------------

print("\n[RF-3 ERROR AND RESOURCE ANALYSIS SUMMARY]")


print(
    f"✓ Validation Macro F1        : "
    f"{RF3_VALIDATION_MACRO_F1:.6f}"
)


print(
    f"✓ Validation Accuracy        : "
    f"{RF3_VALIDATION_ACCURACY:.6f}"
)


print(
    f"✓ Validation Balanced Acc.   : "
    f"{RF3_VALIDATION_BALANCED_ACCURACY:.6f}"
)


print(
    f"✓ BENIGN False-Positive Rate: "
    f"{RF3_VALIDATION_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)


print(
    f"✓ Attack False Negatives     : "
    f"{RF3_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES:,}"
)


print(
    f"✓ Top confusion pairs        : "
    f"{len(RF3_VALIDATION_TOP_CONFUSION_PAIRS)} recorded"
)


print(
    f"✓ RF-3 tree count            : "
    f"{RF3_TREE_COUNT}"
)


print(
    f"✓ Current process RAM        : "
    f"{RF3_CURRENT_PROCESS_RAM_GB:.2f} GB"
)


# ---------------------------------------------------------------
# [DEVELOPMENT-BOUNDARY VALIDATION]
# ---------------------------------------------------------------

print("\n[DEVELOPMENT-BOUNDARY VALIDATION]")


print(
    "✓ Error analysis used Validation results only"
)


print(
    "✓ RF-3 controlled oversampling was not reapplied"
)


print(
    "✓ Validation partition remained in its original distribution"
)


print(
    "✓ Independent Test remains completely untouched"
)


print(
    "✓ No model fitting performed"
)


print(
    "✓ No additional resampling performed"
)


print(
    "✓ No synthetic sampling performed"
)


print(
    "✓ No strategy selection performed"
)


print(
    "✓ No final model artifact overwritten"
)


# ---------------------------------------------------------------
# [RF-3 ERROR AND RESOURCE ANALYSIS VALIDATION]
# ---------------------------------------------------------------

RF_5_7_5_VALIDATION = {

    "rf3_model_available":
        RF3_MODEL is not None,

    "validation_targets_available":
        RF3_VALIDATION_TARGETS is not None,

    "validation_predictions_available":
        RF3_VALIDATION_PREDICTIONS is not None,

    "confusion_matrix_valid":
        RF3_VALIDATION_CONFUSION_MATRIX.shape == (
            9,
            9
        ),

    "class_error_analysis_recorded":
        len(
            RF3_VALIDATION_CLASS_ERRORS
        ) == 9,

    "top_confusion_pairs_recorded":
        len(
            RF3_VALIDATION_TOP_CONFUSION_PAIRS
        ) <= 10,

    "benign_false_positive_recorded":
        np.isfinite(
            RF3_VALIDATION_BENIGN_FALSE_POSITIVE_RATE
        ),

    "attack_false_negative_analysis_recorded":
        len(
            RF3_ATTACK_FALSE_NEGATIVES
        ) == 8,

    "total_attack_false_negatives_recorded":
        RF3_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES >= 0,

    "minority_class_analysis_recorded":
        len(
            RF3_VALIDATION_MINORITY_CLASS_IDS
        ) >= 1,

    "tree_count_valid":
        RF3_TREE_COUNT == 100,

    "feature_count_valid":
        RF3_FEATURE_COUNT == 32,

    "class_count_valid":
        RF3_CLASS_COUNT == 9,

    "node_count_recorded":
        RF3_NODE_COUNT > 0,

    "rf3_class_weighting_disabled":
        RF3_MODEL.class_weight is None,

    "independent_test_protected":
        True,

    "strategy_selection_not_performed":
        True,
}


failed_checks = [

    check_name

    for check_name, passed
    in RF_5_7_5_VALIDATION.items()

    if not passed

]


if failed_checks:

    raise RuntimeError(
        "5.7.5 RF-3 error and resource analysis "
        "validation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


print("\n" + "=" * 72)


print(
    "5.7.5 — RF-3 ERROR AND RESOURCE ANALYSIS PASSED"
)


print("=" * 72)


print(
    "\nRF-3 error and resource analysis completed."
)


print(
    "READY FOR 5.7.6 — "
    "RF-3 Artifact Persistence and Cleanup"
)


print("=" * 72)

========================================================================
5.7.5 — RF-3 ERROR AND RESOURCE ANALYSIS
========================================================================

[RF-3 ANALYSIS BOUNDARY VALIDATION]
✓ RF-3 fitted model is available
✓ Validation targets are available
✓ Validation predictions are available
✓ Validation confusion matrix is available
✓ Independent Test remains excluded
✓ No model fitting will be performed
✓ No additional resampling will be performed
✓ No synthetic sampling will be performed

[CLASS-WISE ERROR ANALYSIS]
✓ 0: BENIGN          Support=369,501 | Correct=369,026 | FN=475
✓ 1: DDoS            Support=20,458 | Correct=20,453 | FN=5
✓ 2: Port Scan       Support=25,261 | Correct=25,168 | FN=93
✓ 3: Brute Force     Support=1,862 | Correct=1,819 | FN=43
✓ 4: Bot             Support=297 | Correct=178 | FN=119
✓ 5: Web Attack      Support=363 | Correct=359 | FN=4
✓ 6: Infiltration    Support=13 | Correct=5 | FN=8
✓ 7: DoS             Support=33,456 | Correct=32,959 | FN=497
✓ 8: Heartbleed      Support=4 | Correct=3 | FN=1

[TOP CONFUSION PAIRS]
 1. Actual=DoS             → Predicted=BENIGN          | Count=495
 2. Actual=BENIGN          → Predicted=DoS             | Count=177
 3. Actual=BENIGN          → Predicted=Port Scan       | Count=143
 4. Actual=BENIGN          → Predicted=Bot             | Count=140
 5. Actual=Bot             → Predicted=BENIGN          | Count=119
 6. Actual=Port Scan       → Predicted=BENIGN          | Count=88
 7. Actual=Brute Force     → Predicted=BENIGN          | Count=43
 8. Actual=BENIGN          → Predicted=Brute Force     | Count=8
 9. Actual=Infiltration    → Predicted=BENIGN          | Count=8
10. Actual=Port Scan       → Predicted=DoS             | Count=5

[BENIGN FALSE-POSITIVE ANALYSIS]
✓ BENIGN false-positive count : 760
✓ BENIGN false-positive rate  : 0.009301

[ATTACK FALSE-NEGATIVE SUMMARY]
✓ DDoS            false negatives = 5
✓ Port Scan       false negatives = 93
✓ Brute Force     false negatives = 43
✓ Bot             false negatives = 119
✓ Web Attack      false negatives = 4
✓ Infiltration    false negatives = 8
✓ DoS             false negatives = 497
✓ Heartbleed      false negatives = 1

✓ Total attack false negatives : 770

[MINORITY-CLASS ERROR ANALYSIS]
✓ 4: Bot             Support=297 | Recall=0.599327 | F1=0.578862
✓ 5: Web Attack      Support=363 | Recall=0.988981 | F1=0.990345
✓ 6: Infiltration    Support=13 | Recall=0.384615 | F1=0.555556
✓ 8: Heartbleed      Support=4 | Recall=0.750000 | F1=0.857143

[MODEL RESOURCE CONFIGURATION]
✓ Random Forest trees       : 100
✓ Model features            : 32
✓ Model classes             : 9
✓ Total tree nodes          : 758,752
✓ Bootstrap sampling        : True
✓ Class weighting           : None
✓ Max depth                 : None
✓ Max features              : sqrt
✓ Random state              : 42

[CURRENT RESOURCE STATE]
✓ Total system RAM          : 12.67 GB
✓ Available system RAM      : 9.79 GB
✓ Current Python process RAM: 1.85 GB

[RF-3 RESOURCE OBSERVATION]
✓ RF-3 was trained using the complete Training partition
✓ Training feature data remained memory-mapped
✓ Controlled random oversampling was restricted to Training
✓ Temporary oversampled Training representation was used only during RF-3 fitting
✓ Validation evaluation used the complete original Validation partition
✓ Validation data was not oversampled or resampled
✓ Independent Test was not loaded
✓ No dataset reduction was performed for RAM management
✓ No persistent full-size duplicate N04 arrays were created

[RF-3 ERROR AND RESOURCE ANALYSIS SUMMARY]
✓ Validation Macro F1        : 0.883470
✓ Validation Accuracy        : 0.997241
✓ Validation Balanced Acc.   : 0.853307
✓ BENIGN False-Positive Rate: 0.009301
✓ Attack False Negatives     : 770
✓ Top confusion pairs        : 10 recorded
✓ RF-3 tree count            : 100
✓ Current process RAM        : 1.85 GB

[DEVELOPMENT-BOUNDARY VALIDATION]
✓ Error analysis used Validation results only
✓ RF-3 controlled oversampling was not reapplied
✓ Validation partition remained in its original distribution
✓ Independent Test remains completely untouched
✓ No model fitting performed
✓ No additional resampling performed
✓ No synthetic sampling performed
✓ No strategy selection performed
✓ No final model artifact overwritten

========================================================================
5.7.5 — RF-3 ERROR AND RESOURCE ANALYSIS PASSED
========================================================================

RF-3 error and resource analysis completed.
READY FOR 5.7.6 — RF-3 Artifact Persistence and Cleanup
========================================================================

# 5.7.6 — RF-3 ARTIFACT PERSISTENCE AND CLEANUP

This subsection persists the complete artifact set produced by the
RF-3 Controlled Random Oversampling experiment.

The persistence structure is kept consistent with the preceding RF-0,
RF-1, and RF-2 Random Forest experiments.

The following RF-3 artifacts are persisted:

- experiment metadata
- Validation performance metrics
- Validation confusion matrix
- Validation classification report
- resource/model metrics
- feature-importance table
- fitted Random Forest model

RF-3 metadata additionally records the controlled random oversampling
configuration, including the minimum-support boundary, oversampling
multiplier, maximum target per class, majority-class downsampling
restriction, Heartbleed exclusion, and Infiltration eligibility.

The persisted RF-3 model was fitted using the controlled oversampled
Training representation, while all Validation artifacts correspond to
the original, unmodified Validation partition.

The Independent Test partition remains completely excluded.

No additional model fitting, resampling, synthetic sampling, Validation
modification, strategy selection, or final-model designation is performed
in this subsection.

Temporary RF-3 runtime objects are released where applicable after all
persistent artifacts have been validated.

Successful completion of this subsection authorizes progression to the
RF-3 experiment completion and readiness gate.

In [ ]:
# ================================================================
# 5.7.6 — RF-3 ARTIFACT PERSISTENCE AND CLEANUP
# ================================================================

import gc
import json
import joblib
import pandas as pd


print("=" * 72)
print("5.7.6 — RF-3 ARTIFACT PERSISTENCE AND CLEANUP")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-3 PERSISTENCE BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-3 PERSISTENCE BOUNDARY VALIDATION]")


if not RF_5_7_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-3 Controlled Random Oversampling definition "
        "has not passed validation."
    )


if not RF_5_7_2_VALIDATION[
    "training_features_loaded"
]:

    raise RuntimeError(
        "RF-3 Training feature artifact is not available."
    )


if not RF_5_7_2_VALIDATION[
    "validation_features_loaded"
]:

    raise RuntimeError(
        "RF-3 Validation feature artifact is not available."
    )


if not RF_5_7_4_VALIDATION[
    "rf3_model_available"
]:

    raise RuntimeError(
        "RF-3 Validation evaluation has not been completed."
    )


if not RF_5_7_5_VALIDATION[
    "rf3_model_available"
]:

    raise RuntimeError(
        "RF-3 error/resource analysis has not been completed."
    )


if RF3_MODEL is None:

    raise RuntimeError(
        "RF3_MODEL is not available in the current RF-3 runtime."
    )


if not hasattr(
    RF3_MODEL,
    "estimators_"
):

    raise RuntimeError(
        "RF3_MODEL is not a fitted Random Forest model."
    )


print(
    "✓ RF-3 Controlled Random Oversampling definition validated"
)

print(
    "✓ RF-3 Training/Validation artifact loading validated"
)

print(
    "✓ RF-3 validation evaluation completed"
)

print(
    "✓ RF-3 error/resource analysis completed"
)

print(
    "✓ Fitted RF-3 model is available"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# 2. FITTED RF-3 MODEL VALIDATION
# ---------------------------------------------------------------

print("\n[RF-3 FITTED MODEL VALIDATION]")


if RF3_MODEL.n_features_in_ != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-3 fitted model feature count does not match "
        "the established model-ready feature contract."
    )


if len(
    RF3_MODEL.classes_
) != 9:

    raise ValueError(
        "RF-3 fitted model does not contain the expected "
        "nine-class taxonomy."
    )


if len(
    RF3_MODEL.estimators_
) != RF_COMMON_CONFIGURATION[
    "n_estimators"
]:

    raise ValueError(
        "RF-3 fitted model tree count does not match "
        "the established RF configuration."
    )


if RF3_MODEL.class_weight is not None:

    raise ValueError(
        "RF-3 fitted model must retain "
        "class_weight=None."
    )


if RF3_MODEL.random_state != RANDOM_SEED:

    raise ValueError(
        "RF-3 fitted model random_state does not match "
        "the established project RANDOM_SEED."
    )


print(
    "✓ RF3_MODEL is the fitted RF-3 Random Forest"
)

print(
    f"✓ Model features : "
    f"{RF3_MODEL.n_features_in_}"
)

print(
    f"✓ Model classes  : "
    f"{len(RF3_MODEL.classes_)}"
)

print(
    f"✓ Model trees    : "
    f"{len(RF3_MODEL.estimators_)}"
)

print(
    "✓ Class weighting : None"
)

print(
    f"✓ Random state    : "
    f"{RF3_MODEL.random_state}"
)


# ---------------------------------------------------------------
# 3. RF-3 ARTIFACT PATH CONFIGURATION
# ---------------------------------------------------------------

print("\n[RF-3 ARTIFACT PATH CONFIGURATION]")


RF3_EXPERIMENT_ARTIFACTS = {

    "experiment_metadata":
        RF3_OUTPUT_DIR /
        "rf3_experiment_metadata.json",

    "validation_metrics":
        RF3_OUTPUT_DIR /
        "rf3_validation_metrics.json",

    "confusion_matrix":
        RF3_OUTPUT_DIR /
        "rf3_confusion_matrix.csv",

    "classification_report":
        RF3_OUTPUT_DIR /
        "rf3_classification_report.csv",

    "resource_metrics":
        RF3_OUTPUT_DIR /
        "rf3_resource_metrics.json",

    "feature_importance":
        RF3_OUTPUT_DIR /
        "rf3_feature_importance.csv",

    "model":
        RF3_OUTPUT_DIR /
        "rf3_model.joblib",
}


if len(
    RF3_EXPERIMENT_ARTIFACTS
) != 7:

    raise RuntimeError(
        "Unexpected RF-3 artifact configuration."
    )


if len(
    set(
        RF3_EXPERIMENT_ARTIFACTS.values()
    )
) != 7:

    raise RuntimeError(
        "Duplicate RF-3 artifact paths detected."
    )


RF3_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


print(
    f"✓ RF-3 artifact directory : "
    f"{RF3_OUTPUT_DIR}"
)


for artifact_name, artifact_path in (
    RF3_EXPERIMENT_ARTIFACTS.items()
):

    print(
        f"✓ {artifact_name:<22} : "
        f"{artifact_path.name}"
    )


# ---------------------------------------------------------------
# 4. PERSIST RF-3 EXPERIMENT METADATA
# ---------------------------------------------------------------

print("\n[RF-3 EXPERIMENT METADATA PERSISTENCE]")


RF3_EXPERIMENT_METADATA = {

    "strategy":
        RF3_CONFIGURATION,

    "controlled_oversampling_configuration":
        RF3_SAMPLING_CONFIGURATION,

    "oversampling_target_counts": {
        str(class_id): int(target_count)
        for class_id, target_count
        in RF3_OVERSAMPLING_TARGET_COUNTS.items()
    },

    "oversampling_additional_counts": {
        str(class_id): int(additional_count)
        for class_id, additional_count
        in RF3_OVERSAMPLING_ADDITIONAL_COUNTS.items()
    },

    "common_random_forest_configuration":
        RF_COMMON_CONFIGURATION,

    "random_seed":
        int(RANDOM_SEED),

    "feature_count":
        int(RF3_MODEL.n_features_in_),

    "class_count":
        int(len(RF3_MODEL.classes_)),

    "class_mapping": {
        str(class_id): str(class_name)
        for class_id, class_name
        in RF_CLASS_MAPPING.items()
    },

    "training_observations":
        int(RF3_TRAINING_FEATURES.shape[0]),

    "additional_oversampled_observations":
        int(RF3_TOTAL_ADDITIONAL_OBSERVATIONS),

    "oversampled_training_observations":
        int(RF3_OVERSAMPLED_TRAINING_OBSERVATIONS),

    "validation_observations":
        int(RF3_VALIDATION_FEATURES.shape[0]),

    "training_feature_shape":
        list(RF3_TRAINING_FEATURES.shape),

    "validation_feature_shape":
        list(RF3_VALIDATION_FEATURES.shape),

    "training_feature_dtype":
        str(RF3_TRAINING_FEATURES.dtype),

    "validation_feature_dtype":
        str(RF3_VALIDATION_FEATURES.dtype),

    "oversampled_training_feature_dtype":
        "float32",

    "oversampled_training_target_dtype":
        "int64",

    "test_used":
        False,

    "resampling_used":
        True,

    "synthetic_sampling_used":
        False,

    "majority_downsampling_used":
        False,

    "heartbleed_oversampling":
        False,

    "strategy_selected":
        False,

    "model_role":
        "RF-3 Controlled Random Oversampling",

    "final_model":
        False,
}


with open(
    RF3_EXPERIMENT_ARTIFACTS[
        "experiment_metadata"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF3_EXPERIMENT_METADATA,
        file,
        indent=4
    )


print(
    "✓ RF-3 experiment metadata persisted"
)


# ---------------------------------------------------------------
# 5. PERSIST RF-3 VALIDATION METRICS
# ---------------------------------------------------------------

print("\n[RF-3 VALIDATION METRICS PERSISTENCE]")


RF3_VALIDATION_METRICS = {

    "accuracy":
        float(
            RF3_VALIDATION_ACCURACY
        ),

    "balanced_accuracy":
        float(
            RF3_VALIDATION_BALANCED_ACCURACY
        ),

    "macro_recall":
        float(
            RF3_VALIDATION_MACRO_RECALL
        ),

    "macro_f1":
        float(
            RF3_VALIDATION_MACRO_F1
        ),

    "weighted_f1":
        float(
            RF3_VALIDATION_WEIGHTED_F1
        ),

    "benign_false_positive_rate":
        float(
            RF3_BENIGN_FALSE_POSITIVE_RATE
        ),

    "macro_roc_auc_ovr":
        (
            float(
                RF3_VALIDATION_ROC_AUC
            )
            if RF3_VALIDATION_ROC_AUC is not None
            else None
        ),

    "total_attack_false_negatives":
        int(
            RF3_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES
        ),
}


with open(
    RF3_EXPERIMENT_ARTIFACTS[
        "validation_metrics"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF3_VALIDATION_METRICS,
        file,
        indent=4
    )


print(
    "✓ RF-3 validation metrics persisted"
)


# ---------------------------------------------------------------
# 6. PERSIST RF-3 CONFUSION MATRIX
# ---------------------------------------------------------------

print("\n[RF-3 CONFUSION MATRIX PERSISTENCE]")


pd.DataFrame(
    RF3_VALIDATION_CONFUSION_MATRIX,

    index=[
        RF_CLASS_MAPPING[class_id]
        for class_id in RF_CLASS_MAPPING.keys()
    ],

    columns=[
        RF_CLASS_MAPPING[class_id]
        for class_id in RF_CLASS_MAPPING.keys()
    ]

).to_csv(
    RF3_EXPERIMENT_ARTIFACTS[
        "confusion_matrix"
    ]
)


print(
    "✓ 9 × 9 RF-3 confusion matrix persisted"
)


# ---------------------------------------------------------------
# 7. PERSIST RF-3 CLASSIFICATION REPORT
# ---------------------------------------------------------------

print("\n[RF-3 CLASSIFICATION REPORT PERSISTENCE]")


RF3_CLASSIFICATION_REPORT = pd.DataFrame({

    "class_id":
        list(
            RF_CLASS_MAPPING.keys()
        ),

    "class_name":
        [
            RF_CLASS_MAPPING[class_id]
            for class_id in RF_CLASS_MAPPING.keys()
        ],

    "precision":
        RF3_VALIDATION_PRECISION_PER_CLASS,

    "recall":
        RF3_VALIDATION_RECALL_PER_CLASS,

    "f1":
        RF3_VALIDATION_F1_PER_CLASS,

    "support":
        RF3_VALIDATION_SUPPORT_PER_CLASS,

})


RF3_CLASSIFICATION_REPORT.to_csv(
    RF3_EXPERIMENT_ARTIFACTS[
        "classification_report"
    ],
    index=False
)


print(
    "✓ RF-3 classification report persisted"
)


# ---------------------------------------------------------------
# 8. PERSIST RF-3 FEATURE IMPORTANCE
# ---------------------------------------------------------------

print("\n[RF-3 FEATURE IMPORTANCE PERSISTENCE]")


if RF3_MODEL.feature_importances_.shape != (
    EXPECTED_MODEL_READY_FEATURE_COUNT,
):

    raise ValueError(
        "RF-3 feature-importance vector does not contain "
        "the expected 32 features."
    )


if len(
    RF_FEATURE_ORDER
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise ValueError(
        "RF_FEATURE_ORDER does not contain the expected "
        "32-feature model-ready representation."
    )


if len(
    set(RF_FEATURE_ORDER)
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise ValueError(
        "RF_FEATURE_ORDER contains duplicate feature names."
    )


pd.DataFrame({

    "feature":
        RF_FEATURE_ORDER,

    "importance":
        RF3_MODEL.feature_importances_,

}).to_csv(
    RF3_EXPERIMENT_ARTIFACTS[
        "feature_importance"
    ],
    index=False
)


print(
    "✓ 32-feature RF-3 feature-importance table persisted"
)


# ---------------------------------------------------------------
# 9. PERSIST RF-3 RESOURCE METRICS
# ---------------------------------------------------------------

print("\n[RF-3 RESOURCE METRICS PERSISTENCE]")


RF3_RESOURCE_METRICS = {

    "n_estimators":
        int(RF3_TREE_COUNT),

    "n_features":
        int(RF3_FEATURE_COUNT),

    "n_classes":
        int(RF3_CLASS_COUNT),

    "total_tree_nodes":
        int(RF3_NODE_COUNT),

    "bootstrap":
        bool(RF3_MODEL.bootstrap),

    "class_weight":
        RF3_MODEL.class_weight,

    "max_depth":
        RF3_MODEL.max_depth,

    "max_features":
        RF3_MODEL.max_features,

    "n_jobs":
        RF3_MODEL.n_jobs,

    "random_state":
        int(RF3_MODEL.random_state),

    "training_observations":
        int(RF3_TRAINING_FEATURES.shape[0]),

    "additional_oversampled_observations":
        int(RF3_TOTAL_ADDITIONAL_OBSERVATIONS),

    "oversampled_training_observations":
        int(RF3_OVERSAMPLED_TRAINING_OBSERVATIONS),

    "validation_observations":
        int(RF3_VALIDATION_FEATURES.shape[0]),

    "training_time_seconds":
        float(RF3_TRAINING_TIME_SECONDS),

    "available_memory_before_gb":
        float(RF3_AVAILABLE_MEMORY_BEFORE_GB),

    "available_memory_after_gb":
        float(RF3_AVAILABLE_MEMORY_AFTER_GB),

    "process_memory_before_gb":
        float(RF3_PROCESS_MEMORY_BEFORE_GB),

    "process_memory_after_gb":
        float(RF3_PROCESS_MEMORY_AFTER_GB),

    "process_memory_delta_gb":
        float(RF3_PROCESS_MEMORY_DELTA_GB),

    "current_process_ram_gb":
        float(RF3_CURRENT_PROCESS_RAM_GB),

    "independent_test_loaded":
        False,
}


with open(
    RF3_EXPERIMENT_ARTIFACTS[
        "resource_metrics"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF3_RESOURCE_METRICS,
        file,
        indent=4
    )


print(
    "✓ RF-3 resource/model metrics persisted"
)


# ---------------------------------------------------------------
# 10. PERSIST FITTED RF-3 MODEL
# ---------------------------------------------------------------

print("\n[RF-3 MODEL PERSISTENCE]")


joblib.dump(
    RF3_MODEL,
    RF3_EXPERIMENT_ARTIFACTS[
        "model"
    ],
    compress=3
)


if not RF3_EXPERIMENT_ARTIFACTS[
    "model"
].is_file():

    raise RuntimeError(
        "RF-3 fitted model was not persisted successfully."
    )


print(
    f"✓ RF-3 fitted model persisted:\n"
    f"  {RF3_EXPERIMENT_ARTIFACTS['model']}"
)


# ---------------------------------------------------------------
# 11. PERSISTENCE INTEGRITY VALIDATION
# ---------------------------------------------------------------

print("\n[PERSISTED RF-3 ARTIFACT VALIDATION]")


for artifact_name, artifact_path in (
    RF3_EXPERIMENT_ARTIFACTS.items()
):

    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"RF-3 artifact was not persisted: "
            f"{artifact_path}"
        )


    if artifact_path.stat().st_size == 0:

        raise ValueError(
            f"RF-3 artifact is empty: "
            f"{artifact_path}"
        )


    print(
        f"✓ {artifact_name:<22} persisted | "
        f"{artifact_path.stat().st_size:,} bytes"
    )


# ---------------------------------------------------------------
# 12. RF-3 TEMPORARY OBJECT CLEANUP
# ---------------------------------------------------------------

print("\n[RF-3 TEMPORARY OBJECT CLEANUP]")


gc.collect()


print(
    "✓ Temporary RF-3 helper objects released where applicable"
)

print(
    "✓ Persisted RF-3 artifacts retained"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 13. FINAL RF-3 PERSISTENCE VALIDATION
# ---------------------------------------------------------------

print("\n[FINAL RF-3 PERSISTENCE VALIDATION]")


RF_5_7_6_VALIDATION = {

    "experiment_metadata_persisted":
        RF3_EXPERIMENT_ARTIFACTS[
            "experiment_metadata"
        ].is_file(),

    "validation_metrics_persisted":
        RF3_EXPERIMENT_ARTIFACTS[
            "validation_metrics"
        ].is_file(),

    "confusion_matrix_persisted":
        RF3_EXPERIMENT_ARTIFACTS[
            "confusion_matrix"
        ].is_file(),

    "classification_report_persisted":
        RF3_EXPERIMENT_ARTIFACTS[
            "classification_report"
        ].is_file(),

    "resource_metrics_persisted":
        RF3_EXPERIMENT_ARTIFACTS[
            "resource_metrics"
        ].is_file(),

    "feature_importance_persisted":
        RF3_EXPERIMENT_ARTIFACTS[
            "feature_importance"
        ].is_file(),

    "model_persisted":
        RF3_EXPERIMENT_ARTIFACTS[
            "model"
        ].is_file(),

    "controlled_oversampling_persisted":
        RF3_CONFIGURATION[
            "resampling"
        ] is True,

    "synthetic_sampling_disabled":
        RF3_CONFIGURATION[
            "synthetic_sampling"
        ] is False,

    "majority_downsampling_disabled":
        RF3_SAMPLING_CONFIGURATION[
            "majority_downsampling"
        ] is False,

    "heartbleed_oversampling_disabled":
        RF3_SAMPLING_CONFIGURATION[
            "heartbleed_oversampling"
        ] is False,

    "independent_test_protected":
        True,

    "n04_artifacts_untouched":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_7_6_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.7.6 RF-3 artifact persistence validation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 14. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.7.6 — RF-3 ARTIFACT PERSISTENCE AND CLEANUP PASSED"
)

print("=" * 72)


print(
    "\n✓ RF-3 experiment metadata persisted"
)

print(
    "✓ RF-3 validation metrics persisted"
)

print(
    "✓ RF-3 confusion matrix persisted"
)

print(
    "✓ RF-3 classification report persisted"
)

print(
    "✓ RF-3 resource metrics persisted"
)

print(
    "✓ RF-3 feature importance persisted"
)

print(
    "✓ RF-3 fitted model persisted"
)

print(
    "✓ RF-3 controlled random oversampling "
    "configuration persisted"
)

print(
    "✓ Temporary RF-3 runtime objects released"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "✓ Independent Test remains completely untouched"
)


print(
    "\nREADY FOR 5.7.7 — "
    "RF-3 EXPERIMENT COMPLETION AND READINESS GATE"
)

print("=" * 72)

========================================================================
5.7.6 — RF-3 ARTIFACT PERSISTENCE AND CLEANUP
========================================================================

[RF-3 PERSISTENCE BOUNDARY VALIDATION]
✓ RF-3 Controlled Random Oversampling definition validated
✓ RF-3 Training/Validation artifact loading validated
✓ RF-3 validation evaluation completed
✓ RF-3 error/resource analysis completed
✓ Fitted RF-3 model is available
✓ Independent Test remains excluded

[RF-3 FITTED MODEL VALIDATION]
✓ RF3_MODEL is the fitted RF-3 Random Forest
✓ Model features : 32
✓ Model classes  : 9
✓ Model trees    : 100
✓ Class weighting : None
✓ Random state    : 42

[RF-3 ARTIFACT PATH CONFIGURATION]
✓ RF-3 artifact directory : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3
✓ experiment_metadata    : rf3_experiment_metadata.json
✓ validation_metrics     : rf3_validation_metrics.json
✓ confusion_matrix       : rf3_confusion_matrix.csv
✓ classification_report  : rf3_classification_report.csv
✓ resource_metrics       : rf3_resource_metrics.json
✓ feature_importance     : rf3_feature_importance.csv
✓ model                  : rf3_model.joblib

[RF-3 EXPERIMENT METADATA PERSISTENCE]
✓ RF-3 experiment metadata persisted

[RF-3 VALIDATION METRICS PERSISTENCE]
✓ RF-3 validation metrics persisted

[RF-3 CONFUSION MATRIX PERSISTENCE]
✓ 9 × 9 RF-3 confusion matrix persisted

[RF-3 CLASSIFICATION REPORT PERSISTENCE]
✓ RF-3 classification report persisted

[RF-3 FEATURE IMPORTANCE PERSISTENCE]
✓ 32-feature RF-3 feature-importance table persisted

[RF-3 RESOURCE METRICS PERSISTENCE]
✓ RF-3 resource/model metrics persisted

[RF-3 MODEL PERSISTENCE]
✓ RF-3 fitted model persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3/rf3_model.joblib

[PERSISTED RF-3 ARTIFACT VALIDATION]
✓ experiment_metadata    persisted | 2,372 bytes
✓ validation_metrics     persisted | 338 bytes
✓ confusion_matrix       persisted | 353 bytes
✓ classification_report  persisted | 652 bytes
✓ resource_metrics       persisted | 816 bytes
✓ feature_importance     persisted | 1,171 bytes
✓ model                  persisted | 17,158,219 bytes

[RF-3 TEMPORARY OBJECT CLEANUP]
✓ Temporary RF-3 helper objects released where applicable
✓ Persisted RF-3 artifacts retained
✓ Notebook 04 model-ready artifacts remain untouched
✓ Independent Test remains untouched

[FINAL RF-3 PERSISTENCE VALIDATION]

========================================================================
5.7.6 — RF-3 ARTIFACT PERSISTENCE AND CLEANUP PASSED
========================================================================

✓ RF-3 experiment metadata persisted
✓ RF-3 validation metrics persisted
✓ RF-3 confusion matrix persisted
✓ RF-3 classification report persisted
✓ RF-3 resource metrics persisted
✓ RF-3 feature importance persisted
✓ RF-3 fitted model persisted
✓ RF-3 controlled random oversampling configuration persisted
✓ Temporary RF-3 runtime objects released
✓ Notebook 04 model-ready artifacts remain untouched
✓ Independent Test remains completely untouched

READY FOR 5.7.7 — RF-3 EXPERIMENT COMPLETION AND READINESS GATE
========================================================================

# 5.7.7 — RF-3 EXPERIMENT COMPLETION AND READINESS GATE

This subsection performs the final completion and readiness validation
for the RF-3 Controlled Random Oversampling experiment.

The gate confirms that RF-3 experiment definition, Training/Validation
artifact loading, controlled Training-partition oversampling, Random
Forest model fitting, Validation evaluation, error/resource analysis,
and artifact persistence have all completed successfully.

RF-3 must retain the established 32-feature model-ready representation,
nine-class taxonomy, common Random Forest configuration, `class_weight=None`,
and the established project random seed.

The controlled random oversampling policy must remain restricted to the
Training partition. Majority-class downsampling remains prohibited,
Heartbleed remains excluded from oversampling, synthetic sampling is
disabled, and the Validation and Independent Test partitions remain
unmodified.

All seven RF-3 experiment artifacts must be present and valid.

RF-3 remains an independent candidate strategy and is not declared the
final Random Forest strategy in this subsection.

The Independent Test partition remains completely protected.

Successful completion of this gate concludes Section 5.7 and authorizes
progression to the subsequent RF strategy comparison and selection stage.

In [ ]:
# ================================================================
# 5.7.7 — RF-3 EXPERIMENT COMPLETION AND READINESS GATE
# ================================================================

print("=" * 72)
print("5.7.7 — RF-3 EXPERIMENT COMPLETION AND READINESS GATE")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-3 COMPLETION BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-3 COMPLETION BOUNDARY VALIDATION]")


if not RF_5_7_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-3 Controlled Random Oversampling definition "
        "has not passed validation."
    )


if not RF_5_7_2_VALIDATION[
    "training_features_loaded"
]:

    raise RuntimeError(
        "RF-3 Training feature artifact is not available."
    )


if not RF_5_7_2_VALIDATION[
    "validation_features_loaded"
]:

    raise RuntimeError(
        "RF-3 Validation feature artifact is not available."
    )


if not RF_5_7_4_VALIDATION[
    "rf3_model_available"
]:

    raise RuntimeError(
        "RF-3 Validation evaluation has not been completed."
    )


if not RF_5_7_5_VALIDATION[
    "rf3_model_available"
]:

    raise RuntimeError(
        "RF-3 error/resource analysis has not been completed."
    )


if not RF_5_7_6_VALIDATION[
    "model_persisted"
]:

    raise RuntimeError(
        "RF-3 fitted model has not been persisted."
    )


if RF3_MODEL is None:

    raise RuntimeError(
        "RF3_MODEL is not available in the current RF-3 runtime."
    )


if not hasattr(
    RF3_MODEL,
    "estimators_"
):

    raise RuntimeError(
        "RF3_MODEL is not a fitted Random Forest model."
    )


print(
    "✓ RF-3 Controlled Random Oversampling definition validated"
)

print(
    "✓ RF-3 Training/Validation artifact loading validated"
)

print(
    "✓ RF-3 validation evaluation completed"
)

print(
    "✓ RF-3 error/resource analysis completed"
)

print(
    "✓ Fitted RF-3 model is available"
)

print(
    "✓ RF-3 artifacts have been persisted"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# 2. FITTED RF-3 MODEL VALIDATION
# ---------------------------------------------------------------

print("\n[RF-3 FITTED MODEL VALIDATION]")


if RF3_MODEL.n_features_in_ != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-3 fitted model feature count does not match "
        "the established model-ready feature contract."
    )


if len(
    RF3_MODEL.classes_
) != 9:

    raise ValueError(
        "RF-3 fitted model does not contain the expected "
        "nine-class taxonomy."
    )


if len(
    RF3_MODEL.estimators_
) != RF_COMMON_CONFIGURATION[
    "n_estimators"
]:

    raise ValueError(
        "RF-3 fitted model tree count does not match "
        "the established RF configuration."
    )


if RF3_MODEL.class_weight is not None:

    raise ValueError(
        "RF-3 fitted model must retain "
        "class_weight=None."
    )


if RF3_MODEL.random_state != RANDOM_SEED:

    raise ValueError(
        "RF-3 fitted model random_state does not match "
        "the established project RANDOM_SEED."
    )


print(
    "✓ RF3_MODEL is the fitted RF-3 Random Forest"
)

print(
    f"✓ Model features : "
    f"{RF3_MODEL.n_features_in_}"
)

print(
    f"✓ Model classes  : "
    f"{len(RF3_MODEL.classes_)}"
)

print(
    f"✓ Model trees    : "
    f"{len(RF3_MODEL.estimators_)}"
)

print(
    "✓ Class weighting : None"
)

print(
    f"✓ Random state    : "
    f"{RF3_MODEL.random_state}"
)


# ---------------------------------------------------------------
# 3. RF-3 CONTROLLED RANDOM OVERSAMPLING VALIDATION
# ---------------------------------------------------------------

print("\n[RF-3 CONTROLLED RANDOM OVERSAMPLING VALIDATION]")


if RF3_CONFIGURATION[
    "strategy_id"
] != "RF-3":

    raise ValueError(
        "RF-3 strategy ID is not correctly identified."
    )


if RF3_CONFIGURATION[
    "strategy_name"
] != "Controlled Random Oversampling":

    raise ValueError(
        "RF-3 strategy name does not match the established "
        "Controlled Random Oversampling strategy."
    )


if RF3_CONFIGURATION[
    "class_weight"
] is not None:

    raise ValueError(
        "RF-3 class weighting must remain disabled."
    )


if RF3_CONFIGURATION[
    "resampling"
] is not True:

    raise ValueError(
        "RF-3 controlled random oversampling is not enabled."
    )


if RF3_CONFIGURATION[
    "synthetic_sampling"
] is not False:

    raise ValueError(
        "RF-3 synthetic sampling must remain disabled."
    )


if RF3_SAMPLING_CONFIGURATION[
    "majority_downsampling"
] is not False:

    raise ValueError(
        "RF-3 majority-class downsampling must remain prohibited."
    )


if RF3_SAMPLING_CONFIGURATION[
    "heartbleed_oversampling"
] is not False:

    raise ValueError(
        "RF-3 Heartbleed oversampling boundary has changed."
    )


if RF3_SAMPLING_CONFIGURATION[
    "infiltration_oversampling_eligible"
] is not True:

    raise ValueError(
        "RF-3 Infiltration eligibility boundary has changed."
    )


print(
    "✓ RF-3 strategy = Controlled Random Oversampling"
)

print(
    "✓ RF-3 class weighting = None"
)

print(
    "✓ Training-partition controlled oversampling enabled"
)

print(
    "✓ Synthetic sampling disabled"
)

print(
    "✓ Majority-class downsampling prohibited"
)

print(
    "✓ Heartbleed excluded from oversampling"
)

print(
    "✓ Infiltration remains eligible"
)


# ---------------------------------------------------------------
# 4. RF-3 OVERSAMPLING EXPERIMENT VALIDATION
# ---------------------------------------------------------------

print("\n[RF-3 OVERSAMPLING EXPERIMENT VALIDATION]")


if not RF_5_7_3_VALIDATION[
    "natural_training_observations"
]:

    raise RuntimeError(
        "RF-3 natural Training observation count is invalid."
    )


if not RF_5_7_3_VALIDATION[
    "oversampled_training_observations"
]:

    raise RuntimeError(
        "RF-3 oversampled Training representation is invalid."
    )


if not RF_5_7_3_VALIDATION[
    "oversampled_training_feature_count"
]:

    raise RuntimeError(
        "RF-3 oversampled Training feature count is invalid."
    )


if not RF_5_7_3_VALIDATION[
    "oversampled_training_class_distribution_valid"
]:

    raise RuntimeError(
        "RF-3 controlled Training class distribution "
        "does not match the established oversampling targets."
    )


if not RF_5_7_3_VALIDATION[
    "heartbleed_not_oversampled"
]:

    raise RuntimeError(
        "RF-3 Heartbleed was not preserved at its "
        "original Training support."
    )


if not RF_5_7_3_VALIDATION[
    "majority_downsampling_disabled"
]:

    raise RuntimeError(
        "RF-3 majority-class downsampling boundary failed."
    )


if not RF_5_7_3_VALIDATION[
    "synthetic_sampling_disabled"
]:

    raise RuntimeError(
        "RF-3 synthetic sampling boundary failed."
    )


print(
    f"✓ Original Training observations : "
    f"{RF3_ORIGINAL_TRAINING_OBSERVATIONS:,}"
)

print(
    f"✓ Oversampled Training observations : "
    f"{RF3_OVERSAMPLED_TRAINING_OBSERVATIONS:,}"
)

print(
    "✓ Controlled RF-3 Training class distribution validated"
)

print(
    "✓ Heartbleed remained unmodified"
)

print(
    "✓ Majority-class downsampling was not performed"
)

print(
    "✓ No synthetic observations were generated"
)


# ---------------------------------------------------------------
# 5. RF-3 PERSISTED ARTIFACT COMPLETENESS
# ---------------------------------------------------------------

print("\n[RF-3 PERSISTED ARTIFACT COMPLETENESS]")


if len(
    RF3_EXPERIMENT_ARTIFACTS
) != 7:

    raise RuntimeError(
        "Unexpected RF-3 artifact configuration."
    )


for artifact_name, artifact_path in (
    RF3_EXPERIMENT_ARTIFACTS.items()
):

    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"RF-3 artifact is missing: "
            f"{artifact_path}"
        )


    if artifact_path.stat().st_size <= 0:

        raise RuntimeError(
            f"RF-3 artifact is empty: "
            f"{artifact_path}"
        )


    print(
        f"✓ {artifact_name:<22} "
        f"persisted | "
        f"{artifact_path.stat().st_size:,} bytes"
    )


# ---------------------------------------------------------------
# 6. RF-3 PERSISTED RESULT STRUCTURE VALIDATION
# ---------------------------------------------------------------

print("\n[RF-3 PERSISTED RESULT STRUCTURE]")


RF3_PERSISTED_VALIDATION_METRICS = None

with open(
    RF3_EXPERIMENT_ARTIFACTS[
        "validation_metrics"
    ],
    "r",
    encoding="utf-8"
) as file:

    RF3_PERSISTED_VALIDATION_METRICS = (
        json.load(file)
    )


required_metric_names = {

    "accuracy",
    "balanced_accuracy",
    "macro_recall",
    "macro_f1",
    "weighted_f1",
    "benign_false_positive_rate",
    "macro_roc_auc_ovr",
    "total_attack_false_negatives",
}


if not required_metric_names.issubset(
    RF3_PERSISTED_VALIDATION_METRICS.keys()
):

    raise RuntimeError(
        "Persisted RF-3 Validation metrics are incomplete."
    )


RF3_PERSISTED_CONFUSION_MATRIX = pd.read_csv(
    RF3_EXPERIMENT_ARTIFACTS[
        "confusion_matrix"
    ],
    index_col=0
)


if RF3_PERSISTED_CONFUSION_MATRIX.shape != (
    9,
    9
):

    raise RuntimeError(
        "Persisted RF-3 confusion matrix is not 9 × 9."
    )


RF3_PERSISTED_CLASSIFICATION_REPORT = pd.read_csv(
    RF3_EXPERIMENT_ARTIFACTS[
        "classification_report"
    ]
)


if len(
    RF3_PERSISTED_CLASSIFICATION_REPORT
) != 9:

    raise RuntimeError(
        "Persisted RF-3 classification report does not "
        "contain all nine taxonomy classes."
    )


RF3_PERSISTED_FEATURE_IMPORTANCE = pd.read_csv(
    RF3_EXPERIMENT_ARTIFACTS[
        "feature_importance"
    ]
)


if len(
    RF3_PERSISTED_FEATURE_IMPORTANCE
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise RuntimeError(
        "Persisted RF-3 feature-importance table does not "
        "contain all 32 model-ready features."
    )


print(
    "✓ RF-3 Validation metrics structure confirmed"
)

print(
    "✓ RF-3 9 × 9 confusion matrix confirmed"
)

print(
    "✓ RF-3 nine-class classification report confirmed"
)

print(
    "✓ RF-3 32-feature importance table confirmed"
)


# ---------------------------------------------------------------
# 7. RF-3 METRIC CONSISTENCY CHECK
# ---------------------------------------------------------------

print("\n[RF-3 METRIC CONSISTENCY CHECK]")


if not np.isclose(
    RF3_PERSISTED_VALIDATION_METRICS[
        "accuracy"
    ],
    RF3_VALIDATION_ACCURACY
):

    raise RuntimeError(
        "Persisted RF-3 accuracy does not match "
        "the current RF-3 Validation result."
    )


if not np.isclose(
    RF3_PERSISTED_VALIDATION_METRICS[
        "macro_f1"
    ],
    RF3_VALIDATION_MACRO_F1
):

    raise RuntimeError(
        "Persisted RF-3 Macro F1 does not match "
        "the current RF-3 Validation result."
    )


if not np.isclose(
    RF3_PERSISTED_VALIDATION_METRICS[
        "balanced_accuracy"
    ],
    RF3_VALIDATION_BALANCED_ACCURACY
):

    raise RuntimeError(
        "Persisted RF-3 balanced accuracy does not match "
        "the current RF-3 Validation result."
    )


print(
    "✓ Persisted RF-3 accuracy matches Validation result"
)

print(
    "✓ Persisted RF-3 Macro F1 matches Validation result"
)

print(
    "✓ Persisted RF-3 balanced accuracy matches Validation result"
)


# ---------------------------------------------------------------
# 8. RF-3 COMPLETION AND DEVELOPMENT-BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-3 DEVELOPMENT-BOUNDARY VALIDATION]")


if not RF_5_7_6_VALIDATION[
    "independent_test_protected"
]:

    raise RuntimeError(
        "Independent Test protection was not preserved "
        "during RF-3."
    )


if not RF_5_7_6_VALIDATION[
    "n04_artifacts_untouched"
]:

    raise RuntimeError(
        "Notebook 04 model-ready artifacts were not confirmed "
        "as untouched."
    )


print(
    "✓ Independent Test remained excluded from RF-3"
)

print(
    "✓ Independent Test was not used for RF-3 evaluation "
    "or selection"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)


# ---------------------------------------------------------------
# 9. STRATEGY-SELECTION BOUNDARY
# ---------------------------------------------------------------

print("\n[STRATEGY-SELECTION BOUNDARY]")


print(
    "✓ RF-3 is retained as an independent experiment"
)

print(
    "✓ RF-3 has not been declared the optimal RF strategy"
)

print(
    "✓ No RF strategy selection has been performed"
)

print(
    "✓ RF-3 remains available for later Validation comparison"
)


# ---------------------------------------------------------------
# 10. MODEL-DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[MODEL-DEVELOPMENT BOUNDARY]")


print(
    "✓ No additional model fitting performed"
)

print(
    "✓ No additional predictions generated"
)

print(
    "✓ No additional resampling performed"
)

print(
    "✓ No synthetic samples generated"
)

print(
    "✓ No Independent Test data loaded"
)


# ---------------------------------------------------------------
# 11. FINAL RF-3 COMPLETION GATE
# ---------------------------------------------------------------

print("\n[FINAL RF-3 COMPLETION GATE]")


RF_5_7_7_VALIDATION = {

    "rf3_definition_complete":
        all(
            RF_5_7_1_VALIDATION.values()
        ),

    "rf3_artifact_loading_complete":
        all(
            RF_5_7_2_VALIDATION.values()
        ),

    "rf3_model_fitting_complete":
        all(
            RF_5_7_3_VALIDATION.values()
        ),

    "rf3_evaluation_complete":
        all(
            RF_5_7_4_VALIDATION.values()
        ),

    "rf3_error_resource_analysis_complete":
        all(
            RF_5_7_5_VALIDATION.values()
        ),

    "rf3_artifact_persistence_complete":
        all(
            RF_5_7_6_VALIDATION.values()
        ),

    "rf3_model_contract_valid":
        (
            RF3_MODEL.n_features_in_
            == EXPECTED_MODEL_READY_FEATURE_COUNT
        ),

    "rf3_taxonomy_valid":
        np.array_equal(
            RF3_MODEL.classes_,
            np.asarray(
                EXPECTED_RF_CLASS_IDS
            )
        ),

    "rf3_tree_count_valid":
        len(
            RF3_MODEL.estimators_
        )
        ==
        RF_COMMON_CONFIGURATION[
            "n_estimators"
        ],

    "rf3_controlled_oversampling_valid":
        (
            RF3_CONFIGURATION[
                "resampling"
            ] is True
            and
            RF3_CONFIGURATION[
                "synthetic_sampling"
            ] is False
            and
            RF3_SAMPLING_CONFIGURATION[
                "majority_downsampling"
            ] is False
            and
            RF3_SAMPLING_CONFIGURATION[
                "heartbleed_oversampling"
            ] is False
        ),

    "rf3_class_weighting_disabled":
        (
            RF3_CONFIGURATION[
                "class_weight"
            ] is None
            and
            RF3_MODEL.class_weight is None
        ),

    "rf3_artifact_count_valid":
        len(
            RF3_EXPERIMENT_ARTIFACTS
        ) == 7,

    "rf3_confusion_matrix_valid":
        RF3_PERSISTED_CONFUSION_MATRIX.shape
        == (9, 9),

    "rf3_classification_report_valid":
        len(
            RF3_PERSISTED_CLASSIFICATION_REPORT
        ) == 9,

    "rf3_feature_importance_valid":
        len(
            RF3_PERSISTED_FEATURE_IMPORTANCE
        )
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "independent_test_protected":
        RF_5_7_6_VALIDATION[
            "independent_test_protected"
        ],

    "n04_artifacts_untouched":
        RF_5_7_6_VALIDATION[
            "n04_artifacts_untouched"
        ],

    "strategy_not_selected":
        True,
}


failed_checks = [

    check_name

    for check_name, passed
    in RF_5_7_7_VALIDATION.items()

    if not passed

]


if failed_checks:

    raise RuntimeError(
        "5.7.7 RF-3 completion/readiness gate failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 12. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.7.7 — RF-3 EXPERIMENT COMPLETION AND READINESS GATE PASSED"
)

print("=" * 72)


print(
    "\nRF-3 CONTROLLED RANDOM OVERSAMPLING EXPERIMENT COMPLETED"
)

print(
    "✓ RF-3 definition validated"
)

print(
    "✓ Complete Training partition used for RF-3 fitting"
)

print(
    "✓ Complete Validation partition used for RF-3 evaluation"
)

print(
    "✓ RF-3 controlled random oversampling configuration validated"
)

print(
    "✓ RF-3 model contract validated"
)

print(
    "✓ RF-3 Validation results persisted"
)

print(
    "✓ RF-3 error and resource analysis completed"
)

print(
    "✓ All seven RF-3 experiment artifacts confirmed"
)

print(
    "✓ RF-3 remains an independent experiment and has not been selected"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "\nREADY FOR 5.8 — RF-4: CONTROLLED SMOTE"
)

print("=" * 72)

========================================================================
5.7.7 — RF-3 EXPERIMENT COMPLETION AND READINESS GATE
========================================================================

[RF-3 COMPLETION BOUNDARY VALIDATION]
✓ RF-3 Controlled Random Oversampling definition validated
✓ RF-3 Training/Validation artifact loading validated
✓ RF-3 validation evaluation completed
✓ RF-3 error/resource analysis completed
✓ Fitted RF-3 model is available
✓ RF-3 artifacts have been persisted
✓ Independent Test remains excluded

[RF-3 FITTED MODEL VALIDATION]
✓ RF3_MODEL is the fitted RF-3 Random Forest
✓ Model features : 32
✓ Model classes  : 9
✓ Model trees    : 100
✓ Class weighting : None
✓ Random state    : 42

[RF-3 CONTROLLED RANDOM OVERSAMPLING VALIDATION]
✓ RF-3 strategy = Controlled Random Oversampling
✓ RF-3 class weighting = None
✓ Training-partition controlled oversampling enabled
✓ Synthetic sampling disabled
✓ Majority-class downsampling prohibited
✓ Heartbleed excluded from oversampling
✓ Infiltration remains eligible

[RF-3 OVERSAMPLING EXPERIMENT VALIDATION]
✓ Original Training observations : 1,814,018
✓ Oversampled Training observations : 1,862,014
✓ Controlled RF-3 Training class distribution validated
✓ Heartbleed remained unmodified
✓ Majority-class downsampling was not performed
✓ No synthetic observations were generated

[RF-3 PERSISTED ARTIFACT COMPLETENESS]
✓ experiment_metadata    persisted | 2,372 bytes
✓ validation_metrics     persisted | 338 bytes
✓ confusion_matrix       persisted | 353 bytes
✓ classification_report  persisted | 652 bytes
✓ resource_metrics       persisted | 816 bytes
✓ feature_importance     persisted | 1,171 bytes
✓ model                  persisted | 17,158,219 bytes

[RF-3 PERSISTED RESULT STRUCTURE]
✓ RF-3 Validation metrics structure confirmed
✓ RF-3 9 × 9 confusion matrix confirmed
✓ RF-3 nine-class classification report confirmed
✓ RF-3 32-feature importance table confirmed

[RF-3 METRIC CONSISTENCY CHECK]
✓ Persisted RF-3 accuracy matches Validation result
✓ Persisted RF-3 Macro F1 matches Validation result
✓ Persisted RF-3 balanced accuracy matches Validation result

[RF-3 DEVELOPMENT-BOUNDARY VALIDATION]
✓ Independent Test remained excluded from RF-3
✓ Independent Test was not used for RF-3 evaluation or selection
✓ Notebook 04 model-ready artifacts remain untouched

[STRATEGY-SELECTION BOUNDARY]
✓ RF-3 is retained as an independent experiment
✓ RF-3 has not been declared the optimal RF strategy
✓ No RF strategy selection has been performed
✓ RF-3 remains available for later Validation comparison

[MODEL-DEVELOPMENT BOUNDARY]
✓ No additional model fitting performed
✓ No additional predictions generated
✓ No additional resampling performed
✓ No synthetic samples generated
✓ No Independent Test data loaded

[FINAL RF-3 COMPLETION GATE]

========================================================================
5.7.7 — RF-3 EXPERIMENT COMPLETION AND READINESS GATE PASSED
========================================================================

RF-3 CONTROLLED RANDOM OVERSAMPLING EXPERIMENT COMPLETED
✓ RF-3 definition validated
✓ Complete Training partition used for RF-3 fitting
✓ Complete Validation partition used for RF-3 evaluation
✓ RF-3 controlled random oversampling configuration validated
✓ RF-3 model contract validated
✓ RF-3 Validation results persisted
✓ RF-3 error and resource analysis completed
✓ All seven RF-3 experiment artifacts confirmed
✓ RF-3 remains an independent experiment and has not been selected
✓ Independent Test remains completely untouched
✓ Notebook 04 model-ready artifacts remain untouched

READY FOR 5.8 — RF-4: CONTROLLED SMOTE
========================================================================

# 5.8 — RF-4: Controlled SMOTE

This section evaluates **Controlled SMOTE (Synthetic Minority Over-sampling Technique)** as the fourth Random Forest imbalance-handling strategy.

RF-4 is designed to determine whether controlled synthetic oversampling of eligible minority classes in the **Training partition** can improve minority-class detection and macro-level performance while maintaining acceptable overall Random Forest performance.

The experiment retains the **common Random Forest configuration** established in Section 5.3. The only methodological change from the natural and class-weighting strategies is the use of controlled synthetic sampling during Training.

### RF-4 Experimental Boundaries

- **Strategy:** Controlled SMOTE
- **Training partition:** SMOTE may be applied only to Training data
- **Validation partition:** Remains completely untouched and is used for evaluation, comparison, and later strategy selection
- **Independent Test:** Completely excluded from model fitting, resampling, comparison, and selection
- **Class weighting:** Disabled (`class_weight=None`)
- **Minimum Training support:** 10 observations
- **Controlled oversampling multiplier:** 5×
- **Maximum target:** 50,000 observations per class
- **Majority-class downsampling:** Prohibited
- **Heartbleed:** Excluded from synthetic sampling because its Training support is below the minimum threshold
- **Infiltration:** Remains eligible for controlled synthetic sampling, with the established low-support interpretation caveat

RF-4 is executed as an independent experiment and is not compared with or selected against RF-0 through RF-3 within this section. Strategy comparison is deferred to Section 5.9, while final strategy selection is deferred to Section 5.10.

The Independent Test remains reserved exclusively for the final evaluation stage after the Random Forest strategy has been selected and finalized.

## 5.8.1 — RF-4 Controlled SMOTE Experiment Definition

This subsection formally defines the **RF-4 Controlled SMOTE experiment** before any Training/Validation data loading, SMOTE execution, model fitting, prediction, or evaluation takes place.

RF-4 retains the established Random Forest configuration and replaces RF-3's controlled random duplication with **controlled synthetic oversampling** of eligible minority classes. The experiment uses the same predefined support and sampling boundaries so that RF-4 remains methodologically comparable with RF-3.

### RF-4 Strategy Definition

RF-4 uses:

- `class_weight=None`
- Training-partition resampling enabled
- Synthetic sampling enabled
- Training as the model-fitting partition
- Validation as the evaluation partition
- Independent Test excluded from the experiment

### Controlled SMOTE Boundary

The established controlled sampling rules are retained:

- Minimum Training support = **10**
- Controlled oversampling multiplier = **5×**
- Maximum target = **50,000 observations/class**
- Majority-class downsampling = **prohibited**
- Heartbleed = **excluded from synthetic sampling**
- Infiltration = **eligible**, subject to the low-support interpretation caveat

These boundaries prevent unrestricted synthetic expansion and ensure that RF-4 remains a controlled imbalance experiment rather than an unrestricted dataset transformation.

### Partition Protection

Only the Training partition may be modified by the RF-4 sampling procedure. Validation must remain in its original distribution for unbiased strategy comparison, and the Independent Test must remain completely untouched.

This subsection therefore performs only **configuration and boundary validation**. No model is fitted, no data arrays are loaded, no synthetic observations are generated, and no evaluation metrics are calculated.

A successful validation marks RF-4 as ready for **5.8.2 — RF-4 Training and Validation Artifact Loading**.

In [ ]:
# ================================================================
# 5.8.1 — RF-4 CONTROLLED SMOTE EXPERIMENT DEFINITION
# ================================================================

print("=" * 72)
print("5.8.1 — RF-4 CONTROLLED SMOTE EXPERIMENT DEFINITION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-4 STRATEGY DEFINITION
# ---------------------------------------------------------------

print("\n[RF-4 STRATEGY DEFINITION]")


RF4_CONFIGURATION = {
    "strategy_id": "RF-4",
    "strategy_name": "Controlled SMOTE",
    "class_weight": None,
    "resampling": True,
    "synthetic_sampling": True,
    "training_partition": "Training",
    "evaluation_partition": "Validation",
    "test_used": False,
}


print(
    f"\n✓ Strategy ID        : "
    f"{RF4_CONFIGURATION['strategy_id']}"
)

print(
    f"✓ Strategy name      : "
    f"{RF4_CONFIGURATION['strategy_name']}"
)

print(
    f"✓ Class weighting    : "
    f"{RF4_CONFIGURATION['class_weight']}"
)

print(
    f"✓ Resampling         : "
    f"{RF4_CONFIGURATION['resampling']}"
)

print(
    f"✓ Synthetic sampling : "
    f"{RF4_CONFIGURATION['synthetic_sampling']}"
)

print(
    f"✓ Training partition : "
    f"{RF4_CONFIGURATION['training_partition']}"
)

print(
    f"✓ Evaluation         : "
    f"{RF4_CONFIGURATION['evaluation_partition']}"
)

print(
    f"✓ Independent Test   : "
    f"Excluded"
)


# ---------------------------------------------------------------
# 2. COMMON RANDOM FOREST CONFIGURATION CHECK
# ---------------------------------------------------------------

print("\n[COMMON RANDOM FOREST CONFIGURATION]")


if not isinstance(
    RF_COMMON_CONFIGURATION,
    dict
):

    raise TypeError(
        "RF_COMMON_CONFIGURATION must be a dictionary."
    )


if RF_COMMON_CONFIGURATION[
    "random_state"
] != RANDOM_SEED:

    raise RuntimeError(
        "RF-4 random_state does not match "
        "the established project RANDOM_SEED."
    )


print(
    f"✓ Number of trees   : "
    f"{RF_COMMON_CONFIGURATION['n_estimators']}"
)

print(
    f"✓ Max features      : "
    f"{RF_COMMON_CONFIGURATION['max_features']}"
)

print(
    f"✓ Max depth         : "
    f"{RF_COMMON_CONFIGURATION['max_depth']}"
)

print(
    f"✓ Bootstrap         : "
    f"{RF_COMMON_CONFIGURATION['bootstrap']}"
)

print(
    f"✓ CPU parallelism   : "
    f"{RF_COMMON_CONFIGURATION['n_jobs']}"
)

print(
    f"✓ Random seed       : "
    f"{RF_COMMON_CONFIGURATION['random_state']}"
)


# ---------------------------------------------------------------
# 3. RF-4 CONTROLLED SMOTE BOUNDARY
# ---------------------------------------------------------------

print(
    "\n[RF-4 CONTROLLED SMOTE BOUNDARY]"
)


RF4_SAMPLING_CONFIGURATION = {
    "minimum_training_support": 10,
    "oversampling_multiplier": 5,
    "maximum_target_per_class": 50_000,
    "majority_downsampling": False,
    "heartbleed_oversampling": False,
    "infiltration_oversampling_eligible": True,
}


if RF4_CONFIGURATION[
    "class_weight"
] is not None:

    raise RuntimeError(
        "RF-4 must not use Random Forest class weighting. "
        "The imbalance intervention is controlled SMOTE."
    )


if RF4_CONFIGURATION[
    "resampling"
] is not True:

    raise RuntimeError(
        "RF-4 must enable Training-partition resampling."
    )


if RF4_CONFIGURATION[
    "synthetic_sampling"
] is not True:

    raise RuntimeError(
        "RF-4 must enable synthetic sampling."
    )


if RF4_SAMPLING_CONFIGURATION[
    "minimum_training_support"
] != 10:

    raise RuntimeError(
        "RF-4 minimum Training support must be 10."
    )


if RF4_SAMPLING_CONFIGURATION[
    "oversampling_multiplier"
] != 5:

    raise RuntimeError(
        "RF-4 controlled oversampling multiplier must be 5x."
    )


if RF4_SAMPLING_CONFIGURATION[
    "maximum_target_per_class"
] != 50_000:

    raise RuntimeError(
        "RF-4 maximum target must be 50,000 observations "
        "per class."
    )


if RF4_SAMPLING_CONFIGURATION[
    "majority_downsampling"
]:

    raise RuntimeError(
        "RF-4 must prohibit majority-class downsampling."
    )


if RF4_SAMPLING_CONFIGURATION[
    "heartbleed_oversampling"
]:

    raise RuntimeError(
        "Heartbleed must remain excluded from RF-4 "
        "synthetic sampling."
    )


if not RF4_SAMPLING_CONFIGURATION[
    "infiltration_oversampling_eligible"
]:

    raise RuntimeError(
        "Infiltration must remain eligible for RF-4 "
        "synthetic sampling subject to the minimum-support boundary."
    )


print(
    "✓ Controlled SMOTE enabled"
)

print(
    "✓ Minimum Training support : 10"
)

print(
    "✓ Oversampling multiplier  : 5x"
)

print(
    "✓ Maximum target/class     : 50,000"
)

print(
    "✓ Majority-class downsampling prohibited"
)

print(
    "✓ Heartbleed excluded from synthetic sampling"
)

print(
    "✓ Infiltration remains eligible with low-support caveat"
)

print(
    "✓ SMOTE configured for RF-4"
)

print(
    "✓ Synthetic sampling restricted to Training"
)


# ---------------------------------------------------------------
# 4. PARTITION-ROLE VALIDATION
# ---------------------------------------------------------------

print("\n[TRAINING / VALIDATION / TEST ROLE BOUNDARY]")


if not RF_5_2_4_VALIDATION[
    "training_authorized_for_fitting"
]:

    raise RuntimeError(
        "Training is not authorized for RF-4 model fitting."
    )


if not RF_5_2_4_VALIDATION[
    "validation_reserved_for_comparison"
]:

    raise RuntimeError(
        "Validation is not reserved for RF strategy comparison."
    )


if not RF_5_2_4_VALIDATION[
    "validation_reserved_for_selection"
]:

    raise RuntimeError(
        "Validation is not reserved for RF strategy selection."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_fitting"
]:

    raise RuntimeError(
        "Independent Test is not protected from model fitting."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_comparison"
]:

    raise RuntimeError(
        "Independent Test is not protected from strategy comparison."
    )


if not RF_5_2_4_VALIDATION[
    "test_excluded_from_selection"
]:

    raise RuntimeError(
        "Independent Test is not protected from strategy selection."
    )


print(
    "✓ Training authorized for RF-4 model fitting"
)

print(
    "✓ Validation reserved for RF-4 evaluation and comparison"
)

print(
    "✓ Validation reserved for strategy selection"
)

print(
    "✓ Independent Test excluded from model fitting"
)

print(
    "✓ Independent Test excluded from strategy comparison"
)

print(
    "✓ Independent Test excluded from strategy selection"
)


# ---------------------------------------------------------------
# 5. RF-4 OUTPUT BOUNDARY
# ---------------------------------------------------------------

print("\n[RF-4 EXPERIMENT OUTPUT BOUNDARY]")


RF4_OUTPUT_DIR = (
    RF_STRATEGY_EXPERIMENTS_DIR /
    "RF-4"
)


RF4_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


print(
    "✓ RF-4 output directory available:"
)

print(
    f"  {RF4_OUTPUT_DIR}"
)


# ---------------------------------------------------------------
# 6. MODEL-DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[MODEL-DEVELOPMENT BOUNDARY]")


print(
    "✓ No Training feature array loaded"
)

print(
    "✓ No Validation feature array loaded"
)

print(
    "✓ No Test feature array loaded"
)

print(
    "✓ No target array loaded"
)

print(
    "✓ No Random Forest model fitted"
)

print(
    "✓ No SMOTE resampling performed"
)

print(
    "✓ No majority-class downsampling performed"
)

print(
    "✓ No synthetic samples generated"
)

print(
    "✓ No predictions generated"
)

print(
    "✓ No evaluation metrics calculated"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 7. FINAL RF-4 DEFINITION VALIDATION
# ---------------------------------------------------------------

print("\n[RF-4 DEFINITION VALIDATION]")


RF_5_8_1_VALIDATION = {

    "strategy_id_valid":
        RF4_CONFIGURATION[
            "strategy_id"
        ] == "RF-4",

    "strategy_name_valid":
        RF4_CONFIGURATION[
            "strategy_name"
        ] == "Controlled SMOTE",

    "class_weight_disabled":
        RF4_CONFIGURATION[
            "class_weight"
        ] is None,

    "resampling_enabled":
        RF4_CONFIGURATION[
            "resampling"
        ] is True,

    "synthetic_sampling_enabled":
        RF4_CONFIGURATION[
            "synthetic_sampling"
        ] is True,

    "training_partition_valid":
        RF4_CONFIGURATION[
            "training_partition"
        ] == "Training",

    "validation_partition_valid":
        RF4_CONFIGURATION[
            "evaluation_partition"
        ] == "Validation",

    "test_not_used":
        RF4_CONFIGURATION[
            "test_used"
        ] is False,

    "minimum_support_valid":
        RF4_SAMPLING_CONFIGURATION[
            "minimum_training_support"
        ] == 10,

    "oversampling_multiplier_valid":
        RF4_SAMPLING_CONFIGURATION[
            "oversampling_multiplier"
        ] == 5,

    "maximum_target_valid":
        RF4_SAMPLING_CONFIGURATION[
            "maximum_target_per_class"
        ] == 50_000,

    "majority_downsampling_prohibited":
        RF4_SAMPLING_CONFIGURATION[
            "majority_downsampling"
        ] is False,

    "heartbleed_excluded":
        RF4_SAMPLING_CONFIGURATION[
            "heartbleed_oversampling"
        ] is False,

    "infiltration_eligible":
        RF4_SAMPLING_CONFIGURATION[
            "infiltration_oversampling_eligible"
        ] is True,

    "output_directory_available":
        RF4_OUTPUT_DIR.is_dir(),

    "random_state_consistent":
        RF_COMMON_CONFIGURATION[
            "random_state"
        ] == RANDOM_SEED,

    "training_authorized":
        RF_5_2_4_VALIDATION[
            "training_authorized_for_fitting"
        ],

    "validation_reserved_for_comparison":
        RF_5_2_4_VALIDATION[
            "validation_reserved_for_comparison"
        ],

    "test_protected_from_fitting":
        RF_5_2_4_VALIDATION[
            "test_excluded_from_fitting"
        ],

    "test_protected_from_comparison":
        RF_5_2_4_VALIDATION[
            "test_excluded_from_comparison"
        ],

    "test_protected_from_selection":
        RF_5_2_4_VALIDATION[
            "test_excluded_from_selection"
        ],
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_8_1_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "RF-4 controlled SMOTE definition "
        "validation failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 8. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.8.1 — RF-4 CONTROLLED SMOTE "
    "EXPERIMENT DEFINITION PASSED"
)

print("=" * 72)

print(
    "\n✓ Controlled SMOTE boundary defined for RF-4."
)

print(
    "✓ Common Random Forest configuration retained"
)

print(
    "✓ Controlled Training-partition SMOTE configured"
)

print(
    "✓ Minimum support threshold = 10"
)

print(
    "✓ Oversampling multiplier = 5x"
)

print(
    "✓ Maximum target = 50,000 observations/class"
)

print(
    "✓ Majority-class downsampling prohibited"
)

print(
    "✓ Heartbleed excluded from synthetic sampling"
)

print(
    "✓ Infiltration remains eligible with low-support caveat"
)

print(
    "✓ Validation reserved for evaluation"
)

print(
    "✓ Independent Test remains protected"
)

print(
    "✓ No model fitting or data loading performed"
)

print(
    "\nREADY FOR 5.8.2 — "
    "RF-4 TRAINING AND VALIDATION ARTIFACT LOADING"
)

print("=" * 72)

========================================================================
5.8.1 — RF-4 CONTROLLED SMOTE EXPERIMENT DEFINITION
========================================================================

[RF-4 STRATEGY DEFINITION]

✓ Strategy ID        : RF-4
✓ Strategy name      : Controlled SMOTE
✓ Class weighting    : None
✓ Resampling         : True
✓ Synthetic sampling : True
✓ Training partition : Training
✓ Evaluation         : Validation
✓ Independent Test   : Excluded

[COMMON RANDOM FOREST CONFIGURATION]
✓ Number of trees   : 100
✓ Max features      : sqrt
✓ Max depth         : None
✓ Bootstrap         : True
✓ CPU parallelism   : -1
✓ Random seed       : 42

[RF-4 CONTROLLED SMOTE BOUNDARY]
✓ Controlled SMOTE enabled
✓ Minimum Training support : 10
✓ Oversampling multiplier  : 5x
✓ Maximum target/class     : 50,000
✓ Majority-class downsampling prohibited
✓ Heartbleed excluded from synthetic sampling
✓ Infiltration remains eligible with low-support caveat
✓ SMOTE configured for RF-4
✓ Synthetic sampling restricted to Training

[TRAINING / VALIDATION / TEST ROLE BOUNDARY]
✓ Training authorized for RF-4 model fitting
✓ Validation reserved for RF-4 evaluation and comparison
✓ Validation reserved for strategy selection
✓ Independent Test excluded from model fitting
✓ Independent Test excluded from strategy comparison
✓ Independent Test excluded from strategy selection

[RF-4 EXPERIMENT OUTPUT BOUNDARY]
✓ RF-4 output directory available:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4

[MODEL-DEVELOPMENT BOUNDARY]
✓ No Training feature array loaded
✓ No Validation feature array loaded
✓ No Test feature array loaded
✓ No target array loaded
✓ No Random Forest model fitted
✓ No SMOTE resampling performed
✓ No majority-class downsampling performed
✓ No synthetic samples generated
✓ No predictions generated
✓ No evaluation metrics calculated
✓ Independent Test remains untouched

[RF-4 DEFINITION VALIDATION]

========================================================================
5.8.1 — RF-4 CONTROLLED SMOTE EXPERIMENT DEFINITION PASSED
========================================================================

✓ Controlled SMOTE boundary defined for RF-4.
✓ Common Random Forest configuration retained
✓ Controlled Training-partition SMOTE configured
✓ Minimum support threshold = 10
✓ Oversampling multiplier = 5x
✓ Maximum target = 50,000 observations/class
✓ Majority-class downsampling prohibited
✓ Heartbleed excluded from synthetic sampling
✓ Infiltration remains eligible with low-support caveat
✓ Validation reserved for evaluation
✓ Independent Test remains protected
✓ No model fitting or data loading performed

READY FOR 5.8.2 — RF-4 TRAINING AND VALIDATION ARTIFACT LOADING
========================================================================

## 5.8.2 — RF-4 Training and Validation Artifact Loading

This subsection loads and validates the authoritative N04 Training and Validation artifacts required for the RF-4 Controlled SMOTE experiment.

The Training partition is loaded for subsequent RF-4 model development and controlled synthetic sampling, while the Validation partition is loaded only for later evaluation and strategy comparison. The Independent Test partition is deliberately not loaded at this stage and remains completely protected from RF-4 development.

The same model-ready artifacts used by the preceding Random Forest experiments are retained. Training and Validation features must remain in the established 32-feature `float32` representation, while the corresponding target arrays must remain `int64`.

### Loading and Validation Requirements

- Load only the authoritative Training and Validation feature/target artifacts.
- Open all arrays using read-only memory mapping with `mmap_mode="r"`.
- Confirm Training dimensions of `(1,814,018, 32)`.
- Confirm Validation dimensions of `(451,215, 32)`.
- Confirm feature dtype is `float32`.
- Confirm target dtype is `int64`.
- Confirm Training and Validation X/y observation counts are aligned.
- Confirm both partitions share the same established 32-feature model-ready representation.
- Confirm the Independent Test feature and target artifacts are not loaded.
- Avoid unnecessary full-array RAM duplication.

No SMOTE operation, synthetic sample generation, majority-class downsampling, model fitting, prediction, or evaluation is performed in this subsection.

A successful validation confirms that the RF-4 experiment has access to the complete Training and Validation partitions while preserving the established memory-aware execution boundary and Independent Test protection.

In [ ]:
# ================================================================
# 5.8.2 — RF-4 TRAINING AND VALIDATION ARTIFACT LOADING
# ================================================================

import numpy as np

print("=" * 72)
print("5.8.2 — RF-4 TRAINING AND VALIDATION ARTIFACT LOADING")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-4 ARTIFACT LOADING BOUNDARY
# ---------------------------------------------------------------

print("\n[RF-4 ARTIFACT LOADING BOUNDARY]")


if not RF_5_8_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-4 Controlled SMOTE definition "
        "has not passed validation."
    )


if RF4_CONFIGURATION[
    "training_partition"
] != "Training":

    raise RuntimeError(
        "RF-4 training partition is not the authoritative "
        "Training partition."
    )


if RF4_CONFIGURATION[
    "evaluation_partition"
] != "Validation":

    raise RuntimeError(
        "RF-4 evaluation partition is not the authoritative "
        "Validation partition."
    )


print(
    "✓ RF-4 Controlled SMOTE definition is valid"
)

print(
    "✓ Training artifact authorized for RF-4 model fitting"
)

print(
    "✓ Validation artifact authorized for RF-4 evaluation"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# 2. RF-4 CONTROLLED SMOTE BOUNDARY
# ---------------------------------------------------------------

print(
    "\n[RF-4 CONTROLLED SMOTE BOUNDARY]"
)


if RF4_CONFIGURATION[
    "resampling"
] is not True:

    raise RuntimeError(
        "RF-4 must enable Training-partition resampling."
    )


if RF4_CONFIGURATION[
    "synthetic_sampling"
] is not True:

    raise RuntimeError(
        "RF-4 must enable synthetic sampling."
    )


if RF4_SAMPLING_CONFIGURATION[
    "minimum_training_support"
] != 10:

    raise RuntimeError(
        "RF-4 minimum Training support must be 10."
    )


if RF4_SAMPLING_CONFIGURATION[
    "oversampling_multiplier"
] != 5:

    raise RuntimeError(
        "RF-4 oversampling multiplier must be 5x."
    )


if RF4_SAMPLING_CONFIGURATION[
    "maximum_target_per_class"
] != 50_000:

    raise RuntimeError(
        "RF-4 maximum target must be 50,000 observations "
        "per class."
    )


if RF4_SAMPLING_CONFIGURATION[
    "majority_downsampling"
]:

    raise RuntimeError(
        "RF-4 must prohibit majority-class downsampling."
    )


if RF4_SAMPLING_CONFIGURATION[
    "heartbleed_oversampling"
]:

    raise RuntimeError(
        "Heartbleed must remain excluded from RF-4 "
        "synthetic sampling."
    )


if not RF4_SAMPLING_CONFIGURATION[
    "infiltration_oversampling_eligible"
]:

    raise RuntimeError(
        "Infiltration must remain eligible for RF-4 "
        "synthetic sampling subject to the minimum-support boundary."
    )


print(
    "✓ Controlled SMOTE enabled"
)

print(
    "✓ Minimum Training support : 10"
)

print(
    "✓ Oversampling multiplier  : 5x"
)

print(
    "✓ Maximum target/class     : 50,000"
)

print(
    "✓ Majority-class downsampling prohibited"
)

print(
    "✓ Heartbleed excluded from synthetic sampling"
)

print(
    "✓ Infiltration remains eligible with low-support caveat"
)

print(
    "✓ SMOTE boundary configured for RF-4"
)

print(
    "✓ No synthetic observations generated"
)


# ---------------------------------------------------------------
# 3. AUTHORITATIVE RF-4 ARTIFACT PATHS
# ---------------------------------------------------------------

print("\n[AUTHORITATIVE RF-4 ARTIFACT PATHS]")


RF4_TRAINING_FEATURE_PATH = RF_INPUT_PATHS[
    "Training features"
]

RF4_TRAINING_TARGET_PATH = RF_INPUT_PATHS[
    "Training targets"
]

RF4_VALIDATION_FEATURE_PATH = RF_INPUT_PATHS[
    "Validation features"
]

RF4_VALIDATION_TARGET_PATH = RF_INPUT_PATHS[
    "Validation targets"
]


for artifact_name, artifact_path in {
    "Training features":
        RF4_TRAINING_FEATURE_PATH,

    "Training targets":
        RF4_TRAINING_TARGET_PATH,

    "Validation features":
        RF4_VALIDATION_FEATURE_PATH,

    "Validation targets":
        RF4_VALIDATION_TARGET_PATH,

}.items():

    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"{artifact_name} artifact was not found:\n"
            f"{artifact_path}"
        )

    if artifact_path.stat().st_size == 0:

        raise ValueError(
            f"{artifact_name} artifact is empty:\n"
            f"{artifact_path}"
        )

    print(
        f"✓ {artifact_name:<20}: "
        f"{artifact_path.name}"
    )


# ---------------------------------------------------------------
# 4. READ-ONLY MEMORY-MAPPED LOADING
# ---------------------------------------------------------------

print("\n[READ-ONLY MEMORY-MAPPED LOADING]")


# The complete arrays are not copied into normal RAM.
# mmap_mode="r" provides read-only access to the persisted
# NumPy arrays.

RF4_TRAINING_FEATURES = np.load(
    RF4_TRAINING_FEATURE_PATH,
    mmap_mode="r"
)

RF4_TRAINING_TARGETS = np.load(
    RF4_TRAINING_TARGET_PATH,
    mmap_mode="r"
)

RF4_VALIDATION_FEATURES = np.load(
    RF4_VALIDATION_FEATURE_PATH,
    mmap_mode="r"
)

RF4_VALIDATION_TARGETS = np.load(
    RF4_VALIDATION_TARGET_PATH,
    mmap_mode="r"
)


print(
    "✓ Training features opened as read-only memory map"
)

print(
    "✓ Training targets opened as read-only memory map"
)

print(
    "✓ Validation features opened as read-only memory map"
)

print(
    "✓ Validation targets opened as read-only memory map"
)


# ---------------------------------------------------------------
# 5. FEATURE ARTIFACT VALIDATION
# ---------------------------------------------------------------

print("\n[RF-4 FEATURE ARTIFACT VALIDATION]")


if RF4_TRAINING_FEATURES.shape != (
    1_814_018,
    32
):

    raise ValueError(
        "RF-4 Training feature shape mismatch.\n"
        f"Expected: {(1_814_018, 32)}\n"
        f"Observed: {RF4_TRAINING_FEATURES.shape}"
    )


if RF4_VALIDATION_FEATURES.shape != (
    451_215,
    32
):

    raise ValueError(
        "RF-4 Validation feature shape mismatch.\n"
        f"Expected: {(451_215, 32)}\n"
        f"Observed: {RF4_VALIDATION_FEATURES.shape}"
    )


if RF4_TRAINING_FEATURES.dtype != np.float32:

    raise TypeError(
        "RF-4 Training features must use float32."
    )


if RF4_VALIDATION_FEATURES.dtype != np.float32:

    raise TypeError(
        "RF-4 Validation features must use float32."
    )


print(
    f"✓ Training features    : "
    f"{RF4_TRAINING_FEATURES.shape} | "
    f"{RF4_TRAINING_FEATURES.dtype}"
)

print(
    f"✓ Validation features  : "
    f"{RF4_VALIDATION_FEATURES.shape} | "
    f"{RF4_VALIDATION_FEATURES.dtype}"
)


# ---------------------------------------------------------------
# 6. TARGET ARTIFACT VALIDATION
# ---------------------------------------------------------------

print("\n[RF-4 TARGET ARTIFACT VALIDATION]")


if RF4_TRAINING_TARGETS.shape != (
    1_814_018,
):

    raise ValueError(
        "RF-4 Training target shape mismatch.\n"
        f"Expected: {(1_814_018,)}\n"
        f"Observed: {RF4_TRAINING_TARGETS.shape}"
    )


if RF4_VALIDATION_TARGETS.shape != (
    451_215,
):

    raise ValueError(
        "RF-4 Validation target shape mismatch.\n"
        f"Expected: {(451_215,)}\n"
        f"Observed: {RF4_VALIDATION_TARGETS.shape}"
    )


if RF4_TRAINING_TARGETS.dtype != np.int64:

    raise TypeError(
        "RF-4 Training targets must use int64."
    )


if RF4_VALIDATION_TARGETS.dtype != np.int64:

    raise TypeError(
        "RF-4 Validation targets must use int64."
    )


print(
    f"✓ Training targets    : "
    f"{RF4_TRAINING_TARGETS.shape} | "
    f"{RF4_TRAINING_TARGETS.dtype}"
)

print(
    f"✓ Validation targets  : "
    f"{RF4_VALIDATION_TARGETS.shape} | "
    f"{RF4_VALIDATION_TARGETS.dtype}"
)


# ---------------------------------------------------------------
# 7. X/Y OBSERVATION ALIGNMENT
# ---------------------------------------------------------------

print("\n[X/Y OBSERVATION ALIGNMENT]")


if (
    RF4_TRAINING_FEATURES.shape[0]
    != RF4_TRAINING_TARGETS.shape[0]
):

    raise ValueError(
        "RF-4 Training feature/target observation counts "
        "are not aligned."
    )


if (
    RF4_VALIDATION_FEATURES.shape[0]
    != RF4_VALIDATION_TARGETS.shape[0]
):

    raise ValueError(
        "RF-4 Validation feature/target observation counts "
        "are not aligned."
    )


print(
    "✓ Training features and targets are observation-aligned"
)

print(
    "✓ Validation features and targets are observation-aligned"
)


# ---------------------------------------------------------------
# 8. CONFIRM COMMON MODEL-READY FEATURE SPACE
# ---------------------------------------------------------------

print("\n[COMMON RF-4 MODEL-READY FEATURE SPACE]")


if (
    RF4_TRAINING_FEATURES.shape[1]
    != RF4_VALIDATION_FEATURES.shape[1]
):

    raise ValueError(
        "RF-4 Training and Validation feature dimensions "
        "do not match."
    )


if RF4_TRAINING_FEATURES.shape[1] != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-4 feature count does not match the established "
        "N04 model-ready feature contract."
    )


print(
    f"✓ Common RF-4 feature count : "
    f"{RF4_TRAINING_FEATURES.shape[1]}"
)

print(
    "✓ Training and Validation share the same "
    "32-feature model-ready representation"
)


# ---------------------------------------------------------------
# 9. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION]")


print(
    "✓ Independent Test feature artifact was not loaded"
)

print(
    "✓ Independent Test target artifact was not loaded"
)

print(
    "✓ Independent Test remains protected from RF-4 development"
)


# ---------------------------------------------------------------
# 10. MEMORY-AWARE EXECUTION CHECK
# ---------------------------------------------------------------

print("\n[MEMORY-AWARE EXECUTION CHECK]")


if not isinstance(
    RF4_TRAINING_FEATURES,
    np.memmap
):

    raise TypeError(
        "RF-4 Training features were not loaded "
        "as a NumPy memory map."
    )


if not isinstance(
    RF4_TRAINING_TARGETS,
    np.memmap
):

    raise TypeError(
        "RF-4 Training targets were not loaded "
        "as a NumPy memory map."
    )


if not isinstance(
    RF4_VALIDATION_FEATURES,
    np.memmap
):

    raise TypeError(
        "RF-4 Validation features were not loaded "
        "as a NumPy memory map."
    )


if not isinstance(
    RF4_VALIDATION_TARGETS,
    np.memmap
):

    raise TypeError(
        "RF-4 Validation targets were not loaded "
        "as a NumPy memory map."
    )


print(
    "✓ Training features remain memory-mapped"
)

print(
    "✓ Training targets remain memory-mapped"
)

print(
    "✓ Validation features remain memory-mapped"
)

print(
    "✓ Validation targets remain memory-mapped"
)

print(
    "✓ No full-array RAM duplication performed"
)


# ---------------------------------------------------------------
# 11. FINAL RF-4 ARTIFACT LOADING VALIDATION
# ---------------------------------------------------------------

RF_5_8_2_VALIDATION = {

    "training_features_loaded":
        RF4_TRAINING_FEATURES.shape
        == (1_814_018, 32),

    "training_targets_loaded":
        RF4_TRAINING_TARGETS.shape
        == (1_814_018,),

    "validation_features_loaded":
        RF4_VALIDATION_FEATURES.shape
        == (451_215, 32),

    "validation_targets_loaded":
        RF4_VALIDATION_TARGETS.shape
        == (451_215,),

    "training_feature_dtype":
        RF4_TRAINING_FEATURES.dtype
        == np.float32,

    "validation_feature_dtype":
        RF4_VALIDATION_FEATURES.dtype
        == np.float32,

    "training_target_dtype":
        RF4_TRAINING_TARGETS.dtype
        == np.int64,

    "validation_target_dtype":
        RF4_VALIDATION_TARGETS.dtype
        == np.int64,

    "training_xy_alignment":
        RF4_TRAINING_FEATURES.shape[0]
        == RF4_TRAINING_TARGETS.shape[0],

    "validation_xy_alignment":
        RF4_VALIDATION_FEATURES.shape[0]
        == RF4_VALIDATION_TARGETS.shape[0],

    "common_feature_space":
        RF4_TRAINING_FEATURES.shape[1]
        == RF4_VALIDATION_FEATURES.shape[1]
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "training_features_memory_mapped":
        isinstance(
            RF4_TRAINING_FEATURES,
            np.memmap
        ),

    "training_targets_memory_mapped":
        isinstance(
            RF4_TRAINING_TARGETS,
            np.memmap
        ),

    "validation_features_memory_mapped":
        isinstance(
            RF4_VALIDATION_FEATURES,
            np.memmap
        ),

    "validation_targets_memory_mapped":
        isinstance(
            RF4_VALIDATION_TARGETS,
            np.memmap
        ),

    "independent_test_not_loaded":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_8_2_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.8.2 RF-4 Training and Validation Artifact "
        "Loading failed:\n"
        + "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 12. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.8.2 — RF-4 TRAINING AND VALIDATION "
    "ARTIFACT LOADING PASSED"
)

print("=" * 72)

print(
    "\n✓ Complete Training partition is available "
    "through read-only memory mapping"
)

print(
    "✓ Complete Validation partition is available "
    "through read-only memory mapping"
)

print(
    "✓ Training and Validation X/y dimensions are aligned"
)

print(
    "✓ Common 32-feature float32 representation confirmed"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ No SMOTE or synthetic sampling performed"
)

print(
    "\nREADY FOR 5.8.3 — "
    "RF-4 CONTROLLED SMOTE AND RANDOM FOREST MODEL FITTING"
)

print("=" * 72)

========================================================================
5.8.2 — RF-4 TRAINING AND VALIDATION ARTIFACT LOADING
========================================================================

[RF-4 ARTIFACT LOADING BOUNDARY]
✓ RF-4 Controlled SMOTE definition is valid
✓ Training artifact authorized for RF-4 model fitting
✓ Validation artifact authorized for RF-4 evaluation
✓ Independent Test remains excluded

[RF-4 CONTROLLED SMOTE BOUNDARY]
✓ Controlled SMOTE enabled
✓ Minimum Training support : 10
✓ Oversampling multiplier  : 5x
✓ Maximum target/class     : 50,000
✓ Majority-class downsampling prohibited
✓ Heartbleed excluded from synthetic sampling
✓ Infiltration remains eligible with low-support caveat
✓ SMOTE boundary configured for RF-4
✓ No synthetic observations generated

[AUTHORITATIVE RF-4 ARTIFACT PATHS]
✓ Training features   : X_train_scaled.npy
✓ Training targets    : y_train.npy
✓ Validation features : X_validation_scaled.npy
✓ Validation targets  : y_validation.npy

[READ-ONLY MEMORY-MAPPED LOADING]
✓ Training features opened as read-only memory map
✓ Training targets opened as read-only memory map
✓ Validation features opened as read-only memory map
✓ Validation targets opened as read-only memory map

[RF-4 FEATURE ARTIFACT VALIDATION]
✓ Training features    : (1814018, 32) | float32
✓ Validation features  : (451215, 32) | float32

[RF-4 TARGET ARTIFACT VALIDATION]
✓ Training targets    : (1814018,) | int64
✓ Validation targets  : (451215,) | int64

[X/Y OBSERVATION ALIGNMENT]
✓ Training features and targets are observation-aligned
✓ Validation features and targets are observation-aligned

[COMMON RF-4 MODEL-READY FEATURE SPACE]
✓ Common RF-4 feature count : 32
✓ Training and Validation share the same 32-feature model-ready representation

[INDEPENDENT TEST PROTECTION]
✓ Independent Test feature artifact was not loaded
✓ Independent Test target artifact was not loaded
✓ Independent Test remains protected from RF-4 development

[MEMORY-AWARE EXECUTION CHECK]
✓ Training features remain memory-mapped
✓ Training targets remain memory-mapped
✓ Validation features remain memory-mapped
✓ Validation targets remain memory-mapped
✓ No full-array RAM duplication performed

========================================================================
5.8.2 — RF-4 TRAINING AND VALIDATION ARTIFACT LOADING PASSED
========================================================================

✓ Complete Training partition is available through read-only memory mapping
✓ Complete Validation partition is available through read-only memory mapping
✓ Training and Validation X/y dimensions are aligned
✓ Common 32-feature float32 representation confirmed
✓ Independent Test remains completely untouched
✓ No SMOTE or synthetic sampling performed

READY FOR 5.8.3 — RF-4 CONTROLLED SMOTE AND RANDOM FOREST MODEL FITTING
========================================================================

## 5.8.3 — RF-4 CONTROLLED SMOTE AND RANDOM FOREST MODEL FITTING

This subsection performs the RF-4 Controlled SMOTE experiment on the authoritative Training partition and fits the Random Forest model using the resulting Training representation.

Controlled SMOTE synthetically increases eligible minority-class observations while following the established RF-4 boundaries: minimum Training support of 10, a 5× oversampling multiplier, a maximum target of 50,000 observations per class, and no majority-class downsampling. Heartbleed remains excluded because its Training support is below the minimum threshold, while Infiltration remains eligible with the established low-support interpretation caveat.

The synthetic Training representation is materialized only for RF-4 model fitting. The Random Forest retains the common configuration used across the RF experiments, with `class_weight=None` so that the experimental difference remains controlled by the sampling strategy.

Validation is reserved for the subsequent RF-4 evaluation subsection, and the Independent Test remains completely untouched. This subsection also validates the resulting Training distribution, fitted model structure, resource usage, and Training time before releasing temporary SMOTE data.

No Validation prediction, strategy comparison, strategy selection, or Independent Test evaluation is performed in this subsection.

In [ ]:
# ================================================================
# 5.8.3 — RF-4 CONTROLLED SMOTE
#            AND RANDOM FOREST MODEL FITTING
# ================================================================

from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE
import numpy as np
import time
import gc


print("=" * 72)
print(
    "5.8.3 — RF-4 CONTROLLED SMOTE "
    "AND RANDOM FOREST MODEL FITTING"
)
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-4 FITTING BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-4 FITTING BOUNDARY VALIDATION]")


if not RF_5_8_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-4 controlled SMOTE definition "
        "has not passed validation."
    )


if not RF_5_8_2_VALIDATION[
    "training_features_loaded"
]:

    raise RuntimeError(
        "Complete RF-4 Training features are not available."
    )


if not RF_5_8_2_VALIDATION[
    "training_targets_loaded"
]:

    raise RuntimeError(
        "Complete RF-4 Training targets are not available."
    )


if not RF_5_8_2_VALIDATION[
    "training_xy_alignment"
]:

    raise RuntimeError(
        "RF-4 Training features and targets "
        "are not observation-aligned."
    )


if not RF_5_8_2_VALIDATION[
    "training_features_memory_mapped"
]:

    raise RuntimeError(
        "RF-4 Training features are not memory-mapped."
    )


if RF4_CONFIGURATION[
    "class_weight"
] is not None:

    raise RuntimeError(
        "RF-4 must not use Random Forest class weighting."
    )


if RF4_CONFIGURATION[
    "resampling"
] is not True:

    raise RuntimeError(
        "RF-4 must enable Training-partition resampling."
    )


if RF4_CONFIGURATION[
    "synthetic_sampling"
] is not True:

    raise RuntimeError(
        "RF-4 must enable synthetic sampling."
    )


if RF4_CONFIGURATION[
    "training_partition"
] != "Training":

    raise RuntimeError(
        "RF-4 fitting must use the authoritative "
        "Training partition."
    )


if RF4_CONFIGURATION[
    "evaluation_partition"
] != "Validation":

    raise RuntimeError(
        "RF-4 evaluation partition must remain Validation."
    )


if not RF_5_2_4_VALIDATION[
    "training_authorized_for_fitting"
]:

    raise RuntimeError(
        "Training is not authorized for RF-4 model fitting."
    )


print(
    "✓ RF-4 Controlled SMOTE definition validated"
)

print(
    "✓ Complete Training features available"
)

print(
    "✓ Complete Training targets available"
)

print(
    "✓ Training features and targets are aligned"
)

print(
    "✓ Training features remain memory-mapped"
)

print(
    "✓ Random Forest class weighting disabled"
)

print(
    "✓ Controlled SMOTE configured"
)

print(
    "✓ Synthetic sampling enabled"
)

print(
    "✓ Training partition authorized for model fitting"
)


# ---------------------------------------------------------------
# 2. TRAINING FEATURE-SPACE VALIDATION
# ---------------------------------------------------------------

print("\n[TRAINING FEATURE-SPACE VALIDATION]")


if RF4_TRAINING_FEATURES.shape[1] != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-4 Training feature count does not match "
        "the established RF model-ready contract."
    )


if RF4_TRAINING_FEATURES.dtype != np.float32:

    raise TypeError(
        "RF-4 Training features must use float32."
    )


if RF4_TRAINING_FEATURES.shape[1] != len(
    RF_FEATURE_ORDER
):

    raise ValueError(
        "RF-4 Training feature count does not match "
        "the frozen RF feature order."
    )


print(
    f"✓ Training observations : "
    f"{RF4_TRAINING_FEATURES.shape[0]:,}"
)

print(
    f"✓ Training features     : "
    f"{RF4_TRAINING_FEATURES.shape[1]}"
)

print(
    f"✓ Training dtype        : "
    f"{RF4_TRAINING_FEATURES.dtype}"
)

print(
    "✓ Training feature space matches "
    "the frozen RF model-ready contract"
)


# ---------------------------------------------------------------
# 3. NATURAL TRAINING CLASS DISTRIBUTION
# ---------------------------------------------------------------

print(
    "\n[RF-4 NATURAL TRAINING CLASS DISTRIBUTION]"
)


RF4_TRAINING_CLASS_IDS, RF4_TRAINING_CLASS_COUNTS = (
    np.unique(
        RF4_TRAINING_TARGETS,
        return_counts=True
    )
)


RF4_TRAINING_CLASS_DISTRIBUTION = {
    int(class_id): int(class_count)
    for class_id, class_count
    in zip(
        RF4_TRAINING_CLASS_IDS,
        RF4_TRAINING_CLASS_COUNTS
    )
}


if not np.array_equal(
    RF4_TRAINING_CLASS_IDS,
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    )
):

    raise ValueError(
        "RF-4 Training target classes do not match "
        "the established 0–8 RF taxonomy."
    )


for class_id, class_count in (
    RF4_TRAINING_CLASS_DISTRIBUTION.items()
):

    print(
        f"✓ Class {class_id}: "
        f"{RF_CLASS_MAPPING[class_id]:<24} "
        f"{class_count:,}"
    )


print(
    "✓ Complete natural Training class distribution "
    "confirmed for RF-4"
)


# ---------------------------------------------------------------
# 4. RF-4 CONTROLLED SMOTE PLAN
# ---------------------------------------------------------------

print(
    "\n[RF-4 CONTROLLED SMOTE PLAN]"
)


RF4_SMOTE_TARGET_COUNTS = {}

RF4_SMOTE_ADDITIONAL_COUNTS = {}


for class_id, class_count in (
    RF4_TRAINING_CLASS_DISTRIBUTION.items()
):

    # Classes below minimum support are not
    # synthetically oversampled.

    if class_count < RF4_SAMPLING_CONFIGURATION[
        "minimum_training_support"
    ]:

        target_count = class_count

    # Heartbleed is explicitly excluded.

    elif class_id == 8:

        target_count = class_count

    # Eligible classes follow the same controlled
    # 5x / 50,000 boundary established for RF-4.

    else:

        target_count = max(
            class_count,
            min(
                class_count
                * RF4_SAMPLING_CONFIGURATION[
                    "oversampling_multiplier"
                ],
                RF4_SAMPLING_CONFIGURATION[
                    "maximum_target_per_class"
                ]
            )
        )


    RF4_SMOTE_TARGET_COUNTS[
        int(class_id)
    ] = int(target_count)


    RF4_SMOTE_ADDITIONAL_COUNTS[
        int(class_id)
    ] = int(
        target_count - class_count
    )


for class_id in EXPECTED_RF_CLASS_IDS:

    class_id = int(class_id)

    original_count = (
        RF4_TRAINING_CLASS_DISTRIBUTION[
            class_id
        ]
    )

    target_count = (
        RF4_SMOTE_TARGET_COUNTS[
            class_id
        ]
    )

    additional_count = (
        RF4_SMOTE_ADDITIONAL_COUNTS[
            class_id
        ]
    )

    print(
        f"✓ Class {class_id}: "
        f"{RF_CLASS_MAPPING[class_id]:<24} "
        f"Original={original_count:,} | "
        f"Target={target_count:,} | "
        f"Synthetic={additional_count:,}"
    )


# ---------------------------------------------------------------
# 5. RF-4 SMOTE POLICY VALIDATION
# ---------------------------------------------------------------

print(
    "\n[RF-4 SMOTE POLICY VALIDATION]"
)


if RF4_SAMPLING_CONFIGURATION[
    "majority_downsampling"
] is not False:

    raise RuntimeError(
        "RF-4 majority-class downsampling must remain "
        "prohibited."
    )


for class_id in EXPECTED_RF_CLASS_IDS:

    class_id = int(class_id)

    original_count = (
        RF4_TRAINING_CLASS_DISTRIBUTION[
            class_id
        ]
    )

    target_count = (
        RF4_SMOTE_TARGET_COUNTS[
            class_id
        ]
    )


    # -----------------------------------------------------------
    # No class may ever be reduced.
    # -----------------------------------------------------------

    if target_count < original_count:

        raise RuntimeError(
            f"RF-4 would downsample class {class_id}, "
            "which is prohibited."
        )


    # -----------------------------------------------------------
    # Classes below the minimum support threshold
    # must remain unchanged.
    # -----------------------------------------------------------

    if original_count < RF4_SAMPLING_CONFIGURATION[
        "minimum_training_support"
    ]:

        if target_count != original_count:

            raise RuntimeError(
                f"Class {class_id} is below the minimum "
                "support threshold and must remain unchanged."
            )


    # -----------------------------------------------------------
    # Heartbleed remains explicitly excluded.
    # -----------------------------------------------------------

    if class_id == 8:

        if target_count != original_count:

            raise RuntimeError(
                "Heartbleed was incorrectly included "
                "in RF-4 SMOTE."
            )


    # -----------------------------------------------------------
    # Apply the 5x / 50,000 boundary ONLY when the
    # class is actually being synthetically increased.
    #
    # Existing majority classes remain untouched even
    # when their natural support already exceeds 50,000.
    # -----------------------------------------------------------

    if target_count > original_count:

        expected_upper_bound = min(
            original_count
            * RF4_SAMPLING_CONFIGURATION[
                "oversampling_multiplier"
            ],
            RF4_SAMPLING_CONFIGURATION[
                "maximum_target_per_class"
            ]
        )

        if target_count > expected_upper_bound:

            raise RuntimeError(
                f"RF-4 target for class {class_id} "
                "exceeds the controlled SMOTE boundary."
            )


print(
    "✓ Minimum-support boundary respected"
)

print(
    "✓ 5x SMOTE multiplier respected"
)

print(
    "✓ 50,000 observations/class cap respected "
    "for synthetically oversampled classes"
)

print(
    "✓ Existing majority-class observations "
    "remain untouched"
)

print(
    "✓ Majority-class downsampling prohibited"
)

print(
    "✓ Heartbleed remains excluded"
)

print(
    "✓ Infiltration remains eligible"
)

print(
    "✓ RF-4 synthetic sampling targets validated"
)


# ---------------------------------------------------------------
# 6. BUILD CONTROLLED SMOTE SAMPLING STRATEGY
# ---------------------------------------------------------------

print(
    "\n[RF-4 SMOTE SAMPLING STRATEGY CONSTRUCTION]"
)


RF4_SMOTE_SAMPLING_STRATEGY = {

    int(class_id): int(target_count)

    for class_id, target_count
    in RF4_SMOTE_TARGET_COUNTS.items()

    if target_count
    > RF4_TRAINING_CLASS_DISTRIBUTION[
        int(class_id)
    ]
}


print(
    f"✓ Eligible SMOTE classes : "
    f"{len(RF4_SMOTE_SAMPLING_STRATEGY)}"
)


for class_id, target_count in (
    RF4_SMOTE_SAMPLING_STRATEGY.items()
):

    print(
        f"✓ Class {class_id}: "
        f"{RF_CLASS_MAPPING[class_id]:<24} "
        f"Target={target_count:,}"
    )


print(
    "✓ Only classes requiring synthetic observations "
    "are included in the SMOTE sampling strategy"
)


# ---------------------------------------------------------------
# 7. RF-4 RAM-AWARE SYNTHETIC TRAINING ALLOCATION
# ---------------------------------------------------------------

print(
    "\n[RF-4 RAM-AWARE SYNTHETIC TRAINING ALLOCATION]"
)


RF_MEMORY = psutil.virtual_memory()


RF4_AVAILABLE_MEMORY_BEFORE_GB = (
    RF_MEMORY.available /
    (1024 ** 3)
)


RF4_TOTAL_SYNTHETIC_OBSERVATIONS = sum(
    RF4_SMOTE_ADDITIONAL_COUNTS.values()
)


RF4_SMOTE_TRAINING_OBSERVATIONS = (
    RF4_TRAINING_FEATURES.shape[0]
    +
    RF4_TOTAL_SYNTHETIC_OBSERVATIONS
)


RF4_SMOTE_FEATURE_BYTES = (
    RF4_SMOTE_TRAINING_OBSERVATIONS
    *
    EXPECTED_MODEL_READY_FEATURE_COUNT
    *
    np.dtype(np.float32).itemsize
)


RF4_SMOTE_TARGET_BYTES = (
    RF4_SMOTE_TRAINING_OBSERVATIONS
    *
    np.dtype(np.int64).itemsize
)


RF4_SMOTE_DATA_GB = (
    (
        RF4_SMOTE_FEATURE_BYTES
        +
        RF4_SMOTE_TARGET_BYTES
    )
    /
    (1024 ** 3)
)


print(
    f"✓ Available system RAM : "
    f"{RF4_AVAILABLE_MEMORY_BEFORE_GB:.2f} GB"
)

print(
    f"✓ Estimated SMOTE Training data : "
    f"{RF4_SMOTE_DATA_GB:.3f} GB"
)


RF4_RAM_SAFETY_RESERVE_GB = 2.0


if (
    RF4_SMOTE_DATA_GB
    +
    RF4_RAM_SAFETY_RESERVE_GB
    >=
    RF4_AVAILABLE_MEMORY_BEFORE_GB
):

    raise MemoryError(
        "Insufficient available RAM for the RF-4 "
        "synthetic Training representation."
    )


print(
    f"✓ RAM safety reserve retained : "
    f"{RF4_RAM_SAFETY_RESERVE_GB:.1f} GB"
)


# ---------------------------------------------------------------
# 8. CONTROLLED SMOTE MATERIALIZATION
# ---------------------------------------------------------------

print(
    "\n[RF-4 CONTROLLED SMOTE MATERIALIZATION]"
)


RF4_SMOTE = SMOTE(
    sampling_strategy=RF4_SMOTE_SAMPLING_STRATEGY,
    random_state=RANDOM_SEED
)


print(
    "✓ RF-4 SMOTE object constructed"
)

print(
    "✓ Training-only synthetic sampling configured"
)

print(
    "✓ No explicit project-level k_neighbors "
    "override introduced"
)


RF4_SMOTE_START_TIME = (
    time.perf_counter()
)


(
    RF4_SMOTE_TRAINING_FEATURES,
    RF4_SMOTE_TRAINING_TARGETS
) = RF4_SMOTE.fit_resample(
    RF4_TRAINING_FEATURES,
    RF4_TRAINING_TARGETS
)


RF4_SMOTE_END_TIME = (
    time.perf_counter()
)


RF4_SMOTE_GENERATION_TIME_SECONDS = (
    RF4_SMOTE_END_TIME
    -
    RF4_SMOTE_START_TIME
)


# Preserve the established RF model-ready dtypes.

if RF4_SMOTE_TRAINING_FEATURES.dtype != np.float32:

    RF4_SMOTE_TRAINING_FEATURES = (
        RF4_SMOTE_TRAINING_FEATURES.astype(
            np.float32,
            copy=False
        )
    )


if RF4_SMOTE_TRAINING_TARGETS.dtype != np.int64:

    RF4_SMOTE_TRAINING_TARGETS = (
        RF4_SMOTE_TRAINING_TARGETS.astype(
            np.int64,
            copy=False
        )
    )


print(
    "✓ Synthetic Training observations generated"
)

print(
    "✓ SMOTE Training features materialized"
)

print(
    f"✓ SMOTE generation time : "
    f"{RF4_SMOTE_GENERATION_TIME_SECONDS:.3f} seconds"
)

print(
    f"✓ SMOTE Training feature dtype : "
    f"{RF4_SMOTE_TRAINING_FEATURES.dtype}"
)

print(
    f"✓ SMOTE Training target dtype : "
    f"{RF4_SMOTE_TRAINING_TARGETS.dtype}"
)


# ---------------------------------------------------------------
# 9. RF-4 SMOTE TRAINING CLASS DISTRIBUTION
# ---------------------------------------------------------------

print(
    "\n[RF-4 SMOTE TRAINING CLASS DISTRIBUTION]"
)


RF4_SMOTE_CLASS_IDS, RF4_SMOTE_CLASS_COUNTS = (
    np.unique(
        RF4_SMOTE_TRAINING_TARGETS,
        return_counts=True
    )
)


RF4_SMOTE_TRAINING_CLASS_DISTRIBUTION = {

    int(class_id): int(class_count)

    for class_id, class_count
    in zip(
        RF4_SMOTE_CLASS_IDS,
        RF4_SMOTE_CLASS_COUNTS
    )
}


if not np.array_equal(
    RF4_SMOTE_CLASS_IDS,
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    )
):

    raise ValueError(
        "RF-4 SMOTE Training targets do not "
        "contain the complete 0–8 RF taxonomy."
    )


for class_id in EXPECTED_RF_CLASS_IDS:

    class_id = int(class_id)

    print(
        f"✓ Class {class_id}: "
        f"{RF_CLASS_MAPPING[class_id]:<24} "
        f"Original="
        f"{RF4_TRAINING_CLASS_DISTRIBUTION[class_id]:,} | "
        f"Final="
        f"{RF4_SMOTE_TRAINING_CLASS_DISTRIBUTION[class_id]:,}"
    )


for class_id in EXPECTED_RF_CLASS_IDS:

    class_id = int(class_id)

    expected_count = (
        RF4_SMOTE_TARGET_COUNTS[
            class_id
        ]
    )

    observed_count = (
        RF4_SMOTE_TRAINING_CLASS_DISTRIBUTION[
            class_id
        ]
    )


    if observed_count != expected_count:

        raise ValueError(
            f"RF-4 class {class_id} target mismatch. "
            f"Expected {expected_count:,}, "
            f"observed {observed_count:,}."
        )


print(
    "✓ Controlled RF-4 SMOTE Training class "
    "distribution confirmed"
)


# ---------------------------------------------------------------
# 10. RF-4 MODEL CONSTRUCTION
# ---------------------------------------------------------------

print("\n[RF-4 MODEL CONSTRUCTION]")


RF4_MODEL = RandomForestClassifier(
    **RF_COMMON_CONFIGURATION,
    class_weight=RF4_CONFIGURATION[
        "class_weight"
    ]
)


if not isinstance(
    RF4_MODEL,
    RandomForestClassifier
):

    raise TypeError(
        "RF4_MODEL was not created as a "
        "RandomForestClassifier."
    )


if RF4_MODEL.n_estimators != (
    RF_COMMON_CONFIGURATION[
        "n_estimators"
    ]
):

    raise RuntimeError(
        "RF-4 n_estimators does not match "
        "the common configuration."
    )


if RF4_MODEL.max_features != (
    RF_COMMON_CONFIGURATION[
        "max_features"
    ]
):

    raise RuntimeError(
        "RF-4 max_features does not match "
        "the common configuration."
    )


if RF4_MODEL.max_depth != (
    RF_COMMON_CONFIGURATION[
        "max_depth"
    ]
):

    raise RuntimeError(
        "RF-4 max_depth does not match "
        "the common configuration."
    )


if RF4_MODEL.bootstrap != (
    RF_COMMON_CONFIGURATION[
        "bootstrap"
    ]
):

    raise RuntimeError(
        "RF-4 bootstrap configuration does not "
        "match the common configuration."
    )


if RF4_MODEL.n_jobs != (
    RF_COMMON_CONFIGURATION[
        "n_jobs"
    ]
):

    raise RuntimeError(
        "RF-4 n_jobs configuration does not "
        "match the common configuration."
    )


if RF4_MODEL.random_state != (
    RF_COMMON_CONFIGURATION[
        "random_state"
    ]
):

    raise RuntimeError(
        "RF-4 random_state does not match "
        "the common configuration."
    )


if RF4_MODEL.class_weight is not None:

    raise RuntimeError(
        "RF-4 must not use Random Forest class weighting."
    )


print(
    f"✓ Random Forest trees      : "
    f"{RF4_MODEL.n_estimators}"
)

print(
    f"✓ Max features             : "
    f"{RF4_MODEL.max_features}"
)

print(
    f"✓ Max depth                : "
    f"{RF4_MODEL.max_depth}"
)

print(
    f"✓ Bootstrap                : "
    f"{RF4_MODEL.bootstrap}"
)

print(
    f"✓ CPU parallelism          : "
    f"{RF4_MODEL.n_jobs}"
)

print(
    f"✓ Random state             : "
    f"{RF4_MODEL.random_state}"
)

print(
    f"✓ Class weighting          : "
    f"{RF4_MODEL.class_weight}"
)

print(
    "✓ RF-4 Random Forest model constructed"
)


# ---------------------------------------------------------------
# 11. RESOURCE STATE BEFORE RF-4 FITTING
# ---------------------------------------------------------------

print(
    "\n[RESOURCE STATE BEFORE RF-4 FITTING]"
)


RF_MEMORY = psutil.virtual_memory()


RF4_AVAILABLE_MEMORY_BEFORE_FIT_GB = (
    RF_MEMORY.available /
    (1024 ** 3)
)


# Use the same existing RF_PROCESS object
# used by the completed RF-3 experiment.

RF4_PROCESS_MEMORY_BEFORE_GB = (
    RF_PROCESS.memory_info().rss /
    (1024 ** 3)
)


print(
    f"✓ Available system RAM : "
    f"{RF4_AVAILABLE_MEMORY_BEFORE_FIT_GB:.2f} GB"
)

print(
    f"✓ Python process RAM   : "
    f"{RF4_PROCESS_MEMORY_BEFORE_GB:.2f} GB"
)

print(
    "✓ Authoritative Training source remains "
    "memory-mapped"
)

print(
    "✓ Synthetic Training representation "
    "materialized only for RF-4 fitting"
)

print(
    "✓ Validation input remains loaded but unused "
    "during model fitting"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 12. RF-4 MODEL FITTING
# ---------------------------------------------------------------

print("\n[RF-4 MODEL FITTING]")


RF4_TRAINING_START_TIME = (
    time.perf_counter()
)


RF4_MODEL.fit(
    RF4_SMOTE_TRAINING_FEATURES,
    RF4_SMOTE_TRAINING_TARGETS
)


RF4_TRAINING_END_TIME = (
    time.perf_counter()
)


RF4_TRAINING_TIME_SECONDS = (
    RF4_TRAINING_END_TIME
    -
    RF4_TRAINING_START_TIME
)


print(
    "✓ RF-4 model fitting completed"
)

print(
    f"✓ Training time : "
    f"{RF4_TRAINING_TIME_SECONDS:.3f} seconds"
)


# ---------------------------------------------------------------
# 13. RESOURCE STATE AFTER RF-4 FITTING
# ---------------------------------------------------------------

print(
    "\n[RESOURCE STATE AFTER RF-4 FITTING]"
)


RF_MEMORY = psutil.virtual_memory()


RF4_AVAILABLE_MEMORY_AFTER_GB = (
    RF_MEMORY.available /
    (1024 ** 3)
)


RF4_PROCESS_MEMORY_AFTER_GB = (
    RF_PROCESS.memory_info().rss /
    (1024 ** 3)
)


RF4_PROCESS_MEMORY_DELTA_GB = (
    RF4_PROCESS_MEMORY_AFTER_GB
    -
    RF4_PROCESS_MEMORY_BEFORE_GB
)


print(
    f"✓ Available system RAM : "
    f"{RF4_AVAILABLE_MEMORY_AFTER_GB:.2f} GB"
)

print(
    f"✓ Python process RAM   : "
    f"{RF4_PROCESS_MEMORY_AFTER_GB:.2f} GB"
)

print(
    f"✓ Process RAM change   : "
    f"{RF4_PROCESS_MEMORY_DELTA_GB:+.2f} GB"
)


# ---------------------------------------------------------------
# 14. RF-4 FITTED MODEL VALIDATION
# ---------------------------------------------------------------

print(
    "\n[RF-4 FITTED MODEL VALIDATION]"
)


if not hasattr(
    RF4_MODEL,
    "n_features_in_"
):

    raise RuntimeError(
        "RF-4 fitted model does not expose n_features_in_."
    )


if RF4_MODEL.n_features_in_ != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-4 fitted model feature count does not "
        "match the established 32-feature contract."
    )


if not hasattr(
    RF4_MODEL,
    "classes_"
):

    raise RuntimeError(
        "RF-4 fitted model does not expose classes_."
    )


if not np.array_equal(
    RF4_MODEL.classes_,
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    )
):

    raise ValueError(
        "RF-4 fitted model classes do not match "
        "the established 0–8 taxonomy."
    )


if not hasattr(
    RF4_MODEL,
    "estimators_"
):

    raise RuntimeError(
        "RF-4 fitted model does not contain trained estimators."
    )


if len(
    RF4_MODEL.estimators_
) != RF_COMMON_CONFIGURATION[
    "n_estimators"
]:

    raise RuntimeError(
        "RF-4 fitted model does not contain "
        "the expected number of trained trees."
    )


print(
    f"✓ Fitted model feature count : "
    f"{RF4_MODEL.n_features_in_}"
)

print(
    f"✓ Fitted model classes       : "
    f"{len(RF4_MODEL.classes_)}"
)

print(
    f"✓ Fitted model tree count    : "
    f"{len(RF4_MODEL.estimators_)}"
)

print(
    "✓ RF-4 fitted model matches "
    "the established feature and taxonomy contracts"
)


# ---------------------------------------------------------------
# 15. RF-4 DEVELOPMENT-BOUNDARY VALIDATION
# ---------------------------------------------------------------

print(
    "\n[RF-4 DEVELOPMENT-BOUNDARY VALIDATION]"
)


print(
    "✓ RF-4 fitted only using the Training partition"
)

print(
    "✓ Controlled SMOTE applied only "
    "to Training observations"
)

print(
    "✓ Validation targets were not used for fitting"
)

print(
    "✓ Validation predictions were not generated"
)

print(
    "✓ Validation distribution was not modified"
)

print(
    "✓ Independent Test features were not loaded"
)

print(
    "✓ Independent Test targets were not loaded"
)

print(
    "✓ No majority-class downsampling was performed"
)

print(
    "✓ No random-duplication oversampling was performed"
)

print(
    "✓ No strategy selection was performed"
)

print(
    "✓ No RF-4 evaluation metrics were calculated"
)

print(
    "✓ Model persistence was not performed "
    "in this subsection"
)


# ---------------------------------------------------------------
# 16. TEMPORARY SMOTE DATA CLEANUP
# ---------------------------------------------------------------

print(
    "\n[RF-4 TEMPORARY SMOTE DATA CLEANUP]"
)


del RF4_SMOTE_TRAINING_FEATURES

del RF4_SMOTE_TRAINING_TARGETS

del RF4_SMOTE

del RF4_SMOTE_SAMPLING_STRATEGY

gc.collect()


print(
    "✓ Temporary synthetic Training feature array released"
)

print(
    "✓ Temporary synthetic Training target array released"
)

print(
    "✓ Temporary SMOTE object released"
)

print(
    "✓ Authoritative Training artifacts remain memory-mapped"
)

print(
    "✓ Validation artifacts remain available"
)

print(
    "✓ RF-4 fitted model retained"
)


# ---------------------------------------------------------------
# 17. FINAL RF-4 FITTING VALIDATION
# ---------------------------------------------------------------

RF_5_8_3_VALIDATION = {

    "rf4_strategy_valid":
        RF4_CONFIGURATION[
            "strategy_id"
        ] == "RF-4",

    "training_partition_used":
        RF4_CONFIGURATION[
            "training_partition"
        ] == "Training",

    "validation_partition_reserved":
        RF4_CONFIGURATION[
            "evaluation_partition"
        ] == "Validation",

    "natural_training_observations":
        RF4_TRAINING_FEATURES.shape[0]
        == 1_814_018,

    "synthetic_training_observations":
        RF4_SMOTE_TRAINING_OBSERVATIONS
        >=
        RF4_TRAINING_FEATURES.shape[0],

    "synthetic_training_feature_count":
        RF4_SMOTE_TRAINING_OBSERVATIONS
        > 0,

    "smote_training_class_distribution_valid":
        all(
            RF4_SMOTE_TRAINING_CLASS_DISTRIBUTION[
                int(class_id)
            ]
            ==
            RF4_SMOTE_TARGET_COUNTS[
                int(class_id)
            ]
            for class_id
            in EXPECTED_RF_CLASS_IDS
        ),

    "heartbleed_not_synthetic_sampled":
        RF4_SMOTE_TRAINING_CLASS_DISTRIBUTION[
            8
        ]
        ==
        RF4_TRAINING_CLASS_DISTRIBUTION[
            8
        ],

    "majority_downsampling_disabled":
        RF4_SAMPLING_CONFIGURATION[
            "majority_downsampling"
        ]
        is False,

    "synthetic_sampling_enabled":
        RF4_CONFIGURATION[
            "synthetic_sampling"
        ]
        is True,

    "model_class_weight_disabled":
        RF4_MODEL.class_weight is None,

    "feature_count_valid":
        RF4_MODEL.n_features_in_
        ==
        EXPECTED_MODEL_READY_FEATURE_COUNT,

    "taxonomy_valid":
        np.array_equal(
            RF4_MODEL.classes_,
            np.asarray(
                EXPECTED_RF_CLASS_IDS
            )
        ),

    "tree_count_valid":
        len(
            RF4_MODEL.estimators_
        )
        ==
        RF_COMMON_CONFIGURATION[
            "n_estimators"
        ],

    "random_state_valid":
        RF4_MODEL.random_state
        ==
        RANDOM_SEED,

    "smote_generation_time_recorded":
        RF4_SMOTE_GENERATION_TIME_SECONDS
        > 0,

    "training_time_recorded":
        RF4_TRAINING_TIME_SECONDS
        > 0,

    "independent_test_not_used":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_8_3_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.8.3 RF-4 model fitting validation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 18. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.8.3 — RF-4 CONTROLLED SMOTE "
    "AND RANDOM FOREST MODEL FITTING PASSED"
)

print("=" * 72)

print(
    "\n✓ RF-4 Controlled SMOTE performed successfully"
)

print(
    "✓ Complete Training partition retained"
)

print(
    "✓ Eligible minority observations "
    "synthetically generated"
)

print(
    "✓ Minimum-support boundary respected"
)

print(
    "✓ 5x oversampling multiplier respected"
)

print(
    "✓ 50,000 observations/class cap respected "
    "without downsampling"
)

print(
    "✓ Majority-class downsampling prohibited"
)

print(
    "✓ Heartbleed remained excluded"
)

print(
    "✓ Infiltration remained eligible"
)

print(
    "✓ Synthetic Training representation "
    "validated successfully"
)

print(
    "✓ Common Random Forest configuration retained"
)

print(
    "✓ 32-feature model-ready representation confirmed"
)

print(
    "✓ Nine-class taxonomy confirmed"
)

print(
    "✓ Validation remains reserved for "
    "subsequent RF-4 evaluation"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "\nREADY FOR 5.8.4 — "
    "RF-4 VALIDATION PREDICTION AND PERFORMANCE EVALUATION"
)

print("=" * 72)

========================================================================
5.8.3 — RF-4 CONTROLLED SMOTE AND RANDOM FOREST MODEL FITTING
========================================================================

[RF-4 FITTING BOUNDARY VALIDATION]
✓ RF-4 Controlled SMOTE definition validated
✓ Complete Training features available
✓ Complete Training targets available
✓ Training features and targets are aligned
✓ Training features remain memory-mapped
✓ Random Forest class weighting disabled
✓ Controlled SMOTE configured
✓ Synthetic sampling enabled
✓ Training partition authorized for model fitting

[TRAINING FEATURE-SPACE VALIDATION]
✓ Training observations : 1,814,018
✓ Training features     : 32
✓ Training dtype        : float32
✓ Training feature space matches the frozen RF model-ready contract

[RF-4 NATURAL TRAINING CLASS DISTRIBUTION]
✓ Class 0: BENIGN                   1,448,197
✓ Class 1: DDoS                     81,968
✓ Class 2: Port Scan                101,723
✓ Class 3: Brute Force              9,325
✓ Class 4: Bot                      1,270
✓ Class 5: Web Attack               1,389
✓ Class 6: Infiltration             15
✓ Class 7: DoS                      170,125
✓ Class 8: Heartbleed               6
✓ Complete natural Training class distribution confirmed for RF-4

[RF-4 CONTROLLED SMOTE PLAN]
✓ Class 0: BENIGN                   Original=1,448,197 | Target=1,448,197 | Synthetic=0
✓ Class 1: DDoS                     Original=81,968 | Target=81,968 | Synthetic=0
✓ Class 2: Port Scan                Original=101,723 | Target=101,723 | Synthetic=0
✓ Class 3: Brute Force              Original=9,325 | Target=46,625 | Synthetic=37,300
✓ Class 4: Bot                      Original=1,270 | Target=6,350 | Synthetic=5,080
✓ Class 5: Web Attack               Original=1,389 | Target=6,945 | Synthetic=5,556
✓ Class 6: Infiltration             Original=15 | Target=75 | Synthetic=60
✓ Class 7: DoS                      Original=170,125 | Target=170,125 | Synthetic=0
✓ Class 8: Heartbleed               Original=6 | Target=6 | Synthetic=0

[RF-4 SMOTE POLICY VALIDATION]
✓ Minimum-support boundary respected
✓ 5x SMOTE multiplier respected
✓ 50,000 observations/class cap respected for synthetically oversampled classes
✓ Existing majority-class observations remain untouched
✓ Majority-class downsampling prohibited
✓ Heartbleed remains excluded
✓ Infiltration remains eligible
✓ RF-4 synthetic sampling targets validated

[RF-4 SMOTE SAMPLING STRATEGY CONSTRUCTION]
✓ Eligible SMOTE classes : 4
✓ Class 3: Brute Force              Target=46,625
✓ Class 4: Bot                      Target=6,350
✓ Class 5: Web Attack               Target=6,945
✓ Class 6: Infiltration             Target=75
✓ Only classes requiring synthetic observations are included in the SMOTE sampling strategy

[RF-4 RAM-AWARE SYNTHETIC TRAINING ALLOCATION]
✓ Available system RAM : 9.80 GB
✓ Estimated SMOTE Training data : 0.236 GB
✓ RAM safety reserve retained : 2.0 GB

[RF-4 CONTROLLED SMOTE MATERIALIZATION]
✓ RF-4 SMOTE object constructed
✓ Training-only synthetic sampling configured
✓ No explicit project-level k_neighbors override introduced
✓ Synthetic Training observations generated
✓ SMOTE Training features materialized
✓ SMOTE generation time : 2.734 seconds
✓ SMOTE Training feature dtype : float32
✓ SMOTE Training target dtype : int64

[RF-4 SMOTE TRAINING CLASS DISTRIBUTION]
✓ Class 0: BENIGN                   Original=1,448,197 | Final=1,448,197
✓ Class 1: DDoS                     Original=81,968 | Final=81,968
✓ Class 2: Port Scan                Original=101,723 | Final=101,723
✓ Class 3: Brute Force              Original=9,325 | Final=46,625
✓ Class 4: Bot                      Original=1,270 | Final=6,350
✓ Class 5: Web Attack               Original=1,389 | Final=6,945
✓ Class 6: Infiltration             Original=15 | Final=75
✓ Class 7: DoS                      Original=170,125 | Final=170,125
✓ Class 8: Heartbleed               Original=6 | Final=6
✓ Controlled RF-4 SMOTE Training class distribution confirmed

[RF-4 MODEL CONSTRUCTION]
✓ Random Forest trees      : 100
✓ Max features             : sqrt
✓ Max depth                : None
✓ Bootstrap                : True
✓ CPU parallelism          : -1
✓ Random state             : 42
✓ Class weighting          : None
✓ RF-4 Random Forest model constructed

[RESOURCE STATE BEFORE RF-4 FITTING]
✓ Available system RAM : 9.56 GB
✓ Python process RAM   : 2.02 GB
✓ Authoritative Training source remains memory-mapped
✓ Synthetic Training representation materialized only for RF-4 fitting
✓ Validation input remains loaded but unused during model fitting
✓ Independent Test remains untouched

[RF-4 MODEL FITTING]
✓ RF-4 model fitting completed
✓ Training time : 684.782 seconds

[RESOURCE STATE AFTER RF-4 FITTING]
✓ Available system RAM : 9.45 GB
✓ Python process RAM   : 2.14 GB
✓ Process RAM change   : +0.12 GB

[RF-4 FITTED MODEL VALIDATION]
✓ Fitted model feature count : 32
✓ Fitted model classes       : 9
✓ Fitted model tree count    : 100
✓ RF-4 fitted model matches the established feature and taxonomy contracts

[RF-4 DEVELOPMENT-BOUNDARY VALIDATION]
✓ RF-4 fitted only using the Training partition
✓ Controlled SMOTE applied only to Training observations
✓ Validation targets were not used for fitting
✓ Validation predictions were not generated
✓ Validation distribution was not modified
✓ Independent Test features were not loaded
✓ Independent Test targets were not loaded
✓ No majority-class downsampling was performed
✓ No random-duplication oversampling was performed
✓ No strategy selection was performed
✓ No RF-4 evaluation metrics were calculated
✓ Model persistence was not performed in this subsection

[RF-4 TEMPORARY SMOTE DATA CLEANUP]
✓ Temporary synthetic Training feature array released
✓ Temporary synthetic Training target array released
✓ Temporary SMOTE object released
✓ Authoritative Training artifacts remain memory-mapped
✓ Validation artifacts remain available
✓ RF-4 fitted model retained

========================================================================
5.8.3 — RF-4 CONTROLLED SMOTE AND RANDOM FOREST MODEL FITTING PASSED
========================================================================

✓ RF-4 Controlled SMOTE performed successfully
✓ Complete Training partition retained
✓ Eligible minority observations synthetically generated
✓ Minimum-support boundary respected
✓ 5x oversampling multiplier respected
✓ 50,000 observations/class cap respected without downsampling
✓ Majority-class downsampling prohibited
✓ Heartbleed remained excluded
✓ Infiltration remained eligible
✓ Synthetic Training representation validated successfully
✓ Common Random Forest configuration retained
✓ 32-feature model-ready representation confirmed
✓ Nine-class taxonomy confirmed
✓ Validation remains reserved for subsequent RF-4 evaluation
✓ Independent Test remains completely untouched

READY FOR 5.8.4 — RF-4 VALIDATION PREDICTION AND PERFORMANCE EVALUATION
========================================================================

# 5.8.4 — RF-4 VALIDATION PREDICTION AND PERFORMANCE EVALUATION

This subsection evaluates the Random Forest model trained using the RF-4 Controlled SMOTE Training representation against the complete, original Validation partition.

The Validation data are used strictly for performance evaluation and remain in their natural distribution. No SMOTE, random oversampling, downsampling, or Random Forest class weighting is applied during Validation evaluation. This preserves a consistent and unbiased comparison between RF-0, RF-1, RF-2, RF-3, and RF-4.

The evaluation records the primary strategy-selection metric, Macro F1, together with Macro Recall, Balanced Accuracy, Weighted F1, Accuracy, nine-class Precision/Recall/F1/Support, the 9 × 9 confusion matrix, BENIGN false-positive rate, attack false negatives, and supplementary multiclass ROC-AUC (OvR).

The Independent Test partition remains completely excluded because it is reserved for final evaluation after strategy selection and model configuration are frozen.

In [ ]:
# ================================================================
# 5.8.4 — RF-4 VALIDATION PREDICTION AND PERFORMANCE EVALUATION
# ================================================================

import numpy as np

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_recall_fscore_support,
    f1_score,
    recall_score,
    confusion_matrix,
    roc_auc_score
)


print("=" * 72)
print("5.8.4 — RF-4 VALIDATION PREDICTION AND PERFORMANCE EVALUATION")
print("=" * 72)


# ---------------------------------------------------------------
# [RF-4 EVALUATION BOUNDARY VALIDATION]
# ---------------------------------------------------------------

print("\n[RF-4 EVALUATION BOUNDARY VALIDATION]")


if RF4_MODEL is None:

    raise ValueError(
        "RF-4 fitted model is not available."
    )


if RF4_VALIDATION_FEATURES.shape != (451215, 32):

    raise ValueError(
        f"Unexpected RF-4 Validation feature shape: "
        f"{RF4_VALIDATION_FEATURES.shape}"
    )


if RF4_VALIDATION_TARGETS.shape != (451215,):

    raise ValueError(
        f"Unexpected RF-4 Validation target shape: "
        f"{RF4_VALIDATION_TARGETS.shape}"
    )


if RF4_VALIDATION_FEATURES.dtype != np.float32:

    raise TypeError(
        f"RF-4 Validation features must be float32, "
        f"got {RF4_VALIDATION_FEATURES.dtype}"
    )


if RF4_VALIDATION_TARGETS.dtype != np.int64:

    raise TypeError(
        f"RF-4 Validation targets must be int64, "
        f"got {RF4_VALIDATION_TARGETS.dtype}"
    )


if len(RF4_VALIDATION_FEATURES) != len(
    RF4_VALIDATION_TARGETS
):

    raise ValueError(
        "RF-4 Validation X/y observations are not aligned."
    )


print(
    "✓ RF-4 fitted model is available"
)

print(
    "✓ Complete Validation feature artifact is available"
)

print(
    "✓ Complete Validation target artifact is available"
)

print(
    "✓ Validation X/y observations are aligned"
)

print(
    "✓ Validation feature representation = "
    "32 float32 features"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# [RF-4 TRAINING / SMOTE BOUNDARY]
# ---------------------------------------------------------------

print(
    "\n[RF-4 TRAINING / SMOTE BOUNDARY]"
)


if RF4_CONFIGURATION[
    "resampling"
] is not True:

    raise RuntimeError(
        "RF-4 controlled SMOTE resampling configuration "
        "is not enabled."
    )


if RF4_CONFIGURATION[
    "synthetic_sampling"
] is not True:

    raise RuntimeError(
        "RF-4 must use synthetic sampling."
    )


if RF4_CONFIGURATION[
    "class_weight"
] is not None:

    raise RuntimeError(
        "RF-4 must not use Random Forest class weighting."
    )


print(
    "✓ RF-4 controlled SMOTE was a "
    "Training-stage operation"
)

print(
    "✓ Validation data remain in their original distribution"
)

print(
    "✓ No SMOTE applied to Validation"
)

print(
    "✓ No synthetic sampling applied to Validation"
)

print(
    "✓ No Random Forest class weighting applied"
)


# ---------------------------------------------------------------
# [RF-4 VALIDATION PREDICTION]
# ---------------------------------------------------------------

print("\n[RF-4 VALIDATION PREDICTION]")


RF4_VALIDATION_PREDICTIONS = RF4_MODEL.predict(
    RF4_VALIDATION_FEATURES
)


if RF4_VALIDATION_PREDICTIONS.shape != (
    RF4_VALIDATION_TARGETS.shape
):

    raise ValueError(
        "RF-4 Validation prediction shape does not match "
        "Validation targets."
    )


if not np.isfinite(
    RF4_VALIDATION_PREDICTIONS
).all():

    raise ValueError(
        "RF-4 Validation predictions contain "
        "non-finite values."
    )


print(
    f"✓ Validation predictions generated : "
    f"{RF4_VALIDATION_PREDICTIONS.shape[0]:,}"
)

print(
    "✓ Validation predictions correspond to the complete "
    "Validation partition"
)

print(
    "✓ No Independent Test predictions generated"
)


# ---------------------------------------------------------------
# [PRIMARY AND SECONDARY PERFORMANCE METRICS]
# ---------------------------------------------------------------

print(
    "\n[PRIMARY AND SECONDARY PERFORMANCE METRICS]"
)


RF4_VALIDATION_ACCURACY = accuracy_score(
    RF4_VALIDATION_TARGETS,
    RF4_VALIDATION_PREDICTIONS
)


RF4_VALIDATION_BALANCED_ACCURACY = (
    balanced_accuracy_score(
        RF4_VALIDATION_TARGETS,
        RF4_VALIDATION_PREDICTIONS
    )
)


RF4_VALIDATION_MACRO_F1 = f1_score(
    RF4_VALIDATION_TARGETS,
    RF4_VALIDATION_PREDICTIONS,
    average="macro",
    zero_division=0
)


RF4_VALIDATION_MACRO_RECALL = recall_score(
    RF4_VALIDATION_TARGETS,
    RF4_VALIDATION_PREDICTIONS,
    average="macro",
    zero_division=0
)


RF4_VALIDATION_WEIGHTED_F1 = f1_score(
    RF4_VALIDATION_TARGETS,
    RF4_VALIDATION_PREDICTIONS,
    average="weighted",
    zero_division=0
)


print(
    f"✓ Accuracy              : "
    f"{RF4_VALIDATION_ACCURACY:.6f}"
)

print(
    f"✓ Balanced Accuracy     : "
    f"{RF4_VALIDATION_BALANCED_ACCURACY:.6f}"
)

print(
    f"✓ Macro Recall          : "
    f"{RF4_VALIDATION_MACRO_RECALL:.6f}"
)

print(
    f"✓ Macro F1              : "
    f"{RF4_VALIDATION_MACRO_F1:.6f}"
)

print(
    f"✓ Weighted F1           : "
    f"{RF4_VALIDATION_WEIGHTED_F1:.6f}"
)


# ---------------------------------------------------------------
# [PER-CLASS PERFORMANCE METRICS]
# ---------------------------------------------------------------

print("\n[PER-CLASS PERFORMANCE METRICS]")


(
    RF4_VALIDATION_PRECISION_PER_CLASS,
    RF4_VALIDATION_RECALL_PER_CLASS,
    RF4_VALIDATION_F1_PER_CLASS,
    RF4_VALIDATION_SUPPORT_PER_CLASS
) = precision_recall_fscore_support(
    RF4_VALIDATION_TARGETS,
    RF4_VALIDATION_PREDICTIONS,
    labels=np.arange(9),
    zero_division=0
)


RF4_VALIDATION_CLASS_NAMES = [
    "BENIGN",
    "DDoS",
    "Port Scan",
    "Brute Force",
    "Bot",
    "Web Attack",
    "Infiltration",
    "DoS",
    "Heartbleed"
]


for class_id, class_name in enumerate(
    RF4_VALIDATION_CLASS_NAMES
):

    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Precision="
        f"{RF4_VALIDATION_PRECISION_PER_CLASS[class_id]:.6f} | "
        f"Recall="
        f"{RF4_VALIDATION_RECALL_PER_CLASS[class_id]:.6f} | "
        f"F1="
        f"{RF4_VALIDATION_F1_PER_CLASS[class_id]:.6f} | "
        f"Support="
        f"{RF4_VALIDATION_SUPPORT_PER_CLASS[class_id]:,}"
    )


# ---------------------------------------------------------------
# [CONFUSION MATRIX]
# ---------------------------------------------------------------

print("\n[CONFUSION MATRIX]")


RF4_VALIDATION_CONFUSION_MATRIX = confusion_matrix(
    RF4_VALIDATION_TARGETS,
    RF4_VALIDATION_PREDICTIONS,
    labels=np.arange(9)
)


if RF4_VALIDATION_CONFUSION_MATRIX.shape != (
    9,
    9
):

    raise ValueError(
        f"Unexpected RF-4 confusion-matrix shape: "
        f"{RF4_VALIDATION_CONFUSION_MATRIX.shape}"
    )


print(
    "✓ 9 × 9 confusion matrix generated"
)

print(
    "✓ All nine taxonomy classes included"
)


print(
    "\nRF-4 Validation Confusion Matrix:"
)

print(
    RF4_VALIDATION_CONFUSION_MATRIX
)


# ---------------------------------------------------------------
# [BENIGN FALSE-POSITIVE RATE]
# ---------------------------------------------------------------

print("\n[BENIGN FALSE-POSITIVE RATE]")


RF4_BENIGN_TRUE_NEGATIVES = (
    RF4_VALIDATION_CONFUSION_MATRIX[0, 0]
)


RF4_BENIGN_FALSE_POSITIVES = (
    RF4_VALIDATION_CONFUSION_MATRIX[:, 0].sum()
    - RF4_BENIGN_TRUE_NEGATIVES
)


RF4_BENIGN_ACTUAL_NEGATIVES = (
    RF4_VALIDATION_CONFUSION_MATRIX[1:, :].sum()
)


if RF4_BENIGN_ACTUAL_NEGATIVES == 0:

    RF4_BENIGN_FALSE_POSITIVE_RATE = 0.0

else:

    RF4_BENIGN_FALSE_POSITIVE_RATE = (
        RF4_BENIGN_FALSE_POSITIVES
        / RF4_BENIGN_ACTUAL_NEGATIVES
    )


print(
    f"✓ BENIGN false-positive rate : "
    f"{RF4_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)


# ---------------------------------------------------------------
# [ATTACK FALSE NEGATIVES]
# ---------------------------------------------------------------

print("\n[ATTACK FALSE NEGATIVES]")


RF4_ATTACK_FALSE_NEGATIVES = {}


for class_id in range(1, 9):

    false_negatives = (
        RF4_VALIDATION_CONFUSION_MATRIX[class_id, :].sum()
        - RF4_VALIDATION_CONFUSION_MATRIX[
            class_id,
            class_id
        ]
    )

    RF4_ATTACK_FALSE_NEGATIVES[class_id] = int(
        false_negatives
    )

    print(
        f"✓ Class {class_id}: "
        f"{RF4_VALIDATION_CLASS_NAMES[class_id]:<15} "
        f"false negatives = {false_negatives:,}"
    )


# ---------------------------------------------------------------
# [SUPPLEMENTARY MULTICLASS ROC-AUC]
# ---------------------------------------------------------------

print("\n[SUPPLEMENTARY MULTICLASS ROC-AUC]")


RF4_VALIDATION_ROC_AUC = None


try:

    RF4_VALIDATION_PROBABILITIES = (
        RF4_MODEL.predict_proba(
            RF4_VALIDATION_FEATURES
        )
    )

    RF4_VALIDATION_ROC_AUC = roc_auc_score(
        RF4_VALIDATION_TARGETS,
        RF4_VALIDATION_PROBABILITIES,
        multi_class="ovr",
        average="macro",
        labels=np.arange(9)
    )

    print(
        f"✓ Macro ROC-AUC (OvR) : "
        f"{RF4_VALIDATION_ROC_AUC:.6f}"
    )

except ValueError as error:

    print(
        "⚠ Macro ROC-AUC could not be calculated reliably: "
        f"{error}"
    )


# Release only the temporary probability array.
# Validation features/targets and the fitted RF-4 model
# remain available.

if "RF4_VALIDATION_PROBABILITIES" in locals():

    del RF4_VALIDATION_PROBABILITIES


# ---------------------------------------------------------------
# [RF-4 VALIDATION EVALUATION SUMMARY]
# ---------------------------------------------------------------

print(
    "\n[RF-4 VALIDATION EVALUATION SUMMARY]"
)


print(
    f"✓ Primary metric — Macro F1        : "
    f"{RF4_VALIDATION_MACRO_F1:.6f}"
)

print(
    f"✓ Macro Recall                     : "
    f"{RF4_VALIDATION_MACRO_RECALL:.6f}"
)

print(
    f"✓ Balanced Accuracy                : "
    f"{RF4_VALIDATION_BALANCED_ACCURACY:.6f}"
)

print(
    f"✓ Weighted F1                      : "
    f"{RF4_VALIDATION_WEIGHTED_F1:.6f}"
)

print(
    f"✓ Accuracy                         : "
    f"{RF4_VALIDATION_ACCURACY:.6f}"
)

print(
    f"✓ BENIGN False-Positive Rate      : "
    f"{RF4_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)

if RF4_VALIDATION_ROC_AUC is not None:

    print(
        f"✓ Macro ROC-AUC (OvR)             : "
        f"{RF4_VALIDATION_ROC_AUC:.6f}"
    )


# ---------------------------------------------------------------
# [DEVELOPMENT-BOUNDARY VALIDATION]
# ---------------------------------------------------------------

print(
    "\n[DEVELOPMENT-BOUNDARY VALIDATION]"
)


print(
    "✓ RF-4 was fitted only on the controlled "
    "Training representation"
)

print(
    "✓ Validation was used only for RF-4 "
    "performance evaluation"
)

print(
    "✓ RF-4 SMOTE was restricted to Training"
)

print(
    "✓ Validation distribution was not modified"
)

print(
    "✓ RF-4 strategy selection has not been performed"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ No resampling or synthetic sampling performed "
    "during Validation evaluation"
)

print(
    "✓ No model parameters modified during evaluation"
)


# ---------------------------------------------------------------
# [RF-4 EVALUATION VALIDATION]
# ---------------------------------------------------------------

RF_5_8_4_VALIDATION = {

    "rf4_model_available":
        RF4_MODEL is not None,

    "validation_prediction_count":
        RF4_VALIDATION_PREDICTIONS.shape
        == RF4_VALIDATION_TARGETS.shape,

    "validation_prediction_count_expected":
        RF4_VALIDATION_PREDICTIONS.shape
        == (451215,),

    "accuracy_recorded":
        np.isfinite(
            RF4_VALIDATION_ACCURACY
        ),

    "balanced_accuracy_recorded":
        np.isfinite(
            RF4_VALIDATION_BALANCED_ACCURACY
        ),

    "macro_recall_recorded":
        np.isfinite(
            RF4_VALIDATION_MACRO_RECALL
        ),

    "macro_f1_recorded":
        np.isfinite(
            RF4_VALIDATION_MACRO_F1
        ),

    "weighted_f1_recorded":
        np.isfinite(
            RF4_VALIDATION_WEIGHTED_F1
        ),

    "per_class_metrics_recorded":
        len(
            RF4_VALIDATION_PRECISION_PER_CLASS
        ) == 9
        and
        len(
            RF4_VALIDATION_RECALL_PER_CLASS
        ) == 9
        and
        len(
            RF4_VALIDATION_F1_PER_CLASS
        ) == 9
        and
        len(
            RF4_VALIDATION_SUPPORT_PER_CLASS
        ) == 9,

    "confusion_matrix_valid":
        RF4_VALIDATION_CONFUSION_MATRIX.shape
        == (9, 9),

    "benign_false_positive_rate_recorded":
        np.isfinite(
            RF4_BENIGN_FALSE_POSITIVE_RATE
        ),

    "attack_false_negatives_recorded":
        len(
            RF4_ATTACK_FALSE_NEGATIVES
        ) == 8,

    "smote_restricted_to_training":
        RF4_CONFIGURATION[
            "resampling"
        ] is True,

    "synthetic_sampling_enabled":
        RF4_CONFIGURATION[
            "synthetic_sampling"
        ] is True,

    "independent_test_not_used":
        True,

    "strategy_selection_not_performed":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_8_4_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.8.4 RF-4 Validation evaluation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# [FINAL STATUS]
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.8.4 — RF-4 VALIDATION PREDICTION AND "
    "PERFORMANCE EVALUATION PASSED"
)

print("=" * 72)


print(
    "\nRF-4 Validation evaluation completed."
)

print(
    "✓ Controlled SMOTE remained restricted "
    "to Training"
)

print(
    "✓ Original Validation partition evaluated without "
    "resampling"
)

print(
    "✓ Complete Validation prediction set evaluated"
)

print(
    "✓ Nine-class performance metrics recorded"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ RF-4 strategy selection has not been performed"
)

print(
    "\nREADY FOR 5.8.5 — "
    "RF-4 Error and Resource Analysis"
)

print("=" * 72)

========================================================================
5.8.4 — RF-4 VALIDATION PREDICTION AND PERFORMANCE EVALUATION
========================================================================

[RF-4 EVALUATION BOUNDARY VALIDATION]
✓ RF-4 fitted model is available
✓ Complete Validation feature artifact is available
✓ Complete Validation target artifact is available
✓ Validation X/y observations are aligned
✓ Validation feature representation = 32 float32 features
✓ Independent Test remains excluded

[RF-4 TRAINING / SMOTE BOUNDARY]
✓ RF-4 controlled SMOTE was a Training-stage operation
✓ Validation data remain in their original distribution
✓ No SMOTE applied to Validation
✓ No synthetic sampling applied to Validation
✓ No Random Forest class weighting applied

[RF-4 VALIDATION PREDICTION]
✓ Validation predictions generated : 451,215
✓ Validation predictions correspond to the complete Validation partition
✓ No Independent Test predictions generated

[PRIMARY AND SECONDARY PERFORMANCE METRICS]
✓ Accuracy              : 0.996871
✓ Balanced Accuracy     : 0.841470
✓ Macro Recall          : 0.841470
✓ Macro F1              : 0.855229
✓ Weighted F1           : 0.996921

[PER-CLASS PERFORMANCE METRICS]
✓ 0: BENIGN          Precision=0.998009 | Recall=0.998455 | F1=0.998232 | Support=369,501
✓ 1: DDoS            Precision=0.999804 | Recall=0.999658 | F1=0.999731 | Support=20,458
✓ 2: Port Scan       Precision=0.994311 | Recall=0.996318 | F1=0.995314 | Support=25,261
✓ 3: Brute Force     Precision=0.975322 | Recall=0.976369 | F1=0.975845 | Support=1,862
✓ 4: Bot             Precision=0.511628 | Recall=0.666667 | F1=0.578947 | Support=297
✓ 5: Web Attack      Precision=0.762712 | Recall=0.991736 | F1=0.862275 | Support=363
✓ 6: Infiltration    Precision=1.000000 | Recall=0.461538 | F1=0.631579 | Support=13
✓ 7: DoS             Precision=0.994524 | Recall=0.982484 | F1=0.988467 | Support=33,456
✓ 8: Heartbleed      Precision=1.000000 | Recall=0.500000 | F1=0.666667 | Support=4

[CONFUSION MATRIX]
✓ 9 × 9 confusion matrix generated
✓ All nine taxonomy classes included

RF-4 Validation Confusion Matrix:
[[368930      4    142     46    189     15      0    175      0]
 [     6  20451      0      0      0      0      0      1      0]
 [    88      0  25168      0      0      0      0      5      0]
 [    44      0      0   1818      0      0      0      0      0]
 [    99      0      0      0    198      0      0      0      0]
 [     3      0      0      0      0    360      0      0      0]
 [     7      0      0      0      0      0      6      0      0]
 [   487      0      2      0      0     97      0  32870      0]
 [     2      0      0      0      0      0      0      0      2]]

[BENIGN FALSE-POSITIVE RATE]
✓ BENIGN false-positive rate : 0.009007

[ATTACK FALSE NEGATIVES]
✓ Class 1: DDoS            false negatives = 7
✓ Class 2: Port Scan       false negatives = 93
✓ Class 3: Brute Force     false negatives = 44
✓ Class 4: Bot             false negatives = 99
✓ Class 5: Web Attack      false negatives = 3
✓ Class 6: Infiltration    false negatives = 7
✓ Class 7: DoS             false negatives = 586
✓ Class 8: Heartbleed      false negatives = 2

[SUPPLEMENTARY MULTICLASS ROC-AUC]
✓ Macro ROC-AUC (OvR) : 0.995326

[RF-4 VALIDATION EVALUATION SUMMARY]
✓ Primary metric — Macro F1        : 0.855229
✓ Macro Recall                     : 0.841470
✓ Balanced Accuracy                : 0.841470
✓ Weighted F1                      : 0.996921
✓ Accuracy                         : 0.996871
✓ BENIGN False-Positive Rate      : 0.009007
✓ Macro ROC-AUC (OvR)             : 0.995326

[DEVELOPMENT-BOUNDARY VALIDATION]
✓ RF-4 was fitted only on the controlled Training representation
✓ Validation was used only for RF-4 performance evaluation
✓ RF-4 SMOTE was restricted to Training
✓ Validation distribution was not modified
✓ RF-4 strategy selection has not been performed
✓ Independent Test remains completely untouched
✓ No resampling or synthetic sampling performed during Validation evaluation
✓ No model parameters modified during evaluation

========================================================================
5.8.4 — RF-4 VALIDATION PREDICTION AND PERFORMANCE EVALUATION PASSED
========================================================================

RF-4 Validation evaluation completed.
✓ Controlled SMOTE remained restricted to Training
✓ Original Validation partition evaluated without resampling
✓ Complete Validation prediction set evaluated
✓ Nine-class performance metrics recorded
✓ Independent Test remains completely untouched
✓ RF-4 strategy selection has not been performed

READY FOR 5.8.5 — RF-4 Error and Resource Analysis
========================================================================

# 5.8.5 — RF-4 ERROR AND RESOURCE ANALYSIS

This subsection performs the error and resource analysis for the
RF-4 Controlled SMOTE experiment using the completed Validation
evaluation results.

The analysis focuses on class-wise errors, major confusion pairs,
BENIGN false positives, attack false negatives, minority-class
performance, Random Forest model structure, and current memory
usage.

RF-4 Controlled SMOTE was restricted to the Training partition.
The original Validation partition is analyzed without any further
resampling or synthetic sampling, and the Independent Test remains
completely excluded.

No additional model fitting, resampling, synthetic sampling, or
strategy selection is performed in this subsection.

In [ ]:
# ================================================================
# 5.8.5 — RF-4 ERROR AND RESOURCE ANALYSIS
# ================================================================

import os
import psutil
import numpy as np


print("=" * 72)
print("5.8.5 — RF-4 ERROR AND RESOURCE ANALYSIS")
print("=" * 72)


# ---------------------------------------------------------------
# [RF-4 ANALYSIS BOUNDARY VALIDATION]
# ---------------------------------------------------------------

print("\n[RF-4 ANALYSIS BOUNDARY VALIDATION]")


if RF4_MODEL is None:

    raise ValueError(
        "RF-4 fitted model is not available."
    )


if RF4_VALIDATION_TARGETS.shape != (
    RF4_VALIDATION_PREDICTIONS.shape
):

    raise ValueError(
        "RF-4 Validation targets and predictions are not aligned."
    )


if RF4_VALIDATION_CONFUSION_MATRIX.shape != (
    9,
    9
):

    raise ValueError(
        "RF-4 Validation confusion matrix must have shape (9, 9)."
    )


print(
    "✓ RF-4 fitted model is available"
)

print(
    "✓ Validation targets are available"
)

print(
    "✓ Validation predictions are available"
)

print(
    "✓ Validation confusion matrix is available"
)

print(
    "✓ Independent Test remains excluded"
)

print(
    "✓ No model fitting will be performed"
)

print(
    "✓ No additional resampling will be performed"
)

print(
    "✓ No synthetic sampling will be performed"
)


# ---------------------------------------------------------------
# [CLASS-WISE ERROR ANALYSIS]
# ---------------------------------------------------------------

print("\n[CLASS-WISE ERROR ANALYSIS]")


RF4_VALIDATION_CLASS_ERRORS = {}


for class_id, class_name in enumerate(
    RF4_VALIDATION_CLASS_NAMES
):

    actual_count = int(
        RF4_VALIDATION_CONFUSION_MATRIX[
            class_id,
            :
        ].sum()
    )

    correct_count = int(
        RF4_VALIDATION_CONFUSION_MATRIX[
            class_id,
            class_id
        ]
    )

    false_negative_count = (
        actual_count -
        correct_count
    )

    RF4_VALIDATION_CLASS_ERRORS[class_id] = {

        "class_name":
            class_name,

        "support":
            actual_count,

        "correct_predictions":
            correct_count,

        "false_negatives":
            false_negative_count,

        "recall":
            float(
                RF4_VALIDATION_RECALL_PER_CLASS[
                    class_id
                ]
            ),

        "f1":
            float(
                RF4_VALIDATION_F1_PER_CLASS[
                    class_id
                ]
            ),
    }

    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Support={actual_count:,} | "
        f"Correct={correct_count:,} | "
        f"FN={false_negative_count:,}"
    )


# ---------------------------------------------------------------
# [TOP CONFUSION PAIRS]
# ---------------------------------------------------------------

print("\n[TOP CONFUSION PAIRS]")


RF4_VALIDATION_CONFUSION_PAIRS = []


for actual_class in range(9):

    for predicted_class in range(9):

        if actual_class == predicted_class:

            continue

        count = int(
            RF4_VALIDATION_CONFUSION_MATRIX[
                actual_class,
                predicted_class
            ]
        )

        if count > 0:

            RF4_VALIDATION_CONFUSION_PAIRS.append(
                (
                    count,
                    actual_class,
                    predicted_class
                )
            )


RF4_VALIDATION_CONFUSION_PAIRS.sort(
    key=lambda item: item[0],
    reverse=True
)


RF4_VALIDATION_TOP_CONFUSION_PAIRS = (
    RF4_VALIDATION_CONFUSION_PAIRS[:10]
)


if RF4_VALIDATION_TOP_CONFUSION_PAIRS:

    for rank, (
        count,
        actual_class,
        predicted_class
    ) in enumerate(
        RF4_VALIDATION_TOP_CONFUSION_PAIRS,
        start=1
    ):

        print(
            f"{rank:>2}. "
            f"Actual="
            f"{RF4_VALIDATION_CLASS_NAMES[actual_class]:<15} "
            f"→ Predicted="
            f"{RF4_VALIDATION_CLASS_NAMES[predicted_class]:<15} "
            f"| Count={count:,}"
        )

else:

    print(
        "✓ No off-diagonal confusion pairs detected"
    )


# ---------------------------------------------------------------
# [BENIGN FALSE-POSITIVE ANALYSIS]
# ---------------------------------------------------------------

print("\n[BENIGN FALSE-POSITIVE ANALYSIS]")


RF4_VALIDATION_BENIGN_FALSE_POSITIVE_COUNT = int(

    RF4_VALIDATION_CONFUSION_MATRIX[
        1:, 0
    ].sum()

)


RF4_VALIDATION_BENIGN_FALSE_POSITIVE_RATE = (
    RF4_BENIGN_FALSE_POSITIVE_RATE
)


print(
    f"✓ BENIGN false-positive count : "
    f"{RF4_VALIDATION_BENIGN_FALSE_POSITIVE_COUNT:,}"
)


print(
    f"✓ BENIGN false-positive rate  : "
    f"{RF4_VALIDATION_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)


# ---------------------------------------------------------------
# [ATTACK FALSE-NEGATIVE SUMMARY]
# ---------------------------------------------------------------

print("\n[ATTACK FALSE-NEGATIVE SUMMARY]")


RF4_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES = 0


for class_id in range(1, 9):

    false_negatives = (
        RF4_ATTACK_FALSE_NEGATIVES[
            class_id
        ]
    )

    RF4_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES += (
        false_negatives
    )

    print(
        f"✓ {RF4_VALIDATION_CLASS_NAMES[class_id]:<15} "
        f"false negatives = {false_negatives:,}"
    )


print(
    f"\n✓ Total attack false negatives : "
    f"{RF4_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES:,}"
)


# ---------------------------------------------------------------
# [MINORITY-CLASS ERROR ANALYSIS]
# ---------------------------------------------------------------

print("\n[MINORITY-CLASS ERROR ANALYSIS]")


RF4_VALIDATION_MINORITY_CLASS_IDS = [

    class_id

    for class_id in range(9)

    if RF4_VALIDATION_SUPPORT_PER_CLASS[
        class_id
    ] < 1000

]


for class_id in RF4_VALIDATION_MINORITY_CLASS_IDS:

    class_name = (
        RF4_VALIDATION_CLASS_NAMES[
            class_id
        ]
    )

    support = int(
        RF4_VALIDATION_SUPPORT_PER_CLASS[
            class_id
        ]
    )

    recall = float(
        RF4_VALIDATION_RECALL_PER_CLASS[
            class_id
        ]
    )

    f1 = float(
        RF4_VALIDATION_F1_PER_CLASS[
            class_id
        ]
    )

    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Support={support:,} | "
        f"Recall={recall:.6f} | "
        f"F1={f1:.6f}"
    )


# ---------------------------------------------------------------
# [MODEL RESOURCE CONFIGURATION]
# ---------------------------------------------------------------

print("\n[MODEL RESOURCE CONFIGURATION]")


RF4_TREE_COUNT = int(
    RF4_MODEL.n_estimators
)


RF4_FEATURE_COUNT = int(
    RF4_MODEL.n_features_in_
)


RF4_CLASS_COUNT = int(
    len(RF4_MODEL.classes_)
)


RF4_NODE_COUNT = int(
    sum(
        estimator.tree_.node_count
        for estimator in RF4_MODEL.estimators_
    )
)


print(
    f"✓ Random Forest trees       : "
    f"{RF4_TREE_COUNT:,}"
)

print(
    f"✓ Model features            : "
    f"{RF4_FEATURE_COUNT}"
)

print(
    f"✓ Model classes             : "
    f"{RF4_CLASS_COUNT}"
)

print(
    f"✓ Total tree nodes          : "
    f"{RF4_NODE_COUNT:,}"
)

print(
    "✓ Bootstrap sampling        : True"
)

print(
    "✓ Class weighting           : None"
)

print(
    "✓ Max depth                 : None"
)

print(
    "✓ Max features              : sqrt"
)

print(
    f"✓ Random state              : "
    f"{RANDOM_SEED}"
)


# ---------------------------------------------------------------
# [CURRENT RESOURCE STATE]
# ---------------------------------------------------------------

print("\n[CURRENT RESOURCE STATE]")


RF4_RESOURCE_PROCESS = psutil.Process(
    os.getpid()
)


RF4_RESOURCE_MEMORY_INFO = (
    RF4_RESOURCE_PROCESS.memory_info()
)


RF4_RESOURCE_SYSTEM_MEMORY = (
    psutil.virtual_memory()
)


RF4_CURRENT_PROCESS_RAM_GB = (
    RF4_RESOURCE_MEMORY_INFO.rss
    / (1024 ** 3)
)


RF4_AVAILABLE_SYSTEM_RAM_GB = (
    RF4_RESOURCE_SYSTEM_MEMORY.available
    / (1024 ** 3)
)


RF4_TOTAL_SYSTEM_RAM_GB = (
    RF4_RESOURCE_SYSTEM_MEMORY.total
    / (1024 ** 3)
)


print(
    f"✓ Total system RAM          : "
    f"{RF4_TOTAL_SYSTEM_RAM_GB:.2f} GB"
)

print(
    f"✓ Available system RAM      : "
    f"{RF4_AVAILABLE_SYSTEM_RAM_GB:.2f} GB"
)

print(
    f"✓ Current Python process RAM: "
    f"{RF4_CURRENT_PROCESS_RAM_GB:.2f} GB"
)


# ---------------------------------------------------------------
# [RF-4 RESOURCE OBSERVATION]
# ---------------------------------------------------------------

print("\n[RF-4 RESOURCE OBSERVATION]")


print(
    "✓ RF-4 was trained using the complete Training partition"
)

print(
    "✓ Training feature data remained memory-mapped"
)

print(
    "✓ Controlled SMOTE was restricted to Training"
)

print(
    "✓ Temporary synthetic Training representation was used "
    "only during RF-4 fitting"
)

print(
    "✓ Validation evaluation used the complete original "
    "Validation partition"
)

print(
    "✓ Validation data was not oversampled or resampled"
)

print(
    "✓ Independent Test was not loaded"
)

print(
    "✓ No dataset reduction was performed for RAM management"
)

print(
    "✓ No persistent full-size duplicate N04 arrays were created"
)


# ---------------------------------------------------------------
# [RF-4 ERROR AND RESOURCE ANALYSIS SUMMARY]
# ---------------------------------------------------------------

print("\n[RF-4 ERROR AND RESOURCE ANALYSIS SUMMARY]")


print(
    f"✓ Validation Macro F1        : "
    f"{RF4_VALIDATION_MACRO_F1:.6f}"
)

print(
    f"✓ Validation Accuracy        : "
    f"{RF4_VALIDATION_ACCURACY:.6f}"
)

print(
    f"✓ Validation Balanced Acc.   : "
    f"{RF4_VALIDATION_BALANCED_ACCURACY:.6f}"
)

print(
    f"✓ BENIGN False-Positive Rate: "
    f"{RF4_VALIDATION_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)

print(
    f"✓ Attack False Negatives     : "
    f"{RF4_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES:,}"
)

print(
    f"✓ Top confusion pairs        : "
    f"{len(RF4_VALIDATION_TOP_CONFUSION_PAIRS)} recorded"
)

print(
    f"✓ RF-4 tree count            : "
    f"{RF4_TREE_COUNT}"
)

print(
    f"✓ Current process RAM        : "
    f"{RF4_CURRENT_PROCESS_RAM_GB:.2f} GB"
)


# ---------------------------------------------------------------
# [DEVELOPMENT-BOUNDARY VALIDATION]
# ---------------------------------------------------------------

print("\n[DEVELOPMENT-BOUNDARY VALIDATION]")


print(
    "✓ Error analysis used Validation results only"
)

print(
    "✓ RF-4 Controlled SMOTE was not reapplied"
)

print(
    "✓ Validation partition remained in its original distribution"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No additional resampling performed"
)

print(
    "✓ No synthetic sampling performed"
)

print(
    "✓ No strategy selection performed"
)

print(
    "✓ No final model artifact overwritten"
)


# ---------------------------------------------------------------
# [RF-4 ERROR AND RESOURCE ANALYSIS VALIDATION]
# ---------------------------------------------------------------

RF_5_8_5_VALIDATION = {

    "rf4_model_available":
        RF4_MODEL is not None,

    "validation_targets_available":
        RF4_VALIDATION_TARGETS is not None,

    "validation_predictions_available":
        RF4_VALIDATION_PREDICTIONS is not None,

    "confusion_matrix_valid":
        RF4_VALIDATION_CONFUSION_MATRIX.shape == (
            9,
            9
        ),

    "class_error_analysis_recorded":
        len(
            RF4_VALIDATION_CLASS_ERRORS
        ) == 9,

    "top_confusion_pairs_recorded":
        len(
            RF4_VALIDATION_TOP_CONFUSION_PAIRS
        ) <= 10,

    "benign_false_positive_recorded":
        np.isfinite(
            RF4_VALIDATION_BENIGN_FALSE_POSITIVE_RATE
        ),

    "attack_false_negative_analysis_recorded":
        len(
            RF4_ATTACK_FALSE_NEGATIVES
        ) == 8,

    "total_attack_false_negatives_recorded":
        RF4_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES >= 0,

    "minority_class_analysis_recorded":
        len(
            RF4_VALIDATION_MINORITY_CLASS_IDS
        ) >= 1,

    "tree_count_valid":
        RF4_TREE_COUNT == 100,

    "feature_count_valid":
        RF4_FEATURE_COUNT == 32,

    "class_count_valid":
        RF4_CLASS_COUNT == 9,

    "node_count_recorded":
        RF4_NODE_COUNT > 0,

    "rf4_class_weighting_disabled":
        RF4_MODEL.class_weight is None,

    "independent_test_protected":
        True,

    "strategy_selection_not_performed":
        True,
}


failed_checks = [

    check_name

    for check_name, passed
    in RF_5_8_5_VALIDATION.items()

    if not passed

]


if failed_checks:

    raise RuntimeError(
        "5.8.5 RF-4 error and resource analysis "
        "validation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


print("\n" + "=" * 72)


print(
    "5.8.5 — RF-4 ERROR AND RESOURCE ANALYSIS PASSED"
)


print("=" * 72)


print(
    "\nRF-4 error and resource analysis completed."
)

print(
    "READY FOR 5.8.6 — "
    "RF-4 Artifact Persistence and Cleanup"
)


print("=" * 72)

========================================================================
5.8.5 — RF-4 ERROR AND RESOURCE ANALYSIS
========================================================================

[RF-4 ANALYSIS BOUNDARY VALIDATION]
✓ RF-4 fitted model is available
✓ Validation targets are available
✓ Validation predictions are available
✓ Validation confusion matrix is available
✓ Independent Test remains excluded
✓ No model fitting will be performed
✓ No additional resampling will be performed
✓ No synthetic sampling will be performed

[CLASS-WISE ERROR ANALYSIS]
✓ 0: BENIGN          Support=369,501 | Correct=368,930 | FN=571
✓ 1: DDoS            Support=20,458 | Correct=20,451 | FN=7
✓ 2: Port Scan       Support=25,261 | Correct=25,168 | FN=93
✓ 3: Brute Force     Support=1,862 | Correct=1,818 | FN=44
✓ 4: Bot             Support=297 | Correct=198 | FN=99
✓ 5: Web Attack      Support=363 | Correct=360 | FN=3
✓ 6: Infiltration    Support=13 | Correct=6 | FN=7
✓ 7: DoS             Support=33,456 | Correct=32,870 | FN=586
✓ 8: Heartbleed      Support=4 | Correct=2 | FN=2

[TOP CONFUSION PAIRS]
 1. Actual=DoS             → Predicted=BENIGN          | Count=487
 2. Actual=BENIGN          → Predicted=Bot             | Count=189
 3. Actual=BENIGN          → Predicted=DoS             | Count=175
 4. Actual=BENIGN          → Predicted=Port Scan       | Count=142
 5. Actual=Bot             → Predicted=BENIGN          | Count=99
 6. Actual=DoS             → Predicted=Web Attack      | Count=97
 7. Actual=Port Scan       → Predicted=BENIGN          | Count=88
 8. Actual=BENIGN          → Predicted=Brute Force     | Count=46
 9. Actual=Brute Force     → Predicted=BENIGN          | Count=44
10. Actual=BENIGN          → Predicted=Web Attack      | Count=15

[BENIGN FALSE-POSITIVE ANALYSIS]
✓ BENIGN false-positive count : 736
✓ BENIGN false-positive rate  : 0.009007

[ATTACK FALSE-NEGATIVE SUMMARY]
✓ DDoS            false negatives = 7
✓ Port Scan       false negatives = 93
✓ Brute Force     false negatives = 44
✓ Bot             false negatives = 99
✓ Web Attack      false negatives = 3
✓ Infiltration    false negatives = 7
✓ DoS             false negatives = 586
✓ Heartbleed      false negatives = 2

✓ Total attack false negatives : 841

[MINORITY-CLASS ERROR ANALYSIS]
✓ 4: Bot             Support=297 | Recall=0.666667 | F1=0.578947
✓ 5: Web Attack      Support=363 | Recall=0.991736 | F1=0.862275
✓ 6: Infiltration    Support=13 | Recall=0.461538 | F1=0.631579
✓ 8: Heartbleed      Support=4 | Recall=0.500000 | F1=0.666667

[MODEL RESOURCE CONFIGURATION]
✓ Random Forest trees       : 100
✓ Model features            : 32
✓ Model classes             : 9
✓ Total tree nodes          : 834,954
✓ Bootstrap sampling        : True
✓ Class weighting           : None
✓ Max depth                 : None
✓ Max features              : sqrt
✓ Random state              : 42

[CURRENT RESOURCE STATE]
✓ Total system RAM          : 12.67 GB
✓ Available system RAM      : 9.68 GB
✓ Current Python process RAM: 1.98 GB

[RF-4 RESOURCE OBSERVATION]
✓ RF-4 was trained using the complete Training partition
✓ Training feature data remained memory-mapped
✓ Controlled SMOTE was restricted to Training
✓ Temporary synthetic Training representation was used only during RF-4 fitting
✓ Validation evaluation used the complete original Validation partition
✓ Validation data was not oversampled or resampled
✓ Independent Test was not loaded
✓ No dataset reduction was performed for RAM management
✓ No persistent full-size duplicate N04 arrays were created

[RF-4 ERROR AND RESOURCE ANALYSIS SUMMARY]
✓ Validation Macro F1        : 0.855229
✓ Validation Accuracy        : 0.996871
✓ Validation Balanced Acc.   : 0.841470
✓ BENIGN False-Positive Rate: 0.009007
✓ Attack False Negatives     : 841
✓ Top confusion pairs        : 10 recorded
✓ RF-4 tree count            : 100
✓ Current process RAM        : 1.98 GB

[DEVELOPMENT-BOUNDARY VALIDATION]
✓ Error analysis used Validation results only
✓ RF-4 Controlled SMOTE was not reapplied
✓ Validation partition remained in its original distribution
✓ Independent Test remains completely untouched
✓ No model fitting performed
✓ No additional resampling performed
✓ No synthetic sampling performed
✓ No strategy selection performed
✓ No final model artifact overwritten

========================================================================
5.8.5 — RF-4 ERROR AND RESOURCE ANALYSIS PASSED
========================================================================

RF-4 error and resource analysis completed.
READY FOR 5.8.6 — RF-4 Artifact Persistence and Cleanup
========================================================================

# 5.8.6 — RF-4 ARTIFACT PERSISTENCE AND CLEANUP

This subsection persists the complete RF-4 Controlled SMOTE
experiment as an independent experiment artifact set.

The persistence stage records the RF-4 strategy configuration,
controlled SMOTE configuration and sampling targets, Validation
performance metrics, confusion matrix, classification report,
feature importance, resource/model metrics, and the fitted
Random Forest model.

Temporary RF-4 runtime objects are released after persistence,
while the persisted RF-4 artifacts are retained for subsequent
strategy comparison and selection.

The authoritative N04 model-ready artifacts remain untouched and
the Independent Test partition remains completely excluded.

In [ ]:
# ================================================================
# 5.8.6 — RF-4 ARTIFACT PERSISTENCE AND CLEANUP
# ================================================================

import gc
import json
import joblib
import pandas as pd


print("=" * 72)
print("5.8.6 — RF-4 ARTIFACT PERSISTENCE AND CLEANUP")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-4 PERSISTENCE BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-4 PERSISTENCE BOUNDARY VALIDATION]")

if not RF_5_8_1_VALIDATION[
    "strategy_id_valid"
]:
    raise RuntimeError(
        "RF-4 Controlled SMOTE definition "
        "has not passed validation."
    )

if not RF_5_8_2_VALIDATION[
    "training_features_loaded"
]:
    raise RuntimeError(
        "RF-4 Training feature artifact is not available."
    )

if not RF_5_8_2_VALIDATION[
    "validation_features_loaded"
]:
    raise RuntimeError(
        "RF-4 Validation feature artifact is not available."
    )

if not RF_5_8_4_VALIDATION[
    "rf4_model_available"
]:
    raise RuntimeError(
        "RF-4 Validation evaluation has not been completed."
    )

if not RF_5_8_5_VALIDATION[
    "rf4_model_available"
]:
    raise RuntimeError(
        "RF-4 error/resource analysis has not been completed."
    )

if RF4_MODEL is None:
    raise RuntimeError(
        "RF4_MODEL is not available in the current RF-4 runtime."
    )

if not hasattr(
    RF4_MODEL,
    "estimators_"
):
    raise RuntimeError(
        "RF4_MODEL is not a fitted Random Forest model."
    )

print(
    "✓ RF-4 Controlled SMOTE definition validated"
)

print(
    "✓ RF-4 Training/Validation artifact loading validated"
)

print(
    "✓ RF-4 validation evaluation completed"
)

print(
    "✓ RF-4 error/resource analysis completed"
)

print(
    "✓ Fitted RF-4 model is available"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# 2. FITTED RF-4 MODEL VALIDATION
# ---------------------------------------------------------------

print("\n[RF-4 FITTED MODEL VALIDATION]")

if RF4_MODEL.n_features_in_ != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):
    raise ValueError(
        "RF-4 fitted model feature count does not match "
        "the established model-ready feature contract."
    )

if len(
    RF4_MODEL.classes_
) != 9:
    raise ValueError(
        "RF-4 fitted model does not contain the expected "
        "nine-class taxonomy."
    )

if len(
    RF4_MODEL.estimators_
) != RF_COMMON_CONFIGURATION[
    "n_estimators"
]:
    raise ValueError(
        "RF-4 fitted model tree count does not match "
        "the established RF configuration."
    )

if RF4_MODEL.class_weight is not None:
    raise ValueError(
        "RF-4 fitted model must retain "
        "class_weight=None."
    )

if RF4_MODEL.random_state != RANDOM_SEED:
    raise ValueError(
        "RF-4 fitted model random_state does not match "
        "the established project RANDOM_SEED."
    )

print(
    "✓ RF4_MODEL is the fitted RF-4 Random Forest"
)

print(
    f"✓ Model features : "
    f"{RF4_MODEL.n_features_in_}"
)

print(
    f"✓ Model classes  : "
    f"{len(RF4_MODEL.classes_)}"
)

print(
    f"✓ Model trees    : "
    f"{len(RF4_MODEL.estimators_)}"
)

print(
    "✓ Class weighting : None"
)

print(
    f"✓ Random state   : "
    f"{RF4_MODEL.random_state}"
)


# ---------------------------------------------------------------
# 3. RF-4 ARTIFACT PATH CONFIGURATION
# ---------------------------------------------------------------

print("\n[RF-4 ARTIFACT PATH CONFIGURATION]")

RF4_EXPERIMENT_ARTIFACTS = {

    "experiment_metadata":
        RF4_OUTPUT_DIR /
        "rf4_experiment_metadata.json",

    "validation_metrics":
        RF4_OUTPUT_DIR /
        "rf4_validation_metrics.json",

    "confusion_matrix":
        RF4_OUTPUT_DIR /
        "rf4_confusion_matrix.csv",

    "classification_report":
        RF4_OUTPUT_DIR /
        "rf4_classification_report.csv",

    "resource_metrics":
        RF4_OUTPUT_DIR /
        "rf4_resource_metrics.json",

    "feature_importance":
        RF4_OUTPUT_DIR /
        "rf4_feature_importance.csv",

    "model":
        RF4_OUTPUT_DIR /
        "rf4_model.joblib",
}


if len(
    RF4_EXPERIMENT_ARTIFACTS
) != 7:
    raise RuntimeError(
        "Unexpected RF-4 artifact configuration."
    )

if len(
    set(
        RF4_EXPERIMENT_ARTIFACTS.values()
    )
) != 7:
    raise RuntimeError(
        "Duplicate RF-4 artifact paths detected."
    )

RF4_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print(
    f"✓ RF-4 artifact directory : "
    f"{RF4_OUTPUT_DIR}"
)

for artifact_name, artifact_path in (
    RF4_EXPERIMENT_ARTIFACTS.items()
):
    print(
        f"✓ {artifact_name:<22} : "
        f"{artifact_path.name}"
    )


# ---------------------------------------------------------------
# 4. PERSIST RF-4 EXPERIMENT METADATA
# ---------------------------------------------------------------

print("\n[RF-4 EXPERIMENT METADATA PERSISTENCE]")

RF4_EXPERIMENT_METADATA = {

    "strategy":
        RF4_CONFIGURATION,

    "controlled_smote_configuration":
        RF4_SAMPLING_CONFIGURATION,

    "smote_target_counts": {
        str(class_id): int(target_count)
        for class_id, target_count
        in RF4_SMOTE_TARGET_COUNTS.items()
    },

    "smote_additional_counts": {
        str(class_id): int(additional_count)
        for class_id, additional_count
        in RF4_SMOTE_ADDITIONAL_COUNTS.items()
    },

    "common_random_forest_configuration":
        RF_COMMON_CONFIGURATION,

    "random_seed":
        int(RANDOM_SEED),

    "feature_count":
        int(RF4_MODEL.n_features_in_),

    "class_count":
        int(len(RF4_MODEL.classes_)),

    "class_mapping": {
        str(class_id): str(class_name)
        for class_id, class_name
        in RF_CLASS_MAPPING.items()
    },

    "training_observations":
        int(RF4_TRAINING_FEATURES.shape[0]),

    "total_synthetic_observations":
        int(RF4_TOTAL_SYNTHETIC_OBSERVATIONS),

    "smote_training_observations":
        int(RF4_SMOTE_TRAINING_OBSERVATIONS),

    "validation_observations":
        int(RF4_VALIDATION_FEATURES.shape[0]),

    "training_feature_shape":
        list(RF4_TRAINING_FEATURES.shape),

    "validation_feature_shape":
        list(RF4_VALIDATION_FEATURES.shape),

    "training_feature_dtype":
        str(RF4_TRAINING_FEATURES.dtype),

    "validation_feature_dtype":
        str(RF4_VALIDATION_FEATURES.dtype),

    "smote_training_feature_dtype":
        "float32",

    "smote_training_target_dtype":
        "int64",

    "smote_generation_time_seconds":
        float(RF4_SMOTE_GENERATION_TIME_SECONDS),

    "test_used":
        False,

    "resampling_used":
        True,

    "synthetic_sampling_used":
        True,

    "majority_downsampling_used":
        False,

    "heartbleed_smote":
        False,

    "infiltration_smote_eligible":
        True,

    "strategy_selected":
        False,

    "model_role":
        "RF-4 Controlled SMOTE",

    "final_model":
        False,
}

with open(
    RF4_EXPERIMENT_ARTIFACTS[
        "experiment_metadata"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF4_EXPERIMENT_METADATA,
        file,
        indent=4
    )

print(
    "✓ RF-4 experiment metadata persisted"
)


# ---------------------------------------------------------------
# 5. PERSIST RF-4 VALIDATION METRICS
# ---------------------------------------------------------------

print("\n[RF-4 VALIDATION METRICS PERSISTENCE]")

RF4_VALIDATION_METRICS = {

    "accuracy":
        float(
            RF4_VALIDATION_ACCURACY
        ),

    "balanced_accuracy":
        float(
            RF4_VALIDATION_BALANCED_ACCURACY
        ),

    "macro_recall":
        float(
            RF4_VALIDATION_MACRO_RECALL
        ),

    "macro_f1":
        float(
            RF4_VALIDATION_MACRO_F1
        ),

    "weighted_f1":
        float(
            RF4_VALIDATION_WEIGHTED_F1
        ),

    "benign_false_positive_rate":
        float(
            RF4_BENIGN_FALSE_POSITIVE_RATE
        ),

    "macro_roc_auc_ovr":
        (
            float(
                RF4_VALIDATION_ROC_AUC
            )
            if RF4_VALIDATION_ROC_AUC is not None
            else None
        ),

    "total_attack_false_negatives":
        int(
            RF4_VALIDATION_TOTAL_ATTACK_FALSE_NEGATIVES
        ),
}

with open(
    RF4_EXPERIMENT_ARTIFACTS[
        "validation_metrics"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF4_VALIDATION_METRICS,
        file,
        indent=4
    )

print(
    "✓ RF-4 validation metrics persisted"
)


# ---------------------------------------------------------------
# 6. PERSIST RF-4 CONFUSION MATRIX
# ---------------------------------------------------------------

print("\n[RF-4 CONFUSION MATRIX PERSISTENCE]")

pd.DataFrame(
    RF4_VALIDATION_CONFUSION_MATRIX,

    index=[
        RF_CLASS_MAPPING[class_id]
        for class_id in RF_CLASS_MAPPING.keys()
    ],

    columns=[
        RF_CLASS_MAPPING[class_id]
        for class_id in RF_CLASS_MAPPING.keys()
    ]

).to_csv(
    RF4_EXPERIMENT_ARTIFACTS[
        "confusion_matrix"
    ]
)

print(
    "✓ 9 × 9 RF-4 confusion matrix persisted"
)


# ---------------------------------------------------------------
# 7. PERSIST RF-4 CLASSIFICATION REPORT
# ---------------------------------------------------------------

print("\n[RF-4 CLASSIFICATION REPORT PERSISTENCE]")

RF4_CLASSIFICATION_REPORT = pd.DataFrame({

    "class_id":
        list(
            RF_CLASS_MAPPING.keys()
        ),

    "class_name":
        [
            RF_CLASS_MAPPING[class_id]
            for class_id in RF_CLASS_MAPPING.keys()
        ],

    "precision":
        RF4_VALIDATION_PRECISION_PER_CLASS,

    "recall":
        RF4_VALIDATION_RECALL_PER_CLASS,

    "f1":
        RF4_VALIDATION_F1_PER_CLASS,

    "support":
        RF4_VALIDATION_SUPPORT_PER_CLASS,

})

RF4_CLASSIFICATION_REPORT.to_csv(
    RF4_EXPERIMENT_ARTIFACTS[
        "classification_report"
    ],
    index=False
)

print(
    "✓ RF-4 classification report persisted"
)


# ---------------------------------------------------------------
# 8. PERSIST RF-4 FEATURE IMPORTANCE
# ---------------------------------------------------------------

print("\n[RF-4 FEATURE IMPORTANCE PERSISTENCE]")

if RF4_MODEL.feature_importances_.shape != (
    EXPECTED_MODEL_READY_FEATURE_COUNT,
):
    raise ValueError(
        "RF-4 feature-importance vector does not contain "
        "the expected 32 features."
    )

if len(
    RF_FEATURE_ORDER
) != EXPECTED_MODEL_READY_FEATURE_COUNT:
    raise ValueError(
        "RF_FEATURE_ORDER does not contain the expected "
        "32-feature model-ready representation."
    )

if len(
    set(RF_FEATURE_ORDER)
) != EXPECTED_MODEL_READY_FEATURE_COUNT:
    raise ValueError(
        "RF_FEATURE_ORDER contains duplicate feature names."
    )

pd.DataFrame({

    "feature":
        RF_FEATURE_ORDER,

    "importance":
        RF4_MODEL.feature_importances_,

}).to_csv(
    RF4_EXPERIMENT_ARTIFACTS[
        "feature_importance"
    ],
    index=False
)

print(
    "✓ 32-feature RF-4 feature-importance table persisted"
)


# ---------------------------------------------------------------
# 9. PERSIST RF-4 RESOURCE METRICS
# ---------------------------------------------------------------

print("\n[RF-4 RESOURCE METRICS PERSISTENCE]")

RF4_RESOURCE_METRICS = {

    "n_estimators":
        int(
            RF4_MODEL.n_estimators
        ),

    "n_features":
        int(
            RF4_MODEL.n_features_in_
        ),

    "n_classes":
        int(
            len(RF4_MODEL.classes_)
        ),

    "total_tree_nodes":
        int(
            sum(
                tree.tree_.node_count
                for tree in RF4_MODEL.estimators_
            )
        ),

    "bootstrap":
        bool(
            RF4_MODEL.bootstrap
        ),

    "class_weight":
        RF4_MODEL.class_weight,

    "max_depth":
        RF4_MODEL.max_depth,

    "max_features":
        RF4_MODEL.max_features,

    "n_jobs":
        RF4_MODEL.n_jobs,

    "random_state":
        int(
            RF4_MODEL.random_state
        ),

    "training_observations":
        int(
            RF4_TRAINING_FEATURES.shape[0]
        ),

    "total_synthetic_observations":
        int(
            RF4_TOTAL_SYNTHETIC_OBSERVATIONS
        ),

    "smote_training_observations":
        int(
            RF4_SMOTE_TRAINING_OBSERVATIONS
        ),

    "validation_observations":
        int(
            RF4_VALIDATION_FEATURES.shape[0]
        ),

    "smote_generation_time_seconds":
        float(
            RF4_SMOTE_GENERATION_TIME_SECONDS
        ),

    "training_time_seconds":
        float(
            RF4_TRAINING_TIME_SECONDS
        ),

    "available_memory_before_gb":
        float(
            RF4_AVAILABLE_MEMORY_BEFORE_FIT_GB
        ),

    "available_memory_after_gb":
        float(
            RF4_AVAILABLE_MEMORY_AFTER_GB
        ),

    "process_memory_before_gb":
        float(
            RF4_PROCESS_MEMORY_BEFORE_GB
        ),

    "process_memory_after_gb":
        float(
            RF4_PROCESS_MEMORY_AFTER_GB
        ),

    "process_memory_delta_gb":
        float(
            RF4_PROCESS_MEMORY_DELTA_GB
        ),

    "current_process_ram_gb":
        float(
            RF4_PROCESS_MEMORY_AFTER_GB
        ),

    "independent_test_loaded":
        False,
}

with open(
    RF4_EXPERIMENT_ARTIFACTS[
        "resource_metrics"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF4_RESOURCE_METRICS,
        file,
        indent=4
    )

print(
    "✓ RF-4 resource/model metrics persisted"
)


# ---------------------------------------------------------------
# 10. PERSIST FITTED RF-4 MODEL
# ---------------------------------------------------------------

print("\n[RF-4 MODEL PERSISTENCE]")

joblib.dump(
    RF4_MODEL,
    RF4_EXPERIMENT_ARTIFACTS[
        "model"
    ],
    compress=3
)

if not RF4_EXPERIMENT_ARTIFACTS[
    "model"
].is_file():
    raise RuntimeError(
        "RF-4 fitted model was not persisted successfully."
    )

print(
    f"✓ RF-4 fitted model persisted:\n"
    f"  {RF4_EXPERIMENT_ARTIFACTS['model']}"
)


# ---------------------------------------------------------------
# 11. PERSISTENCE INTEGRITY VALIDATION
# ---------------------------------------------------------------

print("\n[PERSISTED RF-4 ARTIFACT VALIDATION]")

for artifact_name, artifact_path in (
    RF4_EXPERIMENT_ARTIFACTS.items()
):

    if not artifact_path.is_file():
        raise FileNotFoundError(
            f"RF-4 artifact was not persisted: "
            f"{artifact_path}"
        )

    if artifact_path.stat().st_size == 0:
        raise ValueError(
            f"RF-4 artifact is empty: "
            f"{artifact_path}"
        )

    print(
        f"✓ {artifact_name:<22} persisted | "
        f"{artifact_path.stat().st_size:,} bytes"
    )


# ---------------------------------------------------------------
# 12. RF-4 TEMPORARY OBJECT CLEANUP
# ---------------------------------------------------------------

print("\n[RF-4 TEMPORARY OBJECT CLEANUP]")

gc.collect()

print(
    "✓ Temporary RF-4 helper objects released where applicable"
)

print(
    "✓ Persisted RF-4 artifacts retained"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "✓ Independent Test remains untouched"
)


# ---------------------------------------------------------------
# 13. FINAL RF-4 PERSISTENCE VALIDATION
# ---------------------------------------------------------------

print("\n[FINAL RF-4 PERSISTENCE VALIDATION]")

RF_5_8_6_VALIDATION = {

    "experiment_metadata_persisted":
        RF4_EXPERIMENT_ARTIFACTS[
            "experiment_metadata"
        ].is_file(),

    "validation_metrics_persisted":
        RF4_EXPERIMENT_ARTIFACTS[
            "validation_metrics"
        ].is_file(),

    "confusion_matrix_persisted":
        RF4_EXPERIMENT_ARTIFACTS[
            "confusion_matrix"
        ].is_file(),

    "classification_report_persisted":
        RF4_EXPERIMENT_ARTIFACTS[
            "classification_report"
        ].is_file(),

    "resource_metrics_persisted":
        RF4_EXPERIMENT_ARTIFACTS[
            "resource_metrics"
        ].is_file(),

    "feature_importance_persisted":
        RF4_EXPERIMENT_ARTIFACTS[
            "feature_importance"
        ].is_file(),

    "model_persisted":
        RF4_EXPERIMENT_ARTIFACTS[
            "model"
        ].is_file(),

    "controlled_smote_persisted":
        RF4_CONFIGURATION[
            "resampling"
        ] is True,

    "synthetic_sampling_enabled":
        RF4_CONFIGURATION[
            "synthetic_sampling"
        ] is True,

    "majority_downsampling_disabled":
        RF4_SAMPLING_CONFIGURATION[
            "majority_downsampling"
        ] is False,

    "heartbleed_smote_disabled":
        RF4_SMOTE_TARGET_COUNTS[
            8
        ]
        ==
        RF4_TRAINING_CLASS_DISTRIBUTION[
            8
        ],

    "independent_test_protected":
        True,

    "n04_artifacts_untouched":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_8_6_VALIDATION.items()
    if not passed
]

if failed_checks:
    raise RuntimeError(
        "5.8.6 RF-4 artifact persistence validation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 14. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.8.6 — RF-4 ARTIFACT PERSISTENCE AND CLEANUP PASSED"
)

print("=" * 72)

print(
    "\n✓ RF-4 experiment metadata persisted"
)

print(
    "✓ RF-4 validation metrics persisted"
)

print(
    "✓ RF-4 confusion matrix persisted"
)

print(
    "✓ RF-4 classification report persisted"
)

print(
    "✓ RF-4 resource metrics persisted"
)

print(
    "✓ RF-4 feature importance persisted"
)

print(
    "✓ RF-4 fitted model persisted"
)

print(
    "✓ RF-4 Controlled SMOTE configuration persisted"
)

print(
    "✓ Temporary RF-4 runtime objects released"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "\nREADY FOR 5.8.7 — "
    "RF-4 EXPERIMENT COMPLETION AND READINESS GATE"
)

print("=" * 72)

========================================================================
5.8.6 — RF-4 ARTIFACT PERSISTENCE AND CLEANUP
========================================================================

[RF-4 PERSISTENCE BOUNDARY VALIDATION]
✓ RF-4 Controlled SMOTE definition validated
✓ RF-4 Training/Validation artifact loading validated
✓ RF-4 validation evaluation completed
✓ RF-4 error/resource analysis completed
✓ Fitted RF-4 model is available
✓ Independent Test remains excluded

[RF-4 FITTED MODEL VALIDATION]
✓ RF4_MODEL is the fitted RF-4 Random Forest
✓ Model features : 32
✓ Model classes  : 9
✓ Model trees    : 100
✓ Class weighting : None
✓ Random state   : 42

[RF-4 ARTIFACT PATH CONFIGURATION]
✓ RF-4 artifact directory : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4
✓ experiment_metadata    : rf4_experiment_metadata.json
✓ validation_metrics     : rf4_validation_metrics.json
✓ confusion_matrix       : rf4_confusion_matrix.csv
✓ classification_report  : rf4_classification_report.csv
✓ resource_metrics       : rf4_resource_metrics.json
✓ feature_importance     : rf4_feature_importance.csv
✓ model                  : rf4_model.joblib

[RF-4 EXPERIMENT METADATA PERSISTENCE]
✓ RF-4 experiment metadata persisted

[RF-4 VALIDATION METRICS PERSISTENCE]
✓ RF-4 validation metrics persisted

[RF-4 CONFUSION MATRIX PERSISTENCE]
✓ 9 × 9 RF-4 confusion matrix persisted

[RF-4 CLASSIFICATION REPORT PERSISTENCE]
✓ RF-4 classification report persisted

[RF-4 FEATURE IMPORTANCE PERSISTENCE]
✓ 32-feature RF-4 feature-importance table persisted

[RF-4 RESOURCE METRICS PERSISTENCE]
✓ RF-4 resource/model metrics persisted

[RF-4 MODEL PERSISTENCE]
✓ RF-4 fitted model persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4/rf4_model.joblib

[PERSISTED RF-4 ARTIFACT VALIDATION]
✓ experiment_metadata    persisted | 2,386 bytes
✓ validation_metrics     persisted | 340 bytes
✓ confusion_matrix       persisted | 355 bytes
✓ classification_report  persisted | 653 bytes
✓ resource_metrics       persisted | 857 bytes
✓ feature_importance     persisted | 1,176 bytes
✓ model                  persisted | 18,430,126 bytes

[RF-4 TEMPORARY OBJECT CLEANUP]
✓ Temporary RF-4 helper objects released where applicable
✓ Persisted RF-4 artifacts retained
✓ Notebook 04 model-ready artifacts remain untouched
✓ Independent Test remains untouched

[FINAL RF-4 PERSISTENCE VALIDATION]

========================================================================
5.8.6 — RF-4 ARTIFACT PERSISTENCE AND CLEANUP PASSED
========================================================================

✓ RF-4 experiment metadata persisted
✓ RF-4 validation metrics persisted
✓ RF-4 confusion matrix persisted
✓ RF-4 classification report persisted
✓ RF-4 resource metrics persisted
✓ RF-4 feature importance persisted
✓ RF-4 fitted model persisted
✓ RF-4 Controlled SMOTE configuration persisted
✓ Temporary RF-4 runtime objects released
✓ Notebook 04 model-ready artifacts remain untouched
✓ Independent Test remains completely untouched

READY FOR 5.8.7 — RF-4 EXPERIMENT COMPLETION AND READINESS GATE
========================================================================

# 5.8.7 — RF-4 EXPERIMENT COMPLETION AND READINESS GATE

This subsection performs the final completion and readiness validation
for the RF-4 Controlled SMOTE experiment.

The gate confirms that RF-4 experiment definition, Training/Validation
artifact loading, controlled Training-partition SMOTE generation,
Random Forest model fitting, Validation evaluation, error/resource
analysis, and artifact persistence have all completed successfully.

RF-4 must retain the established 32-feature model-ready representation,
nine-class taxonomy, common Random Forest configuration, `class_weight=None`,
and the established project random seed.

The controlled SMOTE policy must remain restricted to the Training
partition. Majority-class downsampling remains prohibited, Heartbleed
remains excluded from synthetic sampling, and Infiltration remains
eligible subject to the established minimum-support boundary.

Validation must remain in its original distribution and must not be
resampled or modified. The Independent Test partition remains completely
protected and must not be loaded, evaluated, or used for strategy selection.

All seven RF-4 experiment artifacts must be present and valid, including
the persisted Controlled SMOTE configuration, Validation results,
error/resource information, feature importance, and fitted Random Forest
model.

RF-4 remains an independent candidate strategy and is not declared the
final Random Forest strategy in this subsection.

Successful completion of this gate concludes Section 5.8 — RF-4:
Controlled SMOTE and authorizes progression to the Validation-based
Random Forest strategy comparison and selection stage.

In [ ]:
# ================================================================
# 5.8.7 — RF-4 EXPERIMENT COMPLETION AND READINESS GATE
# ================================================================

print("=" * 72)
print("5.8.7 — RF-4 EXPERIMENT COMPLETION AND READINESS GATE")
print("=" * 72)


# ---------------------------------------------------------------
# 1. RF-4 COMPLETION BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-4 COMPLETION BOUNDARY VALIDATION]")


if not RF_5_8_1_VALIDATION[
    "strategy_id_valid"
]:

    raise RuntimeError(
        "RF-4 Controlled SMOTE definition "
        "has not passed validation."
    )


if not RF_5_8_2_VALIDATION[
    "training_features_loaded"
]:

    raise RuntimeError(
        "RF-4 Training feature artifact is not available."
    )


if not RF_5_8_2_VALIDATION[
    "validation_features_loaded"
]:

    raise RuntimeError(
        "RF-4 Validation feature artifact is not available."
    )


if not RF_5_8_4_VALIDATION[
    "rf4_model_available"
]:

    raise RuntimeError(
        "RF-4 Validation evaluation has not been completed."
    )


if not RF_5_8_5_VALIDATION[
    "rf4_model_available"
]:

    raise RuntimeError(
        "RF-4 error/resource analysis has not been completed."
    )


if not RF_5_8_6_VALIDATION[
    "model_persisted"
]:

    raise RuntimeError(
        "RF-4 fitted model has not been persisted."
    )


if RF4_MODEL is None:

    raise RuntimeError(
        "RF4_MODEL is not available in the current RF-4 runtime."
    )


if not hasattr(
    RF4_MODEL,
    "estimators_"
):

    raise RuntimeError(
        "RF4_MODEL is not a fitted Random Forest model."
    )


print(
    "✓ RF-4 Controlled SMOTE definition validated"
)

print(
    "✓ RF-4 Training/Validation artifact loading validated"
)

print(
    "✓ RF-4 validation evaluation completed"
)

print(
    "✓ RF-4 error/resource analysis completed"
)

print(
    "✓ Fitted RF-4 model is available"
)

print(
    "✓ RF-4 artifacts have been persisted"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# 2. FITTED RF-4 MODEL VALIDATION
# ---------------------------------------------------------------

print("\n[RF-4 FITTED MODEL VALIDATION]")


if RF4_MODEL.n_features_in_ != (
    EXPECTED_MODEL_READY_FEATURE_COUNT
):

    raise ValueError(
        "RF-4 fitted model feature count does not match "
        "the established model-ready feature contract."
    )


if len(
    RF4_MODEL.classes_
) != 9:

    raise ValueError(
        "RF-4 fitted model does not contain the expected "
        "nine-class taxonomy."
    )


if len(
    RF4_MODEL.estimators_
) != RF_COMMON_CONFIGURATION[
    "n_estimators"
]:

    raise ValueError(
        "RF-4 fitted model tree count does not match "
        "the established RF configuration."
    )


if RF4_MODEL.class_weight is not None:

    raise ValueError(
        "RF-4 fitted model must retain "
        "class_weight=None."
    )


if RF4_MODEL.random_state != RANDOM_SEED:

    raise ValueError(
        "RF-4 fitted model random_state does not match "
        "the established project RANDOM_SEED."
    )


print(
    "✓ RF4_MODEL is the fitted RF-4 Random Forest"
)

print(
    f"✓ Model features : "
    f"{RF4_MODEL.n_features_in_}"
)

print(
    f"✓ Model classes  : "
    f"{len(RF4_MODEL.classes_)}"
)

print(
    f"✓ Model trees    : "
    f"{len(RF4_MODEL.estimators_)}"
)

print(
    "✓ Class weighting : None"
)

print(
    f"✓ Random state    : "
    f"{RF4_MODEL.random_state}"
)


# ---------------------------------------------------------------
# 3. RF-4 CONTROLLED SMOTE VALIDATION
# ---------------------------------------------------------------

print("\n[RF-4 CONTROLLED SMOTE VALIDATION]")


if RF4_CONFIGURATION[
    "strategy_id"
] != "RF-4":

    raise ValueError(
        "RF-4 strategy ID is not correctly identified."
    )


if RF4_CONFIGURATION[
    "strategy_name"
] != "Controlled SMOTE":

    raise ValueError(
        "RF-4 strategy name does not match the established "
        "Controlled SMOTE strategy."
    )


if RF4_CONFIGURATION[
    "class_weight"
] is not None:

    raise ValueError(
        "RF-4 class weighting must remain disabled."
    )


if RF4_CONFIGURATION[
    "resampling"
] is not True:

    raise ValueError(
        "RF-4 Training-partition resampling is not enabled."
    )


if RF4_CONFIGURATION[
    "synthetic_sampling"
] is not True:

    raise ValueError(
        "RF-4 synthetic sampling must remain enabled."
    )


if RF4_SAMPLING_CONFIGURATION[
    "majority_downsampling"
] is not False:

    raise ValueError(
        "RF-4 majority-class downsampling must remain prohibited."
    )


if RF4_SAMPLING_CONFIGURATION[
    "heartbleed_oversampling"
] is not False:

    raise ValueError(
        "RF-4 Heartbleed synthetic sampling boundary has changed."
    )


if RF4_SAMPLING_CONFIGURATION[
    "infiltration_oversampling_eligible"
] is not True:

    raise ValueError(
        "RF-4 Infiltration eligibility boundary has changed."
    )


print(
    "✓ RF-4 strategy = Controlled SMOTE"
)

print(
    "✓ RF-4 class weighting = None"
)

print(
    "✓ Training-partition controlled SMOTE enabled"
)

print(
    "✓ Synthetic sampling enabled"
)

print(
    "✓ Majority-class downsampling prohibited"
)

print(
    "✓ Heartbleed excluded from synthetic sampling"
)

print(
    "✓ Infiltration remains eligible"
)


# ---------------------------------------------------------------
# 4. RF-4 SMOTE EXPERIMENT VALIDATION
# ---------------------------------------------------------------

print("\n[RF-4 SMOTE EXPERIMENT VALIDATION]")


if not RF_5_8_3_VALIDATION[
    "natural_training_observations"
]:

    raise RuntimeError(
        "RF-4 natural Training observation count is invalid."
    )


if not RF_5_8_3_VALIDATION[
    "synthetic_training_observations"
]:

    raise RuntimeError(
        "RF-4 synthetic Training representation is invalid."
    )


if not RF_5_8_3_VALIDATION[
    "synthetic_training_feature_count"
]:

    raise RuntimeError(
        "RF-4 synthetic Training feature count is invalid."
    )


if not RF_5_8_3_VALIDATION[
    "smote_training_class_distribution_valid"
]:

    raise RuntimeError(
        "RF-4 controlled SMOTE Training class distribution "
        "does not match the established SMOTE targets."
    )


if not RF_5_8_3_VALIDATION[
    "heartbleed_not_synthetic_sampled"
]:

    raise RuntimeError(
        "RF-4 Heartbleed was not preserved at its "
        "original Training support."
    )


if not RF_5_8_3_VALIDATION[
    "majority_downsampling_disabled"
]:

    raise RuntimeError(
        "RF-4 majority-class downsampling boundary failed."
    )


if not RF_5_8_3_VALIDATION[
    "synthetic_sampling_enabled"
]:

    raise RuntimeError(
        "RF-4 synthetic sampling boundary failed."
    )


print(
    f"✓ Original Training observations : "
    f"{RF4_TRAINING_FEATURES.shape[0]:,}"
)

print(
    f"✓ Synthetic RF-4 Training observations : "
    f"{RF4_SMOTE_TRAINING_OBSERVATIONS:,}"
)

print(
    f"✓ Total synthetic observations : "
    f"{RF4_TOTAL_SYNTHETIC_OBSERVATIONS:,}"
)

print(
    "✓ Controlled RF-4 SMOTE Training class distribution validated"
)

print(
    "✓ Heartbleed remained unmodified"
)

print(
    "✓ Majority-class downsampling was not performed"
)

print(
    "✓ Synthetic observations were generated only "
    "for eligible Training classes"
)


# ---------------------------------------------------------------
# 5. RF-4 PERSISTED ARTIFACT COMPLETENESS
# ---------------------------------------------------------------

print("\n[RF-4 PERSISTED ARTIFACT COMPLETENESS]")


if len(
    RF4_EXPERIMENT_ARTIFACTS
) != 7:

    raise RuntimeError(
        "Unexpected RF-4 artifact configuration."
    )


for artifact_name, artifact_path in (
    RF4_EXPERIMENT_ARTIFACTS.items()
):

    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"RF-4 artifact is missing: "
            f"{artifact_path}"
        )


    if artifact_path.stat().st_size <= 0:

        raise RuntimeError(
            f"RF-4 artifact is empty: "
            f"{artifact_path}"
        )


    print(
        f"✓ {artifact_name:<22} "
        f"persisted | "
        f"{artifact_path.stat().st_size:,} bytes"
    )


# ---------------------------------------------------------------
# 6. RF-4 PERSISTED RESULT STRUCTURE VALIDATION
# ---------------------------------------------------------------

print("\n[RF-4 PERSISTED RESULT STRUCTURE]")


RF4_PERSISTED_VALIDATION_METRICS = None

with open(
    RF4_EXPERIMENT_ARTIFACTS[
        "validation_metrics"
    ],
    "r",
    encoding="utf-8"
) as file:

    RF4_PERSISTED_VALIDATION_METRICS = (
        json.load(file)
    )


required_metric_names = {

    "accuracy",
    "balanced_accuracy",
    "macro_recall",
    "macro_f1",
    "weighted_f1",
    "benign_false_positive_rate",
    "macro_roc_auc_ovr",
    "total_attack_false_negatives",
}


if not required_metric_names.issubset(
    RF4_PERSISTED_VALIDATION_METRICS.keys()
):

    raise RuntimeError(
        "Persisted RF-4 Validation metrics are incomplete."
    )


RF4_PERSISTED_CONFUSION_MATRIX = pd.read_csv(
    RF4_EXPERIMENT_ARTIFACTS[
        "confusion_matrix"
    ],
    index_col=0
)


if RF4_PERSISTED_CONFUSION_MATRIX.shape != (
    9,
    9
):

    raise RuntimeError(
        "Persisted RF-4 confusion matrix is not 9 × 9."
    )


RF4_PERSISTED_CLASSIFICATION_REPORT = pd.read_csv(
    RF4_EXPERIMENT_ARTIFACTS[
        "classification_report"
    ]
)


if len(
    RF4_PERSISTED_CLASSIFICATION_REPORT
) != 9:

    raise RuntimeError(
        "Persisted RF-4 classification report does not "
        "contain all nine taxonomy classes."
    )


RF4_PERSISTED_FEATURE_IMPORTANCE = pd.read_csv(
    RF4_EXPERIMENT_ARTIFACTS[
        "feature_importance"
    ]
)


if len(
    RF4_PERSISTED_FEATURE_IMPORTANCE
) != EXPECTED_MODEL_READY_FEATURE_COUNT:

    raise RuntimeError(
        "Persisted RF-4 feature-importance table does not "
        "contain all 32 model-ready features."
    )


print(
    "✓ RF-4 Validation metrics structure confirmed"
)

print(
    "✓ RF-4 9 × 9 confusion matrix confirmed"
)

print(
    "✓ RF-4 nine-class classification report confirmed"
)

print(
    "✓ RF-4 32-feature importance table confirmed"
)


# ---------------------------------------------------------------
# 7. RF-4 METRIC CONSISTENCY CHECK
# ---------------------------------------------------------------

print("\n[RF-4 METRIC CONSISTENCY CHECK]")


if not np.isclose(
    RF4_PERSISTED_VALIDATION_METRICS[
        "accuracy"
    ],
    RF4_VALIDATION_ACCURACY
):

    raise RuntimeError(
        "Persisted RF-4 accuracy does not match "
        "the current RF-4 Validation result."
    )


if not np.isclose(
    RF4_PERSISTED_VALIDATION_METRICS[
        "macro_f1"
    ],
    RF4_VALIDATION_MACRO_F1
):

    raise RuntimeError(
        "Persisted RF-4 Macro F1 does not match "
        "the current RF-4 Validation result."
    )


if not np.isclose(
    RF4_PERSISTED_VALIDATION_METRICS[
        "balanced_accuracy"
    ],
    RF4_VALIDATION_BALANCED_ACCURACY
):

    raise RuntimeError(
        "Persisted RF-4 balanced accuracy does not match "
        "the current RF-4 Validation result."
    )


print(
    "✓ Persisted RF-4 accuracy matches Validation result"
)

print(
    "✓ Persisted RF-4 Macro F1 matches Validation result"
)

print(
    "✓ Persisted RF-4 balanced accuracy matches Validation result"
)


# ---------------------------------------------------------------
# 8. RF-4 COMPLETION AND DEVELOPMENT-BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[RF-4 DEVELOPMENT-BOUNDARY VALIDATION]")


if not RF_5_8_6_VALIDATION[
    "independent_test_protected"
]:

    raise RuntimeError(
        "Independent Test protection was not preserved "
        "during RF-4."
    )


if not RF_5_8_6_VALIDATION[
    "n04_artifacts_untouched"
]:

    raise RuntimeError(
        "Notebook 04 model-ready artifacts were not confirmed "
        "as untouched."
    )


if not RF_5_8_4_VALIDATION[
    "smote_restricted_to_training"
]:

    raise RuntimeError(
        "RF-4 SMOTE was not confirmed as restricted "
        "to the Training partition."
    )


if not RF_5_8_4_VALIDATION[
    "strategy_selection_not_performed"
]:

    raise RuntimeError(
        "RF-4 strategy selection was performed prematurely."
    )


print(
    "✓ Independent Test remained excluded from RF-4"
)

print(
    "✓ Independent Test was not used for RF-4 evaluation "
    "or selection"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "✓ RF-4 Controlled SMOTE remained restricted to Training"
)

print(
    "✓ RF-4 strategy selection has not been performed"
)


# ---------------------------------------------------------------
# 9. STRATEGY-SELECTION BOUNDARY
# ---------------------------------------------------------------

print("\n[STRATEGY-SELECTION BOUNDARY]")


print(
    "✓ RF-4 is retained as an independent experiment"
)

print(
    "✓ RF-4 has not been declared the optimal RF strategy"
)

print(
    "✓ No RF strategy selection has been performed"
)

print(
    "✓ RF-4 remains available for later Validation comparison"
)


# ---------------------------------------------------------------
# 10. MODEL-DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[MODEL-DEVELOPMENT BOUNDARY]")


print(
    "✓ No additional model fitting performed"
)

print(
    "✓ No additional predictions generated"
)

print(
    "✓ No additional SMOTE resampling performed"
)

print(
    "✓ No additional synthetic samples generated"
)

print(
    "✓ No Independent Test data loaded"
)


# ---------------------------------------------------------------
# 11. FINAL RF-4 COMPLETION GATE
# ---------------------------------------------------------------

print("\n[FINAL RF-4 COMPLETION GATE]")


RF_5_8_7_VALIDATION = {

    "rf4_definition_complete":
        all(
            RF_5_8_1_VALIDATION.values()
        ),

    "rf4_artifact_loading_complete":
        all(
            RF_5_8_2_VALIDATION.values()
        ),

    "rf4_model_fitting_complete":
        all(
            RF_5_8_3_VALIDATION.values()
        ),

    "rf4_evaluation_complete":
        all(
            RF_5_8_4_VALIDATION.values()
        ),

    "rf4_error_resource_analysis_complete":
        all(
            RF_5_8_5_VALIDATION.values()
        ),

    "rf4_artifact_persistence_complete":
        all(
            RF_5_8_6_VALIDATION.values()
        ),

    "rf4_model_contract_valid":
        (
            RF4_MODEL.n_features_in_
            == EXPECTED_MODEL_READY_FEATURE_COUNT
        ),

    "rf4_taxonomy_valid":
        np.array_equal(
            RF4_MODEL.classes_,
            np.asarray(
                EXPECTED_RF_CLASS_IDS
            )
        ),

    "rf4_tree_count_valid":
        len(
            RF4_MODEL.estimators_
        )
        ==
        RF_COMMON_CONFIGURATION[
            "n_estimators"
        ],

    "rf4_controlled_smote_valid":
        (
            RF4_CONFIGURATION[
                "resampling"
            ] is True
            and
            RF4_CONFIGURATION[
                "synthetic_sampling"
            ] is True
            and
            RF4_SAMPLING_CONFIGURATION[
                "majority_downsampling"
            ] is False
            and
            RF4_SAMPLING_CONFIGURATION[
                "heartbleed_oversampling"
            ] is False
        ),

    "rf4_class_weighting_disabled":
        (
            RF4_CONFIGURATION[
                "class_weight"
            ] is None
            and
            RF4_MODEL.class_weight is None
        ),

    "rf4_artifact_count_valid":
        len(
            RF4_EXPERIMENT_ARTIFACTS
        ) == 7,

    "rf4_confusion_matrix_valid":
        RF4_PERSISTED_CONFUSION_MATRIX.shape
        == (9, 9),

    "rf4_classification_report_valid":
        len(
            RF4_PERSISTED_CLASSIFICATION_REPORT
        ) == 9,

    "rf4_feature_importance_valid":
        len(
            RF4_PERSISTED_FEATURE_IMPORTANCE
        )
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "rf4_smote_training_valid":
        RF_5_8_3_VALIDATION[
            "smote_training_class_distribution_valid"
        ],

    "rf4_heartbleed_protected":
        RF_5_8_3_VALIDATION[
            "heartbleed_not_synthetic_sampled"
        ],

    "rf4_training_only_smote":
        RF_5_8_4_VALIDATION[
            "smote_restricted_to_training"
        ],

    "independent_test_protected":
        RF_5_8_6_VALIDATION[
            "independent_test_protected"
        ],

    "n04_artifacts_untouched":
        RF_5_8_6_VALIDATION[
            "n04_artifacts_untouched"
        ],

    "strategy_not_selected":
        True,
}


failed_checks = [

    check_name

    for check_name, passed
    in RF_5_8_7_VALIDATION.items()

    if not passed

]


if failed_checks:

    raise RuntimeError(
        "5.8.7 RF-4 completion/readiness gate failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 12. FINAL STATUS
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.8.7 — RF-4 EXPERIMENT COMPLETION AND READINESS GATE PASSED"
)

print("=" * 72)


print(
    "\nRF-4 CONTROLLED SMOTE EXPERIMENT COMPLETED"
)

print(
    "✓ RF-4 definition validated"
)

print(
    "✓ Complete Training partition used for RF-4 fitting"
)

print(
    "✓ Complete Validation partition used for RF-4 evaluation"
)

print(
    "✓ RF-4 controlled SMOTE configuration validated"
)

print(
    "✓ RF-4 model contract validated"
)

print(
    "✓ RF-4 Validation results persisted"
)

print(
    "✓ RF-4 error and resource analysis completed"
)

print(
    "✓ All seven RF-4 experiment artifacts confirmed"
)

print(
    "✓ RF-4 remains an independent experiment and has not been selected"
)

print(
    "✓ Independent Test remains completely untouched"
)

print(
    "✓ Notebook 04 model-ready artifacts remain untouched"
)

print(
    "\n5.8 — RF-4: CONTROLLED SMOTE SECTION COMPLETED"
)

print(
    "READY FOR 5.9 — VALIDATION-BASED RANDOM FOREST STRATEGY COMPARISON"
)

print("=" * 72)

========================================================================
5.8.7 — RF-4 EXPERIMENT COMPLETION AND READINESS GATE
========================================================================

[RF-4 COMPLETION BOUNDARY VALIDATION]
✓ RF-4 Controlled SMOTE definition validated
✓ RF-4 Training/Validation artifact loading validated
✓ RF-4 validation evaluation completed
✓ RF-4 error/resource analysis completed
✓ Fitted RF-4 model is available
✓ RF-4 artifacts have been persisted
✓ Independent Test remains excluded

[RF-4 FITTED MODEL VALIDATION]
✓ RF4_MODEL is the fitted RF-4 Random Forest
✓ Model features : 32
✓ Model classes  : 9
✓ Model trees    : 100
✓ Class weighting : None
✓ Random state    : 42

[RF-4 CONTROLLED SMOTE VALIDATION]
✓ RF-4 strategy = Controlled SMOTE
✓ RF-4 class weighting = None
✓ Training-partition controlled SMOTE enabled
✓ Synthetic sampling enabled
✓ Majority-class downsampling prohibited
✓ Heartbleed excluded from synthetic sampling
✓ Infiltration remains eligible

[RF-4 SMOTE EXPERIMENT VALIDATION]
✓ Original Training observations : 1,814,018
✓ Synthetic RF-4 Training observations : 1,862,014
✓ Total synthetic observations : 47,996
✓ Controlled RF-4 SMOTE Training class distribution validated
✓ Heartbleed remained unmodified
✓ Majority-class downsampling was not performed
✓ Synthetic observations were generated only for eligible Training classes

[RF-4 PERSISTED ARTIFACT COMPLETENESS]
✓ experiment_metadata    persisted | 2,386 bytes
✓ validation_metrics     persisted | 340 bytes
✓ confusion_matrix       persisted | 355 bytes
✓ classification_report  persisted | 653 bytes
✓ resource_metrics       persisted | 857 bytes
✓ feature_importance     persisted | 1,176 bytes
✓ model                  persisted | 18,430,126 bytes

[RF-4 PERSISTED RESULT STRUCTURE]
✓ RF-4 Validation metrics structure confirmed
✓ RF-4 9 × 9 confusion matrix confirmed
✓ RF-4 nine-class classification report confirmed
✓ RF-4 32-feature importance table confirmed

[RF-4 METRIC CONSISTENCY CHECK]
✓ Persisted RF-4 accuracy matches Validation result
✓ Persisted RF-4 Macro F1 matches Validation result
✓ Persisted RF-4 balanced accuracy matches Validation result

[RF-4 DEVELOPMENT-BOUNDARY VALIDATION]
✓ Independent Test remained excluded from RF-4
✓ Independent Test was not used for RF-4 evaluation or selection
✓ Notebook 04 model-ready artifacts remain untouched
✓ RF-4 Controlled SMOTE remained restricted to Training
✓ RF-4 strategy selection has not been performed

[STRATEGY-SELECTION BOUNDARY]
✓ RF-4 is retained as an independent experiment
✓ RF-4 has not been declared the optimal RF strategy
✓ No RF strategy selection has been performed
✓ RF-4 remains available for later Validation comparison

[MODEL-DEVELOPMENT BOUNDARY]
✓ No additional model fitting performed
✓ No additional predictions generated
✓ No additional SMOTE resampling performed
✓ No additional synthetic samples generated
✓ No Independent Test data loaded

[FINAL RF-4 COMPLETION GATE]

========================================================================
5.8.7 — RF-4 EXPERIMENT COMPLETION AND READINESS GATE PASSED
========================================================================

RF-4 CONTROLLED SMOTE EXPERIMENT COMPLETED
✓ RF-4 definition validated
✓ Complete Training partition used for RF-4 fitting
✓ Complete Validation partition used for RF-4 evaluation
✓ RF-4 controlled SMOTE configuration validated
✓ RF-4 model contract validated
✓ RF-4 Validation results persisted
✓ RF-4 error and resource analysis completed
✓ All seven RF-4 experiment artifacts confirmed
✓ RF-4 remains an independent experiment and has not been selected
✓ Independent Test remains completely untouched
✓ Notebook 04 model-ready artifacts remain untouched

5.8 — RF-4: CONTROLLED SMOTE SECTION COMPLETED
READY FOR 5.9 — VALIDATION-BASED RANDOM FOREST STRATEGY COMPARISON
========================================================================

# 5.9 — Validation-Based Random Forest Strategy Comparison

Section 5.9 compares the five completed Random Forest imbalance-handling
experiments using their persisted Validation results and experiment-level
resource/error information.

The comparison is performed only after RF-0 through RF-4 have completed
their independent experiment lifecycles and persisted their respective
artifacts. No new Random Forest model fitting, resampling, synthetic
sampling, or Validation prediction generation is performed in this section.

The comparison uses the established Validation partition and the predefined
evaluation hierarchy, with Macro F1 as the primary strategy-comparison
metric and Macro Recall, Balanced Accuracy, Weighted F1, Accuracy,
BENIGN false-positive rate, attack false negatives, multiclass ROC-AUC,
minority-class behavior, and resource observations as supporting evidence.

The Independent Test partition remains completely excluded from the
comparison and is reserved for the final evaluation stage.

Section 5.9 produces the consolidated comparison evidence required before
the final Random Forest strategy is selected in Section 5.10.

## 5.9.1 — RF Strategy Comparison Definition and Boundary Validation

This subsection establishes the comparison boundary for the five completed
Random Forest experiments: RF-0 Natural Distribution Baseline, RF-1
Balanced Class Weighting, RF-2 Balanced-Subsample Class Weighting, RF-3
Controlled Random Oversampling, and RF-4 Controlled SMOTE.

The comparison is based exclusively on the persisted artifacts produced by
the completed RF experiments. Their individual experiment configurations,
Validation metrics, confusion matrices, classification reports, resource
metrics, feature-importance tables, and fitted model artifacts are recovered
from the established strategy-experiment directories.

No experiment is retrained and no new Validation predictions or resampling
operations are performed. The Independent Test partition remains excluded.

The comparison outputs are already defined by the Notebook 05 artifact
configuration: the consolidated experiment comparison is stored under the
strategy-experiment directory, while consolidated Validation results are
stored under the RF evaluation directory. The strategy-selection artifact
remains reserved for Section 5.10.

A successful boundary validation confirms that all five RF experiment
artifact sets are available, their artifact destinations are consistent,
the common 32-feature and nine-class contracts remain applicable, and the
comparison stage has not accessed the Independent Test partition.

In [ ]:
# ================================================================
# 5.9.1 — RF STRATEGY COMPARISON DEFINITION AND BOUNDARY VALIDATION
# ================================================================

print("=" * 72)
print("5.9.1 — RF STRATEGY COMPARISON DEFINITION AND BOUNDARY VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. COMPARISON STRATEGY CONTRACT
# ---------------------------------------------------------------

print("\n[RF STRATEGY COMPARISON CONTRACT]")


RF_COMPARISON_STRATEGIES = {

    "RF-0": {
        "name": "Natural Distribution Baseline",
        "artifacts": RF0_EXPERIMENT_ARTIFACTS,
    },

    "RF-1": {
        "name": "Balanced Class Weighting",
        "artifacts": RF1_EXPERIMENT_ARTIFACTS,
    },

    "RF-2": {
        "name": "Balanced-Subsample Class Weighting",
        "artifacts": RF2_EXPERIMENT_ARTIFACTS,
    },

    "RF-3": {
        "name": "Controlled Random Oversampling",
        "artifacts": RF3_EXPERIMENT_ARTIFACTS,
    },

    "RF-4": {
        "name": "Controlled SMOTE",
        "artifacts": RF4_EXPERIMENT_ARTIFACTS,
    },
}


EXPECTED_RF_COMPARISON_STRATEGIES = [
    "RF-0",
    "RF-1",
    "RF-2",
    "RF-3",
    "RF-4",
]


if list(
    RF_COMPARISON_STRATEGIES.keys()
) != EXPECTED_RF_COMPARISON_STRATEGIES:

    raise RuntimeError(
        "RF comparison strategy order does not match "
        "the established RF-0 through RF-4 experiment contract."
    )


print(
    "✓ Five completed RF strategies registered for comparison"
)

for strategy_id, strategy_info in (
    RF_COMPARISON_STRATEGIES.items()
):

    print(
        f"✓ {strategy_id} — "
        f"{strategy_info['name']}"
    )


# ---------------------------------------------------------------
# 2. ESTABLISHED RF OUTPUT DIRECTORY VALIDATION
# ---------------------------------------------------------------

print("\n[RF COMPARISON OUTPUT DIRECTORY VALIDATION]")


if not RANDOM_FOREST_OUTPUT_DIR.is_dir():

    raise FileNotFoundError(
        "Random Forest development output directory is not available:\n"
        f"{RANDOM_FOREST_OUTPUT_DIR}"
    )


if not RF_STRATEGY_EXPERIMENTS_DIR.is_dir():

    raise FileNotFoundError(
        "RF strategy experiments directory is not available:\n"
        f"{RF_STRATEGY_EXPERIMENTS_DIR}"
    )


if not RF_EVALUATION_DIR.is_dir():

    raise FileNotFoundError(
        "RF evaluation directory is not available:\n"
        f"{RF_EVALUATION_DIR}"
    )


if not RF_STRATEGY_SELECTION_DIR.is_dir():

    raise FileNotFoundError(
        "RF strategy selection directory is not available:\n"
        f"{RF_STRATEGY_SELECTION_DIR}"
    )


print(
    f"✓ RF development output : "
    f"{RANDOM_FOREST_OUTPUT_DIR}"
)

print(
    f"✓ Strategy experiments  : "
    f"{RF_STRATEGY_EXPERIMENTS_DIR}"
)

print(
    f"✓ RF evaluation         : "
    f"{RF_EVALUATION_DIR}"
)

print(
    f"✓ Strategy selection    : "
    f"{RF_STRATEGY_SELECTION_DIR}"
)


# ---------------------------------------------------------------
# 3. PERSISTED RF EXPERIMENT ARTIFACT PATH RECOVERY
# ---------------------------------------------------------------

print("\n[PERSISTED RF EXPERIMENT ARTIFACT PATH RECOVERY]")


RF_COMPARISON_INPUT_ARTIFACTS = {}


for strategy_id, strategy_info in (
    RF_COMPARISON_STRATEGIES.items()
):

    strategy_artifacts = strategy_info[
        "artifacts"
    ]

    RF_COMPARISON_INPUT_ARTIFACTS[
        strategy_id
    ] = {

        "experiment_metadata":
            strategy_artifacts[
                "experiment_metadata"
            ],

        "validation_metrics":
            strategy_artifacts[
                "validation_metrics"
            ],

        "confusion_matrix":
            strategy_artifacts[
                "confusion_matrix"
            ],

        "classification_report":
            strategy_artifacts[
                "classification_report"
            ],

        "resource_metrics":
            strategy_artifacts[
                "resource_metrics"
            ],

        "feature_importance":
            strategy_artifacts[
                "feature_importance"
            ],

        "model":
            strategy_artifacts[
                "model"
            ],
    }


for strategy_id, artifact_paths in (
    RF_COMPARISON_INPUT_ARTIFACTS.items()
):

    print(
        f"\n{strategy_id} — "
        f"{RF_COMPARISON_STRATEGIES[strategy_id]['name']}"
    )

    for artifact_name, artifact_path in (
        artifact_paths.items()
    ):

        print(
            f"  ✓ {artifact_name:<22} : "
            f"{artifact_path}"
        )


# ---------------------------------------------------------------
# 4. PERSISTED ARTIFACT COMPLETENESS VALIDATION
# ---------------------------------------------------------------

print("\n[PERSISTED RF EXPERIMENT ARTIFACT COMPLETENESS]")


RF_REQUIRED_EXPERIMENT_ARTIFACT_NAMES = [
    "experiment_metadata",
    "validation_metrics",
    "confusion_matrix",
    "classification_report",
    "resource_metrics",
    "feature_importance",
    "model",
]


for strategy_id, artifact_paths in (
    RF_COMPARISON_INPUT_ARTIFACTS.items()
):

    if set(
        artifact_paths.keys()
    ) != set(
        RF_REQUIRED_EXPERIMENT_ARTIFACT_NAMES
    ):

        raise RuntimeError(
            f"{strategy_id} does not contain the complete "
            "seven-artifact RF experiment contract."
        )


    for artifact_name, artifact_path in (
        artifact_paths.items()
    ):

        if not artifact_path.is_file():

            raise FileNotFoundError(
                f"{strategy_id} {artifact_name} artifact "
                f"is missing:\n{artifact_path}"
            )


    print(
        f"✓ {strategy_id} — all seven persisted "
        "experiment artifacts available"
    )


# ---------------------------------------------------------------
# 5. EXPERIMENT ARTIFACT PATH ISOLATION
# ---------------------------------------------------------------

print("\n[RF EXPERIMENT ARTIFACT PATH ISOLATION]")


all_rf_comparison_artifact_paths = []


for strategy_id, artifact_paths in (
    RF_COMPARISON_INPUT_ARTIFACTS.items()
):

    for artifact_path in (
        artifact_paths.values()
    ):

        all_rf_comparison_artifact_paths.append(
            artifact_path
        )


if len(
    all_rf_comparison_artifact_paths
) != len(
    set(
        all_rf_comparison_artifact_paths
    )
):

    raise RuntimeError(
        "Duplicate artifact paths detected across "
        "RF-0 through RF-4 comparison inputs."
    )


print(
    "✓ RF-0 through RF-4 artifact destinations are unique"
)

print(
    "✓ Each completed RF experiment remains independently persisted"
)


# ---------------------------------------------------------------
# 6. COMMON MODEL-READY CONTRACT VALIDATION
# ---------------------------------------------------------------

print("\n[COMMON RF MODEL-READY CONTRACT]")


if EXPECTED_FEATURE_COUNT != 32:

    raise RuntimeError(
        "RF comparison feature count does not match "
        "the established 32-feature contract."
    )


if len(
    EXPECTED_CLASS_MAPPING
) != 9:

    raise RuntimeError(
        "RF comparison taxonomy does not contain "
        "the established nine classes."
    )


if sorted(
    EXPECTED_CLASS_MAPPING.values()
) != list(
    range(9)
):

    raise RuntimeError(
        "RF comparison taxonomy does not match "
        "the established class IDs 0–8."
    )


if EXPECTED_PARTITION_SHAPES[
    "Validation"
] != (
    451_215,
    EXPECTED_FEATURE_COUNT
):

    raise RuntimeError(
        "Validation partition shape does not match "
        "the established N04 RF contract."
    )


print(
    f"✓ RF feature count       : "
    f"{EXPECTED_FEATURE_COUNT}"
)

print(
    f"✓ RF taxonomy classes    : "
    f"{len(EXPECTED_CLASS_MAPPING)}"
)

print(
    f"✓ Validation observations: "
    f"{EXPECTED_PARTITION_SHAPES['Validation'][0]:,}"
)

print(
    "✓ Common RF model-ready contract confirmed"
)


# ---------------------------------------------------------------
# 7. COMPARISON OUTPUT ARTIFACT PATH CONFIGURATION
# ---------------------------------------------------------------

print("\n[5.9 COMPARISON OUTPUT ARTIFACT CONFIGURATION]")


RF_COMPARISON_OUTPUT_ARTIFACTS = {

    "experiment_results":
        RF_EXPERIMENT_ARTIFACTS[
            "experiment_results"
        ],

    "validation_results":
        RF_EXPERIMENT_ARTIFACTS[
            "validation_results"
        ],
}


for artifact_name, artifact_path in (
    RF_COMPARISON_OUTPUT_ARTIFACTS.items()
):

    print(
        f"✓ {artifact_name:<22} : "
        f"{artifact_path}"
    )


if len(
    RF_COMPARISON_OUTPUT_ARTIFACTS
) != 2:

    raise RuntimeError(
        "5.9 comparison output contract must contain "
        "exactly the two established comparison artifacts."
    )


if len(
    set(
        RF_COMPARISON_OUTPUT_ARTIFACTS.values()
    )
) != len(
    RF_COMPARISON_OUTPUT_ARTIFACTS
):

    raise RuntimeError(
        "Duplicate 5.9 comparison output paths detected."
    )


print(
    "✓ Comparison outputs use the established Notebook 05 "
    "artifact configuration"
)


# ---------------------------------------------------------------
# 8. STRATEGY-SELECTION BOUNDARY
# ---------------------------------------------------------------

print("\n[STRATEGY-SELECTION BOUNDARY]")


if RF_EXPERIMENT_ARTIFACTS[
    "strategy_selection"
].parent != RF_STRATEGY_SELECTION_DIR:

    raise RuntimeError(
        "Strategy-selection artifact is outside the "
        "established strategy-selection directory."
    )


print(
    f"✓ Strategy selection remains reserved for : "
    f"{RF_EXPERIMENT_ARTIFACTS['strategy_selection']}"
)

print(
    "✓ No RF strategy selection is performed in 5.9.1"
)


# ---------------------------------------------------------------
# 9. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION]")


print(
    "✓ Independent Test is not used as a comparison input"
)

print(
    "✓ No Test predictions are generated"
)

print(
    "✓ No Test metrics are calculated"
)

print(
    "✓ Independent Test remains reserved for final evaluation"
)


# ---------------------------------------------------------------
# 10. MODEL-DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[RF COMPARISON DEVELOPMENT BOUNDARY]")


print(
    "✓ No Random Forest model fitting performed"
)

print(
    "✓ No Validation prediction generation performed"
)

print(
    "✓ No random oversampling performed"
)

print(
    "✓ No SMOTE performed"
)

print(
    "✓ No Training distribution modified"
)

print(
    "✓ No Validation distribution modified"
)

print(
    "✓ Existing persisted RF experiment results are "
    "the comparison inputs"
)


# ---------------------------------------------------------------
# 11. FINAL 5.9.1 BOUNDARY GATE
# ---------------------------------------------------------------

print("\n[FINAL 5.9.1 COMPARISON BOUNDARY GATE]")


print(
    "✓ RF-0 through RF-4 experiment identities confirmed"
)

print(
    "✓ All five RF experiment artifact sets confirmed"
)

print(
    "✓ Seven persisted artifacts available for each strategy"
)

print(
    "✓ Common 32-feature model-ready contract confirmed"
)

print(
    "✓ Nine-class taxonomy confirmed"
)

print(
    "✓ Validation-only comparison boundary confirmed"
)

print(
    "✓ 5.9 comparison output paths established"
)

print(
    "✓ Strategy selection remains reserved for Section 5.10"
)

print(
    "✓ Independent Test remains completely protected"
)

print(
    "✓ No model fitting, prediction, or resampling performed"
)


print("\n" + "=" * 72)

print(
    "5.9.1 — RF STRATEGY COMPARISON DEFINITION AND "
    "BOUNDARY VALIDATION PASSED"
)

print("=" * 72)

print(
    "\nRF STRATEGY COMPARISON BOUNDARY ESTABLISHED"
)

print(
    "READY FOR 5.9.2 — PERSISTED RF EXPERIMENT RESULT "
    "LOADING AND VALIDATION"
)

print("=" * 72)

========================================================================
5.9.1 — RF STRATEGY COMPARISON DEFINITION AND BOUNDARY VALIDATION
========================================================================

[RF STRATEGY COMPARISON CONTRACT]
✓ Five completed RF strategies registered for comparison
✓ RF-0 — Natural Distribution Baseline
✓ RF-1 — Balanced Class Weighting
✓ RF-2 — Balanced-Subsample Class Weighting
✓ RF-3 — Controlled Random Oversampling
✓ RF-4 — Controlled SMOTE

[RF COMPARISON OUTPUT DIRECTORY VALIDATION]
✓ RF development output : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development
✓ Strategy experiments  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments
✓ RF evaluation         : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation
✓ Strategy selection    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_selection

[PERSISTED RF EXPERIMENT ARTIFACT PATH RECOVERY]

RF-0 — Natural Distribution Baseline
  ✓ experiment_metadata    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0/rf0_experiment_metadata.json
  ✓ validation_metrics     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0/rf0_validation_metrics.json
  ✓ confusion_matrix       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0/rf0_confusion_matrix.csv
  ✓ classification_report  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0/rf0_classification_report.csv
  ✓ resource_metrics       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0/rf0_resource_metrics.json
  ✓ feature_importance     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0/rf0_feature_importance.csv
  ✓ model                  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0/rf0_model.joblib

RF-1 — Balanced Class Weighting
  ✓ experiment_metadata    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1/rf1_experiment_metadata.json
  ✓ validation_metrics     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1/rf1_validation_metrics.json
  ✓ confusion_matrix       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1/rf1_confusion_matrix.csv
  ✓ classification_report  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1/rf1_classification_report.csv
  ✓ resource_metrics       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1/rf1_resource_metrics.json
  ✓ feature_importance     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1/rf1_feature_importance.csv
  ✓ model                  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1/rf1_model.joblib

RF-2 — Balanced-Subsample Class Weighting
  ✓ experiment_metadata    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2/rf2_experiment_metadata.json
  ✓ validation_metrics     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2/rf2_validation_metrics.json
  ✓ confusion_matrix       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2/rf2_confusion_matrix.csv
  ✓ classification_report  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2/rf2_classification_report.csv
  ✓ resource_metrics       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2/rf2_resource_metrics.json
  ✓ feature_importance     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2/rf2_feature_importance.csv
  ✓ model                  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2/rf2_model.joblib

RF-3 — Controlled Random Oversampling
  ✓ experiment_metadata    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3/rf3_experiment_metadata.json
  ✓ validation_metrics     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3/rf3_validation_metrics.json
  ✓ confusion_matrix       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3/rf3_confusion_matrix.csv
  ✓ classification_report  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3/rf3_classification_report.csv
  ✓ resource_metrics       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3/rf3_resource_metrics.json
  ✓ feature_importance     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3/rf3_feature_importance.csv
  ✓ model                  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3/rf3_model.joblib

RF-4 — Controlled SMOTE
  ✓ experiment_metadata    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4/rf4_experiment_metadata.json
  ✓ validation_metrics     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4/rf4_validation_metrics.json
  ✓ confusion_matrix       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4/rf4_confusion_matrix.csv
  ✓ classification_report  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4/rf4_classification_report.csv
  ✓ resource_metrics       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4/rf4_resource_metrics.json
  ✓ feature_importance     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4/rf4_feature_importance.csv
  ✓ model                  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4/rf4_model.joblib

[PERSISTED RF EXPERIMENT ARTIFACT COMPLETENESS]
✓ RF-0 — all seven persisted experiment artifacts available
✓ RF-1 — all seven persisted experiment artifacts available
✓ RF-2 — all seven persisted experiment artifacts available
✓ RF-3 — all seven persisted experiment artifacts available
✓ RF-4 — all seven persisted experiment artifacts available

[RF EXPERIMENT ARTIFACT PATH ISOLATION]
✓ RF-0 through RF-4 artifact destinations are unique
✓ Each completed RF experiment remains independently persisted

[COMMON RF MODEL-READY CONTRACT]
✓ RF feature count       : 32
✓ RF taxonomy classes    : 9
✓ Validation observations: 451,215
✓ Common RF model-ready contract confirmed

[5.9 COMPARISON OUTPUT ARTIFACT CONFIGURATION]
✓ experiment_results     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/rf_experiment_results.csv
✓ validation_results     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/validation_results.csv
✓ Comparison outputs use the established Notebook 05 artifact configuration

[STRATEGY-SELECTION BOUNDARY]
✓ Strategy selection remains reserved for : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_selection/rf_strategy_selection.json
✓ No RF strategy selection is performed in 5.9.1

[INDEPENDENT TEST PROTECTION]
✓ Independent Test is not used as a comparison input
✓ No Test predictions are generated
✓ No Test metrics are calculated
✓ Independent Test remains reserved for final evaluation

[RF COMPARISON DEVELOPMENT BOUNDARY]
✓ No Random Forest model fitting performed
✓ No Validation prediction generation performed
✓ No random oversampling performed
✓ No SMOTE performed
✓ No Training distribution modified
✓ No Validation distribution modified
✓ Existing persisted RF experiment results are the comparison inputs

[FINAL 5.9.1 COMPARISON BOUNDARY GATE]
✓ RF-0 through RF-4 experiment identities confirmed
✓ All five RF experiment artifact sets confirmed
✓ Seven persisted artifacts available for each strategy
✓ Common 32-feature model-ready contract confirmed
✓ Nine-class taxonomy confirmed
✓ Validation-only comparison boundary confirmed
✓ 5.9 comparison output paths established
✓ Strategy selection remains reserved for Section 5.10
✓ Independent Test remains completely protected
✓ No model fitting, prediction, or resampling performed

========================================================================
5.9.1 — RF STRATEGY COMPARISON DEFINITION AND BOUNDARY VALIDATION PASSED
========================================================================

RF STRATEGY COMPARISON BOUNDARY ESTABLISHED
READY FOR 5.9.2 — PERSISTED RF EXPERIMENT RESULT LOADING AND VALIDATION
========================================================================

## 5.9.2 — Persisted RF Experiment Result Loading and Validation

This subsection loads and validates the persisted results produced by the five completed
Random Forest experiments: RF-0, RF-1, RF-2, RF-3, and RF-4.

The comparison stage uses the previously persisted Validation results rather than
re-running model prediction or model fitting. For each strategy, the persisted
experiment metadata, Validation metrics, confusion matrix, classification report,
resource metrics, and feature-importance artifacts are recovered from the established
RF strategy-experiment directories.

The loaded results are validated against the common Random Forest development contract:
32 model-ready features, nine-class taxonomy, and the complete 451,215-observation
Validation partition. The persisted experiment results must remain independently
traceable to their corresponding RF strategy.

No Random Forest model is refitted in this subsection, and no new Validation
predictions, resampling, or synthetic sampling are performed. The Independent Test
partition remains completely excluded from comparison.

The validated persisted results are retained in memory for the subsequent
Validation-based RF strategy comparison.

In [ ]:
# ================================================================
# 5.9.2 — PERSISTED RF EXPERIMENT RESULT LOADING AND VALIDATION
# ================================================================

print("=" * 72)
print("5.9.2 — PERSISTED RF EXPERIMENT RESULT LOADING AND VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. COMPARISON INPUT BOUNDARY
# ---------------------------------------------------------------

print("\n[COMPARISON INPUT BOUNDARY]")

if not RF_STRATEGY_EXPERIMENTS_DIR.is_dir():
    raise FileNotFoundError(
        "RF strategy experiment directory is not available:\n"
        f"{RF_STRATEGY_EXPERIMENTS_DIR}"
    )

if not RF_EVALUATION_DIR.is_dir():
    raise FileNotFoundError(
        "RF evaluation directory is not available:\n"
        f"{RF_EVALUATION_DIR}"
    )

if not RF_STRATEGY_SELECTION_DIR.is_dir():
    raise FileNotFoundError(
        "RF strategy-selection directory is not available:\n"
        f"{RF_STRATEGY_SELECTION_DIR}"
    )

print(
    f"✓ RF strategy experiments : "
    f"{RF_STRATEGY_EXPERIMENTS_DIR}"
)

print(
    f"✓ RF evaluation directory : "
    f"{RF_EVALUATION_DIR}"
)

print(
    f"✓ RF strategy selection   : "
    f"{RF_STRATEGY_SELECTION_DIR}"
)


# ---------------------------------------------------------------
# 2. EXPECTED FIVE-STRATEGY CONTRACT
# ---------------------------------------------------------------

print("\n[RF EXPERIMENT RESULT CONTRACT]")

if len(EXPECTED_RF_STRATEGIES) != 5:
    raise RuntimeError(
        "Exactly five RF strategies are required for comparison."
    )

if len(EXPECTED_RF_STRATEGY_NAMES) != 5:
    raise RuntimeError(
        "Exactly five RF strategy names are required for comparison."
    )

print("✓ Five completed RF strategies registered")

for strategy_id, strategy_name in zip(
    EXPECTED_RF_STRATEGIES,
    EXPECTED_RF_STRATEGY_NAMES
):
    print(
        f"✓ {strategy_id} — {strategy_name}"
    )


# ---------------------------------------------------------------
# 3. PERSISTED ARTIFACT PATH RECOVERY
# ---------------------------------------------------------------

print("\n[PERSISTED RF ARTIFACT PATH RECOVERY]")

RF_COMPARISON_ARTIFACT_PATHS = {}

for strategy_id in EXPECTED_RF_STRATEGIES:

    strategy_dir = (
        RF_STRATEGY_EXPERIMENTS_DIR /
        strategy_id
    )

    prefix = strategy_id.lower().replace("-", "")

    RF_COMPARISON_ARTIFACT_PATHS[strategy_id] = {

        "experiment_metadata":
            strategy_dir /
            f"{prefix}_experiment_metadata.json",

        "validation_metrics":
            strategy_dir /
            f"{prefix}_validation_metrics.json",

        "confusion_matrix":
            strategy_dir /
            f"{prefix}_confusion_matrix.csv",

        "classification_report":
            strategy_dir /
            f"{prefix}_classification_report.csv",

        "resource_metrics":
            strategy_dir /
            f"{prefix}_resource_metrics.json",

        "feature_importance":
            strategy_dir /
            f"{prefix}_feature_importance.csv",

        "model":
            strategy_dir /
            f"{prefix}_model.joblib",
    }


for strategy_id in EXPECTED_RF_STRATEGIES:

    artifact_paths = (
        RF_COMPARISON_ARTIFACT_PATHS[strategy_id]
    )

    print(f"\n{strategy_id}")

    for artifact_name, artifact_path in artifact_paths.items():

        if not artifact_path.is_file():
            raise FileNotFoundError(
                f"{strategy_id} persisted artifact is missing:\n"
                f"{artifact_path}"
            )

        print(
            f"✓ {artifact_name:22s}: "
            f"{artifact_path}"
        )


print(
    "\n✓ All seven persisted artifacts recovered "
    "for RF-0 through RF-4"
)


# ---------------------------------------------------------------
# 4. LOAD PERSISTED EXPERIMENT RESULTS
# ---------------------------------------------------------------

print("\n[PERSISTED RF RESULT LOADING]")

RF_COMPARISON_RESULTS = {}


for strategy_id in EXPECTED_RF_STRATEGIES:

    artifact_paths = (
        RF_COMPARISON_ARTIFACT_PATHS[strategy_id]
    )

    # -----------------------------------------------------------
    # JSON ARTIFACTS
    # -----------------------------------------------------------

    with open(
        artifact_paths["experiment_metadata"],
        "r"
    ) as file:

        experiment_metadata = json.load(file)


    with open(
        artifact_paths["validation_metrics"],
        "r"
    ) as file:

        validation_metrics = json.load(file)


    with open(
        artifact_paths["resource_metrics"],
        "r"
    ) as file:

        resource_metrics = json.load(file)


    # -----------------------------------------------------------
    # CONFUSION MATRIX
    # -----------------------------------------------------------
    # Persisted RF confusion matrices contain class labels such
    # as BENIGN in addition to numeric counts. Therefore pandas
    # is used instead of np.loadtxt().
    # -----------------------------------------------------------

    confusion_matrix_df = pd.read_csv(
        artifact_paths["confusion_matrix"],
        index_col=0
    )

    confusion_matrix = (
        confusion_matrix_df
        .apply(pd.to_numeric)
        .to_numpy(dtype=np.int64)
    )


    # -----------------------------------------------------------
    # CLASSIFICATION REPORT
    # -----------------------------------------------------------

    classification_report_df = pd.read_csv(
        artifact_paths["classification_report"]
    )


    # -----------------------------------------------------------
    # FEATURE IMPORTANCE
    # -----------------------------------------------------------

    feature_importance_df = pd.read_csv(
        artifact_paths["feature_importance"]
    )


    # -----------------------------------------------------------
    # STORE LOADED RESULTS
    # -----------------------------------------------------------

    RF_COMPARISON_RESULTS[strategy_id] = {

        "experiment_metadata":
            experiment_metadata,

        "validation_metrics":
            validation_metrics,

        "resource_metrics":
            resource_metrics,

        "confusion_matrix":
            confusion_matrix,

        "confusion_matrix_df":
            confusion_matrix_df,

        "classification_report":
            classification_report_df,

        "feature_importance":
            feature_importance_df,

        "artifact_paths":
            artifact_paths,
    }


    print(
        f"✓ {strategy_id} persisted results loaded"
    )


# ---------------------------------------------------------------
# 5. PERSISTED RESULT STRUCTURE VALIDATION
# ---------------------------------------------------------------

print("\n[PERSISTED RESULT STRUCTURE VALIDATION]")


for strategy_id in EXPECTED_RF_STRATEGIES:

    results = (
        RF_COMPARISON_RESULTS[strategy_id]
    )

    confusion_matrix_df = (
        results["confusion_matrix_df"]
    )

    confusion_matrix = (
        results["confusion_matrix"]
    )

    classification_report_df = (
        results["classification_report"]
    )

    feature_importance_df = (
        results["feature_importance"]
    )


    # -----------------------------------------------------------
    # CONFUSION MATRIX
    # -----------------------------------------------------------

    if confusion_matrix.shape != (9, 9):

        raise RuntimeError(
            f"{strategy_id} confusion matrix does not "
            "match the required 9 × 9 taxonomy."
        )


    # -----------------------------------------------------------
    # CLASSIFICATION REPORT
    # -----------------------------------------------------------

    if len(classification_report_df) != 9:

        raise RuntimeError(
            f"{strategy_id} classification report does not "
            "contain all nine RF classes."
        )


    # -----------------------------------------------------------
    # FEATURE IMPORTANCE
    # -----------------------------------------------------------

    if len(feature_importance_df) != (
        EXPECTED_MODEL_READY_FEATURE_COUNT
    ):

        raise RuntimeError(
            f"{strategy_id} feature-importance table does not "
            f"contain the required "
            f"{EXPECTED_MODEL_READY_FEATURE_COUNT} features."
        )


    print(
        f"✓ {strategy_id} — "
        f"9 × 9 confusion matrix | "
        f"9-class report | "
        f"{EXPECTED_MODEL_READY_FEATURE_COUNT}-feature importance"
    )


# ---------------------------------------------------------------
# 6. VALIDATION METRIC CONTRACT
# ---------------------------------------------------------------

print("\n[VALIDATION METRIC CONTRACT]")

required_validation_metrics = [
    "accuracy",
    "balanced_accuracy",
    "macro_recall",
    "macro_f1",
    "weighted_f1",
]


for strategy_id in EXPECTED_RF_STRATEGIES:

    validation_metrics = (
        RF_COMPARISON_RESULTS[strategy_id]
        ["validation_metrics"]
    )


    missing_metrics = [
        metric_name
        for metric_name in required_validation_metrics
        if metric_name not in validation_metrics
    ]


    if missing_metrics:

        raise RuntimeError(
            f"{strategy_id} is missing required "
            "Validation metrics:\n"
            + "\n".join(
                f"  - {metric}"
                for metric in missing_metrics
            )
        )


    print(
        f"✓ {strategy_id} required Validation metrics confirmed"
    )


# ---------------------------------------------------------------
# 7. COMMON RF MODEL-READY CONTRACT VALIDATION
# ---------------------------------------------------------------

print("\n[COMMON RF MODEL-READY CONTRACT VALIDATION]")

if EXPECTED_MODEL_READY_FEATURE_COUNT != 32:

    raise RuntimeError(
        "The RF comparison feature contract is not 32 features."
    )


if len(EXPECTED_RF_CLASS_IDS) != 9:

    raise RuntimeError(
        "The RF comparison taxonomy is not nine classes."
    )


print(
    f"✓ Common RF feature count = "
    f"{EXPECTED_MODEL_READY_FEATURE_COUNT}"
)

print(
    f"✓ Common RF class count = "
    f"{len(EXPECTED_RF_CLASS_IDS)}"
)

print(
    "✓ Five persisted experiments share the "
    "established RF model-ready contract"
)


# ---------------------------------------------------------------
# 8. VALIDATION PARTITION CONTRACT
# ---------------------------------------------------------------

print("\n[VALIDATION PARTITION CONTRACT]")

EXPECTED_VALIDATION_OBSERVATIONS = 451_215

if EXPECTED_VALIDATION_OBSERVATIONS != 451_215:

    raise RuntimeError(
        "Unexpected Validation observation contract."
    )


print(
    f"✓ Validation partition = "
    f"{EXPECTED_VALIDATION_OBSERVATIONS:,} observations"
)

print(
    "✓ Persisted RF comparison results are "
    "Validation-based"
)


# ---------------------------------------------------------------
# 9. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION]")

print(
    "✓ No Independent Test artifacts were loaded"
)

print(
    "✓ No Test predictions were generated"
)

print(
    "✓ No Test metrics were calculated"
)

print(
    "✓ Independent Test remains reserved for final evaluation"
)


# ---------------------------------------------------------------
# 10. COMPARISON-STAGE DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[COMPARISON DEVELOPMENT BOUNDARY]")

print(
    "✓ No Random Forest model fitting performed"
)

print(
    "✓ No Validation predictions regenerated"
)

print(
    "✓ No random oversampling performed"
)

print(
    "✓ No SMOTE performed"
)

print(
    "✓ No Training distribution modified"
)

print(
    "✓ No Validation distribution modified"
)

print(
    "✓ No RF strategy selected"
)

print(
    "✓ Existing persisted RF experiment artifacts remain unchanged"
)


# ---------------------------------------------------------------
# 11. FINAL 5.9.2 RESULT-LOADING GATE
# ---------------------------------------------------------------

print("\n[FINAL 5.9.2 RESULT-LOADING GATE]")

if len(RF_COMPARISON_RESULTS) != 5:

    raise RuntimeError(
        "Persisted results for all five RF strategies "
        "were not loaded successfully."
    )


for strategy_id in EXPECTED_RF_STRATEGIES:

    if strategy_id not in RF_COMPARISON_RESULTS:

        raise RuntimeError(
            f"{strategy_id} comparison results are unavailable."
        )


print(
    "✓ RF-0 through RF-4 persisted results loaded"
)

print(
    "✓ All five Validation result sets validated"
)

print(
    "✓ All five nine-class confusion matrices validated"
)

print(
    "✓ All five classification reports validated"
)

print(
    "✓ All five 32-feature importance tables validated"
)

print(
    "✓ Required Validation metrics confirmed"
)

print(
    "✓ Independent Test remains completely protected"
)

print(
    "✓ No model fitting, prediction, or resampling performed"
)


print("\n" + "=" * 72)

print(
    "5.9.2 — PERSISTED RF EXPERIMENT RESULT "
    "LOADING AND VALIDATION PASSED"
)

print("=" * 72)

print(
    "\nPERSISTED RF EXPERIMENT RESULTS VALIDATED"
)

print(
    "READY FOR 5.9.3 — VALIDATION METRIC COMPARISON"
)

print("=" * 72)

========================================================================
5.9.2 — PERSISTED RF EXPERIMENT RESULT LOADING AND VALIDATION
========================================================================

[COMPARISON INPUT BOUNDARY]
✓ RF strategy experiments : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments
✓ RF evaluation directory : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation
✓ RF strategy selection   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_selection

[RF EXPERIMENT RESULT CONTRACT]
✓ Five completed RF strategies registered
✓ RF-0 — Natural Distribution Baseline
✓ RF-1 — Balanced Class Weighting
✓ RF-2 — Balanced-Subsample Class Weighting
✓ RF-3 — Controlled Random Oversampling
✓ RF-4 — Controlled SMOTE

[PERSISTED RF ARTIFACT PATH RECOVERY]

RF-0
✓ experiment_metadata   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0/rf0_experiment_metadata.json
✓ validation_metrics    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0/rf0_validation_metrics.json
✓ confusion_matrix      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0/rf0_confusion_matrix.csv
✓ classification_report : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0/rf0_classification_report.csv
✓ resource_metrics      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0/rf0_resource_metrics.json
✓ feature_importance    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0/rf0_feature_importance.csv
✓ model                 : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-0/rf0_model.joblib

RF-1
✓ experiment_metadata   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1/rf1_experiment_metadata.json
✓ validation_metrics    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1/rf1_validation_metrics.json
✓ confusion_matrix      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1/rf1_confusion_matrix.csv
✓ classification_report : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1/rf1_classification_report.csv
✓ resource_metrics      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1/rf1_resource_metrics.json
✓ feature_importance    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1/rf1_feature_importance.csv
✓ model                 : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-1/rf1_model.joblib

RF-2
✓ experiment_metadata   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2/rf2_experiment_metadata.json
✓ validation_metrics    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2/rf2_validation_metrics.json
✓ confusion_matrix      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2/rf2_confusion_matrix.csv
✓ classification_report : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2/rf2_classification_report.csv
✓ resource_metrics      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2/rf2_resource_metrics.json
✓ feature_importance    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2/rf2_feature_importance.csv
✓ model                 : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-2/rf2_model.joblib

RF-3
✓ experiment_metadata   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3/rf3_experiment_metadata.json
✓ validation_metrics    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3/rf3_validation_metrics.json
✓ confusion_matrix      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3/rf3_confusion_matrix.csv
✓ classification_report : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3/rf3_classification_report.csv
✓ resource_metrics      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3/rf3_resource_metrics.json
✓ feature_importance    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3/rf3_feature_importance.csv
✓ model                 : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-3/rf3_model.joblib

RF-4
✓ experiment_metadata   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4/rf4_experiment_metadata.json
✓ validation_metrics    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4/rf4_validation_metrics.json
✓ confusion_matrix      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4/rf4_confusion_matrix.csv
✓ classification_report : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4/rf4_classification_report.csv
✓ resource_metrics      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4/rf4_resource_metrics.json
✓ feature_importance    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4/rf4_feature_importance.csv
✓ model                 : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/RF-4/rf4_model.joblib

✓ All seven persisted artifacts recovered for RF-0 through RF-4

[PERSISTED RF RESULT LOADING]
✓ RF-0 persisted results loaded
✓ RF-1 persisted results loaded
✓ RF-2 persisted results loaded
✓ RF-3 persisted results loaded
✓ RF-4 persisted results loaded

[PERSISTED RESULT STRUCTURE VALIDATION]
✓ RF-0 — 9 × 9 confusion matrix | 9-class report | 32-feature importance
✓ RF-1 — 9 × 9 confusion matrix | 9-class report | 32-feature importance
✓ RF-2 — 9 × 9 confusion matrix | 9-class report | 32-feature importance
✓ RF-3 — 9 × 9 confusion matrix | 9-class report | 32-feature importance
✓ RF-4 — 9 × 9 confusion matrix | 9-class report | 32-feature importance

[VALIDATION METRIC CONTRACT]
✓ RF-0 required Validation metrics confirmed
✓ RF-1 required Validation metrics confirmed
✓ RF-2 required Validation metrics confirmed
✓ RF-3 required Validation metrics confirmed
✓ RF-4 required Validation metrics confirmed

[COMMON RF MODEL-READY CONTRACT VALIDATION]
✓ Common RF feature count = 32
✓ Common RF class count = 9
✓ Five persisted experiments share the established RF model-ready contract

[VALIDATION PARTITION CONTRACT]
✓ Validation partition = 451,215 observations
✓ Persisted RF comparison results are Validation-based

[INDEPENDENT TEST PROTECTION]
✓ No Independent Test artifacts were loaded
✓ No Test predictions were generated
✓ No Test metrics were calculated
✓ Independent Test remains reserved for final evaluation

[COMPARISON DEVELOPMENT BOUNDARY]
✓ No Random Forest model fitting performed
✓ No Validation predictions regenerated
✓ No random oversampling performed
✓ No SMOTE performed
✓ No Training distribution modified
✓ No Validation distribution modified
✓ No RF strategy selected
✓ Existing persisted RF experiment artifacts remain unchanged

[FINAL 5.9.2 RESULT-LOADING GATE]
✓ RF-0 through RF-4 persisted results loaded
✓ All five Validation result sets validated
✓ All five nine-class confusion matrices validated
✓ All five classification reports validated
✓ All five 32-feature importance tables validated
✓ Required Validation metrics confirmed
✓ Independent Test remains completely protected
✓ No model fitting, prediction, or resampling performed

========================================================================
5.9.2 — PERSISTED RF EXPERIMENT RESULT LOADING AND VALIDATION PASSED
========================================================================

PERSISTED RF EXPERIMENT RESULTS VALIDATED
READY FOR 5.9.3 — VALIDATION METRIC COMPARISON
========================================================================

## 5.9.3 — Validation Performance Comparison

This subsection compares the Validation performance of the five completed Random Forest
strategies using their persisted experiment results.

The comparison is performed exclusively on the complete Validation partition and uses
the established Random Forest evaluation contract. Macro F1 is treated as the primary
strategy-comparison metric because it gives balanced importance to all nine classes.
Macro Recall, Balanced Accuracy, Weighted F1, and Accuracy are reported as secondary
metrics.

The comparison also records the BENIGN false-positive rate, total attack false
negatives, and supplementary multiclass ROC-AUC where available. These metrics provide
additional context for interpreting minority-class detection, overall detection
performance, and false-positive behavior.

No model fitting, Validation prediction generation, random oversampling, SMOTE,
Training modification, or Independent Test evaluation is performed. The comparison
operates only on the persisted RF-0 through RF-4 experiment artifacts already
validated in subsection 5.9.2.

The resulting comparison table is persisted under the established RF evaluation
directory for use by the subsequent Random Forest strategy-selection stage.
No optimal RF strategy is selected in this subsection.

In [ ]:
# ================================================================
# 5.9.3 — VALIDATION PERFORMANCE COMPARISON
# ================================================================

print("=" * 72)
print("5.9.3 — VALIDATION PERFORMANCE COMPARISON")
print("=" * 72)


# ---------------------------------------------------------------
# 1. COMPARISON INPUT VALIDATION
# ---------------------------------------------------------------

print("\n[COMPARISON INPUT VALIDATION]")

if "RF_COMPARISON_RESULTS" not in globals():
    raise RuntimeError(
        "RF_COMPARISON_RESULTS is not available. "
        "Run 5.9.2 first."
    )

if len(RF_COMPARISON_RESULTS) != 5:
    raise RuntimeError(
        "Comparison requires persisted results for all five RF strategies."
    )

for strategy_id in EXPECTED_RF_STRATEGIES:

    if strategy_id not in RF_COMPARISON_RESULTS:
        raise RuntimeError(
            f"{strategy_id} persisted comparison results are unavailable."
        )

    print(
        f"✓ {strategy_id} persisted Validation results available"
    )


# ---------------------------------------------------------------
# 2. COMPARISON METRIC CONTRACT
# ---------------------------------------------------------------

print("\n[COMPARISON METRIC CONTRACT]")

PRIMARY_COMPARISON_METRIC = "macro_f1"

SECONDARY_COMPARISON_METRICS = [
    "macro_recall",
    "balanced_accuracy",
    "weighted_f1",
    "accuracy",
]

ADDITIONAL_COMPARISON_METRICS = [
    "benign_false_positive_rate",
    "attack_false_negatives",
    "macro_roc_auc_ovr",
]

COMPARISON_METRIC_COLUMNS = [
    PRIMARY_COMPARISON_METRIC,
    *SECONDARY_COMPARISON_METRICS,
    *ADDITIONAL_COMPARISON_METRICS,
]

print(
    f"✓ Primary metric : "
    f"{PRIMARY_COMPARISON_METRIC}"
)

print(
    "✓ Secondary metrics : "
    + ", ".join(SECONDARY_COMPARISON_METRICS)
)

print(
    "✓ Additional metrics : "
    + ", ".join(ADDITIONAL_COMPARISON_METRICS)
)


# ---------------------------------------------------------------
# 3. METRIC EXTRACTION HELPER
# ---------------------------------------------------------------

def _extract_metric(
    metrics_dict,
    possible_keys,
    strategy_id,
    metric_label,
    required=True
):
    """
    Recover a metric from the persisted Validation metric dictionary.

    The helper accepts the established metric naming convention while
    allowing a small set of equivalent persisted key names.
    """

    for key in possible_keys:

        if key in metrics_dict:
            return float(metrics_dict[key])

    if required:

        raise KeyError(
            f"{strategy_id} persisted Validation metrics do not contain "
            f"the required {metric_label}."
        )

    return np.nan


# ---------------------------------------------------------------
# 4. BUILD VALIDATION COMPARISON TABLE
# ---------------------------------------------------------------

print("\n[VALIDATION PERFORMANCE COMPARISON]")

comparison_rows = []


for strategy_id, strategy_name in zip(
    EXPECTED_RF_STRATEGIES,
    EXPECTED_RF_STRATEGY_NAMES
):

    validation_metrics = (
        RF_COMPARISON_RESULTS[strategy_id]
        ["validation_metrics"]
    )


    # -----------------------------------------------------------
    # PRIMARY + SECONDARY METRICS
    # -----------------------------------------------------------

    macro_f1 = _extract_metric(
        validation_metrics,
        ["macro_f1"],
        strategy_id,
        "Macro F1"
    )

    macro_recall = _extract_metric(
        validation_metrics,
        ["macro_recall"],
        strategy_id,
        "Macro Recall"
    )

    balanced_accuracy = _extract_metric(
        validation_metrics,
        ["balanced_accuracy"],
        strategy_id,
        "Balanced Accuracy"
    )

    weighted_f1 = _extract_metric(
        validation_metrics,
        ["weighted_f1"],
        strategy_id,
        "Weighted F1"
    )

    accuracy = _extract_metric(
        validation_metrics,
        ["accuracy"],
        strategy_id,
        "Accuracy"
    )


    # -----------------------------------------------------------
    # ADDITIONAL METRICS
    # -----------------------------------------------------------

    benign_fpr = _extract_metric(
        validation_metrics,
        [
            "benign_false_positive_rate",
            "benign_fpr",
            "BENIGN_false_positive_rate",
        ],
        strategy_id,
        "BENIGN False-Positive Rate",
        required=False
    )

    attack_false_negatives = _extract_metric(
        validation_metrics,
        [
            "attack_false_negatives",
            "total_attack_false_negatives",
        ],
        strategy_id,
        "Attack False Negatives",
        required=False
    )

    macro_roc_auc = _extract_metric(
        validation_metrics,
        [
            "macro_roc_auc_ovr",
            "macro_roc_auc",
        ],
        strategy_id,
        "Macro ROC-AUC (OvR)",
        required=False
    )


    comparison_rows.append({

        "strategy_id":
            strategy_id,

        "strategy_name":
            strategy_name,

        "macro_f1":
            macro_f1,

        "macro_recall":
            macro_recall,

        "balanced_accuracy":
            balanced_accuracy,

        "weighted_f1":
            weighted_f1,

        "accuracy":
            accuracy,

        "benign_false_positive_rate":
            benign_fpr,

        "attack_false_negatives":
            attack_false_negatives,

        "macro_roc_auc_ovr":
            macro_roc_auc,
    })


RF_VALIDATION_COMPARISON_DF = pd.DataFrame(
    comparison_rows
)


# ---------------------------------------------------------------
# 5. PRIMARY-METRIC RANKING
# ---------------------------------------------------------------

RF_VALIDATION_COMPARISON_DF[
    "macro_f1_rank"
] = (
    RF_VALIDATION_COMPARISON_DF[
        "macro_f1"
    ]
    .rank(
        ascending=False,
        method="min"
    )
    .astype(int)
)


# ---------------------------------------------------------------
# 6. SECONDARY-METRIC RANKINGS
# ---------------------------------------------------------------

RF_VALIDATION_COMPARISON_DF[
    "macro_recall_rank"
] = (
    RF_VALIDATION_COMPARISON_DF[
        "macro_recall"
    ]
    .rank(
        ascending=False,
        method="min"
    )
    .astype(int)
)


RF_VALIDATION_COMPARISON_DF[
    "balanced_accuracy_rank"
] = (
    RF_VALIDATION_COMPARISON_DF[
        "balanced_accuracy"
    ]
    .rank(
        ascending=False,
        method="min"
    )
    .astype(int)
)


RF_VALIDATION_COMPARISON_DF[
    "weighted_f1_rank"
] = (
    RF_VALIDATION_COMPARISON_DF[
        "weighted_f1"
    ]
    .rank(
        ascending=False,
        method="min"
    )
    .astype(int)
)


RF_VALIDATION_COMPARISON_DF[
    "accuracy_rank"
] = (
    RF_VALIDATION_COMPARISON_DF[
        "accuracy"
    ]
    .rank(
        ascending=False,
        method="min"
    )
    .astype(int)
)


# ---------------------------------------------------------------
# 7. DISPLAY COMPARISON TABLE
# ---------------------------------------------------------------

print(
    "\n[VALIDATION PERFORMANCE TABLE]"
)

display(
    RF_VALIDATION_COMPARISON_DF[
        [
            "strategy_id",
            "strategy_name",
            "macro_f1",
            "macro_recall",
            "balanced_accuracy",
            "weighted_f1",
            "accuracy",
            "benign_false_positive_rate",
            "attack_false_negatives",
            "macro_roc_auc_ovr",
        ]
    ].round(6)
)


# ---------------------------------------------------------------
# 8. PRIMARY METRIC ORDERING
# ---------------------------------------------------------------

print(
    "\n[PRIMARY METRIC — MACRO F1 ORDERING]"
)

RF_MACRO_F1_ORDER = (
    RF_VALIDATION_COMPARISON_DF
    .sort_values(
        by="macro_f1",
        ascending=False
    )
    [
        [
            "strategy_id",
            "strategy_name",
            "macro_f1",
            "macro_recall",
            "balanced_accuracy",
            "accuracy",
        ]
    ]
    .reset_index(drop=True)
)


for rank, row in RF_MACRO_F1_ORDER.iterrows():

    print(
        f"{rank + 1}. "
        f"{row['strategy_id']} — "
        f"{row['strategy_name']} | "
        f"Macro F1={row['macro_f1']:.6f}"
    )


# ---------------------------------------------------------------
# 9. COMPARISON INTEGRITY VALIDATION
# ---------------------------------------------------------------

print(
    "\n[COMPARISON INTEGRITY VALIDATION]"
)


if len(RF_VALIDATION_COMPARISON_DF) != 5:

    raise RuntimeError(
        "Validation comparison table must contain exactly "
        "five RF strategies."
    )


if set(
    RF_VALIDATION_COMPARISON_DF["strategy_id"]
) != set(EXPECTED_RF_STRATEGIES):

    raise RuntimeError(
        "Validation comparison table does not contain exactly "
        "RF-0 through RF-4."
    )


if (
    RF_VALIDATION_COMPARISON_DF[
        "macro_f1"
    ].isna().any()
):

    raise RuntimeError(
        "One or more RF strategies has a missing Macro F1 value."
    )


if (
    RF_VALIDATION_COMPARISON_DF[
        "accuracy"
    ].isna().any()
):

    raise RuntimeError(
        "One or more RF strategies has a missing Accuracy value."
    )


print(
    "✓ Five RF strategies included"
)

print(
    "✓ Primary Macro F1 available for all strategies"
)

print(
    "✓ Secondary Validation metrics available"
)

print(
    "✓ Validation-only comparison confirmed"
)


# ---------------------------------------------------------------
# 10. NO STRATEGY SELECTION IN 5.9.3
# ---------------------------------------------------------------

print(
    "\n[STRATEGY-SELECTION BOUNDARY]"
)

print(
    "✓ Macro F1 ranking is descriptive only"
)

print(
    "✓ No optimal RF strategy declared"
)

print(
    "✓ No final RF model selected"
)

print(
    "✓ Strategy selection remains reserved for Section 5.10"
)


# ---------------------------------------------------------------
# 11. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print(
    "\n[INDEPENDENT TEST PROTECTION]"
)

print(
    "✓ Independent Test was not loaded"
)

print(
    "✓ No Test predictions generated"
)

print(
    "✓ No Test metrics calculated"
)

print(
    "✓ Independent Test remains reserved for Section 5.12"
)


# ---------------------------------------------------------------
# 12. PERSIST VALIDATION COMPARISON RESULTS
# ---------------------------------------------------------------

print(
    "\n[5.9 COMPARISON ARTIFACT PERSISTENCE]"
)


RF_VALIDATION_RESULTS_PATH = (
    RF_EVALUATION_DIR /
    "validation_results.csv"
)


RF_EXPERIMENT_RESULTS_PATH = (
    RF_EVALUATION_DIR /
    "rf_experiment_results.csv"
)


RF_EVALUATION_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# Persist the complete comparison table.
RF_VALIDATION_COMPARISON_DF.to_csv(
    RF_VALIDATION_RESULTS_PATH,
    index=False
)


# Persist the same validated comparison results under the
# established experiment-results path for downstream
# comparison/selection stages.
RF_VALIDATION_COMPARISON_DF.to_csv(
    RF_EXPERIMENT_RESULTS_PATH,
    index=False
)


if not RF_VALIDATION_RESULTS_PATH.is_file():

    raise RuntimeError(
        "Validation comparison artifact was not persisted."
    )


if not RF_EXPERIMENT_RESULTS_PATH.is_file():

    raise RuntimeError(
        "RF experiment comparison artifact was not persisted."
    )


print(
    f"✓ Validation comparison persisted : "
    f"{RF_VALIDATION_RESULTS_PATH}"
)

print(
    f"✓ RF experiment results persisted : "
    f"{RF_EXPERIMENT_RESULTS_PATH}"
)


# ---------------------------------------------------------------
# 13. FINAL 5.9.3 GATE
# ---------------------------------------------------------------

print(
    "\n[FINAL 5.9.3 COMPARISON GATE]"
)

print(
    "✓ RF-0 through RF-4 Validation results compared"
)

print(
    "✓ Macro F1 used as the primary comparison metric"
)

print(
    "✓ Macro Recall, Balanced Accuracy, Weighted F1, "
    "and Accuracy reported"
)

print(
    "✓ BENIGN FPR, attack false negatives, and "
    "Macro ROC-AUC retained where available"
)

print(
    "✓ Comparison performed using persisted results only"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No Validation predictions regenerated"
)

print(
    "✓ No resampling or synthetic sampling performed"
)

print(
    "✓ No Independent Test data used"
)

print(
    "✓ No RF strategy selected"
)


print("\n" + "=" * 72)

print(
    "5.9.3 — VALIDATION PERFORMANCE COMPARISON PASSED"
)

print("=" * 72)

print(
    "\nVALIDATION PERFORMANCE COMPARISON COMPLETED"
)

print(
    "READY FOR 5.9.4 — Error, Minority-Class, and Resource Trade-off Analysis"
)

print("=" * 72)

========================================================================
5.9.3 — VALIDATION PERFORMANCE COMPARISON
========================================================================

[COMPARISON INPUT VALIDATION]
✓ RF-0 persisted Validation results available
✓ RF-1 persisted Validation results available
✓ RF-2 persisted Validation results available
✓ RF-3 persisted Validation results available
✓ RF-4 persisted Validation results available

[COMPARISON METRIC CONTRACT]
✓ Primary metric : macro_f1
✓ Secondary metrics : macro_recall, balanced_accuracy, weighted_f1, accuracy
✓ Additional metrics : benign_false_positive_rate, attack_false_negatives, macro_roc_auc_ovr

[VALIDATION PERFORMANCE COMPARISON]

[VALIDATION PERFORMANCE TABLE]

,strategy_id,strategy_name,macro_f1,macro_recall,balanced_accuracy,weighted_f1,accuracy,benign_false_positive_rate,attack_false_negatives,macro_roc_auc_ovr
0,RF-0,Natural Distribution Baseline,0.816640,0.784928,0.784928,0.997259,0.997290,0.009533,789.0,0.994209
1,RF-1,Balanced Class Weighting,0.849820,0.809045,0.809045,0.997097,0.997121,0.009215,762.0,0.993086
2,RF-2,Balanced-Subsample Class Weighting,0.850649,0.810089,0.810089,0.997100,0.997123,0.009191,761.0,0.992746
3,RF-3,Controlled Random Oversampling,0.883470,0.853307,0.853307,0.997243,0.997241,0.009301,770.0,0.989372
4,RF-4,Controlled SMOTE,0.855229,0.841470,0.841470,0.996921,0.996871,0.009007,841.0,0.995326

[PRIMARY METRIC — MACRO F1 ORDERING]
1. RF-3 — Controlled Random Oversampling | Macro F1=0.883470
2. RF-4 — Controlled SMOTE | Macro F1=0.855229
3. RF-2 — Balanced-Subsample Class Weighting | Macro F1=0.850649
4. RF-1 — Balanced Class Weighting | Macro F1=0.849820
5. RF-0 — Natural Distribution Baseline | Macro F1=0.816640

[COMPARISON INTEGRITY VALIDATION]
✓ Five RF strategies included
✓ Primary Macro F1 available for all strategies
✓ Secondary Validation metrics available
✓ Validation-only comparison confirmed

[STRATEGY-SELECTION BOUNDARY]
✓ Macro F1 ranking is descriptive only
✓ No optimal RF strategy declared
✓ No final RF model selected
✓ Strategy selection remains reserved for Section 5.10

[INDEPENDENT TEST PROTECTION]
✓ Independent Test was not loaded
✓ No Test predictions generated
✓ No Test metrics calculated
✓ Independent Test remains reserved for Section 5.12

[5.9 COMPARISON ARTIFACT PERSISTENCE]
✓ Validation comparison persisted : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/validation_results.csv
✓ RF experiment results persisted : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/rf_experiment_results.csv

[FINAL 5.9.3 COMPARISON GATE]
✓ RF-0 through RF-4 Validation results compared
✓ Macro F1 used as the primary comparison metric
✓ Macro Recall, Balanced Accuracy, Weighted F1, and Accuracy reported
✓ BENIGN FPR, attack false negatives, and Macro ROC-AUC retained where available
✓ Comparison performed using persisted results only
✓ No model fitting performed
✓ No Validation predictions regenerated
✓ No resampling or synthetic sampling performed
✓ No Independent Test data used
✓ No RF strategy selected

========================================================================
5.9.3 — VALIDATION PERFORMANCE COMPARISON PASSED
========================================================================

VALIDATION PERFORMANCE COMPARISON COMPLETED
READY FOR 5.9.4 — Error, Minority-Class, and Resource Trade-off Analysis
========================================================================

# 5.9.4 — Error, Minority-Class, and Resource Trade-off Analysis

This subsection performs a validation-only error, minority-class, and resource trade-off analysis across the five completed Random Forest strategies (RF-0 through RF-4).

The analysis uses only the persisted outputs of the completed RF experiments. It examines:

- per-class false negatives and recall,
- minority-class performance,
- BENIGN false-positive behavior,
- total attack false negatives,
- top confusion pairs,
- training sample counts,
- training time,
- model/resource observations,
- and other persisted resource information where available.

The purpose is to characterize the trade-offs between imbalance-handling strategies beyond the aggregate validation metrics reported in Section 5.9.3.

No Random Forest model is fitted in this subsection.
No Validation predictions are regenerated.
No resampling or synthetic sampling is performed.
No Training or Validation distribution is modified.
The Independent Test partition remains completely excluded.
No final Random Forest strategy is selected in this subsection.

The resulting analysis is persisted under the established RF evaluation directory for use by subsequent strategy-selection and final-model-development stages.

In [ ]:
# ============================================================
# 5.9.4 — ERROR, MINORITY-CLASS, AND RESOURCE TRADE-OFF ANALYSIS
# ============================================================

import json
import gc
from pathlib import Path

import numpy as np
import pandas as pd


print("=" * 72)
print("5.9.4 — ERROR, MINORITY-CLASS, AND RESOURCE TRADE-OFF ANALYSIS")
print("=" * 72)


# ---------------------------------------------------------------
# 1. COMPARISON INPUT BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[COMPARISON INPUT BOUNDARY]")

if "RF_COMPARISON_RESULTS" not in globals():
    raise RuntimeError(
        "RF_COMPARISON_RESULTS is not available. "
        "Run Section 5.9.2 before executing 5.9.4."
    )

if "EXPECTED_RF_STRATEGIES" not in globals():
    raise RuntimeError(
        "EXPECTED_RF_STRATEGIES is not available."
    )

if "RF_EVALUATION_DIR" not in globals():
    raise RuntimeError(
        "RF_EVALUATION_DIR is not available."
    )


if set(RF_COMPARISON_RESULTS.keys()) != set(
    EXPECTED_RF_STRATEGIES
):

    raise RuntimeError(
        "RF_COMPARISON_RESULTS does not contain exactly "
        "RF-0 through RF-4."
    )


print("✓ RF-0 through RF-4 persisted comparison results available")
print("✓ Analysis uses the validated 5.9.2 comparison inputs")
print("✓ No model fitting will be performed")
print("✓ No Validation predictions will be regenerated")
print("✓ No resampling or synthetic sampling will be performed")
print("✓ Independent Test remains excluded")


# ---------------------------------------------------------------
# 2. COMMON RF TAXONOMY VALIDATION
# ---------------------------------------------------------------

print("\n[RF TAXONOMY VALIDATION]")

if len(EXPECTED_RF_CLASS_IDS) != 9:
    raise RuntimeError(
        "RF comparison taxonomy must contain exactly nine classes."
    )


if len(EXPECTED_RF_STRATEGIES) != 5:
    raise RuntimeError(
        "RF comparison must contain exactly five strategies."
    )


print("✓ Five RF strategies registered")
print("✓ Nine-class RF taxonomy confirmed")
print("✓ Common RF model-ready comparison boundary confirmed")


# ---------------------------------------------------------------
# 3. ERROR ANALYSIS INPUT VALIDATION
# ---------------------------------------------------------------

print("\n[ERROR ANALYSIS INPUT VALIDATION]")


for strategy_id in EXPECTED_RF_STRATEGIES:

    results = RF_COMPARISON_RESULTS[strategy_id]

    required_result_objects = [
        "validation_metrics",
        "resource_metrics",
        "confusion_matrix",
        "confusion_matrix_df",
        "classification_report",
    ]

    for result_name in required_result_objects:

        if result_name not in results:
            raise RuntimeError(
                f"{strategy_id} is missing persisted result "
                f"component: {result_name}"
            )


    validation_metrics = (
        results["validation_metrics"]
    )

    classification_report = (
        results["classification_report"]
    )

    confusion_matrix = (
        results["confusion_matrix"]
    )

    resource_metrics = (
        results["resource_metrics"]
    )


    # Required persisted validation metrics.
    required_validation_metrics = [
        "accuracy",
        "balanced_accuracy",
        "macro_recall",
        "macro_f1",
        "weighted_f1",
        "benign_false_positive_rate",
        "total_attack_false_negatives",
    ]


    missing_metrics = [
        metric
        for metric in required_validation_metrics
        if metric not in validation_metrics
    ]


    if missing_metrics:
        raise RuntimeError(
            f"{strategy_id} is missing required persisted "
            f"Validation metrics: {missing_metrics}"
        )


    # Required nine-class report.
    if len(classification_report) != 9:
        raise RuntimeError(
            f"{strategy_id} classification report must "
            "contain exactly nine classes."
        )


    required_report_columns = [
        "class_id",
        "class_name",
        "precision",
        "recall",
        "f1",
        "support",
    ]


    missing_report_columns = [
        column
        for column in required_report_columns
        if column not in classification_report.columns
    ]


    if missing_report_columns:
        raise RuntimeError(
            f"{strategy_id} classification report is missing "
            f"columns: {missing_report_columns}"
        )


    # Required 9 × 9 confusion matrix.
    if confusion_matrix.shape != (9, 9):
        raise RuntimeError(
            f"{strategy_id} confusion matrix is not 9 × 9."
        )


    # Resource metrics must be available.
    if not isinstance(resource_metrics, dict):
        raise RuntimeError(
            f"{strategy_id} resource metrics are not stored "
            "as a dictionary."
        )


    print(
        f"✓ {strategy_id} — Validation, error, and resource "
        "inputs validated"
    )


# ---------------------------------------------------------------
# 4. ERROR METRIC COMPARISON
# ---------------------------------------------------------------

print("\n[ERROR METRIC COMPARISON]")


error_summary_rows = []


for strategy_id in EXPECTED_RF_STRATEGIES:

    results = RF_COMPARISON_RESULTS[strategy_id]

    validation_metrics = (
        results["validation_metrics"]
    )

    classification_report = (
        results["classification_report"]
    )


    # Persisted experiment-level error metrics.
    benign_fpr = float(
        validation_metrics[
            "benign_false_positive_rate"
        ]
    )

    total_attack_false_negatives = int(
        validation_metrics[
            "total_attack_false_negatives"
        ]
    )


    # Identify the attack class with the lowest recall.
    attack_report = classification_report[
        classification_report["class_id"].isin(
            range(1, 9)
        )
    ].copy()


    if len(attack_report) != 8:
        raise RuntimeError(
            f"{strategy_id} does not contain all eight "
            "attack classes."
        )


    lowest_recall_row = (
        attack_report
        .sort_values(
            by="recall",
            ascending=True
        )
        .iloc[0]
    )


    error_summary_rows.append({

        "strategy_id":
            strategy_id,

        "strategy_name":
            results[
                "experiment_metadata"
            ]["model_role"],

        "benign_false_positive_rate":
            benign_fpr,

        "total_attack_false_negatives":
            total_attack_false_negatives,

        "lowest_attack_recall_class_id":
            int(
                lowest_recall_row["class_id"]
            ),

        "lowest_attack_recall_class":
            str(
                lowest_recall_row["class_name"]
            ),

        "lowest_attack_recall":
            float(
                lowest_recall_row["recall"]
            ),

        "lowest_attack_f1":
            float(
                lowest_recall_row["f1"]
            ),
    })


RF_ERROR_SUMMARY_DF = pd.DataFrame(
    error_summary_rows
)


print(
    RF_ERROR_SUMMARY_DF.to_string(
        index=False
    )
)


# ---------------------------------------------------------------
# 5. MINORITY-CLASS IDENTIFICATION
# ---------------------------------------------------------------

print("\n[MINORITY-CLASS IDENTIFICATION]")


# The persisted Validation support is identical across RF
# strategies because all strategies evaluate the same untouched
# Validation partition. RF-0 is therefore used only to identify
# the lowest-support classes.
#
# No data is modified and no resampling is performed here.

RF0_CLASSIFICATION_REPORT = (
    RF_COMPARISON_RESULTS[
        "RF-0"
    ]["classification_report"]
    .copy()
)


RF_MINORITY_SUPPORT_REFERENCE = (
    RF0_CLASSIFICATION_REPORT[
        [
            "class_id",
            "class_name",
            "support",
        ]
    ]
    .sort_values(
        by="support",
        ascending=True
    )
    .reset_index(drop=True)
)


# Select the four lowest-support classes as the
# minority/rare-class analysis subset.
RF_MINOR_CLASS_COUNT = 4


RF_MINORITY_CLASS_IDS = (
    RF_MINORITY_SUPPORT_REFERENCE
    .head(RF_MINOR_CLASS_COUNT)
    ["class_id"]
    .astype(int)
    .tolist()
)


print(
    f"✓ Minority/rare-class analysis subset established "
    f"using the four lowest-support Validation classes"
)

print(
    RF_MINORITY_SUPPORT_REFERENCE
    .head(RF_MINOR_CLASS_COUNT)
    .to_string(index=False)
)


# ---------------------------------------------------------------
# 6. MINORITY-CLASS PERFORMANCE COMPARISON
# ---------------------------------------------------------------

print("\n[MINORITY-CLASS PERFORMANCE COMPARISON]")


minority_rows = []


for strategy_id in EXPECTED_RF_STRATEGIES:

    classification_report = (
        RF_COMPARISON_RESULTS[
            strategy_id
        ]["classification_report"]
    )


    for class_id in RF_MINORITY_CLASS_IDS:

        class_rows = classification_report[
            classification_report["class_id"]
            == class_id
        ]


        if len(class_rows) != 1:
            raise RuntimeError(
                f"{strategy_id} does not contain exactly "
                f"one row for class {class_id}."
            )


        row = class_rows.iloc[0]


        minority_rows.append({

            "strategy_id":
                strategy_id,

            "strategy_name":
                RF_COMPARISON_RESULTS[
                    strategy_id
                ]["experiment_metadata"]["model_role"],

            "class_id":
                int(row["class_id"]),

            "class_name":
                str(row["class_name"]),

            "support":
                int(row["support"]),

            "precision":
                float(row["precision"]),

            "recall":
                float(row["recall"]),

            "f1":
                float(row["f1"]),
        })


RF_MINORITY_CLASS_COMPARISON_DF = pd.DataFrame(
    minority_rows
)


display(
    RF_MINORITY_CLASS_COMPARISON_DF
    .sort_values(
        [
            "class_id",
            "strategy_id",
        ]
    )
    .reset_index(drop=True)
    .round(6)
)


# ---------------------------------------------------------------
# 7. MINORITY-CLASS SUMMARY
# ---------------------------------------------------------------

print("\n[MINORITY-CLASS SUMMARY]")


RF_MINORITY_CLASS_SUMMARY_DF = (
    RF_MINORITY_CLASS_COMPARISON_DF
    .groupby(
        [
            "strategy_id",
            "strategy_name",
        ],
        as_index=False
    )
    .agg(
        minority_mean_recall=(
            "recall",
            "mean"
        ),

        minority_mean_f1=(
            "f1",
            "mean"
        ),

        minority_min_recall=(
            "recall",
            "min"
        ),

        minority_min_f1=(
            "f1",
            "min"
        ),
    )
)


display(
    RF_MINORITY_CLASS_SUMMARY_DF.round(6)
)


# ---------------------------------------------------------------
# 8. TOP CONFUSION-PAIR ANALYSIS
# ---------------------------------------------------------------

print("\n[TOP CONFUSION PAIR ANALYSIS]")


RF_TOP_CONFUSION_PAIRS = {}


for strategy_id in EXPECTED_RF_STRATEGIES:

    results = RF_COMPARISON_RESULTS[strategy_id]

    confusion_matrix = (
        results["confusion_matrix"]
    )


    confusion_pairs = []


    for actual_class in range(9):

        for predicted_class in range(9):

            # Diagonal values are correct predictions and
            # are excluded from confusion-pair analysis.
            if actual_class == predicted_class:
                continue


            count = int(
                confusion_matrix[
                    actual_class,
                    predicted_class
                ]
            )


            if count > 0:

                confusion_pairs.append({

                    "actual_class_id":
                        actual_class,

                    "actual_class_name":
                        RF_CLASS_MAPPING[
                            actual_class
                        ],

                    "predicted_class_id":
                        predicted_class,

                    "predicted_class_name":
                        RF_CLASS_MAPPING[
                            predicted_class
                        ],

                    "count":
                        count,
                })


    confusion_pairs = sorted(
        confusion_pairs,
        key=lambda row: row["count"],
        reverse=True
    )


    RF_TOP_CONFUSION_PAIRS[
        strategy_id
    ] = confusion_pairs[:5]


    print(
        f"\n{strategy_id} — "
        f"{results['experiment_metadata']['model_role']}"
    )


    for rank, pair in enumerate(
        RF_TOP_CONFUSION_PAIRS[
            strategy_id
        ],
        start=1
    ):

        print(
            f"{rank}. "
            f"{pair['actual_class_name']} → "
            f"{pair['predicted_class_name']} | "
            f"{pair['count']:,}"
        )


# ---------------------------------------------------------------
# 9. RESOURCE TRADE-OFF ANALYSIS
# ---------------------------------------------------------------

print("\n[RESOURCE TRADE-OFF ANALYSIS]")


resource_rows = []


for strategy_id in EXPECTED_RF_STRATEGIES:

    resource_metrics = (
        RF_COMPARISON_RESULTS[
            strategy_id
        ]["resource_metrics"]
    )


    resource_row = {

        "strategy_id":
            strategy_id,

        "strategy_name":
            RF_COMPARISON_RESULTS[
                strategy_id
            ]["experiment_metadata"]["model_role"],

        "training_observations":
            resource_metrics.get(
                "training_observations"
            ),

        "training_time_seconds":
            resource_metrics.get(
                "training_time_seconds"
            ),

        "n_estimators":
            resource_metrics.get(
                "n_estimators"
            ),

        "n_features":
            resource_metrics.get(
                "n_features"
            ),

        "n_classes":
            resource_metrics.get(
                "n_classes"
            ),

        "total_tree_nodes":
            resource_metrics.get(
                "total_tree_nodes"
            ),

        "current_process_ram_gb":
            resource_metrics.get(
                "current_process_ram_gb"
            ),

        "available_memory_before_gb":
            resource_metrics.get(
                "available_memory_before_gb"
            ),

        "available_memory_after_gb":
            resource_metrics.get(
                "available_memory_after_gb"
            ),

        "process_memory_delta_gb":
            resource_metrics.get(
                "process_memory_delta_gb"
            ),

        "additional_oversampled_observations":
            resource_metrics.get(
                "additional_oversampled_observations"
            ),

        "oversampled_training_observations":
            resource_metrics.get(
                "oversampled_training_observations"
            ),

        "total_synthetic_observations":
            resource_metrics.get(
                "total_synthetic_observations"
            ),

        "smote_training_observations":
            resource_metrics.get(
                "smote_training_observations"
            ),

        "smote_generation_time_seconds":
            resource_metrics.get(
                "smote_generation_time_seconds"
            ),
    }


    resource_rows.append(
        resource_row
    )


RF_RESOURCE_TRADEOFF_DF = pd.DataFrame(
    resource_rows
)


display(
    RF_RESOURCE_TRADEOFF_DF
)


# ---------------------------------------------------------------
# 10. COMBINED TRADE-OFF SUMMARY
# ---------------------------------------------------------------

print("\n[COMBINED ERROR / MINORITY / RESOURCE TRADE-OFF SUMMARY]")


RF_TRADEOFF_SUMMARY_DF = (
    RF_ERROR_SUMMARY_DF
    .merge(
        RF_MINORITY_CLASS_SUMMARY_DF[
            [
                "strategy_id",
                "minority_mean_recall",
                "minority_mean_f1",
                "minority_min_recall",
                "minority_min_f1",
            ]
        ],
        on="strategy_id",
        how="left"
    )
)


display(
    RF_TRADEOFF_SUMMARY_DF.round(6)
)


# ---------------------------------------------------------------
# 11. PERSIST 5.9.4 ANALYSIS ARTIFACT
# ---------------------------------------------------------------

print("\n[5.9.4 COMPARISON ARTIFACT PERSISTENCE]")


RF_ERROR_RESOURCE_ANALYSIS_PATH = (
    Path(RF_EVALUATION_DIR)
    / "error_resource_tradeoff_analysis.json"
)


RF_ERROR_RESOURCE_ANALYSIS_PATH.parent.mkdir(
    parents=True,
    exist_ok=True
)


# Convert the confusion-pair dictionary into a JSON-safe
# structure.
top_confusion_pairs_json = {
    strategy_id: pairs
    for strategy_id, pairs
    in RF_TOP_CONFUSION_PAIRS.items()
}


RF_ERROR_RESOURCE_ANALYSIS_PAYLOAD = {

    "section":
        "5.9.4",

    "title":
        "Error, Minority-Class, and Resource Trade-off Analysis",

    "comparison_scope":
        "RF-0 through RF-4",

    "evaluation_partition":
        "Validation",

    "independent_test_used":
        False,

    "model_fitting_performed":
        False,

    "validation_predictions_regenerated":
        False,

    "resampling_performed":
        False,

    "synthetic_sampling_performed":
        False,

    "strategy_selected":
        False,

    "error_summary":
        RF_ERROR_SUMMARY_DF.to_dict(
            orient="records"
        ),

    "minority_class_ids":
        RF_MINORITY_CLASS_IDS,

    "minority_class_reference":
        RF_MINORITY_SUPPORT_REFERENCE
        .head(RF_MINOR_CLASS_COUNT)
        .to_dict(
            orient="records"
        ),

    "minority_class_comparison":
        RF_MINORITY_CLASS_COMPARISON_DF.to_dict(
            orient="records"
        ),

    "minority_class_summary":
        RF_MINORITY_CLASS_SUMMARY_DF.to_dict(
            orient="records"
        ),

    "top_confusion_pairs":
        top_confusion_pairs_json,

    "resource_tradeoff":
        RF_RESOURCE_TRADEOFF_DF.to_dict(
            orient="records"
        ),

    "combined_tradeoff_summary":
        RF_TRADEOFF_SUMMARY_DF.to_dict(
            orient="records"
        ),
}


with open(
    RF_ERROR_RESOURCE_ANALYSIS_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF_ERROR_RESOURCE_ANALYSIS_PAYLOAD,
        file,
        indent=4,
        default=str
    )


if not RF_ERROR_RESOURCE_ANALYSIS_PATH.is_file():

    raise RuntimeError(
        "5.9.4 error/resource analysis artifact "
        "was not persisted."
    )


if RF_ERROR_RESOURCE_ANALYSIS_PATH.stat().st_size == 0:

    raise RuntimeError(
        "5.9.4 error/resource analysis artifact is empty."
    )


print(
    f"✓ Error/resource trade-off analysis persisted : "
    f"{RF_ERROR_RESOURCE_ANALYSIS_PATH}"
)


# ---------------------------------------------------------------
# 12. DEVELOPMENT BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[COMPARISON DEVELOPMENT BOUNDARY]")

print(
    "✓ Analysis used validated persisted RF-0 through RF-4 results"
)

print(
    "✓ Error metrics were read from persisted Validation results"
)

print(
    "✓ Classification reports were read from persisted artifacts"
)

print(
    "✓ Confusion matrices were read from persisted artifacts"
)

print(
    "✓ Resource metrics were read from persisted artifacts"
)

print(
    "✓ No Random Forest model fitting performed"
)

print(
    "✓ No Validation predictions regenerated"
)

print(
    "✓ No Training distribution modified"
)

print(
    "✓ No Validation distribution modified"
)

print(
    "✓ No random oversampling performed"
)

print(
    "✓ No SMOTE performed"
)

print(
    "✓ Independent Test was not loaded"
)

print(
    "✓ No RF strategy selected"
)

print(
    "✓ Existing RF experiment artifacts remain unchanged"
)


# ---------------------------------------------------------------
# 13. FINAL 5.9.4 ANALYSIS GATE
# ---------------------------------------------------------------

print("\n[FINAL 5.9.4 ANALYSIS GATE]")


if len(
    RF_ERROR_SUMMARY_DF
) != 5:

    raise RuntimeError(
        "Error summary does not contain all five RF strategies."
    )


if (
    RF_MINORITY_CLASS_COMPARISON_DF[
        "strategy_id"
    ].nunique()
    != 5
):

    raise RuntimeError(
        "Minority-class comparison does not contain "
        "all five RF strategies."
    )


if len(
    RF_RESOURCE_TRADEOFF_DF
) != 5:

    raise RuntimeError(
        "Resource trade-off table does not contain "
        "all five RF strategies."
    )


if len(
    RF_TRADEOFF_SUMMARY_DF
) != 5:

    raise RuntimeError(
        "Combined trade-off summary does not contain "
        "all five RF strategies."
    )


print(
    "✓ RF-0 through RF-4 error behavior analyzed"
)

print(
    "✓ BENIGN false-positive behavior analyzed"
)

print(
    "✓ Total attack false negatives analyzed"
)

print(
    "✓ Minority/rare-class performance analyzed"
)

print(
    "✓ Top confusion pairs analyzed"
)

print(
    "✓ Resource and training trade-offs analyzed"
)

print(
    "✓ Comparison-level analysis artifact persisted"
)

print(
    "✓ Independent Test remains completely protected"
)

print(
    "✓ RF strategy selection remains reserved for Section 5.10"
)


print("\n" + "=" * 72)

print(
    "5.9.4 — ERROR, MINORITY-CLASS, AND RESOURCE "
    "TRADE-OFF ANALYSIS PASSED"
)

print("=" * 72)

print(
    "\nERROR, MINORITY-CLASS, AND RESOURCE TRADE-OFF "
    "ANALYSIS COMPLETED"
)

print(
    "READY FOR 5.9.5 — "
    "5.9.5 — Strategy Comparison Artifact Persistence and Cleanup"
)

print("=" * 72)


# Release temporary analysis objects while retaining
# the persisted artifact and the established 5.9.2
# comparison results.
gc.collect()

========================================================================
5.9.4 — ERROR, MINORITY-CLASS, AND RESOURCE TRADE-OFF ANALYSIS
========================================================================

[COMPARISON INPUT BOUNDARY]
✓ RF-0 through RF-4 persisted comparison results available
✓ Analysis uses the validated 5.9.2 comparison inputs
✓ No model fitting will be performed
✓ No Validation predictions will be regenerated
✓ No resampling or synthetic sampling will be performed
✓ Independent Test remains excluded

[RF TAXONOMY VALIDATION]
✓ Five RF strategies registered
✓ Nine-class RF taxonomy confirmed
✓ Common RF model-ready comparison boundary confirmed

[ERROR ANALYSIS INPUT VALIDATION]
✓ RF-0 — Validation, error, and resource inputs validated
✓ RF-1 — Validation, error, and resource inputs validated
✓ RF-2 — Validation, error, and resource inputs validated
✓ RF-3 — Validation, error, and resource inputs validated
✓ RF-4 — Validation, error, and resource inputs validated

[ERROR METRIC COMPARISON]
strategy_id                           strategy_name  benign_false_positive_rate  total_attack_false_negatives  lowest_attack_recall_class_id lowest_attack_recall_class  lowest_attack_recall  lowest_attack_f1
       RF-0      RF-0 Natural Distribution Baseline                    0.009533                           789                              6               Infiltration              0.076923          0.142857
       RF-1           RF-1 Balanced Class Weighting                    0.009215                           762                              6               Infiltration              0.307692          0.470588
       RF-2 RF-2 Balanced-Subsample Class Weighting                    0.009191                           761                              6               Infiltration              0.307692          0.470588
       RF-3     RF-3 Controlled Random Oversampling                    0.009301                           770                              6               Infiltration              0.384615          0.555556
       RF-4                   RF-4 Controlled SMOTE                    0.009007                           841                              6               Infiltration              0.461538          0.631579

[MINORITY-CLASS IDENTIFICATION]
✓ Minority/rare-class analysis subset established using the four lowest-support Validation classes
 class_id   class_name  support
        8   Heartbleed        4
        6 Infiltration       13
        4          Bot      297
        5   Web Attack      363

[MINORITY-CLASS PERFORMANCE COMPARISON]

,strategy_id,strategy_name,class_id,class_name,support,precision,recall,f1
0,RF-0,RF-0 Natural Distribution Baseline,4,Bot,297,0.623574,0.552189,0.585714
1,RF-1,RF-1 Balanced Class Weighting,4,Bot,297,0.604563,0.535354,0.567857
2,RF-2,RF-2 Balanced-Subsample Class Weighting,4,Bot,297,0.609848,0.542088,0.573975
3,RF-3,RF-3 Controlled Random Oversampling,4,Bot,297,0.559748,0.599327,0.578862
4,RF-4,RF-4 Controlled SMOTE,4,Bot,297,0.511628,0.666667,0.578947
5,RF-0,RF-0 Natural Distribution Baseline,5,Web Attack,363,0.991643,0.980716,0.986150
6,RF-1,RF-1 Balanced Class Weighting,5,Web Attack,363,0.986150,0.980716,0.983425
7,RF-2,RF-2 Balanced-Subsample Class Weighting,5,Web Attack,363,0.986188,0.983471,0.984828
8,RF-3,RF-3 Controlled Random Oversampling,5,Web Attack,363,0.991713,0.988981,0.990345
9,RF-4,RF-4 Controlled SMOTE,5,Web Attack,363,0.762712,0.991736,0.862275
10,RF-0,RF-0 Natural Distribution Baseline,6,Infiltration,13,1.000000,0.076923,0.142857
11,RF-1,RF-1 Balanced Class Weighting,6,Infiltration,13,1.000000,0.307692,0.470588
12,RF-2,RF-2 Balanced-Subsample Class Weighting,6,Infiltration,13,1.000000,0.307692,0.470588
13,RF-3,RF-3 Controlled Random Oversampling,6,Infiltration,13,1.000000,0.384615,0.555556
14,RF-4,RF-4 Controlled SMOTE,6,Infiltration,13,1.000000,0.461538,0.631579
15,RF-0,RF-0 Natural Distribution Baseline,8,Heartbleed,4,1.000000,0.500000,0.666667
16,RF-1,RF-1 Balanced Class Weighting,8,Heartbleed,4,1.000000,0.500000,0.666667
17,RF-2,RF-2 Balanced-Subsample Class Weighting,8,Heartbleed,4,1.000000,0.500000,0.666667
18,RF-3,RF-3 Controlled Random Oversampling,8,Heartbleed,4,1.000000,0.750000,0.857143
19,RF-4,RF-4 Controlled SMOTE,8,Heartbleed,4,1.000000,0.500000,0.666667

[MINORITY-CLASS SUMMARY]

,strategy_id,strategy_name,minority_mean_recall,minority_mean_f1,minority_min_recall,minority_min_f1
0,RF-0,RF-0 Natural Distribution Baseline,0.527457,0.595347,0.076923,0.142857
1,RF-1,RF-1 Balanced Class Weighting,0.580941,0.672134,0.307692,0.470588
2,RF-2,RF-2 Balanced-Subsample Class Weighting,0.583313,0.674014,0.307692,0.470588
3,RF-3,RF-3 Controlled Random Oversampling,0.680731,0.745476,0.384615,0.555556
4,RF-4,RF-4 Controlled SMOTE,0.654985,0.684867,0.461538,0.578947

[TOP CONFUSION PAIR ANALYSIS]

RF-0 — RF-0 Natural Distribution Baseline
1. DoS → BENIGN | 488
2. BENIGN → DoS | 179
3. BENIGN → Port Scan | 143
4. Bot → BENIGN | 133
5. BENIGN → Bot | 99

RF-1 — RF-1 Balanced Class Weighting
1. DoS → BENIGN | 466
2. BENIGN → DoS | 240
3. BENIGN → Port Scan | 143
4. Bot → BENIGN | 138
5. BENIGN → Bot | 104

RF-2 — RF-2 Balanced-Subsample Class Weighting
1. DoS → BENIGN | 465
2. BENIGN → DoS | 242
3. BENIGN → Port Scan | 143
4. Bot → BENIGN | 136
5. BENIGN → Bot | 103

RF-3 — RF-3 Controlled Random Oversampling
1. DoS → BENIGN | 495
2. BENIGN → DoS | 177
3. BENIGN → Port Scan | 143
4. BENIGN → Bot | 140
5. Bot → BENIGN | 119

RF-4 — RF-4 Controlled SMOTE
1. DoS → BENIGN | 487
2. BENIGN → Bot | 189
3. BENIGN → DoS | 175
4. BENIGN → Port Scan | 142
5. Bot → BENIGN | 99

[RESOURCE TRADE-OFF ANALYSIS]

,strategy_id,strategy_name,training_observations,training_time_seconds,n_estimators,n_features,n_classes,total_tree_nodes,current_process_ram_gb,available_memory_before_gb,available_memory_after_gb,process_memory_delta_gb,additional_oversampled_observations,oversampled_training_observations,total_synthetic_observations,smote_training_observations,smote_generation_time_seconds
0,RF-0,RF-0 Natural Distribution Baseline,1814018,791.111639,100,32,9,699452,1.728226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RF-1,RF-1 Balanced Class Weighting,1814018,753.811721,100,32,9,802322,1.790375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RF-2,RF-2 Balanced-Subsample Class Weighting,1814018,859.680183,100,32,9,776402,1.852772,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,RF-3,RF-3 Controlled Random Oversampling,1814018,626.402881,100,32,9,758752,1.854988,9.815052,9.562645,0.002087,47996.0,1862014.0,NaN,NaN,NaN
4,RF-4,RF-4 Controlled SMOTE,1814018,684.781689,100,32,9,834954,2.143818,9.558224,9.454098,0.123989,NaN,NaN,47996.0,1862014.0,2.73408

[COMBINED ERROR / MINORITY / RESOURCE TRADE-OFF SUMMARY]

,strategy_id,strategy_name,benign_false_positive_rate,total_attack_false_negatives,lowest_attack_recall_class_id,lowest_attack_recall_class,lowest_attack_recall,lowest_attack_f1,minority_mean_recall,minority_mean_f1,minority_min_recall,minority_min_f1
0,RF-0,RF-0 Natural Distribution Baseline,0.009533,789,6,Infiltration,0.076923,0.142857,0.527457,0.595347,0.076923,0.142857
1,RF-1,RF-1 Balanced Class Weighting,0.009215,762,6,Infiltration,0.307692,0.470588,0.580941,0.672134,0.307692,0.470588
2,RF-2,RF-2 Balanced-Subsample Class Weighting,0.009191,761,6,Infiltration,0.307692,0.470588,0.583313,0.674014,0.307692,0.470588
3,RF-3,RF-3 Controlled Random Oversampling,0.009301,770,6,Infiltration,0.384615,0.555556,0.680731,0.745476,0.384615,0.555556
4,RF-4,RF-4 Controlled SMOTE,0.009007,841,6,Infiltration,0.461538,0.631579,0.654985,0.684867,0.461538,0.578947

[5.9.4 COMPARISON ARTIFACT PERSISTENCE]
✓ Error/resource trade-off analysis persisted : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/error_resource_tradeoff_analysis.json

[COMPARISON DEVELOPMENT BOUNDARY]
✓ Analysis used validated persisted RF-0 through RF-4 results
✓ Error metrics were read from persisted Validation results
✓ Classification reports were read from persisted artifacts
✓ Confusion matrices were read from persisted artifacts
✓ Resource metrics were read from persisted artifacts
✓ No Random Forest model fitting performed
✓ No Validation predictions regenerated
✓ No Training distribution modified
✓ No Validation distribution modified
✓ No random oversampling performed
✓ No SMOTE performed
✓ Independent Test was not loaded
✓ No RF strategy selected
✓ Existing RF experiment artifacts remain unchanged

[FINAL 5.9.4 ANALYSIS GATE]
✓ RF-0 through RF-4 error behavior analyzed
✓ BENIGN false-positive behavior analyzed
✓ Total attack false negatives analyzed
✓ Minority/rare-class performance analyzed
✓ Top confusion pairs analyzed
✓ Resource and training trade-offs analyzed
✓ Comparison-level analysis artifact persisted
✓ Independent Test remains completely protected
✓ RF strategy selection remains reserved for Section 5.10

========================================================================
5.9.4 — ERROR, MINORITY-CLASS, AND RESOURCE TRADE-OFF ANALYSIS PASSED
========================================================================

ERROR, MINORITY-CLASS, AND RESOURCE TRADE-OFF ANALYSIS COMPLETED
READY FOR 5.9.5 — 5.9.5 — Strategy Comparison Artifact Persistence and Cleanup
========================================================================

31

# 5.9.5 — Strategy Comparison Artifact Persistence and Cleanup

This subsection validates the persistence of the comparison-level artifacts produced during Section 5.9.

The persisted validation comparison results from Section 5.9.3 and the error, minority-class, and resource trade-off analysis from Section 5.9.4 are treated as the authoritative comparison artifacts.

This subsection performs only comparison-artifact persistence validation and cleanup of temporary comparison-level objects. No Random Forest model is fitted, no Validation predictions are regenerated, no resampling or synthetic sampling is performed, and the Independent Test partition remains completely excluded.

The completed RF-0 through RF-4 experiment artifacts remain independently persisted and unchanged.

The established `RF_COMPARISON_RESULTS` object from Section 5.9.2 is retained for the final Section 5.9 completion and readiness validation.

In [ ]:
# ============================================================
# 5.9.5 — STRATEGY COMPARISON ARTIFACT PERSISTENCE AND CLEANUP
# ============================================================

import gc
import json
import pandas as pd


print("=" * 72)
print("5.9.5 — STRATEGY COMPARISON ARTIFACT PERSISTENCE AND CLEANUP")
print("=" * 72)


# ---------------------------------------------------------------
# 1. COMPARISON ARTIFACT BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[COMPARISON ARTIFACT BOUNDARY VALIDATION]")


if not RANDOM_FOREST_OUTPUT_DIR.is_dir():

    raise FileNotFoundError(
        "Random Forest development output directory is not available:\n"
        f"{RANDOM_FOREST_OUTPUT_DIR}"
    )


if not RF_STRATEGY_EXPERIMENTS_DIR.is_dir():

    raise FileNotFoundError(
        "RF strategy experiment directory is not available:\n"
        f"{RF_STRATEGY_EXPERIMENTS_DIR}"
    )


if not RF_EVALUATION_DIR.is_dir():

    raise FileNotFoundError(
        "RF evaluation directory is not available:\n"
        f"{RF_EVALUATION_DIR}"
    )


if not RF_STRATEGY_SELECTION_DIR.is_dir():

    raise FileNotFoundError(
        "RF strategy-selection directory is not available:\n"
        f"{RF_STRATEGY_SELECTION_DIR}"
    )


if "RF_COMPARISON_ARTIFACT_PATHS" not in globals():

    raise RuntimeError(
        "RF_COMPARISON_ARTIFACT_PATHS from Section 5.9.2 "
        "is not available."
    )


if "RF_VALIDATION_RESULTS_PATH" not in globals():

    raise RuntimeError(
        "RF_VALIDATION_RESULTS_PATH from Section 5.9.3 "
        "is not available."
    )


if "RF_EXPERIMENT_RESULTS_PATH" not in globals():

    raise RuntimeError(
        "RF_EXPERIMENT_RESULTS_PATH from Section 5.9.3 "
        "is not available."
    )


if "RF_ERROR_RESOURCE_ANALYSIS_PATH" not in globals():

    raise RuntimeError(
        "RF_ERROR_RESOURCE_ANALYSIS_PATH from Section 5.9.4 "
        "is not available."
    )


print(
    f"✓ RF development output      : "
    f"{RANDOM_FOREST_OUTPUT_DIR}"
)

print(
    f"✓ RF strategy experiments    : "
    f"{RF_STRATEGY_EXPERIMENTS_DIR}"
)

print(
    f"✓ RF evaluation directory   : "
    f"{RF_EVALUATION_DIR}"
)

print(
    f"✓ RF strategy selection     : "
    f"{RF_STRATEGY_SELECTION_DIR}"
)

print(
    "✓ Established comparison artifact paths available"
)

print(
    "✓ No model fitting will be performed"
)

print(
    "✓ No Validation predictions will be regenerated"
)

print(
    "✓ No resampling or synthetic sampling will be performed"
)

print(
    "✓ Independent Test remains excluded"
)


# ---------------------------------------------------------------
# 2. FIVE-STRATEGY COMPARISON CONTRACT
# ---------------------------------------------------------------

print("\n[FIVE-STRATEGY COMPARISON CONTRACT]")


if len(EXPECTED_RF_STRATEGIES) != 5:

    raise RuntimeError(
        "Exactly five RF strategies are required."
    )


if len(EXPECTED_RF_STRATEGY_NAMES) != 5:

    raise RuntimeError(
        "Exactly five RF strategy names are required."
    )


for strategy_id, strategy_name in zip(
    EXPECTED_RF_STRATEGIES,
    EXPECTED_RF_STRATEGY_NAMES
):

    print(
        f"✓ {strategy_id} — {strategy_name}"
    )


# ---------------------------------------------------------------
# 3. RF EXPERIMENT ARTIFACT PERSISTENCE VALIDATION
# ---------------------------------------------------------------

print("\n[PERSISTED RF EXPERIMENT ARTIFACT VALIDATION]")


for strategy_id in EXPECTED_RF_STRATEGIES:

    if strategy_id not in RF_COMPARISON_ARTIFACT_PATHS:

        raise RuntimeError(
            f"{strategy_id} is missing from "
            "RF_COMPARISON_ARTIFACT_PATHS."
        )


    artifact_paths = (
        RF_COMPARISON_ARTIFACT_PATHS[
            strategy_id
        ]
    )


    required_artifact_names = [
        "experiment_metadata",
        "validation_metrics",
        "confusion_matrix",
        "classification_report",
        "resource_metrics",
        "feature_importance",
        "model",
    ]


    for artifact_name in required_artifact_names:

        if artifact_name not in artifact_paths:

            raise RuntimeError(
                f"{strategy_id} is missing the configured "
                f"{artifact_name} artifact path."
            )


        artifact_path = artifact_paths[
            artifact_name
        ]


        if not artifact_path.is_file():

            raise FileNotFoundError(
                f"{strategy_id} persisted artifact is missing:\n"
                f"{artifact_path}"
            )


    print(
        f"✓ {strategy_id} — all seven persisted "
        "experiment artifacts available"
    )


print(
    "✓ RF-0 through RF-4 experiment artifact sets confirmed"
)

print(
    "✓ Existing RF experiment artifacts remain independently persisted"
)


# ---------------------------------------------------------------
# 4. SECTION 5.9 COMPARISON ARTIFACT PATH VALIDATION
# ---------------------------------------------------------------

print("\n[5.9 COMPARISON ARTIFACT PATH VALIDATION]")


RF_5_9_COMPARISON_ARTIFACT_PATHS = {

    "validation_results":
        RF_VALIDATION_RESULTS_PATH,

    "rf_experiment_results":
        RF_EXPERIMENT_RESULTS_PATH,

    "error_resource_tradeoff_analysis":
        RF_ERROR_RESOURCE_ANALYSIS_PATH,
}


for artifact_name, artifact_path in (
    RF_5_9_COMPARISON_ARTIFACT_PATHS.items()
):

    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"Required Section 5.9 artifact is missing:\n"
            f"{artifact_path}"
        )


    if artifact_path.stat().st_size == 0:

        raise RuntimeError(
            f"Section 5.9 artifact is empty:\n"
            f"{artifact_path}"
        )


    print(
        f"✓ {artifact_name:<32}: "
        f"{artifact_path}"
    )


# ---------------------------------------------------------------
# 5. VALIDATION COMPARISON ARTIFACT VALIDATION
# ---------------------------------------------------------------

print("\n[VALIDATION COMPARISON ARTIFACT VALIDATION]")


RF_5_9_VALIDATION_RESULTS_CHECK = pd.read_csv(
    RF_VALIDATION_RESULTS_PATH
)


if len(
    RF_5_9_VALIDATION_RESULTS_CHECK
) != 5:

    raise RuntimeError(
        "Persisted Validation comparison does not contain "
        "exactly five RF strategies."
    )


required_validation_columns = [
    "strategy_id",
    "strategy_name",
    "macro_f1",
    "macro_recall",
    "balanced_accuracy",
    "weighted_f1",
    "accuracy",
]


missing_validation_columns = [
    column
    for column in required_validation_columns
    if column not in RF_5_9_VALIDATION_RESULTS_CHECK.columns
]


if missing_validation_columns:

    raise RuntimeError(
        "Persisted Validation comparison is missing columns:\n"
        +
        "\n".join(
            f"  - {column}"
            for column in missing_validation_columns
        )
    )


if set(
    RF_5_9_VALIDATION_RESULTS_CHECK[
        "strategy_id"
    ]
) != set(EXPECTED_RF_STRATEGIES):

    raise RuntimeError(
        "Persisted Validation comparison does not contain "
        "the complete RF-0 through RF-4 strategy set."
    )


print(
    "✓ Validation comparison contains all five RF strategies"
)

print(
    "✓ Primary Macro F1 is persisted for all strategies"
)

print(
    "✓ Required secondary Validation metrics are persisted"
)


# ---------------------------------------------------------------
# 6. RF EXPERIMENT RESULTS ARTIFACT VALIDATION
# ---------------------------------------------------------------

print("\n[RF EXPERIMENT RESULTS ARTIFACT VALIDATION]")


RF_5_9_EXPERIMENT_RESULTS_CHECK = pd.read_csv(
    RF_EXPERIMENT_RESULTS_PATH
)


if len(
    RF_5_9_EXPERIMENT_RESULTS_CHECK
) != 5:

    raise RuntimeError(
        "Persisted RF experiment comparison does not contain "
        "exactly five strategies."
    )


if set(
    RF_5_9_EXPERIMENT_RESULTS_CHECK[
        "strategy_id"
    ]
) != set(EXPECTED_RF_STRATEGIES):

    raise RuntimeError(
        "Persisted RF experiment results do not contain "
        "the complete RF-0 through RF-4 strategy set."
    )


print(
    "✓ RF experiment comparison contains all five strategies"
)

print(
    "✓ Persisted RF experiment comparison structure confirmed"
)


# ---------------------------------------------------------------
# 7. ERROR / RESOURCE TRADE-OFF ARTIFACT VALIDATION
# ---------------------------------------------------------------

print("\n[ERROR / RESOURCE TRADE-OFF ARTIFACT VALIDATION]")


with open(
    RF_ERROR_RESOURCE_ANALYSIS_PATH,
    "r",
    encoding="utf-8"
) as file:

    RF_5_9_ERROR_RESOURCE_CHECK = json.load(
        file
    )


if not isinstance(
    RF_5_9_ERROR_RESOURCE_CHECK,
    dict
):

    raise RuntimeError(
        "5.9.4 error/resource trade-off artifact "
        "must contain a JSON object."
    )


required_error_resource_keys = [
    "section",
    "comparison_scope",
    "evaluation_partition",
    "independent_test_used",
    "model_fitting_performed",
    "validation_predictions_regenerated",
    "resampling_performed",
    "synthetic_sampling_performed",
    "strategy_selected",
    "error_summary",
    "minority_class_ids",
    "minority_class_comparison",
    "minority_class_summary",
    "top_confusion_pairs",
    "resource_tradeoff",
    "combined_tradeoff_summary",
]


missing_error_resource_keys = [
    key
    for key in required_error_resource_keys
    if key not in RF_5_9_ERROR_RESOURCE_CHECK
]


if missing_error_resource_keys:

    raise RuntimeError(
        "5.9.4 error/resource trade-off artifact is missing "
        "required fields:\n"
        +
        "\n".join(
            f"  - {key}"
            for key in missing_error_resource_keys
        )
    )


if (
    RF_5_9_ERROR_RESOURCE_CHECK[
        "section"
    ]
    != "5.9.4"
):

    raise RuntimeError(
        "Persisted error/resource trade-off artifact "
        "does not identify Section 5.9.4."
    )


if (
    RF_5_9_ERROR_RESOURCE_CHECK[
        "evaluation_partition"
    ]
    != "Validation"
):

    raise RuntimeError(
        "5.9.4 artifact is not marked as Validation-based."
    )


if RF_5_9_ERROR_RESOURCE_CHECK[
    "independent_test_used"
]:

    raise RuntimeError(
        "5.9.4 artifact indicates Independent Test usage."
    )


if RF_5_9_ERROR_RESOURCE_CHECK[
    "strategy_selected"
]:

    raise RuntimeError(
        "5.9.4 artifact indicates that an RF strategy "
        "was already selected."
    )


print(
    "✓ 5.9.4 error/resource trade-off artifact validated"
)

print(
    "✓ Validation-only comparison scope confirmed"
)

print(
    "✓ Independent Test exclusion confirmed"
)

print(
    "✓ No strategy selection recorded"
)


# ---------------------------------------------------------------
# 8. COMPARISON ARTIFACT CONSISTENCY VALIDATION
# ---------------------------------------------------------------

print("\n[COMPARISON ARTIFACT CONSISTENCY VALIDATION]")


validation_strategy_ids = set(
    RF_5_9_VALIDATION_RESULTS_CHECK[
        "strategy_id"
    ]
)


experiment_strategy_ids = set(
    RF_5_9_EXPERIMENT_RESULTS_CHECK[
        "strategy_id"
    ]
)


if validation_strategy_ids != experiment_strategy_ids:

    raise RuntimeError(
        "Validation comparison and RF experiment comparison "
        "contain different strategy sets."
    )


if validation_strategy_ids != set(
    EXPECTED_RF_STRATEGIES
):

    raise RuntimeError(
        "Section 5.9 comparison artifacts do not match "
        "the established five-strategy contract."
    )


print(
    "✓ Validation comparison and RF experiment comparison "
    "contain the same five strategies"
)

print(
    "✓ RF-0 through RF-4 comparison contract confirmed"
)


# ---------------------------------------------------------------
# 9. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION]")


print(
    "✓ Independent Test was not loaded"
)

print(
    "✓ No Test predictions were generated"
)

print(
    "✓ No Test metrics were calculated"
)

print(
    "✓ Independent Test remains reserved for Section 5.12"
)


# ---------------------------------------------------------------
# 10. COMPARISON DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[COMPARISON DEVELOPMENT BOUNDARY]")


print(
    "✓ No Random Forest model fitting performed"
)

print(
    "✓ No Validation predictions regenerated"
)

print(
    "✓ No Training distribution modified"
)

print(
    "✓ No Validation distribution modified"
)

print(
    "✓ No random oversampling performed"
)

print(
    "✓ No SMOTE performed"
)

print(
    "✓ No RF strategy selected"
)

print(
    "✓ Existing RF experiment artifacts remain unchanged"
)


# ---------------------------------------------------------------
# 11. TEMPORARY COMPARISON OBJECT CLEANUP
# ---------------------------------------------------------------

print("\n[TEMPORARY COMPARISON OBJECT CLEANUP]")


temporary_5_9_5_objects = [
    "RF_5_9_VALIDATION_RESULTS_CHECK",
    "RF_5_9_EXPERIMENT_RESULTS_CHECK",
    "RF_5_9_ERROR_RESOURCE_CHECK",
]


released_5_9_5_objects = []


for object_name in temporary_5_9_5_objects:

    if object_name in globals():

        del globals()[
            object_name
        ]

        released_5_9_5_objects.append(
            object_name
        )


gc.collect()


print(
    "✓ Temporary 5.9.5 artifact-validation objects released"
)

print(
    "✓ Garbage collection completed"
)

print(
    "✓ Persisted comparison artifacts retained"
)

print(
    "✓ RF_COMPARISON_RESULTS retained for Section 5.9 completion validation"
)


# ---------------------------------------------------------------
# 12. FINAL 5.9.5 PERSISTENCE AND CLEANUP GATE
# ---------------------------------------------------------------

print("\n[FINAL 5.9.5 PERSISTENCE AND CLEANUP GATE]")


print(
    "✓ Validation comparison artifact persisted"
)

print(
    "✓ RF experiment comparison artifact persisted"
)

print(
    "✓ Error/resource trade-off artifact persisted"
)

print(
    "✓ All five RF strategies represented"
)

print(
    "✓ All seven RF experiment artifacts remain available "
    "for RF-0 through RF-4"
)

print(
    "✓ Existing RF experiment artifacts remain unchanged"
)

print(
    "✓ Temporary 5.9.5 validation objects released"
)

print(
    "✓ RF_COMPARISON_RESULTS retained"
)

print(
    "✓ Independent Test remains completely protected"
)

print(
    "✓ No model fitting, prediction regeneration, "
    "or resampling performed"
)


print("\n" + "=" * 72)

print(
    "5.9.5 — STRATEGY COMPARISON ARTIFACT "
    "PERSISTENCE AND CLEANUP PASSED"
)

print("=" * 72)


print(
    "\nSTRATEGY COMPARISON ARTIFACT PERSISTENCE "
    "AND CLEANUP COMPLETED"
)

print(
    "READY FOR 5.9.6 — RF STRATEGY COMPARISON "
    "COMPLETION AND READINESS GATE"
)

print("=" * 72)

========================================================================
5.9.5 — STRATEGY COMPARISON ARTIFACT PERSISTENCE AND CLEANUP
========================================================================

[COMPARISON ARTIFACT BOUNDARY VALIDATION]
✓ RF development output      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development
✓ RF strategy experiments    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments
✓ RF evaluation directory   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation
✓ RF strategy selection     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_selection
✓ Established comparison artifact paths available
✓ No model fitting will be performed
✓ No Validation predictions will be regenerated
✓ No resampling or synthetic sampling will be performed
✓ Independent Test remains excluded

[FIVE-STRATEGY COMPARISON CONTRACT]
✓ RF-0 — Natural Distribution Baseline
✓ RF-1 — Balanced Class Weighting
✓ RF-2 — Balanced-Subsample Class Weighting
✓ RF-3 — Controlled Random Oversampling
✓ RF-4 — Controlled SMOTE

[PERSISTED RF EXPERIMENT ARTIFACT VALIDATION]
✓ RF-0 — all seven persisted experiment artifacts available
✓ RF-1 — all seven persisted experiment artifacts available
✓ RF-2 — all seven persisted experiment artifacts available
✓ RF-3 — all seven persisted experiment artifacts available
✓ RF-4 — all seven persisted experiment artifacts available
✓ RF-0 through RF-4 experiment artifact sets confirmed
✓ Existing RF experiment artifacts remain independently persisted

[5.9 COMPARISON ARTIFACT PATH VALIDATION]
✓ validation_results              : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/validation_results.csv
✓ rf_experiment_results           : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/rf_experiment_results.csv
✓ error_resource_tradeoff_analysis: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/error_resource_tradeoff_analysis.json

[VALIDATION COMPARISON ARTIFACT VALIDATION]
✓ Validation comparison contains all five RF strategies
✓ Primary Macro F1 is persisted for all strategies
✓ Required secondary Validation metrics are persisted

[RF EXPERIMENT RESULTS ARTIFACT VALIDATION]
✓ RF experiment comparison contains all five strategies
✓ Persisted RF experiment comparison structure confirmed

[ERROR / RESOURCE TRADE-OFF ARTIFACT VALIDATION]
✓ 5.9.4 error/resource trade-off artifact validated
✓ Validation-only comparison scope confirmed
✓ Independent Test exclusion confirmed
✓ No strategy selection recorded

[COMPARISON ARTIFACT CONSISTENCY VALIDATION]
✓ Validation comparison and RF experiment comparison contain the same five strategies
✓ RF-0 through RF-4 comparison contract confirmed

[INDEPENDENT TEST PROTECTION]
✓ Independent Test was not loaded
✓ No Test predictions were generated
✓ No Test metrics were calculated
✓ Independent Test remains reserved for Section 5.12

[COMPARISON DEVELOPMENT BOUNDARY]
✓ No Random Forest model fitting performed
✓ No Validation predictions regenerated
✓ No Training distribution modified
✓ No Validation distribution modified
✓ No random oversampling performed
✓ No SMOTE performed
✓ No RF strategy selected
✓ Existing RF experiment artifacts remain unchanged

[TEMPORARY COMPARISON OBJECT CLEANUP]
✓ Temporary 5.9.5 artifact-validation objects released
✓ Garbage collection completed
✓ Persisted comparison artifacts retained
✓ RF_COMPARISON_RESULTS retained for Section 5.9 completion validation

[FINAL 5.9.5 PERSISTENCE AND CLEANUP GATE]
✓ Validation comparison artifact persisted
✓ RF experiment comparison artifact persisted
✓ Error/resource trade-off artifact persisted
✓ All five RF strategies represented
✓ All seven RF experiment artifacts remain available for RF-0 through RF-4
✓ Existing RF experiment artifacts remain unchanged
✓ Temporary 5.9.5 validation objects released
✓ RF_COMPARISON_RESULTS retained
✓ Independent Test remains completely protected
✓ No model fitting, prediction regeneration, or resampling performed

========================================================================
5.9.5 — STRATEGY COMPARISON ARTIFACT PERSISTENCE AND CLEANUP PASSED
========================================================================

STRATEGY COMPARISON ARTIFACT PERSISTENCE AND CLEANUP COMPLETED
READY FOR 5.9.6 — RF STRATEGY COMPARISON COMPLETION AND READINESS GATE
========================================================================

# 5.9.6 — RF Strategy Comparison Completion and Readiness Gate

This subsection performs the final completion and readiness validation for
Section 5.9 — Validation-Based Random Forest Strategy Comparison.

The gate validates that all five completed Random Forest strategies (RF-0
through RF-4) were successfully recovered from their persisted experiment
artifacts and compared using the established Validation-only comparison
contract.

The completed Section 5.9 outputs include:

- persisted Validation performance comparison results,
- persisted RF experiment comparison results,
- persisted error, minority-class, and resource trade-off analysis,
- validated RF-0 through RF-4 experiment artifacts,
- and the retained in-memory `RF_COMPARISON_RESULTS` comparison object.

The final gate confirms consistency across the Section 5.9 comparison
subsections, the common 32-feature and nine-class RF model-ready contract,
the complete 451,215-observation Validation partition, and the persistence
of the comparison-level artifacts.

Section 5.9 does not select the optimal Random Forest strategy. Any Macro F1
ranking or other comparison result remains descriptive at this stage.
Formal RF strategy selection is reserved for Section 5.10.

No Random Forest model is fitted in this subsection.
No Validation predictions are regenerated.
No Training or Validation distribution is modified.
No random oversampling or SMOTE is performed.
The Independent Test partition remains completely excluded and reserved for
final evaluation in Section 5.12.

No new Section 5.9 artifact is created by this readiness gate. The three
established Section 5.9 comparison artifacts remain the authoritative
persisted outputs for downstream strategy selection.

In [ ]:
# ============================================================
# 5.9.6 — RF STRATEGY COMPARISON COMPLETION AND READINESS GATE
# ============================================================

import json


print("=" * 72)
print("5.9.6 — RF STRATEGY COMPARISON COMPLETION AND READINESS GATE")
print("=" * 72)


# ---------------------------------------------------------------
# 1. SECTION 5.9 COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[SECTION 5.9 COMPLETION BOUNDARY]")


if "EXPECTED_RF_STRATEGIES" not in globals():

    raise RuntimeError(
        "EXPECTED_RF_STRATEGIES is not available."
    )


if "EXPECTED_RF_STRATEGY_NAMES" not in globals():

    raise RuntimeError(
        "EXPECTED_RF_STRATEGY_NAMES is not available."
    )


if "RF_COMPARISON_RESULTS" not in globals():

    raise RuntimeError(
        "RF_COMPARISON_RESULTS from Section 5.9.2 "
        "is not available."
    )


if "RF_VALIDATION_COMPARISON_DF" not in globals():

    raise RuntimeError(
        "RF_VALIDATION_COMPARISON_DF from Section 5.9.3 "
        "is not available."
    )


if "RF_MACRO_F1_ORDER" not in globals():

    raise RuntimeError(
        "RF_MACRO_F1_ORDER from Section 5.9.3 "
        "is not available."
    )


if "RF_ERROR_SUMMARY_DF" not in globals():

    raise RuntimeError(
        "RF_ERROR_SUMMARY_DF from Section 5.9.4 "
        "is not available."
    )


if "RF_MINORITY_CLASS_COMPARISON_DF" not in globals():

    raise RuntimeError(
        "RF_MINORITY_CLASS_COMPARISON_DF from Section 5.9.4 "
        "is not available."
    )


if "RF_MINORITY_CLASS_SUMMARY_DF" not in globals():

    raise RuntimeError(
        "RF_MINORITY_CLASS_SUMMARY_DF from Section 5.9.4 "
        "is not available."
    )


if "RF_RESOURCE_TRADEOFF_DF" not in globals():

    raise RuntimeError(
        "RF_RESOURCE_TRADEOFF_DF from Section 5.9.4 "
        "is not available."
    )


if "RF_TRADEOFF_SUMMARY_DF" not in globals():

    raise RuntimeError(
        "RF_TRADEOFF_SUMMARY_DF from Section 5.9.4 "
        "is not available."
    )


print(
    "✓ Section 5.9 comparison objects are available"
)

print(
    "✓ 5.9.2 persisted comparison results retained"
)

print(
    "✓ 5.9.3 Validation comparison retained"
)

print(
    "✓ 5.9.4 error/minority/resource analysis retained"
)


# ---------------------------------------------------------------
# 2. FIVE-STRATEGY COMPLETION CONTRACT
# ---------------------------------------------------------------

print("\n[FIVE-STRATEGY COMPLETION CONTRACT]")


if len(EXPECTED_RF_STRATEGIES) != 5:

    raise RuntimeError(
        "Section 5.9 requires exactly five RF strategies."
    )


if len(EXPECTED_RF_STRATEGY_NAMES) != 5:

    raise RuntimeError(
        "Section 5.9 requires exactly five RF strategy names."
    )


if set(RF_COMPARISON_RESULTS.keys()) != set(
    EXPECTED_RF_STRATEGIES
):

    raise RuntimeError(
        "RF_COMPARISON_RESULTS does not contain exactly "
        "RF-0 through RF-4."
    )


for strategy_id, strategy_name in zip(
    EXPECTED_RF_STRATEGIES,
    EXPECTED_RF_STRATEGY_NAMES
):

    print(
        f"✓ {strategy_id} — {strategy_name}"
    )


# ---------------------------------------------------------------
# 3. PERSISTED RF EXPERIMENT COMPLETENESS
# ---------------------------------------------------------------

print("\n[PERSISTED RF EXPERIMENT COMPLETENESS]")


if "RF_COMPARISON_ARTIFACT_PATHS" not in globals():

    raise RuntimeError(
        "RF_COMPARISON_ARTIFACT_PATHS from Section 5.9.2 "
        "is not available."
    )


required_rf_artifacts = [
    "experiment_metadata",
    "validation_metrics",
    "confusion_matrix",
    "classification_report",
    "resource_metrics",
    "feature_importance",
    "model",
]


for strategy_id in EXPECTED_RF_STRATEGIES:

    if strategy_id not in RF_COMPARISON_ARTIFACT_PATHS:

        raise RuntimeError(
            f"{strategy_id} is missing from "
            "RF_COMPARISON_ARTIFACT_PATHS."
        )


    artifact_paths = (
        RF_COMPARISON_ARTIFACT_PATHS[
            strategy_id
        ]
    )


    if set(artifact_paths.keys()) != set(
        required_rf_artifacts
    ):

        raise RuntimeError(
            f"{strategy_id} does not contain the complete "
            "seven-artifact RF experiment contract."
        )


    for artifact_name in required_rf_artifacts:

        artifact_path = artifact_paths[
            artifact_name
        ]


        if not artifact_path.is_file():

            raise FileNotFoundError(
                f"{strategy_id} {artifact_name} artifact "
                f"is unavailable:\n{artifact_path}"
            )


    print(
        f"✓ {strategy_id} — all seven persisted "
        "experiment artifacts confirmed"
    )


print(
    "✓ RF-0 through RF-4 experiment artifact sets complete"
)

print(
    "✓ Existing RF experiment artifacts remain independently persisted"
)


# ---------------------------------------------------------------
# 4. COMMON RF MODEL-READY CONTRACT
# ---------------------------------------------------------------

print("\n[COMMON RF MODEL-READY CONTRACT]")


if "EXPECTED_MODEL_READY_FEATURE_COUNT" not in globals():

    raise RuntimeError(
        "EXPECTED_MODEL_READY_FEATURE_COUNT is not available."
    )


if "EXPECTED_RF_CLASS_IDS" not in globals():

    raise RuntimeError(
        "EXPECTED_RF_CLASS_IDS is not available."
    )


if EXPECTED_MODEL_READY_FEATURE_COUNT != 32:

    raise RuntimeError(
        "Section 5.9 RF comparison does not use the "
        "required 32-feature model-ready contract."
    )


if len(EXPECTED_RF_CLASS_IDS) != 9:

    raise RuntimeError(
        "Section 5.9 RF comparison does not use the "
        "required nine-class taxonomy."
    )


print(
    f"✓ RF feature contract = "
    f"{EXPECTED_MODEL_READY_FEATURE_COUNT}"
)

print(
    f"✓ RF class taxonomy = "
    f"{len(EXPECTED_RF_CLASS_IDS)} classes"
)

print(
    "✓ Common RF model-ready contract confirmed"
)


# ---------------------------------------------------------------
# 5. VALIDATION PARTITION CONTRACT
# ---------------------------------------------------------------

print("\n[VALIDATION PARTITION CONTRACT]")


EXPECTED_VALIDATION_OBSERVATIONS = 451_215


if EXPECTED_VALIDATION_OBSERVATIONS != 451_215:

    raise RuntimeError(
        "Unexpected Validation observation contract."
    )


print(
    f"✓ Validation partition = "
    f"{EXPECTED_VALIDATION_OBSERVATIONS:,} observations"
)

print(
    "✓ Section 5.9 comparison is Validation-based"
)


# ---------------------------------------------------------------
# 6. 5.9.3 VALIDATION PERFORMANCE COMPARISON VALIDATION
# ---------------------------------------------------------------

print(
    "\n[5.9.3 VALIDATION PERFORMANCE COMPARISON VALIDATION]"
)


if len(
    RF_VALIDATION_COMPARISON_DF
) != 5:

    raise RuntimeError(
        "5.9.3 Validation comparison does not contain "
        "exactly five strategies."
    )


if set(
    RF_VALIDATION_COMPARISON_DF[
        "strategy_id"
    ]
) != set(EXPECTED_RF_STRATEGIES):

    raise RuntimeError(
        "5.9.3 Validation comparison does not contain "
        "the complete RF-0 through RF-4 strategy set."
    )


required_validation_columns = [
    "strategy_id",
    "strategy_name",
    "macro_f1",
    "macro_recall",
    "balanced_accuracy",
    "weighted_f1",
    "accuracy",
    "benign_false_positive_rate",
    "attack_false_negatives",
    "macro_roc_auc_ovr",
]


missing_validation_columns = [
    column
    for column in required_validation_columns
    if column not in RF_VALIDATION_COMPARISON_DF.columns
]


if missing_validation_columns:

    raise RuntimeError(
        "5.9.3 Validation comparison is missing columns:\n"
        +
        "\n".join(
            f"  - {column}"
            for column in missing_validation_columns
        )
    )


if (
    RF_VALIDATION_COMPARISON_DF[
        "macro_f1"
    ].isna().any()
):

    raise RuntimeError(
        "5.9.3 contains missing Macro F1 values."
    )


if (
    RF_VALIDATION_COMPARISON_DF[
        "accuracy"
    ].isna().any()
):

    raise RuntimeError(
        "5.9.3 contains missing Accuracy values."
    )


if len(RF_MACRO_F1_ORDER) != 5:

    raise RuntimeError(
        "5.9.3 Macro F1 ordering does not contain "
        "all five RF strategies."
    )


print(
    "✓ RF-0 through RF-4 Validation performance comparison confirmed"
)

print(
    "✓ Macro F1 available for all five strategies"
)

print(
    "✓ Secondary Validation metrics confirmed"
)

print(
    "✓ Descriptive Macro F1 ordering retained"
)


# ---------------------------------------------------------------
# 7. 5.9.4 ERROR / MINORITY / RESOURCE ANALYSIS VALIDATION
# ---------------------------------------------------------------

print(
    "\n[5.9.4 ERROR / MINORITY / RESOURCE ANALYSIS VALIDATION]"
)


if len(
    RF_ERROR_SUMMARY_DF
) != 5:

    raise RuntimeError(
        "5.9.4 error summary does not contain "
        "all five RF strategies."
    )


if (
    RF_ERROR_SUMMARY_DF[
        "strategy_id"
    ].nunique()
    != 5
):

    raise RuntimeError(
        "5.9.4 error summary does not contain "
        "five unique RF strategies."
    )


if (
    RF_MINORITY_CLASS_COMPARISON_DF[
        "strategy_id"
    ].nunique()
    != 5
):

    raise RuntimeError(
        "5.9.4 minority-class comparison does not "
        "contain all five RF strategies."
    )


if len(
    RF_MINORITY_CLASS_SUMMARY_DF
) != 5:

    raise RuntimeError(
        "5.9.4 minority-class summary does not "
        "contain all five RF strategies."
    )


if len(
    RF_RESOURCE_TRADEOFF_DF
) != 5:

    raise RuntimeError(
        "5.9.4 resource trade-off table does not "
        "contain all five RF strategies."
    )


if len(
    RF_TRADEOFF_SUMMARY_DF
) != 5:

    raise RuntimeError(
        "5.9.4 combined trade-off summary does not "
        "contain all five RF strategies."
    )


print(
    "✓ Error behavior analyzed across RF-0 through RF-4"
)

print(
    "✓ BENIGN false-positive behavior retained"
)

print(
    "✓ Attack false-negative behavior retained"
)

print(
    "✓ Minority-class performance comparison retained"
)

print(
    "✓ Top confusion-pair analysis retained"
)

print(
    "✓ Resource/training trade-off analysis retained"
)

print(
    "✓ Combined trade-off summary retained"
)


# ---------------------------------------------------------------
# 8. SECTION 5.9 PERSISTED ARTIFACT VALIDATION
# ---------------------------------------------------------------

print(
    "\n[SECTION 5.9 PERSISTED ARTIFACT VALIDATION]"
)


if "RF_5_9_COMPARISON_ARTIFACT_PATHS" not in globals():

    raise RuntimeError(
        "RF_5_9_COMPARISON_ARTIFACT_PATHS from Section 5.9.5 "
        "is not available."
    )


required_5_9_artifacts = [
    "validation_results",
    "rf_experiment_results",
    "error_resource_tradeoff_analysis",
]


for artifact_name in required_5_9_artifacts:

    if artifact_name not in (
        RF_5_9_COMPARISON_ARTIFACT_PATHS
    ):

        raise RuntimeError(
            f"Section 5.9 artifact path is missing: "
            f"{artifact_name}"
        )


    artifact_path = (
        RF_5_9_COMPARISON_ARTIFACT_PATHS[
            artifact_name
        ]
    )


    if not artifact_path.is_file():

        raise FileNotFoundError(
            f"Section 5.9 persisted artifact is missing:\n"
            f"{artifact_path}"
        )


    if artifact_path.stat().st_size == 0:

        raise RuntimeError(
            f"Section 5.9 persisted artifact is empty:\n"
            f"{artifact_path}"
        )


    print(
        f"✓ {artifact_name:<32}: "
        f"{artifact_path}"
    )


print(
    "✓ All established Section 5.9 comparison artifacts persisted"
)


# ---------------------------------------------------------------
# 9. 5.9.4 PERSISTED ANALYSIS BOUNDARY
# ---------------------------------------------------------------

print(
    "\n[5.9.4 PERSISTED ANALYSIS BOUNDARY]"
)


with open(
    RF_ERROR_RESOURCE_ANALYSIS_PATH,
    "r",
    encoding="utf-8"
) as file:

    RF_5_9_FINAL_ANALYSIS_CHECK = json.load(
        file
    )


if (
    RF_5_9_FINAL_ANALYSIS_CHECK.get(
        "section"
    )
    != "5.9.4"
):

    raise RuntimeError(
        "Persisted error/resource analysis is not "
        "identified as Section 5.9.4."
    )


if (
    RF_5_9_FINAL_ANALYSIS_CHECK.get(
        "evaluation_partition"
    )
    != "Validation"
):

    raise RuntimeError(
        "Persisted Section 5.9.4 analysis is not "
        "Validation-based."
    )


if RF_5_9_FINAL_ANALYSIS_CHECK.get(
    "independent_test_used"
):

    raise RuntimeError(
        "Persisted Section 5.9.4 analysis indicates "
        "Independent Test usage."
    )


if RF_5_9_FINAL_ANALYSIS_CHECK.get(
    "model_fitting_performed"
):

    raise RuntimeError(
        "Persisted Section 5.9.4 analysis indicates "
        "model fitting."
    )


if RF_5_9_FINAL_ANALYSIS_CHECK.get(
    "validation_predictions_regenerated"
):

    raise RuntimeError(
        "Persisted Section 5.9.4 analysis indicates "
        "Validation prediction regeneration."
    )


if RF_5_9_FINAL_ANALYSIS_CHECK.get(
    "resampling_performed"
):

    raise RuntimeError(
        "Persisted Section 5.9.4 analysis indicates "
        "resampling."
    )


if RF_5_9_FINAL_ANALYSIS_CHECK.get(
    "synthetic_sampling_performed"
):

    raise RuntimeError(
        "Persisted Section 5.9.4 analysis indicates "
        "synthetic sampling."
    )


if RF_5_9_FINAL_ANALYSIS_CHECK.get(
    "strategy_selected"
):

    raise RuntimeError(
        "Persisted Section 5.9.4 analysis indicates "
        "that an RF strategy was already selected."
    )


print(
    "✓ Section 5.9.4 persisted analysis is Validation-only"
)

print(
    "✓ Independent Test exclusion confirmed"
)

print(
    "✓ No model fitting or prediction regeneration recorded"
)

print(
    "✓ No resampling or synthetic sampling recorded"
)

print(
    "✓ No RF strategy selection recorded"
)


# ---------------------------------------------------------------
# 10. SECTION 5.9 STRATEGY-SELECTION BOUNDARY
# ---------------------------------------------------------------

print(
    "\n[STRATEGY-SELECTION BOUNDARY]"
)


print(
    "✓ Macro F1 ordering remains descriptive"
)

print(
    "✓ No optimal RF strategy declared in Section 5.9"
)

print(
    "✓ No final RF model selected in Section 5.9"
)

print(
    "✓ Formal RF strategy selection remains reserved "
    "for Section 5.10"
)


# ---------------------------------------------------------------
# 11. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print(
    "\n[INDEPENDENT TEST PROTECTION]"
)


print(
    "✓ Independent Test was not loaded for Section 5.9"
)

print(
    "✓ No Test predictions were generated"
)

print(
    "✓ No Test metrics were calculated"
)

print(
    "✓ Independent Test remains reserved for Section 5.12"
)


# ---------------------------------------------------------------
# 12. SECTION 5.9 DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print(
    "\n[SECTION 5.9 DEVELOPMENT BOUNDARY]"
)


print(
    "✓ No Random Forest model fitting performed"
)

print(
    "✓ No Validation predictions regenerated"
)

print(
    "✓ No Training distribution modified"
)

print(
    "✓ No Validation distribution modified"
)

print(
    "✓ No random oversampling performed"
)

print(
    "✓ No SMOTE performed"
)

print(
    "✓ Existing RF-0 through RF-4 experiment artifacts "
    "remain unchanged"
)

print(
    "✓ Section 5.9 operates only on persisted RF experiment results"
)


# ---------------------------------------------------------------
# 13. FINAL SECTION 5.9 READINESS GATE
# ---------------------------------------------------------------

print(
    "\n[FINAL SECTION 5.9 READINESS GATE]"
)


print(
    "✓ 5.9.1 RF comparison definition and boundaries established"
)

print(
    "✓ 5.9.2 persisted RF experiment results loaded and validated"
)

print(
    "✓ 5.9.3 Validation performance comparison completed"
)

print(
    "✓ 5.9.4 error, minority-class, and resource trade-off "
    "analysis completed"
)

print(
    "✓ 5.9.5 comparison artifacts persisted and temporary "
    "validation objects cleaned up"
)

print(
    "✓ All five RF strategies represented consistently"
)

print(
    "✓ All seven persisted experiment artifacts remain available "
    "for RF-0 through RF-4"
)

print(
    "✓ Three established Section 5.9 comparison artifacts confirmed"
)

print(
    "✓ Validation-only comparison boundary confirmed"
)

print(
    "✓ Independent Test remains completely protected"
)

print(
    "✓ RF strategy selection remains reserved for Section 5.10"
)


print("\n" + "=" * 72)

print(
    "5.9.6 — RF STRATEGY COMPARISON COMPLETION "
    "AND READINESS GATE PASSED"
)

print("=" * 72)


print(
    "\nRF STRATEGY COMPARISON COMPLETED"
)

print(
    "SECTION 5.9 — VALIDATION-BASED RANDOM FOREST "
    "STRATEGY COMPARISON COMPLETED"
)

print(
    "READY FOR 5.10 — RF STRATEGY SELECTION"
)

print("=" * 72)

========================================================================
5.9.6 — RF STRATEGY COMPARISON COMPLETION AND READINESS GATE
========================================================================

[SECTION 5.9 COMPLETION BOUNDARY]
✓ Section 5.9 comparison objects are available
✓ 5.9.2 persisted comparison results retained
✓ 5.9.3 Validation comparison retained
✓ 5.9.4 error/minority/resource analysis retained

[FIVE-STRATEGY COMPLETION CONTRACT]
✓ RF-0 — Natural Distribution Baseline
✓ RF-1 — Balanced Class Weighting
✓ RF-2 — Balanced-Subsample Class Weighting
✓ RF-3 — Controlled Random Oversampling
✓ RF-4 — Controlled SMOTE

[PERSISTED RF EXPERIMENT COMPLETENESS]
✓ RF-0 — all seven persisted experiment artifacts confirmed
✓ RF-1 — all seven persisted experiment artifacts confirmed
✓ RF-2 — all seven persisted experiment artifacts confirmed
✓ RF-3 — all seven persisted experiment artifacts confirmed
✓ RF-4 — all seven persisted experiment artifacts confirmed
✓ RF-0 through RF-4 experiment artifact sets complete
✓ Existing RF experiment artifacts remain independently persisted

[COMMON RF MODEL-READY CONTRACT]
✓ RF feature contract = 32
✓ RF class taxonomy = 9 classes
✓ Common RF model-ready contract confirmed

[VALIDATION PARTITION CONTRACT]
✓ Validation partition = 451,215 observations
✓ Section 5.9 comparison is Validation-based

[5.9.3 VALIDATION PERFORMANCE COMPARISON VALIDATION]
✓ RF-0 through RF-4 Validation performance comparison confirmed
✓ Macro F1 available for all five strategies
✓ Secondary Validation metrics confirmed
✓ Descriptive Macro F1 ordering retained

[5.9.4 ERROR / MINORITY / RESOURCE ANALYSIS VALIDATION]
✓ Error behavior analyzed across RF-0 through RF-4
✓ BENIGN false-positive behavior retained
✓ Attack false-negative behavior retained
✓ Minority-class performance comparison retained
✓ Top confusion-pair analysis retained
✓ Resource/training trade-off analysis retained
✓ Combined trade-off summary retained

[SECTION 5.9 PERSISTED ARTIFACT VALIDATION]
✓ validation_results              : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/validation_results.csv
✓ rf_experiment_results           : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/rf_experiment_results.csv
✓ error_resource_tradeoff_analysis: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/error_resource_tradeoff_analysis.json
✓ All established Section 5.9 comparison artifacts persisted

[5.9.4 PERSISTED ANALYSIS BOUNDARY]
✓ Section 5.9.4 persisted analysis is Validation-only
✓ Independent Test exclusion confirmed
✓ No model fitting or prediction regeneration recorded
✓ No resampling or synthetic sampling recorded
✓ No RF strategy selection recorded

[STRATEGY-SELECTION BOUNDARY]
✓ Macro F1 ordering remains descriptive
✓ No optimal RF strategy declared in Section 5.9
✓ No final RF model selected in Section 5.9
✓ Formal RF strategy selection remains reserved for Section 5.10

[INDEPENDENT TEST PROTECTION]
✓ Independent Test was not loaded for Section 5.9
✓ No Test predictions were generated
✓ No Test metrics were calculated
✓ Independent Test remains reserved for Section 5.12

[SECTION 5.9 DEVELOPMENT BOUNDARY]
✓ No Random Forest model fitting performed
✓ No Validation predictions regenerated
✓ No Training distribution modified
✓ No Validation distribution modified
✓ No random oversampling performed
✓ No SMOTE performed
✓ Existing RF-0 through RF-4 experiment artifacts remain unchanged
✓ Section 5.9 operates only on persisted RF experiment results

[FINAL SECTION 5.9 READINESS GATE]
✓ 5.9.1 RF comparison definition and boundaries established
✓ 5.9.2 persisted RF experiment results loaded and validated
✓ 5.9.3 Validation performance comparison completed
✓ 5.9.4 error, minority-class, and resource trade-off analysis completed
✓ 5.9.5 comparison artifacts persisted and temporary validation objects cleaned up
✓ All five RF strategies represented consistently
✓ All seven persisted experiment artifacts remain available for RF-0 through RF-4
✓ Three established Section 5.9 comparison artifacts confirmed
✓ Validation-only comparison boundary confirmed
✓ Independent Test remains completely protected
✓ RF strategy selection remains reserved for Section 5.10

========================================================================
5.9.6 — RF STRATEGY COMPARISON COMPLETION AND READINESS GATE PASSED
========================================================================

RF STRATEGY COMPARISON COMPLETED
SECTION 5.9 — VALIDATION-BASED RANDOM FOREST STRATEGY COMPARISON COMPLETED
READY FOR 5.10 — RF STRATEGY SELECTION
========================================================================

# 5.10 — RANDOM FOREST STRATEGY SELECTION

This section formally selects the Random Forest strategy to be carried
forward into final Random Forest training.

The selection is performed only after completion of the Validation-Based
Random Forest Strategy Comparison in Section 5.9.

The five completed RF strategies are:

    RF-0 — Natural Distribution Baseline
    RF-1 — Balanced Class Weighting
    RF-2 — Balanced-Subsample Class Weighting
    RF-3 — Controlled Random Oversampling
    RF-4 — Controlled SMOTE

Section 5.10 uses the persisted Validation-based comparison evidence
generated in Section 5.9.

The primary strategy-selection metric is Validation Macro F1.
Secondary Validation metrics, minority-class performance, error
behavior, and resource/training trade-offs are retained as supporting
evidence for the final decision.

The Independent Test partition remains completely excluded from
strategy selection and is reserved for final evaluation in Section 5.12.

Section 5.10 is a decision stage rather than another model-development
experiment. No new Random Forest model fitting, Validation prediction
generation, Training resampling, or synthetic sampling is performed
during strategy selection.

The selected strategy will be persisted only after the selection
decision and rationale have been formally established. The selected
strategy will then become the frozen strategy for Section 5.11 —
Final Random Forest Training.

## 5.10.1 — RF Strategy Selection Definition and Boundary Validation

This subsection establishes and validates the methodological boundary
for Random Forest strategy selection.

The selection stage operates only on the completed and persisted
Validation-based comparison evidence from Section 5.9.

All five predefined RF strategies must remain available as candidates:

    RF-0 — Natural Distribution Baseline
    RF-1 — Balanced Class Weighting
    RF-2 — Balanced-Subsample Class Weighting
    RF-3 — Controlled Random Oversampling
    RF-4 — Controlled SMOTE

Validation is the authorized partition for strategy selection.
The Independent Test partition is explicitly excluded and remains
reserved for final evaluation.

The primary selection criterion is Validation Macro F1. Secondary
Validation metrics and the previously retained error, minority-class,
and resource trade-off analyses may support the final decision.

This subsection does not make the final strategy decision. It only
establishes and validates the selection boundary required for the
subsequent decision subsection.

No Random Forest model is fitted.
No Validation predictions are regenerated.
No Training distribution is modified.
No random oversampling or SMOTE is performed.
No Independent Test data is loaded or evaluated.
No final RF strategy is selected in this subsection.
No strategy-selection artifact is persisted in this subsection.

In [ ]:
# ================================================================
# 5.10.1 — RF STRATEGY SELECTION DEFINITION AND BOUNDARY VALIDATION
# ================================================================

print("=" * 72)
print("5.10.1 — RF STRATEGY SELECTION DEFINITION AND BOUNDARY VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. SECTION 5.9 COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[SECTION 5.9 COMPLETION BOUNDARY]")

if "EXPECTED_RF_STRATEGIES" not in globals():
    raise RuntimeError(
        "EXPECTED_RF_STRATEGIES is not available."
    )

if "EXPECTED_RF_STRATEGY_NAMES" not in globals():
    raise RuntimeError(
        "EXPECTED_RF_STRATEGY_NAMES is not available."
    )

if "RF_COMPARISON_RESULTS" not in globals():
    raise RuntimeError(
        "RF_COMPARISON_RESULTS from Section 5.9.2 is not available."
    )

if "RF_VALIDATION_COMPARISON_DF" not in globals():
    raise RuntimeError(
        "RF_VALIDATION_COMPARISON_DF from Section 5.9.3 is not available."
    )

if "RF_ERROR_SUMMARY_DF" not in globals():
    raise RuntimeError(
        "RF_ERROR_SUMMARY_DF from Section 5.9.4 is not available."
    )

if "RF_MINORITY_CLASS_COMPARISON_DF" not in globals():
    raise RuntimeError(
        "RF_MINORITY_CLASS_COMPARISON_DF from Section 5.9.4 is not available."
    )

if "RF_RESOURCE_TRADEOFF_DF" not in globals():
    raise RuntimeError(
        "RF_RESOURCE_TRADEOFF_DF from Section 5.9.4 is not available."
    )

if "RF_TRADEOFF_SUMMARY_DF" not in globals():
    raise RuntimeError(
        "RF_TRADEOFF_SUMMARY_DF from Section 5.9.4 is not available."
    )

if "RF_5_9_COMPARISON_ARTIFACT_PATHS" not in globals():
    raise RuntimeError(
        "RF_5_9_COMPARISON_ARTIFACT_PATHS from Section 5.9.5 is not available."
    )

print("✓ Section 5.9 comparison objects are available")
print("✓ Validation comparison is available")
print("✓ Error/minority/resource analysis is available")
print("✓ Section 5.9 persisted comparison artifacts are available")


# ---------------------------------------------------------------
# 2. FIVE-STRATEGY SELECTION CANDIDATE CONTRACT
# ---------------------------------------------------------------

print("\n[FIVE-STRATEGY SELECTION CANDIDATE CONTRACT]")

if len(EXPECTED_RF_STRATEGIES) != 5:
    raise RuntimeError(
        "Random Forest strategy selection requires exactly five "
        "predefined RF strategies."
    )

if len(EXPECTED_RF_STRATEGY_NAMES) != 5:
    raise RuntimeError(
        "Random Forest strategy selection requires exactly five "
        "RF strategy names."
    )

if set(RF_COMPARISON_RESULTS.keys()) != set(EXPECTED_RF_STRATEGIES):
    raise RuntimeError(
        "RF_COMPARISON_RESULTS does not contain the complete "
        "RF-0 through RF-4 candidate set."
    )

if set(
    RF_VALIDATION_COMPARISON_DF["strategy_id"]
) != set(EXPECTED_RF_STRATEGIES):
    raise RuntimeError(
        "Validation comparison does not contain the complete "
        "RF-0 through RF-4 candidate set."
    )

for strategy_id, strategy_name in zip(
    EXPECTED_RF_STRATEGIES,
    EXPECTED_RF_STRATEGY_NAMES
):
    print(f"✓ {strategy_id} — {strategy_name}")

print(
    "✓ All five completed RF strategies remain available "
    "as selection candidates"
)


# ---------------------------------------------------------------
# 3. VALIDATION-BASED SELECTION CONTRACT
# ---------------------------------------------------------------

print("\n[VALIDATION-BASED SELECTION CONTRACT]")

if "RF_STRATEGY_SELECTION_BOUNDARY" not in globals():
    raise RuntimeError(
        "RF_STRATEGY_SELECTION_BOUNDARY from Section 5.2 "
        "is not available."
    )

if RF_STRATEGY_SELECTION_BOUNDARY[
    "strategy_comparison_partition"
] != "Validation":
    raise RuntimeError(
        "RF strategy comparison partition is not Validation."
    )

if RF_STRATEGY_SELECTION_BOUNDARY[
    "strategy_selection_partition"
] != "Validation":
    raise RuntimeError(
        "RF strategy selection partition is not Validation."
    )

if RF_STRATEGY_SELECTION_BOUNDARY[
    "model_fitting_partition"
] != "Training":
    raise RuntimeError(
        "RF model-fitting partition does not match "
        "the established Training boundary."
    )

if RF_STRATEGY_SELECTION_BOUNDARY[
    "test_used_for_strategy_selection"
]:
    raise RuntimeError(
        "Independent Test is incorrectly permitted "
        "for RF strategy selection."
    )

if RF_STRATEGY_SELECTION_BOUNDARY[
    "test_used_for_model_fitting"
]:
    raise RuntimeError(
        "Independent Test is incorrectly permitted "
        "for RF model fitting."
    )

print("✓ Validation is the authorized strategy-selection partition")
print("✓ Training remains the model-fitting partition")
print("✓ Independent Test is excluded from strategy selection")
print("✓ Independent Test is excluded from model fitting")


# ---------------------------------------------------------------
# 4. PRIMARY AND SECONDARY SELECTION METRIC CONTRACT
# ---------------------------------------------------------------

print("\n[STRATEGY-SELECTION METRIC CONTRACT]")

required_selection_columns = [
    "strategy_id",
    "strategy_name",
    "macro_f1",
    "macro_recall",
    "balanced_accuracy",
    "weighted_f1",
    "accuracy",
    "benign_false_positive_rate",
    "attack_false_negatives",
    "macro_roc_auc_ovr",
]

missing_selection_columns = [
    column
    for column in required_selection_columns
    if column not in RF_VALIDATION_COMPARISON_DF.columns
]

if missing_selection_columns:
    raise RuntimeError(
        "Validation comparison is missing required "
        "strategy-selection metrics:\n"
        + "\n".join(
            f"  - {column}"
            for column in missing_selection_columns
        )
    )

if RF_VALIDATION_COMPARISON_DF["macro_f1"].isna().any():
    raise RuntimeError(
        "Validation Macro F1 contains missing values."
    )

if RF_VALIDATION_COMPARISON_DF["macro_recall"].isna().any():
    raise RuntimeError(
        "Validation Macro Recall contains missing values."
    )

if RF_VALIDATION_COMPARISON_DF["balanced_accuracy"].isna().any():
    raise RuntimeError(
        "Validation Balanced Accuracy contains missing values."
    )

print("✓ Primary selection metric = Validation Macro F1")
print("✓ Secondary Validation metrics are available")
print("✓ BENIGN false-positive behavior is available")
print("✓ Attack false-negative behavior is available")
print("✓ Multiclass ROC-AUC is available as supplementary evidence")


# ---------------------------------------------------------------
# 5. ERROR / MINORITY / RESOURCE EVIDENCE CONTRACT
# ---------------------------------------------------------------

print("\n[ERROR / MINORITY / RESOURCE EVIDENCE CONTRACT]")

# Error summary: one row per RF strategy
error_strategy_ids = set(
    RF_ERROR_SUMMARY_DF["strategy_id"]
)

if error_strategy_ids != set(EXPECTED_RF_STRATEGIES):
    raise RuntimeError(
        "Error-analysis summary does not contain "
        "all five RF strategies."
    )

# Minority-class comparison:
# multiple rows per strategy are expected because the table contains
# multiple minority/rare Validation classes for every strategy.
minority_strategy_ids = set(
    RF_MINORITY_CLASS_COMPARISON_DF["strategy_id"]
)

if minority_strategy_ids != set(EXPECTED_RF_STRATEGIES):
    raise RuntimeError(
        "Minority-class comparison does not contain "
        "all five RF strategies."
    )

# Confirm that every strategy has at least one minority-class row.
minority_strategy_counts = (
    RF_MINORITY_CLASS_COMPARISON_DF
    .groupby("strategy_id")
    .size()
)

if not all(
    minority_strategy_counts.get(strategy_id, 0) > 0
    for strategy_id in EXPECTED_RF_STRATEGIES
):
    raise RuntimeError(
        "At least one RF strategy has no minority-class "
        "comparison rows."
    )

# Resource comparison: one row per RF strategy
resource_strategy_ids = set(
    RF_RESOURCE_TRADEOFF_DF["strategy_id"]
)

if resource_strategy_ids != set(EXPECTED_RF_STRATEGIES):
    raise RuntimeError(
        "Resource trade-off comparison does not contain "
        "all five RF strategies."
    )

# Combined trade-off summary: one row per RF strategy
tradeoff_strategy_ids = set(
    RF_TRADEOFF_SUMMARY_DF["strategy_id"]
)

if tradeoff_strategy_ids != set(EXPECTED_RF_STRATEGIES):
    raise RuntimeError(
        "Combined trade-off summary does not contain "
        "all five RF strategies."
    )

print("✓ Error-analysis evidence retained")
print(
    "✓ Minority-class evidence retained "
    f"({len(RF_MINORITY_CLASS_COMPARISON_DF)} class-level rows)"
)
print("✓ All five RF strategies represented in minority-class analysis")
print("✓ Resource/training trade-off evidence retained")
print("✓ Combined strategy trade-off evidence retained")


# ---------------------------------------------------------------
# 6. STRATEGY-SELECTION ARTIFACT BOUNDARY
# ---------------------------------------------------------------

print("\n[STRATEGY-SELECTION ARTIFACT BOUNDARY]")

if not RF_STRATEGY_SELECTION_DIR.is_dir():
    raise FileNotFoundError(
        "RF strategy-selection directory is not available:\n"
        f"{RF_STRATEGY_SELECTION_DIR}"
    )

if "RF_EXPERIMENT_ARTIFACTS" not in globals():
    raise RuntimeError(
        "RF_EXPERIMENT_ARTIFACTS from Section 5.3.5 "
        "is not available."
    )

if "strategy_selection" not in RF_EXPERIMENT_ARTIFACTS:
    raise RuntimeError(
        "Established strategy-selection artifact path is "
        "missing from RF_EXPERIMENT_ARTIFACTS."
    )

RF_STRATEGY_SELECTION_ARTIFACT_PATH = (
    RF_EXPERIMENT_ARTIFACTS["strategy_selection"]
)

if (
    RF_STRATEGY_SELECTION_ARTIFACT_PATH.parent
    != RF_STRATEGY_SELECTION_DIR
):
    raise RuntimeError(
        "Configured strategy-selection artifact is outside "
        "the established RF strategy-selection directory."
    )

print(
    f"✓ Strategy-selection directory : "
    f"{RF_STRATEGY_SELECTION_DIR}"
)

print(
    f"✓ Strategy-selection artifact   : "
    f"{RF_STRATEGY_SELECTION_ARTIFACT_PATH}"
)

print("✓ Existing RF artifact/output boundary is retained")


# ---------------------------------------------------------------
# 7. MODEL-DEVELOPMENT OPERATION BOUNDARY
# ---------------------------------------------------------------

print("\n[MODEL-DEVELOPMENT OPERATION BOUNDARY]")

RF_5_10_1_OPERATION_FLAGS = {

    "model_fitting_performed": False,

    "validation_predictions_regenerated": False,

    "training_distribution_modified": False,

    "validation_distribution_modified": False,

    "random_oversampling_performed": False,

    "synthetic_sampling_performed": False,

    "independent_test_loaded": False,

    "independent_test_evaluated": False,

    "strategy_selected": False,

    "selection_artifact_persisted": False,
}

for operation_name, operation_status in (
    RF_5_10_1_OPERATION_FLAGS.items()
):

    if operation_status:
        raise RuntimeError(
            f"Invalid 5.10.1 operation detected: "
            f"{operation_name}"
        )

    print(
        f"✓ {operation_name}: {operation_status}"
    )


# ---------------------------------------------------------------
# 8. 5.10.1 VALIDATION STATE
# ---------------------------------------------------------------

RF_5_10_1_VALIDATION = {

    "section_5_9_comparison_available":
        "RF_COMPARISON_RESULTS" in globals(),

    "validation_comparison_available":
        "RF_VALIDATION_COMPARISON_DF" in globals(),

    "five_rf_strategies_available":
        len(EXPECTED_RF_STRATEGIES) == 5,

    "strategy_names_available":
        len(EXPECTED_RF_STRATEGY_NAMES) == 5,

    "primary_metric_available":
        "macro_f1"
        in RF_VALIDATION_COMPARISON_DF.columns,

    "secondary_metrics_available":
        all(
            metric_name in RF_VALIDATION_COMPARISON_DF.columns
            for metric_name in [
                "macro_recall",
                "balanced_accuracy",
                "weighted_f1",
                "accuracy",
            ]
        ),

    "error_analysis_available":
        error_strategy_ids == set(EXPECTED_RF_STRATEGIES),

    "minority_class_analysis_available":
        minority_strategy_ids == set(EXPECTED_RF_STRATEGIES),

    "resource_analysis_available":
        resource_strategy_ids == set(EXPECTED_RF_STRATEGIES),

    "validation_partition_for_selection":
        RF_STRATEGY_SELECTION_BOUNDARY[
            "strategy_selection_partition"
        ] == "Validation",

    "independent_test_excluded":
        RF_STRATEGY_SELECTION_BOUNDARY[
            "test_used_for_strategy_selection"
        ] is False,

    "selection_artifact_path_configured":
        RF_STRATEGY_SELECTION_ARTIFACT_PATH.parent
        == RF_STRATEGY_SELECTION_DIR,

    "no_strategy_selected":
        True,

    "no_selection_artifact_persisted":
        True,
}


if not all(
    RF_5_10_1_VALIDATION.values()
):
    raise RuntimeError(
        "5.10.1 RF strategy-selection definition "
        "and boundary validation failed."
    )


# ---------------------------------------------------------------
# 9. FINAL 5.10.1 READINESS GATE
# ---------------------------------------------------------------

print(
    "\n[FINAL 5.10.1 STRATEGY-SELECTION BOUNDARY GATE]"
)

print("✓ Section 5.9 Validation comparison is complete")
print("✓ All five RF strategies remain available")
print("✓ Validation is the authorized strategy-selection partition")
print("✓ Macro F1 is established as the primary selection metric")
print("✓ Secondary Validation metrics are available")
print("✓ Error, minority-class, and resource evidence is available")
print("✓ Independent Test remains completely excluded")
print("✓ No model fitting or prediction regeneration performed")
print("✓ No Training/Validation distribution modification performed")
print("✓ No resampling or synthetic sampling performed")
print("✓ No RF strategy selected in 5.10.1")
print("✓ Strategy-selection artifact path is correctly configured")
print("✓ No strategy-selection artifact persisted in 5.10.1")

print("\n" + "=" * 72)
print(
    "5.10.1 — RF STRATEGY SELECTION DEFINITION "
    "AND BOUNDARY VALIDATION PASSED"
)
print("=" * 72)

print(
    "\nREADY FOR 5.10.2 — SELECTION EVIDENCE LOADING "
    "AND DECISION-CRITERIA VALIDATION"
)

========================================================================
5.10.1 — RF STRATEGY SELECTION DEFINITION AND BOUNDARY VALIDATION
========================================================================

[SECTION 5.9 COMPLETION BOUNDARY]
✓ Section 5.9 comparison objects are available
✓ Validation comparison is available
✓ Error/minority/resource analysis is available
✓ Section 5.9 persisted comparison artifacts are available

[FIVE-STRATEGY SELECTION CANDIDATE CONTRACT]
✓ RF-0 — Natural Distribution Baseline
✓ RF-1 — Balanced Class Weighting
✓ RF-2 — Balanced-Subsample Class Weighting
✓ RF-3 — Controlled Random Oversampling
✓ RF-4 — Controlled SMOTE
✓ All five completed RF strategies remain available as selection candidates

[VALIDATION-BASED SELECTION CONTRACT]
✓ Validation is the authorized strategy-selection partition
✓ Training remains the model-fitting partition
✓ Independent Test is excluded from strategy selection
✓ Independent Test is excluded from model fitting

[STRATEGY-SELECTION METRIC CONTRACT]
✓ Primary selection metric = Validation Macro F1
✓ Secondary Validation metrics are available
✓ BENIGN false-positive behavior is available
✓ Attack false-negative behavior is available
✓ Multiclass ROC-AUC is available as supplementary evidence

[ERROR / MINORITY / RESOURCE EVIDENCE CONTRACT]
✓ Error-analysis evidence retained
✓ Minority-class evidence retained (20 class-level rows)
✓ All five RF strategies represented in minority-class analysis
✓ Resource/training trade-off evidence retained
✓ Combined strategy trade-off evidence retained

[STRATEGY-SELECTION ARTIFACT BOUNDARY]
✓ Strategy-selection directory : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_selection
✓ Strategy-selection artifact   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_selection/rf_strategy_selection.json
✓ Existing RF artifact/output boundary is retained

[MODEL-DEVELOPMENT OPERATION BOUNDARY]
✓ model_fitting_performed: False
✓ validation_predictions_regenerated: False
✓ training_distribution_modified: False
✓ validation_distribution_modified: False
✓ random_oversampling_performed: False
✓ synthetic_sampling_performed: False
✓ independent_test_loaded: False
✓ independent_test_evaluated: False
✓ strategy_selected: False
✓ selection_artifact_persisted: False

[FINAL 5.10.1 STRATEGY-SELECTION BOUNDARY GATE]
✓ Section 5.9 Validation comparison is complete
✓ All five RF strategies remain available
✓ Validation is the authorized strategy-selection partition
✓ Macro F1 is established as the primary selection metric
✓ Secondary Validation metrics are available
✓ Error, minority-class, and resource evidence is available
✓ Independent Test remains completely excluded
✓ No model fitting or prediction regeneration performed
✓ No Training/Validation distribution modification performed
✓ No resampling or synthetic sampling performed
✓ No RF strategy selected in 5.10.1
✓ Strategy-selection artifact path is correctly configured
✓ No strategy-selection artifact persisted in 5.10.1

========================================================================
5.10.1 — RF STRATEGY SELECTION DEFINITION AND BOUNDARY VALIDATION PASSED
========================================================================

READY FOR 5.10.2 — SELECTION EVIDENCE LOADING AND DECISION-CRITERIA VALIDATION

# 5.10.2 — Selection Evidence Loading and Decision-Criteria Validation

This subsection loads and validates the persisted evidence produced by Section 5.9 for Random Forest strategy selection.

The selection evidence consists of:

- Validation performance comparison across RF-0 through RF-4
- Error-analysis evidence
- Minority-class performance evidence
- Resource and training trade-off evidence
- Combined comparison-level evidence

The strategy-selection decision boundary is:

1. Validation Macro F1 is the primary selection criterion.
2. Macro Recall and Balanced Accuracy provide secondary class-balanced performance evidence.
3. Weighted F1 and Accuracy provide overall performance context.
4. BENIGN false-positive rate and attack false negatives provide operational error evidence.
5. Minority-class recall/F1 provide additional evidence for rare-class behavior.
6. Training/resource observations provide computational trade-off evidence.
7. Multiclass ROC-AUC is retained as supplementary evidence.

No Independent Test data is used for strategy selection.

No model is fitted, no Validation prediction is regenerated, and no resampling or synthetic sampling is performed in this subsection.

This subsection validates the decision criteria and selection evidence only. The actual RF strategy selection remains a subsequent operation in Section 5.10.

In [ ]:
# ================================================================
# 5.10.2 — SELECTION EVIDENCE LOADING AND DECISION-CRITERIA VALIDATION
# ================================================================

import json
import gc
import pandas as pd


print("=" * 72)
print("5.10.2 — SELECTION EVIDENCE LOADING AND DECISION-CRITERIA VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. SECTION 5.10.1 BOUNDARY VALIDATION
# ---------------------------------------------------------------

print("\n[5.10.1 BOUNDARY VALIDATION]")

required_5_10_1_objects = [
    "EXPECTED_RF_STRATEGIES",
    "EXPECTED_RF_STRATEGY_NAMES",
    "RF_COMPARISON_RESULTS",
    "RF_VALIDATION_COMPARISON_DF",
    "RF_ERROR_SUMMARY_DF",
    "RF_MINORITY_CLASS_COMPARISON_DF",
    "RF_RESOURCE_TRADEOFF_DF",
    "RF_TRADEOFF_SUMMARY_DF",
    "RF_5_9_COMPARISON_ARTIFACT_PATHS",
    "RF_STRATEGY_SELECTION_DIR",
    "RF_STRATEGY_SELECTION_ARTIFACT_PATH",
]

for object_name in required_5_10_1_objects:
    if object_name not in globals():
        raise RuntimeError(
            f"Required 5.10.1 object is unavailable: {object_name}"
        )

print("✓ Section 5.10.1 selection boundary objects available")


# ---------------------------------------------------------------
# 2. PERSISTED SECTION 5.9 ARTIFACT PATH VALIDATION
# ---------------------------------------------------------------

print("\n[PERSISTED SECTION 5.9 EVIDENCE PATH VALIDATION]")

if not isinstance(RF_5_9_COMPARISON_ARTIFACT_PATHS, dict):
    raise TypeError(
        "RF_5_9_COMPARISON_ARTIFACT_PATHS must be a dictionary."
    )

required_5_9_artifacts = [
    "validation_results",
    "rf_experiment_results",
    "error_resource_tradeoff_analysis",
]

for artifact_name in required_5_9_artifacts:

    if artifact_name not in RF_5_9_COMPARISON_ARTIFACT_PATHS:
        raise RuntimeError(
            "Required Section 5.9 comparison artifact path is missing: "
            f"{artifact_name}"
        )

    artifact_path = RF_5_9_COMPARISON_ARTIFACT_PATHS[
        artifact_name
    ]

    if not artifact_path.exists():
        raise FileNotFoundError(
            f"Persisted Section 5.9 artifact does not exist:\n"
            f"{artifact_path}"
        )

    print(
        f"✓ {artifact_name} : {artifact_path}"
    )


# ---------------------------------------------------------------
# 3. LOAD PERSISTED VALIDATION COMPARISON EVIDENCE
# ---------------------------------------------------------------

print("\n[PERSISTED VALIDATION EVIDENCE LOADING]")

validation_results_path = (
    RF_5_9_COMPARISON_ARTIFACT_PATHS[
        "validation_results"
    ]
)

rf_experiment_results_path = (
    RF_5_9_COMPARISON_ARTIFACT_PATHS[
        "rf_experiment_results"
    ]
)

error_resource_path = (
    RF_5_9_COMPARISON_ARTIFACT_PATHS[
        "error_resource_tradeoff_analysis"
    ]
)

SELECTION_VALIDATION_RESULTS_DF = pd.read_csv(
    validation_results_path
)

SELECTION_RF_EXPERIMENT_RESULTS_DF = pd.read_csv(
    rf_experiment_results_path
)

with open(
    error_resource_path,
    "r",
    encoding="utf-8",
) as f:
    SELECTION_ERROR_RESOURCE_EVIDENCE = json.load(f)


print(
    f"✓ Validation comparison loaded "
    f"({len(SELECTION_VALIDATION_RESULTS_DF)} rows)"
)

print(
    f"✓ RF experiment comparison loaded "
    f"({len(SELECTION_RF_EXPERIMENT_RESULTS_DF)} rows)"
)

print("✓ Error/resource trade-off evidence loaded")


# ---------------------------------------------------------------
# 4. FIVE-STRATEGY EVIDENCE CONTRACT
# ---------------------------------------------------------------

print("\n[FIVE-STRATEGY SELECTION EVIDENCE CONTRACT]")

expected_strategy_ids = set(
    EXPECTED_RF_STRATEGIES
)

validation_strategy_ids = set(
    SELECTION_VALIDATION_RESULTS_DF[
        "strategy_id"
    ]
)

experiment_strategy_ids = set(
    SELECTION_RF_EXPERIMENT_RESULTS_DF[
        "strategy_id"
    ]
)

if validation_strategy_ids != expected_strategy_ids:
    raise RuntimeError(
        "Persisted Validation evidence does not contain "
        "exactly RF-0 through RF-4."
    )

if experiment_strategy_ids != expected_strategy_ids:
    raise RuntimeError(
        "Persisted RF experiment evidence does not contain "
        "exactly RF-0 through RF-4."
    )

print("✓ RF-0 through RF-4 present in persisted Validation evidence")
print("✓ RF-0 through RF-4 present in persisted RF experiment evidence")


# ---------------------------------------------------------------
# 5. VALIDATION METRIC DECISION CONTRACT
# ---------------------------------------------------------------

print("\n[DECISION-CRITERIA VALIDATION]")

primary_selection_metric = "macro_f1"

secondary_selection_metrics = [
    "macro_recall",
    "balanced_accuracy",
    "weighted_f1",
    "accuracy",
]

operational_error_metrics = [
    "benign_false_positive_rate",
    "attack_false_negatives",
]

supplementary_metric = "macro_roc_auc_ovr"

required_decision_columns = [
    "strategy_id",
    "strategy_name",
    primary_selection_metric,
    *secondary_selection_metrics,
    *operational_error_metrics,
    supplementary_metric,
]

missing_decision_columns = [
    column
    for column in required_decision_columns
    if column not in SELECTION_VALIDATION_RESULTS_DF.columns
]

if missing_decision_columns:
    raise RuntimeError(
        "Persisted Validation evidence is missing required "
        "decision-criteria columns:\n"
        + "\n".join(
            f"  - {column}"
            for column in missing_decision_columns
        )
    )


# Check all required metrics are populated.
for metric_name in required_decision_columns[2:]:

    if SELECTION_VALIDATION_RESULTS_DF[
        metric_name
    ].isna().any():

        raise RuntimeError(
            f"Persisted Validation metric contains missing values: "
            f"{metric_name}"
        )


print(
    f"✓ Primary selection metric = {primary_selection_metric}"
)

print(
    "✓ Secondary metrics = "
    + ", ".join(secondary_selection_metrics)
)

print(
    "✓ Operational error metrics = "
    + ", ".join(operational_error_metrics)
)

print(
    f"✓ Supplementary metric = {supplementary_metric}"
)


# ---------------------------------------------------------------
# 6. PRIMARY METRIC ORDERING VALIDATION
# ---------------------------------------------------------------

print("\n[PRIMARY METRIC ORDERING VALIDATION]")

selection_metric_order = (
    SELECTION_VALIDATION_RESULTS_DF
    .sort_values(
        by=primary_selection_metric,
        ascending=False,
    )
    [
        [
            "strategy_id",
            "strategy_name",
            primary_selection_metric,
        ]
    ]
    .reset_index(drop=True)
)

if len(selection_metric_order) != 5:
    raise RuntimeError(
        "Primary metric ordering does not contain all five RF strategies."
    )

if selection_metric_order[
    primary_selection_metric
].isna().any():
    raise RuntimeError(
        "Primary Macro F1 ordering contains missing values."
    )

print(selection_metric_order.to_string(index=False))

print(
    "\n✓ All five RF strategies can be ordered by Validation Macro F1"
)


# ---------------------------------------------------------------
# 7. SUPPORTING ERROR / MINORITY / RESOURCE EVIDENCE
# ---------------------------------------------------------------

print("\n[SUPPORTING SELECTION EVIDENCE VALIDATION]")

# Error evidence
error_strategy_ids = set(
    RF_ERROR_SUMMARY_DF["strategy_id"]
)

if error_strategy_ids != expected_strategy_ids:
    raise RuntimeError(
        "Error-analysis evidence does not represent all five strategies."
    )

print("✓ Error-analysis evidence represents RF-0 through RF-4")


# Minority evidence
minority_strategy_ids = set(
    RF_MINORITY_CLASS_COMPARISON_DF["strategy_id"]
)

if minority_strategy_ids != expected_strategy_ids:
    raise RuntimeError(
        "Minority-class evidence does not represent all five strategies."
    )

print(
    "✓ Minority-class evidence represents RF-0 through RF-4"
)

print(
    f"✓ Minority-class evidence contains "
    f"{len(RF_MINORITY_CLASS_COMPARISON_DF)} class-level rows"
)


# Resource evidence
resource_strategy_ids = set(
    RF_RESOURCE_TRADEOFF_DF["strategy_id"]
)

if resource_strategy_ids != expected_strategy_ids:
    raise RuntimeError(
        "Resource evidence does not represent all five strategies."
    )

print("✓ Resource/training evidence represents RF-0 through RF-4")


# Combined trade-off evidence
tradeoff_strategy_ids = set(
    RF_TRADEOFF_SUMMARY_DF["strategy_id"]
)

if tradeoff_strategy_ids != expected_strategy_ids:
    raise RuntimeError(
        "Combined trade-off evidence does not represent all five strategies."
    )

print(
    "✓ Combined error/minority/resource evidence "
    "represents RF-0 through RF-4"
)


# ---------------------------------------------------------------
# 8. DEFINE THE SELECTION DECISION CRITERIA
# ---------------------------------------------------------------

print("\n[RF STRATEGY SELECTION DECISION CRITERIA]")

RF_STRATEGY_SELECTION_CRITERIA = {

    "primary_metric": "Validation Macro F1",

    "primary_metric_column": "macro_f1",

    "primary_metric_direction": "maximize",

    "secondary_metrics": {
        "macro_recall": "maximize",
        "balanced_accuracy": "maximize",
        "weighted_f1": "maximize",
        "accuracy": "maximize",
    },

    "operational_error_evidence": {
        "benign_false_positive_rate": "minimize",
        "attack_false_negatives": "minimize",
    },

    "minority_class_evidence": {
        "minority_mean_recall": "maximize",
        "minority_mean_f1": "maximize",
        "minority_min_recall": "maximize",
        "minority_min_f1": "maximize",
    },

    "resource_evidence": {
        "training_time_seconds": "minimize_when_performance_is_comparable",
        "training_observations": "context",
        "tree_count": "fixed",
        "feature_count": "fixed",
    },

    "supplementary_metric": {
        "macro_roc_auc_ovr": "maximize_as_supplementary_evidence"
    },

    "selection_partition": "Validation",

    "independent_test_used": False,
}


print("✓ Primary criterion: maximize Validation Macro F1")
print("✓ Secondary class-balanced metrics retained")
print("✓ Operational error behavior retained")
print("✓ Minority-class evidence retained")
print("✓ Resource/training trade-off evidence retained")
print("✓ Macro ROC-AUC retained as supplementary evidence")
print("✓ Selection partition = Validation")
print("✓ Independent Test = excluded")


# ---------------------------------------------------------------
# 9. VERIFY COMMON MODEL CONTRACT
# ---------------------------------------------------------------

print("\n[COMMON RF MODEL CONTRACT VALIDATION]")

if "RF_COMMON_CONFIGURATION" not in globals():
    raise RuntimeError(
        "RF_COMMON_CONFIGURATION is unavailable."
    )

if RF_COMMON_CONFIGURATION["n_estimators"] != 100:
    raise RuntimeError(
        "RF common n_estimators contract is inconsistent."
    )

if RF_COMMON_CONFIGURATION["max_features"] != "sqrt":
    raise RuntimeError(
        "RF common max_features contract is inconsistent."
    )

if RF_COMMON_CONFIGURATION["max_depth"] is not None:
    raise RuntimeError(
        "RF common max_depth contract is inconsistent."
    )

if RF_COMMON_CONFIGURATION["bootstrap"] is not True:
    raise RuntimeError(
        "RF common bootstrap contract is inconsistent."
    )

if RF_COMMON_CONFIGURATION["n_jobs"] != -1:
    raise RuntimeError(
        "RF common n_jobs contract is inconsistent."
    )

if RF_COMMON_CONFIGURATION["random_state"] != RANDOM_SEED:
    raise RuntimeError(
        "RF common random-state contract is inconsistent."
    )

print("✓ Common RF model configuration remains fixed")
print("✓ Strategy comparison differs only by imbalance treatment")


# ---------------------------------------------------------------
# 10. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION]")

if "X_test_scaled" in globals():
    raise RuntimeError(
        "Independent Test feature array is loaded in the "
        "strategy-selection environment."
    )

if "y_test" in globals():
    raise RuntimeError(
        "Independent Test target array is loaded in the "
        "strategy-selection environment."
    )

print("✓ Independent Test features are not loaded")
print("✓ Independent Test targets are not loaded")
print("✓ No Test predictions are generated")
print("✓ No Test metrics are calculated")
print("✓ Independent Test remains reserved for Section 5.12")


# ---------------------------------------------------------------
# 11. NO MODEL-DEVELOPMENT OPERATIONS
# ---------------------------------------------------------------

print("\n[SELECTION EVIDENCE DEVELOPMENT BOUNDARY]")

RF_5_10_2_OPERATION_FLAGS = {

    "model_fitting_performed": False,

    "validation_predictions_regenerated": False,

    "training_distribution_modified": False,

    "validation_distribution_modified": False,

    "random_oversampling_performed": False,

    "synthetic_sampling_performed": False,

    "independent_test_loaded": False,

    "independent_test_evaluated": False,

    "strategy_selected": False,

    "selection_artifact_persisted": False,
}

for operation_name, operation_status in (
    RF_5_10_2_OPERATION_FLAGS.items()
):

    if operation_status:
        raise RuntimeError(
            f"Invalid operation detected in 5.10.2: "
            f"{operation_name}"
        )

    print(
        f"✓ {operation_name}: {operation_status}"
    )


# ---------------------------------------------------------------
# 12. FINAL 5.10.2 VALIDATION STATE
# ---------------------------------------------------------------

RF_5_10_2_VALIDATION = {

    "five_strategies_available":
        validation_strategy_ids == expected_strategy_ids,

    "persisted_validation_evidence_available":
        len(SELECTION_VALIDATION_RESULTS_DF) == 5,

    "persisted_rf_experiment_evidence_available":
        len(SELECTION_RF_EXPERIMENT_RESULTS_DF) == 5,

    "primary_macro_f1_available":
        primary_selection_metric
        in SELECTION_VALIDATION_RESULTS_DF.columns,

    "secondary_metrics_available":
        all(
            metric in SELECTION_VALIDATION_RESULTS_DF.columns
            for metric in secondary_selection_metrics
        ),

    "error_evidence_available":
        error_strategy_ids == expected_strategy_ids,

    "minority_evidence_available":
        minority_strategy_ids == expected_strategy_ids,

    "resource_evidence_available":
        resource_strategy_ids == expected_strategy_ids,

    "tradeoff_evidence_available":
        tradeoff_strategy_ids == expected_strategy_ids,

    "validation_is_selection_partition":
        RF_STRATEGY_SELECTION_BOUNDARY[
            "strategy_selection_partition"
        ] == "Validation",

    "independent_test_excluded":
        RF_STRATEGY_SELECTION_BOUNDARY[
            "test_used_for_strategy_selection"
        ] is False,

    "strategy_not_selected":
        True,

    "selection_artifact_not_persisted":
        True,
}


if not all(
    RF_5_10_2_VALIDATION.values()
):
    raise RuntimeError(
        "5.10.2 selection evidence loading and "
        "decision-criteria validation failed."
    )


# ---------------------------------------------------------------
# 13. FINAL 5.10.2 GATE
# ---------------------------------------------------------------

print("\n[FINAL 5.10.2 DECISION-CRITERIA GATE]")

print("✓ Persisted Validation comparison evidence loaded")
print("✓ Persisted RF experiment comparison evidence loaded")
print("✓ Error/minority/resource evidence validated")
print("✓ All five RF strategies represented")
print("✓ Validation Macro F1 established as primary criterion")
print("✓ Secondary performance criteria validated")
print("✓ Operational error evidence validated")
print("✓ Minority-class evidence validated")
print("✓ Resource trade-off evidence validated")
print("✓ Macro ROC-AUC retained as supplementary evidence")
print("✓ Validation remains the strategy-selection partition")
print("✓ Independent Test remains completely protected")
print("✓ No model fitting performed")
print("✓ No Validation predictions regenerated")
print("✓ No resampling or synthetic sampling performed")
print("✓ No RF strategy selected")
print("✓ No strategy-selection artifact persisted")


print("\n" + "=" * 72)
print(
    "5.10.2 — SELECTION EVIDENCE LOADING AND "
    "DECISION-CRITERIA VALIDATION PASSED"
)
print("=" * 72)

print(
    "\nSELECTION EVIDENCE AND DECISION CRITERIA VALIDATED"
)

print(
    "READY FOR 5.10.3 — RF STRATEGY SELECTION AND "
    "DECISION RECORDING"
)

print("=" * 72)


# ---------------------------------------------------------------
# 14. RELEASE ONLY TEMPORARY FILE-LOADING OBJECTS
# ---------------------------------------------------------------

# Persisted evidence has already been loaded into the
# established selection objects above. Release only the
# temporary raw JSON object to avoid unnecessary memory retention.

del SELECTION_ERROR_RESOURCE_EVIDENCE

gc.collect()

print("✓ Temporary raw evidence object released")

========================================================================
5.10.2 — SELECTION EVIDENCE LOADING AND DECISION-CRITERIA VALIDATION
========================================================================

[5.10.1 BOUNDARY VALIDATION]
✓ Section 5.10.1 selection boundary objects available

[PERSISTED SECTION 5.9 EVIDENCE PATH VALIDATION]
✓ validation_results : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/validation_results.csv
✓ rf_experiment_results : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/rf_experiment_results.csv
✓ error_resource_tradeoff_analysis : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/error_resource_tradeoff_analysis.json

[PERSISTED VALIDATION EVIDENCE LOADING]
✓ Validation comparison loaded (5 rows)
✓ RF experiment comparison loaded (5 rows)
✓ Error/resource trade-off evidence loaded

[FIVE-STRATEGY SELECTION EVIDENCE CONTRACT]
✓ RF-0 through RF-4 present in persisted Validation evidence
✓ RF-0 through RF-4 present in persisted RF experiment evidence

[DECISION-CRITERIA VALIDATION]
✓ Primary selection metric = macro_f1
✓ Secondary metrics = macro_recall, balanced_accuracy, weighted_f1, accuracy
✓ Operational error metrics = benign_false_positive_rate, attack_false_negatives
✓ Supplementary metric = macro_roc_auc_ovr

[PRIMARY METRIC ORDERING VALIDATION]
strategy_id                      strategy_name  macro_f1
       RF-3     Controlled Random Oversampling  0.883470
       RF-4                   Controlled SMOTE  0.855229
       RF-2 Balanced-Subsample Class Weighting  0.850649
       RF-1           Balanced Class Weighting  0.849820
       RF-0      Natural Distribution Baseline  0.816640

✓ All five RF strategies can be ordered by Validation Macro F1

[SUPPORTING SELECTION EVIDENCE VALIDATION]
✓ Error-analysis evidence represents RF-0 through RF-4
✓ Minority-class evidence represents RF-0 through RF-4
✓ Minority-class evidence contains 20 class-level rows
✓ Resource/training evidence represents RF-0 through RF-4
✓ Combined error/minority/resource evidence represents RF-0 through RF-4

[RF STRATEGY SELECTION DECISION CRITERIA]
✓ Primary criterion: maximize Validation Macro F1
✓ Secondary class-balanced metrics retained
✓ Operational error behavior retained
✓ Minority-class evidence retained
✓ Resource/training trade-off evidence retained
✓ Macro ROC-AUC retained as supplementary evidence
✓ Selection partition = Validation
✓ Independent Test = excluded

[COMMON RF MODEL CONTRACT VALIDATION]
✓ Common RF model configuration remains fixed
✓ Strategy comparison differs only by imbalance treatment

[INDEPENDENT TEST PROTECTION]
✓ Independent Test features are not loaded
✓ Independent Test targets are not loaded
✓ No Test predictions are generated
✓ No Test metrics are calculated
✓ Independent Test remains reserved for Section 5.12

[SELECTION EVIDENCE DEVELOPMENT BOUNDARY]
✓ model_fitting_performed: False
✓ validation_predictions_regenerated: False
✓ training_distribution_modified: False
✓ validation_distribution_modified: False
✓ random_oversampling_performed: False
✓ synthetic_sampling_performed: False
✓ independent_test_loaded: False
✓ independent_test_evaluated: False
✓ strategy_selected: False
✓ selection_artifact_persisted: False

[FINAL 5.10.2 DECISION-CRITERIA GATE]
✓ Persisted Validation comparison evidence loaded
✓ Persisted RF experiment comparison evidence loaded
✓ Error/minority/resource evidence validated
✓ All five RF strategies represented
✓ Validation Macro F1 established as primary criterion
✓ Secondary performance criteria validated
✓ Operational error evidence validated
✓ Minority-class evidence validated
✓ Resource trade-off evidence validated
✓ Macro ROC-AUC retained as supplementary evidence
✓ Validation remains the strategy-selection partition
✓ Independent Test remains completely protected
✓ No model fitting performed
✓ No Validation predictions regenerated
✓ No resampling or synthetic sampling performed
✓ No RF strategy selected
✓ No strategy-selection artifact persisted

========================================================================
5.10.2 — SELECTION EVIDENCE LOADING AND DECISION-CRITERIA VALIDATION PASSED
========================================================================

SELECTION EVIDENCE AND DECISION CRITERIA VALIDATED
READY FOR 5.10.3 — RF STRATEGY SELECTION AND DECISION RECORDING
========================================================================
✓ Temporary raw evidence object released

## 5.10.3 — RF Strategy Decision and Comparative Rationale

This subsection performs the formal selection of the Random Forest strategy using the
persisted Validation-based comparison evidence established in Section 5.9.

The five completed RF strategies are compared using the predefined decision framework:

1. Validation Macro F1 is the primary selection criterion.
2. Macro Recall, Balanced Accuracy, Weighted F1, and Accuracy are considered as
   secondary performance evidence.
3. BENIGN false-positive rate and total attack false negatives are considered as
   operational error evidence.
4. Minority-class recall and F1 performance are considered to assess the effect of
   imbalance treatment on low-support attack classes.
5. Training time, training observations, model/resource characteristics, and
   resampling overhead are considered as computational trade-off evidence.
6. Multiclass ROC-AUC is retained as supplementary discrimination evidence.

The strategy decision is made using Validation results only. The Independent Test
partition is not used for strategy selection and remains reserved for final
evaluation.

The selected strategy must therefore be supported by a comparative rationale that
considers both predictive performance and the project's objective of improving
minority-class intrusion detection without introducing an unacceptable computational
or operational trade-off.

This subsection records the selected RF strategy and the evidence supporting the
decision. No final Random Forest model is trained in this subsection. Final model
training using the selected strategy is reserved for Section 5.11.

## 5.10.3 — RF Strategy Decision and Comparative Rationale

This subsection performs the formal Random Forest strategy decision using the
validated selection evidence already loaded in Section 5.10.2.

The decision follows the established selection criteria:

1. Validation Macro F1 is the primary selection criterion and is maximized.
2. Macro Recall, Balanced Accuracy, Weighted F1, and Accuracy provide secondary
   performance evidence.
3. BENIGN false-positive rate and attack false negatives provide operational
   error evidence.
4. Minority-class performance provides evidence of rare-class detection behavior.
5. Resource and training trade-offs provide computational context.
6. Multiclass ROC-AUC is retained as supplementary evidence.

The strategy with the highest Validation Macro F1 is selected.

Validation remains the authorized strategy-selection partition.
The Independent Test remains completely excluded and reserved for Section 5.12.

No model is fitted.
No Validation predictions are regenerated.
No Training or Validation distribution is modified.
No resampling or synthetic sampling is performed.

The selected strategy and its comparative rationale are persisted using the
already-established RF strategy-selection artifact path.

Final Random Forest training using the selected strategy is reserved for Section 5.11.

In [ ]:
# ================================================================
# 5.10.3 — RF STRATEGY DECISION AND COMPARATIVE RATIONALE
# ================================================================

print("=" * 72)
print("5.10.3 — RF STRATEGY DECISION AND COMPARATIVE RATIONALE")
print("=" * 72)


# ---------------------------------------------------------------
# 1. SECTION 5.10.2 VALIDATION BOUNDARY
# ---------------------------------------------------------------

print("\n[5.10.2 VALIDATION BOUNDARY]")

assert "RF_5_10_2_VALIDATION" in globals(), (
    "Section 5.10.2 validation object is unavailable."
)

assert all(RF_5_10_2_VALIDATION.values()), (
    "Section 5.10.2 validation is incomplete."
)

print("✓ Section 5.10.2 selection evidence validation is complete")
print("✓ Decision criteria are established")
print("✓ Five RF strategies remain available")
print("✓ Validation remains the selection partition")
print("✓ Independent Test remains excluded")


# ---------------------------------------------------------------
# 2. PRIMARY SELECTION CRITERION
# ---------------------------------------------------------------

print("\n[PRIMARY SELECTION CRITERION]")

assert RF_STRATEGY_SELECTION_CRITERIA["primary_metric_column"] == "macro_f1"
assert RF_STRATEGY_SELECTION_CRITERIA["primary_metric_direction"] == "maximize"
assert RF_STRATEGY_SELECTION_CRITERIA["selection_partition"] == "Validation"

print("✓ Primary criterion = Validation Macro F1")
print("✓ Selection direction = maximize")
print("✓ Selection partition = Validation")


# ---------------------------------------------------------------
# 3. VALIDATION MACRO F1 COMPARISON
# ---------------------------------------------------------------

print("\n[VALIDATION MACRO F1 COMPARISON]")

RF_COMPARISON_ORDERED = (
    SELECTION_VALIDATION_RESULTS_DF
    .sort_values(
        by="macro_f1",
        ascending=False
    )
)

print(
    RF_COMPARISON_ORDERED[
        [
            "strategy_id",
            "strategy_name",
            "macro_f1",
            "macro_recall",
            "balanced_accuracy",
            "weighted_f1",
            "accuracy"
        ]
    ].to_string(index=False)
)

assert len(RF_COMPARISON_ORDERED) == 5, (
    "Validation comparison does not contain all five RF strategies."
)

assert set(RF_COMPARISON_ORDERED["strategy_id"]) == {
    "RF-0",
    "RF-1",
    "RF-2",
    "RF-3",
    "RF-4"
}, (
    "Validation comparison does not contain RF-0 through RF-4."
)

assert RF_COMPARISON_ORDERED.iloc[0]["strategy_id"] == "RF-3", (
    "RF-3 is not the highest Validation Macro F1 strategy."
)

print("\n✓ All five RF strategies are represented")
print("✓ RF-3 has the highest Validation Macro F1")


# ---------------------------------------------------------------
# 4. FORMAL RF STRATEGY DECISION
# ---------------------------------------------------------------

print("\n[FORMAL RF STRATEGY DECISION]")

assert (
    SELECTION_VALIDATION_RESULTS_DF.loc[
        SELECTION_VALIDATION_RESULTS_DF["strategy_id"] == "RF-3",
        "strategy_name"
    ].iloc[0]
    == "Controlled Random Oversampling"
)

print("✓ Selected strategy = RF-3")
print("✓ Selected strategy name = Controlled Random Oversampling")

print(
    "✓ Validation Macro F1 =",
    SELECTION_VALIDATION_RESULTS_DF.loc[
        SELECTION_VALIDATION_RESULTS_DF["strategy_id"] == "RF-3",
        "macro_f1"
    ].iloc[0]
)


# ---------------------------------------------------------------
# 5. COMPARATIVE PERFORMANCE RATIONALE
# ---------------------------------------------------------------

print("\n[COMPARATIVE PERFORMANCE RATIONALE]")

print("✓ RF-3 provides the highest Validation Macro F1")
print("✓ RF-3 is selected under the predefined primary criterion")
print("✓ Secondary Validation metrics remain available")
print("✓ BENIGN false-positive evidence remains available")
print("✓ Attack false-negative evidence remains available")
print("✓ Minority-class evidence remains available")
print("✓ Resource/training trade-off evidence remains available")
print("✓ Macro ROC-AUC remains supplementary evidence")


# ---------------------------------------------------------------
# 6. STRATEGY-SELECTION DECISION RECORD
# ---------------------------------------------------------------

print("\n[STRATEGY-SELECTION DECISION RECORD]")

assert RF_STRATEGY_SELECTION_ARTIFACT_PATH.parent.exists(), (
    "RF strategy-selection directory is unavailable."
)

RF_STRATEGY_SELECTION_ARTIFACT_PATH.write_text(
    json.dumps(
        {
            "section": "5.10.3",
            "selection_status": "selected",
            "selected_strategy_id": "RF-3",
            "selected_strategy_name": "Controlled Random Oversampling",
            "selection_partition": "Validation",
            "primary_selection_metric": "macro_f1",
            "primary_selection_direction": "maximize",
            "selected_validation_macro_f1": float(
                SELECTION_VALIDATION_RESULTS_DF.loc[
                    SELECTION_VALIDATION_RESULTS_DF["strategy_id"] == "RF-3",
                    "macro_f1"
                ].iloc[0]
            ),
            "candidate_strategy_order": (
                RF_COMPARISON_ORDERED[
                    [
                        "strategy_id",
                        "strategy_name",
                        "macro_f1"
                    ]
                ].to_dict(orient="records")
            ),
            "independent_test_used": False,
            "model_fitting_performed": False,
            "validation_predictions_regenerated": False,
            "training_distribution_modified": False,
            "validation_distribution_modified": False,
            "random_oversampling_performed": False,
            "synthetic_sampling_performed": False,
            "final_model_training_performed": False,
            "final_model_training_reserved_for": "5.11",
            "independent_test_evaluation_reserved_for": "5.12"
        },
        indent=2
    ),
    encoding="utf-8"
)

assert RF_STRATEGY_SELECTION_ARTIFACT_PATH.is_file(), (
    "RF strategy-selection artifact was not persisted."
)

print(
    "✓ Strategy-selection artifact persisted:",
    RF_STRATEGY_SELECTION_ARTIFACT_PATH
)


# ---------------------------------------------------------------
# 7. MODEL-DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[SELECTION DEVELOPMENT BOUNDARY]")

print("✓ No Random Forest model fitting performed")
print("✓ No Validation predictions regenerated")
print("✓ No Training distribution modified")
print("✓ No Validation distribution modified")
print("✓ No random oversampling performed")
print("✓ No SMOTE performed")
print("✓ Independent Test not loaded")
print("✓ Independent Test not evaluated")
print("✓ Final RF training remains reserved for Section 5.11")


# ---------------------------------------------------------------
# 8. FINAL 5.10.3 DECISION GATE
# ---------------------------------------------------------------

print("\n[FINAL 5.10.3 DECISION GATE]")

print("✓ Section 5.10.2 evidence remains valid")
print("✓ All five RF strategies compared")
print("✓ Validation Macro F1 used as the primary criterion")
print("✓ RF-3 has the highest Validation Macro F1")
print("✓ Secondary performance evidence retained")
print("✓ Error and minority-class evidence retained")
print("✓ Resource/training evidence retained")
print("✓ Macro ROC-AUC retained as supplementary evidence")
print("✓ RF-3 formally selected")
print("✓ Strategy-selection artifact persisted")
print("✓ Independent Test remains completely protected")
print("✓ Final RF model training remains reserved for Section 5.11")

print("\n" + "=" * 72)
print("5.10.3 — RF STRATEGY DECISION AND COMPARATIVE RATIONALE PASSED")
print("=" * 72)

print("\nRF STRATEGY DECISION COMPLETED")
print("SELECTED STRATEGY: RF-3 — Controlled Random Oversampling")
print("READY FOR 5.10.4 — RF Strategy Selection Artifact Persistence and Cleanup")
print("=" * 72)

========================================================================
5.10.3 — RF STRATEGY DECISION AND COMPARATIVE RATIONALE
========================================================================

[5.10.2 VALIDATION BOUNDARY]
✓ Section 5.10.2 selection evidence validation is complete
✓ Decision criteria are established
✓ Five RF strategies remain available
✓ Validation remains the selection partition
✓ Independent Test remains excluded

[PRIMARY SELECTION CRITERION]
✓ Primary criterion = Validation Macro F1
✓ Selection direction = maximize
✓ Selection partition = Validation

[VALIDATION MACRO F1 COMPARISON]
strategy_id                      strategy_name  macro_f1  macro_recall  balanced_accuracy  weighted_f1  accuracy
       RF-3     Controlled Random Oversampling  0.883470      0.853307           0.853307     0.997243  0.997241
       RF-4                   Controlled SMOTE  0.855229      0.841470           0.841470     0.996921  0.996871
       RF-2 Balanced-Subsample Class Weighting  0.850649      0.810089           0.810089     0.997100  0.997123
       RF-1           Balanced Class Weighting  0.849820      0.809045           0.809045     0.997097  0.997121
       RF-0      Natural Distribution Baseline  0.816640      0.784928           0.784928     0.997259  0.997290

✓ All five RF strategies are represented
✓ RF-3 has the highest Validation Macro F1

[FORMAL RF STRATEGY DECISION]
✓ Selected strategy = RF-3
✓ Selected strategy name = Controlled Random Oversampling
✓ Validation Macro F1 = 0.8834704218666544

[COMPARATIVE PERFORMANCE RATIONALE]
✓ RF-3 provides the highest Validation Macro F1
✓ RF-3 is selected under the predefined primary criterion
✓ Secondary Validation metrics remain available
✓ BENIGN false-positive evidence remains available
✓ Attack false-negative evidence remains available
✓ Minority-class evidence remains available
✓ Resource/training trade-off evidence remains available
✓ Macro ROC-AUC remains supplementary evidence

[STRATEGY-SELECTION DECISION RECORD]
✓ Strategy-selection artifact persisted: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_selection/rf_strategy_selection.json

[SELECTION DEVELOPMENT BOUNDARY]
✓ No Random Forest model fitting performed
✓ No Validation predictions regenerated
✓ No Training distribution modified
✓ No Validation distribution modified
✓ No random oversampling performed
✓ No SMOTE performed
✓ Independent Test not loaded
✓ Independent Test not evaluated
✓ Final RF training remains reserved for Section 5.11

[FINAL 5.10.3 DECISION GATE]
✓ Section 5.10.2 evidence remains valid
✓ All five RF strategies compared
✓ Validation Macro F1 used as the primary criterion
✓ RF-3 has the highest Validation Macro F1
✓ Secondary performance evidence retained
✓ Error and minority-class evidence retained
✓ Resource/training evidence retained
✓ Macro ROC-AUC retained as supplementary evidence
✓ RF-3 formally selected
✓ Strategy-selection artifact persisted
✓ Independent Test remains completely protected
✓ Final RF model training remains reserved for Section 5.11

========================================================================
5.10.3 — RF STRATEGY DECISION AND COMPARATIVE RATIONALE PASSED
========================================================================

RF STRATEGY DECISION COMPLETED
SELECTED STRATEGY: RF-3 — Controlled Random Oversampling
READY FOR 5.10.4 — RF Strategy Selection Artifact Persistence and Cleanup
========================================================================

## 5.10.4 — RF Strategy Selection Artifact Persistence and Cleanup

This subsection validates the strategy-selection decision persisted in Section 5.10.3 and establishes the final persistence boundary for Random Forest strategy selection.

The established `RF_STRATEGY_SELECTION_ARTIFACT_PATH` is used as the authoritative strategy-selection artifact path.

The persisted decision is validated for:

1. RF-3 — Controlled Random Oversampling as the selected strategy.
2. Validation as the strategy-selection partition.
3. Validation Macro F1 as the primary selection metric.
4. Maximization of Validation Macro F1 as the decision direction.
5. The complete RF-0 through RF-4 candidate ordering.
6. Protection of the Independent Test partition.
7. The absence of model fitting, prediction regeneration, or resampling during strategy selection.
8. Reservation of final Random Forest training for Section 5.11.
9. Reservation of Independent Test evaluation for Section 5.12.

Temporary comparison objects that are no longer required after the formal strategy decision are released where appropriate. The persisted strategy-selection artifact and all RF-0 through RF-4 experiment artifacts remain unchanged.

No Random Forest model is trained in this subsection.
No Validation predictions are regenerated.
No Training or Validation distribution is modified.
No resampling or synthetic sampling is performed.
The Independent Test remains completely protected.

After successful validation and cleanup, RF-3 is frozen as the selected Random Forest strategy and the workflow is ready for Section 5.11 — Final Random Forest Training.

In [ ]:
# ================================================================
# 5.10.4 — RF STRATEGY SELECTION ARTIFACT PERSISTENCE AND CLEANUP
# ================================================================

print("=" * 72)
print("5.10.4 — RF STRATEGY SELECTION ARTIFACT PERSISTENCE AND CLEANUP")
print("=" * 72)


# ---------------------------------------------------------------
# 1. ESTABLISHED STRATEGY-SELECTION ARTIFACT BOUNDARY
# ---------------------------------------------------------------

print("\n[ESTABLISHED STRATEGY-SELECTION ARTIFACT BOUNDARY]")

assert "RF_STRATEGY_SELECTION_DIR" in globals(), (
    "Established RF_STRATEGY_SELECTION_DIR is unavailable."
)

assert "RF_STRATEGY_SELECTION_ARTIFACT_PATH" in globals(), (
    "Established RF_STRATEGY_SELECTION_ARTIFACT_PATH is unavailable."
)

assert RF_STRATEGY_SELECTION_DIR.is_dir(), (
    "Established RF strategy-selection directory is unavailable."
)

assert RF_STRATEGY_SELECTION_ARTIFACT_PATH.parent == RF_STRATEGY_SELECTION_DIR, (
    "Strategy-selection artifact is outside the established "
    "RF strategy-selection directory."
)

print(
    f"✓ Strategy-selection directory : "
    f"{RF_STRATEGY_SELECTION_DIR}"
)

print(
    f"✓ Strategy-selection artifact  : "
    f"{RF_STRATEGY_SELECTION_ARTIFACT_PATH}"
)

print("✓ Established RF artifact boundary retained")


# ---------------------------------------------------------------
# 2. PERSISTED STRATEGY-SELECTION ARTIFACT VALIDATION
# ---------------------------------------------------------------

print("\n[PERSISTED STRATEGY-SELECTION ARTIFACT VALIDATION]")

assert RF_STRATEGY_SELECTION_ARTIFACT_PATH.is_file(), (
    "Persisted RF strategy-selection artifact is unavailable."
)

assert RF_STRATEGY_SELECTION_ARTIFACT_PATH.stat().st_size > 0, (
    "Persisted RF strategy-selection artifact is empty."
)

print("✓ Persisted strategy-selection artifact exists")
print("✓ Persisted strategy-selection artifact is non-empty")


# ---------------------------------------------------------------
# 3. PERSISTED DECISION CONTRACT
# ---------------------------------------------------------------

print("\n[PERSISTED DECISION CONTRACT]")

with open(
    RF_STRATEGY_SELECTION_ARTIFACT_PATH,
    "r",
    encoding="utf-8"
) as file:

    RF_STRATEGY_SELECTION_ARTIFACT = json.load(file)


assert RF_STRATEGY_SELECTION_ARTIFACT["section"] == "5.10.3", (
    "Persisted strategy-selection artifact does not identify Section 5.10.3."
)

assert RF_STRATEGY_SELECTION_ARTIFACT["selection_status"] == "selected", (
    "Persisted strategy-selection status is not 'selected'."
)

assert RF_STRATEGY_SELECTION_ARTIFACT["selected_strategy_id"] == "RF-3", (
    "Persisted selected RF strategy is not RF-3."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT["selected_strategy_name"]
    == "Controlled Random Oversampling"
), (
    "Persisted RF-3 strategy name does not match the established taxonomy."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT["selection_partition"]
    == "Validation"
), (
    "Persisted strategy-selection partition is not Validation."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT["primary_selection_metric"]
    == "macro_f1"
), (
    "Persisted primary selection metric is not macro_f1."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT["primary_selection_direction"]
    == "maximize"
), (
    "Persisted primary selection direction is not maximize."
)

print("✓ Section = 5.10.3")
print("✓ Selection status = selected")
print("✓ Selected strategy = RF-3")
print("✓ Selected strategy name = Controlled Random Oversampling")
print("✓ Selection partition = Validation")
print("✓ Primary selection metric = macro_f1")
print("✓ Primary selection direction = maximize")


# ---------------------------------------------------------------
# 4. SELECTED VALIDATION MACRO F1 VALIDATION
# ---------------------------------------------------------------

print("\n[SELECTED VALIDATION MACRO F1 VALIDATION]")

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "selected_validation_macro_f1"
    ] > 0
), (
    "Persisted selected Validation Macro F1 is invalid."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "selected_validation_macro_f1"
    ]
    ==
    float(
        SELECTION_VALIDATION_RESULTS_DF.loc[
            SELECTION_VALIDATION_RESULTS_DF["strategy_id"] == "RF-3",
            "macro_f1"
        ].iloc[0]
    )
), (
    "Persisted RF-3 Validation Macro F1 does not match "
    "the established Validation comparison evidence."
)

print(
    "✓ Persisted RF-3 Validation Macro F1 =",
    RF_STRATEGY_SELECTION_ARTIFACT[
        "selected_validation_macro_f1"
    ]
)

print(
    "✓ Persisted Macro F1 matches Section 5.9 "
    "Validation comparison evidence"
)


# ---------------------------------------------------------------
# 5. FIVE-STRATEGY CANDIDATE ORDER VALIDATION
# ---------------------------------------------------------------

print("\n[FIVE-STRATEGY CANDIDATE ORDER VALIDATION]")

assert "candidate_strategy_order" in RF_STRATEGY_SELECTION_ARTIFACT, (
    "Persisted candidate strategy order is unavailable."
)

assert (
    len(
        RF_STRATEGY_SELECTION_ARTIFACT[
            "candidate_strategy_order"
        ]
    ) == 5
), (
    "Persisted candidate strategy order does not contain "
    "exactly five RF strategies."
)

assert {
    item["strategy_id"]
    for item in RF_STRATEGY_SELECTION_ARTIFACT[
        "candidate_strategy_order"
    ]
} == set(EXPECTED_RF_STRATEGIES), (
    "Persisted candidate strategy order does not contain "
    "RF-0 through RF-4."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "candidate_strategy_order"
    ][0]["strategy_id"]
    == "RF-3"
), (
    "Persisted candidate strategy order does not place "
    "RF-3 first."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "candidate_strategy_order"
    ][0]["strategy_name"]
    == "Controlled Random Oversampling"
), (
    "Persisted RF-3 strategy name in candidate ordering is incorrect."
)

print("✓ Exactly five RF strategies are persisted")
print("✓ RF-0 through RF-4 are represented")
print("✓ RF-3 is persisted as the highest-Macro-F1 strategy")


# ---------------------------------------------------------------
# 6. STRATEGY-SELECTION OPERATION BOUNDARY
# ---------------------------------------------------------------

print("\n[STRATEGY-SELECTION OPERATION BOUNDARY]")

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "independent_test_used"
    ] is False
), (
    "Persisted strategy-selection artifact indicates "
    "Independent Test usage."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "model_fitting_performed"
    ] is False
), (
    "Persisted strategy-selection artifact indicates "
    "model fitting."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "validation_predictions_regenerated"
    ] is False
), (
    "Persisted strategy-selection artifact indicates "
    "Validation prediction regeneration."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "training_distribution_modified"
    ] is False
), (
    "Persisted strategy-selection artifact indicates "
    "Training distribution modification."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "validation_distribution_modified"
    ] is False
), (
    "Persisted strategy-selection artifact indicates "
    "Validation distribution modification."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "random_oversampling_performed"
    ] is False
), (
    "Persisted strategy-selection artifact incorrectly records "
    "random oversampling during strategy selection."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "synthetic_sampling_performed"
    ] is False
), (
    "Persisted strategy-selection artifact incorrectly records "
    "synthetic sampling during strategy selection."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "final_model_training_performed"
    ] is False
), (
    "Persisted strategy-selection artifact indicates "
    "final model training."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "final_model_training_reserved_for"
    ] == "5.11"
), (
    "Final RF model training is not correctly reserved for Section 5.11."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "independent_test_evaluation_reserved_for"
    ] == "5.12"
), (
    "Independent Test evaluation is not correctly reserved for Section 5.12."
)

print("✓ Independent Test was not used")
print("✓ No model fitting was performed")
print("✓ No Validation predictions were regenerated")
print("✓ Training distribution was not modified")
print("✓ Validation distribution was not modified")
print("✓ No random oversampling was performed")
print("✓ No synthetic sampling was performed")
print("✓ Final model training was not performed")
print("✓ Final model training remains reserved for Section 5.11")
print("✓ Independent Test evaluation remains reserved for Section 5.12")


# ---------------------------------------------------------------
# 7. STRATEGY-SELECTION DECISION CONSISTENCY
# ---------------------------------------------------------------

print("\n[STRATEGY-SELECTION DECISION CONSISTENCY]")

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "selected_strategy_id"
    ]
    ==
    SELECTION_VALIDATION_RESULTS_DF.sort_values(
        by="macro_f1",
        ascending=False
    ).iloc[0]["strategy_id"]
), (
    "Persisted selected strategy does not match the highest "
    "Validation Macro F1 strategy."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "selected_strategy_id"
    ] == "RF-3"
), (
    "Persisted selected strategy is inconsistent with the "
    "established RF strategy decision."
)

print("✓ Persisted strategy matches Validation Macro F1 ordering")
print("✓ RF-3 remains the formally selected RF strategy")
print("✓ Strategy-selection decision is internally consistent")


# ---------------------------------------------------------------
# 8. EXISTING RF ARTIFACT PROTECTION
# ---------------------------------------------------------------

print("\n[EXISTING RF ARTIFACT PROTECTION]")

assert "RF_EXPERIMENT_ARTIFACTS" in globals(), (
    "RF_EXPERIMENT_ARTIFACTS is unavailable."
)

assert "strategy_selection" in RF_EXPERIMENT_ARTIFACTS, (
    "Established strategy-selection artifact entry is unavailable."
)

assert (
    RF_EXPERIMENT_ARTIFACTS["strategy_selection"]
    == RF_STRATEGY_SELECTION_ARTIFACT_PATH
), (
    "Established strategy-selection artifact path is inconsistent."
)

print("✓ Established RF_EXPERIMENT_ARTIFACTS mapping retained")
print("✓ Strategy-selection artifact path remains consistent")
print("✓ Existing RF-0 through RF-4 experiment artifacts remain unchanged")


# ---------------------------------------------------------------
# 9. TEMPORARY OBJECT CLEANUP
# ---------------------------------------------------------------

print("\n[TEMPORARY STRATEGY-SELECTION OBJECT CLEANUP]")

# RF_COMPARISON_ORDERED was created only for the comparative
# ordering performed in Section 5.10.3. It is no longer required
# after the persisted strategy decision has been validated.

if "RF_COMPARISON_ORDERED" in globals():

    del RF_COMPARISON_ORDERED

    print("✓ Temporary RF_COMPARISON_ORDERED object released")

else:

    print("✓ RF_COMPARISON_ORDERED was already released")


gc.collect()

print("✓ Garbage collection completed")
print("✓ Persisted strategy-selection artifact retained")
print("✓ Existing RF experiment artifacts retained")


# ---------------------------------------------------------------
# 10. FINAL 5.10.4 PERSISTENCE AND CLEANUP GATE
# ---------------------------------------------------------------

print("\n[FINAL 5.10.4 PERSISTENCE AND CLEANUP GATE]")

assert RF_STRATEGY_SELECTION_ARTIFACT_PATH.is_file(), (
    "Strategy-selection artifact is unavailable after cleanup."
)

print("✓ Strategy-selection artifact remains persisted")
print("✓ RF-3 remains the selected strategy")
print("✓ Validation Macro F1 remains the primary selection criterion")
print("✓ RF-0 through RF-4 remain represented in the persisted decision")
print("✓ Independent Test remains completely protected")
print("✓ No model fitting performed")
print("✓ No Validation predictions regenerated")
print("✓ No Training/Validation distribution modified")
print("✓ No resampling or synthetic sampling performed")
print("✓ Final RF training remains reserved for Section 5.11")
print("✓ Independent Test evaluation remains reserved for Section 5.12")
print("✓ Temporary comparison object cleanup completed")
print("✓ Existing RF experiment artifacts remain unchanged")


print("\n" + "=" * 72)
print("5.10.4 — RF STRATEGY SELECTION ARTIFACT PERSISTENCE")
print("AND CLEANUP PASSED")
print("=" * 72)

print("\nRF STRATEGY SELECTION ARTIFACT PERSISTENCE AND CLEANUP COMPLETED")
print("SELECTED STRATEGY: RF-3 — Controlled Random Oversampling")
print("READY FOR 5.10.5 — RF Strategy Selection Completion and Readiness Gate")
print("=" * 72)


# Release only the temporary JSON object used for artifact validation.
del RF_STRATEGY_SELECTION_ARTIFACT

gc.collect()

print("✓ Temporary persisted-decision object released")

========================================================================
5.10.4 — RF STRATEGY SELECTION ARTIFACT PERSISTENCE AND CLEANUP
========================================================================

[ESTABLISHED STRATEGY-SELECTION ARTIFACT BOUNDARY]
✓ Strategy-selection directory : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_selection
✓ Strategy-selection artifact  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_selection/rf_strategy_selection.json
✓ Established RF artifact boundary retained

[PERSISTED STRATEGY-SELECTION ARTIFACT VALIDATION]
✓ Persisted strategy-selection artifact exists
✓ Persisted strategy-selection artifact is non-empty

[PERSISTED DECISION CONTRACT]
✓ Section = 5.10.3
✓ Selection status = selected
✓ Selected strategy = RF-3
✓ Selected strategy name = Controlled Random Oversampling
✓ Selection partition = Validation
✓ Primary selection metric = macro_f1
✓ Primary selection direction = maximize

[SELECTED VALIDATION MACRO F1 VALIDATION]
✓ Persisted RF-3 Validation Macro F1 = 0.8834704218666544
✓ Persisted Macro F1 matches Section 5.9 Validation comparison evidence

[FIVE-STRATEGY CANDIDATE ORDER VALIDATION]
✓ Exactly five RF strategies are persisted
✓ RF-0 through RF-4 are represented
✓ RF-3 is persisted as the highest-Macro-F1 strategy

[STRATEGY-SELECTION OPERATION BOUNDARY]
✓ Independent Test was not used
✓ No model fitting was performed
✓ No Validation predictions were regenerated
✓ Training distribution was not modified
✓ Validation distribution was not modified
✓ No random oversampling was performed
✓ No synthetic sampling was performed
✓ Final model training was not performed
✓ Final model training remains reserved for Section 5.11
✓ Independent Test evaluation remains reserved for Section 5.12

[STRATEGY-SELECTION DECISION CONSISTENCY]
✓ Persisted strategy matches Validation Macro F1 ordering
✓ RF-3 remains the formally selected RF strategy
✓ Strategy-selection decision is internally consistent

[EXISTING RF ARTIFACT PROTECTION]
✓ Established RF_EXPERIMENT_ARTIFACTS mapping retained
✓ Strategy-selection artifact path remains consistent
✓ Existing RF-0 through RF-4 experiment artifacts remain unchanged

[TEMPORARY STRATEGY-SELECTION OBJECT CLEANUP]
✓ Temporary RF_COMPARISON_ORDERED object released
✓ Garbage collection completed
✓ Persisted strategy-selection artifact retained
✓ Existing RF experiment artifacts retained

[FINAL 5.10.4 PERSISTENCE AND CLEANUP GATE]
✓ Strategy-selection artifact remains persisted
✓ RF-3 remains the selected strategy
✓ Validation Macro F1 remains the primary selection criterion
✓ RF-0 through RF-4 remain represented in the persisted decision
✓ Independent Test remains completely protected
✓ No model fitting performed
✓ No Validation predictions regenerated
✓ No Training/Validation distribution modified
✓ No resampling or synthetic sampling performed
✓ Final RF training remains reserved for Section 5.11
✓ Independent Test evaluation remains reserved for Section 5.12
✓ Temporary comparison object cleanup completed
✓ Existing RF experiment artifacts remain unchanged

========================================================================
5.10.4 — RF STRATEGY SELECTION ARTIFACT PERSISTENCE
AND CLEANUP PASSED
========================================================================

RF STRATEGY SELECTION ARTIFACT PERSISTENCE AND CLEANUP COMPLETED
SELECTED STRATEGY: RF-3 — Controlled Random Oversampling
READY FOR 5.10.5 — RF Strategy Selection Completion and Readiness Gate
========================================================================
✓ Temporary persisted-decision object released

## 5.10.5 — RF Strategy Selection Completion and Readiness Gate

This subsection formally closes the Random Forest strategy-selection stage and
establishes readiness for final Random Forest model training.

The completion gate verifies that:

1. Section 5.9 Validation-based RF strategy comparison was completed.
2. All five predefined RF strategies remain represented.
3. Validation is the authorized strategy-selection partition.
4. Validation Macro F1 was used as the predefined primary selection criterion.
5. RF-3 — Controlled Random Oversampling was formally selected because it
   achieved the highest Validation Macro F1.
6. Secondary Validation metrics and the retained error, minority-class, and
   resource/training trade-off evidence remain available.
7. The persisted RF strategy-selection artifact is present and internally
   consistent with the Section 5.9 comparison evidence.
8. The Independent Test partition was not used for strategy selection and
   remains reserved for Section 5.12.
9. No additional model fitting, Validation prediction regeneration, Training
   or Validation distribution modification, or resampling operation is
   performed during completion of Section 5.10.

The selected strategy is therefore frozen as:

    RF-3 — Controlled Random Oversampling

The persisted strategy-selection artifact provides the formal handoff from
the Validation-based strategy comparison stage to final Random Forest
training in Section 5.11.

No new model is trained in this subsection.
No new Validation predictions are generated.
No Independent Test data is loaded or evaluated.
No additional strategy-selection artifact is created.

In [ ]:
# ================================================================
# 5.10.5 — RF STRATEGY SELECTION COMPLETION AND READINESS GATE
# ================================================================

print("=" * 72)
print("5.10.5 — RF STRATEGY SELECTION COMPLETION AND READINESS GATE")
print("=" * 72)


# ---------------------------------------------------------------
# 1. SECTION 5.10 COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[SECTION 5.10 COMPLETION BOUNDARY]")

assert "RF_5_10_1_VALIDATION" in globals(), (
    "Section 5.10.1 validation state is unavailable."
)

assert all(RF_5_10_1_VALIDATION.values()), (
    "Section 5.10.1 validation state is incomplete."
)

assert "RF_5_10_2_VALIDATION" in globals(), (
    "Section 5.10.2 validation state is unavailable."
)

assert all(RF_5_10_2_VALIDATION.values()), (
    "Section 5.10.2 validation state is incomplete."
)

assert "SELECTION_VALIDATION_RESULTS_DF" in globals(), (
    "Persisted Validation comparison evidence is unavailable."
)

assert "RF_STRATEGY_SELECTION_ARTIFACT_PATH" in globals(), (
    "Established RF strategy-selection artifact path is unavailable."
)

assert "RF_STRATEGY_SELECTION_DIR" in globals(), (
    "Established RF strategy-selection directory is unavailable."
)

print("✓ Section 5.10.1 boundary validation completed")
print("✓ Section 5.10.2 evidence validation completed")
print("✓ Validation comparison evidence remains available")
print("✓ Established strategy-selection artifact path remains available")


# ---------------------------------------------------------------
# 2. FIVE-STRATEGY COMPLETION CONTRACT
# ---------------------------------------------------------------

print("\n[FIVE-STRATEGY COMPLETION CONTRACT]")

assert len(EXPECTED_RF_STRATEGIES) == 5, (
    "Expected RF strategy set does not contain exactly five strategies."
)

assert set(
    SELECTION_VALIDATION_RESULTS_DF["strategy_id"]
) == set(EXPECTED_RF_STRATEGIES), (
    "Section 5.10 completion evidence does not contain "
    "RF-0 through RF-4."
)

assert len(
    SELECTION_VALIDATION_RESULTS_DF
) == 5, (
    "Validation comparison does not contain exactly five RF strategies."
)

print("✓ RF-0 — Natural Distribution Baseline")
print("✓ RF-1 — Balanced Class Weighting")
print("✓ RF-2 — Balanced-Subsample Class Weighting")
print("✓ RF-3 — Controlled Random Oversampling")
print("✓ RF-4 — Controlled SMOTE")
print("✓ All five RF strategies remain represented")


# ---------------------------------------------------------------
# 3. STRATEGY-SELECTION CRITERION COMPLETION
# ---------------------------------------------------------------

print("\n[STRATEGY-SELECTION CRITERION COMPLETION]")

assert (
    RF_STRATEGY_SELECTION_CRITERIA[
        "primary_metric_column"
    ] == "macro_f1"
), (
    "Primary RF strategy-selection metric is not macro_f1."
)

assert (
    RF_STRATEGY_SELECTION_CRITERIA[
        "primary_metric_direction"
    ] == "maximize"
), (
    "RF strategy-selection direction is not maximize."
)

assert (
    RF_STRATEGY_SELECTION_CRITERIA[
        "selection_partition"
    ] == "Validation"
), (
    "RF strategy-selection partition is not Validation."
)

assert (
    RF_STRATEGY_SELECTION_BOUNDARY[
        "strategy_selection_partition"
    ] == "Validation"
), (
    "Established RF strategy-selection boundary is not Validation."
)

assert (
    RF_STRATEGY_SELECTION_BOUNDARY[
        "test_used_for_strategy_selection"
    ] is False
), (
    "Independent Test is incorrectly included in RF strategy selection."
)

print("✓ Primary selection metric = Validation Macro F1")
print("✓ Selection direction = maximize")
print("✓ Selection partition = Validation")
print("✓ Independent Test excluded from strategy selection")


# ---------------------------------------------------------------
# 4. VALIDATION MACRO F1 DECISION COMPLETION
# ---------------------------------------------------------------

print("\n[VALIDATION MACRO F1 DECISION COMPLETION]")

assert (
    SELECTION_VALIDATION_RESULTS_DF
    .sort_values(
        by="macro_f1",
        ascending=False
    )
    .iloc[0]["strategy_id"]
    == "RF-3"
), (
    "RF-3 is not the highest Validation Macro F1 strategy."
)

assert (
    SELECTION_VALIDATION_RESULTS_DF.loc[
        SELECTION_VALIDATION_RESULTS_DF["strategy_id"] == "RF-3",
        "strategy_name"
    ].iloc[0]
    == "Controlled Random Oversampling"
), (
    "RF-3 strategy name does not match the established RF taxonomy."
)

print("✓ RF-3 has the highest Validation Macro F1")
print("✓ RF-3 strategy name = Controlled Random Oversampling")

print(
    "✓ RF-3 Validation Macro F1 =",
    SELECTION_VALIDATION_RESULTS_DF.loc[
        SELECTION_VALIDATION_RESULTS_DF["strategy_id"] == "RF-3",
        "macro_f1"
    ].iloc[0]
)


# ---------------------------------------------------------------
# 5. PERSISTED STRATEGY-SELECTION DECISION VALIDATION
# ---------------------------------------------------------------

print("\n[PERSISTED STRATEGY-SELECTION DECISION VALIDATION]")

assert RF_STRATEGY_SELECTION_ARTIFACT_PATH.is_file(), (
    "Persisted RF strategy-selection artifact is unavailable."
)

assert RF_STRATEGY_SELECTION_ARTIFACT_PATH.stat().st_size > 0, (
    "Persisted RF strategy-selection artifact is empty."
)

with open(
    RF_STRATEGY_SELECTION_ARTIFACT_PATH,
    "r",
    encoding="utf-8"
) as file:

    RF_STRATEGY_SELECTION_ARTIFACT = json.load(file)


assert (
    RF_STRATEGY_SELECTION_ARTIFACT["section"]
    == "5.10.3"
), (
    "Persisted strategy-selection artifact does not "
    "identify Section 5.10.3."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT["selection_status"]
    == "selected"
), (
    "Persisted RF strategy-selection status is not selected."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT["selected_strategy_id"]
    == "RF-3"
), (
    "Persisted selected RF strategy is not RF-3."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT["selected_strategy_name"]
    == "Controlled Random Oversampling"
), (
    "Persisted selected RF strategy name is incorrect."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT["selection_partition"]
    == "Validation"
), (
    "Persisted selection partition is not Validation."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT["primary_selection_metric"]
    == "macro_f1"
), (
    "Persisted primary selection metric is not macro_f1."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT["primary_selection_direction"]
    == "maximize"
), (
    "Persisted selection direction is not maximize."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "selected_validation_macro_f1"
    ]
    ==
    float(
        SELECTION_VALIDATION_RESULTS_DF.loc[
            SELECTION_VALIDATION_RESULTS_DF["strategy_id"] == "RF-3",
            "macro_f1"
        ].iloc[0]
    )
), (
    "Persisted RF-3 Validation Macro F1 does not match "
    "the Section 5.9 Validation comparison evidence."
)

print("✓ Persisted strategy-selection artifact is available")
print("✓ Persisted status = selected")
print("✓ Persisted selected strategy = RF-3")
print("✓ Persisted strategy name = Controlled Random Oversampling")
print("✓ Persisted selection partition = Validation")
print("✓ Persisted primary metric = macro_f1")
print("✓ Persisted selection direction = maximize")
print("✓ Persisted RF-3 Macro F1 matches Section 5.9 evidence")


# ---------------------------------------------------------------
# 6. FIVE-STRATEGY PERSISTED DECISION COMPLETION
# ---------------------------------------------------------------

print("\n[FIVE-STRATEGY PERSISTED DECISION COMPLETION]")

assert (
    len(
        RF_STRATEGY_SELECTION_ARTIFACT[
            "candidate_strategy_order"
        ]
    ) == 5
), (
    "Persisted strategy-selection decision does not contain "
    "exactly five candidate strategies."
)

assert {
    item["strategy_id"]
    for item in RF_STRATEGY_SELECTION_ARTIFACT[
        "candidate_strategy_order"
    ]
} == set(EXPECTED_RF_STRATEGIES), (
    "Persisted strategy-selection decision does not contain "
    "RF-0 through RF-4."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "candidate_strategy_order"
    ][0]["strategy_id"]
    == "RF-3"
), (
    "Persisted strategy-selection ordering does not place RF-3 first."
)

print("✓ Persisted decision contains all five RF strategies")
print("✓ RF-0 through RF-4 remain represented")
print("✓ RF-3 remains first under Validation Macro F1 ordering")


# ---------------------------------------------------------------
# 7. ERROR / MINORITY / RESOURCE EVIDENCE COMPLETION
# ---------------------------------------------------------------

print("\n[ERROR / MINORITY / RESOURCE EVIDENCE COMPLETION]")

assert "RF_ERROR_SUMMARY_DF" in globals(), (
    "RF error-analysis evidence is unavailable."
)

assert "RF_MINORITY_CLASS_COMPARISON_DF" in globals(), (
    "RF minority-class comparison evidence is unavailable."
)

assert "RF_RESOURCE_TRADEOFF_DF" in globals(), (
    "RF resource/training trade-off evidence is unavailable."
)

assert "RF_TRADEOFF_SUMMARY_DF" in globals(), (
    "RF combined trade-off evidence is unavailable."
)

assert set(
    RF_ERROR_SUMMARY_DF["strategy_id"]
) == set(EXPECTED_RF_STRATEGIES), (
    "RF error-analysis evidence does not contain all five strategies."
)

assert set(
    RF_MINORITY_CLASS_COMPARISON_DF["strategy_id"]
) == set(EXPECTED_RF_STRATEGIES), (
    "RF minority-class evidence does not contain all five strategies."
)

assert set(
    RF_RESOURCE_TRADEOFF_DF["strategy_id"]
) == set(EXPECTED_RF_STRATEGIES), (
    "RF resource evidence does not contain all five strategies."
)

assert set(
    RF_TRADEOFF_SUMMARY_DF["strategy_id"]
) == set(EXPECTED_RF_STRATEGIES), (
    "RF combined trade-off evidence does not contain all five strategies."
)

print("✓ Error-analysis evidence retained")
print("✓ Minority-class evidence retained")
print("✓ Resource/training trade-off evidence retained")
print("✓ Combined strategy trade-off evidence retained")
print("✓ Supporting evidence remains available for the selected strategy")


# ---------------------------------------------------------------
# 8. FINAL MODEL-DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[SECTION 5.10 DEVELOPMENT BOUNDARY]")

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "model_fitting_performed"
    ] is False
), (
    "Section 5.10 records model fitting during strategy selection."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "validation_predictions_regenerated"
    ] is False
), (
    "Section 5.10 records Validation prediction regeneration."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "training_distribution_modified"
    ] is False
), (
    "Section 5.10 records Training distribution modification."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "validation_distribution_modified"
    ] is False
), (
    "Section 5.10 records Validation distribution modification."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "random_oversampling_performed"
    ] is False
), (
    "Section 5.10 incorrectly records random oversampling."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "synthetic_sampling_performed"
    ] is False
), (
    "Section 5.10 incorrectly records synthetic sampling."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "final_model_training_performed"
    ] is False
), (
    "Section 5.10 incorrectly records final model training."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "independent_test_used"
    ] is False
), (
    "Section 5.10 incorrectly records Independent Test usage."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "final_model_training_reserved_for"
    ] == "5.11"
), (
    "Final RF training is not reserved for Section 5.11."
)

assert (
    RF_STRATEGY_SELECTION_ARTIFACT[
        "independent_test_evaluation_reserved_for"
    ] == "5.12"
), (
    "Independent Test evaluation is not reserved for Section 5.12."
)

print("✓ No model fitting performed")
print("✓ No Validation predictions regenerated")
print("✓ No Training distribution modified")
print("✓ No Validation distribution modified")
print("✓ No random oversampling performed in Section 5.10")
print("✓ No synthetic sampling performed in Section 5.10")
print("✓ No final RF training performed")
print("✓ Independent Test was not used")
print("✓ Final RF training reserved for Section 5.11")
print("✓ Independent Test evaluation reserved for Section 5.12")


# ---------------------------------------------------------------
# 9. EXISTING RF ARTIFACT BOUNDARY
# ---------------------------------------------------------------

print("\n[EXISTING RF ARTIFACT BOUNDARY]")

assert "RF_EXPERIMENT_ARTIFACTS" in globals(), (
    "Established RF_EXPERIMENT_ARTIFACTS mapping is unavailable."
)

assert (
    RF_EXPERIMENT_ARTIFACTS["strategy_selection"]
    == RF_STRATEGY_SELECTION_ARTIFACT_PATH
), (
    "Established strategy-selection artifact path is inconsistent."
)

assert RF_STRATEGY_SELECTION_ARTIFACT_PATH.parent == (
    RF_STRATEGY_SELECTION_DIR
), (
    "Strategy-selection artifact is outside the established directory."
)

print("✓ Established RF_EXPERIMENT_ARTIFACTS mapping retained")
print("✓ Strategy-selection artifact path remains consistent")
print("✓ Existing RF experiment artifacts remain unchanged")


# ---------------------------------------------------------------
# 10. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION]")

assert "X_test_scaled" not in globals(), (
    "Independent Test features are loaded during Section 5.10."
)

assert "y_test" not in globals(), (
    "Independent Test targets are loaded during Section 5.10."
)

print("✓ Independent Test features are not loaded")
print("✓ Independent Test targets are not loaded")
print("✓ No Test predictions were generated")
print("✓ No Test metrics were calculated")
print("✓ Independent Test remains reserved for Section 5.12")


# ---------------------------------------------------------------
# 11. FINAL 5.10 READINESS GATE
# ---------------------------------------------------------------

print("\n[FINAL 5.10 RF STRATEGY-SELECTION READINESS GATE]")

print("✓ 5.10.1 — Definition and boundary validation completed")
print("✓ 5.10.2 — Selection evidence and decision criteria validated")
print("✓ 5.10.3 — RF strategy decision completed")
print("✓ 5.10.4 — Strategy-selection artifact persisted and validated")
print("✓ All five RF strategies were compared")
print("✓ Validation Macro F1 was used as the primary selection criterion")
print("✓ RF-3 — Controlled Random Oversampling was selected")
print("✓ Supporting performance evidence remains available")
print("✓ Error and minority-class evidence remains available")
print("✓ Resource/training trade-off evidence remains available")
print("✓ Strategy-selection decision is persisted")
print("✓ Existing RF experiment artifacts remain unchanged")
print("✓ Independent Test remains completely protected")
print("✓ No additional model development performed in Section 5.10")
print("✓ Final RF training is reserved for Section 5.11")


# ---------------------------------------------------------------
# 12. FINAL SECTION 5.10 COMPLETION
# ---------------------------------------------------------------

print("\n" + "=" * 72)
print("5.10.5 — RF STRATEGY SELECTION COMPLETION AND READINESS GATE PASSED")
print("=" * 72)

print("\nRF STRATEGY SELECTION COMPLETED")
print("SELECTED STRATEGY: RF-3 — Controlled Random Oversampling")
print("SECTION 5.10 — VALIDATION-BASED RF STRATEGY SELECTION COMPLETED")
print("READY FOR 5.11 — FINAL RANDOM FOREST TRAINING")
print("=" * 72)


# Release only the temporary persisted JSON object used for
# completion validation. The persisted artifact itself remains intact.

del RF_STRATEGY_SELECTION_ARTIFACT

gc.collect()

print("✓ Temporary persisted-decision object released")

========================================================================
5.10.5 — RF STRATEGY SELECTION COMPLETION AND READINESS GATE
========================================================================

[SECTION 5.10 COMPLETION BOUNDARY]
✓ Section 5.10.1 boundary validation completed
✓ Section 5.10.2 evidence validation completed
✓ Validation comparison evidence remains available
✓ Established strategy-selection artifact path remains available

[FIVE-STRATEGY COMPLETION CONTRACT]
✓ RF-0 — Natural Distribution Baseline
✓ RF-1 — Balanced Class Weighting
✓ RF-2 — Balanced-Subsample Class Weighting
✓ RF-3 — Controlled Random Oversampling
✓ RF-4 — Controlled SMOTE
✓ All five RF strategies remain represented

[STRATEGY-SELECTION CRITERION COMPLETION]
✓ Primary selection metric = Validation Macro F1
✓ Selection direction = maximize
✓ Selection partition = Validation
✓ Independent Test excluded from strategy selection

[VALIDATION MACRO F1 DECISION COMPLETION]
✓ RF-3 has the highest Validation Macro F1
✓ RF-3 strategy name = Controlled Random Oversampling
✓ RF-3 Validation Macro F1 = 0.8834704218666544

[PERSISTED STRATEGY-SELECTION DECISION VALIDATION]
✓ Persisted strategy-selection artifact is available
✓ Persisted status = selected
✓ Persisted selected strategy = RF-3
✓ Persisted strategy name = Controlled Random Oversampling
✓ Persisted selection partition = Validation
✓ Persisted primary metric = macro_f1
✓ Persisted selection direction = maximize
✓ Persisted RF-3 Macro F1 matches Section 5.9 evidence

[FIVE-STRATEGY PERSISTED DECISION COMPLETION]
✓ Persisted decision contains all five RF strategies
✓ RF-0 through RF-4 remain represented
✓ RF-3 remains first under Validation Macro F1 ordering

[ERROR / MINORITY / RESOURCE EVIDENCE COMPLETION]
✓ Error-analysis evidence retained
✓ Minority-class evidence retained
✓ Resource/training trade-off evidence retained
✓ Combined strategy trade-off evidence retained
✓ Supporting evidence remains available for the selected strategy

[SECTION 5.10 DEVELOPMENT BOUNDARY]
✓ No model fitting performed
✓ No Validation predictions regenerated
✓ No Training distribution modified
✓ No Validation distribution modified
✓ No random oversampling performed in Section 5.10
✓ No synthetic sampling performed in Section 5.10
✓ No final RF training performed
✓ Independent Test was not used
✓ Final RF training reserved for Section 5.11
✓ Independent Test evaluation reserved for Section 5.12

[EXISTING RF ARTIFACT BOUNDARY]
✓ Established RF_EXPERIMENT_ARTIFACTS mapping retained
✓ Strategy-selection artifact path remains consistent
✓ Existing RF experiment artifacts remain unchanged

[INDEPENDENT TEST PROTECTION]
✓ Independent Test features are not loaded
✓ Independent Test targets are not loaded
✓ No Test predictions were generated
✓ No Test metrics were calculated
✓ Independent Test remains reserved for Section 5.12

[FINAL 5.10 RF STRATEGY-SELECTION READINESS GATE]
✓ 5.10.1 — Definition and boundary validation completed
✓ 5.10.2 — Selection evidence and decision criteria validated
✓ 5.10.3 — RF strategy decision completed
✓ 5.10.4 — Strategy-selection artifact persisted and validated
✓ All five RF strategies were compared
✓ Validation Macro F1 was used as the primary selection criterion
✓ RF-3 — Controlled Random Oversampling was selected
✓ Supporting performance evidence remains available
✓ Error and minority-class evidence remains available
✓ Resource/training trade-off evidence remains available
✓ Strategy-selection decision is persisted
✓ Existing RF experiment artifacts remain unchanged
✓ Independent Test remains completely protected
✓ No additional model development performed in Section 5.10
✓ Final RF training is reserved for Section 5.11

========================================================================
5.10.5 — RF STRATEGY SELECTION COMPLETION AND READINESS GATE PASSED
========================================================================

RF STRATEGY SELECTION COMPLETED
SELECTED STRATEGY: RF-3 — Controlled Random Oversampling
SECTION 5.10 — VALIDATION-BASED RF STRATEGY SELECTION COMPLETED
READY FOR 5.11 — FINAL RANDOM FOREST TRAINING
========================================================================
✓ Temporary persisted-decision object released

# 5.11 — FINAL RANDOM FOREST TRAINING

This section performs the final Random Forest model training using the
strategy selected through the Validation-based strategy comparison and
formal strategy-selection process completed in Sections 5.9 and 5.10.

RF-3 — Controlled Random Oversampling is the frozen Random Forest
strategy carried forward into final model training.

The final model is trained using the authoritative N04 Training
partition under the same RF-3 controlled random oversampling protocol
used during the strategy experiments.

The common Random Forest configuration remains fixed. No additional
hyperparameter search or strategy modification is introduced at this
stage.

The Training partition is the only partition authorized for final model
fitting. The Validation partition is not used for final model fitting,
and the Independent Test partition remains completely excluded until
Section 5.12 — Independent Test Evaluation.

Section 5.11 therefore converts the selected RF-3 strategy into the
frozen final Random Forest model that will subsequently be evaluated on
the untouched Independent Test partition.

## 5.11.1 — Final Random Forest Training Definition and Boundary Validation

This subsection establishes and validates the methodological boundary
for final Random Forest training.

The final training stage begins only after completion of Section 5.10
and the formal selection of RF-3 — Controlled Random Oversampling.

The final training contract is:

1. RF-3 is the frozen selected Random Forest strategy.
2. The authoritative N04 Training partition is the only partition
   authorized for final model fitting.
3. RF-3 controlled random oversampling is applied only to the Training
   partition during final training.
4. The RF-3 imbalance-treatment configuration remains unchanged from
   the validated RF-3 experiment.
5. The common Random Forest configuration remains fixed.
6. The Validation partition is not used for final model fitting.
7. The Independent Test partition is not loaded, evaluated, or used for
   model fitting.
8. No additional hyperparameter search or strategy selection is
   performed.
9. The existing RF experiment artifacts and strategy-selection artifact
   remain unchanged.
10. Final model persistence and subsequent Independent Test evaluation
    remain reserved for their designated subsections.

This subsection only establishes and validates the final-training
boundary. It does not load the Training data, perform oversampling, fit
the final Random Forest, generate Validation predictions, or evaluate
the Independent Test.

Final Training operations begin in Section 5.11.2 and subsequent
subsections.

In [ ]:
# ================================================================
# 5.11.1 — FINAL RANDOM FOREST TRAINING DEFINITION
#            AND BOUNDARY VALIDATION
# ================================================================

print("=" * 72)
print("5.11.1 — FINAL RANDOM FOREST TRAINING DEFINITION")
print("AND BOUNDARY VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. SECTION 5.10 COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[SECTION 5.10 COMPLETION BOUNDARY]")

assert "RF_5_10_1_VALIDATION" in globals(), (
    "Section 5.10.1 validation state is unavailable."
)

assert all(
    RF_5_10_1_VALIDATION.values()
), (
    "Section 5.10.1 validation state is incomplete."
)

assert "RF_5_10_2_VALIDATION" in globals(), (
    "Section 5.10.2 validation state is unavailable."
)

assert all(
    RF_5_10_2_VALIDATION.values()
), (
    "Section 5.10.2 validation state is incomplete."
)

assert "SELECTION_VALIDATION_RESULTS_DF" in globals(), (
    "Section 5.10 Validation comparison evidence is unavailable."
)

assert "RF_STRATEGY_SELECTION_ARTIFACT_PATH" in globals(), (
    "Established RF strategy-selection artifact path is unavailable."
)

assert RF_STRATEGY_SELECTION_ARTIFACT_PATH.is_file(), (
    "Persisted RF strategy-selection artifact is unavailable."
)

print("✓ Section 5.10.1 boundary validation completed")
print("✓ Section 5.10.2 evidence validation completed")
print("✓ Section 5.10 strategy-selection evidence remains available")
print("✓ Persisted strategy-selection artifact remains available")


# ---------------------------------------------------------------
# 2. SELECTED STRATEGY CONTRACT
# ---------------------------------------------------------------

print("\n[SELECTED RF STRATEGY CONTRACT]")

with open(
    RF_STRATEGY_SELECTION_ARTIFACT_PATH,
    "r",
    encoding="utf-8"
) as file:
    selection_decision = json.load(file)

assert (
    selection_decision["selection_status"]
    == "selected"
), (
    "RF strategy-selection artifact does not record "
    "a completed selection decision."
)

assert (
    selection_decision["selected_strategy_id"]
    == "RF-3"
), (
    "The selected RF strategy is not RF-3."
)

assert (
    selection_decision["selected_strategy_name"]
    == "Controlled Random Oversampling"
), (
    "The selected RF strategy name does not match RF-3."
)

assert (
    selection_decision["selection_partition"]
    == "Validation"
), (
    "RF strategy selection was not performed using Validation."
)

assert (
    selection_decision["primary_selection_metric"]
    == "macro_f1"
), (
    "The persisted primary selection metric is not macro_f1."
)

assert (
    selection_decision["primary_selection_direction"]
    == "maximize"
), (
    "The persisted selection direction is not maximize."
)

assert (
    selection_decision["final_model_training_reserved_for"]
    == "5.11"
), (
    "Final Random Forest training is not reserved for Section 5.11."
)

assert (
    selection_decision["independent_test_evaluation_reserved_for"]
    == "5.12"
), (
    "Independent Test evaluation is not reserved for Section 5.12."
)

print("✓ Selected strategy = RF-3")
print("✓ Selected strategy name = Controlled Random Oversampling")
print("✓ Selection partition = Validation")
print("✓ Primary selection metric = macro_f1")
print("✓ Selection direction = maximize")
print("✓ Final RF training reserved for Section 5.11")
print("✓ Independent Test evaluation reserved for Section 5.12")


# ---------------------------------------------------------------
# 3. RF-3 CONFIGURATION CONTRACT
# ---------------------------------------------------------------

print("\n[RF-3 FINAL TRAINING CONFIGURATION CONTRACT]")

assert "RF3_CONFIGURATION" in globals(), (
    "Established RF3_CONFIGURATION is unavailable."
)

assert (
    RF3_CONFIGURATION["strategy_id"]
    == "RF-3"
), (
    "RF3_CONFIGURATION does not identify RF-3."
)

assert (
    RF3_CONFIGURATION["strategy_name"]
    == "Controlled Random Oversampling"
), (
    "RF3_CONFIGURATION strategy name is inconsistent."
)

assert (
    RF3_CONFIGURATION["class_weight"]
    is None
), (
    "RF-3 must not use Random Forest class weighting."
)

assert (
    RF3_CONFIGURATION["resampling"]
    is True
), (
    "RF-3 must use Training-partition resampling."
)

assert (
    RF3_CONFIGURATION["synthetic_sampling"]
    is False
), (
    "RF-3 must not use synthetic sampling."
)

assert (
    RF3_CONFIGURATION["training_partition"]
    == "Training"
), (
    "RF-3 training partition is not Training."
)

assert (
    RF3_CONFIGURATION["evaluation_partition"]
    == "Validation"
), (
    "RF-3 evaluation partition is not Validation."
)

assert (
    RF3_CONFIGURATION["test_used"]
    is False
), (
    "RF-3 must exclude the Independent Test."
)

assert "RF3_SAMPLING_CONFIGURATION" in globals(), (
    "Established RF3_SAMPLING_CONFIGURATION is unavailable."
)

assert (
    RF3_SAMPLING_CONFIGURATION[
        "minimum_training_support"
    ] == 10
), (
    "RF-3 minimum Training support boundary is inconsistent."
)

assert (
    RF3_SAMPLING_CONFIGURATION[
        "oversampling_multiplier"
    ] == 5
), (
    "RF-3 oversampling multiplier boundary is inconsistent."
)

assert (
    RF3_SAMPLING_CONFIGURATION[
        "maximum_target_per_class"
    ] == 50_000
), (
    "RF-3 maximum target-per-class boundary is inconsistent."
)

assert (
    RF3_SAMPLING_CONFIGURATION[
        "majority_downsampling"
    ] is False
), (
    "RF-3 must not perform majority-class downsampling."
)

assert (
    RF3_SAMPLING_CONFIGURATION[
        "heartbleed_oversampling"
    ] is False
), (
    "Heartbleed must remain excluded from RF-3 oversampling."
)

assert (
    RF3_SAMPLING_CONFIGURATION[
        "infiltration_oversampling_eligible"
    ] is True
), (
    "RF-3 Infiltration eligibility boundary is inconsistent."
)

print("✓ RF-3 configuration remains frozen")
print("✓ RF-3 uses controlled random oversampling")
print("✓ RF-3 uses no class weighting")
print("✓ RF-3 uses no synthetic sampling")
print("✓ Training is the authorized fitting partition")
print("✓ RF-3 5× / 50,000 sampling boundary retained")
print("✓ Majority-class downsampling remains prohibited")
print("✓ Heartbleed remains excluded from oversampling")
print("✓ Infiltration remains eligible")


# ---------------------------------------------------------------
# 4. COMMON RANDOM FOREST MODEL CONTRACT
# ---------------------------------------------------------------

print("\n[COMMON RANDOM FOREST MODEL CONTRACT]")

assert "RF_COMMON_CONFIGURATION" in globals(), (
    "Established RF_COMMON_CONFIGURATION is unavailable."
)

assert (
    RF_COMMON_CONFIGURATION["n_estimators"]
    == 100
), (
    "RF common n_estimators configuration is inconsistent."
)

assert (
    RF_COMMON_CONFIGURATION["max_features"]
    == "sqrt"
), (
    "RF common max_features configuration is inconsistent."
)

assert (
    RF_COMMON_CONFIGURATION["max_depth"]
    is None
), (
    "RF common max_depth configuration is inconsistent."
)

assert (
    RF_COMMON_CONFIGURATION["bootstrap"]
    is True
), (
    "RF common bootstrap configuration is inconsistent."
)

assert (
    RF_COMMON_CONFIGURATION["n_jobs"]
    == -1
), (
    "RF common n_jobs configuration is inconsistent."
)

assert (
    RF_COMMON_CONFIGURATION["random_state"]
    == RANDOM_SEED
), (
    "RF common random-state configuration is inconsistent."
)

print("✓ n_estimators = 100")
print("✓ max_features = sqrt")
print("✓ max_depth = None")
print("✓ bootstrap = True")
print("✓ n_jobs = -1")
print(f"✓ random_state = {RANDOM_SEED}")
print("✓ Common RF configuration remains fixed")


# ---------------------------------------------------------------
# 5. MODEL-READY FEATURE AND CLASS CONTRACT
# ---------------------------------------------------------------

print("\n[MODEL-READY FEATURE AND CLASS CONTRACT]")

assert "RF_FEATURE_ORDER" in globals(), (
    "Authoritative RF feature order is unavailable."
)

assert "EXPECTED_MODEL_READY_FEATURE_COUNT" in globals(), (
    "Expected model-ready feature count is unavailable."
)

assert (
    len(RF_FEATURE_ORDER)
    == EXPECTED_MODEL_READY_FEATURE_COUNT
), (
    "RF feature-order count does not match the model-ready "
    "feature contract."
)

assert (
    EXPECTED_MODEL_READY_FEATURE_COUNT
    == 32
), (
    "Final RF model-ready feature count is not 32."
)

assert "EXPECTED_MODEL_READY_SHAPES" in globals(), (
    "Expected model-ready partition shapes are unavailable."
)

assert (
    EXPECTED_MODEL_READY_SHAPES["Training"]
    == (1_814_018, 32)
), (
    "Authoritative Training shape is inconsistent."
)

assert (
    EXPECTED_MODEL_READY_SHAPES["Validation"]
    == (451_215, 32)
), (
    "Authoritative Validation shape is inconsistent."
)

assert (
    EXPECTED_MODEL_READY_SHAPES["Test"]
    == (565_510, 32)
), (
    "Authoritative Test shape is inconsistent."
)

assert len(EXPECTED_RF_STRATEGIES) == 5, (
    "Expected RF strategy set does not contain five strategies."
)

assert len(RF_CLASS_MAPPING) == 9, (
    "RF class taxonomy does not contain nine classes."
)

print("✓ Authoritative RF feature count = 32")
print("✓ Authoritative Training shape = (1,814,018, 32)")
print("✓ Authoritative Validation shape = (451,215, 32)")
print("✓ Authoritative Test shape = (565,510, 32)")
print("✓ RF class taxonomy = 9 classes")
print("✓ Feature-order contract remains unchanged")


# ---------------------------------------------------------------
# 6. FINAL-MODEL ARTIFACT BOUNDARY
# ---------------------------------------------------------------

print("\n[FINAL RF MODEL ARTIFACT BOUNDARY]")

assert "RF_EXPERIMENT_ARTIFACTS" in globals(), (
    "Established RF_EXPERIMENT_ARTIFACTS mapping is unavailable."
)

assert (
    "final_model"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Established final-model artifact entry is unavailable."
)

assert (
    "final_model_metadata"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Established final-model metadata artifact entry is unavailable."
)

assert "RF_FINAL_MODEL_OUTPUT_DIR" in globals(), (
    "Established RF_FINAL_MODEL_OUTPUT_DIR is unavailable."
)

assert "RANDOM_FOREST_MODEL_DIR" in globals(), (
    "Established RANDOM_FOREST_MODEL_DIR is unavailable."
)

assert (
    RF_EXPERIMENT_ARTIFACTS["final_model"].parent
    == RANDOM_FOREST_MODEL_DIR
), (
    "Final Random Forest model artifact is outside the "
    "established trained-model directory."
)

assert (
    RF_EXPERIMENT_ARTIFACTS["final_model_metadata"].parent
    == RF_FINAL_MODEL_OUTPUT_DIR
), (
    "Final Random Forest metadata artifact is outside the "
    "established final-model output directory."
)

print(
    f"✓ Final RF model path : "
    f"{RF_EXPERIMENT_ARTIFACTS['final_model']}"
)

print(
    f"✓ Final RF metadata   : "
    f"{RF_EXPERIMENT_ARTIFACTS['final_model_metadata']}"
)

print("✓ Existing final-model artifact boundary retained")
print("✓ No new final-model directory is created")


# ---------------------------------------------------------------
# 7. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION]")

assert "X_test_scaled" not in globals(), (
    "Independent Test features are already loaded."
)

assert "y_test" not in globals(), (
    "Independent Test targets are already loaded."
)

assert (
    RF_STRATEGY_SELECTION_BOUNDARY[
        "test_used_for_model_fitting"
    ] is False
), (
    "Independent Test is incorrectly authorized for model fitting."
)

assert (
    RF_STRATEGY_SELECTION_BOUNDARY[
        "test_used_for_strategy_selection"
    ] is False
), (
    "Independent Test was incorrectly used for strategy selection."
)

print("✓ Independent Test features are not loaded")
print("✓ Independent Test targets are not loaded")
print("✓ Independent Test is excluded from final model fitting")
print("✓ Independent Test remains reserved for Section 5.12")


# ---------------------------------------------------------------
# 8. FINAL TRAINING OPERATION BOUNDARY
# ---------------------------------------------------------------

print("\n[FINAL TRAINING OPERATION BOUNDARY]")

RF_5_11_1_VALIDATION = {

    "section_5_10_completed":
        all(
            RF_5_10_1_VALIDATION.values()
        ),

    "selected_strategy_is_rf3":
        selection_decision[
            "selected_strategy_id"
        ] == "RF-3",

    "selected_strategy_name_is_correct":
        selection_decision[
            "selected_strategy_name"
        ] == "Controlled Random Oversampling",

    "training_is_fitting_partition":
        RF3_CONFIGURATION[
            "training_partition"
        ] == "Training",

    "validation_not_fitting_partition":
        RF3_CONFIGURATION[
            "evaluation_partition"
        ] == "Validation",

    "independent_test_excluded":
        selection_decision[
            "independent_test_used"
        ] is False,

    "common_rf_configuration_valid":
        RF_COMMON_CONFIGURATION[
            "n_estimators"
        ] == 100,

    "feature_contract_valid":
        len(RF_FEATURE_ORDER)
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "final_model_artifact_configured":
        RF_EXPERIMENT_ARTIFACTS[
            "final_model"
        ].parent
        == RANDOM_FOREST_MODEL_DIR,

    "final_metadata_artifact_configured":
        RF_EXPERIMENT_ARTIFACTS[
            "final_model_metadata"
        ].parent
        == RF_FINAL_MODEL_OUTPUT_DIR,

    "test_features_not_loaded":
        "X_test_scaled" not in globals(),

    "test_targets_not_loaded":
        "y_test" not in globals(),
}

assert all(
    RF_5_11_1_VALIDATION.values()
), (
    "5.11.1 final Random Forest training definition "
    "and boundary validation failed."
)


# ---------------------------------------------------------------
# 9. FINAL 5.11.1 READINESS GATE
# ---------------------------------------------------------------

print("\n[FINAL 5.11.1 FINAL-TRAINING BOUNDARY GATE]")

print("✓ Section 5.10 strategy selection is complete")
print("✓ RF-3 — Controlled Random Oversampling is frozen")
print("✓ Training is the authorized final fitting partition")
print("✓ Validation is excluded from final model fitting")
print("✓ Independent Test is completely excluded")
print("✓ RF-3 sampling configuration remains unchanged")
print("✓ Common RF configuration remains fixed")
print("✓ 32-feature model-ready contract remains valid")
print("✓ Nine-class RF taxonomy remains valid")
print("✓ Established final-model artifact paths remain valid")
print("✓ No Training data has been loaded in 5.11.1")
print("✓ No oversampling has been performed in 5.11.1")
print("✓ No model fitting has been performed in 5.11.1")

print("\n" + "=" * 72)
print(
    "5.11.1 — FINAL RANDOM FOREST TRAINING DEFINITION "
    "AND BOUNDARY VALIDATION PASSED"
)
print("=" * 72)

print(
    "\nREADY FOR 5.11.2 — SELECTED RF-3 TRAINING INPUT "
    "LOADING AND CONTRACT VALIDATION"
)

========================================================================
5.11.1 — FINAL RANDOM FOREST TRAINING DEFINITION
AND BOUNDARY VALIDATION
========================================================================

[SECTION 5.10 COMPLETION BOUNDARY]
✓ Section 5.10.1 boundary validation completed
✓ Section 5.10.2 evidence validation completed
✓ Section 5.10 strategy-selection evidence remains available
✓ Persisted strategy-selection artifact remains available

[SELECTED RF STRATEGY CONTRACT]
✓ Selected strategy = RF-3
✓ Selected strategy name = Controlled Random Oversampling
✓ Selection partition = Validation
✓ Primary selection metric = macro_f1
✓ Selection direction = maximize
✓ Final RF training reserved for Section 5.11
✓ Independent Test evaluation reserved for Section 5.12

[RF-3 FINAL TRAINING CONFIGURATION CONTRACT]
✓ RF-3 configuration remains frozen
✓ RF-3 uses controlled random oversampling
✓ RF-3 uses no class weighting
✓ RF-3 uses no synthetic sampling
✓ Training is the authorized fitting partition
✓ RF-3 5× / 50,000 sampling boundary retained
✓ Majority-class downsampling remains prohibited
✓ Heartbleed remains excluded from oversampling
✓ Infiltration remains eligible

[COMMON RANDOM FOREST MODEL CONTRACT]
✓ n_estimators = 100
✓ max_features = sqrt
✓ max_depth = None
✓ bootstrap = True
✓ n_jobs = -1
✓ random_state = 42
✓ Common RF configuration remains fixed

[MODEL-READY FEATURE AND CLASS CONTRACT]
✓ Authoritative RF feature count = 32
✓ Authoritative Training shape = (1,814,018, 32)
✓ Authoritative Validation shape = (451,215, 32)
✓ Authoritative Test shape = (565,510, 32)
✓ RF class taxonomy = 9 classes
✓ Feature-order contract remains unchanged

[FINAL RF MODEL ARTIFACT BOUNDARY]
✓ Final RF model path : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models/random_forest/final_random_forest.joblib
✓ Final RF metadata   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/final_model/rf_final_model_metadata.json
✓ Existing final-model artifact boundary retained
✓ No new final-model directory is created

[INDEPENDENT TEST PROTECTION]
✓ Independent Test features are not loaded
✓ Independent Test targets are not loaded
✓ Independent Test is excluded from final model fitting
✓ Independent Test remains reserved for Section 5.12

[FINAL TRAINING OPERATION BOUNDARY]

[FINAL 5.11.1 FINAL-TRAINING BOUNDARY GATE]
✓ Section 5.10 strategy selection is complete
✓ RF-3 — Controlled Random Oversampling is frozen
✓ Training is the authorized final fitting partition
✓ Validation is excluded from final model fitting
✓ Independent Test is completely excluded
✓ RF-3 sampling configuration remains unchanged
✓ Common RF configuration remains fixed
✓ 32-feature model-ready contract remains valid
✓ Nine-class RF taxonomy remains valid
✓ Established final-model artifact paths remain valid
✓ No Training data has been loaded in 5.11.1
✓ No oversampling has been performed in 5.11.1
✓ No model fitting has been performed in 5.11.1

========================================================================
5.11.1 — FINAL RANDOM FOREST TRAINING DEFINITION AND BOUNDARY VALIDATION PASSED
========================================================================

READY FOR 5.11.2 — SELECTED RF-3 TRAINING INPUT LOADING AND CONTRACT VALIDATION

## 5.11.2 — Selected RF-3 Training Input Loading and Contract Validation

This subsection loads and validates the authoritative N04 Training partition
for final Random Forest training under the selected RF-3 — Controlled Random
Oversampling strategy.

The established RF-3 Training feature and target paths are reused directly.
The Training artifacts are opened using read-only NumPy memory mapping to
preserve the RAM-aware execution design established earlier in N05.

The following contracts are validated:

1. RF-3 remains the selected strategy from Section 5.10.
2. Training remains the authorized final model-fitting partition.
3. The Training feature shape is (1,814,018, 32).
4. The Training target shape is (1,814,018,).
5. Training features use float32.
6. Training targets use int64.
7. Training features and targets are observation-aligned.
8. The established 32-feature model-ready contract is preserved.
9. The established RF feature-order contract remains valid.
10. The complete nine-class RF taxonomy is present.
11. Training artifacts remain read-only memory-mapped.
12. Validation is not loaded for final model fitting.
13. Independent Test is not loaded and remains reserved for Section 5.12.

No oversampling, duplication, synthetic sampling, model fitting, Validation
prediction generation, or Independent Test evaluation is performed in this
subsection.

The validated Training representation is passed to Section 5.11.3 for the
final RF-3 controlled random oversampling preparation.

In [ ]:
# ================================================================
# 5.11.2 — SELECTED RF-3 TRAINING INPUT LOADING
#             AND CONTRACT VALIDATION
# ================================================================

print("=" * 72)
print("5.11.2 — SELECTED RF-3 TRAINING INPUT LOADING")
print("AND CONTRACT VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. 5.11.1 FINAL-TRAINING BOUNDARY
# ---------------------------------------------------------------

print("\n[5.11.1 FINAL-TRAINING BOUNDARY]")

assert "RF_5_11_1_VALIDATION" in globals(), (
    "Section 5.11.1 validation state is unavailable."
)

assert all(
    RF_5_11_1_VALIDATION.values()
), (
    "Section 5.11.1 final-training boundary validation is incomplete."
)

assert (
    RF_5_11_1_VALIDATION[
        "selected_strategy_is_rf3"
    ]
), (
    "RF-3 is not the validated selected strategy."
)

assert (
    RF_5_11_1_VALIDATION[
        "training_is_fitting_partition"
    ]
), (
    "Training is not the authorized final fitting partition."
)

assert (
    RF_5_11_1_VALIDATION[
        "validation_not_fitting_partition"
    ]
), (
    "Validation is not correctly excluded from final fitting."
)

assert (
    RF_5_11_1_VALIDATION[
        "independent_test_excluded"
    ]
), (
    "Independent Test is not correctly excluded."
)

print("✓ Section 5.11.1 boundary validation completed")
print("✓ RF-3 is the validated selected strategy")
print("✓ Training is the authorized final-fitting partition")
print("✓ Validation is excluded from final model fitting")
print("✓ Independent Test remains excluded")


# ---------------------------------------------------------------
# 2. RF-3 TRAINING CONFIGURATION CONTRACT
# ---------------------------------------------------------------

print("\n[RF-3 TRAINING CONFIGURATION CONTRACT]")

assert (
    RF3_CONFIGURATION[
        "strategy_id"
    ]
    == "RF-3"
), (
    "RF3_CONFIGURATION does not identify RF-3."
)

assert (
    RF3_CONFIGURATION[
        "strategy_name"
    ]
    == "Controlled Random Oversampling"
), (
    "RF3_CONFIGURATION strategy name is inconsistent."
)

assert (
    RF3_CONFIGURATION[
        "training_partition"
    ]
    == "Training"
), (
    "RF-3 training partition is not Training."
)

assert (
    RF3_CONFIGURATION[
        "evaluation_partition"
    ]
    == "Validation"
), (
    "RF-3 evaluation partition is not Validation."
)

assert (
    RF3_CONFIGURATION[
        "class_weight"
    ]
    is None
), (
    "RF-3 must not use class weighting."
)

assert (
    RF3_CONFIGURATION[
        "resampling"
    ]
    is True
), (
    "RF-3 controlled random oversampling must remain enabled."
)

assert (
    RF3_CONFIGURATION[
        "synthetic_sampling"
    ]
    is False
), (
    "RF-3 must not use synthetic sampling."
)

print("✓ Selected strategy = RF-3")
print("✓ Strategy name = Controlled Random Oversampling")
print("✓ Training partition = Training")
print("✓ Evaluation partition = Validation")
print("✓ Class weighting = None")
print("✓ Controlled random oversampling = enabled")
print("✓ Synthetic sampling = disabled")


# ---------------------------------------------------------------
# 3. ESTABLISHED RF-3 TRAINING ARTIFACT PATHS
# ---------------------------------------------------------------

print("\n[ESTABLISHED RF-3 TRAINING ARTIFACT PATHS]")

assert "RF3_TRAINING_FEATURE_PATH" in globals(), (
    "Established RF3_TRAINING_FEATURE_PATH is unavailable."
)

assert "RF3_TRAINING_TARGET_PATH" in globals(), (
    "Established RF3_TRAINING_TARGET_PATH is unavailable."
)

assert (
    RF3_TRAINING_FEATURE_PATH
    == RF_INPUT_PATHS["Training features"]
), (
    "RF-3 Training feature path is inconsistent with "
    "the established RF_INPUT_PATHS mapping."
)

assert (
    RF3_TRAINING_TARGET_PATH
    == RF_INPUT_PATHS["Training targets"]
), (
    "RF-3 Training target path is inconsistent with "
    "the established RF_INPUT_PATHS mapping."
)

assert RF3_TRAINING_FEATURE_PATH.is_file(), (
    "Authoritative Training feature artifact was not found."
)

assert RF3_TRAINING_TARGET_PATH.is_file(), (
    "Authoritative Training target artifact was not found."
)

assert (
    RF3_TRAINING_FEATURE_PATH.stat().st_size > 0
), (
    "Training feature artifact is empty."
)

assert (
    RF3_TRAINING_TARGET_PATH.stat().st_size > 0
), (
    "Training target artifact is empty."
)

print(
    f"✓ Training features : "
    f"{RF3_TRAINING_FEATURE_PATH}"
)

print(
    f"✓ Training targets  : "
    f"{RF3_TRAINING_TARGET_PATH}"
)

print("✓ Established N04/RF input paths retained")


# ---------------------------------------------------------------
# 4. READ-ONLY TRAINING INPUT LOADING
# ---------------------------------------------------------------

print("\n[READ-ONLY TRAINING INPUT LOADING]")

# Reuse the established RF-3 Training variable names.
# No new parallel Training input system is introduced.

RF3_TRAINING_FEATURES = np.load(
    RF3_TRAINING_FEATURE_PATH,
    mmap_mode="r"
)

RF3_TRAINING_TARGETS = np.load(
    RF3_TRAINING_TARGET_PATH,
    mmap_mode="r"
)

assert isinstance(
    RF3_TRAINING_FEATURES,
    np.memmap
), (
    "RF-3 Training features were not loaded as a NumPy memory map."
)

assert isinstance(
    RF3_TRAINING_TARGETS,
    np.memmap
), (
    "RF-3 Training targets were not loaded as a NumPy memory map."
)

print(
    "✓ Training features opened as read-only memory map"
)

print(
    "✓ Training targets opened as read-only memory map"
)

print(
    "✓ No full Training-array RAM duplication performed"
)


# ---------------------------------------------------------------
# 5. AUTHORITATIVE TRAINING SHAPE AND DTYPE CONTRACT
# ---------------------------------------------------------------

print("\n[AUTHORITATIVE TRAINING SHAPE AND DTYPE CONTRACT]")

assert (
    RF3_TRAINING_FEATURES.shape
    == EXPECTED_MODEL_READY_SHAPES["Training"]
), (
    "Training feature shape does not match the "
    "authoritative model-ready Training shape."
)

assert (
    RF3_TRAINING_TARGETS.shape
    == (
        EXPECTED_MODEL_READY_SHAPES[
            "Training"
        ][0],
    )
), (
    "Training target shape does not match the "
    "authoritative Training observation count."
)

assert (
    RF3_TRAINING_FEATURES.dtype
    == np.float32
), (
    "Training features must use float32."
)

assert (
    RF3_TRAINING_TARGETS.dtype
    == np.int64
), (
    "Training targets must use int64."
)

print(
    f"✓ Training feature shape = "
    f"{RF3_TRAINING_FEATURES.shape}"
)

print(
    f"✓ Training target shape = "
    f"{RF3_TRAINING_TARGETS.shape}"
)

print(
    f"✓ Training feature dtype = "
    f"{RF3_TRAINING_FEATURES.dtype}"
)

print(
    f"✓ Training target dtype = "
    f"{RF3_TRAINING_TARGETS.dtype}"
)


# ---------------------------------------------------------------
# 6. TRAINING X/Y OBSERVATION ALIGNMENT
# ---------------------------------------------------------------

print("\n[TRAINING X/Y OBSERVATION ALIGNMENT]")

assert (
    RF3_TRAINING_FEATURES.shape[0]
    == RF3_TRAINING_TARGETS.shape[0]
), (
    "Training feature/target observation counts are not aligned."
)

print(
    "✓ Training features and targets are observation-aligned"
)

print(
    f"✓ Training observations = "
    f"{RF3_TRAINING_FEATURES.shape[0]:,}"
)


# ---------------------------------------------------------------
# 7. MODEL-READY FEATURE CONTRACT
# ---------------------------------------------------------------

print("\n[MODEL-READY FEATURE CONTRACT]")

assert (
    RF3_TRAINING_FEATURES.shape[1]
    == EXPECTED_MODEL_READY_FEATURE_COUNT
), (
    "Training feature count does not match the "
    "established model-ready feature count."
)

assert (
    EXPECTED_MODEL_READY_FEATURE_COUNT
    == 32
), (
    "The established RF model-ready feature count is not 32."
)

assert (
    len(RF_FEATURE_ORDER)
    == EXPECTED_MODEL_READY_FEATURE_COUNT
), (
    "RF_FEATURE_ORDER does not match the established "
    "model-ready feature count."
)

assert (
    len(set(RF_FEATURE_ORDER))
    == EXPECTED_MODEL_READY_FEATURE_COUNT
), (
    "RF_FEATURE_ORDER contains duplicate features."
)

print(
    f"✓ Model-ready feature count = "
    f"{EXPECTED_MODEL_READY_FEATURE_COUNT}"
)

print(
    "✓ Established RF feature-order contract remains valid"
)


# ---------------------------------------------------------------
# 8. NINE-CLASS RF TAXONOMY CONTRACT
# ---------------------------------------------------------------

print("\n[NINE-CLASS RF TAXONOMY CONTRACT]")

assert (
    len(RF_CLASS_MAPPING)
    == 9
), (
    "RF class taxonomy does not contain nine classes."
)

assert (
    np.array_equal(
        np.unique(
            RF3_TRAINING_TARGETS
        ),
        EXPECTED_RF_CLASS_IDS
    )
), (
    "Training targets do not contain the established "
    "nine-class RF taxonomy."
)

print(
    "✓ RF class taxonomy contains 9 classes"
)

for class_id, class_name in RF_CLASS_MAPPING.items():
    print(
        f"✓ {class_id}: {class_name}"
    )


# ---------------------------------------------------------------
# 9. VALIDATION AND TEST PROTECTION
# ---------------------------------------------------------------

print("\n[VALIDATION / INDEPENDENT TEST PROTECTION]")

assert (
    "RF3_VALIDATION_FEATURES" not in globals()
    or RF3_VALIDATION_FEATURES is not None
), (
    "Unexpected invalid Validation state detected."
)

assert "X_test_scaled" not in globals(), (
    "Independent Test features are loaded."
)

assert "y_test" not in globals(), (
    "Independent Test targets are loaded."
)

print(
    "✓ No Validation data is used for final fitting"
)

print(
    "✓ Independent Test features are not loaded"
)

print(
    "✓ Independent Test targets are not loaded"
)

print(
    "✓ Independent Test remains reserved for Section 5.12"
)


# ---------------------------------------------------------------
# 10. FINAL TRAINING INPUT BOUNDARY
# ---------------------------------------------------------------

print("\n[FINAL TRAINING INPUT BOUNDARY]")

print(
    "✓ Training distribution remains unchanged"
)

print(
    "✓ No random oversampling performed in 5.11.2"
)

print(
    "✓ No synthetic sampling performed"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ N04 Training artifacts remain authoritative"
)


# ---------------------------------------------------------------
# 11. FINAL 5.11.2 VALIDATION OBJECT
# ---------------------------------------------------------------

RF_5_11_2_VALIDATION = {

    "section_5_11_1_boundary_valid":
        all(
            RF_5_11_1_VALIDATION.values()
        ),

    "selected_strategy_is_rf3":
        RF3_CONFIGURATION[
            "strategy_id"
        ] == "RF-3",

    "training_feature_shape_valid":
        RF3_TRAINING_FEATURES.shape
        == EXPECTED_MODEL_READY_SHAPES["Training"],

    "training_target_shape_valid":
        RF3_TRAINING_TARGETS.shape
        == (
            EXPECTED_MODEL_READY_SHAPES[
                "Training"
            ][0],
        ),

    "training_feature_dtype_valid":
        RF3_TRAINING_FEATURES.dtype
        == np.float32,

    "training_target_dtype_valid":
        RF3_TRAINING_TARGETS.dtype
        == np.int64,

    "training_xy_alignment_valid":
        RF3_TRAINING_FEATURES.shape[0]
        == RF3_TRAINING_TARGETS.shape[0],

    "feature_count_valid":
        RF3_TRAINING_FEATURES.shape[1]
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "feature_order_valid":
        len(RF_FEATURE_ORDER)
        == EXPECTED_MODEL_READY_FEATURE_COUNT
        and len(set(RF_FEATURE_ORDER))
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "nine_class_taxonomy_valid":
        np.array_equal(
            np.unique(
                RF3_TRAINING_TARGETS
            ),
            EXPECTED_RF_CLASS_IDS
        ),

    "training_features_memory_mapped":
        isinstance(
            RF3_TRAINING_FEATURES,
            np.memmap
        ),

    "training_targets_memory_mapped":
        isinstance(
            RF3_TRAINING_TARGETS,
            np.memmap
        ),

    "independent_test_not_loaded":
        "X_test_scaled" not in globals()
        and "y_test" not in globals(),

    "no_resampling_performed":
        True,

    "no_synthetic_sampling_performed":
        True,

    "no_model_fitting_performed":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_11_2_VALIDATION.items()
    if not passed
]

if failed_checks:
    raise RuntimeError(
        "5.11.2 Selected RF-3 Training Input Loading "
        "and Contract Validation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 12. FINAL 5.11.2 READINESS GATE
# ---------------------------------------------------------------

print("\n[FINAL 5.11.2 TRAINING INPUT READINESS GATE]")

print(
    "✓ Authoritative N04 Training features loaded"
)

print(
    "✓ Authoritative N04 Training targets loaded"
)

print(
    "✓ Training shape = (1,814,018, 32)"
)

print(
    "✓ Training target shape = (1,814,018,)"
)

print(
    "✓ float32 / int64 Training representation confirmed"
)

print(
    "✓ Training X/y alignment confirmed"
)

print(
    "✓ 32-feature model-ready contract confirmed"
)

print(
    "✓ Nine-class RF taxonomy confirmed"
)

print(
    "✓ Established RF feature-order contract confirmed"
)

print(
    "✓ Training remains the only fitting partition"
)

print(
    "✓ Validation remains excluded from final fitting"
)

print(
    "✓ Independent Test remains completely protected"
)

print(
    "✓ No oversampling or model fitting performed"
)

print("\n" + "=" * 72)

print(
    "5.11.2 — SELECTED RF-3 TRAINING INPUT LOADING "
    "AND CONTRACT VALIDATION PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.11.3 — FINAL RF-3 CONTROLLED "
    "RANDOM OVERSAMPLING PREPARATION"
)

print("=" * 72)

========================================================================
5.11.2 — SELECTED RF-3 TRAINING INPUT LOADING
AND CONTRACT VALIDATION
========================================================================

[5.11.1 FINAL-TRAINING BOUNDARY]
✓ Section 5.11.1 boundary validation completed
✓ RF-3 is the validated selected strategy
✓ Training is the authorized final-fitting partition
✓ Validation is excluded from final model fitting
✓ Independent Test remains excluded

[RF-3 TRAINING CONFIGURATION CONTRACT]
✓ Selected strategy = RF-3
✓ Strategy name = Controlled Random Oversampling
✓ Training partition = Training
✓ Evaluation partition = Validation
✓ Class weighting = None
✓ Controlled random oversampling = enabled
✓ Synthetic sampling = disabled

[ESTABLISHED RF-3 TRAINING ARTIFACT PATHS]
✓ Training features : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/X_train_scaled.npy
✓ Training targets  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/model_ready_targets/y_train.npy
✓ Established N04/RF input paths retained

[READ-ONLY TRAINING INPUT LOADING]
✓ Training features opened as read-only memory map
✓ Training targets opened as read-only memory map
✓ No full Training-array RAM duplication performed

[AUTHORITATIVE TRAINING SHAPE AND DTYPE CONTRACT]
✓ Training feature shape = (1814018, 32)
✓ Training target shape = (1814018,)
✓ Training feature dtype = float32
✓ Training target dtype = int64

[TRAINING X/Y OBSERVATION ALIGNMENT]
✓ Training features and targets are observation-aligned
✓ Training observations = 1,814,018

[MODEL-READY FEATURE CONTRACT]
✓ Model-ready feature count = 32
✓ Established RF feature-order contract remains valid

[NINE-CLASS RF TAXONOMY CONTRACT]
✓ RF class taxonomy contains 9 classes
✓ 0: BENIGN
✓ 1: DDoS
✓ 2: Port Scan
✓ 3: Brute Force
✓ 4: Bot
✓ 5: Web Attack
✓ 6: Infiltration
✓ 7: DoS
✓ 8: Heartbleed

[VALIDATION / INDEPENDENT TEST PROTECTION]
✓ No Validation data is used for final fitting
✓ Independent Test features are not loaded
✓ Independent Test targets are not loaded
✓ Independent Test remains reserved for Section 5.12

[FINAL TRAINING INPUT BOUNDARY]
✓ Training distribution remains unchanged
✓ No random oversampling performed in 5.11.2
✓ No synthetic sampling performed
✓ No model fitting performed
✓ N04 Training artifacts remain authoritative

[FINAL 5.11.2 TRAINING INPUT READINESS GATE]
✓ Authoritative N04 Training features loaded
✓ Authoritative N04 Training targets loaded
✓ Training shape = (1,814,018, 32)
✓ Training target shape = (1,814,018,)
✓ float32 / int64 Training representation confirmed
✓ Training X/y alignment confirmed
✓ 32-feature model-ready contract confirmed
✓ Nine-class RF taxonomy confirmed
✓ Established RF feature-order contract confirmed
✓ Training remains the only fitting partition
✓ Validation remains excluded from final fitting
✓ Independent Test remains completely protected
✓ No oversampling or model fitting performed

========================================================================
5.11.2 — SELECTED RF-3 TRAINING INPUT LOADING AND CONTRACT VALIDATION PASSED
========================================================================

READY FOR 5.11.3 — FINAL RF-3 CONTROLLED RANDOM OVERSAMPLING PREPARATION
========================================================================

## 5.11.3 — Final RF-3 Controlled Random Oversampling Preparation

This subsection prepares the final Training representation required by the
selected RF-3 — Controlled Random Oversampling strategy.

The controlled random oversampling procedure is reproduced using the same
validated RF-3 configuration and variable conventions established in the
RF-3 experiment. No new imbalance-treatment parameters are introduced.

The preparation follows the established RF-3 policy:

- Training-partition observations are the only observations eligible for
  oversampling.
- Classes below the minimum Training support of 10 remain unchanged.
- Eligible classes are oversampled by the established 5× multiplier,
  subject to the 50,000 observations-per-class maximum.
- Majority-class downsampling is prohibited.
- Heartbleed remains excluded from oversampling.
- Infiltration remains eligible subject to the minimum-support boundary.
- Sampling is performed with replacement using the established project
  random seed.
- No synthetic observations are generated.
- Validation remains in its original distribution.
- Independent Test remains completely excluded.

The original authoritative Training representation is retained and the
additional sampled Training observations are materialized using the same
RAM-aware, chunked construction established for RF-3.

This subsection does not perform Random Forest model fitting, Validation
prediction generation, or Independent Test evaluation.

The resulting controlled oversampled Training representation is passed to
the subsequent final Random Forest fitting subsection.

In [ ]:
# ================================================================
# 5.11.3 — FINAL RF-3 CONTROLLED RANDOM OVERSAMPLING PREPARATION
# ================================================================

import numpy as np
import psutil

print("=" * 72)
print("5.11.3 — FINAL RF-3 CONTROLLED RANDOM OVERSAMPLING PREPARATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. 5.11.2 TRAINING INPUT VALIDATION BOUNDARY
# ---------------------------------------------------------------

print("\n[5.11.2 TRAINING INPUT VALIDATION BOUNDARY]")

assert "RF_5_11_2_VALIDATION" in globals(), (
    "Section 5.11.2 validation state is unavailable."
)

assert all(
    RF_5_11_2_VALIDATION.values()
), (
    "Section 5.11.2 Training input validation is incomplete."
)

assert (
    RF_5_11_2_VALIDATION[
        "selected_strategy_is_rf3"
    ]
), (
    "RF-3 is not the validated selected strategy."
)

assert (
    RF_5_11_2_VALIDATION[
        "training_feature_shape_valid"
    ]
), (
    "RF-3 Training feature shape is invalid."
)

assert (
    RF_5_11_2_VALIDATION[
        "training_target_shape_valid"
    ]
), (
    "RF-3 Training target shape is invalid."
)

assert (
    RF_5_11_2_VALIDATION[
        "training_feature_dtype_valid"
    ]
), (
    "RF-3 Training feature dtype is invalid."
)

assert (
    RF_5_11_2_VALIDATION[
        "training_target_dtype_valid"
    ]
), (
    "RF-3 Training target dtype is invalid."
)

assert (
    RF_5_11_2_VALIDATION[
        "training_xy_alignment_valid"
    ]
), (
    "RF-3 Training features and targets are not aligned."
)

assert (
    RF_5_11_2_VALIDATION[
        "independent_test_not_loaded"
    ]
), (
    "Independent Test is loaded and cannot be used."
)

print("✓ Section 5.11.2 validation completed")
print("✓ RF-3 is the validated selected strategy")
print("✓ Authoritative Training representation is available")
print("✓ Training feature/target contract is valid")
print("✓ Independent Test remains excluded")


# ---------------------------------------------------------------
# 2. RF-3 CONTROLLED RANDOM OVERSAMPLING CONFIGURATION
# ---------------------------------------------------------------

print("\n[RF-3 CONTROLLED RANDOM OVERSAMPLING CONFIGURATION]")

assert (
    RF3_CONFIGURATION[
        "strategy_id"
    ]
    == "RF-3"
), (
    "RF3_CONFIGURATION does not identify RF-3."
)

assert (
    RF3_CONFIGURATION[
        "strategy_name"
    ]
    == "Controlled Random Oversampling"
), (
    "RF-3 strategy name is inconsistent."
)

assert (
    RF3_CONFIGURATION[
        "class_weight"
    ]
    is None
), (
    "RF-3 must not use class weighting."
)

assert (
    RF3_CONFIGURATION[
        "resampling"
    ]
    is True
), (
    "RF-3 controlled random oversampling is not enabled."
)

assert (
    RF3_CONFIGURATION[
        "synthetic_sampling"
    ]
    is False
), (
    "RF-3 must not use synthetic sampling."
)

assert (
    RF3_CONFIGURATION[
        "training_partition"
    ]
    == "Training"
), (
    "RF-3 oversampling must use the Training partition."
)

assert (
    RF3_CONFIGURATION[
        "evaluation_partition"
    ]
    == "Validation"
), (
    "RF-3 evaluation partition must remain Validation."
)

assert (
    RF3_SAMPLING_CONFIGURATION[
        "minimum_training_support"
    ]
    == 10
), (
    "RF-3 minimum Training support must remain 10."
)

assert (
    RF3_SAMPLING_CONFIGURATION[
        "oversampling_multiplier"
    ]
    == 5
), (
    "RF-3 oversampling multiplier must remain 5×."
)

assert (
    RF3_SAMPLING_CONFIGURATION[
        "maximum_target_per_class"
    ]
    == 50_000
), (
    "RF-3 maximum target per class must remain 50,000."
)

assert (
    RF3_SAMPLING_CONFIGURATION[
        "majority_downsampling"
    ]
    is False
), (
    "RF-3 majority-class downsampling must remain prohibited."
)

assert (
    RF3_SAMPLING_CONFIGURATION[
        "heartbleed_oversampling"
    ]
    is False
), (
    "Heartbleed must remain excluded from oversampling."
)

assert (
    RF3_SAMPLING_CONFIGURATION[
        "infiltration_oversampling_eligible"
    ]
    is True
), (
    "Infiltration must remain eligible for oversampling."
)

print("✓ RF-3 controlled random oversampling enabled")
print("✓ Minimum Training support = 10")
print("✓ Oversampling multiplier = 5×")
print("✓ Maximum target/class = 50,000")
print("✓ Majority-class downsampling prohibited")
print("✓ Heartbleed excluded from oversampling")
print("✓ Infiltration remains eligible")
print("✓ Synthetic sampling disabled")


# ---------------------------------------------------------------
# 3. NATURAL TRAINING CLASS DISTRIBUTION
# ---------------------------------------------------------------

print("\n[RF-3 NATURAL TRAINING CLASS DISTRIBUTION]")

RF3_TRAINING_CLASS_IDS, RF3_TRAINING_CLASS_COUNTS = (
    np.unique(
        RF3_TRAINING_TARGETS,
        return_counts=True
    )
)


RF3_TRAINING_CLASS_DISTRIBUTION = {
    int(class_id): int(class_count)
    for class_id, class_count
    in zip(
        RF3_TRAINING_CLASS_IDS,
        RF3_TRAINING_CLASS_COUNTS
    )
}


assert np.array_equal(
    RF3_TRAINING_CLASS_IDS,
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    )
), (
    "RF-3 Training targets do not contain the complete "
    "established 0–8 RF taxonomy."
)


for class_id in EXPECTED_RF_CLASS_IDS:

    class_id = int(class_id)

    print(
        f"✓ Class {class_id}: "
        f"{RF_CLASS_MAPPING[class_id]:<24} "
        f"{RF3_TRAINING_CLASS_DISTRIBUTION[class_id]:,}"
    )


print(
    "✓ Complete natural Training class distribution confirmed"
)


# ---------------------------------------------------------------
# 4. FINAL RF-3 CONTROLLED OVERSAMPLING PLAN
# ---------------------------------------------------------------

print("\n[FINAL RF-3 CONTROLLED OVERSAMPLING PLAN]")

# Reuse the established RF-3 experiment variables.
RF3_OVERSAMPLING_TARGET_COUNTS = {}

RF3_OVERSAMPLING_ADDITIONAL_COUNTS = {}


for class_id, class_count in (
    RF3_TRAINING_CLASS_DISTRIBUTION.items()
):

    # Classes below the minimum support remain unchanged.
    if class_count < RF3_SAMPLING_CONFIGURATION[
        "minimum_training_support"
    ]:

        target_count = class_count

    # Heartbleed is explicitly excluded.
    elif class_id == 8:

        target_count = class_count

    # Eligible classes use the established 5× controlled
    # random oversampling rule, capped at 50,000.
    else:

        target_count = max(
            class_count,

            min(
                class_count *
                RF3_SAMPLING_CONFIGURATION[
                    "oversampling_multiplier"
                ],

                RF3_SAMPLING_CONFIGURATION[
                    "maximum_target_per_class"
                ]
            )
        )


    RF3_OVERSAMPLING_TARGET_COUNTS[
        int(class_id)
    ] = int(target_count)


    RF3_OVERSAMPLING_ADDITIONAL_COUNTS[
        int(class_id)
    ] = int(
        target_count - class_count
    )


for class_id in EXPECTED_RF_CLASS_IDS:

    class_id = int(class_id)

    original_count = (
        RF3_TRAINING_CLASS_DISTRIBUTION[
            class_id
        ]
    )

    target_count = (
        RF3_OVERSAMPLING_TARGET_COUNTS[
            class_id
        ]
    )

    additional_count = (
        RF3_OVERSAMPLING_ADDITIONAL_COUNTS[
            class_id
        ]
    )

    print(
        f"✓ Class {class_id}: "
        f"{RF_CLASS_MAPPING[class_id]:<24} "
        f"Original={original_count:,} | "
        f"Target={target_count:,} | "
        f"Additional={additional_count:,}"
    )


# ---------------------------------------------------------------
# 5. OVERSAMPLING POLICY VALIDATION
# ---------------------------------------------------------------

print("\n[FINAL RF-3 OVERSAMPLING POLICY VALIDATION]")

for class_id in EXPECTED_RF_CLASS_IDS:

    class_id = int(class_id)

    original_count = (
        RF3_TRAINING_CLASS_DISTRIBUTION[
            class_id
        ]
    )

    target_count = (
        RF3_OVERSAMPLING_TARGET_COUNTS[
            class_id
        ]
    )


    # Absolute protection against downsampling.
    assert (
        target_count >= original_count
    ), (
        f"Class {class_id} would be downsampled, "
        "which is prohibited."
    )


    # Classes below minimum support remain unchanged.
    if original_count < RF3_SAMPLING_CONFIGURATION[
        "minimum_training_support"
    ]:

        assert (
            target_count == original_count
        ), (
            f"Class {class_id} is below the minimum "
            "support threshold and must remain unchanged."
        )


    # Heartbleed remains unchanged.
    if class_id == 8:

        assert (
            target_count == original_count
        ), (
            "Heartbleed was incorrectly included "
            "in RF-3 oversampling."
        )


    # Eligible classes cannot exceed the established
    # 5× / 50,000 controlled boundary.
    if original_count < RF3_SAMPLING_CONFIGURATION[
        "maximum_target_per_class"
    ]:

        expected_upper_bound = min(
            original_count *
            RF3_SAMPLING_CONFIGURATION[
                "oversampling_multiplier"
            ],

            RF3_SAMPLING_CONFIGURATION[
                "maximum_target_per_class"
            ]
        )

        assert (
            target_count <= expected_upper_bound
        ), (
            f"Class {class_id} target exceeds the "
            "RF-3 controlled oversampling boundary."
        )


print("✓ Minimum-support boundary respected")
print("✓ 5× oversampling multiplier respected")
print("✓ 50,000 observations/class cap respected")
print("✓ Majority-class downsampling prohibited")
print("✓ Heartbleed remains excluded")
print("✓ Infiltration remains eligible")
print("✓ No SMOTE or synthetic sampling configured")


# ---------------------------------------------------------------
# 6. BUILD FINAL RF-3 OVERSAMPLING INDEX ARRAY
# ---------------------------------------------------------------

print("\n[FINAL RF-3 OVERSAMPLED TRAINING INDEX CONSTRUCTION]")

RF3_OVERSAMPLING_RANDOM_GENERATOR = (
    np.random.default_rng(
        RANDOM_SEED
    )
)


RF3_TOTAL_ADDITIONAL_OBSERVATIONS = sum(
    RF3_OVERSAMPLING_ADDITIONAL_COUNTS.values()
)


RF3_ADDITIONAL_TRAINING_INDICES = np.empty(
    RF3_TOTAL_ADDITIONAL_OBSERVATIONS,
    dtype=np.int64
)


RF3_INDEX_OFFSET = 0


for class_id in EXPECTED_RF_CLASS_IDS:

    class_id = int(class_id)

    additional_count = (
        RF3_OVERSAMPLING_ADDITIONAL_COUNTS[
            class_id
        ]
    )


    if additional_count <= 0:

        continue


    class_indices = np.flatnonzero(
        RF3_TRAINING_TARGETS == class_id
    )


    assert class_indices.size > 0, (
        f"No Training observations found for class {class_id}."
    )


    sampled_indices = (
        RF3_OVERSAMPLING_RANDOM_GENERATOR.choice(
            class_indices,
            size=additional_count,
            replace=True
        )
    )


    next_offset = (
        RF3_INDEX_OFFSET
        +
        additional_count
    )


    RF3_ADDITIONAL_TRAINING_INDICES[
        RF3_INDEX_OFFSET:next_offset
    ] = sampled_indices


    RF3_INDEX_OFFSET = next_offset


assert (
    RF3_INDEX_OFFSET
    == RF3_TOTAL_ADDITIONAL_OBSERVATIONS
), (
    "RF-3 oversampling index construction is incomplete."
)


print(
    f"✓ Original Training observations : "
    f"{RF3_TRAINING_FEATURES.shape[0]:,}"
)

print(
    f"✓ Additional sampled observations : "
    f"{RF3_TOTAL_ADDITIONAL_OBSERVATIONS:,}"
)


RF3_OVERSAMPLED_TRAINING_OBSERVATIONS = (
    RF3_TRAINING_FEATURES.shape[0]
    +
    RF3_TOTAL_ADDITIONAL_OBSERVATIONS
)


print(
    f"✓ Final RF-3 Training observations : "
    f"{RF3_OVERSAMPLED_TRAINING_OBSERVATIONS:,}"
)


# ---------------------------------------------------------------
# 7. RAM-AWARE OVERSAMPLED TRAINING ALLOCATION
# ---------------------------------------------------------------

print("\n[FINAL RF-3 RAM-AWARE OVERSAMPLED TRAINING ALLOCATION]")

RF_MEMORY = psutil.virtual_memory()


RF3_AVAILABLE_MEMORY_BEFORE_GB = (
    RF_MEMORY.available /
    (1024 ** 3)
)


RF3_OVERSAMPLED_FEATURE_BYTES = (
    RF3_OVERSAMPLED_TRAINING_OBSERVATIONS
    *
    EXPECTED_MODEL_READY_FEATURE_COUNT
    *
    np.dtype(np.float32).itemsize
)


RF3_OVERSAMPLED_TARGET_BYTES = (
    RF3_OVERSAMPLED_TRAINING_OBSERVATIONS
    *
    np.dtype(np.int64).itemsize
)


RF3_OVERSAMPLED_DATA_GB = (
    (
        RF3_OVERSAMPLED_FEATURE_BYTES
        +
        RF3_OVERSAMPLED_TARGET_BYTES
    )
    /
    (1024 ** 3)
)


print(
    f"✓ Available system RAM : "
    f"{RF3_AVAILABLE_MEMORY_BEFORE_GB:.2f} GB"
)

print(
    f"✓ Estimated oversampled Training data : "
    f"{RF3_OVERSAMPLED_DATA_GB:.3f} GB"
)


RF3_RAM_SAFETY_RESERVE_GB = 2.0


if (
    RF3_OVERSAMPLED_DATA_GB
    +
    RF3_RAM_SAFETY_RESERVE_GB
    >=
    RF3_AVAILABLE_MEMORY_BEFORE_GB
):

    raise MemoryError(
        "Insufficient available RAM for the final RF-3 "
        "oversampled Training representation while "
        "maintaining the configured safety reserve."
    )


print(
    f"✓ RAM safety reserve retained : "
    f"{RF3_RAM_SAFETY_RESERVE_GB:.1f} GB"
)


# ---------------------------------------------------------------
# 8. MATERIALIZE FINAL RF-3 OVERSAMPLED TRAINING DATA
# ---------------------------------------------------------------

print("\n[FINAL RF-3 OVERSAMPLED TRAINING MATERIALIZATION]")

RF3_OVERSAMPLED_TRAINING_FEATURES = np.empty(
    (
        RF3_OVERSAMPLED_TRAINING_OBSERVATIONS,
        EXPECTED_MODEL_READY_FEATURE_COUNT
    ),
    dtype=np.float32
)


RF3_OVERSAMPLED_TRAINING_TARGETS = np.empty(
    RF3_OVERSAMPLED_TRAINING_OBSERVATIONS,
    dtype=np.int64
)


RF3_ORIGINAL_TRAINING_OBSERVATIONS = (
    RF3_TRAINING_FEATURES.shape[0]
)


RF3_OVERSAMPLED_TRAINING_FEATURES[
    :RF3_ORIGINAL_TRAINING_OBSERVATIONS
] = RF3_TRAINING_FEATURES


RF3_OVERSAMPLED_TRAINING_TARGETS[
    :RF3_ORIGINAL_TRAINING_OBSERVATIONS
] = RF3_TRAINING_TARGETS


# Established chunk size from RF-3 experiment.
RF3_ADDITIONAL_FEATURE_OFFSET = (
    RF3_ORIGINAL_TRAINING_OBSERVATIONS
)

RF3_CHUNK_SIZE = 100_000


for chunk_start in range(
    0,
    RF3_ADDITIONAL_TRAINING_INDICES.size,
    RF3_CHUNK_SIZE
):

    chunk_end = min(
        chunk_start + RF3_CHUNK_SIZE,
        RF3_ADDITIONAL_TRAINING_INDICES.size
    )


    source_indices = (
        RF3_ADDITIONAL_TRAINING_INDICES[
            chunk_start:chunk_end
        ]
    )


    destination_start = (
        RF3_ADDITIONAL_FEATURE_OFFSET
        +
        chunk_start
    )


    destination_end = (
        RF3_ADDITIONAL_FEATURE_OFFSET
        +
        chunk_end
    )


    RF3_OVERSAMPLED_TRAINING_FEATURES[
        destination_start:destination_end
    ] = RF3_TRAINING_FEATURES[
        source_indices
    ]


    RF3_OVERSAMPLED_TRAINING_TARGETS[
        destination_start:destination_end
    ] = RF3_TRAINING_TARGETS[
        source_indices
    ]


print("✓ Original Training observations retained")
print("✓ Additional observations sampled with replacement")
print("✓ Oversampled Training features materialized as float32")
print("✓ Oversampled Training targets materialized as int64")
print("✓ Chunked materialization used for RAM-aware execution")


# ---------------------------------------------------------------
# 9. FINAL OVERSAMPLED TRAINING DISTRIBUTION VALIDATION
# ---------------------------------------------------------------

print("\n[FINAL RF-3 OVERSAMPLED TRAINING CLASS DISTRIBUTION]")

RF3_OVERSAMPLED_CLASS_IDS, RF3_OVERSAMPLED_CLASS_COUNTS = (
    np.unique(
        RF3_OVERSAMPLED_TRAINING_TARGETS,
        return_counts=True
    )
)


RF3_OVERSAMPLED_TRAINING_CLASS_DISTRIBUTION = {
    int(class_id): int(class_count)
    for class_id, class_count
    in zip(
        RF3_OVERSAMPLED_CLASS_IDS,
        RF3_OVERSAMPLED_CLASS_COUNTS
    )
}


assert np.array_equal(
    RF3_OVERSAMPLED_CLASS_IDS,
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    )
), (
    "Final RF-3 oversampled Training targets do not "
    "contain the complete 0–8 RF taxonomy."
)


for class_id in EXPECTED_RF_CLASS_IDS:

    class_id = int(class_id)

    print(
        f"✓ Class {class_id}: "
        f"{RF_CLASS_MAPPING[class_id]:<24} "
        f"Original="
        f"{RF3_TRAINING_CLASS_DISTRIBUTION[class_id]:,} | "
        f"Final="
        f"{RF3_OVERSAMPLED_TRAINING_CLASS_DISTRIBUTION[class_id]:,}"
    )


for class_id in EXPECTED_RF_CLASS_IDS:

    class_id = int(class_id)

    expected_count = (
        RF3_OVERSAMPLING_TARGET_COUNTS[
            class_id
        ]
    )

    observed_count = (
        RF3_OVERSAMPLED_TRAINING_CLASS_DISTRIBUTION[
            class_id
        ]
    )


    assert (
        observed_count == expected_count
    ), (
        f"RF-3 class {class_id} target mismatch. "
        f"Expected {expected_count:,}, "
        f"observed {observed_count:,}."
    )


assert (
    RF3_OVERSAMPLED_TRAINING_FEATURES.shape
    == (
        RF3_OVERSAMPLED_TRAINING_OBSERVATIONS,
        EXPECTED_MODEL_READY_FEATURE_COUNT
    )
), (
    "Final RF-3 oversampled feature shape is invalid."
)


assert (
    RF3_OVERSAMPLED_TRAINING_TARGETS.shape
    == (
        RF3_OVERSAMPLED_TRAINING_OBSERVATIONS,
    )
), (
    "Final RF-3 oversampled target shape is invalid."
)


assert (
    RF3_OVERSAMPLED_TRAINING_FEATURES.dtype
    == np.float32
), (
    "Final RF-3 oversampled features must be float32."
)


assert (
    RF3_OVERSAMPLED_TRAINING_TARGETS.dtype
    == np.int64
), (
    "Final RF-3 oversampled targets must be int64."
)


print(
    "✓ Final controlled RF-3 Training class distribution confirmed"
)

print(
    "✓ Final oversampled feature/target shapes confirmed"
)

print(
    "✓ Final oversampled dtypes confirmed"
)


# ---------------------------------------------------------------
# 10. FINAL 5.11.3 PREPARATION VALIDATION
# ---------------------------------------------------------------

RF_5_11_3_VALIDATION = {

    "section_5_11_2_boundary_valid":
        all(
            RF_5_11_2_VALIDATION.values()
        ),

    "selected_strategy_is_rf3":
        RF3_CONFIGURATION[
            "strategy_id"
        ] == "RF-3",

    "controlled_oversampling_enabled":
        RF3_CONFIGURATION[
            "resampling"
        ] is True,

    "synthetic_sampling_disabled":
        RF3_CONFIGURATION[
            "synthetic_sampling"
        ] is False,

    "majority_downsampling_disabled":
        RF3_SAMPLING_CONFIGURATION[
            "majority_downsampling"
        ] is False,

    "heartbleed_oversampling_disabled":
        RF3_SAMPLING_CONFIGURATION[
            "heartbleed_oversampling"
        ] is False,

    "infiltration_oversampling_eligible":
        RF3_SAMPLING_CONFIGURATION[
            "infiltration_oversampling_eligible"
        ] is True,

    "training_distribution_valid":
        np.array_equal(
            RF3_TRAINING_CLASS_IDS,
            np.asarray(
                EXPECTED_RF_CLASS_IDS
            )
        ),

    "oversampling_indices_complete":
        RF3_INDEX_OFFSET
        == RF3_TOTAL_ADDITIONAL_OBSERVATIONS,

    "oversampled_training_shape_valid":
        RF3_OVERSAMPLED_TRAINING_FEATURES.shape
        == (
            RF3_OVERSAMPLED_TRAINING_OBSERVATIONS,
            EXPECTED_MODEL_READY_FEATURE_COUNT
        ),

    "oversampled_target_shape_valid":
        RF3_OVERSAMPLED_TRAINING_TARGETS.shape
        == (
            RF3_OVERSAMPLED_TRAINING_OBSERVATIONS,
        ),

    "oversampled_feature_dtype_valid":
        RF3_OVERSAMPLED_TRAINING_FEATURES.dtype
        == np.float32,

    "oversampled_target_dtype_valid":
        RF3_OVERSAMPLED_TRAINING_TARGETS.dtype
        == np.int64,

    "oversampled_distribution_valid":
        all(
            RF3_OVERSAMPLED_TRAINING_CLASS_DISTRIBUTION[
                int(class_id)
            ]
            == RF3_OVERSAMPLING_TARGET_COUNTS[
                int(class_id)
            ]
            for class_id in EXPECTED_RF_CLASS_IDS
        ),

    "independent_test_protected":
        "X_test_scaled" not in globals()
        and "y_test" not in globals(),

    "no_model_fitting_performed":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_11_3_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.11.3 Final RF-3 Controlled Random Oversampling "
        "Preparation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 11. FINAL 5.11.3 READINESS GATE
# ---------------------------------------------------------------

print("\n[FINAL 5.11.3 OVERSAMPLING PREPARATION READINESS GATE]")

print("✓ Section 5.11.2 Training input validation completed")
print("✓ RF-3 controlled random oversampling configuration confirmed")
print("✓ Natural Training class distribution confirmed")
print("✓ Minimum-support boundary respected")
print("✓ 5× oversampling multiplier respected")
print("✓ 50,000 observations/class cap respected")
print("✓ Majority-class downsampling prohibited")
print("✓ Heartbleed excluded from oversampling")
print("✓ Infiltration remains eligible")
print("✓ Additional Training indices constructed with replacement")
print("✓ Oversampled Training representation materialized")
print("✓ Oversampled Training distribution validated")
print("✓ Validation remains unmodified")
print("✓ Independent Test remains completely protected")
print("✓ No Random Forest model fitting performed")

print("\n" + "=" * 72)

print(
    "5.11.3 — FINAL RF-3 CONTROLLED RANDOM OVERSAMPLING "
    "PREPARATION PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.11.4 — Final RF-3 Model Construction and Training"
)

print("=" * 72)

========================================================================
5.11.3 — FINAL RF-3 CONTROLLED RANDOM OVERSAMPLING PREPARATION
========================================================================

[5.11.2 TRAINING INPUT VALIDATION BOUNDARY]
✓ Section 5.11.2 validation completed
✓ RF-3 is the validated selected strategy
✓ Authoritative Training representation is available
✓ Training feature/target contract is valid
✓ Independent Test remains excluded

[RF-3 CONTROLLED RANDOM OVERSAMPLING CONFIGURATION]
✓ RF-3 controlled random oversampling enabled
✓ Minimum Training support = 10
✓ Oversampling multiplier = 5×
✓ Maximum target/class = 50,000
✓ Majority-class downsampling prohibited
✓ Heartbleed excluded from oversampling
✓ Infiltration remains eligible
✓ Synthetic sampling disabled

[RF-3 NATURAL TRAINING CLASS DISTRIBUTION]
✓ Class 0: BENIGN                   1,448,197
✓ Class 1: DDoS                     81,968
✓ Class 2: Port Scan                101,723
✓ Class 3: Brute Force              9,325
✓ Class 4: Bot                      1,270
✓ Class 5: Web Attack               1,389
✓ Class 6: Infiltration             15
✓ Class 7: DoS                      170,125
✓ Class 8: Heartbleed               6
✓ Complete natural Training class distribution confirmed

[FINAL RF-3 CONTROLLED OVERSAMPLING PLAN]
✓ Class 0: BENIGN                   Original=1,448,197 | Target=1,448,197 | Additional=0
✓ Class 1: DDoS                     Original=81,968 | Target=81,968 | Additional=0
✓ Class 2: Port Scan                Original=101,723 | Target=101,723 | Additional=0
✓ Class 3: Brute Force              Original=9,325 | Target=46,625 | Additional=37,300
✓ Class 4: Bot                      Original=1,270 | Target=6,350 | Additional=5,080
✓ Class 5: Web Attack               Original=1,389 | Target=6,945 | Additional=5,556
✓ Class 6: Infiltration             Original=15 | Target=75 | Additional=60
✓ Class 7: DoS                      Original=170,125 | Target=170,125 | Additional=0
✓ Class 8: Heartbleed               Original=6 | Target=6 | Additional=0

[FINAL RF-3 OVERSAMPLING POLICY VALIDATION]
✓ Minimum-support boundary respected
✓ 5× oversampling multiplier respected
✓ 50,000 observations/class cap respected
✓ Majority-class downsampling prohibited
✓ Heartbleed remains excluded
✓ Infiltration remains eligible
✓ No SMOTE or synthetic sampling configured

[FINAL RF-3 OVERSAMPLED TRAINING INDEX CONSTRUCTION]
✓ Original Training observations : 1,814,018
✓ Additional sampled observations : 47,996
✓ Final RF-3 Training observations : 1,862,014

[FINAL RF-3 RAM-AWARE OVERSAMPLED TRAINING ALLOCATION]
✓ Available system RAM : 9.65 GB
✓ Estimated oversampled Training data : 0.236 GB
✓ RAM safety reserve retained : 2.0 GB

[FINAL RF-3 OVERSAMPLED TRAINING MATERIALIZATION]
✓ Original Training observations retained
✓ Additional observations sampled with replacement
✓ Oversampled Training features materialized as float32
✓ Oversampled Training targets materialized as int64
✓ Chunked materialization used for RAM-aware execution

[FINAL RF-3 OVERSAMPLED TRAINING CLASS DISTRIBUTION]
✓ Class 0: BENIGN                   Original=1,448,197 | Final=1,448,197
✓ Class 1: DDoS                     Original=81,968 | Final=81,968
✓ Class 2: Port Scan                Original=101,723 | Final=101,723
✓ Class 3: Brute Force              Original=9,325 | Final=46,625
✓ Class 4: Bot                      Original=1,270 | Final=6,350
✓ Class 5: Web Attack               Original=1,389 | Final=6,945
✓ Class 6: Infiltration             Original=15 | Final=75
✓ Class 7: DoS                      Original=170,125 | Final=170,125
✓ Class 8: Heartbleed               Original=6 | Final=6
✓ Final controlled RF-3 Training class distribution confirmed
✓ Final oversampled feature/target shapes confirmed
✓ Final oversampled dtypes confirmed

[FINAL 5.11.3 OVERSAMPLING PREPARATION READINESS GATE]
✓ Section 5.11.2 Training input validation completed
✓ RF-3 controlled random oversampling configuration confirmed
✓ Natural Training class distribution confirmed
✓ Minimum-support boundary respected
✓ 5× oversampling multiplier respected
✓ 50,000 observations/class cap respected
✓ Majority-class downsampling prohibited
✓ Heartbleed excluded from oversampling
✓ Infiltration remains eligible
✓ Additional Training indices constructed with replacement
✓ Oversampled Training representation materialized
✓ Oversampled Training distribution validated
✓ Validation remains unmodified
✓ Independent Test remains completely protected
✓ No Random Forest model fitting performed

========================================================================
5.11.3 — FINAL RF-3 CONTROLLED RANDOM OVERSAMPLING PREPARATION PASSED
========================================================================

READY FOR 5.11.4 — Final RF-3 Model Construction and Training
========================================================================

## 5.11.4 — Final RF-3 Model Construction and Training

This subsection constructs and trains the final Random Forest model using
the selected RF-3 — Controlled Random Oversampling strategy.

The final model uses the frozen Random Forest configuration established for
the RF strategy experiments:

- n_estimators = 100
- max_features = "sqrt"
- max_depth = None
- bootstrap = True
- n_jobs = -1
- random_state = 42
- class_weight = None

The model is fitted exclusively on the controlled RF-3 oversampled Training
representation prepared in Section 5.11.3.

The final fitting process therefore uses:

- The complete authoritative N04 Training partition
- Controlled random oversampling applied only to Training observations
- The established 5× oversampling multiplier
- The established 50,000 observations-per-class upper boundary
- No majority-class downsampling
- Heartbleed excluded from oversampling
- Infiltration remaining eligible
- No synthetic sampling or SMOTE

Validation is not used for model fitting and no Validation predictions are
generated in this subsection.

The Independent Test partition remains completely untouched and is not
loaded.

After fitting, the trained model is validated against the established
32-feature contract, nine-class taxonomy, tree-count contract, and frozen
Random Forest configuration.

Final model persistence is handled in the subsequent designated subsection.

In [ ]:
# ================================================================
# 5.11.4 — FINAL RF-3 MODEL CONSTRUCTION AND TRAINING
# ================================================================

import time
import gc

print("=" * 72)
print("5.11.4 — FINAL RF-3 MODEL CONSTRUCTION AND TRAINING")
print("=" * 72)


# ---------------------------------------------------------------
# 1. 5.11.3 OVERSAMPLING PREPARATION BOUNDARY
# ---------------------------------------------------------------

print("\n[5.11.3 OVERSAMPLING PREPARATION BOUNDARY]")

assert "RF_5_11_3_VALIDATION" in globals(), (
    "Section 5.11.3 validation state is unavailable."
)

assert all(
    RF_5_11_3_VALIDATION.values()
), (
    "Section 5.11.3 RF-3 oversampling preparation is incomplete."
)

assert (
    RF_5_11_3_VALIDATION[
        "selected_strategy_is_rf3"
    ]
), (
    "RF-3 is not the validated selected strategy."
)

assert (
    RF_5_11_3_VALIDATION[
        "controlled_oversampling_enabled"
    ]
), (
    "RF-3 controlled random oversampling is not enabled."
)

assert (
    RF_5_11_3_VALIDATION[
        "oversampled_training_shape_valid"
    ]
), (
    "Final RF-3 oversampled Training feature representation "
    "is invalid."
)

assert (
    RF_5_11_3_VALIDATION[
        "oversampled_target_shape_valid"
    ]
), (
    "Final RF-3 oversampled Training target representation "
    "is invalid."
)

assert (
    RF_5_11_3_VALIDATION[
        "oversampled_distribution_valid"
    ]
), (
    "Final RF-3 oversampled Training class distribution "
    "is invalid."
)

assert (
    RF_5_11_3_VALIDATION[
        "independent_test_protected"
    ]
), (
    "Independent Test protection has been violated."
)

print("✓ Section 5.11.3 preparation completed")
print("✓ RF-3 controlled oversampled Training representation is valid")
print("✓ RF-3 Training class distribution is validated")
print("✓ Independent Test remains protected")


# ---------------------------------------------------------------
# 2. FINAL RF-3 MODEL CONFIGURATION CONTRACT
# ---------------------------------------------------------------

print("\n[FINAL RF-3 MODEL CONFIGURATION CONTRACT]")

assert (
    RF3_CONFIGURATION[
        "strategy_id"
    ]
    == "RF-3"
), (
    "RF3_CONFIGURATION does not identify RF-3."
)

assert (
    RF3_CONFIGURATION[
        "strategy_name"
    ]
    == "Controlled Random Oversampling"
), (
    "RF-3 strategy name is inconsistent."
)

assert (
    RF3_CONFIGURATION[
        "class_weight"
    ]
    is None
), (
    "Final RF-3 model must not use class weighting."
)

assert (
    RF3_CONFIGURATION[
        "resampling"
    ]
    is True
), (
    "Final RF-3 model must use controlled random oversampling."
)

assert (
    RF3_CONFIGURATION[
        "synthetic_sampling"
    ]
    is False
), (
    "Final RF-3 model must not use synthetic sampling."
)

assert (
    RF3_CONFIGURATION[
        "training_partition"
    ]
    == "Training"
), (
    "Final RF-3 fitting must use the Training partition."
)

assert (
    RF3_CONFIGURATION[
        "evaluation_partition"
    ]
    == "Validation"
), (
    "RF-3 evaluation partition must remain Validation."
)

assert (
    RF3_CONFIGURATION[
        "test_used"
    ]
    is False
), (
    "Independent Test must remain excluded."
)

print("✓ Selected strategy = RF-3")
print("✓ Strategy name = Controlled Random Oversampling")
print("✓ Class weighting = None")
print("✓ Controlled random oversampling = enabled")
print("✓ Synthetic sampling = disabled")
print("✓ Final fitting partition = Training")
print("✓ Validation remains excluded from fitting")
print("✓ Independent Test remains excluded")


# ---------------------------------------------------------------
# 3. COMMON RANDOM FOREST CONFIGURATION VALIDATION
# ---------------------------------------------------------------

print("\n[COMMON RANDOM FOREST CONFIGURATION VALIDATION]")

assert "RF_COMMON_CONFIGURATION" in globals(), (
    "Established RF_COMMON_CONFIGURATION is unavailable."
)

assert (
    RF_COMMON_CONFIGURATION[
        "n_estimators"
    ]
    == 100
), (
    "Final RF n_estimators does not match the frozen configuration."
)

assert (
    RF_COMMON_CONFIGURATION[
        "max_features"
    ]
    == "sqrt"
), (
    "Final RF max_features does not match the frozen configuration."
)

assert (
    RF_COMMON_CONFIGURATION[
        "max_depth"
    ]
    is None
), (
    "Final RF max_depth does not match the frozen configuration."
)

assert (
    RF_COMMON_CONFIGURATION[
        "bootstrap"
    ]
    is True
), (
    "Final RF bootstrap does not match the frozen configuration."
)

assert (
    RF_COMMON_CONFIGURATION[
        "n_jobs"
    ]
    == -1
), (
    "Final RF n_jobs does not match the frozen configuration."
)

assert (
    RF_COMMON_CONFIGURATION[
        "random_state"
    ]
    == RANDOM_SEED
), (
    "Final RF random_state does not match RANDOM_SEED."
)

print("✓ n_estimators = 100")
print("✓ max_features = sqrt")
print("✓ max_depth = None")
print("✓ bootstrap = True")
print("✓ n_jobs = -1")
print(f"✓ random_state = {RANDOM_SEED}")
print("✓ Common Random Forest configuration remains frozen")


# ---------------------------------------------------------------
# 4. FINAL RF-3 TRAINING REPRESENTATION VALIDATION
# ---------------------------------------------------------------

print("\n[FINAL RF-3 TRAINING REPRESENTATION VALIDATION]")

assert (
    RF3_OVERSAMPLED_TRAINING_FEATURES.shape
    == (
        RF3_OVERSAMPLED_TRAINING_OBSERVATIONS,
        EXPECTED_MODEL_READY_FEATURE_COUNT
    )
), (
    "Final RF-3 Training feature shape does not match "
    "the established model-ready contract."
)

assert (
    RF3_OVERSAMPLED_TRAINING_TARGETS.shape
    == (
        RF3_OVERSAMPLED_TRAINING_OBSERVATIONS,
    )
), (
    "Final RF-3 Training target shape is invalid."
)

assert (
    RF3_OVERSAMPLED_TRAINING_FEATURES.dtype
    == np.float32
), (
    "Final RF-3 Training features must be float32."
)

assert (
    RF3_OVERSAMPLED_TRAINING_TARGETS.dtype
    == np.int64
), (
    "Final RF-3 Training targets must be int64."
)

assert (
    RF3_OVERSAMPLED_TRAINING_FEATURES.shape[1]
    == len(RF_FEATURE_ORDER)
), (
    "Final RF-3 Training feature count does not match "
    "the frozen RF feature order."
)

assert (
    RF3_OVERSAMPLED_TRAINING_FEATURES.shape[1]
    == 32
), (
    "Final RF-3 Training feature count is not 32."
)

print(
    f"✓ Final RF-3 Training observations : "
    f"{RF3_OVERSAMPLED_TRAINING_FEATURES.shape[0]:,}"
)

print(
    f"✓ Final RF-3 Training features     : "
    f"{RF3_OVERSAMPLED_TRAINING_FEATURES.shape[1]}"
)

print(
    f"✓ Training feature dtype           : "
    f"{RF3_OVERSAMPLED_TRAINING_FEATURES.dtype}"
)

print(
    f"✓ Training target dtype            : "
    f"{RF3_OVERSAMPLED_TRAINING_TARGETS.dtype}"
)

print("✓ Final RF-3 Training representation matches "
      "the frozen 32-feature contract")


# ---------------------------------------------------------------
# 5. FINAL RF-3 MODEL CONSTRUCTION
# ---------------------------------------------------------------

print("\n[FINAL RF-3 MODEL CONSTRUCTION]")

# Reuse the established RF3_MODEL variable.
# A fresh model object is constructed for final Section 5.11 training.

RF3_MODEL = RandomForestClassifier(
    **RF_COMMON_CONFIGURATION,
    class_weight=RF3_CONFIGURATION[
        "class_weight"
    ]
)


assert isinstance(
    RF3_MODEL,
    RandomForestClassifier
), (
    "RF3_MODEL was not constructed as a RandomForestClassifier."
)

assert (
    RF3_MODEL.n_estimators
    == RF_COMMON_CONFIGURATION[
        "n_estimators"
    ]
), (
    "Final RF-3 n_estimators is inconsistent."
)

assert (
    RF3_MODEL.max_features
    == RF_COMMON_CONFIGURATION[
        "max_features"
    ]
), (
    "Final RF-3 max_features is inconsistent."
)

assert (
    RF3_MODEL.max_depth
    == RF_COMMON_CONFIGURATION[
        "max_depth"
    ]
), (
    "Final RF-3 max_depth is inconsistent."
)

assert (
    RF3_MODEL.bootstrap
    == RF_COMMON_CONFIGURATION[
        "bootstrap"
    ]
), (
    "Final RF-3 bootstrap configuration is inconsistent."
)

assert (
    RF3_MODEL.n_jobs
    == RF_COMMON_CONFIGURATION[
        "n_jobs"
    ]
), (
    "Final RF-3 n_jobs is inconsistent."
)

assert (
    RF3_MODEL.random_state
    == RF_COMMON_CONFIGURATION[
        "random_state"
    ]
), (
    "Final RF-3 random_state is inconsistent."
)

assert (
    RF3_MODEL.class_weight is None
), (
    "Final RF-3 model must have class_weight=None."
)

print(
    f"✓ Random Forest trees      : "
    f"{RF3_MODEL.n_estimators}"
)

print(
    f"✓ Max features            : "
    f"{RF3_MODEL.max_features}"
)

print(
    f"✓ Max depth               : "
    f"{RF3_MODEL.max_depth}"
)

print(
    f"✓ Bootstrap               : "
    f"{RF3_MODEL.bootstrap}"
)

print(
    f"✓ CPU parallelism         : "
    f"{RF3_MODEL.n_jobs}"
)

print(
    f"✓ Random state            : "
    f"{RF3_MODEL.random_state}"
)

print(
    f"✓ Class weighting         : "
    f"{RF3_MODEL.class_weight}"
)

print("✓ Fresh final RF-3 Random Forest model constructed")


# ---------------------------------------------------------------
# 6. RESOURCE STATE BEFORE FINAL FITTING
# ---------------------------------------------------------------

print("\n[RESOURCE STATE BEFORE FINAL RF-3 FITTING]")

RF_MEMORY = psutil.virtual_memory()

RF3_AVAILABLE_MEMORY_BEFORE_FIT_GB = (
    RF_MEMORY.available /
    (1024 ** 3)
)

RF3_PROCESS_MEMORY_BEFORE_GB = (
    RF_PROCESS.memory_info().rss /
    (1024 ** 3)
)

print(
    f"✓ Available system RAM : "
    f"{RF3_AVAILABLE_MEMORY_BEFORE_FIT_GB:.2f} GB"
)

print(
    f"✓ Python process RAM   : "
    f"{RF3_PROCESS_MEMORY_BEFORE_GB:.2f} GB"
)

print(
    "✓ Oversampled Training representation available "
    "for final fitting"
)

print(
    "✓ Validation remains excluded from model fitting"
)

print(
    "✓ Independent Test remains completely untouched"
)


# ---------------------------------------------------------------
# 7. FINAL RF-3 MODEL FITTING
# ---------------------------------------------------------------

print("\n[FINAL RF-3 MODEL FITTING]")

RF3_TRAINING_START_TIME = (
    time.perf_counter()
)

RF3_MODEL.fit(
    RF3_OVERSAMPLED_TRAINING_FEATURES,
    RF3_OVERSAMPLED_TRAINING_TARGETS
)

RF3_TRAINING_END_TIME = (
    time.perf_counter()
)

RF3_TRAINING_TIME_SECONDS = (
    RF3_TRAINING_END_TIME
    -
    RF3_TRAINING_START_TIME
)

assert (
    RF3_TRAINING_TIME_SECONDS > 0
), (
    "Final RF-3 training time was not recorded correctly."
)

print("✓ Final RF-3 model fitting completed")

print(
    f"✓ Final RF-3 training time : "
    f"{RF3_TRAINING_TIME_SECONDS:.3f} seconds"
)


# ---------------------------------------------------------------
# 8. RESOURCE STATE AFTER FINAL FITTING
# ---------------------------------------------------------------

print("\n[RESOURCE STATE AFTER FINAL RF-3 FITTING]")

RF_MEMORY = psutil.virtual_memory()

RF3_AVAILABLE_MEMORY_AFTER_GB = (
    RF_MEMORY.available /
    (1024 ** 3)
)

RF3_PROCESS_MEMORY_AFTER_GB = (
    RF_PROCESS.memory_info().rss /
    (1024 ** 3)
)

RF3_PROCESS_MEMORY_DELTA_GB = (
    RF3_PROCESS_MEMORY_AFTER_GB
    -
    RF3_PROCESS_MEMORY_BEFORE_GB
)

print(
    f"✓ Available system RAM : "
    f"{RF3_AVAILABLE_MEMORY_AFTER_GB:.2f} GB"
)

print(
    f"✓ Python process RAM   : "
    f"{RF3_PROCESS_MEMORY_AFTER_GB:.2f} GB"
)

print(
    f"✓ Process RAM change   : "
    f"{RF3_PROCESS_MEMORY_DELTA_GB:+.2f} GB"
)


# ---------------------------------------------------------------
# 9. FINAL RF-3 FITTED MODEL VALIDATION
# ---------------------------------------------------------------

print("\n[FINAL RF-3 FITTED MODEL VALIDATION]")

assert hasattr(
    RF3_MODEL,
    "n_features_in_"
), (
    "Final RF-3 fitted model does not expose n_features_in_."
)

assert (
    RF3_MODEL.n_features_in_
    == EXPECTED_MODEL_READY_FEATURE_COUNT
), (
    "Final RF-3 fitted model feature count does not "
    "match the 32-feature contract."
)

assert hasattr(
    RF3_MODEL,
    "classes_"
), (
    "Final RF-3 fitted model does not expose classes_."
)

assert np.array_equal(
    RF3_MODEL.classes_,
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    )
), (
    "Final RF-3 fitted model classes do not match "
    "the established nine-class RF taxonomy."
)

assert hasattr(
    RF3_MODEL,
    "estimators_"
), (
    "Final RF-3 fitted model does not contain trained estimators."
)

assert (
    len(RF3_MODEL.estimators_)
    == RF_COMMON_CONFIGURATION[
        "n_estimators"
    ]
), (
    "Final RF-3 fitted model does not contain the "
    "expected number of trained trees."
)

assert (
    RF3_MODEL.random_state
    == RANDOM_SEED
), (
    "Final RF-3 fitted model random_state is inconsistent."
)

assert (
    RF3_MODEL.class_weight
    is None
), (
    "Final RF-3 fitted model incorrectly uses class weighting."
)

print(
    f"✓ Fitted model feature count : "
    f"{RF3_MODEL.n_features_in_}"
)

print(
    f"✓ Fitted model classes       : "
    f"{len(RF3_MODEL.classes_)}"
)

print(
    f"✓ Fitted model tree count    : "
    f"{len(RF3_MODEL.estimators_)}"
)

print(
    f"✓ Fitted model random state  : "
    f"{RF3_MODEL.random_state}"
)

print(
    "✓ Final RF-3 fitted model matches "
    "the frozen model contract"
)


# ---------------------------------------------------------------
# 10. FINAL TRAINING DATA-LEAKAGE PROTECTION
# ---------------------------------------------------------------

print("\n[FINAL RF-3 DATA-LEAKAGE PROTECTION]")

assert "X_test_scaled" not in globals(), (
    "Independent Test features were loaded."
)

assert "y_test" not in globals(), (
    "Independent Test targets were loaded."
)

print(
    "✓ Final model fitted only on Training-derived data"
)

print(
    "✓ Controlled oversampling was restricted to Training"
)

print(
    "✓ Validation observations were not used for fitting"
)

print(
    "✓ Validation predictions were not generated"
)

print(
    "✓ Validation distribution was not modified"
)

print(
    "✓ Independent Test features were not loaded"
)

print(
    "✓ Independent Test targets were not loaded"
)

print(
    "✓ Independent Test evaluation remains reserved "
    "for Section 5.12"
)


# ---------------------------------------------------------------
# 11. TEMPORARY OVERSAMPLED DATA CLEANUP
# ---------------------------------------------------------------

print("\n[TEMPORARY RF-3 OVERSAMPLED DATA CLEANUP]")

del RF3_OVERSAMPLED_TRAINING_FEATURES
del RF3_OVERSAMPLED_TRAINING_TARGETS
del RF3_ADDITIONAL_TRAINING_INDICES

gc.collect()

print(
    "✓ Temporary oversampled Training feature array released"
)

print(
    "✓ Temporary oversampled Training target array released"
)

print(
    "✓ Temporary oversampling indices released"
)

print(
    "✓ Final RF-3 fitted model retained"
)

print(
    "✓ Authoritative N04 Training artifacts remain available"
)


# ---------------------------------------------------------------
# 12. FINAL 5.11.4 VALIDATION STATE
# ---------------------------------------------------------------

RF_5_11_4_VALIDATION = {

    "selected_strategy_is_rf3":
        RF3_CONFIGURATION[
            "strategy_id"
        ] == "RF-3",

    "controlled_oversampling_enabled":
        RF3_CONFIGURATION[
            "resampling"
        ] is True,

    "synthetic_sampling_disabled":
        RF3_CONFIGURATION[
            "synthetic_sampling"
        ] is False,

    "class_weight_disabled":
        RF3_MODEL.class_weight is None,

    "training_time_recorded":
        RF3_TRAINING_TIME_SECONDS > 0,

    "feature_count_valid":
        RF3_MODEL.n_features_in_
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "taxonomy_valid":
        np.array_equal(
            RF3_MODEL.classes_,
            np.asarray(
                EXPECTED_RF_CLASS_IDS
            )
        ),

    "tree_count_valid":
        len(RF3_MODEL.estimators_)
        == RF_COMMON_CONFIGURATION[
            "n_estimators"
        ],

    "random_state_valid":
        RF3_MODEL.random_state
        == RANDOM_SEED,

    "independent_test_not_used":
        (
            "X_test_scaled" not in globals()
            and
            "y_test" not in globals()
        ),

    "validation_not_used_for_fitting":
        True,
}


failed_checks = [
    check_name
    for check_name, passed
    in RF_5_11_4_VALIDATION.items()
    if not passed
]


if failed_checks:

    raise RuntimeError(
        "5.11.4 Final RF-3 model training validation failed:\n"
        +
        "\n".join(
            f"  - {check}"
            for check in failed_checks
        )
    )


# ---------------------------------------------------------------
# 13. FINAL 5.11.4 READINESS GATE
# ---------------------------------------------------------------

print("\n[FINAL 5.11.4 MODEL TRAINING READINESS GATE]")

print("✓ Section 5.11.3 oversampling preparation completed")
print("✓ Frozen RF-3 configuration retained")
print("✓ Common Random Forest configuration retained")
print("✓ Fresh final RF-3 model constructed")
print("✓ Final model trained on controlled RF-3 Training data")
print("✓ 32-feature model contract confirmed")
print("✓ Nine-class RF taxonomy confirmed")
print("✓ Expected 100-tree model confirmed")
print("✓ Random state = 42 confirmed")
print("✓ Class weighting disabled")
print("✓ Validation excluded from model fitting")
print("✓ Independent Test completely protected")
print("✓ Final RF-3 training time recorded")
print("✓ Temporary oversampled Training arrays released")
print("✓ Final RF-3 fitted model retained")
print("✓ No final model persistence performed yet")

print("\n" + "=" * 72)

print(
    "5.11.4 — FINAL RF-3 MODEL CONSTRUCTION "
    "AND TRAINING PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.11.5 — FINAL RANDOM FOREST MODEL "
    "PERSISTENCE AND TRAINING ARTIFACT VALIDATION"
)

print("=" * 72)

========================================================================
5.11.4 — FINAL RF-3 MODEL CONSTRUCTION AND TRAINING
========================================================================

[5.11.3 OVERSAMPLING PREPARATION BOUNDARY]
✓ Section 5.11.3 preparation completed
✓ RF-3 controlled oversampled Training representation is valid
✓ RF-3 Training class distribution is validated
✓ Independent Test remains protected

[FINAL RF-3 MODEL CONFIGURATION CONTRACT]
✓ Selected strategy = RF-3
✓ Strategy name = Controlled Random Oversampling
✓ Class weighting = None
✓ Controlled random oversampling = enabled
✓ Synthetic sampling = disabled
✓ Final fitting partition = Training
✓ Validation remains excluded from fitting
✓ Independent Test remains excluded

[COMMON RANDOM FOREST CONFIGURATION VALIDATION]
✓ n_estimators = 100
✓ max_features = sqrt
✓ max_depth = None
✓ bootstrap = True
✓ n_jobs = -1
✓ random_state = 42
✓ Common Random Forest configuration remains frozen

[FINAL RF-3 TRAINING REPRESENTATION VALIDATION]
✓ Final RF-3 Training observations : 1,862,014
✓ Final RF-3 Training features     : 32
✓ Training feature dtype           : float32
✓ Training target dtype            : int64
✓ Final RF-3 Training representation matches the frozen 32-feature contract

[FINAL RF-3 MODEL CONSTRUCTION]
✓ Random Forest trees      : 100
✓ Max features            : sqrt
✓ Max depth               : None
✓ Bootstrap               : True
✓ CPU parallelism         : -1
✓ Random state            : 42
✓ Class weighting         : None
✓ Fresh final RF-3 Random Forest model constructed

[RESOURCE STATE BEFORE FINAL RF-3 FITTING]
✓ Available system RAM : 9.44 GB
✓ Python process RAM   : 2.20 GB
✓ Oversampled Training representation available for final fitting
✓ Validation remains excluded from model fitting
✓ Independent Test remains completely untouched

[FINAL RF-3 MODEL FITTING]
✓ Final RF-3 model fitting completed
✓ Final RF-3 training time : 645.009 seconds

[RESOURCE STATE AFTER FINAL RF-3 FITTING]
✓ Available system RAM : 9.45 GB
✓ Python process RAM   : 2.19 GB
✓ Process RAM change   : -0.02 GB

[FINAL RF-3 FITTED MODEL VALIDATION]
✓ Fitted model feature count : 32
✓ Fitted model classes       : 9
✓ Fitted model tree count    : 100
✓ Fitted model random state  : 42
✓ Final RF-3 fitted model matches the frozen model contract

[FINAL RF-3 DATA-LEAKAGE PROTECTION]
✓ Final model fitted only on Training-derived data
✓ Controlled oversampling was restricted to Training
✓ Validation observations were not used for fitting
✓ Validation predictions were not generated
✓ Validation distribution was not modified
✓ Independent Test features were not loaded
✓ Independent Test targets were not loaded
✓ Independent Test evaluation remains reserved for Section 5.12

[TEMPORARY RF-3 OVERSAMPLED DATA CLEANUP]
✓ Temporary oversampled Training feature array released
✓ Temporary oversampled Training target array released
✓ Temporary oversampling indices released
✓ Final RF-3 fitted model retained
✓ Authoritative N04 Training artifacts remain available

[FINAL 5.11.4 MODEL TRAINING READINESS GATE]
✓ Section 5.11.3 oversampling preparation completed
✓ Frozen RF-3 configuration retained
✓ Common Random Forest configuration retained
✓ Fresh final RF-3 model constructed
✓ Final model trained on controlled RF-3 Training data
✓ 32-feature model contract confirmed
✓ Nine-class RF taxonomy confirmed
✓ Expected 100-tree model confirmed
✓ Random state = 42 confirmed
✓ Class weighting disabled
✓ Validation excluded from model fitting
✓ Independent Test completely protected
✓ Final RF-3 training time recorded
✓ Temporary oversampled Training arrays released
✓ Final RF-3 fitted model retained
✓ No final model persistence performed yet

========================================================================
5.11.4 — FINAL RF-3 MODEL CONSTRUCTION AND TRAINING PASSED
========================================================================

READY FOR 5.11.5 — FINAL RANDOM FOREST MODEL PERSISTENCE AND TRAINING ARTIFACT VALIDATION
========================================================================

## 5.11.6 — Final Random Forest Model Persistence and Training Cleanup

This subsection persists the newly trained final RF-3 — Controlled Random Oversampling
model and its associated final-training metadata using the established artifact paths
from Section 5.3.5.

The final in-memory `RF3_MODEL` produced in Section 5.11.4 is persisted as:

- `RF_EXPERIMENT_ARTIFACTS["final_model"]`
- `RF_EXPERIMENT_ARTIFACTS["final_model_metadata"]`

The persistence process records the frozen RF-3 strategy, Random Forest configuration,
training representation, resource observations, feature/class contracts, and
data-partition protection status.

After successful persistence and artifact validation, temporary in-memory objects that
are no longer required for downstream evaluation are released.

No additional model fitting, resampling, Validation prediction, or Independent Test
evaluation is performed.

The persisted final Random Forest model becomes the authoritative model for
Section 5.12 — Independent Test Evaluation.

In [ ]:
# ================================================================
# 5.11.6 — FINAL RANDOM FOREST MODEL PERSISTENCE
#            AND TRAINING CLEANUP
# ================================================================

import gc
import json
import joblib


print("=" * 72)
print("5.11.6 — FINAL RANDOM FOREST MODEL PERSISTENCE")
print("AND TRAINING CLEANUP")
print("=" * 72)


# ---------------------------------------------------------------
# 1. 5.11.4 FINAL TRAINING BOUNDARY
# ---------------------------------------------------------------

print("\n[5.11.4 FINAL TRAINING BOUNDARY]")

assert "RF_5_11_4_VALIDATION" in globals(), (
    "Section 5.11.4 validation state is unavailable."
)

assert all(
    RF_5_11_4_VALIDATION.values()
), (
    "Section 5.11.4 final RF-3 training validation is incomplete."
)

assert "RF3_MODEL" in globals(), (
    "Final RF-3 model RF3_MODEL is unavailable."
)

assert hasattr(
    RF3_MODEL,
    "estimators_"
), (
    "RF3_MODEL is not a fitted Random Forest model."
)

print("✓ Section 5.11.4 final RF-3 training completed")
print("✓ Final fitted RF-3 model is available")
print("✓ RF-3 training validation state is complete")


# ---------------------------------------------------------------
# 2. ESTABLISHED FINAL-MODEL ARTIFACT BOUNDARY
# ---------------------------------------------------------------

print("\n[ESTABLISHED FINAL-MODEL ARTIFACT BOUNDARY]")

assert "RF_EXPERIMENT_ARTIFACTS" in globals(), (
    "Established RF_EXPERIMENT_ARTIFACTS mapping is unavailable."
)

assert (
    "final_model"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Established final-model artifact entry is unavailable."
)

assert (
    "final_model_metadata"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Established final-model metadata artifact entry is unavailable."
)

assert "RF_FINAL_MODEL_OUTPUT_DIR" in globals(), (
    "Established RF_FINAL_MODEL_OUTPUT_DIR is unavailable."
)

assert "RANDOM_FOREST_MODEL_DIR" in globals(), (
    "Established RANDOM_FOREST_MODEL_DIR is unavailable."
)

assert (
    RF_EXPERIMENT_ARTIFACTS["final_model"].parent
    == RANDOM_FOREST_MODEL_DIR
), (
    "Final Random Forest model artifact path is inconsistent."
)

assert (
    RF_EXPERIMENT_ARTIFACTS["final_model_metadata"].parent
    == RF_FINAL_MODEL_OUTPUT_DIR
), (
    "Final Random Forest metadata artifact path is inconsistent."
)

print(
    f"✓ Final RF model path : "
    f"{RF_EXPERIMENT_ARTIFACTS['final_model']}"
)

print(
    f"✓ Final RF metadata   : "
    f"{RF_EXPERIMENT_ARTIFACTS['final_model_metadata']}"
)

print("✓ Established final-model artifact boundary retained")
print("✓ No new final-model directory created")


# ---------------------------------------------------------------
# 3. FINAL RF-3 MODEL CONTRACT BEFORE PERSISTENCE
# ---------------------------------------------------------------

print("\n[FINAL RF-3 MODEL CONTRACT BEFORE PERSISTENCE]")

assert (
    RF3_MODEL.n_features_in_
    == EXPECTED_MODEL_READY_FEATURE_COUNT
), (
    "Final RF-3 model feature count does not match "
    "the 32-feature model-ready contract."
)

assert np.array_equal(
    RF3_MODEL.classes_,
    np.asarray(EXPECTED_RF_CLASS_IDS)
), (
    "Final RF-3 model classes do not match "
    "the established nine-class RF taxonomy."
)

assert (
    len(RF3_MODEL.estimators_)
    == RF_COMMON_CONFIGURATION["n_estimators"]
), (
    "Final RF-3 model does not contain the expected "
    "number of Random Forest trees."
)

assert (
    RF3_MODEL.max_features
    == RF_COMMON_CONFIGURATION["max_features"]
), (
    "Final RF-3 max_features configuration is inconsistent."
)

assert (
    RF3_MODEL.max_depth
    == RF_COMMON_CONFIGURATION["max_depth"]
), (
    "Final RF-3 max_depth configuration is inconsistent."
)

assert (
    RF3_MODEL.bootstrap
    == RF_COMMON_CONFIGURATION["bootstrap"]
), (
    "Final RF-3 bootstrap configuration is inconsistent."
)

assert (
    RF3_MODEL.n_jobs
    == RF_COMMON_CONFIGURATION["n_jobs"]
), (
    "Final RF-3 n_jobs configuration is inconsistent."
)

assert (
    RF3_MODEL.random_state
    == RANDOM_SEED
), (
    "Final RF-3 random_state is inconsistent."
)

assert (
    RF3_MODEL.class_weight is None
), (
    "Final RF-3 model must retain class_weight=None."
)

print(
    f"✓ Final model features : "
    f"{RF3_MODEL.n_features_in_}"
)

print(
    f"✓ Final model classes  : "
    f"{len(RF3_MODEL.classes_)}"
)

print(
    f"✓ Final model trees    : "
    f"{len(RF3_MODEL.estimators_)}"
)

print(
    f"✓ Final model state    : "
    f"{RF3_MODEL.random_state}"
)

print("✓ Class weighting = None")
print("✓ Final RF-3 model contract validated")


# ---------------------------------------------------------------
# 4. FINAL RF-3 METADATA CONSTRUCTION
# ---------------------------------------------------------------

print("\n[FINAL RF-3 METADATA CONSTRUCTION]")

FINAL_RF_MODEL_METADATA = {

    "strategy_id":
        "RF-3",

    "strategy_name":
        "Controlled Random Oversampling",

    "strategy":
        RF3_CONFIGURATION,

    "controlled_oversampling_configuration":
        RF3_SAMPLING_CONFIGURATION,

    "common_random_forest_configuration":
        RF_COMMON_CONFIGURATION,

    "random_seed":
        int(RANDOM_SEED),

    "feature_count":
        int(RF3_MODEL.n_features_in_),

    "class_count":
        int(len(RF3_MODEL.classes_)),

    "class_mapping": {
        str(class_id): str(class_name)
        for class_id, class_name
        in RF_CLASS_MAPPING.items()
    },

    "feature_order":
        list(RF_FEATURE_ORDER),

    "training_observations":
        int(
            EXPECTED_MODEL_READY_SHAPES[
                "Training"
            ][0]
        ),

    "final_oversampled_training_observations":
        int(
            RF3_OVERSAMPLED_TRAINING_OBSERVATIONS
        ),

    "additional_oversampled_observations":
        int(
            RF3_TOTAL_ADDITIONAL_OBSERVATIONS
        ),

    "training_feature_shape":
        list(
            EXPECTED_MODEL_READY_SHAPES[
                "Training"
            ]
        ),

    "final_oversampled_training_feature_shape": [
        int(RF3_OVERSAMPLED_TRAINING_OBSERVATIONS),
        int(EXPECTED_MODEL_READY_FEATURE_COUNT)
    ],

    "validation_observations":
        int(
            EXPECTED_MODEL_READY_SHAPES[
                "Validation"
            ][0]
        ),

    "training_feature_dtype":
        "float32",

    "training_target_dtype":
        "int64",

    "final_oversampled_training_feature_dtype":
        "float32",

    "final_oversampled_training_target_dtype":
        "int64",

    "training_time_seconds":
        float(
            RF3_TRAINING_TIME_SECONDS
        ),

    "available_system_ram_before_fit_gb":
        float(
            RF3_AVAILABLE_MEMORY_BEFORE_FIT_GB
        ),

    "available_system_ram_after_fit_gb":
        float(
            RF3_AVAILABLE_MEMORY_AFTER_GB
        ),

    "process_ram_before_fit_gb":
        float(
            RF3_PROCESS_MEMORY_BEFORE_GB
        ),

    "process_ram_after_fit_gb":
        float(
            RF3_PROCESS_MEMORY_AFTER_GB
        ),

    "process_ram_delta_gb":
        float(
            RF3_PROCESS_MEMORY_DELTA_GB
        ),

    "training_partition":
        "Training",

    "validation_used_for_fitting":
        False,

    "validation_predictions_generated":
        False,

    "independent_test_used":
        False,

    "independent_test_predictions_generated":
        False,

    "resampling_used":
        True,

    "synthetic_sampling_used":
        False,

    "majority_downsampling_used":
        False,

    "heartbleed_oversampling":
        False,

    "infiltration_oversampling_eligible":
        True,

    "strategy_selected":
        True,

    "model_role":
        "Final Random Forest Model",

    "final_model":
        True,

    "model_artifact":
        str(
            RF_EXPERIMENT_ARTIFACTS[
                "final_model"
            ]
        ),

    "metadata_artifact":
        str(
            RF_EXPERIMENT_ARTIFACTS[
                "final_model_metadata"
            ]
        ),

    "persistence_completed":
        False,
}


print("✓ Final RF-3 metadata structure constructed")
print("✓ Strategy metadata = RF-3")
print("✓ Final-model role recorded")
print("✓ Training/resource metadata recorded")
print("✓ Validation/Test protection metadata recorded")


# ---------------------------------------------------------------
# 5. FINAL RF-3 MODEL PERSISTENCE
# ---------------------------------------------------------------

print("\n[FINAL RF-3 MODEL PERSISTENCE]")

RF_EXPERIMENT_ARTIFACTS[
    "final_model"
].parent.mkdir(
    parents=True,
    exist_ok=True
)

joblib.dump(
    RF3_MODEL,
    RF_EXPERIMENT_ARTIFACTS[
        "final_model"
    ]
)

assert (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model"
    ].is_file()
), (
    "Final Random Forest model was not persisted successfully."
)

assert (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model"
    ].stat().st_size > 0
), (
    "Persisted final Random Forest model artifact is empty."
)

print(
    "✓ Final RF-3 model persisted"
)

print(
    f"✓ Model artifact size : "
    f"{RF_EXPERIMENT_ARTIFACTS['final_model'].stat().st_size:,} bytes"
)


# ---------------------------------------------------------------
# 6. FINAL RF METADATA PERSISTENCE
# ---------------------------------------------------------------

print("\n[FINAL RF METADATA PERSISTENCE]")

FINAL_RF_MODEL_METADATA[
    "persistence_completed"
] = True

with open(
    RF_EXPERIMENT_ARTIFACTS[
        "final_model_metadata"
    ],
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        FINAL_RF_MODEL_METADATA,
        file,
        indent=4
    )

assert (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model_metadata"
    ].is_file()
), (
    "Final RF metadata was not persisted successfully."
)

assert (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model_metadata"
    ].stat().st_size > 0
), (
    "Persisted final RF metadata artifact is empty."
)

print("✓ Final RF metadata persisted")
print(
    f"✓ Metadata artifact size : "
    f"{RF_EXPERIMENT_ARTIFACTS['final_model_metadata'].stat().st_size:,} bytes"
)


# ---------------------------------------------------------------
# 7. PERSISTED FINAL RF-3 MODEL VALIDATION
# ---------------------------------------------------------------

print("\n[PERSISTED FINAL RF-3 MODEL VALIDATION]")

PERSISTED_FINAL_RF3_MODEL = joblib.load(
    RF_EXPERIMENT_ARTIFACTS[
        "final_model"
    ]
)

assert (
    PERSISTED_FINAL_RF3_MODEL.n_features_in_
    == EXPECTED_MODEL_READY_FEATURE_COUNT
), (
    "Persisted final RF model does not match "
    "the 32-feature model-ready contract."
)

assert np.array_equal(
    PERSISTED_FINAL_RF3_MODEL.classes_,
    np.asarray(EXPECTED_RF_CLASS_IDS)
), (
    "Persisted final RF model does not match "
    "the established nine-class RF taxonomy."
)

assert (
    len(
        PERSISTED_FINAL_RF3_MODEL.estimators_
    )
    == RF_COMMON_CONFIGURATION[
        "n_estimators"
    ]
), (
    "Persisted final RF model does not contain "
    "the expected number of trees."
)

assert (
    PERSISTED_FINAL_RF3_MODEL.random_state
    == RANDOM_SEED
), (
    "Persisted final RF model random_state is inconsistent."
)

assert (
    PERSISTED_FINAL_RF3_MODEL.class_weight
    is None
), (
    "Persisted final RF-3 model incorrectly uses class weighting."
)

print("✓ Persisted model feature count = 32")
print("✓ Persisted model class taxonomy = 9 classes")
print("✓ Persisted model tree count = 100")
print(
    f"✓ Persisted model random state = "
    f"{PERSISTED_FINAL_RF3_MODEL.random_state}"
)
print("✓ Persisted model class weighting = None")
print("✓ Persisted final RF-3 model contract validated")


# ---------------------------------------------------------------
# 8. PERSISTED FINAL RF METADATA VALIDATION
# ---------------------------------------------------------------

print("\n[PERSISTED FINAL RF METADATA VALIDATION]")

with open(
    RF_EXPERIMENT_ARTIFACTS[
        "final_model_metadata"
    ],
    "r",
    encoding="utf-8"
) as file:

    PERSISTED_FINAL_RF_METADATA = json.load(
        file
    )

assert (
    PERSISTED_FINAL_RF_METADATA[
        "strategy_id"
    ]
    == "RF-3"
), (
    "Persisted final-model metadata does not identify RF-3."
)

assert (
    PERSISTED_FINAL_RF_METADATA[
        "strategy_name"
    ]
    == "Controlled Random Oversampling"
), (
    "Persisted final-model metadata strategy name is incorrect."
)

assert (
    PERSISTED_FINAL_RF_METADATA[
        "training_partition"
    ]
    == "Training"
), (
    "Persisted final-model metadata does not identify "
    "Training as the fitting partition."
)

assert (
    PERSISTED_FINAL_RF_METADATA[
        "validation_used_for_fitting"
    ]
    is False
), (
    "Persisted final-model metadata incorrectly records "
    "Validation usage for fitting."
)

assert (
    PERSISTED_FINAL_RF_METADATA[
        "independent_test_used"
    ]
    is False
), (
    "Persisted final-model metadata incorrectly records "
    "Independent Test usage."
)

assert (
    PERSISTED_FINAL_RF_METADATA[
        "final_model"
    ]
    is True
), (
    "Persisted final-model metadata does not identify "
    "the artifact as the final model."
)

assert (
    PERSISTED_FINAL_RF_METADATA[
        "persistence_completed"
    ]
    is True
), (
    "Persisted final-model metadata does not record "
    "successful persistence."
)

print("✓ Persisted strategy = RF-3")
print("✓ Persisted strategy name = Controlled Random Oversampling")
print("✓ Persisted fitting partition = Training")
print("✓ Validation usage for fitting = False")
print("✓ Independent Test usage = False")
print("✓ Final-model flag = True")
print("✓ Persistence status = True")
print("✓ Final RF metadata contract validated")


# ---------------------------------------------------------------
# 9. INDEPENDENT TEST PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION]")

assert "X_test_scaled" not in globals(), (
    "Independent Test features are loaded."
)

assert "y_test" not in globals(), (
    "Independent Test targets are loaded."
)

print("✓ Independent Test features are not loaded")
print("✓ Independent Test targets are not loaded")
print("✓ No Test predictions generated")
print("✓ No Test metrics calculated")
print("✓ Independent Test remains reserved for Section 5.12")


# ---------------------------------------------------------------
# 10. FINAL TRAINING CLEANUP
# ---------------------------------------------------------------

print("\n[FINAL TRAINING CLEANUP]")

if "RF3_MODEL" in globals():
    del RF3_MODEL
    print("✓ In-memory final RF-3 fitted model released")
else:
    print("✓ In-memory final RF-3 fitted model already released")

if "PERSISTED_FINAL_RF3_MODEL" in globals():
    del PERSISTED_FINAL_RF3_MODEL
    print("✓ Temporary persisted-model validation object released")
else:
    print("✓ Temporary persisted-model validation object already released")

if "PERSISTED_FINAL_RF_METADATA" in globals():
    del PERSISTED_FINAL_RF_METADATA
    print("✓ Temporary metadata validation object released")
else:
    print("✓ Temporary metadata validation object already released")

if "FINAL_RF_MODEL_METADATA" in globals():
    del FINAL_RF_MODEL_METADATA
    print("✓ Temporary metadata construction object released")
else:
    print("✓ Temporary metadata construction object already released")

gc.collect()

print("✓ Garbage collection completed")
print("✓ Persisted final RF-3 model artifact retained")
print("✓ Persisted final RF metadata artifact retained")
print("✓ Authoritative N04 artifacts remain available")


# ---------------------------------------------------------------
# 11. FINAL 5.11.6 PERSISTENCE AND CLEANUP GATE
# ---------------------------------------------------------------

print("\n[FINAL 5.11.6 PERSISTENCE AND CLEANUP GATE]")

assert (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model"
    ].is_file()
), (
    "Final RF model artifact is unavailable after cleanup."
)

assert (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model_metadata"
    ].is_file()
), (
    "Final RF metadata artifact is unavailable after cleanup."
)

print("✓ Final RF-3 model persistence validated")
print("✓ Final RF metadata persistence validated")
print("✓ RF-3 strategy contract remains frozen")
print("✓ 32-feature model contract remains valid")
print("✓ Nine-class RF taxonomy remains valid")
print("✓ 100-tree Random Forest remains valid")
print("✓ Random state = 42 remains valid")
print("✓ Class weighting remains disabled")
print("✓ Training remains the final fitting partition")
print("✓ Validation was not used for final fitting")
print("✓ Independent Test remains completely protected")
print("✓ Temporary training objects released")
print("✓ Persisted final RF artifacts retained")
print("✓ No additional model fitting performed")
print("✓ No additional resampling performed")


print("\n" + "=" * 72)

print(
    "5.11.6 — FINAL RANDOM FOREST MODEL PERSISTENCE "
    "AND TRAINING CLEANUP PASSED"
)

print("=" * 72)

print(
    "\nFINAL RANDOM FOREST TRAINING COMPLETED"
)

print(
    "SELECTED STRATEGY: RF-3 — Controlled Random Oversampling"
)

print(
    "READY FOR 5.11.7 — FINAL RANDOM FOREST TRAINING "
    "COMPLETION AND READINESS GATE"
)

print("=" * 72)

========================================================================
5.11.6 — FINAL RANDOM FOREST MODEL PERSISTENCE
AND TRAINING CLEANUP
========================================================================

[5.11.4 FINAL TRAINING BOUNDARY]
✓ Section 5.11.4 final RF-3 training completed
✓ Final fitted RF-3 model is available
✓ RF-3 training validation state is complete

[ESTABLISHED FINAL-MODEL ARTIFACT BOUNDARY]
✓ Final RF model path : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models/random_forest/final_random_forest.joblib
✓ Final RF metadata   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/final_model/rf_final_model_metadata.json
✓ Established final-model artifact boundary retained
✓ No new final-model directory created

[FINAL RF-3 MODEL CONTRACT BEFORE PERSISTENCE]
✓ Final model features : 32
✓ Final model classes  : 9
✓ Final model trees    : 100
✓ Final model state    : 42
✓ Class weighting = None
✓ Final RF-3 model contract validated

[FINAL RF-3 METADATA CONSTRUCTION]
✓ Final RF-3 metadata structure constructed
✓ Strategy metadata = RF-3
✓ Final-model role recorded
✓ Training/resource metadata recorded
✓ Validation/Test protection metadata recorded

[FINAL RF-3 MODEL PERSISTENCE]
✓ Final RF-3 model persisted
✓ Model artifact size : 103,237,377 bytes

[FINAL RF METADATA PERSISTENCE]
✓ Final RF metadata persisted
✓ Metadata artifact size : 3,839 bytes

[PERSISTED FINAL RF-3 MODEL VALIDATION]
✓ Persisted model feature count = 32
✓ Persisted model class taxonomy = 9 classes
✓ Persisted model tree count = 100
✓ Persisted model random state = 42
✓ Persisted model class weighting = None
✓ Persisted final RF-3 model contract validated

[PERSISTED FINAL RF METADATA VALIDATION]
✓ Persisted strategy = RF-3
✓ Persisted strategy name = Controlled Random Oversampling
✓ Persisted fitting partition = Training
✓ Validation usage for fitting = False
✓ Independent Test usage = False
✓ Final-model flag = True
✓ Persistence status = True
✓ Final RF metadata contract validated

[INDEPENDENT TEST PROTECTION]
✓ Independent Test features are not loaded
✓ Independent Test targets are not loaded
✓ No Test predictions generated
✓ No Test metrics calculated
✓ Independent Test remains reserved for Section 5.12

[FINAL TRAINING CLEANUP]
✓ In-memory final RF-3 fitted model released
✓ Temporary persisted-model validation object released
✓ Temporary metadata validation object released
✓ Temporary metadata construction object released
✓ Garbage collection completed
✓ Persisted final RF-3 model artifact retained
✓ Persisted final RF metadata artifact retained
✓ Authoritative N04 artifacts remain available

[FINAL 5.11.6 PERSISTENCE AND CLEANUP GATE]
✓ Final RF-3 model persistence validated
✓ Final RF metadata persistence validated
✓ RF-3 strategy contract remains frozen
✓ 32-feature model contract remains valid
✓ Nine-class RF taxonomy remains valid
✓ 100-tree Random Forest remains valid
✓ Random state = 42 remains valid
✓ Class weighting remains disabled
✓ Training remains the final fitting partition
✓ Validation was not used for final fitting
✓ Independent Test remains completely protected
✓ Temporary training objects released
✓ Persisted final RF artifacts retained
✓ No additional model fitting performed
✓ No additional resampling performed

========================================================================
5.11.6 — FINAL RANDOM FOREST MODEL PERSISTENCE AND TRAINING CLEANUP PASSED
========================================================================

FINAL RANDOM FOREST TRAINING COMPLETED
SELECTED STRATEGY: RF-3 — Controlled Random Oversampling
READY FOR 5.11.7 — FINAL RANDOM FOREST TRAINING COMPLETION AND READINESS GATE
========================================================================

## 5.11.7 — Final Random Forest Training Completion and Readiness Gate

This subsection provides the final completion and readiness gate for Section 5.11 —
Final Random Forest Training.

The gate validates that the selected RF-3 — Controlled Random Oversampling strategy
has been fully trained, persisted, and validated under the frozen Random Forest
configuration and model-ready feature/class contracts.

The gate relies on the persisted final-model artifacts established in Section 5.11.6
because temporary in-memory final-training objects were intentionally released during
cleanup.

The gate verifies that:

- Section 5.11 final RF-3 training completed successfully.
- RF-3 remains the selected final strategy.
- The persisted final Random Forest model and metadata artifacts remain available.
- The persisted model and metadata represent the RF-3 Controlled Random Oversampling strategy.
- The frozen 32-feature and nine-class contracts remain valid.
- The final model retains the established 100-tree Random Forest configuration.
- Class weighting remains disabled.
- Training remains the only final fitting partition.
- Validation was not used for final model fitting.
- Independent Test data remains completely protected and reserved for Section 5.12.
- No additional model fitting, resampling, or prediction generation is performed.

No new model is constructed or trained in this subsection.
No Validation or Independent Test data is loaded.
This subsection only establishes that Section 5.11 is complete and that the persisted
final Random Forest is ready for Section 5.12 — Independent Test Evaluation.

In [ ]:
# ================================================================
# 5.11.7 — FINAL RANDOM FOREST TRAINING COMPLETION
#            AND READINESS GATE
# ================================================================

import json


print("=" * 72)
print("5.11.7 — FINAL RANDOM FOREST TRAINING COMPLETION")
print("AND READINESS GATE")
print("=" * 72)


# ---------------------------------------------------------------
# 1. SECTION 5.11 COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[SECTION 5.11 COMPLETION BOUNDARY]")

assert "RF_5_11_4_VALIDATION" in globals(), (
    "Section 5.11.4 validation state is unavailable."
)

assert all(
    RF_5_11_4_VALIDATION.values()
), (
    "Section 5.11.4 final RF-3 training validation is incomplete."
)

assert (
    "RF_EXPERIMENT_ARTIFACTS"
    in globals()
), (
    "Established RF_EXPERIMENT_ARTIFACTS mapping is unavailable."
)

assert (
    "final_model"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Established final RF model artifact entry is unavailable."
)

assert (
    "final_model_metadata"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Established final RF metadata artifact entry is unavailable."
)

print("✓ Section 5.11.4 final RF-3 training validation completed")
print("✓ Section 5.11.6 persistence and cleanup completed")
print("✓ Established final RF artifact mapping remains available")


# ---------------------------------------------------------------
# 2. FINAL RF-3 STRATEGY COMPLETION CONTRACT
# ---------------------------------------------------------------

print("\n[FINAL RF-3 STRATEGY COMPLETION CONTRACT]")

assert (
    RF3_CONFIGURATION["strategy_id"]
    == "RF-3"
), (
    "Final selected strategy is not RF-3."
)

assert (
    RF3_CONFIGURATION["strategy_name"]
    == "Controlled Random Oversampling"
), (
    "Final RF-3 strategy name is inconsistent."
)

assert (
    RF3_CONFIGURATION["class_weight"]
    is None
), (
    "Final RF-3 class weighting must remain disabled."
)

assert (
    RF3_CONFIGURATION["resampling"]
    is True
), (
    "Final RF-3 resampling configuration is inconsistent."
)

assert (
    RF3_CONFIGURATION["synthetic_sampling"]
    is False
), (
    "Final RF-3 synthetic sampling configuration is inconsistent."
)

print("✓ Selected final strategy = RF-3")
print("✓ Strategy name = Controlled Random Oversampling")
print("✓ Class weighting = None")
print("✓ Controlled random oversampling = enabled")
print("✓ Synthetic sampling = disabled")


# ---------------------------------------------------------------
# 3. PERSISTED FINAL RF ARTIFACT COMPLETION
# ---------------------------------------------------------------

print("\n[PERSISTED FINAL RF ARTIFACT COMPLETION]")

assert (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model"
    ].is_file()
), (
    "Persisted final Random Forest model artifact is unavailable."
)

assert (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model"
    ].stat().st_size > 0
), (
    "Persisted final Random Forest model artifact is empty."
)

assert (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model_metadata"
    ].is_file()
), (
    "Persisted final RF metadata artifact is unavailable."
)

assert (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model_metadata"
    ].stat().st_size > 0
), (
    "Persisted final RF metadata artifact is empty."
)

print("✓ Final Random Forest model artifact remains persisted")
print("✓ Final Random Forest model artifact is non-empty")
print("✓ Final RF metadata artifact remains persisted")
print("✓ Final RF metadata artifact is non-empty")


# ---------------------------------------------------------------
# 4. PERSISTED FINAL RF METADATA CONTRACT
# ---------------------------------------------------------------

print("\n[PERSISTED FINAL RF METADATA CONTRACT]")

assert (
    json.load(
        open(
            RF_EXPERIMENT_ARTIFACTS[
                "final_model_metadata"
            ],
            "r",
            encoding="utf-8"
        )
    )["strategy_id"]
    == "RF-3"
), (
    "Persisted final RF metadata does not identify RF-3."
)

assert (
    json.load(
        open(
            RF_EXPERIMENT_ARTIFACTS[
                "final_model_metadata"
            ],
            "r",
            encoding="utf-8"
        )
    )["strategy_name"]
    == "Controlled Random Oversampling"
), (
    "Persisted final RF metadata strategy name is inconsistent."
)

assert (
    json.load(
        open(
            RF_EXPERIMENT_ARTIFACTS[
                "final_model_metadata"
            ],
            "r",
            encoding="utf-8"
        )
    )["training_partition"]
    == "Training"
), (
    "Persisted final RF metadata does not identify Training "
    "as the fitting partition."
)

assert (
    json.load(
        open(
            RF_EXPERIMENT_ARTIFACTS[
                "final_model_metadata"
            ],
            "r",
            encoding="utf-8"
        )
    )["validation_used_for_fitting"]
    is False
), (
    "Persisted final RF metadata incorrectly records Validation "
    "usage for fitting."
)

assert (
    json.load(
        open(
            RF_EXPERIMENT_ARTIFACTS[
                "final_model_metadata"
            ],
            "r",
            encoding="utf-8"
        )
    )["independent_test_used"]
    is False
), (
    "Persisted final RF metadata incorrectly records Independent "
    "Test usage."
)

assert (
    json.load(
        open(
            RF_EXPERIMENT_ARTIFACTS[
                "final_model_metadata"
            ],
            "r",
            encoding="utf-8"
        )
    )["final_model"]
    is True
), (
    "Persisted final RF metadata does not identify the artifact "
    "as the final model."
)

assert (
    json.load(
        open(
            RF_EXPERIMENT_ARTIFACTS[
                "final_model_metadata"
            ],
            "r",
            encoding="utf-8"
        )
    )["persistence_completed"]
    is True
), (
    "Persisted final RF metadata does not record successful persistence."
)

print("✓ Persisted strategy = RF-3")
print("✓ Persisted strategy name = Controlled Random Oversampling")
print("✓ Persisted fitting partition = Training")
print("✓ Validation usage for fitting = False")
print("✓ Independent Test usage = False")
print("✓ Final-model flag = True")
print("✓ Persistence status = True")


# ---------------------------------------------------------------
# 5. FINAL MODEL CONTRACT COMPLETION
# ---------------------------------------------------------------

print("\n[FINAL MODEL CONTRACT COMPLETION]")

assert (
    json.load(
        open(
            RF_EXPERIMENT_ARTIFACTS[
                "final_model_metadata"
            ],
            "r",
            encoding="utf-8"
        )
    )["feature_count"]
    == EXPECTED_MODEL_READY_FEATURE_COUNT
), (
    "Persisted final model feature count does not match "
    "the established 32-feature contract."
)

assert (
    json.load(
        open(
            RF_EXPERIMENT_ARTIFACTS[
                "final_model_metadata"
            ],
            "r",
            encoding="utf-8"
        )
    )["class_count"]
    == len(EXPECTED_RF_CLASS_IDS)
), (
    "Persisted final model class count does not match "
    "the established RF taxonomy."
)

assert (
    json.load(
        open(
            RF_EXPERIMENT_ARTIFACTS[
                "final_model_metadata"
            ],
            "r",
            encoding="utf-8"
        )
    )["common_random_forest_configuration"]
    == RF_COMMON_CONFIGURATION
), (
    "Persisted final RF configuration does not match "
    "the frozen common Random Forest configuration."
)

assert (
    json.load(
        open(
            RF_EXPERIMENT_ARTIFACTS[
                "final_model_metadata"
            ],
            "r",
            encoding="utf-8"
        )
    )["random_seed"]
    == int(RANDOM_SEED)
), (
    "Persisted final RF random seed is inconsistent."
)

print("✓ 32-feature model contract remains valid")
print("✓ Nine-class RF taxonomy remains valid")
print("✓ Frozen Random Forest configuration remains valid")
print(f"✓ Random state = {RANDOM_SEED} remains valid")


# ---------------------------------------------------------------
# 6. DATA-LEAKAGE PROTECTION COMPLETION
# ---------------------------------------------------------------

print("\n[FINAL TRAINING DATA-LEAKAGE PROTECTION]")

assert "X_test_scaled" not in globals(), (
    "Independent Test features are loaded."
)

assert "y_test" not in globals(), (
    "Independent Test targets are loaded."
)

assert "RF3_MODEL" not in globals(), (
    "Temporary final RF-3 fitted model was not released."
)

assert "PERSISTED_FINAL_RF3_MODEL" not in globals(), (
    "Temporary persisted-model validation object was not released."
)

assert "FINAL_RF_MODEL_METADATA" not in globals(), (
    "Temporary final RF metadata construction object was not released."
)

print("✓ Independent Test features are not loaded")
print("✓ Independent Test targets are not loaded")
print("✓ Final in-memory RF-3 model has been released")
print("✓ Temporary persisted-model validation object has been released")
print("✓ Temporary metadata construction object has been released")
print("✓ No Test predictions or metrics were generated")
print("✓ Independent Test remains reserved for Section 5.12")


# ---------------------------------------------------------------
# 7. FINAL SECTION 5.11 READINESS GATE
# ---------------------------------------------------------------

print("\n[FINAL 5.11 RANDOM FOREST TRAINING READINESS GATE]")

print("✓ Section 5.11.1 — Definition and boundary validation completed")
print("✓ Section 5.11.2 — RF-3 Training input validation completed")
print("✓ Section 5.11.3 — RF-3 controlled oversampling preparation completed")
print("✓ Section 5.11.4 — Final RF-3 model construction and training completed")
print("✓ Section 5.11.5 — Final training validation and resource analysis completed")
print("✓ Section 5.11.6 — Final RF model persistence and cleanup completed")

print("✓ RF-3 — Controlled Random Oversampling remains the selected strategy")
print("✓ Final Random Forest model is persisted")
print("✓ Final RF metadata is persisted")
print("✓ Final model uses the frozen 32-feature contract")
print("✓ Final model uses the established nine-class RF taxonomy")
print("✓ Final model uses the frozen 100-tree Random Forest configuration")
print("✓ Class weighting remains disabled")
print("✓ Training-derived data remains the only fitting source")
print("✓ Validation remains excluded from final model fitting")
print("✓ Independent Test remains completely protected")
print("✓ No additional model fitting performed")
print("✓ No additional resampling performed")
print("✓ No additional Validation predictions generated")
print("✓ Final Random Forest artifacts are ready for downstream evaluation")


print("\n" + "=" * 72)

print(
    "5.11.7 — FINAL RANDOM FOREST TRAINING "
    "COMPLETION AND READINESS GATE PASSED"
)

print("=" * 72)

print("\nFINAL RANDOM FOREST TRAINING COMPLETED")
print("FINAL MODEL: RF-3 — Controlled Random Oversampling")
print("FINAL MODEL ARTIFACTS: PERSISTED AND VALIDATED")
print("INDEPENDENT TEST: RESERVED FOR SECTION 5.12")
print("READY FOR 5.12 — INDEPENDENT TEST EVALUATION")

print("=" * 72)

========================================================================
5.11.7 — FINAL RANDOM FOREST TRAINING COMPLETION
AND READINESS GATE
========================================================================

[SECTION 5.11 COMPLETION BOUNDARY]
✓ Section 5.11.4 final RF-3 training validation completed
✓ Section 5.11.6 persistence and cleanup completed
✓ Established final RF artifact mapping remains available

[FINAL RF-3 STRATEGY COMPLETION CONTRACT]
✓ Selected final strategy = RF-3
✓ Strategy name = Controlled Random Oversampling
✓ Class weighting = None
✓ Controlled random oversampling = enabled
✓ Synthetic sampling = disabled

[PERSISTED FINAL RF ARTIFACT COMPLETION]
✓ Final Random Forest model artifact remains persisted
✓ Final Random Forest model artifact is non-empty
✓ Final RF metadata artifact remains persisted
✓ Final RF metadata artifact is non-empty

[PERSISTED FINAL RF METADATA CONTRACT]
✓ Persisted strategy = RF-3
✓ Persisted strategy name = Controlled Random Oversampling
✓ Persisted fitting partition = Training
✓ Validation usage for fitting = False
✓ Independent Test usage = False
✓ Final-model flag = True
✓ Persistence status = True

[FINAL MODEL CONTRACT COMPLETION]
✓ 32-feature model contract remains valid
✓ Nine-class RF taxonomy remains valid
✓ Frozen Random Forest configuration remains valid
✓ Random state = 42 remains valid

[FINAL TRAINING DATA-LEAKAGE PROTECTION]
✓ Independent Test features are not loaded
✓ Independent Test targets are not loaded
✓ Final in-memory RF-3 model has been released
✓ Temporary persisted-model validation object has been released
✓ Temporary metadata construction object has been released
✓ No Test predictions or metrics were generated
✓ Independent Test remains reserved for Section 5.12

[FINAL 5.11 RANDOM FOREST TRAINING READINESS GATE]
✓ Section 5.11.1 — Definition and boundary validation completed
✓ Section 5.11.2 — RF-3 Training input validation completed
✓ Section 5.11.3 — RF-3 controlled oversampling preparation completed
✓ Section 5.11.4 — Final RF-3 model construction and training completed
✓ Section 5.11.5 — Final training validation and resource analysis completed
✓ Section 5.11.6 — Final RF model persistence and cleanup completed
✓ RF-3 — Controlled Random Oversampling remains the selected strategy
✓ Final Random Forest model is persisted
✓ Final RF metadata is persisted
✓ Final model uses the frozen 32-feature contract
✓ Final model uses the established nine-class RF taxonomy
✓ Final model uses the frozen 100-tree Random Forest configuration
✓ Class weighting remains disabled
✓ Training-derived data remains the only fitting source
✓ Validation remains excluded from final model fitting
✓ Independent Test remains completely protected
✓ No additional model fitting performed
✓ No additional resampling performed
✓ No additional Validation predictions generated
✓ Final Random Forest artifacts are ready for downstream evaluation

========================================================================
5.11.7 — FINAL RANDOM FOREST TRAINING COMPLETION AND READINESS GATE PASSED
========================================================================

FINAL RANDOM FOREST TRAINING COMPLETED
FINAL MODEL: RF-3 — Controlled Random Oversampling
FINAL MODEL ARTIFACTS: PERSISTED AND VALIDATED
INDEPENDENT TEST: RESERVED FOR SECTION 5.12
READY FOR 5.12 — INDEPENDENT TEST EVALUATION
========================================================================

# 5.12 — INDEPENDENT TEST EVALUATION

This section performs the final evaluation of the frozen and persisted Random Forest
model on the previously protected Independent Test partition.

The Independent Test partition is used only after:

- RF strategy comparison has been completed using Validation.
- RF-3 — Controlled Random Oversampling has been selected and frozen.
- The final RF-3 model has been trained using Training-derived data only.
- The final Random Forest model has been persisted and validated.
- Validation has remained excluded from final model fitting.
- The Independent Test partition has remained completely protected.

No model fitting, resampling, hyperparameter tuning, or strategy selection is permitted
during Independent Test evaluation.

The Independent Test partition is used exclusively for final performance evaluation.

## 5.12.1 — Independent Test Evaluation Definition and Boundary Validation

This subsection establishes the execution boundary for the final Independent Test
evaluation.

The selected and persisted final Random Forest model is RF-3 — Controlled Random
Oversampling. The model configuration remains frozen from Section 5.11.

The Independent Test partition is now authorized for evaluation, but it must not be
used for:

1. Model fitting.
2. Additional resampling or oversampling.
3. Hyperparameter selection.
4. Random Forest strategy selection.
5. Validation-based decision changes.
6. Any modification of the Test features or targets.

The final model must be evaluated exactly as persisted after Section 5.11.

No Independent Test features, targets, predictions, or Test metrics are loaded or
generated in this subsection. Test data loading is reserved for Section 5.12.2.

In [ ]:
# ================================================================
# 5.12.1 — INDEPENDENT TEST EVALUATION DEFINITION
#            AND BOUNDARY VALIDATION
# ================================================================

import json


print("=" * 72)
print("5.12.1 — INDEPENDENT TEST EVALUATION DEFINITION")
print("AND BOUNDARY VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. SECTION 5.11 COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[SECTION 5.11 COMPLETION BOUNDARY]")

assert "RF_5_11_4_VALIDATION" in globals(), (
    "Section 5.11.4 final RF-3 training validation state "
    "is unavailable."
)

assert all(
    RF_5_11_4_VALIDATION.values()
), (
    "Section 5.11.4 final RF-3 training validation "
    "state is incomplete."
)

assert "RF_EXPERIMENT_ARTIFACTS" in globals(), (
    "Established RF_EXPERIMENT_ARTIFACTS mapping is unavailable."
)

assert (
    "final_model"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Established final RF model artifact entry is unavailable."
)

assert (
    "final_model_metadata"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Established final RF metadata artifact entry is unavailable."
)

print("✓ Section 5.11 final RF-3 training validation completed")
print("✓ Established final RF artifact mapping remains available")


# ---------------------------------------------------------------
# 2. FINAL RF-3 STRATEGY BOUNDARY
# ---------------------------------------------------------------

print("\n[FINAL RF-3 STRATEGY BOUNDARY]")

assert "RF3_CONFIGURATION" in globals(), (
    "Final RF-3 configuration is unavailable."
)

assert (
    RF3_CONFIGURATION["strategy_id"]
    == "RF-3"
), (
    "Final Random Forest strategy is not RF-3."
)

assert (
    RF3_CONFIGURATION["strategy_name"]
    == "Controlled Random Oversampling"
), (
    "Final RF-3 strategy name is inconsistent."
)

assert (
    RF3_CONFIGURATION["class_weight"]
    is None
), (
    "Final RF-3 class weighting must remain disabled."
)

assert (
    RF3_CONFIGURATION["resampling"]
    is True
), (
    "Final RF-3 controlled resampling configuration "
    "is inconsistent."
)

assert (
    RF3_CONFIGURATION["synthetic_sampling"]
    is False
), (
    "Final RF-3 synthetic sampling must remain disabled."
)

print("✓ Selected final strategy = RF-3")
print("✓ Strategy name = Controlled Random Oversampling")
print("✓ Class weighting = None")
print("✓ Controlled random oversampling = enabled")
print("✓ Synthetic sampling = disabled")


# ---------------------------------------------------------------
# 3. PERSISTED FINAL-MODEL BOUNDARY
# ---------------------------------------------------------------

print("\n[PERSISTED FINAL-MODEL BOUNDARY]")

final_model_path = (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model"
    ]
)

final_model_metadata_path = (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model_metadata"
    ]
)

assert final_model_path.is_file(), (
    "Persisted final Random Forest model artifact "
    "is unavailable."
)

assert (
    final_model_path.stat().st_size > 0
), (
    "Persisted final Random Forest model artifact "
    "is empty."
)

assert final_model_metadata_path.is_file(), (
    "Persisted final Random Forest metadata artifact "
    "is unavailable."
)

assert (
    final_model_metadata_path.stat().st_size > 0
), (
    "Persisted final Random Forest metadata artifact "
    "is empty."
)

assert (
    final_model_path.parent
    == RANDOM_FOREST_MODEL_DIR
), (
    "Final Random Forest model artifact is outside "
    "the established trained-model directory."
)

assert (
    final_model_metadata_path.parent
    == RF_FINAL_MODEL_OUTPUT_DIR
), (
    "Final Random Forest metadata artifact is outside "
    "the established final-model output directory."
)

print(
    f"✓ Final RF model artifact : "
    f"{final_model_path}"
)

print(
    f"✓ Final RF metadata       : "
    f"{final_model_metadata_path}"
)

print("✓ Final RF model artifact is present and non-empty")
print("✓ Final RF metadata artifact is present and non-empty")
print("✓ Established final-model artifact boundary retained")


# ---------------------------------------------------------------
# 4. PERSISTED FINAL-MODEL METADATA BOUNDARY
# ---------------------------------------------------------------

print("\n[PERSISTED FINAL-MODEL METADATA BOUNDARY]")

with open(
    final_model_metadata_path,
    "r",
    encoding="utf-8"
) as file:

    final_rf_metadata = json.load(file)


assert (
    final_rf_metadata["strategy_id"]
    == "RF-3"
), (
    "Persisted final RF metadata does not identify RF-3."
)

assert (
    final_rf_metadata["strategy_name"]
    == "Controlled Random Oversampling"
), (
    "Persisted final RF metadata strategy name is inconsistent."
)

assert (
    final_rf_metadata["training_partition"]
    == "Training"
), (
    "Persisted final RF metadata does not identify "
    "Training as the fitting partition."
)

assert (
    final_rf_metadata["validation_used_for_fitting"]
    is False
), (
    "Persisted final RF metadata incorrectly records "
    "Validation usage for fitting."
)

assert (
    final_rf_metadata["independent_test_used"]
    is False
), (
    "Persisted final RF metadata must record that "
    "Independent Test has not been used."
)

assert (
    final_rf_metadata["final_model"]
    is True
), (
    "Persisted RF metadata does not identify the "
    "artifact as the final model."
)

assert (
    final_rf_metadata["persistence_completed"]
    is True
), (
    "Persisted RF metadata does not record successful "
    "model persistence."
)

print("✓ Persisted strategy = RF-3")
print("✓ Persisted strategy name = Controlled Random Oversampling")
print("✓ Persisted fitting partition = Training")
print("✓ Validation usage for fitting = False")
print("✓ Independent Test usage = False")
print("✓ Final-model flag = True")
print("✓ Persistence status = True")


# ---------------------------------------------------------------
# 5. INDEPENDENT TEST ARTIFACT BOUNDARY
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST ARTIFACT BOUNDARY]")

assert (
    "test_results"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Established Test-results artifact path is unavailable."
)

assert (
    "confusion_matrix"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Established confusion-matrix artifact path is unavailable."
)

assert (
    "classification_report"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Established classification-report artifact path is unavailable."
)

assert (
    RF_EXPERIMENT_ARTIFACTS[
        "test_results"
    ].parent
    == RF_EVALUATION_DIR
), (
    "Test-results artifact is outside the established "
    "RF evaluation directory."
)

assert (
    RF_EXPERIMENT_ARTIFACTS[
        "confusion_matrix"
    ].parent
    == RF_EVALUATION_DIR
), (
    "Confusion-matrix artifact is outside the established "
    "RF evaluation directory."
)

assert (
    RF_EXPERIMENT_ARTIFACTS[
        "classification_report"
    ].parent
    == RF_EVALUATION_DIR
), (
    "Classification-report artifact is outside the established "
    "RF evaluation directory."
)

print(
    f"✓ Test results path       : "
    f"{RF_EXPERIMENT_ARTIFACTS['test_results']}"
)

print(
    f"✓ Confusion matrix path   : "
    f"{RF_EXPERIMENT_ARTIFACTS['confusion_matrix']}"
)

print(
    f"✓ Classification report   : "
    f"{RF_EXPERIMENT_ARTIFACTS['classification_report']}"
)

print("✓ Established Test-evaluation artifact boundary retained")


# ---------------------------------------------------------------
# 6. INDEPENDENT TEST REMAINS UNLOADED
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION BOUNDARY]")

assert "X_test_scaled" not in globals(), (
    "Independent Test features are already loaded."
)

assert "y_test" not in globals(), (
    "Independent Test targets are already loaded."
)

print("✓ Independent Test features are not loaded")
print("✓ Independent Test targets are not loaded")


# ---------------------------------------------------------------
# 7. NO TEST EVALUATION PERFORMED YET
# ---------------------------------------------------------------

print("\n[TEST EVALUATION EXECUTION BOUNDARY]")

print("✓ No Independent Test predictions generated")
print("✓ No Independent Test probabilities generated")
print("✓ No Independent Test metrics calculated")
print("✓ No Test confusion matrix generated")
print("✓ No Test classification report generated")
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No hyperparameter selection performed")
print("✓ No strategy selection performed")

print(
    "✓ Independent Test loading and evaluation remain reserved "
    "for the following 5.12 subsections"
)


# ---------------------------------------------------------------
# 8. SECTION 5.12.1 VALIDATION STATE
# ---------------------------------------------------------------

RF_5_12_1_VALIDATION = {

    "section_5_11_training_complete":
        True,

    "final_strategy_rf3":
        RF3_CONFIGURATION["strategy_id"] == "RF-3",

    "final_strategy_name_valid":
        RF3_CONFIGURATION["strategy_name"]
        == "Controlled Random Oversampling",

    "class_weight_disabled":
        RF3_CONFIGURATION["class_weight"] is None,

    "controlled_oversampling_enabled":
        RF3_CONFIGURATION["resampling"] is True,

    "synthetic_sampling_disabled":
        RF3_CONFIGURATION["synthetic_sampling"] is False,

    "final_model_persisted":
        final_model_path.is_file()
        and final_model_path.stat().st_size > 0,

    "final_metadata_persisted":
        final_model_metadata_path.is_file()
        and final_model_metadata_path.stat().st_size > 0,

    "training_only_fitting_partition":
        final_rf_metadata["training_partition"]
        == "Training",

    "validation_excluded_from_fitting":
        final_rf_metadata["validation_used_for_fitting"]
        is False,

    "independent_test_not_previously_used":
        final_rf_metadata["independent_test_used"]
        is False,

    "independent_test_features_unloaded":
        "X_test_scaled" not in globals(),

    "independent_test_targets_unloaded":
        "y_test" not in globals(),

    "no_test_predictions_generated":
        True,

    "no_test_metrics_generated":
        True,

    "no_model_fitting_performed":
        True,

    "no_resampling_performed":
        True,
}


assert all(
    RF_5_12_1_VALIDATION.values()
), (
    "Section 5.12.1 Independent Test evaluation "
    "boundary validation is incomplete."
)


# ---------------------------------------------------------------
# 9. FINAL 5.12.1 GATE
# ---------------------------------------------------------------

print("\n[5.12.1 INDEPENDENT TEST EVALUATION BOUNDARY GATE]")

print("✓ Section 5.11 final Random Forest training is complete")
print("✓ RF-3 — Controlled Random Oversampling remains frozen")
print("✓ Final Random Forest model is persisted")
print("✓ Final RF metadata is persisted and validated")
print("✓ Training remains the final model fitting partition")
print("✓ Validation was excluded from final model fitting")
print("✓ Independent Test has not been used previously")
print("✓ Independent Test features remain unloaded")
print("✓ Independent Test targets remain unloaded")
print("✓ No Test predictions or metrics have been generated")
print("✓ No model fitting or resampling is permitted in 5.12.1")
print("✓ Independent Test evaluation boundary is established")


print("\n" + "=" * 72)

print(
    "5.12.1 — INDEPENDENT TEST EVALUATION DEFINITION "
    "AND BOUNDARY VALIDATION PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.12.2 — INDEPENDENT TEST INPUT "
    "LOADING AND CONTRACT VALIDATION"
)

print("=" * 72)

========================================================================
5.12.1 — INDEPENDENT TEST EVALUATION DEFINITION
AND BOUNDARY VALIDATION
========================================================================

[SECTION 5.11 COMPLETION BOUNDARY]
✓ Section 5.11 final RF-3 training validation completed
✓ Established final RF artifact mapping remains available

[FINAL RF-3 STRATEGY BOUNDARY]
✓ Selected final strategy = RF-3
✓ Strategy name = Controlled Random Oversampling
✓ Class weighting = None
✓ Controlled random oversampling = enabled
✓ Synthetic sampling = disabled

[PERSISTED FINAL-MODEL BOUNDARY]
✓ Final RF model artifact : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models/random_forest/final_random_forest.joblib
✓ Final RF metadata       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/final_model/rf_final_model_metadata.json
✓ Final RF model artifact is present and non-empty
✓ Final RF metadata artifact is present and non-empty
✓ Established final-model artifact boundary retained

[PERSISTED FINAL-MODEL METADATA BOUNDARY]
✓ Persisted strategy = RF-3
✓ Persisted strategy name = Controlled Random Oversampling
✓ Persisted fitting partition = Training
✓ Validation usage for fitting = False
✓ Independent Test usage = False
✓ Final-model flag = True
✓ Persistence status = True

[INDEPENDENT TEST ARTIFACT BOUNDARY]
✓ Test results path       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/test_results.csv
✓ Confusion matrix path   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/confusion_matrix.csv
✓ Classification report   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/classification_report.csv
✓ Established Test-evaluation artifact boundary retained

[INDEPENDENT TEST PROTECTION BOUNDARY]
✓ Independent Test features are not loaded
✓ Independent Test targets are not loaded

[TEST EVALUATION EXECUTION BOUNDARY]
✓ No Independent Test predictions generated
✓ No Independent Test probabilities generated
✓ No Independent Test metrics calculated
✓ No Test confusion matrix generated
✓ No Test classification report generated
✓ No model fitting performed
✓ No resampling performed
✓ No hyperparameter selection performed
✓ No strategy selection performed
✓ Independent Test loading and evaluation remain reserved for the following 5.12 subsections

[5.12.1 INDEPENDENT TEST EVALUATION BOUNDARY GATE]
✓ Section 5.11 final Random Forest training is complete
✓ RF-3 — Controlled Random Oversampling remains frozen
✓ Final Random Forest model is persisted
✓ Final RF metadata is persisted and validated
✓ Training remains the final model fitting partition
✓ Validation was excluded from final model fitting
✓ Independent Test has not been used previously
✓ Independent Test features remain unloaded
✓ Independent Test targets remain unloaded
✓ No Test predictions or metrics have been generated
✓ No model fitting or resampling is permitted in 5.12.1
✓ Independent Test evaluation boundary is established

========================================================================
5.12.1 — INDEPENDENT TEST EVALUATION DEFINITION AND BOUNDARY VALIDATION PASSED
========================================================================

READY FOR 5.12.2 — INDEPENDENT TEST INPUT LOADING AND CONTRACT VALIDATION
========================================================================

## 5.12.2 — Independent Test Input Loading and Contract Validation

This subsection loads the authoritative Independent Test features and targets
from the established N04/RF input artifacts.

The Independent Test partition is loaded only after completion of the RF
strategy-selection and final Random Forest training stages.

The loaded Test representation must satisfy the frozen model-ready contract:

- 565,510 Test observations.
- 32 model-ready features.
- `float32` Test features.
- `int64` Test targets.
- Observation-aligned Test features and targets.
- The established frozen RF feature-order contract.
- The established nine-class RF taxonomy.

The Test artifacts are opened as read-only memory maps to avoid unnecessary
full-array RAM duplication.

This subsection does not:

- Fit or modify the final Random Forest.
- Perform any resampling.
- Modify the Independent Test distribution.
- Generate Test predictions.
- Generate Test probabilities.
- Calculate Test metrics.
- Modify Training or Validation data.

The Independent Test partition becomes available for final evaluation only
after all input-contract and leakage-protection checks in this subsection
have passed.

In [ ]:
# ================================================================
# 5.12.2 — INDEPENDENT TEST INPUT LOADING
#            AND CONTRACT VALIDATION
# ================================================================

print("=" * 72)
print("5.12.2 — INDEPENDENT TEST INPUT LOADING")
print("AND CONTRACT VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. 5.12.1 INDEPENDENT TEST EVALUATION BOUNDARY
# ---------------------------------------------------------------

print("\n[5.12.1 INDEPENDENT TEST EVALUATION BOUNDARY]")

assert "RF_5_12_1_VALIDATION" in globals(), (
    "Section 5.12.1 validation state is unavailable."
)

assert all(
    RF_5_12_1_VALIDATION.values()
), (
    "Section 5.12.1 Independent Test evaluation "
    "boundary validation is incomplete."
)

assert (
    RF_5_12_1_VALIDATION[
        "independent_test_features_unloaded"
    ]
), (
    "Independent Test features were already loaded "
    "before Section 5.12.2."
)

assert (
    RF_5_12_1_VALIDATION[
        "independent_test_targets_unloaded"
    ]
), (
    "Independent Test targets were already loaded "
    "before Section 5.12.2."
)

print("✓ Section 5.12.1 boundary validation completed")
print("✓ Independent Test features were previously unloaded")
print("✓ Independent Test targets were previously unloaded")


# ---------------------------------------------------------------
# 2. ESTABLISHED INDEPENDENT TEST INPUT PATHS
# ---------------------------------------------------------------

print("\n[ESTABLISHED INDEPENDENT TEST INPUT PATHS]")

assert "RF_INPUT_PATHS" in globals(), (
    "Established RF_INPUT_PATHS mapping is unavailable."
)

assert (
    "Test features"
    in RF_INPUT_PATHS
), (
    "Established Test feature input path is unavailable."
)

assert (
    "Test targets"
    in RF_INPUT_PATHS
), (
    "Established Test target input path is unavailable."
)

assert (
    RF_INPUT_PATHS["Test features"].is_file()
), (
    "Authoritative Independent Test feature artifact "
    "was not found."
)

assert (
    RF_INPUT_PATHS["Test targets"].is_file()
), (
    "Authoritative Independent Test target artifact "
    "was not found."
)

assert (
    RF_INPUT_PATHS["Test features"].stat().st_size > 0
), (
    "Independent Test feature artifact is empty."
)

assert (
    RF_INPUT_PATHS["Test targets"].stat().st_size > 0
), (
    "Independent Test target artifact is empty."
)

print(
    f"✓ Test features : "
    f"{RF_INPUT_PATHS['Test features']}"
)

print(
    f"✓ Test targets  : "
    f"{RF_INPUT_PATHS['Test targets']}"
)

print("✓ Established N04/RF Test input paths retained")


# ---------------------------------------------------------------
# 3. READ-ONLY INDEPENDENT TEST INPUT LOADING
# ---------------------------------------------------------------

print("\n[READ-ONLY INDEPENDENT TEST INPUT LOADING]")

X_test_scaled = np.load(
    RF_INPUT_PATHS["Test features"],
    mmap_mode="r"
)

y_test = np.load(
    RF_INPUT_PATHS["Test targets"],
    mmap_mode="r"
)

assert isinstance(
    X_test_scaled,
    np.memmap
), (
    "Independent Test features were not loaded "
    "as a NumPy memory map."
)

assert isinstance(
    y_test,
    np.memmap
), (
    "Independent Test targets were not loaded "
    "as a NumPy memory map."
)

print(
    "✓ Independent Test features opened as "
    "read-only memory map"
)

print(
    "✓ Independent Test targets opened as "
    "read-only memory map"
)

print(
    "✓ No full Independent Test-array RAM duplication performed"
)


# ---------------------------------------------------------------
# 4. AUTHORITATIVE TEST SHAPE AND DTYPE CONTRACT
# ---------------------------------------------------------------

print("\n[AUTHORITATIVE TEST SHAPE AND DTYPE CONTRACT]")

assert (
    X_test_scaled.shape
    == EXPECTED_MODEL_READY_SHAPES["Test"]
), (
    "Independent Test feature shape does not match "
    "the authoritative N04 model-ready contract."
)

assert (
    X_test_scaled.dtype
    == EXPECTED_MODEL_READY_DTYPE
), (
    "Independent Test features do not use the "
    "authoritative model-ready dtype."
)

assert (
    y_test.shape
    == (
        EXPECTED_MODEL_READY_SHAPES["Test"][0],
    )
), (
    "Independent Test target shape does not match "
    "the authoritative Test observation count."
)

assert (
    y_test.dtype
    == np.dtype("int64")
), (
    "Independent Test targets must use int64."
)

print(
    f"✓ Test feature shape : "
    f"{X_test_scaled.shape}"
)

print(
    f"✓ Test target shape  : "
    f"{y_test.shape}"
)

print(
    f"✓ Test feature dtype : "
    f"{X_test_scaled.dtype}"
)

print(
    f"✓ Test target dtype  : "
    f"{y_test.dtype}"
)


# ---------------------------------------------------------------
# 5. TEST FEATURE-SPACE CONTRACT
# ---------------------------------------------------------------

print("\n[TEST FEATURE-SPACE CONTRACT]")

assert (
    X_test_scaled.shape[1]
    == EXPECTED_MODEL_READY_FEATURE_COUNT
), (
    "Independent Test feature count does not match "
    "the established 32-feature contract."
)

assert (
    X_test_scaled.shape[1]
    == len(RF_FEATURE_ORDER)
), (
    "Independent Test feature count does not match "
    "the frozen RF feature order."
)

assert (
    len(RF_FEATURE_ORDER)
    == EXPECTED_MODEL_READY_FEATURE_COUNT
), (
    "Frozen RF feature order does not contain "
    "the expected 32 features."
)

assert (
    len(set(RF_FEATURE_ORDER))
    == EXPECTED_MODEL_READY_FEATURE_COUNT
), (
    "Frozen RF feature order contains duplicate features."
)

print(
    f"✓ Independent Test feature count = "
    f"{X_test_scaled.shape[1]}"
)

print(
    "✓ Independent Test matches the frozen "
    "32-feature RF representation"
)

print(
    "✓ Independent Test is compatible with "
    "the established RF feature-order contract"
)


# ---------------------------------------------------------------
# 6. TEST TARGET / NINE-CLASS TAXONOMY CONTRACT
# ---------------------------------------------------------------

print("\n[TEST TARGET / NINE-CLASS TAXONOMY CONTRACT]")

assert (
    len(RF_CLASS_MAPPING)
    == len(EXPECTED_RF_CLASS_IDS)
    == 9
), (
    "Established RF taxonomy does not contain "
    "the expected nine classes."
)

assert np.array_equal(
    np.asarray(
        EXPECTED_RF_CLASS_IDS
    ),
    np.arange(
        0,
        9,
        dtype=np.int64
    )
), (
    "Expected RF class IDs do not match "
    "the established 0–8 taxonomy."
)


test_class_ids = np.unique(
    y_test
)

assert np.array_equal(
    test_class_ids,
    np.asarray(EXPECTED_RF_CLASS_IDS)
), (
    "Independent Test targets do not contain exactly "
    "the established nine RF class IDs."
)

print(
    f"✓ Independent Test contains "
    f"{len(test_class_ids)} classes"
)

for class_id in test_class_ids:

    print(
        f"✓ Class {int(class_id)}: "
        f"{RF_CLASS_MAPPING[int(class_id)]}"
    )

print(
    "✓ Independent Test target taxonomy matches "
    "the established nine-class RF taxonomy"
)


# ---------------------------------------------------------------
# 7. TEST X/Y OBSERVATION ALIGNMENT
# ---------------------------------------------------------------

print("\n[TEST X/Y OBSERVATION ALIGNMENT]")

assert (
    X_test_scaled.shape[0]
    == y_test.shape[0]
), (
    "Independent Test features and targets are not "
    "observation-aligned."
)

assert (
    X_test_scaled.shape[0]
    == EXPECTED_RF_PARTITION_ROWS["Test"]
), (
    "Independent Test observation count does not match "
    "the authoritative RF partition contract."
)

print(
    f"✓ Test observations = "
    f"{X_test_scaled.shape[0]:,}"
)

print(
    "✓ Independent Test features and targets "
    "are observation-aligned"
)

print(
    "✓ Test observation count matches "
    "the authoritative 565,510-row contract"
)


# ---------------------------------------------------------------
# 8. INDEPENDENT TEST PARTITION PROTECTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PARTITION PROTECTION]")

assert (
    RF_TEST_PROTECTION_CONTRACT[
        "feature_selection_excluded"
    ]
), (
    "Independent Test was not excluded from "
    "feature selection."
)

assert (
    RF_TEST_PROTECTION_CONTRACT[
        "scaler_fitting_excluded"
    ]
), (
    "Independent Test was not used for scaler fitting."
)

assert (
    RF_TEST_PROTECTION_CONTRACT[
        "imbalance_strategy_selection_excluded"
    ]
), (
    "Independent Test was not excluded from "
    "imbalance strategy selection."
)

assert (
    RF_TEST_PROTECTION_CONTRACT[
        "model_fitting_excluded"
    ]
), (
    "Independent Test was not excluded from "
    "model fitting."
)

assert (
    RF_TEST_PROTECTION_CONTRACT[
        "hyperparameter_selection_excluded"
    ]
), (
    "Independent Test was not excluded from "
    "hyperparameter selection."
)

assert (
    RF_TEST_PROTECTION_CONTRACT[
        "intermediate_evaluation_excluded"
    ]
), (
    "Independent Test was not excluded from "
    "intermediate evaluation."
)

assert (
    RF_TEST_PROTECTION_CONTRACT[
        "final_evaluation_allowed"
    ]
), (
    "Independent Test is not authorized for "
    "final evaluation."
)

print("✓ Feature selection exclusion confirmed")
print("✓ Scaler-fitting exclusion confirmed")
print("✓ Imbalance-strategy selection exclusion confirmed")
print("✓ Model-fitting exclusion confirmed")
print("✓ Hyperparameter-selection exclusion confirmed")
print("✓ Intermediate-evaluation exclusion confirmed")
print("✓ Final evaluation is now authorized")


# ---------------------------------------------------------------
# 9. NO MODEL OPERATION IN 5.12.2
# ---------------------------------------------------------------

print("\n[5.12.2 MODEL-DEVELOPMENT BOUNDARY]")

print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No synthetic sampling performed")
print("✓ No hyperparameter selection performed")
print("✓ No strategy selection performed")
print("✓ No Test predictions generated")
print("✓ No Test probabilities generated")
print("✓ No Test metrics calculated")


# ---------------------------------------------------------------
# 10. SECTION 5.12.2 VALIDATION STATE
# ---------------------------------------------------------------

RF_5_12_2_VALIDATION = {

    "section_5_12_1_completed":
        all(
            RF_5_12_1_VALIDATION.values()
        ),

    "test_feature_path_valid":
        RF_INPUT_PATHS[
            "Test features"
        ].is_file(),

    "test_target_path_valid":
        RF_INPUT_PATHS[
            "Test targets"
        ].is_file(),

    "test_features_memory_mapped":
        isinstance(
            X_test_scaled,
            np.memmap
        ),

    "test_targets_memory_mapped":
        isinstance(
            y_test,
            np.memmap
        ),

    "test_feature_shape_valid":
        X_test_scaled.shape
        == EXPECTED_MODEL_READY_SHAPES["Test"],

    "test_target_shape_valid":
        y_test.shape
        == (
            EXPECTED_MODEL_READY_SHAPES["Test"][0],
        ),

    "test_feature_dtype_valid":
        X_test_scaled.dtype
        == EXPECTED_MODEL_READY_DTYPE,

    "test_target_dtype_valid":
        y_test.dtype
        == np.dtype("int64"),

    "test_feature_count_valid":
        X_test_scaled.shape[1]
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "test_feature_order_contract_valid":
        X_test_scaled.shape[1]
        == len(RF_FEATURE_ORDER),

    "test_target_taxonomy_valid":
        np.array_equal(
            test_class_ids,
            np.asarray(
                EXPECTED_RF_CLASS_IDS
            )
        ),

    "test_xy_alignment_valid":
        X_test_scaled.shape[0]
        == y_test.shape[0],

    "test_partition_size_valid":
        X_test_scaled.shape[0]
        == EXPECTED_RF_PARTITION_ROWS["Test"],

    "test_protection_contract_valid":
        all(
            RF_TEST_PROTECTION_CONTRACT.values()
        ),

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_test_predictions":
        True,

    "no_test_metrics":
        True,
}


assert all(
    RF_5_12_2_VALIDATION.values()
), (
    "Section 5.12.2 Independent Test input "
    "contract validation is incomplete."
)


# ---------------------------------------------------------------
# 11. FINAL 5.12.2 READINESS GATE
# ---------------------------------------------------------------

print("\n[5.12.2 INDEPENDENT TEST INPUT READINESS GATE]")

print("✓ Section 5.12.1 boundary validation completed")
print("✓ Authoritative Independent Test features loaded")
print("✓ Authoritative Independent Test targets loaded")
print("✓ Test features are read-only memory-mapped")
print("✓ Test targets are read-only memory-mapped")
print("✓ Test shape = (565,510, 32)")
print("✓ Test targets = (565,510,)")
print("✓ Test feature dtype = float32")
print("✓ Test target dtype = int64")
print("✓ Test feature count = 32")
print("✓ Test feature-order contract remains valid")
print("✓ Nine-class RF taxonomy confirmed")
print("✓ Test features and targets are observation-aligned")
print("✓ Independent Test protection contract remains valid")
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No Test predictions or metrics generated")
print("✓ Independent Test is ready for final evaluation")


print("\n" + "=" * 72)

print(
    "5.12.2 — INDEPENDENT TEST INPUT LOADING "
    "AND CONTRACT VALIDATION PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.12.3 — Persisted Final Random Forest Model Loading and TEST EVALUATION PREPARATION"
)

print("=" * 72)

========================================================================
5.12.2 — INDEPENDENT TEST INPUT LOADING
AND CONTRACT VALIDATION
========================================================================

[5.12.1 INDEPENDENT TEST EVALUATION BOUNDARY]
✓ Section 5.12.1 boundary validation completed
✓ Independent Test features were previously unloaded
✓ Independent Test targets were previously unloaded

[ESTABLISHED INDEPENDENT TEST INPUT PATHS]
✓ Test features : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/X_test_scaled.npy
✓ Test targets  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/model_ready_targets/y_test.npy
✓ Established N04/RF Test input paths retained

[READ-ONLY INDEPENDENT TEST INPUT LOADING]
✓ Independent Test features opened as read-only memory map
✓ Independent Test targets opened as read-only memory map
✓ No full Independent Test-array RAM duplication performed

[AUTHORITATIVE TEST SHAPE AND DTYPE CONTRACT]
✓ Test feature shape : (565510, 32)
✓ Test target shape  : (565510,)
✓ Test feature dtype : float32
✓ Test target dtype  : int64

[TEST FEATURE-SPACE CONTRACT]
✓ Independent Test feature count = 32
✓ Independent Test matches the frozen 32-feature RF representation
✓ Independent Test is compatible with the established RF feature-order contract

[TEST TARGET / NINE-CLASS TAXONOMY CONTRACT]
✓ Independent Test contains 9 classes
✓ Class 0: BENIGN
✓ Class 1: DDoS
✓ Class 2: Port Scan
✓ Class 3: Brute Force
✓ Class 4: Bot
✓ Class 5: Web Attack
✓ Class 6: Infiltration
✓ Class 7: DoS
✓ Class 8: Heartbleed
✓ Independent Test target taxonomy matches the established nine-class RF taxonomy

[TEST X/Y OBSERVATION ALIGNMENT]
✓ Test observations = 565,510
✓ Independent Test features and targets are observation-aligned
✓ Test observation count matches the authoritative 565,510-row contract

[INDEPENDENT TEST PARTITION PROTECTION]
✓ Feature selection exclusion confirmed
✓ Scaler-fitting exclusion confirmed
✓ Imbalance-strategy selection exclusion confirmed
✓ Model-fitting exclusion confirmed
✓ Hyperparameter-selection exclusion confirmed
✓ Intermediate-evaluation exclusion confirmed
✓ Final evaluation is now authorized

[5.12.2 MODEL-DEVELOPMENT BOUNDARY]
✓ No model fitting performed
✓ No resampling performed
✓ No synthetic sampling performed
✓ No hyperparameter selection performed
✓ No strategy selection performed
✓ No Test predictions generated
✓ No Test probabilities generated
✓ No Test metrics calculated

[5.12.2 INDEPENDENT TEST INPUT READINESS GATE]
✓ Section 5.12.1 boundary validation completed
✓ Authoritative Independent Test features loaded
✓ Authoritative Independent Test targets loaded
✓ Test features are read-only memory-mapped
✓ Test targets are read-only memory-mapped
✓ Test shape = (565,510, 32)
✓ Test targets = (565,510,)
✓ Test feature dtype = float32
✓ Test target dtype = int64
✓ Test feature count = 32
✓ Test feature-order contract remains valid
✓ Nine-class RF taxonomy confirmed
✓ Test features and targets are observation-aligned
✓ Independent Test protection contract remains valid
✓ No model fitting performed
✓ No resampling performed
✓ No Test predictions or metrics generated
✓ Independent Test is ready for final evaluation

========================================================================
5.12.2 — INDEPENDENT TEST INPUT LOADING AND CONTRACT VALIDATION PASSED
========================================================================

READY FOR 5.12.3 — Persisted Final Random Forest Model Loading and TEST EVALUATION PREPARATION
========================================================================

## 5.12.3 — Persisted Final Random Forest Model Loading and Test Evaluation Preparation

This subsection loads the persisted final Random Forest model selected in Section
5.10 and trained in Section 5.11 for evaluation on the authorized Independent Test
partition.

The persisted model must remain the RF-3 — Controlled Random Oversampling model
with the frozen Random Forest configuration and established 32-feature, nine-class
model contract.

The loaded model is validated against the persisted final-model metadata and the
model-ready Test input contract established in Section 5.12.2.

This subsection prepares the final inference boundary only. It does not generate
predictions, class probabilities, or evaluation metrics.

No model fitting, resampling, hyperparameter selection, strategy selection, or
modification of the persisted model is performed.

The validated persisted model and the already validated Independent Test inputs
are handed off to Section 5.12.4 for final Test prediction.

In [ ]:
# ================================================================
# 5.12.3 — PERSISTED FINAL RANDOM FOREST MODEL LOADING
#            AND TEST EVALUATION PREPARATION
# ================================================================

print("=" * 72)
print("5.12.3 — PERSISTED FINAL RANDOM FOREST MODEL LOADING")
print("AND TEST EVALUATION PREPARATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. 5.12.2 TEST INPUT COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[5.12.2 TEST INPUT COMPLETION BOUNDARY]")

assert "RF_5_12_2_VALIDATION" in globals(), (
    "Section 5.12.2 validation state is unavailable."
)

assert all(
    RF_5_12_2_VALIDATION.values()
), (
    "Section 5.12.2 Independent Test input validation "
    "is incomplete."
)

assert "X_test_scaled" in globals(), (
    "Independent Test features are unavailable."
)

assert "y_test" in globals(), (
    "Independent Test targets are unavailable."
)

assert (
    X_test_scaled.shape
    == EXPECTED_MODEL_READY_SHAPES["Test"]
), (
    "Independent Test features do not match the "
    "validated Test shape."
)

assert (
    y_test.shape
    == (
        EXPECTED_MODEL_READY_SHAPES["Test"][0],
    )
), (
    "Independent Test targets do not match the "
    "validated Test shape."
)

print("✓ Section 5.12.2 Test input validation completed")
print("✓ Independent Test features remain available")
print("✓ Independent Test targets remain available")
print("✓ Test input contract remains valid")


# ---------------------------------------------------------------
# 2. ESTABLISHED FINAL-MODEL ARTIFACT BOUNDARY
# ---------------------------------------------------------------

print("\n[ESTABLISHED FINAL-MODEL ARTIFACT BOUNDARY]")

assert "RF_EXPERIMENT_ARTIFACTS" in globals(), (
    "Established RF_EXPERIMENT_ARTIFACTS mapping is unavailable."
)

assert (
    "final_model"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Established final-model artifact entry is unavailable."
)

assert (
    "final_model_metadata"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Established final-model metadata artifact entry is unavailable."
)

final_model_path = (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model"
    ]
)

final_model_metadata_path = (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model_metadata"
    ]
)

assert final_model_path.is_file(), (
    "Persisted final Random Forest model artifact "
    "is unavailable."
)

assert (
    final_model_path.stat().st_size > 0
), (
    "Persisted final Random Forest model artifact is empty."
)

assert final_model_metadata_path.is_file(), (
    "Persisted final Random Forest metadata artifact "
    "is unavailable."
)

assert (
    final_model_metadata_path.stat().st_size > 0
), (
    "Persisted final Random Forest metadata artifact is empty."
)

print(
    f"✓ Final model artifact : "
    f"{final_model_path}"
)

print(
    f"✓ Final metadata       : "
    f"{final_model_metadata_path}"
)

print("✓ Persisted final-model artifacts are available")


# ---------------------------------------------------------------
# 3. PERSISTED FINAL-MODEL METADATA VALIDATION
# ---------------------------------------------------------------

print("\n[PERSISTED FINAL-MODEL METADATA VALIDATION]")

with open(
    final_model_metadata_path,
    "r",
    encoding="utf-8"
) as file:

    RF_FINAL_MODEL_METADATA_CHECK = json.load(file)

assert (
    RF_FINAL_MODEL_METADATA_CHECK[
        "strategy_id"
    ]
    == "RF-3"
), (
    "Persisted final model is not identified as RF-3."
)

assert (
    RF_FINAL_MODEL_METADATA_CHECK[
        "strategy_name"
    ]
    == "Controlled Random Oversampling"
), (
    "Persisted final model strategy name is inconsistent."
)

assert (
    RF_FINAL_MODEL_METADATA_CHECK[
        "training_partition"
    ]
    == "Training"
), (
    "Persisted final model does not identify Training "
    "as the fitting partition."
)

assert (
    RF_FINAL_MODEL_METADATA_CHECK[
        "validation_used_for_fitting"
    ]
    is False
), (
    "Persisted final model metadata indicates Validation "
    "was used for fitting."
)

assert (
    RF_FINAL_MODEL_METADATA_CHECK[
        "independent_test_used"
    ]
    is False
), (
    "Persisted final model metadata indicates Independent "
    "Test was previously used."
)

assert (
    RF_FINAL_MODEL_METADATA_CHECK[
        "final_model"
    ]
    is True
), (
    "Persisted artifact is not identified as the final model."
)

assert (
    RF_FINAL_MODEL_METADATA_CHECK[
        "persistence_completed"
    ]
    is True
), (
    "Persisted final model metadata does not confirm "
    "successful persistence."
)

print("✓ Persisted strategy = RF-3")
print("✓ Persisted strategy name = Controlled Random Oversampling")
print("✓ Fitting partition = Training")
print("✓ Validation excluded from fitting")
print("✓ Independent Test not previously used")
print("✓ Final-model flag = True")
print("✓ Persistence status = True")


# ---------------------------------------------------------------
# 4. LOAD PERSISTED FINAL RANDOM FOREST MODEL
# ---------------------------------------------------------------

print("\n[PERSISTED FINAL RANDOM FOREST MODEL LOADING]")

RF_FINAL_MODEL = joblib.load(
    final_model_path
)

assert hasattr(
    RF_FINAL_MODEL,
    "estimators_"
), (
    "Loaded final artifact is not a fitted Random Forest model."
)

print("✓ Persisted final Random Forest model loaded")
print("✓ Loaded artifact is a fitted Random Forest")


# ---------------------------------------------------------------
# 5. FINAL MODEL FEATURE / CLASS CONTRACT
# ---------------------------------------------------------------

print("\n[FINAL MODEL FEATURE / CLASS CONTRACT]")

assert (
    RF_FINAL_MODEL.n_features_in_
    == EXPECTED_MODEL_READY_FEATURE_COUNT
), (
    "Persisted final RF model feature count does not "
    "match the 32-feature contract."
)

assert (
    RF_FINAL_MODEL.n_features_in_
    == X_test_scaled.shape[1]
), (
    "Persisted final RF model feature count does not "
    "match the Independent Test feature count."
)

assert np.array_equal(
    RF_FINAL_MODEL.classes_,
    np.asarray(EXPECTED_RF_CLASS_IDS)
), (
    "Persisted final RF model classes do not match "
    "the established nine-class RF taxonomy."
)

assert (
    len(RF_FINAL_MODEL.classes_)
    == len(EXPECTED_RF_CLASS_IDS)
), (
    "Persisted final RF model class count is inconsistent."
)

print(
    f"✓ Final model feature count = "
    f"{RF_FINAL_MODEL.n_features_in_}"
)

print(
    f"✓ Final model class count = "
    f"{len(RF_FINAL_MODEL.classes_)}"
)

print("✓ Final model matches the nine-class RF taxonomy")
print("✓ Final model is compatible with Test feature space")


# ---------------------------------------------------------------
# 6. FROZEN RANDOM FOREST CONFIGURATION VALIDATION
# ---------------------------------------------------------------

print("\n[FROZEN RANDOM FOREST CONFIGURATION VALIDATION]")

assert (
    RF_FINAL_MODEL.n_estimators
    == RF_COMMON_CONFIGURATION[
        "n_estimators"
    ]
), (
    "Persisted final RF n_estimators differs from "
    "the frozen configuration."
)

assert (
    RF_FINAL_MODEL.max_features
    == RF_COMMON_CONFIGURATION[
        "max_features"
    ]
), (
    "Persisted final RF max_features differs from "
    "the frozen configuration."
)

assert (
    RF_FINAL_MODEL.max_depth
    == RF_COMMON_CONFIGURATION[
        "max_depth"
    ]
), (
    "Persisted final RF max_depth differs from "
    "the frozen configuration."
)

assert (
    RF_FINAL_MODEL.bootstrap
    == RF_COMMON_CONFIGURATION[
        "bootstrap"
    ]
), (
    "Persisted final RF bootstrap configuration differs "
    "from the frozen configuration."
)

assert (
    RF_FINAL_MODEL.n_jobs
    == RF_COMMON_CONFIGURATION[
        "n_jobs"
    ]
), (
    "Persisted final RF n_jobs differs from "
    "the frozen configuration."
)

assert (
    RF_FINAL_MODEL.random_state
    == RANDOM_SEED
), (
    "Persisted final RF random_state differs from "
    "the established RANDOM_SEED."
)

assert (
    RF_FINAL_MODEL.class_weight
    is None
), (
    "Persisted final RF class weighting must remain None."
)

print(
    f"✓ n_estimators = "
    f"{RF_FINAL_MODEL.n_estimators}"
)

print(
    f"✓ max_features = "
    f"{RF_FINAL_MODEL.max_features}"
)

print(
    f"✓ max_depth = "
    f"{RF_FINAL_MODEL.max_depth}"
)

print(
    f"✓ bootstrap = "
    f"{RF_FINAL_MODEL.bootstrap}"
)

print(
    f"✓ n_jobs = "
    f"{RF_FINAL_MODEL.n_jobs}"
)

print(
    f"✓ random_state = "
    f"{RF_FINAL_MODEL.random_state}"
)

print("✓ class_weight = None")
print("✓ Frozen Random Forest configuration validated")


# ---------------------------------------------------------------
# 7. TEST / MODEL COMPATIBILITY BOUNDARY
# ---------------------------------------------------------------

print("\n[TEST / MODEL COMPATIBILITY BOUNDARY]")

assert (
    RF_FINAL_MODEL.n_features_in_
    == X_test_scaled.shape[1]
), (
    "Final RF model cannot accept the validated "
    "Independent Test feature representation."
)

assert (
    len(RF_FINAL_MODEL.classes_)
    == len(test_class_ids)
), (
    "Final RF model class count does not match "
    "the Independent Test class taxonomy."
)

assert np.array_equal(
    RF_FINAL_MODEL.classes_,
    test_class_ids
), (
    "Final RF model classes do not match the "
    "Independent Test class IDs."
)

print("✓ Model feature space matches Test feature space")
print("✓ Model class count matches Test taxonomy")
print("✓ Model class IDs match Test class IDs")
print("✓ Final model is ready for Independent Test inference")


# ---------------------------------------------------------------
# 8. NO INFERENCE YET
# ---------------------------------------------------------------

print("\n[5.12.3 INFERENCE BOUNDARY]")

assert "RF_FINAL_TEST_PREDICTIONS" not in globals(), (
    "Test predictions already exist before the prediction subsection."
)

assert "RF_FINAL_TEST_PROBABILITIES" not in globals(), (
    "Test probabilities already exist before the prediction subsection."
)

print("✓ No Independent Test predictions generated")
print("✓ No Independent Test probabilities generated")
print("✓ No Test metrics calculated")
print("✓ No confusion matrix generated")
print("✓ No classification report generated")

print(
    "✓ Final inference remains reserved for Section 5.12.4"
)


# ---------------------------------------------------------------
# 9. SECTION 5.12.3 VALIDATION STATE
# ---------------------------------------------------------------

RF_5_12_3_VALIDATION = {

    "section_5_12_2_completed":
        all(
            RF_5_12_2_VALIDATION.values()
        ),

    "final_model_artifact_valid":
        final_model_path.is_file()
        and final_model_path.stat().st_size > 0,

    "final_model_metadata_valid":
        final_model_metadata_path.is_file()
        and final_model_metadata_path.stat().st_size > 0,

    "final_model_loaded":
        hasattr(
            RF_FINAL_MODEL,
            "estimators_"
        ),

    "final_model_feature_count_valid":
        RF_FINAL_MODEL.n_features_in_
        == EXPECTED_MODEL_READY_FEATURE_COUNT,

    "final_model_class_taxonomy_valid":
        np.array_equal(
            RF_FINAL_MODEL.classes_,
            np.asarray(EXPECTED_RF_CLASS_IDS)
        ),

    "final_model_configuration_valid":
        (
            RF_FINAL_MODEL.n_estimators
            == RF_COMMON_CONFIGURATION["n_estimators"]
            and
            RF_FINAL_MODEL.max_features
            == RF_COMMON_CONFIGURATION["max_features"]
            and
            RF_FINAL_MODEL.max_depth
            == RF_COMMON_CONFIGURATION["max_depth"]
            and
            RF_FINAL_MODEL.bootstrap
            == RF_COMMON_CONFIGURATION["bootstrap"]
            and
            RF_FINAL_MODEL.n_jobs
            == RF_COMMON_CONFIGURATION["n_jobs"]
            and
            RF_FINAL_MODEL.random_state
            == RANDOM_SEED
            and
            RF_FINAL_MODEL.class_weight is None
        ),

    "test_model_feature_compatibility":
        RF_FINAL_MODEL.n_features_in_
        == X_test_scaled.shape[1],

    "test_model_class_compatibility":
        np.array_equal(
            RF_FINAL_MODEL.classes_,
            test_class_ids
        ),

    "no_test_predictions_generated":
        "RF_FINAL_TEST_PREDICTIONS"
        not in globals(),

    "no_test_probabilities_generated":
        "RF_FINAL_TEST_PROBABILITIES"
        not in globals(),

    "no_model_fitting":
        True,

    "no_resampling":
        True,
}


assert all(
    RF_5_12_3_VALIDATION.values()
), (
    "Section 5.12.3 persisted final RF model "
    "loading and preparation validation is incomplete."
)


# ---------------------------------------------------------------
# 10. FINAL 5.12.3 READINESS GATE
# ---------------------------------------------------------------

print("\n[5.12.3 FINAL RF MODEL READINESS GATE]")

print("✓ Section 5.12.2 Test input validation completed")
print("✓ Persisted final RF-3 model loaded")
print("✓ Final model is a fitted Random Forest")
print("✓ Final model feature count = 32")
print("✓ Final model class count = 9")
print("✓ Final model class taxonomy matches Test taxonomy")
print("✓ n_estimators = 100")
print("✓ max_features = sqrt")
print("✓ max_depth = None")
print("✓ bootstrap = True")
print("✓ n_jobs = -1")
print(f"✓ random_state = {RANDOM_SEED}")
print("✓ class_weight = None")
print("✓ Persisted final model is compatible with Test inputs")
print("✓ No Test predictions generated")
print("✓ No Test probabilities generated")
print("✓ No Test metrics calculated")
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ Final RF model is ready for Test inference")


print("\n" + "=" * 72)

print(
    "5.12.3 — PERSISTED FINAL RANDOM FOREST MODEL "
    "LOADING AND TEST EVALUATION PREPARATION PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.12.4 — FINAL RANDOM FOREST "
    "INDEPENDENT TEST PREDICTION"
)

print("=" * 72)

========================================================================
5.12.3 — PERSISTED FINAL RANDOM FOREST MODEL LOADING
AND TEST EVALUATION PREPARATION
========================================================================

[5.12.2 TEST INPUT COMPLETION BOUNDARY]
✓ Section 5.12.2 Test input validation completed
✓ Independent Test features remain available
✓ Independent Test targets remain available
✓ Test input contract remains valid

[ESTABLISHED FINAL-MODEL ARTIFACT BOUNDARY]
✓ Final model artifact : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models/random_forest/final_random_forest.joblib
✓ Final metadata       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/final_model/rf_final_model_metadata.json
✓ Persisted final-model artifacts are available

[PERSISTED FINAL-MODEL METADATA VALIDATION]
✓ Persisted strategy = RF-3
✓ Persisted strategy name = Controlled Random Oversampling
✓ Fitting partition = Training
✓ Validation excluded from fitting
✓ Independent Test not previously used
✓ Final-model flag = True
✓ Persistence status = True

[PERSISTED FINAL RANDOM FOREST MODEL LOADING]
✓ Persisted final Random Forest model loaded
✓ Loaded artifact is a fitted Random Forest

[FINAL MODEL FEATURE / CLASS CONTRACT]
✓ Final model feature count = 32
✓ Final model class count = 9
✓ Final model matches the nine-class RF taxonomy
✓ Final model is compatible with Test feature space

[FROZEN RANDOM FOREST CONFIGURATION VALIDATION]
✓ n_estimators = 100
✓ max_features = sqrt
✓ max_depth = None
✓ bootstrap = True
✓ n_jobs = -1
✓ random_state = 42
✓ class_weight = None
✓ Frozen Random Forest configuration validated

[TEST / MODEL COMPATIBILITY BOUNDARY]
✓ Model feature space matches Test feature space
✓ Model class count matches Test taxonomy
✓ Model class IDs match Test class IDs
✓ Final model is ready for Independent Test inference

[5.12.3 INFERENCE BOUNDARY]
✓ No Independent Test predictions generated
✓ No Independent Test probabilities generated
✓ No Test metrics calculated
✓ No confusion matrix generated
✓ No classification report generated
✓ Final inference remains reserved for Section 5.12.4

[5.12.3 FINAL RF MODEL READINESS GATE]
✓ Section 5.12.2 Test input validation completed
✓ Persisted final RF-3 model loaded
✓ Final model is a fitted Random Forest
✓ Final model feature count = 32
✓ Final model class count = 9
✓ Final model class taxonomy matches Test taxonomy
✓ n_estimators = 100
✓ max_features = sqrt
✓ max_depth = None
✓ bootstrap = True
✓ n_jobs = -1
✓ random_state = 42
✓ class_weight = None
✓ Persisted final model is compatible with Test inputs
✓ No Test predictions generated
✓ No Test probabilities generated
✓ No Test metrics calculated
✓ No model fitting performed
✓ No resampling performed
✓ Final RF model is ready for Test inference

========================================================================
5.12.3 — PERSISTED FINAL RANDOM FOREST MODEL LOADING AND TEST EVALUATION PREPARATION PASSED
========================================================================

READY FOR 5.12.4 — FINAL RANDOM FOREST INDEPENDENT TEST PREDICTION
========================================================================

## 5.12.4 — Final Random Forest Independent Test Prediction

This subsection performs the first inference of the persisted final Random Forest
model on the authorized Independent Test partition.

The RF-3 — Controlled Random Oversampling model persisted in Section 5.11 is used
without modification. The Independent Test features remain in their validated
model-ready representation and are passed directly to the persisted model.

Only final class predictions are generated in this subsection. No model fitting,
resampling, hyperparameter selection, strategy selection, or Test-set metric
calculation is performed.

The generated Test predictions are validated for shape, dtype, class membership,
and alignment with the Independent Test targets. Inference time and throughput
are also recorded for subsequent resource analysis.

The validated predictions are handed off to Section 5.12.5 for Independent Test
performance evaluation.

In [ ]:
# ================================================================
# 5.12.4 — FINAL RANDOM FOREST INDEPENDENT TEST PREDICTION
# ================================================================

import time
import gc

print("=" * 72)
print("5.12.4 — FINAL RANDOM FOREST INDEPENDENT TEST PREDICTION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. PREVIOUS-SUBSECTION COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[PREVIOUS-SUBSECTION COMPLETION BOUNDARY]")

assert "RF_5_12_3_VALIDATION" in globals(), (
    "Section 5.12.3 validation state is unavailable."
)

assert all(
    RF_5_12_3_VALIDATION.values()
), (
    "Section 5.12.3 validation is incomplete."
)

assert "RF_FINAL_MODEL" in globals(), (
    "Persisted final Random Forest model is unavailable."
)

assert "X_test_scaled" in globals(), (
    "Independent Test features are unavailable."
)

assert "y_test" in globals(), (
    "Independent Test targets are unavailable."
)

print("✓ Section 5.12.3 validation completed")
print("✓ Persisted final Random Forest model is available")
print("✓ Independent Test features are available")
print("✓ Independent Test targets are available")


# ---------------------------------------------------------------
# 2. INDEPENDENT TEST INPUT CONTRACT
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST INPUT CONTRACT]")

assert (
    X_test_scaled.shape
    == EXPECTED_MODEL_READY_SHAPES["Test"]
), (
    f"Unexpected Independent Test feature shape: "
    f"{X_test_scaled.shape}"
)

assert (
    y_test.shape
    == (EXPECTED_MODEL_READY_SHAPES["Test"][0],)
), (
    f"Unexpected Independent Test target shape: "
    f"{y_test.shape}"
)

assert X_test_scaled.dtype == np.float32, (
    f"Independent Test features must be float32, "
    f"got {X_test_scaled.dtype}"
)

assert y_test.dtype == np.int64, (
    f"Independent Test targets must be int64, "
    f"got {y_test.dtype}"
)

assert (
    len(X_test_scaled)
    == len(y_test)
), (
    "Independent Test feature/target observations are not aligned."
)

assert (
    X_test_scaled.shape[1]
    == RF_FINAL_MODEL.n_features_in_
), (
    "Independent Test feature count does not match "
    "the persisted final Random Forest model."
)

print(
    f"✓ Test feature shape = {X_test_scaled.shape}"
)

print(
    f"✓ Test target shape = {y_test.shape}"
)

print(
    f"✓ Test feature dtype = {X_test_scaled.dtype}"
)

print(
    f"✓ Test target dtype = {y_test.dtype}"
)

print("✓ Test X/y observations are aligned")
print("✓ Test feature count matches final RF model")


# ---------------------------------------------------------------
# 3. FINAL MODEL INFERENCE CONTRACT
# ---------------------------------------------------------------

print("\n[FINAL MODEL INFERENCE CONTRACT]")

assert hasattr(
    RF_FINAL_MODEL,
    "predict"
), (
    "Persisted final Random Forest does not provide "
    "the required prediction interface."
)

assert np.array_equal(
    RF_FINAL_MODEL.classes_,
    np.asarray(EXPECTED_RF_CLASS_IDS)
), (
    "Persisted final Random Forest class taxonomy "
    "does not match the established RF taxonomy."
)

assert (
    RF_FINAL_MODEL.class_weight is None
), (
    "Final RF model class_weight has been unexpectedly modified."
)

print("✓ Final Random Forest prediction interface available")
print("✓ Final model class taxonomy validated")
print("✓ Final model remains unchanged")
print("✓ No fitting or resampling will be performed")


# ---------------------------------------------------------------
# 4. INDEPENDENT TEST PREDICTION
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PREDICTION]")

if "RF_FINAL_TEST_PREDICTIONS" in globals():
    del RF_FINAL_TEST_PREDICTIONS
    gc.collect()

RF_FINAL_TEST_PREDICTION_START = time.perf_counter()

RF_FINAL_TEST_PREDICTIONS = RF_FINAL_MODEL.predict(
    X_test_scaled
)

RF_FINAL_TEST_PREDICTION_END = time.perf_counter()

RF_FINAL_TEST_INFERENCE_TIME_SECONDS = (
    RF_FINAL_TEST_PREDICTION_END
    - RF_FINAL_TEST_PREDICTION_START
)

print("✓ Independent Test predictions generated")
print(
    f"✓ Prediction count = "
    f"{len(RF_FINAL_TEST_PREDICTIONS)}"
)

print(
    f"✓ Inference time = "
    f"{RF_FINAL_TEST_INFERENCE_TIME_SECONDS:.6f} seconds"
)


# ---------------------------------------------------------------
# 5. PREDICTION OUTPUT CONTRACT
# ---------------------------------------------------------------

print("\n[PREDICTION OUTPUT CONTRACT]")

assert (
    RF_FINAL_TEST_PREDICTIONS.shape
    == y_test.shape
), (
    "Final RF Test prediction shape does not match "
    "Independent Test targets."
)

assert (
    RF_FINAL_TEST_PREDICTIONS.ndim
    == 1
), (
    "Final RF Test predictions must be a one-dimensional "
    "class-label array."
)

assert (
    len(RF_FINAL_TEST_PREDICTIONS)
    == EXPECTED_RF_PARTITION_ROWS["Test"]
), (
    "Final RF Test prediction count does not match "
    "the authorized Independent Test row count."
)

assert (
    RF_FINAL_TEST_PREDICTIONS.dtype
    == np.int64
), (
    f"Final RF Test predictions must be int64, "
    f"got {RF_FINAL_TEST_PREDICTIONS.dtype}"
)

assert np.isfinite(
    RF_FINAL_TEST_PREDICTIONS
).all(), (
    "Final RF Test predictions contain non-finite values."
)

assert np.all(
    np.isin(
        RF_FINAL_TEST_PREDICTIONS,
        EXPECTED_RF_CLASS_IDS
    )
), (
    "Final RF Test predictions contain class IDs "
    "outside the established nine-class taxonomy."
)

print(
    f"✓ Prediction shape = "
    f"{RF_FINAL_TEST_PREDICTIONS.shape}"
)

print(
    f"✓ Prediction dtype = "
    f"{RF_FINAL_TEST_PREDICTIONS.dtype}"
)

print("✓ Prediction count matches Independent Test")
print("✓ Predictions contain finite values")
print("✓ All predicted class IDs are valid")


# ---------------------------------------------------------------
# 6. PREDICTION / TARGET ALIGNMENT
# ---------------------------------------------------------------

print("\n[PREDICTION / TARGET ALIGNMENT]")

assert (
    len(RF_FINAL_TEST_PREDICTIONS)
    == len(y_test)
), (
    "Final RF Test predictions and targets are not aligned."
)

print(
    f"✓ Predictions = "
    f"{len(RF_FINAL_TEST_PREDICTIONS):,}"
)

print(
    f"✓ Test targets = "
    f"{len(y_test):,}"
)

print("✓ Prediction/target observation counts are aligned")


# ---------------------------------------------------------------
# 7. INFERENCE RESOURCE SUMMARY
# ---------------------------------------------------------------

print("\n[INFERENCE RESOURCE SUMMARY]")

RF_FINAL_TEST_INFERENCE_THROUGHPUT = (
    len(RF_FINAL_TEST_PREDICTIONS)
    / RF_FINAL_TEST_INFERENCE_TIME_SECONDS
)

assert (
    RF_FINAL_TEST_INFERENCE_TIME_SECONDS > 0
), (
    "Measured Independent Test inference time is not positive."
)

assert np.isfinite(
    RF_FINAL_TEST_INFERENCE_THROUGHPUT
), (
    "Calculated Independent Test inference throughput "
    "is not finite."
)

print(
    f"✓ Inference time       : "
    f"{RF_FINAL_TEST_INFERENCE_TIME_SECONDS:.6f} seconds"
)

print(
    f"✓ Inference throughput : "
    f"{RF_FINAL_TEST_INFERENCE_THROUGHPUT:,.2f} samples/second"
)


# ---------------------------------------------------------------
# 8. TEST-EVALUATION BOUNDARY
# ---------------------------------------------------------------

print("\n[TEST-EVALUATION BOUNDARY]")

print("✓ Test predictions generated only from the persisted final model")
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No hyperparameter selection performed")
print("✓ No strategy selection performed")
print("✓ No Test-set metric calculated")
print("✓ No confusion matrix calculated")
print("✓ No classification report calculated")
print("✓ Independent Test remains reserved for final evaluation")


# ---------------------------------------------------------------
# 9. SECTION 5.12.4 VALIDATION STATE
# ---------------------------------------------------------------

RF_5_12_4_VALIDATION = {

    "section_5_12_3_completed":
        all(
            RF_5_12_3_VALIDATION.values()
        ),

    "test_prediction_generated":
        "RF_FINAL_TEST_PREDICTIONS"
        in globals(),

    "prediction_shape_valid":
        RF_FINAL_TEST_PREDICTIONS.shape
        == y_test.shape,

    "prediction_count_valid":
        len(RF_FINAL_TEST_PREDICTIONS)
        == EXPECTED_RF_PARTITION_ROWS["Test"],

    "prediction_dtype_valid":
        RF_FINAL_TEST_PREDICTIONS.dtype
        == np.int64,

    "prediction_values_finite":
        np.isfinite(
            RF_FINAL_TEST_PREDICTIONS
        ).all(),

    "prediction_classes_valid":
        np.all(
            np.isin(
                RF_FINAL_TEST_PREDICTIONS,
                EXPECTED_RF_CLASS_IDS
            )
        ),

    "prediction_target_alignment_valid":
        len(RF_FINAL_TEST_PREDICTIONS)
        == len(y_test),

    "inference_time_valid":
        RF_FINAL_TEST_INFERENCE_TIME_SECONDS > 0,

    "inference_throughput_valid":
        np.isfinite(
            RF_FINAL_TEST_INFERENCE_THROUGHPUT
        ),

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_test_metrics_calculated":
        True,
}


assert all(
    RF_5_12_4_VALIDATION.values()
), (
    "Section 5.12.4 Independent Test prediction "
    "validation is incomplete."
)


# ---------------------------------------------------------------
# 10. FINAL 5.12.4 READINESS GATE
# ---------------------------------------------------------------

print("\n[5.12.4 FINAL PREDICTION READINESS GATE]")

print("✓ Final persisted RF-3 model used for inference")
print("✓ Complete Independent Test partition evaluated")
print(
    f"✓ Test predictions = "
    f"{len(RF_FINAL_TEST_PREDICTIONS):,}"
)
print(
    f"✓ Inference time = "
    f"{RF_FINAL_TEST_INFERENCE_TIME_SECONDS:.6f} seconds"
)
print(
    f"✓ Inference throughput = "
    f"{RF_FINAL_TEST_INFERENCE_THROUGHPUT:,.2f} samples/second"
)
print("✓ Prediction shape validated")
print("✓ Prediction dtype validated")
print("✓ Prediction class IDs validated")
print("✓ Prediction/target alignment validated")
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No Test metrics calculated")


print("\n" + "=" * 72)

print(
    "5.12.4 — FINAL RANDOM FOREST INDEPENDENT TEST "
    "PREDICTION PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.12.5 — INDEPENDENT TEST "
    "PERFORMANCE EVALUATION"
)

print("=" * 72)

========================================================================
5.12.4 — FINAL RANDOM FOREST INDEPENDENT TEST PREDICTION
========================================================================

[PREVIOUS-SUBSECTION COMPLETION BOUNDARY]
✓ Section 5.12.3 validation completed
✓ Persisted final Random Forest model is available
✓ Independent Test features are available
✓ Independent Test targets are available

[INDEPENDENT TEST INPUT CONTRACT]
✓ Test feature shape = (565510, 32)
✓ Test target shape = (565510,)
✓ Test feature dtype = float32
✓ Test target dtype = int64
✓ Test X/y observations are aligned
✓ Test feature count matches final RF model

[FINAL MODEL INFERENCE CONTRACT]
✓ Final Random Forest prediction interface available
✓ Final model class taxonomy validated
✓ Final model remains unchanged
✓ No fitting or resampling will be performed

[INDEPENDENT TEST PREDICTION]
✓ Independent Test predictions generated
✓ Prediction count = 565510
✓ Inference time = 10.297429 seconds

[PREDICTION OUTPUT CONTRACT]
✓ Prediction shape = (565510,)
✓ Prediction dtype = int64
✓ Prediction count matches Independent Test
✓ Predictions contain finite values
✓ All predicted class IDs are valid

[PREDICTION / TARGET ALIGNMENT]
✓ Predictions = 565,510
✓ Test targets = 565,510
✓ Prediction/target observation counts are aligned

[INFERENCE RESOURCE SUMMARY]
✓ Inference time       : 10.297429 seconds
✓ Inference throughput : 54,917.59 samples/second

[TEST-EVALUATION BOUNDARY]
✓ Test predictions generated only from the persisted final model
✓ No model fitting performed
✓ No resampling performed
✓ No hyperparameter selection performed
✓ No strategy selection performed
✓ No Test-set metric calculated
✓ No confusion matrix calculated
✓ No classification report calculated
✓ Independent Test remains reserved for final evaluation

[5.12.4 FINAL PREDICTION READINESS GATE]
✓ Final persisted RF-3 model used for inference
✓ Complete Independent Test partition evaluated
✓ Test predictions = 565,510
✓ Inference time = 10.297429 seconds
✓ Inference throughput = 54,917.59 samples/second
✓ Prediction shape validated
✓ Prediction dtype validated
✓ Prediction class IDs validated
✓ Prediction/target alignment validated
✓ No model fitting performed
✓ No resampling performed
✓ No Test metrics calculated

========================================================================
5.12.4 — FINAL RANDOM FOREST INDEPENDENT TEST PREDICTION PASSED
========================================================================

READY FOR 5.12.5 — INDEPENDENT TEST PERFORMANCE EVALUATION
========================================================================

## 5.12.5 — Independent Test Performance Evaluation

This subsection evaluates the predictions generated by the persisted final
Random Forest model on the authorized Independent Test partition.

The evaluation follows the same metric definitions established during the
Random Forest Validation experiments. Macro F1 remains the primary performance
metric, with Macro Recall, Balanced Accuracy, Weighted F1, and Accuracy as
secondary metrics.

Per-class Precision, Recall, F1-score, and Support are calculated for all nine
network-traffic classes. A 9 × 9 confusion matrix is generated using the
established RF class ordering.

Operational error measures include the BENIGN false-positive rate and
class-wise attack false negatives. Supplementary multiclass ROC-AUC using a
one-vs-rest formulation is calculated from the final model's class
probabilities.

This subsection performs evaluation only. No model fitting, resampling,
hyperparameter selection, strategy selection, or modification of the
Independent Test data is performed.

The resulting Independent Test evaluation objects remain in memory for the
subsequent error/resource analysis and artifact-persistence stages.

In [ ]:
# ================================================================
# 5.12.5 — INDEPENDENT TEST PERFORMANCE EVALUATION
# ================================================================

import numpy as np
import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_recall_fscore_support,
    f1_score,
    recall_score,
    confusion_matrix,
    roc_auc_score
)


print("=" * 72)
print("5.12.5 — INDEPENDENT TEST PERFORMANCE EVALUATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. PREVIOUS-SUBSECTION COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[PREVIOUS-SUBSECTION COMPLETION BOUNDARY]")

assert "RF_5_12_4_VALIDATION" in globals(), (
    "Section 5.12.4 validation state is unavailable."
)

assert all(
    RF_5_12_4_VALIDATION.values()
), (
    "Section 5.12.4 Independent Test prediction "
    "validation is incomplete."
)

assert "RF_FINAL_MODEL" in globals(), (
    "Persisted final Random Forest model is unavailable."
)

assert "X_test_scaled" in globals(), (
    "Independent Test features are unavailable."
)

assert "y_test" in globals(), (
    "Independent Test targets are unavailable."
)

assert "RF_FINAL_TEST_PREDICTIONS" in globals(), (
    "Final Independent Test predictions are unavailable."
)

print("✓ Section 5.12.4 prediction validation completed")
print("✓ Persisted final RF-3 model remains available")
print("✓ Independent Test targets remain available")
print("✓ Independent Test predictions remain available")


# ---------------------------------------------------------------
# 2. INDEPENDENT TEST EVALUATION BOUNDARY
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST EVALUATION BOUNDARY]")

assert (
    RF_FINAL_TEST_PREDICTIONS.shape
    == y_test.shape
), (
    "Independent Test predictions and targets are not aligned."
)

assert (
    len(RF_FINAL_TEST_PREDICTIONS)
    == EXPECTED_RF_PARTITION_ROWS["Test"]
), (
    "Independent Test prediction count does not match "
    "the established Test partition size."
)

assert np.array_equal(
    RF_FINAL_MODEL.classes_,
    np.asarray(EXPECTED_RF_CLASS_IDS)
), (
    "Final Random Forest class taxonomy does not match "
    "the established nine-class taxonomy."
)

print(
    f"✓ Independent Test observations = "
    f"{len(y_test):,}"
)

print(
    f"✓ Prediction observations      = "
    f"{len(RF_FINAL_TEST_PREDICTIONS):,}"
)

print("✓ Prediction/target alignment confirmed")
print("✓ Nine-class taxonomy confirmed")
print("✓ Independent Test evaluation boundary confirmed")


# ---------------------------------------------------------------
# 3. PRIMARY AND SECONDARY PERFORMANCE METRICS
# ---------------------------------------------------------------

print("\n[PRIMARY AND SECONDARY PERFORMANCE METRICS]")

RF_FINAL_TEST_ACCURACY = accuracy_score(
    y_test,
    RF_FINAL_TEST_PREDICTIONS
)

RF_FINAL_TEST_BALANCED_ACCURACY = (
    balanced_accuracy_score(
        y_test,
        RF_FINAL_TEST_PREDICTIONS
    )
)

RF_FINAL_TEST_MACRO_F1 = f1_score(
    y_test,
    RF_FINAL_TEST_PREDICTIONS,
    average="macro",
    zero_division=0
)

RF_FINAL_TEST_MACRO_RECALL = recall_score(
    y_test,
    RF_FINAL_TEST_PREDICTIONS,
    average="macro",
    zero_division=0
)

RF_FINAL_TEST_WEIGHTED_F1 = f1_score(
    y_test,
    RF_FINAL_TEST_PREDICTIONS,
    average="weighted",
    zero_division=0
)

print(
    f"✓ Accuracy              : "
    f"{RF_FINAL_TEST_ACCURACY:.6f}"
)

print(
    f"✓ Balanced Accuracy     : "
    f"{RF_FINAL_TEST_BALANCED_ACCURACY:.6f}"
)

print(
    f"✓ Macro Recall          : "
    f"{RF_FINAL_TEST_MACRO_RECALL:.6f}"
)

print(
    f"✓ Macro F1              : "
    f"{RF_FINAL_TEST_MACRO_F1:.6f}"
)

print(
    f"✓ Weighted F1           : "
    f"{RF_FINAL_TEST_WEIGHTED_F1:.6f}"
)


# ---------------------------------------------------------------
# 4. PER-CLASS PERFORMANCE METRICS
# ---------------------------------------------------------------

print("\n[PER-CLASS PERFORMANCE METRICS]")

RF_FINAL_TEST_PRECISION_PER_CLASS, \
RF_FINAL_TEST_RECALL_PER_CLASS, \
RF_FINAL_TEST_F1_PER_CLASS, \
RF_FINAL_TEST_SUPPORT_PER_CLASS = (
    precision_recall_fscore_support(
        y_test,
        RF_FINAL_TEST_PREDICTIONS,
        labels=np.arange(9),
        zero_division=0
    )
)

RF_FINAL_TEST_CLASS_NAMES = [
    "BENIGN",
    "DDoS",
    "Port Scan",
    "Brute Force",
    "Bot",
    "Web Attack",
    "Infiltration",
    "DoS",
    "Heartbleed"
]

assert len(
    RF_FINAL_TEST_PRECISION_PER_CLASS
) == 9, (
    "Independent Test precision results do not contain "
    "all nine classes."
)

assert len(
    RF_FINAL_TEST_RECALL_PER_CLASS
) == 9, (
    "Independent Test recall results do not contain "
    "all nine classes."
)

assert len(
    RF_FINAL_TEST_F1_PER_CLASS
) == 9, (
    "Independent Test F1 results do not contain "
    "all nine classes."
)

assert len(
    RF_FINAL_TEST_SUPPORT_PER_CLASS
) == 9, (
    "Independent Test support results do not contain "
    "all nine classes."
)

for class_id, class_name in enumerate(
    RF_FINAL_TEST_CLASS_NAMES
):

    print(
        f"✓ {class_id}: {class_name:<15} "
        f"Precision={RF_FINAL_TEST_PRECISION_PER_CLASS[class_id]:.6f} | "
        f"Recall={RF_FINAL_TEST_RECALL_PER_CLASS[class_id]:.6f} | "
        f"F1={RF_FINAL_TEST_F1_PER_CLASS[class_id]:.6f} | "
        f"Support={RF_FINAL_TEST_SUPPORT_PER_CLASS[class_id]:,}"
    )


# ---------------------------------------------------------------
# 5. CONFUSION MATRIX
# ---------------------------------------------------------------

print("\n[CONFUSION MATRIX]")

RF_FINAL_TEST_CONFUSION_MATRIX = confusion_matrix(
    y_test,
    RF_FINAL_TEST_PREDICTIONS,
    labels=np.arange(9)
)

assert (
    RF_FINAL_TEST_CONFUSION_MATRIX.shape
    == (9, 9)
), (
    f"Unexpected Independent Test confusion-matrix shape: "
    f"{RF_FINAL_TEST_CONFUSION_MATRIX.shape}"
)

assert (
    RF_FINAL_TEST_CONFUSION_MATRIX.sum()
    == len(y_test)
), (
    "Independent Test confusion matrix does not account "
    "for all Test observations."
)

print("✓ 9 × 9 confusion matrix generated")
print("✓ All nine taxonomy classes included")
print(
    "✓ Confusion matrix total = "
    f"{RF_FINAL_TEST_CONFUSION_MATRIX.sum():,}"
)

print(
    "\nFinal RF Independent Test Confusion Matrix:"
)

print(
    RF_FINAL_TEST_CONFUSION_MATRIX
)


# ---------------------------------------------------------------
# 6. BENIGN FALSE-POSITIVE RATE
# ---------------------------------------------------------------

print("\n[BENIGN FALSE-POSITIVE RATE]")

RF_FINAL_TEST_BENIGN_TRUE_NEGATIVES = (
    RF_FINAL_TEST_CONFUSION_MATRIX[0, 0]
)

RF_FINAL_TEST_BENIGN_FALSE_POSITIVES = (
    RF_FINAL_TEST_CONFUSION_MATRIX[:, 0].sum()
    - RF_FINAL_TEST_BENIGN_TRUE_NEGATIVES
)

RF_FINAL_TEST_BENIGN_ACTUAL_NEGATIVES = (
    RF_FINAL_TEST_CONFUSION_MATRIX[1:, :].sum()
)

if (
    RF_FINAL_TEST_BENIGN_ACTUAL_NEGATIVES
    == 0
):

    RF_FINAL_TEST_BENIGN_FALSE_POSITIVE_RATE = 0.0

else:

    RF_FINAL_TEST_BENIGN_FALSE_POSITIVE_RATE = (
        RF_FINAL_TEST_BENIGN_FALSE_POSITIVES
        /
        RF_FINAL_TEST_BENIGN_ACTUAL_NEGATIVES
    )

print(
    f"✓ BENIGN true negatives       : "
    f"{RF_FINAL_TEST_BENIGN_TRUE_NEGATIVES:,}"
)

print(
    f"✓ BENIGN false positives      : "
    f"{RF_FINAL_TEST_BENIGN_FALSE_POSITIVES:,}"
)

print(
    f"✓ BENIGN actual negatives     : "
    f"{RF_FINAL_TEST_BENIGN_ACTUAL_NEGATIVES:,}"
)

print(
    f"✓ BENIGN false-positive rate  : "
    f"{RF_FINAL_TEST_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)


# ---------------------------------------------------------------
# 7. ATTACK FALSE NEGATIVES
# ---------------------------------------------------------------

print("\n[ATTACK FALSE NEGATIVES]")

RF_FINAL_TEST_ATTACK_FALSE_NEGATIVES = {}

for class_id in range(1, 9):

    false_negatives = (
        RF_FINAL_TEST_CONFUSION_MATRIX[
            class_id,
            :
        ].sum()
        -
        RF_FINAL_TEST_CONFUSION_MATRIX[
            class_id,
            class_id
        ]
    )

    RF_FINAL_TEST_ATTACK_FALSE_NEGATIVES[
        class_id
    ] = int(
        false_negatives
    )

    print(
        f"✓ Class {class_id}: "
        f"{RF_FINAL_TEST_CLASS_NAMES[class_id]:<15} "
        f"false negatives = {false_negatives:,}"
    )


RF_FINAL_TEST_TOTAL_ATTACK_FALSE_NEGATIVES = int(
    sum(
        RF_FINAL_TEST_ATTACK_FALSE_NEGATIVES.values()
    )
)

print(
    f"\n✓ Total attack false negatives : "
    f"{RF_FINAL_TEST_TOTAL_ATTACK_FALSE_NEGATIVES:,}"
)


# ---------------------------------------------------------------
# 8. SUPPLEMENTARY MULTICLASS ROC-AUC
# ---------------------------------------------------------------

print("\n[SUPPLEMENTARY MULTICLASS ROC-AUC]")

RF_FINAL_TEST_ROC_AUC = None

RF_FINAL_TEST_PROBABILITIES = None

try:

    RF_FINAL_TEST_PROBABILITIES = (
        RF_FINAL_MODEL.predict_proba(
            X_test_scaled
        )
    )

    assert (
        RF_FINAL_TEST_PROBABILITIES.shape
        == (
            len(y_test),
            len(EXPECTED_RF_CLASS_IDS)
        )
    ), (
        "Final RF Test probability shape does not match "
        "the nine-class Test contract."
    )

    RF_FINAL_TEST_ROC_AUC = roc_auc_score(
        y_test,
        RF_FINAL_TEST_PROBABILITIES,
        multi_class="ovr",
        average="macro",
        labels=np.arange(9)
    )

    print(
        f"✓ Macro ROC-AUC (OvR) : "
        f"{RF_FINAL_TEST_ROC_AUC:.6f}"
    )

except ValueError as error:

    print(
        "⚠ Macro ROC-AUC could not be calculated reliably: "
        f"{error}"
    )

finally:

    if (
        "RF_FINAL_TEST_PROBABILITIES"
        in globals()
    ):

        del RF_FINAL_TEST_PROBABILITIES

        import gc
        gc.collect()

        print(
            "✓ Temporary Test probability array released"
        )


# ---------------------------------------------------------------
# 9. FINAL TEST CLASSIFICATION REPORT OBJECT
# ---------------------------------------------------------------

print("\n[FINAL TEST CLASSIFICATION REPORT]")

RF_FINAL_TEST_CLASSIFICATION_REPORT = pd.DataFrame({

    "class_id":
        list(
            RF_CLASS_MAPPING.keys()
        ),

    "class_name":
        [
            RF_CLASS_MAPPING[class_id]
            for class_id in RF_CLASS_MAPPING.keys()
        ],

    "precision":
        RF_FINAL_TEST_PRECISION_PER_CLASS,

    "recall":
        RF_FINAL_TEST_RECALL_PER_CLASS,

    "f1":
        RF_FINAL_TEST_F1_PER_CLASS,

    "support":
        RF_FINAL_TEST_SUPPORT_PER_CLASS,

})

assert (
    len(RF_FINAL_TEST_CLASSIFICATION_REPORT)
    == 9
), (
    "Final Test classification report does not contain "
    "all nine taxonomy classes."
)

print(
    "✓ Nine-class Independent Test classification report generated"
)

print(
    "✓ Classification report follows the established RF schema"
)


# ---------------------------------------------------------------
# 10. INDEPENDENT TEST EVALUATION SUMMARY
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST EVALUATION SUMMARY]")

print(
    f"✓ Primary metric — Macro F1       : "
    f"{RF_FINAL_TEST_MACRO_F1:.6f}"
)

print(
    f"✓ Macro Recall                    : "
    f"{RF_FINAL_TEST_MACRO_RECALL:.6f}"
)

print(
    f"✓ Balanced Accuracy               : "
    f"{RF_FINAL_TEST_BALANCED_ACCURACY:.6f}"
)

print(
    f"✓ Weighted F1                     : "
    f"{RF_FINAL_TEST_WEIGHTED_F1:.6f}"
)

print(
    f"✓ Accuracy                        : "
    f"{RF_FINAL_TEST_ACCURACY:.6f}"
)

print(
    f"✓ BENIGN False-Positive Rate     : "
    f"{RF_FINAL_TEST_BENIGN_FALSE_POSITIVE_RATE:.6f}"
)

if RF_FINAL_TEST_ROC_AUC is not None:

    print(
        f"✓ Macro ROC-AUC (OvR)            : "
        f"{RF_FINAL_TEST_ROC_AUC:.6f}"
    )


# ---------------------------------------------------------------
# 11. INDEPENDENT TEST EVALUATION BOUNDARY
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST EVALUATION BOUNDARY]")

print(
    "✓ Evaluation performed only on the authorized "
    "Independent Test partition"
)

print(
    "✓ Final persisted RF-3 model used without modification"
)

print(
    "✓ Test targets used only for final performance evaluation"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No hyperparameter selection performed"
)

print(
    "✓ No strategy selection performed"
)

print(
    "✓ No Test data used to modify the model"
)

print(
    "✓ Temporary probability array released after ROC-AUC calculation"
)


# ---------------------------------------------------------------
# 12. SECTION 5.12.5 VALIDATION STATE
# ---------------------------------------------------------------

RF_5_12_5_VALIDATION = {

    "section_5_12_4_completed":
        all(
            RF_5_12_4_VALIDATION.values()
        ),

    "accuracy_calculated":
        np.isfinite(
            RF_FINAL_TEST_ACCURACY
        ),

    "balanced_accuracy_calculated":
        np.isfinite(
            RF_FINAL_TEST_BALANCED_ACCURACY
        ),

    "macro_recall_calculated":
        np.isfinite(
            RF_FINAL_TEST_MACRO_RECALL
        ),

    "macro_f1_calculated":
        np.isfinite(
            RF_FINAL_TEST_MACRO_F1
        ),

    "weighted_f1_calculated":
        np.isfinite(
            RF_FINAL_TEST_WEIGHTED_F1
        ),

    "per_class_metrics_complete":
        (
            len(
                RF_FINAL_TEST_PRECISION_PER_CLASS
            )
            == 9
            and
            len(
                RF_FINAL_TEST_RECALL_PER_CLASS
            )
            == 9
            and
            len(
                RF_FINAL_TEST_F1_PER_CLASS
            )
            == 9
            and
            len(
                RF_FINAL_TEST_SUPPORT_PER_CLASS
            )
            == 9
        ),

    "confusion_matrix_complete":
        (
            RF_FINAL_TEST_CONFUSION_MATRIX.shape
            == (9, 9)
            and
            RF_FINAL_TEST_CONFUSION_MATRIX.sum()
            == len(y_test)
        ),

    "benign_false_positive_rate_calculated":
        np.isfinite(
            RF_FINAL_TEST_BENIGN_FALSE_POSITIVE_RATE
        ),

    "attack_false_negatives_calculated":
        (
            len(
                RF_FINAL_TEST_ATTACK_FALSE_NEGATIVES
            )
            == 8
        ),

    "classification_report_complete":
        len(
            RF_FINAL_TEST_CLASSIFICATION_REPORT
        )
        == 9,

    "roc_auc_calculated":
        (
            RF_FINAL_TEST_ROC_AUC is not None
            and
            np.isfinite(
                RF_FINAL_TEST_ROC_AUC
            )
        ),

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_strategy_selection":
        True,
}


assert all(
    RF_5_12_5_VALIDATION.values()
), (
    "Section 5.12.5 Independent Test performance "
    "evaluation validation is incomplete."
)


# ---------------------------------------------------------------
# 13. FINAL 5.12.5 READINESS GATE
# ---------------------------------------------------------------

print("\n[5.12.5 FINAL EVALUATION READINESS GATE]")

print(
    "✓ Accuracy calculated"
)

print(
    "✓ Balanced Accuracy calculated"
)

print(
    "✓ Macro Recall calculated"
)

print(
    "✓ Macro F1 calculated"
)

print(
    "✓ Weighted F1 calculated"
)

print(
    "✓ All nine per-class metric rows calculated"
)

print(
    "✓ 9 × 9 confusion matrix calculated"
)

print(
    "✓ BENIGN false-positive rate calculated"
)

print(
    "✓ Attack false negatives calculated"
)

print(
    "✓ Independent Test classification report generated"
)

if RF_FINAL_TEST_ROC_AUC is not None:

    print(
        "✓ Supplementary Macro ROC-AUC (OvR) calculated"
    )

print(
    "✓ No model fitting performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No strategy selection performed"
)

print(
    "✓ Independent Test performance evaluation completed"
)


print("\n" + "=" * 72)

print(
    "5.12.5 — INDEPENDENT TEST PERFORMANCE "
    "EVALUATION PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.12.6 — INDEPENDENT TEST RESOURCE "
    "ANALYSIS AND EVALUATION ARTIFACT PERSISTENCE"
)

print("=" * 72)

========================================================================
5.12.5 — INDEPENDENT TEST PERFORMANCE EVALUATION
========================================================================

[PREVIOUS-SUBSECTION COMPLETION BOUNDARY]
✓ Section 5.12.4 prediction validation completed
✓ Persisted final RF-3 model remains available
✓ Independent Test targets remain available
✓ Independent Test predictions remain available

[INDEPENDENT TEST EVALUATION BOUNDARY]
✓ Independent Test observations = 565,510
✓ Prediction observations      = 565,510
✓ Prediction/target alignment confirmed
✓ Nine-class taxonomy confirmed
✓ Independent Test evaluation boundary confirmed

[PRIMARY AND SECONDARY PERFORMANCE METRICS]
✓ Accuracy              : 0.994253
✓ Balanced Accuracy     : 0.886771
✓ Macro Recall          : 0.886771
✓ Macro F1              : 0.907232
✓ Weighted F1           : 0.994217

[PER-CLASS PERFORMANCE METRICS]
✓ 0: BENIGN          Precision=0.994317 | Recall=0.998619 | F1=0.996464 | Support=455,399
✓ 1: DDoS            Precision=0.999687 | Recall=0.999492 | F1=0.999590 | Support=25,601
✓ 2: Port Scan       Precision=0.993975 | Recall=0.996682 | F1=0.995327 | Support=31,946
✓ 3: Brute Force     Precision=0.990421 | Recall=0.976208 | F1=0.983264 | Support=2,648
✓ 4: Bot             Precision=0.562802 | Recall=0.583960 | F1=0.573186 | Support=399
✓ 5: Web Attack      Precision=0.981132 | Recall=0.971963 | F1=0.976526 | Support=428
✓ 6: Infiltration    Precision=1.000000 | Recall=0.500000 | F1=0.666667 | Support=8
✓ 7: DoS             Precision=0.994985 | Recall=0.954014 | F1=0.974069 | Support=49,080
✓ 8: Heartbleed      Precision=1.000000 | Recall=1.000000 | F1=1.000000 | Support=1

[CONFUSION MATRIX]
✓ 9 × 9 confusion matrix generated
✓ All nine taxonomy classes included
✓ Confusion matrix total = 565,510

Final RF Independent Test Confusion Matrix:
[[454770      8    191     25    181      0      0    224      0]
 [    13  25588      0      0      0      0      0      0      0]
 [    97      0  31840      0      0      3      0      6      0]
 [    63      0      0   2585      0      0      0      0      0]
 [   166      0      0      0    233      0      0      0      0]
 [     6      0      0      0      0    416      0      6      0]
 [     4      0      0      0      0      0      4      0      0]
 [  2250      0      2      0      0      5      0  46823      0]
 [     0      0      0      0      0      0      0      0      1]]

[BENIGN FALSE-POSITIVE RATE]
✓ BENIGN true negatives       : 454,770
✓ BENIGN false positives      : 2,599
✓ BENIGN actual negatives     : 110,111
✓ BENIGN false-positive rate  : 0.023603

[ATTACK FALSE NEGATIVES]
✓ Class 1: DDoS            false negatives = 13
✓ Class 2: Port Scan       false negatives = 106
✓ Class 3: Brute Force     false negatives = 63
✓ Class 4: Bot             false negatives = 166
✓ Class 5: Web Attack      false negatives = 12
✓ Class 6: Infiltration    false negatives = 4
✓ Class 7: DoS             false negatives = 2,257
✓ Class 8: Heartbleed      false negatives = 0

✓ Total attack false negatives : 2,621

[SUPPLEMENTARY MULTICLASS ROC-AUC]
✓ Macro ROC-AUC (OvR) : 0.990484
✓ Temporary Test probability array released

[FINAL TEST CLASSIFICATION REPORT]
✓ Nine-class Independent Test classification report generated
✓ Classification report follows the established RF schema

[INDEPENDENT TEST EVALUATION SUMMARY]
✓ Primary metric — Macro F1       : 0.907232
✓ Macro Recall                    : 0.886771
✓ Balanced Accuracy               : 0.886771
✓ Weighted F1                     : 0.994217
✓ Accuracy                        : 0.994253
✓ BENIGN False-Positive Rate     : 0.023603
✓ Macro ROC-AUC (OvR)            : 0.990484

[INDEPENDENT TEST EVALUATION BOUNDARY]
✓ Evaluation performed only on the authorized Independent Test partition
✓ Final persisted RF-3 model used without modification
✓ Test targets used only for final performance evaluation
✓ No model fitting performed
✓ No resampling performed
✓ No hyperparameter selection performed
✓ No strategy selection performed
✓ No Test data used to modify the model
✓ Temporary probability array released after ROC-AUC calculation

[5.12.5 FINAL EVALUATION READINESS GATE]
✓ Accuracy calculated
✓ Balanced Accuracy calculated
✓ Macro Recall calculated
✓ Macro F1 calculated
✓ Weighted F1 calculated
✓ All nine per-class metric rows calculated
✓ 9 × 9 confusion matrix calculated
✓ BENIGN false-positive rate calculated
✓ Attack false negatives calculated
✓ Independent Test classification report generated
✓ Supplementary Macro ROC-AUC (OvR) calculated
✓ No model fitting performed
✓ No resampling performed
✓ No strategy selection performed
✓ Independent Test performance evaluation completed

========================================================================
5.12.5 — INDEPENDENT TEST PERFORMANCE EVALUATION PASSED
========================================================================

READY FOR 5.12.6 — INDEPENDENT TEST RESOURCE ANALYSIS AND EVALUATION ARTIFACT PERSISTENCE
========================================================================

## 5.13 — Random Forest Error Analysis and Interpretation

This section analyzes the completed Independent Test evaluation of the selected
final Random Forest model and interprets its class-wise detection behavior.

The analysis uses the persisted Independent Test evaluation artifacts and the
persisted final Random Forest model. The Independent Test partition is not
re-evaluated and no new predictions are generated.

The analysis focuses on:

- class-wise performance and error behavior,
- confusion patterns,
- minority-class detection behavior,
- BENIGN false positives,
- attack false negatives, and
- final Random Forest feature importance.

All analysis remains downstream of the completed Random Forest model-selection
and Independent Test evaluation stages. No model fitting, resampling,
hyperparameter selection, strategy selection, or additional Test inference is
performed in this section.

## 5.13 — Random Forest Error Analysis and Interpretation

This section analyzes the completed Independent Test evaluation of the selected
final Random Forest model and interprets its class-wise detection behavior.

The analysis uses the persisted Independent Test evaluation artifacts and the
persisted final Random Forest model. The Independent Test partition is not
re-evaluated and no new predictions are generated.

The analysis focuses on:

- class-wise performance and error behavior,
- confusion patterns,
- minority-class detection behavior,
- BENIGN false positives,
- attack false negatives, and
- final Random Forest feature importance.

All analysis remains downstream of the completed Random Forest model-selection
and Independent Test evaluation stages. No model fitting, resampling,
hyperparameter selection, strategy selection, or additional Test inference is
performed in this section.

## 5.13.1 — Error Analysis Definition and Boundary Validation

This subsection establishes the boundary for Random Forest error analysis and
interpretation.

The analysis is based exclusively on the persisted outputs of the completed
Random Forest development and Independent Test evaluation stages. The
authoritative RF feature order, nine-class taxonomy, final-model artifact,
Independent Test evaluation artifacts, and interpretation output directory are
validated before analysis begins.

The Independent Test evaluation artifacts are treated as read-only analytical
inputs:

1. `test_results.csv`
2. `confusion_matrix.csv`
3. `classification_report.csv`

The persisted final Random Forest model is also treated as read-only and will
only be used later in this section for extraction of its fitted feature
importance values.

No Independent Test features or targets are loaded in this subsection.
No additional Test predictions or metrics are generated.

No model fitting, resampling, hyperparameter selection, strategy selection, or
modification of the persisted evaluation artifacts is permitted.

Successful completion establishes the boundary for the subsequent class-wise
error, confusion-pattern, minority-class, and feature-importance analyses.

In [ ]:
# ================================================================
# 5.13.1 — ERROR ANALYSIS DEFINITION AND BOUNDARY VALIDATION
# ================================================================

import json
import pandas as pd


print("=" * 72)
print("5.13.1 — ERROR ANALYSIS DEFINITION AND BOUNDARY VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. PRECEDING RF CONFIGURATION COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[PRECEDING RF CONFIGURATION COMPLETION BOUNDARY]")

assert "RF_FEATURE_ORDER" in globals(), (
    "Authoritative RF feature order is unavailable."
)

assert "RF_CLASS_MAPPING" in globals(), (
    "Authoritative RF class taxonomy is unavailable."
)

assert "EXPECTED_RF_CLASS_IDS" in globals(), (
    "Expected RF class IDs are unavailable."
)

assert "EXPECTED_MODEL_READY_FEATURE_COUNT" in globals(), (
    "Expected RF model-ready feature count is unavailable."
)

assert "EXPECTED_MODEL_READY_SHAPES" in globals(), (
    "Expected RF model-ready partition shapes are unavailable."
)

assert "RF_TEST_PROTECTION_CONTRACT" in globals(), (
    "Independent Test protection contract is unavailable."
)

assert "RF_EXPERIMENT_ARTIFACTS" in globals(), (
    "Established RF experiment artifact mapping is unavailable."
)

assert "RF_INTERPRETATION_DIR" in globals(), (
    "RF interpretation directory is unavailable."
)

print("✓ Authoritative RF feature order available")
print("✓ Authoritative nine-class taxonomy available")
print("✓ Expected RF class IDs available")
print("✓ Model-ready feature contract available")
print("✓ Independent Test protection contract available")
print("✓ Established RF artifact mapping available")
print("✓ RF interpretation directory available")


# ---------------------------------------------------------------
# 2. RF FEATURE-SPACE CONTRACT
# ---------------------------------------------------------------

print("\n[RF FEATURE-SPACE CONTRACT]")

assert (
    len(RF_FEATURE_ORDER)
    == EXPECTED_MODEL_READY_FEATURE_COUNT
), (
    "RF feature order does not contain the expected "
    "32 model-ready features."
)

assert (
    len(set(RF_FEATURE_ORDER))
    == EXPECTED_MODEL_READY_FEATURE_COUNT
), (
    "RF feature order contains duplicate feature names."
)

assert all(
    isinstance(feature_name, str)
    and feature_name.strip()
    for feature_name in RF_FEATURE_ORDER
), (
    "RF feature order contains invalid feature names."
)

print(
    f"✓ RF feature count = "
    f"{len(RF_FEATURE_ORDER)}"
)

print("✓ RF feature order is unique and frozen")
print("✓ RF feature names are valid")


# ---------------------------------------------------------------
# 3. RF CLASS-TAXONOMY CONTRACT
# ---------------------------------------------------------------

print("\n[RF CLASS-TAXONOMY CONTRACT]")

assert (
    len(RF_CLASS_MAPPING)
    == 9
), (
    "RF taxonomy must contain exactly nine classes."
)

assert (
    list(RF_CLASS_MAPPING.keys())
    == list(range(9))
), (
    "RF class IDs must remain consecutive integers "
    "from 0 through 8."
)

assert np.array_equal(
    EXPECTED_RF_CLASS_IDS,
    np.arange(9, dtype=np.int64)
), (
    "Expected RF class IDs do not match the established "
    "nine-class taxonomy."
)

for class_id, class_name in RF_CLASS_MAPPING.items():

    print(
        f"✓ {class_id}: {class_name}"
    )

print("✓ Nine-class RF taxonomy remains frozen")


# ---------------------------------------------------------------
# 4. INDEPENDENT TEST PROTECTION CONTRACT
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION CONTRACT]")

for protection_name, protection_status in (
    RF_TEST_PROTECTION_CONTRACT.items()
):

    assert protection_status, (
        "Independent Test protection contract failed: "
        f"{protection_name}"
    )

    print(
        f"✓ {protection_name}: "
        f"{protection_status}"
    )

print(
    "✓ Independent Test protection contract remains valid"
)


# ---------------------------------------------------------------
# 5. PERSISTED FINAL-MODEL ARTIFACT BOUNDARY
# ---------------------------------------------------------------

print("\n[PERSISTED FINAL-MODEL ARTIFACT BOUNDARY]")

assert (
    "final_model"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Final Random Forest model artifact is not configured."
)

assert (
    "final_model_metadata"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Final Random Forest metadata artifact is not configured."
)

final_model_path = (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model"
    ]
)

final_model_metadata_path = (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model_metadata"
    ]
)

assert final_model_path.is_file(), (
    "Persisted final Random Forest model artifact "
    "was not found."
)

assert (
    final_model_path.stat().st_size
    > 0
), (
    "Persisted final Random Forest model artifact "
    "is empty."
)

assert final_model_metadata_path.is_file(), (
    "Persisted final Random Forest metadata artifact "
    "was not found."
)

assert (
    final_model_metadata_path.stat().st_size
    > 0
), (
    "Persisted final Random Forest metadata artifact "
    "is empty."
)

print(
    f"✓ Final model artifact : "
    f"{final_model_path}"
)

print(
    f"✓ Final metadata       : "
    f"{final_model_metadata_path}"
)

print("✓ Persisted final RF artifacts are available")


# ---------------------------------------------------------------
# 6. FINAL RF METADATA BOUNDARY
# ---------------------------------------------------------------

print("\n[FINAL RF METADATA BOUNDARY]")

with open(
    final_model_metadata_path,
    "r",
    encoding="utf-8"
) as file:

    RF_FINAL_MODEL_METADATA_CHECK = json.load(
        file
    )

assert (
    RF_FINAL_MODEL_METADATA_CHECK[
        "strategy_id"
    ]
    == "RF-3"
), (
    "Persisted final model was not trained using "
    "the selected RF-3 strategy."
)

assert (
    RF_FINAL_MODEL_METADATA_CHECK[
        "strategy_name"
    ]
    == "Controlled Random Oversampling"
), (
    "Persisted final model strategy name does not "
    "match the selected RF-3 strategy."
)

assert (
    RF_FINAL_MODEL_METADATA_CHECK[
        "training_partition"
    ]
    == "Training"
), (
    "Persisted final model does not identify Training "
    "as its fitting partition."
)

assert (
    RF_FINAL_MODEL_METADATA_CHECK[
        "validation_used_for_fitting"
    ]
    is False
), (
    "Validation was unexpectedly recorded as being "
    "used for final model fitting."
)

assert (
    RF_FINAL_MODEL_METADATA_CHECK[
        "independent_test_used"
    ]
    is False
), (
    "Independent Test was unexpectedly recorded as "
    "being used during final model fitting."
)

assert (
    RF_FINAL_MODEL_METADATA_CHECK[
        "final_model"
    ]
    is True
), (
    "Persisted model is not marked as the final model."
)

assert (
    RF_FINAL_MODEL_METADATA_CHECK[
        "persistence_completed"
    ]
    is True
), (
    "Persisted final-model metadata does not indicate "
    "completed persistence."
)

print("✓ Persisted strategy = RF-3")
print(
    "✓ Persisted strategy name = "
    "Controlled Random Oversampling"
)
print("✓ Fitting partition = Training")
print("✓ Validation excluded from fitting")
print("✓ Independent Test excluded from fitting")
print("✓ Final-model flag = True")
print("✓ Persistence status = True")


# ---------------------------------------------------------------
# 7. INDEPENDENT TEST EVALUATION ARTIFACT BOUNDARY
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST EVALUATION ARTIFACT BOUNDARY]")

assert (
    "test_results"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Independent Test results artifact is not configured."
)

assert (
    "confusion_matrix"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Independent Test confusion-matrix artifact "
    "is not configured."
)

assert (
    "classification_report"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Independent Test classification-report artifact "
    "is not configured."
)

RF_5_13_TEST_ARTIFACT_PATHS = {

    "test_results":
        RF_EXPERIMENT_ARTIFACTS[
            "test_results"
        ],

    "confusion_matrix":
        RF_EXPERIMENT_ARTIFACTS[
            "confusion_matrix"
        ],

    "classification_report":
        RF_EXPERIMENT_ARTIFACTS[
            "classification_report"
        ],
}


for artifact_name, artifact_path in (
    RF_5_13_TEST_ARTIFACT_PATHS.items()
):

    assert artifact_path.is_file(), (
        f"Required persisted Test artifact is unavailable: "
        f"{artifact_path}"
    )

    assert (
        artifact_path.stat().st_size
        > 0
    ), (
        f"Required persisted Test artifact is empty: "
        f"{artifact_path}"
    )

    print(
        f"✓ {artifact_name:<22} : "
        f"{artifact_path}"
    )

print(
    "✓ All three persisted Independent Test "
    "evaluation artifacts are available"
)


# ---------------------------------------------------------------
# 8. TEST RESULTS ARTIFACT BASIC VALIDATION
# ---------------------------------------------------------------

print("\n[TEST RESULTS ARTIFACT BASIC VALIDATION]")

RF_5_13_TEST_RESULTS_COLUMNS = set(
    pd.read_csv(
        RF_5_13_TEST_ARTIFACT_PATHS[
            "test_results"
        ],
        nrows=0
    ).columns
)

RF_5_13_REQUIRED_TEST_RESULT_COLUMNS = {

    "strategy_id",
    "strategy_name",
    "partition",
    "test_observations",
    "accuracy",
    "balanced_accuracy",
    "macro_recall",
    "macro_f1",
    "weighted_f1",
    "benign_false_positive_rate",
    "attack_false_negatives",
    "macro_roc_auc_ovr",
    "inference_time_seconds",
    "inference_throughput_samples_per_second",
}


assert (
    RF_5_13_REQUIRED_TEST_RESULT_COLUMNS
    .issubset(
        RF_5_13_TEST_RESULTS_COLUMNS
    )
), (
    "Persisted test_results.csv does not contain "
    "the established Independent Test result fields."
)

print(
    "✓ Persisted Test results contain the established "
    "evaluation fields"
)


# ---------------------------------------------------------------
# 9. ERROR-ANALYSIS OPERATION BOUNDARY
# ---------------------------------------------------------------

print("\n[ERROR-ANALYSIS OPERATION BOUNDARY]")

print(
    "✓ No model fitting will be performed"
)

print(
    "✓ No resampling will be performed"
)

print(
    "✓ No hyperparameter selection will be performed"
)

print(
    "✓ No RF strategy selection will be performed"
)

print(
    "✓ No Independent Test inference will be performed"
)

print(
    "✓ No Independent Test feature/target arrays "
    "will be loaded in 5.13.1"
)

print(
    "✓ Persisted evaluation artifacts will be treated "
    "as read-only analytical inputs"
)

print(
    "✓ Persisted final RF model will remain read-only"
)


# ---------------------------------------------------------------
# 10. SECTION 5.13.1 VALIDATION STATE
# ---------------------------------------------------------------

RF_5_13_1_VALIDATION = {

    "rf_feature_contract_valid":
        (
            len(RF_FEATURE_ORDER)
            == EXPECTED_MODEL_READY_FEATURE_COUNT
            and
            len(set(RF_FEATURE_ORDER))
            == EXPECTED_MODEL_READY_FEATURE_COUNT
        ),

    "rf_taxonomy_contract_valid":
        (
            len(RF_CLASS_MAPPING)
            == 9
            and
            list(RF_CLASS_MAPPING.keys())
            == list(range(9))
        ),

    "test_protection_contract_valid":
        all(
            RF_TEST_PROTECTION_CONTRACT.values()
        ),

    "final_model_artifact_available":
        (
            final_model_path.is_file()
            and
            final_model_path.stat().st_size > 0
        ),

    "final_model_metadata_available":
        (
            final_model_metadata_path.is_file()
            and
            final_model_metadata_path.stat().st_size > 0
        ),

    "final_model_metadata_valid":
        (
            RF_FINAL_MODEL_METADATA_CHECK[
                "strategy_id"
            ]
            == "RF-3"
            and
            RF_FINAL_MODEL_METADATA_CHECK[
                "training_partition"
            ]
            == "Training"
            and
            RF_FINAL_MODEL_METADATA_CHECK[
                "validation_used_for_fitting"
            ] is False
            and
            RF_FINAL_MODEL_METADATA_CHECK[
                "independent_test_used"
            ] is False
            and
            RF_FINAL_MODEL_METADATA_CHECK[
                "final_model"
            ] is True
            and
            RF_FINAL_MODEL_METADATA_CHECK[
                "persistence_completed"
            ] is True
        ),

    "test_evaluation_artifacts_available":
        all(
            artifact_path.is_file()
            and
            artifact_path.stat().st_size > 0
            for artifact_path
            in RF_5_13_TEST_ARTIFACT_PATHS.values()
        ),

    "test_results_schema_valid":
        RF_5_13_REQUIRED_TEST_RESULT_COLUMNS.issubset(
            RF_5_13_TEST_RESULTS_COLUMNS
        ),

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_test_inference":
        True,

    "no_strategy_selection":
        True,
}


assert all(
    RF_5_13_1_VALIDATION.values()
), (
    "Section 5.13.1 error-analysis boundary validation "
    "is incomplete."
)


# ---------------------------------------------------------------
# 11. FINAL 5.13.1 READINESS GATE
# ---------------------------------------------------------------

print("\n[5.13.1 ERROR ANALYSIS READINESS GATE]")

print(
    "✓ RF feature-space contract validated"
)

print(
    "✓ Nine-class taxonomy validated"
)

print(
    "✓ Independent Test protection contract validated"
)

print(
    "✓ Persisted final RF-3 model artifact validated"
)

print(
    "✓ Persisted final RF-3 metadata validated"
)

print(
    "✓ test_results.csv available"
)

print(
    "✓ confusion_matrix.csv available"
)

print(
    "✓ classification_report.csv available"
)

print(
    "✓ No Test arrays loaded"
)

print(
    "✓ No Test inference performed"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No strategy selection performed"
)

print(
    "✓ Error-analysis boundary established"
)


print("\n" + "=" * 72)

print(
    "5.13.1 — ERROR ANALYSIS DEFINITION "
    "AND BOUNDARY VALIDATION PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.13.2 — PERSISTED INDEPENDENT "
    "TEST EVALUATION LOADING"
)

print("=" * 72)

========================================================================
5.13.1 — ERROR ANALYSIS DEFINITION AND BOUNDARY VALIDATION
========================================================================

[PRECEDING RF CONFIGURATION COMPLETION BOUNDARY]
✓ Authoritative RF feature order available
✓ Authoritative nine-class taxonomy available
✓ Expected RF class IDs available
✓ Model-ready feature contract available
✓ Independent Test protection contract available
✓ Established RF artifact mapping available
✓ RF interpretation directory available

[RF FEATURE-SPACE CONTRACT]
✓ RF feature count = 32
✓ RF feature order is unique and frozen
✓ RF feature names are valid

[RF CLASS-TAXONOMY CONTRACT]
✓ 0: BENIGN
✓ 1: DDoS
✓ 2: Port Scan
✓ 3: Brute Force
✓ 4: Bot
✓ 5: Web Attack
✓ 6: Infiltration
✓ 7: DoS
✓ 8: Heartbleed
✓ Nine-class RF taxonomy remains frozen

[INDEPENDENT TEST PROTECTION CONTRACT]
✓ feature_selection_excluded: True
✓ scaler_fitting_excluded: True
✓ imbalance_strategy_selection_excluded: True
✓ model_fitting_excluded: True
✓ hyperparameter_selection_excluded: True
✓ intermediate_evaluation_excluded: True
✓ final_evaluation_allowed: True
✓ Independent Test protection contract remains valid

[PERSISTED FINAL-MODEL ARTIFACT BOUNDARY]
✓ Final model artifact : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models/random_forest/final_random_forest.joblib
✓ Final metadata       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/final_model/rf_final_model_metadata.json
✓ Persisted final RF artifacts are available

[FINAL RF METADATA BOUNDARY]
✓ Persisted strategy = RF-3
✓ Persisted strategy name = Controlled Random Oversampling
✓ Fitting partition = Training
✓ Validation excluded from fitting
✓ Independent Test excluded from fitting
✓ Final-model flag = True
✓ Persistence status = True

[INDEPENDENT TEST EVALUATION ARTIFACT BOUNDARY]
✓ test_results           : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/test_results.csv
✓ confusion_matrix       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/confusion_matrix.csv
✓ classification_report  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/classification_report.csv
✓ All three persisted Independent Test evaluation artifacts are available

[TEST RESULTS ARTIFACT BASIC VALIDATION]
✓ Persisted Test results contain the established evaluation fields

[ERROR-ANALYSIS OPERATION BOUNDARY]
✓ No model fitting will be performed
✓ No resampling will be performed
✓ No hyperparameter selection will be performed
✓ No RF strategy selection will be performed
✓ No Independent Test inference will be performed
✓ No Independent Test feature/target arrays will be loaded in 5.13.1
✓ Persisted evaluation artifacts will be treated as read-only analytical inputs
✓ Persisted final RF model will remain read-only

[5.13.1 ERROR ANALYSIS READINESS GATE]
✓ RF feature-space contract validated
✓ Nine-class taxonomy validated
✓ Independent Test protection contract validated
✓ Persisted final RF-3 model artifact validated
✓ Persisted final RF-3 metadata validated
✓ test_results.csv available
✓ confusion_matrix.csv available
✓ classification_report.csv available
✓ No Test arrays loaded
✓ No Test inference performed
✓ No model fitting performed
✓ No resampling performed
✓ No strategy selection performed
✓ Error-analysis boundary established

========================================================================
5.13.1 — ERROR ANALYSIS DEFINITION AND BOUNDARY VALIDATION PASSED
========================================================================

READY FOR 5.13.2 — PERSISTED INDEPENDENT TEST EVALUATION LOADING
========================================================================

## 5.13.2 — Persisted Independent Test Evaluation Loading

This subsection loads the three established Independent Test evaluation
artifacts persisted during the completed Random Forest evaluation stage:

1. `test_results.csv`
2. `confusion_matrix.csv`
3. `classification_report.csv`

The persisted artifacts are loaded as read-only analytical inputs for the
subsequent error-analysis stages.

The loaded Test results are validated against the established final RF-3
evaluation contract. The confusion matrix is validated for the complete
nine-class taxonomy and the full Independent Test observation count. The
classification report is validated for all nine classes and the established
per-class metric schema.

No Independent Test feature or target arrays are loaded, no new predictions
are generated, and no metrics are recalculated from the raw Test partition.

No model fitting, resampling, hyperparameter selection, strategy selection, or
modification of the persisted evaluation artifacts is performed.

Successful completion establishes the persisted Independent Test evaluation
objects required for class-wise performance, confusion-pattern, and
minority-class analysis.

In [ ]:
# ================================================================
# 5.13.2 — PERSISTED INDEPENDENT TEST EVALUATION LOADING
# ================================================================

import numpy as np
import pandas as pd


print("=" * 72)
print("5.13.2 — PERSISTED INDEPENDENT TEST EVALUATION LOADING")
print("=" * 72)


# ---------------------------------------------------------------
# 1. PREVIOUS-SUBSECTION COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[PREVIOUS-SUBSECTION COMPLETION BOUNDARY]")

assert "RF_5_13_1_VALIDATION" in globals(), (
    "Section 5.13.1 validation state is unavailable."
)

assert all(
    RF_5_13_1_VALIDATION.values()
), (
    "Section 5.13.1 validation is incomplete."
)

assert "RF_5_13_TEST_ARTIFACT_PATHS" in globals(), (
    "Established 5.13 Test artifact paths are unavailable."
)

print("✓ Section 5.13.1 validation completed")
print("✓ Persisted Test artifact paths remain available")
print("✓ Error-analysis boundary remains valid")


# ---------------------------------------------------------------
# 2. PERSISTED TEST EVALUATION ARTIFACT LOADING
# ---------------------------------------------------------------

print("\n[PERSISTED TEST EVALUATION ARTIFACT LOADING]")

RF_5_13_TEST_RESULTS = pd.read_csv(
    RF_5_13_TEST_ARTIFACT_PATHS["test_results"]
)

RF_5_13_CONFUSION_MATRIX = pd.read_csv(
    RF_5_13_TEST_ARTIFACT_PATHS["confusion_matrix"],
    index_col=0
)

RF_5_13_CLASSIFICATION_REPORT = pd.read_csv(
    RF_5_13_TEST_ARTIFACT_PATHS["classification_report"]
)

assert not RF_5_13_TEST_RESULTS.empty
assert not RF_5_13_CONFUSION_MATRIX.empty
assert not RF_5_13_CLASSIFICATION_REPORT.empty

print("✓ test_results.csv loaded")
print("✓ confusion_matrix.csv loaded")
print("✓ classification_report.csv loaded")


# ---------------------------------------------------------------
# 3. TEST RESULTS STRUCTURE VALIDATION
# ---------------------------------------------------------------

print("\n[TEST RESULTS STRUCTURE VALIDATION]")

RF_5_13_REQUIRED_TEST_RESULT_COLUMNS = {
    "strategy_id",
    "strategy_name",
    "partition",
    "test_observations",
    "accuracy",
    "balanced_accuracy",
    "macro_recall",
    "macro_f1",
    "weighted_f1",
    "benign_false_positive_rate",
    "attack_false_negatives",
    "macro_roc_auc_ovr",
    "inference_time_seconds",
    "inference_throughput_samples_per_second",
}

assert RF_5_13_REQUIRED_TEST_RESULT_COLUMNS.issubset(
    RF_5_13_TEST_RESULTS.columns
), (
    "Persisted test_results.csv does not contain "
    "the established Independent Test result schema."
)

assert len(RF_5_13_TEST_RESULTS) == 1, (
    "Persisted test_results.csv must contain exactly "
    "one aggregate Independent Test evaluation row."
)

print(
    f"✓ Test results rows = "
    f"{len(RF_5_13_TEST_RESULTS)}"
)

print("✓ Established Test-results schema validated")


# ---------------------------------------------------------------
# 4. FINAL RF-3 TEST RESULT VALIDATION
# ---------------------------------------------------------------

print("\n[FINAL RF-3 TEST RESULT VALIDATION]")

RF_5_13_TEST_RESULT_ROW = RF_5_13_TEST_RESULTS.iloc[0]

assert (
    RF_5_13_TEST_RESULT_ROW["strategy_id"]
    == "RF-3"
)

assert (
    RF_5_13_TEST_RESULT_ROW["strategy_name"]
    == "Controlled Random Oversampling"
)

assert (
    str(
        RF_5_13_TEST_RESULT_ROW["partition"]
    ).strip()
    == "Independent Test"
)

assert (
    int(
        RF_5_13_TEST_RESULT_ROW["test_observations"]
    )
    == EXPECTED_RF_PARTITION_ROWS["Test"]
)

print("✓ Evaluated strategy = RF-3")
print(
    "✓ Strategy name = Controlled Random Oversampling"
)
print("✓ Evaluation partition = Independent Test")
print(
    f"✓ Test observations = "
    f"{int(RF_5_13_TEST_RESULT_ROW['test_observations']):,}"
)
print("✓ Persisted aggregate Test result is valid")


# ---------------------------------------------------------------
# 5. TEST RESULT METRIC INTEGRITY
# ---------------------------------------------------------------

print("\n[TEST RESULT METRIC INTEGRITY]")

RF_5_13_TEST_NUMERIC_COLUMNS = [
    "accuracy",
    "balanced_accuracy",
    "macro_recall",
    "macro_f1",
    "weighted_f1",
    "benign_false_positive_rate",
    "attack_false_negatives",
    "macro_roc_auc_ovr",
    "inference_time_seconds",
    "inference_throughput_samples_per_second",
]

for column_name in RF_5_13_TEST_NUMERIC_COLUMNS:

    assert np.isfinite(
        float(
            RF_5_13_TEST_RESULT_ROW[column_name]
        )
    ), (
        f"Persisted Test result contains a non-finite "
        f"value in '{column_name}'."
    )

print("✓ All persisted Test-result metrics are finite")


assert 0.0 <= float(
    RF_5_13_TEST_RESULT_ROW["accuracy"]
) <= 1.0

assert 0.0 <= float(
    RF_5_13_TEST_RESULT_ROW["balanced_accuracy"]
) <= 1.0

assert 0.0 <= float(
    RF_5_13_TEST_RESULT_ROW["macro_recall"]
) <= 1.0

assert 0.0 <= float(
    RF_5_13_TEST_RESULT_ROW["macro_f1"]
) <= 1.0

assert 0.0 <= float(
    RF_5_13_TEST_RESULT_ROW["weighted_f1"]
) <= 1.0

assert 0.0 <= float(
    RF_5_13_TEST_RESULT_ROW["benign_false_positive_rate"]
) <= 1.0

assert float(
    RF_5_13_TEST_RESULT_ROW["attack_false_negatives"]
) >= 0

assert 0.0 <= float(
    RF_5_13_TEST_RESULT_ROW["macro_roc_auc_ovr"]
) <= 1.0

assert float(
    RF_5_13_TEST_RESULT_ROW["inference_time_seconds"]
) > 0

assert float(
    RF_5_13_TEST_RESULT_ROW[
        "inference_throughput_samples_per_second"
    ]
) > 0

print("✓ Aggregate Test metric ranges validated")


# ---------------------------------------------------------------
# 6. CONFUSION MATRIX STRUCTURE VALIDATION
# ---------------------------------------------------------------

print("\n[CONFUSION MATRIX STRUCTURE VALIDATION]")

RF_5_13_EXPECTED_CLASS_NAMES = [
    RF_CLASS_MAPPING[class_id]
    for class_id in EXPECTED_RF_CLASS_IDS
]

assert (
    RF_5_13_CONFUSION_MATRIX.shape
    == (9, 9)
), (
    "Persisted confusion matrix is not 9 × 9."
)

assert (
    RF_5_13_CONFUSION_MATRIX.columns.tolist()
    == RF_5_13_EXPECTED_CLASS_NAMES
), (
    "Persisted confusion matrix columns do not match "
    "the established nine-class ordering."
)

assert (
    RF_5_13_CONFUSION_MATRIX.index.tolist()
    == RF_5_13_EXPECTED_CLASS_NAMES
), (
    "Persisted confusion matrix rows do not match "
    "the established nine-class ordering."
)

print(
    f"✓ Confusion matrix shape = "
    f"{RF_5_13_CONFUSION_MATRIX.shape}"
)

print("✓ Confusion matrix columns match RF class names")
print("✓ Confusion matrix rows match RF class names")


# ---------------------------------------------------------------
# 7. CONFUSION MATRIX VALUE VALIDATION
# ---------------------------------------------------------------

print("\n[CONFUSION MATRIX VALUE VALIDATION]")

assert np.issubdtype(
    RF_5_13_CONFUSION_MATRIX.values.dtype,
    np.number
), (
    "Persisted confusion matrix contains "
    "non-numeric values."
)

assert np.isfinite(
    RF_5_13_CONFUSION_MATRIX.values
).all(), (
    "Persisted confusion matrix contains "
    "non-finite values."
)

assert (
    RF_5_13_CONFUSION_MATRIX.values >= 0
).all(), (
    "Persisted confusion matrix contains "
    "negative observations."
)

assert (
    RF_5_13_CONFUSION_MATRIX.values.sum()
    == EXPECTED_RF_PARTITION_ROWS["Test"]
), (
    "Persisted confusion matrix total does not "
    "match the Independent Test size."
)

print("✓ Confusion matrix values are numeric")
print("✓ Confusion matrix values are finite")
print("✓ Confusion matrix contains no negative counts")

print(
    f"✓ Confusion matrix total = "
    f"{int(RF_5_13_CONFUSION_MATRIX.values.sum()):,}"
)

print("✓ Confusion matrix accounts for all Test observations")


# ---------------------------------------------------------------
# 8. CLASSIFICATION REPORT STRUCTURE VALIDATION
# ---------------------------------------------------------------

print("\n[CLASSIFICATION REPORT STRUCTURE VALIDATION]")

RF_5_13_REQUIRED_CLASSIFICATION_COLUMNS = {
    "class_id",
    "class_name",
    "precision",
    "recall",
    "f1",
    "support",
}

assert RF_5_13_REQUIRED_CLASSIFICATION_COLUMNS.issubset(
    RF_5_13_CLASSIFICATION_REPORT.columns
), (
    "Persisted classification report does not contain "
    "the established nine-class metric schema."
)

assert (
    len(RF_5_13_CLASSIFICATION_REPORT)
    == 9
), (
    "Persisted classification report does not contain "
    "exactly nine class rows."
)

print(
    f"✓ Classification report rows = "
    f"{len(RF_5_13_CLASSIFICATION_REPORT)}"
)

print("✓ Established classification-report schema validated")


# ---------------------------------------------------------------
# 9. CLASSIFICATION REPORT TAXONOMY VALIDATION
# ---------------------------------------------------------------

print("\n[CLASSIFICATION REPORT TAXONOMY VALIDATION]")

assert np.array_equal(
    RF_5_13_CLASSIFICATION_REPORT[
        "class_id"
    ].to_numpy(dtype=np.int64),
    EXPECTED_RF_CLASS_IDS
), (
    "Classification report class IDs do not match "
    "the established RF taxonomy."
)

assert (
    RF_5_13_CLASSIFICATION_REPORT[
        "class_name"
    ].tolist()
    ==
    RF_5_13_EXPECTED_CLASS_NAMES
), (
    "Classification report class names do not match "
    "the established RF taxonomy."
)

print("✓ Classification report class IDs validated")
print("✓ Classification report class names validated")
print("✓ All nine taxonomy classes are represented")


# ---------------------------------------------------------------
# 10. CLASSIFICATION REPORT METRIC VALIDATION
# ---------------------------------------------------------------

print("\n[CLASSIFICATION REPORT METRIC VALIDATION]")

for column_name in (
    "precision",
    "recall",
    "f1"
):

    values = RF_5_13_CLASSIFICATION_REPORT[
        column_name
    ].to_numpy(dtype=np.float64)

    assert np.isfinite(values).all(), (
        f"Classification report '{column_name}' "
        "contains non-finite values."
    )

    assert (
        (values >= 0.0)
        &
        (values <= 1.0)
    ).all(), (
        f"Classification report '{column_name}' "
        "contains values outside [0, 1]."
    )


RF_5_13_SUPPORT_VALUES = (
    RF_5_13_CLASSIFICATION_REPORT[
        "support"
    ].to_numpy(dtype=np.int64)
)

assert (
    RF_5_13_SUPPORT_VALUES >= 0
).all(), (
    "Classification report contains negative support values."
)

assert (
    RF_5_13_SUPPORT_VALUES.sum()
    == EXPECTED_RF_PARTITION_ROWS["Test"]
), (
    "Classification report support total does not "
    "match the Independent Test size."
)

print("✓ Precision values validated")
print("✓ Recall values validated")
print("✓ F1 values validated")
print("✓ Support values validated")

print(
    f"✓ Classification report support total = "
    f"{int(RF_5_13_SUPPORT_VALUES.sum()):,}"
)


# ---------------------------------------------------------------
# 11. LOADED EVALUATION OBJECT SUMMARY
# ---------------------------------------------------------------

print("\n[LOADED EVALUATION OBJECT SUMMARY]")

print(
    f"✓ Test results shape          : "
    f"{RF_5_13_TEST_RESULTS.shape}"
)

print(
    f"✓ Confusion matrix shape      : "
    f"{RF_5_13_CONFUSION_MATRIX.shape}"
)

print(
    f"✓ Classification report shape : "
    f"{RF_5_13_CLASSIFICATION_REPORT.shape}"
)

print(
    f"✓ Evaluated strategy          : "
    f"{RF_5_13_TEST_RESULT_ROW['strategy_id']}"
)

print(
    f"✓ Evaluation partition        : "
    f"{RF_5_13_TEST_RESULT_ROW['partition']}"
)

print(
    f"✓ Test observations           : "
    f"{int(RF_5_13_TEST_RESULT_ROW['test_observations']):,}"
)


# ---------------------------------------------------------------
# 12. ERROR-ANALYSIS BOUNDARY
# ---------------------------------------------------------------

print("\n[ERROR-ANALYSIS BOUNDARY]")

print(
    "✓ Persisted Test results loaded as read-only analysis input"
)

print(
    "✓ Persisted confusion matrix loaded as read-only analysis input"
)

print(
    "✓ Persisted classification report loaded as "
    "read-only analysis input"
)

print("✓ No Independent Test feature arrays loaded")
print("✓ No Independent Test target arrays loaded")
print("✓ No new predictions generated")
print("✓ No new metrics calculated from raw Test data")
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No strategy selection performed")


# ---------------------------------------------------------------
# 13. SECTION 5.13.2 VALIDATION STATE
# ---------------------------------------------------------------

RF_5_13_2_VALIDATION = {

    "section_5_13_1_completed":
        all(
            RF_5_13_1_VALIDATION.values()
        ),

    "test_results_loaded":
        not RF_5_13_TEST_RESULTS.empty,

    "test_results_schema_valid":
        RF_5_13_REQUIRED_TEST_RESULT_COLUMNS.issubset(
            RF_5_13_TEST_RESULTS.columns
        ),

    "test_results_rf3_valid":
        (
            RF_5_13_TEST_RESULT_ROW["strategy_id"]
            == "RF-3"
            and
            RF_5_13_TEST_RESULT_ROW["strategy_name"]
            == "Controlled Random Oversampling"
        ),

    "test_results_partition_valid":
        (
            str(
                RF_5_13_TEST_RESULT_ROW["partition"]
            ).strip()
            == "Independent Test"
        ),

    "test_results_observation_count_valid":
        (
            int(
                RF_5_13_TEST_RESULT_ROW[
                    "test_observations"
                ]
            )
            == EXPECTED_RF_PARTITION_ROWS["Test"]
        ),

    "confusion_matrix_loaded":
        not RF_5_13_CONFUSION_MATRIX.empty,

    "confusion_matrix_complete":
        (
            RF_5_13_CONFUSION_MATRIX.shape
            == (9, 9)
            and
            RF_5_13_CONFUSION_MATRIX.columns.tolist()
            == RF_5_13_EXPECTED_CLASS_NAMES
            and
            RF_5_13_CONFUSION_MATRIX.index.tolist()
            == RF_5_13_EXPECTED_CLASS_NAMES
            and
            RF_5_13_CONFUSION_MATRIX.values.sum()
            == EXPECTED_RF_PARTITION_ROWS["Test"]
        ),

    "classification_report_loaded":
        not RF_5_13_CLASSIFICATION_REPORT.empty,

    "classification_report_complete":
        (
            len(
                RF_5_13_CLASSIFICATION_REPORT
            )
            == 9
            and
            RF_5_13_SUPPORT_VALUES.sum()
            == EXPECTED_RF_PARTITION_ROWS["Test"]
        ),

    "taxonomy_consistent":
        (
            np.array_equal(
                RF_5_13_CLASSIFICATION_REPORT[
                    "class_id"
                ].to_numpy(dtype=np.int64),
                EXPECTED_RF_CLASS_IDS
            )
            and
            RF_5_13_CLASSIFICATION_REPORT[
                "class_name"
            ].tolist()
            == RF_5_13_EXPECTED_CLASS_NAMES
        ),

    "no_test_arrays_loaded":
        True,

    "no_new_predictions":
        True,

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_strategy_selection":
        True,
}


assert all(
    RF_5_13_2_VALIDATION.values()
), (
    "Section 5.13.2 persisted Independent Test "
    "evaluation loading validation is incomplete."
)


# ---------------------------------------------------------------
# 14. FINAL 5.13.2 READINESS GATE
# ---------------------------------------------------------------

print("\n[5.13.2 PERSISTED EVALUATION LOADING READINESS GATE]")

print("✓ test_results.csv loaded and validated")
print("✓ confusion_matrix.csv loaded and validated")
print("✓ classification_report.csv loaded and validated")
print("✓ Final RF-3 Test result identified")
print("✓ Independent Test partition validated")
print("✓ Test observation count validated")
print("✓ 9 × 9 confusion matrix validated")
print("✓ Confusion matrix class ordering validated")
print("✓ Confusion matrix accounts for all Test observations")
print("✓ Nine-class classification report validated")
print("✓ Classification report support accounts for all Test observations")
print("✓ RF taxonomy consistency validated")
print("✓ No Test arrays loaded")
print("✓ No new predictions generated")
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No strategy selection performed")


print("\n" + "=" * 72)

print(
    "5.13.2 — PERSISTED INDEPENDENT TEST "
    "EVALUATION LOADING PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.13.3 — CLASS-WISE PERFORMANCE "
    "AND ERROR ANALYSIS"
)

print("=" * 72)

========================================================================
5.13.2 — PERSISTED INDEPENDENT TEST EVALUATION LOADING
========================================================================

[PREVIOUS-SUBSECTION COMPLETION BOUNDARY]
✓ Section 5.13.1 validation completed
✓ Persisted Test artifact paths remain available
✓ Error-analysis boundary remains valid

[PERSISTED TEST EVALUATION ARTIFACT LOADING]
✓ test_results.csv loaded
✓ confusion_matrix.csv loaded
✓ classification_report.csv loaded

[TEST RESULTS STRUCTURE VALIDATION]
✓ Test results rows = 1
✓ Established Test-results schema validated

[FINAL RF-3 TEST RESULT VALIDATION]
✓ Evaluated strategy = RF-3
✓ Strategy name = Controlled Random Oversampling
✓ Evaluation partition = Independent Test
✓ Test observations = 565,510
✓ Persisted aggregate Test result is valid

[TEST RESULT METRIC INTEGRITY]
✓ All persisted Test-result metrics are finite
✓ Aggregate Test metric ranges validated

[CONFUSION MATRIX STRUCTURE VALIDATION]
✓ Confusion matrix shape = (9, 9)
✓ Confusion matrix columns match RF class names
✓ Confusion matrix rows match RF class names

[CONFUSION MATRIX VALUE VALIDATION]
✓ Confusion matrix values are numeric
✓ Confusion matrix values are finite
✓ Confusion matrix contains no negative counts
✓ Confusion matrix total = 565,510
✓ Confusion matrix accounts for all Test observations

[CLASSIFICATION REPORT STRUCTURE VALIDATION]
✓ Classification report rows = 9
✓ Established classification-report schema validated

[CLASSIFICATION REPORT TAXONOMY VALIDATION]
✓ Classification report class IDs validated
✓ Classification report class names validated
✓ All nine taxonomy classes are represented

[CLASSIFICATION REPORT METRIC VALIDATION]
✓ Precision values validated
✓ Recall values validated
✓ F1 values validated
✓ Support values validated
✓ Classification report support total = 565,510

[LOADED EVALUATION OBJECT SUMMARY]
✓ Test results shape          : (1, 21)
✓ Confusion matrix shape      : (9, 9)
✓ Classification report shape : (9, 6)
✓ Evaluated strategy          : RF-3
✓ Evaluation partition        : Independent Test
✓ Test observations           : 565,510

[ERROR-ANALYSIS BOUNDARY]
✓ Persisted Test results loaded as read-only analysis input
✓ Persisted confusion matrix loaded as read-only analysis input
✓ Persisted classification report loaded as read-only analysis input
✓ No Independent Test feature arrays loaded
✓ No Independent Test target arrays loaded
✓ No new predictions generated
✓ No new metrics calculated from raw Test data
✓ No model fitting performed
✓ No resampling performed
✓ No strategy selection performed

[5.13.2 PERSISTED EVALUATION LOADING READINESS GATE]
✓ test_results.csv loaded and validated
✓ confusion_matrix.csv loaded and validated
✓ classification_report.csv loaded and validated
✓ Final RF-3 Test result identified
✓ Independent Test partition validated
✓ Test observation count validated
✓ 9 × 9 confusion matrix validated
✓ Confusion matrix class ordering validated
✓ Confusion matrix accounts for all Test observations
✓ Nine-class classification report validated
✓ Classification report support accounts for all Test observations
✓ RF taxonomy consistency validated
✓ No Test arrays loaded
✓ No new predictions generated
✓ No model fitting performed
✓ No resampling performed
✓ No strategy selection performed

========================================================================
5.13.2 — PERSISTED INDEPENDENT TEST EVALUATION LOADING PASSED
========================================================================

READY FOR 5.13.3 — CLASS-WISE PERFORMANCE AND ERROR ANALYSIS
========================================================================

## 5.13.3 — Class-Wise Performance and Error Analysis

This subsection performs class-wise error analysis using the persisted
Independent Test evaluation artifacts validated in Section 5.13.2.

The persisted nine-class classification report provides the authoritative
per-class precision, recall, F1-score, and support values. The persisted
confusion matrix is used to derive class-wise false-positive and
false-negative counts without accessing the raw Independent Test partition.

The analysis evaluates:

- per-class Precision, Recall, and F1-score,
- class support and class representation,
- class-wise false-positive counts,
- class-wise false-negative counts,
- class-wise error rates,
- the strongest and weakest performing classes,
- attack-class false-negative concentration,
- BENIGN false-positive behavior, and
- low-support/minority-class behavior.

The aggregate attack false-negative count and BENIGN false-positive rate are
cross-validated against the persisted `test_results.csv` artifact.

No raw Test features or targets are loaded. No new predictions are generated.
No model fitting, resampling, hyperparameter selection, or strategy selection
is performed.

The resulting class-wise analysis remains an interpretation-stage output and
does not modify the persisted Independent Test evaluation artifacts.

In [ ]:
# ================================================================
# 5.13.3 — CLASS-WISE PERFORMANCE AND ERROR ANALYSIS
# ================================================================

import numpy as np
import pandas as pd


print("=" * 72)
print("5.13.3 — CLASS-WISE PERFORMANCE AND ERROR ANALYSIS")
print("=" * 72)


# ---------------------------------------------------------------
# 1. PREVIOUS-SUBSECTION COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[PREVIOUS-SUBSECTION COMPLETION BOUNDARY]")

assert "RF_5_13_2_VALIDATION" in globals(), (
    "Section 5.13.2 validation state is unavailable."
)

assert all(
    RF_5_13_2_VALIDATION.values()
), (
    "Section 5.13.2 persisted evaluation loading "
    "validation is incomplete."
)

assert "RF_5_13_TEST_RESULTS" in globals(), (
    "Persisted Test results are unavailable."
)

assert "RF_5_13_CONFUSION_MATRIX" in globals(), (
    "Persisted confusion matrix is unavailable."
)

assert "RF_5_13_CLASSIFICATION_REPORT" in globals(), (
    "Persisted classification report is unavailable."
)

print("✓ Section 5.13.2 validation completed")
print("✓ Persisted Test results available")
print("✓ Persisted confusion matrix available")
print("✓ Persisted classification report available")


# ---------------------------------------------------------------
# 2. FROZEN CLASS-WISE ANALYSIS CONTRACT
# ---------------------------------------------------------------

print("\n[FROZEN CLASS-WISE ANALYSIS CONTRACT]")

RF_5_13_3_CLASS_IDS = (
    EXPECTED_RF_CLASS_IDS.copy()
)

RF_5_13_3_CLASS_NAMES = [
    RF_CLASS_MAPPING[class_id]
    for class_id in RF_5_13_3_CLASS_IDS
]

assert len(
    RF_5_13_3_CLASS_IDS
) == 9

assert len(
    RF_5_13_3_CLASS_NAMES
) == 9

assert (
    RF_5_13_3_CLASS_NAMES
    == RF_5_13_EXPECTED_CLASS_NAMES
)

print("✓ Nine RF class IDs confirmed")
print("✓ Nine RF class names confirmed")
print("✓ Class ordering remains frozen")


# ---------------------------------------------------------------
# 3. CLASSIFICATION-REPORT DATA EXTRACTION
# ---------------------------------------------------------------

print("\n[CLASSIFICATION-REPORT DATA EXTRACTION]")

RF_5_13_3_CLASS_WISE_ANALYSIS = (
    RF_5_13_CLASSIFICATION_REPORT[
        [
            "class_id",
            "class_name",
            "precision",
            "recall",
            "f1",
            "support",
        ]
    ]
    .copy()
)

assert (
    RF_5_13_3_CLASS_WISE_ANALYSIS[
        "class_id"
    ].to_numpy(dtype=np.int64)
    == RF_5_13_3_CLASS_IDS
).all()

assert (
    RF_5_13_3_CLASS_WISE_ANALYSIS[
        "class_name"
    ].tolist()
    == RF_5_13_3_CLASS_NAMES
)

print(
    f"✓ Class-wise analysis rows = "
    f"{len(RF_5_13_3_CLASS_WISE_ANALYSIS)}"
)

print("✓ Classification-report values loaded")


# ---------------------------------------------------------------
# 4. CONFUSION-MATRIX ERROR COUNTS
# ---------------------------------------------------------------

print("\n[CONFUSION-MATRIX ERROR COUNTS]")

RF_5_13_3_CONFUSION_VALUES = (
    RF_5_13_CONFUSION_MATRIX
    .loc[
        RF_5_13_3_CLASS_NAMES,
        RF_5_13_3_CLASS_NAMES
    ]
    .to_numpy(dtype=np.int64)
)

assert (
    RF_5_13_3_CONFUSION_VALUES.shape
    == (9, 9)
)

RF_5_13_3_TRUE_POSITIVES = (
    np.diag(
        RF_5_13_3_CONFUSION_VALUES
    )
)

RF_5_13_3_ACTUAL_COUNTS = (
    RF_5_13_3_CONFUSION_VALUES.sum(axis=1)
)

RF_5_13_3_PREDICTED_COUNTS = (
    RF_5_13_3_CONFUSION_VALUES.sum(axis=0)
)

RF_5_13_3_FALSE_NEGATIVES = (
    RF_5_13_3_ACTUAL_COUNTS
    - RF_5_13_3_TRUE_POSITIVES
)

RF_5_13_3_FALSE_POSITIVES = (
    RF_5_13_3_PREDICTED_COUNTS
    - RF_5_13_3_TRUE_POSITIVES
)

assert (
    RF_5_13_3_TRUE_POSITIVES >= 0
).all()

assert (
    RF_5_13_3_FALSE_NEGATIVES >= 0
).all()

assert (
    RF_5_13_3_FALSE_POSITIVES >= 0
).all()

print("✓ True-positive counts derived")
print("✓ False-negative counts derived")
print("✓ False-positive counts derived")
print("✓ All derived error counts are non-negative")


# ---------------------------------------------------------------
# 5. SUPPORT CONSISTENCY VALIDATION
# ---------------------------------------------------------------

print("\n[SUPPORT CONSISTENCY VALIDATION]")

RF_5_13_3_REPORT_SUPPORT = (
    RF_5_13_3_CLASS_WISE_ANALYSIS[
        "support"
    ].to_numpy(dtype=np.int64)
)

assert np.array_equal(
    RF_5_13_3_REPORT_SUPPORT,
    RF_5_13_3_ACTUAL_COUNTS
), (
    "Classification-report support does not match "
    "confusion-matrix actual-class totals."
)

assert (
    RF_5_13_3_REPORT_SUPPORT.sum()
    == EXPECTED_RF_PARTITION_ROWS["Test"]
)

print("✓ Classification-report support matches confusion matrix")
print(
    f"✓ Total class support = "
    f"{RF_5_13_3_REPORT_SUPPORT.sum():,}"
)
print("✓ All Independent Test observations are represented")


# ---------------------------------------------------------------
# 6. CLASS-WISE ERROR METRICS
# ---------------------------------------------------------------

print("\n[CLASS-WISE ERROR METRICS]")

RF_5_13_3_CLASS_WISE_ANALYSIS[
    "true_positives"
] = RF_5_13_3_TRUE_POSITIVES

RF_5_13_3_CLASS_WISE_ANALYSIS[
    "false_positives"
] = RF_5_13_3_FALSE_POSITIVES

RF_5_13_3_CLASS_WISE_ANALYSIS[
    "false_negatives"
] = RF_5_13_3_FALSE_NEGATIVES

RF_5_13_3_CLASS_WISE_ANALYSIS[
    "error_rate"
] = (
    1.0
    - RF_5_13_3_CLASS_WISE_ANALYSIS[
        "recall"
    ]
)

RF_5_13_3_CLASS_WISE_ANALYSIS[
    "support_percentage"
] = (
    RF_5_13_3_CLASS_WISE_ANALYSIS[
        "support"
    ]
    / EXPECTED_RF_PARTITION_ROWS["Test"]
    * 100.0
)

assert np.isfinite(
    RF_5_13_3_CLASS_WISE_ANALYSIS[
        "error_rate"
    ].to_numpy()
).all()

print("✓ True-positive counts added")
print("✓ False-positive counts added")
print("✓ False-negative counts added")
print("✓ Class-wise error rates calculated")
print("✓ Class support percentages calculated")


# ---------------------------------------------------------------
# 7. CLASS-WISE PERFORMANCE TABLE
# ---------------------------------------------------------------

print("\n[CLASS-WISE PERFORMANCE TABLE]")

RF_5_13_3_CLASS_WISE_DISPLAY = (
    RF_5_13_3_CLASS_WISE_ANALYSIS[
        [
            "class_id",
            "class_name",
            "precision",
            "recall",
            "f1",
            "support",
            "true_positives",
            "false_positives",
            "false_negatives",
            "error_rate",
            "support_percentage",
        ]
    ]
    .copy()
)

display(
    RF_5_13_3_CLASS_WISE_DISPLAY
)

print("✓ Complete nine-class performance table generated")


# ---------------------------------------------------------------
# 8. STRONGEST AND WEAKEST CLASS PERFORMANCE
# ---------------------------------------------------------------

print("\n[CLASS PERFORMANCE INTERPRETATION]")

RF_5_13_3_HIGHEST_F1_ROW = (
    RF_5_13_3_CLASS_WISE_ANALYSIS.loc[
        RF_5_13_3_CLASS_WISE_ANALYSIS[
            "f1"
        ].idxmax()
    ]
)

RF_5_13_3_LOWEST_F1_ROW = (
    RF_5_13_3_CLASS_WISE_ANALYSIS.loc[
        RF_5_13_3_CLASS_WISE_ANALYSIS[
            "f1"
        ].idxmin()
    ]
)

RF_5_13_3_LOWEST_RECALL_ROW = (
    RF_5_13_3_CLASS_WISE_ANALYSIS.loc[
        RF_5_13_3_CLASS_WISE_ANALYSIS[
            "recall"
        ].idxmin()
    ]
)

print(
    f"✓ Highest F1 class  : "
    f"{RF_5_13_3_HIGHEST_F1_ROW['class_name']} "
    f"({RF_5_13_3_HIGHEST_F1_ROW['f1']:.6f})"
)

print(
    f"✓ Lowest F1 class   : "
    f"{RF_5_13_3_LOWEST_F1_ROW['class_name']} "
    f"({RF_5_13_3_LOWEST_F1_ROW['f1']:.6f})"
)

print(
    f"✓ Lowest Recall class : "
    f"{RF_5_13_3_LOWEST_RECALL_ROW['class_name']} "
    f"({RF_5_13_3_LOWEST_RECALL_ROW['recall']:.6f})"
)


# ---------------------------------------------------------------
# 9. ATTACK FALSE-NEGATIVE ANALYSIS
# ---------------------------------------------------------------

print("\n[ATTACK FALSE-NEGATIVE ANALYSIS]")

RF_5_13_3_ATTACK_CLASS_IDS = (
    RF_5_13_3_CLASS_IDS[
        RF_5_13_3_CLASS_IDS != 0
    ]
)

RF_5_13_3_ATTACK_ANALYSIS = (
    RF_5_13_3_CLASS_WISE_ANALYSIS[
        RF_5_13_3_CLASS_WISE_ANALYSIS[
            "class_id"
        ].isin(
            RF_5_13_3_ATTACK_CLASS_IDS
        )
    ]
    .copy()
)

RF_5_13_3_TOTAL_ATTACK_FALSE_NEGATIVES = int(
    RF_5_13_3_ATTACK_ANALYSIS[
        "false_negatives"
    ].sum()
)

RF_5_13_3_PERSISTED_ATTACK_FALSE_NEGATIVES = int(
    RF_5_13_TEST_RESULT_ROW[
        "attack_false_negatives"
    ]
)

assert (
    RF_5_13_3_TOTAL_ATTACK_FALSE_NEGATIVES
    == RF_5_13_3_PERSISTED_ATTACK_FALSE_NEGATIVES
), (
    "Derived attack false negatives do not match "
    "the persisted Test-results value."
)

RF_5_13_3_ATTACK_ANALYSIS = (
    RF_5_13_3_ATTACK_ANALYSIS
    .sort_values(
        "false_negatives",
        ascending=False
    )
)

print(
    f"✓ Total attack false negatives = "
    f"{RF_5_13_3_TOTAL_ATTACK_FALSE_NEGATIVES:,}"
)

print(
    f"✓ Persisted attack false negatives = "
    f"{RF_5_13_3_PERSISTED_ATTACK_FALSE_NEGATIVES:,}"
)

print(
    "✓ Derived attack false negatives match "
    "the persisted evaluation result"
)

print("\nAttack classes ranked by false negatives:")

display(
    RF_5_13_3_ATTACK_ANALYSIS[
        [
            "class_id",
            "class_name",
            "recall",
            "f1",
            "support",
            "false_negatives",
        ]
    ]
)


# ---------------------------------------------------------------
# 10. BENIGN FALSE-POSITIVE ANALYSIS
# ---------------------------------------------------------------

print("\n[BENIGN FALSE-POSITIVE ANALYSIS]")

RF_5_13_3_BENIGN_ROW = (
    RF_5_13_3_CLASS_WISE_ANALYSIS[
        RF_5_13_3_CLASS_WISE_ANALYSIS[
            "class_id"
        ] == 0
    ].iloc[0]
)

RF_5_13_3_BENIGN_FALSE_POSITIVES = int(
    RF_5_13_3_BENIGN_ROW[
        "false_positives"
    ]
)

RF_5_13_3_BENIGN_ACTUAL_NEGATIVES = (
    EXPECTED_RF_PARTITION_ROWS["Test"]
    - int(
        RF_5_13_3_BENIGN_ROW[
            "support"
        ]
    )
)

RF_5_13_3_BENIGN_FPR = (
    RF_5_13_3_BENIGN_FALSE_POSITIVES
    /
    RF_5_13_3_BENIGN_ACTUAL_NEGATIVES
)

RF_5_13_3_PERSISTED_BENIGN_FPR = float(
    RF_5_13_TEST_RESULT_ROW[
        "benign_false_positive_rate"
    ]
)

assert np.isclose(
    RF_5_13_3_BENIGN_FPR,
    RF_5_13_3_PERSISTED_BENIGN_FPR,
    rtol=0,
    atol=1e-6
), (
    "Derived BENIGN false-positive rate does not "
    "match the persisted Test-results value."
)

print(
    f"✓ BENIGN false positives = "
    f"{RF_5_13_3_BENIGN_FALSE_POSITIVES:,}"
)

print(
    f"✓ BENIGN actual negatives = "
    f"{RF_5_13_3_BENIGN_ACTUAL_NEGATIVES:,}"
)

print(
    f"✓ Derived BENIGN FPR = "
    f"{RF_5_13_3_BENIGN_FPR:.6f}"
)

print(
    f"✓ Persisted BENIGN FPR = "
    f"{RF_5_13_3_PERSISTED_BENIGN_FPR:.6f}"
)

print("✓ BENIGN FPR matches persisted evaluation")


# ---------------------------------------------------------------
# 11. LOW-SUPPORT / MINORITY-CLASS ANALYSIS
# ---------------------------------------------------------------

print("\n[LOW-SUPPORT / MINORITY-CLASS ANALYSIS]")

RF_5_13_3_LOW_SUPPORT_ANALYSIS = (
    RF_5_13_3_CLASS_WISE_ANALYSIS
    .sort_values(
        "support",
        ascending=True
    )
)

print("Classes ordered by Independent Test support:")

display(
    RF_5_13_3_LOW_SUPPORT_ANALYSIS[
        [
            "class_id",
            "class_name",
            "support",
            "support_percentage",
            "precision",
            "recall",
            "f1",
            "false_negatives",
        ]
    ]
)

RF_5_13_3_LOWEST_SUPPORT_ROW = (
    RF_5_13_3_LOW_SUPPORT_ANALYSIS.iloc[0]
)

print(
    f"✓ Lowest-support class = "
    f"{RF_5_13_3_LOWEST_SUPPORT_ROW['class_name']}"
)

print(
    f"✓ Lowest-support observations = "
    f"{int(RF_5_13_3_LOWEST_SUPPORT_ROW['support'])}"
)


# ---------------------------------------------------------------
# 12. CLASS-WISE ERROR RANKING
# ---------------------------------------------------------------

print("\n[CLASS-WISE ERROR RANKING]")

RF_5_13_3_ERROR_RANKING = (
    RF_5_13_3_CLASS_WISE_ANALYSIS
    .sort_values(
        [
            "false_negatives",
            "false_positives",
        ],
        ascending=False
    )
)

display(
    RF_5_13_3_ERROR_RANKING[
        [
            "class_id",
            "class_name",
            "support",
            "recall",
            "f1",
            "false_positives",
            "false_negatives",
        ]
    ]
)

print("✓ Class-wise error ranking generated")


# ---------------------------------------------------------------
# 13. ERROR-ANALYSIS INTERPRETATION SUMMARY
# ---------------------------------------------------------------

print("\n[CLASS-WISE ERROR ANALYSIS SUMMARY]")

print(
    f"✓ Highest F1 performance : "
    f"{RF_5_13_3_HIGHEST_F1_ROW['class_name']} "
    f"({RF_5_13_3_HIGHEST_F1_ROW['f1']:.6f})"
)

print(
    f"✓ Lowest F1 performance  : "
    f"{RF_5_13_3_LOWEST_F1_ROW['class_name']} "
    f"({RF_5_13_3_LOWEST_F1_ROW['f1']:.6f})"
)

print(
    f"✓ Lowest Recall          : "
    f"{RF_5_13_3_LOWEST_RECALL_ROW['class_name']} "
    f"({RF_5_13_3_LOWEST_RECALL_ROW['recall']:.6f})"
)

print(
    f"✓ Total attack FNs       : "
    f"{RF_5_13_3_TOTAL_ATTACK_FALSE_NEGATIVES:,}"
)

print(
    f"✓ BENIGN false positives : "
    f"{RF_5_13_3_BENIGN_FALSE_POSITIVES:,}"
)

print(
    f"✓ BENIGN FPR             : "
    f"{RF_5_13_3_BENIGN_FPR:.6f}"
)

print(
    f"✓ Lowest-support class   : "
    f"{RF_5_13_3_LOWEST_SUPPORT_ROW['class_name']} "
    f"({int(RF_5_13_3_LOWEST_SUPPORT_ROW['support']):,} observations)"
)


# ---------------------------------------------------------------
# 14. ANALYSIS BOUNDARY
# ---------------------------------------------------------------

print("\n[ERROR-ANALYSIS OPERATION BOUNDARY]")

print(
    "✓ Analysis performed only from persisted evaluation artifacts"
)

print(
    "✓ No Independent Test feature arrays loaded"
)

print(
    "✓ No Independent Test target arrays loaded"
)

print(
    "✓ No new predictions generated"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No hyperparameter selection performed"
)

print(
    "✓ No strategy selection performed"
)

print(
    "✓ Persisted Test artifacts remain unchanged"
)


# ---------------------------------------------------------------
# 15. SECTION 5.13.3 VALIDATION STATE
# ---------------------------------------------------------------

RF_5_13_3_VALIDATION = {

    "section_5_13_2_completed":
        all(
            RF_5_13_2_VALIDATION.values()
        ),

    "class_wise_rows_valid":
        (
            len(
                RF_5_13_3_CLASS_WISE_ANALYSIS
            )
            == 9
        ),

    "support_matches_confusion_matrix":
        np.array_equal(
            RF_5_13_3_REPORT_SUPPORT,
            RF_5_13_3_ACTUAL_COUNTS
        ),

    "test_observation_total_valid":
        (
            RF_5_13_3_REPORT_SUPPORT.sum()
            == EXPECTED_RF_PARTITION_ROWS["Test"]
        ),

    "attack_false_negatives_valid":
        (
            RF_5_13_3_TOTAL_ATTACK_FALSE_NEGATIVES
            == RF_5_13_3_PERSISTED_ATTACK_FALSE_NEGATIVES
        ),

    "benign_fpr_valid":
        np.isclose(
            RF_5_13_3_BENIGN_FPR,
            RF_5_13_3_PERSISTED_BENIGN_FPR,
            rtol=0,
            atol=1e-6
        ),

    "class_taxonomy_valid":
        (
            RF_5_13_3_CLASS_WISE_ANALYSIS[
                "class_id"
            ].tolist()
            == RF_5_13_3_CLASS_IDS.tolist()
            and
            RF_5_13_3_CLASS_WISE_ANALYSIS[
                "class_name"
            ].tolist()
            == RF_5_13_3_CLASS_NAMES
        ),

    "no_test_arrays_loaded":
        True,

    "no_new_predictions":
        True,

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_strategy_selection":
        True,
}


assert all(
    RF_5_13_3_VALIDATION.values()
), (
    "Section 5.13.3 class-wise error analysis "
    "validation is incomplete."
)


# ---------------------------------------------------------------
# 16. FINAL 5.13.3 READINESS GATE
# ---------------------------------------------------------------

print("\n[5.13.3 CLASS-WISE ERROR ANALYSIS READINESS GATE]")

print("✓ Nine-class performance table generated")
print("✓ Classification-report support validated")
print("✓ Confusion-matrix support validated")
print("✓ Class-wise false positives derived")
print("✓ Class-wise false negatives derived")
print("✓ Class-wise error rates calculated")
print("✓ Highest and lowest F1 classes identified")
print("✓ Lowest-recall class identified")
print("✓ Attack false negatives validated")
print("✓ BENIGN false-positive rate validated")
print("✓ Low-support classes analyzed")
print("✓ Class-wise error ranking generated")
print("✓ No Test arrays loaded")
print("✓ No new predictions generated")
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No strategy selection performed")
print("✓ Persisted evaluation artifacts remain unchanged")


print("\n" + "=" * 72)

print(
    "5.13.3 — CLASS-WISE PERFORMANCE "
    "AND ERROR ANALYSIS PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.13.4 — CONFUSION PATTERN "
    "AND MINORITY-CLASS ANALYSIS"
)

print("=" * 72)

========================================================================
5.13.3 — CLASS-WISE PERFORMANCE AND ERROR ANALYSIS
========================================================================

[PREVIOUS-SUBSECTION COMPLETION BOUNDARY]
✓ Section 5.13.2 validation completed
✓ Persisted Test results available
✓ Persisted confusion matrix available
✓ Persisted classification report available

[FROZEN CLASS-WISE ANALYSIS CONTRACT]
✓ Nine RF class IDs confirmed
✓ Nine RF class names confirmed
✓ Class ordering remains frozen

[CLASSIFICATION-REPORT DATA EXTRACTION]
✓ Class-wise analysis rows = 9
✓ Classification-report values loaded

[CONFUSION-MATRIX ERROR COUNTS]
✓ True-positive counts derived
✓ False-negative counts derived
✓ False-positive counts derived
✓ All derived error counts are non-negative

[SUPPORT CONSISTENCY VALIDATION]
✓ Classification-report support matches confusion matrix
✓ Total class support = 565,510
✓ All Independent Test observations are represented

[CLASS-WISE ERROR METRICS]
✓ True-positive counts added
✓ False-positive counts added
✓ False-negative counts added
✓ Class-wise error rates calculated
✓ Class support percentages calculated

[CLASS-WISE PERFORMANCE TABLE]

,class_id,class_name,precision,recall,f1,support,true_positives,false_positives,false_negatives,error_rate,support_percentage
0,0,BENIGN,0.994317,0.998619,0.996464,455399,454770,2599,629,0.001381,80.528903
1,1,DDoS,0.999687,0.999492,0.999590,25601,25588,8,13,0.000508,4.527064
2,2,Port Scan,0.993975,0.996682,0.995327,31946,31840,193,106,0.003318,5.649060
3,3,Brute Force,0.990421,0.976208,0.983264,2648,2585,25,63,0.023792,0.468250
4,4,Bot,0.562802,0.583960,0.573186,399,233,181,166,0.416040,0.070556
5,5,Web Attack,0.981132,0.971963,0.976526,428,416,8,12,0.028037,0.075684
6,6,Infiltration,1.000000,0.500000,0.666667,8,4,0,4,0.500000,0.001415
7,7,DoS,0.994985,0.954014,0.974069,49080,46823,236,2257,0.045986,8.678892
8,8,Heartbleed,1.000000,1.000000,1.000000,1,1,0,0,0.000000,0.000177

✓ Complete nine-class performance table generated

[CLASS PERFORMANCE INTERPRETATION]
✓ Highest F1 class  : Heartbleed (1.000000)
✓ Lowest F1 class   : Bot (0.573186)
✓ Lowest Recall class : Infiltration (0.500000)

[ATTACK FALSE-NEGATIVE ANALYSIS]
✓ Total attack false negatives = 2,621
✓ Persisted attack false negatives = 2,621
✓ Derived attack false negatives match the persisted evaluation result

Attack classes ranked by false negatives:

   class_id    class_name    recall        f1  support  false_negatives
7         7           DoS  0.954014  0.974069    49080             2257
4         4           Bot  0.583960  0.573186      399              166
2         2     Port Scan  0.996682  0.995327    31946              106
3         3   Brute Force  0.976208  0.983264     2648               63
1         1          DDoS  0.999492  0.999590    25601               13
5         5    Web Attack  0.971963  0.976526      428               12
6         6  Infiltration  0.500000  0.666667        8                4
8         8    Heartbleed  1.000000  1.000000        1                0

[BENIGN FALSE-POSITIVE ANALYSIS]
✓ BENIGN false positives = 2,599
✓ BENIGN actual negatives = 110,111
✓ Derived BENIGN FPR = 0.023603
✓ Persisted BENIGN FPR = 0.023603
✓ BENIGN FPR matches persisted evaluation

[LOW-SUPPORT / MINORITY-CLASS ANALYSIS]
Classes ordered by Independent Test support:

,class_id,class_name,support,support_percentage,precision,recall,f1,false_negatives
8,8,Heartbleed,1,0.000177,1.000000,1.000000,1.000000,0
6,6,Infiltration,8,0.001415,1.000000,0.500000,0.666667,4
4,4,Bot,399,0.070556,0.562802,0.583960,0.573186,166
5,5,Web Attack,428,0.075684,0.981132,0.971963,0.976526,12
3,3,Brute Force,2648,0.468250,0.990421,0.976208,0.983264,63
1,1,DDoS,25601,4.527064,0.999687,0.999492,0.999590,13
2,2,Port Scan,31946,5.649060,0.993975,0.996682,0.995327,106
7,7,DoS,49080,8.678892,0.994985,0.954014,0.974069,2257
0,0,BENIGN,455399,80.528903,0.994317,0.998619,0.996464,629

✓ Lowest-support class = Heartbleed
✓ Lowest-support observations = 1

[CLASS-WISE ERROR RANKING]

,class_id,class_name,support,recall,f1,false_positives,false_negatives
7,7,DoS,49080,0.954014,0.974069,236,2257
0,0,BENIGN,455399,0.998619,0.996464,2599,629
4,4,Bot,399,0.583960,0.573186,181,166
2,2,Port Scan,31946,0.996682,0.995327,193,106
3,3,Brute Force,2648,0.976208,0.983264,25,63
1,1,DDoS,25601,0.999492,0.999590,8,13
5,5,Web Attack,428,0.971963,0.976526,8,12
6,6,Infiltration,8,0.500000,0.666667,0,4
8,8,Heartbleed,1,1.000000,1.000000,0,0

✓ Class-wise error ranking generated

[CLASS-WISE ERROR ANALYSIS SUMMARY]
✓ Highest F1 performance : Heartbleed (1.000000)
✓ Lowest F1 performance  : Bot (0.573186)
✓ Lowest Recall          : Infiltration (0.500000)
✓ Total attack FNs       : 2,621
✓ BENIGN false positives : 2,599
✓ BENIGN FPR             : 0.023603
✓ Lowest-support class   : Heartbleed (1 observations)

[ERROR-ANALYSIS OPERATION BOUNDARY]
✓ Analysis performed only from persisted evaluation artifacts
✓ No Independent Test feature arrays loaded
✓ No Independent Test target arrays loaded
✓ No new predictions generated
✓ No model fitting performed
✓ No resampling performed
✓ No hyperparameter selection performed
✓ No strategy selection performed
✓ Persisted Test artifacts remain unchanged

[5.13.3 CLASS-WISE ERROR ANALYSIS READINESS GATE]
✓ Nine-class performance table generated
✓ Classification-report support validated
✓ Confusion-matrix support validated
✓ Class-wise false positives derived
✓ Class-wise false negatives derived
✓ Class-wise error rates calculated
✓ Highest and lowest F1 classes identified
✓ Lowest-recall class identified
✓ Attack false negatives validated
✓ BENIGN false-positive rate validated
✓ Low-support classes analyzed
✓ Class-wise error ranking generated
✓ No Test arrays loaded
✓ No new predictions generated
✓ No model fitting performed
✓ No resampling performed
✓ No strategy selection performed
✓ Persisted evaluation artifacts remain unchanged

========================================================================
5.13.3 — CLASS-WISE PERFORMANCE AND ERROR ANALYSIS PASSED
========================================================================

READY FOR 5.13.4 — CONFUSION PATTERN AND MINORITY-CLASS ANALYSIS
========================================================================

## 5.13.4 — Confusion Pattern and Minority-Class Analysis

This subsection analyzes the detailed confusion patterns of the final RF-3
Random Forest using the persisted Independent Test confusion matrix and the
class-wise analysis established in Section 5.13.3.

The analysis identifies:

- the largest non-diagonal confusion pairs,
- attack instances incorrectly classified as BENIGN,
- BENIGN instances incorrectly classified as attack classes,
- attack-to-attack confusion patterns,
- the dominant misclassification destination for each class,
- the concentration of classification errors across classes, and
- the behavior of the lowest-support classes in the Independent Test set.

The lowest-support classes are examined descriptively rather than through a
new arbitrary numerical minority-class threshold. This preserves the
established project methodology and avoids introducing an additional
classification rule during interpretation.

All analysis is derived from the persisted Independent Test evaluation
artifacts. No Independent Test feature or target arrays are loaded, and no
new predictions are generated.

No model fitting, resampling, hyperparameter selection, or RF strategy
selection is performed. The persisted evaluation artifacts remain unchanged.

In [ ]:
# ================================================================
# 5.13.4 — CONFUSION PATTERN AND MINORITY-CLASS ANALYSIS
# ================================================================

print("=" * 72)
print("5.13.4 — CONFUSION PATTERN AND MINORITY-CLASS ANALYSIS")
print("=" * 72)


# ---------------------------------------------------------------
# 1. PREVIOUS-SUBSECTION COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[PREVIOUS-SUBSECTION COMPLETION BOUNDARY]")

assert "RF_5_13_3_VALIDATION" in globals()
assert all(RF_5_13_3_VALIDATION.values())

assert "RF_5_13_CONFUSION_MATRIX" in globals()
assert "RF_5_13_3_CLASS_WISE_ANALYSIS" in globals()

print("✓ Section 5.13.3 validation completed")
print("✓ Persisted confusion matrix available")
print("✓ Class-wise performance analysis available")


# ---------------------------------------------------------------
# 2. FROZEN CONFUSION-MATRIX CONTRACT
# ---------------------------------------------------------------

print("\n[FROZEN CONFUSION-MATRIX CONTRACT]")

assert RF_5_13_CONFUSION_MATRIX.shape == (9, 9)

assert (
    RF_5_13_CONFUSION_MATRIX.index.tolist()
    == RF_5_13_3_CLASS_NAMES
)

assert (
    RF_5_13_CONFUSION_MATRIX.columns.tolist()
    == RF_5_13_3_CLASS_NAMES
)

RF_5_13_4_CONFUSION_VALUES = (
    RF_5_13_CONFUSION_MATRIX
    .loc[
        RF_5_13_3_CLASS_NAMES,
        RF_5_13_3_CLASS_NAMES
    ]
    .to_numpy(dtype=np.int64)
)

assert (RF_5_13_4_CONFUSION_VALUES >= 0).all()

assert (
    RF_5_13_4_CONFUSION_VALUES.sum()
    == EXPECTED_RF_PARTITION_ROWS["Test"]
)

print("✓ Nine-class confusion matrix confirmed")
print("✓ Frozen class ordering confirmed")
print("✓ Confusion counts are non-negative")
print(
    f"✓ Confusion matrix total = "
    f"{int(RF_5_13_4_CONFUSION_VALUES.sum()):,}"
)


# ---------------------------------------------------------------
# 3. NON-DIAGONAL CONFUSION PAIRS
# ---------------------------------------------------------------

print("\n[NON-DIAGONAL CONFUSION PAIRS]")

RF_5_13_4_CONFUSION_PAIR_ROWS = []

for actual_index, actual_class in enumerate(
    RF_5_13_3_CLASS_NAMES
):

    for predicted_index, predicted_class in enumerate(
        RF_5_13_3_CLASS_NAMES
    ):

        if actual_index == predicted_index:
            continue

        confusion_count = int(
            RF_5_13_4_CONFUSION_VALUES[
                actual_index,
                predicted_index
            ]
        )

        if confusion_count > 0:
            RF_5_13_4_CONFUSION_PAIR_ROWS.append(
                {
                    "actual_class_id": actual_index,
                    "actual_class": actual_class,
                    "predicted_class_id": predicted_index,
                    "predicted_class": predicted_class,
                    "confusion_count": confusion_count,
                }
            )

RF_5_13_4_CONFUSION_PAIRS = (
    pd.DataFrame(
        RF_5_13_4_CONFUSION_PAIR_ROWS
    )
    .sort_values(
        "confusion_count",
        ascending=False
    )
    .reset_index(drop=True)
)

assert (
    RF_5_13_4_CONFUSION_PAIRS["confusion_count"] > 0
).all()

print(
    f"✓ Non-zero confusion pairs = "
    f"{len(RF_5_13_4_CONFUSION_PAIRS)}"
)

print("\nTop non-diagonal confusion pairs:")

display(
    RF_5_13_4_CONFUSION_PAIRS.head(15)
)


# ---------------------------------------------------------------
# 4. ATTACK → BENIGN CONFUSION
# ---------------------------------------------------------------

print("\n[ATTACK → BENIGN CONFUSION ANALYSIS]")

RF_5_13_4_ATTACK_TO_BENIGN = (
    RF_5_13_4_CONFUSION_PAIRS[
        (
            RF_5_13_4_CONFUSION_PAIRS[
                "actual_class_id"
            ] != 0
        )
        &
        (
            RF_5_13_4_CONFUSION_PAIRS[
                "predicted_class_id"
            ] == 0
        )
    ]
    .copy()
    .sort_values(
        "confusion_count",
        ascending=False
    )
    .reset_index(drop=True)
)

RF_5_13_4_TOTAL_ATTACK_TO_BENIGN = int(
    RF_5_13_4_ATTACK_TO_BENIGN[
        "confusion_count"
    ].sum()
)

# Attack → BENIGN is equivalent to the
# false positives of the BENIGN class.
assert (
    RF_5_13_4_TOTAL_ATTACK_TO_BENIGN
    == RF_5_13_3_BENIGN_FALSE_POSITIVES
)

print(
    f"✓ Total attack → BENIGN errors = "
    f"{RF_5_13_4_TOTAL_ATTACK_TO_BENIGN:,}"
)

print(
    "✓ Attack → BENIGN total matches "
    "validated BENIGN false positives"
)

display(
    RF_5_13_4_ATTACK_TO_BENIGN
)


# ---------------------------------------------------------------
# 5. BENIGN → ATTACK CONFUSION
# ---------------------------------------------------------------

print("\n[BENIGN → ATTACK CONFUSION ANALYSIS]")

RF_5_13_4_BENIGN_TO_ATTACK = (
    RF_5_13_4_CONFUSION_PAIRS[
        (
            RF_5_13_4_CONFUSION_PAIRS[
                "actual_class_id"
            ] == 0
        )
        &
        (
            RF_5_13_4_CONFUSION_PAIRS[
                "predicted_class_id"
            ] != 0
        )
    ]
    .copy()
    .sort_values(
        "confusion_count",
        ascending=False
    )
    .reset_index(drop=True)
)

RF_5_13_4_TOTAL_BENIGN_TO_ATTACK = int(
    RF_5_13_4_BENIGN_TO_ATTACK[
        "confusion_count"
    ].sum()
)

# BENIGN → attack represents actual BENIGN
# observations incorrectly classified as attacks.
# It is intentionally NOT compared with BENIGN FPs.
RF_5_13_4_EXPECTED_BENIGN_TO_ATTACK = int(
    RF_5_13_4_CONFUSION_VALUES[
        0, 1:
    ].sum()
)

assert (
    RF_5_13_4_TOTAL_BENIGN_TO_ATTACK
    == RF_5_13_4_EXPECTED_BENIGN_TO_ATTACK
)

print(
    f"✓ Total BENIGN → attack errors = "
    f"{RF_5_13_4_TOTAL_BENIGN_TO_ATTACK:,}"
)

print(
    "✓ BENIGN → attack confusion accounting validated"
)

display(
    RF_5_13_4_BENIGN_TO_ATTACK
)


# ---------------------------------------------------------------
# 6. ATTACK → ATTACK CONFUSION
# ---------------------------------------------------------------

print("\n[ATTACK → ATTACK CONFUSION ANALYSIS]")

RF_5_13_4_ATTACK_TO_ATTACK = (
    RF_5_13_4_CONFUSION_PAIRS[
        (
            RF_5_13_4_CONFUSION_PAIRS[
                "actual_class_id"
            ] != 0
        )
        &
        (
            RF_5_13_4_CONFUSION_PAIRS[
                "predicted_class_id"
            ] != 0
        )
    ]
    .copy()
    .sort_values(
        "confusion_count",
        ascending=False
    )
    .reset_index(drop=True)
)

RF_5_13_4_TOTAL_ATTACK_TO_ATTACK = int(
    RF_5_13_4_ATTACK_TO_ATTACK[
        "confusion_count"
    ].sum()
)

RF_5_13_4_EXPECTED_ATTACK_TO_ATTACK = int(
    RF_5_13_4_CONFUSION_VALUES[
        1:, 1:
    ].sum()
    -
    np.trace(
        RF_5_13_4_CONFUSION_VALUES[
            1:, 1:
        ]
    )
)

assert (
    RF_5_13_4_TOTAL_ATTACK_TO_ATTACK
    == RF_5_13_4_EXPECTED_ATTACK_TO_ATTACK
)

print(
    f"✓ Total attack → attack confusions = "
    f"{RF_5_13_4_TOTAL_ATTACK_TO_ATTACK:,}"
)

if len(RF_5_13_4_ATTACK_TO_ATTACK) > 0:
    display(
        RF_5_13_4_ATTACK_TO_ATTACK
    )
else:
    print(
        "✓ No attack → attack confusion pairs detected"
    )


# ---------------------------------------------------------------
# 7. ATTACK FALSE-NEGATIVE ACCOUNTING
# ---------------------------------------------------------------

print("\n[ATTACK FALSE-NEGATIVE ACCOUNTING]")

# Attack false negatives consist of:
#
#   Attack → BENIGN
#   +
#   Attack → another attack class

RF_5_13_4_TOTAL_ATTACK_FALSE_NEGATIVES = (
    RF_5_13_4_TOTAL_ATTACK_TO_BENIGN
    +
    RF_5_13_4_TOTAL_ATTACK_TO_ATTACK
)

assert (
    RF_5_13_4_TOTAL_ATTACK_FALSE_NEGATIVES
    == RF_5_13_3_TOTAL_ATTACK_FALSE_NEGATIVES
)

print(
    f"✓ Attack → BENIGN errors : "
    f"{RF_5_13_4_TOTAL_ATTACK_TO_BENIGN:,}"
)

print(
    f"✓ Attack → attack errors : "
    f"{RF_5_13_4_TOTAL_ATTACK_TO_ATTACK:,}"
)

print(
    f"✓ Total attack false negatives : "
    f"{RF_5_13_4_TOTAL_ATTACK_FALSE_NEGATIVES:,}"
)

print(
    "✓ Attack false-negative accounting reconciled"
)


# ---------------------------------------------------------------
# 8. DOMINANT ERROR DESTINATION FOR EACH CLASS
# ---------------------------------------------------------------

print("\n[DOMINANT ERROR DESTINATION ANALYSIS]")

RF_5_13_4_DOMINANT_ERROR_ROWS = []

for actual_index, actual_class in enumerate(
    RF_5_13_3_CLASS_NAMES
):

    actual_row = (
        RF_5_13_4_CONFUSION_VALUES[
            actual_index
        ]
        .copy()
    )

    actual_row[actual_index] = 0

    dominant_prediction_index = int(
        np.argmax(actual_row)
    )

    dominant_error_count = int(
        actual_row[
            dominant_prediction_index
        ]
    )

    RF_5_13_4_DOMINANT_ERROR_ROWS.append(
        {
            "actual_class_id": actual_index,
            "actual_class": actual_class,
            "dominant_error_prediction_id":
                dominant_prediction_index,
            "dominant_error_prediction":
                RF_5_13_3_CLASS_NAMES[
                    dominant_prediction_index
                ],
            "error_count":
                dominant_error_count,
        }
    )

RF_5_13_4_DOMINANT_ERROR_ANALYSIS = (
    pd.DataFrame(
        RF_5_13_4_DOMINANT_ERROR_ROWS
    )
)

assert (
    len(
        RF_5_13_4_DOMINANT_ERROR_ANALYSIS
    )
    == 9
)

print(
    "✓ Dominant error destination identified "
    "for all nine classes"
)

display(
    RF_5_13_4_DOMINANT_ERROR_ANALYSIS
)


# ---------------------------------------------------------------
# 9. ERROR CONCENTRATION BY ACTUAL CLASS
# ---------------------------------------------------------------

print("\n[ERROR CONCENTRATION BY ACTUAL CLASS]")

RF_5_13_4_ERROR_CONCENTRATION = (
    RF_5_13_3_CLASS_WISE_ANALYSIS[
        [
            "class_id",
            "class_name",
            "support",
            "false_negatives",
            "false_positives",
        ]
    ]
    .copy()
)

RF_5_13_4_ERROR_CONCENTRATION[
    "false_negative_rate"
] = (
    RF_5_13_4_ERROR_CONCENTRATION[
        "false_negatives"
    ]
    /
    RF_5_13_4_ERROR_CONCENTRATION[
        "support"
    ]
)

RF_5_13_4_ERROR_CONCENTRATION[
    "support_percentage"
] = (
    RF_5_13_4_ERROR_CONCENTRATION[
        "support"
    ]
    /
    EXPECTED_RF_PARTITION_ROWS["Test"]
    * 100.0
)

assert np.isfinite(
    RF_5_13_4_ERROR_CONCENTRATION[
        "false_negative_rate"
    ]
).all()

assert np.isfinite(
    RF_5_13_4_ERROR_CONCENTRATION[
        "support_percentage"
    ]
).all()

RF_5_13_4_ERROR_CONCENTRATION = (
    RF_5_13_4_ERROR_CONCENTRATION
    .sort_values(
        "false_negatives",
        ascending=False
    )
    .reset_index(drop=True)
)

display(
    RF_5_13_4_ERROR_CONCENTRATION
)

print(
    "✓ Error concentration by actual class calculated"
)


# ---------------------------------------------------------------
# 10. LOWEST-SUPPORT CLASS ANALYSIS
# ---------------------------------------------------------------

print("\n[LOWEST-SUPPORT CLASS ANALYSIS]")

RF_5_13_4_LOW_SUPPORT_ANALYSIS = (
    RF_5_13_3_CLASS_WISE_ANALYSIS[
        [
            "class_id",
            "class_name",
            "support",
            "support_percentage",
            "precision",
            "recall",
            "f1",
            "false_positives",
            "false_negatives",
        ]
    ]
    .copy()
    .sort_values(
        [
            "support",
            "class_id",
        ],
        ascending=[
            True,
            True,
        ]
    )
    .reset_index(drop=True)
)

RF_5_13_4_LOWEST_SUPPORT_CLASSES = (
    RF_5_13_4_LOW_SUPPORT_ANALYSIS
    .head(3)
    .copy()
)

assert (
    len(
        RF_5_13_4_LOWEST_SUPPORT_CLASSES
    )
    == 3
)

print(
    "✓ Three lowest-support classes identified "
    "for descriptive minority-class analysis"
)

display(
    RF_5_13_4_LOWEST_SUPPORT_CLASSES
)


# ---------------------------------------------------------------
# 11. LOWEST-SUPPORT CLASS CONFUSION PATTERNS
# ---------------------------------------------------------------

print("\n[LOWEST-SUPPORT CLASS CONFUSION PATTERNS]")

RF_5_13_4_LOW_SUPPORT_CLASS_IDS = (
    RF_5_13_4_LOWEST_SUPPORT_CLASSES[
        "class_id"
    ].to_numpy(dtype=np.int64)
)

RF_5_13_4_LOW_SUPPORT_CONFUSIONS = (
    RF_5_13_4_CONFUSION_PAIRS[
        RF_5_13_4_CONFUSION_PAIRS[
            "actual_class_id"
        ].isin(
            RF_5_13_4_LOW_SUPPORT_CLASS_IDS
        )
    ]
    .copy()
    .reset_index(drop=True)
)

if len(
    RF_5_13_4_LOW_SUPPORT_CONFUSIONS
) > 0:

    display(
        RF_5_13_4_LOW_SUPPORT_CONFUSIONS
    )

else:

    print(
        "✓ No non-zero confusion pairs originate "
        "from the three lowest-support classes"
    )


# ---------------------------------------------------------------
# 12. CONFUSION ACCOUNTING VALIDATION
# ---------------------------------------------------------------

print("\n[CONFUSION ACCOUNTING VALIDATION]")

RF_5_13_4_CORRECT_CLASSIFICATIONS = int(
    np.trace(
        RF_5_13_4_CONFUSION_VALUES
    )
)

RF_5_13_4_TOTAL_MISCLASSIFICATIONS = int(
    RF_5_13_4_CONFUSION_VALUES.sum()
    -
    RF_5_13_4_CORRECT_CLASSIFICATIONS
)

RF_5_13_4_OFF_DIAGONAL_TOTAL = int(
    RF_5_13_4_CONFUSION_PAIRS[
        "confusion_count"
    ].sum()
)

assert (
    RF_5_13_4_TOTAL_MISCLASSIFICATIONS
    == RF_5_13_4_OFF_DIAGONAL_TOTAL
)

assert (
    RF_5_13_4_CORRECT_CLASSIFICATIONS
    +
    RF_5_13_4_TOTAL_MISCLASSIFICATIONS
    ==
    EXPECTED_RF_PARTITION_ROWS["Test"]
)

print(
    f"✓ Correct classifications = "
    f"{RF_5_13_4_CORRECT_CLASSIFICATIONS:,}"
)

print(
    f"✓ Total misclassifications = "
    f"{RF_5_13_4_TOTAL_MISCLASSIFICATIONS:,}"
)

print(
    f"✓ Off-diagonal confusion total = "
    f"{RF_5_13_4_OFF_DIAGONAL_TOTAL:,}"
)

print(
    f"✓ Test accounting total = "
    f"{(
        RF_5_13_4_CORRECT_CLASSIFICATIONS
        +
        RF_5_13_4_TOTAL_MISCLASSIFICATIONS
    ):,}"
)


# ---------------------------------------------------------------
# 13. CONFUSION PATTERN SUMMARY
# ---------------------------------------------------------------

print("\n[CONFUSION PATTERN SUMMARY]")

RF_5_13_4_TOP_CONFUSION_PAIR = (
    RF_5_13_4_CONFUSION_PAIRS.iloc[0]
)

print(
    f"✓ Largest confusion pair : "
    f"{RF_5_13_4_TOP_CONFUSION_PAIR['actual_class']} "
    f"→ "
    f"{RF_5_13_4_TOP_CONFUSION_PAIR['predicted_class']} "
    f"("
    f"{int(
        RF_5_13_4_TOP_CONFUSION_PAIR[
            'confusion_count'
        ]
    ):,}"
    f")"
)

print(
    f"✓ Attack → BENIGN errors : "
    f"{RF_5_13_4_TOTAL_ATTACK_TO_BENIGN:,}"
)

print(
    f"✓ BENIGN → attack errors : "
    f"{RF_5_13_4_TOTAL_BENIGN_TO_ATTACK:,}"
)

print(
    f"✓ Attack → attack errors : "
    f"{RF_5_13_4_TOTAL_ATTACK_TO_ATTACK:,}"
)

print(
    f"✓ Total attack false negatives : "
    f"{RF_5_13_4_TOTAL_ATTACK_FALSE_NEGATIVES:,}"
)

print(
    f"✓ Total misclassifications : "
    f"{RF_5_13_4_TOTAL_MISCLASSIFICATIONS:,}"
)


# ---------------------------------------------------------------
# 14. ERROR-ANALYSIS OPERATION BOUNDARY
# ---------------------------------------------------------------

print("\n[ERROR-ANALYSIS OPERATION BOUNDARY]")

print(
    "✓ Analysis performed only from persisted evaluation artifacts"
)

print(
    "✓ No Independent Test feature arrays loaded"
)

print(
    "✓ No Independent Test target arrays loaded"
)

print(
    "✓ No new predictions generated"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No hyperparameter selection performed"
)

print(
    "✓ No strategy selection performed"
)

print(
    "✓ Persisted Test artifacts remain unchanged"
)


# ---------------------------------------------------------------
# 15. SECTION 5.13.4 VALIDATION STATE
# ---------------------------------------------------------------

RF_5_13_4_VALIDATION = {

    "section_5_13_3_completed":
        all(
            RF_5_13_3_VALIDATION.values()
        ),

    "confusion_matrix_shape_valid":
        (
            RF_5_13_4_CONFUSION_VALUES.shape
            == (9, 9)
        ),

    "class_order_valid":
        (
            RF_5_13_CONFUSION_MATRIX.index.tolist()
            == RF_5_13_3_CLASS_NAMES
            and
            RF_5_13_CONFUSION_MATRIX.columns.tolist()
            == RF_5_13_3_CLASS_NAMES
        ),

    "confusion_matrix_total_valid":
        (
            RF_5_13_4_CONFUSION_VALUES.sum()
            == EXPECTED_RF_PARTITION_ROWS["Test"]
        ),

    "attack_to_benign_valid":
        (
            RF_5_13_4_TOTAL_ATTACK_TO_BENIGN
            == RF_5_13_3_BENIGN_FALSE_POSITIVES
        ),

    "benign_to_attack_valid":
        (
            RF_5_13_4_TOTAL_BENIGN_TO_ATTACK
            == RF_5_13_4_EXPECTED_BENIGN_TO_ATTACK
        ),

    "attack_false_negative_accounting_valid":
        (
            RF_5_13_4_TOTAL_ATTACK_FALSE_NEGATIVES
            == RF_5_13_3_TOTAL_ATTACK_FALSE_NEGATIVES
        ),

    "confusion_accounting_valid":
        (
            RF_5_13_4_CORRECT_CLASSIFICATIONS
            +
            RF_5_13_4_TOTAL_MISCLASSIFICATIONS
            ==
            EXPECTED_RF_PARTITION_ROWS["Test"]
        ),

    "lowest_support_classes_identified":
        (
            len(
                RF_5_13_4_LOWEST_SUPPORT_CLASSES
            )
            == 3
        ),

    "no_test_arrays_loaded":
        True,

    "no_new_predictions":
        True,

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_strategy_selection":
        True,
}


assert all(
    RF_5_13_4_VALIDATION.values()
), (
    "Section 5.13.4 confusion-pattern analysis "
    "validation is incomplete."
)


# ---------------------------------------------------------------
# 16. FINAL 5.13.4 READINESS GATE
# ---------------------------------------------------------------

print("\n[5.13.4 CONFUSION PATTERN READINESS GATE]")

print("✓ Nine-class confusion matrix validated")
print("✓ Non-diagonal confusion pairs identified")
print("✓ Attack → BENIGN confusion analyzed")
print("✓ BENIGN → attack confusion analyzed")
print("✓ Attack → attack confusion analyzed")
print("✓ Attack false-negative accounting reconciled")
print("✓ Dominant error destination identified per class")
print("✓ Error concentration by actual class calculated")
print("✓ Lowest-support classes identified")
print("✓ Lowest-support confusion patterns analyzed")
print("✓ Confusion-matrix accounting validated")
print("✓ No Test arrays loaded")
print("✓ No new predictions generated")
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No strategy selection performed")
print("✓ Persisted evaluation artifacts remain unchanged")

print("\n" + "=" * 72)

print(
    "5.13.4 — CONFUSION PATTERN "
    "AND MINORITY-CLASS ANALYSIS PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.13.5 — Final Random Forest Feature Importance Analysis"
)

print("=" * 72)

========================================================================
5.13.4 — CONFUSION PATTERN AND MINORITY-CLASS ANALYSIS
========================================================================

[PREVIOUS-SUBSECTION COMPLETION BOUNDARY]
✓ Section 5.13.3 validation completed
✓ Persisted confusion matrix available
✓ Class-wise performance analysis available

[FROZEN CONFUSION-MATRIX CONTRACT]
✓ Nine-class confusion matrix confirmed
✓ Frozen class ordering confirmed
✓ Confusion counts are non-negative
✓ Confusion matrix total = 565,510

[NON-DIAGONAL CONFUSION PAIRS]
✓ Non-zero confusion pairs = 17

Top non-diagonal confusion pairs:

,actual_class_id,actual_class,predicted_class_id,predicted_class,confusion_count
0,7,DoS,0,BENIGN,2250
1,0,BENIGN,7,DoS,224
2,0,BENIGN,2,Port Scan,191
3,0,BENIGN,4,Bot,181
4,4,Bot,0,BENIGN,166
5,2,Port Scan,0,BENIGN,97
6,3,Brute Force,0,BENIGN,63
7,0,BENIGN,3,Brute Force,25
8,1,DDoS,0,BENIGN,13
9,0,BENIGN,1,DDoS,8
10,2,Port Scan,7,DoS,6
11,5,Web Attack,7,DoS,6
12,5,Web Attack,0,BENIGN,6
13,7,DoS,5,Web Attack,5
14,6,Infiltration,0,BENIGN,4

[ATTACK → BENIGN CONFUSION ANALYSIS]
✓ Total attack → BENIGN errors = 2,599
✓ Attack → BENIGN total matches validated BENIGN false positives

,actual_class_id,actual_class,predicted_class_id,predicted_class,confusion_count
0,7,DoS,0,BENIGN,2250
1,4,Bot,0,BENIGN,166
2,2,Port Scan,0,BENIGN,97
3,3,Brute Force,0,BENIGN,63
4,1,DDoS,0,BENIGN,13
5,5,Web Attack,0,BENIGN,6
6,6,Infiltration,0,BENIGN,4

[BENIGN → ATTACK CONFUSION ANALYSIS]
✓ Total BENIGN → attack errors = 629
✓ BENIGN → attack confusion accounting validated

,actual_class_id,actual_class,predicted_class_id,predicted_class,confusion_count
0,0,BENIGN,7,DoS,224
1,0,BENIGN,2,Port Scan,191
2,0,BENIGN,4,Bot,181
3,0,BENIGN,3,Brute Force,25
4,0,BENIGN,1,DDoS,8

[ATTACK → ATTACK CONFUSION ANALYSIS]
✓ Total attack → attack confusions = 22

,actual_class_id,actual_class,predicted_class_id,predicted_class,confusion_count
0,2,Port Scan,7,DoS,6
1,5,Web Attack,7,DoS,6
2,7,DoS,5,Web Attack,5
3,2,Port Scan,5,Web Attack,3
4,7,DoS,2,Port Scan,2

[ATTACK FALSE-NEGATIVE ACCOUNTING]
✓ Attack → BENIGN errors : 2,599
✓ Attack → attack errors : 22
✓ Total attack false negatives : 2,621
✓ Attack false-negative accounting reconciled

[DOMINANT ERROR DESTINATION ANALYSIS]
✓ Dominant error destination identified for all nine classes

,actual_class_id,actual_class,dominant_error_prediction_id,dominant_error_prediction,error_count
0,0,BENIGN,7,DoS,224
1,1,DDoS,0,BENIGN,13
2,2,Port Scan,0,BENIGN,97
3,3,Brute Force,0,BENIGN,63
4,4,Bot,0,BENIGN,166
5,5,Web Attack,0,BENIGN,6
6,6,Infiltration,0,BENIGN,4
7,7,DoS,0,BENIGN,2250
8,8,Heartbleed,0,BENIGN,0

[ERROR CONCENTRATION BY ACTUAL CLASS]

,class_id,class_name,support,false_negatives,false_positives,false_negative_rate,support_percentage
0,7,DoS,49080,2257,236,0.045986,8.678892
1,0,BENIGN,455399,629,2599,0.001381,80.528903
2,4,Bot,399,166,181,0.416040,0.070556
3,2,Port Scan,31946,106,193,0.003318,5.649060
4,3,Brute Force,2648,63,25,0.023792,0.468250
5,1,DDoS,25601,13,8,0.000508,4.527064
6,5,Web Attack,428,12,8,0.028037,0.075684
7,6,Infiltration,8,4,0,0.500000,0.001415
8,8,Heartbleed,1,0,0,0.000000,0.000177

✓ Error concentration by actual class calculated

[LOWEST-SUPPORT CLASS ANALYSIS]
✓ Three lowest-support classes identified for descriptive minority-class analysis

,class_id,class_name,support,support_percentage,precision,recall,f1,false_positives,false_negatives
0,8,Heartbleed,1,0.000177,1.000000,1.00000,1.000000,0,0
1,6,Infiltration,8,0.001415,1.000000,0.50000,0.666667,0,4
2,4,Bot,399,0.070556,0.562802,0.58396,0.573186,181,166

[LOWEST-SUPPORT CLASS CONFUSION PATTERNS]

,actual_class_id,actual_class,predicted_class_id,predicted_class,confusion_count
0,4,Bot,0,BENIGN,166
1,6,Infiltration,0,BENIGN,4

[CONFUSION ACCOUNTING VALIDATION]
✓ Correct classifications = 562,260
✓ Total misclassifications = 3,250
✓ Off-diagonal confusion total = 3,250
✓ Test accounting total = 565,510

[CONFUSION PATTERN SUMMARY]
✓ Largest confusion pair : DoS → BENIGN (2,250)
✓ Attack → BENIGN errors : 2,599
✓ BENIGN → attack errors : 629
✓ Attack → attack errors : 22
✓ Total attack false negatives : 2,621
✓ Total misclassifications : 3,250

[ERROR-ANALYSIS OPERATION BOUNDARY]
✓ Analysis performed only from persisted evaluation artifacts
✓ No Independent Test feature arrays loaded
✓ No Independent Test target arrays loaded
✓ No new predictions generated
✓ No model fitting performed
✓ No resampling performed
✓ No hyperparameter selection performed
✓ No strategy selection performed
✓ Persisted Test artifacts remain unchanged

[5.13.4 CONFUSION PATTERN READINESS GATE]
✓ Nine-class confusion matrix validated
✓ Non-diagonal confusion pairs identified
✓ Attack → BENIGN confusion analyzed
✓ BENIGN → attack confusion analyzed
✓ Attack → attack confusion analyzed
✓ Attack false-negative accounting reconciled
✓ Dominant error destination identified per class
✓ Error concentration by actual class calculated
✓ Lowest-support classes identified
✓ Lowest-support confusion patterns analyzed
✓ Confusion-matrix accounting validated
✓ No Test arrays loaded
✓ No new predictions generated
✓ No model fitting performed
✓ No resampling performed
✓ No strategy selection performed
✓ Persisted evaluation artifacts remain unchanged

========================================================================
5.13.4 — CONFUSION PATTERN AND MINORITY-CLASS ANALYSIS PASSED
========================================================================

READY FOR 5.13.5 — Final Random Forest Feature Importance Analysis
========================================================================

## 5.13.5 — Final Random Forest Feature Importance Analysis

This subsection analyzes the fitted feature importance values of the persisted
final RF-3 Random Forest model.

The persisted final Random Forest model is loaded as a read-only analytical
artifact. Its fitted `feature_importances_` vector is validated against the
authoritative 32-feature `RF_FEATURE_ORDER` established during model
preparation.

The analysis:

- validates the final model feature-importance vector,
- aligns each importance value with the authoritative RF feature order,
- verifies that all importance values are finite and non-negative,
- verifies that the feature-importance values form a valid normalized
  distribution,
- ranks all 32 model-ready features by importance,
- identifies the most and least influential features, and
- persists the final Random Forest feature-importance table under the
  established RF interpretation directory.

The feature importance is derived directly from the fitted final Random
Forest model and does not involve the Independent Test partition.

No Independent Test feature or target arrays are loaded. No new predictions,
model fitting, resampling, hyperparameter selection, or RF strategy selection
is performed.

The persisted final model and previously persisted Independent Test
evaluation artifacts remain unchanged.

In [ ]:
# ================================================================
# 5.13.5 — FINAL RANDOM FOREST FEATURE IMPORTANCE ANALYSIS
# FINAL CORRECTION AND VALIDATION
# ================================================================

print("=" * 72)
print("5.13.5 — FINAL RANDOM FOREST FEATURE IMPORTANCE ANALYSIS")
print("FINAL CORRECTION AND VALIDATION")
print("=" * 72)


# ---------------------------------------------------------------
# 1. ESTABLISHED RF FEATURE-IMPORTANCE CONTRACT
# ---------------------------------------------------------------

print("\n[ESTABLISHED RF FEATURE-IMPORTANCE CONTRACT]")

assert "RF_FEATURE_ORDER" in globals(), (
    "Authoritative RF feature order is unavailable."
)

assert "RF_EXPERIMENT_ARTIFACTS" in globals(), (
    "Established RF artifact mapping is unavailable."
)

assert (
    "final_model" in RF_EXPERIMENT_ARTIFACTS
), (
    "Final Random Forest model artifact path is unavailable."
)

assert (
    "feature_importance" in RF_EXPERIMENT_ARTIFACTS
), (
    "Final feature-importance artifact path is unavailable."
)

assert (
    len(RF_FEATURE_ORDER)
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

assert (
    len(set(RF_FEATURE_ORDER))
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

print(
    f"✓ RF feature count = "
    f"{EXPECTED_MODEL_READY_FEATURE_COUNT}"
)

print("✓ RF feature order is unique and frozen")

print(
    "✓ Established feature-importance artifact path available"
)


# ---------------------------------------------------------------
# 2. LOAD PERSISTED FINAL RF-3 MODEL
# ---------------------------------------------------------------

print("\n[PERSISTED FINAL RF-3 MODEL VALIDATION]")

RF_5_13_5_FINAL_MODEL_PATH = (
    RF_EXPERIMENT_ARTIFACTS[
        "final_model"
    ]
)

RF_5_13_5_FEATURE_IMPORTANCE_PATH = (
    RF_EXPERIMENT_ARTIFACTS[
        "feature_importance"
    ]
)

assert RF_5_13_5_FINAL_MODEL_PATH.is_file(), (
    "Persisted final Random Forest model is unavailable."
)

RF_5_13_5_FINAL_MODEL = joblib.load(
    RF_5_13_5_FINAL_MODEL_PATH
)

assert hasattr(
    RF_5_13_5_FINAL_MODEL,
    "feature_importances_"
)

assert (
    RF_5_13_5_FINAL_MODEL.n_features_in_
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

assert np.array_equal(
    RF_5_13_5_FINAL_MODEL.classes_,
    EXPECTED_RF_CLASS_IDS
)

assert (
    RF_5_13_5_FINAL_MODEL.class_weight
    is None
)

assert (
    RF_5_13_5_FINAL_MODEL.random_state
    == RANDOM_SEED
)

print("✓ Persisted final RF-3 model loaded")
print("✓ Final model feature count = 32")
print("✓ Final model nine-class taxonomy validated")
print("✓ Final model class_weight = None")
print(
    f"✓ Final model random_state = "
    f"{RF_5_13_5_FINAL_MODEL.random_state}"
)


# ---------------------------------------------------------------
# 3. EXTRACT FINAL MODEL FEATURE IMPORTANCE
# ---------------------------------------------------------------

print("\n[FINAL MODEL FEATURE-IMPORTANCE EXTRACTION]")

RF_5_13_5_FEATURE_IMPORTANCES = np.asarray(
    RF_5_13_5_FINAL_MODEL.feature_importances_,
    dtype=np.float64
)

assert (
    RF_5_13_5_FEATURE_IMPORTANCES.shape
    == (
        EXPECTED_MODEL_READY_FEATURE_COUNT,
    )
)

assert np.isfinite(
    RF_5_13_5_FEATURE_IMPORTANCES
).all()

assert (
    RF_5_13_5_FEATURE_IMPORTANCES
    >= 0
).all()

RF_5_13_5_FEATURE_IMPORTANCE_SUM = float(
    RF_5_13_5_FEATURE_IMPORTANCES.sum()
)

assert np.isclose(
    RF_5_13_5_FEATURE_IMPORTANCE_SUM,
    1.0,
    atol=1e-10
)

print(
    f"✓ Feature-importance values = "
    f"{len(RF_5_13_5_FEATURE_IMPORTANCES)}"
)

print("✓ All importance values are finite")
print("✓ All importance values are non-negative")
print(
    f"✓ Importance sum = "
    f"{RF_5_13_5_FEATURE_IMPORTANCE_SUM:.12f}"
)


# ---------------------------------------------------------------
# 4. REBUILD ARTIFACT IN AUTHORITATIVE RF FEATURE ORDER
# ---------------------------------------------------------------

print(
    "\n[AUTHORITATIVE FEATURE-IMPORTANCE ARTIFACT "
    "RECONSTRUCTION]"
)

# IMPORTANT:
# The established RF artifact contract stores features in
# RF_FEATURE_ORDER. It must NOT be sorted before persistence.

RF_5_13_5_FEATURE_IMPORTANCE_DF = pd.DataFrame({

    "feature":
        RF_FEATURE_ORDER,

    "importance":
        RF_5_13_5_FEATURE_IMPORTANCES,

})

assert (
    RF_5_13_5_FEATURE_IMPORTANCE_DF[
        "feature"
    ].tolist()
    == list(RF_FEATURE_ORDER)
)

assert (
    len(RF_5_13_5_FEATURE_IMPORTANCE_DF)
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

print(
    "✓ Feature importance aligned with authoritative "
    "RF_FEATURE_ORDER"
)

print(
    "✓ 32-feature feature-importance table constructed"
)


# ---------------------------------------------------------------
# 5. PERSIST CORRECTED FINAL FEATURE IMPORTANCE
# ---------------------------------------------------------------

print("\n[PERSIST FINAL RF FEATURE IMPORTANCE]")

RF_5_13_5_FEATURE_IMPORTANCE_DF[
    [
        "feature",
        "importance",
    ]
].to_csv(
    RF_5_13_5_FEATURE_IMPORTANCE_PATH,
    index=False
)

assert (
    RF_5_13_5_FEATURE_IMPORTANCE_PATH.is_file()
)

assert (
    RF_5_13_5_FEATURE_IMPORTANCE_PATH.stat().st_size
    > 0
)

print(
    f"✓ Final feature-importance artifact persisted:\n"
    f"  {RF_5_13_5_FEATURE_IMPORTANCE_PATH}"
)


# ---------------------------------------------------------------
# 6. RELOAD AND VALIDATE PERSISTED ARTIFACT
# ---------------------------------------------------------------

print("\n[PERSISTED FEATURE-IMPORTANCE VALIDATION]")

RF_5_13_5_PERSISTED_FEATURE_IMPORTANCE = (
    pd.read_csv(
        RF_5_13_5_FEATURE_IMPORTANCE_PATH
    )
)

assert (
    list(
        RF_5_13_5_PERSISTED_FEATURE_IMPORTANCE.columns
    )
    == [
        "feature",
        "importance",
    ]
)

assert (
    len(
        RF_5_13_5_PERSISTED_FEATURE_IMPORTANCE
    )
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

# This is the correct ordering check.
assert (
    RF_5_13_5_PERSISTED_FEATURE_IMPORTANCE[
        "feature"
    ].tolist()
    == list(RF_FEATURE_ORDER)
)

assert np.allclose(
    RF_5_13_5_PERSISTED_FEATURE_IMPORTANCE[
        "importance"
    ].to_numpy(dtype=np.float64),
    RF_5_13_5_FEATURE_IMPORTANCES,
    atol=1e-12
)

assert np.isfinite(
    RF_5_13_5_PERSISTED_FEATURE_IMPORTANCE[
        "importance"
    ].to_numpy(dtype=np.float64)
).all()

assert (
    RF_5_13_5_PERSISTED_FEATURE_IMPORTANCE[
        "importance"
    ]
    >= 0
).all()

assert np.isclose(
    RF_5_13_5_PERSISTED_FEATURE_IMPORTANCE[
        "importance"
    ].sum(),
    1.0,
    atol=1e-10
)

print("✓ Persisted feature-importance schema validated")
print("✓ Persisted table contains all 32 features")
print("✓ Persisted feature order matches RF_FEATURE_ORDER")
print("✓ Persisted importance values match final RF-3 model")
print("✓ Persisted importance values are finite")
print("✓ Persisted importance values are non-negative")
print("✓ Persisted importance values sum to 1")


# ---------------------------------------------------------------
# 7. ANALYTICAL RANKING — WITHOUT MODIFYING THE ARTIFACT
# ---------------------------------------------------------------

print("\n[FEATURE IMPORTANCE RANKING]")

RF_5_13_5_FEATURE_IMPORTANCE_RANKING = (
    RF_5_13_5_PERSISTED_FEATURE_IMPORTANCE
    .copy()
    .sort_values(
        "importance",
        ascending=False
    )
    .reset_index(drop=True)
)

RF_5_13_5_FEATURE_IMPORTANCE_RANKING[
    "rank"
] = np.arange(
    1,
    EXPECTED_MODEL_READY_FEATURE_COUNT + 1
)

RF_5_13_5_FEATURE_IMPORTANCE_RANKING[
    "importance_percentage"
] = (
    RF_5_13_5_FEATURE_IMPORTANCE_RANKING[
        "importance"
    ]
    * 100.0
)

assert (
    len(
        RF_5_13_5_FEATURE_IMPORTANCE_RANKING
    )
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

print("✓ All 32 features ranked by importance")

print("\nTop 10 most important features:")

display(
    RF_5_13_5_FEATURE_IMPORTANCE_RANKING[
        [
            "rank",
            "feature",
            "importance",
            "importance_percentage",
        ]
    ].head(10)
)

print("\nBottom 10 least important features:")

display(
    RF_5_13_5_FEATURE_IMPORTANCE_RANKING[
        [
            "rank",
            "feature",
            "importance",
            "importance_percentage",
        ]
    ].tail(10)
)


# ---------------------------------------------------------------
# 8. FEATURE IMPORTANCE SUMMARY
# ---------------------------------------------------------------

print("\n[FEATURE IMPORTANCE SUMMARY]")

RF_5_13_5_TOP_FEATURE = (
    RF_5_13_5_FEATURE_IMPORTANCE_RANKING.iloc[0]
)

RF_5_13_5_LOWEST_FEATURE = (
    RF_5_13_5_FEATURE_IMPORTANCE_RANKING.iloc[-1]
)

print(
    f"✓ Highest-importance feature : "
    f"{RF_5_13_5_TOP_FEATURE['feature']} "
    f"("
    f"{RF_5_13_5_TOP_FEATURE['importance']:.6f}"
    f")"
)

print(
    f"✓ Lowest-importance feature  : "
    f"{RF_5_13_5_LOWEST_FEATURE['feature']} "
    f"("
    f"{RF_5_13_5_LOWEST_FEATURE['importance']:.6f}"
    f")"
)

print(
    f"✓ Number of analyzed features : "
    f"{len(RF_5_13_5_FEATURE_IMPORTANCE_RANKING)}"
)


# ---------------------------------------------------------------
# 9. ERROR-ANALYSIS OPERATION BOUNDARY
# ---------------------------------------------------------------

print("\n[ERROR-ANALYSIS OPERATION BOUNDARY]")

print(
    "✓ Feature importance derived only from "
    "the persisted final RF-3 model"
)

print(
    "✓ No Independent Test feature arrays loaded"
)

print(
    "✓ No Independent Test target arrays loaded"
)

print(
    "✓ No new Test predictions generated"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No hyperparameter selection performed"
)

print(
    "✓ No RF strategy selection performed"
)

print(
    "✓ Independent Test evaluation artifacts remain unchanged"
)


# ---------------------------------------------------------------
# 10. SECTION 5.13.5 VALIDATION STATE
# ---------------------------------------------------------------

RF_5_13_5_VALIDATION = {

    "section_5_13_4_completed":
        all(
            RF_5_13_4_VALIDATION.values()
        ),

    "final_model_available":
        (
            RF_5_13_5_FINAL_MODEL_PATH.is_file()
            and
            RF_5_13_5_FINAL_MODEL_PATH.stat().st_size > 0
        ),

    "final_model_feature_count_valid":
        (
            RF_5_13_5_FINAL_MODEL.n_features_in_
            == EXPECTED_MODEL_READY_FEATURE_COUNT
        ),

    "final_model_class_taxonomy_valid":
        np.array_equal(
            RF_5_13_5_FINAL_MODEL.classes_,
            EXPECTED_RF_CLASS_IDS
        ),

    "feature_importance_count_valid":
        (
            len(
                RF_5_13_5_FEATURE_IMPORTANCES
            )
            == EXPECTED_MODEL_READY_FEATURE_COUNT
        ),

    "feature_importance_values_valid":
        (
            np.isfinite(
                RF_5_13_5_FEATURE_IMPORTANCES
            ).all()
            and
            (
                RF_5_13_5_FEATURE_IMPORTANCES
                >= 0
            ).all()
        ),

    "feature_importance_sum_valid":
        np.isclose(
            RF_5_13_5_FEATURE_IMPORTANCE_SUM,
            1.0,
            atol=1e-10
        ),

    "feature_order_alignment_valid":
        (
            RF_5_13_5_PERSISTED_FEATURE_IMPORTANCE[
                "feature"
            ].tolist()
            == list(RF_FEATURE_ORDER)
        ),

    "feature_importance_artifact_persisted":
        (
            RF_5_13_5_FEATURE_IMPORTANCE_PATH.is_file()
            and
            RF_5_13_5_FEATURE_IMPORTANCE_PATH.stat().st_size > 0
        ),

    "persisted_feature_importance_valid":
        (
            len(
                RF_5_13_5_PERSISTED_FEATURE_IMPORTANCE
            )
            == EXPECTED_MODEL_READY_FEATURE_COUNT
            and
            np.allclose(
                RF_5_13_5_PERSISTED_FEATURE_IMPORTANCE[
                    "importance"
                ].to_numpy(dtype=np.float64),
                RF_5_13_5_FEATURE_IMPORTANCES,
                atol=1e-12
            )
        ),

    "no_test_arrays_loaded":
        True,

    "no_new_predictions":
        True,

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_strategy_selection":
        True,
}


assert all(
    RF_5_13_5_VALIDATION.values()
), (
    "5.13.5 final feature-importance validation failed."
)


# ---------------------------------------------------------------
# 11. FINAL 5.13.5 READINESS GATE
# ---------------------------------------------------------------

print("\n[5.13.5 FEATURE IMPORTANCE READINESS GATE]")

print("✓ Persisted final RF-3 model validated")
print("✓ 32 feature-importance values extracted")
print("✓ Importance values are finite and non-negative")
print("✓ Importance values sum to 1")
print("✓ Feature order matches frozen RF_FEATURE_ORDER")
print("✓ All 32 features ranked analytically")
print("✓ Final feature-importance artifact persisted")
print("✓ Persisted feature-importance artifact reloaded and validated")
print("✓ No Independent Test arrays loaded")
print("✓ No new Test predictions generated")
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No RF strategy selection performed")
print("✓ Independent Test evaluation artifacts remain unchanged")

print("\n" + "=" * 72)

print(
    "5.13.5 — FINAL RANDOM FOREST "
    "FEATURE IMPORTANCE ANALYSIS PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.13.6 — Error Analysis and Interpretation Artifact Persistence"
)

print("=" * 72)

========================================================================
5.13.5 — FINAL RANDOM FOREST FEATURE IMPORTANCE ANALYSIS
FINAL CORRECTION AND VALIDATION
========================================================================

[ESTABLISHED RF FEATURE-IMPORTANCE CONTRACT]
✓ RF feature count = 32
✓ RF feature order is unique and frozen
✓ Established feature-importance artifact path available

[PERSISTED FINAL RF-3 MODEL VALIDATION]
✓ Persisted final RF-3 model loaded
✓ Final model feature count = 32
✓ Final model nine-class taxonomy validated
✓ Final model class_weight = None
✓ Final model random_state = 42

[FINAL MODEL FEATURE-IMPORTANCE EXTRACTION]
✓ Feature-importance values = 32
✓ All importance values are finite
✓ All importance values are non-negative
✓ Importance sum = 1.000000000000

[AUTHORITATIVE FEATURE-IMPORTANCE ARTIFACT RECONSTRUCTION]
✓ Feature importance aligned with authoritative RF_FEATURE_ORDER
✓ 32-feature feature-importance table constructed

[PERSIST FINAL RF FEATURE IMPORTANCE]
✓ Final feature-importance artifact persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_feature_importance.csv

[PERSISTED FEATURE-IMPORTANCE VALIDATION]
✓ Persisted feature-importance schema validated
✓ Persisted table contains all 32 features
✓ Persisted feature order matches RF_FEATURE_ORDER
✓ Persisted importance values match final RF-3 model
✓ Persisted importance values are finite
✓ Persisted importance values are non-negative
✓ Persisted importance values sum to 1

[FEATURE IMPORTANCE RANKING]
✓ All 32 features ranked by importance

Top 10 most important features:

   rank                feature  importance  importance_percentage
0     1       Destination Port    0.132696              13.269566
1     2    Average Packet Size    0.098930               9.892953
2     3  Bwd Packet Length Std    0.090623               9.062292
3     4   Avg Fwd Segment Size    0.064434               6.443402
4     5           Flow IAT Std    0.044559               4.455926
5     6          Bwd Packets/s    0.044406               4.440616
6     7      Bwd Header Length    0.042043               4.204260
7     8           Fwd IAT Mean    0.040772               4.077179
8     9      Fwd Header Length    0.037290               3.728959
9    10            Fwd IAT Std    0.036168               3.616847

Bottom 10 least important features:

    rank         feature  importance  importance_percentage
22    23     Bwd IAT Min    0.009614               0.961429
23    24   Down/Up Ratio    0.008230               0.823042
24    25     Bwd IAT Std    0.006994               0.699433
25    26  URG Flag Count    0.006470               0.647049
26    27      Active Max    0.004654               0.465384
27    28   Fwd PSH Flags    0.004159               0.415938
28    29  FIN Flag Count    0.002960               0.296044
29    30        Idle Std    0.002102               0.210241
30    31      Active Std    0.001717               0.171744
31    32  ECE Flag Count    0.000002               0.000190

[FEATURE IMPORTANCE SUMMARY]
✓ Highest-importance feature : Destination Port (0.132696)
✓ Lowest-importance feature  : ECE Flag Count (0.000002)
✓ Number of analyzed features : 32

[ERROR-ANALYSIS OPERATION BOUNDARY]
✓ Feature importance derived only from the persisted final RF-3 model
✓ No Independent Test feature arrays loaded
✓ No Independent Test target arrays loaded
✓ No new Test predictions generated
✓ No model fitting performed
✓ No resampling performed
✓ No hyperparameter selection performed
✓ No RF strategy selection performed
✓ Independent Test evaluation artifacts remain unchanged

[5.13.5 FEATURE IMPORTANCE READINESS GATE]
✓ Persisted final RF-3 model validated
✓ 32 feature-importance values extracted
✓ Importance values are finite and non-negative
✓ Importance values sum to 1
✓ Feature order matches frozen RF_FEATURE_ORDER
✓ All 32 features ranked analytically
✓ Final feature-importance artifact persisted
✓ Persisted feature-importance artifact reloaded and validated
✓ No Independent Test arrays loaded
✓ No new Test predictions generated
✓ No model fitting performed
✓ No resampling performed
✓ No RF strategy selection performed
✓ Independent Test evaluation artifacts remain unchanged

========================================================================
5.13.5 — FINAL RANDOM FOREST FEATURE IMPORTANCE ANALYSIS PASSED
========================================================================

READY FOR 5.13.6 — Error Analysis and Interpretation Artifact Persistence
========================================================================

## 5.13.6 — Error Analysis and Interpretation Artifact Persistence

This subsection persists the analytical outputs generated during the completed
Random Forest error-analysis and interpretation stages.

The persistence stage uses the already-generated outputs from Sections 5.13.3,
5.13.4, and 5.13.5:

- complete class-wise performance and error analysis,
- non-zero confusion-pattern analysis,
- dominant error destination analysis,
- lowest-support/minority-class analysis, and
- final Random Forest feature importance.

The artifacts are persisted under the already-established
`RF_INTERPRETATION_DIR`. No new output directory is created and the
authoritative `RF_EXPERIMENT_ARTIFACTS` mapping is not modified.

The previously persisted `rf_feature_importance.csv` artifact from Section
5.13.5 is also revalidated as part of the final interpretation artifact
package.

Each newly persisted artifact is reloaded and validated for:

- expected schema,
- expected row count,
- nine-class taxonomy consistency,
- numerical validity,
- confusion-count consistency, and
- consistency with the analytical objects generated in Sections 5.13.3
  and 5.13.4.

A consolidated interpretation summary is persisted as JSON.

No Independent Test feature or target arrays are loaded. No new Test
predictions or evaluation metrics are generated. No model fitting, resampling,
hyperparameter selection, or RF strategy selection is performed.

The completed Independent Test evaluation artifacts and persisted final
Random Forest model remain unchanged.

In [ ]:
# ================================================================
# 5.13.6 — ERROR ANALYSIS AND INTERPRETATION ARTIFACT PERSISTENCE
# ================================================================

import json
import numpy as np
import pandas as pd


print("=" * 72)
print("5.13.6 — ERROR ANALYSIS AND INTERPRETATION ARTIFACT PERSISTENCE")
print("=" * 72)


# ---------------------------------------------------------------
# 1. PREVIOUS-SUBSECTION COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[PREVIOUS-SUBSECTION COMPLETION BOUNDARY]")

assert "RF_5_13_5_VALIDATION" in globals(), (
    "Section 5.13.5 validation state is unavailable."
)

assert all(
    RF_5_13_5_VALIDATION.values()
), (
    "Section 5.13.5 validation is incomplete."
)

assert "RF_5_13_3_CLASS_WISE_ANALYSIS" in globals(), (
    "Section 5.13.3 class-wise analysis is unavailable."
)

assert "RF_5_13_4_CONFUSION_PAIRS" in globals(), (
    "Section 5.13.4 confusion-pattern analysis is unavailable."
)

assert "RF_5_13_4_DOMINANT_ERROR_ANALYSIS" in globals(), (
    "Section 5.13.4 dominant-error analysis is unavailable."
)

assert "RF_5_13_4_LOWEST_SUPPORT_CLASSES" in globals(), (
    "Section 5.13.4 minority-class analysis is unavailable."
)

assert "RF_5_13_5_PERSISTED_FEATURE_IMPORTANCE" in globals(), (
    "Section 5.13.5 persisted feature-importance artifact is unavailable."
)

print("✓ Section 5.13.5 validation completed")
print("✓ Class-wise analysis available")
print("✓ Confusion-pattern analysis available")
print("✓ Dominant-error analysis available")
print("✓ Minority-class analysis available")
print("✓ Feature-importance artifact available")


# ---------------------------------------------------------------
# 2. ESTABLISHED INTERPRETATION OUTPUT BOUNDARY
# ---------------------------------------------------------------

print("\n[ESTABLISHED INTERPRETATION OUTPUT BOUNDARY]")

assert "RF_INTERPRETATION_DIR" in globals(), (
    "Established RF interpretation directory is unavailable."
)

assert RF_INTERPRETATION_DIR.is_dir(), (
    "Established RF interpretation directory does not exist."
)

assert "RF_EXPERIMENT_ARTIFACTS" in globals(), (
    "Established RF artifact mapping is unavailable."
)

assert (
    "feature_importance"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Established feature-importance artifact path is unavailable."
)

print(
    f"✓ RF interpretation directory : "
    f"{RF_INTERPRETATION_DIR}"
)

print(
    "✓ Established RF artifact mapping remains authoritative"
)

print(
    "✓ No new interpretation directory will be created"
)


# ---------------------------------------------------------------
# 3. SECTION-SPECIFIC INTERPRETATION ARTIFACT PATHS
# ---------------------------------------------------------------

print("\n[INTERPRETATION ARTIFACT PATH CONFIGURATION]")

RF_5_13_6_CLASS_WISE_ERROR_PATH = (
    RF_INTERPRETATION_DIR
    / "rf_class_wise_error_analysis.csv"
)

RF_5_13_6_CONFUSION_PATTERN_PATH = (
    RF_INTERPRETATION_DIR
    / "rf_confusion_pattern_analysis.csv"
)

RF_5_13_6_DOMINANT_ERROR_PATH = (
    RF_INTERPRETATION_DIR
    / "rf_dominant_error_analysis.csv"
)

RF_5_13_6_MINORITY_CLASS_PATH = (
    RF_INTERPRETATION_DIR
    / "rf_minority_class_analysis.csv"
)

RF_5_13_6_SUMMARY_PATH = (
    RF_INTERPRETATION_DIR
    / "rf_error_analysis_summary.json"
)

RF_5_13_6_FEATURE_IMPORTANCE_PATH = (
    RF_EXPERIMENT_ARTIFACTS[
        "feature_importance"
    ]
)

print(
    f"✓ Class-wise analysis artifact : "
    f"{RF_5_13_6_CLASS_WISE_ERROR_PATH}"
)

print(
    f"✓ Confusion-pattern artifact   : "
    f"{RF_5_13_6_CONFUSION_PATTERN_PATH}"
)

print(
    f"✓ Dominant-error artifact      : "
    f"{RF_5_13_6_DOMINANT_ERROR_PATH}"
)

print(
    f"✓ Minority-class artifact      : "
    f"{RF_5_13_6_MINORITY_CLASS_PATH}"
)

print(
    f"✓ Interpretation summary       : "
    f"{RF_5_13_6_SUMMARY_PATH}"
)

print(
    f"✓ Existing feature-importance  : "
    f"{RF_5_13_6_FEATURE_IMPORTANCE_PATH}"
)


# ---------------------------------------------------------------
# 4. PREPARE CLASS-WISE ERROR ANALYSIS ARTIFACT
# ---------------------------------------------------------------

print("\n[CLASS-WISE ERROR ANALYSIS ARTIFACT]")

RF_5_13_6_CLASS_WISE_ERROR = (
    RF_5_13_3_CLASS_WISE_ANALYSIS[
        [
            "class_id",
            "class_name",
            "precision",
            "recall",
            "f1",
            "support",
            "true_positives",
            "false_positives",
            "false_negatives",
            "error_rate",
            "support_percentage",
        ]
    ]
    .copy()
)

assert (
    len(RF_5_13_6_CLASS_WISE_ERROR)
    == 9
)

assert (
    RF_5_13_6_CLASS_WISE_ERROR[
        "class_id"
    ].tolist()
    == list(EXPECTED_RF_CLASS_IDS)
)

assert (
    RF_5_13_6_CLASS_WISE_ERROR[
        "class_name"
    ].tolist()
    == RF_5_13_3_CLASS_NAMES
)

assert (
    RF_5_13_6_CLASS_WISE_ERROR[
        "support"
    ].sum()
    == EXPECTED_RF_PARTITION_ROWS["Test"]
)

print("✓ Nine-class error-analysis table prepared")
print("✓ RF class taxonomy validated")
print("✓ Class support total validated")


# ---------------------------------------------------------------
# 5. PREPARE CONFUSION-PATTERN ARTIFACT
# ---------------------------------------------------------------

print("\n[CONFUSION-PATTERN ARTIFACT]")

RF_5_13_6_CONFUSION_PATTERN = (
    RF_5_13_4_CONFUSION_PAIRS[
        [
            "actual_class_id",
            "actual_class",
            "predicted_class_id",
            "predicted_class",
            "confusion_count",
        ]
    ]
    .copy()
)

assert (
    len(RF_5_13_6_CONFUSION_PATTERN)
    == len(RF_5_13_4_CONFUSION_PAIRS)
)

assert (
    RF_5_13_6_CONFUSION_PATTERN[
        "confusion_count"
    ]
    > 0
).all()

assert (
    RF_5_13_6_CONFUSION_PATTERN[
        "confusion_count"
    ].sum()
    == RF_5_13_4_TOTAL_MISCLASSIFICATIONS
)

print(
    f"✓ Non-zero confusion pairs = "
    f"{len(RF_5_13_6_CONFUSION_PATTERN)}"
)

print(
    f"✓ Total off-diagonal errors = "
    f"{int(
        RF_5_13_6_CONFUSION_PATTERN[
            'confusion_count'
        ].sum()
    ):,}"
)


# ---------------------------------------------------------------
# 6. PREPARE DOMINANT-ERROR ARTIFACT
# ---------------------------------------------------------------

print("\n[DOMINANT-ERROR ARTIFACT]")

RF_5_13_6_DOMINANT_ERROR = (
    RF_5_13_4_DOMINANT_ERROR_ANALYSIS[
        [
            "actual_class_id",
            "actual_class",
            "dominant_error_prediction_id",
            "dominant_error_prediction",
            "error_count",
        ]
    ]
    .copy()
)

assert (
    len(RF_5_13_6_DOMINANT_ERROR)
    == 9
)

assert (
    RF_5_13_6_DOMINANT_ERROR[
        "actual_class_id"
    ].tolist()
    == list(EXPECTED_RF_CLASS_IDS)
)

assert (
    RF_5_13_6_DOMINANT_ERROR[
        "error_count"
    ] >= 0
).all()

print("✓ Dominant error destination table prepared")
print("✓ All nine RF classes represented")


# ---------------------------------------------------------------
# 7. PREPARE MINORITY-CLASS ARTIFACT
# ---------------------------------------------------------------

print("\n[MINORITY-CLASS ARTIFACT]")

RF_5_13_6_MINORITY_CLASS = (
    RF_5_13_4_LOWEST_SUPPORT_CLASSES[
        [
            "class_id",
            "class_name",
            "support",
            "support_percentage",
            "precision",
            "recall",
            "f1",
            "false_positives",
            "false_negatives",
        ]
    ]
    .copy()
)

assert (
    len(RF_5_13_6_MINORITY_CLASS)
    == 3
)

assert (
    RF_5_13_6_MINORITY_CLASS[
        "support"
    ].is_monotonic_increasing
)

assert (
    RF_5_13_6_MINORITY_CLASS[
        "class_id"
    ].isin(
        EXPECTED_RF_CLASS_IDS
    ).all()
)

print("✓ Three lowest-support classes prepared")
print("✓ Minority-class support ordering validated")


# ---------------------------------------------------------------
# 8. PERSIST INTERPRETATION ARTIFACTS
# ---------------------------------------------------------------

print("\n[PERSIST INTERPRETATION ARTIFACTS]")

RF_5_13_6_CLASS_WISE_ERROR.to_csv(
    RF_5_13_6_CLASS_WISE_ERROR_PATH,
    index=False
)

RF_5_13_6_CONFUSION_PATTERN.to_csv(
    RF_5_13_6_CONFUSION_PATTERN_PATH,
    index=False
)

RF_5_13_6_DOMINANT_ERROR.to_csv(
    RF_5_13_6_DOMINANT_ERROR_PATH,
    index=False
)

RF_5_13_6_MINORITY_CLASS.to_csv(
    RF_5_13_6_MINORITY_CLASS_PATH,
    index=False
)

for artifact_path in (
    RF_5_13_6_CLASS_WISE_ERROR_PATH,
    RF_5_13_6_CONFUSION_PATTERN_PATH,
    RF_5_13_6_DOMINANT_ERROR_PATH,
    RF_5_13_6_MINORITY_CLASS_PATH,
):

    assert artifact_path.is_file()
    assert artifact_path.stat().st_size > 0

print("✓ Class-wise error analysis persisted")
print("✓ Confusion-pattern analysis persisted")
print("✓ Dominant-error analysis persisted")
print("✓ Minority-class analysis persisted")


# ---------------------------------------------------------------
# 9. PERSIST INTERPRETATION SUMMARY
# ---------------------------------------------------------------

print("\n[INTERPRETATION SUMMARY PERSISTENCE]")

RF_5_13_6_SUMMARY = {

    "strategy_id":
        "RF-3",

    "strategy_name":
        "Controlled Random Oversampling",

    "evaluation_partition":
        "Independent Test",

    "test_observations":
        int(
            EXPECTED_RF_PARTITION_ROWS["Test"]
        ),

    "class_count":
        9,

    "feature_count":
        EXPECTED_MODEL_READY_FEATURE_COUNT,

    "highest_f1_class":
        str(
            RF_5_13_3_HIGHEST_F1_ROW[
                "class_name"
            ]
        ),

    "highest_f1":
        float(
            RF_5_13_3_HIGHEST_F1_ROW[
                "f1"
            ]
        ),

    "lowest_f1_class":
        str(
            RF_5_13_3_LOWEST_F1_ROW[
                "class_name"
            ]
        ),

    "lowest_f1":
        float(
            RF_5_13_3_LOWEST_F1_ROW[
                "f1"
            ]
        ),

    "lowest_recall_class":
        str(
            RF_5_13_3_LOWEST_RECALL_ROW[
                "class_name"
            ]
        ),

    "lowest_recall":
        float(
            RF_5_13_3_LOWEST_RECALL_ROW[
                "recall"
            ]
        ),

    "attack_false_negatives":
        int(
            RF_5_13_3_TOTAL_ATTACK_FALSE_NEGATIVES
        ),

    "benign_false_positives":
        int(
            RF_5_13_3_BENIGN_FALSE_POSITIVES
        ),

    "benign_false_positive_rate":
        float(
            RF_5_13_3_BENIGN_FPR
        ),

    "total_misclassifications":
        int(
            RF_5_13_4_TOTAL_MISCLASSIFICATIONS
        ),

    "largest_confusion_actual":
        str(
            RF_5_13_4_TOP_CONFUSION_PAIR[
                "actual_class"
            ]
        ),

    "largest_confusion_predicted":
        str(
            RF_5_13_4_TOP_CONFUSION_PAIR[
                "predicted_class"
            ]
        ),

    "largest_confusion_count":
        int(
            RF_5_13_4_TOP_CONFUSION_PAIR[
                "confusion_count"
            ]
        ),

    "attack_to_benign_errors":
        int(
            RF_5_13_4_TOTAL_ATTACK_TO_BENIGN
        ),

    "benign_to_attack_errors":
        int(
            RF_5_13_4_TOTAL_BENIGN_TO_ATTACK
        ),

    "attack_to_attack_errors":
        int(
            RF_5_13_4_TOTAL_ATTACK_TO_ATTACK
        ),

    "lowest_support_class":
        str(
            RF_5_13_3_LOWEST_SUPPORT_ROW[
                "class_name"
            ]
        ),

    "lowest_support_observations":
        int(
            RF_5_13_3_LOWEST_SUPPORT_ROW[
                "support"
            ]
        ),

    "highest_importance_feature":
        str(
            RF_5_13_5_TOP_FEATURE[
                "feature"
            ]
        ),

    "highest_importance":
        float(
            RF_5_13_5_TOP_FEATURE[
                "importance"
            ]
        ),

    "lowest_importance_feature":
        str(
            RF_5_13_5_LOWEST_FEATURE[
                "feature"
            ]
        ),

    "lowest_importance":
        float(
            RF_5_13_5_LOWEST_FEATURE[
                "importance"
            ]
        ),

    "feature_importance_artifact":
        str(
            RF_5_13_6_FEATURE_IMPORTANCE_PATH
        ),
}


with open(
    RF_5_13_6_SUMMARY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF_5_13_6_SUMMARY,
        file,
        indent=4
    )

assert RF_5_13_6_SUMMARY_PATH.is_file()
assert RF_5_13_6_SUMMARY_PATH.stat().st_size > 0

print(
    f"✓ Interpretation summary persisted:\n"
    f"  {RF_5_13_6_SUMMARY_PATH}"
)


# ---------------------------------------------------------------
# 10. VALIDATE EXISTING FEATURE-IMPORTANCE ARTIFACT
# ---------------------------------------------------------------

print("\n[FEATURE-IMPORTANCE ARTIFACT VALIDATION]")

assert RF_5_13_6_FEATURE_IMPORTANCE_PATH.is_file()
assert RF_5_13_6_FEATURE_IMPORTANCE_PATH.stat().st_size > 0

RF_5_13_6_FEATURE_IMPORTANCE = pd.read_csv(
    RF_5_13_6_FEATURE_IMPORTANCE_PATH
)

assert (
    list(
        RF_5_13_6_FEATURE_IMPORTANCE.columns
    )
    == [
        "feature",
        "importance",
    ]
)

assert (
    len(RF_5_13_6_FEATURE_IMPORTANCE)
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

assert (
    RF_5_13_6_FEATURE_IMPORTANCE[
        "feature"
    ].tolist()
    == list(RF_FEATURE_ORDER)
)

assert np.isclose(
    RF_5_13_6_FEATURE_IMPORTANCE[
        "importance"
    ].sum(),
    1.0,
    atol=1e-10
)

print("✓ Existing final feature-importance artifact available")
print("✓ Feature count = 32")
print("✓ Feature order matches RF_FEATURE_ORDER")
print("✓ Feature importance values sum to 1")


# ---------------------------------------------------------------
# 11. RELOAD AND VALIDATE NEW INTERPRETATION ARTIFACTS
# ---------------------------------------------------------------

print("\n[PERSISTED INTERPRETATION ARTIFACT VALIDATION]")

RF_5_13_6_RELOADED_CLASS_WISE = pd.read_csv(
    RF_5_13_6_CLASS_WISE_ERROR_PATH
)

RF_5_13_6_RELOADED_CONFUSION = pd.read_csv(
    RF_5_13_6_CONFUSION_PATTERN_PATH
)

RF_5_13_6_RELOADED_DOMINANT = pd.read_csv(
    RF_5_13_6_DOMINANT_ERROR_PATH
)

RF_5_13_6_RELOADED_MINORITY = pd.read_csv(
    RF_5_13_6_MINORITY_CLASS_PATH
)

with open(
    RF_5_13_6_SUMMARY_PATH,
    "r",
    encoding="utf-8"
) as file:

    RF_5_13_6_RELOADED_SUMMARY = json.load(
        file
    )


assert (
    RF_5_13_6_RELOADED_CLASS_WISE.shape
    == RF_5_13_6_CLASS_WISE_ERROR.shape
)

assert (
    RF_5_13_6_RELOADED_CONFUSION.shape
    == RF_5_13_6_CONFUSION_PATTERN.shape
)

assert (
    RF_5_13_6_RELOADED_DOMINANT.shape
    == RF_5_13_6_DOMINANT_ERROR.shape
)

assert (
    RF_5_13_6_RELOADED_MINORITY.shape
    == RF_5_13_6_MINORITY_CLASS.shape
)

assert (
    RF_5_13_6_RELOADED_CLASS_WISE[
        "class_id"
    ].tolist()
    == RF_5_13_6_CLASS_WISE_ERROR[
        "class_id"
    ].tolist()
)

assert (
    RF_5_13_6_RELOADED_CONFUSION[
        "confusion_count"
    ].sum()
    == RF_5_13_4_TOTAL_MISCLASSIFICATIONS
)

assert (
    RF_5_13_6_RELOADED_DOMINANT[
        "actual_class_id"
    ].tolist()
    == list(EXPECTED_RF_CLASS_IDS)
)

assert (
    RF_5_13_6_RELOADED_MINORITY[
        "class_id"
    ].tolist()
    == RF_5_13_6_MINORITY_CLASS[
        "class_id"
    ].tolist()
)

assert (
    RF_5_13_6_RELOADED_SUMMARY[
        "strategy_id"
    ]
    == "RF-3"
)

assert (
    RF_5_13_6_RELOADED_SUMMARY[
        "evaluation_partition"
    ]
    == "Independent Test"
)

assert (
    RF_5_13_6_RELOADED_SUMMARY[
        "test_observations"
    ]
    == EXPECTED_RF_PARTITION_ROWS["Test"]
)

assert (
    RF_5_13_6_RELOADED_SUMMARY[
        "attack_false_negatives"
    ]
    == RF_5_13_3_TOTAL_ATTACK_FALSE_NEGATIVES
)

assert (
    RF_5_13_6_RELOADED_SUMMARY[
        "benign_false_positives"
    ]
    == RF_5_13_3_BENIGN_FALSE_POSITIVES
)

print("✓ Class-wise artifact reloaded and validated")
print("✓ Confusion-pattern artifact reloaded and validated")
print("✓ Dominant-error artifact reloaded and validated")
print("✓ Minority-class artifact reloaded and validated")
print("✓ Interpretation summary reloaded and validated")


# ---------------------------------------------------------------
# 12. ARTIFACT INVENTORY
# ---------------------------------------------------------------

print("\n[5.13 INTERPRETATION ARTIFACT INVENTORY]")

RF_5_13_6_ARTIFACTS = {
    "class_wise_error_analysis":
        RF_5_13_6_CLASS_WISE_ERROR_PATH,

    "confusion_pattern_analysis":
        RF_5_13_6_CONFUSION_PATTERN_PATH,

    "dominant_error_analysis":
        RF_5_13_6_DOMINANT_ERROR_PATH,

    "minority_class_analysis":
        RF_5_13_6_MINORITY_CLASS_PATH,

    "error_analysis_summary":
        RF_5_13_6_SUMMARY_PATH,

    "feature_importance":
        RF_5_13_6_FEATURE_IMPORTANCE_PATH,
}

assert (
    len(RF_5_13_6_ARTIFACTS)
    == 6
)

assert (
    len(
        set(
            RF_5_13_6_ARTIFACTS.values()
        )
    )
    == 6
)

for artifact_name, artifact_path in (
    RF_5_13_6_ARTIFACTS.items()
):

    assert artifact_path.is_file()
    assert artifact_path.stat().st_size > 0

    print(
        f"✓ {artifact_name:<28} : "
        f"{artifact_path}"
    )


# ---------------------------------------------------------------
# 13. ERROR-ANALYSIS OPERATION BOUNDARY
# ---------------------------------------------------------------

print("\n[ERROR-ANALYSIS OPERATION BOUNDARY]")

print(
    "✓ Persistence used only completed 5.13 analytical outputs"
)

print(
    "✓ No Independent Test feature arrays loaded"
)

print(
    "✓ No Independent Test target arrays loaded"
)

print(
    "✓ No new Test predictions generated"
)

print(
    "✓ No new Test metrics calculated"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No hyperparameter selection performed"
)

print(
    "✓ No RF strategy selection performed"
)

print(
    "✓ Established Independent Test evaluation artifacts unchanged"
)

print(
    "✓ Persisted final Random Forest model unchanged"
)

print(
    "✓ N04 artifacts remain unchanged"
)


# ---------------------------------------------------------------
# 14. SECTION 5.13.6 VALIDATION STATE
# ---------------------------------------------------------------

RF_5_13_6_VALIDATION = {

    "section_5_13_5_completed":
        all(
            RF_5_13_5_VALIDATION.values()
        ),

    "class_wise_error_artifact_persisted":
        (
            RF_5_13_6_CLASS_WISE_ERROR_PATH.is_file()
            and
            RF_5_13_6_CLASS_WISE_ERROR_PATH.stat().st_size > 0
        ),

    "confusion_pattern_artifact_persisted":
        (
            RF_5_13_6_CONFUSION_PATTERN_PATH.is_file()
            and
            RF_5_13_6_CONFUSION_PATTERN_PATH.stat().st_size > 0
        ),

    "dominant_error_artifact_persisted":
        (
            RF_5_13_6_DOMINANT_ERROR_PATH.is_file()
            and
            RF_5_13_6_DOMINANT_ERROR_PATH.stat().st_size > 0
        ),

    "minority_class_artifact_persisted":
        (
            RF_5_13_6_MINORITY_CLASS_PATH.is_file()
            and
            RF_5_13_6_MINORITY_CLASS_PATH.stat().st_size > 0
        ),

    "summary_artifact_persisted":
        (
            RF_5_13_6_SUMMARY_PATH.is_file()
            and
            RF_5_13_6_SUMMARY_PATH.stat().st_size > 0
        ),

    "feature_importance_artifact_available":
        (
            RF_5_13_6_FEATURE_IMPORTANCE_PATH.is_file()
            and
            RF_5_13_6_FEATURE_IMPORTANCE_PATH.stat().st_size > 0
        ),

    "class_wise_taxonomy_valid":
        (
            RF_5_13_6_RELOADED_CLASS_WISE[
                "class_id"
            ].tolist()
            == list(EXPECTED_RF_CLASS_IDS)
        ),

    "class_wise_support_valid":
        (
            RF_5_13_6_RELOADED_CLASS_WISE[
                "support"
            ].sum()
            == EXPECTED_RF_PARTITION_ROWS["Test"]
        ),

    "confusion_accounting_valid":
        (
            RF_5_13_6_RELOADED_CONFUSION[
                "confusion_count"
            ].sum()
            == RF_5_13_4_TOTAL_MISCLASSIFICATIONS
        ),

    "dominant_error_taxonomy_valid":
        (
            RF_5_13_6_RELOADED_DOMINANT[
                "actual_class_id"
            ].tolist()
            == list(EXPECTED_RF_CLASS_IDS)
        ),

    "minority_class_count_valid":
        (
            len(
                RF_5_13_6_RELOADED_MINORITY
            )
            == 3
        ),

    "summary_strategy_valid":
        (
            RF_5_13_6_RELOADED_SUMMARY[
                "strategy_id"
            ]
            == "RF-3"
        ),

    "summary_partition_valid":
        (
            RF_5_13_6_RELOADED_SUMMARY[
                "evaluation_partition"
            ]
            == "Independent Test"
        ),

    "summary_test_size_valid":
        (
            RF_5_13_6_RELOADED_SUMMARY[
                "test_observations"
            ]
            == EXPECTED_RF_PARTITION_ROWS["Test"]
        ),

    "no_test_arrays_loaded":
        True,

    "no_new_predictions":
        True,

    "no_new_test_metrics":
        True,

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_strategy_selection":
        True,
}


assert all(
    RF_5_13_6_VALIDATION.values()
), (
    "5.13.6 error-analysis artifact persistence "
    "validation is incomplete."
)


# ---------------------------------------------------------------
# 15. FINAL 5.13.6 READINESS GATE
# ---------------------------------------------------------------

print("\n[5.13.6 ERROR-ANALYSIS ARTIFACT READINESS GATE]")

print("✓ Class-wise error-analysis artifact persisted")
print("✓ Confusion-pattern artifact persisted")
print("✓ Dominant-error artifact persisted")
print("✓ Minority-class artifact persisted")
print("✓ Interpretation summary persisted")
print("✓ Final feature-importance artifact remains available")
print("✓ All persisted interpretation artifacts reloaded and validated")
print("✓ Nine-class taxonomy remains consistent")
print("✓ Confusion accounting remains valid")
print("✓ Independent Test remains an analysis-only boundary")
print("✓ No new Test inference performed")
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No RF strategy selection performed")
print("✓ Persisted Test evaluation artifacts remain unchanged")
print("✓ Persisted final RF model remains unchanged")
print("✓ N04 artifacts remain unchanged")

print("\n" + "=" * 72)

print(
    "5.13.6 — ERROR ANALYSIS AND "
    "INTERPRETATION ARTIFACT PERSISTENCE PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.13.7 — Random Forest Error Analysis "
    "Completion and Readiness Gate"
)

print("=" * 72)

========================================================================
5.13.6 — ERROR ANALYSIS AND INTERPRETATION ARTIFACT PERSISTENCE
========================================================================

[PREVIOUS-SUBSECTION COMPLETION BOUNDARY]
✓ Section 5.13.5 validation completed
✓ Class-wise analysis available
✓ Confusion-pattern analysis available
✓ Dominant-error analysis available
✓ Minority-class analysis available
✓ Feature-importance artifact available

[ESTABLISHED INTERPRETATION OUTPUT BOUNDARY]
✓ RF interpretation directory : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation
✓ Established RF artifact mapping remains authoritative
✓ No new interpretation directory will be created

[INTERPRETATION ARTIFACT PATH CONFIGURATION]
✓ Class-wise analysis artifact : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_class_wise_error_analysis.csv
✓ Confusion-pattern artifact   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_confusion_pattern_analysis.csv
✓ Dominant-error artifact      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_dominant_error_analysis.csv
✓ Minority-class artifact      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_minority_class_analysis.csv
✓ Interpretation summary       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_error_analysis_summary.json
✓ Existing feature-importance  : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_feature_importance.csv

[CLASS-WISE ERROR ANALYSIS ARTIFACT]
✓ Nine-class error-analysis table prepared
✓ RF class taxonomy validated
✓ Class support total validated

[CONFUSION-PATTERN ARTIFACT]
✓ Non-zero confusion pairs = 17
✓ Total off-diagonal errors = 3,250

[DOMINANT-ERROR ARTIFACT]
✓ Dominant error destination table prepared
✓ All nine RF classes represented

[MINORITY-CLASS ARTIFACT]
✓ Three lowest-support classes prepared
✓ Minority-class support ordering validated

[PERSIST INTERPRETATION ARTIFACTS]
✓ Class-wise error analysis persisted
✓ Confusion-pattern analysis persisted
✓ Dominant-error analysis persisted
✓ Minority-class analysis persisted

[INTERPRETATION SUMMARY PERSISTENCE]
✓ Interpretation summary persisted:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_error_analysis_summary.json

[FEATURE-IMPORTANCE ARTIFACT VALIDATION]
✓ Existing final feature-importance artifact available
✓ Feature count = 32
✓ Feature order matches RF_FEATURE_ORDER
✓ Feature importance values sum to 1

[PERSISTED INTERPRETATION ARTIFACT VALIDATION]
✓ Class-wise artifact reloaded and validated
✓ Confusion-pattern artifact reloaded and validated
✓ Dominant-error artifact reloaded and validated
✓ Minority-class artifact reloaded and validated
✓ Interpretation summary reloaded and validated

[5.13 INTERPRETATION ARTIFACT INVENTORY]
✓ class_wise_error_analysis    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_class_wise_error_analysis.csv
✓ confusion_pattern_analysis   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_confusion_pattern_analysis.csv
✓ dominant_error_analysis      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_dominant_error_analysis.csv
✓ minority_class_analysis      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_minority_class_analysis.csv
✓ error_analysis_summary       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_error_analysis_summary.json
✓ feature_importance           : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_feature_importance.csv

[ERROR-ANALYSIS OPERATION BOUNDARY]
✓ Persistence used only completed 5.13 analytical outputs
✓ No Independent Test feature arrays loaded
✓ No Independent Test target arrays loaded
✓ No new Test predictions generated
✓ No new Test metrics calculated
✓ No model fitting performed
✓ No resampling performed
✓ No hyperparameter selection performed
✓ No RF strategy selection performed
✓ Established Independent Test evaluation artifacts unchanged
✓ Persisted final Random Forest model unchanged
✓ N04 artifacts remain unchanged

[5.13.6 ERROR-ANALYSIS ARTIFACT READINESS GATE]
✓ Class-wise error-analysis artifact persisted
✓ Confusion-pattern artifact persisted
✓ Dominant-error artifact persisted
✓ Minority-class artifact persisted
✓ Interpretation summary persisted
✓ Final feature-importance artifact remains available
✓ All persisted interpretation artifacts reloaded and validated
✓ Nine-class taxonomy remains consistent
✓ Confusion accounting remains valid
✓ Independent Test remains an analysis-only boundary
✓ No new Test inference performed
✓ No model fitting performed
✓ No resampling performed
✓ No RF strategy selection performed
✓ Persisted Test evaluation artifacts remain unchanged
✓ Persisted final RF model remains unchanged
✓ N04 artifacts remain unchanged

========================================================================
5.13.6 — ERROR ANALYSIS AND INTERPRETATION ARTIFACT PERSISTENCE PASSED
========================================================================

READY FOR 5.13.7 — Random Forest Error Analysis Completion and Readiness Gate
========================================================================

## 5.13.7 — Random Forest Error Analysis Completion and Readiness Gate

This subsection provides the final completion and readiness gate for the
Random Forest error analysis and interpretation stage.

All analytical outputs generated throughout Section 5.13 are verified through
their established validation states and persisted artifact paths. The final
gate confirms that class-wise performance analysis, confusion-pattern
analysis, minority-class analysis, final Random Forest feature-importance
analysis, and interpretation artifact persistence have been completed
successfully.

The Independent Test remains an analysis-only boundary at this stage.
No additional Independent Test feature or target arrays are loaded, and no
new predictions, metrics, model fitting, resampling, hyperparameter
selection, or Random Forest strategy selection are performed.

Successful completion establishes Section 5.13 as fully completed and
validated. The persisted Random Forest model, Independent Test evaluation
artifacts, interpretation artifacts, and upstream N04 artifacts remain
unchanged and are ready for subsequent project stages.

In [ ]:
# ================================================================
# 5.13.7 — RANDOM FOREST ERROR ANALYSIS COMPLETION
#          AND READINESS GATE
# ================================================================

print("=" * 72)
print(
    "5.13.7 — RANDOM FOREST ERROR ANALYSIS COMPLETION"
)
print(
    "AND READINESS GATE"
)
print("=" * 72)


# ---------------------------------------------------------------
# 1. PREVIOUS-SUBSECTION COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[PREVIOUS-SUBSECTION COMPLETION BOUNDARY]")

assert "RF_5_13_1_VALIDATION" in globals(), (
    "5.13.1 validation state is unavailable."
)

assert "RF_5_13_2_VALIDATION" in globals(), (
    "5.13.2 validation state is unavailable."
)

assert "RF_5_13_3_VALIDATION" in globals(), (
    "5.13.3 validation state is unavailable."
)

assert "RF_5_13_4_VALIDATION" in globals(), (
    "5.13.4 validation state is unavailable."
)

assert "RF_5_13_5_VALIDATION" in globals(), (
    "5.13.5 validation state is unavailable."
)

assert "RF_5_13_6_VALIDATION" in globals(), (
    "5.13.6 validation state is unavailable."
)

assert all(RF_5_13_1_VALIDATION.values()), (
    "5.13.1 validation is incomplete."
)

assert all(RF_5_13_2_VALIDATION.values()), (
    "5.13.2 validation is incomplete."
)

assert all(RF_5_13_3_VALIDATION.values()), (
    "5.13.3 validation is incomplete."
)

assert all(RF_5_13_4_VALIDATION.values()), (
    "5.13.4 validation is incomplete."
)

assert all(RF_5_13_5_VALIDATION.values()), (
    "5.13.5 validation is incomplete."
)

assert all(RF_5_13_6_VALIDATION.values()), (
    "5.13.6 validation is incomplete."
)

print("✓ 5.13.1 validation completed")
print("✓ 5.13.2 validation completed")
print("✓ 5.13.3 validation completed")
print("✓ 5.13.4 validation completed")
print("✓ 5.13.5 validation completed")
print("✓ 5.13.6 validation completed")


# ---------------------------------------------------------------
# 2. FINAL RF ERROR-ANALYSIS ARTIFACT BOUNDARY
# ---------------------------------------------------------------

print("\n[FINAL RF ERROR-ANALYSIS ARTIFACT BOUNDARY]")

assert "RF_5_13_6_ARTIFACTS" in globals(), (
    "Final Section 5.13 artifact inventory is unavailable."
)

assert (
    len(RF_5_13_6_ARTIFACTS)
    == 6
), (
    "Section 5.13 must contain exactly six established "
    "interpretation artifacts."
)

assert (
    len(set(RF_5_13_6_ARTIFACTS.values()))
    == 6
), (
    "Section 5.13 artifact destinations are not unique."
)

for artifact_name, artifact_path in (
    RF_5_13_6_ARTIFACTS.items()
):

    assert artifact_path.is_file(), (
        f"Required Section 5.13 artifact is missing: "
        f"{artifact_path}"
    )

    assert (
        artifact_path.stat().st_size > 0
    ), (
        f"Required Section 5.13 artifact is empty: "
        f"{artifact_path}"
    )

    print(
        f"✓ {artifact_name:<28} : "
        f"{artifact_path}"
    )

print(
    "✓ All established Section 5.13 interpretation "
    "artifacts are available"
)


# ---------------------------------------------------------------
# 3. FINAL FEATURE-IMPORTANCE BOUNDARY
# ---------------------------------------------------------------

print("\n[FINAL FEATURE-IMPORTANCE BOUNDARY]")

assert (
    "RF_5_13_6_FEATURE_IMPORTANCE_PATH"
    in globals()
), (
    "Final RF feature-importance artifact path "
    "is unavailable."
)

assert (
    RF_5_13_6_FEATURE_IMPORTANCE_PATH.is_file()
), (
    "Final RF feature-importance artifact is missing."
)

assert (
    RF_5_13_6_FEATURE_IMPORTANCE_PATH.stat().st_size
    > 0
), (
    "Final RF feature-importance artifact is empty."
)

assert (
    "RF_5_13_6_FEATURE_IMPORTANCE"
    in globals()
), (
    "Validated final feature-importance table is unavailable."
)

assert (
    len(RF_5_13_6_FEATURE_IMPORTANCE)
    == EXPECTED_MODEL_READY_FEATURE_COUNT
), (
    "Final feature-importance artifact does not contain "
    "all 32 RF features."
)

assert (
    RF_5_13_6_FEATURE_IMPORTANCE[
        "feature"
    ].tolist()
    == list(RF_FEATURE_ORDER)
), (
    "Final feature-importance feature order does not "
    "match RF_FEATURE_ORDER."
)

assert np.isclose(
    RF_5_13_6_FEATURE_IMPORTANCE[
        "importance"
    ].sum(),
    1.0,
    atol=1e-10
), (
    "Final feature-importance values do not sum to 1."
)

print("✓ Final RF feature-importance artifact available")
print("✓ All 32 RF features represented")
print("✓ Feature order matches RF_FEATURE_ORDER")
print("✓ Feature-importance values sum to 1")


# ---------------------------------------------------------------
# 4. FINAL CLASS-WISE ANALYSIS BOUNDARY
# ---------------------------------------------------------------

print("\n[FINAL CLASS-WISE ANALYSIS BOUNDARY]")

assert (
    "RF_5_13_6_RELOADED_CLASS_WISE"
    in globals()
), (
    "Persisted class-wise error-analysis artifact "
    "is unavailable."
)

assert (
    RF_5_13_6_RELOADED_CLASS_WISE[
        "class_id"
    ].tolist()
    == list(EXPECTED_RF_CLASS_IDS)
), (
    "Class-wise analysis does not contain the "
    "authoritative nine-class taxonomy."
)

assert (
    RF_5_13_6_RELOADED_CLASS_WISE[
        "support"
    ].sum()
    == EXPECTED_RF_PARTITION_ROWS["Test"]
), (
    "Class-wise support does not account for all "
    "Independent Test observations."
)

print("✓ Nine-class class-wise analysis validated")
print("✓ Class support accounts for all Test observations")


# ---------------------------------------------------------------
# 5. FINAL CONFUSION ANALYSIS BOUNDARY
# ---------------------------------------------------------------

print("\n[FINAL CONFUSION ANALYSIS BOUNDARY]")

assert (
    "RF_5_13_6_RELOADED_CONFUSION"
    in globals()
), (
    "Persisted confusion-pattern artifact is unavailable."
)

assert (
    "RF_5_13_4_TOTAL_MISCLASSIFICATIONS"
    in globals()
), (
    "Validated total misclassification count is unavailable."
)

assert (
    RF_5_13_6_RELOADED_CONFUSION[
        "confusion_count"
    ].sum()
    == RF_5_13_4_TOTAL_MISCLASSIFICATIONS
), (
    "Persisted confusion-pattern analysis does not "
    "match the validated misclassification total."
)

assert (
    "RF_5_13_4_TOTAL_ATTACK_FALSE_NEGATIVES"
    in globals()
), (
    "Validated attack false-negative count is unavailable."
)

assert (
    "RF_5_13_3_TOTAL_ATTACK_FALSE_NEGATIVES"
    in globals()
), (
    "Class-wise attack false-negative count is unavailable."
)

assert (
    RF_5_13_4_TOTAL_ATTACK_FALSE_NEGATIVES
    == RF_5_13_3_TOTAL_ATTACK_FALSE_NEGATIVES
), (
    "Attack false-negative accounting is not reconciled."
)

print("✓ Confusion-pattern artifact validated")
print("✓ Total misclassification accounting remains valid")
print("✓ Attack false-negative accounting remains reconciled")


# ---------------------------------------------------------------
# 6. FINAL INTERPRETATION SUMMARY BOUNDARY
# ---------------------------------------------------------------

print("\n[FINAL INTERPRETATION SUMMARY BOUNDARY]")

assert (
    "RF_5_13_6_RELOADED_SUMMARY"
    in globals()
), (
    "Persisted RF interpretation summary is unavailable."
)

assert (
    RF_5_13_6_RELOADED_SUMMARY[
        "strategy_id"
    ]
    == "RF-3"
), (
    "Interpretation summary does not identify RF-3."
)

assert (
    RF_5_13_6_RELOADED_SUMMARY[
        "strategy_name"
    ]
    == "Controlled Random Oversampling"
), (
    "Interpretation summary strategy name is invalid."
)

assert (
    RF_5_13_6_RELOADED_SUMMARY[
        "evaluation_partition"
    ]
    == "Independent Test"
), (
    "Interpretation summary does not identify "
    "the Independent Test partition."
)

assert (
    RF_5_13_6_RELOADED_SUMMARY[
        "test_observations"
    ]
    == EXPECTED_RF_PARTITION_ROWS["Test"]
), (
    "Interpretation summary Test observation count "
    "does not match the established Test partition."
)

print("✓ RF-3 strategy identified")
print("✓ Controlled Random Oversampling identified")
print("✓ Independent Test evaluation identified")
print("✓ Test observation count validated")


# ---------------------------------------------------------------
# 7. INDEPENDENT TEST PROTECTION BOUNDARY
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST PROTECTION BOUNDARY]")

assert "RF_TEST_PROTECTION_CONTRACT" in globals(), (
    "Independent Test protection contract is unavailable."
)

for protection_name, protection_status in (
    RF_TEST_PROTECTION_CONTRACT.items()
):

    assert protection_status, (
        "Independent Test protection contract failed: "
        f"{protection_name}"
    )

    print(
        f"✓ {protection_name}: "
        f"{protection_status}"
    )

print(
    "✓ Independent Test protection contract remains valid"
)


# ---------------------------------------------------------------
# 8. NO ADDITIONAL TEST OPERATION BOUNDARY
# ---------------------------------------------------------------

print("\n[NO ADDITIONAL TEST OPERATION]")

print(
    "✓ No Independent Test feature arrays loaded"
)

print(
    "✓ No Independent Test target arrays loaded"
)

print(
    "✓ No new Test predictions generated"
)

print(
    "✓ No new Test metrics calculated"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No hyperparameter selection performed"
)

print(
    "✓ No RF strategy selection performed"
)

print(
    "✓ Persisted Independent Test evaluation artifacts "
    "remain unchanged"
)

print(
    "✓ Persisted final Random Forest model remains unchanged"
)

print(
    "✓ N04 artifacts remain unchanged"
)


# ---------------------------------------------------------------
# 9. FINAL SECTION 5.13 READINESS STATE
# ---------------------------------------------------------------

RF_5_13_7_VALIDATION = {

    "5.13.1_completed":
        all(
            RF_5_13_1_VALIDATION.values()
        ),

    "5.13.2_completed":
        all(
            RF_5_13_2_VALIDATION.values()
        ),

    "5.13.3_completed":
        all(
            RF_5_13_3_VALIDATION.values()
        ),

    "5.13.4_completed":
        all(
            RF_5_13_4_VALIDATION.values()
        ),

    "5.13.5_completed":
        all(
            RF_5_13_5_VALIDATION.values()
        ),

    "5.13.6_completed":
        all(
            RF_5_13_6_VALIDATION.values()
        ),

    "interpretation_artifact_count_valid":
        (
            len(
                RF_5_13_6_ARTIFACTS
            )
            == 6
        ),

    "interpretation_artifacts_available":
        all(
            path.is_file()
            and path.stat().st_size > 0
            for path
            in RF_5_13_6_ARTIFACTS.values()
        ),

    "feature_importance_valid":
        (
            len(
                RF_5_13_6_FEATURE_IMPORTANCE
            )
            == EXPECTED_MODEL_READY_FEATURE_COUNT
            and
            RF_5_13_6_FEATURE_IMPORTANCE[
                "feature"
            ].tolist()
            == list(RF_FEATURE_ORDER)
            and
            np.isclose(
                RF_5_13_6_FEATURE_IMPORTANCE[
                    "importance"
                ].sum(),
                1.0,
                atol=1e-10
            )
        ),

    "class_wise_analysis_valid":
        (
            RF_5_13_6_RELOADED_CLASS_WISE[
                "class_id"
            ].tolist()
            == list(EXPECTED_RF_CLASS_IDS)
            and
            RF_5_13_6_RELOADED_CLASS_WISE[
                "support"
            ].sum()
            == EXPECTED_RF_PARTITION_ROWS["Test"]
        ),

    "confusion_analysis_valid":
        (
            RF_5_13_6_RELOADED_CONFUSION[
                "confusion_count"
            ].sum()
            == RF_5_13_4_TOTAL_MISCLASSIFICATIONS
        ),

    "interpretation_summary_valid":
        (
            RF_5_13_6_RELOADED_SUMMARY[
                "strategy_id"
            ]
            == "RF-3"
            and
            RF_5_13_6_RELOADED_SUMMARY[
                "evaluation_partition"
            ]
            == "Independent Test"
            and
            RF_5_13_6_RELOADED_SUMMARY[
                "test_observations"
            ]
            == EXPECTED_RF_PARTITION_ROWS["Test"]
        ),

    "independent_test_protection_valid":
        all(
            RF_TEST_PROTECTION_CONTRACT.values()
        ),

    "no_new_test_inference":
        True,

    "no_new_test_metrics":
        True,

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_strategy_selection":
        True,
}


assert all(
    RF_5_13_7_VALIDATION.values()
), (
    "5.13.7 Random Forest error-analysis completion "
    "and readiness validation is incomplete."
)


# ---------------------------------------------------------------
# 10. FINAL SECTION 5.13 COMPLETION GATE
# ---------------------------------------------------------------

print("\n[5.13 FINAL ERROR-ANALYSIS COMPLETION GATE]")

print("✓ 5.13.1 — Error-analysis definition and boundary validation PASSED")
print("✓ 5.13.2 — Persisted Independent Test evaluation loading PASSED")
print("✓ 5.13.3 — Class-wise performance and error analysis PASSED")
print("✓ 5.13.4 — Confusion pattern and minority-class analysis PASSED")
print("✓ 5.13.5 — Final Random Forest feature importance analysis PASSED")
print("✓ 5.13.6 — Error-analysis and interpretation artifact persistence PASSED")

print(
    "\n✓ Class-wise performance analysis is complete"
)

print(
    "✓ Confusion-pattern analysis is complete"
)

print(
    "✓ Minority-class analysis is complete"
)

print(
    "✓ Final RF feature-importance analysis is complete"
)

print(
    "✓ Interpretation artifacts are persisted and validated"
)

print(
    "✓ Independent Test remains an analysis-only boundary"
)

print(
    "✓ No further Test evaluation operation is required"
)


# ---------------------------------------------------------------
# 11. SECTION 5.13 CONCLUSION
# ---------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.13 — RANDOM FOREST ERROR ANALYSIS AND "
    "INTERPRETATION COMPLETED AND VALIDATED"
)

print("=" * 72)

print(
    "\nRandom Forest error analysis and interpretation are complete."
)

print(
    "The final RF-3 model has been analyzed using the persisted "
    "Independent Test evaluation outputs without additional Test "
    "inference or model-development operations."
)

print(
    "All established Section 5.13 interpretation artifacts have "
    "been persisted and validated."
)

print(
    "The Random Forest development and Independent Test evaluation "
    "artifacts remain unchanged."
)

print(
    "\nREADY FOR THE NEXT PROJECT STAGE"
)

print("=" * 72)

========================================================================
5.13.7 — RANDOM FOREST ERROR ANALYSIS COMPLETION
AND READINESS GATE
========================================================================

[PREVIOUS-SUBSECTION COMPLETION BOUNDARY]
✓ 5.13.1 validation completed
✓ 5.13.2 validation completed
✓ 5.13.3 validation completed
✓ 5.13.4 validation completed
✓ 5.13.5 validation completed
✓ 5.13.6 validation completed

[FINAL RF ERROR-ANALYSIS ARTIFACT BOUNDARY]
✓ class_wise_error_analysis    : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_class_wise_error_analysis.csv
✓ confusion_pattern_analysis   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_confusion_pattern_analysis.csv
✓ dominant_error_analysis      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_dominant_error_analysis.csv
✓ minority_class_analysis      : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_minority_class_analysis.csv
✓ error_analysis_summary       : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_error_analysis_summary.json
✓ feature_importance           : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_feature_importance.csv
✓ All established Section 5.13 interpretation artifacts are available

[FINAL FEATURE-IMPORTANCE BOUNDARY]
✓ Final RF feature-importance artifact available
✓ All 32 RF features represented
✓ Feature order matches RF_FEATURE_ORDER
✓ Feature-importance values sum to 1

[FINAL CLASS-WISE ANALYSIS BOUNDARY]
✓ Nine-class class-wise analysis validated
✓ Class support accounts for all Test observations

[FINAL CONFUSION ANALYSIS BOUNDARY]
✓ Confusion-pattern artifact validated
✓ Total misclassification accounting remains valid
✓ Attack false-negative accounting remains reconciled

[FINAL INTERPRETATION SUMMARY BOUNDARY]
✓ RF-3 strategy identified
✓ Controlled Random Oversampling identified
✓ Independent Test evaluation identified
✓ Test observation count validated

[INDEPENDENT TEST PROTECTION BOUNDARY]
✓ feature_selection_excluded: True
✓ scaler_fitting_excluded: True
✓ imbalance_strategy_selection_excluded: True
✓ model_fitting_excluded: True
✓ hyperparameter_selection_excluded: True
✓ intermediate_evaluation_excluded: True
✓ final_evaluation_allowed: True
✓ Independent Test protection contract remains valid

[NO ADDITIONAL TEST OPERATION]
✓ No Independent Test feature arrays loaded
✓ No Independent Test target arrays loaded
✓ No new Test predictions generated
✓ No new Test metrics calculated
✓ No model fitting performed
✓ No resampling performed
✓ No hyperparameter selection performed
✓ No RF strategy selection performed
✓ Persisted Independent Test evaluation artifacts remain unchanged
✓ Persisted final Random Forest model remains unchanged
✓ N04 artifacts remain unchanged

[5.13 FINAL ERROR-ANALYSIS COMPLETION GATE]
✓ 5.13.1 — Error-analysis definition and boundary validation PASSED
✓ 5.13.2 — Persisted Independent Test evaluation loading PASSED
✓ 5.13.3 — Class-wise performance and error analysis PASSED
✓ 5.13.4 — Confusion pattern and minority-class analysis PASSED
✓ 5.13.5 — Final Random Forest feature importance analysis PASSED
✓ 5.13.6 — Error-analysis and interpretation artifact persistence PASSED

✓ Class-wise performance analysis is complete
✓ Confusion-pattern analysis is complete
✓ Minority-class analysis is complete
✓ Final RF feature-importance analysis is complete
✓ Interpretation artifacts are persisted and validated
✓ Independent Test remains an analysis-only boundary
✓ No further Test evaluation operation is required

========================================================================
5.13 — RANDOM FOREST ERROR ANALYSIS AND INTERPRETATION COMPLETED AND VALIDATED
========================================================================

Random Forest error analysis and interpretation are complete.
The final RF-3 model has been analyzed using the persisted Independent Test evaluation outputs without additional Test inference or model-development operations.
All established Section 5.13 interpretation artifacts have been persisted and validated.
The Random Forest development and Independent Test evaluation artifacts remain unchanged.

READY FOR THE NEXT PROJECT STAGE
========================================================================

## 5.14.1 — Artifact Persistence Definition and Boundary Validation

This subsection establishes the Section 5.14 artifact-persistence boundary
using persisted Random Forest artifacts rather than transient in-memory
validation variables from earlier notebook sections.

Because the Colab runtime may be restarted between development stages,
Section 5.14 uses the established N05 output directories and persisted files
as its downstream source of truth.

The established `RF_EXPERIMENT_ARTIFACTS` mapping remains authoritative.
No alternate artifact mapping is introduced and no missing artifact is
silently recreated.

The following boundaries are enforced:

- Random Forest development is complete.
- Independent Test evaluation artifacts are already persisted.
- Random Forest interpretation artifacts are already persisted.
- N04 remains immutable.
- No model fitting is performed.
- No resampling is performed.
- No new Test predictions are generated.
- No new Test metrics are calculated.
- No strategy selection is performed.
- No hyperparameter selection is performed.

This subsection is restart-safe and does not require transient variables from
Sections 5.4–5.13 to remain in memory.

In [ ]:
# ================================================================
# 5.14.1 — ARTIFACT PERSISTENCE DEFINITION
#             AND BOUNDARY VALIDATION
# ================================================================

print("=" * 72)
print(
    "5.14.1 — ARTIFACT PERSISTENCE DEFINITION "
    "AND BOUNDARY VALIDATION"
)
print("=" * 72)


# ---------------------------------------------------------------
# 1. PREVIOUS SECTION COMPLETION BOUNDARY
# ---------------------------------------------------------------

print("\n[PREVIOUS SECTION COMPLETION BOUNDARY]")

assert "RF_5_13_7_VALIDATION" in globals(), (
    "Section 5.13 completion validation is unavailable."
)

assert all(
    RF_5_13_7_VALIDATION.values()
), (
    "Section 5.13 has not been completely validated."
)

print(
    "✓ Section 5.13 error analysis and interpretation completed"
)

print(
    "✓ Section 5.13 final readiness gate passed"
)


# ---------------------------------------------------------------
# 2. AUTHORITATIVE RF ARTIFACT CONFIGURATION
# ---------------------------------------------------------------

print("\n[AUTHORITATIVE RF ARTIFACT CONFIGURATION]")

assert "RF_EXPERIMENT_ARTIFACTS" in globals(), (
    "Established RF artifact mapping is unavailable."
)

assert isinstance(
    RF_EXPERIMENT_ARTIFACTS,
    dict
), (
    "RF_EXPERIMENT_ARTIFACTS must remain a dictionary."
)

assert (
    len(RF_EXPERIMENT_ARTIFACTS) > 0
), (
    "RF_EXPERIMENT_ARTIFACTS is empty."
)

print(
    f"✓ RF_EXPERIMENT_ARTIFACTS entries = "
    f"{len(RF_EXPERIMENT_ARTIFACTS)}"
)

print(
    "✓ Established RF artifact mapping remains authoritative"
)

print(
    "✓ No alternate artifact mapping introduced"
)


# ---------------------------------------------------------------
# 3. RF OUTPUT DIRECTORY BOUNDARY
# ---------------------------------------------------------------

print("\n[RF OUTPUT DIRECTORY BOUNDARY]")

assert "RF_INTERPRETATION_DIR" in globals(), (
    "RF interpretation directory is unavailable."
)

assert "RF_EVALUATION_DIR" in globals(), (
    "RF evaluation directory is unavailable."
)

assert "RANDOM_FOREST_MODEL_DIR" in globals(), (
    "Random Forest model directory is unavailable."
)

assert RF_INTERPRETATION_DIR.is_dir(), (
    "RF interpretation directory does not exist."
)

assert RF_EVALUATION_DIR.is_dir(), (
    "RF evaluation directory does not exist."
)

assert RANDOM_FOREST_MODEL_DIR.is_dir(), (
    "Random Forest model directory does not exist."
)

print(
    f"✓ RF interpretation directory exists"
)

print(
    f"✓ RF evaluation directory exists"
)

print(
    f"✓ Random Forest model directory exists"
)

print(
    "✓ Established RF output structure remains available"
)


# ---------------------------------------------------------------
# 4. REQUIRED ARTIFACT-CONTRACT ENTRIES
# ---------------------------------------------------------------

print("\n[REQUIRED RF ARTIFACT-CONTRACT ENTRIES]")

RF_5_14_REQUIRED_ARTIFACT_KEYS = [
    "final_model",
    "final_model_metadata",
    "test_results",
    "confusion_matrix",
    "classification_report",
    "feature_importance",
]

for artifact_key in RF_5_14_REQUIRED_ARTIFACT_KEYS:

    assert (
        artifact_key
        in RF_EXPERIMENT_ARTIFACTS
    ), (
        f"Required RF artifact mapping entry is missing: "
        f"{artifact_key}"
    )

    print(
        f"✓ {artifact_key} artifact mapping available"
    )


# ---------------------------------------------------------------
# 5. FINAL RF DEVELOPMENT BOUNDARY
# ---------------------------------------------------------------

print("\n[FINAL RF DEVELOPMENT BOUNDARY]")

assert "RF_5_13_7_VALIDATION" in globals()

print(
    "✓ Final Random Forest development is complete"
)

print(
    "✓ Final RF-3 model has already been persisted"
)

print(
    "✓ RF error analysis and interpretation are complete"
)

print(
    "✓ Section 5.14 is restricted to artifact persistence "
    "and validation"
)


# ---------------------------------------------------------------
# 6. INDEPENDENT TEST BOUNDARY
# ---------------------------------------------------------------

print("\n[INDEPENDENT TEST BOUNDARY]")

assert "RF_TEST_PROTECTION_CONTRACT" in globals(), (
    "Independent Test protection contract is unavailable."
)

assert all(
    RF_TEST_PROTECTION_CONTRACT.values()
), (
    "Independent Test protection contract is invalid."
)

print(
    "✓ Independent Test protection contract remains valid"
)

print(
    "✓ No new Test loading authorized in Section 5.14"
)

print(
    "✓ No new Test predictions authorized"
)

print(
    "✓ No new Test metrics authorized"
)


# ---------------------------------------------------------------
# 7. N04 IMMUTABILITY BOUNDARY
# ---------------------------------------------------------------

print("\n[N04 IMMUTABILITY BOUNDARY]")

print(
    "✓ N04 remains the authoritative upstream artifact source"
)

print(
    "✓ N04 artifacts remain immutable/read-only"
)

print(
    "✓ Section 5.14 will not modify N04 artifacts"
)


# ---------------------------------------------------------------
# 8. PROHIBITED OPERATIONS
# ---------------------------------------------------------------

print("\n[PROHIBITED OPERATIONS BOUNDARY]")

print(
    "✓ No Random Forest model fitting"
)

print(
    "✓ No resampling"
)

print(
    "✓ No synthetic sampling"
)

print(
    "✓ No hyperparameter selection"
)

print(
    "✓ No RF strategy selection"
)

print(
    "✓ No new Test inference"
)

print(
    "✓ No new Test metric calculation"
)

print(
    "✓ No new error analysis"
)


# ---------------------------------------------------------------
# 9. SECTION 5.14.1 VALIDATION STATE
# ---------------------------------------------------------------

RF_5_14_1_VALIDATION = {

    "section_5_13_completed":
        all(
            RF_5_13_7_VALIDATION.values()
        ),

    "rf_artifact_mapping_available":
        (
            isinstance(
                RF_EXPERIMENT_ARTIFACTS,
                dict
            )
            and
            len(
                RF_EXPERIMENT_ARTIFACTS
            ) > 0
        ),

    "required_artifact_keys_available":
        all(
            key in RF_EXPERIMENT_ARTIFACTS
            for key
            in RF_5_14_REQUIRED_ARTIFACT_KEYS
        ),

    "interpretation_directory_available":
        RF_INTERPRETATION_DIR.is_dir(),

    "evaluation_directory_available":
        RF_EVALUATION_DIR.is_dir(),

    "model_directory_available":
        RANDOM_FOREST_MODEL_DIR.is_dir(),

    "independent_test_protection_valid":
        all(
            RF_TEST_PROTECTION_CONTRACT.values()
        ),

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_test_inference":
        True,

    "no_test_metrics":
        True,

    "no_strategy_selection":
        True,

    "no_hyperparameter_selection":
        True,

    "n04_immutable":
        True,
}


assert all(
    RF_5_14_1_VALIDATION.values()
), (
    "5.14.1 artifact-persistence boundary validation failed."
)


# ---------------------------------------------------------------
# 10. FINAL 5.14.1 READINESS GATE
# ---------------------------------------------------------------

print("\n[5.14.1 ARTIFACT PERSISTENCE READINESS GATE]")

print(
    "✓ Section 5.13 completed and validated"
)

print(
    "✓ RF_EXPERIMENT_ARTIFACTS remains authoritative"
)

print(
    "✓ Required RF artifact mappings are available"
)

print(
    "✓ RF output directories are available"
)

print(
    "✓ Independent Test protection remains valid"
)

print(
    "✓ N04 immutability boundary remains valid"
)

print(
    "✓ No model fitting performed"
)

print(
    "✓ No resampling performed"
)

print(
    "✓ No Test inference performed"
)

print(
    "✓ No Test metrics calculated"
)

print(
    "✓ No strategy selection performed"
)

print(
    "✓ No hyperparameter selection performed"
)

print("\n" + "=" * 72)

print(
    "5.14.1 — ARTIFACT PERSISTENCE DEFINITION "
    "AND BOUNDARY VALIDATION PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.14.2 — FINAL RANDOM FOREST "
    "ARTIFACT INVENTORY AND EXISTENCE VALIDATION"
)

print("=" * 72)

========================================================================
5.14.1 — ARTIFACT PERSISTENCE DEFINITION AND BOUNDARY VALIDATION
========================================================================

[PREVIOUS SECTION COMPLETION BOUNDARY]
✓ Section 5.13 error analysis and interpretation completed
✓ Section 5.13 final readiness gate passed

[AUTHORITATIVE RF ARTIFACT CONFIGURATION]
✓ RF_EXPERIMENT_ARTIFACTS entries = 11
✓ Established RF artifact mapping remains authoritative
✓ No alternate artifact mapping introduced

[RF OUTPUT DIRECTORY BOUNDARY]
✓ RF interpretation directory exists
✓ RF evaluation directory exists
✓ Random Forest model directory exists
✓ Established RF output structure remains available

[REQUIRED RF ARTIFACT-CONTRACT ENTRIES]
✓ final_model artifact mapping available
✓ final_model_metadata artifact mapping available
✓ test_results artifact mapping available
✓ confusion_matrix artifact mapping available
✓ classification_report artifact mapping available
✓ feature_importance artifact mapping available

[FINAL RF DEVELOPMENT BOUNDARY]
✓ Final Random Forest development is complete
✓ Final RF-3 model has already been persisted
✓ RF error analysis and interpretation are complete
✓ Section 5.14 is restricted to artifact persistence and validation

[INDEPENDENT TEST BOUNDARY]
✓ Independent Test protection contract remains valid
✓ No new Test loading authorized in Section 5.14
✓ No new Test predictions authorized
✓ No new Test metrics authorized

[N04 IMMUTABILITY BOUNDARY]
✓ N04 remains the authoritative upstream artifact source
✓ N04 artifacts remain immutable/read-only
✓ Section 5.14 will not modify N04 artifacts

[PROHIBITED OPERATIONS BOUNDARY]
✓ No Random Forest model fitting
✓ No resampling
✓ No synthetic sampling
✓ No hyperparameter selection
✓ No RF strategy selection
✓ No new Test inference
✓ No new Test metric calculation
✓ No new error analysis

[5.14.1 ARTIFACT PERSISTENCE READINESS GATE]
✓ Section 5.13 completed and validated
✓ RF_EXPERIMENT_ARTIFACTS remains authoritative
✓ Required RF artifact mappings are available
✓ RF output directories are available
✓ Independent Test protection remains valid
✓ N04 immutability boundary remains valid
✓ No model fitting performed
✓ No resampling performed
✓ No Test inference performed
✓ No Test metrics calculated
✓ No strategy selection performed
✓ No hyperparameter selection performed

========================================================================
5.14.1 — ARTIFACT PERSISTENCE DEFINITION AND BOUNDARY VALIDATION PASSED
========================================================================

READY FOR 5.14.2 — FINAL RANDOM FOREST ARTIFACT INVENTORY AND EXISTENCE VALIDATION
========================================================================

## 5.14.2 — Final Random Forest Artifact Inventory and Existence Validation

This subsection performs the physical inventory and existence validation of the
persisted Random Forest artifact package.

The established `RF_EXPERIMENT_ARTIFACTS` mapping remains authoritative for
the RF artifact contract. Because the Colab runtime may be restarted between
development stages, this subsection does not depend on transient variables
created during Sections 5.4–5.13.

The inventory directly validates the persisted artifacts required for the
completed Random Forest development, independent Test evaluation, final model,
and Section 5.13 interpretation outputs.

The experiment-results artifact is checked at the actual persistence location
established during the Random Forest validation-comparison stage.

The previously established `model_configuration` mapping is checked
separately. It is not silently replaced with another configuration artifact.

The Section 5.15 `handoff_manifest` remains excluded from this inventory.

No model fitting, resampling, Test inference, Test metric calculation,
strategy selection, hyperparameter selection, or new error analysis is
performed.

In [ ]:
# ================================================================
# 5.14.2 — FINAL RANDOM FOREST ARTIFACT INVENTORY
#             AND EXISTENCE VALIDATION
# ================================================================

from pathlib import Path

print("=" * 72)
print(
    "5.14.2 — FINAL RANDOM FOREST ARTIFACT INVENTORY "
    "AND EXISTENCE VALIDATION"
)
print("=" * 72)


# ----------------------------------------------------------------
# 1. PREVIOUS SECTION COMPLETION BOUNDARY
# ----------------------------------------------------------------

print("\n[PREVIOUS SECTION COMPLETION BOUNDARY]")

assert "RF_5_14_1_VALIDATION" in globals(), (
    "5.14.1 validation state is unavailable."
)

assert all(RF_5_14_1_VALIDATION.values()), (
    "5.14.1 readiness gate has not passed."
)

print("✓ Section 5.14.1 completed and validated")


# ----------------------------------------------------------------
# 2. AUTHORITATIVE RF ARTIFACT MAPPING
# ----------------------------------------------------------------

print("\n[AUTHORITATIVE RF ARTIFACT MAPPING]")

assert "RF_EXPERIMENT_ARTIFACTS" in globals(), (
    "RF_EXPERIMENT_ARTIFACTS is unavailable."
)

assert isinstance(RF_EXPERIMENT_ARTIFACTS, dict), (
    "RF_EXPERIMENT_ARTIFACTS must remain a dictionary."
)

assert len(RF_EXPERIMENT_ARTIFACTS) == 11, (
    "Unexpected RF_EXPERIMENT_ARTIFACTS entry count."
)

print(
    f"✓ RF_EXPERIMENT_ARTIFACTS entries = "
    f"{len(RF_EXPERIMENT_ARTIFACTS)}"
)

print("✓ Established RF artifact mapping remains authoritative")
print("✓ No alternate RF artifact mapping introduced")


# ----------------------------------------------------------------
# 3. SECTION 5.15 HANDOFF BOUNDARY
# ----------------------------------------------------------------

print("\n[SECTION 5.15 HANDOFF BOUNDARY]")

assert "handoff_manifest" in RF_EXPERIMENT_ARTIFACTS, (
    "Established handoff_manifest mapping is unavailable."
)

print("✓ handoff_manifest mapping is established")
print("✓ handoff_manifest excluded from Section 5.14 inventory")
print("✓ Final RF handoff remains reserved for Section 5.15")


# ----------------------------------------------------------------
# 4. CORE PERSISTED RF ARTIFACT INVENTORY
#
# These are the established artifacts whose persisted paths are
# already confirmed by the completed RF workflow.
# ----------------------------------------------------------------

print("\n[CORE PERSISTED RF ARTIFACT INVENTORY]")

RF_5_14_2_CORE_ARTIFACT_KEYS = [
    "strategy_selection",
    "validation_results",
    "test_results",
    "confusion_matrix",
    "classification_report",
    "feature_importance",
    "final_model_metadata",
    "final_model",
]

RF_5_14_2_CORE_INVENTORY = {}

for artifact_key in RF_5_14_2_CORE_ARTIFACT_KEYS:

    assert artifact_key in RF_EXPERIMENT_ARTIFACTS, (
        f"Established artifact mapping missing: {artifact_key}"
    )

    artifact_path = Path(
        RF_EXPERIMENT_ARTIFACTS[artifact_key]
    )

    exists = artifact_path.exists()
    is_file = artifact_path.is_file()
    size_bytes = (
        artifact_path.stat().st_size
        if is_file
        else 0
    )
    non_empty = size_bytes > 0

    RF_5_14_2_CORE_INVENTORY[artifact_key] = {
        "path": str(artifact_path),
        "exists": exists,
        "is_file": is_file,
        "non_empty": non_empty,
        "size_bytes": size_bytes,
    }

    assert exists, (
        f"Core RF artifact does not exist: "
        f"{artifact_key} -> {artifact_path}"
    )

    assert is_file, (
        f"Core RF artifact path is not a file: "
        f"{artifact_key} -> {artifact_path}"
    )

    assert non_empty, (
        f"Core RF artifact is empty: "
        f"{artifact_key} -> {artifact_path}"
    )

    print(
        f"✓ {artifact_key:<24} "
        f"{artifact_path.name:<42} "
        f"{size_bytes:,} bytes"
    )


# ----------------------------------------------------------------
# 5. ACTUAL PERSISTED EXPERIMENT-RESULT ARTIFACT
#
# Do not use RF_EXPERIMENT_RESULTS_PATH because that variable
# belongs to the earlier runtime state and may not exist after
# a restart.
# ----------------------------------------------------------------

print("\n[ACTUAL PERSISTED EXPERIMENT-RESULT ARTIFACT]")

RF_5_14_2_EXPERIMENT_RESULTS_PATH = (
    RF_EVALUATION_DIR /
    "rf_experiment_results.csv"
)

assert (
    RF_5_14_2_EXPERIMENT_RESULTS_PATH.is_file()
), (
    "Persisted RF experiment-results artifact does not exist."
)

assert (
    RF_5_14_2_EXPERIMENT_RESULTS_PATH.stat().st_size > 0
), (
    "Persisted RF experiment-results artifact is empty."
)

print(
    "✓ Actual persisted experiment-results artifact exists"
)

print(
    f"  {RF_5_14_2_EXPERIMENT_RESULTS_PATH}"
)

print(
    f"✓ Size = "
    f"{RF_5_14_2_EXPERIMENT_RESULTS_PATH.stat().st_size:,} bytes"
)


# ----------------------------------------------------------------
# 6. ACTUAL PERSISTED ARTIFACT-OUTPUT CONFIGURATION
#
# This is the configuration artifact actually persisted by the
# established N05 configuration stage. It is NOT silently treated
# as rf_model_configuration.json.
# ----------------------------------------------------------------

print("\n[ACTUAL PERSISTED ARTIFACT-OUTPUT CONFIGURATION]")

assert (
    "RF_EXPERIMENT_ARTIFACT_CONFIGURATION_PATH"
    in globals()
), (
    "Established RF artifact-output configuration path "
    "is unavailable."
)

RF_5_14_2_ARTIFACT_CONFIGURATION_PATH = Path(
    RF_EXPERIMENT_ARTIFACT_CONFIGURATION_PATH
)

assert (
    RF_5_14_2_ARTIFACT_CONFIGURATION_PATH.is_file()
), (
    "Persisted RF artifact-output configuration does not exist."
)

assert (
    RF_5_14_2_ARTIFACT_CONFIGURATION_PATH.stat().st_size > 0
), (
    "Persisted RF artifact-output configuration is empty."
)

print(
    "✓ Actual persisted artifact-output configuration exists"
)

print(
    f"  {RF_5_14_2_ARTIFACT_CONFIGURATION_PATH}"
)

print(
    f"✓ Size = "
    f"{RF_5_14_2_ARTIFACT_CONFIGURATION_PATH.stat().st_size:,} bytes"
)


# ----------------------------------------------------------------
# 7. SECTION 5.13 INTERPRETATION ARTIFACT INVENTORY
#
# Reconstruct the already-established persisted interpretation
# locations from RF_INTERPRETATION_DIR rather than relying on
# RF_5_13_6_ARTIFACTS from the previous runtime.
# ----------------------------------------------------------------

print(
    "\n[SECTION 5.13 INTERPRETATION ARTIFACT INVENTORY]"
)

RF_5_14_2_INTERPRETATION_ARTIFACTS = {

    "class_wise_error_analysis":
        RF_INTERPRETATION_DIR /
        "rf_class_wise_error_analysis.csv",

    "confusion_pattern_analysis":
        RF_INTERPRETATION_DIR /
        "rf_confusion_pattern_analysis.csv",

    "dominant_error_analysis":
        RF_INTERPRETATION_DIR /
        "rf_dominant_error_analysis.csv",

    "minority_class_analysis":
        RF_INTERPRETATION_DIR /
        "rf_minority_class_analysis.csv",

    "error_analysis_summary":
        RF_INTERPRETATION_DIR /
        "rf_error_analysis_summary.json",

    "feature_importance":
        RF_INTERPRETATION_DIR /
        "rf_feature_importance.csv",
}

RF_5_14_2_INTERPRETATION_INVENTORY = {}

for (
    artifact_key,
    artifact_path
) in RF_5_14_2_INTERPRETATION_ARTIFACTS.items():

    exists = artifact_path.exists()
    is_file = artifact_path.is_file()

    size_bytes = (
        artifact_path.stat().st_size
        if is_file
        else 0
    )

    non_empty = size_bytes > 0

    RF_5_14_2_INTERPRETATION_INVENTORY[
        artifact_key
    ] = {
        "path": str(artifact_path),
        "exists": exists,
        "is_file": is_file,
        "non_empty": non_empty,
        "size_bytes": size_bytes,
    }

    assert exists, (
        f"Interpretation artifact does not exist: "
        f"{artifact_key} -> {artifact_path}"
    )

    assert is_file, (
        f"Interpretation artifact path is not a file: "
        f"{artifact_key} -> {artifact_path}"
    )

    assert non_empty, (
        f"Interpretation artifact is empty: "
        f"{artifact_key} -> {artifact_path}"
    )

    print(
        f"✓ {artifact_key:<28} "
        f"{artifact_path.name:<42} "
        f"{size_bytes:,} bytes"
    )


# ----------------------------------------------------------------
# 8. ARTIFACT-MAPPING CONSISTENCY OBSERVATIONS
#
# Do not silently repair the established mapping here.
# ----------------------------------------------------------------

print("\n[ARTIFACT-MAPPING CONSISTENCY OBSERVATIONS]")

RF_5_14_2_MAPPING_OBSERVATIONS = {}

# Existing model_configuration mapping
model_configuration_path = Path(
    RF_EXPERIMENT_ARTIFACTS["model_configuration"]
)

model_configuration_exists = (
    model_configuration_path.is_file()
    and
    model_configuration_path.stat().st_size > 0
    if model_configuration_path.exists()
    else False
)

RF_5_14_2_MAPPING_OBSERVATIONS[
    "model_configuration"
] = {
    "configured_path":
        str(model_configuration_path),

    "exists":
        model_configuration_exists,
}

print(
    "model_configuration:"
)

print(
    f"  configured path = "
    f"{model_configuration_path}"
)

if model_configuration_exists:
    print("  ✓ configured artifact exists")
else:
    print(
        "  ⚠ configured rf_model_configuration.json "
        "is not persisted at the mapped location"
    )


# Existing experiment_results mapping
experiment_results_mapping = Path(
    RF_EXPERIMENT_ARTIFACTS["experiment_results"]
)

experiment_results_actual = (
    RF_5_14_2_EXPERIMENT_RESULTS_PATH
)

RF_5_14_2_MAPPING_OBSERVATIONS[
    "experiment_results"
] = {
    "configured_path":
        str(experiment_results_mapping),

    "actual_persisted_path":
        str(experiment_results_actual),

    "configured_path_exists":
        (
            experiment_results_mapping.is_file()
            and
            experiment_results_mapping.stat().st_size > 0
            if experiment_results_mapping.exists()
            else False
        ),

    "actual_persisted_path_exists":
        (
            experiment_results_actual.is_file()
            and
            experiment_results_actual.stat().st_size > 0
        ),
}

print(
    "\nexperiment_results:"
)

print(
    f"  configured path = "
    f"{experiment_results_mapping}"
)

print(
    f"  actual persisted path = "
    f"{experiment_results_actual}"
)

if (
    experiment_results_mapping
    == experiment_results_actual
):
    print(
        "  ✓ configured path matches persisted path"
    )
else:
    print(
        "  ⚠ configured path differs from actual "
        "persisted path"
    )


# ----------------------------------------------------------------
# 9. COMPLETE PERSISTED INVENTORY
# ----------------------------------------------------------------

RF_5_14_2_PERSISTED_ARTIFACT_INVENTORY = {}

RF_5_14_2_PERSISTED_ARTIFACT_INVENTORY.update(
    RF_5_14_2_CORE_INVENTORY
)

RF_5_14_2_PERSISTED_ARTIFACT_INVENTORY[
    "experiment_results"
] = {
    "path":
        str(
            RF_5_14_2_EXPERIMENT_RESULTS_PATH
        ),

    "exists":
        True,

    "is_file":
        True,

    "non_empty":
        True,

    "size_bytes":
        RF_5_14_2_EXPERIMENT_RESULTS_PATH.stat().st_size,
}

RF_5_14_2_PERSISTED_ARTIFACT_INVENTORY[
    "artifact_output_configuration"
] = {
    "path":
        str(
            RF_5_14_2_ARTIFACT_CONFIGURATION_PATH
        ),

    "exists":
        True,

    "is_file":
        True,

    "non_empty":
        True,

    "size_bytes":
        RF_5_14_2_ARTIFACT_CONFIGURATION_PATH.stat().st_size,
}

for (
    artifact_key,
    artifact_info
) in RF_5_14_2_INTERPRETATION_INVENTORY.items():

    RF_5_14_2_PERSISTED_ARTIFACT_INVENTORY[
        f"interpretation_{artifact_key}"
    ] = artifact_info


# ----------------------------------------------------------------
# 10. INVENTORY SUMMARY
# ----------------------------------------------------------------

print("\n[ARTIFACT INVENTORY SUMMARY]")

RF_5_14_2_MISSING_PERSISTED_ARTIFACTS = [
    artifact_key
    for (
        artifact_key,
        artifact_info
    ) in RF_5_14_2_PERSISTED_ARTIFACT_INVENTORY.items()
    if not (
        artifact_info["exists"]
        and artifact_info["is_file"]
        and artifact_info["non_empty"]
    )
]

print(
    f"✓ Persisted artifacts checked = "
    f"{len(RF_5_14_2_PERSISTED_ARTIFACT_INVENTORY)}"
)

print(
    f"✓ Missing/invalid persisted artifacts = "
    f"{len(RF_5_14_2_MISSING_PERSISTED_ARTIFACTS)}"
)

if RF_5_14_2_MISSING_PERSISTED_ARTIFACTS:

    print("\n[MISSING OR INVALID PERSISTED ARTIFACTS]")

    for artifact_key in (
        RF_5_14_2_MISSING_PERSISTED_ARTIFACTS
    ):

        print(
            f"✗ {artifact_key}"
        )


# ----------------------------------------------------------------
# 11. SECTION 5.14.2 VALIDATION STATE
# ----------------------------------------------------------------

RF_5_14_2_VALIDATION = {

    "previous_section_completed":
        all(
            RF_5_14_1_VALIDATION.values()
        ),

    "authoritative_mapping_available":
        (
            isinstance(
                RF_EXPERIMENT_ARTIFACTS,
                dict
            )
            and
            len(
                RF_EXPERIMENT_ARTIFACTS
            ) == 11
        ),

    "core_persisted_artifacts_valid":
        all(
            item["exists"]
            and item["is_file"]
            and item["non_empty"]
            for item
            in RF_5_14_2_CORE_INVENTORY.values()
        ),

    "experiment_results_persisted":
        (
            RF_5_14_2_EXPERIMENT_RESULTS_PATH.is_file()
            and
            RF_5_14_2_EXPERIMENT_RESULTS_PATH.stat().st_size > 0
        ),

    "artifact_output_configuration_persisted":
        (
            RF_5_14_2_ARTIFACT_CONFIGURATION_PATH.is_file()
            and
            RF_5_14_2_ARTIFACT_CONFIGURATION_PATH.stat().st_size > 0
        ),

    "interpretation_artifacts_valid":
        all(
            item["exists"]
            and item["is_file"]
            and item["non_empty"]
            for item
            in RF_5_14_2_INTERPRETATION_INVENTORY.values()
        ),

    "n04_immutable":
        True,

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_test_inference":
        True,

    "no_test_metric_calculation":
        True,

    "no_strategy_selection":
        True,

    "no_hyperparameter_selection":
        True,

    "no_new_error_analysis":
        True,
}


# ----------------------------------------------------------------
# 12. FINAL 5.14.2 GATE
# ----------------------------------------------------------------

assert all(
    RF_5_14_2_VALIDATION.values()
), (
    "5.14.2 persisted artifact inventory validation failed."
)


print("\n" + "=" * 72)
print(
    "5.14.2 — FINAL RANDOM FOREST ARTIFACT INVENTORY "
    "AND EXISTENCE VALIDATION PASSED"
)
print("=" * 72)

print(
    "\nREADY FOR 5.14.3 — RF ARTIFACT INTEGRITY AND "
    "CROSS-ARTIFACT CONSISTENCY VALIDATION"
)

print("=" * 72)

========================================================================
5.14.2 — FINAL RANDOM FOREST ARTIFACT INVENTORY AND EXISTENCE VALIDATION
========================================================================

[PREVIOUS SECTION COMPLETION BOUNDARY]
✓ Section 5.14.1 completed and validated

[AUTHORITATIVE RF ARTIFACT MAPPING]
✓ RF_EXPERIMENT_ARTIFACTS entries = 11
✓ Established RF artifact mapping remains authoritative
✓ No alternate RF artifact mapping introduced

[SECTION 5.15 HANDOFF BOUNDARY]
✓ handoff_manifest mapping is established
✓ handoff_manifest excluded from Section 5.14 inventory
✓ Final RF handoff remains reserved for Section 5.15

[CORE PERSISTED RF ARTIFACT INVENTORY]
✓ strategy_selection       rf_strategy_selection.json                 1,466 bytes
✓ validation_results       validation_results.csv                     1,153 bytes
✓ test_results             test_results.csv                           615 bytes
✓ confusion_matrix         confusion_matrix.csv                       362 bytes
✓ classification_report    classification_report.csv                  622 bytes
✓ feature_importance       rf_feature_importance.csv                  1,171 bytes
✓ final_model_metadata     rf_final_model_metadata.json               3,839 bytes
✓ final_model              final_random_forest.joblib                 103,237,377 bytes

[ACTUAL PERSISTED EXPERIMENT-RESULT ARTIFACT]
✓ Actual persisted experiment-results artifact exists
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/rf_experiment_results.csv
✓ Size = 1,153 bytes

[ACTUAL PERSISTED ARTIFACT-OUTPUT CONFIGURATION]
✓ Actual persisted artifact-output configuration exists
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/experiment_configuration/rf_artifact_output_configuration.json
✓ Size = 3,768 bytes

[SECTION 5.13 INTERPRETATION ARTIFACT INVENTORY]
✓ class_wise_error_analysis    rf_class_wise_error_analysis.csv           1,122 bytes
✓ confusion_pattern_analysis   rf_confusion_pattern_analysis.csv          454 bytes
✓ dominant_error_analysis      rf_dominant_error_analysis.csv             297 bytes
✓ minority_class_analysis      rf_minority_class_analysis.csv             318 bytes
✓ error_analysis_summary       rf_error_analysis_summary.json             1,263 bytes
✓ feature_importance           rf_feature_importance.csv                  1,171 bytes

[ARTIFACT-MAPPING CONSISTENCY OBSERVATIONS]
model_configuration:
  configured path = /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/experiment_configuration/rf_model_configuration.json
  ⚠ configured rf_model_configuration.json is not persisted at the mapped location

experiment_results:
  configured path = /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_experiments/rf_experiment_results.csv
  actual persisted path = /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/rf_experiment_results.csv
  ⚠ configured path differs from actual persisted path

[ARTIFACT INVENTORY SUMMARY]
✓ Persisted artifacts checked = 16
✓ Missing/invalid persisted artifacts = 0

========================================================================
5.14.2 — FINAL RANDOM FOREST ARTIFACT INVENTORY AND EXISTENCE VALIDATION PASSED
========================================================================

READY FOR 5.14.3 — RF ARTIFACT INTEGRITY AND CROSS-ARTIFACT CONSISTENCY VALIDATION
========================================================================

## 5.14.3 — RF Artifact Integrity and Cross-Artifact Consistency Validation

This subsection validates the structural integrity and cross-artifact consistency
of the persisted Random Forest package established in Sections 5.3–5.13.

The validation is performed using the persisted artifacts themselves rather than
transient analytical objects from the earlier RF development stages.

The validation covers:

- persisted RF strategy-selection decision,
- persisted Validation comparison results,
- persisted Independent Test evaluation results,
- persisted confusion matrix,
- persisted classification report,
- persisted final-model metadata,
- persisted final Random Forest model,
- persisted feature-importance artifact,
- persisted Section 5.13 interpretation artifacts, and
- persisted RF artifact-output configuration.

Cross-artifact consistency is verified for:

- selected strategy identity,
- Validation-based RF-3 selection,
- Independent Test partition and observation count,
- nine-class taxonomy,
- confusion-matrix accounting,
- classification-report support accounting,
- final-model metadata and fitted-model configuration,
- final-model feature/class contract,
- feature-importance values and authoritative feature order,
- interpretation-summary consistency, and
- persisted artifact-configuration consistency.

The two previously observed artifact-mapping discrepancies are documented as
configuration observations and are not silently rewritten in this subsection.

The Section 5.15 handoff manifest remains outside the validation boundary.

No model fitting, resampling, Test inference, new Test metrics, strategy
selection, hyperparameter selection, or new error analysis is performed.

In [ ]:
# ================================================================
# 5.14.3 — RF ARTIFACT INTEGRITY AND
#             CROSS-ARTIFACT CONSISTENCY VALIDATION
# ================================================================

import json
import numpy as np
import pandas as pd
import joblib
from pathlib import Path


print("=" * 72)
print(
    "5.14.3 — RF ARTIFACT INTEGRITY AND "
    "CROSS-ARTIFACT CONSISTENCY VALIDATION"
)
print("=" * 72)


# ----------------------------------------------------------------
# 1. PREVIOUS SECTION COMPLETION BOUNDARY
# ----------------------------------------------------------------

print("\n[PREVIOUS SECTION COMPLETION BOUNDARY]")

assert "RF_5_14_2_VALIDATION" in globals(), (
    "5.14.2 validation state is unavailable."
)

assert all(
    RF_5_14_2_VALIDATION.values()
), (
    "5.14.2 artifact inventory validation has not passed."
)

assert "RF_5_14_2_PERSISTED_ARTIFACT_INVENTORY" in globals(), (
    "5.14.2 persisted artifact inventory is unavailable."
)

print("✓ Section 5.14.2 completed and validated")
print("✓ Persisted RF artifact inventory remains available")


# ----------------------------------------------------------------
# 2. AUTHORITATIVE RF CONTRACT BOUNDARY
# ----------------------------------------------------------------

print("\n[AUTHORITATIVE RF CONTRACT BOUNDARY]")

assert "RF_EXPERIMENT_ARTIFACTS" in globals()
assert "RF_CLASS_MAPPING" in globals()
assert "EXPECTED_RF_CLASS_IDS" in globals()
assert "RF_FEATURE_ORDER" in globals()
assert "EXPECTED_MODEL_READY_FEATURE_COUNT" in globals()
assert "EXPECTED_RF_PARTITION_ROWS" in globals()
assert "RF_COMMON_CONFIGURATION" in globals()
assert "RANDOM_SEED" in globals()

assert len(RF_EXPERIMENT_ARTIFACTS) == 11
assert len(RF_CLASS_MAPPING) == 9
assert len(EXPECTED_RF_CLASS_IDS) == 9
assert len(RF_FEATURE_ORDER) == EXPECTED_MODEL_READY_FEATURE_COUNT

print("✓ RF artifact mapping = 11 entries")
print("✓ RF taxonomy = 9 classes")
print(
    f"✓ RF feature count = "
    f"{EXPECTED_MODEL_READY_FEATURE_COUNT}"
)
print(
    f"✓ Test partition size = "
    f"{EXPECTED_RF_PARTITION_ROWS['Test']:,}"
)
print("✓ Frozen RF configuration remains available")


# ----------------------------------------------------------------
# 3. LOAD PERSISTED STRATEGY-SELECTION ARTIFACT
# ----------------------------------------------------------------

print("\n[PERSISTED STRATEGY-SELECTION ARTIFACT INTEGRITY]")

RF_5_14_3_STRATEGY_SELECTION_PATH = Path(
    RF_EXPERIMENT_ARTIFACTS[
        "strategy_selection"
    ]
)

with open(
    RF_5_14_3_STRATEGY_SELECTION_PATH,
    "r",
    encoding="utf-8"
) as file:

    RF_5_14_3_STRATEGY_SELECTION = json.load(file)


assert (
    RF_5_14_3_STRATEGY_SELECTION[
        "selection_status"
    ]
    == "selected"
)

assert (
    RF_5_14_3_STRATEGY_SELECTION[
        "selected_strategy_id"
    ]
    == "RF-3"
)

assert (
    RF_5_14_3_STRATEGY_SELECTION[
        "selected_strategy_name"
    ]
    == "Controlled Random Oversampling"
)

assert (
    RF_5_14_3_STRATEGY_SELECTION[
        "selection_partition"
    ]
    == "Validation"
)

assert (
    RF_5_14_3_STRATEGY_SELECTION[
        "primary_selection_metric"
    ]
    == "macro_f1"
)

assert (
    RF_5_14_3_STRATEGY_SELECTION[
        "primary_selection_direction"
    ]
    == "maximize"
)

assert (
    len(
        RF_5_14_3_STRATEGY_SELECTION[
            "candidate_strategy_order"
        ]
    )
    == 5
)

assert {
    item["strategy_id"]
    for item in RF_5_14_3_STRATEGY_SELECTION[
        "candidate_strategy_order"
    ]
} == {
    "RF-0",
    "RF-1",
    "RF-2",
    "RF-3",
    "RF-4",
}

assert (
    RF_5_14_3_STRATEGY_SELECTION[
        "candidate_strategy_order"
    ][0]["strategy_id"]
    == "RF-3"
)

print("✓ Strategy-selection artifact is valid")
print("✓ Selected strategy = RF-3")
print("✓ Strategy name = Controlled Random Oversampling")
print("✓ Selection partition = Validation")
print("✓ Primary metric = macro_f1")
print("✓ All five RF strategies are represented")
print("✓ RF-3 is first in persisted Validation Macro F1 ordering")


# ----------------------------------------------------------------
# 4. LOAD PERSISTED VALIDATION COMPARISON ARTIFACTS
# ----------------------------------------------------------------

print("\n[PERSISTED VALIDATION COMPARISON INTEGRITY]")

RF_5_14_3_VALIDATION_RESULTS_PATH = Path(
    RF_EXPERIMENT_ARTIFACTS[
        "validation_results"
    ]
)

RF_5_14_3_EXPERIMENT_RESULTS_PATH = (
    RF_5_14_2_EXPERIMENT_RESULTS_PATH
)

RF_5_14_3_VALIDATION_RESULTS = pd.read_csv(
    RF_5_14_3_VALIDATION_RESULTS_PATH
)

RF_5_14_3_EXPERIMENT_RESULTS = pd.read_csv(
    RF_5_14_3_EXPERIMENT_RESULTS_PATH
)

RF_5_14_3_REQUIRED_VALIDATION_COLUMNS = {
    "strategy_id",
    "strategy_name",
    "macro_f1",
    "macro_recall",
    "balanced_accuracy",
    "weighted_f1",
    "accuracy",
    "benign_false_positive_rate",
    "attack_false_negatives",
    "macro_roc_auc_ovr",
}

assert RF_5_14_3_REQUIRED_VALIDATION_COLUMNS.issubset(
    RF_5_14_3_VALIDATION_RESULTS.columns
)

assert len(
    RF_5_14_3_VALIDATION_RESULTS
) == 5

assert set(
    RF_5_14_3_VALIDATION_RESULTS[
        "strategy_id"
    ]
) == {
    "RF-0",
    "RF-1",
    "RF-2",
    "RF-3",
    "RF-4",
}

for column_name in (
    "macro_f1",
    "macro_recall",
    "balanced_accuracy",
    "weighted_f1",
    "accuracy",
):

    values = RF_5_14_3_VALIDATION_RESULTS[
        column_name
    ].to_numpy(dtype=np.float64)

    assert np.isfinite(values).all()
    assert (
        (values >= 0.0)
        &
        (values <= 1.0)
    ).all()


RF_5_14_3_VALIDATION_TOP_STRATEGY = (
    RF_5_14_3_VALIDATION_RESULTS
    .sort_values(
        "macro_f1",
        ascending=False
    )
    .iloc[0]
)

assert (
    RF_5_14_3_VALIDATION_TOP_STRATEGY[
        "strategy_id"
    ]
    == "RF-3"
)

assert (
    RF_5_14_3_VALIDATION_TOP_STRATEGY[
        "strategy_name"
    ]
    == "Controlled Random Oversampling"
)


# The two persisted comparison artifacts were written from the same
# validated comparison table in Section 5.9.3.

pd.testing.assert_frame_equal(
    RF_5_14_3_VALIDATION_RESULTS,
    RF_5_14_3_EXPERIMENT_RESULTS,
    check_dtype=True,
    check_like=False,
)

print("✓ Validation-results schema is valid")
print("✓ Five RF strategies are represented")
print("✓ Validation metric values are finite and in valid ranges")
print("✓ RF-3 has the highest persisted Validation Macro F1")
print("✓ validation_results.csv and rf_experiment_results.csv agree exactly")


# ----------------------------------------------------------------
# 5. FINAL MODEL METADATA INTEGRITY
# ----------------------------------------------------------------

print("\n[FINAL MODEL METADATA INTEGRITY]")

RF_5_14_3_FINAL_MODEL_METADATA_PATH = Path(
    RF_EXPERIMENT_ARTIFACTS[
        "final_model_metadata"
    ]
)

with open(
    RF_5_14_3_FINAL_MODEL_METADATA_PATH,
    "r",
    encoding="utf-8"
) as file:

    RF_5_14_3_FINAL_MODEL_METADATA = json.load(file)


assert (
    RF_5_14_3_FINAL_MODEL_METADATA[
        "strategy_id"
    ]
    == "RF-3"
)

assert (
    RF_5_14_3_FINAL_MODEL_METADATA[
        "strategy_name"
    ]
    == "Controlled Random Oversampling"
)

assert (
    RF_5_14_3_FINAL_MODEL_METADATA[
        "training_partition"
    ]
    == "Training"
)

assert (
    RF_5_14_3_FINAL_MODEL_METADATA[
        "validation_used_for_fitting"
    ]
    is False
)

assert (
    RF_5_14_3_FINAL_MODEL_METADATA[
        "independent_test_used"
    ]
    is False
)

assert (
    RF_5_14_3_FINAL_MODEL_METADATA[
        "final_model"
    ]
    is True
)

assert (
    RF_5_14_3_FINAL_MODEL_METADATA[
        "persistence_completed"
    ]
    is True
)

assert (
    RF_5_14_3_FINAL_MODEL_METADATA[
        "feature_count"
    ]
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

assert (
    RF_5_14_3_FINAL_MODEL_METADATA[
        "class_count"
    ]
    == len(EXPECTED_RF_CLASS_IDS)
)

assert (
    RF_5_14_3_FINAL_MODEL_METADATA[
        "common_random_forest_configuration"
    ]
    == RF_COMMON_CONFIGURATION
)

assert (
    RF_5_14_3_FINAL_MODEL_METADATA[
        "random_seed"
    ]
    == int(RANDOM_SEED)
)

print("✓ Final metadata identifies RF-3")
print("✓ Training is the fitting partition")
print("✓ Validation excluded from fitting")
print("✓ Independent Test excluded from fitting")
print("✓ Final-model flag = True")
print("✓ Persistence-completed flag = True")
print("✓ Metadata feature count = 32")
print("✓ Metadata class count = 9")
print("✓ Metadata RF configuration matches frozen configuration")
print("✓ Metadata random seed matches established seed")


# ----------------------------------------------------------------
# 6. LOAD AND VALIDATE PERSISTED FINAL RANDOM FOREST
# ----------------------------------------------------------------

print("\n[PERSISTED FINAL RANDOM FOREST INTEGRITY]")

RF_5_14_3_FINAL_MODEL_PATH = Path(
    RF_EXPERIMENT_ARTIFACTS[
        "final_model"
    ]
)

RF_5_14_3_FINAL_MODEL = joblib.load(
    RF_5_14_3_FINAL_MODEL_PATH
)

assert hasattr(
    RF_5_14_3_FINAL_MODEL,
    "estimators_"
)

assert (
    RF_5_14_3_FINAL_MODEL.n_features_in_
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

assert np.array_equal(
    RF_5_14_3_FINAL_MODEL.classes_,
    np.asarray(EXPECTED_RF_CLASS_IDS)
)

assert (
    RF_5_14_3_FINAL_MODEL.n_estimators
    == RF_COMMON_CONFIGURATION[
        "n_estimators"
    ]
)

assert (
    RF_5_14_3_FINAL_MODEL.max_features
    == RF_COMMON_CONFIGURATION[
        "max_features"
    ]
)

assert (
    RF_5_14_3_FINAL_MODEL.max_depth
    == RF_COMMON_CONFIGURATION[
        "max_depth"
    ]
)

assert (
    RF_5_14_3_FINAL_MODEL.bootstrap
    == RF_COMMON_CONFIGURATION[
        "bootstrap"
    ]
)

assert (
    RF_5_14_3_FINAL_MODEL.n_jobs
    == RF_COMMON_CONFIGURATION[
        "n_jobs"
    ]
)

assert (
    RF_5_14_3_FINAL_MODEL.random_state
    == RANDOM_SEED
)

assert (
    RF_5_14_3_FINAL_MODEL.class_weight
    is None
)

print("✓ Persisted final artifact is a fitted Random Forest")
print("✓ Final model feature count = 32")
print("✓ Final model class count = 9")
print("✓ Final model class IDs match RF taxonomy")
print("✓ Frozen Random Forest configuration matches")
print("✓ Final model random_state matches established seed")
print("✓ Final model class_weight = None")


# ----------------------------------------------------------------
# 7. FINAL MODEL ↔ FEATURE-IMPORTANCE CROSS-CONSISTENCY
# ----------------------------------------------------------------

print("\n[FINAL MODEL ↔ FEATURE-IMPORTANCE CONSISTENCY]")

RF_5_14_3_FEATURE_IMPORTANCE_PATH = Path(
    RF_EXPERIMENT_ARTIFACTS[
        "feature_importance"
    ]
)

RF_5_14_3_FEATURE_IMPORTANCE = pd.read_csv(
    RF_5_14_3_FEATURE_IMPORTANCE_PATH
)

assert (
    RF_5_14_3_FEATURE_IMPORTANCE.columns.tolist()
    == [
        "feature",
        "importance",
    ]
)

assert (
    len(RF_5_14_3_FEATURE_IMPORTANCE)
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

assert (
    RF_5_14_3_FEATURE_IMPORTANCE[
        "feature"
    ].tolist()
    == list(RF_FEATURE_ORDER)
)

RF_5_14_3_MODEL_IMPORTANCES = np.asarray(
    RF_5_14_3_FINAL_MODEL.feature_importances_,
    dtype=np.float64
)

RF_5_14_3_PERSISTED_IMPORTANCES = (
    RF_5_14_3_FEATURE_IMPORTANCE[
        "importance"
    ].to_numpy(dtype=np.float64)
)

assert np.isfinite(
    RF_5_14_3_PERSISTED_IMPORTANCES
).all()

assert (
    RF_5_14_3_PERSISTED_IMPORTANCES
    >= 0
).all()

assert np.isclose(
    RF_5_14_3_PERSISTED_IMPORTANCES.sum(),
    1.0,
    atol=1e-10
)

assert np.allclose(
    RF_5_14_3_PERSISTED_IMPORTANCES,
    RF_5_14_3_MODEL_IMPORTANCES,
    atol=1e-12
)

print("✓ Feature-importance schema is valid")
print("✓ 32 features are present")
print("✓ Feature order matches RF_FEATURE_ORDER")
print("✓ Importance values are finite and non-negative")
print("✓ Importance values sum to 1")
print("✓ Persisted importance values match the fitted final RF model")


# ----------------------------------------------------------------
# 8. INDEPENDENT TEST ARTIFACT CROSS-CONSISTENCY
# ----------------------------------------------------------------

print("\n[INDEPENDENT TEST ARTIFACT CROSS-CONSISTENCY]")

RF_5_14_3_TEST_RESULTS = pd.read_csv(
    RF_EXPERIMENT_ARTIFACTS[
        "test_results"
    ]
)

RF_5_14_3_CONFUSION_MATRIX = pd.read_csv(
    RF_EXPERIMENT_ARTIFACTS[
        "confusion_matrix"
    ],
    index_col=0
)

RF_5_14_3_CLASSIFICATION_REPORT = pd.read_csv(
    RF_EXPERIMENT_ARTIFACTS[
        "classification_report"
    ]
)

RF_5_14_3_REQUIRED_TEST_COLUMNS = {
    "strategy_id",
    "strategy_name",
    "partition",
    "test_observations",
    "accuracy",
    "balanced_accuracy",
    "macro_recall",
    "macro_f1",
    "weighted_f1",
    "benign_false_positive_rate",
    "attack_false_negatives",
    "macro_roc_auc_ovr",
    "inference_time_seconds",
    "inference_throughput_samples_per_second",
}

assert RF_5_14_3_REQUIRED_TEST_COLUMNS.issubset(
    RF_5_14_3_TEST_RESULTS.columns
)

assert len(
    RF_5_14_3_TEST_RESULTS
) == 1

RF_5_14_3_TEST_ROW = (
    RF_5_14_3_TEST_RESULTS.iloc[0]
)

assert (
    RF_5_14_3_TEST_ROW["strategy_id"]
    == "RF-3"
)

assert (
    RF_5_14_3_TEST_ROW["strategy_name"]
    == "Controlled Random Oversampling"
)

assert (
    str(
        RF_5_14_3_TEST_ROW["partition"]
    ).strip()
    == "Independent Test"
)

assert (
    int(
        RF_5_14_3_TEST_ROW["test_observations"]
    )
    == EXPECTED_RF_PARTITION_ROWS["Test"]
)

for column_name in (
    "accuracy",
    "balanced_accuracy",
    "macro_recall",
    "macro_f1",
    "weighted_f1",
    "benign_false_positive_rate",
    "macro_roc_auc_ovr",
    "inference_time_seconds",
    "inference_throughput_samples_per_second",
):

    assert np.isfinite(
        float(
            RF_5_14_3_TEST_ROW[
                column_name
            ]
        )
    )

assert (
    0.0
    <= float(
        RF_5_14_3_TEST_ROW[
            "accuracy"
        ]
    )
    <= 1.0
)

assert (
    0.0
    <= float(
        RF_5_14_3_TEST_ROW[
            "macro_f1"
        ]
    )
    <= 1.0
)

assert (
    float(
        RF_5_14_3_TEST_ROW[
            "inference_time_seconds"
        ]
    )
    > 0
)

assert (
    float(
        RF_5_14_3_TEST_ROW[
            "inference_throughput_samples_per_second"
        ]
    )
    > 0
)


# Confusion matrix
RF_5_14_3_CLASS_NAMES = [
    RF_CLASS_MAPPING[class_id]
    for class_id in EXPECTED_RF_CLASS_IDS
]

assert (
    RF_5_14_3_CONFUSION_MATRIX.shape
    == (9, 9)
)

assert (
    RF_5_14_3_CONFUSION_MATRIX.columns.tolist()
    == RF_5_14_3_CLASS_NAMES
)

assert (
    RF_5_14_3_CONFUSION_MATRIX.index.tolist()
    == RF_5_14_3_CLASS_NAMES
)

RF_5_14_3_CONFUSION_VALUES = (
    RF_5_14_3_CONFUSION_MATRIX.to_numpy(
        dtype=np.int64
    )
)

assert (
    RF_5_14_3_CONFUSION_VALUES >= 0
).all()

assert (
    RF_5_14_3_CONFUSION_VALUES.sum()
    == EXPECTED_RF_PARTITION_ROWS["Test"]
)


# Classification report
assert (
    RF_5_14_3_CLASSIFICATION_REPORT.columns
    .tolist()
    == [
        "class_id",
        "class_name",
        "precision",
        "recall",
        "f1",
        "support",
    ]
)

assert (
    len(
        RF_5_14_3_CLASSIFICATION_REPORT
    )
    == 9
)

assert (
    RF_5_14_3_CLASSIFICATION_REPORT[
        "class_id"
    ].to_numpy(dtype=np.int64).tolist()
    == list(EXPECTED_RF_CLASS_IDS)
)

assert (
    RF_5_14_3_CLASSIFICATION_REPORT[
        "class_name"
    ].tolist()
    == RF_5_14_3_CLASS_NAMES
)

RF_5_14_3_SUPPORT = (
    RF_5_14_3_CLASSIFICATION_REPORT[
        "support"
    ].to_numpy(dtype=np.int64)
)

assert (
    RF_5_14_3_SUPPORT.sum()
    == EXPECTED_RF_PARTITION_ROWS["Test"]
)

print("✓ Test result identifies RF-3")
print("✓ Test result identifies Independent Test")
print("✓ Test observation count = 565,510")
print("✓ Confusion matrix is 9 × 9")
print("✓ Confusion matrix accounts for all Test observations")
print("✓ Classification report contains all nine classes")
print("✓ Classification report support accounts for all Test observations")


# ----------------------------------------------------------------
# 9. TEST RESULT ↔ CONFUSION MATRIX CONSISTENCY
# ----------------------------------------------------------------

print("\n[TEST RESULT ↔ CONFUSION MATRIX CONSISTENCY]")

RF_5_14_3_TOTAL_MISCLASSIFICATIONS = int(
    RF_5_14_3_CONFUSION_VALUES.sum()
    -
    np.trace(
        RF_5_14_3_CONFUSION_VALUES
    )
)

RF_5_14_3_BENIGN_FALSE_POSITIVES = int(
    RF_5_14_3_CONFUSION_VALUES[
        1:,
        0
    ].sum()
)

RF_5_14_3_ATTACK_FALSE_NEGATIVES = int(
    RF_5_14_3_CONFUSION_VALUES[
        1:,
        :
    ].sum()
    -
    np.trace(
        RF_5_14_3_CONFUSION_VALUES[
            1:,
            1:
        ]
    )
)

RF_5_14_3_BENIGN_ACTUAL_NEGATIVES = int(
    RF_5_14_3_CONFUSION_VALUES[
        1:,
        :
    ].sum()
)

if RF_5_14_3_BENIGN_ACTUAL_NEGATIVES > 0:

    RF_5_14_3_BENIGN_FPR = (
        RF_5_14_3_BENIGN_FALSE_POSITIVES
        /
        RF_5_14_3_BENIGN_ACTUAL_NEGATIVES
    )

else:

    RF_5_14_3_BENIGN_FPR = 0.0


assert (
    int(
        RF_5_14_3_TEST_ROW[
            "attack_false_negatives"
        ]
    )
    == RF_5_14_3_ATTACK_FALSE_NEGATIVES
)

assert np.isclose(
    float(
        RF_5_14_3_TEST_ROW[
            "benign_false_positive_rate"
        ]
    ),
    RF_5_14_3_BENIGN_FPR,
    atol=1e-12
)

assert (
    RF_5_14_3_TEST_ROW[
        "test_observations"
    ]
    ==
    RF_5_14_3_CONFUSION_VALUES.sum()
)

print(
    f"✓ Total Test observations reconciled = "
    f"{RF_5_14_3_CONFUSION_VALUES.sum():,}"
)

print(
    f"✓ Attack false negatives reconciled = "
    f"{RF_5_14_3_ATTACK_FALSE_NEGATIVES:,}"
)

print(
    f"✓ BENIGN false-positive rate reconciled = "
    f"{RF_5_14_3_BENIGN_FPR:.6f}"
)

print(
    f"✓ Total misclassifications = "
    f"{RF_5_14_3_TOTAL_MISCLASSIFICATIONS:,}"
)


# ----------------------------------------------------------------
# 10. CLASSIFICATION REPORT ↔ CONFUSION MATRIX CONSISTENCY
# ----------------------------------------------------------------

print("\n[CLASSIFICATION REPORT ↔ CONFUSION MATRIX CONSISTENCY]")

RF_5_14_3_TRUE_POSITIVES = np.diag(
    RF_5_14_3_CONFUSION_VALUES
)

RF_5_14_3_REPORTED_RECALL = (
    RF_5_14_3_CLASSIFICATION_REPORT[
        "recall"
    ].to_numpy(dtype=np.float64)
)

RF_5_14_3_REPORTED_F1 = (
    RF_5_14_3_CLASSIFICATION_REPORT[
        "f1"
    ].to_numpy(dtype=np.float64)
)

RF_5_14_3_COMPUTED_RECALL = np.divide(
    RF_5_14_3_TRUE_POSITIVES,
    RF_5_14_3_SUPPORT,
    out=np.zeros(9, dtype=np.float64),
    where=RF_5_14_3_SUPPORT > 0
)

assert np.allclose(
    RF_5_14_3_REPORTED_RECALL,
    RF_5_14_3_COMPUTED_RECALL,
    atol=1e-12
)

assert (
    (
        RF_5_14_3_CLASSIFICATION_REPORT[
            "precision"
        ].to_numpy(dtype=np.float64)
        >= 0
    )
    &
    (
        RF_5_14_3_CLASSIFICATION_REPORT[
            "precision"
        ].to_numpy(dtype=np.float64)
        <= 1
    )
).all()

assert (
    (
        RF_5_14_3_REPORTED_RECALL
        >= 0
    )
    &
    (
        RF_5_14_3_REPORTED_RECALL
        <= 1
    )
).all()

assert (
    (
        RF_5_14_3_REPORTED_F1
        >= 0
    )
    &
    (
        RF_5_14_3_REPORTED_F1
        <= 1
    )
).all()

print("✓ Classification-report support matches Test taxonomy")
print("✓ Classification-report recall matches confusion matrix")
print("✓ Classification-report metric ranges are valid")


# ----------------------------------------------------------------
# 11. SECTION 5.13 INTERPRETATION ARTIFACT INTEGRITY
# ----------------------------------------------------------------

print("\n[SECTION 5.13 INTERPRETATION ARTIFACT INTEGRITY]")

RF_5_14_3_CLASS_WISE = pd.read_csv(
    RF_INTERPRETATION_DIR /
    "rf_class_wise_error_analysis.csv"
)

RF_5_14_3_CONFUSION_PATTERN = pd.read_csv(
    RF_INTERPRETATION_DIR /
    "rf_confusion_pattern_analysis.csv"
)

RF_5_14_3_DOMINANT_ERROR = pd.read_csv(
    RF_INTERPRETATION_DIR /
    "rf_dominant_error_analysis.csv"
)

RF_5_14_3_MINORITY_CLASS = pd.read_csv(
    RF_INTERPRETATION_DIR /
    "rf_minority_class_analysis.csv"
)

with open(
    RF_INTERPRETATION_DIR /
    "rf_error_analysis_summary.json",
    "r",
    encoding="utf-8"
) as file:

    RF_5_14_3_ERROR_SUMMARY = json.load(file)


assert (
    RF_5_14_3_CLASS_WISE.columns.tolist()
    == [
        "class_id",
        "class_name",
        "precision",
        "recall",
        "f1",
        "support",
        "true_positives",
        "false_positives",
        "false_negatives",
        "error_rate",
        "support_percentage",
    ]
)

assert len(
    RF_5_14_3_CLASS_WISE
) == 9

assert (
    RF_5_14_3_CLASS_WISE[
        "class_id"
    ].tolist()
    == list(EXPECTED_RF_CLASS_IDS)
)

assert (
    RF_5_14_3_CLASS_WISE[
        "support"
    ].sum()
    == EXPECTED_RF_PARTITION_ROWS["Test"]
)

assert (
    RF_5_14_3_CONFUSION_PATTERN.columns.tolist()
    == [
        "actual_class_id",
        "actual_class",
        "predicted_class_id",
        "predicted_class",
        "confusion_count",
    ]
)

assert (
    RF_5_14_3_CONFUSION_PATTERN[
        "confusion_count"
    ].sum()
    == RF_5_14_3_TOTAL_MISCLASSIFICATIONS
)

assert (
    RF_5_14_3_DOMINANT_ERROR.columns.tolist()
    == [
        "actual_class_id",
        "actual_class",
        "dominant_error_prediction_id",
        "dominant_error_prediction",
        "error_count",
    ]
)

assert len(
    RF_5_14_3_DOMINANT_ERROR
) == 9

assert (
    RF_5_14_3_DOMINANT_ERROR[
        "actual_class_id"
    ].tolist()
    == list(EXPECTED_RF_CLASS_IDS)
)

assert (
    RF_5_14_3_MINORITY_CLASS.columns.tolist()
    == [
        "class_id",
        "class_name",
        "support",
        "support_percentage",
        "precision",
        "recall",
        "f1",
        "false_positives",
        "false_negatives",
    ]
)

assert len(
    RF_5_14_3_MINORITY_CLASS
) == 3

print("✓ Class-wise error-analysis artifact schema is valid")
print("✓ Class-wise support reconciles with Test size")
print("✓ Confusion-pattern artifact reconciles with total errors")
print("✓ Dominant-error artifact contains all nine classes")
print("✓ Minority-class artifact contains three classes")


# ----------------------------------------------------------------
# 12. INTERPRETATION SUMMARY CROSS-CONSISTENCY
# ----------------------------------------------------------------

print("\n[INTERPRETATION SUMMARY CROSS-CONSISTENCY]")

assert (
    RF_5_14_3_ERROR_SUMMARY[
        "strategy_id"
    ]
    == "RF-3"
)

assert (
    RF_5_14_3_ERROR_SUMMARY[
        "strategy_name"
    ]
    == "Controlled Random Oversampling"
)

assert (
    RF_5_14_3_ERROR_SUMMARY[
        "evaluation_partition"
    ]
    == "Independent Test"
)

assert (
    RF_5_14_3_ERROR_SUMMARY[
        "test_observations"
    ]
    == EXPECTED_RF_PARTITION_ROWS["Test"]
)

assert (
    RF_5_14_3_ERROR_SUMMARY[
        "class_count"
    ]
    == 9
)

assert (
    RF_5_14_3_ERROR_SUMMARY[
        "feature_count"
    ]
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

assert (
    RF_5_14_3_ERROR_SUMMARY[
        "total_misclassifications"
    ]
    == RF_5_14_3_TOTAL_MISCLASSIFICATIONS
)

assert (
    RF_5_14_3_ERROR_SUMMARY[
        "attack_false_negatives"
    ]
    == RF_5_14_3_ATTACK_FALSE_NEGATIVES
)

assert (
    RF_5_14_3_ERROR_SUMMARY[
        "benign_false_positives"
    ]
    == RF_5_14_3_BENIGN_FALSE_POSITIVES
)

RF_5_14_3_FEATURE_RANKING = (
    RF_5_14_3_FEATURE_IMPORTANCE
    .sort_values(
        "importance",
        ascending=False
    )
    .reset_index(drop=True)
)

assert (
    RF_5_14_3_ERROR_SUMMARY[
        "highest_importance_feature"
    ]
    ==
    RF_5_14_3_FEATURE_RANKING.iloc[0][
        "feature"
    ]
)

assert np.isclose(
    float(
        RF_5_14_3_ERROR_SUMMARY[
            "highest_importance"
        ]
    ),
    float(
        RF_5_14_3_FEATURE_RANKING.iloc[0][
            "importance"
        ]
    ),
    atol=1e-12
)

assert (
    RF_5_14_3_ERROR_SUMMARY[
        "lowest_importance_feature"
    ]
    ==
    RF_5_14_3_FEATURE_RANKING.iloc[-1][
        "feature"
    ]
)

assert np.isclose(
    float(
        RF_5_14_3_ERROR_SUMMARY[
            "lowest_importance"
        ]
    ),
    float(
        RF_5_14_3_FEATURE_RANKING.iloc[-1][
            "importance"
        ]
    ),
    atol=1e-12
)

assert (
    RF_5_14_3_ERROR_SUMMARY[
        "feature_importance_artifact"
    ]
    ==
    str(
        RF_5_14_3_FEATURE_IMPORTANCE_PATH
    )
)

print("✓ Interpretation summary strategy is consistent")
print("✓ Interpretation summary partition is consistent")
print("✓ Interpretation summary Test size is consistent")
print("✓ Interpretation summary error counts are consistent")
print("✓ Interpretation summary feature-importance values are consistent")


# ----------------------------------------------------------------
# 13. ARTIFACT-OUTPUT CONFIGURATION INTEGRITY
# ----------------------------------------------------------------

print("\n[ARTIFACT-OUTPUT CONFIGURATION INTEGRITY]")

with open(
    RF_5_14_2_ARTIFACT_CONFIGURATION_PATH,
    "r",
    encoding="utf-8"
) as file:

    RF_5_14_3_ARTIFACT_CONFIGURATION = json.load(file)

assert (
    RF_5_14_3_ARTIFACT_CONFIGURATION[
        "output_root"
    ]
    == str(RANDOM_FOREST_OUTPUT_DIR)
)

assert (
    RF_5_14_3_ARTIFACT_CONFIGURATION[
        "evaluation_directory"
    ]
    == str(RF_EVALUATION_DIR)
)

assert (
    RF_5_14_3_ARTIFACT_CONFIGURATION[
        "interpretation_directory"
    ]
    == str(RF_INTERPRETATION_DIR)
)

assert (
    RF_5_14_3_ARTIFACT_CONFIGURATION[
        "trained_model_directory"
    ]
    == str(RANDOM_FOREST_MODEL_DIR)
)

assert (
    RF_5_14_3_ARTIFACT_CONFIGURATION[
    "artifacts"
    ]
    ==
    {
        name: str(path)
        for name, path
        in RF_EXPERIMENT_ARTIFACTS.items()
    }
)

assert (
    RF_5_14_3_ARTIFACT_CONFIGURATION[
        "test_results_authorized_only_after_final_evaluation"
    ]
    is True
)

assert (
    RF_5_14_3_ARTIFACT_CONFIGURATION[
        "n04_artifacts_modified"
    ]
    is False
)

print("✓ Persisted output-root configuration is valid")
print("✓ Persisted evaluation directory is consistent")
print("✓ Persisted interpretation directory is consistent")
print("✓ Persisted trained-model directory is consistent")
print("✓ Persisted artifact mapping matches configured mapping")
print("✓ Test-result authorization policy is preserved")
print("✓ N04 modification flag = False")


# ----------------------------------------------------------------
# 14. KNOWN MAPPING OBSERVATIONS — NOT SILENTLY REPAIRED
# ----------------------------------------------------------------

print("\n[KNOWN ARTIFACT-MAPPING OBSERVATIONS]")

assert (
    "RF_5_14_2_MAPPING_OBSERVATIONS"
    in globals()
)

RF_5_14_3_MODEL_CONFIGURATION_MAPPING = (
    RF_5_14_2_MAPPING_OBSERVATIONS[
        "model_configuration"
    ]
)

RF_5_14_3_EXPERIMENT_RESULTS_MAPPING = (
    RF_5_14_2_MAPPING_OBSERVATIONS[
        "experiment_results"
    ]
)

print(
    "✓ Historical model_configuration mapping observation retained"
)

print(
    "✓ Historical experiment_results mapping observation retained"
)

print(
    "✓ No artifact mapping was silently rewritten"
)

print(
    "✓ Actual persisted experiment-results artifact remains "
    "the validated downstream source"
)


# ----------------------------------------------------------------
# 15. SECTION 5.14.3 VALIDATION STATE
# ----------------------------------------------------------------

RF_5_14_3_VALIDATION = {

    "section_5_14_2_completed":
        all(
            RF_5_14_2_VALIDATION.values()
        ),

    "strategy_selection_integrity_valid":
        True,

    "validation_results_integrity_valid":
        True,

    "validation_experiment_results_consistent":
        True,

    "final_metadata_integrity_valid":
        True,

    "final_model_integrity_valid":
        True,

    "model_feature_importance_consistent":
        True,

    "test_results_integrity_valid":
        True,

    "confusion_matrix_integrity_valid":
        True,

    "classification_report_integrity_valid":
        True,

    "test_artifact_cross_consistency_valid":
        True,

    "interpretation_artifacts_integrity_valid":
        True,

    "interpretation_summary_consistent":
        True,

    "artifact_configuration_integrity_valid":
        True,

    "known_mapping_observations_documented":
        True,

    "n04_immutable":
        True,

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_test_inference":
        True,

    "no_new_test_metrics":
        True,

    "no_strategy_selection":
        True,

    "no_hyperparameter_selection":
        True,

    "no_new_error_analysis":
        True,
}


assert all(
    RF_5_14_3_VALIDATION.values()
), (
    "5.14.3 RF artifact integrity and "
    "cross-artifact consistency validation failed."
)


# ----------------------------------------------------------------
# 16. FINAL 5.14.3 READINESS GATE
# ----------------------------------------------------------------

print("\n[5.14.3 ARTIFACT INTEGRITY READINESS GATE]")

print("✓ Strategy-selection artifact integrity validated")
print("✓ Validation comparison artifacts cross-validated")
print("✓ Final-model metadata integrity validated")
print("✓ Persisted final RF model integrity validated")
print("✓ Model ↔ feature-importance consistency validated")
print("✓ Independent Test artifacts cross-validated")
print("✓ Confusion-matrix accounting reconciled")
print("✓ Classification-report accounting reconciled")
print("✓ Section 5.13 interpretation artifacts validated")
print("✓ Interpretation summary cross-consistency validated")
print("✓ Artifact-output configuration validated")
print("✓ Known mapping observations documented")
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No Test inference performed")
print("✓ No new Test metrics calculated")
print("✓ No strategy selection performed")
print("✓ No hyperparameter selection performed")
print("✓ No new error analysis performed")
print("✓ N04 remains immutable")

print("\n" + "=" * 72)

print(
    "5.14.3 — RF ARTIFACT INTEGRITY AND "
    "CROSS-ARTIFACT CONSISTENCY VALIDATION PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.14.4 — RANDOM FOREST ARTIFACT "
    "PERSISTENCE COMPLETION AND READINESS GATE"
)

print("=" * 72)

========================================================================
5.14.3 — RF ARTIFACT INTEGRITY AND CROSS-ARTIFACT CONSISTENCY VALIDATION
========================================================================

[PREVIOUS SECTION COMPLETION BOUNDARY]
✓ Section 5.14.2 completed and validated
✓ Persisted RF artifact inventory remains available

[AUTHORITATIVE RF CONTRACT BOUNDARY]
✓ RF artifact mapping = 11 entries
✓ RF taxonomy = 9 classes
✓ RF feature count = 32
✓ Test partition size = 565,510
✓ Frozen RF configuration remains available

[PERSISTED STRATEGY-SELECTION ARTIFACT INTEGRITY]
✓ Strategy-selection artifact is valid
✓ Selected strategy = RF-3
✓ Strategy name = Controlled Random Oversampling
✓ Selection partition = Validation
✓ Primary metric = macro_f1
✓ All five RF strategies are represented
✓ RF-3 is first in persisted Validation Macro F1 ordering

[PERSISTED VALIDATION COMPARISON INTEGRITY]
✓ Validation-results schema is valid
✓ Five RF strategies are represented
✓ Validation metric values are finite and in valid ranges
✓ RF-3 has the highest persisted Validation Macro F1
✓ validation_results.csv and rf_experiment_results.csv agree exactly

[FINAL MODEL METADATA INTEGRITY]
✓ Final metadata identifies RF-3
✓ Training is the fitting partition
✓ Validation excluded from fitting
✓ Independent Test excluded from fitting
✓ Final-model flag = True
✓ Persistence-completed flag = True
✓ Metadata feature count = 32
✓ Metadata class count = 9
✓ Metadata RF configuration matches frozen configuration
✓ Metadata random seed matches established seed

[PERSISTED FINAL RANDOM FOREST INTEGRITY]
✓ Persisted final artifact is a fitted Random Forest
✓ Final model feature count = 32
✓ Final model class count = 9
✓ Final model class IDs match RF taxonomy
✓ Frozen Random Forest configuration matches
✓ Final model random_state matches established seed
✓ Final model class_weight = None

[FINAL MODEL ↔ FEATURE-IMPORTANCE CONSISTENCY]
✓ Feature-importance schema is valid
✓ 32 features are present
✓ Feature order matches RF_FEATURE_ORDER
✓ Importance values are finite and non-negative
✓ Importance values sum to 1
✓ Persisted importance values match the fitted final RF model

[INDEPENDENT TEST ARTIFACT CROSS-CONSISTENCY]
✓ Test result identifies RF-3
✓ Test result identifies Independent Test
✓ Test observation count = 565,510
✓ Confusion matrix is 9 × 9
✓ Confusion matrix accounts for all Test observations
✓ Classification report contains all nine classes
✓ Classification report support accounts for all Test observations

[TEST RESULT ↔ CONFUSION MATRIX CONSISTENCY]
✓ Total Test observations reconciled = 565,510
✓ Attack false negatives reconciled = 2,621
✓ BENIGN false-positive rate reconciled = 0.023603
✓ Total misclassifications = 3,250

[CLASSIFICATION REPORT ↔ CONFUSION MATRIX CONSISTENCY]
✓ Classification-report support matches Test taxonomy
✓ Classification-report recall matches confusion matrix
✓ Classification-report metric ranges are valid

[SECTION 5.13 INTERPRETATION ARTIFACT INTEGRITY]
✓ Class-wise error-analysis artifact schema is valid
✓ Class-wise support reconciles with Test size
✓ Confusion-pattern artifact reconciles with total errors
✓ Dominant-error artifact contains all nine classes
✓ Minority-class artifact contains three classes

[INTERPRETATION SUMMARY CROSS-CONSISTENCY]
✓ Interpretation summary strategy is consistent
✓ Interpretation summary partition is consistent
✓ Interpretation summary Test size is consistent
✓ Interpretation summary error counts are consistent
✓ Interpretation summary feature-importance values are consistent

[ARTIFACT-OUTPUT CONFIGURATION INTEGRITY]
✓ Persisted output-root configuration is valid
✓ Persisted evaluation directory is consistent
✓ Persisted interpretation directory is consistent
✓ Persisted trained-model directory is consistent
✓ Persisted artifact mapping matches configured mapping
✓ Test-result authorization policy is preserved
✓ N04 modification flag = False

[KNOWN ARTIFACT-MAPPING OBSERVATIONS]
✓ Historical model_configuration mapping observation retained
✓ Historical experiment_results mapping observation retained
✓ No artifact mapping was silently rewritten
✓ Actual persisted experiment-results artifact remains the validated downstream source

[5.14.3 ARTIFACT INTEGRITY READINESS GATE]
✓ Strategy-selection artifact integrity validated
✓ Validation comparison artifacts cross-validated
✓ Final-model metadata integrity validated
✓ Persisted final RF model integrity validated
✓ Model ↔ feature-importance consistency validated
✓ Independent Test artifacts cross-validated
✓ Confusion-matrix accounting reconciled
✓ Classification-report accounting reconciled
✓ Section 5.13 interpretation artifacts validated
✓ Interpretation summary cross-consistency validated
✓ Artifact-output configuration validated
✓ Known mapping observations documented
✓ No model fitting performed
✓ No resampling performed
✓ No Test inference performed
✓ No new Test metrics calculated
✓ No strategy selection performed
✓ No hyperparameter selection performed
✓ No new error analysis performed
✓ N04 remains immutable

========================================================================
5.14.3 — RF ARTIFACT INTEGRITY AND CROSS-ARTIFACT CONSISTENCY VALIDATION PASSED
========================================================================

READY FOR 5.14.4 — RANDOM FOREST ARTIFACT PERSISTENCE COMPLETION AND READINESS GATE
========================================================================

## 5.14.4 — Random Forest Artifact Persistence Completion and Readiness Gate

This subsection provides the final completion gate for Section 5.14.

The gate consolidates the results of:

- 5.14.1 — Artifact Persistence Definition and Boundary Validation,
- 5.14.2 — Final Random Forest Artifact Inventory and Existence Validation, and
- 5.14.3 — RF Artifact Integrity and Cross-Artifact Consistency Validation.

The persisted Random Forest package is considered ready when the completed
artifact inventory, integrity validation, and cross-artifact consistency
validation have all passed.

The two previously identified artifact-mapping observations remain explicitly
documented and are not silently rewritten:

- the historical `model_configuration` mapping points to a file that was not
  persisted at that mapped location;
- the historical `experiment_results` mapping differs from the actual
  persisted experiment-results location.

These observations do not invalidate the physically persisted artifact package,
because the actual persisted experiment-results artifact and the actual
artifact-output configuration have already been independently validated.

The Section 5.15 handoff manifest remains outside the Section 5.14 boundary
and is reserved for the final Random Forest handoff and validation stage.

No new model fitting, resampling, Test inference, Test metric calculation,
strategy selection, hyperparameter selection, or error analysis is performed.
No existing RF artifact is modified by this subsection.

In [ ]:
# ================================================================
# 5.14.4 — RANDOM FOREST ARTIFACT PERSISTENCE COMPLETION
#             AND READINESS GATE
# ================================================================

print("=" * 72)
print(
    "5.14.4 — RANDOM FOREST ARTIFACT PERSISTENCE "
    "COMPLETION AND READINESS GATE"
)
print("=" * 72)


# ----------------------------------------------------------------
# 1. SECTION 5.14 COMPLETION BOUNDARY
# ----------------------------------------------------------------

print("\n[SECTION 5.14 COMPLETION BOUNDARY]")

assert "RF_5_14_1_VALIDATION" in globals(), (
    "5.14.1 validation state is unavailable."
)

assert "RF_5_14_2_VALIDATION" in globals(), (
    "5.14.2 validation state is unavailable."
)

assert "RF_5_14_3_VALIDATION" in globals(), (
    "5.14.3 validation state is unavailable."
)

assert all(
    RF_5_14_1_VALIDATION.values()
), (
    "5.14.1 readiness gate has not passed."
)

assert all(
    RF_5_14_2_VALIDATION.values()
), (
    "5.14.2 readiness gate has not passed."
)

assert all(
    RF_5_14_3_VALIDATION.values()
), (
    "5.14.3 readiness gate has not passed."
)

print("✓ Section 5.14.1 completed and validated")
print("✓ Section 5.14.2 completed and validated")
print("✓ Section 5.14.3 completed and validated")


# ----------------------------------------------------------------
# 2. PERSISTED RF ARTIFACT PACKAGE COMPLETENESS
# ----------------------------------------------------------------

print("\n[PERSISTED RF ARTIFACT PACKAGE COMPLETENESS]")

assert (
    "RF_5_14_2_PERSISTED_ARTIFACT_INVENTORY"
    in globals()
), (
    "Persisted RF artifact inventory is unavailable."
)

RF_5_14_4_ARTIFACT_INVENTORY = (
    RF_5_14_2_PERSISTED_ARTIFACT_INVENTORY
)

assert (
    len(
        RF_5_14_4_ARTIFACT_INVENTORY
    )
    == 16
), (
    "Unexpected persisted RF artifact inventory size."
)

RF_5_14_4_INVALID_ARTIFACTS = [
    artifact_key
    for (
        artifact_key,
        artifact_info
    )
    in RF_5_14_4_ARTIFACT_INVENTORY.items()
    if not (
        artifact_info["exists"]
        and artifact_info["is_file"]
        and artifact_info["non_empty"]
    )
]

assert (
    len(
        RF_5_14_4_INVALID_ARTIFACTS
    )
    == 0
), (
    "Invalid persisted RF artifacts remain."
)

print(
    f"✓ Persisted RF artifacts checked = "
    f"{len(RF_5_14_4_ARTIFACT_INVENTORY)}"
)

print("✓ Missing/invalid persisted artifacts = 0")
print("✓ Final RF model is persisted")
print("✓ Final RF metadata is persisted")
print("✓ RF evaluation artifacts are persisted")
print("✓ RF interpretation artifacts are persisted")


# ----------------------------------------------------------------
# 3. CROSS-ARTIFACT INTEGRITY COMPLETION
# ----------------------------------------------------------------

print("\n[CROSS-ARTIFACT INTEGRITY COMPLETION]")

print("✓ RF-3 strategy selection is validated")
print("✓ Validation comparison artifacts are consistent")
print("✓ Final-model metadata is consistent with final model")
print("✓ Final model configuration is validated")
print("✓ Feature-importance artifact matches final model")
print("✓ Independent Test artifacts are mutually consistent")
print("✓ Classification-report accounting is reconciled")
print("✓ Confusion-matrix accounting is reconciled")
print("✓ Section 5.13 interpretation artifacts are consistent")
print("✓ Persisted artifact-output configuration is validated")


# ----------------------------------------------------------------
# 4. KNOWN MAPPING OBSERVATIONS
#
# These observations were deliberately retained rather than
# silently rewriting the historical RF_EXPERIMENT_ARTIFACTS mapping.
# ----------------------------------------------------------------

print("\n[KNOWN ARTIFACT-MAPPING OBSERVATIONS]")

assert (
    "RF_5_14_2_MAPPING_OBSERVATIONS"
    in globals()
), (
    "5.14.2 artifact-mapping observations are unavailable."
)

RF_5_14_4_MAPPING_OBSERVATIONS = (
    RF_5_14_2_MAPPING_OBSERVATIONS
)

assert (
    "model_configuration"
    in RF_5_14_4_MAPPING_OBSERVATIONS
)

assert (
    "experiment_results"
    in RF_5_14_4_MAPPING_OBSERVATIONS
)

assert (
    RF_5_14_4_MAPPING_OBSERVATIONS[
        "experiment_results"
    ][
        "actual_persisted_path_exists"
    ]
    is True
)

print(
    "✓ Historical model_configuration mapping observation "
    "remains documented"
)

print(
    "✓ Historical experiment_results mapping observation "
    "remains documented"
)

print(
    "✓ Actual persisted experiment-results artifact "
    "remains validated"
)

print(
    "✓ No historical artifact mapping was silently rewritten"
)


# ----------------------------------------------------------------
# 5. SECTION 5.15 HANDOFF BOUNDARY
# ----------------------------------------------------------------

print("\n[SECTION 5.15 HANDOFF BOUNDARY]")

assert (
    "handoff_manifest"
    in RF_EXPERIMENT_ARTIFACTS
), (
    "Established handoff_manifest mapping is unavailable."
)

print(
    "✓ handoff_manifest remains established in the RF mapping"
)

print(
    "✓ handoff_manifest remains excluded from Section 5.14"
)

print(
    "✓ Final RF handoff and manifest validation remain reserved "
    "for Section 5.15"
)


# ----------------------------------------------------------------
# 6. PROTECTED BOUNDARIES
# ----------------------------------------------------------------

print("\n[PROTECTED BOUNDARIES]")

assert all(
    RF_TEST_PROTECTION_CONTRACT.values()
), (
    "Independent Test protection contract is invalid."
)

print("✓ Independent Test protection remains valid")
print("✓ N04 remains immutable/read-only")
print("✓ No RF model fitting performed")
print("✓ No resampling performed")
print("✓ No synthetic sampling performed")
print("✓ No new Test inference performed")
print("✓ No new Test metrics calculated")
print("✓ No RF strategy selection performed")
print("✓ No hyperparameter selection performed")
print("✓ No new error analysis performed")


# ----------------------------------------------------------------
# 7. FINAL SECTION 5.14 VALIDATION STATE
# ----------------------------------------------------------------

RF_5_14_4_VALIDATION = {

    "section_5_14_1_completed":
        all(
            RF_5_14_1_VALIDATION.values()
        ),

    "section_5_14_2_completed":
        all(
            RF_5_14_2_VALIDATION.values()
        ),

    "section_5_14_3_completed":
        all(
            RF_5_14_3_VALIDATION.values()
        ),

    "persisted_artifact_inventory_complete":
        (
            len(
                RF_5_14_4_ARTIFACT_INVENTORY
            )
            == 16
        ),

    "persisted_artifact_inventory_valid":
        (
            len(
                RF_5_14_4_INVALID_ARTIFACTS
            )
            == 0
        ),

    "mapping_observations_documented":
        (
            "model_configuration"
            in RF_5_14_4_MAPPING_OBSERVATIONS
            and
            "experiment_results"
            in RF_5_14_4_MAPPING_OBSERVATIONS
        ),

    "actual_experiment_results_persisted":
        (
            RF_5_14_4_MAPPING_OBSERVATIONS[
                "experiment_results"
            ][
                "actual_persisted_path_exists"
            ]
            is True
        ),

    "handoff_manifest_reserved_for_5_15":
        (
            "handoff_manifest"
            in RF_EXPERIMENT_ARTIFACTS
        ),

    "independent_test_protected":
        all(
            RF_TEST_PROTECTION_CONTRACT.values()
        ),

    "n04_immutable":
        True,

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_test_inference":
        True,

    "no_new_test_metrics":
        True,

    "no_strategy_selection":
        True,

    "no_hyperparameter_selection":
        True,

    "no_new_error_analysis":
        True,
}


assert all(
    RF_5_14_4_VALIDATION.values()
), (
    "Section 5.14 final artifact persistence "
    "readiness gate failed."
)


# ----------------------------------------------------------------
# 8. FINAL SECTION 5.14 READINESS GATE
# ----------------------------------------------------------------

print("\n[5.14 FINAL ARTIFACT PERSISTENCE READINESS GATE]")

print("✓ 5.14.1 boundary validation passed")
print("✓ 5.14.2 artifact inventory passed")
print("✓ 5.14.3 integrity and consistency validation passed")
print("✓ 16 persisted RF artifacts are valid")
print("✓ No missing or invalid persisted artifacts remain")
print("✓ Known artifact-mapping observations are documented")
print("✓ Actual experiment-results artifact is validated")
print("✓ Section 5.15 handoff manifest remains excluded")
print("✓ Independent Test protection remains valid")
print("✓ N04 remains immutable")
print("✓ No model fitting performed")
print("✓ No resampling performed")
print("✓ No Test inference performed")
print("✓ No new Test metrics calculated")
print("✓ No strategy selection performed")
print("✓ No hyperparameter selection performed")
print("✓ No new error analysis performed")


# ----------------------------------------------------------------
# 9. FINAL SECTION 5.14 COMPLETION
# ----------------------------------------------------------------

print("\n" + "=" * 72)

print(
    "5.14.4 — RANDOM FOREST ARTIFACT PERSISTENCE "
    "COMPLETION AND READINESS GATE PASSED"
)

print("=" * 72)

print(
    "\nSECTION 5.14 — RANDOM FOREST ARTIFACT "
    "PERSISTENCE COMPLETED"
)

print(
    "\nREADY FOR 5.15 — FINAL RANDOM FOREST "
    "HANDOFF AND VALIDATION"
)

print("=" * 72)

========================================================================
5.14.4 — RANDOM FOREST ARTIFACT PERSISTENCE COMPLETION AND READINESS GATE
========================================================================

[SECTION 5.14 COMPLETION BOUNDARY]
✓ Section 5.14.1 completed and validated
✓ Section 5.14.2 completed and validated
✓ Section 5.14.3 completed and validated

[PERSISTED RF ARTIFACT PACKAGE COMPLETENESS]
✓ Persisted RF artifacts checked = 16
✓ Missing/invalid persisted artifacts = 0
✓ Final RF model is persisted
✓ Final RF metadata is persisted
✓ RF evaluation artifacts are persisted
✓ RF interpretation artifacts are persisted

[CROSS-ARTIFACT INTEGRITY COMPLETION]
✓ RF-3 strategy selection is validated
✓ Validation comparison artifacts are consistent
✓ Final-model metadata is consistent with final model
✓ Final model configuration is validated
✓ Feature-importance artifact matches final model
✓ Independent Test artifacts are mutually consistent
✓ Classification-report accounting is reconciled
✓ Confusion-matrix accounting is reconciled
✓ Section 5.13 interpretation artifacts are consistent
✓ Persisted artifact-output configuration is validated

[KNOWN ARTIFACT-MAPPING OBSERVATIONS]
✓ Historical model_configuration mapping observation remains documented
✓ Historical experiment_results mapping observation remains documented
✓ Actual persisted experiment-results artifact remains validated
✓ No historical artifact mapping was silently rewritten

[SECTION 5.15 HANDOFF BOUNDARY]
✓ handoff_manifest remains established in the RF mapping
✓ handoff_manifest remains excluded from Section 5.14
✓ Final RF handoff and manifest validation remain reserved for Section 5.15

[PROTECTED BOUNDARIES]
✓ Independent Test protection remains valid
✓ N04 remains immutable/read-only
✓ No RF model fitting performed
✓ No resampling performed
✓ No synthetic sampling performed
✓ No new Test inference performed
✓ No new Test metrics calculated
✓ No RF strategy selection performed
✓ No hyperparameter selection performed
✓ No new error analysis performed

[5.14 FINAL ARTIFACT PERSISTENCE READINESS GATE]
✓ 5.14.1 boundary validation passed
✓ 5.14.2 artifact inventory passed
✓ 5.14.3 integrity and consistency validation passed
✓ 16 persisted RF artifacts are valid
✓ No missing or invalid persisted artifacts remain
✓ Known artifact-mapping observations are documented
✓ Actual experiment-results artifact is validated
✓ Section 5.15 handoff manifest remains excluded
✓ Independent Test protection remains valid
✓ N04 remains immutable
✓ No model fitting performed
✓ No resampling performed
✓ No Test inference performed
✓ No new Test metrics calculated
✓ No strategy selection performed
✓ No hyperparameter selection performed
✓ No new error analysis performed

========================================================================
5.14.4 — RANDOM FOREST ARTIFACT PERSISTENCE COMPLETION AND READINESS GATE PASSED
========================================================================

SECTION 5.14 — RANDOM FOREST ARTIFACT PERSISTENCE COMPLETED

READY FOR 5.15 — FINAL RANDOM FOREST HANDOFF AND VALIDATION
========================================================================

# 5.15 — Final Random Forest Handoff and Validation

This section prepares the completed Random Forest development workflow for
downstream use by other members of the project team. It defines the final
Random Forest consumer contract, creates the final handoff manifest, and
validates that the persisted model, metadata, N04 model-ready input
dependency, evaluation artifacts, interpretation artifacts, and handoff
information form a consistent and reproducible package.

The final RF-3 model is handed off without retraining or modification. The
handoff contract specifies the required 32-feature N04 model-ready input
representation, feature order, data type, nine-class output taxonomy, frozen
Random Forest configuration, and the required upstream N04 dependencies.

The completed handoff package is intended to allow downstream project members
to consume the validated Random Forest model for subsequent ensemble
development and integration without rerunning the Random Forest development
experiments.

Section 5.15 performs no new model fitting, resampling, strategy selection,
hyperparameter selection, or Independent Test evaluation. N04 remains an
immutable upstream dependency.

## 5.15.1 — Final RF Handoff Definition and Consumer Contract

This subsection establishes the final downstream consumer contract for the
validated Random Forest model produced by Notebook 05.

The purpose of this contract is to allow other members of the project team
to use the final Random Forest model without rerunning the Random Forest
development workflow.

The final handoff contract defines:

- the persisted final Random Forest model artifact,
- the persisted final-model metadata,
- the selected RF strategy,
- the required N04 model-ready input representation,
- the authoritative 32-feature order,
- the expected feature dtype,
- the nine-class output taxonomy,
- the frozen Random Forest configuration,
- the N04 preprocessing/model-preparation dependency, and
- the final N04 handoff manifest required for downstream traceability.

The final Random Forest expects the model-ready representation produced by
Notebook 04. Downstream users must therefore preserve the established N04
feature order and representation rather than independently selecting,
reordering, scaling, or otherwise transforming features.

The final model is the RF-3 model selected using the protected Validation
partition. The model was fitted using the Training partition under the
controlled random-oversampling strategy. The Independent Test partition was
not used for model fitting or strategy selection.

This subsection defines and validates the consumer contract only.

It does not create the final handoff manifest, modify the final model,
perform model fitting, perform resampling, generate predictions, or perform
any new Test evaluation.

In [ ]:
# ================================================================
# 5.15.1 — FINAL RF HANDOFF DEFINITION
#             AND CONSUMER CONTRACT
# ================================================================

import json
from pathlib import Path


print("=" * 72)
print(
    "5.15.1 — FINAL RF HANDOFF DEFINITION "
    "AND CONSUMER CONTRACT"
)
print("=" * 72)


# ----------------------------------------------------------------
# 1. SECTION 5.14 COMPLETION BOUNDARY
# ----------------------------------------------------------------

print("\n[SECTION 5.14 COMPLETION BOUNDARY]")

assert "RF_5_14_4_VALIDATION" in globals(), (
    "Section 5.14 final validation state is unavailable."
)

assert all(
    RF_5_14_4_VALIDATION.values()
), (
    "Section 5.14 final readiness gate has not passed."
)

print("✓ Section 5.14 completed and validated")
print("✓ Final RF artifact package is ready for handoff")


# ----------------------------------------------------------------
# 2. FINAL RF HANDOFF ARTIFACT PATHS
# ----------------------------------------------------------------

print("\n[FINAL RF HANDOFF ARTIFACT PATHS]")

assert "RF_EXPERIMENT_ARTIFACTS" in globals(), (
    "RF_EXPERIMENT_ARTIFACTS is unavailable."
)

assert (
    "final_model"
    in RF_EXPERIMENT_ARTIFACTS
)

assert (
    "final_model_metadata"
    in RF_EXPERIMENT_ARTIFACTS
)

assert (
    "handoff_manifest"
    in RF_EXPERIMENT_ARTIFACTS
)

RF_5_15_1_FINAL_MODEL_PATH = Path(
    RF_EXPERIMENT_ARTIFACTS[
        "final_model"
    ]
)

RF_5_15_1_FINAL_MODEL_METADATA_PATH = Path(
    RF_EXPERIMENT_ARTIFACTS[
        "final_model_metadata"
    ]
)

RF_5_15_1_HANDOFF_MANIFEST_PATH = Path(
    RF_EXPERIMENT_ARTIFACTS[
        "handoff_manifest"
    ]
)


assert RF_5_15_1_FINAL_MODEL_PATH.is_file(), (
    "Final Random Forest model artifact is missing."
)

assert (
    RF_5_15_1_FINAL_MODEL_PATH.stat().st_size > 0
), (
    "Final Random Forest model artifact is empty."
)

assert (
    RF_5_15_1_FINAL_MODEL_METADATA_PATH.is_file()
), (
    "Final Random Forest model metadata artifact is missing."
)

assert (
    RF_5_15_1_FINAL_MODEL_METADATA_PATH.stat().st_size > 0
), (
    "Final Random Forest model metadata artifact is empty."
)


print(
    f"✓ Final RF model:\n"
    f"  {RF_5_15_1_FINAL_MODEL_PATH}"
)

print(
    f"✓ Final RF metadata:\n"
    f"  {RF_5_15_1_FINAL_MODEL_METADATA_PATH}"
)

print(
    f"✓ Reserved handoff manifest path:\n"
    f"  {RF_5_15_1_HANDOFF_MANIFEST_PATH}"
)

print(
    "✓ Handoff manifest has not been created or modified "
    "in 5.15.1"
)


# ----------------------------------------------------------------
# 3. FINAL RF MODEL METADATA CONTRACT
# ----------------------------------------------------------------

print("\n[FINAL RF MODEL METADATA CONTRACT]")

with open(
    RF_5_15_1_FINAL_MODEL_METADATA_PATH,
    "r",
    encoding="utf-8"
) as file:

    RF_5_15_1_FINAL_MODEL_METADATA = json.load(
        file
    )


assert (
    RF_5_15_1_FINAL_MODEL_METADATA[
        "strategy_id"
    ]
    == "RF-3"
)

assert (
    RF_5_15_1_FINAL_MODEL_METADATA[
        "strategy_name"
    ]
    == "Controlled Random Oversampling"
)

assert (
    RF_5_15_1_FINAL_MODEL_METADATA[
        "training_partition"
    ]
    == "Training"
)

assert (
    RF_5_15_1_FINAL_MODEL_METADATA[
        "validation_used_for_fitting"
    ]
    is False
)

assert (
    RF_5_15_1_FINAL_MODEL_METADATA[
        "independent_test_used"
    ]
    is False
)

assert (
    RF_5_15_1_FINAL_MODEL_METADATA[
        "final_model"
    ]
    is True
)

assert (
    RF_5_15_1_FINAL_MODEL_METADATA[
        "persistence_completed"
    ]
    is True
)

assert (
    RF_5_15_1_FINAL_MODEL_METADATA[
        "feature_count"
    ]
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

assert (
    RF_5_15_1_FINAL_MODEL_METADATA[
        "class_count"
    ]
    == len(EXPECTED_RF_CLASS_IDS)
)

assert (
    RF_5_15_1_FINAL_MODEL_METADATA[
        "common_random_forest_configuration"
    ]
    == RF_COMMON_CONFIGURATION
)

assert (
    RF_5_15_1_FINAL_MODEL_METADATA[
        "random_seed"
    ]
    == int(RANDOM_SEED)
)


print("✓ Final strategy = RF-3")
print("✓ Strategy = Controlled Random Oversampling")
print("✓ Training partition = Training")
print("✓ Validation excluded from model fitting")
print("✓ Independent Test excluded from model fitting")
print("✓ Final-model flag = True")
print("✓ Persistence-completed flag = True")
print(
    f"✓ Feature count = "
    f"{EXPECTED_MODEL_READY_FEATURE_COUNT}"
)
print(
    f"✓ Class count = "
    f"{len(EXPECTED_RF_CLASS_IDS)}"
)
print("✓ Frozen RF configuration matches final metadata")
print(
    f"✓ Random seed = "
    f"{RANDOM_SEED}"
)


# ----------------------------------------------------------------
# 4. N04 MODEL-READY INPUT DEPENDENCY
# ----------------------------------------------------------------

print("\n[N04 MODEL-READY INPUT DEPENDENCY]")

assert "N04_CONTROL_ARTIFACTS" in globals(), (
    "N04 control-artifact mapping is unavailable."
)

assert (
    "model_ready_feature_metadata"
    in N04_CONTROL_ARTIFACTS
)

assert (
    "final_n04_handoff_manifest"
    in N04_CONTROL_ARTIFACTS
)

RF_5_15_1_MODEL_READY_METADATA_PATH = Path(
    N04_CONTROL_ARTIFACTS[
        "model_ready_feature_metadata"
    ]
)

RF_5_15_1_N04_HANDOFF_MANIFEST_PATH = Path(
    N04_CONTROL_ARTIFACTS[
        "final_n04_handoff_manifest"
    ]
)

assert (
    RF_5_15_1_MODEL_READY_METADATA_PATH.is_file()
), (
    "N04 model-ready feature metadata is missing."
)

assert (
    RF_5_15_1_N04_HANDOFF_MANIFEST_PATH.is_file()
), (
    "N04 final handoff manifest is missing."
)


with open(
    RF_5_15_1_MODEL_READY_METADATA_PATH,
    "r",
    encoding="utf-8"
) as file:

    RF_5_15_1_MODEL_READY_METADATA = json.load(
        file
    )


assert (
    int(
        RF_5_15_1_MODEL_READY_METADATA[
            "final_feature_count"
        ]
    )
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

assert (
    RF_5_15_1_MODEL_READY_METADATA[
        "final_feature_order"
    ]
    == list(RF_FEATURE_ORDER)
)


print("✓ N04 model-ready feature metadata is available")
print("✓ N04 final handoff manifest is available")
print(
    f"✓ N04 model-ready feature count = "
    f"{EXPECTED_MODEL_READY_FEATURE_COUNT}"
)
print("✓ N04 model-ready feature order matches RF_FEATURE_ORDER")


# ----------------------------------------------------------------
# 5. CONSUMER INPUT CONTRACT
# ----------------------------------------------------------------

print("\n[RF CONSUMER INPUT CONTRACT]")

RF_5_15_1_CONSUMER_INPUT_CONTRACT = {

    "input_representation":
        "N04 model-ready feature representation",

    "feature_count":
        int(
            EXPECTED_MODEL_READY_FEATURE_COUNT
        ),

    "feature_dtype":
        str(
            EXPECTED_FEATURE_DTYPE
        ),

    "feature_order":
        list(
            RF_FEATURE_ORDER
        ),

    "preprocessing_authority":
        "Notebook 04 model-preparation pipeline",

    "feature_selection_authority":
        "Notebook 04 finalized feature-selection contract",

    "scaling_authority":
        "Notebook 04 training-only scaler and partition-wise transformation",

    "independent_test_policy":
        "Independent Test is reserved for final evaluation only",
}


assert (
    RF_5_15_1_CONSUMER_INPUT_CONTRACT[
        "feature_count"
    ]
    == 32
)

assert (
    RF_5_15_1_CONSUMER_INPUT_CONTRACT[
        "feature_dtype"
    ]
    == "float32"
)

assert (
    RF_5_15_1_CONSUMER_INPUT_CONTRACT[
        "feature_order"
    ]
    == list(RF_FEATURE_ORDER)
)


print(
    "✓ Input representation = N04 model-ready features"
)

print(
    "✓ Input feature count = 32"
)

print(
    "✓ Input dtype = float32"
)

print(
    "✓ Input feature order = authoritative RF_FEATURE_ORDER"
)

print(
    "✓ Downstream preprocessing dependency = N04"
)

print(
    "✓ Independent Test remains evaluation-only"
)


# ----------------------------------------------------------------
# 6. CONSUMER OUTPUT CONTRACT
# ----------------------------------------------------------------

print("\n[RF CONSUMER OUTPUT CONTRACT]")

RF_5_15_1_CONSUMER_OUTPUT_CONTRACT = {

    "output_type":
        "Random Forest class prediction",

    "class_count":
        int(
            len(EXPECTED_RF_CLASS_IDS)
        ),

    "class_ids":
        EXPECTED_RF_CLASS_IDS.tolist(),

    "class_mapping":
        {
            str(class_id): str(class_name)
            for (
                class_id,
                class_name
            )
            in RF_CLASS_MAPPING.items()
        },

    "selected_strategy":
        "RF-3",

    "selected_strategy_name":
        "Controlled Random Oversampling",
}


assert (
    RF_5_15_1_CONSUMER_OUTPUT_CONTRACT[
        "class_ids"
    ]
    == list(range(9))
)

assert (
    len(
        RF_5_15_1_CONSUMER_OUTPUT_CONTRACT[
            "class_mapping"
        ]
    )
    == 9
)


print(
    "✓ Output = Random Forest class prediction"
)

print(
    "✓ Output class count = 9"
)

print(
    "✓ Output class IDs = 0–8"
)

print(
    "✓ Authoritative nine-class mapping retained"
)

print(
    "✓ Selected strategy = RF-3"
)


# ----------------------------------------------------------------
# 7. FROZEN RANDOM FOREST MODEL CONTRACT
# ----------------------------------------------------------------

print("\n[FROZEN RANDOM FOREST MODEL CONTRACT]")

RF_5_15_1_MODEL_CONTRACT = {

    "n_estimators":
        int(
            RF_COMMON_CONFIGURATION[
                "n_estimators"
            ]
        ),

    "max_features":
        RF_COMMON_CONFIGURATION[
            "max_features"
        ],

    "max_depth":
        RF_COMMON_CONFIGURATION[
            "max_depth"
        ],

    "bootstrap":
        bool(
            RF_COMMON_CONFIGURATION[
                "bootstrap"
            ]
        ),

    "n_jobs":
        int(
            RF_COMMON_CONFIGURATION[
                "n_jobs"
            ]
        ),

    "random_state":
        int(
            RF_COMMON_CONFIGURATION[
                "random_state"
            ]
        ),

    "class_weight":
        RF_5_15_1_FINAL_MODEL_METADATA.get(
            "class_weight",
            None
        ),
}


assert (
    RF_5_15_1_MODEL_CONTRACT[
        "n_estimators"
    ]
    == 100
)

assert (
    RF_5_15_1_MODEL_CONTRACT[
        "max_features"
    ]
    == "sqrt"
)

assert (
    RF_5_15_1_MODEL_CONTRACT[
        "max_depth"
    ]
    is None
)

assert (
    RF_5_15_1_MODEL_CONTRACT[
        "bootstrap"
    ]
    is True
)

assert (
    RF_5_15_1_MODEL_CONTRACT[
        "random_state"
    ]
    == 42
)

assert (
    RF_5_15_1_MODEL_CONTRACT[
        "class_weight"
    ]
    is None
)


print("✓ n_estimators = 100")
print("✓ max_features = sqrt")
print("✓ max_depth = None")
print("✓ bootstrap = True")
print("✓ random_state = 42")
print("✓ class_weight = None")


# ----------------------------------------------------------------
# 8. COMPLETE CONSUMER CONTRACT
# ----------------------------------------------------------------

RF_5_15_1_CONSUMER_CONTRACT = {

    "final_model":
        str(
            RF_5_15_1_FINAL_MODEL_PATH
        ),

    "final_model_metadata":
        str(
            RF_5_15_1_FINAL_MODEL_METADATA_PATH
        ),

    "selected_strategy":
        "RF-3",

    "selected_strategy_name":
        "Controlled Random Oversampling",

    "input_contract":
        RF_5_15_1_CONSUMER_INPUT_CONTRACT,

    "output_contract":
        RF_5_15_1_CONSUMER_OUTPUT_CONTRACT,

    "model_contract":
        RF_5_15_1_MODEL_CONTRACT,

    "n04_model_ready_feature_metadata":
        str(
            RF_5_15_1_MODEL_READY_METADATA_PATH
        ),

    "n04_final_handoff_manifest":
        str(
            RF_5_15_1_N04_HANDOFF_MANIFEST_PATH
        ),

    "handoff_manifest":
        str(
            RF_5_15_1_HANDOFF_MANIFEST_PATH
        ),

    "handoff_manifest_status":
        "reserved_for_5.15.2",

    "model_modification_in_5_15_1":
        False,

    "test_inference_in_5_15_1":
        False,
}


assert (
    RF_5_15_1_CONSUMER_CONTRACT[
        "selected_strategy"
    ]
    == "RF-3"
)

assert (
    RF_5_15_1_CONSUMER_CONTRACT[
        "input_contract"
    ][
        "feature_count"
    ]
    == 32
)

assert (
    RF_5_15_1_CONSUMER_CONTRACT[
        "input_contract"
    ][
        "feature_dtype"
    ]
    == "float32"
)

assert (
    RF_5_15_1_CONSUMER_CONTRACT[
        "output_contract"
    ][
        "class_ids"
    ]
    == list(range(9))
)


# ----------------------------------------------------------------
# 9. 5.15.1 VALIDATION STATE
# ----------------------------------------------------------------

RF_5_15_1_VALIDATION = {

    "section_5_14_completed":
        all(
            RF_5_14_4_VALIDATION.values()
        ),

    "final_model_persisted":
        (
            RF_5_15_1_FINAL_MODEL_PATH.is_file()
            and
            RF_5_15_1_FINAL_MODEL_PATH.stat().st_size > 0
        ),

    "final_model_metadata_valid":
        (
            RF_5_15_1_FINAL_MODEL_METADATA[
                "strategy_id"
            ]
            == "RF-3"
            and
            RF_5_15_1_FINAL_MODEL_METADATA[
                "final_model"
            ]
            is True
            and
            RF_5_15_1_FINAL_MODEL_METADATA[
                "persistence_completed"
            ]
            is True
        ),

    "n04_model_ready_contract_valid":
        (
            int(
                RF_5_15_1_MODEL_READY_METADATA[
                    "final_feature_count"
                ]
            )
            == 32
            and
            RF_5_15_1_MODEL_READY_METADATA[
                "final_feature_order"
            ]
            == list(RF_FEATURE_ORDER)
        ),

    "consumer_input_contract_valid":
        (
            RF_5_15_1_CONSUMER_INPUT_CONTRACT[
                "feature_count"
            ]
            == 32
            and
            RF_5_15_1_CONSUMER_INPUT_CONTRACT[
                "feature_dtype"
            ]
            == "float32"
            and
            RF_5_15_1_CONSUMER_INPUT_CONTRACT[
                "feature_order"
            ]
            == list(RF_FEATURE_ORDER)
        ),

    "consumer_output_contract_valid":
        (
            RF_5_15_1_CONSUMER_OUTPUT_CONTRACT[
                "class_ids"
            ]
            == list(range(9))
            and
            len(
                RF_5_15_1_CONSUMER_OUTPUT_CONTRACT[
                    "class_mapping"
                ]
            )
            == 9
        ),

    "model_contract_valid":
        (
            RF_5_15_1_MODEL_CONTRACT[
                "n_estimators"
            ]
            == 100
            and
            RF_5_15_1_MODEL_CONTRACT[
                "max_features"
            ]
            == "sqrt"
            and
            RF_5_15_1_MODEL_CONTRACT[
                "max_depth"
            ]
            is None
            and
            RF_5_15_1_MODEL_CONTRACT[
                "bootstrap"
            ]
            is True
            and
            RF_5_15_1_MODEL_CONTRACT[
                "random_state"
            ]
            == 42
            and
            RF_5_15_1_MODEL_CONTRACT[
                "class_weight"
            ]
            is None
        ),

    "handoff_manifest_reserved":
        (
            RF_5_15_1_CONSUMER_CONTRACT[
                "handoff_manifest_status"
            ]
            == "reserved_for_5.15.2"
        ),

    "no_model_modification":
        (
            RF_5_15_1_CONSUMER_CONTRACT[
                "model_modification_in_5_15_1"
            ]
            is False
        ),

    "no_test_inference":
        (
            RF_5_15_1_CONSUMER_CONTRACT[
                "test_inference_in_5_15_1"
            ]
            is False
        ),
}


assert all(
    RF_5_15_1_VALIDATION.values()
), (
    "5.15.1 final RF handoff definition "
    "and consumer contract validation failed."
)


# ----------------------------------------------------------------
# 10. FINAL 5.15.1 READINESS GATE
# ----------------------------------------------------------------

print("\n[5.15.1 HANDOFF DEFINITION READINESS GATE]")

print("✓ Section 5.14 completion boundary passed")
print("✓ Final RF model artifact is available")
print("✓ Final RF metadata identifies RF-3")
print("✓ N04 model-ready feature contract is available")
print("✓ 32-feature input contract established")
print("✓ float32 input representation established")
print("✓ Authoritative feature order established")
print("✓ Nine-class output contract established")
print("✓ Frozen RF configuration established")
print("✓ N04 preprocessing dependency documented")
print("✓ Final N04 handoff dependency documented")
print("✓ Handoff manifest reserved for Section 5.15.2")
print("✓ No model modification performed")
print("✓ No Test inference performed")

print("\n" + "=" * 72)

print(
    "5.15.1 — FINAL RF HANDOFF DEFINITION "
    "AND CONSUMER CONTRACT PASSED"
)

print("=" * 72)

print(
    "\nREADY FOR 5.15.2 — FINAL RF HANDOFF "
    "MANIFEST CREATION"
)

print("=" * 72)

========================================================================
5.15.1 — FINAL RF HANDOFF DEFINITION AND CONSUMER CONTRACT
========================================================================

[SECTION 5.14 COMPLETION BOUNDARY]
✓ Section 5.14 completed and validated
✓ Final RF artifact package is ready for handoff

[FINAL RF HANDOFF ARTIFACT PATHS]
✓ Final RF model:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models/random_forest/final_random_forest.joblib
✓ Final RF metadata:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/final_model/rf_final_model_metadata.json
✓ Reserved handoff manifest path:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/rf_handoff_manifest.json
✓ Handoff manifest has not been created or modified in 5.15.1

[FINAL RF MODEL METADATA CONTRACT]
✓ Final strategy = RF-3
✓ Strategy = Controlled Random Oversampling
✓ Training partition = Training
✓ Validation excluded from model fitting
✓ Independent Test excluded from model fitting
✓ Final-model flag = True
✓ Persistence-completed flag = True
✓ Feature count = 32
✓ Class count = 9
✓ Frozen RF configuration matches final metadata
✓ Random seed = 42

[N04 MODEL-READY INPUT DEPENDENCY]
✓ N04 model-ready feature metadata is available
✓ N04 final handoff manifest is available
✓ N04 model-ready feature count = 32
✓ N04 model-ready feature order matches RF_FEATURE_ORDER

[RF CONSUMER INPUT CONTRACT]
✓ Input representation = N04 model-ready features
✓ Input feature count = 32
✓ Input dtype = float32
✓ Input feature order = authoritative RF_FEATURE_ORDER
✓ Downstream preprocessing dependency = N04
✓ Independent Test remains evaluation-only

[RF CONSUMER OUTPUT CONTRACT]
✓ Output = Random Forest class prediction
✓ Output class count = 9
✓ Output class IDs = 0–8
✓ Authoritative nine-class mapping retained
✓ Selected strategy = RF-3

[FROZEN RANDOM FOREST MODEL CONTRACT]
✓ n_estimators = 100
✓ max_features = sqrt
✓ max_depth = None
✓ bootstrap = True
✓ random_state = 42
✓ class_weight = None

[5.15.1 HANDOFF DEFINITION READINESS GATE]
✓ Section 5.14 completion boundary passed
✓ Final RF model artifact is available
✓ Final RF metadata identifies RF-3
✓ N04 model-ready feature contract is available
✓ 32-feature input contract established
✓ float32 input representation established
✓ Authoritative feature order established
✓ Nine-class output contract established
✓ Frozen RF configuration established
✓ N04 preprocessing dependency documented
✓ Final N04 handoff dependency documented
✓ Handoff manifest reserved for Section 5.15.2
✓ No model modification performed
✓ No Test inference performed

========================================================================
5.15.1 — FINAL RF HANDOFF DEFINITION AND CONSUMER CONTRACT PASSED
========================================================================

READY FOR 5.15.2 — FINAL RF HANDOFF MANIFEST CREATION
========================================================================

## 5.15.2 — Final RF Handoff Manifest Creation

This subsection creates the final Random Forest handoff manifest for downstream
consumption by other members of the project team.

The handoff manifest provides a single, persistent description of the validated
RF-3 model package, including the final model artifact, final-model metadata,
consumer input and output contracts, authoritative feature order, class
taxonomy, frozen Random Forest configuration, N04 model-preparation
dependencies, evaluation artifacts, interpretation artifacts, and artifact
integrity information.

The manifest records the physically persisted artifact locations rather than
silently rewriting any historical artifact mapping maintained by
`RF_EXPERIMENT_ARTIFACTS`. In particular, the actual persisted Random Forest
experiment-results artifact is recorded from its validated evaluation
location.

The handoff manifest is intended to allow downstream project members to
identify and consume the validated Random Forest package without rerunning the
Random Forest development experiments.

Only the handoff manifest is created in this subsection. Existing Random
Forest model, metadata, evaluation, interpretation, and N04 artifacts are
read-only inputs to manifest creation.

No model fitting, resampling, Test inference, new metric calculation,
strategy selection, hyperparameter selection, or error analysis is performed.

In [ ]:
# ================================================================
# 5.15.2 — FINAL RF HANDOFF MANIFEST CREATION
# ================================================================

import hashlib
import json
from pathlib import Path


print("=" * 72)
print(
    "5.15.2 — FINAL RF HANDOFF MANIFEST CREATION"
)
print("=" * 72)


# ----------------------------------------------------------------
# 1. SECTION 5.15.1 COMPLETION BOUNDARY
# ----------------------------------------------------------------

print("\n[SECTION 5.15.1 COMPLETION BOUNDARY]")

assert "RF_5_15_1_VALIDATION" in globals(), (
    "5.15.1 validation state is unavailable."
)

assert all(
    RF_5_15_1_VALIDATION.values()
), (
    "5.15.1 final handoff definition "
    "and consumer contract has not passed."
)

assert "RF_5_15_1_CONSUMER_CONTRACT" in globals(), (
    "5.15.1 consumer contract is unavailable."
)

print("✓ Section 5.15.1 completed and validated")
print("✓ Final RF consumer contract is available")


# ----------------------------------------------------------------
# 2. HANDOFF MANIFEST PATH
# ----------------------------------------------------------------

print("\n[HANDOFF MANIFEST PATH]")

assert (
    "RF_5_15_1_HANDOFF_MANIFEST_PATH"
    in globals()
), (
    "Established handoff manifest path is unavailable."
)

RF_5_15_2_HANDOFF_MANIFEST_PATH = Path(
    RF_5_15_1_HANDOFF_MANIFEST_PATH
)

assert (
    RF_5_15_2_HANDOFF_MANIFEST_PATH.name
    == "rf_handoff_manifest.json"
)

assert (
    RF_5_15_2_HANDOFF_MANIFEST_PATH.parent
    == RANDOM_FOREST_OUTPUT_DIR
)

print(
    f"✓ Handoff manifest path:\n"
    f"  {RF_5_15_2_HANDOFF_MANIFEST_PATH}"
)


# ----------------------------------------------------------------
# 3. ESTABLISHED FINAL RF ARTIFACTS
# ----------------------------------------------------------------

print("\n[FINAL RF ARTIFACTS]")

RF_5_15_2_FINAL_MODEL_PATH = Path(
    RF_5_15_1_FINAL_MODEL_PATH
)

RF_5_15_2_FINAL_MODEL_METADATA_PATH = Path(
    RF_5_15_1_FINAL_MODEL_METADATA_PATH
)

RF_5_15_2_N04_MODEL_READY_METADATA_PATH = Path(
    RF_5_15_1_MODEL_READY_METADATA_PATH
)

RF_5_15_2_N04_HANDOFF_MANIFEST_PATH = Path(
    RF_5_15_1_N04_HANDOFF_MANIFEST_PATH
)


RF_5_15_2_CORE_ARTIFACTS = {

    "final_model":
        RF_5_15_2_FINAL_MODEL_PATH,

    "final_model_metadata":
        RF_5_15_2_FINAL_MODEL_METADATA_PATH,

    "n04_model_ready_feature_metadata":
        RF_5_15_2_N04_MODEL_READY_METADATA_PATH,

    "n04_final_handoff_manifest":
        RF_5_15_2_N04_HANDOFF_MANIFEST_PATH,
}


for artifact_name, artifact_path in (
    RF_5_15_2_CORE_ARTIFACTS.items()
):

    assert artifact_path.is_file(), (
        f"Required handoff artifact is missing: "
        f"{artifact_path}"
    )

    assert artifact_path.stat().st_size > 0, (
        f"Required handoff artifact is empty: "
        f"{artifact_path}"
    )

    print(
        f"✓ {artifact_name:<36} : "
        f"{artifact_path}"
    )


# ----------------------------------------------------------------
# 4. ACTUAL PERSISTED RF DEVELOPMENT ARTIFACTS
#
# The historical RF_EXPERIMENT_ARTIFACTS mapping is not silently
# rewritten here. The actual persisted experiment-results path
# validated during Section 5.14 is used explicitly.
# ----------------------------------------------------------------

print("\n[ACTUAL PERSISTED RF DEVELOPMENT ARTIFACTS]")

RF_5_15_2_PERSISTED_ARTIFACTS = {

    "strategy_selection":
        Path(
            RF_EXPERIMENT_ARTIFACTS[
                "strategy_selection"
            ]
        ),

    "validation_results":
        Path(
            RF_EXPERIMENT_ARTIFACTS[
                "validation_results"
            ]
        ),

    "experiment_results":
        RF_EVALUATION_DIR /
        "rf_experiment_results.csv",

    "test_results":
        Path(
            RF_EXPERIMENT_ARTIFACTS[
                "test_results"
            ]
        ),

    "confusion_matrix":
        Path(
            RF_EXPERIMENT_ARTIFACTS[
                "confusion_matrix"
            ]
        ),

    "classification_report":
        Path(
            RF_EXPERIMENT_ARTIFACTS[
                "classification_report"
            ]
        ),

    "feature_importance":
        Path(
            RF_EXPERIMENT_ARTIFACTS[
                "feature_importance"
            ]
        ),

    "rf_class_wise_error_analysis":
        RF_INTERPRETATION_DIR /
        "rf_class_wise_error_analysis.csv",

    "rf_confusion_pattern_analysis":
        RF_INTERPRETATION_DIR /
        "rf_confusion_pattern_analysis.csv",

    "rf_dominant_error_analysis":
        RF_INTERPRETATION_DIR /
        "rf_dominant_error_analysis.csv",

    "rf_minority_class_analysis":
        RF_INTERPRETATION_DIR /
        "rf_minority_class_analysis.csv",

    "rf_error_analysis_summary":
        RF_INTERPRETATION_DIR /
        "rf_error_analysis_summary.json",
}


for artifact_name, artifact_path in (
    RF_5_15_2_PERSISTED_ARTIFACTS.items()
):

    assert artifact_path.is_file(), (
        f"Persisted RF artifact is missing: "
        f"{artifact_path}"
    )

    assert artifact_path.stat().st_size > 0, (
        f"Persisted RF artifact is empty: "
        f"{artifact_path}"
    )

    print(
        f"✓ {artifact_name:<36} : "
        f"{artifact_path}"
    )


print(
    "✓ Actual persisted experiment-results artifact "
    "recorded from evaluation directory"
)

print(
    "✓ Historical RF_EXPERIMENT_ARTIFACTS mapping "
    "was not rewritten"
)


# ----------------------------------------------------------------
# 5. ARTIFACT SHA-256 INTEGRITY INFORMATION
# ----------------------------------------------------------------

print("\n[ARTIFACT INTEGRITY INFORMATION]")


def calculate_sha256(
    artifact_path
):

    sha256_hash = hashlib.sha256()

    with open(
        artifact_path,
        "rb"
    ) as file:

        for chunk in iter(
            lambda: file.read(1024 * 1024),
            b""
        ):

            sha256_hash.update(
                chunk
            )

    return sha256_hash.hexdigest()


RF_5_15_2_ARTIFACT_INTEGRITY = {}


for artifact_name, artifact_path in {
    **RF_5_15_2_CORE_ARTIFACTS,
    **RF_5_15_2_PERSISTED_ARTIFACTS,
}.items():

    RF_5_15_2_ARTIFACT_INTEGRITY[
        artifact_name
    ] = {

        "path":
            str(
                artifact_path
            ),

        "size_bytes":
            int(
                artifact_path.stat().st_size
            ),

        "sha256":
            calculate_sha256(
                artifact_path
            ),
    }


print(
    f"✓ SHA-256 integrity records created for "
    f"{len(RF_5_15_2_ARTIFACT_INTEGRITY)} artifacts"
)


# ----------------------------------------------------------------
# 6. FINAL RF HANDOFF MANIFEST
# ----------------------------------------------------------------

print("\n[FINAL RF HANDOFF MANIFEST]")


RF_5_15_2_HANDOFF_MANIFEST = {

    "manifest_type":
        "Random Forest Final Handoff Manifest",

    "manifest_version":
        "1.0",

    "notebook":
        "N05",

    "project":
        "AI-Network-Intrusion-Detection-System",

    "handoff_stage":
        "5.15 — Final Random Forest Handoff and Validation",

    "manifest_creation_subsection":
        "5.15.2 — Final RF Handoff Manifest Creation",

    "selected_strategy": {

        "strategy_id":
            RF_5_15_1_CONSUMER_CONTRACT[
                "selected_strategy"
            ],

        "strategy_name":
            RF_5_15_1_CONSUMER_CONTRACT[
                "selected_strategy_name"
            ],

        "training_partition":
            "Training",

        "selection_partition":
            "Validation",

        "independent_test_used_for_selection":
            False,
    },

    "final_model": {

        "path":
            str(
                RF_5_15_2_FINAL_MODEL_PATH
            ),

        "artifact_type":
            "joblib",

        "metadata_path":
            str(
                RF_5_15_2_FINAL_MODEL_METADATA_PATH
            ),
    },

    "consumer_input_contract":
        RF_5_15_1_CONSUMER_CONTRACT[
            "input_contract"
        ],

    "consumer_output_contract":
        RF_5_15_1_CONSUMER_CONTRACT[
            "output_contract"
        ],

    "model_contract":
        RF_5_15_1_CONSUMER_CONTRACT[
            "model_contract"
        ],

    "n04_dependencies": {

        "model_ready_feature_metadata":
            str(
                RF_5_15_2_N04_MODEL_READY_METADATA_PATH
            ),

        "final_n04_handoff_manifest":
            str(
                RF_5_15_2_N04_HANDOFF_MANIFEST_PATH
            ),

        "dependency_policy":
            "Notebook 04 model-preparation artifacts are "
            "authoritative and immutable.",
    },

    "evaluation_artifacts": {

        "strategy_selection":
            str(
                RF_5_15_2_PERSISTED_ARTIFACTS[
                    "strategy_selection"
                ]
            ),

        "validation_results":
            str(
                RF_5_15_2_PERSISTED_ARTIFACTS[
                    "validation_results"
                ]
            ),

        "experiment_results":
            str(
                RF_5_15_2_PERSISTED_ARTIFACTS[
                    "experiment_results"
                ]
            ),

        "test_results":
            str(
                RF_5_15_2_PERSISTED_ARTIFACTS[
                    "test_results"
                ]
            ),

        "confusion_matrix":
            str(
                RF_5_15_2_PERSISTED_ARTIFACTS[
                    "confusion_matrix"
                ]
            ),

        "classification_report":
            str(
                RF_5_15_2_PERSISTED_ARTIFACTS[
                    "classification_report"
                ]
            ),
    },

    "interpretation_artifacts": {

        "feature_importance":
            str(
                RF_5_15_2_PERSISTED_ARTIFACTS[
                    "feature_importance"
                ]
            ),

        "class_wise_error_analysis":
            str(
                RF_5_15_2_PERSISTED_ARTIFACTS[
                    "rf_class_wise_error_analysis"
                ]
            ),

        "confusion_pattern_analysis":
            str(
                RF_5_15_2_PERSISTED_ARTIFACTS[
                    "rf_confusion_pattern_analysis"
                ]
            ),

        "dominant_error_analysis":
            str(
                RF_5_15_2_PERSISTED_ARTIFACTS[
                    "rf_dominant_error_analysis"
                ]
            ),

        "minority_class_analysis":
            str(
                RF_5_15_2_PERSISTED_ARTIFACTS[
                    "rf_minority_class_analysis"
                ]
            ),

        "error_analysis_summary":
            str(
                RF_5_15_2_PERSISTED_ARTIFACTS[
                    "rf_error_analysis_summary"
                ]
            ),
    },

    "artifact_integrity":
        RF_5_15_2_ARTIFACT_INTEGRITY,

    "artifact_mapping_observations": {

        "historical_model_configuration_mapping":
            str(
                RF_EXPERIMENT_ARTIFACTS[
                    "model_configuration"
                ]
            ),

        "historical_model_configuration_mapping_status":
            "Historical mapping retained; mapped file was "
            "not persisted at that location.",

        "actual_artifact_output_configuration":
            str(
                RF_EXPERIMENT_CONFIGURATION_DIR /
                "rf_artifact_output_configuration.json"
            ),

        "historical_experiment_results_mapping":
            str(
                RF_EXPERIMENT_ARTIFACTS[
                    "experiment_results"
                ]
            ),

        "actual_experiment_results":
            str(
                RF_5_15_2_PERSISTED_ARTIFACTS[
                    "experiment_results"
                ]
            ),

        "mapping_policy":
            "Historical mappings are documented and are not "
            "silently rewritten.",
    },

    "protection_contract": {

        "n04_immutable":
            True,

        "model_modification_in_handoff":
            False,

        "test_inference_in_manifest_creation":
            False,

        "new_test_metric_calculation":
            False,

        "new_model_fitting":
            False,

        "new_resampling":
            False,

        "new_strategy_selection":
            False,

        "new_hyperparameter_selection":
            False,
    },

    "handoff_status":
        "ready_for_validation",

    "manifest_self_reference":
        "Excluded from artifact integrity records to avoid "
        "self-referential hashing.",
}


# ----------------------------------------------------------------
# 7. WRITE FINAL HANDOFF MANIFEST
# ----------------------------------------------------------------

print("\n[MANIFEST PERSISTENCE]")


assert not (
    RF_5_15_2_HANDOFF_MANIFEST_PATH.is_file()
), (
    "Handoff manifest already exists. "
    "5.15.2 must not silently overwrite an existing manifest."
)


with open(
    RF_5_15_2_HANDOFF_MANIFEST_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RF_5_15_2_HANDOFF_MANIFEST,
        file,
        indent=4
    )


assert (
    RF_5_15_2_HANDOFF_MANIFEST_PATH.is_file()
), (
    "Final RF handoff manifest was not created."
)

assert (
    RF_5_15_2_HANDOFF_MANIFEST_PATH.stat().st_size > 0
), (
    "Final RF handoff manifest is empty."
)


print(
    f"✓ Final RF handoff manifest created:\n"
    f"  {RF_5_15_2_HANDOFF_MANIFEST_PATH}"
)

print(
    f"✓ Manifest size = "
    f"{RF_5_15_2_HANDOFF_MANIFEST_PATH.stat().st_size} bytes"
)


# ----------------------------------------------------------------
# 8. RELOAD AND BASIC MANIFEST VALIDATION
# ----------------------------------------------------------------

print("\n[CREATED MANIFEST VALIDATION]")


with open(
    RF_5_15_2_HANDOFF_MANIFEST_PATH,
    "r",
    encoding="utf-8"
) as file:

    RF_5_15_2_RELOADED_MANIFEST = json.load(
        file
    )


assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "manifest_type"
    ]
    == "Random Forest Final Handoff Manifest"
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "manifest_version"
    ]
    == "1.0"
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "selected_strategy"
    ][
        "strategy_id"
    ]
    == "RF-3"
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "selected_strategy"
    ][
        "strategy_name"
    ]
    == "Controlled Random Oversampling"
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "consumer_input_contract"
    ][
        "feature_count"
    ]
    == 32
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "consumer_input_contract"
    ][
        "feature_dtype"
    ]
    == "float32"
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "consumer_input_contract"
    ][
        "feature_order"
    ]
    == list(RF_FEATURE_ORDER)
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "consumer_output_contract"
    ][
        "class_ids"
    ]
    == list(range(9))
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "model_contract"
    ][
        "n_estimators"
    ]
    == 100
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "model_contract"
    ][
        "random_state"
    ]
    == 42
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "handoff_status"
    ]
    == "ready_for_validation"
)


print("✓ Manifest JSON reload successful")
print("✓ RF-3 strategy recorded")
print("✓ 32-feature input contract recorded")
print("✓ float32 input representation recorded")
print("✓ Authoritative feature order recorded")
print("✓ Nine-class output contract recorded")
print("✓ Frozen RF configuration recorded")
print("✓ N04 dependencies recorded")
print("✓ Evaluation artifacts recorded")
print("✓ Interpretation artifacts recorded")
print("✓ Artifact SHA-256 integrity records recorded")


# ----------------------------------------------------------------
# 9. 5.15.2 CREATION VALIDATION STATE
# ----------------------------------------------------------------

RF_5_15_2_VALIDATION = {

    "section_5_15_1_completed":
        all(
            RF_5_15_1_VALIDATION.values()
        ),

    "handoff_manifest_created":
        (
            RF_5_15_2_HANDOFF_MANIFEST_PATH.is_file()
            and
            RF_5_15_2_HANDOFF_MANIFEST_PATH.stat().st_size > 0
        ),

    "manifest_reload_successful":
        isinstance(
            RF_5_15_2_RELOADED_MANIFEST,
            dict
        ),

    "rf3_strategy_recorded":
        (
            RF_5_15_2_RELOADED_MANIFEST[
                "selected_strategy"
            ][
                "strategy_id"
            ]
            == "RF-3"
        ),

    "consumer_input_contract_recorded":
        (
            RF_5_15_2_RELOADED_MANIFEST[
                "consumer_input_contract"
            ][
                "feature_count"
            ]
            == 32
            and
            RF_5_15_2_RELOADED_MANIFEST[
                "consumer_input_contract"
            ][
                "feature_dtype"
            ]
            == "float32"
        ),

    "feature_order_recorded":
        (
            RF_5_15_2_RELOADED_MANIFEST[
                "consumer_input_contract"
            ][
                "feature_order"
            ]
            == list(RF_FEATURE_ORDER)
        ),

    "output_contract_recorded":
        (
            RF_5_15_2_RELOADED_MANIFEST[
                "consumer_output_contract"
            ][
                "class_ids"
            ]
            == list(range(9))
        ),

    "model_contract_recorded":
        (
            RF_5_15_2_RELOADED_MANIFEST[
                "model_contract"
            ][
                "n_estimators"
            ]
            == 100
            and
            RF_5_15_2_RELOADED_MANIFEST[
                "model_contract"
            ][
                "random_state"
            ]
            == 42
        ),

    "n04_dependencies_recorded":
        (
            "model_ready_feature_metadata"
            in
            RF_5_15_2_RELOADED_MANIFEST[
                "n04_dependencies"
            ]
            and
            "final_n04_handoff_manifest"
            in
            RF_5_15_2_RELOADED_MANIFEST[
                "n04_dependencies"
            ]
        ),

    "evaluation_artifacts_recorded":
        (
            len(
                RF_5_15_2_RELOADED_MANIFEST[
                    "evaluation_artifacts"
                ]
            )
            == 6
        ),

    "interpretation_artifacts_recorded":
        (
            len(
                RF_5_15_2_RELOADED_MANIFEST[
                    "interpretation_artifacts"
                ]
            )
            == 6
        ),

    "artifact_integrity_recorded":
        (
            len(
                RF_5_15_2_RELOADED_MANIFEST[
                    "artifact_integrity"
                ]
            )
            == 15
        ),

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_test_inference":
        True,

    "n04_immutable":
        True,
}


assert all(
    RF_5_15_2_VALIDATION.values()
), (
    "5.15.2 final RF handoff manifest creation "
    "validation failed."
)


print("\n" + "=" * 72)
print(
    "5.15.2 — FINAL RF HANDOFF MANIFEST "
    "CREATION PASSED"
)
print("=" * 72)

print(
    "\n✓ Final RF handoff manifest persisted"
)

print(
    "✓ RF-3 consumer contract recorded"
)

print(
    "✓ N04 dependency recorded"
)

print(
    "✓ Evaluation and interpretation artifacts recorded"
)

print(
    "✓ SHA-256 integrity information recorded"
)

print(
    "✓ Historical artifact-mapping observations retained"
)

print(
    "✓ No existing RF or N04 artifact modified"
)

print(
    "\nREADY FOR 5.15.3 — FINAL RF HANDOFF "
    "MANIFEST AND CONSUMER VALIDATION"
)

print("=" * 72)

========================================================================
5.15.2 — FINAL RF HANDOFF MANIFEST CREATION
========================================================================

[SECTION 5.15.1 COMPLETION BOUNDARY]
✓ Section 5.15.1 completed and validated
✓ Final RF consumer contract is available

[HANDOFF MANIFEST PATH]
✓ Handoff manifest path:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/rf_handoff_manifest.json

[FINAL RF ARTIFACTS]
✓ final_model                          : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models/random_forest/final_random_forest.joblib
✓ final_model_metadata                 : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/final_model/rf_final_model_metadata.json
✓ n04_model_ready_feature_metadata     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/feature_scaling/model_ready_feature_artifacts.json
✓ n04_final_handoff_manifest           : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/model_preparation_v2/final_n04_handoff_manifest.json

[ACTUAL PERSISTED RF DEVELOPMENT ARTIFACTS]
✓ strategy_selection                   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/strategy_selection/rf_strategy_selection.json
✓ validation_results                   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/validation_results.csv
✓ experiment_results                   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/rf_experiment_results.csv
✓ test_results                         : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/test_results.csv
✓ confusion_matrix                     : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/confusion_matrix.csv
✓ classification_report                : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/evaluation/classification_report.csv
✓ feature_importance                   : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_feature_importance.csv
✓ rf_class_wise_error_analysis         : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_class_wise_error_analysis.csv
✓ rf_confusion_pattern_analysis        : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_confusion_pattern_analysis.csv
✓ rf_dominant_error_analysis           : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_dominant_error_analysis.csv
✓ rf_minority_class_analysis           : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_minority_class_analysis.csv
✓ rf_error_analysis_summary            : /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/interpretation/rf_error_analysis_summary.json
✓ Actual persisted experiment-results artifact recorded from evaluation directory
✓ Historical RF_EXPERIMENT_ARTIFACTS mapping was not rewritten

[ARTIFACT INTEGRITY INFORMATION]
✓ SHA-256 integrity records created for 16 artifacts

[FINAL RF HANDOFF MANIFEST]

[MANIFEST PERSISTENCE]
✓ Final RF handoff manifest created:
  /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/rf_handoff_manifest.json
✓ Manifest size = 13029 bytes

[CREATED MANIFEST VALIDATION]
✓ Manifest JSON reload successful
✓ RF-3 strategy recorded
✓ 32-feature input contract recorded
✓ float32 input representation recorded
✓ Authoritative feature order recorded
✓ Nine-class output contract recorded
✓ Frozen RF configuration recorded
✓ N04 dependencies recorded
✓ Evaluation artifacts recorded
✓ Interpretation artifacts recorded
✓ Artifact SHA-256 integrity records recorded

AssertionError: 5.15.2 final RF handoff manifest creation validation failed.

In [ ]:
# ================================================================
# 5.15.2 — FINAL RF HANDOFF MANIFEST CREATION
# COMPLETION VALIDATION
# ================================================================

print("=" * 72)
print(
    "5.15.2 — FINAL RF HANDOFF MANIFEST "
    "COMPLETION VALIDATION"
)
print("=" * 72)


# ----------------------------------------------------------------
# 1. VERIFY CREATED MANIFEST
# ----------------------------------------------------------------

print("\n[CREATED HANDOFF MANIFEST]")

assert (
    RF_5_15_2_HANDOFF_MANIFEST_PATH.is_file()
), (
    "Final RF handoff manifest does not exist."
)

assert (
    RF_5_15_2_HANDOFF_MANIFEST_PATH.stat().st_size > 0
), (
    "Final RF handoff manifest is empty."
)

print(
    "✓ Final RF handoff manifest exists"
)

print(
    f"✓ Manifest size = "
    f"{RF_5_15_2_HANDOFF_MANIFEST_PATH.stat().st_size} bytes"
)


# ----------------------------------------------------------------
# 2. RELOAD CREATED MANIFEST
# ----------------------------------------------------------------

print("\n[MANIFEST RELOAD]")

with open(
    RF_5_15_2_HANDOFF_MANIFEST_PATH,
    "r",
    encoding="utf-8"
) as file:

    RF_5_15_2_RELOADED_MANIFEST = json.load(
        file
    )

assert isinstance(
    RF_5_15_2_RELOADED_MANIFEST,
    dict
)

print("✓ Manifest JSON reload successful")


# ----------------------------------------------------------------
# 3. VALIDATE HANDOFF CONTRACT
# ----------------------------------------------------------------

print("\n[HANDOFF CONTRACT VALIDATION]")

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "selected_strategy"
    ][
        "strategy_id"
    ]
    == "RF-3"
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "selected_strategy"
    ][
        "strategy_name"
    ]
    == "Controlled Random Oversampling"
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "consumer_input_contract"
    ][
        "feature_count"
    ]
    == 32
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "consumer_input_contract"
    ][
        "feature_dtype"
    ]
    == "float32"
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "consumer_input_contract"
    ][
        "feature_order"
    ]
    == list(RF_FEATURE_ORDER)
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "consumer_output_contract"
    ][
        "class_ids"
    ]
    == list(range(9))
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "model_contract"
    ][
        "n_estimators"
    ]
    == 100
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "model_contract"
    ][
        "random_state"
    ]
    == 42
)

print("✓ RF-3 strategy recorded")
print("✓ 32-feature input contract recorded")
print("✓ float32 input representation recorded")
print("✓ Authoritative feature order recorded")
print("✓ Nine-class output contract recorded")
print("✓ Frozen RF configuration recorded")


# ----------------------------------------------------------------
# 4. VALIDATE N04 DEPENDENCIES
# ----------------------------------------------------------------

print("\n[N04 DEPENDENCY VALIDATION]")

assert (
    "model_ready_feature_metadata"
    in RF_5_15_2_RELOADED_MANIFEST[
        "n04_dependencies"
    ]
)

assert (
    "final_n04_handoff_manifest"
    in RF_5_15_2_RELOADED_MANIFEST[
        "n04_dependencies"
    ]
)

print("✓ N04 model-ready feature metadata recorded")
print("✓ Final N04 handoff manifest recorded")


# ----------------------------------------------------------------
# 5. VALIDATE ARTIFACT GROUPS
# ----------------------------------------------------------------

print("\n[ARTIFACT GROUP VALIDATION]")

assert (
    len(
        RF_5_15_2_RELOADED_MANIFEST[
            "evaluation_artifacts"
        ]
    )
    == 6
)

assert (
    len(
        RF_5_15_2_RELOADED_MANIFEST[
            "interpretation_artifacts"
        ]
    )
    == 6
)

# 4 core artifacts + 12 RF persisted artifacts = 16
assert (
    len(
        RF_5_15_2_RELOADED_MANIFEST[
            "artifact_integrity"
        ]
    )
    == 16
)

print("✓ 6 evaluation artifacts recorded")
print("✓ 6 interpretation artifacts recorded")
print("✓ 16 artifact integrity records recorded")


# ----------------------------------------------------------------
# 6. VALIDATE HANDOFF STATUS
# ----------------------------------------------------------------

print("\n[HANDOFF STATUS]")

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "handoff_status"
    ]
    == "ready_for_validation"
)

assert (
    RF_5_15_2_RELOADED_MANIFEST[
        "manifest_self_reference"
    ]
    == (
        "Excluded from artifact integrity records "
        "to avoid self-referential hashing."
    )
)

print("✓ Handoff status = ready_for_validation")
print("✓ Manifest self-reference excluded")


# ----------------------------------------------------------------
# 7. FINAL 5.15.2 VALIDATION STATE
# ----------------------------------------------------------------

RF_5_15_2_VALIDATION = {

    "section_5_15_1_completed":
        all(
            RF_5_15_1_VALIDATION.values()
        ),

    "handoff_manifest_created":
        (
            RF_5_15_2_HANDOFF_MANIFEST_PATH.is_file()
            and
            RF_5_15_2_HANDOFF_MANIFEST_PATH.stat().st_size > 0
        ),

    "manifest_reload_successful":
        isinstance(
            RF_5_15_2_RELOADED_MANIFEST,
            dict
        ),

    "rf3_strategy_recorded":
        (
            RF_5_15_2_RELOADED_MANIFEST[
                "selected_strategy"
            ][
                "strategy_id"
            ]
            == "RF-3"
        ),

    "consumer_input_contract_recorded":
        (
            RF_5_15_2_RELOADED_MANIFEST[
                "consumer_input_contract"
            ][
                "feature_count"
            ]
            == 32
            and
            RF_5_15_2_RELOADED_MANIFEST[
                "consumer_input_contract"
            ][
                "feature_dtype"
            ]
            == "float32"
        ),

    "feature_order_recorded":
        (
            RF_5_15_2_RELOADED_MANIFEST[
                "consumer_input_contract"
            ][
                "feature_order"
            ]
            == list(RF_FEATURE_ORDER)
        ),

    "output_contract_recorded":
        (
            RF_5_15_2_RELOADED_MANIFEST[
                "consumer_output_contract"
            ][
                "class_ids"
            ]
            == list(range(9))
        ),

    "model_contract_recorded":
        (
            RF_5_15_2_RELOADED_MANIFEST[
                "model_contract"
            ][
                "n_estimators"
            ]
            == 100
            and
            RF_5_15_2_RELOADED_MANIFEST[
                "model_contract"
            ][
                "random_state"
            ]
            == 42
        ),

    "n04_dependencies_recorded":
        (
            "model_ready_feature_metadata"
            in RF_5_15_2_RELOADED_MANIFEST[
                "n04_dependencies"
            ]
            and
            "final_n04_handoff_manifest"
            in RF_5_15_2_RELOADED_MANIFEST[
                "n04_dependencies"
            ]
        ),

    "evaluation_artifacts_recorded":
        (
            len(
                RF_5_15_2_RELOADED_MANIFEST[
                    "evaluation_artifacts"
                ]
            )
            == 6
        ),

    "interpretation_artifacts_recorded":
        (
            len(
                RF_5_15_2_RELOADED_MANIFEST[
                    "interpretation_artifacts"
                ]
            )
            == 6
        ),

    "artifact_integrity_recorded":
        (
            len(
                RF_5_15_2_RELOADED_MANIFEST[
                    "artifact_integrity"
                ]
            )
            == 16
        ),

    "no_model_fitting":
        True,

    "no_resampling":
        True,

    "no_test_inference":
        True,

    "n04_immutable":
        True,
}


assert all(
    RF_5_15_2_VALIDATION.values()
), (
    "5.15.2 final RF handoff manifest "
    "completion validation failed."
)


print("\n" + "=" * 72)
print(
    "5.15.2 — FINAL RF HANDOFF MANIFEST "
    "CREATION PASSED"
)
print("=" * 72)

print(
    "\n✓ Final RF handoff manifest persisted"
)
print(
    "✓ RF-3 consumer contract recorded"
)
print(
    "✓ N04 dependency recorded"
)
print(
    "✓ Evaluation and interpretation artifacts recorded"
)
print(
    "✓ 16 SHA-256 integrity records validated"
)
print(
    "✓ Historical artifact-mapping observations retained"
)
print(
    "✓ No existing RF or N04 artifact modified"
)
print(
    "\nREADY FOR 5.15.3 — FINAL RF HANDOFF "
    "MANIFEST AND CONSUMER VALIDATION"
)
print("=" * 72)

========================================================================
5.15.2 — FINAL RF HANDOFF MANIFEST COMPLETION VALIDATION
========================================================================

[CREATED HANDOFF MANIFEST]
✓ Final RF handoff manifest exists
✓ Manifest size = 13029 bytes

[MANIFEST RELOAD]
✓ Manifest JSON reload successful

[HANDOFF CONTRACT VALIDATION]
✓ RF-3 strategy recorded
✓ 32-feature input contract recorded
✓ float32 input representation recorded
✓ Authoritative feature order recorded
✓ Nine-class output contract recorded
✓ Frozen RF configuration recorded

[N04 DEPENDENCY VALIDATION]
✓ N04 model-ready feature metadata recorded
✓ Final N04 handoff manifest recorded

[ARTIFACT GROUP VALIDATION]
✓ 6 evaluation artifacts recorded
✓ 6 interpretation artifacts recorded
✓ 16 artifact integrity records recorded

[HANDOFF STATUS]
✓ Handoff status = ready_for_validation
✓ Manifest self-reference excluded

========================================================================
5.15.2 — FINAL RF HANDOFF MANIFEST CREATION PASSED
========================================================================

✓ Final RF handoff manifest persisted
✓ RF-3 consumer contract recorded
✓ N04 dependency recorded
✓ Evaluation and interpretation artifacts recorded
✓ 16 SHA-256 integrity records validated
✓ Historical artifact-mapping observations retained
✓ No existing RF or N04 artifact modified

READY FOR 5.15.3 — FINAL RF HANDOFF MANIFEST AND CONSUMER VALIDATION
========================================================================

## 5.15.3 — Final RF Handoff Manifest and Consumer Validation

This subsection independently validates the persisted Random Forest handoff
manifest and the consumer package defined by Section 5.15.2. The validation
checks that the handoff manifest is readable, all referenced artifacts remain
available, the recorded SHA-256 integrity values match the current persisted
artifacts, the final RF model agrees with the frozen model contract, and the
N04 model-ready input dependency agrees with the authoritative feature
contract.

The validation also confirms that the selected RF-3 strategy, nine-class
output taxonomy, 32-feature float32 input representation, authoritative
feature order, frozen Random Forest configuration, evaluation artifacts, and
interpretation artifacts are internally consistent with the persisted
handoff package.

The final Random Forest model is loaded only for structural and configuration
validation. No prediction is generated and no Independent Test data is loaded
or used. Existing Random Forest and N04 artifacts remain read-only.

This subsection performs no model fitting, resampling, strategy selection,
hyperparameter selection, Test inference, new metric calculation, or model
modification. Its purpose is to establish that the persisted RF handoff
package can be safely consumed by downstream project components.

In [ ]:
# ================================================================
# 5.15.3 — FINAL RF HANDOFF MANIFEST
#             AND CONSUMER VALIDATION
# ================================================================

import hashlib
import json
import joblib
from pathlib import Path


print("=" * 72)
print(
    "5.15.3 — FINAL RF HANDOFF MANIFEST "
    "AND CONSUMER VALIDATION"
)
print("=" * 72)


# ----------------------------------------------------------------
# 1. SECTION 5.15.2 COMPLETION BOUNDARY
# ----------------------------------------------------------------

print("\n[SECTION 5.15.2 COMPLETION BOUNDARY]")

assert "RF_5_15_2_VALIDATION" in globals(), (
    "5.15.2 validation state is unavailable."
)

assert all(
    RF_5_15_2_VALIDATION.values()
), (
    "Section 5.15.2 final handoff manifest creation "
    "has not passed."
)

assert (
    "RF_5_15_2_HANDOFF_MANIFEST_PATH"
    in globals()
), (
    "Established RF handoff manifest path is unavailable."
)

print("✓ Section 5.15.2 completed and validated")
print("✓ Persisted RF handoff manifest is available")


# ----------------------------------------------------------------
# 2. INDEPENDENT MANIFEST RELOAD
# ----------------------------------------------------------------

print("\n[INDEPENDENT HANDOFF MANIFEST RELOAD]")

RF_5_15_3_HANDOFF_MANIFEST_PATH = Path(
    RF_5_15_2_HANDOFF_MANIFEST_PATH
)

assert (
    RF_5_15_3_HANDOFF_MANIFEST_PATH.is_file()
), (
    "Final RF handoff manifest is missing."
)

with open(
    RF_5_15_3_HANDOFF_MANIFEST_PATH,
    "r",
    encoding="utf-8"
) as file:

    RF_5_15_3_HANDOFF_MANIFEST = json.load(
        file
    )

assert isinstance(
    RF_5_15_3_HANDOFF_MANIFEST,
    dict
)

assert (
    RF_5_15_3_HANDOFF_MANIFEST[
        "manifest_type"
    ]
    == "Random Forest Final Handoff Manifest"
)

assert (
    RF_5_15_3_HANDOFF_MANIFEST[
        "manifest_version"
    ]
    == "1.0"
)

assert (
    RF_5_15_3_HANDOFF_MANIFEST[
        "notebook"
    ]
    == "N05"
)

print("✓ Manifest JSON loaded independently")
print("✓ Manifest type validated")
print("✓ Manifest version validated")
print("✓ Notebook identifier validated")


# ----------------------------------------------------------------
# 3. FINAL RF STRATEGY VALIDATION
# ----------------------------------------------------------------

print("\n[FINAL RF STRATEGY VALIDATION]")

RF_5_15_3_SELECTED_STRATEGY = (
    RF_5_15_3_HANDOFF_MANIFEST[
        "selected_strategy"
    ]
)

assert (
    RF_5_15_3_SELECTED_STRATEGY[
        "strategy_id"
    ]
    == "RF-3"
)

assert (
    RF_5_15_3_SELECTED_STRATEGY[
        "strategy_name"
    ]
    == "Controlled Random Oversampling"
)

assert (
    RF_5_15_3_SELECTED_STRATEGY[
        "training_partition"
    ]
    == "Training"
)

assert (
    RF_5_15_3_SELECTED_STRATEGY[
        "selection_partition"
    ]
    == "Validation"
)

assert (
    RF_5_15_3_SELECTED_STRATEGY[
        "independent_test_used_for_selection"
    ]
    is False
)

print("✓ Selected strategy = RF-3")
print("✓ Strategy = Controlled Random Oversampling")
print("✓ Training partition = Training")
print("✓ Selection partition = Validation")
print("✓ Independent Test excluded from selection")


# ----------------------------------------------------------------
# 4. FINAL MODEL AND METADATA PATH VALIDATION
# ----------------------------------------------------------------

print("\n[FINAL MODEL ARTIFACT VALIDATION]")

RF_5_15_3_FINAL_MODEL_PATH = Path(
    RF_5_15_3_HANDOFF_MANIFEST[
        "final_model"
    ][
        "path"
    ]
)

RF_5_15_3_FINAL_MODEL_METADATA_PATH = Path(
    RF_5_15_3_HANDOFF_MANIFEST[
        "final_model"
    ][
        "metadata_path"
    ]
)

assert (
    RF_5_15_3_FINAL_MODEL_PATH.is_file()
)

assert (
    RF_5_15_3_FINAL_MODEL_PATH.stat().st_size > 0
)

assert (
    RF_5_15_3_FINAL_MODEL_METADATA_PATH.is_file()
)

assert (
    RF_5_15_3_FINAL_MODEL_METADATA_PATH.stat().st_size > 0
)

assert (
    RF_5_15_3_FINAL_MODEL_PATH
    == RF_5_15_1_FINAL_MODEL_PATH
)

assert (
    RF_5_15_3_FINAL_MODEL_METADATA_PATH
    == RF_5_15_1_FINAL_MODEL_METADATA_PATH
)

print("✓ Final RF model path matches established artifact")
print("✓ Final RF metadata path matches established artifact")
print("✓ Final RF model artifact exists and is non-empty")
print("✓ Final RF metadata artifact exists and is non-empty")


# ----------------------------------------------------------------
# 5. FINAL RF METADATA CONSISTENCY
# ----------------------------------------------------------------

print("\n[FINAL RF METADATA CONSISTENCY]")

with open(
    RF_5_15_3_FINAL_MODEL_METADATA_PATH,
    "r",
    encoding="utf-8"
) as file:

    RF_5_15_3_FINAL_MODEL_METADATA = json.load(
        file
    )

assert (
    RF_5_15_3_FINAL_MODEL_METADATA[
        "strategy_id"
    ]
    == RF_5_15_3_SELECTED_STRATEGY[
        "strategy_id"
    ]
)

assert (
    RF_5_15_3_FINAL_MODEL_METADATA[
        "strategy_name"
    ]
    == RF_5_15_3_SELECTED_STRATEGY[
        "strategy_name"
    ]
)

assert (
    RF_5_15_3_FINAL_MODEL_METADATA[
        "training_partition"
    ]
    == "Training"
)

assert (
    RF_5_15_3_FINAL_MODEL_METADATA[
        "validation_used_for_fitting"
    ]
    is False
)

assert (
    RF_5_15_3_FINAL_MODEL_METADATA[
        "independent_test_used"
    ]
    is False
)

assert (
    RF_5_15_3_FINAL_MODEL_METADATA[
        "final_model"
    ]
    is True
)

assert (
    RF_5_15_3_FINAL_MODEL_METADATA[
        "persistence_completed"
    ]
    is True
)

assert (
    RF_5_15_3_FINAL_MODEL_METADATA[
        "feature_count"
    ]
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

assert (
    RF_5_15_3_FINAL_MODEL_METADATA[
        "class_count"
    ]
    == len(EXPECTED_RF_CLASS_IDS)
)

assert (
    RF_5_15_3_FINAL_MODEL_METADATA[
        "common_random_forest_configuration"
    ]
    == RF_COMMON_CONFIGURATION
)

assert (
    RF_5_15_3_FINAL_MODEL_METADATA[
        "random_seed"
    ]
    == int(RANDOM_SEED)
)

print("✓ Final metadata identifies RF-3")
print("✓ Final metadata confirms Training-only fitting")
print("✓ Validation excluded from model fitting")
print("✓ Independent Test excluded from model fitting")
print("✓ Final-model flag validated")
print("✓ Persistence-completed flag validated")
print("✓ 32-feature metadata validated")
print("✓ Nine-class metadata validated")
print("✓ Frozen RF configuration validated")
print("✓ Random seed = 42")


# ----------------------------------------------------------------
# 6. CONSUMER INPUT CONTRACT VALIDATION
# ----------------------------------------------------------------

print("\n[CONSUMER INPUT CONTRACT VALIDATION]")

RF_5_15_3_INPUT_CONTRACT = (
    RF_5_15_3_HANDOFF_MANIFEST[
        "consumer_input_contract"
    ]
)

assert (
    RF_5_15_3_INPUT_CONTRACT[
        "input_representation"
    ]
    == "N04 model-ready feature representation"
)

assert (
    RF_5_15_3_INPUT_CONTRACT[
        "feature_count"
    ]
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

assert (
    RF_5_15_3_INPUT_CONTRACT[
        "feature_dtype"
    ]
    == str(EXPECTED_FEATURE_DTYPE)
)

assert (
    RF_5_15_3_INPUT_CONTRACT[
        "feature_order"
    ]
    == list(RF_FEATURE_ORDER)
)

assert (
    RF_5_15_3_INPUT_CONTRACT[
        "preprocessing_authority"
    ]
    == "Notebook 04 model-preparation pipeline"
)

assert (
    RF_5_15_3_INPUT_CONTRACT[
        "independent_test_policy"
    ]
    == "Independent Test is reserved for final evaluation only"
)

print("✓ Input representation = N04 model-ready features")
print("✓ Input feature count = 32")
print("✓ Input dtype = float32")
print("✓ Authoritative feature order validated")
print("✓ N04 preprocessing authority validated")
print("✓ Independent Test policy validated")


# ----------------------------------------------------------------
# 7. N04 DEPENDENCY VALIDATION
# ----------------------------------------------------------------

print("\n[N04 DEPENDENCY VALIDATION]")

RF_5_15_3_N04_DEPENDENCIES = (
    RF_5_15_3_HANDOFF_MANIFEST[
        "n04_dependencies"
    ]
)

RF_5_15_3_N04_MODEL_READY_METADATA_PATH = Path(
    RF_5_15_3_N04_DEPENDENCIES[
        "model_ready_feature_metadata"
    ]
)

RF_5_15_3_N04_HANDOFF_MANIFEST_PATH = Path(
    RF_5_15_3_N04_DEPENDENCIES[
        "final_n04_handoff_manifest"
    ]
)

assert (
    RF_5_15_3_N04_MODEL_READY_METADATA_PATH.is_file()
)

assert (
    RF_5_15_3_N04_HANDOFF_MANIFEST_PATH.is_file()
)

with open(
    RF_5_15_3_N04_MODEL_READY_METADATA_PATH,
    "r",
    encoding="utf-8"
) as file:

    RF_5_15_3_N04_MODEL_READY_METADATA = json.load(
        file
    )

assert (
    int(
        RF_5_15_3_N04_MODEL_READY_METADATA[
            "final_feature_count"
        ]
    )
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

assert (
    RF_5_15_3_N04_MODEL_READY_METADATA[
        "final_feature_order"
    ]
    == list(RF_FEATURE_ORDER)
)

assert (
    RF_5_15_3_N04_MODEL_READY_METADATA_PATH
    == RF_5_15_1_MODEL_READY_METADATA_PATH
)

assert (
    RF_5_15_3_N04_HANDOFF_MANIFEST_PATH
    == RF_5_15_1_N04_HANDOFF_MANIFEST_PATH
)

print("✓ N04 model-ready metadata exists")
print("✓ N04 final handoff manifest exists")
print("✓ N04 feature count = 32")
print("✓ N04 feature order matches RF_FEATURE_ORDER")
print("✓ N04 dependency paths match established artifacts")


# ----------------------------------------------------------------
# 8. CONSUMER OUTPUT CONTRACT VALIDATION
# ----------------------------------------------------------------

print("\n[CONSUMER OUTPUT CONTRACT VALIDATION]")

RF_5_15_3_OUTPUT_CONTRACT = (
    RF_5_15_3_HANDOFF_MANIFEST[
        "consumer_output_contract"
    ]
)

assert (
    RF_5_15_3_OUTPUT_CONTRACT[
        "output_type"
    ]
    == "Random Forest class prediction"
)

assert (
    RF_5_15_3_OUTPUT_CONTRACT[
        "class_count"
    ]
    == len(EXPECTED_RF_CLASS_IDS)
)

assert (
    RF_5_15_3_OUTPUT_CONTRACT[
        "class_ids"
    ]
    == EXPECTED_RF_CLASS_IDS.tolist()
)

assert (
    RF_5_15_3_OUTPUT_CONTRACT[
        "class_mapping"
    ]
    == {
        str(class_id): str(class_name)
        for (
            class_id,
            class_name
        )
        in RF_CLASS_MAPPING.items()
    }
)

assert (
    RF_5_15_3_OUTPUT_CONTRACT[
        "selected_strategy"
    ]
    == "RF-3"
)

assert (
    RF_5_15_3_OUTPUT_CONTRACT[
        "selected_strategy_name"
    ]
    == "Controlled Random Oversampling"
)

print("✓ Random Forest class-prediction output validated")
print("✓ Nine-class output count validated")
print("✓ Class IDs 0–8 validated")
print("✓ Authoritative class mapping validated")
print("✓ RF-3 output strategy validated")


# ----------------------------------------------------------------
# 9. FROZEN MODEL CONTRACT VALIDATION
# ----------------------------------------------------------------

print("\n[FROZEN MODEL CONTRACT VALIDATION]")

RF_5_15_3_MODEL_CONTRACT = (
    RF_5_15_3_HANDOFF_MANIFEST[
        "model_contract"
    ]
)

assert (
    RF_5_15_3_MODEL_CONTRACT[
        "n_estimators"
    ]
    == 100
)

assert (
    RF_5_15_3_MODEL_CONTRACT[
        "max_features"
    ]
    == "sqrt"
)

assert (
    RF_5_15_3_MODEL_CONTRACT[
        "max_depth"
    ]
    is None
)

assert (
    RF_5_15_3_MODEL_CONTRACT[
        "bootstrap"
    ]
    is True
)

assert (
    RF_5_15_3_MODEL_CONTRACT[
        "n_jobs"
    ]
    == -1
)

assert (
    RF_5_15_3_MODEL_CONTRACT[
        "random_state"
    ]
    == 42
)

assert (
    RF_5_15_3_MODEL_CONTRACT[
        "class_weight"
    ]
    is None
)

print("✓ n_estimators = 100")
print("✓ max_features = sqrt")
print("✓ max_depth = None")
print("✓ bootstrap = True")
print("✓ n_jobs = -1")
print("✓ random_state = 42")
print("✓ class_weight = None")


# ----------------------------------------------------------------
# 10. PERSISTED MODEL STRUCTURAL VALIDATION
#
# The final model is loaded only to validate its structure and
# frozen configuration. No prediction is generated.
# ----------------------------------------------------------------

print("\n[PERSISTED MODEL STRUCTURAL VALIDATION]")

RF_5_15_3_FINAL_MODEL = joblib.load(
    RF_5_15_3_FINAL_MODEL_PATH
)

assert (
    RF_5_15_3_FINAL_MODEL.n_features_in_
    == EXPECTED_MODEL_READY_FEATURE_COUNT
)

assert (
    RF_5_15_3_FINAL_MODEL.classes_.tolist()
    == EXPECTED_RF_CLASS_IDS.tolist()
)

assert (
    RF_5_15_3_FINAL_MODEL.n_estimators
    == RF_5_15_3_MODEL_CONTRACT[
        "n_estimators"
    ]
)

assert (
    RF_5_15_3_FINAL_MODEL.max_features
    == RF_5_15_3_MODEL_CONTRACT[
        "max_features"
    ]
)

assert (
    RF_5_15_3_FINAL_MODEL.max_depth
    == RF_5_15_3_MODEL_CONTRACT[
        "max_depth"
    ]
)

assert (
    RF_5_15_3_FINAL_MODEL.bootstrap
    == RF_5_15_3_MODEL_CONTRACT[
        "bootstrap"
    ]
)

assert (
    RF_5_15_3_FINAL_MODEL.n_jobs
    == RF_5_15_3_MODEL_CONTRACT[
        "n_jobs"
    ]
)

assert (
    RF_5_15_3_FINAL_MODEL.random_state
    == RF_5_15_3_MODEL_CONTRACT[
        "random_state"
    ]
)

assert (
    RF_5_15_3_FINAL_MODEL.class_weight
    == RF_5_15_3_MODEL_CONTRACT[
        "class_weight"
    ]
)

print("✓ Persisted final RF model loaded")
print("✓ Model input feature count = 32")
print("✓ Model classes = 0–8")
print("✓ Persisted model configuration matches handoff contract")
print("✓ No prediction generated")


# ----------------------------------------------------------------
# 11. EVALUATION AND INTERPRETATION ARTIFACT VALIDATION
# ----------------------------------------------------------------

print("\n[EVALUATION AND INTERPRETATION ARTIFACT VALIDATION]")

RF_5_15_3_EVALUATION_ARTIFACTS = (
    RF_5_15_3_HANDOFF_MANIFEST[
        "evaluation_artifacts"
    ]
)

RF_5_15_3_INTERPRETATION_ARTIFACTS = (
    RF_5_15_3_HANDOFF_MANIFEST[
        "interpretation_artifacts"
    ]
)

assert (
    len(RF_5_15_3_EVALUATION_ARTIFACTS)
    == 6
)

assert (
    len(RF_5_15_3_INTERPRETATION_ARTIFACTS)
    == 6
)

for artifact_name, artifact_path in {
    **RF_5_15_3_EVALUATION_ARTIFACTS,
    **RF_5_15_3_INTERPRETATION_ARTIFACTS,
}.items():

    artifact_path = Path(
        artifact_path
    )

    assert artifact_path.is_file(), (
        f"Handoff artifact is missing: "
        f"{artifact_path}"
    )

    assert artifact_path.stat().st_size > 0, (
        f"Handoff artifact is empty: "
        f"{artifact_path}"
    )

print("✓ 6 evaluation artifacts exist")
print("✓ 6 interpretation artifacts exist")
print("✓ All referenced downstream artifacts are available")


# ----------------------------------------------------------------
# 12. SHA-256 ARTIFACT INTEGRITY VALIDATION
# ----------------------------------------------------------------

print("\n[SHA-256 ARTIFACT INTEGRITY VALIDATION]")


def rf_5_15_3_calculate_sha256(
    artifact_path
):

    sha256_hash = hashlib.sha256()

    with open(
        artifact_path,
        "rb"
    ) as file:

        for chunk in iter(
            lambda: file.read(1024 * 1024),
            b""
        ):

            sha256_hash.update(
                chunk
            )

    return sha256_hash.hexdigest()


RF_5_15_3_INTEGRITY_RESULTS = {}

RF_5_15_3_MANIFEST_INTEGRITY = (
    RF_5_15_3_HANDOFF_MANIFEST[
        "artifact_integrity"
    ]
)

assert (
    len(RF_5_15_3_MANIFEST_INTEGRITY)
    == 16
)

for (
    artifact_name,
    integrity_record
) in RF_5_15_3_MANIFEST_INTEGRITY.items():

    artifact_path = Path(
        integrity_record[
            "path"
        ]
    )

    assert artifact_path.is_file(), (
        f"Integrity artifact is missing: "
        f"{artifact_path}"
    )

    current_size = (
        artifact_path.stat().st_size
    )

    current_sha256 = (
        rf_5_15_3_calculate_sha256(
            artifact_path
        )
    )

    recorded_size = int(
        integrity_record[
            "size_bytes"
        ]
    )

    recorded_sha256 = (
        integrity_record[
            "sha256"
        ]
    )

    assert (
        current_size
        == recorded_size
    ), (
        f"Size mismatch for "
        f"{artifact_name}"
    )

    assert (
        current_sha256
        == recorded_sha256
    ), (
        f"SHA-256 mismatch for "
        f"{artifact_name}"
    )

    RF_5_15_3_INTEGRITY_RESULTS[
        artifact_name
    ] = True


assert (
    len(
        RF_5_15_3_INTEGRITY_RESULTS
    )
    == 16
)

assert all(
    RF_5_15_3_INTEGRITY_RESULTS.values()
)

print(
    "✓ All 16 persisted artifact sizes match"
)

print(
    "✓ All 16 persisted artifact SHA-256 values match"
)


# ----------------------------------------------------------------
# 13. ARTIFACT MAPPING OBSERVATION VALIDATION
# ----------------------------------------------------------------

print("\n[ARTIFACT MAPPING OBSERVATION VALIDATION]")

RF_5_15_3_MAPPING_OBSERVATIONS = (
    RF_5_15_3_HANDOFF_MANIFEST[
        "artifact_mapping_observations"
    ]
)

RF_5_15_3_ACTUAL_ARTIFACT_OUTPUT_CONFIGURATION = Path(
    RF_5_15_3_MAPPING_OBSERVATIONS[
        "actual_artifact_output_configuration"
    ]
)

RF_5_15_3_ACTUAL_EXPERIMENT_RESULTS = Path(
    RF_5_15_3_MAPPING_OBSERVATIONS[
        "actual_experiment_results"
    ]
)

assert (
    RF_5_15_3_ACTUAL_ARTIFACT_OUTPUT_CONFIGURATION.is_file()
)

assert (
    RF_5_15_3_ACTUAL_EXPERIMENT_RESULTS.is_file()
)

assert (
    RF_5_15_3_ACTUAL_EXPERIMENT_RESULTS
    == RF_EVALUATION_DIR /
    "rf_experiment_results.csv"
)

assert (
    RF_5_15_3_MAPPING_OBSERVATIONS[
        "mapping_policy"
    ]
    == (
        "Historical mappings are documented and are not "
        "silently rewritten."
    )
)

print("✓ Actual artifact-output configuration exists")
print("✓ Actual experiment-results artifact exists")
print("✓ Evaluation-directory experiment-results path validated")
print("✓ Historical mapping policy retained")


# ----------------------------------------------------------------
# 14. PROTECTION CONTRACT VALIDATION
# ----------------------------------------------------------------

print("\n[PROTECTION CONTRACT VALIDATION]")

RF_5_15_3_PROTECTION_CONTRACT = (
    RF_5_15_3_HANDOFF_MANIFEST[
        "protection_contract"
    ]
)

assert (
    RF_5_15_3_PROTECTION_CONTRACT[
        "n04_immutable"
    ]
    is True
)

assert (
    RF_5_15_3_PROTECTION_CONTRACT[
        "model_modification_in_handoff"
    ]
    is False
)

assert (
    RF_5_15_3_PROTECTION_CONTRACT[
        "test_inference_in_manifest_creation"
    ]
    is False
)

assert (
    RF_5_15_3_PROTECTION_CONTRACT[
        "new_test_metric_calculation"
    ]
    is False
)

assert (
    RF_5_15_3_PROTECTION_CONTRACT[
        "new_model_fitting"
    ]
    is False
)

assert (
    RF_5_15_3_PROTECTION_CONTRACT[
        "new_resampling"
    ]
    is False
)

assert (
    RF_5_15_3_PROTECTION_CONTRACT[
        "new_strategy_selection"
    ]
    is False
)

assert (
    RF_5_15_3_PROTECTION_CONTRACT[
        "new_hyperparameter_selection"
    ]
    is False
)

print("✓ N04 immutability requirement validated")
print("✓ Model modification prohibited")
print("✓ Test inference prohibited")
print("✓ New metric calculation prohibited")
print("✓ New model fitting prohibited")
print("✓ New resampling prohibited")
print("✓ New strategy selection prohibited")
print("✓ New hyperparameter selection prohibited")


# ----------------------------------------------------------------
# 15. FINAL 5.15.3 VALIDATION STATE
# ----------------------------------------------------------------

RF_5_15_3_VALIDATION = {

    "section_5_15_2_completed":
        all(
            RF_5_15_2_VALIDATION.values()
        ),

    "manifest_reloaded":
        isinstance(
            RF_5_15_3_HANDOFF_MANIFEST,
            dict
        ),

    "strategy_contract_valid":
        (
            RF_5_15_3_SELECTED_STRATEGY[
                "strategy_id"
            ]
            == "RF-3"
            and
            RF_5_15_3_SELECTED_STRATEGY[
                "strategy_name"
            ]
            == "Controlled Random Oversampling"
        ),

    "consumer_input_contract_valid":
        (
            RF_5_15_3_INPUT_CONTRACT[
                "feature_count"
            ]
            == 32
            and
            RF_5_15_3_INPUT_CONTRACT[
                "feature_dtype"
            ]
            == "float32"
            and
            RF_5_15_3_INPUT_CONTRACT[
                "feature_order"
            ]
            == list(RF_FEATURE_ORDER)
        ),

    "consumer_output_contract_valid":
        (
            RF_5_15_3_OUTPUT_CONTRACT[
                "class_ids"
            ]
            == list(range(9))
            and
            RF_5_15_3_OUTPUT_CONTRACT[
                "class_mapping"
            ]
            == {
                str(class_id): str(class_name)
                for (
                    class_id,
                    class_name
                )
                in RF_CLASS_MAPPING.items()
            }
        ),

    "n04_dependency_valid":
        (
            RF_5_15_3_N04_MODEL_READY_METADATA_PATH.is_file()
            and
            RF_5_15_3_N04_HANDOFF_MANIFEST_PATH.is_file()
            and
            RF_5_15_3_N04_MODEL_READY_METADATA[
                "final_feature_order"
            ]
            == list(RF_FEATURE_ORDER)
        ),

    "final_model_contract_valid":
        (
            RF_5_15_3_FINAL_MODEL.n_features_in_
            == 32
            and
            RF_5_15_3_FINAL_MODEL.classes_.tolist()
            == list(range(9))
            and
            RF_5_15_3_FINAL_MODEL.n_estimators
            == 100
            and
            RF_5_15_3_FINAL_MODEL.random_state
            == 42
        ),

    "evaluation_artifacts_valid":
        (
            len(
                RF_5_15_3_EVALUATION_ARTIFACTS
            )
            == 6
            and
            all(
                Path(path).is_file()
                for path
                in RF_5_15_3_EVALUATION_ARTIFACTS.values()
            )
        ),

    "interpretation_artifacts_valid":
        (
            len(
                RF_5_15_3_INTERPRETATION_ARTIFACTS
            )
            == 6
            and
            all(
                Path(path).is_file()
                for path
                in RF_5_15_3_INTERPRETATION_ARTIFACTS.values()
            )
        ),

    "artifact_integrity_valid":
        (
            len(
                RF_5_15_3_INTEGRITY_RESULTS
            )
            == 16
            and
            all(
                RF_5_15_3_INTEGRITY_RESULTS.values()
            )
        ),

    "mapping_observations_valid":
        (
            RF_5_15_3_ACTUAL_ARTIFACT_OUTPUT_CONFIGURATION.is_file()
            and
            RF_5_15_3_ACTUAL_EXPERIMENT_RESULTS.is_file()
        ),

    "protection_contract_valid":
        (
            RF_5_15_3_PROTECTION_CONTRACT[
                "n04_immutable"
            ]
            is True
            and
            RF_5_15_3_PROTECTION_CONTRACT[
                "model_modification_in_handoff"
            ]
            is False
            and
            RF_5_15_3_PROTECTION_CONTRACT[
                "test_inference_in_manifest_creation"
            ]
            is False
            and
            RF_5_15_3_PROTECTION_CONTRACT[
                "new_model_fitting"
            ]
            is False
        ),
}


assert all(
    RF_5_15_3_VALIDATION.values()
), (
    "5.15.3 final RF handoff manifest "
    "and consumer validation failed."
)


print("\n" + "=" * 72)
print(
    "5.15.3 — FINAL RF HANDOFF MANIFEST "
    "AND CONSUMER VALIDATION PASSED"
)
print("=" * 72)

print(
    "\n✓ Persisted handoff manifest independently validated"
)

print(
    "✓ RF-3 strategy and consumer contract validated"
)

print(
    "✓ N04 model-ready dependency validated"
)

print(
    "✓ Final RF model structure and frozen configuration validated"
)

print(
    "✓ Evaluation and interpretation artifacts validated"
)

print(
    "✓ All 16 SHA-256 integrity records validated"
)

print(
    "✓ Historical artifact-mapping observations validated"
)

print(
    "✓ No Test inference performed"
)

print(
    "✓ No model fitting, resampling, or model modification performed"
)

print(
    "\nREADY FOR 5.15.4 — FINAL RF HANDOFF COMPLETION "
    "AND READINESS GATE"
)

print("=" * 72)

========================================================================
5.15.3 — FINAL RF HANDOFF MANIFEST AND CONSUMER VALIDATION
========================================================================

[SECTION 5.15.2 COMPLETION BOUNDARY]
✓ Section 5.15.2 completed and validated
✓ Persisted RF handoff manifest is available

[INDEPENDENT HANDOFF MANIFEST RELOAD]
✓ Manifest JSON loaded independently
✓ Manifest type validated
✓ Manifest version validated
✓ Notebook identifier validated

[FINAL RF STRATEGY VALIDATION]
✓ Selected strategy = RF-3
✓ Strategy = Controlled Random Oversampling
✓ Training partition = Training
✓ Selection partition = Validation
✓ Independent Test excluded from selection

[FINAL MODEL ARTIFACT VALIDATION]
✓ Final RF model path matches established artifact
✓ Final RF metadata path matches established artifact
✓ Final RF model artifact exists and is non-empty
✓ Final RF metadata artifact exists and is non-empty

[FINAL RF METADATA CONSISTENCY]
✓ Final metadata identifies RF-3
✓ Final metadata confirms Training-only fitting
✓ Validation excluded from model fitting
✓ Independent Test excluded from model fitting
✓ Final-model flag validated
✓ Persistence-completed flag validated
✓ 32-feature metadata validated
✓ Nine-class metadata validated
✓ Frozen RF configuration validated
✓ Random seed = 42

[CONSUMER INPUT CONTRACT VALIDATION]
✓ Input representation = N04 model-ready features
✓ Input feature count = 32
✓ Input dtype = float32
✓ Authoritative feature order validated
✓ N04 preprocessing authority validated
✓ Independent Test policy validated

[N04 DEPENDENCY VALIDATION]
✓ N04 model-ready metadata exists
✓ N04 final handoff manifest exists
✓ N04 feature count = 32
✓ N04 feature order matches RF_FEATURE_ORDER
✓ N04 dependency paths match established artifacts

[CONSUMER OUTPUT CONTRACT VALIDATION]
✓ Random Forest class-prediction output validated
✓ Nine-class output count validated
✓ Class IDs 0–8 validated
✓ Authoritative class mapping validated
✓ RF-3 output strategy validated

[FROZEN MODEL CONTRACT VALIDATION]
✓ n_estimators = 100
✓ max_features = sqrt
✓ max_depth = None
✓ bootstrap = True
✓ n_jobs = -1
✓ random_state = 42
✓ class_weight = None

[PERSISTED MODEL STRUCTURAL VALIDATION]
✓ Persisted final RF model loaded
✓ Model input feature count = 32
✓ Model classes = 0–8
✓ Persisted model configuration matches handoff contract
✓ No prediction generated

[EVALUATION AND INTERPRETATION ARTIFACT VALIDATION]
✓ 6 evaluation artifacts exist
✓ 6 interpretation artifacts exist
✓ All referenced downstream artifacts are available

[SHA-256 ARTIFACT INTEGRITY VALIDATION]
✓ All 16 persisted artifact sizes match
✓ All 16 persisted artifact SHA-256 values match

[ARTIFACT MAPPING OBSERVATION VALIDATION]
✓ Actual artifact-output configuration exists
✓ Actual experiment-results artifact exists
✓ Evaluation-directory experiment-results path validated
✓ Historical mapping policy retained

[PROTECTION CONTRACT VALIDATION]
✓ N04 immutability requirement validated
✓ Model modification prohibited
✓ Test inference prohibited
✓ New metric calculation prohibited
✓ New model fitting prohibited
✓ New resampling prohibited
✓ New strategy selection prohibited
✓ New hyperparameter selection prohibited

========================================================================
5.15.3 — FINAL RF HANDOFF MANIFEST AND CONSUMER VALIDATION PASSED
========================================================================

✓ Persisted handoff manifest independently validated
✓ RF-3 strategy and consumer contract validated
✓ N04 model-ready dependency validated
✓ Final RF model structure and frozen configuration validated
✓ Evaluation and interpretation artifacts validated
✓ All 16 SHA-256 integrity records validated
✓ Historical artifact-mapping observations validated
✓ No Test inference performed
✓ No model fitting, resampling, or model modification performed

READY FOR 5.15.4 — FINAL RF HANDOFF COMPLETION AND READINESS GATE
========================================================================

## 5.15.4 — Final RF Handoff Completion and Readiness Gate

This subsection provides the final completion and readiness gate for the
Random Forest development workflow in Notebook 05.

The gate consolidates the validated results of Section 5.14 and Section 5.15,
including Random Forest artifact persistence, the final RF consumer contract,
the persisted handoff manifest, and independent handoff and consumer
validation.

The final RF-3 model, its metadata, the N04 model-ready input dependency,
evaluation artifacts, interpretation artifacts, and final handoff manifest
have all been validated as a consistent and reproducible downstream package.

The completed handoff package is now ready for use by subsequent project
components, including ensemble development and integration, without rerunning
the Random Forest development workflow.

Notebook 05 therefore concludes with the final Random Forest model and its
validated handoff package preserved as the authoritative RF downstream
dependency.

No new model fitting, resampling, Test inference, metric calculation,
strategy selection, hyperparameter selection, model modification, or artifact
creation is performed in this final gate. N04 remains an immutable upstream
dependency.

In [ ]:
# ================================================================
# 5.15.4 — FINAL RF HANDOFF COMPLETION
#             AND READINESS GATE
# ================================================================

print("=" * 72)
print(
    "5.15.4 — FINAL RF HANDOFF COMPLETION "
    "AND READINESS GATE"
)
print("=" * 72)


# ----------------------------------------------------------------
# 1. SECTION 5.14 COMPLETION BOUNDARY
# ----------------------------------------------------------------

print("\n[SECTION 5.14 COMPLETION BOUNDARY]")

assert "RF_5_14_4_VALIDATION" in globals(), (
    "Section 5.14 final validation state is unavailable."
)

assert all(
    RF_5_14_4_VALIDATION.values()
), (
    "Section 5.14 final readiness gate has not passed."
)

print("✓ Section 5.14 completed and validated")
print("✓ Final RF artifact package is complete")


# ----------------------------------------------------------------
# 2. SECTION 5.15 COMPLETION BOUNDARY
# ----------------------------------------------------------------

print("\n[SECTION 5.15 COMPLETION BOUNDARY]")

assert "RF_5_15_1_VALIDATION" in globals(), (
    "5.15.1 validation state is unavailable."
)

assert "RF_5_15_2_VALIDATION" in globals(), (
    "5.15.2 validation state is unavailable."
)

assert "RF_5_15_3_VALIDATION" in globals(), (
    "5.15.3 validation state is unavailable."
)

assert all(
    RF_5_15_1_VALIDATION.values()
), (
    "5.15.1 final RF consumer contract has not passed."
)

assert all(
    RF_5_15_2_VALIDATION.values()
), (
    "5.15.2 final RF handoff manifest creation has not passed."
)

assert all(
    RF_5_15_3_VALIDATION.values()
), (
    "5.15.3 final RF handoff validation has not passed."
)

print("✓ 5.15.1 consumer contract completed and validated")
print("✓ 5.15.2 handoff manifest completed and validated")
print("✓ 5.15.3 handoff and consumer validation completed")


# ----------------------------------------------------------------
# 3. FINAL HANDOFF MANIFEST READINESS
# ----------------------------------------------------------------

print("\n[FINAL HANDOFF MANIFEST READINESS]")

assert (
    "RF_5_15_3_HANDOFF_MANIFEST_PATH"
    in globals()
), (
    "Final RF handoff manifest path is unavailable."
)

assert (
    RF_5_15_3_HANDOFF_MANIFEST_PATH.is_file()
), (
    "Final RF handoff manifest does not exist."
)

assert (
    RF_5_15_3_HANDOFF_MANIFEST_PATH.stat().st_size > 0
), (
    "Final RF handoff manifest is empty."
)

assert (
    "RF_5_15_3_HANDOFF_MANIFEST"
    in globals()
), (
    "Validated final RF handoff manifest is unavailable."
)

assert (
    RF_5_15_3_HANDOFF_MANIFEST[
        "handoff_status"
    ]
    == "ready_for_validation"
), (
    "Final RF handoff manifest does not have "
    "the expected validated handoff status."
)

print("✓ Final RF handoff manifest exists")
print("✓ Final RF handoff manifest is non-empty")
print("✓ Final RF handoff package is validated")


# ----------------------------------------------------------------
# 4. FINAL RF CONSUMER READINESS
# ----------------------------------------------------------------

print("\n[FINAL RF CONSUMER READINESS]")

assert (
    RF_5_15_3_INPUT_CONTRACT[
        "feature_count"
    ]
    == 32
)

assert (
    RF_5_15_3_INPUT_CONTRACT[
        "feature_dtype"
    ]
    == "float32"
)

assert (
    RF_5_15_3_INPUT_CONTRACT[
        "feature_order"
    ]
    == list(RF_FEATURE_ORDER)
)

assert (
    RF_5_15_3_OUTPUT_CONTRACT[
        "class_ids"
    ]
    == list(range(9))
)

assert (
    RF_5_15_3_SELECTED_STRATEGY[
        "strategy_id"
    ]
    == "RF-3"
)

assert (
    RF_5_15_3_SELECTED_STRATEGY[
        "strategy_name"
    ]
    == "Controlled Random Oversampling"
)

print("✓ RF-3 final strategy confirmed")
print("✓ 32-feature float32 input contract confirmed")
print("✓ Authoritative feature order confirmed")
print("✓ Nine-class output contract confirmed")
print("✓ Final RF consumer package is ready")


# ----------------------------------------------------------------
# 5. DOWNSTREAM DEPENDENCY READINESS
# ----------------------------------------------------------------

print("\n[DOWNSTREAM DEPENDENCY READINESS]")

assert (
    RF_5_15_3_N04_MODEL_READY_METADATA_PATH.is_file()
)

assert (
    RF_5_15_3_N04_HANDOFF_MANIFEST_PATH.is_file()
)

assert (
    RF_5_15_3_FINAL_MODEL_PATH.is_file()
)

assert (
    RF_5_15_3_FINAL_MODEL_METADATA_PATH.is_file()
)

print("✓ N04 model-ready feature metadata available")
print("✓ Final N04 handoff manifest available")
print("✓ Final RF model available")
print("✓ Final RF metadata available")


# ----------------------------------------------------------------
# 6. FINAL PROTECTION BOUNDARY
# ----------------------------------------------------------------

print("\n[FINAL PROTECTION BOUNDARY]")

assert (
    RF_5_15_3_PROTECTION_CONTRACT[
        "n04_immutable"
    ]
    is True
)

assert (
    RF_5_15_3_PROTECTION_CONTRACT[
        "model_modification_in_handoff"
    ]
    is False
)

assert (
    RF_5_15_3_PROTECTION_CONTRACT[
        "test_inference_in_manifest_creation"
    ]
    is False
)

assert (
    RF_5_15_3_PROTECTION_CONTRACT[
        "new_model_fitting"
    ]
    is False
)

assert (
    RF_5_15_3_PROTECTION_CONTRACT[
        "new_resampling"
    ]
    is False
)

assert (
    RF_5_15_3_PROTECTION_CONTRACT[
        "new_strategy_selection"
    ]
    is False
)

print("✓ N04 remains immutable")
print("✓ Final model remains unmodified")
print("✓ No Test inference performed")
print("✓ No new model fitting performed")
print("✓ No new resampling performed")
print("✓ No new strategy selection performed")


# ----------------------------------------------------------------
# 7. FINAL NOTEBOOK 05 READINESS STATE
# ----------------------------------------------------------------

RF_5_15_4_VALIDATION = {

    "section_5_14_completed":
        all(
            RF_5_14_4_VALIDATION.values()
        ),

    "section_5_15_1_completed":
        all(
            RF_5_15_1_VALIDATION.values()
        ),

    "section_5_15_2_completed":
        all(
            RF_5_15_2_VALIDATION.values()
        ),

    "section_5_15_3_completed":
        all(
            RF_5_15_3_VALIDATION.values()
        ),

    "final_handoff_manifest_available":
        (
            RF_5_15_3_HANDOFF_MANIFEST_PATH.is_file()
            and
            RF_5_15_3_HANDOFF_MANIFEST_PATH.stat().st_size > 0
        ),

    "final_rf_consumer_contract_ready":
        (
            RF_5_15_3_INPUT_CONTRACT[
                "feature_count"
            ]
            == 32
            and
            RF_5_15_3_INPUT_CONTRACT[
                "feature_dtype"
            ]
            == "float32"
            and
            RF_5_15_3_INPUT_CONTRACT[
                "feature_order"
            ]
            == list(RF_FEATURE_ORDER)
        ),

    "final_rf_strategy_ready":
        (
            RF_5_15_3_SELECTED_STRATEGY[
                "strategy_id"
            ]
            == "RF-3"
            and
            RF_5_15_3_SELECTED_STRATEGY[
                "strategy_name"
            ]
            == "Controlled Random Oversampling"
        ),

    "final_output_taxonomy_ready":
        (
            RF_5_15_3_OUTPUT_CONTRACT[
                "class_ids"
            ]
            == list(range(9))
        ),

    "n04_dependency_ready":
        (
            RF_5_15_3_N04_MODEL_READY_METADATA_PATH.is_file()
            and
            RF_5_15_3_N04_HANDOFF_MANIFEST_PATH.is_file()
        ),

    "final_rf_model_ready":
        (
            RF_5_15_3_FINAL_MODEL_PATH.is_file()
            and
            RF_5_15_3_FINAL_MODEL_METADATA_PATH.is_file()
        ),

    "protection_contract_preserved":
        (
            RF_5_15_3_PROTECTION_CONTRACT[
                "n04_immutable"
            ]
            is True
            and
            RF_5_15_3_PROTECTION_CONTRACT[
                "model_modification_in_handoff"
            ]
            is False
            and
            RF_5_15_3_PROTECTION_CONTRACT[
                "test_inference_in_manifest_creation"
            ]
            is False
            and
            RF_5_15_3_PROTECTION_CONTRACT[
                "new_model_fitting"
            ]
            is False
            and
            RF_5_15_3_PROTECTION_CONTRACT[
                "new_resampling"
            ]
            is False
            and
            RF_5_15_3_PROTECTION_CONTRACT[
                "new_strategy_selection"
            ]
            is False
        ),
}


assert all(
    RF_5_15_4_VALIDATION.values()
), (
    "5.15.4 final RF handoff completion "
    "and readiness gate failed."
)


# ----------------------------------------------------------------
# 8. FINAL NOTEBOOK 05 CONCLUSION
# ----------------------------------------------------------------

print("\n" + "=" * 72)
print(
    "5.15.4 — FINAL RF HANDOFF COMPLETION "
    "AND READINESS GATE PASSED"
)
print("=" * 72)

print("\n[FINAL RANDOM FOREST HANDOFF STATUS]")

print("✓ Section 5.14 artifact persistence completed")
print("✓ Section 5.15.1 consumer contract completed")
print("✓ Section 5.15.2 handoff manifest created")
print("✓ Section 5.15.3 handoff package independently validated")
print("✓ Final RF-3 model is ready for downstream consumption")
print("✓ N04 model-ready dependency is preserved")
print("✓ Final RF model and metadata are preserved")
print("✓ Evaluation and interpretation artifacts are preserved")
print("✓ Final handoff manifest is preserved")
print("✓ No protected Test boundary was violated")
print("✓ No model fitting or modification occurred during handoff")


print("\n" + "=" * 72)
print(
    "NOTEBOOK 05 — RANDOM FOREST DEVELOPMENT "
    "AND FINAL HANDOFF COMPLETED"
)
print("=" * 72)

print(
    "\nFINAL MODEL : RF-3 — Controlled Random Oversampling"
)

print(
    "INPUT       : N04 model-ready 32-feature float32 representation"
)

print(
    "OUTPUT      : Nine-class Random Forest prediction (0–8)"
)

print(
    "HANDOFF     : Final RF handoff manifest validated"
)

print(
    "STATUS      : READY FOR DOWNSTREAM ENSEMBLE INTEGRATION"
)

print(
    "\nNotebook 05 is complete."
)

print("=" * 72)

========================================================================
5.15.4 — FINAL RF HANDOFF COMPLETION AND READINESS GATE
========================================================================

[SECTION 5.14 COMPLETION BOUNDARY]
✓ Section 5.14 completed and validated
✓ Final RF artifact package is complete

[SECTION 5.15 COMPLETION BOUNDARY]
✓ 5.15.1 consumer contract completed and validated
✓ 5.15.2 handoff manifest completed and validated
✓ 5.15.3 handoff and consumer validation completed

[FINAL HANDOFF MANIFEST READINESS]
✓ Final RF handoff manifest exists
✓ Final RF handoff manifest is non-empty
✓ Final RF handoff package is validated

[FINAL RF CONSUMER READINESS]
✓ RF-3 final strategy confirmed
✓ 32-feature float32 input contract confirmed
✓ Authoritative feature order confirmed
✓ Nine-class output contract confirmed
✓ Final RF consumer package is ready

[DOWNSTREAM DEPENDENCY READINESS]
✓ N04 model-ready feature metadata available
✓ Final N04 handoff manifest available
✓ Final RF model available
✓ Final RF metadata available

[FINAL PROTECTION BOUNDARY]
✓ N04 remains immutable
✓ Final model remains unmodified
✓ No Test inference performed
✓ No new model fitting performed
✓ No new resampling performed
✓ No new strategy selection performed

========================================================================
5.15.4 — FINAL RF HANDOFF COMPLETION AND READINESS GATE PASSED
========================================================================

[FINAL RANDOM FOREST HANDOFF STATUS]
✓ Section 5.14 artifact persistence completed
✓ Section 5.15.1 consumer contract completed
✓ Section 5.15.2 handoff manifest created
✓ Section 5.15.3 handoff package independently validated
✓ Final RF-3 model is ready for downstream consumption
✓ N04 model-ready dependency is preserved
✓ Final RF model and metadata are preserved
✓ Evaluation and interpretation artifacts are preserved
✓ Final handoff manifest is preserved
✓ No protected Test boundary was violated
✓ No model fitting or modification occurred during handoff

========================================================================
NOTEBOOK 05 — RANDOM FOREST DEVELOPMENT AND FINAL HANDOFF COMPLETED
========================================================================

FINAL MODEL : RF-3 — Controlled Random Oversampling
INPUT       : N04 model-ready 32-feature float32 representation
OUTPUT      : Nine-class Random Forest prediction (0–8)
HANDOFF     : Final RF handoff manifest validated
STATUS      : READY FOR DOWNSTREAM ENSEMBLE INTEGRATION

Notebook 05 is complete.
========================================================================

### 5.16 — RF Ensemble Preparation and OOF Generation

This section prepares the selected RF-3 model for leakage-controlled stacking with LSTM-3. It preserves all existing RF model and evaluation artifacts, generates fold-specific out-of-fold predictions separately from the final model, and publishes a validated handoff for N08.

#### 5.16.1 — Shared Ensemble Protocol and Fold Contract

Recover the persisted N04 Training artifacts and the existing shared five-fold plan. Verify the feature and target shapes, class mapping, fold-plan structure, and existing alignment-audit evidence. This subsection performs no model training and does not access the Test arrays.

In [ ]:

# ================================================================
# 5.16.1 — SHARED ENSEMBLE PROTOCOL AND FOLD CONTRACT
# ================================================================

import json
from pathlib import Path
import numpy as np

print("=" * 72)
print("5.16.1 — SHARED ENSEMBLE PROTOCOL AND FOLD CONTRACT")
print("=" * 72)

# ------------------------------------------------
# 1. RECOVER PROJECT ROOT WITHOUT RERUNNING N05
# ------------------------------------------------

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/"
    "AI-Network-Intrusion-Detection-System"
)

if not PROJECT_ROOT.is_dir():
    try:
        from google.colab import drive
        drive.mount("/content/drive", force_remount=False)
    except ImportError:
        pass

if not PROJECT_ROOT.is_dir():
    raise FileNotFoundError(
        "Project root is unavailable. Mount Google Drive and verify:\n"
        f"{PROJECT_ROOT}"
    )

OUTPUTS_DIR = PROJECT_ROOT / "outputs"

# ------------------------------------------------
# 2. AUTHORITATIVE N04 TRAINING ARTIFACTS ONLY
#    Do not load Validation or Test arrays here.
# ------------------------------------------------

N04_DIR = OUTPUTS_DIR / "model_preparation_v2"

X_TRAIN_PATH = (
    N04_DIR / "feature_scaling" / "X_train_scaled.npy"
)
Y_TRAIN_PATH = (
    N04_DIR / "model_ready_targets" / "y_train.npy"
)

for path in (X_TRAIN_PATH, Y_TRAIN_PATH):
    if not path.is_file():
        raise FileNotFoundError(
            f"Required N04 Training artifact is missing:\n{path}"
        )

X_train = np.load(X_TRAIN_PATH, mmap_mode="r")
y_train = np.load(Y_TRAIN_PATH, mmap_mode="r")

assert X_train.ndim == 2, (
    f"Expected 2D Training features, got {X_train.shape}"
)
assert X_train.shape == (1_814_018, 32), (
    f"Unexpected N04 Training feature shape: {X_train.shape}"
)
assert y_train.shape == (X_train.shape[0],), (
    f"Training feature/target alignment failed: "
    f"{X_train.shape} vs {y_train.shape}"
)
assert np.issubdtype(X_train.dtype, np.floating)
assert np.issubdtype(y_train.dtype, np.integer)

classes_present = np.unique(y_train).astype(int).tolist()
assert classes_present == list(range(9)), (
    f"Unexpected class IDs: {classes_present}"
)

print("[PASS] N04 Training feature/target contract")
print(f"  X_train: {X_train.shape}, {X_train.dtype}")
print(f"  y_train: {y_train.shape}, {y_train.dtype}")
print(f"  Classes: {classes_present}")

# ------------------------------------------------
# 3. RECOVER EXISTING SHARED FIVE-FOLD PLAN
# ------------------------------------------------

ENSEMBLE_DIR = OUTPUTS_DIR / "ensemble_model_development"
EXPERIMENT_DIR = ENSEMBLE_DIR / "experiments"

FOLD_PLAN_PATH = EXPERIMENT_DIR / "oof_fold_plan_v1.json"
ALIGNMENT_AUDIT_PATH = (
    EXPERIMENT_DIR / "oof_index_alignment_audit_v1.json"
)

required_protocol_files = {
    "shared fold plan": FOLD_PLAN_PATH,
    "RF/LSTM alignment audit": ALIGNMENT_AUDIT_PATH,
}

missing = [
    f"{name}: {path}"
    for name, path in required_protocol_files.items()
    if not path.is_file()
]

if missing:
    raise FileNotFoundError(
        "The shared OOF protocol is not ready. Missing required "
        "existing artifact(s):\n- "
        + "\n- ".join(missing)
        + "\nNo replacement fold plan was created."
    )

with FOLD_PLAN_PATH.open("r", encoding="utf-8") as f:
    fold_plan = json.load(f)

with ALIGNMENT_AUDIT_PATH.open("r", encoding="utf-8") as f:
    alignment_audit = json.load(f)

assert isinstance(fold_plan, dict), (
    "Fold plan must be a JSON object."
)
assert isinstance(alignment_audit, dict), (
    "Alignment audit must be a JSON object."
)

print("\n[EXISTING SHARED PROTOCOL]")
print(f"  Fold plan: {FOLD_PLAN_PATH}")
print(f"  Fold-plan top-level keys: {list(fold_plan.keys())}")
print(f"  Alignment audit: {ALIGNMENT_AUDIT_PATH}")
print(
    "  Alignment-audit top-level keys: "
    f"{list(alignment_audit.keys())}"
)

# Display fold-plan structure without assuming its schema.
for key, value in fold_plan.items():
    if isinstance(value, list):
        print(f"  {key}: list with {len(value)} item(s)")
        if value and isinstance(value[0], dict):
            print(f"    First item keys: {list(value[0].keys())}")
    elif isinstance(value, dict):
        print(f"  {key}: object with keys {list(value.keys())}")
    else:
        print(f"  {key}: {value}")

# ------------------------------------------------
# 4. CHECK EXISTING RF MODEL/HANDOFF PRESENCE
#    This verifies paths only; it does not retrain.
# ------------------------------------------------

RF_OUTPUT_DIR = OUTPUTS_DIR / "random_forest_model_development"
RF_MODEL_PATH = (
    PROJECT_ROOT
    / "trained_models"
    / "random_forest"
    / "final_random_forest.joblib"
)

# The notebook's established mapping places the final model under
# the RF output directory's configured model path. Report both
# candidate locations and require the actual established file.
rf_candidates = [
    RF_MODEL_PATH,
    RF_OUTPUT_DIR / "trained_models" / "random_forest"
    / "final_random_forest.joblib",
]

existing_rf_models = [p for p in rf_candidates if p.is_file()]

print("\n[EXISTING FINAL RF MODEL]")
if existing_rf_models:
    for path in existing_rf_models:
        print(f"  FOUND: {path}")
else:
    print("  Model not found at the two conventional locations.")
    print("  We will recover its exact path from the RF handoff manifest.")

handoff_path = RF_OUTPUT_DIR / "rf_handoff_manifest.json"
if handoff_path.is_file():
    print(f"  RF handoff manifest: FOUND — {handoff_path}")
else:
    print(f"  RF handoff manifest: MISSING — {handoff_path}")

# ------------------------------------------------
# 5. SAFE STATUS SUMMARY
#    No models trained; no predictions generated.
# ------------------------------------------------

print("\n[5.16.1 STATUS]")
print("Training artifacts loaded read-only.")
print("Existing fold plan and alignment audit loaded read-only.")
print("No RF model was trained or modified.")
print("No Validation or Test arrays were loaded.")
print("No existing model/evaluation artifacts were overwritten.")
print(
    "\nNext: verify the exact fold-plan schema and alignment-audit "
    "status before approving any OOF training."
)

========================================================================
5.16.1 — SHARED ENSEMBLE PROTOCOL AND FOLD CONTRACT
========================================================================
[PASS] N04 Training feature/target contract
  X_train: (1814018, 32), float32
  y_train: (1814018,), int64
  Classes: [0, 1, 2, 3, 4, 5, 6, 7, 8]

[EXISTING SHARED PROTOCOL]
  Fold plan: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/experiments/oof_fold_plan_v1.json
  Fold-plan top-level keys: ['created_utc', 'status', 'partition_used', 'training_rows', 'feature_count', 'class_ids', 'fold_count', 'sequence_length', 'purge_rows_each_side', 'eligible_sequence_targets', 'heldout_targets_covered_once', 'folds', 'limitations']
  Alignment audit: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/experiments/oof_index_alignment_audit_v1.json
  Alignment-audit top-level keys: ['status', 'sequence_length', 'target_assignment', 'training_rows', 'training_sequences', 'sequence_to_raw_row_mapping', 'all_sequence_labels_match_last_observation', 'sampled_window_checks', 'fold_mappings', 'validation_accessed', 'test_accessed', 'models_trained', 'predictions_generated', 'temporal_order_verified', 'session_boundaries_verified']
  created_utc: 2026-10-15T09:48:40.447121+00:00
  status: FOLD_PLAN_DEFINED_REQUIRES_REVIEW
  partition_used: Training only
  training_rows: 1814018
  feature_count: 32
  class_ids: list with 9 item(s)
  fold_count: 5
  sequence_length: 10
  purge_rows_each_side: 9
  eligible_sequence_targets: 1814009
  heldout_targets_covered_once: True
  folds: list with 5 item(s)
    First item keys: ['fold_id', 'heldout_target_start', 'heldout_target_end_exclusive', 'heldout_target_count', 'heldout_class_counts', 'purged_target_start', 'purged_target_end_exclusive', 'training_target_count_after_purge', 'training_target_indices_are_contiguous']
  limitations: list with 5 item(s)

[EXISTING FINAL RF MODEL]
  FOUND: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models/random_forest/final_random_forest.joblib
  RF handoff manifest: FOUND — /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/rf_handoff_manifest.json

[5.16.1 STATUS]
Training artifacts loaded read-only.
Existing fold plan and alignment audit loaded read-only.
No RF model was trained or modified.
No Validation or Test arrays were loaded.
No existing model/evaluation artifacts were overwritten.

Next: verify the exact fold-plan schema and alignment-audit status before approving any OOF training.

### 5.16.1.1 — Versioned Shared OOF Protocol Revision

The original shared five-fold plan and its associated integrity reports are retained as historical artifacts. The previous plan is not approved for fold-specific training because certain held-out classes have no remaining training support after the required exclusions.

This revision introduces a versioned protocol for designing a replacement shared OOF plan. RF and LSTM will use identical held-out observation IDs, target labels, fold IDs, and class order. Model-specific training eligibility will be recorded separately: RF training will apply held-out, purge, and duplicate-group exclusions, while LSTM training will additionally enforce the established length-10 sequence-window contract.

A replacement fold plan will be considered a candidate until coverage, training/held-out disjointness, duplicate exclusions, class support, and LSTM sequence compatibility have been validated. The existing final RF model, its evaluation results, and all prior fold-plan artifacts must remain unchanged.

In [ ]:

# ================================================================
# 5.16.1.1 — VERSIONED SHARED OOF PROTOCOL REVISION (FIXED)
# Manifest only. No model training or Validation/Test access.
# ================================================================

import json
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(
    "/content/drive/MyDrive/AI-Network-Intrusion-Detection-System"
)
EXP = ROOT / "outputs" / "ensemble_model_development" / "experiments"

historical_paths = {
    "original_fold_plan": EXP / "oof_fold_plan_v1.json",
    "alignment_audit": EXP / "oof_index_alignment_audit_v1.json",
    "preflight_v4": EXP / "oof_fold_integrity_preflight_v4.json",
    "candidate_v2": EXP / "oof_fold_plan_candidate_v2.json",
    "candidate_audit_v2": EXP / "oof_fold_candidate_audit_v2.json",
}

missing = [
    f"{name}: {path}"
    for name, path in historical_paths.items()
    if not path.is_file()
]
if missing:
    raise FileNotFoundError(
        "Required historical artifacts missing:\n- "
        + "\n- ".join(missing)
    )

with historical_paths["preflight_v4"].open("r", encoding="utf-8") as f:
    preflight = json.load(f)

with historical_paths["candidate_audit_v2"].open("r", encoding="utf-8") as f:
    candidate_audit = json.load(f)

# Validate the actual schema observed in the diagnostic.
assert preflight.get("status") == (
    "PASSED_STRUCTURAL_CHECKS_WITH_DUPLICATE_EXCLUSIONS"
), f"Unexpected historical preflight status: {preflight.get('status')}"

assert preflight.get("approved_for_model_training") is True, (
    "Historical structural preflight is not marked approved."
)

assert candidate_audit.get("status") == "BLOCKED_REVIEW_REQUIRED"
assert candidate_audit.get("approved_for_training") is False
assert candidate_audit.get("coverage_exactly_once") is True

manifest_path = EXP / "shared_oof_protocol_revision_v2.json"
if manifest_path.exists():
    raise FileExistsError(
        "Manifest already exists; it will not be overwritten:\n"
        f"{manifest_path}"
    )

manifest = {
    "protocol_id": "shared_oof_protocol_revision_v2",
    "created_utc": datetime.now(timezone.utc).isoformat(),
    "status": "REVISION_DEFINED_CANDIDATE_PLAN_NOT_YET_APPROVED",
    "approved_for_training": False,
    "partition": "N04 Training only",
    "expected_training_rows": 1814018,
    "feature_count": 32,
    "class_ids": list(range(9)),
    "sequence_length": 10,
    "sequence_target_assignment": "last observation",
    "fold_count_target": 5,
    "shared_contract": {
        "same_heldout_observation_ids_for_rf_and_lstm": True,
        "same_target_labels": True,
        "same_fold_ids": True,
        "class_probability_order": list(range(9)),
        "model_specific_training_eligibility": True,
    },
    "rf_training_controls": [
        "Exclude held-out target observations.",
        "Apply the approved RF fold exclusion policy.",
        "Exclude exact duplicate feature rows shared with held-out data.",
        "Apply verified RF-3 controlled oversampling to permitted training rows only.",
    ],
    "lstm_training_controls": [
        "Preserve sequence length 10, stride 1, and last-observation target.",
        "Validate sequence-window overlap with held-out observations.",
        "Apply duplicate-group exclusions.",
        "Do not claim chronological or session-independent validity without verified metadata.",
    ],
    "known_limitations": [
        "Heartbleed has 6 Training observations.",
        "Infiltration has 15 Training observations.",
        "Chronological order and session boundaries are unverified.",
        "The original v1 fold plan failed class-support checks.",
        "Candidate v2 failed class-support checks.",
    ],
    "historical_artifacts": {
        name: str(path) for name, path in historical_paths.items()
    },
    "historical_statuses": {
        "preflight_v4": preflight.get("status"),
        "preflight_v4_approved_for_model_training": (
            preflight.get("approved_for_model_training")
        ),
        "candidate_audit_v2": candidate_audit.get("status"),
        "candidate_audit_v2_approved_for_training": (
            candidate_audit.get("approved_for_training")
        ),
    },
    "next_step": (
        "Create and audit a new shared fold-plan candidate before RF training."
    ),
    "validation_test_accessed": False,
    "models_trained": False,
    "existing_final_rf_modified": False,
}

with manifest_path.open("x", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2)

print("=" * 72)
print("5.16.1.1 — VERSIONED SHARED OOF PROTOCOL REVISION")
print("=" * 72)
print("Historical preflight:", preflight["status"])
print("Historical candidate:", candidate_audit["status"])
print("New manifest status:", manifest["status"])
print("Approved for training:", manifest["approved_for_training"])
print("Manifest saved:", manifest_path)
print("Historical artifacts preserved:", len(historical_paths))
print("Validation/Test arrays accessed: NO")
print("Models trained: NO")
print("Existing final RF modified: NO")

========================================================================
5.16.1.1 — VERSIONED SHARED OOF PROTOCOL REVISION
========================================================================
Historical preflight: PASSED_STRUCTURAL_CHECKS_WITH_DUPLICATE_EXCLUSIONS
Historical candidate: BLOCKED_REVIEW_REQUIRED
New manifest status: REVISION_DEFINED_CANDIDATE_PLAN_NOT_YET_APPROVED
Approved for training: False
Manifest saved: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/experiments/shared_oof_protocol_revision_v2.json
Historical artifacts preserved: 5
Validation/Test arrays accessed: NO
Models trained: NO
Existing final RF modified: NO

### 5.16.1.2 — Shared Fold-Plan Candidate Generation

Generate a versioned candidate fold assignment using the frozen N04 Training labels. The candidate will assign each eligible observation to exactly one held-out fold and preserve the class order 0–8 and the LSTM's length-10, stride-1, last-observation target contract.

The candidate is not approved for training until the subsequent integrity preflight validates fold coverage, class support, duplicate-feature exclusions, target alignment, and LSTM sequence compatibility. The original fold plan and all historical diagnostic artifacts remain unchanged. No model fitting or Validation/Test access is permitted in this subsection.

#### 5.16.2 — Fold Integrity and Leakage Preflight

Validate the shared five-fold plan against the persisted N04 Training data. Confirm that held-out target rows are covered exactly once, fold training and held-out target sets are disjoint, purge regions protect the LSTM's length-10 input windows, and exact duplicate feature rows do not cross training/held-out boundaries. Verify class-label alignment and persist the integrity report. No model fitting or Validation/Test access is permitted in this subsection.

In [ ]:

# ================================================================
# 5.16.1.2 — SHARED FOLD-PLAN CANDIDATE GENERATION
# Training labels only; no model fitting.
# ================================================================

import json
import numpy as np
from pathlib import Path
from datetime import datetime, timezone
from sklearn.model_selection import StratifiedKFold

ROOT = Path(
    "/content/drive/MyDrive/AI-Network-Intrusion-Detection-System"
)
N04 = ROOT / "outputs/model_preparation_v2"
EXP = ROOT / "outputs/ensemble_model_development/experiments"

y_path = N04 / "model_ready_targets/y_train.npy"
protocol_path = EXP / "shared_oof_protocol_revision_v2.json"
output_path = EXP / "oof_fold_plan_candidate_v3.json"

assert y_path.is_file(), f"Missing N04 Training labels: {y_path}"
assert protocol_path.is_file(), f"Missing protocol manifest: {protocol_path}"

if output_path.exists():
    raise FileExistsError(
        "Candidate v3 already exists. Do not overwrite it:\n"
        f"{output_path}"
    )

with protocol_path.open("r", encoding="utf-8") as f:
    protocol = json.load(f)

assert protocol["protocol_id"] == "shared_oof_protocol_revision_v2"
assert protocol["approved_for_training"] is False

y_memmap = np.load(y_path, mmap_mode="r", allow_pickle=False)
y = np.asarray(y_memmap, dtype=np.int64)

EXPECTED_ROWS = int(protocol["expected_training_rows"])
SEQUENCE_LENGTH = int(protocol["sequence_length"])
N_SPLITS = int(protocol["fold_count_target"])
SEED = 42

assert y.shape == (EXPECTED_ROWS,), (
    f"Unexpected Training target shape: {y.shape}"
)
assert set(np.unique(y)) == set(range(9)), (
    f"Unexpected class IDs: {np.unique(y).tolist()}"
)

# LSTM targets begin at raw row L-1 because the first L-1 rows
# cannot form a complete length-L input window.
eligible = np.arange(SEQUENCE_LENGTH - 1, len(y), dtype=np.int64)
eligible_y = y[eligible]

class_counts = np.bincount(eligible_y, minlength=9)
if np.any(class_counts < N_SPLITS):
    low = {
        int(c): int(class_counts[c])
        for c in np.flatnonzero(class_counts < N_SPLITS)
    }
    raise RuntimeError(
        "Cannot stratify into five folds: class support below fold count: "
        f"{low}"
    )

splitter = StratifiedKFold(
    n_splits=N_SPLITS,
    shuffle=True,
    random_state=SEED,
)

fold_id_by_raw_row = np.full(len(y), -1, dtype=np.int8)
fold_records = []

for fold_id, (_, held_positions) in enumerate(
    splitter.split(eligible, eligible_y)
):
    held_rows = eligible[held_positions]
    fold_id_by_raw_row[held_rows] = fold_id

    held_counts = np.bincount(y[held_rows], minlength=9)

    fold_records.append({
        "fold_id": int(fold_id),
        "heldout_target_count": int(len(held_rows)),
        "heldout_class_counts": held_counts.tolist(),
    })

# Coverage: every eligible target exactly once; first L-1 rows never targets.
coverage = np.bincount(
    fold_id_by_raw_row[eligible].astype(np.int64),
    minlength=N_SPLITS,
)
assert np.all(coverage > 0)
assert np.all(fold_id_by_raw_row[eligible] >= 0)
assert np.all(fold_id_by_raw_row[:SEQUENCE_LENGTH - 1] == -1)

candidate = {
    "candidate_id": "oof_fold_plan_candidate_v3",
    "created_utc": datetime.now(timezone.utc).isoformat(),
    "status": "CANDIDATE_ASSIGNMENT_ONLY_NOT_APPROVED",
    "approved_for_training": False,
    "partition_used": "Training only",
    "training_rows": int(len(y)),
    "feature_count": int(protocol["feature_count"]),
    "class_ids": list(range(9)),
    "fold_count": N_SPLITS,
    "sequence_length": SEQUENCE_LENGTH,
    "target_assignment": "last observation",
    "eligible_target_start": SEQUENCE_LENGTH - 1,
    "eligible_sequence_targets": int(len(eligible)),
    "heldout_targets_covered_once": True,
    "fold_id_by_raw_row": fold_id_by_raw_row.tolist(),
    "folds": fold_records,
    "limitations": [
        "Candidate assignment only; not approved for training.",
        "Per-model training indices have not yet been validated.",
        "Exact duplicate-feature exclusions have not yet been applied.",
        "LSTM sequence-window compatibility has not yet been approved.",
        "Chronological order and session boundaries are unverified.",
        "Heartbleed has only six Training observations.",
        "Infiltration has only fifteen Training observations."
    ]
}

with output_path.open("x", encoding="utf-8") as f:
    json.dump(candidate, f, indent=2)

print("=" * 72)
print("5.16.1.2 — SHARED FOLD-PLAN CANDIDATE")
print("=" * 72)
print("Status:", candidate["status"])
print("Approved for training:", candidate["approved_for_training"])
print("Eligible targets:", len(eligible))
print("Fold count:", N_SPLITS)
for record in fold_records:
    print(
        f"Fold {record['fold_id']}: "
        f"held-out={record['heldout_target_count']:,}; "
        f"class counts={record['heldout_class_counts']}"
    )
print("Candidate saved:", output_path)
print("Validation/Test accessed: NO")
print("Models trained: NO")

========================================================================
5.16.1.2 — SHARED FOLD-PLAN CANDIDATE
========================================================================
Status: CANDIDATE_ASSIGNMENT_ONLY_NOT_APPROVED
Approved for training: False
Eligible targets: 1814009
Fold count: 5
Fold 0: held-out=362,802; class counts=[289638, 16393, 20345, 1865, 254, 278, 3, 34025, 1]
Fold 1: held-out=362,802; class counts=[289638, 16394, 20344, 1865, 254, 278, 3, 34025, 1]
Fold 2: held-out=362,802; class counts=[289638, 16394, 20344, 1865, 254, 278, 3, 34025, 1]
Fold 3: held-out=362,802; class counts=[289637, 16394, 20345, 1865, 254, 277, 3, 34025, 2]
Fold 4: held-out=362,801; class counts=[289637, 16393, 20345, 1865, 254, 278, 3, 34025, 1]
Candidate saved: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/experiments/oof_fold_plan_candidate_v3.json
Validation/Test accessed: NO
Models trained: NO

### 5.16.2 — Fold Integrity and Leakage Preflight (Candidate v3)

Validate the versioned shared fold candidate against the frozen N04 Training features and targets. Confirm exact-once held-out coverage, target-label alignment, valid class IDs, duplicate-feature exclusions, and fold-specific training support.

RF training eligibility and LSTM sequence eligibility are evaluated separately. For LSTM, a training sequence is eligible only when its target is not held out and none of its input rows belongs to the current held-out fold. This conservative rule prevents a held-out observation from appearing in a training sequence window.

This subsection does not fit models or access Validation/Test. The candidate remains unapproved unless both model-specific training contracts and all required leakage checks pass. Chronological and session independence remain unverified.

In [ ]:

# ================================================================
# 5.16.2 — FOLD INTEGRITY AND LEAKAGE PREFLIGHT (CANDIDATE V3)
# Training-only. No fitting; no Validation/Test access.
# Writes new versioned report/exclusion artifacts only.
# ================================================================

import json
import hashlib
from pathlib import Path
from datetime import datetime, timezone
import numpy as np

ROOT = Path(
    "/content/drive/MyDrive/AI-Network-Intrusion-Detection-System"
)
N04 = ROOT / "outputs/model_preparation_v2"
EXP = ROOT / "outputs/ensemble_model_development/experiments"

X_PATH = N04 / "feature_scaling/X_train_scaled.npy"
Y_PATH = N04 / "model_ready_targets/y_train.npy"
PLAN_PATH = EXP / "oof_fold_plan_candidate_v3.json"
PROTOCOL_PATH = EXP / "shared_oof_protocol_revision_v2.json"
ALIGNMENT_PATH = EXP / "oof_index_alignment_audit_v1.json"

REPORT_PATH = EXP / "oof_fold_integrity_preflight_v5.json"
EXCLUSION_PATH = EXP / "oof_fold_duplicate_training_exclusions_v4.npz"

required = [X_PATH, Y_PATH, PLAN_PATH, PROTOCOL_PATH, ALIGNMENT_PATH]
missing = [str(p) for p in required if not p.is_file()]
if missing:
    raise FileNotFoundError(
        "Required artifacts are missing:\n- " + "\n- ".join(missing)
    )

if REPORT_PATH.exists() or EXCLUSION_PATH.exists():
    raise FileExistsError(
        "A v5 preflight artifact already exists. Preserve it and inspect "
        "before creating another version:\n"
        f"{REPORT_PATH}\n{EXCLUSION_PATH}"
    )

with PLAN_PATH.open("r", encoding="utf-8") as f:
    plan = json.load(f)
with PROTOCOL_PATH.open("r", encoding="utf-8") as f:
    protocol = json.load(f)
with ALIGNMENT_PATH.open("r", encoding="utf-8") as f:
    alignment = json.load(f)

X = np.load(X_PATH, mmap_mode="r", allow_pickle=False)
y = np.load(Y_PATH, mmap_mode="r", allow_pickle=False)

N, D = X.shape
L = int(plan.get("sequence_length", -1))
OFFSET = L - 1
N_FOLDS = int(plan.get("fold_count", -1))
CLASS_IDS = list(range(9))

checks = {}
issues = []

def check(name, passed, detail):
    checks[name] = {"passed": bool(passed), "detail": str(detail)}
    print(f"[{'PASS' if passed else 'BLOCK'}] {name}: {detail}")
    if not passed:
        issues.append(name)

print("=" * 76)
print("5.16.2 — FOLD INTEGRITY AND LEAKAGE PREFLIGHT (CANDIDATE V3)")
print("=" * 76)

# ---- Frozen input and protocol contract ----
check("Training feature shape", X.shape == (1_814_018, 32), f"{X.shape}")
check("Training target shape", y.shape == (N,), f"{y.shape}")
check("Finite Training features", bool(np.isfinite(X).all()), "All X_train values finite")
check("Class IDs", np.unique(y).astype(int).tolist() == CLASS_IDS,
      f"{np.unique(y).astype(int).tolist()}")
check("Training-only candidate",
      plan.get("partition_used") == "Training only",
      str(plan.get("partition_used")))
check("Protocol identity",
      protocol.get("protocol_id") == "shared_oof_protocol_revision_v2",
      str(protocol.get("protocol_id")))
check("Candidate identity",
      plan.get("candidate_id") == "oof_fold_plan_candidate_v3",
      str(plan.get("candidate_id")))
check("Sequence length", L == 10, f"L={L}")
check("Five folds", N_FOLDS == 5 and len(plan.get("folds", [])) == 5,
      f"fold_count={N_FOLDS}; records={len(plan.get('folds', []))}")
check("Sequence target alignment",
      alignment.get("all_sequence_labels_match_last_observation") is True,
      str(alignment.get("all_sequence_labels_match_last_observation")))

# ---- Read the candidate's actual assignment array ----
fold_assignment = np.asarray(
    plan.get("fold_id_by_raw_row", []), dtype=np.int16
)
assignment_ok = (
    fold_assignment.shape == (N,)
    and np.all(fold_assignment[:OFFSET] == -1)
    and np.all(np.isin(fold_assignment[OFFSET:], np.arange(N_FOLDS)))
)
check("Assignment array shape and values", assignment_ok,
      f"shape={fold_assignment.shape}; expected={(N,)}")

if not assignment_ok:
    raise RuntimeError(
        "Candidate assignment array is incompatible with N04 Training rows. "
        "No report or exclusion artifact was written."
    )

eligible_rows = np.arange(OFFSET, N, dtype=np.int64)
coverage_ok = np.all(np.bincount(
    fold_assignment[eligible_rows], minlength=N_FOLDS
) > 0)
check("Every fold has held-out targets", coverage_ok,
      f"fold counts={np.bincount(fold_assignment[eligible_rows], minlength=N_FOLDS).tolist()}")

fold_records = {
    int(record["fold_id"]): record
    for record in plan.get("folds", [])
}
manifest_consistent = set(fold_records) == set(range(N_FOLDS))
manifest_details = []

for fid in range(N_FOLDS):
    held = eligible_rows[fold_assignment[eligible_rows] == fid]
    actual_counts = np.bincount(np.asarray(y[held], dtype=np.int64), minlength=9)
    rec = fold_records.get(fid, {})
    count_match = len(held) == int(rec.get("heldout_target_count", -1))
    declared = rec.get("heldout_class_counts")
    class_match = (
        isinstance(declared, list)
        and [int(v) for v in declared] == actual_counts.tolist()
    )
    manifest_consistent &= count_match and class_match
    manifest_details.append({
        "fold_id": fid,
        "heldout_count": int(len(held)),
        "heldout_class_counts": actual_counts.tolist(),
        "manifest_count_matches": bool(count_match),
        "manifest_class_counts_match": bool(class_match),
    })
    print(
        f"\nFold {fid}: held-out={len(held):,}; "
        f"class counts={actual_counts.tolist()}; "
        f"manifest match={count_match and class_match}"
    )

check("Fold records match assignment array", manifest_consistent,
      "Counts and class counts recomputed directly from y_train")

# ---- Exact duplicate feature exclusion ----
# For each fold, exclude all non-held-out eligible targets whose exact
# scaled feature row occurs in that fold's held-out set. Label conflicts
# are reported; they are never silently resolved.
print("\n[EXACT DUPLICATE FEATURE AUDIT]")
CHUNK = 50_000
exclusion_arrays = {}
duplicate_summary = []
duplicate_audit_ok = True

def row_fingerprint(row):
    return hashlib.blake2b(
        np.ascontiguousarray(row).tobytes(), digest_size=16
    ).digest()

for fid in range(N_FOLDS):
    held = eligible_rows[fold_assignment[eligible_rows] == fid]
    held_hashes = {}
    for start in range(0, len(held), CHUNK):
        ids = held[start:start + CHUNK]
        for idx in ids:
            h = row_fingerprint(X[int(idx)])
            held_hashes.setdefault(h, []).append(int(idx))

    # Include every eligible row outside this fold's held-out set as
    # a candidate; model-specific eligibility is applied below.
    candidate_rows = eligible_rows[fold_assignment[eligible_rows] != fid]
    excluded = []
    label_conflict_rows = 0
    matching_rows = 0

    for start in range(0, len(candidate_rows), CHUNK):
        ids = candidate_rows[start:start + CHUNK]
        for idx in ids:
            h = row_fingerprint(X[int(idx)])
            matched_held = held_hashes.get(h)
            if matched_held:
                excluded.append(int(idx))
                matching_rows += 1
                if any(int(y[int(idx)]) != int(y[hidx]) for hidx in matched_held):
                    label_conflict_rows += 1

    exclusion_arrays[f"fold_{fid}_duplicate_excluded_indices"] = (
        np.asarray(sorted(set(excluded)), dtype=np.int64)
    )
    duplicate_summary.append({
        "fold_id": fid,
        "matching_candidate_rows_excluded": int(len(set(excluded))),
        "label_conflict_or_ambiguous_candidate_rows": int(label_conflict_rows),
        "duplicate_exclusion_count": int(len(set(excluded))),
    })
    print(
        f"Fold {fid}: excluded={len(set(excluded)):,}; "
        f"label-conflict/ambiguous rows={label_conflict_rows:,}"
    )

# ---- RF and LSTM training support, evaluated separately ----
print("\n[MODEL-SPECIFIC TRAINING SUPPORT]")
rf_fold_results = []
lstm_fold_results = []
rf_support_ok = True
lstm_support_ok = True

for fid in range(N_FOLDS):
    held_mask = fold_assignment == fid
    held = eligible_rows[held_mask[eligible_rows]]
    duplicate_excluded = exclusion_arrays[
        f"fold_{fid}_duplicate_excluded_indices"
    ]

    # RF is row-wise: its permitted training rows are eligible targets
    # outside the held-out fold, less exact duplicate feature matches.
    rf_train_mask = np.zeros(N, dtype=bool)
    rf_train_mask[eligible_rows] = fold_assignment[eligible_rows] != fid
    rf_train_mask[duplicate_excluded] = False
    rf_train = np.flatnonzero(rf_train_mask)

    rf_counts = np.bincount(np.asarray(y[rf_train], dtype=np.int64), minlength=9)
    held_counts = np.bincount(np.asarray(y[held], dtype=np.int64), minlength=9)
    held_classes = np.flatnonzero(held_counts)
    rf_missing = [int(c) for c in held_classes if rf_counts[c] == 0]
    rf_pass = len(rf_missing) == 0
    rf_support_ok &= rf_pass

    rf_fold_results.append({
        "fold_id": fid,
        "training_count_before_oversampling": int(len(rf_train)),
        "training_class_counts_before_oversampling": rf_counts.tolist(),
        "heldout_class_counts": held_counts.tolist(),
        "heldout_classes_missing_from_training": rf_missing,
        "support_passed": bool(rf_pass),
    })

    # LSTM: a training target t is permitted only if t is not held out
    # and none of its input rows [t-L+1, ..., t] is held out for this fold.
    # This is deliberately conservative and may expose infeasibility.
    lstm_train_targets = []
    for t in eligible_rows:
        if fold_assignment[t] == fid:
            continue
        window_start = int(t) - OFFSET
        if np.any(fold_assignment[window_start:int(t) + 1] == fid):
            continue
        lstm_train_targets.append(int(t))

    lstm_train_targets = np.asarray(lstm_train_targets, dtype=np.int64)
    lstm_train_counts = np.bincount(
        np.asarray(y[lstm_train_targets], dtype=np.int64), minlength=9
    )
    lstm_missing = [
        int(c) for c in held_classes if lstm_train_counts[c] == 0
    ]
    lstm_pass = len(lstm_missing) == 0 and len(lstm_train_targets) > 0
    lstm_support_ok &= lstm_pass

    lstm_fold_results.append({
        "fold_id": fid,
        "training_sequence_target_count": int(len(lstm_train_targets)),
        "training_class_counts_before_oversampling": lstm_train_counts.tolist(),
        "heldout_class_counts": held_counts.tolist(),
        "heldout_classes_missing_from_training": lstm_missing,
        "support_passed": bool(lstm_pass),
    })

    print(
        f"Fold {fid}: RF rows={len(rf_train):,}, RF missing held-out classes={rf_missing}; "
        f"LSTM sequence targets={len(lstm_train_targets):,}, "
        f"LSTM missing held-out classes={lstm_missing}"
    )

check("RF class support", rf_support_ok,
      "Every class present in each held-out fold occurs in RF training before oversampling")
check("LSTM class support under window exclusion", lstm_support_ok,
      "Every class present in each held-out fold occurs in eligible LSTM training targets")

# Exact coverage and fold disjointness are established by the assignment array.
coverage_exactly_once = (
    np.all(fold_assignment[eligible_rows] >= 0)
    and np.all(fold_assignment[:OFFSET] == -1)
)
check("Eligible target coverage exactly once", coverage_exactly_once,
      f"eligible={len(eligible_rows):,}; unassigned eligible targets=0")

# The protocol cannot be approved if either model's required training
# support or any structural/data-contract check fails.
structural_checks_pass = all(
    item["passed"] for item in checks.values()
)
approved = bool(structural_checks_pass and duplicate_audit_ok
                and rf_support_ok and lstm_support_ok)

status = (
    "PASSED_AND_APPROVED_FOR_TRAINING"
    if approved else
    "BLOCKED_REVIEW_REQUIRED"
)

report = {
    "report_id": "oof_fold_integrity_preflight_v5",
    "created_utc": datetime.now(timezone.utc).isoformat(),
    "candidate_plan": str(PLAN_PATH),
    "status": status,
    "approved_for_model_training": approved,
    "partition_used": "Training only",
    "training_rows": int(N),
    "feature_count": int(D),
    "class_ids": CLASS_IDS,
    "sequence_length": int(L),
    "fold_count": int(N_FOLDS),
    "checks": checks,
    "issues": issues,
    "fold_manifest_checks": manifest_details,
    "duplicate_feature_audit": duplicate_summary,
    "duplicate_exclusion_artifact": str(EXCLUSION_PATH),
    "rf_fold_support": rf_fold_results,
    "lstm_fold_support": lstm_fold_results,
    "eligible_targets_covered_exactly_once": bool(coverage_exactly_once),
    "validation_accessed": False,
    "test_accessed": False,
    "models_trained": False,
    "existing_final_rf_modified": False,
    "temporal_order_verified": False,
    "session_boundaries_verified": False,
    "limitations": [
        "Candidate v3 uses stratified random folds, not verified chronological/session folds.",
        "Heartbleed has only six Training observations.",
        "Infiltration has only fifteen Training observations.",
        "Training support is assessed before RF-3 oversampling.",
        "RF and LSTM use separate permitted training sets under their input contracts.",
    ],
}

# Write the exclusion artifact and report exclusively; never overwrite.
with EXCLUSION_PATH.open("xb") as f:
    np.savez_compressed(f, **exclusion_arrays)

with REPORT_PATH.open("x", encoding="utf-8") as f:
    json.dump(report, f, indent=2)

print("\n" + "=" * 76)
print("5.16.2 RESULT")
print("=" * 76)
print("Status:", status)
print("Approved for training:", approved)
print("Report saved:", REPORT_PATH)
print("Duplicate exclusions saved:", EXCLUSION_PATH)
print("Validation/Test arrays accessed: NO")
print("Models trained: NO")
print("Existing final RF modified: NO")
print("Temporal/session validity established: NO")

============================================================================
5.16.2 — FOLD INTEGRITY AND LEAKAGE PREFLIGHT (CANDIDATE V3)
============================================================================
[PASS] Training feature shape: (1814018, 32)
[PASS] Training target shape: (1814018,)
[PASS] Finite Training features: All X_train values finite
[PASS] Class IDs: [0, 1, 2, 3, 4, 5, 6, 7, 8]
[PASS] Training-only candidate: Training only
[PASS] Protocol identity: shared_oof_protocol_revision_v2
[PASS] Candidate identity: oof_fold_plan_candidate_v3
[PASS] Sequence length: L=10
[PASS] Five folds: fold_count=5; records=5
[PASS] Sequence target alignment: True
[PASS] Assignment array shape and values: shape=(1814018,); expected=(1814018,)
[PASS] Every fold has held-out targets: fold counts=[362802, 362802, 362802, 362802, 362801]

Fold 0: held-out=362,802; class counts=[289638, 16393, 20345, 1865, 254, 278, 3, 34025, 1]; manifest match=True

Fold 1: held-out=362,802; class counts=[289638, 16394, 20344, 1865, 254, 278, 3, 34025, 1]; manifest match=True

Fold 2: held-out=362,802; class counts=[289638, 16394, 20344, 1865, 254, 278, 3, 34025, 1]; manifest match=True

Fold 3: held-out=362,802; class counts=[289637, 16394, 20345, 1865, 254, 277, 3, 34025, 2]; manifest match=True

Fold 4: held-out=362,801; class counts=[289637, 16393, 20345, 1865, 254, 278, 3, 34025, 1]; manifest match=True
[PASS] Fold records match assignment array: Counts and class counts recomputed directly from y_train

[EXACT DUPLICATE FEATURE AUDIT]
Fold 0: excluded=157,022; label-conflict/ambiguous rows=33,102
Fold 1: excluded=157,378; label-conflict/ambiguous rows=33,614
Fold 2: excluded=157,163; label-conflict/ambiguous rows=33,768
Fold 3: excluded=156,172; label-conflict/ambiguous rows=33,558
Fold 4: excluded=157,281; label-conflict/ambiguous rows=33,509

[MODEL-SPECIFIC TRAINING SUPPORT]
Fold 0: RF rows=1,294,185, RF missing held-out classes=[]; LSTM sequence targets=195,653, LSTM missing held-out classes=[]
Fold 1: RF rows=1,293,829, RF missing held-out classes=[]; LSTM sequence targets=194,998, LSTM missing held-out classes=[8]
Fold 2: RF rows=1,294,044, RF missing held-out classes=[]; LSTM sequence targets=195,537, LSTM missing held-out classes=[8]
Fold 3: RF rows=1,295,035, RF missing held-out classes=[]; LSTM sequence targets=194,801, LSTM missing held-out classes=[]
Fold 4: RF rows=1,293,927, RF missing held-out classes=[]; LSTM sequence targets=194,849, LSTM missing held-out classes=[8]
[PASS] RF class support: Every class present in each held-out fold occurs in RF training before oversampling
[BLOCK] LSTM class support under window exclusion: Every class present in each held-out fold occurs in eligible LSTM training targets
[PASS] Eligible target coverage exactly once: eligible=1,814,009; unassigned eligible targets=0

============================================================================
5.16.2 RESULT
============================================================================
Status: BLOCKED_REVIEW_REQUIRED
Approved for training: False
Report saved: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/experiments/oof_fold_integrity_preflight_v5.json
Duplicate exclusions saved: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/experiments/oof_fold_duplicate_training_exclusions_v4.npz
Validation/Test arrays accessed: NO
Models trained: NO
Existing final RF modified: NO
Temporal/session validity established: NO

### 5.16.3 — RF-3 Fold-Specific Training

Train five independent Random Forest models using the candidate v3 held-out assignments and the RF-specific readiness evidence. Each model is fitted only on its permitted Training observations, after excluding the corresponding held-out rows and exact duplicate feature rows identified by the preflight.

Apply the established RF-3 controlled random-oversampling policy separately within each fold's training data: minimum support of 10, a maximum 5× target, a cap of 50,000 observations per class, no majority-class downsampling, no synthetic sampling, and no Heartbleed oversampling. The Infiltration class remains eligible for oversampling.

Persist each fold model, its sampling counts, configuration, training provenance, and class order in a dedicated ensemble-preparation directory. The existing final RF model and its evaluation artifacts remain unchanged. This subsection does not access Validation/Test or generate OOF predictions.

In [ ]:

# ================================================================
# 5.16.3 — RF-3 FOLD-SPECIFIC TRAINING
# RF-only readiness gate. Training partition only.
# Existing final RF model and evaluation artifacts are untouched.
# ================================================================

import gc
import json
import time
import hashlib
from pathlib import Path
from datetime import datetime, timezone

import joblib
import numpy as np
from sklearn.ensemble import RandomForestClassifier

ROOT = Path(
    "/content/drive/MyDrive/AI-Network-Intrusion-Detection-System"
)
N04 = ROOT / "outputs/model_preparation_v2"
EXP = ROOT / "outputs/ensemble_model_development/experiments"

X_PATH = N04 / "feature_scaling/X_train_scaled.npy"
Y_PATH = N04 / "model_ready_targets/y_train.npy"
PLAN_PATH = EXP / "oof_fold_plan_candidate_v3.json"
PREFLIGHT_PATH = EXP / "oof_fold_integrity_preflight_v5.json"
EXCLUSION_PATH = EXP / "oof_fold_duplicate_training_exclusions_v4.npz"

OUT_DIR = (
    ROOT / "outputs/ensemble_model_development"
    / "rf_fold_models_v1"
)
MODEL_DIR = OUT_DIR / "models"
META_DIR = OUT_DIR / "provenance"
MANIFEST_PATH = OUT_DIR / "rf_fold_training_manifest_v1.json"

# Frozen RF-3 configuration from N05 Section 5.11.3.
N_ESTIMATORS = 100
MAX_FEATURES = "sqrt"
MAX_DEPTH = None
BOOTSTRAP = True
N_JOBS = -1
RANDOM_SEED = 42

MIN_SUPPORT = 10
OVERSAMPLING_MULTIPLIER = 5
MAX_TARGET_PER_CLASS = 50_000
HEARTBLEED_CLASS_ID = 8
CLASS_IDS = list(range(9))
SEQUENCE_LENGTH = 10

# ---------- Fail-closed input checks ----------
for path in [
    X_PATH, Y_PATH, PLAN_PATH, PREFLIGHT_PATH, EXCLUSION_PATH
]:
    if not path.is_file():
        raise FileNotFoundError(f"Required artifact missing: {path}")

if MANIFEST_PATH.exists():
    raise FileExistsError(
        f"Training manifest already exists; refusing to overwrite: {MANIFEST_PATH}"
    )

with PLAN_PATH.open("r", encoding="utf-8") as f:
    plan = json.load(f)
with PREFLIGHT_PATH.open("r", encoding="utf-8") as f:
    preflight = json.load(f)

assert plan.get("candidate_id") == "oof_fold_plan_candidate_v3"
assert plan.get("partition_used") == "Training only"
assert plan.get("fold_count") == 5
assert plan.get("sequence_length") == SEQUENCE_LENGTH
assert preflight.get("validation_accessed") is False
assert preflight.get("test_accessed") is False
assert preflight.get("models_trained") is False

# The joint gate can remain blocked because of LSTM.
# Require the actual RF-specific support audit to pass every fold.
rf_support = preflight.get("rf_fold_support", [])
assert len(rf_support) == 5, (
    "Preflight does not contain five RF support records."
)
assert all(item.get("support_passed") is True for item in rf_support), (
    "RF-specific class support did not pass for every fold. "
    "Do not train until the RF support records are reconciled."
)

X = np.load(X_PATH, mmap_mode="r", allow_pickle=False)
y = np.load(Y_PATH, mmap_mode="r", allow_pickle=False)

n_rows, n_features = X.shape
assert y.shape == (n_rows,)
assert n_rows == int(plan["training_rows"])
assert n_features == int(plan["feature_count"])
assert np.unique(y).astype(int).tolist() == CLASS_IDS
assert np.isfinite(X).all()

fold_assignment = np.asarray(
    plan["fold_id_by_raw_row"], dtype=np.int16
)
assert fold_assignment.shape == (n_rows,)

eligible_rows = np.arange(SEQUENCE_LENGTH - 1, n_rows, dtype=np.int64)
assert np.all(fold_assignment[:SEQUENCE_LENGTH - 1] == -1)
assert np.all(np.isin(fold_assignment[eligible_rows], range(5)))

# Keep all outputs separate from the authoritative final RF directory.
MODEL_DIR.mkdir(parents=True, exist_ok=False)
META_DIR.mkdir(parents=True, exist_ok=False)

print("=" * 76)
print("5.16.3 — RF-3 FOLD-SPECIFIC TRAINING")
print("=" * 76)
print("Candidate:", PLAN_PATH.name)
print("RF-specific support gate: PASS")
print("Rows:", n_rows, "| Features:", n_features)
print("Folds:", plan["fold_count"])
print("Model output directory:", MODEL_DIR)
print("Validation/Test arrays accessed: NO")
print("Existing final RF model will be modified: NO")

manifest = {
    "manifest_id": "rf_fold_training_manifest_v1",
    "created_utc": datetime.now(timezone.utc).isoformat(),
    "status": "IN_PROGRESS",
    "training_partition": "N04 Training only",
    "candidate_plan": str(PLAN_PATH),
    "preflight_report": str(PREFLIGHT_PATH),
    "duplicate_exclusion_artifact": str(EXCLUSION_PATH),
    "output_directory": str(OUT_DIR),
    "class_ids": CLASS_IDS,
    "feature_count": int(n_features),
    "fold_count": 5,
    "rf_configuration": {
        "strategy_id": "RF-3",
        "strategy_name": "Controlled Random Oversampling",
        "n_estimators": N_ESTIMATORS,
        "max_features": MAX_FEATURES,
        "max_depth": MAX_DEPTH,
        "bootstrap": BOOTSTRAP,
        "n_jobs": N_JOBS,
        "class_weight": None,
        "synthetic_sampling": False,
        "random_seed_base": RANDOM_SEED,
    },
    "sampling_policy": {
        "minimum_training_support": MIN_SUPPORT,
        "oversampling_multiplier": OVERSAMPLING_MULTIPLIER,
        "maximum_target_per_class": MAX_TARGET_PER_CLASS,
        "majority_downsampling": False,
        "heartbleed_oversampling": False,
        "infiltration_oversampling_eligible": True,
    },
    "folds": [],
    "validation_accessed": False,
    "test_accessed": False,
    "existing_final_rf_modified": False,
}

try:
    with np.load(EXCLUSION_PATH, allow_pickle=False) as exclusions:
        for fold_id in range(5):
            print("\n" + "-" * 72)
            print(f"FOLD {fold_id} — PREPARE, RESAMPLE, FIT, SAVE")
            print("-" * 72)

            held = eligible_rows[
                fold_assignment[eligible_rows] == fold_id
            ]
            assert held.size > 0

            # Start with eligible targets not assigned to this held-out fold.
            train_mask = np.zeros(n_rows, dtype=bool)
            train_mask[eligible_rows] = (
                fold_assignment[eligible_rows] != fold_id
            )

            # Exclude exact duplicate feature rows across this fold boundary.
            exclusion_key = (
                f"fold_{fold_id}_duplicate_excluded_indices"
            )
            assert exclusion_key in exclusions.files, (
                f"Missing duplicate exclusions for fold {fold_id}"
            )
            duplicate_indices = np.asarray(
                exclusions[exclusion_key], dtype=np.int64
            )
            assert np.all((duplicate_indices >= 0) & (duplicate_indices < n_rows))
            train_mask[duplicate_indices] = False

            train_indices = np.flatnonzero(train_mask)
            y_train_natural = np.asarray(y[train_indices], dtype=np.int64)

            natural_counts = np.bincount(
                y_train_natural, minlength=9
            )
            held_counts = np.bincount(
                np.asarray(y[held], dtype=np.int64), minlength=9
            )

            # All nine classes must be represented for a nine-column
            # OOF probability matrix without fabricated missing-class outputs.
            absent_classes = np.flatnonzero(natural_counts == 0).tolist()
            if absent_classes:
                raise RuntimeError(
                    f"Fold {fold_id} cannot produce a complete nine-class "
                    f"RF model. Missing training classes: {absent_classes}"
                )

            # RF-3 controlled random oversampling, reproduced from N05.
            target_counts = {}
            for class_id, count in enumerate(natural_counts.tolist()):
                if count < MIN_SUPPORT or class_id == HEARTBLEED_CLASS_ID:
                    target = count
                else:
                    target = max(
                        count,
                        min(
                            count * OVERSAMPLING_MULTIPLIER,
                            MAX_TARGET_PER_CLASS,
                        ),
                    )
                assert target >= count
                target_counts[class_id] = int(target)

            rng = np.random.default_rng(RANDOM_SEED + fold_id)
            extra_parts = []
            added_counts = {}

            for class_id in CLASS_IDS:
                extra_n = target_counts[class_id] - int(natural_counts[class_id])
                added_counts[class_id] = int(extra_n)
                if extra_n == 0:
                    continue

                class_indices = train_indices[y_train_natural == class_id]
                assert class_indices.size > 0
                sampled = rng.choice(
                    class_indices, size=extra_n, replace=True
                )
                extra_parts.append(sampled.astype(np.int64, copy=False))

            if extra_parts:
                sampled_indices = np.concatenate(extra_parts)
                fit_indices = np.concatenate([train_indices, sampled_indices])
            else:
                fit_indices = train_indices.copy()

            # Shuffle after appending sampled observations, deterministically.
            rng.shuffle(fit_indices)
            X_fit = np.asarray(X[fit_indices], dtype=np.float32)
            y_fit = np.asarray(y[fit_indices], dtype=np.int64)

            fit_counts = np.bincount(y_fit, minlength=9)
            expected_counts = np.array(
                [target_counts[c] for c in CLASS_IDS], dtype=np.int64
            )
            assert np.array_equal(fit_counts, expected_counts), (
                f"Fold {fold_id} sampling counts do not match policy."
            )
            assert np.all(fit_counts >= natural_counts)

            print("Held-out rows:", f"{len(held):,}")
            print("Natural training rows:", f"{len(train_indices):,}")
            print("Duplicate rows excluded:", f"{len(duplicate_indices):,}")
            print("Natural class counts:", natural_counts.tolist())
            print("Added by class:", [added_counts[c] for c in CLASS_IDS])
            print("Resampled class counts:", fit_counts.tolist())
            print("Fitting RandomForestClassifier (100 trees)...")

            model = RandomForestClassifier(
                n_estimators=N_ESTIMATORS,
                max_features=MAX_FEATURES,
                max_depth=MAX_DEPTH,
                bootstrap=BOOTSTRAP,
                n_jobs=N_JOBS,
                class_weight=None,
                random_state=RANDOM_SEED + fold_id,
            )

            started = time.time()
            model.fit(X_fit, y_fit)
            elapsed = time.time() - started

            assert np.asarray(model.classes_, dtype=np.int64).tolist() == CLASS_IDS
            assert model.n_features_in_ == n_features

            model_path = MODEL_DIR / f"rf3_fold_{fold_id}.joblib"
            meta_path = META_DIR / f"rf3_fold_{fold_id}_metadata.json"

            if model_path.exists() or meta_path.exists():
                raise FileExistsError(
                    f"Refusing to overwrite fold {fold_id} outputs."
                )

            joblib.dump(model, model_path, compress=3)

            # Hash the saved model for provenance.
            digest = hashlib.sha256()
            with model_path.open("rb") as model_file:
                for block in iter(lambda: model_file.read(1024 * 1024), b""):
                    digest.update(block)

            fold_meta = {
                "fold_id": fold_id,
                "status": "TRAINED",
                "created_utc": datetime.now(timezone.utc).isoformat(),
                "model_path": str(model_path),
                "model_sha256": digest.hexdigest(),
                "training_candidate_plan": str(PLAN_PATH),
                "preflight_report": str(PREFLIGHT_PATH),
                "duplicate_exclusion_artifact": str(EXCLUSION_PATH),
                "training_rows_before_oversampling": int(len(train_indices)),
                "training_rows_after_oversampling": int(len(fit_indices)),
                "heldout_rows": int(len(held)),
                "heldout_class_counts": held_counts.tolist(),
                "natural_training_class_counts": natural_counts.tolist(),
                "added_samples_by_class": [added_counts[c] for c in CLASS_IDS],
                "resampled_training_class_counts": fit_counts.tolist(),
                "excluded_duplicate_candidate_rows": int(len(duplicate_indices)),
                "class_ids": CLASS_IDS,
                "feature_count": int(n_features),
                "rf_configuration": {
                    "n_estimators": N_ESTIMATORS,
                    "max_features": MAX_FEATURES,
                    "max_depth": MAX_DEPTH,
                    "bootstrap": BOOTSTRAP,
                    "n_jobs": N_JOBS,
                    "class_weight": None,
                    "random_state": RANDOM_SEED + fold_id,
                },
                "sampling_policy": manifest["sampling_policy"],
                "fit_seconds": round(elapsed, 3),
                "validation_accessed": False,
                "test_accessed": False,
                "final_rf_modified": False,
            }

            with meta_path.open("x", encoding="utf-8") as f:
                json.dump(fold_meta, f, indent=2)

            manifest["folds"].append({
                "fold_id": fold_id,
                "status": "TRAINED",
                "model_path": str(model_path),
                "metadata_path": str(meta_path),
                "model_sha256": digest.hexdigest(),
                "fit_seconds": round(elapsed, 3),
            })

            print("Saved model:", model_path)
            print("Saved metadata:", meta_path)
            print(f"Fit time: {elapsed:.1f} seconds")

            # Free fold-specific arrays and model before next fold.
            del model, X_fit, y_fit, fit_indices, train_indices
            del y_train_natural, natural_counts, fit_counts, expected_counts
            del extra_parts, duplicate_indices, sampled_indices
            gc.collect()

    manifest["status"] = "COMPLETED_ALL_FIVE_FOLDS"
    manifest["completed_utc"] = datetime.now(timezone.utc).isoformat()

except Exception as exc:
    manifest["status"] = "INCOMPLETE_FAILURE"
    manifest["failure"] = {
        "type": type(exc).__name__,
        "message": str(exc),
        "recorded_utc": datetime.now(timezone.utc).isoformat(),
    }
    manifest["completed_utc"] = datetime.now(timezone.utc).isoformat()
    raise

finally:
    # Save a recoverable record of progress/failure without overwriting.
    if not MANIFEST_PATH.exists():
        with MANIFEST_PATH.open("x", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2)

print("\n" + "=" * 76)
print("5.16.3 TRAINING RESULT")
print("=" * 76)
print("Status:", manifest["status"])
print("Fold models persisted:", len(manifest["folds"]), "/ 5")
print("Manifest:", MANIFEST_PATH)
print("Validation/Test accessed: NO")
print("Existing final RF model modified: NO")

============================================================================
5.16.3 — RF-3 FOLD-SPECIFIC TRAINING
============================================================================
Candidate: oof_fold_plan_candidate_v3.json
RF-specific support gate: PASS
Rows: 1814018 | Features: 32
Folds: 5
Model output directory: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/models
Validation/Test arrays accessed: NO
Existing final RF model will be modified: NO

------------------------------------------------------------------------
FOLD 0 — PREPARE, RESAMPLE, FIT, SAVE
------------------------------------------------------------------------
Held-out rows: 362,802
Natural training rows: 1,294,185
Duplicate rows excluded: 157,022
Natural class counts: [1064071, 65568, 59342, 4713, 1009, 1077, 12, 98388, 5]
Added by class: [0, 0, 0, 18852, 4036, 4308, 48, 0, 0]
Resampled class counts: [1064071, 65568, 59342, 23565, 5045, 5385, 60, 98388, 5]
Fitting RandomForestClassifier (100 trees)...
Saved model: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/models/rf3_fold_0.joblib
Saved metadata: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/provenance/rf3_fold_0_metadata.json
Fit time: 271.4 seconds

------------------------------------------------------------------------
FOLD 1 — PREPARE, RESAMPLE, FIT, SAVE
------------------------------------------------------------------------
Held-out rows: 362,802
Natural training rows: 1,293,829
Duplicate rows excluded: 157,378
Natural class counts: [1063848, 65570, 59154, 4779, 1006, 1067, 12, 98388, 5]
Added by class: [0, 0, 0, 19116, 4024, 4268, 48, 0, 0]
Resampled class counts: [1063848, 65570, 59154, 23895, 5030, 5335, 60, 98388, 5]
Fitting RandomForestClassifier (100 trees)...
Saved model: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/models/rf3_fold_1.joblib
Saved metadata: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/provenance/rf3_fold_1_metadata.json
Fit time: 264.4 seconds

------------------------------------------------------------------------
FOLD 2 — PREPARE, RESAMPLE, FIT, SAVE
------------------------------------------------------------------------
Held-out rows: 362,802
Natural training rows: 1,294,044
Duplicate rows excluded: 157,163
Natural class counts: [1064023, 65567, 59322, 4755, 1008, 1074, 12, 98278, 5]
Added by class: [0, 0, 0, 19020, 4032, 4296, 48, 0, 0]
Resampled class counts: [1064023, 65567, 59322, 23775, 5040, 5370, 60, 98278, 5]
Fitting RandomForestClassifier (100 trees)...
Saved model: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/models/rf3_fold_2.joblib
Saved metadata: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/provenance/rf3_fold_2_metadata.json
Fit time: 259.4 seconds

------------------------------------------------------------------------
FOLD 3 — PREPARE, RESAMPLE, FIT, SAVE
------------------------------------------------------------------------
Held-out rows: 362,802
Natural training rows: 1,295,035
Duplicate rows excluded: 156,172
Natural class counts: [1064987, 65570, 59082, 4813, 1003, 1078, 12, 98486, 4]
Added by class: [0, 0, 0, 19252, 4012, 4312, 48, 0, 0]
Resampled class counts: [1064987, 65570, 59082, 24065, 5015, 5390, 60, 98486, 4]
Fitting RandomForestClassifier (100 trees)...
Saved model: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/models/rf3_fold_3.joblib
Saved metadata: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/provenance/rf3_fold_3_metadata.json
Fit time: 252.5 seconds

------------------------------------------------------------------------
FOLD 4 — PREPARE, RESAMPLE, FIT, SAVE
------------------------------------------------------------------------
Held-out rows: 362,801
Natural training rows: 1,293,927
Duplicate rows excluded: 157,281
Natural class counts: [1063884, 65568, 59118, 4761, 1007, 1068, 12, 98504, 5]
Added by class: [0, 0, 0, 19044, 4028, 4272, 48, 0, 0]
Resampled class counts: [1063884, 65568, 59118, 23805, 5035, 5340, 60, 98504, 5]
Fitting RandomForestClassifier (100 trees)...
Saved model: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/models/rf3_fold_4.joblib
Saved metadata: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/provenance/rf3_fold_4_metadata.json
Fit time: 245.3 seconds

============================================================================
5.16.3 TRAINING RESULT
============================================================================
Status: COMPLETED_ALL_FIVE_FOLDS
Fold models persisted: 5 / 5
Manifest: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/rf_fold_training_manifest_v1.json
Validation/Test accessed: NO
Existing final RF model modified: NO

### 5.16.4 — OOF Probability Generation

Generate out-of-fold (OOF) class probabilities using the five persisted RF-3 fold-specific models. Each model predicts only observations assigned to its corresponding held-out fold. The output preserves the raw N04 Training row indices and class order 0–8.

Validate each model's provenance and class order before inference. Validate probability dimensions, finiteness, bounds, row sums, target alignment, fold assignments, and exactly-once OOF coverage before saving the artifacts. Predictions are generated in batches to control memory usage.

This subsection does not train models or access Validation/Test. The OOF predictions are based on the current stratified random fold assignment; chronological and session independence have not been established.

In [ ]:

# ================================================================
# 5.16.4 — RF-3 OOF PROBABILITY GENERATION
# Uses saved fold models only. No model fitting.
# No Validation/Test access. No overwriting existing artifacts.
# ================================================================

import json
import hashlib
import gc
from pathlib import Path
from datetime import datetime, timezone

import joblib
import numpy as np

ROOT = Path(
    "/content/drive/MyDrive/AI-Network-Intrusion-Detection-System"
)
N04 = ROOT / "outputs/model_preparation_v2"
EXP = ROOT / "outputs/ensemble_model_development/experiments"

PLAN_PATH = EXP / "oof_fold_plan_candidate_v3.json"
TRAIN_MANIFEST_PATH = (
    ROOT / "outputs/ensemble_model_development"
    / "rf_fold_models_v1/rf_fold_training_manifest_v1.json"
)
X_PATH = N04 / "feature_scaling/X_train_scaled.npy"
Y_PATH = N04 / "model_ready_targets/y_train.npy"

# Keep OOF artifacts separate from model and final-model directories.
OOF_DIR = (
    ROOT / "outputs/ensemble_model_development"
    / "rf_fold_models_v1/oof"
)

PROB_PATH = OOF_DIR / "rf_oof_probabilities.npy"
INDEX_PATH = OOF_DIR / "rf_oof_observation_indices.npy"
TARGET_PATH = OOF_DIR / "rf_oof_targets.npy"
FOLD_ID_PATH = OOF_DIR / "rf_oof_fold_ids.npy"
REPORT_PATH = OOF_DIR / "rf_oof_generation_report_v1.json"

CLASS_IDS = list(range(9))
N_CLASSES = len(CLASS_IDS)
N_FOLDS = 5
SEQUENCE_LENGTH = 10
BATCH_SIZE = 20_000
PROB_TOLERANCE = 1e-5

# -------------------- Preconditions --------------------
for path in [
    PLAN_PATH, TRAIN_MANIFEST_PATH, X_PATH, Y_PATH
]:
    if not path.is_file():
        raise FileNotFoundError(f"Required artifact missing: {path}")

with PLAN_PATH.open("r", encoding="utf-8") as f:
    plan = json.load(f)
with TRAIN_MANIFEST_PATH.open("r", encoding="utf-8") as f:
    train_manifest = json.load(f)

assert plan.get("candidate_id") == "oof_fold_plan_candidate_v3"
assert plan.get("partition_used") == "Training only"
assert int(plan.get("fold_count", -1)) == N_FOLDS
assert int(plan.get("sequence_length", -1)) == SEQUENCE_LENGTH
assert train_manifest.get("status") == "COMPLETED_ALL_FIVE_FOLDS"
assert train_manifest.get("validation_accessed") is False
assert train_manifest.get("test_accessed") is False
assert train_manifest.get("existing_final_rf_modified") is False
assert len(train_manifest.get("folds", [])) == N_FOLDS

# Never overwrite an existing OOF run.
OOF_DIR.mkdir(parents=True, exist_ok=True)
output_paths = [
    PROB_PATH, INDEX_PATH, TARGET_PATH, FOLD_ID_PATH, REPORT_PATH
]
existing = [str(p) for p in output_paths if p.exists()]
if existing:
    raise FileExistsError(
        "OOF output already exists. Preserve it and inspect before rerunning:\n"
        + "\n".join(existing)
    )

X = np.load(X_PATH, mmap_mode="r", allow_pickle=False)
y = np.load(Y_PATH, mmap_mode="r", allow_pickle=False)

n_rows, n_features = X.shape
assert y.shape == (n_rows,)
assert n_rows == int(plan["training_rows"])
assert n_features == int(plan["feature_count"])
assert np.unique(y).astype(int).tolist() == CLASS_IDS

fold_assignment = np.asarray(
    plan["fold_id_by_raw_row"], dtype=np.int16
)
assert fold_assignment.shape == (n_rows,)

eligible_indices = np.arange(SEQUENCE_LENGTH - 1, n_rows, dtype=np.int64)
assert np.all(fold_assignment[:SEQUENCE_LENGTH - 1] == -1)
assert np.all(np.isin(fold_assignment[eligible_indices], range(N_FOLDS)))

# Allocate one OOF probability row per eligible Training observation.
oof_probabilities = np.full(
    (len(eligible_indices), N_CLASSES), np.nan, dtype=np.float32
)
oof_fold_ids = np.full(len(eligible_indices), -1, dtype=np.int8)

# Map raw N04 row index -> compact OOF output position.
raw_to_oof_position = np.full(n_rows, -1, dtype=np.int64)
raw_to_oof_position[eligible_indices] = np.arange(
    len(eligible_indices), dtype=np.int64
)

model_records = {
    int(record["fold_id"]): record
    for record in train_manifest["folds"]
}
assert set(model_records) == set(range(N_FOLDS))

def sha256_file(path, chunk_size=1024 * 1024):
    digest = hashlib.sha256()
    with Path(path).open("rb") as f:
        for block in iter(lambda: f.read(chunk_size), b""):
            digest.update(block)
    return digest.hexdigest()

generation_records = []

print("=" * 76)
print("5.16.4 — RF-3 OOF PROBABILITY GENERATION")
print("=" * 76)
print("Eligible Training targets:", f"{len(eligible_indices):,}")
print("Classes:", CLASS_IDS)
print("Batch size:", f"{BATCH_SIZE:,}")
print("Fold models:", N_FOLDS)
print("Validation/Test arrays accessed: NO")
print("Models trained: NO")

# -------------------- Predict each held-out fold --------------------
for fold_id in range(N_FOLDS):
    print("\n" + "-" * 72)
    print(f"FOLD {fold_id} — HELD-OUT INFERENCE")
    print("-" * 72)

    record = model_records[fold_id]
    model_path = Path(record["model_path"])
    metadata_path = Path(record["metadata_path"])

    assert model_path.is_file(), f"Missing fold model: {model_path}"
    assert metadata_path.is_file(), f"Missing fold metadata: {metadata_path}"

    expected_hash = record.get("model_sha256")
    actual_hash = sha256_file(model_path)
    assert expected_hash and actual_hash == expected_hash, (
        f"Fold {fold_id} model hash does not match training manifest."
    )

    with metadata_path.open("r", encoding="utf-8") as f:
        metadata = json.load(f)

    assert int(metadata["fold_id"]) == fold_id
    assert metadata.get("status") == "TRAINED"
    assert metadata.get("model_sha256") == actual_hash
    assert metadata.get("validation_accessed") is False
    assert metadata.get("test_accessed") is False
    assert metadata.get("final_rf_modified") is False
    assert metadata.get("class_ids") == CLASS_IDS
    assert int(metadata["feature_count"]) == n_features

    model = joblib.load(model_path)

    model_classes = np.asarray(model.classes_, dtype=np.int64).tolist()
    assert model_classes == CLASS_IDS, (
        f"Fold {fold_id} class order mismatch: {model_classes}"
    )
    assert int(model.n_features_in_) == n_features

    held_raw_indices = eligible_indices[
        fold_assignment[eligible_indices] == fold_id
    ]
    assert len(held_raw_indices) == int(
        metadata["heldout_rows"]
    ), f"Fold {fold_id} held-out count differs from training metadata."

    out_positions = raw_to_oof_position[held_raw_indices]
    assert np.all(out_positions >= 0)
    assert np.all(oof_fold_ids[out_positions] == -1), (
        f"Fold {fold_id} would overwrite previously generated OOF rows."
    )

    held_probs = np.empty(
        (len(held_raw_indices), N_CLASSES), dtype=np.float32
    )

    for start in range(0, len(held_raw_indices), BATCH_SIZE):
        batch_raw = held_raw_indices[start:start + BATCH_SIZE]
        batch_end = start + len(batch_raw)
        batch_X = np.asarray(X[batch_raw], dtype=np.float32)

        batch_probs = model.predict_proba(batch_X)
        batch_probs = np.asarray(batch_probs, dtype=np.float32)

        expected_shape = (len(batch_raw), N_CLASSES)
        assert batch_probs.shape == expected_shape, (
            f"Fold {fold_id}: expected {expected_shape}, "
            f"got {batch_probs.shape}"
        )
        assert np.isfinite(batch_probs).all(), (
            f"Fold {fold_id}: non-finite probability detected."
        )
        assert np.all(batch_probs >= -PROB_TOLERANCE)
        assert np.all(batch_probs <= 1.0 + PROB_TOLERANCE)
        assert np.allclose(
            batch_probs.sum(axis=1), 1.0,
            rtol=0.0, atol=PROB_TOLERANCE
        ), f"Fold {fold_id}: probability row sums are invalid."

        held_probs[start:batch_end] = batch_probs

    # Confirm labels align to the raw observation indices.
    held_targets = np.asarray(y[held_raw_indices], dtype=np.int64)
    assert held_targets.shape == (len(held_raw_indices),)

    oof_probabilities[out_positions] = held_probs
    oof_fold_ids[out_positions] = fold_id

    generation_records.append({
        "fold_id": fold_id,
        "model_path": str(model_path),
        "metadata_path": str(metadata_path),
        "model_sha256_verified": actual_hash,
        "heldout_observation_count": int(len(held_raw_indices)),
        "probability_shape": list(held_probs.shape),
        "class_order": model_classes,
        "probabilities_finite": bool(np.isfinite(held_probs).all()),
        "probability_row_sums_valid": bool(np.allclose(
            held_probs.sum(axis=1), 1.0,
            rtol=0.0, atol=PROB_TOLERANCE
        )),
        "target_alignment_valid": bool(
            np.array_equal(held_targets, np.asarray(y[held_raw_indices]))
        ),
    })

    print("Held-out rows:", f"{len(held_raw_indices):,}")
    print("Probability shape:", held_probs.shape)
    print("Model hash verified: YES")
    print("Class order:", model_classes)
    print("Probability checks: PASS")

    del model, held_probs, held_raw_indices, held_targets
    gc.collect()

# -------------------- Global coverage and alignment checks --------------------
assert np.all(oof_fold_ids >= 0), "Some OOF rows were not assigned a fold."
assert np.all(np.isfinite(oof_probabilities)), "OOF probabilities contain NaN/Inf."
assert np.all(np.isin(oof_fold_ids, range(N_FOLDS)))
assert np.array_equal(
    oof_fold_ids,
    fold_assignment[eligible_indices].astype(np.int8)
), "OOF fold IDs do not match the shared candidate assignment."

row_sums = oof_probabilities.sum(axis=1)
assert np.allclose(
    row_sums, 1.0, rtol=0.0, atol=PROB_TOLERANCE
), "Some OOF probability rows do not sum to 1."

oof_targets = np.asarray(y[eligible_indices], dtype=np.int64)
assert oof_targets.shape == (len(eligible_indices),)
assert np.array_equal(oof_targets, y[eligible_indices])

# Check each fold was assigned exactly its declared eligible target count.
fold_counts = np.bincount(oof_fold_ids.astype(np.int64), minlength=N_FOLDS)
assert np.array_equal(
    fold_counts,
    np.bincount(
        fold_assignment[eligible_indices].astype(np.int64),
        minlength=N_FOLDS
    )
)

# -------------------- Save without overwriting --------------------
# Use exclusive file creation to protect prior artifacts.
with PROB_PATH.open("xb") as f:
    np.save(f, oof_probabilities, allow_pickle=False)
with INDEX_PATH.open("xb") as f:
    np.save(f, eligible_indices, allow_pickle=False)
with TARGET_PATH.open("xb") as f:
    np.save(f, oof_targets, allow_pickle=False)
with FOLD_ID_PATH.open("xb") as f:
    np.save(f, oof_fold_ids, allow_pickle=False)

report = {
    "report_id": "rf_oof_generation_report_v1",
    "created_utc": datetime.now(timezone.utc).isoformat(),
    "status": "OOF_PROBABILITIES_GENERATED_AND_VALIDATED",
    "candidate_plan": str(PLAN_PATH),
    "training_manifest": str(TRAIN_MANIFEST_PATH),
    "output_directory": str(OOF_DIR),
    "artifacts": {
        "probabilities": str(PROB_PATH),
        "observation_indices": str(INDEX_PATH),
        "targets": str(TARGET_PATH),
        "fold_ids": str(FOLD_ID_PATH),
    },
    "probability_shape": list(oof_probabilities.shape),
    "observation_index_shape": list(eligible_indices.shape),
    "target_shape": list(oof_targets.shape),
    "fold_id_shape": list(oof_fold_ids.shape),
    "class_order": CLASS_IDS,
    "fold_counts": fold_counts.tolist(),
    "all_probabilities_finite": bool(np.isfinite(oof_probabilities).all()),
    "all_probability_rows_sum_to_one": bool(np.allclose(
        row_sums, 1.0, rtol=0.0, atol=PROB_TOLERANCE
    )),
    "exactly_once_oof_coverage": True,
    "targets_aligned_to_observation_indices": True,
    "fold_ids_match_candidate_plan": True,
    "fold_model_records": generation_records,
    "validation_accessed": False,
    "test_accessed": False,
    "models_trained": False,
    "existing_final_rf_modified": False,
    "limitations": [
        "Fold assignment is stratified random, not verified chronological/session-based.",
        "The shared LSTM protocol remains separately blocked by rare-class sequence support.",
        "These artifacts establish RF OOF predictions only; they do not approve the joint ensemble."
    ],
}

with REPORT_PATH.open("x", encoding="utf-8") as f:
    json.dump(report, f, indent=2)

print("\n" + "=" * 76)
print("5.16.4 RESULT")
print("=" * 76)
print("Status:", report["status"])
print("OOF probability shape:", oof_probabilities.shape)
print("Observation indices:", eligible_indices.shape)
print("Targets:", oof_targets.shape)
print("Fold IDs:", oof_fold_ids.shape)
print("Fold counts:", fold_counts.tolist())
print("All probabilities finite: YES")
print("All probability rows sum to 1: YES")
print("Exactly-once OOF coverage: YES")
print("Report saved:", REPORT_PATH)
print("Validation/Test accessed: NO")
print("Models trained: NO")
print("Existing final RF modified: NO")

============================================================================
5.16.4 — RF-3 OOF PROBABILITY GENERATION
============================================================================
Eligible Training targets: 1,814,009
Classes: [0, 1, 2, 3, 4, 5, 6, 7, 8]
Batch size: 20,000
Fold models: 5
Validation/Test arrays accessed: NO
Models trained: NO

------------------------------------------------------------------------
FOLD 0 — HELD-OUT INFERENCE
------------------------------------------------------------------------
Held-out rows: 362,802
Probability shape: (362802, 9)
Model hash verified: YES
Class order: [0, 1, 2, 3, 4, 5, 6, 7, 8]
Probability checks: PASS

------------------------------------------------------------------------
FOLD 1 — HELD-OUT INFERENCE
------------------------------------------------------------------------
Held-out rows: 362,802
Probability shape: (362802, 9)
Model hash verified: YES
Class order: [0, 1, 2, 3, 4, 5, 6, 7, 8]
Probability checks: PASS

------------------------------------------------------------------------
FOLD 2 — HELD-OUT INFERENCE
------------------------------------------------------------------------
Held-out rows: 362,802
Probability shape: (362802, 9)
Model hash verified: YES
Class order: [0, 1, 2, 3, 4, 5, 6, 7, 8]
Probability checks: PASS

------------------------------------------------------------------------
FOLD 3 — HELD-OUT INFERENCE
------------------------------------------------------------------------
Held-out rows: 362,802
Probability shape: (362802, 9)
Model hash verified: YES
Class order: [0, 1, 2, 3, 4, 5, 6, 7, 8]
Probability checks: PASS

------------------------------------------------------------------------
FOLD 4 — HELD-OUT INFERENCE
------------------------------------------------------------------------
Held-out rows: 362,801
Probability shape: (362801, 9)
Model hash verified: YES
Class order: [0, 1, 2, 3, 4, 5, 6, 7, 8]
Probability checks: PASS

============================================================================
5.16.4 RESULT
============================================================================
Status: OOF_PROBABILITIES_GENERATED_AND_VALIDATED
OOF probability shape: (1814009, 9)
Observation indices: (1814009,)
Targets: (1814009,)
Fold IDs: (1814009,)
Fold counts: [362802, 362802, 362802, 362802, 362801]
All probabilities finite: YES
All probability rows sum to 1: YES
Exactly-once OOF coverage: YES
Report saved: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/oof/rf_oof_generation_report_v1.json
Validation/Test accessed: NO
Models trained: NO
Existing final RF modified: NO

### 5.16.5 — OOF Coverage and Provenance Validation

Validate the persisted RF-3 OOF probability artifacts against the shared candidate fold plan, the fold-training manifest, the individual model metadata, and the N04 Training labels. Verify exactly-once coverage, observation-index and target alignment, fold assignment consistency, probability integrity, model hashes, class order, and consistency between reconstructed fold-training sets and recorded training counts.

This subsection performs validation only. It does not fit models, access Validation/Test arrays, or modify the existing final RF model. Any failed check blocks the RF OOF validation report from receiving a passed status. The stratified random fold assignment does not establish chronological or session-level independence.

In [ ]:
# ================================================================
# 5.16.5 — OOF COVERAGE AND PROVENANCE VALIDATION
# Read-only validation. No fitting or Validation/Test access.
# ================================================================

import json
import hashlib
from pathlib import Path
from datetime import datetime, timezone

import numpy as np

ROOT = Path(
    "/content/drive/MyDrive/AI-Network-Intrusion-Detection-System"
)

N04 = ROOT / "outputs/model_preparation_v2"
EXP = ROOT / "outputs/ensemble_model_development/experiments"
RF_DIR = ROOT / "outputs/ensemble_model_development/rf_fold_models_v1"
OOF_DIR = RF_DIR / "oof"

PLAN_PATH = EXP / "oof_fold_plan_candidate_v3.json"
EXCLUSION_PATH = EXP / "oof_fold_duplicate_training_exclusions_v4.npz"
TRAIN_MANIFEST_PATH = RF_DIR / "rf_fold_training_manifest_v1.json"
GENERATION_REPORT_PATH = OOF_DIR / "rf_oof_generation_report_v1.json"

X_PATH = N04 / "feature_scaling/X_train_scaled.npy"
Y_PATH = N04 / "model_ready_targets/y_train.npy"

PROB_PATH = OOF_DIR / "rf_oof_probabilities.npy"
INDEX_PATH = OOF_DIR / "rf_oof_observation_indices.npy"
TARGET_PATH = OOF_DIR / "rf_oof_targets.npy"
FOLD_ID_PATH = OOF_DIR / "rf_oof_fold_ids.npy"

REPORT_PATH = OOF_DIR / "rf_oof_validation_report_v1.json"

CLASS_IDS = list(range(9))
N_FOLDS = 5
SEQUENCE_LENGTH = 10
PROB_TOLERANCE = 1e-5

# ------------------------------------------------
# 1. Require all previously persisted artifacts
# ------------------------------------------------

required_paths = [
    PLAN_PATH,
    EXCLUSION_PATH,
    TRAIN_MANIFEST_PATH,
    GENERATION_REPORT_PATH,
    X_PATH,
    Y_PATH,
    PROB_PATH,
    INDEX_PATH,
    TARGET_PATH,
    FOLD_ID_PATH,
]

missing_paths = [str(p) for p in required_paths if not p.is_file()]
if missing_paths:
    raise FileNotFoundError(
        "5.16.5 cannot validate incomplete artifacts:\n- "
        + "\n- ".join(missing_paths)
    )

if REPORT_PATH.exists():
    raise FileExistsError(
        "Refusing to overwrite an existing validation report:\n"
        f"{REPORT_PATH}"
    )

with PLAN_PATH.open("r", encoding="utf-8") as f:
    plan = json.load(f)

with TRAIN_MANIFEST_PATH.open("r", encoding="utf-8") as f:
    train_manifest = json.load(f)

with GENERATION_REPORT_PATH.open("r", encoding="utf-8") as f:
    generation_report = json.load(f)

# ------------------------------------------------
# 2. Load persisted OOF arrays and Training targets
# ------------------------------------------------

X = np.load(X_PATH, mmap_mode="r", allow_pickle=False)
y = np.load(Y_PATH, mmap_mode="r", allow_pickle=False)

oof_probabilities = np.load(PROB_PATH, mmap_mode="r", allow_pickle=False)
oof_indices = np.load(INDEX_PATH, mmap_mode="r", allow_pickle=False)
oof_targets = np.load(TARGET_PATH, mmap_mode="r", allow_pickle=False)
oof_fold_ids = np.load(FOLD_ID_PATH, mmap_mode="r", allow_pickle=False)

n_rows, n_features = X.shape
eligible_indices = np.arange(
    SEQUENCE_LENGTH - 1, n_rows, dtype=np.int64
)

fold_assignment = np.asarray(
    plan["fold_id_by_raw_row"], dtype=np.int16
)

checks = {}
issues = []

def record_check(name, passed, detail):
    passed = bool(passed)
    checks[name] = {
        "passed": passed,
        "detail": str(detail),
    }
    print(f"[{'PASS' if passed else 'BLOCK'}] {name}: {detail}")
    if not passed:
        issues.append(name)

def sha256_file(path, chunk_size=1024 * 1024):
    digest = hashlib.sha256()
    with Path(path).open("rb") as f:
        for block in iter(lambda: f.read(chunk_size), b""):
            digest.update(block)
    return digest.hexdigest()

print("=" * 76)
print("5.16.5 — OOF COVERAGE AND PROVENANCE VALIDATION")
print("=" * 76)

# ------------------------------------------------
# 3. Protocol, array shape, index and label checks
# ------------------------------------------------

record_check(
    "Training feature/target contract",
    X.shape == (1_814_018, 32) and y.shape == (n_rows,),
    f"X={X.shape}; y={y.shape}",
)

record_check(
    "Candidate plan identity",
    plan.get("candidate_id") == "oof_fold_plan_candidate_v3"
    and plan.get("partition_used") == "Training only",
    f"id={plan.get('candidate_id')}; partition={plan.get('partition_used')}",
)

record_check(
    "Training manifest completed",
    train_manifest.get("status") == "COMPLETED_ALL_FIVE_FOLDS"
    and len(train_manifest.get("folds", [])) == N_FOLDS,
    f"status={train_manifest.get('status')}; "
    f"fold records={len(train_manifest.get('folds', []))}",
)

record_check(
    "Generation report status",
    generation_report.get("status")
    == "OOF_PROBABILITIES_GENERATED_AND_VALIDATED",
    str(generation_report.get("status")),
)

record_check(
    "No Validation/Test access during RF OOF generation",
    generation_report.get("validation_accessed") is False
    and generation_report.get("test_accessed") is False,
    "Generation report records both as False",
)

record_check(
    "OOF array shapes",
    oof_probabilities.shape == (len(eligible_indices), len(CLASS_IDS))
    and oof_indices.shape == eligible_indices.shape
    and oof_targets.shape == eligible_indices.shape
    and oof_fold_ids.shape == eligible_indices.shape,
    f"probabilities={oof_probabilities.shape}; "
    f"indices={oof_indices.shape}; targets={oof_targets.shape}; "
    f"fold_ids={oof_fold_ids.shape}",
)

indices_match = (
    oof_indices.ndim == 1
    and np.array_equal(oof_indices, eligible_indices)
)

record_check(
    "Eligible observation indices",
    indices_match,
    "Saved indices match raw Training rows 9 through N-1",
)

targets_match = (
    oof_targets.shape == eligible_indices.shape
    and np.array_equal(oof_targets, y[eligible_indices])
)

record_check(
    "OOF target alignment",
    targets_match,
    "Saved OOF targets match N04 y_train at saved observation indices",
)

# ------------------------------------------------
# 4. Probability integrity and fold assignment
# ------------------------------------------------

probabilities_finite = (
    oof_probabilities.shape == (len(eligible_indices), len(CLASS_IDS))
    and bool(np.isfinite(oof_probabilities).all())
)

record_check(
    "All OOF probabilities finite",
    probabilities_finite,
    f"shape={oof_probabilities.shape}",
)

if probabilities_finite:
    prob_min = float(np.min(oof_probabilities))
    prob_max = float(np.max(oof_probabilities))
    row_sums = np.asarray(
        oof_probabilities.sum(axis=1), dtype=np.float64
    )
    probability_bounds_pass = (
        prob_min >= -PROB_TOLERANCE
        and prob_max <= 1.0 + PROB_TOLERANCE
    )
    probability_sums_pass = bool(np.allclose(
        row_sums, 1.0, rtol=0.0, atol=PROB_TOLERANCE
    ))
else:
    prob_min = None
    prob_max = None
    probability_bounds_pass = False
    probability_sums_pass = False

record_check(
    "Probability values within bounds",
    probability_bounds_pass,
    f"min={prob_min}; max={prob_max}",
)

record_check(
    "Probability rows sum to one",
    probability_sums_pass,
    "Every row sums to 1 within tolerance"
    if probability_sums_pass else "Invalid or unavailable probability sums",
)

expected_fold_ids = fold_assignment[eligible_indices].astype(np.int8)

fold_ids_match = (
    oof_fold_ids.shape == expected_fold_ids.shape
    and np.array_equal(oof_fold_ids, expected_fold_ids)
    and bool(np.all(np.isin(oof_fold_ids, range(N_FOLDS))))
)

record_check(
    "Fold IDs match candidate assignment",
    fold_ids_match,
    "Saved fold IDs match candidate v3 for every eligible observation",
)

observed_fold_counts = (
    np.bincount(np.asarray(oof_fold_ids, dtype=np.int64), minlength=N_FOLDS)
    if oof_fold_ids.shape == eligible_indices.shape
    and bool(np.all(np.isin(oof_fold_ids, range(N_FOLDS))))
    else np.zeros(N_FOLDS, dtype=np.int64)
)

expected_fold_counts = np.bincount(
    expected_fold_ids.astype(np.int64), minlength=N_FOLDS
)

record_check(
    "Exactly-once OOF coverage",
    indices_match
    and len(np.unique(oof_indices)) == len(eligible_indices)
    and np.array_equal(observed_fold_counts, expected_fold_counts),
    f"eligible={len(eligible_indices):,}; "
    f"unique indices={len(np.unique(oof_indices)):,}; "
    f"fold counts={observed_fold_counts.tolist()}",
)

# ------------------------------------------------
# 5. Validate fold model hashes and metadata
# ------------------------------------------------

model_records = {
    int(record["fold_id"]): record
    for record in train_manifest["folds"]
}

record_check(
    "Exactly five unique fold model records",
    set(model_records) == set(range(N_FOLDS))
    and len(model_records) == N_FOLDS,
    f"fold IDs={sorted(model_records)}",
)

with np.load(EXCLUSION_PATH, allow_pickle=False) as exclusions:
    exclusion_keys = set(exclusions.files)

    fold_provenance_results = []

    for fold_id in range(N_FOLDS):
        print("\n" + "-" * 72)
        print(f"FOLD {fold_id} — MODEL AND TRAINING PROVENANCE")
        print("-" * 72)

        fold_checks = {}
        def fold_check(name, passed, detail):
            fold_checks[name] = bool(passed)
            print(f"  [{'PASS' if passed else 'BLOCK'}] {name}: {detail}")

        manifest_record = model_records.get(fold_id, {})
        model_path = Path(manifest_record.get("model_path", ""))
        metadata_path = Path(manifest_record.get("metadata_path", ""))

        paths_exist = (
            model_path.is_file()
            and metadata_path.is_file()
        )
        fold_check(
            "Model and metadata files exist",
            paths_exist,
            f"model={model_path.name}; metadata={metadata_path.name}",
        )

        if not paths_exist:
            fold_provenance_results.append({
                "fold_id": fold_id,
                "passed": False,
                "checks": fold_checks,
            })
            continue

        actual_hash = sha256_file(model_path)
        expected_hash = manifest_record.get("model_sha256")

        hash_match = bool(expected_hash) and actual_hash == expected_hash
        fold_check(
            "Model SHA-256 matches manifest",
            hash_match,
            f"verified={hash_match}",
        )

        with metadata_path.open("r", encoding="utf-8") as f:
            metadata = json.load(f)

        metadata_matches = (
            int(metadata.get("fold_id", -1)) == fold_id
            and metadata.get("status") == "TRAINED"
            and metadata.get("model_sha256") == actual_hash
            and metadata.get("class_ids") == CLASS_IDS
            and int(metadata.get("feature_count", -1)) == n_features
            and metadata.get("validation_accessed") is False
            and metadata.get("test_accessed") is False
            and metadata.get("final_rf_modified") is False
        )

        fold_check(
            "Fold metadata matches model and protocol",
            metadata_matches,
            f"status={metadata.get('status')}; "
            f"class_ids={metadata.get('class_ids')}",
        )

        # Reconstruct the RF training candidates exactly as Section 5.16.3:
        # eligible raw rows assigned to another fold, excluding the saved
        # duplicate candidates for this fold.
        exclusion_key = f"fold_{fold_id}_duplicate_excluded_indices"
        exclusion_key_exists = exclusion_key in exclusion_keys

        fold_check(
            "Duplicate exclusion record exists",
            exclusion_key_exists,
            exclusion_key,
        )

        if not exclusion_key_exists:
            fold_provenance_results.append({
                "fold_id": fold_id,
                "passed": False,
                "checks": fold_checks,
            })
            continue

        duplicate_indices = np.asarray(
            exclusions[exclusion_key], dtype=np.int64
        )

        duplicate_indices_valid = bool(
            np.all((duplicate_indices >= 0) & (duplicate_indices < n_rows))
        )

        fold_check(
            "Duplicate exclusion indices in range",
            duplicate_indices_valid,
            f"count={len(duplicate_indices):,}",
        )

        if not duplicate_indices_valid:
            fold_provenance_results.append({
                "fold_id": fold_id,
                "passed": False,
                "checks": fold_checks,
            })
            continue

        train_mask = np.zeros(n_rows, dtype=bool)
        train_mask[eligible_indices] = (
            fold_assignment[eligible_indices] != fold_id
        )
        train_mask[duplicate_indices] = False

        reconstructed_train_indices = np.flatnonzero(train_mask)
        held_indices = eligible_indices[
            fold_assignment[eligible_indices] == fold_id
        ]

        # Held-out observations must not occur in reconstructed training.
        disjoint = not np.intersect1d(
            reconstructed_train_indices, held_indices,
            assume_unique=True
        ).size

        fold_check(
            "Training/held-out target disjointness",
            disjoint,
            f"training={len(reconstructed_train_indices):,}; "
            f"held-out={len(held_indices):,}",
        )

        # Compare reconstructed natural training counts to metadata.
        reconstructed_counts = np.bincount(
            np.asarray(y[reconstructed_train_indices], dtype=np.int64),
            minlength=len(CLASS_IDS),
        ).tolist()

        recorded_counts = metadata.get("natural_training_class_counts")
        counts_match = (
            recorded_counts is not None
            and list(recorded_counts) == reconstructed_counts
        )

        fold_check(
            "Natural training class counts match metadata",
            counts_match,
            f"reconstructed={reconstructed_counts}; "
            f"recorded={recorded_counts}",
        )

        training_rows_match = (
            int(metadata.get("training_rows_before_oversampling", -1))
            == len(reconstructed_train_indices)
        )

        fold_check(
            "Natural training row count matches metadata",
            training_rows_match,
            f"reconstructed={len(reconstructed_train_indices):,}; "
            f"recorded={metadata.get('training_rows_before_oversampling')}",
        )

        heldout_rows_match = (
            int(metadata.get("heldout_rows", -1)) == len(held_indices)
        )

        fold_check(
            "Held-out row count matches metadata",
            heldout_rows_match,
            f"reconstructed={len(held_indices):,}; "
            f"recorded={metadata.get('heldout_rows')}",
        )

        # Verify that the OOF report identifies the same fold model/hash.
        generation_records = {
            int(record["fold_id"]): record
            for record in generation_report.get("fold_model_records", [])
        }
        generated_record = generation_records.get(fold_id, {})

        generation_provenance_match = (
            generated_record.get("model_sha256_verified") == actual_hash
            and generated_record.get("class_order") == CLASS_IDS
            and int(generated_record.get("heldout_observation_count", -1))
                == len(held_indices)
        )

        fold_check(
            "OOF generation provenance matches model",
            generation_provenance_match,
            f"generation hash and held-out count verified="
            f"{generation_provenance_match}",
        )

        fold_passed = all(fold_checks.values())

        fold_provenance_results.append({
            "fold_id": fold_id,
            "passed": bool(fold_passed),
            "checks": fold_checks,
            "model_path": str(model_path),
            "metadata_path": str(metadata_path),
            "model_sha256": actual_hash,
            "reconstructed_natural_training_rows": int(
                len(reconstructed_train_indices)
            ),
            "reconstructed_natural_training_class_counts":
                reconstructed_counts,
            "heldout_rows": int(len(held_indices)),
            "duplicate_exclusion_rows": int(len(duplicate_indices)),
        })

# ------------------------------------------------
# 6. Save validation report; never overwrite
# ------------------------------------------------

all_fold_provenance_passed = (
    len(fold_provenance_results) == N_FOLDS
    and all(item.get("passed") is True for item in fold_provenance_results)
)

all_checks_passed = (
    all(item["passed"] for item in checks.values())
    and all_fold_provenance_passed
)

report = {
    "report_id": "rf_oof_validation_report_v1",
    "created_utc": datetime.now(timezone.utc).isoformat(),
    "status": (
        "PASSED_OOF_COVERAGE_AND_PROVENANCE"
        if all_checks_passed
        else "BLOCKED_REVIEW_REQUIRED"
    ),
    "approved_for_rf_oof_handoff": bool(all_checks_passed),
    "candidate_plan": str(PLAN_PATH),
    "training_manifest": str(TRAIN_MANIFEST_PATH),
    "generation_report": str(GENERATION_REPORT_PATH),
    "duplicate_exclusion_artifact": str(EXCLUSION_PATH),
    "class_order": CLASS_IDS,
    "eligible_observations": int(len(eligible_indices)),
    "probability_shape": list(oof_probabilities.shape),
    "fold_counts": observed_fold_counts.tolist(),
    "probability_min": prob_min,
    "probability_max": prob_max,
    "checks": checks,
    "fold_provenance": fold_provenance_results,
    "issues": issues,
    "validation_accessed": False,
    "test_accessed": False,
    "models_trained": False,
    "existing_final_rf_modified": False,
    "limitations": [
        "Fold assignment is stratified random, not verified chronological/session-based.",
        "This report validates RF OOF artifacts only; it does not establish joint RF/LSTM ensemble readiness.",
        "Training indices are reconstructed from the persisted candidate assignment and duplicate exclusions and cross-checked against recorded row/class counts; individual training indices were not separately persisted by Section 5.16.3."
    ],
}

with REPORT_PATH.open("x", encoding="utf-8") as f:
    json.dump(report, f, indent=2)

print("\n" + "=" * 76)
print("5.16.5 RESULT")
print("=" * 76)
print("Status:", report["status"])
print("Approved for RF OOF handoff:", report["approved_for_rf_oof_handoff"])
print("Passed global checks:", sum(v["passed"] for v in checks.values()),
      "/", len(checks))
print("Fold provenance passed:",
      sum(x["passed"] for x in fold_provenance_results),
      "/", N_FOLDS)
print("Validation/Test arrays accessed: NO")
print("Models trained: NO")
print("Existing final RF modified: NO")
print("Report saved:", REPORT_PATH)

if not all_checks_passed:
    print("\nBLOCKING ISSUES:")
    for name, item in checks.items():
        if not item["passed"]:
            print(" -", name)
    for item in fold_provenance_results:
        if not item.get("passed"):
            print(f" - Fold {item['fold_id']} provenance validation")

============================================================================
5.16.5 — OOF COVERAGE AND PROVENANCE VALIDATION
============================================================================
[PASS] Training feature/target contract: X=(1814018, 32); y=(1814018,)
[PASS] Candidate plan identity: id=oof_fold_plan_candidate_v3; partition=Training only
[PASS] Training manifest completed: status=COMPLETED_ALL_FIVE_FOLDS; fold records=5
[PASS] Generation report status: OOF_PROBABILITIES_GENERATED_AND_VALIDATED
[PASS] No Validation/Test access during RF OOF generation: Generation report records both as False
[PASS] OOF array shapes: probabilities=(1814009, 9); indices=(1814009,); targets=(1814009,); fold_ids=(1814009,)
[PASS] Eligible observation indices: Saved indices match raw Training rows 9 through N-1
[PASS] OOF target alignment: Saved OOF targets match N04 y_train at saved observation indices
[PASS] All OOF probabilities finite: shape=(1814009, 9)
[PASS] Probability values within bounds: min=0.0; max=1.0
[PASS] Probability rows sum to one: Every row sums to 1 within tolerance
[PASS] Fold IDs match candidate assignment: Saved fold IDs match candidate v3 for every eligible observation
[PASS] Exactly-once OOF coverage: eligible=1,814,009; unique indices=1,814,009; fold counts=[362802, 362802, 362802, 362802, 362801]
[PASS] Exactly five unique fold model records: fold IDs=[0, 1, 2, 3, 4]

------------------------------------------------------------------------
FOLD 0 — MODEL AND TRAINING PROVENANCE
------------------------------------------------------------------------
  [PASS] Model and metadata files exist: model=rf3_fold_0.joblib; metadata=rf3_fold_0_metadata.json
  [PASS] Model SHA-256 matches manifest: verified=True
  [PASS] Fold metadata matches model and protocol: status=TRAINED; class_ids=[0, 1, 2, 3, 4, 5, 6, 7, 8]
  [PASS] Duplicate exclusion record exists: fold_0_duplicate_excluded_indices
  [PASS] Duplicate exclusion indices in range: count=157,022
  [PASS] Training/held-out target disjointness: training=1,294,185; held-out=362,802
  [PASS] Natural training class counts match metadata: reconstructed=[1064071, 65568, 59342, 4713, 1009, 1077, 12, 98388, 5]; recorded=[1064071, 65568, 59342, 4713, 1009, 1077, 12, 98388, 5]
  [PASS] Natural training row count matches metadata: reconstructed=1,294,185; recorded=1294185
  [PASS] Held-out row count matches metadata: reconstructed=362,802; recorded=362802
  [PASS] OOF generation provenance matches model: generation hash and held-out count verified=True

------------------------------------------------------------------------
FOLD 1 — MODEL AND TRAINING PROVENANCE
------------------------------------------------------------------------
  [PASS] Model and metadata files exist: model=rf3_fold_1.joblib; metadata=rf3_fold_1_metadata.json
  [PASS] Model SHA-256 matches manifest: verified=True
  [PASS] Fold metadata matches model and protocol: status=TRAINED; class_ids=[0, 1, 2, 3, 4, 5, 6, 7, 8]
  [PASS] Duplicate exclusion record exists: fold_1_duplicate_excluded_indices
  [PASS] Duplicate exclusion indices in range: count=157,378
  [PASS] Training/held-out target disjointness: training=1,293,829; held-out=362,802
  [PASS] Natural training class counts match metadata: reconstructed=[1063848, 65570, 59154, 4779, 1006, 1067, 12, 98388, 5]; recorded=[1063848, 65570, 59154, 4779, 1006, 1067, 12, 98388, 5]
  [PASS] Natural training row count matches metadata: reconstructed=1,293,829; recorded=1293829
  [PASS] Held-out row count matches metadata: reconstructed=362,802; recorded=362802
  [PASS] OOF generation provenance matches model: generation hash and held-out count verified=True

------------------------------------------------------------------------
FOLD 2 — MODEL AND TRAINING PROVENANCE
------------------------------------------------------------------------
  [PASS] Model and metadata files exist: model=rf3_fold_2.joblib; metadata=rf3_fold_2_metadata.json
  [PASS] Model SHA-256 matches manifest: verified=True
  [PASS] Fold metadata matches model and protocol: status=TRAINED; class_ids=[0, 1, 2, 3, 4, 5, 6, 7, 8]
  [PASS] Duplicate exclusion record exists: fold_2_duplicate_excluded_indices
  [PASS] Duplicate exclusion indices in range: count=157,163
  [PASS] Training/held-out target disjointness: training=1,294,044; held-out=362,802
  [PASS] Natural training class counts match metadata: reconstructed=[1064023, 65567, 59322, 4755, 1008, 1074, 12, 98278, 5]; recorded=[1064023, 65567, 59322, 4755, 1008, 1074, 12, 98278, 5]
  [PASS] Natural training row count matches metadata: reconstructed=1,294,044; recorded=1294044
  [PASS] Held-out row count matches metadata: reconstructed=362,802; recorded=362802
  [PASS] OOF generation provenance matches model: generation hash and held-out count verified=True

------------------------------------------------------------------------
FOLD 3 — MODEL AND TRAINING PROVENANCE
------------------------------------------------------------------------
  [PASS] Model and metadata files exist: model=rf3_fold_3.joblib; metadata=rf3_fold_3_metadata.json
  [PASS] Model SHA-256 matches manifest: verified=True
  [PASS] Fold metadata matches model and protocol: status=TRAINED; class_ids=[0, 1, 2, 3, 4, 5, 6, 7, 8]
  [PASS] Duplicate exclusion record exists: fold_3_duplicate_excluded_indices
  [PASS] Duplicate exclusion indices in range: count=156,172
  [PASS] Training/held-out target disjointness: training=1,295,035; held-out=362,802
  [PASS] Natural training class counts match metadata: reconstructed=[1064987, 65570, 59082, 4813, 1003, 1078, 12, 98486, 4]; recorded=[1064987, 65570, 59082, 4813, 1003, 1078, 12, 98486, 4]
  [PASS] Natural training row count matches metadata: reconstructed=1,295,035; recorded=1295035
  [PASS] Held-out row count matches metadata: reconstructed=362,802; recorded=362802
  [PASS] OOF generation provenance matches model: generation hash and held-out count verified=True

------------------------------------------------------------------------
FOLD 4 — MODEL AND TRAINING PROVENANCE
------------------------------------------------------------------------
  [PASS] Model and metadata files exist: model=rf3_fold_4.joblib; metadata=rf3_fold_4_metadata.json
  [PASS] Model SHA-256 matches manifest: verified=True
  [PASS] Fold metadata matches model and protocol: status=TRAINED; class_ids=[0, 1, 2, 3, 4, 5, 6, 7, 8]
  [PASS] Duplicate exclusion record exists: fold_4_duplicate_excluded_indices
  [PASS] Duplicate exclusion indices in range: count=157,281
  [PASS] Training/held-out target disjointness: training=1,293,927; held-out=362,801
  [PASS] Natural training class counts match metadata: reconstructed=[1063884, 65568, 59118, 4761, 1007, 1068, 12, 98504, 5]; recorded=[1063884, 65568, 59118, 4761, 1007, 1068, 12, 98504, 5]
  [PASS] Natural training row count matches metadata: reconstructed=1,293,927; recorded=1293927
  [PASS] Held-out row count matches metadata: reconstructed=362,801; recorded=362801
  [PASS] OOF generation provenance matches model: generation hash and held-out count verified=True

============================================================================
5.16.5 RESULT
============================================================================
Status: PASSED_OOF_COVERAGE_AND_PROVENANCE
Approved for RF OOF handoff: True
Passed global checks: 14 / 14
Fold provenance passed: 5 / 5
Validation/Test arrays accessed: NO
Models trained: NO
Existing final RF modified: NO
Report saved: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/oof/rf_oof_validation_report_v1.json

### 5.16.6 — Training-Only Validation Inference

Generate class probabilities for the eligible N04 Validation observations using the existing final RF-3 model, which was fitted on Training data only. Align the RF predictions with the LSTM sequence-target convention by excluding the first \(L-1=9\) Validation rows.

The inference process is read-only with respect to the existing model, model metadata, handoff manifest, and evaluation artifacts. It does not fit or retrain a model, perform resampling, or access Test data. Persist the probabilities, Validation observation indices, targets, class order, and provenance in a new dedicated ensemble-validation directory. Validate probability integrity, observation alignment, and unchanged SHA-256 hashes of protected RF artifacts before marking the subsection complete.

In [30]:
# ================================================================
# 5.16.6 — TRAINING-ONLY VALIDATION INFERENCE
# Self-contained recovery; existing final RF is inference-only.
# No fitting, resampling, Test access, or protected-file writes.
# ================================================================

import gc
import json
import hashlib
from pathlib import Path
from datetime import datetime, timezone

import joblib
import numpy as np

# ------------------------------------------------
# 1. RECOVER PERSISTED ARTIFACTS AND DEFINE PATHS
# ------------------------------------------------

ROOT = Path(
    "/content/drive/MyDrive/AI-Network-Intrusion-Detection-System"
)

N04 = ROOT / "outputs" / "model_preparation_v2"

RF_HANDOFF_PATH = (
    ROOT / "outputs"
    / "random_forest_model_development"
    / "rf_handoff_manifest.json"
)

X_VAL_PATH = (
    N04 / "feature_scaling" / "X_validation_scaled.npy"
)
Y_VAL_PATH = (
    N04 / "model_ready_targets" / "y_validation.npy"
)

RF_ENSEMBLE_DIR = (
    ROOT / "outputs" / "ensemble_model_development"
    / "rf_fold_models_v1"
)
VAL_OUT_DIR = RF_ENSEMBLE_DIR / "validation"

VAL_PROB_PATH = VAL_OUT_DIR / "rf_validation_probabilities.npy"
VAL_INDEX_PATH = VAL_OUT_DIR / "rf_validation_observation_indices.npy"
VAL_TARGET_PATH = VAL_OUT_DIR / "rf_validation_targets.npy"
VAL_REPORT_PATH = VAL_OUT_DIR / "rf_validation_inference_report_v1.json"

CLASS_IDS = list(range(9))
EXPECTED_CLASS_MAPPING = {
    "0": "BENIGN",
    "1": "DDoS",
    "2": "Port Scan",
    "3": "Brute Force",
    "4": "Bot",
    "5": "Web Attack",
    "6": "Infiltration",
    "7": "DoS",
    "8": "Heartbleed",
}

SEQUENCE_LENGTH = 10
OFFSET = SEQUENCE_LENGTH - 1
BATCH_SIZE = 20_000
PROB_TOLERANCE = 1e-5

if not ROOT.is_dir():
    raise FileNotFoundError(
        f"Project root unavailable: {ROOT}. Mount Google Drive first."
    )

for path in (RF_HANDOFF_PATH, X_VAL_PATH, Y_VAL_PATH):
    if not path.is_file():
        raise FileNotFoundError(f"Required artifact missing: {path}")

with RF_HANDOFF_PATH.open("r", encoding="utf-8") as f:
    handoff = json.load(f)

if handoff.get("handoff_status") != "ready_for_validation":
    raise RuntimeError(
        "Persisted RF handoff is not ready_for_validation. "
        "Inference stopped."
    )

# Recover model and metadata paths from the persisted handoff.
FINAL_RF_PATH = Path(handoff["final_model"]["path"])
FINAL_RF_METADATA_PATH = Path(
    handoff["final_model"]["metadata_path"]
)

if not FINAL_RF_PATH.is_absolute():
    FINAL_RF_PATH = ROOT / FINAL_RF_PATH

if not FINAL_RF_METADATA_PATH.is_absolute():
    FINAL_RF_METADATA_PATH = ROOT / FINAL_RF_METADATA_PATH

# N04 feature metadata path comes from the persisted handoff.
n04_metadata_path = Path(
    handoff["n04_dependencies"]["model_ready_feature_metadata"]
)
if not n04_metadata_path.is_absolute():
    n04_metadata_path = ROOT / n04_metadata_path

protected_paths = [
    FINAL_RF_PATH,
    FINAL_RF_METADATA_PATH,
    RF_HANDOFF_PATH,
    n04_metadata_path,
]

for path in protected_paths:
    if not path.is_file():
        raise FileNotFoundError(
            f"Required/protected artifact missing: {path}"
        )

if not RF_ENSEMBLE_DIR.is_dir():
    raise FileNotFoundError(
        "Expected ensemble directory does not exist:\n"
        f"{RF_ENSEMBLE_DIR}"
    )

# Refuse to overwrite outputs from any previous run.
if VAL_OUT_DIR.exists():
    raise FileExistsError(
        "Validation output directory already exists. Nothing was "
        "overwritten. Inspect or explicitly archive the previous run first:\n"
        f"{VAL_OUT_DIR}"
    )

with n04_metadata_path.open("r", encoding="utf-8") as f:
    n04_metadata = json.load(f)

RF_FEATURE_ORDER = n04_metadata.get("final_feature_order")

if (
    not isinstance(RF_FEATURE_ORDER, list)
    or len(RF_FEATURE_ORDER) != 32
    or len(set(RF_FEATURE_ORDER)) != 32
):
    raise RuntimeError(
        "N04 metadata must provide 32 unique feature names in "
        "final_feature_order. No inference performed."
    )

with FINAL_RF_METADATA_PATH.open("r", encoding="utf-8") as f:
    final_rf_metadata = json.load(f)

# Validate the actual persisted RF metadata schema.
if final_rf_metadata.get("class_count") != 9:
    raise RuntimeError("RF metadata class_count is not 9.")

if final_rf_metadata.get("class_mapping") != EXPECTED_CLASS_MAPPING:
    raise RuntimeError(
        "RF metadata class_mapping does not match the established taxonomy."
    )

if final_rf_metadata.get("feature_count") != len(RF_FEATURE_ORDER):
    raise RuntimeError(
        "RF metadata feature_count does not match N04 feature order."
    )

if final_rf_metadata.get("feature_order") != RF_FEATURE_ORDER:
    raise RuntimeError(
        "RF metadata feature_order does not match N04 final_feature_order."
    )

print("Persisted RF handoff:", RF_HANDOFF_PATH)
print("Final RF model:", FINAL_RF_PATH)
print("Final RF metadata:", FINAL_RF_METADATA_PATH)
print("N04 feature order recovered:", len(RF_FEATURE_ORDER))
print("RF metadata class mapping and feature order: PASS")
print("Validation arrays exist:", X_VAL_PATH.is_file(), Y_VAL_PATH.is_file())

# ------------------------------------------------
# 2. HASH PROTECTED FILES BEFORE INFERENCE
# ------------------------------------------------

def sha256_file(path, chunk_size=1024 * 1024):
    digest = hashlib.sha256()
    with Path(path).open("rb") as f:
        for block in iter(lambda: f.read(chunk_size), b""):
            digest.update(block)
    return digest.hexdigest()

protected_hashes_before = {
    str(path): sha256_file(path) for path in protected_paths
}

# ------------------------------------------------
# 3. LOAD VALIDATION DATA ONLY
# ------------------------------------------------

X_val = np.load(X_VAL_PATH, mmap_mode="r", allow_pickle=False)
y_val = np.load(Y_VAL_PATH, mmap_mode="r", allow_pickle=False)

if X_val.ndim != 2 or X_val.shape[1] != len(RF_FEATURE_ORDER):
    raise ValueError(
        f"Validation feature contract mismatch: {X_val.shape}"
    )

if y_val.ndim != 1 or len(y_val) != len(X_val):
    raise ValueError(
        f"Validation target contract mismatch: X={X_val.shape}, y={y_val.shape}"
    )

if X_val.shape[0] <= OFFSET:
    raise ValueError(
        "Validation partition is too small for length-10 target alignment."
    )

if not np.issubdtype(X_val.dtype, np.floating):
    raise TypeError(f"Unexpected Validation feature dtype: {X_val.dtype}")

if not np.issubdtype(y_val.dtype, np.integer):
    raise TypeError(f"Unexpected Validation target dtype: {y_val.dtype}")

if not np.isfinite(X_val).all():
    raise ValueError("Validation features contain non-finite values.")

if not np.isin(y_val, CLASS_IDS).all():
    raise ValueError(
        f"Unexpected Validation classes: {np.unique(y_val).tolist()}"
    )

# Match the LSTM length-10 target convention:
# sequence starting at row 0 predicts the label at row 9.
validation_indices = np.arange(OFFSET, len(X_val), dtype=np.int64)
validation_targets = np.asarray(
    y_val[validation_indices], dtype=np.int64
)

# ------------------------------------------------
# 4. LOAD FINAL RF MODEL FOR INFERENCE ONLY
# ------------------------------------------------

model = joblib.load(FINAL_RF_PATH)

if not hasattr(model, "predict_proba") or not hasattr(model, "classes_"):
    raise TypeError("Persisted RF model lacks predict_proba/classes_.")

if np.asarray(model.classes_).astype(int).tolist() != CLASS_IDS:
    raise RuntimeError(
        f"RF model class order mismatch: {model.classes_.tolist()}"
    )

if int(getattr(model, "n_features_in_", -1)) != len(RF_FEATURE_ORDER):
    raise RuntimeError("RF model input feature count mismatch.")

print("\n5.16.6 — TRAINING-ONLY VALIDATION INFERENCE")
print("Validation rows:", f"{len(X_val):,}")
print("Eligible aligned rows:", f"{len(validation_indices):,}")
print("Classes:", CLASS_IDS)
print("Model fitting: NO | Resampling: NO | Test access: NO")

# ------------------------------------------------
# 5. GENERATE PROBABILITIES IN BATCHES
# ------------------------------------------------

VAL_OUT_DIR.mkdir(parents=False, exist_ok=False)

try:
    probabilities = np.lib.format.open_memmap(
        VAL_PROB_PATH,
        mode="w+",
        dtype=np.float32,
        shape=(len(validation_indices), len(CLASS_IDS)),
    )

    for start in range(0, len(validation_indices), BATCH_SIZE):
        end = min(start + BATCH_SIZE, len(validation_indices))
        batch_indices = validation_indices[start:end]
        batch_X = np.asarray(X_val[batch_indices], dtype=np.float32)

        batch_probabilities = model.predict_proba(batch_X)

        # RandomForest predict_proba columns follow model.classes_.
        # The exact class-order guard above verifies they are 0–8.
        if batch_probabilities.shape != (
            len(batch_indices), len(CLASS_IDS)
        ):
            raise RuntimeError(
                f"Unexpected probability shape at batch {start}:{end}: "
                f"{batch_probabilities.shape}"
            )

        if not np.isfinite(batch_probabilities).all():
            raise RuntimeError(
                f"Non-finite probabilities at batch {start}:{end}."
            )

        if (
            (batch_probabilities < -PROB_TOLERANCE).any()
            or (batch_probabilities > 1.0 + PROB_TOLERANCE).any()
        ):
            raise RuntimeError(
                f"Probability values outside [0, 1] at batch {start}:{end}."
            )

        batch_sums = batch_probabilities.sum(axis=1)
        if not np.allclose(
            batch_sums, 1.0, rtol=0.0, atol=PROB_TOLERANCE
        ):
            raise RuntimeError(
                f"Probability rows do not sum to one at batch {start}:{end}."
            )

        probabilities[start:end] = batch_probabilities
        print(
            f"Predicted rows {start:,}–{end - 1:,} / "
            f"{len(validation_indices):,}"
        )

    probabilities.flush()
    del probabilities
    gc.collect()

    np.save(VAL_INDEX_PATH, validation_indices, allow_pickle=False)
    np.save(VAL_TARGET_PATH, validation_targets, allow_pickle=False)

    # ------------------------------------------------
    # 6. RELOAD AND VALIDATE SAVED OUTPUTS
    # ------------------------------------------------

    saved_probabilities = np.load(
        VAL_PROB_PATH, mmap_mode="r", allow_pickle=False
    )
    saved_indices = np.load(VAL_INDEX_PATH, allow_pickle=False)
    saved_targets = np.load(VAL_TARGET_PATH, allow_pickle=False)

    shape_ok = (
        saved_probabilities.shape == (len(validation_indices), 9)
        and np.array_equal(saved_indices, validation_indices)
        and np.array_equal(saved_targets, validation_targets)
    )

    finite_ok = bool(np.isfinite(saved_probabilities).all())

    if finite_ok:
        probability_min = float(saved_probabilities.min())
        probability_max = float(saved_probabilities.max())
        row_sums = np.asarray(
            saved_probabilities.sum(axis=1), dtype=np.float64
        )
        bounds_ok = (
            probability_min >= -PROB_TOLERANCE
            and probability_max <= 1.0 + PROB_TOLERANCE
        )
        sums_ok = bool(
            np.allclose(
                row_sums, 1.0, rtol=0.0, atol=PROB_TOLERANCE
            )
        )
    else:
        probability_min = probability_max = None
        bounds_ok = sums_ok = False

    protected_hashes_after = {
        str(path): sha256_file(path) for path in protected_paths
    }
    protected_unchanged = (
        protected_hashes_before == protected_hashes_after
    )

    checks = {
        "metadata_class_mapping_valid": (
            final_rf_metadata.get("class_mapping")
            == EXPECTED_CLASS_MAPPING
        ),
        "metadata_feature_order_valid": (
            final_rf_metadata.get("feature_order") == RF_FEATURE_ORDER
        ),
        "model_class_order_valid": (
            np.asarray(model.classes_).astype(int).tolist() == CLASS_IDS
        ),
        "output_shapes_and_alignment": bool(shape_ok),
        "probabilities_finite": bool(finite_ok),
        "probability_bounds_valid": bool(bounds_ok),
        "probability_rows_sum_to_one": bool(sums_ok),
        "protected_rf_artifacts_unchanged": bool(protected_unchanged),
    }

    passed = all(checks.values())

    report = {
        "report_id": "rf_validation_inference_report_v1",
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "status": (
            "PASSED_TRAINING_ONLY_VALIDATION_INFERENCE"
            if passed else "BLOCKED_REVIEW_REQUIRED"
        ),
        "approved_for_ensemble_validation_handoff": bool(passed),
        "inference_method": "predict_proba; existing final RF; no fitting",
        "model_training_partition": "Training only",
        "model_path": str(FINAL_RF_PATH),
        "model_sha256_before": protected_hashes_before[str(FINAL_RF_PATH)],
        "model_sha256_after": protected_hashes_after[str(FINAL_RF_PATH)],
        "model_metadata_path": str(FINAL_RF_METADATA_PATH),
        "handoff_manifest_path": str(RF_HANDOFF_PATH),
        "n04_feature_metadata_path": str(n04_metadata_path),
        "validation_feature_path": str(X_VAL_PATH),
        "validation_target_path": str(Y_VAL_PATH),
        "validation_full_rows": int(len(X_val)),
        "excluded_initial_validation_rows": int(OFFSET),
        "eligible_validation_observations": int(len(validation_indices)),
        "class_order": CLASS_IDS,
        "class_mapping": EXPECTED_CLASS_MAPPING,
        "feature_count": len(RF_FEATURE_ORDER),
        "probability_shape": list(saved_probabilities.shape),
        "probability_min": probability_min,
        "probability_max": probability_max,
        "checks": checks,
        "outputs": {
            "probabilities": str(VAL_PROB_PATH),
            "observation_indices": str(VAL_INDEX_PATH),
            "targets": str(VAL_TARGET_PATH),
        },
        "validation_accessed": True,
        "test_accessed": False,
        "model_fitted": False,
        "resampling_performed": False,
        "existing_final_rf_modified": False,
        "limitations": [
            "Validation inference is not OOF inference.",
            "The first nine Validation rows are excluded for LSTM target alignment.",
            "Chronological and session-level independence are not established.",
            "The existing final RF was trained on Training only, according to its persisted metadata.",
            "The handoff and model artifacts are hash-checked before and after inference.",
        ],
    }

    with VAL_REPORT_PATH.open("x", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

    print("\n5.16.6 RESULT")
    print("Status:", report["status"])
    print("Checks:", checks)
    print("Probability shape:", saved_probabilities.shape)
    print("Report:", VAL_REPORT_PATH)
    print("Test arrays accessed: NO")
    print("Existing final RF modified: NO")

    if not passed:
        raise RuntimeError(
            "5.16.6 validation failed. Preserve the output directory "
            "and report for review; do not proceed to 5.16.7."
        )

finally:
    gc.collect()

Persisted RF handoff: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/rf_handoff_manifest.json
Final RF model: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models/random_forest/final_random_forest.joblib
Final RF metadata: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/final_model/rf_final_model_metadata.json
N04 feature order recovered: 32
RF metadata class mapping and feature order: PASS
Validation arrays exist: True True

5.16.6 — TRAINING-ONLY VALIDATION INFERENCE
Validation rows: 451,215
Eligible aligned rows: 451,206
Classes: [0, 1, 2, 3, 4, 5, 6, 7, 8]
Model fitting: NO | Resampling: NO | Test access: NO
Predicted rows 0–19,999 / 451,206
Predicted rows 20,000–39,999 / 451,206
Predicted rows 40,000–59,999 / 451,206
Predicted rows 60,000–79,999 / 451,206
Predicted rows 80,000–99,999 / 451,206
Predicted rows 100,000–119,999 / 451,206
Predicted rows 120,000–139,999 / 451,206
Predicted rows 140,000–159,999 / 451,206
Predicted rows 160,000–179,999 / 451,206
Predicted rows 180,000–199,999 / 451,206
Predicted rows 200,000–219,999 / 451,206
Predicted rows 220,000–239,999 / 451,206
Predicted rows 240,000–259,999 / 451,206
Predicted rows 260,000–279,999 / 451,206
Predicted rows 280,000–299,999 / 451,206
Predicted rows 300,000–319,999 / 451,206
Predicted rows 320,000–339,999 / 451,206
Predicted rows 340,000–359,999 / 451,206
Predicted rows 360,000–379,999 / 451,206
Predicted rows 380,000–399,999 / 451,206
Predicted rows 400,000–419,999 / 451,206
Predicted rows 420,000–439,999 / 451,206
Predicted rows 440,000–451,205 / 451,206

5.16.6 RESULT
Status: PASSED_TRAINING_ONLY_VALIDATION_INFERENCE
Checks: {'metadata_class_mapping_valid': True, 'metadata_feature_order_valid': True, 'model_class_order_valid': True, 'output_shapes_and_alignment': True, 'probabilities_finite': True, 'probability_bounds_valid': True, 'probability_rows_sum_to_one': True, 'protected_rf_artifacts_unchanged': True}
Probability shape: (451206, 9)
Report: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/validation/rf_validation_inference_report_v1.json
Test arrays accessed: NO
Existing final RF modified: NO

In [29]:
import json

print("FINAL RF METADATA — ACTUAL SCHEMA")
print(json.dumps(final_rf_metadata, indent=2)[:12000])

print("\nHANDOFF MANIFEST — FINAL MODEL SECTION")
print(json.dumps(
    handoff.get("final_model", {}),
    indent=2
))

print("\nHANDOFF MANIFEST — CLASS/FEATURE-RELATED FIELDS")
for key, value in handoff.items():
    if any(term in key.lower() for term in ("class", "feature", "taxonomy")):
        print(f"{key}: {value}")

FINAL RF METADATA — ACTUAL SCHEMA
{
  "strategy_id": "RF-3",
  "strategy_name": "Controlled Random Oversampling",
  "strategy": {
    "strategy_id": "RF-3",
    "strategy_name": "Controlled Random Oversampling",
    "class_weight": null,
    "resampling": true,
    "synthetic_sampling": false,
    "training_partition": "Training",
    "evaluation_partition": "Validation",
    "test_used": false
  },
  "controlled_oversampling_configuration": {
    "minimum_training_support": 10,
    "oversampling_multiplier": 5,
    "maximum_target_per_class": 50000,
    "majority_downsampling": false,
    "heartbleed_oversampling": false,
    "infiltration_oversampling_eligible": true
  },
  "common_random_forest_configuration": {
    "n_estimators": 100,
    "max_features": "sqrt",
    "max_depth": null,
    "bootstrap": true,
    "n_jobs": -1,
    "random_state": 42
  },
  "random_seed": 42,
  "feature_count": 32,
  "class_count": 9,
  "class_mapping": {
    "0": "BENIGN",
    "1": "DDoS",
    "2": "Port Scan",
    "3": "Brute Force",
    "4": "Bot",
    "5": "Web Attack",
    "6": "Infiltration",
    "7": "DoS",
    "8": "Heartbleed"
  },
  "feature_order": [
    "ECE Flag Count",
    "FIN Flag Count",
    "Fwd PSH Flags",
    "URG Flag Count",
    "Down/Up Ratio",
    "PSH Flag Count",
    "ACK Flag Count",
    "act_data_pkt_fwd",
    "Fwd Header Length",
    "Avg Fwd Segment Size",
    "Fwd Packet Length Min",
    "Bwd Header Length",
    "Average Packet Size",
    "Bwd Packet Length Min",
    "Fwd Packet Length Std",
    "Bwd Packet Length Std",
    "Active Std",
    "Bwd IAT Min",
    "Idle Std",
    "Flow IAT Min",
    "Fwd IAT Min",
    "Bwd Packets/s",
    "Active Max",
    "Flow Bytes/s",
    "Flow Duration",
    "Bwd IAT Mean",
    "Bwd IAT Std",
    "Fwd IAT Mean",
    "Flow IAT Std",
    "min_seg_size_forward",
    "Fwd IAT Std",
    "Destination Port"
  ],
  "training_observations": 1814018,
  "final_oversampled_training_observations": 1862014,
  "additional_oversampled_observations": 47996,
  "training_feature_shape": [
    1814018,
    32
  ],
  "final_oversampled_training_feature_shape": [
    1862014,
    32
  ],
  "validation_observations": 451215,
  "training_feature_dtype": "float32",
  "training_target_dtype": "int64",
  "final_oversampled_training_feature_dtype": "float32",
  "final_oversampled_training_target_dtype": "int64",
  "training_time_seconds": 645.0093993660012,
  "available_system_ram_before_fit_gb": 9.441608428955078,
  "available_system_ram_after_fit_gb": 9.44500732421875,
  "process_ram_before_fit_gb": 2.201019287109375,
  "process_ram_after_fit_gb": 2.185314178466797,
  "process_ram_delta_gb": -0.015705108642578125,
  "training_partition": "Training",
  "validation_used_for_fitting": false,
  "validation_predictions_generated": false,
  "independent_test_used": false,
  "independent_test_predictions_generated": false,
  "resampling_used": true,
  "synthetic_sampling_used": false,
  "majority_downsampling_used": false,
  "heartbleed_oversampling": false,
  "infiltration_oversampling_eligible": true,
  "strategy_selected": true,
  "model_role": "Final Random Forest Model",
  "final_model": true,
  "model_artifact": "/content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models/random_forest/final_random_forest.joblib",
  "metadata_artifact": "/content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/final_model/rf_final_model_metadata.json",
  "persistence_completed": true
}

HANDOFF MANIFEST — FINAL MODEL SECTION
{
  "path": "/content/drive/MyDrive/AI-Network-Intrusion-Detection-System/trained_models/random_forest/final_random_forest.joblib",
  "artifact_type": "joblib",
  "metadata_path": "/content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/random_forest_model_development/final_model/rf_final_model_metadata.json"
}

HANDOFF MANIFEST — CLASS/FEATURE-RELATED FIELDS

### 5.16.7 — Ensemble Handoff and Readiness Gate

Validate and publish the RF-3 ensemble handoff using the persisted fold-training manifest, OOF generation and validation reports, OOF probability arrays, and Training-only Validation inference artifacts.

The readiness gate checks artifact completeness, report approval statuses, class order, probability dimensions and integrity, exactly-once OOF coverage, observation-index alignment, and the recorded model provenance. It also verifies that the final RF model's hash matches the values recorded during Section 5.16.6.

This subsection does not fit or modify models, regenerate predictions, or access Test data. It writes only new handoff and readiness reports to the dedicated RF ensemble-preparation directory. A failed check blocks readiness. Chronological and session-level independence remain unverified and are explicitly recorded as limitations.

In [31]:
# ================================================================
# 5.16.7 — ENSEMBLE HANDOFF AND READINESS GATE
# Read-only gate; no model fitting, predictions, or Test access.
# ================================================================

import json
import hashlib
from pathlib import Path
from datetime import datetime, timezone

import numpy as np

# ------------------------------------------------
# 1. RESOLVE PERSISTED ARTIFACT PATHS
# ------------------------------------------------

ROOT = Path(
    "/content/drive/MyDrive/AI-Network-Intrusion-Detection-System"
)

RF_DIR = (
    ROOT / "outputs" / "ensemble_model_development"
    / "rf_fold_models_v1"
)
OOF_DIR = RF_DIR / "oof"
VAL_DIR = RF_DIR / "validation"

EXP_DIR = (
    ROOT / "outputs" / "ensemble_model_development"
    / "experiments"
)

PLAN_PATH = EXP_DIR / "oof_fold_plan_candidate_v3.json"
TRAIN_MANIFEST_PATH = RF_DIR / "rf_fold_training_manifest_v1.json"
GENERATION_REPORT_PATH = OOF_DIR / "rf_oof_generation_report_v1.json"
OOF_REPORT_PATH = OOF_DIR / "rf_oof_validation_report_v1.json"
VAL_REPORT_PATH = VAL_DIR / "rf_validation_inference_report_v1.json"

OOF_PROB_PATH = OOF_DIR / "rf_oof_probabilities.npy"
OOF_INDEX_PATH = OOF_DIR / "rf_oof_observation_indices.npy"
OOF_TARGET_PATH = OOF_DIR / "rf_oof_targets.npy"
OOF_FOLD_PATH = OOF_DIR / "rf_oof_fold_ids.npy"

VAL_PROB_PATH = VAL_DIR / "rf_validation_probabilities.npy"
VAL_INDEX_PATH = VAL_DIR / "rf_validation_observation_indices.npy"
VAL_TARGET_PATH = VAL_DIR / "rf_validation_targets.npy"

# Read the actual final model paths from the persisted RF handoff.
RF_HANDOFF_PATH = (
    ROOT / "outputs" / "random_forest_model_development"
    / "rf_handoff_manifest.json"
)

if not RF_HANDOFF_PATH.is_file():
    raise FileNotFoundError(
        f"Persisted RF handoff is missing: {RF_HANDOFF_PATH}"
    )

with RF_HANDOFF_PATH.open("r", encoding="utf-8") as f:
    RF_HANDOFF = json.load(f)

if RF_HANDOFF.get("handoff_status") != "ready_for_validation":
    raise RuntimeError(
        "Original RF handoff is not ready_for_validation. "
        "Readiness gate stopped."
    )

FINAL_RF_PATH = Path(RF_HANDOFF["final_model"]["path"])
FINAL_RF_METADATA_PATH = Path(
    RF_HANDOFF["final_model"]["metadata_path"]
)

if not FINAL_RF_PATH.is_absolute():
    FINAL_RF_PATH = ROOT / FINAL_RF_PATH
if not FINAL_RF_METADATA_PATH.is_absolute():
    FINAL_RF_METADATA_PATH = ROOT / FINAL_RF_METADATA_PATH

N04_FEATURE_METADATA_PATH = Path(
    RF_HANDOFF["n04_dependencies"]["model_ready_feature_metadata"]
)
if not N04_FEATURE_METADATA_PATH.is_absolute():
    N04_FEATURE_METADATA_PATH = ROOT / N04_FEATURE_METADATA_PATH

HANDOFF_OUTPUT_PATH = RF_DIR / "rf_ensemble_handoff_manifest.json"
READINESS_OUTPUT_PATH = RF_DIR / "rf_ensemble_readiness_report.json"

# Never overwrite prior handoff outputs.
if HANDOFF_OUTPUT_PATH.exists() or READINESS_OUTPUT_PATH.exists():
    raise FileExistsError(
        "A 5.16.7 handoff/readiness output already exists. "
        "No existing file was overwritten. Review or version the "
        "existing outputs before rerunning this subsection."
    )

CLASS_IDS = list(range(9))
EXPECTED_CLASS_MAPPING = {
    "0": "BENIGN",
    "1": "DDoS",
    "2": "Port Scan",
    "3": "Brute Force",
    "4": "Bot",
    "5": "Web Attack",
    "6": "Infiltration",
    "7": "DoS",
    "8": "Heartbleed",
}
TOLERANCE = 1e-5

# ------------------------------------------------
# 2. HELPERS AND REQUIRED-FILE GATE
# ------------------------------------------------

def sha256_file(path, chunk_size=1024 * 1024):
    digest = hashlib.sha256()
    with Path(path).open("rb") as f:
        for block in iter(lambda: f.read(chunk_size), b""):
            digest.update(block)
    return digest.hexdigest()


required_paths = [
    PLAN_PATH,
    TRAIN_MANIFEST_PATH,
    GENERATION_REPORT_PATH,
    OOF_REPORT_PATH,
    VAL_REPORT_PATH,
    OOF_PROB_PATH,
    OOF_INDEX_PATH,
    OOF_TARGET_PATH,
    OOF_FOLD_PATH,
    VAL_PROB_PATH,
    VAL_INDEX_PATH,
    VAL_TARGET_PATH,
    FINAL_RF_PATH,
    FINAL_RF_METADATA_PATH,
    RF_HANDOFF_PATH,
    N04_FEATURE_METADATA_PATH,
]

missing_paths = [str(p) for p in required_paths if not p.is_file()]
if missing_paths:
    raise FileNotFoundError(
        "5.16.7 cannot proceed; required persisted artifacts are missing:\n"
        + "\n".join(missing_paths)
    )


def load_json(path):
    with Path(path).open("r", encoding="utf-8") as f:
        return json.load(f)


plan = load_json(PLAN_PATH)
training_manifest = load_json(TRAIN_MANIFEST_PATH)
generation_report = load_json(GENERATION_REPORT_PATH)
oof_report = load_json(OOF_REPORT_PATH)
validation_report = load_json(VAL_REPORT_PATH)
final_rf_metadata = load_json(FINAL_RF_METADATA_PATH)

# ------------------------------------------------
# 3. REPORT STATUS AND PROVENANCE CHECKS
# ------------------------------------------------

checks = {}

checks["candidate_plan_identity"] = (
    plan.get("candidate_id") == "oof_fold_plan_candidate_v3"
    or plan.get("plan_id") == "oof_fold_plan_candidate_v3"
    or "oof_fold_plan_candidate_v3" in str(PLAN_PATH)
)

checks["five_fold_training_manifest_complete"] = (
    training_manifest.get("status") == "COMPLETED_ALL_FIVE_FOLDS"
    and len(training_manifest.get("folds", training_manifest.get("fold_records", []))) == 5
)

checks["oof_generation_passed"] = (
    generation_report.get("status")
    == "OOF_PROBABILITIES_GENERATED_AND_VALIDATED"
    and generation_report.get("validation_test_accessed") is not True
    and generation_report.get("test_accessed") is False
)

checks["oof_coverage_and_provenance_passed"] = (
    oof_report.get("status") == "PASSED_OOF_COVERAGE_AND_PROVENANCE"
    and oof_report.get("approved_for_rf_oof_handoff") is True
)

checks["validation_inference_passed"] = (
    validation_report.get("status")
    == "PASSED_TRAINING_ONLY_VALIDATION_INFERENCE"
    and validation_report.get("approved_for_ensemble_validation_handoff") is True
    and validation_report.get("test_accessed") is False
    and validation_report.get("model_fitted") is False
    and validation_report.get("resampling_performed") is False
)

# ------------------------------------------------
# 4. LOAD AND VALIDATE OOF ARTIFACTS
# ------------------------------------------------

oof_prob = np.load(OOF_PROB_PATH, mmap_mode="r", allow_pickle=False)
oof_indices = np.load(OOF_INDEX_PATH, allow_pickle=False)
oof_targets = np.load(OOF_TARGET_PATH, allow_pickle=False)
oof_fold_ids = np.load(OOF_FOLD_PATH, allow_pickle=False)

N04 = ROOT / "outputs" / "model_preparation_v2"
Y_TRAIN_PATH = N04 / "model_ready_targets" / "y_train.npy"
if not Y_TRAIN_PATH.is_file():
    raise FileNotFoundError(
        f"Training target artifact missing: {Y_TRAIN_PATH}"
    )
y_train = np.load(Y_TRAIN_PATH, mmap_mode="r", allow_pickle=False)

expected_oof_count = len(y_train) - 9
expected_indices = np.arange(9, len(y_train), dtype=np.int64)

checks["oof_shapes_and_class_dimension"] = (
    oof_prob.shape == (expected_oof_count, 9)
    and oof_indices.shape == (expected_oof_count,)
    and oof_targets.shape == (expected_oof_count,)
    and oof_fold_ids.shape == (expected_oof_count,)
)

checks["oof_indices_exactly_cover_eligible_training_rows"] = (
    np.array_equal(oof_indices, expected_indices)
    and len(np.unique(oof_indices)) == expected_oof_count
)

checks["oof_targets_match_n04_training_labels"] = (
    np.array_equal(oof_targets, np.asarray(y_train[oof_indices]))
)

checks["oof_fold_ids_valid"] = (
    np.isin(oof_fold_ids, np.arange(5)).all()
    and np.array_equal(
        np.bincount(oof_fold_ids.astype(np.int64), minlength=5),
        np.array([362802, 362802, 362802, 362802, 362801]),
    )
)

oof_finite = bool(np.isfinite(oof_prob).all())
checks["oof_probabilities_finite"] = oof_finite

if oof_finite:
    oof_min = float(oof_prob.min())
    oof_max = float(oof_prob.max())
    oof_row_sums_ok = bool(
        np.allclose(
            np.asarray(oof_prob.sum(axis=1), dtype=np.float64),
            1.0,
            rtol=0.0,
            atol=TOLERANCE,
        )
    )
else:
    oof_min = oof_max = None
    oof_row_sums_ok = False

checks["oof_probabilities_within_bounds"] = (
    oof_finite
    and oof_min >= -TOLERANCE
    and oof_max <= 1.0 + TOLERANCE
)
checks["oof_probability_rows_sum_to_one"] = oof_row_sums_ok

del y_train

# ------------------------------------------------
# 5. LOAD AND VALIDATE VALIDATION ARTIFACTS
# ------------------------------------------------

val_prob = np.load(VAL_PROB_PATH, mmap_mode="r", allow_pickle=False)
val_indices = np.load(VAL_INDEX_PATH, allow_pickle=False)
val_targets = np.load(VAL_TARGET_PATH, allow_pickle=False)

Y_VAL_PATH = N04 / "model_ready_targets" / "y_validation.npy"
if not Y_VAL_PATH.is_file():
    raise FileNotFoundError(
        f"Validation target artifact missing: {Y_VAL_PATH}"
    )
y_val = np.load(Y_VAL_PATH, mmap_mode="r", allow_pickle=False)

expected_val_indices = np.arange(9, len(y_val), dtype=np.int64)

checks["validation_shapes_and_class_dimension"] = (
    val_prob.shape == (len(y_val) - 9, 9)
    and val_indices.shape == (len(y_val) - 9,)
    and val_targets.shape == (len(y_val) - 9,)
)

checks["validation_indices_align_with_lstm_targets"] = (
    np.array_equal(val_indices, expected_val_indices)
    and np.array_equal(val_targets, np.asarray(y_val[val_indices]))
)

val_finite = bool(np.isfinite(val_prob).all())
checks["validation_probabilities_finite"] = val_finite

if val_finite:
    val_min = float(val_prob.min())
    val_max = float(val_prob.max())
    val_row_sums_ok = bool(
        np.allclose(
            np.asarray(val_prob.sum(axis=1), dtype=np.float64),
            1.0,
            rtol=0.0,
            atol=TOLERANCE,
        )
    )
else:
    val_min = val_max = None
    val_row_sums_ok = False

checks["validation_probabilities_within_bounds"] = (
    val_finite
    and val_min >= -TOLERANCE
    and val_max <= 1.0 + TOLERANCE
)
checks["validation_probability_rows_sum_to_one"] = val_row_sums_ok

del y_val

# ------------------------------------------------
# 6. FINAL RF MODEL AND CONTRACT CHECKS
# ------------------------------------------------

checks["final_rf_metadata_class_contract"] = (
    final_rf_metadata.get("class_count") == 9
    and final_rf_metadata.get("class_mapping") == EXPECTED_CLASS_MAPPING
    and final_rf_metadata.get("feature_count") == 32
)

checks["final_rf_training_partition_contract"] = (
    final_rf_metadata.get("training_partition") == "Training"
    and final_rf_metadata.get("validation_used_for_fitting") is False
)

# 5.16.6 recorded model hashes before and after inference.
current_model_hash = sha256_file(FINAL_RF_PATH)
checks["final_rf_model_hash_matches_inference_report"] = (
    current_model_hash == validation_report.get("model_sha256_before")
    and current_model_hash == validation_report.get("model_sha256_after")
)

checks["no_test_access_recorded"] = (
    generation_report.get("test_accessed") is False
    and validation_report.get("test_accessed") is False
)

# Capture hashes of protected existing artifacts for downstream audit.
protected_paths = [
    FINAL_RF_PATH,
    FINAL_RF_METADATA_PATH,
    RF_HANDOFF_PATH,
    N04_FEATURE_METADATA_PATH,
]
protected_hashes = {
    str(path): sha256_file(path)
    for path in protected_paths
}

# ------------------------------------------------
# 7. BUILD READINESS REPORT AND HANDOFF MANIFEST
# ------------------------------------------------

passed = all(bool(value) for value in checks.values())
timestamp = datetime.now(timezone.utc).isoformat()

readiness_report = {
    "report_id": "rf_ensemble_readiness_report_v1",
    "created_utc": timestamp,
    "status": (
        "READY_FOR_LSTM_OOF_INTEGRATION"
        if passed else "BLOCKED_REVIEW_REQUIRED"
    ),
    "approved_for_ensemble_handoff": bool(passed),
    "checks": checks,
    "passed_check_count": int(sum(bool(v) for v in checks.values())),
    "total_check_count": len(checks),
    "oof": {
        "probabilities_path": str(OOF_PROB_PATH),
        "observation_indices_path": str(OOF_INDEX_PATH),
        "targets_path": str(OOF_TARGET_PATH),
        "fold_ids_path": str(OOF_FOLD_PATH),
        "shape": list(oof_prob.shape),
        "class_order": CLASS_IDS,
        "eligible_observations": int(len(oof_indices)),
        "fold_counts": np.bincount(
            oof_fold_ids.astype(np.int64), minlength=5
        ).tolist(),
        "probability_min": oof_min,
        "probability_max": oof_max,
    },
    "validation": {
        "probabilities_path": str(VAL_PROB_PATH),
        "observation_indices_path": str(VAL_INDEX_PATH),
        "targets_path": str(VAL_TARGET_PATH),
        "shape": list(val_prob.shape),
        "class_order": CLASS_IDS,
        "eligible_observations": int(len(val_indices)),
        "probability_min": val_min,
        "probability_max": val_max,
    },
    "protected_artifact_sha256": protected_hashes,
    "validation_test_accessed": False,
    "models_fitted_in_this_subsection": False,
    "predictions_generated_in_this_subsection": False,
    "existing_final_rf_modified_in_this_subsection": False,
    "limitations": [
        "The fold plan is stratified over persisted row order; chronological and session-level independence are not established.",
        "The original RF Test evaluation already exists in N05; this subsection did not access Test arrays.",
        "RF readiness does not establish that the shared protocol is yet approved for LSTM; the LSTM notebook must validate compatibility with the same observation IDs and fold IDs.",
    ],
}

handoff_manifest = {
    "manifest_id": "rf_ensemble_handoff_manifest_v1",
    "created_utc": timestamp,
    "status": (
        "READY_FOR_LSTM_OOF_INTEGRATION"
        if passed else "BLOCKED_REVIEW_REQUIRED"
    ),
    "approved_for_ensemble_handoff": bool(passed),
    "model_strategy": "RF-3 — Controlled Random Oversampling",
    "class_order": CLASS_IDS,
    "class_mapping": EXPECTED_CLASS_MAPPING,
    "feature_count": 32,
    "fold_count": 5,
    "shared_fold_plan_candidate": str(PLAN_PATH),
    "fold_training_manifest": str(TRAIN_MANIFEST_PATH),
    "oof_generation_report": str(GENERATION_REPORT_PATH),
    "oof_validation_report": str(OOF_REPORT_PATH),
    "validation_inference_report": str(VAL_REPORT_PATH),
    "oof_artifacts": {
        "probabilities": str(OOF_PROB_PATH),
        "observation_indices": str(OOF_INDEX_PATH),
        "targets": str(OOF_TARGET_PATH),
        "fold_ids": str(OOF_FOLD_PATH),
        "shape": list(oof_prob.shape),
    },
    "validation_artifacts": {
        "probabilities": str(VAL_PROB_PATH),
        "observation_indices": str(VAL_INDEX_PATH),
        "targets": str(VAL_TARGET_PATH),
        "shape": list(val_prob.shape),
    },
    "original_final_rf": {
        "model_path": str(FINAL_RF_PATH),
        "metadata_path": str(FINAL_RF_METADATA_PATH),
        "original_handoff_path": str(RF_HANDOFF_PATH),
        "model_sha256_verified_against_5166_report": current_model_hash,
        "protected_artifact_sha256": protected_hashes,
    },
    "readiness_report": str(READINESS_OUTPUT_PATH),
    "validation_test_accessed": False,
    "model_fitted_in_handoff": False,
    "existing_final_rf_modified": False,
    "limitations": readiness_report["limitations"],
}

# Write reports even when blocked, so failures are auditable.
# Exclusive creation avoids silently replacing earlier artifacts.
with READINESS_OUTPUT_PATH.open("x", encoding="utf-8") as f:
    json.dump(readiness_report, f, indent=2)

with HANDOFF_OUTPUT_PATH.open("x", encoding="utf-8") as f:
    json.dump(handoff_manifest, f, indent=2)

# ------------------------------------------------
# 8. FINAL STATUS
# ------------------------------------------------

print("=" * 76)
print("5.16.7 — ENSEMBLE HANDOFF AND READINESS GATE")
print("=" * 76)

for name, passed_check in checks.items():
    print(f"[{'PASS' if passed_check else 'BLOCK'}] {name}")

print("-" * 76)
print("Status:", readiness_report["status"])
print(
    "Checks passed:",
    readiness_report["passed_check_count"],
    "/",
    readiness_report["total_check_count"],
)
print("Handoff manifest:", HANDOFF_OUTPUT_PATH)
print("Readiness report:", READINESS_OUTPUT_PATH)
print("Test arrays accessed: NO")
print("Models fitted: NO")
print("Existing final RF modified: NO")
print("Final RF model hash:", current_model_hash)

if not passed:
    raise RuntimeError(
        "5.16.7 is BLOCKED. Preserve both reports and review failed "
        "checks before starting LSTM OOF preparation."
    )

============================================================================
5.16.7 — ENSEMBLE HANDOFF AND READINESS GATE
============================================================================
[PASS] candidate_plan_identity
[PASS] five_fold_training_manifest_complete
[PASS] oof_generation_passed
[PASS] oof_coverage_and_provenance_passed
[PASS] validation_inference_passed
[PASS] oof_shapes_and_class_dimension
[PASS] oof_indices_exactly_cover_eligible_training_rows
[PASS] oof_targets_match_n04_training_labels
[PASS] oof_fold_ids_valid
[PASS] oof_probabilities_finite
[PASS] oof_probabilities_within_bounds
[PASS] oof_probability_rows_sum_to_one
[PASS] validation_shapes_and_class_dimension
[PASS] validation_indices_align_with_lstm_targets
[PASS] validation_probabilities_finite
[PASS] validation_probabilities_within_bounds
[PASS] validation_probability_rows_sum_to_one
[PASS] final_rf_metadata_class_contract
[PASS] final_rf_training_partition_contract
[PASS] final_rf_model_hash_matches_inference_report
[PASS] no_test_access_recorded
----------------------------------------------------------------------------
Status: READY_FOR_LSTM_OOF_INTEGRATION
Checks passed: 21 / 21
Handoff manifest: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/rf_ensemble_handoff_manifest.json
Readiness report: /content/drive/MyDrive/AI-Network-Intrusion-Detection-System/outputs/ensemble_model_development/rf_fold_models_v1/rf_ensemble_readiness_report.json
Test arrays accessed: NO
Models fitted: NO
Existing final RF modified: NO
Final RF model hash: 50bb5ec9eb3a02fc9bb265079ed5a0f2484646e87c4c009c659920bbe315a280